jena-geo: AvgYDistinct Class Reference
AvgYDistinct Class Reference
Public Member Functions
AvgYDistinct (Expr expr)
Aggregator copy (ExprList exprs)
boolean equals (Aggregator other, boolean bySyntax)
Accumulator createAccumulator ()
Node getValueEmpty ()
int hashCode ()
Static Private Attributes
static Logger log = LoggerFactory.getLogger("AVGY")
static final NodeValue noValuesToAvg = NodeValue.nvZERO
Constructor & Destructor Documentation
AvgYDistinct()
AvgYDistinct (Expr expr)
{
                 super(true,expr);
                 // TODO Auto-generated constructor stub
         }
Referenced by AvgYDistinct.copy(), and AvgYDistinct.equals().
Member Function Documentation
copy()
Aggregator copy (ExprList exprs)
Reimplemented from AvgY.
{
                 return new AvgYDistinct(exprs.get(0)) ;
         }
References AvgYDistinct.AvgYDistinct().
createAccumulator()
Accumulator createAccumulator () inherited
             {
                 return new AccAvgY(getExpr()) ;
             }
equals()
boolean equals (Aggregator other, boolean bySyntax)
Reimplemented from AvgY.
{
                 if ( other == null ) return false ;
         if ( this == other ) return true ;
         if ( ! ( other instanceof AvgYDistinct ) )
             return false ;
         AvgYDistinct agg = (AvgYDistinct)other ;
         return exprList.equals(agg.exprList, bySyntax) ;
         }
References AvgYDistinct.AvgYDistinct(), and AvgYDistinct.equals().
Referenced by AvgYDistinct.equals().
getValueEmpty()
Node getValueEmpty () inherited
 { return NodeValue.toNode(noValuesToAvg) ; }
References AvgY.noValuesToAvg.
hashCode()
int hashCode () inherited
 { return HC_AggAvg ^ getExprList().hashCode() ; }
Member Data Documentation
log
Logger log = LoggerFactory.getLogger("AVGY") static private inherited
Referenced by AvgY.AccAvgY.accumulate().
noValuesToAvg
final NodeValue noValuesToAvg = NodeValue.nvZERO static private inherited
Referenced by AvgY.AccAvgY.accumulate(), AvgY.AccAvgY.getAccValue(), and AvgY.getValueEmpty().