jena-geo: MaxY Class Reference
MaxY Class Reference
Classes
class AccMaxY
Public Member Functions
Aggregator copy (ExprList exprs)
boolean equals (Aggregator other, boolean bySyntax)
Accumulator createAccumulator ()
Node getValueEmpty ()
int hashCode ()
Protected Member Functions
MaxY (String name, boolean isDistinct, Expr expr)
MaxY (Expr expr)
Constructor & Destructor Documentation
MaxY() [1/2]
MaxY (String name, boolean isDistinct, Expr expr) protected
{
                 super("MAXY", true, expr);
                 // TODO Auto-generated constructor stub
         }
Referenced by MaxY.copy(), and MaxY.equals().
MaxY() [2/2]
MaxY (Expr expr) protected
{
                 super("MAXY", false, expr);
         }
Member Function Documentation
copy()
Aggregator copy (ExprList exprs)
Reimplemented in MaxYDistinct.
{
                 return new MaxY(exprs.get(0)) ;
         }
References MaxY.MaxY().
createAccumulator()
Accumulator createAccumulator ()
{
                 return new AccMaxY(getExpr());
         }
equals()
boolean equals (Aggregator other, boolean bySyntax)
Reimplemented in MaxYDistinct.
{
                 if ( other == null ) return false ;
         if ( this == other ) return true ;
         if ( ! ( other instanceof MaxY ) )
             return false ;
         MaxY agg = (MaxY)other ;
         return exprList.equals(agg.exprList, bySyntax) ;
         }
References MaxY.equals(), and MaxY.MaxY().
Referenced by MaxY.equals().
getValueEmpty()
Node getValueEmpty ()
{
                 return null;
         }
hashCode()
int hashCode ()
{
                 return getExpr().hashCode() ;
         }