jena-geo: JDBCConnection Class Reference
JDBCConnection Class Reference
Public Member Functions
JDBCConnection ()
Static Public Member Functions
static JDBCConnection getInstance ()
static void executeQuery (String query) throws SQLException
static void main (String[] args) throws SQLException
Static Public Attributes
static Connection jdbcConnection
static Integer resultSize =0
static JDBCConnection INSTANCE
Static Package Attributes
static java.sql.Connection conn
static ConnectionPool pool
Constructor & Destructor Documentation
JDBCConnection()
JDBCConnection ()
References JDBCConnection.conn.
Referenced by JDBCConnection.getInstance().
{
                 try {
                         this.pool=new ConnectionPool();
                     pool.setUrl("jdbc:postgresql://localhost:5432/geographica_raster");
                     pool.setUser("postgres");
                     pool.setPassword("postgres");
                     pool.setProtocolVersion(3);
                     conn = pool.getConnection();
                     /*
                     * Load the JDBC driver and establish a connection.
                     */
                     Class.forName("org.postgresql.Driver");
                     String url = "jdbc:postgresql://127.0.0.1:5432/postgres";
                     ConnectionPool pool = new ConnectionPool();
                     pool.setUrl("jdbc:postgresql://localhost:5432/geographica_raster");
                     pool.setUser("postgres");
                     pool.setPassword("postgres");
                     pool.setProtocolVersion(3);
                     Connection conn = pool.getConnection();
                     //conn = DriverManager.getConnection(url, "postgres", "postgres");
                     /*
                     * Add the geometry types to the connection. Note that you
                     * must cast the connection to the pgsql-specific connection
                     * implementation before calling the addDataType() method.
                     */
                     //((org.postgresql.PGConnection)conn).addDataType("geometry",(Class<? extends PGobject>) Class.forName("org.postgis.PGgeometry"));
                     //((org.postgresql.PGConnection)conn).addDataType("box3d",(Class<? extends PGobject>) Class.forName("org.postgis.PGbox3d"));
                     /*
                     * Create a statement and execute a select query.
                     */
                    /* Statement s = conn.createStatement();
                     ResultSet r = s.executeQuery("select wkb_geometry from geographica_vector");
                     while( r.next() ) {
                       /*
                       * Retrieve the geometry as an object then cast it to the geometry type.
                       * Print things out.
                       PGgeometry geom = (PGgeometry)r.getObject(1);
                       int id = r.getInt(1);
                       System.out.println("Row " + id + ":");
                       System.out.println(geom.toString());
                     }
                     s.close();
                     conn.close(); */
                   }
                 catch( Exception e ) {
                   e.printStackTrace();
                   }
                 }
Member Function Documentation
executeQuery()
static void executeQuery (String query) throws SQLException static
References JDBCConnection.conn.
Referenced by BenchmarkExecutor.benchmark(), and JDBCConnection.main().
{
                 System.out.println(query);
                 if(conn==null) {
                         conn=pool.getConnection();
                 }
                 Statement s = conn.createStatement();
             ResultSet r = s.executeQuery(query);
             resultSize=0;
             while (r.next()) {
                 resultSize++;
             }
             r.close();
             s.close();
             //conn.close();
         }
getInstance()
static JDBCConnection getInstance () static
References JDBCConnection.INSTANCE, and JDBCConnection.JDBCConnection().
Referenced by BenchmarkExecutor.benchmark(), and JDBCConnection.main().
{
                 if(INSTANCE==null) {
                         INSTANCE=new JDBCConnection();
                 }
                 return INSTANCE;
         }
main()
static void main (String [] args) throws SQLException static
References JDBCConnection.executeQuery(), JDBCConnection.getInstance(), and JDBCConnection.resultSize.
{
                 JDBCConnection.getInstance().executeQuery("select * from geographica_vector");
                 System.out.println(JDBCConnection.resultSize);
         }
Member Data Documentation
conn
java.sql.Connection conn static package
Referenced by JDBCConnection.executeQuery(), and JDBCConnection.JDBCConnection().
INSTANCE
JDBCConnection INSTANCE static
Referenced by JDBCConnection.getInstance().
jdbcConnection
Connection jdbcConnection static
pool
ConnectionPool pool static package
resultSize
Integer resultSize =0 static
Referenced by BenchmarkExecutor.benchmark(), and JDBCConnection.main().