jena-geo: MinZ.AccMinZ Class Reference
MinZ.AccMinZ Class Reference
Public Member Functions
AccMinZ (Expr expr)
void accumulate (NodeValue nv, Binding binding, FunctionEnv functionEnv)
NodeValue getAccValue ()
Protected Member Functions
void accumulateError (Binding binding, FunctionEnv functionEnv)
Static Package Attributes
static final boolean DEBUG = false
Private Attributes
NodeValue minSoFar = null
Constructor & Destructor Documentation
AccMinZ()
AccMinZ (Expr expr)
Referenced by MinZ.createAccumulator().
 { super(expr, false) ; }
Member Function Documentation
accumulate()
void accumulate (NodeValue nv, Binding binding, FunctionEnv functionEnv)
References GeometryWrapper.extract(), and GeometryWrapper.getParsingGeometry().
         {
                 GeometryWrapper geometry = GeometryWrapper.extract(nv);
             Geometry geo=geometry.getParsingGeometry();
             Double localminZ=0.;
             Double minZ=Double.MAX_VALUE;
             for(Coordinate coord:geo.getCoordinates()) {
                 if(minZ>coord.getY()) {
                         minZ=coord.getY();
                 }
             }
                 NodeValue localMin=NodeValue.makeDouble(localminZ);
             if ( minSoFar == null )
             {
                 minSoFar = localMin ;
                 if ( DEBUG ) System.out.println("min: init : "+localMin) ;
                 return ;
             }
             int x = NodeValue.compareAlways(minSoFar, localMin) ;
             if ( x > 0 )
                 minSoFar = localMin ;
             if ( DEBUG ) System.out.println("min: "+localMin+" ==> "+minSoFar) ;
         }
accumulateError()
void accumulateError (Binding binding, FunctionEnv functionEnv) protected
         {}
getAccValue()
NodeValue getAccValue ()
References MinZ.AccMinZ.minSoFar.
         { return minSoFar ; }
Member Data Documentation
DEBUG
final boolean DEBUG = false static package
minSoFar
NodeValue minSoFar = null private
Referenced by MinZ.AccMinZ.getAccValue().