jena-geo: MinimumBoundingRadius Class Reference
MinimumBoundingRadius Class Reference
Returns the center point and radius of the smallest circle that can fully contain a geometry.
Public Member Functions
NodeValue exec (NodeValue arg0)
Detailed Description
Returns the center point and radius of the smallest circle that can fully contain a geometry.
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0)
{
         Wrapper wrapper1=LiteralUtils.rasterOrVector(arg0);
         if(wrapper1 instanceof GeometryWrapper) {
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(arg0);
             Geometry geom = geometry.getXYGeometry();
             org.locationtech.jts.algorithm.MinimumBoundingCircle minCircle = new org.locationtech.jts.algorithm.MinimumBoundingCircle(geom);
                 return NodeValue.makeDouble(minCircle.getRadius());
             } catch (DatatypeFormatException ex) {
                 throw new ExprEvalException(ex.getMessage(), ex);
             }
     }else if(wrapper1 instanceof CoverageWrapper) {
                  CoverageWrapper covwrap = CoverageWrapper.extract(arg0);
        GridCoverage cov = covwrap.getXYGeometry();
        Geometry geom=LiteralUtils.toGeometry(cov.getGridGeometry().getEnvelope());
        org.locationtech.jts.algorithm.MinimumBoundingCircle minCircle = new org.locationtech.jts.algorithm.MinimumBoundingCircle(geom);
        return NodeValue.makeDouble(minCircle.getRadius());
         }else {
                 throw new ExprEvalException("No geometry or coverage literal");
         }
     }
References CoverageWrapper.extract(), GeometryWrapper.extract(), CoverageWrapper.getXYGeometry(), GeometryWrapper.getXYGeometry(), LiteralUtils.rasterOrVector(), and LiteralUtils.toGeometry().
Referenced by MinimumBoundingRadiusTest.testMinimumBoundingRadius().