jena-geo: MinY Class Reference
MinY Class Reference
Classes
class AccMinY
Public Member Functions
Aggregator copy (ExprList exprs)
boolean equals (Aggregator other, boolean bySyntax)
Accumulator createAccumulator ()
Node getValueEmpty ()
int hashCode ()
Protected Member Functions
MinY (String name, boolean isDistinct, Expr expr)
MinY (Expr expr)
Constructor & Destructor Documentation
MinY() [1/2]
MinY (String name, boolean isDistinct, Expr expr) protected
Referenced by MinY.copy(), and MinY.equals().
{
                 super("MINY", false, expr);
                 // TODO Auto-generated constructor stub
         }
MinY() [2/2]
MinY (Expr expr) protected
{
                 super("MINY", false, expr);
         }
Member Function Documentation
copy()
Aggregator copy (ExprList exprs)
References MinY.MinY().
{
                 return new MinY(exprs.get(0)) ;
         }
createAccumulator()
Accumulator createAccumulator ()
References MinY.AccMinY.AccMinY().
{
                 return new AccMinY(getExpr());
         }
equals()
boolean equals (Aggregator other, boolean bySyntax)
References MinY.MinY().
{
                 if ( other == null ) return false ;
         if ( this == other ) return true ;
         if ( ! ( other instanceof MinY ) )
             return false ;
         MinY agg = (MinY)other ;
         return exprList.equals(agg.exprList, bySyntax) ;
         }
getValueEmpty()
Node getValueEmpty ()
{
                 return null;
         }
hashCode()
int hashCode ()
{
                 return getExpr().hashCode() ;
         }