jena-geo: IsSquare Class Reference
IsSquare Class Reference
Public Member Functions
NodeValue exec (NodeValue v)
Member Function Documentation
exec()
NodeValue exec (NodeValue v)
{
                 Geometry geom=null;
                 Wrapper wrapper1=LiteralUtils.rasterOrVector(v);
         if(wrapper1 instanceof GeometryWrapper) {
                try {
                     GeometryWrapper geometry = GeometryWrapper.extract(v);
                     geom = geometry.getParsingGeometry();
                 } catch (DatatypeFormatException ex) {
                     throw new ExprEvalException(ex.getMessage(), ex);
                 }
         }else if(wrapper1 instanceof CoverageWrapper) {
                try {
                     CoverageWrapper geometry = CoverageWrapper.extract(v);
                     geom = LiteralUtils.toGeometry(geometry.getParsingGeometry().getGridGeometry().getEnvelope());
                 } catch (DatatypeFormatException ex) {
                     throw new ExprEvalException(ex.getMessage(), ex);
                 }
         }
         if(geom!=null && geom.isRectangle()) {
                 Double distance01=geom.getCoordinates()[0].distance(geom.getCoordinates()[1]);
                 Double distance12=geom.getCoordinates()[1].distance(geom.getCoordinates()[2]);
                 Double distance23=geom.getCoordinates()[2].distance(geom.getCoordinates()[3]);
                 Double distance34=geom.getCoordinates()[3].distance(geom.getCoordinates()[0]);
                 if(distance01==distance23 && distance12==distance34 && distance01==distance12
                                 && distance23==distance34)
                         return NodeValue.TRUE;
         }
         return NodeValue.FALSE;
         }
References CoverageWrapper.extract(), GeometryWrapper.extract(), CoverageWrapper.getParsingGeometry(), GeometryWrapper.getParsingGeometry(), LiteralUtils.rasterOrVector(), and LiteralUtils.toGeometry().