jena-geo: GeometryType Class Reference
GeometryType Class Reference
Returns the type of the geometry as a string.
Public Member Functions
NodeValue exec (NodeValue arg0)
Detailed Description
Returns the type of the geometry as a string.
Eg: 'LINESTRING', 'POLYGON', 'MULTIPOINT', etc.
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0)
References GeometryWrapper.getGeometryType(), and LiteralUtils.rasterOrVector().
Referenced by GeometryTypeTest.testLineString(), and GeometryTypeTest.testRaster().
{
         Wrapper wrapper1=LiteralUtils.rasterOrVector(arg0);
                 if(wrapper1 instanceof GeometryWrapper) {
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(arg0);
             String geometryType = geometry.getGeometryType();
             return NodeValue.makeString(geometryType);
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
                 }else if(wrapper1 instanceof CoverageWrapper) {
                         return NodeValue.makeString("Coverage");
                 }else {
                         return NodeValue.nvEmptyString;
                 }
     }