jena-geo: AsTWKB Class Reference
AsTWKB Class Reference
Returns the geometry as TWKB, aka "Tiny Well-Known Binary".
Public Member Functions
NodeValue exec (NodeValue v, NodeValue v1)
Detailed Description
Returns the geometry as TWKB, aka "Tiny Well-Known Binary".
Member Function Documentation
exec()
NodeValue exec (NodeValue v, NodeValue v1)
{
                 try {
             GeometryWrapper geometry = GeometryWrapper.extract(v);
             String endianness = v1.getString();
             TWKBWriter writer=new TWKBWriter();
             byte[] result=writer.write(geometry.getParsingGeometry());
             if(v1!=null) {
                 ByteBuffer bb = ByteBuffer.wrap(result);
                 if("XDR".equals(endianness)) {
                     bb.order( ByteOrder.BIG_ENDIAN);
                 }else if("NDR".equals(endianness)) {
                         bb.order( ByteOrder.LITTLE_ENDIAN);
                 }
                 return NodeValue.makeString(new String(bb.array(),"UTF-8"));
             }
             return NodeValue.makeString(new String(result,"UTF-8"));
         } catch (DatatypeFormatException | UnsupportedEncodingException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
         }
References GeometryWrapper.extract(), GeometryWrapper.getParsingGeometry(), and TWKBWriter.write().