jena-geo: Node Class Reference
Node Class Reference
Public Member Functions
NodeValue exec (NodeValue v)
Member Function Documentation
exec()
NodeValue exec (NodeValue v)
{
                 GeometryWrapper geom1 = GeometryWrapper.extract(v);
                  Noder noder = new MCIndexNoder(new IntersectionAdder(new RobustLineIntersector()));
                 noder.computeNodes(SegmentStringUtil.extractNodedSegmentStrings(geom1.getXYGeometry()));
                 GeometryFactory fac=new GeometryFactory();
                 return GeometryWrapperFactory.createGeometry(SegmentStringUtil.toGeometry(noder.getNodedSubstrings(), fac),geom1.getSrsURI(),geom1.getGeometryDatatypeURI()).asNodeValue();
         }
References GeometryWrapper.extract(), GeometryWrapper.getGeometryDatatypeURI(), GeometryWrapper.getSrsURI(), and GeometryWrapper.getXYGeometry().