jena-geo: FlipCoordinates Class Reference
FlipCoordinates Class Reference
Returns a version of the given geometry with X and Y axis flipped.
Public Member Functions
NodeValue exec (NodeValue arg0)
Detailed Description
Returns a version of the given geometry with X and Y axis flipped.
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0)
References LiteralUtils.createGeometry(), GeometryWrapper.extract(), GeometryWrapper.getGeometryType(), and GeometryWrapper.getParsingGeometry().
Referenced by FlipCoordinatesTest.testFlipCoordinates().
{
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(arg0);
             Geometry geom = geometry.getParsingGeometry();
             List<Coordinate> newcoords=new ArrayList<Coordinate>();
                 for(Coordinate coord:geom.getCoordinates()) {
                         if(coord instanceof CoordinateXYM) {
                                 newcoords.add(new CoordinateXYM(coord.getY(),coord.getX(),coord.getM()));
                         }else if(coord instanceof CoordinateXYZM) {
                                 newcoords.add(new CoordinateXYZM(coord.getY(),coord.getX(),coord.getZ(),coord.getM()));
                         }else {
                                 newcoords.add(new Coordinate(coord.getY(),coord.getX()));
                         }
                 }
                  return LiteralUtils.createGeometry(newcoords, geometry.getGeometryType(), geometry).asNodeValue();
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
     }