jena-geo: Distance3D Class Reference
Distance3D Class Reference
Public Member Functions
NodeValue exec (NodeValue arg0, NodeValue arg1)
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0, NodeValue arg1)
References GeometryWrapper.distance(), GeometryWrapper.extract(), GeometryWrapper.getSrsInfo(), GeometryWrapper.getXYGeometry(), and GeometryWrapper.transform().
{
         try {
             GeometryWrapper geom1 = GeometryWrapper.extract(arg0);
             GeometryWrapper geom2 = GeometryWrapper.extract(arg1);
             GeometryWrapper transGeom2 = geom2.transform(geom1.getSrsInfo());
             Distance3DOp op3d=new Distance3DOp(geom1.getXYGeometry(), transGeom2.getXYGeometry());
             double distance3d=op3d.distance();
             return NodeValue.makeDouble(distance3d);
         } catch (DatatypeFormatException | FactoryException | MismatchedDimensionException | TransformException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
         }