jena-geo: VoronoiPolygons Class Reference
VoronoiPolygons Class Reference
Public Member Functions
NodeValue exec (NodeValue v1, NodeValue toleranceV, NodeValue extendto)
Member Function Documentation
exec()
NodeValue exec (NodeValue v1, NodeValue toleranceV, NodeValue extendto)
References GeometryWrapper.asNodeValue(), GeometryWrapper.extract(), GeometryWrapper.getGeometryDatatypeURI(), GeometryWrapper.getSrsURI(), and GeometryWrapper.getXYGeometry().
{
         try {
             GeometryWrapper geom1 = GeometryWrapper.extract(v1);
             Double tolerance=toleranceV.getDouble();
                 VoronoiDiagramBuilder builder=new VoronoiDiagramBuilder();
                 builder.setTolerance(tolerance);
                 builder.setSites(geom1.getXYGeometry());
                 Geometry test = builder.getDiagram(new GeometryFactory());
             GeometryWrapper pointWrapper = GeometryWrapperFactory.createGeometry(test, geom1.getSrsURI(), geom1.getGeometryDatatypeURI());
             return pointWrapper.asNodeValue();
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
         }