jena-geo: SpatialClusteringComponent Class Reference
SpatialClusteringComponent Class Reference
Public Member Functions
String getDescription ()
String getSource ()
String getVersion ()
void init (PluginInfo info)
void prepare (ResponseBuilder rb) throws IOException
void process (ResponseBuilder responseBuilder) throws IOException
Private Member Functions
NamedList< Object > createClusterResult (DblClusters< Document > clusters)
DblClusters< Document > createDocumentClusters (ResponseBuilder rb, int maxCount, Set< String > fields) throws IOException
Set< String > createFieldList ()
String getFieldString (DblResult< Document > dblResult, String name)
String getStringArgument (NamedList<?> values, String fieldName)
Object getType (int count)
boolean isNumeric (String s)
Private Attributes
String fieldNameId
String fieldNameLon
String fieldNameLat
Static Private Attributes
static final String FIELD_NAME_ID = "fieldId"
static final String FIELD_NAME_LON = "fieldLon"
static final String FIELD_NAME_LAT = "fieldLat"
static final String PARAM_SPATIALCLUSTERING = "spatial-clustering"
static final String PARAM_SPATIALCLUSTERING_SIZE = "spatial-clustering.size"
static final int DEFAULT_CLUSTER_SIZE = 10
static final String PIN_TYPE_SINGLE = "single"
static final String PIN_TYPE_CLUSTER = "cluster"
Member Function Documentation
createClusterResult()
NamedList<Object> createClusterResult (DblClusters< Document > clusters) private
References SpatialClusteringComponent.getFieldString(), and SpatialClusteringComponent.getType().
Referenced by SpatialClusteringComponent.process().
{
         NamedList<Object> spatialClusteringRoot = new NamedList<>();
         for (DblResult<Document> cluster : clusters.results()) {
             NamedList<Object> clusterNode = new NamedList<>();
             clusterNode.add("type", this.getType(cluster.getCount()));
             clusterNode.add("size", cluster.getCount());
             clusterNode.add("longitude", cluster.getCoords()[0]);
             clusterNode.add("latitude", cluster.getCoords()[1]);
             if (cluster.getCount() == 1) {
                 clusterNode.add("reference", this.getFieldString(cluster, this.fieldNameId));
             }
             spatialClusteringRoot.add("pin", clusterNode);
         }
         return spatialClusteringRoot;
     }
createDocumentClusters()
DblClusters<Document> createDocumentClusters (ResponseBuilder rb, int maxCount, Set< String > fields) throws IOException private
References SpatialClusteringComponent.isNumeric().
Referenced by SpatialClusteringComponent.process().
{
         DblClusters<Document> clusters = new DblClusters<>(2, maxCount);
         DocSet docSet = rb.getResults().docSet;
         DocIterator iterator = docSet.iterator();
         while (iterator.hasNext()) {
             Integer docId = iterator.next();
             Document doc = rb.req.getSearcher().doc(docId, fields);
             IndexableField latitudeField = doc.getField(this.fieldNameLat);
             IndexableField longitudeField = doc.getField(this.fieldNameLon);
             if (latitudeField == null || longitudeField == null) {
                 continue;
             }
             String latitudeString = latitudeField.stringValue();
             String longitudeString = longitudeField.stringValue();
             if (!this.isNumeric(latitudeString) || !this.isNumeric(longitudeString)) {
                 continue;
             }
             clusters.add(1, new double[] {Double.valueOf(latitudeString), Double.valueOf(longitudeString)}, doc);
         }
         return clusters;
     }
createFieldList()
Set<String> createFieldList () private
Referenced by SpatialClusteringComponent.process().
{
         Set<String> fields = new HashSet<>();
         fields.add(this.fieldNameId);
         fields.add(this.fieldNameLon);
         fields.add(this.fieldNameLat);
         return fields;
     }
getDescription()
String getDescription ()
{
         return "indoqa-spatial-clustering";
     }
getFieldString()
String getFieldString (DblResult< Document > dblResult, String name) private
Referenced by SpatialClusteringComponent.createClusterResult().
{
         IndexableField fieldable = dblResult.getKey().getField(name);
         if (fieldable == null) {
             return null;
         }
         return fieldable.stringValue();
     }
getSource()
String getSource ()
{
         return "indoqa-spatial-clustering";
     }
getStringArgument()
String getStringArgument (NamedList<?> values, String fieldName) private
Referenced by SpatialClusteringComponent.init().
{
         Object value = values.get(fieldName);
         if (value == null) {
             throw new IllegalStateException("No value for parameter '" + fieldName + "' specified in solrconfig.xml!");
         }
         String result = String.valueOf(value);
         if (result.trim().length() == 0) {
             throw new IllegalStateException("Value for parameter '" + fieldName + "' specified in solrconfig.xml was empty!");
         }
         return result;
     }
getType()
Object getType (int count) private
References SpatialClusteringComponent.PIN_TYPE_CLUSTER, and SpatialClusteringComponent.PIN_TYPE_SINGLE.
Referenced by SpatialClusteringComponent.createClusterResult().
{
         if (count == 1) {
             return PIN_TYPE_SINGLE;
         }
         return PIN_TYPE_CLUSTER;
     }
getVersion()
String getVersion ()
{
         return "1";
     }
init()
void init (PluginInfo info)
References SpatialClusteringComponent.getStringArgument().
{
         this.fieldNameId = this.getStringArgument(info.initArgs, FIELD_NAME_ID);
         this.fieldNameLon = this.getStringArgument(info.initArgs, FIELD_NAME_LON);
         this.fieldNameLat = this.getStringArgument(info.initArgs, FIELD_NAME_LAT);
     }
isNumeric()
boolean isNumeric (String s) private
Referenced by SpatialClusteringComponent.createDocumentClusters().
{
         return s != null && Pattern.matches("-?\\d+(\\.\\d+)?", s);
     }
prepare()
void prepare (ResponseBuilder rb) throws IOException
{
         if (rb.req.getParams().getBool(PARAM_SPATIALCLUSTERING, false)) {
             rb.setNeedDocSet(true);
         }
     }
process()
void process (ResponseBuilder responseBuilder) throws IOException
References SpatialClusteringComponent.createClusterResult(), SpatialClusteringComponent.createDocumentClusters(), and SpatialClusteringComponent.createFieldList().
{
         if (!responseBuilder.req.getParams().getBool(PARAM_SPATIALCLUSTERING, false)) {
             return;
         }
         int maxCount = responseBuilder.req.getParams().getInt(PARAM_SPATIALCLUSTERING_SIZE, DEFAULT_CLUSTER_SIZE);
         Set<String> fields = this.createFieldList();
         DblClusters<Document> clusters = this.createDocumentClusters(responseBuilder, maxCount, fields);
         NamedList<Object> spatialClusteringRoot = this.createClusterResult(clusters);
         responseBuilder.rsp.add("spatial-clustering", spatialClusteringRoot);
     }
Member Data Documentation
DEFAULT_CLUSTER_SIZE
final int DEFAULT_CLUSTER_SIZE = 10 static private
FIELD_NAME_ID
final String FIELD_NAME_ID = "fieldId" static private
FIELD_NAME_LAT
final String FIELD_NAME_LAT = "fieldLat" static private
FIELD_NAME_LON
final String FIELD_NAME_LON = "fieldLon" static private
fieldNameId
String fieldNameId private
fieldNameLat
String fieldNameLat private
fieldNameLon
String fieldNameLon private
PARAM_SPATIALCLUSTERING
final String PARAM_SPATIALCLUSTERING = "spatial-clustering" static private
PARAM_SPATIALCLUSTERING_SIZE
final String PARAM_SPATIALCLUSTERING_SIZE = "spatial-clustering.size" static private
PIN_TYPE_CLUSTER
final String PIN_TYPE_CLUSTER = "cluster" static private
Referenced by SpatialClusteringComponent.getType().
PIN_TYPE_SINGLE
final String PIN_TYPE_SINGLE = "single" static private
Referenced by SpatialClusteringComponent.getType().