jena-geo: GeobufEncoder.GeobufFeatureSerializer Class Reference
GeobufEncoder.GeobufFeatureSerializer Class Reference
Public Member Functions
GeobufFeatureSerializer (int precision)
void serialize (DataOutput dataOutput, GeobufFeature geobufFeature) throws IOException
GeobufFeature deserialize (DataInput dataInput, int i) throws IOException
Public Attributes
final int precision
Private Member Functions
GeobufEncoder getEncoder ()
get the geobuf encoder, lazy initializing if needed.
Private Attributes
transient GeobufEncoder encoder
Constructor & Destructor Documentation
GeobufFeatureSerializer()
GeobufFeatureSerializer (int precision)
References GeobufEncoder.GeobufFeatureSerializer.precision.
{
             this.precision = precision;
         }
Member Function Documentation
deserialize()
GeobufFeature deserialize (DataInput dataInput, int i) throws IOException
References Geobuf.Data.parseFrom().
{
             int len = dataInput.readInt();
             byte[] feat = new byte[len];
             dataInput.readFully(feat);
             Geobuf.Data data = Geobuf.Data.parseFrom(feat);
             return new GeobufFeature(data.getFeatureCollection().getFeatures(0), data.getKeysList(), Math.pow(10, data.getPrecision()));
         }
getEncoder()
GeobufEncoder getEncoder () private
get the geobuf encoder, lazy initializing if needed.
JVM should inline this function
References GeobufEncoder.GeobufFeatureSerializer.encoder, and GeobufEncoder.GeobufEncoder().
Referenced by GeobufEncoder.GeobufFeatureSerializer.serialize().
{
             if (encoder == null) {
                 synchronized (this) {
                     if (encoder == null) {
                         encoder = new GeobufEncoder(new ByteArrayOutputStream(), precision);
                     }
                 }
             }
             return encoder;
         }
serialize()
void serialize (DataOutput dataOutput, GeobufFeature geobufFeature) throws IOException
References GeobufEncoder.GeobufFeatureSerializer.getEncoder(), and GeobufEncoder.makeFeatureCollection().
{
             GeobufEncoder enc = getEncoder();
             // This could be more efficient, we're wrapping a single feature in a feature collection. But that way the key/value
             // serialization all works.
             Geobuf.Data feat = enc.makeFeatureCollection(Arrays.asList(geobufFeature));
             byte[] data = feat.toByteArray();
             dataOutput.writeInt(data.length);
             dataOutput.write(data);
         }
Member Data Documentation
encoder
transient GeobufEncoder encoder private
Referenced by GeobufEncoder.GeobufFeatureSerializer.getEncoder().
precision
final int precision
Referenced by GeobufEncoder.GeobufFeatureSerializer.GeobufFeatureSerializer().