jena-geo: MaxXDistinct Class Reference
MaxXDistinct Class Reference
Public Member Functions
Aggregator copy (ExprList exprs)
boolean equals (Aggregator other, boolean bySyntax)
Accumulator createAccumulator ()
Node getValueEmpty ()
int hashCode ()
Protected Member Functions
MaxXDistinct (Expr expr)
Constructor & Destructor Documentation
MaxXDistinct()
MaxXDistinct (Expr expr) protected
Referenced by MaxXDistinct.copy(), and MaxXDistinct.equals().
{
                 super("MAXX", true, expr);
                 // TODO Auto-generated constructor stub
         }
Member Function Documentation
copy()
Aggregator copy (ExprList exprs)
References MaxXDistinct.MaxXDistinct().
{
                 return new MaxXDistinct(exprs.get(0)) ;
         }
createAccumulator()
Accumulator createAccumulator () inherited
{
                 return new AccMaxX(getExpr());
         }
equals()
boolean equals (Aggregator other, boolean bySyntax)
References MaxXDistinct.MaxXDistinct().
{
                 if ( other == null ) return false ;
         if ( this == other ) return true ;
         if ( ! ( other instanceof MaxXDistinct ) )
             return false ;
         MaxXDistinct agg = (MaxXDistinct)other ;
         return exprList.equals(agg.exprList, bySyntax) ;
         }
getValueEmpty()
Node getValueEmpty () inherited
{
                 return null;
         }
hashCode()
int hashCode () inherited
{
                 return getExpr().hashCode() ;
         }