jena-geo: Scale Class Reference
Scale Class Reference
Public Member Functions
NodeValue exec (List< NodeValue > args)
void checkBuild (String uri, ExprList args)
Member Function Documentation
checkBuild()
void checkBuild (String uri, ExprList args)
{
                 // TODO Auto-generated method stub
         }
exec()
NodeValue exec (List< NodeValue > args)
References GeometryWrapper.extract(), GeometryWrapper.getGeometryDatatypeURI(), GeometryWrapper.getSrsURI(), and GeometryWrapper.getXYGeometry().
{
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(args.get(0));
             Geometry geom = geometry.getXYGeometry();
             Geometry originPoint=null;
             Double xFactor = 1.;
             Double yFactor = 1.;
             Double zFactor=1.;
             if(args.size()<2) {
                  return GeometryWrapperFactory.createGeometry(geom, geometry.getSrsURI(), geometry.getGeometryDatatypeURI()).asNodeValue();
             }else if(args.size()>=2) {
                 if(args.size()>=2 && args.get(1).isDouble()) {
                         xFactor=args.get(1).getDouble();
                 }else  {
                     GeometryWrapper matchPoint = GeometryWrapper.extract(args.get(1));
                     Geometry mPoint = matchPoint.getXYGeometry();
                     xFactor=mPoint.getCoordinate().x;
                     yFactor=mPoint.getCoordinate().y;
                     zFactor=mPoint.getCoordinate().z!=Double.NaN?mPoint.getCoordinate().z:1.;
                 }
                 if(args.size()>=3 && args.get(2).isDouble()) {
                         yFactor=args.get(2).getDouble();
                 }else {
                         GeometryWrapper oriPoint = GeometryWrapper.extract(args.get(1));
                     originPoint = oriPoint.getXYGeometry();
                 }
                 if(args.size()>=4 && args.get(3).isDouble()) {
                         zFactor=args.get(3).getDouble();
                 }
             }
             AffineTransformation trans=new AffineTransformation();
             if(originPoint==null) {
                 trans.scale(xFactor, yFactor);
             }else {
                 trans.translate(-originPoint.getCoordinate().x, -originPoint.getCoordinate().y);
                 trans.scale(xFactor, yFactor);
                 trans.translate(originPoint.getCoordinate().x, originPoint.getCoordinate().y);
             }
             return GeometryWrapperFactory.createGeometry(trans.transform(geom), geometry.getSrsURI(), geometry.getGeometryDatatypeURI()).asNodeValue();
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
         }