jena-geo: Segmentize Class Reference
Segmentize Class Reference
Public Member Functions
NodeValue exec (NodeValue arg0, NodeValue arg1)
List< LineString > createSegments (GeometryWrapper geometry, double segmentLength) throws NoSuchAuthorityCodeException, FactoryException
Member Function Documentation
createSegments()
List<LineString> createSegments (GeometryWrapper geometry, double segmentLength) throws NoSuchAuthorityCodeException, FactoryException
{
         GeometryFactory geometryFactory = new GeometryFactory(new PrecisionModel(PrecisionModel.FLOATING));
         Geometry track = geometry.getXYGeometry();
         SRSInfo srsInfo = geometry.getSrsInfo();
         List<Coordinate> coordinates = new ArrayList<>(track.getCoordinates().length);
         Collections.addAll(coordinates, track.getCoordinates());
         double accumulatedLength = 0;
         List<Coordinate> lastSegment = new ArrayList<>();
         List<LineString> segments = new ArrayList<>();
         Iterator<Coordinate> itCoordinates = coordinates.iterator();
         for (int i = 0; itCoordinates.hasNext() && i < coordinates.size() - 1; i++) {
             Coordinate c1 = coordinates.get(i);
             Coordinate c2 = coordinates.get(i + 1);
             lastSegment.add(c1);
             double length;
             //Check for geographic or planar distance.
             //Does the rest of the calculation take into consideration geographic is non-linear in X/Y relationship?
             if (srsInfo.isGeographic()) {
                 length = GreatCircleDistance.haversineFormula(c1, c2);
             } else {
                 length = c1.distance(c2);
             }
             if (length + accumulatedLength >= segmentLength) {
                 double offsetLength = segmentLength - accumulatedLength;
                 double ratio = offsetLength / length;
                 double dx = c2.x - c1.x;
                 double dy = c2.y - c1.y;
                 Coordinate segmentationPoint = new Coordinate(c1.x + (dx * ratio), c1.y + (dy * ratio));
                 lastSegment.add(segmentationPoint); // Last point of the segment is the segmentation point
                 segments.add(geometryFactory.createLineString(lastSegment.toArray(new Coordinate[lastSegment.size()])));
                 lastSegment = new ArrayList<>(); // Resets the variable since a new segment will be built
                 accumulatedLength = 0D;
                 coordinates.add(i + 1, segmentationPoint);
             } else {
                 accumulatedLength += length;
             }
         }
         lastSegment.add(coordinates.get(coordinates.size() - 1)); // Because the last one is never added in the loop above
         segments.add(geometryFactory.createLineString(lastSegment.toArray(new Coordinate[lastSegment.size()])));
         return segments;
     }
Referenced by Segmentize.exec().
exec()
NodeValue exec (NodeValue arg0, NodeValue arg1)
{
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(arg0);
             double segmentLength = arg1.getDouble();
             List<LineString> linestrings = createSegments(geometry, segmentLength);
             return GeometryWrapperFactory.createMultiLineString(linestrings, geometry.getSrsURI(),geometry.getGeometryDatatypeURI()).asNodeValue();
         } catch (DatatypeFormatException | FactoryException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
     }
References Segmentize.createSegments(), GeometryWrapper.extract(), GeometryWrapper.getGeometryDatatypeURI(), and GeometryWrapper.getSrsURI().