jena-geo: Angle Class Reference
Angle Class Reference
Public Member Functions
NodeValue exec (NodeValue v1, NodeValue v2, NodeValue v3)
double findAngle (Coordinate a, Coordinate b, Coordinate c)
Member Function Documentation
exec()
NodeValue exec (NodeValue v1, NodeValue v2, NodeValue v3)
References GeometryWrapper.extract(), Angle.findAngle(), and GeometryWrapper.getXYGeometry().
Referenced by AngleTest.testAngle().
{
             GeometryWrapper pointgeometry = GeometryWrapper.extract(v1);
             Geometry geom = pointgeometry.getXYGeometry();
             GeometryWrapper pointgeometry2 = GeometryWrapper.extract(v2);
             Geometry geom2 = pointgeometry2.getXYGeometry();
             GeometryWrapper pointgeometry3 = GeometryWrapper.extract(v3);
             Geometry geom3 = pointgeometry3.getXYGeometry();
                 Coordinate coord1,coord2,coord3;
                 if("Point".equals(geom.getGeometryType())) {
                         coord1=geom.getCoordinate();
                 }else {
                         coord1=geom.getCentroid().getCoordinate();
                 }
                 if("Point".equals(geom2.getGeometryType())) {
                         coord2=geom2.getCoordinate();
                 }else {
                         coord2=geom2.getCentroid().getCoordinate();
                 }
                 if("Point".equals(geom3.getGeometryType())) {
                         coord3=geom3.getCoordinate();
                 }else {
                         coord3=geom3.getCentroid().getCoordinate();
                 }
                 return NodeValue.makeDouble(findAngle(coord1,coord2,coord3));
         }
findAngle()
double findAngle (Coordinate a, Coordinate b, Coordinate c)
Referenced by Angle.exec().
{
             double AB = Math.sqrt(Math.pow(b.x-a.x,2)+ Math.pow(b.y-a.y,2));
             double BC = Math.sqrt(Math.pow(b.x-c.x,2)+ Math.pow(b.y-c.y,2));
             double AC = Math.sqrt(Math.pow(c.x-a.x,2)+ Math.pow(c.y-a.y,2));
             return Math.acos((BC*BC+AB*AB-AC*AC)/(2*BC*AB));
         }