jena-geo: Azimuth Class Reference
Azimuth Class Reference
Returns the north-based azimuth as the angle in radians measured clockwise from the vertical on pointA to pointB.
Public Member Functions
NodeValue exec (NodeValue arg0, NodeValue argeom1)
Detailed Description
Returns the north-based azimuth as the angle in radians measured clockwise from the vertical on pointA to pointB.
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0, NodeValue argeom1)
References GeometryWrapper.extract(), GeometryWrapper.getSrsInfo(), GeometryWrapper.getXYGeometry(), and GeometryWrapper.transform().
Referenced by AzimuthTest.testAzimuth1(), and AzimuthTest.testAzimuth2().
{
             GeometryWrapper geometry1 = GeometryWrapper.extract(arg0);
             GeometryWrapper geometry2 = GeometryWrapper.extract(argeom1);
             GeometryWrapper transGeometry2;
                         try {
                                 transGeometry2 = geometry2.transform(geometry1.getSrsInfo());
                     Geometry geom1 = geometry1.getXYGeometry();
                     Geometry geom2 = transGeometry2.getXYGeometry();
                     if (geom1 instanceof Point && geom2 instanceof Point) {
                         return NodeValue.makeDouble(io.github.galbiston.geosparql_jena.implementation.great_circle.Azimuth.find(geom1.getCoordinate(), geom2.getCoordinate()));
                     }else {
                         return NodeValue.makeDouble(io.github.galbiston.geosparql_jena.implementation.great_circle.Azimuth.find(geom1.getCentroid().getCoordinate(), geom2.getCentroid().getCoordinate()));
                     }
                         } catch (MismatchedDimensionException | TransformException | FactoryException e) {
                                 // TODO Auto-generated catch block
                                 e.printStackTrace();
                                 return NodeValue.makeDouble(-1);
                         }
     }