jena-geo: AvgY Class Reference
AvgY Class Reference
Classes
class AccAvgY
Public Member Functions
AvgY (Expr expr)
Aggregator copy (ExprList expr)
Accumulator createAccumulator ()
Node getValueEmpty ()
int hashCode ()
boolean equals (Aggregator other, boolean bySyntax)
Protected Member Functions
AvgY (boolean isDistinct, Expr expr)
Static Private Attributes
static Logger log = LoggerFactory.getLogger("AVGY")
static final NodeValue noValuesToAvg = NodeValue.nvZERO
Constructor & Destructor Documentation
AvgY() [1/2]
AvgY (boolean isDistinct, Expr expr) protected
Referenced by AvgY.copy(), and AvgY.equals().
{
                 super("AVGY", false, expr);
                 // TODO Auto-generated constructor stub
         }
AvgY() [2/2]
AvgY (Expr expr)
 { super("AVGY", false, expr) ; }
Member Function Documentation
copy()
Aggregator copy (ExprList expr)
References AvgY.AvgY().
 { return new AvgY(expr.get(0)) ; }
createAccumulator()
Accumulator createAccumulator ()
             {
                 return new AccAvgY(getExpr()) ;
             }
equals()
boolean equals (Aggregator other, boolean bySyntax)
References AvgY.AvgY().
{
                 if ( other == null ) return false ;
                 if ( this == other ) return true ;
                 if ( ! ( other instanceof AvgY ) ) return false ;
                 AvgY a = (AvgY)other ;
                 return exprList.equals(a.exprList, bySyntax) ;
             }
getValueEmpty()
Node getValueEmpty ()
 { return NodeValue.toNode(noValuesToAvg) ; }
hashCode()
int hashCode ()
 { return HC_AggAvg ^ getExprList().hashCode() ; }
Member Data Documentation
log
Logger log = LoggerFactory.getLogger("AVGY") static private
noValuesToAvg
final NodeValue noValuesToAvg = NodeValue.nvZERO static private
Referenced by AvgY.AccAvgY.getAccValue().