jena-geo: MinX Class Reference
MinX Class Reference
Classes
class AccMinX
Public Member Functions
Aggregator copy (ExprList exprs)
boolean equals (Aggregator other, boolean bySyntax)
Accumulator createAccumulator ()
Node getValueEmpty ()
int hashCode ()
Protected Member Functions
MinX (String name, boolean isDistinct, Expr expr)
MinX (Expr expr)
Constructor & Destructor Documentation
MinX() [1/2]
MinX (String name, boolean isDistinct, Expr expr) protected
Referenced by MinX.copy(), and MinX.equals().
{
                 super("MINX", false, expr);
                 // TODO Auto-generated constructor stub
         }
MinX() [2/2]
MinX (Expr expr) protected
{
                 super("MINX", true, expr);
                 // TODO Auto-generated constructor stub
         }
Member Function Documentation
copy()
Aggregator copy (ExprList exprs)
References MinX.MinX().
{
                 return new MinX(exprs.get(0)) ;
         }
createAccumulator()
Accumulator createAccumulator ()
References MinX.AccMinX.AccMinX().
{
                 return new AccMinX(getExpr());
         }
equals()
boolean equals (Aggregator other, boolean bySyntax)
References MinX.MinX().
{
                 if ( other == null ) return false ;
         if ( this == other ) return true ;
         if ( ! ( other instanceof MinX ) )
             return false ;
         MinX agg = (MinX)other ;
         return exprList.equals(agg.exprList, bySyntax) ;
         }
getValueEmpty()
Node getValueEmpty ()
{
                 return null;
         }
hashCode()
int hashCode ()
{
                 return getExpr().hashCode() ;
         }