jena-geo: MaxZ Class Reference
MaxZ Class Reference
Classes
class AccMaxZ
Public Member Functions
Aggregator copy (ExprList exprs)
boolean equals (Aggregator other, boolean bySyntax)
Accumulator createAccumulator ()
Node getValueEmpty ()
int hashCode ()
Protected Member Functions
MaxZ (String name, boolean isDistinct, Expr expr)
MaxZ (Expr expr)
Constructor & Destructor Documentation
MaxZ() [1/2]
MaxZ (String name, boolean isDistinct, Expr expr) protected
Referenced by MaxZ.copy(), and MaxZ.equals().
{
                 super("MAXZ", true, expr);
                 // TODO Auto-generated constructor stub
         }
MaxZ() [2/2]
MaxZ (Expr expr) protected
{
                 super("MAXZ", false, expr);
         }
Member Function Documentation
copy()
Aggregator copy (ExprList exprs)
References MaxZ.MaxZ().
{
                 return new MaxZ(exprs.get(0)) ;
         }
createAccumulator()
Accumulator createAccumulator ()
{
                 return new AccMaxZ(getExpr());
         }
equals()
boolean equals (Aggregator other, boolean bySyntax)
References MaxZ.MaxZ().
{
                 if ( other == null ) return false ;
         if ( this == other ) return true ;
         if ( ! ( other instanceof MaxZ ) )
             return false ;
         MaxZ agg = (MaxZ)other ;
         return exprList.equals(agg.exprList, bySyntax) ;
         }
getValueEmpty()
Node getValueEmpty ()
{
                 return null;
         }
hashCode()
int hashCode ()
{
                 return getExpr().hashCode() ;
         }