jena-geo: GeobufEncoder Class Reference
GeobufEncoder Class Reference
Encode features to GeoBuf.
Classes
class GeobufFeatureSerializer
Public Member Functions
GeobufEncoder (OutputStream outputStream, int precision)
void writeFeatureCollection (Collection< GeobufFeature > featureCollection) throws IOException
Geobuf.Data makeFeatureCollection (Collection< GeobufFeature > featureCollection)
Geobuf.Data.Geometry geomToGeobuf (Geometry geometry)
Geobuf.Data.Geometry pointToGeobuf (Point point)
Geobuf.Data.Geometry multiPolyToGeobuf (MultiPolygon poly)
Geobuf.Data.Geometry polyToGeobuf (Polygon poly)
void close () throws IOException
Public Attributes
final int precision
final long precisionMultiplier
What to multiply floating point values by to get desired precision.
Private Member Functions
Geobuf.Data.Feature makeFeature (GeobufFeature feature, List< String > keys)
void addRing (LineString r, Geobuf.Data.Geometry.Builder builder)
Add a ring to a builder.
Private Attributes
OutputStream outputStream
Static Private Attributes
static final Logger LOG = LoggerFactory.getLogger(GeobufEncoder.class)
Detailed Description
Encode features to GeoBuf.
Constructor & Destructor Documentation
GeobufEncoder()
GeobufEncoder (OutputStream outputStream, int precision)
References GeobufEncoder.outputStream, and GeobufEncoder.precision.
Referenced by GeobufEncoder.GeobufFeatureSerializer.getEncoder().
{
         this.outputStream = outputStream;
         this.precision = precision;
         this.precisionMultiplier = (long) Math.pow(10, precision);
     }
Member Function Documentation
addRing()
void addRing (LineString r, Geobuf.Data.Geometry.Builder builder) private
Add a ring to a builder.
References Coordinate.x, and Coordinate.y.
Referenced by GeobufEncoder.multiPolyToGeobuf(), and GeobufEncoder.polyToGeobuf().
{
         // skip last point, same as first
         builder.addLengths(r.getNumPoints() - 1);
         long x, y, prevX = 0, prevY = 0;
         // last point is same as first, skip
         for (int i = 0; i < r.getNumPoints() - 1; i++) {
             // delta code
             Coordinate coord = r.getCoordinateN(i);
             // note that roundoff errors do not accumulate
             x = (long) (coord.x * precisionMultiplier);
             y = (long) (coord.y * precisionMultiplier);
             builder.addCoords(x - prevX);
             builder.addCoords(y - prevY);
             prevX = x;
             prevY = y;
         }
     }
close()
void close () throws IOException
{
         outputStream.close();
     }
geomToGeobuf()
Geobuf.Data.Geometry geomToGeobuf (Geometry geometry)
References GeobufEncoder.multiPolyToGeobuf(), GeobufEncoder.pointToGeobuf(), and GeobufEncoder.polyToGeobuf().
Referenced by GeobufEncoder.makeFeature().
{
         if (geometry instanceof Point)
             return pointToGeobuf((Point) geometry);
         else if (geometry instanceof Polygon)
             return polyToGeobuf((Polygon) geometry);
         else if (geometry instanceof MultiPolygon)
             return multiPolyToGeobuf((MultiPolygon) geometry);
         else
             throw new UnsupportedOperationException("Unsupported geometry type " + geometry.getGeometryType());
     }
makeFeature()
Geobuf.Data.Feature makeFeature (GeobufFeature feature, List< String > keys) private
References GeobufFeature.geometry, GeobufEncoder.geomToGeobuf(), GeobufFeature.id, Geobuf.Data.Feature.newBuilder(), Geobuf.Data.Value.newBuilder(), GeobufFeature.numericId, GeobufFeature.properties, and Geobuf.Data.Feature.Builder.setGeometry().
Referenced by GeobufEncoder.makeFeatureCollection().
{
         Geobuf.Data.Feature.Builder feat = Geobuf.Data.Feature.newBuilder()
                 .setGeometry(geomToGeobuf(feature.geometry));
         for (Map.Entry<String, Object> e : feature.properties.entrySet()) {
             // TODO store keys separately from features
             Geobuf.Data.Value.Builder val = Geobuf.Data.Value.newBuilder();
             Object featVal = e.getValue();
             if (featVal instanceof String)
                 val.setStringValue((String) featVal);
             else if (featVal instanceof Boolean)
                 val.setBoolValue((Boolean) featVal);
             else if (featVal instanceof Integer) {
                 int keyInt = (Integer) featVal;
                 if (keyInt >= 0)
                     val.setPosIntValue(keyInt);
                 else
                     val.setNegIntValue(keyInt);
             }
             else if (featVal instanceof Long) {
                 long keyLong = (Long) featVal;
                 if (keyLong >= 0)
                     val.setPosIntValue(keyLong);
                 else
                     val.setNegIntValue(keyLong);
             }
             else if (featVal instanceof Double || featVal instanceof Float)
                 val.setDoubleValue(((Number) featVal).doubleValue());
             else {
                 // TODO serialize to JSON
                 LOG.warn("Unable to save object of type {} to geobuf, falling back on toString. Deserialization will not work as expected.", featVal.getClass());
                 val.setStringValue(featVal.toString());
             }
             int keyIdx = keys.indexOf(e.getKey());
             if (keyIdx == -1) {
                 synchronized (keys) {
                     keyIdx = keys.size();
                     keys.add(e.getKey());
                 }
             }
             // properties is a jagged array of [key index, value index, . . .]
             feat.addProperties(keyIdx);
             feat.addProperties(feat.getValuesCount());
             feat.addValues(val);
         }
         if (feature.id != null) {
             feat.setId(feature.id);
             feat.clearIntId();
         }
         else {
             feat.setIntId(feature.numericId);
             feat.clearId();
         }
         return feat.build();
     }
makeFeatureCollection()
Geobuf.Data makeFeatureCollection (Collection< GeobufFeature > featureCollection)
References Geobuf.Data.FeatureCollection.Builder.addAllCustomProperties(), Geobuf.Data.FeatureCollection.Builder.addAllValues(), Geobuf.Data.FeatureCollection.Builder.build(), GeobufEncoder.makeFeature(), Geobuf.Data.FeatureCollection.newBuilder(), Geobuf.Data.newBuilder(), Geobuf.Data.Builder.setDimensions(), and Geobuf.Data.Builder.setPrecision().
Referenced by GeobufEncoder.GeobufFeatureSerializer.serialize(), and GeobufEncoder.writeFeatureCollection().
{
         Geobuf.Data.Builder data = Geobuf.Data.newBuilder()
                 .setPrecision(this.precision)
                 // TODO don't hardwire
                 .setDimensions(2);
         Geobuf.Data.FeatureCollection.Builder fc = Geobuf.Data.FeatureCollection.newBuilder();
         // deduplicate keys
         List<String> keys = new ArrayList<>();
         featureCollection.stream()
                 .map(f -> this.makeFeature(f, keys))
                 .forEach(fc::addFeatures);
         fc.addAllValues(Collections.emptyList());
         fc.addAllCustomProperties(Collections.emptyList());
         data.setFeatureCollection(fc);
         data.addAllKeys(keys);
         return data.build();
     }
multiPolyToGeobuf()
Geobuf.Data.Geometry multiPolyToGeobuf (MultiPolygon poly)
References Geobuf.Data.Geometry.Builder.addLengths(), GeobufEncoder.addRing(), Geobuf.Data.Geometry.Builder.build(), Geobuf.Data.Geometry.Type.MULTIPOLYGON, Geobuf.Data.Geometry.newBuilder(), and Geobuf.Data.Geometry.Builder.setType().
Referenced by GeobufEncoder.geomToGeobuf().
{
         Geobuf.Data.Geometry.Builder builder = Geobuf.Data.Geometry.newBuilder()
                 .setType(Geobuf.Data.Geometry.Type.MULTIPOLYGON);
         // first we specify the number of polygons
         builder.addLengths(poly.getNumGeometries());
         for (int i = 0; i < poly.getNumGeometries(); i++) {
             Polygon p = (Polygon) poly.getGeometryN(i);
             // how many rings there are
             builder.addLengths(p.getNumInteriorRing() + 1);
             Stream<LineString> interiorRings = IntStream.range(0, p.getNumInteriorRing())
                     .<LineString>mapToObj(p::getInteriorRingN);
             Stream.concat(Stream.of(p.getExteriorRing()), interiorRings)
                     .forEach(r -> addRing(r, builder));
         }
         return builder.build();
     }
pointToGeobuf()
Geobuf.Data.Geometry pointToGeobuf (Point point)
References Geobuf.Data.Geometry.Builder.addCoords(), Geobuf.Data.Geometry.Builder.build(), Geobuf.Data.Geometry.newBuilder(), Geobuf.Data.Geometry.Type.POINT, GeobufEncoder.precisionMultiplier, and Geobuf.Data.Geometry.Builder.setType().
Referenced by GeobufEncoder.geomToGeobuf().
{
         return Geobuf.Data.Geometry.newBuilder()
                 .setType(Geobuf.Data.Geometry.Type.POINT)
                 .addCoords((long) (point.getX() * precisionMultiplier))
                 .addCoords((long) (point.getY() * precisionMultiplier))
                 .build();
     }
polyToGeobuf()
Geobuf.Data.Geometry polyToGeobuf (Polygon poly)
References GeobufEncoder.addRing(), Geobuf.Data.Geometry.Builder.build(), Geobuf.Data.Geometry.newBuilder(), Geobuf.Data.Geometry.Type.POLYGON, and Geobuf.Data.Geometry.Builder.setType().
Referenced by GeobufEncoder.geomToGeobuf().
{
         Geobuf.Data.Geometry.Builder builder = Geobuf.Data.Geometry.newBuilder()
                 .setType(Geobuf.Data.Geometry.Type.POLYGON);
         Stream<LineString> interiorRings = IntStream.range(0, poly.getNumInteriorRing())
                 .mapToObj(poly::getInteriorRingN);
         Stream.concat(Stream.of(poly.getExteriorRing()), interiorRings)
                 .forEach(r -> addRing(r, builder));
         return builder.build();
     }
writeFeatureCollection()
void writeFeatureCollection (Collection< GeobufFeature > featureCollection) throws IOException
References GeobufEncoder.makeFeatureCollection().
{
         outputStream.write(makeFeatureCollection(featureCollection).toByteArray());
     }
Member Data Documentation
LOG
final Logger LOG = LoggerFactory.getLogger(GeobufEncoder.class) static private
outputStream
OutputStream outputStream private
Referenced by GeobufEncoder.GeobufEncoder().
precision
final int precision
Referenced by GeobufEncoder.GeobufEncoder().
precisionMultiplier
final long precisionMultiplier
What to multiply floating point values by to get desired precision.
Referenced by GeobufEncoder.pointToGeobuf().