jena-geo: LineSubstring Class Reference
LineSubstring Class Reference
Public Member Functions
NodeValue exec (NodeValue v1, NodeValue v2, NodeValue v3)
Member Function Documentation
exec()
NodeValue exec (NodeValue v1, NodeValue v2, NodeValue v3)
References GeometryWrapper.extract(), GeometryWrapper.getGeometryDatatypeURI(), and GeometryWrapper.getXYGeometry().
{
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(v1);
             Geometry geom = geometry.getXYGeometry();
             Double startPercentage=v2.getDouble();
             Double endPercentage=v3.getDouble();
             LengthSubstring lsub=new LengthSubstring((LineString)geom);
             if (geom instanceof MultiLineString) {
                 List<Coordinate> resultcoords=new LinkedList<Coordinate>();
                 for(int i=0;i<((MultiLineString) geom).getLength();i++) {
                         resultcoords.addAll(Arrays.asList(((MultiLineString) geom).getGeometryN(i).getCoordinates()));
                 }
                 return GeometryWrapperFactory.createLineString(resultcoords.toArray(new Coordinate[0]), geometry.getGeometryDatatypeURI()).asNodeValue();
             }
             return NodeValue.nvNothing;
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
         }