jena-geo: Area Class Reference
Area Class Reference
Returns the area of the surface if it is a Polygon or MultiPolygon.
Public Member Functions
NodeValue exec (NodeValue arg0)
Detailed Description
Returns the area of the surface if it is a Polygon or MultiPolygon.
For geometry, a 2D Cartesian area is determined with units specified by the SRID. For geography, area is determined on a curved surface with units in square meters.
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0)
References GeometryWrapper.getParsingGeometry(), CoverageWrapper.getXYGeometry(), LiteralUtils.rasterOrVector(), and LiteralUtils.toGeometry().
Referenced by AreaTest.testArea().
{
         Wrapper wrapper1=LiteralUtils.rasterOrVector(arg0);
         if(wrapper1 instanceof GeometryWrapper) {
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(arg0);
             Geometry geom = geometry.getParsingGeometry();
             return NodeValue.makeDouble(geom.getArea());
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
         }else if(wrapper1 instanceof CoverageWrapper) {
                  CoverageWrapper covwrap = CoverageWrapper.extract(arg0);
              GridCoverage2D cov = covwrap.getXYGeometry();
              return NodeValue.makeDouble(LiteralUtils.toGeometry(cov.getEnvelope()).getArea());
         }else {
                 return NodeValue.makeDouble(0.);
         }
     }