jena-geo: IsSolid Class Reference
IsSolid Class Reference
Public Member Functions
NodeValue exec (NodeValue v)
Member Function Documentation
exec()
NodeValue exec (NodeValue v)
References GeometryWrapper.extract(), and GeometryWrapper.getParsingGeometry().
Referenced by IsSolidTest.testIsSolidFalse(), and IsSolidTest.testIsSolidTrue().
{
                try {
                     GeometryWrapper geometry = GeometryWrapper.extract(v);
                     Geometry geom = geometry.getParsingGeometry();
                     Boolean is3D=true;
                     for(Coordinate coord:geom.getCoordinates()) {
                         if(Double.isNaN(coord.getZ())) {
                                 is3D=false;
                         }
                     }
                     return NodeValue.makeNodeBoolean(is3D);
                 } catch (DatatypeFormatException ex) {
                     throw new ExprEvalException(ex.getMessage(), ex);
                 }
         }