jena-geo: ExampleWebService Class Reference
ExampleWebService Class Reference
Public Member Functions
String queryService (@QueryParam("query") String query, @QueryParam("dataset") String dataset)
String queryService (@QueryParam("query") String query, @QueryParam("dataset") String dataset, @QueryParam("geojson") String geojson)
String helloWorld ()
String benchmark (@QueryParam("query") String query, @QueryParam("dataset") String dataset)
Static Public Member Functions
static void main (String[] args)
Member Function Documentation
benchmark()
String benchmark (@QueryParam("query") String query, @QueryParam("dataset") String dataset)
References BenchmarkExecutor.benchmark().
{
                 System.out.println("BENCHMARK QUERY!!!");
                 final String dir = System.getProperty("user.dir");
         System.out.println("current dir = " + dir);
         //JSONObject sqlresults=BenchmarkExecutor.benchmark(query,dataset,true);
         JSONObject sparqlresults=BenchmarkExecutor.benchmark(query,dataset,false);
         System.out.println("FINISHED BENCHMARKS!");
                 JSONObject result=new JSONObject();
                 result.put("sparql",sparqlresults);
                 //result.put("sql", sqlresults);
                 System.out.println("PACKING JSON");
                 return result.toString();
         }
helloWorld()
String helloWorld ()
{
                 return "HelloWorld";
         }
main()
static void main (String [] args) static
References TripleStoreConnection.executeQuery().
{
                 TripleStoreConnection.executeQuery("","testdata2.ttl");
         //JSONObject sparqlresults=BenchmarkExecutor.benchmark("all","all",false);
         //JSONObject sqlresults=BenchmarkExecutor.benchmark("all","all",true);
         }
queryService() [1/2]
String queryService (@QueryParam("query") String query, @QueryParam("dataset") String dataset)
References TripleStoreConnection.executeQuery().
{
                 final String dir = System.getProperty("user.dir");
         System.out.println("current dir = " + dir);
                 return TripleStoreConnection.executeQuery(query,dataset);
         }
queryService() [2/2]
String queryService (@QueryParam("query") String query, @QueryParam("dataset") String dataset, @QueryParam("geojson") String geojson)
References TripleStoreConnection.executeQuery().
{
                 final String dir = System.getProperty("user.dir");
         System.out.println("current dir = " + dir);
                 return TripleStoreConnection.executeQuery(query,dataset,true);
         }