jena-geo: YMax Class Reference
YMax Class Reference
Returns Y maxima of a bounding box 2d or 3d or a geometry.
Public Member Functions
NodeValue exec (NodeValue arg0)
Detailed Description
Returns Y maxima of a bounding box 2d or 3d or a geometry.
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0)
References GeometryWrapper.extract(), and GeometryWrapper.getXYGeometry().
Referenced by MaxYTest.testX(), and YMaxTest.testYMax().
{
         GeometryWrapper geometry = GeometryWrapper.extract(arg0);
         Geometry geo=geometry.getXYGeometry();
         Double maxY=0.;
         for(Coordinate coord:geo.getCoordinates()) {
                 if(maxY<coord.getY()) {
                         maxY=coord.getY();
                 }
         }
         return NodeValue.makeDouble(maxY);
     }