jena-geo: ConcaveHull Class Reference
ConcaveHull Class Reference
The concave hull of a geometry represents a possibly concave geometry that encloses all geometries within the set.
Public Member Functions
NodeValue exec (NodeValue arg0, NodeValue arg1, NodeValue arg2)
Detailed Description
The concave hull of a geometry represents a possibly concave geometry that encloses all geometries within the set.
You can think of it as shrink wrapping.
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0, NodeValue arg1, NodeValue arg2)
References GeometryWrapper.asNodeValue(), GeometryWrapper.extract(), ConcaveHull.getConcaveHull(), GeometryWrapper.getGeometryDatatypeURI(), GeometryWrapper.getParsingGeometry(), and GeometryWrapper.getSrsURI().
{
         try {
             GeometryWrapper geom = GeometryWrapper.extract(arg0);
             float targetPercent = arg1.getFloat();
             org.opensphere.geometry.algorithm.ConcaveHull hull = new org.opensphere.geometry.algorithm.ConcaveHull(geom.getParsingGeometry(), targetPercent);
             Geometry concaveHull = hull.getConcaveHull();
             GeometryWrapper concaveWrapper = GeometryWrapperFactory.createGeometry(concaveHull, geom.getSrsURI(), geom.getGeometryDatatypeURI());
             return concaveWrapper.asNodeValue();
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
     }