jena-geo: Max Class Reference
Max Class Reference
Public Member Functions
NodeValue exec (NodeValue v1, NodeValue v2)
Member Function Documentation
exec()
NodeValue exec (NodeValue v1, NodeValue v2)
{
                 CoverageWrapper wrapper=CoverageWrapper.extract(v1);
                 GridCoverage raster=wrapper.getXYGeometry();
                 CoverageWrapper wrapper2=CoverageWrapper.extract(v2);
                 GridCoverage raster2=wrapper2.getXYGeometry();
                  ParameterBlock pbSubtracted = new ParameterBlock();
              pbSubtracted.addSource(raster.render(null));
              pbSubtracted.addSource(raster2.render(null));
              RenderedOp subtractedImage = JAI.create("max",pbSubtracted);
                 final SampleDimension sd =raster.getSampleDimensions().get(0);
                 List<SampleDimension>sds=new LinkedList<SampleDimension>();
                 sds.add(sd);
         GridExtent extent=new GridExtent(subtractedImage.getWidth(), subtractedImage.getHeight());
         GridGeometry gridgeom=new GridGeometry(extent, PixelInCell.CELL_CENTER, raster.getGridGeometry().getGridToCRS(PixelInCell.CELL_CENTER), raster.getCoordinateReferenceSystem());
         List<SampleDimension> dimensions=new LinkedList<SampleDimension>();
         DefaultNameFactory fac=new DefaultNameFactory();
         for(int i=0;i<subtractedImage.getNumBands();i++) {
                 dimensions.add(new SampleDimension(fac.createGenericName(null,  "Dimension "+i),0.,new LinkedList<Category>()));
         }
         BufferedGridCoverage coverage=new BufferedGridCoverage(
                         gridgeom, dimensions, subtractedImage.getData().getDataBuffer());
                         return CoverageWrapper.createCoverage((GridCoverage)coverage, wrapper.getSrsURI(), wrapper.getRasterDatatypeURI())
                                         .asNodeValue();
         }
References CoverageWrapper.asNodeValue(), CoverageWrapper.createCoverage(), CoverageWrapper.extract(), CoverageWrapper.getRasterDatatypeURI(), CoverageWrapper.getSrsURI(), and CoverageWrapper.getXYGeometry().
Referenced by MaxTest.testMax().