jena-geo: IsScaleneTriangle Class Reference
IsScaleneTriangle Class Reference
Public Member Functions
NodeValue exec (NodeValue v)
Member Function Documentation
exec()
NodeValue exec (NodeValue v)
References Coordinate.distance(), GeometryWrapper.extract(), and GeometryWrapper.getParsingGeometry().
Referenced by IsScaleneTriangleTest.testIsScaleneTriangleFalse(), and IsScaleneTriangleTest.testIsScaleneTriangleTrue().
{
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(v);
             Geometry geom = geometry.getParsingGeometry();
             if (geom instanceof Polygon) {
                 if(geom.getCoordinates().length==4) {
                         Coordinate p0=geom.getCoordinates()[0];
                         Coordinate p1=geom.getCoordinates()[1];
                         Coordinate p2=geom.getCoordinates()[2];
                         double len0 = p1.distance(p2);
                     double len1 = p0.distance(p2);
                     double len2 = p0.distance(p1);
                     if ((len0 != len1 && len1 != len2)
                                 ||  (len1 != len2  && len2 != len0)
                                 || (len0 != len1  && len2 != len0))
                         return NodeValue.TRUE;
                     else
                         return NodeValue.FALSE;
                 }
             }
             return NodeValue.FALSE;
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
         }