jena-geo: RemovePoints Class Reference
RemovePoints Class Reference
Removes the points contained in the second geometry from the first geometry.
Public Member Functions
NodeValue exec (NodeValue v1, NodeValue v2)
Detailed Description
Removes the points contained in the second geometry from the first geometry.
Member Function Documentation
exec()
NodeValue exec (NodeValue v1, NodeValue v2)
References GeometryWrapper.asNodeValue(), LiteralUtils.createGeometry(), GeometryWrapper.extract(), GeometryWrapper.getGeometryDatatypeURI(), GeometryWrapper.getSrsURI(), and GeometryWrapper.getXYGeometry().
{
                  GeometryWrapper geometry = GeometryWrapper.extract(v1);
                Geometry geom = geometry.getXYGeometry();
                GeometryWrapper geometry2 = GeometryWrapper.extract(v1);
                Geometry geom2 = geometry2.getXYGeometry();
                         GeometryFactory fac=new GeometryFactory();
                 if (!geom2.intersects(geom)) {
             return GeometryWrapperFactory.createGeometry(fac.createPoint(), geometry.getSrsURI(),geometry.getGeometryDatatypeURI()).asNodeValue();
         }
         Coordinate[] arrayOfCoordinate1 = new Coordinate[geom.getCoordinates().length];
         int j = 0;
         for (Coordinate coordinate : geom.getCoordinates()) {
             if (!geom2.contains(fac.createPoint(coordinate))) {
                 arrayOfCoordinate1[(j++)] = coordinate;
             }
         }
         Coordinate[] arrayOfCoordinate2 = CoordinateArrays.removeNull(arrayOfCoordinate1);
         Coordinate[] localObject = arrayOfCoordinate2;
         if (((geom instanceof LinearRing)) && (arrayOfCoordinate2.length > 1) && (!arrayOfCoordinate2[(arrayOfCoordinate2.length - 1)].equals2D(arrayOfCoordinate2[0]))) {
             Coordinate[] arrayOfCoordinate3 = new Coordinate[arrayOfCoordinate2.length + 1];
             CoordinateArrays.copyDeep(arrayOfCoordinate2, 0, arrayOfCoordinate3, 0, arrayOfCoordinate2.length);
             arrayOfCoordinate3[(arrayOfCoordinate3.length - 1)] = new Coordinate(arrayOfCoordinate3[0]);
             localObject = arrayOfCoordinate3;
         }
         GeometryWrapper resultgeom=LiteralUtils.createGeometry(localObject, geom.getGeometryType(), geometry);
         return resultgeom.asNodeValue();
         }