jena-geo: PointN Class Reference
PointN Class Reference
Return the Nth point in the first LineString or circular LineString in the geometry.
Public Member Functions
NodeValue exec (NodeValue arg0, NodeValue arg1)
Detailed Description
Return the Nth point in the first LineString or circular LineString in the geometry.
Negative values are counted backwards from the end of the LineString. Returns NULL if there is no linestring in the geometry.
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0, NodeValue arg1)
References GeometryWrapper.asNodeValue(), GeometryWrapper.extract(), GeometryWrapper.getGeometryDatatypeURI(), GeometryWrapper.getParsingGeometry(), GeometryWrapper.getSrsURI(), Coordinate.x, and Coordinate.y.
Referenced by PointNTest.testLineString().
{
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(arg0);
             Geometry geom = geometry.getParsingGeometry();
             BigInteger n = arg1.getInteger();
             if (n.intValue() >= geom.getCoordinates().length) {
                  throw new ExprEvalException("No point "+n+" present in the input geometry");
             }
             Coordinate[] coords = geom.getCoordinates();
             CoordinateXY coord = new CoordinateXY(coords[n.intValue()].x, coords[n.intValue()].y);
             GeometryWrapper pointWrapper = GeometryWrapperFactory.createPoint(coord, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
             return pointWrapper.asNodeValue();
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
     }