jena-geo: AddT Class Reference
AddT Class Reference
Public Member Functions
NodeValue exec (NodeValue v1, NodeValue v2)
Member Function Documentation
exec()
NodeValue exec (NodeValue v1, NodeValue v2)
References GeometryWrapper.asNodeValue(), LiteralUtils.createGeometry(), GeometryWrapper.extract(), GeometryWrapper.getGeometryType(), and GeometryWrapper.getParsingGeometry().
{
                 try {
             GeometryWrapper geometry = GeometryWrapper.extract(v1);
             Double tValue=v2.getDouble();
             List<Coordinate> newcoords=new LinkedList<Coordinate>();
             for(Coordinate coord:geometry.getParsingGeometry().getCoordinates()) {
                 newcoords.add(new CoordinateXYZM(coord.x,coord.y,coord.z,tValue));
             }
             GeometryWrapper res=LiteralUtils.createGeometry(newcoords, geometry.getGeometryType(), geometry);
             return res.asNodeValue();
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
         }