jena-geo: MakeEmptyRaster Class Reference
MakeEmptyRaster Class Reference
Public Member Functions
NodeValue exec ()
Member Function Documentation
exec()
NodeValue exec ()
{
                 Integer width=10;
                 Integer height=20;
                 Double upperleftx;
                 Double upperlefty;
                 Double pixelsize;
                 WritableRaster raster = RasterFactory.createBandedRaster(DataBuffer.TYPE_FLOAT, width, height, 1, null);
                 for (int y = 0; y < height; y++) {
                         for (int x = 0; x < width; x++) {
                                 raster.setSample(x, y, 0, x + y);
                         }
                 }
                 //CoordinateReferenceSystem crs = CommonCRS.WGS84.defaultGeographic();
                 CoordinateReferenceSystem crss=null;
                 Envelope2D envelope=null;
                 try {
                         crss = CRS.forCode("EPSG:4326");
                         envelope = new Envelope2D(crss, 0, 0, 30, 30);
                 } catch (FactoryException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                         envelope = new Envelope2D(CommonCRS.WGS84.defaultGeographic(), 0, 0, 30, 30);
                 }
         GridExtent extent=new GridExtent(raster.getWidth(), raster.getHeight());
         GridGeometry gridgeom=new GridGeometry(extent, PixelInCell.CELL_CENTER, null, crss);
         List<SampleDimension> dimensions=new LinkedList<SampleDimension>();
         DefaultNameFactory fac=new DefaultNameFactory();
         for(int i=0;i<raster.getNumBands();i++) {
                 dimensions.add(new SampleDimension(fac.createGenericName(null,  "Dimension "+i),0.,new LinkedList<Category>()));
         }
         BufferedGridCoverage coverage=new BufferedGridCoverage(
                         gridgeom, dimensions, raster.getDataBuffer());
                 return CoverageWrapper.createCoverage(coverage, "EPSG:4326", HexWKBRastDatatype.URI.toString()).asNodeValue();
         }
References CoverageWrapper.asNodeValue(), CoverageWrapper.createCoverage(), and HexWKBRastDatatype.URI.
Referenced by MakeEmptyRasterTest.testMakeEmptyRaster().