jena-geo: NumYTiles Class Reference
NumYTiles Class Reference
Public Member Functions
NodeValue exec (NodeValue v)
Member Function Documentation
exec()
NodeValue exec (NodeValue v)
References CoverageWrapper.extract(), CoverageWrapper.getXYGeometry(), and GridCoverage.render().
Referenced by NumYTilesTest.testNumYTiles().
{
                 CoverageWrapper wrapper=CoverageWrapper.extract(v);
                 GridCoverage raster=wrapper.getXYGeometry();
                 try {
                         return NodeValue.makeInteger(raster.render(null).getNumYTiles());
                 } catch (CannotEvaluateException e) {
                         return null;
                 }
         }