jena-geo: ShortestLine3D Class Reference
ShortestLine3D Class Reference
Public Member Functions
NodeValue exec (NodeValue arg0, NodeValue arg1)
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0, NodeValue arg1)
References GeometryWrapper.asNodeValue(), GeometryWrapper.extract(), GeometryWrapper.getGeometryDatatypeURI(), GeometryWrapper.getSrsInfo(), GeometryWrapper.getSrsURI(), GeometryWrapper.getXYGeometry(), and GeometryWrapper.transform().
{
                  try {
                     GeometryWrapper geometry1 = GeometryWrapper.extract(arg0);
                     GeometryWrapper geometry2 = GeometryWrapper.extract(arg1);
                     GeometryWrapper transGeometry2 = geometry2.transform(geometry1.getSrsInfo());
                     Distance3DOp distop = new Distance3DOp(geometry1.getXYGeometry(), transGeometry2.getXYGeometry());
                     Coordinate[] coord = distop.nearestPoints();
                     GeometryWrapper lineStringWrapper = GeometryWrapperFactory.createLineString(coord, geometry1.getSrsURI(), geometry1.getGeometryDatatypeURI());
                     return lineStringWrapper.asNodeValue();
                 } catch (Exception ex) {
                         return NodeValue.makeString(ex.getMessage());
                     //throw new ExprEvalException(ex.getMessage(), ex);
                 }
         }