jena-geo: DistanceSphere Class Reference
DistanceSphere Class Reference
Public Member Functions
NodeValue exec (NodeValue arg0, NodeValue arg1)
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0, NodeValue arg1)
References GeometryWrapper.distanceGreatCircle(), GeometryWrapper.getSrsInfo(), LiteralUtils.rasterOrVector(), and GeometryWrapper.transform().
Referenced by DistanceSphereTest.testDistanceSphere(), DistanceSphereTest.testDistanceSphere2(), DistanceSphereTest.testDistanceSphereRaster(), and DistanceSphereTest.testDistanceSphereRaster2().
{
                 Wrapper wrapper1=LiteralUtils.rasterOrVector(arg0);
                 Wrapper wrapper2=LiteralUtils.rasterOrVector(arg1);
         if(wrapper1 instanceof GeometryWrapper) {
         try {
             GeometryWrapper geom1 = GeometryWrapper.extract(arg0);
             GeometryWrapper geom2 = GeometryWrapper.extract(arg1);
             GeometryWrapper transGeom2 = geom2.transform(geom1.getSrsInfo());
             double distance = geom1.distanceGreatCircle(transGeom2);
             return NodeValue.makeDouble(distance);
         } catch (DatatypeFormatException | FactoryException | MismatchedDimensionException | TransformException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
         }
         return null;
     }