jena-geo: ContainsProperly Class Reference
ContainsProperly Class Reference
Public Member Functions
NodeValue exec (NodeValue v, NodeValue v1)
Boolean containsProperly (Geometry geom1, Geometry geom2)
Member Function Documentation
containsProperly()
Boolean containsProperly (Geometry geom1, Geometry geom2)
Referenced by ContainsProperly.exec().
{
         if(!geom1.contains(geom2)) {
                 return false;
         }else {
                 Coordinate oldcoord=null;
                 for(Coordinate coord:geom1.getCoordinates()) {
                         if(oldcoord!=null) {
                                 LineString ls=(LineString) GeometryWrapperFactory.createLineString(new Coordinate[] {oldcoord, coord},WKTDatatype.URI).getXYGeometry();
                                 if(ls.intersects(geom2)) {
                                         return false;
                                 }
                         }
                         oldcoord=coord;
                 }
                 return true;
         }
         }
exec()
NodeValue exec (NodeValue v, NodeValue v1)
References ContainsProperly.containsProperly(), GeometryWrapper.getXYGeometry(), LiteralUtils.rasterOrVector(), LiteralUtils.toGeometry(), and GeometryWrapper.transform().
{
                 Wrapper wrapper1=LiteralUtils.rasterOrVector(v);
                 Wrapper wrapper2=LiteralUtils.rasterOrVector(v1);
                 if(wrapper1 instanceof GeometryWrapper && wrapper2 instanceof GeometryWrapper) {
                         GeometryWrapper transGeom2;
                         try {
                                 transGeom2 = ((GeometryWrapper)wrapper2).transform(((GeometryWrapper)wrapper1).getSrsInfo());
                                 return NodeValue.makeBoolean(containsProperly(((GeometryWrapper)wrapper1).getXYGeometry(),transGeom2.getXYGeometry()));
                         } catch (MismatchedDimensionException | TransformException | FactoryException e) {
                                 throw new RuntimeException("CRS transformation failed");
                         }
                 }else if(wrapper1 instanceof CoverageWrapper && wrapper2 instanceof CoverageWrapper) {
                         GridCoverage raster=((CoverageWrapper)wrapper1).getGridGeometry();
                         GridCoverage raster2=((CoverageWrapper)wrapper2).getGridGeometry();
                         Geometry bbox1 = LiteralUtils.toGeometry(raster.getGridGeometry().getEnvelope());
                     Geometry bbox2 = LiteralUtils.toGeometry(raster2.getGridGeometry().getEnvelope());
                     return NodeValue.makeBoolean(containsProperly(bbox1,bbox2));
                 }else {
                         if(wrapper1 instanceof CoverageWrapper) {
                                 GridCoverage raster=((CoverageWrapper)wrapper1).getGridGeometry();
                                 Geometry bbox1 = LiteralUtils.toGeometry(raster.getGridGeometry().getEnvelope());
                                 Geometry geom=((GeometryWrapper)wrapper2).getXYGeometry();
                                 return NodeValue.makeBoolean(containsProperly(bbox1, geom));
                         }else {
                                 GridCoverage raster=((CoverageWrapper)wrapper2).getGridGeometry();
                                 Geometry bbox1 = LiteralUtils.toGeometry(raster.getGridGeometry().getEnvelope());
                                 Geometry geom=((GeometryWrapper)wrapper1).getXYGeometry();
                                 return NodeValue.makeBoolean(containsProperly(bbox1, geom));
                         }
                 }
         }