jena-geo: MaxDistance Class Reference
MaxDistance Class Reference
Returns the 2-dimensional largest distance between two geometries in projected units.
Public Member Functions
NodeValue exec (NodeValue v1, NodeValue v2)
Detailed Description
Returns the 2-dimensional largest distance between two geometries in projected units.
Member Function Documentation
exec()
NodeValue exec (NodeValue v1, NodeValue v2)
References GeometryWrapper.distance(), GeometryWrapper.extract(), GeometryWrapper.getSRID(), GeometryWrapper.getXYGeometry(), and GeometryWrapper.transform().
Referenced by MaxDistanceTest.testMaxDistance().
{
         GeometryWrapper geom1 = GeometryWrapper.extract(v1);
         GeometryWrapper geom2 = GeometryWrapper.extract(v2);
         Double maxDistance=0.;
         try {
                         GeometryWrapper transGeom2 = geom2.transform(geom1.getSRID());
                         for(Coordinate coord:geom1.getXYGeometry().getCoordinates()) {
                                 for(Coordinate coord2:transGeom2.getXYGeometry().getCoordinates()) {
                                         Double curdistance=coord.distance(coord2);
                                         if(curdistance>maxDistance) {
                                                 maxDistance=curdistance;
                                         }
                                 }
                         }
                         return NodeValue.makeDouble(maxDistance);
         } catch (TransformException | FactoryException e) {
                 throw new ExprEvalException("Error in distance calculation");
                 }
         }