jena-geo: ShortestLine Class Reference
ShortestLine Class Reference
Returns the 2-dimensional shortest line between two geometries.
Public Member Functions
NodeValue exec (NodeValue arg0, NodeValue arg1)
Detailed Description
Returns the 2-dimensional shortest line between two geometries.
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0, NodeValue arg1)
References GeometryWrapper.asNodeValue(), GeometryWrapper.extract(), GeometryWrapper.getGeometryDatatypeURI(), GeometryWrapper.getSrsInfo(), GeometryWrapper.getSrsURI(), GeometryWrapper.getXYGeometry(), and GeometryWrapper.transform().
Referenced by ShortestLineTest.testOrderingEquals1(), and ShortestLineTest.testShortestLine().
{
         try {
             GeometryWrapper geometry1 = GeometryWrapper.extract(arg0);
             GeometryWrapper geometry2 = GeometryWrapper.extract(arg1);
             GeometryWrapper transGeometry2 = geometry2.transform(geometry1.getSrsInfo());
             DistanceOp distop = new DistanceOp(geometry1.getXYGeometry(), transGeometry2.getXYGeometry());
             Coordinate[] coord = distop.nearestPoints();
             GeometryWrapper lineStringWrapper = GeometryWrapperFactory.createLineString(coord, geometry1.getSrsURI(), geometry1.getGeometryDatatypeURI());
             return lineStringWrapper.asNodeValue();
         } catch (DatatypeFormatException | FactoryException | TransformException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
     }