jena-geo: ValueIntersects Class Reference
ValueIntersects Class Reference
Public Member Functions
NodeValue exec (NodeValue v1, NodeValue v2, NodeValue v3, NodeValue v4)
Member Function Documentation
exec()
NodeValue exec (NodeValue v1, NodeValue v2, NodeValue v3, NodeValue v4)
{
         Wrapper wrapper1=LiteralUtils.rasterOrVector(v1);
         Wrapper wrapper2=LiteralUtils.rasterOrVector(v2);
         Double value=v4.getDouble();
         Integer bandnum=v3.getInteger().intValue();
         if(wrapper1 instanceof GeometryWrapper && wrapper2 instanceof GeometryWrapper) {
                 throw new RuntimeException("Function only applicable to Vector/Raster Raster/Raster input");
         }else if(wrapper1 instanceof CoverageWrapper && wrapper2 instanceof CoverageWrapper) {
                 GridCoverage raster=((CoverageWrapper)wrapper1).getGridGeometry();
                 GridCoverage raster2=((CoverageWrapper)wrapper2).getGridGeometry();
                 Geometry bbox1 = LiteralUtils.toGeometry(raster.getGridGeometry().getEnvelope());
             Geometry bbox2 = LiteralUtils.toGeometry(raster2.getGridGeometry().getEnvelope());
             if(bbox1.equals(bbox2)) {
                 try {
                                 GridCoverage cov = LiteralUtils.cropRaster2(((CoverageWrapper)wrapper1).getXYGeometry(), bbox1.getEnvelopeInternal().getWidth(), bbox1.getEnvelopeInternal().getHeight(), bbox1.getEnvelopeInternal().getMaxX(), bbox1.getEnvelopeInternal().getMaxY());
                                 if(LiteralUtils.containsRasterValue(cov, bandnum,value)) {
                                         return NodeValue.TRUE;
                                 }
                                 return NodeValue.FALSE;
                 } catch (MismatchedDimensionException | TransformException e) {
                                 throw new RuntimeException("Cropping failed");
                         }
             }
             if(!bbox1.intersects(bbox2)) {
                 return NodeValue.FALSE;
             }else {
                 Geometry intersection=bbox1.intersection(bbox2);
                         try {
                                         GridCoverage cov = LiteralUtils.cropRaster2(((CoverageWrapper)wrapper1).getXYGeometry(), intersection.getEnvelopeInternal().getWidth(), intersection.getEnvelopeInternal().getHeight(), intersection.getEnvelopeInternal().getMaxX(), intersection.getEnvelopeInternal().getMaxY());
                                         if(LiteralUtils.containsRasterValue(cov, bandnum,value)) {
                                                 return NodeValue.TRUE;
                                         }
                                         return NodeValue.FALSE;
                         } catch (MismatchedDimensionException | TransformException e) {
                                         throw new RuntimeException("Cropping failed");
                                 }
             }
         }else {
                 if(wrapper1 instanceof CoverageWrapper) {
                         GridCoverage raster=((CoverageWrapper)wrapper1).getGridGeometry();
                         Geometry bbox1 = LiteralUtils.toGeometry(raster.getGridGeometry().getEnvelope());
                         Geometry geom=((GeometryWrapper)wrapper2).getXYGeometry();
                     if(!bbox1.intersects(geom)) {
                         return NodeValue.FALSE;
                     }else {
                         Geometry intersection=bbox1.intersection(geom);
                                 try {
                                                 GridCoverage cov=LiteralUtils.cropRaster2(((CoverageWrapper)wrapper1).getXYGeometry(), intersection.getEnvelopeInternal().getWidth(), intersection.getEnvelopeInternal().getHeight(), intersection.getEnvelopeInternal().getMaxX(), intersection.getEnvelopeInternal().getMaxY());
                                                 if(LiteralUtils.containsRasterValue(cov, bandnum,value)) {
                                                         return NodeValue.TRUE;
                                                 }
                                                 return NodeValue.FALSE;
                                 } catch (MismatchedDimensionException | TransformException e) {
                                                 throw new RuntimeException("Cropping failed");
                                         }
                     }
                 }else {
                         GridCoverage raster=((CoverageWrapper)wrapper2).getGridGeometry();
                         Geometry bbox1 = LiteralUtils.toGeometry(raster.getGridGeometry().getEnvelope());
                         Geometry geom=((GeometryWrapper)wrapper1).getXYGeometry();
                     if(!bbox1.intersects(geom)) {
                         return NodeValue.FALSE;
                     }else {
                         Geometry intersection=bbox1.intersection(geom);
                                 try {
                                                 GridCoverage cov=LiteralUtils.cropRaster2(((CoverageWrapper)wrapper2).getXYGeometry(), intersection.getEnvelopeInternal().getWidth(), intersection.getEnvelopeInternal().getHeight(), intersection.getEnvelopeInternal().getMaxX(), intersection.getEnvelopeInternal().getMaxY());
                                                 if(LiteralUtils.containsRasterValue(cov, bandnum,value)) {
                                                         return NodeValue.TRUE;
                                                 }
                                                 return NodeValue.FALSE;
                                 } catch (MismatchedDimensionException | TransformException e) {
                                                 throw new RuntimeException("Cropping failed");
                                 }
                     }
         }}}
References LiteralUtils.containsRasterValue(), LiteralUtils.cropRaster2(), LiteralUtils.rasterOrVector(), and LiteralUtils.toGeometry().
Referenced by ValueIntersectsTest.testMedIntersects(), ValueIntersectsTest.testMedIntersectsTrue(), and ValueIntersectsTest.testSmallerIntersects().