jena-geo: Force2D Class Reference
Force2D Class Reference
Force the geometries into a "2-dimensional mode".
Public Member Functions
NodeValue exec (NodeValue v)
Detailed Description
Force the geometries into a "2-dimensional mode".
Member Function Documentation
exec()
NodeValue exec (NodeValue v)
References LiteralUtils.createGeometry(), GeometryWrapper.extract(), and GeometryWrapper.getXYGeometry().
Referenced by Force2DTest.testForce2D().
{
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(v);
             Geometry geom = geometry.getXYGeometry();
             List<Coordinate> newcoords=new ArrayList<Coordinate>();
             for(Coordinate coord:geom.getCoordinates()) {
                 newcoords.add(new Coordinate(coord.x,coord.y));
             }
             return LiteralUtils.createGeometry(newcoords,geom.getGeometryType(),geometry).asNodeValue();
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
         }