jena-geo: EndPoint Class Reference
EndPoint Class Reference
Returns the last point of a LINESTRING or CIRCULARLINESTRING geometry as a POINT.
Public Member Functions
NodeValue exec (NodeValue arg0)
Detailed Description
Returns the last point of a LINESTRING or CIRCULARLINESTRING geometry as a POINT.
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0)
References GeometryWrapper.asNodeValue(), GeometryWrapper.extract(), GeometryWrapper.getGeometryDatatypeURI(), GeometryWrapper.getSrsURI(), and GeometryWrapper.getXYGeometry().
Referenced by EndPointTest.testLineString2D(), EndPointTest.testLineString3D(), and EndPointTest.testPoint().
{
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(arg0);
             Geometry geom = geometry.getXYGeometry();
             if (geom instanceof LineString) {
                 Point point = ((LineString) geom).getEndPoint();
                 GeometryWrapper pointWrapper = GeometryWrapperFactory.createGeometry(point, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                 return pointWrapper.asNodeValue();
             }
             throw new ExprEvalException("Input geometry is not a LineString");
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
     }