jena-geo: Multi Class Reference
Multi Class Reference
Return the geometry as a MULTI* geometry.
Public Member Functions
NodeValue exec (NodeValue arg0)
Detailed Description
Return the geometry as a MULTI* geometry.
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0)
References GeometryWrapper.asNodeValue(), GeometryWrapper.extract(), GeometryWrapper.getGeometryType(), GeometryWrapper.getSrsURI(), and GeometryWrapper.getXYGeometry().
{
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(arg0);
             if(geometry.getGeometryType().toUpperCase().contains("MULTI")) {
                 return geometry.asNodeValue();
             }
             switch(geometry.getGeometryType()) {
             case "Point":
                 return GeometryWrapperFactory.createMultiPoint(Arrays.asList(geometry.getXYGeometry().getCoordinates()), geometry.getSrsURI(), WKTDatatype.URI).asNodeValue();
             case "Polygon":
                 List<Polygon> polylist=new LinkedList<Polygon>();
                 polylist.add((Polygon)geometry.getXYGeometry());
                 return GeometryWrapperFactory.createMultiPolygon(polylist, geometry.getSrsURI(), WKTDatatype.URI).asNodeValue();
             case "LineString":
                 List<LineString> linelist=new LinkedList<LineString>();
                 linelist.add((LineString)geometry.getXYGeometry());
                 return GeometryWrapperFactory.createMultiLineString(linelist, geometry.getSrsURI(), WKTDatatype.URI).asNodeValue();
             default:
                 throw new ExprEvalException("Geometry type does not have a Multi representation or is not supported", null);
             }
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
         }