jena-geo: TransScale Class Reference
TransScale Class Reference
Public Member Functions
NodeValue exec (NodeValue arg0, NodeValue arg1, NodeValue arg2, NodeValue arg3, NodeValue arg4)
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0, NodeValue arg1, NodeValue arg2, NodeValue arg3, NodeValue arg4)
References GeometryWrapper.asNodeValue(), GeometryWrapper.extract(), GeometryWrapper.getGeometryDatatypeURI(), GeometryWrapper.getSrsURI(), and GeometryWrapper.getXYGeometry().
Referenced by TransScaleTest.testTransScale().
{
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(arg0);
             Geometry geom = geometry.getXYGeometry();
             double deltaX = arg1.getDouble();
             double deltaY = arg2.getDouble();
             double xFactor = arg3.getDouble();
             double yFactor = arg4.getDouble();
             //Translate and scale
             AffineTransformation transform = new AffineTransformation();
             transform.translate(deltaX, deltaY);
             transform.scale(xFactor, yFactor);
             Geometry transGeom = transform.transform(geom);
             GeometryWrapper transWrapper = GeometryWrapperFactory.createGeometry(transGeom, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
             return transWrapper.asNodeValue();
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
     }