jena-geo: Split Class Reference
Split Class Reference
Public Member Functions
NodeValue exec (NodeValue arg0, NodeValue arg1)
Static Public Member Functions
static Geometry polygonize (Geometry geometry)
static Geometry splitPolygon (Geometry poly, Geometry line)
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0, NodeValue arg1)
References GeometryWrapper.extract(), GeometryWrapper.getGeometryDatatypeURI(), GeometryWrapper.getSrsInfo(), GeometryWrapper.getSrsURI(), GeometryWrapper.getXYGeometry(), Split.splitPolygon(), and GeometryWrapper.transform().
{
         try {
             GeometryWrapper input = GeometryWrapper.extract(arg0);
             GeometryWrapper blade = GeometryWrapper.extract(arg1);
             GeometryWrapper transBlade = blade.transform(input.getSrsInfo());
             if(input.getXYGeometry().getGeometryType().equalsIgnoreCase("Polygon")
                         && transBlade.getXYGeometry().getGeometryType().equalsIgnoreCase("LineString")) {
                 Geometry result=splitPolygon(input.getXYGeometry(), transBlade.getXYGeometry());
                 return GeometryWrapperFactory.createGeometry(result, input.getSrsURI(), input.getGeometryDatatypeURI()).asNodeValue();
             }else if(input.getXYGeometry().getGeometryType().equalsIgnoreCase("LineString")
                         && input.getXYGeometry().getGeometryType().equalsIgnoreCase("Point")) {
                 throw new ExprEvalException("Constellation of input geometries is not supported by this Split operator");
             }
             throw new ExprEvalException("Constellation of input geometries is not supported by this Split operator");
         } catch (DatatypeFormatException | FactoryException | TransformException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
     }
polygonize()
static Geometry polygonize (Geometry geometry) static
Referenced by Split.splitPolygon().
{
         List lines = LineStringExtracter.getLines(geometry);
         Polygonizer polygonizer = new Polygonizer();
         polygonizer.add(lines);
         Collection polys = polygonizer.getPolygons();
         Polygon[] polyArray = GeometryFactory.toPolygonArray(polys);
         return geometry.getFactory().createGeometryCollection(polyArray);
     }
splitPolygon()
static Geometry splitPolygon (Geometry poly, Geometry line) static
References Split.polygonize().
Referenced by Split.exec().
{
         Geometry nodedLinework = poly.getBoundary().union(line);
         Geometry polys = polygonize(nodedLinework);
         // Only keep polygons which are inside the input
         List output = new ArrayList();
         for (int i = 0; i < polys.getNumGeometries(); i++) {
             Polygon candpoly = (Polygon) polys.getGeometryN(i);
             if (poly.contains(candpoly.getInteriorPoint())) {
                 output.add(candpoly);
             }
         }
         return poly.getFactory().createGeometryCollection(GeometryFactory.toGeometryArray(output));
     }