jena-geo: RemovePoint Class Reference
RemovePoint Class Reference
Remove point from a linestring.
Public Member Functions
NodeValue exec (NodeValue arg0, NodeValue arg1)
Detailed Description
Remove point from a linestring.
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0, NodeValue arg1)
References GeometryWrapper.asNodeValue(), GeometryWrapper.extract(), GeometryWrapper.getParsingGeometry(), and GeometryWrapper.getSRID().
Referenced by RemovePointTest.testRemovePoint().
{
                 try {
                         GeometryWrapper geom1 = GeometryWrapper.extract(arg0);
                         BigInteger zerobasedposition = arg1.getInteger();
                         if (geom1.getParsingGeometry() instanceof LineString) {
                                 Coordinate[] coords = geom1.getParsingGeometry().getCoordinates();
                                 Coordinate[] newcoords = coords;
                                 ArrayUtils.remove(newcoords, zerobasedposition.intValue());
                                 GeometryWrapper lineStringWrapper = GeometryWrapperFactory.createLineString(newcoords,
                                                 "<http://www.opengis.net/def/crs/EPSG/0/" + geom1.getSRID() + ">", WKTDatatype.URI);
                                 return lineStringWrapper.asNodeValue();
                         }
                         throw new ExprEvalException("First argument is not a LineString", null);
                 } catch (DatatypeFormatException ex) {
                         throw new ExprEvalException(ex.getMessage(), ex);
                 }
         }