jena-geo: IsClosed Class Reference
IsClosed Class Reference
Returns TRUE if the LINESTRING's start and end points are coincident.
Public Member Functions
NodeValue exec (NodeValue arg0)
Detailed Description
Returns TRUE if the LINESTRING's start and end points are coincident.
For Polyhedral surface is closed (volumetric).
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0)
References GeometryWrapper.extract(), and GeometryWrapper.getXYGeometry().
Referenced by IsClosedTest.testLineStringClosed(), IsRingTest.testLineStringIsNotRing(), IsRingTest.testLineStringIsRing(), IsClosedTest.testLineStringNotClosed(), IsClosedTest.testMultiLineStringNotClosed(), IsClosedTest.testmultiPointClosed(), and IsClosedTest.testpointClosed().
{
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(arg0);
             Geometry geom = geometry.getXYGeometry();
             if(geom instanceof Point)
                 return NodeValue.TRUE;
             if(geom instanceof MultiPoint) {
                 LineString line=(LineString) GeometryWrapperFactory.createLineString(((MultiPoint)geom).getCoordinates(),  "<http://www.opengis.net/def/crs/EPSG/0/" + geom.getSRID() + ">", WKTDatatype.URI).getXYGeometry();
                 boolean isClosed = line.isClosed();
                 return NodeValue.makeNodeBoolean(isClosed);
             }
             if (geom instanceof LineString) {
                 boolean isClosed = ((LineString) geom).isClosed();
                 return NodeValue.makeNodeBoolean(isClosed);
             }
             if (geom instanceof Polygon) {
                 return NodeValue.TRUE;
             }
             return NodeValue.FALSE;
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
     }