jena-geo: SharedPaths Class Reference
SharedPaths Class Reference
Returns a collection containing paths shared by the two input linestrings/multilinestrings.
Public Member Functions
NodeValue exec (NodeValue arg0, NodeValue arg1)
Detailed Description
Returns a collection containing paths shared by the two input linestrings/multilinestrings.
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0, NodeValue arg1)
References GeometryWrapper.extract(), GeometryWrapper.getGeometryDatatypeURI(), GeometryWrapper.getSrsInfo(), GeometryWrapper.getSrsURI(), GeometryWrapper.getXYGeometry(), and GeometryWrapper.transform().
Referenced by SharedPathsTest.testSharedPaths().
{
                 GeometryWrapper geom1 = GeometryWrapper.extract(arg0);
         GeometryWrapper geom2 = GeometryWrapper.extract(arg1);
         List<Geometry> intersections=new LinkedList<>();
         try {
                         GeometryWrapper transGeom2 = geom2.transform(geom1.getSrsInfo());
                         if((geom1.getXYGeometry().getGeometryType().equals("MultiLineString") || geom1.getXYGeometry().getGeometryType().equals("LineString"))
                                         && (transGeom2.getXYGeometry().getGeometryType().equals("MultiLineString") || transGeom2.getXYGeometry().getGeometryType().equals("LineString"))) {
                                 for(int i=0;i<geom1.getXYGeometry().getNumGeometries();i++) {
                                         for(int j=0;j<transGeom2.getXYGeometry().getNumGeometries();j++) {
                                                 if(geom1.getXYGeometry().intersects(transGeom2.getXYGeometry().getGeometryN(j))){
                                                         intersections.add(geom1.getXYGeometry().getGeometryN(i).intersection(transGeom2.getXYGeometry().getGeometryN(j)));
                                                 }
                                         }
                                 }
                                 return GeometryWrapperFactory.createGeometryCollection(intersections, geom1.getSrsURI(), geom1.getGeometryDatatypeURI()).asNodeValue();
                         }
                         throw new ExprEvalException("Given geometries are not LineString or MultiLineString");
                 } catch (MismatchedDimensionException | TransformException | FactoryException e) {
                         throw new ExprEvalException("Exception occured while transforming CRS");
                 }
         }