jena-geo: Zmflag Class Reference
Zmflag Class Reference
Returns ZM (dimension semantic) flag of the geometries as a small int.
Public Member Functions
NodeValue exec (NodeValue arg0)
Detailed Description
Returns ZM (dimension semantic) flag of the geometries as a small int.
Values are: 0=2d, 1=3dm, 2=3dz, 3=4d.
Member Function Documentation
exec()
NodeValue exec (NodeValue arg0)
References GeometryWrapper.extract(), Coordinate.getM(), GeometryWrapper.getXYGeometry(), and Coordinate.getZ().
{
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(arg0);
             Coordinate coord=geometry.getXYGeometry().getCoordinates()[0];
             if(Double.isNaN(coord.getM()) && Double.isNaN(coord.getZ())) {
                 return NodeValue.makeInteger(0);
             }else if(!Double.isNaN(coord.getM()) && Double.isNaN(coord.getZ())) {
                 return NodeValue.makeInteger(1);
             }else if(Double.isNaN(coord.getM()) && !Double.isNaN(coord.getZ())) {
                 return NodeValue.makeInteger(2);
             }else if(!Double.isNaN(coord.getM()) && !Double.isNaN(coord.getZ())) {
                 return NodeValue.makeInteger(3);
             }
             return NodeValue.nvNothing;
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
         }