jena-geo: LineLocatePoint Class Reference
LineLocatePoint Class Reference
Returns a float between 0 and 1 representing the location of the closest point on LineString to the given Point, as a fraction of total 2d line length.
Public Member Functions
NodeValue exec (NodeValue arg0, NodeValue arg1)
double calculateRelativeDistanceFromStart (Geometry geom, Integer index)
Detailed Description
Returns a float between 0 and 1 representing the location of the closest point on LineString to the given Point, as a fraction of total 2d line length.
Member Function Documentation
calculateRelativeDistanceFromStart()
double calculateRelativeDistanceFromStart (Geometry geom, Integer index)
References Coordinate.distance().
{
                 Double length=geom.getLength();
                 Double distanceaddition=0.;
                 int j=0;
                 Coordinate oldcoord=null;
                 for(Coordinate coord:geom.getCoordinates()) {
                         if(oldcoord!=null && j<index) {
                                 distanceaddition+=coord.distance(oldcoord);
                         }
                         oldcoord=coord;
                         j++;
                 }
                 return distanceaddition/length;
         }
exec()
NodeValue exec (NodeValue arg0, NodeValue arg1)
References GeometryWrapper.extract(), GeometryWrapper.getSrsInfo(), GeometryWrapper.getXYGeometry(), and GeometryWrapper.transform().
{
                 GeometryWrapper geom1 = GeometryWrapper.extract(arg0);
         GeometryWrapper geom2 = GeometryWrapper.extract(arg1);
         try {
                         GeometryWrapper transGeom2 = geom2.transform(geom1.getSrsInfo());
                         if(geom1.getXYGeometry().getGeometryType().equalsIgnoreCase("LineString") &&
                                         transGeom2.getXYGeometry().getGeometryType().equalsIgnoreCase("Point")) {
                                 LineString line=(LineString) geom1.getXYGeometry();
                                 Point point=(Point) transGeom2.getXYGeometry();
                                 //Double minDistance=Double.MAX_VALUE;
                                 throw new ExprEvalException("Not implemented yet");
                                 /*LengthToPoint ltop=new LengthToPoint(line, point.getCoordinate());
                                 ltop.
                                 return NodeValue.makeDouble(ltop.getLength()/line.getLength());
                                 /*Coordinate closestPoint=null;
                                 Integer index=-1;
                                 int j=0;
                                 for(Coordinate coord:line.getCoordinates()) {
                                         Double curdistance=coord.distance(point.getCoordinate());
                                         if(curdistance<minDistance) {
                                                 minDistance=curdistance;
                                                 closestPoint=coord;
                                                 index=j;
                                         }
                                         j++;
                                 }
                                 Double relDistance=calculateRelativeDistanceFromStart(line, index);
                                 return NodeValue.makeDouble(relDistance);*/
                         }
                         throw new ExprEvalException("Input geometries were not a LineString and a Point");
                 } catch (MismatchedDimensionException | TransformException | FactoryException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                         throw new ExprEvalException("An exception occured: "+e.getMessage());
                 }
         }