jena-geo: IsLocationOnEdge Class Reference
IsLocationOnEdge Class Reference
Checks if a point is on the edge of a polygon.
Public Member Functions
NodeValue exec (NodeValue v1, NodeValue v2)
Detailed Description
Checks if a point is on the edge of a polygon.
Member Function Documentation
exec()
NodeValue exec (NodeValue v1, NodeValue v2)
References GeometryWrapper.asNodeValue(), GeometryWrapper.extract(), GeometryWrapper.getParsingGeometry(), and GeometryWrapper.getSrsURI().
{
                 try {
             GeometryWrapper geometry = GeometryWrapper.extract(v1);
             Geometry geom = geometry.getParsingGeometry();
             if (geom instanceof Polygon) {
                 BigInteger ringN = v2.getInteger();
                 LineString result=((Polygon) geom).getInteriorRingN(ringN.intValue());
                 GeometryWrapper lineStringWrapper = GeometryWrapperFactory.createGeometry(result, geometry.getSrsURI(), WKTDatatype.URI);
                 return lineStringWrapper.asNodeValue();
             }
             return NodeValue.nvNothing;
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
         }