jena-geo: GeometricMedian Class Reference
GeometricMedian Class Reference
Returns the geometric median of a MultiPoint.
Public Member Functions
NodeValue exec (NodeValue arg0)
Coordinate getGeoMedian (Coordinate start, Coordinate[] points)
Package Attributes
double lower_limit = 0.01
Static Private Member Functions
static double distance (double x1, double y1, double x2, double y2)
Detailed Description
Returns the geometric median of a MultiPoint.
Member Function Documentation
distance()
static double distance (double x1, double y1, double x2, double y2) static private
Referenced by GeometricMedian.getGeoMedian().
{
         x1 -= x2;
         y1 -= y2;
         return Math.sqrt(x1 * x1 + y1 * y1);
     }
exec()
NodeValue exec (NodeValue arg0)
References GeometryWrapper.extract(), GeometricMedian.getGeoMedian(), GeometryWrapper.getGeometryDatatypeURI(), and GeometryWrapper.getXYGeometry().
{
         try {
             GeometryWrapper geometry = GeometryWrapper.extract(arg0);
             Geometry geom = geometry.getXYGeometry();
             Coordinate median=getGeoMedian(geom.getCentroid().getCoordinate(), geom.getCoordinates());
             return GeometryWrapperFactory.createPoint(median, geometry.getGeometryDatatypeURI()).asNodeValue();
         } catch (DatatypeFormatException ex) {
             throw new ExprEvalException(ex.getMessage(), ex);
         }
         }
getGeoMedian()
Coordinate getGeoMedian (Coordinate start, Coordinate [] points)
References GeometricMedian.distance(), Coordinate.x, and Coordinate.y.
Referenced by GeometricMedian.exec().
{
         double cx = 0;
         double cy = 0;
         double centroidx = start.x;
         double centroidy = start.y;
         do {
             double totalWeight = 0;
             for (int i = 0; i < points.length; i++) {
                 Coordinate pt = points[i];
                 double weight = 1 / distance(pt.x, pt.y, centroidx, centroidy);
                 cx += pt.x * weight;
                 cy += pt.y * weight;
                 totalWeight += weight;
             }
             cx /= totalWeight;
             cy /= totalWeight;
         } while (Math.abs(cx - centroidx) > 0.5
                 || Math.abs(cy - centroidy) > 0.5);// Probably this condition
                                                     // needs to change
         return new Coordinate(cx, cy);
     }
Member Data Documentation
lower_limit
double lower_limit = 0.01 package