jena-geo: MakePoint Class Reference
MakePoint Class Reference
Creates a 2D, 3DZ or 4D point geometry.
Public Member Functions
NodeValue exec (List< NodeValue > args)
void checkBuild (String uri, ExprList args)
Detailed Description
Creates a 2D, 3DZ or 4D point geometry.
Member Function Documentation
checkBuild()
void checkBuild (String uri, ExprList args)
{
         if (args.size() < 2 || args.size() > 4) {
             throw new QueryBuildException("Function '" + Lib.className(this) + "' takes two, three or four arguments");
         }
     }
exec()
NodeValue exec (List< NodeValue > args)
References GeometryWrapper.asNodeValue().
Referenced by MakePointTest.testMakePoint1(), and MakePointTest.testMakePointXYZ().
{
         Coordinate coord;
         switch (args.size()) {
             case 3:
                 coord = new Coordinate(args.get(0).getDouble(), args.get(1).getDouble(), args.get(2).getDouble());
                 break;
             case 4:
                 coord = new CoordinateXYZM(args.get(0).getDouble(), args.get(1).getDouble(), args.get(2).getDouble(), args.get(3).getDouble());
                 break;
             default:
                 coord = new CoordinateXY(args.get(0).getDouble(), args.get(1).getDouble());
         }
         GeometryWrapper pointWrapper = GeometryWrapperFactory.createPoint(coord, SRS_URI.DEFAULT_WKT_CRS84, WKTDatatype.URI);
         return pointWrapper.asNodeValue();
     }