jena-geo: LiteralUtils Class Reference
LiteralUtils Class Reference
Static Public Member Functions
static Wrapper rasterOrVector (NodeValue v)
static Double maxRasterValue (GridCoverage raster, Integer bandnum)
static Double arithmeticMeanRasterValue (GridCoverage raster, Integer bandnum)
static Double minRasterValue (GridCoverage raster, Integer bandnum)
static Boolean containsRasterValue (GridCoverage raster, Integer bandnum, Double value)
static Coordinate worldToRaster (GridCoverage raster, Double latitude, Double longitude) throws MismatchedDimensionException, TransformException
static Coordinate worldToRaster (CoverageWrapper wrapper, Double latitude, Double longitude) throws MismatchedDimensionException, TransformException
static GridCoverage cropRaster2 (GridCoverage raster, Double width, Double height, Double x, Double y) throws MismatchedDimensionException, TransformException
static NodeValue cropRaster (CoverageWrapper wrapper, Double width, Double height, Double x, Double y) throws MismatchedDimensionException, TransformException
static NodeValue createEmptyRaster (Double width, Double height, Double upperleftx, Double upperlefty, Double val)
static Geometry getCorrectVectorRepresentation (Wrapper wrapper)
static Geometry toGeometry (final Envelope2D envelope)
static Geometry toGeometry (final OctagonalEnvelope envelope)
static Geometry toGeometry (final Envelope envelope)
static Geometry toGeometry (final org.opengis.geometry.Envelope envelope)
static Geometry toGeometry (final Rectangle envelope)
static GeometryWrapper createGeometry (List< Coordinate > coordinates, String geomtype, GeometryWrapper geometry)
static GeometryWrapper createGeometry (Coordinate[] coordarray, String geomtype, GeometryWrapper geometry)
Member Function Documentation
arithmeticMeanRasterValue()
static Double arithmeticMeanRasterValue (GridCoverage raster, Integer bandnum) static
References GridCoverage.render().
Referenced by MedianIntersects.exec().
{
                 RenderedImage rendered=raster.render(null);
                 Double sum=0.,counter=0.;
         for(int i=0;i<rendered.getSampleModel().getWidth();i++) {
                 for(int j=0;j<rendered.getSampleModel().getHeight();j++) {
                         sum+=(double) rendered.getData().getSample(i, j, bandnum);
                         counter++;
                 }
         }
         System.out.println("MeanRasterVal: "+(sum/counter));
                 return (sum/counter);
         }
containsRasterValue()
static Boolean containsRasterValue (GridCoverage raster, Integer bandnum, Double value) static
References GridCoverage.render().
Referenced by ValueIntersects.exec().
{
                 RenderedImage rendered=raster.render(null);
                 for(int i=0;i<rendered.getSampleModel().getWidth();i++) {
                         for(int j=0;j<rendered.getSampleModel().getHeight();j++) {
                                 if(rendered.getData().getSample(i, j, bandnum)==value) {
                                         return true;
                                 }
                         }
                 }
                 return false;
         }
createEmptyRaster()
static NodeValue createEmptyRaster (Double width, Double height, Double upperleftx, Double upperlefty, Double val) static
References CoverageWrapper.createCoverage(), and HexWKBRastDatatype.URI.
Referenced by SmallerIntersects.exec(), and RasterIntersection.exec().
{
                 Double pixelsize;
                 WritableRaster raster;
                 if(width.intValue()<=0 || height.intValue()<=0) {
                         raster = RasterFactory.createBandedRaster(DataBuffer.TYPE_FLOAT, 2, 2, 1, null);
                 }else {
                         raster = RasterFactory.createBandedRaster(DataBuffer.TYPE_FLOAT, width.intValue(), height.intValue(), 1, null);
                 }
                 for (int y = 0; y < height; y++) {
                         for (int x = 0; x < width; x++) {
                                 raster.setSample(x, y, 0, val);
                         }
                 }
                 //CoordinateReferenceSystem crs = CommonCRS.WGS84.defaultGeographic();
                 CoordinateReferenceSystem crss=null;
                 Envelope2D envelope=null;
                 try {
                         crss = CRS.forCode("EPSG:4326");
                         envelope = new Envelope2D(crss, 0, 0, 30, 30);
                 } catch (FactoryException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                         envelope = new Envelope2D(CommonCRS.WGS84.defaultGeographic(), 0, 0, 30, 30);
                 }
         GridExtent extent=new GridExtent(raster.getWidth(), raster.getHeight());
         GridGeometry gridgeom=new GridGeometry(extent, PixelInCell.CELL_CENTER, null, crss);
         List<SampleDimension> dimensions=new LinkedList<SampleDimension>();
         DefaultNameFactory fac=new DefaultNameFactory();
         for(int i=0;i<raster.getNumBands();i++) {
                 dimensions.add(new SampleDimension(fac.createGenericName(null,  "Dimension "+i),0.,new LinkedList<Category>()));
         }
         BufferedGridCoverage coverage=new BufferedGridCoverage(
                         gridgeom, dimensions, raster.getDataBuffer());
                 return CoverageWrapper.createCoverage(coverage, "EPSG:4326", HexWKBRastDatatype.URI.toString()).asNodeValue();
         }
createGeometry() [1/2]
static GeometryWrapper createGeometry (List< Coordinate > coordinates, String geomtype, GeometryWrapper geometry) static
References GeometryWrapper.getGeometryDatatypeURI(), and GeometryWrapper.getSrsURI().
Referenced by LiteralUtils.createGeometry(), EnsureClosed.exec(), ShiftLongitude.exec(), AddZ.exec(), MultiplyZ.exec(), AddT.exec(), PartOfGeometryBefore.exec(), PartOfGeometryAfter.exec(), RemovePoints.exec(), Force2D.exec(), Force3D.exec(), FilterByM.exec(), Force4D.exec(), Force3DM.exec(), SwapOrdinates.exec(), and FlipCoordinates.exec().
{
                         switch(geomtype) {
                         case "Point":
                                 return GeometryWrapperFactory.createPoint(coordinates.get(0), geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "MultiPoint":
                                 return GeometryWrapperFactory.createMultiPoint(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "LineString":
                                 return GeometryWrapperFactory.createLineString(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "Polygon":
                                 return GeometryWrapperFactory.createPolygon(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "MultiLineString":
                                 List<LineString> list=new LinkedList<LineString>();
                                 list.add((LineString)GeometryWrapperFactory.createLineString(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI()).getXYGeometry());
                                 return GeometryWrapperFactory.createMultiLineString(list, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "MultiPolygon":
                                 List<Polygon> plist=new LinkedList<Polygon>();
                                 plist.add((Polygon)GeometryWrapperFactory.createPolygon(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI()).getXYGeometry());
                                 return GeometryWrapperFactory.createMultiPolygon(plist, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         default:
                                 return null;
                         }
                 }
createGeometry() [2/2]
static GeometryWrapper createGeometry (Coordinate [] coordarray, String geomtype, GeometryWrapper geometry) static
References LiteralUtils.createGeometry().
{
                         return createGeometry(Arrays.asList(coordarray), geomtype, geometry);
                 }
cropRaster()
static NodeValue cropRaster (CoverageWrapper wrapper, Double width, Double height, Double x, Double y) throws MismatchedDimensionException, TransformException static
References CoverageWrapper.createCoverage(), GridCoverage.getCoordinateReferenceSystem(), GridCoverage.getGridGeometry(), GridCoverage.getSampleDimensions(), Coordinate.getX(), Coordinate.getY(), GridCoverage.render(), and LiteralUtils.worldToRaster().
Referenced by RasterIntersection.exec().
{
                  GridCoverage raster=wrapper.getXYGeometry();
                  Coordinate coord=worldToRaster(wrapper, x, y);
                  Coordinate coord2=worldToRaster(wrapper, x+width, y+height);
                  Double xx=coord.getX();
                  Double yy=coord.getY();
                  xx=Double.valueOf(xx.intValue())-1;
                  yy=Double.valueOf(yy.intValue())-1;
                  Double widthh=coord2.getX()-x;
                  Double heightt=coord2.getY()-y;
                  ParameterBlock pbSubtracted = new ParameterBlock();
              pbSubtracted.addSource(raster.render(null));
              pbSubtracted.add(xx.floatValue());
              pbSubtracted.add(yy.floatValue());
              pbSubtracted.add(widthh.floatValue());
              pbSubtracted.add(heightt.floatValue());
              System.out.println(raster.render(null).getWidth()+" "+raster.render(null).getHeight());
              System.out.println(xx+" "+yy+" "+widthh+" "+heightt);
              RenderedOp subtractedImage = JAI.create("crop",pbSubtracted);
              final SampleDimension sd =raster.getSampleDimensions().get(0);
                         List<SampleDimension>sds=new LinkedList<SampleDimension>();
                         sds.add(sd);
                 GridExtent extent=new GridExtent(subtractedImage.getWidth(), subtractedImage.getHeight());
                 GridGeometry gridgeom=new GridGeometry(extent, PixelInCell.CELL_CENTER, raster.getGridGeometry().getGridToCRS(PixelInCell.CELL_CENTER), raster.getCoordinateReferenceSystem());
                 List<SampleDimension> dimensions=new LinkedList<SampleDimension>();
                 DefaultNameFactory fac=new DefaultNameFactory();
                 for(int i=0;i<subtractedImage.getNumBands();i++) {
                         dimensions.add(new SampleDimension(fac.createGenericName(null,  "Dimension "+i),0.,new LinkedList<Category>()));
                 }
                 BufferedGridCoverage coverage=new BufferedGridCoverage(
                                 gridgeom, dimensions, subtractedImage.getData().getDataBuffer());
                         return CoverageWrapper.createCoverage((GridCoverage)coverage, wrapper.getSrsURI(), wrapper.getRasterDatatypeURI())
                                         .asNodeValue();
         }
cropRaster2()
static GridCoverage cropRaster2 (GridCoverage raster, Double width, Double height, Double x, Double y) throws MismatchedDimensionException, TransformException static
References Coordinate.getX(), Coordinate.getY(), and LiteralUtils.worldToRaster().
Referenced by GreaterIntersects.exec(), ValueIntersects.exec(), SmallerIntersects.exec(), and MedianIntersects.exec().
{
                  Coordinate coord=worldToRaster(raster, x, y);
                  Coordinate coord2=worldToRaster(raster, x+width, y+height);
                  Double xx=coord.getX();
                  Double yy=coord.getY();
                  xx=Double.valueOf(xx.intValue())-1;
                  yy=Double.valueOf(yy.intValue())-1;
                  Double widthh=coord2.getX()-x;
                  Double heightt=coord2.getY()-y;
                  if(widthh==0)
                          widthh=1.;
                  if(heightt==0)
                          heightt=1.;
              RenderedImage rendered = raster.render(null);
                  ParameterBlock pbSubtracted = new ParameterBlock();
              pbSubtracted.addSource(rendered);
              pbSubtracted.add(xx.floatValue());
              pbSubtracted.add(yy.floatValue());
              pbSubtracted.add(widthh.floatValue());
              pbSubtracted.add(heightt.floatValue());
              System.out.println(rendered.getMinX()+" "+rendered.getMinY());
              System.out.println(rendered.getWidth()+" "+rendered.getHeight());
              System.out.println(xx+" "+yy+" "+widthh+" "+heightt);
              RenderedOp subtractedImage = JAI.create("crop",pbSubtracted);
                         final SampleDimension sd =raster.getSampleDimensions().get(0);
                         List<SampleDimension>sds=new LinkedList<SampleDimension>();
                         sds.add(sd);
                 GridExtent extent=new GridExtent(subtractedImage.getWidth(), subtractedImage.getHeight());
                 GridGeometry gridgeom=new GridGeometry(extent, PixelInCell.CELL_CENTER, raster.getGridGeometry().getGridToCRS(PixelInCell.CELL_CENTER), raster.getCoordinateReferenceSystem());
                 List<SampleDimension> dimensions=new LinkedList<SampleDimension>();
                 DefaultNameFactory fac=new DefaultNameFactory();
                 for(int i=0;i<subtractedImage.getNumBands();i++) {
                         dimensions.add(new SampleDimension(fac.createGenericName(null,  "Dimension "+i),0.,new LinkedList<Category>()));
                 }
                 BufferedGridCoverage coverage=new BufferedGridCoverage(
                                 gridgeom, dimensions, subtractedImage.getData().getDataBuffer());
                         return coverage;
         }
getCorrectVectorRepresentation()
static Geometry getCorrectVectorRepresentation (Wrapper wrapper) static
References LiteralUtils.toGeometry().
{
                 if(wrapper instanceof GeometryWrapper) {
                         return ((GeometryWrapper) wrapper).getXYGeometry();
                 }else {
                         return toGeometry(((CoverageWrapper) wrapper).getParsingGeometry().getGridGeometry().getEnvelope());
                 }
         }
maxRasterValue()
static Double maxRasterValue (GridCoverage raster, Integer bandnum) static
References GridCoverage.render().
Referenced by SmallerIntersects.exec().
{
                 RenderedImage rendered=raster.render(null);
                 Double maxVal=Double.MIN_VALUE;
         for(int i=0;i<rendered.getSampleModel().getWidth();i++) {
                 for(int j=0;j<rendered.getSampleModel().getHeight();j++) {
                         if(rendered.getData().getSample(i, j, bandnum)>maxVal) {
                                 maxVal=(double) rendered.getData().getSample(i, j, bandnum);
                         }
                 }
         }
         System.out.println("MaxRasterVal: "+maxVal);
         return maxVal;
         }
minRasterValue()
static Double minRasterValue (GridCoverage raster, Integer bandnum) static
References GridCoverage.render().
Referenced by GreaterIntersects.exec().
{
                 RenderedImage rendered=raster.render(null);
                 Double maxVal=Double.MAX_VALUE;
                 for(int i=0;i<rendered.getSampleModel().getWidth();i++) {
                         for(int j=0;j<rendered.getSampleModel().getHeight();j++) {
                                 if(rendered.getData().getSample(i, j, bandnum)<maxVal) {
                                         maxVal=(double) rendered.getData().getSample(i, j, bandnum);
                                 }
                         }
                 }
         System.out.println("MinRasterVal: "+maxVal);
                 return maxVal;
         }
rasterOrVector()
static Wrapper rasterOrVector (NodeValue v) static
References CoverageWrapper.extract(), GeometryWrapper.extract(), RasterDataType.get(), and GeometryDatatype.get().
Referenced by EqualType.exec(), IsGrayscale.exec(), IsIndexed.exec(), IsTiled.exec(), IsTranslucent.exec(), RasterEquals.exec(), EqualSRS.exec(), CentroidDistance.exec(), SRIDGetAxis1Name.exec(), SRIDGetAxis1Orientation.exec(), SRIDGetAxis2Name.exec(), SRIDGetAxis2Orientation.exec(), SRIDHasFlippedAxis.exec(), CompactnessRatio.exec(), ValueIntersects.exec(), DWithin3D.exec(), GreaterIntersects.exec(), MedianIntersects.exec(), MinimumDiameter.exec(), SmallerIntersects.exec(), EqualNorm.exec(), AreaSimilarity.exec(), BBOXFPIntersects.exec(), DFullyWithin.exec(), Crosses.exec(), Equals.exec(), EqualTopo.exec(), IntersectionPercentage.exec(), IsCollection.exec(), MinimumBoundingCircleCenter.exec(), MinimumDiameterLine.exec(), MinimumRectangle.exec(), RasterIntersection.exec(), Intersection.exec(), Difference.exec(), BBOXContains.exec(), Distance.exec(), MinimumBoundingRadius.exec(), SymDifference.exec(), BBOXDistance.exec(), MinimumClearance.exec(), BBOXRightOf.exec(), BBOXOverlapsRight.exec(), BBOXOverlapsBelow.exec(), BBOXIntersects.exec(), BBOXIsContainedBy.exec(), BBOXAbove.exec(), BBOXLeftOf.exec(), BBOXOverlapsAbove.exec(), BBOXBelow.exec(), BBOXOverlapsLeft.exec(), BBOXEquals.exec(), Union.exec(), MinimumClearanceLine.exec(), Boundary.exec(), BoundingDiagonal.exec(), ContainsProperly.exec(), IsEmpty.exec(), SRID.exec(), Intersects.exec(), Overlaps.exec(), Touches.exec(), GeometryType.exec(), DistanceSphere.exec(), DWithin.exec(), CoveredBy.exec(), Disjoint.exec(), Covers.exec(), Contains.exec(), Area.exec(), Within.exec(), MinimumBoundingCircle.exec(), and Centroid.exec().
{
                 GeometryDatatype datatype=null;
                 try {
                         datatype=GeometryDatatype.get(v.getDatatypeURI());
                 }catch(Exception e) {
                         datatype=null;
                 }
                         if(datatype==null) {
                                 RasterDataType rdatatype=RasterDataType.get(v.getDatatypeURI());
                                 if(rdatatype==null) {
                                         throw new AssertionError("No valid raster or vector geometry definition given!");
                                 }else {
                                         return CoverageWrapper.extract(v);
                                 }
                         }else{
                                 return  GeometryWrapper.extract(v);
                         }
         }
toGeometry() [1/5]
static Geometry toGeometry (final Envelope2D envelope) static
Referenced by EqualSRS.exec(), OctogonalEnvelope.exec(), MedianIntersects.exec(), MinimumDiameter.exec(), CentroidDistance.exec(), SmallerIntersects.exec(), ValueIntersects.exec(), DWithin3D.exec(), GreaterIntersects.exec(), AreaSimilarity.exec(), Crosses.exec(), BBOXFPIntersects.exec(), EqualNorm.exec(), IntersectionPercentage.exec(), MinimumBoundingCircleCenter.exec(), MinimumDiameterLine.exec(), MinimumRectangle.exec(), RasterIntersection.exec(), Equals.exec(), EqualTopo.exec(), Intersection.exec(), Difference.exec(), BBOXDistance.exec(), MinimumBoundingRadius.exec(), MinimumClearance.exec(), SymDifference.exec(), BBOXContains.exec(), Distance.exec(), BBOXIsContainedBy.exec(), BBOXOverlapsAbove.exec(), BBOXOverlapsLeft.exec(), BBOXEquals.exec(), BBOXOverlapsBelow.exec(), BBOXRightOf.exec(), BBOXIntersects.exec(), BBOXOverlapsRight.exec(), MinimumClearanceLine.exec(), Union.exec(), Boundary.exec(), ContainsProperly.exec(), Intersects.exec(), Envelope.exec(), Overlaps.exec(), Touches.exec(), CoveredBy.exec(), Disjoint.exec(), Covers.exec(), Contains.exec(), Area.exec(), Within.exec(), MinimumBoundingCircle.exec(), Centroid.exec(), and LiteralUtils.getCorrectVectorRepresentation().
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMinY())
                 }), null);
     }
toGeometry() [2/5]
static Geometry toGeometry (final OctagonalEnvelope envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMinY())
                 }), null);
     }
toGeometry() [3/5]
static Geometry toGeometry (final Envelope envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMinY())
                 }), null);
     }
toGeometry() [4/5]
static Geometry toGeometry (final org.opengis.geometry.Envelope envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinimum(0), envelope.getMinimum(1)),
                     new Coordinate(envelope.getMaximum(0), envelope.getMinimum(1)),
                     new Coordinate(envelope.getMaximum(0), envelope.getMaximum(1)),
                     new Coordinate(envelope.getMinimum(0), envelope.getMaximum(1)),
                     new Coordinate(envelope.getMinimum(0), envelope.getMinimum(1))
                 }), null);
     }
toGeometry() [5/5]
static Geometry toGeometry (final Rectangle envelope) static
{
                 GeometryFactory gf = new GeometryFactory();
                 return gf.createPolygon(gf.createLinearRing(
                         new Coordinate[]{
                             new Coordinate(envelope.getMinX(), envelope.getMinY()),
                             new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                             new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                             new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                             new Coordinate(envelope.getMinX(), envelope.getMinY())
                         }), null);
             }
worldToRaster() [1/2]
static Coordinate worldToRaster (GridCoverage raster, Double latitude, Double longitude) throws MismatchedDimensionException, TransformException static
Referenced by LiteralUtils.cropRaster(), and LiteralUtils.cropRaster2().
{
          GridGeometry gg2D = raster.getGridGeometry();
          MathTransform gridToCRS = gg2D.getGridToCRS(PixelInCell.CELL_CENTER);
          MathTransform crsToGrid = gridToCRS.inverse();
          DirectPosition realPos=new DirectPosition2D(latitude, longitude);
          DirectPosition gridPos = new DirectPosition2D();
          DirectPosition res=crsToGrid.transform(realPos, gridPos);
          Coordinate coord=new Coordinate(res.getCoordinate()[0],res.getCoordinate()[1]);
          return coord;
         }
worldToRaster() [2/2]
static Coordinate worldToRaster (CoverageWrapper wrapper, Double latitude, Double longitude) throws MismatchedDimensionException, TransformException static
References GridCoverage.getGridGeometry().
{
          GridCoverage raster=wrapper.getXYGeometry();
          GridGeometry gg2D = raster.getGridGeometry();
          MathTransform gridToCRS = gg2D.getGridToCRS(PixelInCell.CELL_CENTER);
          MathTransform crsToGrid = gridToCRS.inverse();
          DirectPosition realPos=new DirectPosition2D(latitude, longitude);
          DirectPosition gridPos = new DirectPosition2D();
          DirectPosition res=crsToGrid.transform(realPos, gridPos);
          Coordinate coord=new Coordinate(res.getCoordinate()[0],res.getCoordinate()[1]);
          return coord;
         }