jena-geo: RasterToWorldCoord Class Reference
RasterToWorldCoord Class Reference
Returns the raster's upper left corner as geometric X and Y (longitude and latitude) given a column and row.
Public Member Functions
NodeValue exec (NodeValue v, NodeValue v1, NodeValue v2)
Detailed Description
Returns the raster's upper left corner as geometric X and Y (longitude and latitude) given a column and row.
Column and row starts at 1.
Member Function Documentation
exec()
NodeValue exec (NodeValue v, NodeValue v1, NodeValue v2)
References GeometryWrapper.asNodeValue(), CoverageWrapper.extract(), GridCoverage.getGridGeometry(), CoverageWrapper.getRasterDatatypeURI(), CoverageWrapper.getSrsURI(), and CoverageWrapper.getXYGeometry().
Referenced by RasterToWorldCoordTest.testRasterToWorldCoord().
{
                 CoverageWrapper wrapper=CoverageWrapper.extract(v);
                 GridCoverage raster=wrapper.getXYGeometry();
                 Integer column = v1.getInteger().intValue();
         Integer row = v2.getInteger().intValue();
         try {
                  GridGeometry gg2D = raster.getGridGeometry();
              MathTransform gridToCRS = gg2D.getGridToCRS(PixelInCell.CELL_CENTER);
              DirectPosition realPos=new DirectPosition2D(column, row);
              DirectPosition gridPos = new DirectPosition2D();
              DirectPosition res=gridToCRS.transform(realPos, gridPos);
              Coordinate coord=new Coordinate(res.getCoordinate()[0],res.getCoordinate()[1]);
              GeometryWrapper pointWrapper = GeometryWrapperFactory.createPoint(coord, wrapper.getSrsURI(), wrapper.getRasterDatatypeURI());
              return pointWrapper.asNodeValue();
         } catch (TransformException e) {
             return NodeValue.nvNothing;
         }
         }