jena-geo: Add Class Reference
Add Class Reference
Public Member Functions
NodeValue exec (NodeValue v1, NodeValue v2)
Member Function Documentation
exec()
NodeValue exec (NodeValue v1, NodeValue v2)
References CoverageWrapper.createCoverage(), CoverageWrapper.extract(), CoverageWrapper.getRasterDatatypeURI(), CoverageWrapper.getSrsURI(), and CoverageWrapper.getXYGeometry().
Referenced by AddTest.testAdd().
{
                 CoverageWrapper wrapper = CoverageWrapper.extract(v1);
                 GridCoverage2D raster = wrapper.getXYGeometry();
                 CoverageWrapper wrapper2 = CoverageWrapper.extract(v2);
                 GridCoverage2D raster2 = wrapper2.getXYGeometry();
                 ParameterBlock pbSubtracted = new ParameterBlock();
                 pbSubtracted.addSource(raster.getRenderedImage());
                 pbSubtracted.addSource(raster2.getRenderedImage());
                 RenderedOp subtractedImage = JAI.create("add", pbSubtracted);
                 /* final GridCoverageBuilder builder = new GridCoverageBuilder();
                 builder.setName("SampleCoverage.SST");
                 builder.setEnvelope(raster.getEnvelope());
                 builder.setCoordinateReferenceSystem(raster.getCoordinateReferenceSystem());
                 builder.variable(0).setSampleDimension(dim); getSampleDimension().
                 builder.variable(0).setName(raster.getSampleDimensions()[rd1].getDescription() + "+"
                                         + raster2.getSampleDimensions()[rd2].getDescription());
                 builder.variable(0).setSampleRange(30, 220);
                 builder.variable(0).setLinearTransform(0.1, 10);
                 builder.variable(0).addNodataValue("Missing values", 255, Color.GRAY);
                 builder.setRenderedImage(subtractedImage);
                 GridCoverage2D cov=(GridCoverage2D) builder.build();
                 //builder.setValues(SampleCoverage.SST.raster());
                 coverage = builder.getGridCoverage2D();
                 /*
                  * final GridGeometry grid = new
                  * GridGeometry(raster.getGridGeometry().getExtent(), PixelInCell.CELL_CENTER,
                  * MathTransforms.identity(2),
                  * raster.getGridGeometry().getCoordinateReferenceSystem());
                  *
                  * final MathTransform1D toUnits = (MathTransform1D) MathTransforms.linear(0.5,
                  * 100);
                  */
                 GridCoverageBuilder builder=new GridCoverageBuilder();
                 builder.setGridGeometry(raster.getGridGeometry());
                 builder.setNumBands(raster.getNumSampleDimensions());
                 builder.setExtent(raster.getGridGeometry().getExtent());
                 builder.setRenderedImage(subtractedImage);
                 /*final SampleDimension sd = new SampleDimension.Builder().setName("t")
                                 .addQuantitative(
                                                 (raster.getSampleDimensions().get(rd1).getName() + "+"
                                                                 + raster2.getSampleDimensions().get(rd2).getName()).toString(),
                                                 raster.getSampleDimensions().get(0).getMeasurementRange().get(),
                                                 raster.getSampleDimensions().get(0).getTransferFunction().get(),
                                                 raster.getSampleDimensions().get(0).getUnits().get())
                                 .build();
                 List<SampleDimension>sds=new LinkedList<SampleDimension>();
                 sds.add(sd);
                 /*
                  * Create the grid coverage, gets its image and set values directly as short
                  * integers.
                 BufferedGridCoverage coverage = new BufferedGridCoverage(raster2.getGridGeometry(),
                                 sds, DataBuffer.TYPE_SHORT);
                 WritableRaster rasterr = ((BufferedImage) coverage.render(null)).getRaster();
                 rasterr.setRect(subtractedImage.getSourceImage(0).getData());
                 return CoverageWrapper.createCoverage(coverage, wrapper.getSrsURI(), wrapper.getRasterDatatypeURI())
                                 .asNodeValue();
                 } catch (CannotEvaluateException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                         return null;
                 }*/
                 GridCoverage cov=builder.build();
                 return CoverageWrapper.createCoverage((GridCoverage2D)cov, wrapper.getSrsURI(), wrapper.getRasterDatatypeURI())
                                 .asNodeValue();
         }