jena-geo: Geobuf.Data.FeatureCollection.Builder Class Reference
Geobuf.Data.FeatureCollection.Builder Class Reference
Protobuf type.
Public Member Functions
Builder clear ()
Builder clone ()
Geobuf.Data.FeatureCollection getDefaultInstanceForType ()
Geobuf.Data.FeatureCollection build ()
Geobuf.Data.FeatureCollection buildPartial ()
Builder mergeFrom (Geobuf.Data.FeatureCollection other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
java.util.List< Geobuf.Data.Feature > getFeaturesList ()
repeated .Data.Feature features = 1;
int getFeaturesCount ()
repeated .Data.Feature features = 1;
Geobuf.Data.Feature getFeatures (int index)
repeated .Data.Feature features = 1;
Builder setFeatures (int index, Geobuf.Data.Feature value)
repeated .Data.Feature features = 1;
Builder setFeatures (int index, Geobuf.Data.Feature.Builder builderForValue)
repeated .Data.Feature features = 1;
Builder addFeatures (Geobuf.Data.Feature value)
repeated .Data.Feature features = 1;
Builder addFeatures (int index, Geobuf.Data.Feature value)
repeated .Data.Feature features = 1;
Builder addFeatures (Geobuf.Data.Feature.Builder builderForValue)
repeated .Data.Feature features = 1;
Builder addFeatures (int index, Geobuf.Data.Feature.Builder builderForValue)
repeated .Data.Feature features = 1;
Builder addAllFeatures (java.lang.Iterable<? extends Geobuf.Data.Feature > values)
repeated .Data.Feature features = 1;
Builder clearFeatures ()
repeated .Data.Feature features = 1;
Builder removeFeatures (int index)
repeated .Data.Feature features = 1;
java.util.List< Geobuf.Data.Value > getValuesList ()
repeated .Data.Value values = 13;
int getValuesCount ()
repeated .Data.Value values = 13;
Geobuf.Data.Value getValues (int index)
repeated .Data.Value values = 13;
Builder setValues (int index, Geobuf.Data.Value value)
repeated .Data.Value values = 13;
Builder setValues (int index, Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
Builder addValues (Geobuf.Data.Value value)
repeated .Data.Value values = 13;
Builder addValues (int index, Geobuf.Data.Value value)
repeated .Data.Value values = 13;
Builder addValues (Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
Builder addValues (int index, Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
Builder addAllValues (java.lang.Iterable<? extends Geobuf.Data.Value > values)
repeated .Data.Value values = 13;
Builder clearValues ()
repeated .Data.Value values = 13;
Builder removeValues (int index)
repeated .Data.Value values = 13;
java.util.List< java.lang.Integer > getCustomPropertiesList ()
repeated uint32 custom_properties = 15 [packed = true];
int getCustomPropertiesCount ()
repeated uint32 custom_properties = 15 [packed = true];
int getCustomProperties (int index)
repeated uint32 custom_properties = 15 [packed = true];
Builder setCustomProperties (int index, int value)
repeated uint32 custom_properties = 15 [packed = true];
Builder addCustomProperties (int value)
repeated uint32 custom_properties = 15 [packed = true];
Builder addAllCustomProperties (java.lang.Iterable<? extends java.lang.Integer > values)
repeated uint32 custom_properties = 15 [packed = true];
Builder clearCustomProperties ()
repeated uint32 custom_properties = 15 [packed = true];
Private Member Functions
Builder ()
void maybeForceBuilderInitialization ()
void ensureFeaturesIsMutable ()
void ensureValuesIsMutable ()
void ensureCustomPropertiesIsMutable ()
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
java.util.List< Geobuf.Data.Feature > features_
java.util.List< Geobuf.Data.Value > values_
java.util.List< java.lang.Integer > customProperties_ = java.util.Collections.emptyList()
Detailed Description
Protobuf type.
Data.FeatureCollection
Constructor & Destructor Documentation
Builder()
Builder () private
{
           maybeForceBuilderInitialization();
         }
Member Function Documentation
addAllCustomProperties()
Builder addAllCustomProperties (java.lang.Iterable<? extends java.lang.Integer > values)
repeated uint32 custom_properties = 15 [packed = true];
Referenced by GeobufEncoder.makeFeatureCollection().
{
           ensureCustomPropertiesIsMutable();
           com.google.protobuf.AbstractMessageLite.Builder.addAll(
               values, customProperties_);
           return this;
         }
addAllFeatures()
Builder addAllFeatures (java.lang.Iterable<? extends Geobuf.Data.Feature > values)
repeated .Data.Feature features = 1;
{
           ensureFeaturesIsMutable();
           com.google.protobuf.AbstractMessageLite.Builder.addAll(
               values, features_);
           return this;
         }
addAllValues()
Builder addAllValues (java.lang.Iterable<? extends Geobuf.Data.Value > values)
repeated .Data.Value values = 13;
Referenced by GeobufEncoder.makeFeatureCollection().
{
           ensureValuesIsMutable();
           com.google.protobuf.AbstractMessageLite.Builder.addAll(
               values, values_);
           return this;
         }
addCustomProperties()
Builder addCustomProperties (int value)
repeated uint32 custom_properties = 15 [packed = true];
{
           ensureCustomPropertiesIsMutable();
           customProperties_.add(value);
           return this;
         }
addFeatures() [1/4]
Builder addFeatures (Geobuf.Data.Feature value)
repeated .Data.Feature features = 1;
{
           if (value == null) {
             throw new NullPointerException();
           }
           ensureFeaturesIsMutable();
           features_.add(value);
           return this;
         }
addFeatures() [2/4]
Builder addFeatures (int index, Geobuf.Data.Feature value)
repeated .Data.Feature features = 1;
{
           if (value == null) {
             throw new NullPointerException();
           }
           ensureFeaturesIsMutable();
           features_.add(index, value);
           return this;
         }
addFeatures() [3/4]
Builder addFeatures (Geobuf.Data.Feature.Builder builderForValue)
repeated .Data.Feature features = 1;
{
           ensureFeaturesIsMutable();
           features_.add(builderForValue.build());
           return this;
         }
addFeatures() [4/4]
Builder addFeatures (int index, Geobuf.Data.Feature.Builder builderForValue)
repeated .Data.Feature features = 1;
{
           ensureFeaturesIsMutable();
           features_.add(index, builderForValue.build());
           return this;
         }
addValues() [1/4]
Builder addValues (Geobuf.Data.Value value)
repeated .Data.Value values = 13;
{
           if (value == null) {
             throw new NullPointerException();
           }
           ensureValuesIsMutable();
           values_.add(value);
           return this;
         }
addValues() [2/4]
Builder addValues (int index, Geobuf.Data.Value value)
repeated .Data.Value values = 13;
{
           if (value == null) {
             throw new NullPointerException();
           }
           ensureValuesIsMutable();
           values_.add(index, value);
           return this;
         }
addValues() [3/4]
Builder addValues (Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
{
           ensureValuesIsMutable();
           values_.add(builderForValue.build());
           return this;
         }
addValues() [4/4]
Builder addValues (int index, Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
{
           ensureValuesIsMutable();
           values_.add(index, builderForValue.build());
           return this;
         }
build()
Geobuf.Data.FeatureCollection build ()
Referenced by GeobufEncoder.makeFeatureCollection().
{
           Geobuf.Data.FeatureCollection result = buildPartial();
           if (!result.isInitialized()) {
             throw newUninitializedMessageException(result);
           }
           return result;
         }
buildPartial()
Geobuf.Data.FeatureCollection buildPartial ()
References Geobuf.Data.FeatureCollection.features_.
Referenced by Geobuf.Data.Data(), and Geobuf.Data.Builder.mergeFeatureCollection().
{
           Geobuf.Data.FeatureCollection result = new Geobuf.Data.FeatureCollection(this);
           int from_bitField0_ = bitField0_;
           if (((bitField0_ & 0x00000001) == 0x00000001)) {
             features_ = java.util.Collections.unmodifiableList(features_);
             bitField0_ = (bitField0_ & ~0x00000001);
           }
           result.features_ = features_;
           if (((bitField0_ & 0x00000002) == 0x00000002)) {
             values_ = java.util.Collections.unmodifiableList(values_);
             bitField0_ = (bitField0_ & ~0x00000002);
           }
           result.values_ = values_;
           if (((bitField0_ & 0x00000004) == 0x00000004)) {
             customProperties_ = java.util.Collections.unmodifiableList(customProperties_);
             bitField0_ = (bitField0_ & ~0x00000004);
           }
           result.customProperties_ = customProperties_;
           return result;
         }
clear()
Builder clear ()
References Geobuf.Data.FeatureCollection.Builder.clear().
Referenced by Geobuf.Data.FeatureCollection.Builder.clear().
{
           super.clear();
           features_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000001);
           values_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000002);
           customProperties_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000004);
           return this;
         }
clearCustomProperties()
Builder clearCustomProperties ()
repeated uint32 custom_properties = 15 [packed = true];
References Geobuf.Data.FeatureCollection.initFields().
{
           customProperties_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000004);
           return this;
         }
clearFeatures()
Builder clearFeatures ()
repeated .Data.Feature features = 1;
{
           features_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000001);
           return this;
         }
clearValues()
Builder clearValues ()
repeated .Data.Value values = 13;
{
           values_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000002);
           return this;
         }
clone()
Builder clone ()
References Geobuf.Data.FeatureCollection.Builder.mergeFrom().
{
           return create().mergeFrom(buildPartial());
         }
create()
static Builder create () static private
Referenced by Geobuf.Data.FeatureCollection.newBuilder().
{
           return new Builder();
         }
ensureCustomPropertiesIsMutable()
void ensureCustomPropertiesIsMutable () private
{
           if (!((bitField0_ & 0x00000004) == 0x00000004)) {
             customProperties_ = new java.util.ArrayList<java.lang.Integer>(customProperties_);
             bitField0_ |= 0x00000004;
            }
         }
ensureFeaturesIsMutable()
void ensureFeaturesIsMutable () private
{
           if (!((bitField0_ & 0x00000001) == 0x00000001)) {
             features_ = new java.util.ArrayList<Geobuf.Data.Feature>(features_);
             bitField0_ |= 0x00000001;
            }
         }
ensureValuesIsMutable()
void ensureValuesIsMutable () private
{
           if (!((bitField0_ & 0x00000002) == 0x00000002)) {
             values_ = new java.util.ArrayList<Geobuf.Data.Value>(values_);
             bitField0_ |= 0x00000002;
            }
         }
getCustomProperties()
int getCustomProperties (int index)
repeated uint32 custom_properties = 15 [packed = true];
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
           return customProperties_.get(index);
         }
getCustomPropertiesCount()
int getCustomPropertiesCount ()
repeated uint32 custom_properties = 15 [packed = true];
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
           return customProperties_.size();
         }
getCustomPropertiesList()
java.util.List<java.lang.Integer> getCustomPropertiesList ()
repeated uint32 custom_properties = 15 [packed = true];
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
           return java.util.Collections.unmodifiableList(customProperties_);
         }
getDefaultInstanceForType()
Geobuf.Data.FeatureCollection getDefaultInstanceForType ()
References Geobuf.Data.FeatureCollection.getDefaultInstance().
{
           return Geobuf.Data.FeatureCollection.getDefaultInstance();
         }
getFeatures()
Geobuf.Data.Feature getFeatures (int index)
repeated .Data.Feature features = 1;
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
           return features_.get(index);
         }
getFeaturesCount()
int getFeaturesCount ()
repeated .Data.Feature features = 1;
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
           return features_.size();
         }
getFeaturesList()
java.util.List<Geobuf.Data.Feature> getFeaturesList ()
repeated .Data.Feature features = 1;
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
           return java.util.Collections.unmodifiableList(features_);
         }
getValues()
Geobuf.Data.Value getValues (int index)
repeated .Data.Value values = 13;
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
           return values_.get(index);
         }
getValuesCount()
int getValuesCount ()
repeated .Data.Value values = 13;
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
           return values_.size();
         }
getValuesList()
java.util.List<Geobuf.Data.Value> getValuesList ()
repeated .Data.Value values = 13;
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
           return java.util.Collections.unmodifiableList(values_);
         }
isInitialized()
final boolean isInitialized ()
{
           for (int i = 0; i < getFeaturesCount(); i++) {
             if (!getFeatures(i).isInitialized()) {
               return false;
             }
           }
           return true;
         }
maybeForceBuilderInitialization()
void maybeForceBuilderInitialization () private
{
         }
mergeFrom() [1/2]
Builder mergeFrom (Geobuf.Data.FeatureCollection other)
References Geobuf.Data.FeatureCollection.Builder.features_, and Geobuf.Data.FeatureCollection.getDefaultInstance().
Referenced by Geobuf.Data.FeatureCollection.Builder.clone(), Geobuf.Data.Data(), Geobuf.Data.Builder.mergeFeatureCollection(), and Geobuf.Data.FeatureCollection.newBuilder().
{
           if (other == Geobuf.Data.FeatureCollection.getDefaultInstance()) return this;
           if (!other.features_.isEmpty()) {
             if (features_.isEmpty()) {
               features_ = other.features_;
               bitField0_ = (bitField0_ & ~0x00000001);
             } else {
               ensureFeaturesIsMutable();
               features_.addAll(other.features_);
             }
           }
           if (!other.values_.isEmpty()) {
             if (values_.isEmpty()) {
               values_ = other.values_;
               bitField0_ = (bitField0_ & ~0x00000002);
             } else {
               ensureValuesIsMutable();
               values_.addAll(other.values_);
             }
           }
           if (!other.customProperties_.isEmpty()) {
             if (customProperties_.isEmpty()) {
               customProperties_ = other.customProperties_;
               bitField0_ = (bitField0_ & ~0x00000004);
             } else {
               ensureCustomPropertiesIsMutable();
               customProperties_.addAll(other.customProperties_);
             }
           }
           setUnknownFields(
               getUnknownFields().concat(other.unknownFields));
           return this;
         }
mergeFrom() [2/2]
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
{
           Geobuf.Data.FeatureCollection parsedMessage = null;
           try {
             parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
           } catch (com.google.protobuf.InvalidProtocolBufferException e) {
             parsedMessage = (Geobuf.Data.FeatureCollection) e.getUnfinishedMessage();
             throw e;
           } finally {
             if (parsedMessage != null) {
               mergeFrom(parsedMessage);
             }
           }
           return this;
         }
removeFeatures()
Builder removeFeatures (int index)
repeated .Data.Feature features = 1;
{
           ensureFeaturesIsMutable();
           features_.remove(index);
           return this;
         }
removeValues()
Builder removeValues (int index)
repeated .Data.Value values = 13;
{
           ensureValuesIsMutable();
           values_.remove(index);
           return this;
         }
setCustomProperties()
Builder setCustomProperties (int index, int value)
repeated uint32 custom_properties = 15 [packed = true];
{
           ensureCustomPropertiesIsMutable();
           customProperties_.set(index, value);
           return this;
         }
setFeatures() [1/2]
Builder setFeatures (int index, Geobuf.Data.Feature value)
repeated .Data.Feature features = 1;
{
           if (value == null) {
             throw new NullPointerException();
           }
           ensureFeaturesIsMutable();
           features_.set(index, value);
           return this;
         }
setFeatures() [2/2]
Builder setFeatures (int index, Geobuf.Data.Feature.Builder builderForValue)
repeated .Data.Feature features = 1;
{
           ensureFeaturesIsMutable();
           features_.set(index, builderForValue.build());
           return this;
         }
setValues() [1/2]
Builder setValues (int index, Geobuf.Data.Value value)
repeated .Data.Value values = 13;
{
           if (value == null) {
             throw new NullPointerException();
           }
           ensureValuesIsMutable();
           values_.set(index, value);
           return this;
         }
setValues() [2/2]
Builder setValues (int index, Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
{
           ensureValuesIsMutable();
           values_.set(index, builderForValue.build());
           return this;
         }
Member Data Documentation
bitField0_
int bitField0_ private
customProperties_
java.util.List<java.lang.Integer> customProperties_ = java.util.Collections.emptyList() private
features_
java.util.List<Geobuf.Data.Feature> features_ private
Initial value:
=
          java.util.Collections.emptyList()
Referenced by Geobuf.Data.FeatureCollection.Builder.mergeFrom().
values_
java.util.List<Geobuf.Data.Value> values_ private
Initial value:
=
          java.util.Collections.emptyList()