jena-geo: Geobuf.Data.Value Class Reference
Geobuf.Data.Value Class Reference
Protobuf type.
Classes
class Builder
Protobuf type.
enum ValueTypeCase
Public Member Functions
Value getDefaultInstanceForType ()
.lang.Override com.google.protobuf.Parser< Value > getParserForType ()
ValueTypeCase getValueTypeCase ()
boolean hasStringValue ()
optional string string_value = 1;
java.lang.String getStringValue ()
optional string string_value = 1;
com.google.protobuf.ByteString getStringValueBytes ()
optional string string_value = 1;
boolean hasDoubleValue ()
optional double double_value = 2;
double getDoubleValue ()
optional double double_value = 2;
boolean hasPosIntValue ()
optional uint64 pos_int_value = 3;
long getPosIntValue ()
optional uint64 pos_int_value = 3;
boolean hasNegIntValue ()
optional uint64 neg_int_value = 4;
long getNegIntValue ()
optional uint64 neg_int_value = 4;
boolean hasBoolValue ()
optional bool bool_value = 5;
boolean getBoolValue ()
optional bool bool_value = 5;
boolean hasJsonValue ()
optional string json_value = 6;
java.lang.String getJsonValue ()
optional string json_value = 6;
com.google.protobuf.ByteString getJsonValueBytes ()
optional string json_value = 6;
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static Value getDefaultInstance ()
static Geobuf.Data.Value parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.Value parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.Value parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.Value parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.Value parseFrom (java.io.InputStream input) throws java.io.IOException
static Geobuf.Data.Value parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Geobuf.Data.Value parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static Geobuf.Data.Value parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Geobuf.Data.Value parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static Geobuf.Data.Value parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (Geobuf.Data.Value prototype)
Static Public Attributes
static com.google.protobuf.Parser< Value > PARSER
static final int STRING_VALUE_FIELD_NUMBER = 1
static final int DOUBLE_VALUE_FIELD_NUMBER = 2
static final int POS_INT_VALUE_FIELD_NUMBER = 3
static final int NEG_INT_VALUE_FIELD_NUMBER = 4
static final int BOOL_VALUE_FIELD_NUMBER = 5
static final int JSON_VALUE_FIELD_NUMBER = 6
Protected Member Functions
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
Static Package Functions
[static initializer]
Private Member Functions
Value (com.google.protobuf.GeneratedMessageLite.Builder builder)
Value (boolean noInit)
Value (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
void initFields ()
Private Attributes
final com.google.protobuf.ByteString unknownFields
int bitField0_
int valueTypeCase_ = 0
java.lang.Object valueType_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final Value defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Protobuf type.
Data.Value
Constructor & Destructor Documentation
Value() [1/3]
Value (com.google.protobuf.GeneratedMessageLite.Builder builder) private
{
         super(builder);
         this.unknownFields = builder.getUnknownFields();
       }
Value() [2/3]
Value (boolean noInit) private
 { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}
Value() [3/3]
Value (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException private
{
         initFields();
         int mutable_bitField0_ = 0;
         com.google.protobuf.ByteString.Output unknownFieldsOutput =
             com.google.protobuf.ByteString.newOutput();
         com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
             com.google.protobuf.CodedOutputStream.newInstance(
                 unknownFieldsOutput);
         try {
           boolean done = false;
           while (!done) {
             int tag = input.readTag();
             switch (tag) {
               case 0:
                 done = true;
                 break;
               default: {
                 if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                        extensionRegistry, tag)) {
                   done = true;
                 }
                 break;
               }
               case 10: {
                 com.google.protobuf.ByteString bs = input.readBytes();
                 valueTypeCase_ = 1;
                 valueType_ = bs;
                 break;
               }
               case 17: {
                 valueTypeCase_ = 2;
                 valueType_ = input.readDouble();
                 break;
               }
               case 24: {
                 valueTypeCase_ = 3;
                 valueType_ = input.readUInt64();
                 break;
               }
               case 32: {
                 valueTypeCase_ = 4;
                 valueType_ = input.readUInt64();
                 break;
               }
               case 40: {
                 valueTypeCase_ = 5;
                 valueType_ = input.readBool();
                 break;
               }
               case 50: {
                 com.google.protobuf.ByteString bs = input.readBytes();
                 valueTypeCase_ = 6;
                 valueType_ = bs;
                 break;
               }
             }
           }
         } catch (com.google.protobuf.InvalidProtocolBufferException e) {
           throw e.setUnfinishedMessage(this);
         } catch (java.io.IOException e) {
           throw new com.google.protobuf.InvalidProtocolBufferException(
               e.getMessage()).setUnfinishedMessage(this);
         } finally {
           try {
             unknownFieldsCodedOutput.flush();
           } catch (java.io.IOException e) {
           // Should not happen
           } finally {
             unknownFields = unknownFieldsOutput.toByteString();
           }
           makeExtensionsImmutable();
         }
       }
Member Function Documentation
[static initializer]()
[static initializer] () static package
getBoolValue()
boolean getBoolValue ()
optional bool bool_value = 5;
Implements Geobuf.Data.ValueOrBuilder.
Referenced by GeobufFeature.GeobufFeature().
{
         if (valueTypeCase_ == 5) {
           return (java.lang.Boolean) valueType_;
         }
         return false;
       }
getDefaultInstance()
static Value getDefaultInstance () static
Referenced by Geobuf.Data.Value.Builder.getDefaultInstanceForType(), and Geobuf.Data.Value.Builder.mergeFrom().
{
         return defaultInstance;
       }
getDefaultInstanceForType()
Value getDefaultInstanceForType ()
{
         return defaultInstance;
       }
getDoubleValue()
double getDoubleValue ()
optional double double_value = 2;
Implements Geobuf.Data.ValueOrBuilder.
{
         if (valueTypeCase_ == 2) {
           return (java.lang.Double) valueType_;
         }
         return 0D;
       }
getJsonValue()
java.lang.String getJsonValue ()
optional string json_value = 6;
Implements Geobuf.Data.ValueOrBuilder.
{
         java.lang.Object ref = "";
         if (valueTypeCase_ == 6) {
           ref = valueType_;
         }
         if (ref instanceof java.lang.String) {
           return (java.lang.String) ref;
         } else {
           com.google.protobuf.ByteString bs =
               (com.google.protobuf.ByteString) ref;
           java.lang.String s = bs.toStringUtf8();
           if (bs.isValidUtf8() && (valueTypeCase_ == 6)) {
             valueType_ = s;
           }
           return s;
         }
       }
getJsonValueBytes()
com.google.protobuf.ByteString getJsonValueBytes ()
optional string json_value = 6;
Implements Geobuf.Data.ValueOrBuilder.
{
         java.lang.Object ref = "";
         if (valueTypeCase_ == 6) {
           ref = valueType_;
         }
         if (ref instanceof java.lang.String) {
           com.google.protobuf.ByteString b =
               com.google.protobuf.ByteString.copyFromUtf8(
                   (java.lang.String) ref);
           if (valueTypeCase_ == 6) {
             valueType_ = b;
           }
           return b;
         } else {
           return (com.google.protobuf.ByteString) ref;
         }
       }
getNegIntValue()
long getNegIntValue ()
optional uint64 neg_int_value = 4;
Implements Geobuf.Data.ValueOrBuilder.
{
         if (valueTypeCase_ == 4) {
           return (java.lang.Long) valueType_;
         }
         return 0L;
       }
getParserForType()
.lang.Override com.google.protobuf.Parser<Value> getParserForType ()
{
         return PARSER;
       }
getPosIntValue()
long getPosIntValue ()
optional uint64 pos_int_value = 3;
Implements Geobuf.Data.ValueOrBuilder.
{
         if (valueTypeCase_ == 3) {
           return (java.lang.Long) valueType_;
         }
         return 0L;
       }
getSerializedSize()
int getSerializedSize ()
{
         int size = memoizedSerializedSize;
         if (size != -1) return size;
         size = 0;
         if (valueTypeCase_ == 1) {
           size += com.google.protobuf.CodedOutputStream
             .computeBytesSize(1, getStringValueBytes());
         }
         if (valueTypeCase_ == 2) {
           size += com.google.protobuf.CodedOutputStream
             .computeDoubleSize(
                 2, (double)((java.lang.Double) valueType_));
         }
         if (valueTypeCase_ == 3) {
           size += com.google.protobuf.CodedOutputStream
             .computeUInt64Size(
                 3, (long)((java.lang.Long) valueType_));
         }
         if (valueTypeCase_ == 4) {
           size += com.google.protobuf.CodedOutputStream
             .computeUInt64Size(
                 4, (long)((java.lang.Long) valueType_));
         }
         if (valueTypeCase_ == 5) {
           size += com.google.protobuf.CodedOutputStream
             .computeBoolSize(
                 5, (boolean)((java.lang.Boolean) valueType_));
         }
         if (valueTypeCase_ == 6) {
           size += com.google.protobuf.CodedOutputStream
             .computeBytesSize(6, getJsonValueBytes());
         }
         size += unknownFields.size();
         memoizedSerializedSize = size;
         return size;
       }
getStringValue()
java.lang.String getStringValue ()
optional string string_value = 1;
Implements Geobuf.Data.ValueOrBuilder.
{
         java.lang.Object ref = "";
         if (valueTypeCase_ == 1) {
           ref = valueType_;
         }
         if (ref instanceof java.lang.String) {
           return (java.lang.String) ref;
         } else {
           com.google.protobuf.ByteString bs =
               (com.google.protobuf.ByteString) ref;
           java.lang.String s = bs.toStringUtf8();
           if (bs.isValidUtf8() && (valueTypeCase_ == 1)) {
             valueType_ = s;
           }
           return s;
         }
       }
getStringValueBytes()
com.google.protobuf.ByteString getStringValueBytes ()
optional string string_value = 1;
Implements Geobuf.Data.ValueOrBuilder.
{
         java.lang.Object ref = "";
         if (valueTypeCase_ == 1) {
           ref = valueType_;
         }
         if (ref instanceof java.lang.String) {
           com.google.protobuf.ByteString b =
               com.google.protobuf.ByteString.copyFromUtf8(
                   (java.lang.String) ref);
           if (valueTypeCase_ == 1) {
             valueType_ = b;
           }
           return b;
         } else {
           return (com.google.protobuf.ByteString) ref;
         }
       }
getValueTypeCase()
ValueTypeCase getValueTypeCase ()
References Geobuf.Data.Value.ValueTypeCase.valueOf().
{
         return ValueTypeCase.valueOf(
             valueTypeCase_);
       }
hasBoolValue()
boolean hasBoolValue ()
optional bool bool_value = 5;
Implements Geobuf.Data.ValueOrBuilder.
{
         return valueTypeCase_ == 5;
       }
hasDoubleValue()
boolean hasDoubleValue ()
optional double double_value = 2;
Implements Geobuf.Data.ValueOrBuilder.
{
         return valueTypeCase_ == 2;
       }
hasJsonValue()
boolean hasJsonValue ()
optional string json_value = 6;
Implements Geobuf.Data.ValueOrBuilder.
{
         return valueTypeCase_ == 6;
       }
hasNegIntValue()
boolean hasNegIntValue ()
optional uint64 neg_int_value = 4;
Implements Geobuf.Data.ValueOrBuilder.
{
         return valueTypeCase_ == 4;
       }
hasPosIntValue()
boolean hasPosIntValue ()
optional uint64 pos_int_value = 3;
Implements Geobuf.Data.ValueOrBuilder.
{
         return valueTypeCase_ == 3;
       }
hasStringValue()
boolean hasStringValue ()
optional string string_value = 1;
Implements Geobuf.Data.ValueOrBuilder.
{
         return valueTypeCase_ == 1;
       }
initFields()
void initFields () private
Referenced by Geobuf.Data.Value.Builder.setJsonValueBytes().
{
       }
isInitialized()
final boolean isInitialized ()
{
         byte isInitialized = memoizedIsInitialized;
         if (isInitialized == 1) return true;
         if (isInitialized == 0) return false;
         memoizedIsInitialized = 1;
         return true;
       }
newBuilder() [1/2]
static Builder newBuilder () static
References Geobuf.Data.Value.Builder.create().
Referenced by GeobufEncoder.makeFeature().
 { return Builder.create(); }
newBuilder() [2/2]
static Builder newBuilder (Geobuf.Data.Value prototype) static
References Geobuf.Data.Value.Builder.mergeFrom().
{
         return newBuilder().mergeFrom(prototype);
       }
newBuilderForType()
Builder newBuilderForType ()
 { return newBuilder(); }
parseDelimitedFrom() [1/2]
static Geobuf.Data.Value parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException static
References Geobuf.Data.Value.parseDelimitedFrom().
Referenced by Geobuf.Data.Value.parseDelimitedFrom().
{
         return PARSER.parseDelimitedFrom(input);
       }
parseDelimitedFrom() [2/2]
static Geobuf.Data.Value parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException static
References Geobuf.Data.Value.parseDelimitedFrom().
{
         return PARSER.parseDelimitedFrom(input, extensionRegistry);
       }
parseFrom() [1/8]
static Geobuf.Data.Value parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.Value.parseFrom().
Referenced by Geobuf.Data.Value.parseFrom().
{
         return PARSER.parseFrom(data);
       }
parseFrom() [2/8]
static Geobuf.Data.Value parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.Value.parseFrom().
{
         return PARSER.parseFrom(data, extensionRegistry);
       }
parseFrom() [3/8]
static Geobuf.Data.Value parseFrom (byte [] data) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.Value.parseFrom().
{
         return PARSER.parseFrom(data);
       }
parseFrom() [4/8]
static Geobuf.Data.Value parseFrom (byte [] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.Value.parseFrom().
{
         return PARSER.parseFrom(data, extensionRegistry);
       }
parseFrom() [5/8]
static Geobuf.Data.Value parseFrom (java.io.InputStream input) throws java.io.IOException static
References Geobuf.Data.Value.parseFrom().
{
         return PARSER.parseFrom(input);
       }
parseFrom() [6/8]
static Geobuf.Data.Value parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException static
References Geobuf.Data.Value.parseFrom().
{
         return PARSER.parseFrom(input, extensionRegistry);
       }
parseFrom() [7/8]
static Geobuf.Data.Value parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException static
References Geobuf.Data.Value.parseFrom().
{
         return PARSER.parseFrom(input);
       }
parseFrom() [8/8]
static Geobuf.Data.Value parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException static
References Geobuf.Data.Value.parseFrom().
{
         return PARSER.parseFrom(input, extensionRegistry);
       }
toBuilder()
Builder toBuilder ()
 { return newBuilder(this); }
writeReplace()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException protected
{
         return super.writeReplace();
       }
writeTo()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
{
         getSerializedSize();
         if (valueTypeCase_ == 1) {
           output.writeBytes(1, getStringValueBytes());
         }
         if (valueTypeCase_ == 2) {
           output.writeDouble(
               2, (double)((java.lang.Double) valueType_));
         }
         if (valueTypeCase_ == 3) {
           output.writeUInt64(
               3, (long)((java.lang.Long) valueType_));
         }
         if (valueTypeCase_ == 4) {
           output.writeUInt64(
               4, (long)((java.lang.Long) valueType_));
         }
         if (valueTypeCase_ == 5) {
           output.writeBool(
               5, (boolean)((java.lang.Boolean) valueType_));
         }
         if (valueTypeCase_ == 6) {
           output.writeBytes(6, getJsonValueBytes());
         }
         output.writeRawBytes(unknownFields);
       }
Member Data Documentation
bitField0_
int bitField0_ private
BOOL_VALUE_FIELD_NUMBER
final int BOOL_VALUE_FIELD_NUMBER = 5 static
defaultInstance
final Value defaultInstance static private
DOUBLE_VALUE_FIELD_NUMBER
final int DOUBLE_VALUE_FIELD_NUMBER = 2 static
JSON_VALUE_FIELD_NUMBER
final int JSON_VALUE_FIELD_NUMBER = 6 static
memoizedIsInitialized
byte memoizedIsInitialized = -1 private
memoizedSerializedSize
int memoizedSerializedSize = -1 private
NEG_INT_VALUE_FIELD_NUMBER
final int NEG_INT_VALUE_FIELD_NUMBER = 4 static
PARSER
com.google.protobuf.Parser<Value> PARSER static
Initial value:
=
          new com.google.protobuf.AbstractParser<Value>() {
        public Value parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Value(input, extensionRegistry);
        }
      }
Referenced by Geobuf.Data.Feature.Feature(), Geobuf.Data.FeatureCollection.FeatureCollection(), and Geobuf.Data.Geometry.Geometry().
POS_INT_VALUE_FIELD_NUMBER
final int POS_INT_VALUE_FIELD_NUMBER = 3 static
serialVersionUID
final long serialVersionUID = 0L static private
STRING_VALUE_FIELD_NUMBER
final int STRING_VALUE_FIELD_NUMBER = 1 static
unknownFields
final com.google.protobuf.ByteString unknownFields private
valueType_
java.lang.Object valueType_ private
Referenced by Geobuf.Data.Value.Builder.buildPartial().
valueTypeCase_
int valueTypeCase_ = 0 private