jena-geo: Not Class Reference
Not Class Reference
Public Member Functions
NodeValue exec (NodeValue v1)
Member Function Documentation
exec()
NodeValue exec (NodeValue v1)
References CoverageWrapper.createCoverage(), CoverageWrapper.extract(), CoverageWrapper.getRasterDatatypeURI(), CoverageWrapper.getSrsURI(), and CoverageWrapper.getXYGeometry().
Referenced by NotTest.testNot().
{
                         CoverageWrapper wrapper=CoverageWrapper.extract(v1);
                         GridCoverage2D raster=wrapper.getXYGeometry();
                          ParameterBlock pbSubtracted = new ParameterBlock();
                      pbSubtracted.addSource(raster.getRenderedImage());
                      RenderedOp subtractedImage = JAI.create("invert",pbSubtracted);
                                 GridCoverageBuilder builder=new GridCoverageBuilder();
                                 builder.setGridGeometry(raster.getGridGeometry());
                                 builder.setNumBands(raster.getNumSampleDimensions());
                                 builder.setExtent(raster.getGridGeometry().getExtent());
                                 builder.setRenderedImage(subtractedImage);
                                 /*final SampleDimension sd = new SampleDimension.Builder().setName("t")
                                                 .addQuantitative(
                                                                 (raster.getSampleDimensions().get(rd1).getName() + "+"
                                                                                 + raster2.getSampleDimensions().get(rd2).getName()).toString(),
                                                                 raster.getSampleDimensions().get(0).getMeasurementRange().get(),
                                                                 raster.getSampleDimensions().get(0).getTransferFunction().get(),
                                                                 raster.getSampleDimensions().get(0).getUnits().get())
                                                 .build();
                                 List<SampleDimension>sds=new LinkedList<SampleDimension>();
                                 sds.add(sd);
                                 /*
                                  * Create the grid coverage, gets its image and set values directly as short
                                  * integers.
                                 BufferedGridCoverage coverage = new BufferedGridCoverage(raster2.getGridGeometry(),
                                                 sds, DataBuffer.TYPE_SHORT);
                                 WritableRaster rasterr = ((BufferedImage) coverage.render(null)).getRaster();
                                 rasterr.setRect(subtractedImage.getSourceImage(0).getData());
                                 return CoverageWrapper.createCoverage(coverage, wrapper.getSrsURI(), wrapper.getRasterDatatypeURI())
                                                 .asNodeValue();
                                 } catch (CannotEvaluateException e) {
                                         // TODO Auto-generated catch block
                                         e.printStackTrace();
                                         return null;
                                 }*/
                                 GridCoverage cov=builder.build();
                                 return CoverageWrapper.createCoverage((GridCoverage2D)cov, wrapper.getSrsURI(), wrapper.getRasterDatatypeURI())
                                                 .asNodeValue();
                 }