jena-geo: MultConst Class Reference
MultConst Class Reference
Public Member Functions
NodeValue exec (NodeValue v1, NodeValue v2, NodeValue v3)
Member Function Documentation
exec()
NodeValue exec (NodeValue v1, NodeValue v2, NodeValue v3)
References CoverageWrapper.createCoverage(), CoverageWrapper.extract(), GridCoverage.getCoordinateReferenceSystem(), GridCoverage.getGridGeometry(), CoverageWrapper.getRasterDatatypeURI(), GridCoverage.getSampleDimensions(), CoverageWrapper.getSrsURI(), CoverageWrapper.getXYGeometry(), and GridCoverage.render().
Referenced by MultConstTest.testMultConst().
{
                 CoverageWrapper wrapper=CoverageWrapper.extract(v1);
                 GridCoverage raster=wrapper.getXYGeometry();
                 BigInteger bandnum=v2.getInteger();
                 Double constval=v3.getDouble();
                 double[] consts=new double[raster.getSampleDimensions().size()];
                 if(bandnum.intValue()<0) {
                         for(int i=0;i<consts.length;i++) {
                                 consts[i]=constval;
                         }
                 }else {
                         for(int i=0;i<consts.length;i++) {
                                 if(i==bandnum.intValue()) {
                                         consts[i]=constval;
                                 }else {
                                         consts[i]=1;
                                 }
                         }
                 }
                  ParameterBlock pbSubtracted = new ParameterBlock();
              pbSubtracted.addSource(raster.render(null));
              pbSubtracted.add(consts);
              RenderedOp subtractedImage = JAI.create("multiplyconst",pbSubtracted);
                 final SampleDimension sd =raster.getSampleDimensions().get(0);
                 List<SampleDimension>sds=new LinkedList<SampleDimension>();
                 sds.add(sd);
         GridExtent extent=new GridExtent(subtractedImage.getWidth(), subtractedImage.getHeight());
         GridGeometry gridgeom=new GridGeometry(extent, PixelInCell.CELL_CENTER, raster.getGridGeometry().getGridToCRS(PixelInCell.CELL_CENTER), raster.getCoordinateReferenceSystem());
         List<SampleDimension> dimensions=new LinkedList<SampleDimension>();
         DefaultNameFactory fac=new DefaultNameFactory();
         for(int i=0;i<subtractedImage.getNumBands();i++) {
                 dimensions.add(new SampleDimension(fac.createGenericName(null,  "Dimension "+i),0.,new LinkedList<Category>()));
         }
         BufferedGridCoverage coverage=new BufferedGridCoverage(
                         gridgeom, dimensions, subtractedImage.getData().getDataBuffer());
                         return CoverageWrapper.createCoverage((GridCoverage)coverage, wrapper.getSrsURI(), wrapper.getRasterDatatypeURI())
                                         .asNodeValue();
         }