jena-geo: GMLDatatype Class Reference
GMLDatatype Class Reference
Public Member Functions
GMLDatatype ()
private constructor - single global instance.
String unparse (Object geometry)
This method Un-parses the JTS Geometry to the GML literal.
GeometryWrapper read (String geometryLiteral)
String toString ()
final GeometryWrapper parse (String lexicalForm) throws DatatypeFormatException
This method Parses the Geometry Literal to the JTS Geometry.
final GeometryWrapper parse (String lexicalForm, GeometryIndex targetIndex) throws DatatypeFormatException
Static Public Member Functions
static final void registerDatatypes ()
static final GeometryDatatype get (RDFDatatype rdfDatatype)
static final GeometryDatatype get (String datatypeURI)
static final boolean checkURI (String datatypeURI)
static final boolean check (RDFDatatype rdfDatatype)
Static Public Attributes
static final String URI = Geo.GML
The default GML type URI.
static final GMLDatatype INSTANCE = new GMLDatatype()
A static instance of GMLDatatype.
static final String GML_PREFIX = "gml"
XML element tag "gml" is defined for the convenience of GML generation.
Static Private Attributes
static final Logger LOGGER = LoggerFactory.getLogger(GMLDatatype.class)
Constructor & Destructor Documentation
GMLDatatype()
GMLDatatype ()
private constructor - single global instance.
{
         super(URI);
     }
Member Function Documentation
check()
static final boolean check (RDFDatatype rdfDatatype) static inherited
References GeometryDatatype.checkURI().
{
         //Ensure that the registered datatypes from the type mapper are used.
         return checkURI(rdfDatatype.getURI());
     }
checkURI()
static final boolean checkURI (String datatypeURI) static inherited
References GeometryDatatype.GeometryDatatype(), and GeometryDatatype.registerDatatypes().
Referenced by GeometryDatatype.check(), and GeometryDatatype.get().
{
         registerDatatypes();
         RDFDatatype rdfDatatype = TYPE_MAPPER.getTypeByName(datatypeURI);
         if (rdfDatatype != null) {
             return rdfDatatype instanceof GeometryDatatype;
         } else {
             throw new DatatypeFormatException("Datatype not found: " + datatypeURI + " Ensure that GeoSPARQL is enabled and Datatype has been registered.");
         }
     }
get() [1/2]
static final GeometryDatatype get (RDFDatatype rdfDatatype) static inherited
References GeometryDatatype.registerDatatypes().
Referenced by GeometryWrapper.asLiteral(), GeometryWrapper.extract(), GeometryDatatype.get(), GeometryWrapper.getGeometryDatatype(), and LiteralUtils.rasterOrVector().
{
         registerDatatypes();
         //System.out.println(rdfDatatype);
         //Iterator it=TYPE_MAPPER.listTypes();
         /*while(it.hasNext()) {
                 System.out.println(it.next());
         }*/
         if (rdfDatatype instanceof GeometryDatatype) {
             return (GeometryDatatype) rdfDatatype;
         } else {
             throw new DatatypeFormatException("Unrecognised Geometry Datatype: " + rdfDatatype.getURI() + " Ensure that Datatype is extending GeometryDatatype.");
         }
     }
get() [2/2]
static final GeometryDatatype get (String datatypeURI) static inherited
References GeometryDatatype.checkURI(), and GeometryDatatype.get().
{
         checkURI(datatypeURI);
         RDFDatatype rdfDatatype = TYPE_MAPPER.getTypeByName(datatypeURI);
         return GeometryDatatype.get(rdfDatatype);
     }
parse() [1/2]
final GeometryWrapper parse (String lexicalForm) throws DatatypeFormatException inherited
This method Parses the Geometry Literal to the JTS Geometry.
Parameters
lexicalForm - the Geometry Literal to be parsed
Returns
geometry - if the Geometry Literal is valid.
empty geometry - if the Geometry Literal is empty.
null - if the Geometry Literal is invalid.
References GeometryLiteralIndex.GeometryIndex.PRIMARY.
Referenced by GeometryWrapper.extract(), and GeomFromGeoJSONTest.testGeomFromGeoJSON().
{
         return parse(lexicalForm, GeometryIndex.PRIMARY);
     }
parse() [2/2]
final GeometryWrapper parse (String lexicalForm, GeometryIndex targetIndex) throws DatatypeFormatException inherited
References GeometryLiteralIndex.retrieve().
{
         //Check the Geometry Literal Index to see if been previously read and cached.
         //DatatypeReader interface used to instruct index on how to obtain the GeometryWrapper.
         try {
             return GeometryLiteralIndex.retrieve(lexicalForm, this, targetIndex);
         } catch (IllegalArgumentException ex) {
             throw new DatatypeFormatException(ex.getMessage() + " - Illegal Geometry Literal: " + lexicalForm);
         }
     }
read()
GeometryWrapper read (String geometryLiteral)
References GeometryWrapper.extract(), GeometryWrapper.getDimensionInfo(), and GMLDatatype.URI.
Referenced by CoverageWrapper.getEmptyGML(), and GeometryWrapper.getEmptyGML().
{
         try {
             GMLReader gmlReader = GMLReader.extract(geometryLiteral);
             Geometry geometry = gmlReader.getGeometry();
             DimensionInfo dimensionInfo = gmlReader.getDimensionInfo();
             return new GeometryWrapper(geometry, gmlReader.getSrsURI(), URI, dimensionInfo, geometryLiteral);
         } catch (JDOMException | IOException ex) {
             throw new DatatypeFormatException("Illegal GML literal:" + geometryLiteral + ". " + ex.getMessage());
         }
     }
registerDatatypes()
static final void registerDatatypes () static inherited
References KMLDatatype.INSTANCE, GeoURIDatatype.INSTANCE, GPXDatatype.INSTANCE, HexWKBDatatype.INSTANCE, WKBDatatype.INSTANCE, EncodedPolylineDatatype.INSTANCE, TWKBDatatype.INSTANCE, GMLDatatype.INSTANCE, and GeoJSONDatatype.INSTANCE.
Referenced by GeometryDatatype.checkURI(), and GeometryDatatype.get().
{
         //System.out.println("Is")
         //if (!isDatatypesRegistered) {
             TYPE_MAPPER.registerDatatype(WKTDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GMLDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GeoJSONDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(KMLDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(WKBDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(TWKBDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(TopoJSONDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(GeobufDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(GeoHashDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(EncodedPolylineDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(HexWKBDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GeoURIDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GPXDatatype.INSTANCE);
             isDatatypesRegistered = true;
         //}
     }
toString()
String toString ()
{
         return "GMLDatatype{" + URI + '}';
     }
unparse()
String unparse (Object geometry)
This method Un-parses the JTS Geometry to the GML literal.
Parameters
geometry - the JTS Geometry to be un-parsed
Returns
GML - the returned GML Literal.
Notice that the Spatial Reference System "urn:ogc:def:crs:OGC::CRS84" is predefined in the returned GML literal.
{
         if (geometry instanceof GeometryWrapper) {
             GeometryWrapper geometryWrapper = (GeometryWrapper) geometry;
             return GMLWriter.write(geometryWrapper);
         } else {
             throw new AssertionError("Object passed to GMLDatatype is not a GeometryWrapper: " + geometry);
         }
     }
Member Data Documentation
GML_PREFIX
final String GML_PREFIX = "gml" static
XML element tag "gml" is defined for the convenience of GML generation.
INSTANCE
final GMLDatatype INSTANCE = new GMLDatatype() static
A static instance of GMLDatatype.
Referenced by CoverageWrapper.getEmptyGML(), GeometryWrapper.getEmptyGML(), and GeometryDatatype.registerDatatypes().
LOGGER
final Logger LOGGER = LoggerFactory.getLogger(GMLDatatype.class) static private
URI
final String URI = Geo.GML static
The default GML type URI.
Referenced by GMLDatatype.read().