jena-geo: DisjointExtentException Class Reference
DisjointExtentException Class Reference
Thrown when operations on a GridGeometry result in an area which does not intersect anymore the GridExtent of the GridGeometry.
Public Member Functions
DisjointExtentException ()
Constructs an exception with no detail message.
DisjointExtentException (final String message)
Constructs an exception with the specified detail message.
DisjointExtentException (final String message, final Throwable cause)
Constructs an exception with the specified detail message and cause.
Package Functions
DisjointExtentException (final Object dim, final long min, final long max, final long lower, final long upper)
Creates an exception with an error message built from the given arguments.
DisjointExtentException (final GridExtent source, final GridExtent request, final int dim)
Creates an exception with an error message built from the given extents.
Static Private Attributes
static final long serialVersionUID = -1437479443547738220L
Serial number for inter-operability with different versions.
Detailed Description
Thrown when operations on a GridGeometry result in an area which does not intersect anymore the GridExtent of the GridGeometry.
Author
Johann Sorel (Geomatys)
Martin Desruisseaux (Geomatys)
Version
1.1
Since
1.0
Constructor & Destructor Documentation
DisjointExtentException() [1/5]
DisjointExtentException ()
Constructs an exception with no detail message.
{
     }
DisjointExtentException() [2/5]
DisjointExtentException (final String message)
Constructs an exception with the specified detail message.
Parameters
message the detail message.
{
         super(message);
     }
DisjointExtentException() [3/5]
DisjointExtentException (final String message, final Throwable cause)
Constructs an exception with the specified detail message and cause.
Parameters
message the detail message.
cause the cause for this exception.
{
         super(message, cause);
     }
DisjointExtentException() [4/5]
DisjointExtentException (final Object dim, final long min, final long max, final long lower, final long upper) package
Creates an exception with an error message built from the given arguments.
Current implementation creates the error message immediately, but we may change to deferred creation later if it is a performance issue.
Parameters
dim identification of the dimension having an invalid value.
min the lower bound of valid area.
max the upper bound of valid area.
lower the lower bound specified by user, which is invalid.
upper the upper bound specified by user, which is invalid.
{
         super(Resources.format(Resources.Keys.GridEnvelopeOutsideCoverage_5, new Object[] {dim, min, max, lower, upper}));
     }
DisjointExtentException() [5/5]
DisjointExtentException (final GridExtent source, final GridExtent request, final int dim) package
Creates an exception with an error message built from the given extents.
Parameters
source extent of the source.
request extent of a slice requested by user.
dim index of the dimension having an invalid value.
References GridExtent.getAxisIdentification(), GridExtent.getHigh(), and GridExtent.getLow().
{
         this(source.getAxisIdentification(dim, dim), source.getLow(dim), source.getHigh(dim),
                 request.getLow(dim), request.getHigh(dim));
     }
Member Data Documentation
serialVersionUID
final long serialVersionUID = -1437479443547738220L static private
Serial number for inter-operability with different versions.