jena-geo: GridExtent Class Reference
GridExtent Class Reference
A range of grid coverage coordinates, also known as "grid envelope".
Public Member Functions
GridExtent (final long width, final long height)
Creates a new grid extent for an image or matrix of the given size.
GridExtent (final DimensionNameType[] axisTypes, final long[] low, final long[] high, final boolean isHighIncluded)
Constructs a new grid envelope set to the specified coordinates.
final int getDimension ()
Returns the number of dimensions.
boolean startsAtZero ()
Returns.
GridCoordinates getLow ()
Returns the valid minimum grid coordinates, inclusive.
GridCoordinates getHigh ()
Returns the valid maximum grid coordinates, inclusive.
long getLow (final int index)
Returns the valid minimum inclusive grid coordinate along the specified dimension.
long getHigh (final int index)
Returns the valid maximum inclusive grid coordinate along the specified dimension.
long getSize (final int index)
Returns the number of integer grid coordinates along the specified dimension.
double getSize (final int index, final boolean minusOne)
Returns the number of grid coordinates as a double precision floating point value.
double [] getPointOfInterest ()
Returns the grid coordinates of a representative point.
int [] getSubspaceDimensions (final int s)
Returns indices of all dimensions where this grid extent has a size greater than 1.
Optional< DimensionNameType > getAxisType (final int index)
Returns the type (vertical, temporal, …) of grid axis at given dimension.
GeneralEnvelope toEnvelope (final MathTransform cornerToCRS) throws TransformException
Transforms this grid extent to a "real world" envelope using the given transform.
GridExtent insert (final int offset, final DimensionNameType axisType, final long low, long high, final boolean isHighIncluded)
Returns a new grid envelope with the specified dimension inserted at the given index in this grid envelope.
GridExtent expand (final long... margins)
Expands or shrinks this grid extent by the given amount of cells along each dimension.
GridExtent resize (final long... sizes)
Sets the size of this grid extent to the given values.
GridExtent reduce (int... dimensions)
Returns a grid envelope that encompass only some dimensions of this grid envelope.
GridExtent subsample (final int... periods)
Creates a new grid extent subsampled by the given amount of cells along each grid dimensions.
int hashCode ()
Returns a hash value for this grid envelope.
final boolean equals (final Object object)
Compares the specified object with this grid envelope for equality.
boolean equals (final Object object, final ComparisonMode mode)
Compares the specified object with this grid envelope for equality.
String toString ()
Returns a string representation of this grid envelope.
Static Public Member Functions
static GridExtent castOrCopy (final GridEnvelope extent)
Returns the given grid envelope as a.
Protected Member Functions
GridExtent (final GridEnvelope extent)
Creates a new grid envelope as a copy of the given one.
Package Functions
GridExtent (final int xmin, final int ymin, final int width, final int height)
Creates a new grid extent for an image of the given size and location.
GridExtent (final AbstractEnvelope envelope, final GridRoundingMode rounding, final int[] margin, final GridExtent enclosing, final int[] modifiedDimensions)
Creates a new grid extent by rounding the given envelope to (usually) nearest integers.
GridExtent (final GridExtent enclosing, final long[] coordinates)
Creates a new grid extent with the same axes than the given extent, but different coordinates.
final int getSubDimension ()
Returns the number of dimensions where this grid extent has a size greater than 1.
final Object getAxisIdentification (final int index, final int indexShown)
Returns the axis number followed by the localized axis type if available.
final GeneralEnvelope toCRS (final MathTransform cornerToCRS, final MathTransform gridToCRS, final Envelope fallback) throws TransformException
Transforms this grid extent to a "real world" envelope using the given transform.
final GridExtent sliceByRatio (final DirectPosition slicePoint, final double sliceRatio, final int[] dimensionsToKeep)
Returns a slice of this given grid extent computed by a ratio between 0 and 1 inclusive.
final GridExtent slice (final DirectPosition slicePoint, final int[] modifiedDimensions)
Creates a new grid extent which represent a slice of this grid at the given point.
final MatrixSIS cornerToCRS (final Envelope env)
Creates an affine transform from the coordinates of this grid to the coordinates of the given envelope.
final void appendTo (final Appendable out, final Vocabulary vocabulary) throws IOException
Writes a string representation of this grid envelope in the given buffer.
Static Package Functions
[static initializer]
static long [] allocate (final int dimension) throws IllegalArgumentException
Creates a new array of coordinates with the given number of dimensions.
static DimensionNameType [] typeFromAxes (final CoordinateReferenceSystem crs, final int dimension)
Infers the axis types from the given coordinate reference system.
static int [] verifyDimensions (int[] dimensions, final int limit)
Verifies the validity of a given.
Private Member Functions
void validateCoordinates () throws IllegalArgumentException
Checks if coordinate values in the low part are less than or equal to the corresponding coordinate value in the high part.
GridExtent (final int dimension, final DimensionNameType[] axisTypes)
Creates an initially empty grid envelope with the given number of dimensions.
GridExtent (final GridExtent extent)
Creates a copy of the given grid extent.
Static Private Member Functions
static DimensionNameType [] validateAxisTypes (DimensionNameType[] types) throws IllegalArgumentException
Verifies that the given array (if non-null) contains no duplicated values, then returns a copy of that array.
Private Attributes
final DimensionNameType [] types
Type of each axis (vertical, temporal, …) or.
final long [] coordinates
Minimum and maximum grid coordinates.
Static Private Attributes
static final long serialVersionUID = -4717353677844056017L
Serial number for inter-operability with different versions.
static final Map< AxisDirection, DimensionNameType > AXIS_DIRECTIONS
The dimension name types for given coordinate system axis directions.
static final DimensionNameType [] DEFAULT_TYPES
Default axis types for the two-dimensional cases.
static final WeakValueHashMap< DimensionNameType[], DimensionNameType[]> POOL = new WeakValueHashMap<>(DimensionNameType[].class)
A pool of shared DimensionNameType arrays.
Detailed Description
A range of grid coverage coordinates, also known as "grid envelope".
GridExtent
are defined by getLow() low} coordinates (often all zeros) and getHigh() high} coordinates, inclusive. For example a grid with a width of 512 cells can have a low coordinate of 0 and high coordinate of 511.
Note: The inclusiveness of getHigh() high} coordinates come from ISO 19123. We follow this specification for all getters methods, but developers should keep in mind that this is the opposite of Java2D usage where java.awt.Rectangle maximal values are exclusive.
GridExtent
instances are immutable and thread-safe. The same instance can be shared by different GridGeometry instances.
Author
Martin Desruisseaux (IRD, Geomatys)
Version
1.1
Since
1.0
Constructor & Destructor Documentation
GridExtent() [1/8]
GridExtent (final int dimension, final DimensionNameType [] axisTypes) private
Creates an initially empty grid envelope with the given number of dimensions.
All grid coordinate values are initialized to zero. This constructor is private since
GridExtent
coordinate values can not be modified by public API.
Parameters
dimension number of dimensions.
axisTypes the axis types, or
null
if unspecified.
See also
GridExtent(GridExtent)
References GridExtent.allocate(), GridExtent.coordinates, GridExtent.types, and GridExtent.validateAxisTypes().
Referenced by GridExtent.castOrCopy(), GridExtent.equals(), GridExtent.expand(), GridExtent.GridExtent(), GridExtent.insert(), GridExtent.reduce(), GridExtent.resize(), GridExtent.slice(), and GridExtent.subsample().
{
         coordinates = allocate(dimension);
         types = validateAxisTypes(axisTypes);
     }
GridExtent() [2/8]
GridExtent (final long width, final long height)
Creates a new grid extent for an image or matrix of the given size.
The getLow() low} grid coordinates are zeros and the axis types are DimensionNameType#COLUMN and ROW in that order.
Parameters
width number of pixels in each row.
height number of pixels in each column.
References GridExtent.coordinates, GridExtent.DEFAULT_TYPES, and GridExtent.types.
{
         ArgumentChecks.ensureStrictlyPositive("width",  width);
         ArgumentChecks.ensureStrictlyPositive("height", height);
         coordinates = new long[4];
         coordinates[2] = width  - 1;
         coordinates[3] = height - 1;
         types = DEFAULT_TYPES;
     }
GridExtent() [3/8]
GridExtent (final int xmin, final int ymin, final int width, final int height) package
Creates a new grid extent for an image of the given size and location.
This constructor is for GridCoverage2D internal usage: it does not check for overflow (arguments are assumed small enough, which is the case when they are converted from
int
s), and argument meanings differ from conventions in public constructors.
Parameters
xmin column index of the first cell.
ymin row index of the first cell.
width number of pixels in each row.
height number of pixels in each column.
References GridExtent.coordinates.
{
         this(width, height);
         for (int i=coordinates.length; --i >= 0;) {
             coordinates[i] += ((i & 1) == 0) ? xmin : ymin;
         }
     }
GridExtent() [4/8]
GridExtent (final DimensionNameType [] axisTypes, final long [] low, final long [] high, final boolean isHighIncluded)
Constructs a new grid envelope set to the specified coordinates.
The given arrays contain a minimum (inclusive) and maximum value for each dimension of the grid coverage. The lowest valid grid coordinates are often zero, but this is not mandatory. As a convenience for this common case, a null
low
array means that all low coordinates are zero.
An optional (nullable)
axisTypes
argument can be used for attaching a label to each grid axis. For example if this
GridExtent
is four-dimensional, then the axis types may be { DimensionNameType::COLUMN column} (x), DimensionNameType::ROW row} (y), DimensionNameType::VERTICAL vertical (z), DimensionNameType::TIME time} (t)}, which means that the last axis is for the temporal dimension, the third axis is for the vertical dimension, etc. This information is related to the "real world" coordinate reference system axes, but not necessarily in the same order; it is caller responsibility to ensure that the grid axes are consistent with the CRS axes. The
axisTypes
array shall not contain duplicated elements, but may contain
null
elements if the type of some axes are unknown.
Parameters
axisTypes the type of each grid axis, or
null
if unspecified.
low the valid minimum grid coordinates (always inclusive), or
null
for all zeros.
high the valid maximum grid coordinates, inclusive or exclusive depending on the next argument.
isHighIncluded
References GridExtent.allocate(), GridExtent.coordinates, GridExtent.types, GridExtent.validateAxisTypes(), and GridExtent.validateCoordinates().
{
         ArgumentChecks.ensureNonNull("high", high);
         final int dimension = high.length;
         if (low != null && low.length != dimension) {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.MismatchedDimension_2, low.length, dimension));
         }
         if (axisTypes != null && axisTypes.length != dimension) {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.MismatchedArrayLengths));
         }
         coordinates = allocate(dimension);
         if (low != null) {
             System.arraycopy(low, 0, coordinates, 0, dimension);
         }
         System.arraycopy(high, 0, coordinates, dimension, dimension);
         if (!isHighIncluded) {
             for (int i=dimension; i < coordinates.length; i++) {
                 coordinates[i] = Math.decrementExact(coordinates[i]);
             }
         }
         types = validateAxisTypes(axisTypes);
         validateCoordinates();
     }
GridExtent() [5/8]
GridExtent (final AbstractEnvelope envelope, final GridRoundingMode rounding, final int [] margin, final GridExtent enclosing, final int [] modifiedDimensions) package
Creates a new grid extent by rounding the given envelope to (usually) nearest integers.
The envelope coordinates shall be cell indices with lower values inclusive and upper values exclusive. Double#NaN envelope coordinates will be set to the corresponding
enclosing
coordinates (an exception will be thrown if
enclosing
is null in that situation).
Envelopes crossing the anti-meridian shall be GeneralEnvelope::simplify() simplified}. The envelope CRS is ignored, except for identifying dimension names for information purpose. The way floating point values are rounded to integers may be adjusted in any future version.
NOTE: this constructor is not public because its contract is a bit approximate.
Parameters
envelope the envelope containing cell indices to store in a
GridExtent
.
rounding controls behavior of rounding from floating point values to integers.
margin if non-null, expands the extent by that amount of cells on each envelope dimension.
enclosing if the new grid is a sub-grid of a larger grid, that larger grid. Otherwise
null
.
modifiedDimensions if
enclosing
is non-null, the grid dimensions to set from the envelope. The length of this array shall be equal to the
envelope
dimension. This argument is ignored if
enclosing
is null.
Exceptions
DisjointExtentException if the given envelope does not intersect the enclosing grid extent.
See also
toCRS(MathTransform, MathTransform, Envelope)
#slice(DirectPosition, int[])
References GridExtent.allocate(), GridExtent.coordinates, GridExtent.getAxisIdentification(), GridExtent.getDimension(), GridExtent.typeFromAxes(), GridExtent.types, and GridExtent.validateAxisTypes().
     {
         final int dimension = envelope.getDimension();
         coordinates = (enclosing != null) ? enclosing.coordinates.clone() : allocate(dimension);
         /*
          * Assign the `types` field before we try to compute the grid extent coordinates
          * because if the coordinate computation fail, `getAxisIdentification(…)` uses
          * that information for producing a more informative error message if possible.
          */
         if (enclosing != null && enclosing.types != null) {
             types = enclosing.types;
         } else {
             types = validateAxisTypes(typeFromAxes(envelope.getCoordinateReferenceSystem(), dimension));
         }
         /*
          * Now computes the grid extent coordinates.
          */
         for (int i=0; i<dimension; i++) {
             double min = envelope.getLower(i);                      // Inclusive
             double max = envelope.getUpper(i);                      // Exclusive
             final boolean isMinValid = (min >= Long.MIN_VALUE);
             final boolean isMaxValid = (max <= Long.MAX_VALUE);
             if (min > max || (enclosing == null && !(isMinValid & isMaxValid))) {
                 /*
                  * We do not throw an exception if `enclosing` is non-null and envelope bounds are NaN
                  * because this case occurs when the gridToCRS transform has a NaN scale factor.  Such
                  * scale factor may occur with ranges like [0 … 0]. With a non-null `enclosing` extent,
                  * we can still have grid coordinates: they are inherited from `enclosing`. We require
                  * the two bounds to be NaN, otherwise the reason for those NaN envelope bounds is not
                  * a NaN scale factor.
                  */
                 throw new IllegalArgumentException(Resources.format(
                         Resources.Keys.IllegalGridEnvelope_3, getAxisIdentification(i,i), min, max));
             }
             if (!isMinValid) min = Long.MIN_VALUE;
             if (!isMaxValid) max = Long.MAX_VALUE;
             long lower, upper;
             switch (rounding) {
                 default: {
                     throw new AssertionError(rounding);
                 }
                 case ENCLOSING: {
                     lower = (long) Math.floor(min);
                     upper = (long) Math.ceil (max);
                     if (lower != upper) upper--;                                // For making the coordinate inclusive.
                     break;
                 }
                 case NEAREST: {
                     lower = Math.round(min);
                     upper = Math.round(max);
                     if (lower == upper) {                                       // Equality implies (max - min) < 1.
                         if (min - Math.floor(min) > Math.ceil(max) - max) {
                             upper = --lower;
                         }
                     } else {
                         upper--;                                                // For making the coordinate inclusive.
                         /*
                          * The [lower … upper] range may be slightly larger than desired in some rounding error situations.
                          * For example if `min` was 1.49999 and `max` was 2.50001,  the rounding will create a [1…3] range
                          * while there is actually only 2 pixels. We detect those rounding problems by comparing the spans
                          * before and after rounding.  We attempt an adjustment only if the span mismatch is ±1, otherwise
                          * the difference is assumed to be caused by overflow. On the three values that can be affected by
                          * the adjustment (min, max and span), we change only the number which is farthest from an integer
                          * value.
                          */
                         long delta = (upper - lower) + 1;                       // Negative number if overflow.
                         if (delta >= 0) {
                             final double span = envelope.getSpan(i);
                             final long extent = Math.round(span);
                             if (extent != 0 && Math.abs(delta -= extent) == 1) {
                                 final double dmin = Math.abs(min - Math.rint(min));
                                 final double dmax = Math.abs(max - Math.rint(max));
                                 final boolean adjustMax = (dmax >= dmin);
                                 if (Math.abs(span - extent) < (adjustMax ? dmax : dmin)) {
                                     if (adjustMax) upper = Math.subtractExact(upper, delta);
                                     else lower = Math.addExact(lower, delta);
                                 }
                             }
                         }
                     }
                 }
             }
             /*
              * If the user specified a margin, add it now. The margin dimension indices follow the envelope
              * dimension indices.  Note that the resulting extent will be intersected with enclosing extent
              * at the next step, which may cancel the margin effect.
              *
              * Note about overflow checks: if m>0, then x < x+m unless the result overflows the `long` capacity.
              */
             if (margin != null && i < margin.length) {
                 final int m = margin[i];
                 if (enclosing != null && m > 0) {
                     if (lower < (lower -= m)) lower = Long.MIN_VALUE;       // Clamp to MIN/MAX if overflow.
                     if (upper > (upper += m)) upper = Long.MAX_VALUE;
                 } else {
                     lower = Math.subtractExact(lower, m);
                     upper = Math.addExact(upper, m);
                 }
             }
             if (lower > upper) {
                 upper += (lower - upper) >>> 1;         // (lower - upper)/2 as unsigned integer: overflow-safe.
                 lower = upper;
             }
             /*
              * At this point the grid range has been computed (lower to upper). Compute intersection,
              * then update the coordinates accordingly. Note that if envelope coordinates were NaN,
              * they will have been replaced by `Long.MIN/MAX_VALUE`, which will usually cause the
              * assignation to be skipt below (so we keep the values inherited from `enclosing`).
              */
             final int m = getDimension();
             if (enclosing != null) {
                 final int lo = (modifiedDimensions != null) ? modifiedDimensions[i] : i;
                 final int hi = lo + m;
                 final long validMin = coordinates[lo];
                 final long validMax = coordinates[hi];
                 if (lower > validMin) coordinates[lo] = lower;
                 if (upper < validMax) coordinates[hi] = upper;
                 if (lower > validMax || upper < validMin) {
                     throw new DisjointExtentException(getAxisIdentification(lo, i), validMin, validMax, lower, upper);
                 }
             } else {
                 coordinates[i]   = lower;
                 coordinates[i+m] = upper;
             }
         }
     }
GridExtent() [6/8]
GridExtent (final GridExtent enclosing, final long [] coordinates) package
Creates a new grid extent with the same axes than the given extent, but different coordinates.
This constructor does not invoke validateCoordinates(); we presume that the caller's computation is correct.
Parameters
enclosing the extent from which to copy axes, or
null
if none.
coordinates the coordinates. This array is not cloned.
References GridExtent.coordinates, GridExtent.getDimension(), and GridExtent.types.
{
         this.coordinates = coordinates;
         types = (enclosing != null) ? enclosing.types : null;
         assert (types == null) || types.length == getDimension();
     }
GridExtent() [7/8]
GridExtent (final GridExtent extent) private
Creates a copy of the given grid extent.
The coordinates array is cloned while the types array is shared between the two instances. This constructor is reserved to methods that modify the coordinates after construction. It must be private since we do not allow coordinates modifications by public API.
See also
#GridExtent(int, DimensionNameType[])
References GridExtent.coordinates, and GridExtent.types.
{
         types = extent.types;
         coordinates = extent.coordinates.clone();
     }
GridExtent() [8/8]
GridExtent (final GridEnvelope extent) protected
Creates a new grid envelope as a copy of the given one.
Parameters
extent the grid envelope to copy.
Exceptions
IllegalArgumentException if a coordinate value in the low part is greater than the corresponding coordinate value in the high part.
See also
castOrCopy(GridEnvelope)
References GridExtent.allocate(), GridExtent.coordinates, GridExtent.GridExtent(), GridExtent.types, and GridExtent.validateCoordinates().
{
         ArgumentChecks.ensureNonNull("extent", extent);
         final int dimension = extent.getDimension();
         coordinates = allocate(dimension);
         for (int i=0; i<dimension; i++) {
             coordinates[i] = extent.getLow(i);
             coordinates[i + dimension] = extent.getHigh(i);
         }
         types = (extent instanceof GridExtent) ? ((GridExtent) extent).types : null;
         validateCoordinates();
     }
Member Function Documentation
[static initializer]()
[static initializer] () static package
allocate()
static long [] allocate (final int dimension) throws IllegalArgumentException static package
Creates a new array of coordinates with the given number of dimensions.
Exceptions
IllegalArgumentException if the given number of dimensions is excessive.
Referenced by GridExtent.GridExtent(), and FractionalGridCoordinates.toExtent().
{
         if (dimension >= Numerics.MAXIMUM_MATRIX_SIZE) {
             // Actually the real limit is Integer.MAX_VALUE / 2, but a value too high is likely to be an error.
             throw new IllegalArgumentException(Errors.format(Errors.Keys.ExcessiveNumberOfDimensions_1, dimension));
         }
         return new long[dimension << 1];
     }
appendTo()
final void appendTo (final Appendable out, final Vocabulary vocabulary) throws IOException package
Writes a string representation of this grid envelope in the given buffer.
This method is provided for allowing caller to recycle the same buffer.
Parameters
out where to write the string representation.
vocabulary resources for some words.
References GridExtent.coordinates, GridExtent.getDimension(), and GridExtent.types.
Referenced by GridExtent.toString().
{
         final TableAppender table = new TableAppender(out, "");
         final int dimension = getDimension();
         for (int i=0; i<dimension; i++) {
             CharSequence name;
             if ((types == null) || (name = Types.getCodeTitle(types[i])) == null) {
                 name = vocabulary.getString(Vocabulary.Keys.Dimension_1, i);
             }
             final long lower = coordinates[i];
             final long upper = coordinates[i + dimension];
             table.setCellAlignment(TableAppender.ALIGN_LEFT);
             table.append(name).append(": ").nextColumn();
             table.append('[').nextColumn();
             table.setCellAlignment(TableAppender.ALIGN_RIGHT);
             table.append(Long.toString(lower)).append(" … ").nextColumn();
             table.append(Long.toString(upper)).append("] ") .nextColumn();
             table.append('(').append(vocabulary.getString(Vocabulary.Keys.CellCount_1,
                     Long.toUnsignedString(upper - lower + 1))).append(')').nextLine();
         }
         table.flush();
     }
castOrCopy()
static GridExtent castOrCopy (final GridEnvelope extent) static
Returns the given grid envelope as a.
GridExtent
implementation. If the given extent is already a
GridExtent
instance or is null, then it is returned as-is. Otherwise a new extent is created using the GridExtent(GridEnvelope) copy constructor}.
Parameters
extent the grid envelope to cast or copy, or
null
.
Returns
the grid envelope as a
GridExtent
, or
null
if the given extent was null.
References GridExtent.GridExtent().
{
         if (extent == null || extent instanceof GridExtent) {
             return (GridExtent) extent;
         } else {
             return new GridExtent(extent);
         }
     }
cornerToCRS()
final MatrixSIS cornerToCRS (final Envelope env) package
Creates an affine transform from the coordinates of this grid to the coordinates of the given envelope.
This method assumes that all axes are in the same order (no axis swapping) and there is no flipping of axis direction. The transform maps cell corners.
This method is not yet public because we have not decided what could be an API for controlling axis swapping and flipping, if desired.
Parameters
env the target envelope. Despite this method name, the envelope CRS is ignored.
Returns
an affine transform from this grid extent to the given envelope, expressed as a matrix.
References GridExtent.coordinates, and GridExtent.getDimension().
Referenced by GridExtent.toCRS(), and GridExtent.toEnvelope().
{
         final int          srcDim = getDimension();
         final int          tgtDim = env.getDimension();
         final MatrixSIS    affine = Matrices.create(tgtDim + 1, srcDim + 1, ExtendedPrecisionMatrix.ZERO);
         final DoubleDouble scale  = new DoubleDouble();
         final DoubleDouble offset = new DoubleDouble();
         for (int j=0; j<tgtDim; j++) {
             if (j < srcDim) {
                 offset.set(coordinates[j]);
                 scale.set(coordinates[j + srcDim]);
                 scale.subtract(offset);
                 scale.add(1);
                 scale.inverseDivideGuessError(env.getSpan(j));
                 if (!offset.isZero()) {                     // Use `if` for keeping the value if scale is NaN.
                     offset.multiply(scale);
                     offset.negate();
                 }
                 offset.addGuessError(env.getMinimum(j));
                 affine.setNumber(j, srcDim, offset);
             } else {
                 scale.value = Double.NaN;
                 scale.error = Double.NaN;
             }
             affine.setNumber(j, j, scale);
         }
         affine.setElement(tgtDim, srcDim, 1);
         return affine;
     }
equals() [1/2]
final boolean equals (final Object object)
Compares the specified object with this grid envelope for equality.
This method delegates to
equals(object, ComparisonMode.STRICT)
.
Parameters
object the object to compare with this grid envelope for equality.
Returns
true
if the given object is equal to this grid envelope.
{
         return equals(object, ComparisonMode.STRICT);
     }
equals() [2/2]
boolean equals (final Object object, final ComparisonMode mode)
Compares the specified object with this grid envelope for equality.
If the mode is ComparisonMode#IGNORE_METADATA or more flexible, then the getAxisType(int) axis types} are ignored.
Parameters
object the object to compare with this grid envelope for equality.
mode the strictness level of the comparison.
Returns
true
if the given object is equal to this grid envelope.
Since
1.1
References GridExtent.coordinates, GridExtent.GridExtent(), and GridExtent.types.
{
         if (object == this) {
             return true;
         }
         if (object instanceof GridExtent) {
             final GridExtent other = (GridExtent) object;
             if (Arrays.equals(coordinates, other.coordinates)) {
                 switch (mode) {
                     case STRICT:      if (!getClass().equals(object.getClass())) return false;  // else fallthrough
                     case BY_CONTRACT: if (!Arrays.equals(types, other.types))    return false;  // else fallthrough
                     default:          return true;
                 }
             }
         }
         return false;
     }
expand()
GridExtent expand (final long... margins)
Expands or shrinks this grid extent by the given amount of cells along each dimension.
This method adds the given margins to the getHigh(int) high coordinates} and subtracts the same margins to the getLow(int) low coordinates}.
Parameters
margins amount of cells to add or subtract.
Returns
a grid extent expanded by the given amount, or
this
if there is no change.
Exceptions
ArithmeticException if expanding this extent by the given margins overflows
long
capacity.
References GridExtent.coordinates, GridExtent.getDimension(), GridExtent.GridExtent(), and GridExtent.resize().
{
         ArgumentChecks.ensureNonNull("margins", margins);
         final int m = getDimension();
         final int length = Math.min(m, margins.length);
         final GridExtent resize = new GridExtent(this);
         final long[] c = resize.coordinates;
         for (int i=0; i<length; i++) {
             final long margin = margins[i];
             c[i] = Math.subtractExact(c[i], margin);
             c[i+m] = Math.addExact(c[i+m], margin);
         }
         return Arrays.equals(c, coordinates) ? this : resize;
     }
getAxisIdentification()
final Object getAxisIdentification (final int index, final int indexShown) package
Returns the axis number followed by the localized axis type if available.
This is used for error messages only.
Parameters
index index of the dimension as stored in this grid extent.
indexShown index to write in the message. Often the same as
index
.
References GridExtent.types.
Referenced by DisjointExtentException.DisjointExtentException(), GridExtent.getSubspaceDimensions(), GridExtent.GridExtent(), FractionalGridCoordinates.pointOutsideCoverage(), GridExtent.slice(), FractionalGridCoordinates.toExtent(), and GridExtent.validateCoordinates().
{
         if (types != null) {
             final DimensionNameType type = types[index];
             if (type != null) {
                 return indexShown + " (" + Types.getCodeTitle(type) + ')';
             }
         }
         return indexShown;
     }
getAxisType()
Optional<DimensionNameType> getAxisType (final int index)
Returns the type (vertical, temporal, …) of grid axis at given dimension.
This information is provided because the grid axis type can not always be inferred from the context. Some examples are:
getAxisType(0)
may return DimensionNameType#COLUMN, TRACK or LINE.
getAxisType(1)
may return DimensionNameType#ROW, CROSS_TRACK or SAMPLE.
getAxisType(2)
may return DimensionNameType#VERTICAL.
getAxisType(3)
may return DimensionNameType#TIME.
Above are only examples; there is no constraint on axis order. In particular grid axes do not need to be in the same order than the corresponding GridGeometry::getCoordinateReferenceSystem() coordinate reference system} axes.
Parameters
index the dimension for which to obtain the axis type.
Returns
the axis type at the given dimension. May be absent if the type is unknown.
Exceptions
IndexOutOfBoundsException if the given index is negative or is equals or greater than the getDimension() grid dimension}.
References GridExtent.getDimension(), and GridExtent.types.
{
         ArgumentChecks.ensureValidIndex(getDimension(), index);
         return Optional.ofNullable((types != null) ? types[index] : null);
     }
getDimension()
final int getDimension ()
Returns the number of dimensions.
Returns
the number of dimensions.
See also
reduce(int...)
References GridExtent.coordinates.
Referenced by GridExtent.appendTo(), GridExtent.cornerToCRS(), GridExtent.expand(), GridExtent.getAxisType(), GridExtent.getHigh(), GridExtent.getLow(), GridExtent.getPointOfInterest(), BufferedGridCoverage.getSampleCount(), GridExtent.getSize(), GridExtent.getSubDimension(), GridExtent.getSubspaceDimensions(), GridExtent.GridExtent(), GridExtent.insert(), FractionalGridCoordinates.pointOutsideCoverage(), GridExtent.reduce(), GridCoverage2D.render(), GridExtent.resize(), GridCoverageBuilder2.setValues(), GridExtent.slice(), GridExtent.startsAtZero(), GridExtent.subsample(), GridExtent.toCRS(), FractionalGridCoordinates.toExtent(), and GridExtent.validateCoordinates().
{
         return coordinates.length >>> 1;
     }
getHigh() [1/2]
GridCoordinates getHigh ()
Returns the valid maximum grid coordinates, inclusive.
The sequence contains a maximum value for each dimension of the grid coverage.
Returns
the valid maximum grid coordinates, inclusive.
References GridExtent.coordinates, and GridExtent.getDimension().
Referenced by DisjointExtentException.DisjointExtentException(), FractionalGridCoordinates.pointOutsideCoverage(), GridCoverage2D.render(), and FractionalGridCoordinates.toExtent().
{
         return new GridCoordinatesView(coordinates, getDimension());
     }
getHigh() [2/2]
long getHigh (final int index)
Returns the valid maximum inclusive grid coordinate along the specified dimension.
Parameters
index the dimension for which to obtain the coordinate value.
Returns
the high coordinate value at the given dimension, inclusive.
Exceptions
IndexOutOfBoundsException if the given index is negative or is equals or greater than the getDimension() grid dimension}.
See also
getHigh()
getLow(int)
References GridExtent.coordinates, and GridExtent.getDimension().
{
         final int dimension = getDimension();
         ArgumentChecks.ensureValidIndex(dimension, index);
         return coordinates[index + dimension];
     }
getLow() [1/2]
GridCoordinates getLow ()
Returns the valid minimum grid coordinates, inclusive.
The sequence contains a minimum value for each dimension of the grid coverage.
Returns
the valid minimum grid coordinates, inclusive.
References GridExtent.coordinates.
Referenced by DisjointExtentException.DisjointExtentException(), GridCoverage2D.GridCoverage2D(), FractionalGridCoordinates.pointOutsideCoverage(), GridCoverage2D.render(), GridExtent.sliceByRatio(), and FractionalGridCoordinates.toExtent().
{
         return new GridCoordinatesView(coordinates, 0);
     }
getLow() [2/2]
long getLow (final int index)
Returns the valid minimum inclusive grid coordinate along the specified dimension.
Parameters
index the dimension for which to obtain the coordinate value.
Returns
the low coordinate value at the given dimension, inclusive.
Exceptions
IndexOutOfBoundsException if the given index is negative or is equals or greater than the getDimension() grid dimension}.
See also
getLow()
getHigh(int)
References GridExtent.coordinates, and GridExtent.getDimension().
{
         ArgumentChecks.ensureValidIndex(getDimension(), index);
         return coordinates[index];
     }
getPointOfInterest()
double [] getPointOfInterest ()
Returns the grid coordinates of a representative point.
This point may be used for estimating a GridGeometry::getResolution(boolean) grid resolution}. The default implementation returns the median (or center) coordinates of this grid extent, but subclasses can override this method if another point is considered more representative.
Returns
the grid coordinates of a representative point.
References GridExtent.coordinates, and GridExtent.getDimension().
{
         final int dimension = getDimension();
         final double[] center = new double[dimension];
         for (int i=0; i<dimension; i++) {
             /*
              * We want the average of (low + hi+1). However for the purpose of computing an average, it does
              * not matter if we add 1 to `low` or `hi`. So we add 1 to `low` because it should not overflow.
              */
             center[i] = MathFunctions.average(Math.incrementExact(coordinates[i]), coordinates[i + dimension]);
         }
         return center;
     }
getSize() [1/2]
long getSize (final int index)
Returns the number of integer grid coordinates along the specified dimension.
This is equal to
getHigh(dimension) - getLow(dimension) + 1
.
Parameters
index the dimension for which to obtain the size.
Returns
the number of integer grid coordinates along the given dimension.
Exceptions
IndexOutOfBoundsException if the given index is negative or is equals or greater than the getDimension() grid dimension}.
ArithmeticException if the size is too large for the
long
primitive type.
See also
getLow(int)
getHigh(int)
References GridExtent.coordinates, and GridExtent.getDimension().
Referenced by BufferedGridCoverage.getSampleCount(), GridCoverage2D.GridCoverage2D(), GridCoverageBuilder2.setValues(), and GridExtent.sliceByRatio().
{
         final int dimension = getDimension();
         ArgumentChecks.ensureValidIndex(dimension, index);
         return Math.incrementExact(Math.subtractExact(coordinates[dimension + index], coordinates[index]));
     }
getSize() [2/2]
double getSize (final int index, final boolean minusOne)
Returns the number of grid coordinates as a double precision floating point value.
Invoking this method is equivalent to invoking getSize(int) and converting the result from
long
to the
double
primitive type, except that this method does not overflow (i.e. does not throw ArithmeticException).
Parameters
index the dimension for which to obtain the size.
minusOne
References GridExtent.coordinates, and GridExtent.getDimension().
{
         final int dimension = getDimension();
         ArgumentChecks.ensureValidIndex(dimension, index);
         long size = coordinates[dimension + index] - coordinates[index];        // Unsigned long.
         if (!minusOne && ++size == 0) {
             return 0x1P64;                          // Unsigned integer overflow. Result is 2^64.
         }
         return Numerics.toUnsignedDouble(size);
     }
getSubDimension()
final int getSubDimension () package
Returns the number of dimensions where this grid extent has a size greater than 1.
This is a value between 0 and getDimension() inclusive.
Returns
the number of dimensions where this grid extent has a size greater than 1.
See also
getSubspaceDimensions(int)
References GridExtent.coordinates, and GridExtent.getDimension().
{
         int n = 0;
         final int dimension = getDimension();
         for (int i=0; i<dimension; i++) {
             if (coordinates[i] != coordinates[i + dimension]) n++;
         }
         return n;
     }
getSubspaceDimensions()
int [] getSubspaceDimensions (final int s)
Returns indices of all dimensions where this grid extent has a size greater than 1.
This method can be used for getting the grid extent of a s-dimensional slice in a n-dimensional cube where s ≦ n.
Example: suppose that we want to get a two-dimensional slice (y,z) in a four-dimensional data cube (x,y,z,t). The first step is to specify the x and t coordinates of the slice. In this example we set x to 5 and t to 8.
{ java GridGeometry grid = ...; // Geometry of the (x,y,z,t) grid. GridGeometry slice4D = grid.slice(new GeneralDirectPosition(5, NaN, NaN, 8)); }
Above code created a slice at the requested position, but that slice still have 4 dimensions. It is a "slice" because the x and t dimensions of
slice4D
have only one cell. If a two-dimensional slice is desired, then above operations can be completed as below. In this example, the result of
getSubspaceDimensions(2)
call will be {1,2}.
{ java int[] subDimensions = slice4D.getExtent().getSubspaceDimensions(2); GridGeometry slice2D = slice4D.reduce(subDimensions); }
Note that in this particular example, it would have been more efficient to execute
grid.reduce(1,2)
directly. This
getSubspaceDimensions(int)
method is more useful for inferring a
slice2D
from a
slice4D
which has been created elsewhere, or when we do not really want the
slice2D
but only its dimension indices.
This method returns exactly s indices. If there is more than s dimensions having a getSize(int) size} greater than 1, then a SubspaceNotSpecifiedException is thrown. If there is less than s dimensions having a size greater than 1, then the returned list of dimensions is completed with some dimensions of size 1, starting with the first dimensions in this grid extent, until there is exactly s dimensions. If this grid extent does not have at least s dimensions, then a CannotEvaluateException is thrown.
Parameters
s number of dimensions of the sub-space.
Returns
indices of sub-space dimensions, in increasing order in an array of length s.
Exceptions
SubspaceNotSpecifiedException if there is more than s dimensions having a size greater than 1.
CannotEvaluateException if this grid extent does not have at least s dimensions.
References GridExtent.coordinates, GridExtent.getAxisIdentification(), and GridExtent.getDimension().
Referenced by GridCoverage2D.GridCoverage2D().
{
         ArgumentChecks.ensurePositive("s", s);
         final int m = getDimension();
         if (s > m) {
             throw new CannotEvaluateException(Resources.format(Resources.Keys.GridEnvelopeMustBeNDimensional_1, s));
         }
         final int[] selected = new int[s];
         int count = 0;
         for (int i=0; i<m; i++) {
             final long low  = coordinates[i];
             final long high = coordinates[i+m];
             if (low != high) {
                 if (count < s) {
                     selected[count++] = i;
                 } else {
                     throw new SubspaceNotSpecifiedException(Resources.format(Resources.Keys.NoNDimensionalSlice_3,
                                     s, getAxisIdentification(i,i), Numerics.toUnsignedDouble(high - low)));
                 }
             }
         }
         if (s != count) {
             for (int i=0; ; i++) {
                 // An IndexOutOfBoundsException would be a bug in our algorithm.
                 if (coordinates[i] == coordinates[i+m]) {
                     selected[count++] = i;
                     if (count == s) break;
                 }
             }
             Arrays.sort(selected);
         }
         return selected;
     }
hashCode()
int hashCode ()
Returns a hash value for this grid envelope.
This value needs not to remain consistent between different implementations of the same class.
Returns
a hash value for this grid envelope.
References GridExtent.coordinates, GridExtent.serialVersionUID, and GridExtent.types.
{
         return Arrays.hashCode(coordinates) + Arrays.hashCode(types) ^ (int) serialVersionUID;
     }
insert()
GridExtent insert (final int offset, final DimensionNameType axisType, final long low, long high, final boolean isHighIncluded)
Returns a new grid envelope with the specified dimension inserted at the given index in this grid envelope.
To append a new dimension after all existing dimensions, set
offset
to getDimension().
Parameters
offset where to insert the new dimension, from 0 to getDimension() inclusive.
axisType the type of the grid axis to add, or
null
if unspecified.
low the valid minimum grid coordinate (always inclusive).
high the valid maximum grid coordinate, inclusive or exclusive depending on the next argument.
isHighIncluded
References GridExtent.coordinates, GridExtent.getDimension(), GridExtent.GridExtent(), GridExtent.types, and GridExtent.validateCoordinates().
{
         final int dimension = getDimension();
         ArgumentChecks.ensureBetween("offset", 0, dimension, offset);
         if (!isHighIncluded) {
             high = Math.decrementExact(high);
         }
         final int newDim = dimension + 1;
         DimensionNameType[] axisTypes = null;
         if (types != null || axisType != null) {
             if (types != null) {
                 axisTypes = ArraysExt.insert(types, offset, 1);
             } else {
                 axisTypes = new DimensionNameType[newDim];
             }
             axisTypes[offset] = axisType;
         }
         final GridExtent ex = new GridExtent(newDim, axisTypes);
         System.arraycopy(coordinates, 0,                  ex.coordinates, 0,                   offset);
         System.arraycopy(coordinates, offset,             ex.coordinates, offset + 1,          dimension - offset);
         System.arraycopy(coordinates, dimension,          ex.coordinates, newDim,              offset);
         System.arraycopy(coordinates, dimension + offset, ex.coordinates, newDim + offset + 1, dimension - offset);
         ex.coordinates[offset]          = low;
         ex.coordinates[offset + newDim] = high;
         ex.validateCoordinates();
         return ex;
     }
reduce()
GridExtent reduce (int... dimensions)
Returns a grid envelope that encompass only some dimensions of this grid envelope.
This method copies the specified dimensions of this grid envelope into a new grid envelope. The given dimensions must be in strictly ascending order without duplicated values. The number of dimensions of the sub grid envelope will be
dimensions.length
.
This method performs a <cite>dimensionality reduction</cite> and can be used as the converse of insert(int, DimensionNameType, long, long, boolean). This method can not be used for changing dimension order.
Parameters
dimensions the dimensions to select, in strictly increasing order.
Returns
the sub-envelope, or
this
if the given array contains all dimensions of this grid extent.
Exceptions
IndexOutOfBoundsException if an index is out of bounds.
See also
getSubspaceDimensions(int)
GridGeometry::reduce(int...)
References GridExtent.coordinates, GridExtent.getDimension(), GridExtent.GridExtent(), GridExtent.types, and GridExtent.verifyDimensions().
{
         final int sd = getDimension();
         dimensions = verifyDimensions(dimensions, sd);
         if (dimensions == null) {
             return this;
         }
         final int td = dimensions.length;
         DimensionNameType[] tt = null;
         if (types != null) {
             tt = new DimensionNameType[td];
             for (int i=0; i<td; i++) {
                 tt[i] = types[dimensions[i]];
             }
         }
         final GridExtent sub = new GridExtent(td, tt);
         for (int i=0; i<td; i++) {
             final int j = dimensions[i];
             sub.coordinates[i]    = coordinates[j];
             sub.coordinates[i+td] = coordinates[j+sd];
         }
         return sub;
     }
resize()
GridExtent resize (final long... sizes)
Sets the size of this grid extent to the given values.
This method modifies grid coordinates as if they were multiplied by (given size) / (getSize(int) current size}), rounded toward zero and with the value farthest from zero adjusted by ±1 for having a size exactly equals to the specified value. In the common case where the getLow(int) low value} is zero, this is equivalent to setting the getHigh(int) high value} to
size
- 1.
The length of the given array should be equal to getDimension(). If the array is shorter, missing dimensions have their size unchanged. If the array is longer, extra sizes are ignored.
Parameters
sizes the new grid sizes for each dimension.
Returns
a grid extent having the given sizes, or
this
if there is no change.
Exceptions
ArithmeticException if resizing this extent to the given size overflows
long
capacity.
See also
GridDerivation::resize(GridExtent, double...)
References GridExtent.coordinates, GridExtent.getDimension(), and GridExtent.GridExtent().
Referenced by GridExtent.expand().
{
         ArgumentChecks.ensureNonNull("sizes", sizes);
         final int m = getDimension();
         final int length = Math.min(m, sizes.length);
         final GridExtent resize = new GridExtent(this);
         final long[] c = resize.coordinates;
         for (int i=0; i<length; i++) {
             final long size = sizes[i];
             if (size <= 0) {
                 throw new IllegalArgumentException(Errors.format(
                         Errors.Keys.ValueNotGreaterThanZero_2, Strings.toIndexed("sizes", i), size));
             }
             long lower = c[i];
             long upper = c[i+m];
             final long current = Math.incrementExact(Math.subtractExact(upper, lower));
             if (Math.abs(lower) <= Math.abs(upper)) {
                 lower = Numerics.multiplyDivide(lower, size, current);
                 upper = Math.addExact(lower, size - 1);
             } else {
                 upper = Numerics.multiplyDivide(upper, size, current);
                 lower = Math.subtractExact(upper, size - 1);
             }
             c[i  ] = lower;
             c[i+m] = upper;
         }
         return Arrays.equals(c, coordinates) ? this : resize;
     }
slice()
final GridExtent slice (final DirectPosition slicePoint, final int [] modifiedDimensions) package
Creates a new grid extent which represent a slice of this grid at the given point.
The given point may have less dimensions than this grid extent, in which case the dimensions must be specified in the
modifiedDimensions
array. Coordinates in the given point will be rounded to nearest integer.
This method does not reduce the number of dimensions of the grid extent. For dimensionality reduction, see reduce(int...).
Parameters
slicePoint where to take a slice. NaN values are handled as if their dimensions were absent.
modifiedDimensions mapping from
slicePoint
dimensions to this
GridExtent
dimensions, or
null
if
slicePoint
contains all grid dimensions in same order.
Returns
a grid extent for the specified slice.
Exceptions
PointOutsideCoverageException if the given point is outside the grid extent.
References GridExtent.coordinates, GridExtent.getAxisIdentification(), GridExtent.getDimension(), and GridExtent.GridExtent().
Referenced by GridExtent.sliceByRatio().
{
         final GridExtent slice = new GridExtent(this);
         final int n = slicePoint.getDimension();
         final int m = getDimension();
         for (int k=0; k<n; k++) {
             double p = slicePoint.getOrdinate(k);
             if (!Double.isNaN(p)) {
                 final long c = Math.round(p);
                 final int i = (modifiedDimensions != null) ? modifiedDimensions[k] : k;
                 final long low  = coordinates[i];
                 final long high = coordinates[i + m];
                 if (c >= low && c <= high) {
                     slice.coordinates[i + m] = slice.coordinates[i] = c;
                 } else {
                     final StringBuilder b = new StringBuilder();
                     for (int j=0; j<n; j++) {
                         if (j != 0) b.append(", ");
                         p = slicePoint.getOrdinate(j);
                         if (Double.isNaN(p)) b.append("NaN");
                         else b.append(Math.round(p));
                     }
                     throw new PointOutsideCoverageException(Resources.format(
                             Resources.Keys.GridCoordinateOutsideCoverage_4,
                             getAxisIdentification(i,k), low, high, b.toString()));
                 }
             }
         }
         return Arrays.equals(coordinates, slice.coordinates) ? this : slice;
     }
sliceByRatio()
final GridExtent sliceByRatio (final DirectPosition slicePoint, final double sliceRatio, final int [] dimensionsToKeep) package
Returns a slice of this given grid extent computed by a ratio between 0 and 1 inclusive.
This is a helper method for GridDerivation#sliceByRatio(double, int...) implementation.
Parameters
slicePoint a pre-allocated direct position to be overwritten by this method.
sliceRatio the ratio to apply on all grid dimensions except the ones to keep.
dimensionsToKeep the grid dimension to keep unchanged.
References GridExtent.getLow(), GridExtent.getSize(), and GridExtent.slice().
{
         for (int i=slicePoint.getDimension(); --i >= 0;) {
             slicePoint.setOrdinate(i, sliceRatio * getSize(i, true) + getLow(i));       // TODO: use Math.fma
         }
         for (int i=0; i<dimensionsToKeep.length; i++) {
             slicePoint.setOrdinate(dimensionsToKeep[i], Double.NaN);
         }
         return slice(slicePoint, null);
     }
startsAtZero()
boolean startsAtZero ()
Returns.
true
if all low coordinates are zero. This is a very common case since many grids start their cell numbering at zero.
Returns
whether all low coordinates are zero.
References GridExtent.coordinates, and GridExtent.getDimension().
{
         for (int i = getDimension(); --i >= 0;) {
             if (coordinates[i] != 0) {
                 return false;
             }
         }
         return true;
     }
subsample()
GridExtent subsample (final int... periods)
Creates a new grid extent subsampled by the given amount of cells along each grid dimensions.
This method divides getLow(int) low coordinates} and getSize(int) grid sizes} by the given periods, rounding toward zero. The getHigh(int) high coordinates} are adjusted accordingly (this is often equivalent to dividing high coordinates by the periods too, but a difference of one cell may exist).
Note: The envelope computed from a grid extent may become larger after subsampling, not smaller. This effect can be understood intuitively if we consider that cells become larger after subsampling, which implies that accurate representation of the same envelope may require fractional cells on some grid borders.
This method does not reduce the number of dimensions of the grid extent. For dimensionality reduction, see reduce(int...).
Parameters
periods the subsamplings. Length shall be equal to the number of dimension and all values shall be greater than zero.
Returns
the subsampled extent, or
this
is subsampling results in the same extent.
Exceptions
IllegalArgumentException if a period is not greater than zero.
See also
GridDerivation::subsample(int...)
References GridExtent.coordinates, GridExtent.getDimension(), and GridExtent.GridExtent().
{
         ArgumentChecks.ensureNonNull("periods", periods);
         final int m = getDimension();
         ArgumentChecks.ensureDimensionMatches("periods", m, periods);
         final GridExtent sub = new GridExtent(this);
         for (int i=0; i<m; i++) {
             final int s = periods[i];
             if (s > 1) {
                 final int j = i + m;
                 long low  = coordinates[i];
                 long size = coordinates[j] - low + 1;                      // Result is an unsigned number.
                 if (size == 0) {
                     throw new ArithmeticException(Errors.format(Errors.Keys.IntegerOverflow_1, Long.SIZE));
                 }
                 long r = Long.divideUnsigned(size, s);
                 if (r*s == size) r--;                           // Make inclusive if the division did not already rounded toward 0.
                 sub.coordinates[i] = low /= s;
                 sub.coordinates[j] = low + r;
             } else if (s <= 0) {
                 throw new IllegalArgumentException(Errors.format(Errors.Keys.ValueNotGreaterThanZero_2, Strings.toIndexed("periods", i), s));
             }
         }
         return Arrays.equals(coordinates, sub.coordinates) ? this : sub;
     }
toCRS()
final GeneralEnvelope toCRS (final MathTransform cornerToCRS, final MathTransform gridToCRS, final Envelope fallback) throws TransformException package
Transforms this grid extent to a "real world" envelope using the given transform.
The transform shall map cell corner to real world coordinates.
Parameters
cornerToCRS a transform from cell corners to real world coordinates.
gridToCRS the transform specified by the user. May be the same as
cornerToCRS
. If different, then this is assumed to map cell centers instead than cell corners.
fallback bounds to use if some values still NaN, or
null
if none.
Returns
this grid extent in real world coordinates.
Exceptions
TransformException if the envelope can not be computed with the given transform.
See also
#GridExtent(AbstractEnvelope, GridRoundingMode, int[], GridExtent, int[])
References GridExtent.coordinates, GridExtent.cornerToCRS(), and GridExtent.getDimension().
Referenced by GridExtent.toEnvelope().
     {
         final int dimension = getDimension();
         GeneralEnvelope envelope = new GeneralEnvelope(dimension);
         for (int i=0; i<dimension; i++) {
             // The +1.0 is for making high coordinate exclusive. See GridExtent(GridExtent, int...) for a discussion.
             envelope.setRange(i, coordinates[i], coordinates[i + dimension] + 1.0);
         }
         envelope = Envelopes.transform(cornerToCRS, envelope);
         if (envelope.isEmpty()) try {
             /*
              * If the envelope contains some NaN values, try to replace them by constant values inferred from the math transform.
              * We must use the MathTransform specified by the user (gridToCRS), not necessarily the cornerToCRS transform, because
              * inferring a 'cornerToCRS' by translating a 'centerToCRS' by 0.5 cell increase the amount of NaN values in the matrix.
              * For giving a chance to TransformSeparator to perform its work, we need the minimal amount of NaN values.
              */
             final boolean isCenter = (gridToCRS != cornerToCRS);
             TransformSeparator separator = null;
             for (int srcDim=0; srcDim < dimension; srcDim++) {
                 if (coordinates[srcDim + dimension] == 0 && coordinates[srcDim] == 0) {
                     /*
                      * At this point we found a grid dimension with [0 … 0] range. Only this specific range is processed because
                      * it is assumed associated to NaN scale factors in the 'gridToCRS' matrix, since the resolution is computed
                      * by 0/0.  We require the range to be [0 … 0] instead of [n … n] because if grid indices are not zero, then
                      * we would need to know the scale factors for computing the offset.
                      */
                     if (separator == null) {
                         separator = new TransformSeparator(gridToCRS);
                     }
                     separator.addSourceDimensionRange(srcDim, srcDim + 1);
                     final Matrix component = MathTransforms.getMatrix(separator.separate());
                     if (component != null) {
                         final int[] targets = separator.getTargetDimensions();
                         for (int j=0; j<targets.length; j++) {
                             final int tgtDim = targets[j];
                             double lower = envelope.getLower(tgtDim);
                             double upper = envelope.getUpper(tgtDim);
                             final double value = component.getElement(j, component.getNumCol() - 1);
                             /*
                              * Replace only the envelope NaN values by the translation term (non-NaN values are left unchanged).
                              * If the gridToCRS map cell corners, then we update only the lower bound since the transform maps
                              * lower-left corner; the upper bound is unknown. If the gridToCRS maps cell center, then we update
                              * both lower and upper bounds to a value assumed to be in the center; the span is set to zero.
                              */
                             if (isCenter) {
                                 double span = upper - value;
                                 if (Double.isNaN(span)) {
                                     span = value - lower;
                                     if (Double.isNaN(span)) {
                                         span = 0;
                                     }
                                 }
                                 if (Double.isNaN(lower)) lower = value - span;
                                 if (Double.isNaN(upper)) upper = value + span;
                             } else if (Double.isNaN(lower)) {
                                 lower = value;
                             }
                             envelope.setRange(tgtDim, lower, upper);
                         }
                     }
                     separator.clear();
                 }
             }
             /*
              * If above block has been unable to fix all NaN values, fix the remaining NaNs by copying the corresponding
              * coordinates from the fallback envelope. It should happen only for dimensions with a thickness of 1, i.e.
              * when `low == high` but not necessarily `low == 0` and `high == 0` (contrarily to above block). We use this
              * fallback is last resort because the envelope may be less reliable than values computed from `gridToCRS`.
              */
             if (fallback != null) {
                 for (int tgtDim = envelope.getDimension(); --tgtDim >= 0;) {
                     boolean modified = false;
                     double lower = envelope.getLower(tgtDim);
                     double upper = envelope.getUpper(tgtDim);
                     if (Double.isNaN(lower)) {lower = fallback.getMinimum(tgtDim); modified = true;}
                     if (Double.isNaN(upper)) {upper = fallback.getMaximum(tgtDim); modified = true;}
                     if (modified && !(lower > upper)) {                // Use '!' for accepting NaN.
                         envelope.setRange(tgtDim, lower, upper);
                     }
                 }
             }
         } catch (FactoryException e) {
             GridGeometry.recoverableException(e);
         }
         return envelope;
     }
toEnvelope()
GeneralEnvelope toEnvelope (final MathTransform cornerToCRS) throws TransformException
Transforms this grid extent to a "real world" envelope using the given transform.
The transform shall map cell corner to real world coordinates.
Parameters
cornerToCRS a transform from cell corners to real world coordinates.
Returns
this grid extent in real world coordinates.
Exceptions
TransformException if the envelope can not be computed with the given transform.
See also
GridGeometry::getEnvelope()
org.opengis.referencing.datum.PixelInCell::CELL_CORNER
Since
1.1
References GridExtent.cornerToCRS(), and GridExtent.toCRS().
{
         ArgumentChecks.ensureNonNull("cornerToCRS", cornerToCRS);
         return toCRS(cornerToCRS, cornerToCRS, null);
     }
toString()
String toString ()
Returns a string representation of this grid envelope.
The returned string is implementation dependent and is provided for debugging purposes only.
References GridExtent.appendTo().
{
         final StringBuilder out = new StringBuilder(256);
         try {
             appendTo(out, Vocabulary.getResources((Locale) null));
         } catch (IOException e) {
             throw new UncheckedIOException(e);
         }
         return out.toString();
     }
typeFromAxes()
static DimensionNameType [] typeFromAxes (final CoordinateReferenceSystem crs, final int dimension) static package
Infers the axis types from the given coordinate reference system.
Parameters
crs the coordinate reference system, or
null
.
dimension number of name type to infer. Shall not be greater than the CRS dimension.
References GridExtent.AXIS_DIRECTIONS.
Referenced by GridCoverage2D.createExtent(), GridExtent.GridExtent(), and GridCoverageBuilder2.setValues().
{
         DimensionNameType[] axisTypes = null;
         if (crs != null) {
             final CoordinateSystem cs = crs.getCoordinateSystem();
             for (int i=0; i<dimension; i++) {
                 final DimensionNameType type = AXIS_DIRECTIONS.get(AxisDirections.absolute(cs.getAxis(i).getDirection()));
                 if (type != null) {
                     if (axisTypes == null) {
                         axisTypes = new DimensionNameType[dimension];
                     }
                     axisTypes[i] = type;
                 }
             }
         }
         return axisTypes;
     }
validateAxisTypes()
static DimensionNameType [] validateAxisTypes (DimensionNameType [] types) throws IllegalArgumentException static private
Verifies that the given array (if non-null) contains no duplicated values, then returns a copy of that array.
The returned copy may be shared by many
GridExtent
instances. Consequently it shall not be modified.
Exceptions
IllegalArgumentException if the given array contains duplicated elements.
References GridExtent.DEFAULT_TYPES, and GridExtent.types.
Referenced by GridExtent.GridExtent().
{
         if (types == null) {
             return null;
         }
         if (Arrays.equals(DEFAULT_TYPES, types)) {          // Common case verified before POOL synchronized lock.
             return DEFAULT_TYPES;
         }
         DimensionNameType[] shared = POOL.get(types);
         if (shared == null) {
             /*
              * Verify the array only if it was not found in the pool. Arrays in the pool were already validated,
              * so do not need to be verified again. The check performed here is inefficient (nested loop), but it
              * should be okay since the arrays are usually small (less than 5 elements) and the checks should not
              * be done often (because of the pool).
              */
             types = types.clone();
             for (int i=1; i<types.length; i++) {
                 final DimensionNameType t = types[i];
                 if (t != null) {
                     for (int j=i; --j >= 0;) {
                         if (t.equals(types[j])) {
                             throw new IllegalArgumentException(Errors.format(Errors.Keys.DuplicatedElement_1, t));
                         }
                     }
                 }
             }
             shared = POOL.putIfAbsent(types, types);
             if (shared == null) {
                 return types;
             }
         }
         return shared;
     }
validateCoordinates()
void validateCoordinates () throws IllegalArgumentException private
Checks if coordinate values in the low part are less than or equal to the corresponding coordinate value in the high part.
Exceptions
IllegalArgumentException if a coordinate value in the low part is greater than the corresponding coordinate value in the high part.
References GridExtent.getAxisIdentification(), and GridExtent.getDimension().
Referenced by GridExtent.GridExtent(), and GridExtent.insert().
{
         final int dimension = getDimension();
         for (int i=0; i<dimension; i++) {
             final long lower = coordinates[i];
             final long upper = coordinates[i + dimension];
             if (lower > upper) {
                 throw new IllegalArgumentException(Resources.format(
                         Resources.Keys.IllegalGridEnvelope_3, getAxisIdentification(i,i), lower, upper));
             }
         }
     }
verifyDimensions()
static int [] verifyDimensions (int [] dimensions, final int limit) static package
Verifies the validity of a given.
dimensions
argument.
Parameters
dimensions the user-supplied argument to validate.
limit maximal number of dimensions, exclusive.
Returns
a clone of the given array, or
null
if the caller can return
this
.
Referenced by GridExtent.reduce().
{
         ArgumentChecks.ensureNonNull("dimensions", dimensions);
         final int n = dimensions.length;
         ArgumentChecks.ensureSizeBetween("dimensions", 1, limit, n);
         dimensions = dimensions.clone();
         if (!ArraysExt.isSorted(dimensions, true)) {
             throw new IllegalArgumentException(Resources.format(Resources.Keys.NotStrictlyOrderedDimensions));
         }
         int d = dimensions[0];
         if (d >= 0) {
             d = dimensions[n - 1];
             if (d < limit) {
                 return (n != limit) ? dimensions : null;
             }
         }
         throw new IndexOutOfBoundsException(Errors.format(Errors.Keys.IndexOutOfBounds_1, d));
     }
Member Data Documentation
AXIS_DIRECTIONS
final Map<AxisDirection,DimensionNameType> AXIS_DIRECTIONS static private
The dimension name types for given coordinate system axis directions.
This map contains only the "positive" axis directions.
Todo:
Verify if there is more directions to add as of ISO 19111:2018.
Referenced by GridExtent.typeFromAxes().
coordinates
final long [] coordinates private
Minimum and maximum grid coordinates.
The first half contains minimum coordinates (inclusive), while the last half contains maximum coordinates (inclusive). Note that the later inclusiveness is the opposite of Java2D usage but conforms to ISO specification.
Referenced by GridExtent.appendTo(), GridExtent.cornerToCRS(), GridExtent.equals(), GridExtent.expand(), GridExtent.getDimension(), GridExtent.getHigh(), GridExtent.getLow(), GridExtent.getPointOfInterest(), GridExtent.getSize(), GridExtent.getSubDimension(), GridExtent.getSubspaceDimensions(), GridExtent.GridExtent(), GridExtent.hashCode(), GridExtent.insert(), GridExtent.reduce(), GridExtent.resize(), GridExtent.slice(), GridExtent.startsAtZero(), GridExtent.subsample(), and GridExtent.toCRS().
DEFAULT_TYPES
final DimensionNameType [] DEFAULT_TYPES static private
Initial value:
= new DimensionNameType[] {
        DimensionNameType.COLUMN,
        DimensionNameType.ROW
    }
Default axis types for the two-dimensional cases.
Referenced by GridExtent.GridExtent(), and GridExtent.validateAxisTypes().
POOL
final WeakValueHashMap<DimensionNameType[],DimensionNameType[]> POOL = new WeakValueHashMap<>(DimensionNameType[].class) static private
A pool of shared DimensionNameType arrays.
We use a pool because a small amount of arrays is shared by most grid extent.
serialVersionUID
final long serialVersionUID = -4717353677844056017L static private
Serial number for inter-operability with different versions.
Referenced by GridExtent.hashCode().
types
final DimensionNameType [] types private
Type of each axis (vertical, temporal, …) or.
null
if unspecified. If non-null, the array length shall be equal to getDimension(). Any array element may be null if unspecified for that particular axis. The same array may be shared by many
GridExtent
instances.
See also
getAxisType(int)
Referenced by GridExtent.appendTo(), GridExtent.equals(), GridExtent.getAxisIdentification(), GridExtent.getAxisType(), GridExtent.GridExtent(), GridExtent.hashCode(), GridExtent.insert(), GridExtent.reduce(), and GridExtent.validateAxisTypes().