jena-geo: MemSize Class Reference
MemSize Class Reference
Returns the amount of space (in bytes) the raster takes.
Public Member Functions
NodeValue exec (NodeValue v)
Detailed Description
Returns the amount of space (in bytes) the raster takes.
Member Function Documentation
exec()
NodeValue exec (NodeValue v)
References CoverageWrapper.extract(), and CoverageWrapper.getXYGeometry().
Referenced by MemSizeTest.testMemSize().
{
                 CoverageWrapper wrapper=CoverageWrapper.extract(v);
                 GridCoverage2D raster=wrapper.getXYGeometry();
         try {
                         return NodeValue.makeInteger(raster.getRenderedImage().getData().getDataBuffer().getSize());
                 } catch (CannotEvaluateException e) {
                         return null;
                 }
         }