jena-geo: HasNoBand Class Reference
HasNoBand Class Reference
Returns true if there is no band with given band number.
Public Member Functions
NodeValue exec (NodeValue v, NodeValue v1)
Detailed Description
Returns true if there is no band with given band number.
If no band number is specified, then band number 1 is assumed.
Member Function Documentation
exec()
NodeValue exec (NodeValue v, NodeValue v1)
References CoverageWrapper.extract(), CoverageWrapper.getParsingGeometry(), and GridCoverage.getSampleDimensions().
Referenced by HasNoBandTest.testRasterHeight().
{
                 CoverageWrapper wrapper=CoverageWrapper.extract(v);
                 GridCoverage raster=wrapper.getParsingGeometry();
                 BigInteger noband=v1.getInteger();
                 return NodeValue.makeBoolean(raster.getSampleDimensions().size()>=noband.intValue());
         }