jena-geo: LongestLineTest Class Reference
LongestLineTest Class Reference
Public Member Functions
void testLongestLine ()
Static Public Attributes
static final String testGeom ="LINESTRING(77.29 29.07,77.42 29.26,77.27 29.31,77.29 29.07)"
static final String testGeom2 ="LINESTRING(5 5 ,10 10)"
static final String result ="LINESTRING(77.42 29.26, 5 5)"
Member Function Documentation
testLongestLine()
void testLongestLine ()
{
         NodeValue geometryLiteral = NodeValue.makeNode(testGeom, WKTDatatype.INSTANCE);
         NodeValue geometryLiteral2 = NodeValue.makeNode(testGeom2, WKTDatatype.INSTANCE);
         LongestLine instance=new LongestLine();
         NodeValue expResult = NodeValue.makeNode(result, WKTDatatype.INSTANCE);
         NodeValue result = instance.exec(geometryLiteral,geometryLiteral2);
         assertEquals(expResult, result);
         }
References LongestLine.exec(), LongestLineTest.result, LongestLineTest.testGeom, and LongestLineTest.testGeom2.
Member Data Documentation
result
final String result ="LINESTRING(77.42 29.26, 5 5)" static
Referenced by LongestLineTest.testLongestLine().
testGeom
final String testGeom ="LINESTRING(77.29 29.07,77.42 29.26,77.27 29.31,77.29 29.07)" static
Referenced by LongestLineTest.testLongestLine().
testGeom2
final String testGeom2 ="LINESTRING(5 5 ,10 10)" static
Referenced by LongestLineTest.testLongestLine().