jena-geo: SelfIntersectionsTest Class Reference
SelfIntersectionsTest Class Reference
Public Member Functions
void testSelfIntersections ()
Static Public Attributes
static final String isRing ="LINESTRING(0 0, 0 1, 1 1, 1 0, 1 1, 0 0)"
static final String point ="MULTIPOINT Z((1 1), (0 0))"
Member Function Documentation
testSelfIntersections()
void testSelfIntersections ()
{
         NodeValue geometryLiteral = NodeValue.makeNode(isRing, WKTDatatype.INSTANCE);
         NodeValue geometryLiteral2 = NodeValue.makeNode(point, WKTDatatype.INSTANCE);
         SelfIntersections instance=new SelfIntersections();
         NodeValue expResult = geometryLiteral2;
         NodeValue result = instance.exec(geometryLiteral);
         assertEquals(expResult, result);
         }
References SelfIntersections.exec(), SelfIntersectionsTest.isRing, and SelfIntersectionsTest.point.
Member Data Documentation
isRing
final String isRing ="LINESTRING(0 0, 0 1, 1 1, 1 0, 1 1, 0 0)" static
Referenced by SelfIntersectionsTest.testSelfIntersections().
point
final String point ="MULTIPOINT Z((1 1), (0 0))" static
Referenced by SelfIntersectionsTest.testSelfIntersections().