jena-geo: PrjFiles Class Reference
PrjFiles Class Reference
Parses and formats PRJ files.
Static Public Member Functions
static CoordinateReferenceSystem read (final File file) throws ContentFormatException, IOException
Parses a PRJ file and returns its content as a coordinate reference system.
static CoordinateReferenceSystem read (final Path file) throws ContentFormatException, IOException
Parses a PRJ file and returns its content as a coordinate reference system.
static CoordinateReferenceSystem read (final URL file) throws ContentFormatException, IOException
Parses a PRJ file from a URL and returns its content as a coordinate reference system.
static CoordinateReferenceSystem read (final ReadableByteChannel in, final boolean close) throws ContentFormatException, IOException
Parses a PRJ file from a channel and returns its content as a coordinate reference system.
static CoordinateReferenceSystem read (final InputStream in, final boolean close) throws ContentFormatException, IOException
Parses a PRJ file from a stream and returns its content as a coordinate reference system.
static CoordinateReferenceSystem read (final BufferedReader in, final boolean close) throws ContentFormatException, IOException
Parses a PRJ file from a reader and returns its content as a coordinate reference system.
static void write (final CoordinateReferenceSystem crs, final File file) throws ContentFormatException, IOException
Formats a coordinate reference system as a PRJ file.
static void write (final CoordinateReferenceSystem crs, final Path file) throws ContentFormatException, IOException
Formats a coordinate reference system as a PRJ file.
static void write (final CoordinateReferenceSystem crs, final WritableByteChannel out) throws ContentFormatException, IOException
Formats a coordinate reference system as a PRJ file in the given channel.
static void write (final CoordinateReferenceSystem crs, final OutputStream out) throws ContentFormatException, IOException
Formats a coordinate reference system as a PRJ file in the given stream.
static void write (final CoordinateReferenceSystem crs, final Writer out) throws ContentFormatException, IOException
Formats a coordinate reference system as a PRJ file in the given writer.
Private Member Functions
PrjFiles ()
Do not allow instantiation of this class.
Static Private Member Functions
static String format (final CoordinateReferenceSystem crs) throws ContentFormatException
Formats the given CRS as a string.
Static Private Attributes
static final String ENCODING = "ISO-8859-1"
The encoding of PRJ files.
Detailed Description
Parses and formats PRJ files.
Those files usually have the
".prj"
suffix and contain the definition of exactly one <cite>Coordinate Reference System</cite> (CRS) in <cite>Well Known Text</cite> (WKT) format. This class allows the definition to span many lines, but the common practice is to provide the full WKT string on a single line.
If the definition is not a valid WKT string (during reads), or if a CRS can not be formatted as a WKT (during writes), then the methods in this class throw a ContentFormatException. This is a subclass of IOException and consequently does not require a try … catch block different than the one for normal I/O operations.
Every files are expected to use the ISO-8859-1 (a.k.a. ISO-LATIN-1) encoding.
Author
Martin Desruisseaux (Geomatys)
Version
3.07
Since
3.05
Constructor & Destructor Documentation
PrjFiles()
PrjFiles () private
Do not allow instantiation of this class.
{
     }
Member Function Documentation
format()
static String format (final CoordinateReferenceSystem crs) throws ContentFormatException static private
Formats the given CRS as a string.
Exceptions
ContentFormatException if the given CRS is not formattable as a WKT.
Referenced by PrjFiles.write().
{
         final WKTFormat format = new WKTFormat(null, null);
         format.setConvention(Convention.WKT1);
         format.setIndentation(WKTFormat.SINGLE_LINE);
         final String wkt = format.format(crs);
         final Warnings warning = format.getWarnings();
         if (warning != null) {
             throw new ContentFormatException(warning.toString());
         }
         return wkt;
     }
read() [1/6]
static CoordinateReferenceSystem read (final File file) throws ContentFormatException, IOException static
Parses a PRJ file and returns its content as a coordinate reference system.
Parameters
file The file to parse. It usually has the
".prj"
suffix,
Returns
The PRJ file content as a coordinate reference system.
Exceptions
ContentFormatException If the content of the PRJ file is an invalid WKT.
IOException If the parsing failed for an other raison.
Deprecated:
use read(Path) instead
Referenced by PrjFiles.read().
{
         return read(new FileInputStream(file), true);
     }
read() [2/6]
static CoordinateReferenceSystem read (final Path file) throws ContentFormatException, IOException static
Parses a PRJ file and returns its content as a coordinate reference system.
Parameters
file The file to parse. It usually has the
".prj"
suffix,
Returns
The PRJ file content as a coordinate reference system.
Exceptions
ContentFormatException If the content of the PRJ file is an invalid WKT.
IOException If the parsing failed for an other raison.
References PrjFiles.read().
{
         return read(Files.newInputStream(file), true);
     }
read() [3/6]
static CoordinateReferenceSystem read (final URL file) throws ContentFormatException, IOException static
Parses a PRJ file from a URL and returns its content as a coordinate reference system.
Parameters
file The file to parse. It usually has the
".prj"
suffix,
Returns
The PRJ file content as a coordinate reference system.
Exceptions
ContentFormatException If the content of the PRJ file is an invalid WKT.
IOException If the parsing failed for an other raison.
References PrjFiles.read().
{
         return read(file.openStream(), true);
     }
read() [4/6]
static CoordinateReferenceSystem read (final ReadableByteChannel in, final boolean close) throws ContentFormatException, IOException static
Parses a PRJ file from a channel and returns its content as a coordinate reference system.
The given channel is not closed by this method, unless the
close
argument is set to
true
. The later case allows this method to close the channel sooner than what could be achieved if the channel was closed by the caller: before the WKT parsing begin.
Parameters
in The channel to read.
close Whatever this method should close the channel.
Returns
The PRJ file content as a coordinate reference system.
Exceptions
ContentFormatException If the content of the PRJ file is an invalid WKT.
IOException If the parsing failed for an other raison.
Since
3.07
References PrjFiles.read().
     {
         return read(Channels.newInputStream(in), close);
     }
read() [5/6]
static CoordinateReferenceSystem read (final InputStream in, final boolean close) throws ContentFormatException, IOException static
Parses a PRJ file from a stream and returns its content as a coordinate reference system.
The given stream is not closed by this method, unless the
close
argument is set to
true
. The later case allows this method to close the stream sooner than what could be achieved if the stream was closed by the caller: before the WKT parsing begin.
Parameters
in The stream to read.
close Whatever this method should close the stream.
Returns
The PRJ file content as a coordinate reference system.
Exceptions
ContentFormatException If the content of the PRJ file is an invalid WKT.
IOException If the parsing failed for an other raison.
References PrjFiles.read().
     {
         return read(new BufferedReader(new InputStreamReader(in, ENCODING)), close);
     }
read() [6/6]
static CoordinateReferenceSystem read (final BufferedReader in, final boolean close) throws ContentFormatException, IOException static
Parses a PRJ file from a reader and returns its content as a coordinate reference system.
The given reader is not closed by this method, unless the
close
argument is set to
true
. The later case allows this method to close the reader sooner than what could be achieved if the reader was closed by the caller: before the WKT parsing begin.
Parameters
in The reader.
close Whatever this method should close the reader.
Returns
The PRJ file content as a coordinate reference system.
Exceptions
ContentFormatException If the content of the PRJ file is an invalid WKT.
IOException If the parsing failed for an other raison.
     {
         StringBuilder buffer = null;
         String wkt=null, line;
         while ((line = in.readLine()) != null) {
             line = line.trim();
             if (!line.isEmpty()) {
                 if (wkt == null) {
                     wkt = line;
                 } else {
                     if (buffer == null) {
                         buffer = new StringBuilder(wkt);
                     }
                     buffer.append('\n').append(line);
                 }
             }
         }
         if (close) {
             in.close();
         }
         if (buffer != null) {
             wkt = buffer.toString();
         }
         if (wkt == null) {
             throw new EOFException(Errors.format(Errors.Keys.EndOfDataFile));
         }
         try {
             return CRS.fromWKT(wkt);
         } catch (FactoryException e) {
             throw new ContentFormatException(e.getLocalizedMessage(), e);
         }
     }
write() [1/5]
static void write (final CoordinateReferenceSystem crs, final File file) throws ContentFormatException, IOException static
Formats a coordinate reference system as a PRJ file.
The file is created only if the given CRS is formattable.
Parameters
crs The PRJ file content as a coordinate reference system.
file The file to create. It usually has the
".prj"
suffix,
Exceptions
ContentFormatException if the given CRS is not formattable as a WKT.
IOException If an other error occurred while writing the file.
References PrjFiles.format().
Referenced by PrjFiles.write().
     {
         final String wkt = format(crs);
         // No need to buffer, because we will write everything (except EOL) in one shot.
         // In addition, OutputStreamWriter already manage its own internal buffer anyway.
         try (Writer out = new OutputStreamWriter(new FileOutputStream(file), ENCODING)) {
             out.write(wkt);
             out.write('\n'); // Use Unix EOL for cross-platform consistency.
         }
     }
write() [2/5]
static void write (final CoordinateReferenceSystem crs, final Path file) throws ContentFormatException, IOException static
Formats a coordinate reference system as a PRJ file.
The file is created only if the given CRS is formattable.
Parameters
crs The PRJ file content as a coordinate reference system.
file The file to create. It usually has the
".prj"
suffix,
Exceptions
ContentFormatException if the given CRS is not formattable as a WKT.
IOException If an other error occurred while writing the file.
References PrjFiles.format().
     {
         final String wkt = format(crs);
         // No need to buffer, because we will write everything (except EOL) in one shot.
         // In addition, OutputStreamWriter already manage its own internal buffer anyway.
         try (Writer out = Files.newBufferedWriter(file, Charset.forName(ENCODING), CREATE, WRITE, TRUNCATE_EXISTING)) {
             out.write(wkt);
             out.write('\n'); // Use Unix EOL for cross-platform consistency.
         }
     }
write() [3/5]
static void write (final CoordinateReferenceSystem crs, final WritableByteChannel out) throws ContentFormatException, IOException static
Formats a coordinate reference system as a PRJ file in the given channel.
The channel is not closed by this method. It is caller responsibility to close it.
Parameters
crs The PRJ file content as a coordinate reference system.
out The channel where to write.
Exceptions
ContentFormatException if the given CRS is not formattable as a WKT.
IOException If an other error occurred while writing the file.
Since
3.07
References PrjFiles.write().
     {
         write(crs, Channels.newOutputStream(out));
     }
write() [4/5]
static void write (final CoordinateReferenceSystem crs, final OutputStream out) throws ContentFormatException, IOException static
Formats a coordinate reference system as a PRJ file in the given stream.
The stream is not closed by this method. It is caller responsibility to close it.
Parameters
crs The PRJ file content as a coordinate reference system.
out The stream where to write.
Exceptions
ContentFormatException if the given CRS is not formattable as a WKT.
IOException If an other error occurred while writing the file.
References PrjFiles.write().
     {
         // No need to buffer - see the above method.
         final Writer writer = new OutputStreamWriter(out, ENCODING);
         write(crs, writer);
         writer.flush();
     }
write() [5/5]
static void write (final CoordinateReferenceSystem crs, final Writer out) throws ContentFormatException, IOException static
Formats a coordinate reference system as a PRJ file in the given writer.
The writer is not closed by this method. It is caller responsibility to close it.
Parameters
crs The PRJ file content as a coordinate reference system.
out The writer.
Exceptions
ContentFormatException if the given CRS is not formattable as a WKT.
IOException If an other error occurred while writing the file.
References PrjFiles.format().
     {
         out.write(format(crs));
         out.write('\n'); // Use Unix EOL for cross-platform consistency.
         // No close - this is caller responsibility.
     }
Member Data Documentation
ENCODING
final String ENCODING = "ISO-8859-1" static private
The encoding of PRJ files.