jena-geo: MetadataFactory Class Reference
MetadataFactory Class Reference
Creates metadata objects of the given Class using the properties given in a Map.
Package Functions
MetadataFactory (final MetadataStandard standard)
Creates a new factory for the given metadata standard.
final Map< String, Class<?> > getDefinition (final Class<?> type)
Returns the property names and expected types for the given class.
private< T > Class<? extends T > guessType (final Class< T > type, final Map<?,?> definition, final Set< String > keys)
Returns the given type or a sub-type which contains all the given key, or.
final< T > T create (final Class< T > type, final Map< String, Class<?>> definition, final Map< String,?> properties, final int position) throws ParseException
Creates a new metadata of the given type, initialized with the property values given in the properties map.
Static Package Attributes
static final MetadataFactory DEFAULT = new MetadataFactory(MetadataStandard.ISO_19115)
The default instance.
Static Private Member Functions
static boolean containsAll (final Map<?,?> definition, final Set<?> keys)
Returns.
Private Attributes
final MetadataStandard standard
The standard implemented by this factory.
Detailed Description
Creates metadata objects of the given Class using the properties given in a Map.
MetadataFactory
tries to instantiate metadata objects using Class#newInstance(). The class given to the create(Class, Map) method is typically a GeoAPI interface (e.g. org.opengis.metadata.citation.Citation), in which case
MetadataFactory
will try to find its implementation class (org.apache.sis.metadata.iso.citation.DefaultCitation). The keys in the map shall be the KeyNamePolicy::UML_IDENTIFIER UML identifiers} of metadata properties, e.g.
"title"
for the value to be returned by org.opengis.metadata.citation.Citation#getTitle().
Author
Martin Desruisseaux (Geomatys)
Constructor & Destructor Documentation
MetadataFactory()
MetadataFactory (final MetadataStandard standard) package
Creates a new factory for the given metadata standard.
Parameters
standard The metadata standard implemented by this factory.
References MetadataFactory.standard.
{
         this.standard = standard;
     }
Member Function Documentation
containsAll()
static boolean containsAll (final Map<?,?> definition, final Set<?> keys) static private
Returns.
true
if the given definition map contains all the given keys.
Referenced by MetadataFactory.guessType().
{
         for (final Object key : keys) {
             if (!definition.containsKey(key)) {
                 return false;
             }
         }
         return true;
     }
create()
final<T> T create (final Class< T > type, final Map< String, Class<?>> definition, final Map< String,?> properties, final int position) throws ParseException package
Creates a new metadata of the given type, initialized with the property values given in the properties map.
Parameters
<T> The parameterized type of the
type
argument.
type The interface or implementation type of the metadata object to be created.
definition The value of
getDefinition(type)
.
properties The property values to be given to the metadata object.
position The position to report in case of error.
Returns
A new metadata object of the given type, filled with the given values.
Exceptions
ParseException If the metadata object can not be created.
References MetadataFactory.guessType().
Referenced by Reader.parse().
     {
         Class<? extends T> impl = standard.getImplementation(type);
         if (impl == null) {
             if (standard.isMetadata(type)) {
                 throw new ParseException(Errors.format(Errors.Keys.UnknownType_1, type), position);
             }
             impl = type; // Will try to instantiate the type directly.
         }
         impl = guessType(impl, definition, properties.keySet());
         final Object metadata;
         try {
             metadata = impl.newInstance();
         } catch (Exception e) {
             /*
              * We catch all Exceptions because Class.newInstance() propagates all of them,
              * including the checked ones (it bypasses the compile-time exception checking).
              */
             throw (ParseException) new ParseException(e.getLocalizedMessage(), position).initCause(e);
         }
         final Map<String,Object> asMap = standard.asValueMap(metadata, null,
                 KeyNamePolicy.UML_IDENTIFIER, ValueExistencePolicy.NON_EMPTY);
         try {
             asMap.putAll(properties);
         } catch (RuntimeException e) {
             throw (ParseException) new ParseException(e.getLocalizedMessage(), position).initCause(e);
         }
         return type.cast(metadata);
     }
getDefinition()
final Map<String,Class<?> > getDefinition (final Class<?> type) package
Returns the property names and expected types for the given class.
Referenced by MetadataFactory.guessType(), and Reader.parse().
{
         return standard.asTypeMap(type, KeyNamePolicy.UML_IDENTIFIER, TypeValuePolicy.ELEMENT_TYPE);
     }
guessType()
private<T> Class<? extends T> guessType (final Class< T > type, final Map<?,?> definition, final Set< String > keys) package
Returns the given type or a sub-type which contains all the given key, or.
null
if none.
Parameters
<T> Compile-time
type
.
type Base type of the desired metadata object.
definition The value of
getDefinition(type)
.
keys The keys of user-supplied properties of the metadata to construct.
Returns
The type of the metadata object to instantiate, or
null
if none.
References MetadataFactory.containsAll(), and MetadataFactory.getDefinition().
Referenced by MetadataFactory.create().
{
         if (containsAll(definition, keys)) {
             return type;
         }
         final XmlSeeAlso see = type.getAnnotation(XmlSeeAlso.class);
         if (see != null) {
             int count = 0;
             Map<?,?>[] subTypeDefinitions = null;
             final Class<?>[] subTypes = see.value(); // We will filter this array in the loop.
             for (final Class<?> subType : subTypes) {
                 if (type.isAssignableFrom(subType) && subType != type) {
                     final Map<String,Class<?>> cd = getDefinition(subType);
                     if (containsAll(cd, keys)) {
                         return subType.asSubclass(type);
                     }
                     if (subTypeDefinitions == null) {
                         subTypeDefinitions = new Map<?,?>[subTypes.length];
                     }
                     subTypeDefinitions[count] = cd;
                     subTypes[count++] = subType;
                 }
             }
             /*
              * Only after we verified all direct children, iterate recursively over other children.
              */
             for (int i=0; i<count; i++) {
                 final Class<?> subType = guessType(subTypes[i], subTypeDefinitions[i], keys);
                 if (subType != null) {
                     return subType.asSubclass(type);
                 }
             }
         }
         return null;
     }
Member Data Documentation
DEFAULT
final MetadataFactory DEFAULT = new MetadataFactory(MetadataStandard.ISO_19115) static package
The default instance.
Referenced by Reader.Reader().
standard
final MetadataStandard standard private
The standard implemented by this factory.
Referenced by MetadataFactory.MetadataFactory().