jena-geo: SpatialFunctionBase Class Reference
SpatialFunctionBase Class Reference abstract
Public Member Functions
final NodeValue exec (Binding binding, ExprList args, String uri, FunctionEnv env)
final void build (String uri, ExprList args)
Protected Member Functions
abstract NodeValue exec (Binding binding, List< NodeValue > evalArgs, String uri, FunctionEnv env)
abstract String [] getRestOfArgumentTypes ()
abstract String [] getArgumentTypes ()
Member Function Documentation
build()
final void build (String uri, ExprList args)
References SpatialFunctionBase.getArgumentTypes(), and SpatialFunctionBase.getRestOfArgumentTypes().
{
         String[] argTypes = getArgumentTypes();
         int numArgs = argTypes.length;
         if ((null == args && numArgs != 0) || (null != args && numArgs != args.size())) {
             StringBuilder message = new StringBuilder();
             for (int i = 0; i < argTypes.length; i++) {
                 String arg = argTypes[i];
                 message.append(arg);
                 if (i < argTypes.length - 1) {
                     message.append(", ");
                 }
             }
             throw new QueryBuildException(
                     String.format("%s requires %d arguments: %s", uri, argTypes.length, message));
         }
     }
exec() [1/2]
final NodeValue exec (Binding binding, ExprList args, String uri, FunctionEnv env)
{
         List<NodeValue> evalArgs = new ArrayList<>();
         for (Iterator<Expr> iter = args.iterator(); iter.hasNext();) {
             Expr e = iter.next();
             NodeValue x = e.eval(binding, env);
             evalArgs.add(x);
         }
         return exec(binding, evalArgs, uri, env);
     }
exec() [2/2]
abstract NodeValue exec (Binding binding, List< NodeValue > evalArgs, String uri, FunctionEnv env) abstract protected
getArgumentTypes()
abstract String [] getArgumentTypes () abstract protected
Referenced by SpatialFunctionBase.build().
getRestOfArgumentTypes()
abstract String [] getRestOfArgumentTypes () abstract protected
Referenced by SpatialFunctionBase.build().