jena-geo: Equals Class Reference
Equals Class Reference
Public Member Functions
NodeValue exec (NodeValue v1, NodeValue v2)
Member Function Documentation
exec()
NodeValue exec (NodeValue v1, NodeValue v2)
References GeometryWrapper.getXYGeometry(), LiteralUtils.rasterOrVector(), LiteralUtils.toGeometry(), and GeometryWrapper.transform().
Referenced by EqualsTest.testEqualsFalse(), and EqualsTest.testEqualsTrue().
{
                 Wrapper wrapper1=LiteralUtils.rasterOrVector(v1);
                 Wrapper wrapper2=LiteralUtils.rasterOrVector(v2);
                 if(wrapper1 instanceof GeometryWrapper && wrapper2 instanceof GeometryWrapper) {
                         GeometryWrapper transGeom2;
                         try {
                                 transGeom2 = ((GeometryWrapper)wrapper2).transform(((GeometryWrapper)wrapper1).getSrsInfo());
                                 return NodeValue.makeBoolean(((GeometryWrapper)wrapper1).getXYGeometry().equals(transGeom2.getXYGeometry()));
                         } catch (MismatchedDimensionException | TransformException | FactoryException e) {
                                 throw new RuntimeException("CRS transformation failed");
                         }
                 }else if(wrapper1 instanceof CoverageWrapper && wrapper2 instanceof CoverageWrapper) {
                         GridCoverage2D raster=((CoverageWrapper)wrapper1).getGridGeometry();
                         GridCoverage2D raster2=((CoverageWrapper)wrapper2).getGridGeometry();
                         return NodeValue.makeBoolean(raster.getEnvelope().equals(raster2.getEnvelope()));
                 }else {
                         if(wrapper1 instanceof CoverageWrapper) {
                                 GridCoverage2D raster=((CoverageWrapper)wrapper1).getGridGeometry();
                                 Envelope bbox1 = raster.getGridGeometry().getEnvelope();
                                 Geometry geom=((GeometryWrapper)wrapper2).getXYGeometry();
                                 return NodeValue.makeBoolean(LiteralUtils.toGeometry(bbox1).equals(geom));
                         }else {
                                 GridCoverage2D raster=((CoverageWrapper)wrapper2).getGridGeometry();
                                 Envelope bbox1 = raster.getGridGeometry().getEnvelope();
                                 Geometry geom=((GeometryWrapper)wrapper1).getXYGeometry();
                                 return NodeValue.makeBoolean(geom.equals(LiteralUtils.toGeometry(bbox1)));
                         }
                 }
         }