jena-geo: RemoveRingTest Class Reference
RemoveRingTest Class Reference
Public Member Functions
void testRemoveRing ()
Static Public Attributes
static final String duplicateRings ="POLYGON ((8 2, 11 13, 2 6, 8 2), (8 2, 11 13, 2 6, 8 2))"
static final String nonduplicateRings ="POLYGON((8 2, 11 13, 2 6, 8 2))"
static final String ring ="LINEARRING (8 2, 11 13, 2 6, 8 2)"
Member Function Documentation
testRemoveRing()
void testRemoveRing ()
{
         NodeValue geometryLiteral = NodeValue.makeNode(duplicateRings, WKTDatatype.INSTANCE);
         NodeValue add= NodeValue.makeInteger(0);
         RemoveRing instance=new RemoveRing();
         NodeValue expResult = NodeValue.makeNode(nonduplicateRings, WKTDatatype.INSTANCE);
         NodeValue result = instance.exec(geometryLiteral,add);
         assertEquals(expResult, result);
         }
References RemoveRingTest.duplicateRings, RemoveRing.exec(), and RemoveRingTest.nonduplicateRings.
Member Data Documentation
duplicateRings
final String duplicateRings ="POLYGON ((8 2, 11 13, 2 6, 8 2), (8 2, 11 13, 2 6, 8 2))" static
Referenced by RemoveRingTest.testRemoveRing().
nonduplicateRings
final String nonduplicateRings ="POLYGON((8 2, 11 13, 2 6, 8 2))" static
Referenced by RemoveRingTest.testRemoveRing().
ring
final String ring ="LINEARRING (8 2, 11 13, 2 6, 8 2)" static