jena-geo: LiteralUtils Class Reference
LiteralUtils Class Reference
Static Public Member Functions
static Wrapper rasterOrVector (NodeValue v)
static Geometry getCorrectVectorRepresentation (Wrapper wrapper)
static Geometry toGeometry (final Envelope2D envelope)
static Geometry toGeometry (final OctagonalEnvelope envelope)
static Geometry toGeometry (final Envelope envelope)
static Geometry toGeometry (final org.opengis.geometry.Envelope envelope)
static Geometry toGeometry (final Rectangle envelope)
static GeometryWrapper createGeometry (List< Coordinate > coordinates, String geomtype, GeometryWrapper geometry)
static GeometryWrapper createGeometry (Coordinate[] coordarray, String geomtype, GeometryWrapper geometry)
Member Function Documentation
createGeometry() [1/2]
static GeometryWrapper createGeometry (List< Coordinate > coordinates, String geomtype, GeometryWrapper geometry) static
References GeometryWrapper.getGeometryDatatypeURI(), and GeometryWrapper.getSrsURI().
Referenced by LiteralUtils.createGeometry(), EnsureClosed.exec(), ShiftLongitude.exec(), AddZ.exec(), MultiplyZ.exec(), AddT.exec(), PartOfGeometryBefore.exec(), PartOfGeometryAfter.exec(), RemovePoints.exec(), Force2D.exec(), Force3D.exec(), FilterByM.exec(), Force4D.exec(), Force3DM.exec(), SwapOrdinates.exec(), and FlipCoordinates.exec().
{
                         switch(geomtype) {
                         case "Point":
                                 return GeometryWrapperFactory.createPoint(coordinates.get(0), geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "MultiPoint":
                                 return GeometryWrapperFactory.createMultiPoint(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "LineString":
                                 return GeometryWrapperFactory.createLineString(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "Polygon":
                                 return GeometryWrapperFactory.createPolygon(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "MultiLineString":
                                 List<LineString> list=new LinkedList<LineString>();
                                 list.add((LineString)GeometryWrapperFactory.createLineString(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI()).getXYGeometry());
                                 return GeometryWrapperFactory.createMultiLineString(list, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "MultiPolygon":
                                 List<Polygon> plist=new LinkedList<Polygon>();
                                 plist.add((Polygon)GeometryWrapperFactory.createPolygon(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI()).getXYGeometry());
                                 return GeometryWrapperFactory.createMultiPolygon(plist, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         default:
                                 return null;
                         }
                 }
createGeometry() [2/2]
static GeometryWrapper createGeometry (Coordinate [] coordarray, String geomtype, GeometryWrapper geometry) static
References LiteralUtils.createGeometry().
{
                         return createGeometry(Arrays.asList(coordarray), geomtype, geometry);
                 }
getCorrectVectorRepresentation()
static Geometry getCorrectVectorRepresentation (Wrapper wrapper) static
References LiteralUtils.toGeometry().
{
                 if(wrapper instanceof GeometryWrapper) {
                         return ((GeometryWrapper) wrapper).getXYGeometry();
                 }else {
                         return toGeometry(((CoverageWrapper) wrapper).getParsingGeometry().getGridGeometry().getEnvelope());
                 }
         }
rasterOrVector()
static Wrapper rasterOrVector (NodeValue v) static
References CoverageWrapper.extract(), GeometryWrapper.extract(), RasterDataType.get(), and GeometryDatatype.get().
Referenced by EqualType.exec(), IsIndexed.exec(), IsTranslucent.exec(), IsTiled.exec(), IsGrayscale.exec(), EqualSRS.exec(), SRIDHasFlippedAxis.exec(), SRIDGetAxis1Name.exec(), SRIDGetAxis1Orientation.exec(), SRIDGetAxis2Name.exec(), DWithin3D.exec(), SRIDGetAxis2Orientation.exec(), Crosses.exec(), EqualNorm.exec(), Equals.exec(), EqualTopo.exec(), Difference.exec(), Intersection.exec(), DFullyWithin.exec(), SymDifference.exec(), ContainsProperly.exec(), IsEmpty.exec(), Intersects.exec(), SRID.exec(), Overlaps.exec(), Disjoint.exec(), CoveredBy.exec(), Touches.exec(), Contains.exec(), Covers.exec(), DWithin.exec(), and Within.exec().
{
                         GeometryDatatype datatype=GeometryDatatype.get(v.getDatatypeURI());
                         if(datatype==null) {
                                 RasterDataType rdatatype=RasterDataType.get(v.getDatatypeURI());
                                 if(rdatatype==null) {
                                         throw new AssertionError("No valid raster or vector geometry definition given!");
                                 }else {
                                         return CoverageWrapper.extract(v);
                                 }
                         }else{
                                 return  GeometryWrapper.extract(v);
                         }
         }
toGeometry() [1/5]
static Geometry toGeometry (final Envelope2D envelope) static
Referenced by EqualSRS.exec(), OctogonalEnvelope.exec(), DWithin3D.exec(), Crosses.exec(), EqualNorm.exec(), Equals.exec(), EqualTopo.exec(), Difference.exec(), Intersection.exec(), SymDifference.exec(), ContainsProperly.exec(), Envelope.exec(), Intersects.exec(), Overlaps.exec(), Touches.exec(), Disjoint.exec(), CoveredBy.exec(), Contains.exec(), Covers.exec(), Within.exec(), and LiteralUtils.getCorrectVectorRepresentation().
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMinY())
                 }), null);
     }
toGeometry() [2/5]
static Geometry toGeometry (final OctagonalEnvelope envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMinY())
                 }), null);
     }
toGeometry() [3/5]
static Geometry toGeometry (final Envelope envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMinY())
                 }), null);
     }
toGeometry() [4/5]
static Geometry toGeometry (final org.opengis.geometry.Envelope envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinimum(0), envelope.getMinimum(1)),
                     new Coordinate(envelope.getMaximum(0), envelope.getMinimum(1)),
                     new Coordinate(envelope.getMaximum(0), envelope.getMaximum(1)),
                     new Coordinate(envelope.getMinimum(0), envelope.getMaximum(1)),
                     new Coordinate(envelope.getMinimum(0), envelope.getMinimum(1))
                 }), null);
     }
toGeometry() [5/5]
static Geometry toGeometry (final Rectangle envelope) static
{
                 GeometryFactory gf = new GeometryFactory();
                 return gf.createPolygon(gf.createLinearRing(
                         new Coordinate[]{
                             new Coordinate(envelope.getMinX(), envelope.getMinY()),
                             new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                             new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                             new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                             new Coordinate(envelope.getMinX(), envelope.getMinY())
                         }), null);
             }