jena-geo: JtsPolyshapeWriter Class Reference
JtsPolyshapeWriter Class Reference
Public Member Functions
void write (Encoder output, Geometry geom) throws IOException
String getFormatName ()
void write (Writer output, Geometry shape) throws IOException
Protected Member Functions
void write (Encoder output, CoordinateSequence coordseq) throws IOException
void write (Encoder output, Coordinate[] coord) throws IOException
void write (Encoder output, Polygon p) throws IOException
Member Function Documentation
getFormatName()
String getFormatName () inherited
{
     return "PolyShape";
   }
write() [1/5]
void write (Encoder output, CoordinateSequence coordseq) throws IOException protected
Referenced by JtsPolyshapeWriter.write().
{
     int dim = coordseq.getDimension();
 //    if(dim>2) {
 //      throw new IllegalArgumentException("only supports 2d geometry now ("+dim+")");
 //    }
     for (int i = 0; i < coordseq.size(); i++) {
       output.write(coordseq.getOrdinate(i, 0),
                    coordseq.getOrdinate(i, 1));
     }
   }
write() [2/5]
void write (Encoder output, Coordinate [] coord) throws IOException protected
{
     for (int i = 0; i < coord.length; i++) {
       output.write(coord[i].x, coord[i].y);
     }
   }
write() [3/5]
void write (Encoder output, Polygon p) throws IOException protected
References JtsPolyshapeWriter.write().
{
     output.write(PolyshapeWriter.KEY_POLYGON);
     write(output, p.getExteriorRing().getCoordinateSequence());
     for (int i = 0; i < p.getNumInteriorRing(); i++) {
       output.startRing();
       write(output, p.getInteriorRingN(i).getCoordinateSequence());
     }
   }
write() [4/5]
void write (Encoder output, Geometry geom) throws IOException
References JtsPolyshapeWriter.write().
{
     if (geom instanceof Point) {
       Point v = (Point) geom;
       output.write(PolyshapeWriter.KEY_POINT);
       write(output, v.getCoordinateSequence());
       return;
     } else if (geom instanceof Polygon) {
       write(output, (Polygon) geom);
       return;
     } else if (geom instanceof LineString) {
       LineString v = (LineString) geom;
       output.write(PolyshapeWriter.KEY_LINE);
       write(output, v.getCoordinateSequence());
       return;
     } else if (geom instanceof MultiPoint) {
       MultiPoint v = (MultiPoint) geom;
       output.write(PolyshapeWriter.KEY_MULTIPOINT);
       write(output, v.getCoordinates());
       return;
     } else if (geom instanceof GeometryCollection) {
       GeometryCollection v = (GeometryCollection) geom;
       for (int i = 0; i < v.getNumGeometries(); i++) {
         if (i > 0) {
           output.seperator();
         }
         write(output, v.getGeometryN(i));
       }
     } else {
       throw new UnsupportedOperationException("unknown: " + geom);
     }
   }
write() [5/5]
void write (Writer output, Geometry shape) throws IOException inherited
{
     if (shape == null) {
       throw new NullPointerException("Shape can not be null");
     }
     throw new UnsupportedOperationException("Not implemented yet");
     //write(new Encoder(output), shape);
   }