jena-geo: Geobuf.Data.Geometry.Builder Class Reference
Geobuf.Data.Geometry.Builder Class Reference
Protobuf type.
Public Member Functions
Builder clear ()
Builder clone ()
Geobuf.Data.Geometry getDefaultInstanceForType ()
Geobuf.Data.Geometry build ()
Geobuf.Data.Geometry buildPartial ()
Builder mergeFrom (Geobuf.Data.Geometry other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
boolean hasType ()
required .Data.Geometry.Type type = 1;
Geobuf.Data.Geometry.Type getType ()
required .Data.Geometry.Type type = 1;
Builder setType (Geobuf.Data.Geometry.Type value)
required .Data.Geometry.Type type = 1;
Builder clearType ()
required .Data.Geometry.Type type = 1;
java.util.List< java.lang.Integer > getLengthsList ()
repeated uint32 lengths = 2 [packed = true];
int getLengthsCount ()
repeated uint32 lengths = 2 [packed = true];
int getLengths (int index)
repeated uint32 lengths = 2 [packed = true];
Builder setLengths (int index, int value)
repeated uint32 lengths = 2 [packed = true];
Builder addLengths (int value)
repeated uint32 lengths = 2 [packed = true];
Builder addAllLengths (java.lang.Iterable<? extends java.lang.Integer > values)
repeated uint32 lengths = 2 [packed = true];
Builder clearLengths ()
repeated uint32 lengths = 2 [packed = true];
java.util.List< java.lang.Long > getCoordsList ()
repeated sint64 coords = 3 [packed = true];
int getCoordsCount ()
repeated sint64 coords = 3 [packed = true];
long getCoords (int index)
repeated sint64 coords = 3 [packed = true];
Builder setCoords (int index, long value)
repeated sint64 coords = 3 [packed = true];
Builder addCoords (long value)
repeated sint64 coords = 3 [packed = true];
Builder addAllCoords (java.lang.Iterable<? extends java.lang.Long > values)
repeated sint64 coords = 3 [packed = true];
Builder clearCoords ()
repeated sint64 coords = 3 [packed = true];
java.util.List< Geobuf.Data.Geometry > getGeometriesList ()
repeated .Data.Geometry geometries = 4;
int getGeometriesCount ()
repeated .Data.Geometry geometries = 4;
Geobuf.Data.Geometry getGeometries (int index)
repeated .Data.Geometry geometries = 4;
Builder setGeometries (int index, Geobuf.Data.Geometry value)
repeated .Data.Geometry geometries = 4;
Builder setGeometries (int index, Geobuf.Data.Geometry.Builder builderForValue)
repeated .Data.Geometry geometries = 4;
Builder addGeometries (Geobuf.Data.Geometry value)
repeated .Data.Geometry geometries = 4;
Builder addGeometries (int index, Geobuf.Data.Geometry value)
repeated .Data.Geometry geometries = 4;
Builder addGeometries (Geobuf.Data.Geometry.Builder builderForValue)
repeated .Data.Geometry geometries = 4;
Builder addGeometries (int index, Geobuf.Data.Geometry.Builder builderForValue)
repeated .Data.Geometry geometries = 4;
Builder addAllGeometries (java.lang.Iterable<? extends Geobuf.Data.Geometry > values)
repeated .Data.Geometry geometries = 4;
Builder clearGeometries ()
repeated .Data.Geometry geometries = 4;
Builder removeGeometries (int index)
repeated .Data.Geometry geometries = 4;
java.util.List< Geobuf.Data.Value > getValuesList ()
repeated .Data.Value values = 13;
int getValuesCount ()
repeated .Data.Value values = 13;
Geobuf.Data.Value getValues (int index)
repeated .Data.Value values = 13;
Builder setValues (int index, Geobuf.Data.Value value)
repeated .Data.Value values = 13;
Builder setValues (int index, Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
Builder addValues (Geobuf.Data.Value value)
repeated .Data.Value values = 13;
Builder addValues (int index, Geobuf.Data.Value value)
repeated .Data.Value values = 13;
Builder addValues (Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
Builder addValues (int index, Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
Builder addAllValues (java.lang.Iterable<? extends Geobuf.Data.Value > values)
repeated .Data.Value values = 13;
Builder clearValues ()
repeated .Data.Value values = 13;
Builder removeValues (int index)
repeated .Data.Value values = 13;
java.util.List< java.lang.Integer > getCustomPropertiesList ()
repeated uint32 custom_properties = 15 [packed = true];
int getCustomPropertiesCount ()
repeated uint32 custom_properties = 15 [packed = true];
int getCustomProperties (int index)
repeated uint32 custom_properties = 15 [packed = true];
Builder setCustomProperties (int index, int value)
repeated uint32 custom_properties = 15 [packed = true];
Builder addCustomProperties (int value)
repeated uint32 custom_properties = 15 [packed = true];
Builder addAllCustomProperties (java.lang.Iterable<? extends java.lang.Integer > values)
repeated uint32 custom_properties = 15 [packed = true];
Builder clearCustomProperties ()
repeated uint32 custom_properties = 15 [packed = true];
Private Member Functions
Builder ()
void maybeForceBuilderInitialization ()
void ensureLengthsIsMutable ()
void ensureCoordsIsMutable ()
void ensureGeometriesIsMutable ()
void ensureValuesIsMutable ()
void ensureCustomPropertiesIsMutable ()
Static Private Member Functions
static Builder create ()
Private Attributes
int bitField0_
Geobuf.Data.Geometry.Type type_ = Geobuf.Data.Geometry.Type.POINT
java.util.List< java.lang.Integer > lengths_ = java.util.Collections.emptyList()
java.util.List< java.lang.Long > coords_ = java.util.Collections.emptyList()
java.util.List< Geobuf.Data.Geometry > geometries_
java.util.List< Geobuf.Data.Value > values_
java.util.List< java.lang.Integer > customProperties_ = java.util.Collections.emptyList()
Detailed Description
Protobuf type.
Data.Geometry
Constructor & Destructor Documentation
Builder()
Builder () private
{
           maybeForceBuilderInitialization();
         }
Member Function Documentation
addAllCoords()
Builder addAllCoords (java.lang.Iterable<? extends java.lang.Long > values)
repeated sint64 coords = 3 [packed = true];
delta-encoded integer values
{
           ensureCoordsIsMutable();
           com.google.protobuf.AbstractMessageLite.Builder.addAll(
               values, coords_);
           return this;
         }
addAllCustomProperties()
Builder addAllCustomProperties (java.lang.Iterable<? extends java.lang.Integer > values)
repeated uint32 custom_properties = 15 [packed = true];
{
           ensureCustomPropertiesIsMutable();
           com.google.protobuf.AbstractMessageLite.Builder.addAll(
               values, customProperties_);
           return this;
         }
addAllGeometries()
Builder addAllGeometries (java.lang.Iterable<? extends Geobuf.Data.Geometry > values)
repeated .Data.Geometry geometries = 4;
{
           ensureGeometriesIsMutable();
           com.google.protobuf.AbstractMessageLite.Builder.addAll(
               values, geometries_);
           return this;
         }
addAllLengths()
Builder addAllLengths (java.lang.Iterable<? extends java.lang.Integer > values)
repeated uint32 lengths = 2 [packed = true];
coordinate structure in lengths
{
           ensureLengthsIsMutable();
           com.google.protobuf.AbstractMessageLite.Builder.addAll(
               values, lengths_);
           return this;
         }
addAllValues()
Builder addAllValues (java.lang.Iterable<? extends Geobuf.Data.Value > values)
repeated .Data.Value values = 13;
{
           ensureValuesIsMutable();
           com.google.protobuf.AbstractMessageLite.Builder.addAll(
               values, values_);
           return this;
         }
addCoords()
Builder addCoords (long value)
repeated sint64 coords = 3 [packed = true];
delta-encoded integer values
Referenced by GeobufEncoder.pointToGeobuf().
{
           ensureCoordsIsMutable();
           coords_.add(value);
           return this;
         }
addCustomProperties()
Builder addCustomProperties (int value)
repeated uint32 custom_properties = 15 [packed = true];
{
           ensureCustomPropertiesIsMutable();
           customProperties_.add(value);
           return this;
         }
addGeometries() [1/4]
Builder addGeometries (Geobuf.Data.Geometry value)
repeated .Data.Geometry geometries = 4;
{
           if (value == null) {
             throw new NullPointerException();
           }
           ensureGeometriesIsMutable();
           geometries_.add(value);
           return this;
         }
addGeometries() [2/4]
Builder addGeometries (int index, Geobuf.Data.Geometry value)
repeated .Data.Geometry geometries = 4;
{
           if (value == null) {
             throw new NullPointerException();
           }
           ensureGeometriesIsMutable();
           geometries_.add(index, value);
           return this;
         }
addGeometries() [3/4]
Builder addGeometries (Geobuf.Data.Geometry.Builder builderForValue)
repeated .Data.Geometry geometries = 4;
{
           ensureGeometriesIsMutable();
           geometries_.add(builderForValue.build());
           return this;
         }
addGeometries() [4/4]
Builder addGeometries (int index, Geobuf.Data.Geometry.Builder builderForValue)
repeated .Data.Geometry geometries = 4;
{
           ensureGeometriesIsMutable();
           geometries_.add(index, builderForValue.build());
           return this;
         }
addLengths()
Builder addLengths (int value)
repeated uint32 lengths = 2 [packed = true];
coordinate structure in lengths
Referenced by GeobufEncoder.multiPolyToGeobuf().
{
           ensureLengthsIsMutable();
           lengths_.add(value);
           return this;
         }
addValues() [1/4]
Builder addValues (Geobuf.Data.Value value)
repeated .Data.Value values = 13;
{
           if (value == null) {
             throw new NullPointerException();
           }
           ensureValuesIsMutable();
           values_.add(value);
           return this;
         }
addValues() [2/4]
Builder addValues (int index, Geobuf.Data.Value value)
repeated .Data.Value values = 13;
{
           if (value == null) {
             throw new NullPointerException();
           }
           ensureValuesIsMutable();
           values_.add(index, value);
           return this;
         }
addValues() [3/4]
Builder addValues (Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
{
           ensureValuesIsMutable();
           values_.add(builderForValue.build());
           return this;
         }
addValues() [4/4]
Builder addValues (int index, Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
{
           ensureValuesIsMutable();
           values_.add(index, builderForValue.build());
           return this;
         }
build()
Geobuf.Data.Geometry build ()
Referenced by GeobufEncoder.multiPolyToGeobuf(), GeobufEncoder.pointToGeobuf(), and GeobufEncoder.polyToGeobuf().
{
           Geobuf.Data.Geometry result = buildPartial();
           if (!result.isInitialized()) {
             throw newUninitializedMessageException(result);
           }
           return result;
         }
buildPartial()
Geobuf.Data.Geometry buildPartial ()
References Geobuf.Data.Geometry.type_.
Referenced by Geobuf.Data.Data(), Geobuf.Data.Feature.Feature(), Geobuf.Data.Feature.Builder.mergeGeometry(), and Geobuf.Data.Builder.mergeGeometry().
{
           Geobuf.Data.Geometry result = new Geobuf.Data.Geometry(this);
           int from_bitField0_ = bitField0_;
           int to_bitField0_ = 0;
           if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
             to_bitField0_ |= 0x00000001;
           }
           result.type_ = type_;
           if (((bitField0_ & 0x00000002) == 0x00000002)) {
             lengths_ = java.util.Collections.unmodifiableList(lengths_);
             bitField0_ = (bitField0_ & ~0x00000002);
           }
           result.lengths_ = lengths_;
           if (((bitField0_ & 0x00000004) == 0x00000004)) {
             coords_ = java.util.Collections.unmodifiableList(coords_);
             bitField0_ = (bitField0_ & ~0x00000004);
           }
           result.coords_ = coords_;
           if (((bitField0_ & 0x00000008) == 0x00000008)) {
             geometries_ = java.util.Collections.unmodifiableList(geometries_);
             bitField0_ = (bitField0_ & ~0x00000008);
           }
           result.geometries_ = geometries_;
           if (((bitField0_ & 0x00000010) == 0x00000010)) {
             values_ = java.util.Collections.unmodifiableList(values_);
             bitField0_ = (bitField0_ & ~0x00000010);
           }
           result.values_ = values_;
           if (((bitField0_ & 0x00000020) == 0x00000020)) {
             customProperties_ = java.util.Collections.unmodifiableList(customProperties_);
             bitField0_ = (bitField0_ & ~0x00000020);
           }
           result.customProperties_ = customProperties_;
           result.bitField0_ = to_bitField0_;
           return result;
         }
clear()
Builder clear ()
References Geobuf.Data.Geometry.Builder.clear(), and Geobuf.Data.Geometry.Type.POINT.
Referenced by Geobuf.Data.Geometry.Builder.clear().
{
           super.clear();
           type_ = Geobuf.Data.Geometry.Type.POINT;
           bitField0_ = (bitField0_ & ~0x00000001);
           lengths_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000002);
           coords_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000004);
           geometries_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000008);
           values_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000010);
           customProperties_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000020);
           return this;
         }
clearCoords()
Builder clearCoords ()
repeated sint64 coords = 3 [packed = true];
delta-encoded integer values
{
           coords_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000004);
           return this;
         }
clearCustomProperties()
Builder clearCustomProperties ()
repeated uint32 custom_properties = 15 [packed = true];
References Geobuf.Data.Geometry.initFields().
{
           customProperties_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000020);
           return this;
         }
clearGeometries()
Builder clearGeometries ()
repeated .Data.Geometry geometries = 4;
{
           geometries_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000008);
           return this;
         }
clearLengths()
Builder clearLengths ()
repeated uint32 lengths = 2 [packed = true];
coordinate structure in lengths
{
           lengths_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000002);
           return this;
         }
clearType()
Builder clearType ()
required .Data.Geometry.Type type = 1;
References Geobuf.Data.Geometry.Type.POINT.
{
           bitField0_ = (bitField0_ & ~0x00000001);
           type_ = Geobuf.Data.Geometry.Type.POINT;
           return this;
         }
clearValues()
Builder clearValues ()
repeated .Data.Value values = 13;
{
           values_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000010);
           return this;
         }
clone()
Builder clone ()
References Geobuf.Data.Geometry.Builder.mergeFrom().
{
           return create().mergeFrom(buildPartial());
         }
create()
static Builder create () static private
Referenced by Geobuf.Data.Geometry.newBuilder().
{
           return new Builder();
         }
ensureCoordsIsMutable()
void ensureCoordsIsMutable () private
{
           if (!((bitField0_ & 0x00000004) == 0x00000004)) {
             coords_ = new java.util.ArrayList<java.lang.Long>(coords_);
             bitField0_ |= 0x00000004;
            }
         }
ensureCustomPropertiesIsMutable()
void ensureCustomPropertiesIsMutable () private
{
           if (!((bitField0_ & 0x00000020) == 0x00000020)) {
             customProperties_ = new java.util.ArrayList<java.lang.Integer>(customProperties_);
             bitField0_ |= 0x00000020;
            }
         }
ensureGeometriesIsMutable()
void ensureGeometriesIsMutable () private
{
           if (!((bitField0_ & 0x00000008) == 0x00000008)) {
             geometries_ = new java.util.ArrayList<Geobuf.Data.Geometry>(geometries_);
             bitField0_ |= 0x00000008;
            }
         }
ensureLengthsIsMutable()
void ensureLengthsIsMutable () private
{
           if (!((bitField0_ & 0x00000002) == 0x00000002)) {
             lengths_ = new java.util.ArrayList<java.lang.Integer>(lengths_);
             bitField0_ |= 0x00000002;
            }
         }
ensureValuesIsMutable()
void ensureValuesIsMutable () private
{
           if (!((bitField0_ & 0x00000010) == 0x00000010)) {
             values_ = new java.util.ArrayList<Geobuf.Data.Value>(values_);
             bitField0_ |= 0x00000010;
            }
         }
getCoords()
long getCoords (int index)
repeated sint64 coords = 3 [packed = true];
delta-encoded integer values
Implements Geobuf.Data.GeometryOrBuilder.
{
           return coords_.get(index);
         }
getCoordsCount()
int getCoordsCount ()
repeated sint64 coords = 3 [packed = true];
delta-encoded integer values
Implements Geobuf.Data.GeometryOrBuilder.
{
           return coords_.size();
         }
getCoordsList()
java.util.List<java.lang.Long> getCoordsList ()
repeated sint64 coords = 3 [packed = true];
delta-encoded integer values
Implements Geobuf.Data.GeometryOrBuilder.
{
           return java.util.Collections.unmodifiableList(coords_);
         }
getCustomProperties()
int getCustomProperties (int index)
repeated uint32 custom_properties = 15 [packed = true];
Implements Geobuf.Data.GeometryOrBuilder.
{
           return customProperties_.get(index);
         }
getCustomPropertiesCount()
int getCustomPropertiesCount ()
repeated uint32 custom_properties = 15 [packed = true];
Implements Geobuf.Data.GeometryOrBuilder.
{
           return customProperties_.size();
         }
getCustomPropertiesList()
java.util.List<java.lang.Integer> getCustomPropertiesList ()
repeated uint32 custom_properties = 15 [packed = true];
Implements Geobuf.Data.GeometryOrBuilder.
{
           return java.util.Collections.unmodifiableList(customProperties_);
         }
getDefaultInstanceForType()
Geobuf.Data.Geometry getDefaultInstanceForType ()
References Geobuf.Data.Geometry.getDefaultInstance().
{
           return Geobuf.Data.Geometry.getDefaultInstance();
         }
getGeometries()
Geobuf.Data.Geometry getGeometries (int index)
repeated .Data.Geometry geometries = 4;
Implements Geobuf.Data.GeometryOrBuilder.
{
           return geometries_.get(index);
         }
getGeometriesCount()
int getGeometriesCount ()
repeated .Data.Geometry geometries = 4;
Implements Geobuf.Data.GeometryOrBuilder.
{
           return geometries_.size();
         }
getGeometriesList()
java.util.List<Geobuf.Data.Geometry> getGeometriesList ()
repeated .Data.Geometry geometries = 4;
Implements Geobuf.Data.GeometryOrBuilder.
{
           return java.util.Collections.unmodifiableList(geometries_);
         }
getLengths()
int getLengths (int index)
repeated uint32 lengths = 2 [packed = true];
coordinate structure in lengths
Implements Geobuf.Data.GeometryOrBuilder.
{
           return lengths_.get(index);
         }
getLengthsCount()
int getLengthsCount ()
repeated uint32 lengths = 2 [packed = true];
coordinate structure in lengths
Implements Geobuf.Data.GeometryOrBuilder.
{
           return lengths_.size();
         }
getLengthsList()
java.util.List<java.lang.Integer> getLengthsList ()
repeated uint32 lengths = 2 [packed = true];
coordinate structure in lengths
Implements Geobuf.Data.GeometryOrBuilder.
{
           return java.util.Collections.unmodifiableList(lengths_);
         }
getType()
Geobuf.Data.Geometry.Type getType ()
required .Data.Geometry.Type type = 1;
Implements Geobuf.Data.GeometryOrBuilder.
{
           return type_;
         }
getValues()
Geobuf.Data.Value getValues (int index)
repeated .Data.Value values = 13;
Implements Geobuf.Data.GeometryOrBuilder.
{
           return values_.get(index);
         }
getValuesCount()
int getValuesCount ()
repeated .Data.Value values = 13;
Implements Geobuf.Data.GeometryOrBuilder.
{
           return values_.size();
         }
getValuesList()
java.util.List<Geobuf.Data.Value> getValuesList ()
repeated .Data.Value values = 13;
Implements Geobuf.Data.GeometryOrBuilder.
{
           return java.util.Collections.unmodifiableList(values_);
         }
hasType()
boolean hasType ()
required .Data.Geometry.Type type = 1;
Implements Geobuf.Data.GeometryOrBuilder.
{
           return ((bitField0_ & 0x00000001) == 0x00000001);
         }
isInitialized()
final boolean isInitialized ()
{
           if (!hasType()) {
             return false;
           }
           for (int i = 0; i < getGeometriesCount(); i++) {
             if (!getGeometries(i).isInitialized()) {
               return false;
             }
           }
           return true;
         }
maybeForceBuilderInitialization()
void maybeForceBuilderInitialization () private
{
         }
mergeFrom() [1/2]
Builder mergeFrom (Geobuf.Data.Geometry other)
References Geobuf.Data.Geometry.getDefaultInstance(), and Geobuf.Data.Geometry.Builder.lengths_.
Referenced by Geobuf.Data.Geometry.Builder.clone(), Geobuf.Data.Data(), Geobuf.Data.Feature.Feature(), Geobuf.Data.Feature.Builder.mergeGeometry(), Geobuf.Data.Builder.mergeGeometry(), and Geobuf.Data.Geometry.newBuilder().
{
           if (other == Geobuf.Data.Geometry.getDefaultInstance()) return this;
           if (other.hasType()) {
             setType(other.getType());
           }
           if (!other.lengths_.isEmpty()) {
             if (lengths_.isEmpty()) {
               lengths_ = other.lengths_;
               bitField0_ = (bitField0_ & ~0x00000002);
             } else {
               ensureLengthsIsMutable();
               lengths_.addAll(other.lengths_);
             }
           }
           if (!other.coords_.isEmpty()) {
             if (coords_.isEmpty()) {
               coords_ = other.coords_;
               bitField0_ = (bitField0_ & ~0x00000004);
             } else {
               ensureCoordsIsMutable();
               coords_.addAll(other.coords_);
             }
           }
           if (!other.geometries_.isEmpty()) {
             if (geometries_.isEmpty()) {
               geometries_ = other.geometries_;
               bitField0_ = (bitField0_ & ~0x00000008);
             } else {
               ensureGeometriesIsMutable();
               geometries_.addAll(other.geometries_);
             }
           }
           if (!other.values_.isEmpty()) {
             if (values_.isEmpty()) {
               values_ = other.values_;
               bitField0_ = (bitField0_ & ~0x00000010);
             } else {
               ensureValuesIsMutable();
               values_.addAll(other.values_);
             }
           }
           if (!other.customProperties_.isEmpty()) {
             if (customProperties_.isEmpty()) {
               customProperties_ = other.customProperties_;
               bitField0_ = (bitField0_ & ~0x00000020);
             } else {
               ensureCustomPropertiesIsMutable();
               customProperties_.addAll(other.customProperties_);
             }
           }
           setUnknownFields(
               getUnknownFields().concat(other.unknownFields));
           return this;
         }
mergeFrom() [2/2]
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
{
           Geobuf.Data.Geometry parsedMessage = null;
           try {
             parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
           } catch (com.google.protobuf.InvalidProtocolBufferException e) {
             parsedMessage = (Geobuf.Data.Geometry) e.getUnfinishedMessage();
             throw e;
           } finally {
             if (parsedMessage != null) {
               mergeFrom(parsedMessage);
             }
           }
           return this;
         }
removeGeometries()
Builder removeGeometries (int index)
repeated .Data.Geometry geometries = 4;
{
           ensureGeometriesIsMutable();
           geometries_.remove(index);
           return this;
         }
removeValues()
Builder removeValues (int index)
repeated .Data.Value values = 13;
{
           ensureValuesIsMutable();
           values_.remove(index);
           return this;
         }
setCoords()
Builder setCoords (int index, long value)
repeated sint64 coords = 3 [packed = true];
delta-encoded integer values
{
           ensureCoordsIsMutable();
           coords_.set(index, value);
           return this;
         }
setCustomProperties()
Builder setCustomProperties (int index, int value)
repeated uint32 custom_properties = 15 [packed = true];
{
           ensureCustomPropertiesIsMutable();
           customProperties_.set(index, value);
           return this;
         }
setGeometries() [1/2]
Builder setGeometries (int index, Geobuf.Data.Geometry value)
repeated .Data.Geometry geometries = 4;
{
           if (value == null) {
             throw new NullPointerException();
           }
           ensureGeometriesIsMutable();
           geometries_.set(index, value);
           return this;
         }
setGeometries() [2/2]
Builder setGeometries (int index, Geobuf.Data.Geometry.Builder builderForValue)
repeated .Data.Geometry geometries = 4;
{
           ensureGeometriesIsMutable();
           geometries_.set(index, builderForValue.build());
           return this;
         }
setLengths()
Builder setLengths (int index, int value)
repeated uint32 lengths = 2 [packed = true];
coordinate structure in lengths
{
           ensureLengthsIsMutable();
           lengths_.set(index, value);
           return this;
         }
setType()
Builder setType (Geobuf.Data.Geometry.Type value)
required .Data.Geometry.Type type = 1;
Referenced by GeobufEncoder.multiPolyToGeobuf(), GeobufEncoder.pointToGeobuf(), and GeobufEncoder.polyToGeobuf().
{
           if (value == null) {
             throw new NullPointerException();
           }
           bitField0_ |= 0x00000001;
           type_ = value;
           return this;
         }
setValues() [1/2]
Builder setValues (int index, Geobuf.Data.Value value)
repeated .Data.Value values = 13;
{
           if (value == null) {
             throw new NullPointerException();
           }
           ensureValuesIsMutable();
           values_.set(index, value);
           return this;
         }
setValues() [2/2]
Builder setValues (int index, Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
{
           ensureValuesIsMutable();
           values_.set(index, builderForValue.build());
           return this;
         }
Member Data Documentation
bitField0_
int bitField0_ private
coords_
java.util.List<java.lang.Long> coords_ = java.util.Collections.emptyList() private
customProperties_
java.util.List<java.lang.Integer> customProperties_ = java.util.Collections.emptyList() private
geometries_
java.util.List<Geobuf.Data.Geometry> geometries_ private
Initial value:
=
          java.util.Collections.emptyList()
lengths_
java.util.List<java.lang.Integer> lengths_ = java.util.Collections.emptyList() private
Referenced by Geobuf.Data.Geometry.Builder.mergeFrom().
type_
Geobuf.Data.Geometry.Type type_ = Geobuf.Data.Geometry.Type.POINT private
values_
java.util.List<Geobuf.Data.Value> values_ private
Initial value:
=
          java.util.Collections.emptyList()