jena-geo: Geobuf.Data.Feature Class Reference
Geobuf.Data.Feature Class Reference
Protobuf type.
Classes
class Builder
Protobuf type.
enum IdTypeCase
Public Member Functions
Feature getDefaultInstanceForType ()
.lang.Override com.google.protobuf.Parser< Feature > getParserForType ()
IdTypeCase getIdTypeCase ()
boolean hasGeometry ()
required .Data.Geometry geometry = 1;
Geobuf.Data.Geometry getGeometry ()
required .Data.Geometry geometry = 1;
boolean hasId ()
optional string id = 11;
java.lang.String getId ()
optional string id = 11;
com.google.protobuf.ByteString getIdBytes ()
optional string id = 11;
boolean hasIntId ()
optional sint64 int_id = 12;
long getIntId ()
optional sint64 int_id = 12;
java.util.List< Geobuf.Data.Value > getValuesList ()
repeated .Data.Value values = 13;
java.util.List<? extends Geobuf.Data.ValueOrBuilder > getValuesOrBuilderList ()
repeated .Data.Value values = 13;
int getValuesCount ()
repeated .Data.Value values = 13;
Geobuf.Data.Value getValues (int index)
repeated .Data.Value values = 13;
Geobuf.Data.ValueOrBuilder getValuesOrBuilder (int index)
repeated .Data.Value values = 13;
java.util.List< java.lang.Integer > getPropertiesList ()
repeated uint32 properties = 14 [packed = true];
int getPropertiesCount ()
repeated uint32 properties = 14 [packed = true];
int getProperties (int index)
repeated uint32 properties = 14 [packed = true];
java.util.List< java.lang.Integer > getCustomPropertiesList ()
repeated uint32 custom_properties = 15 [packed = true];
int getCustomPropertiesCount ()
repeated uint32 custom_properties = 15 [packed = true];
int getCustomProperties (int index)
repeated uint32 custom_properties = 15 [packed = true];
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static Feature getDefaultInstance ()
static Geobuf.Data.Feature parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.Feature parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.Feature parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.Feature parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.Feature parseFrom (java.io.InputStream input) throws java.io.IOException
static Geobuf.Data.Feature parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Geobuf.Data.Feature parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static Geobuf.Data.Feature parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Geobuf.Data.Feature parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static Geobuf.Data.Feature parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (Geobuf.Data.Feature prototype)
Static Public Attributes
static com.google.protobuf.Parser< Feature > PARSER
static final int GEOMETRY_FIELD_NUMBER = 1
static final int ID_FIELD_NUMBER = 11
static final int INT_ID_FIELD_NUMBER = 12
static final int VALUES_FIELD_NUMBER = 13
static final int PROPERTIES_FIELD_NUMBER = 14
static final int CUSTOM_PROPERTIES_FIELD_NUMBER = 15
Protected Member Functions
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
Static Package Functions
[static initializer]
Private Member Functions
Feature (com.google.protobuf.GeneratedMessageLite.Builder builder)
Feature (boolean noInit)
Feature (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
void initFields ()
Private Attributes
final com.google.protobuf.ByteString unknownFields
int bitField0_
int idTypeCase_ = 0
java.lang.Object idType_
Geobuf.Data.Geometry geometry_
java.util.List< Geobuf.Data.Value > values_
java.util.List< java.lang.Integer > properties_
int propertiesMemoizedSerializedSize = -1
java.util.List< java.lang.Integer > customProperties_
int customPropertiesMemoizedSerializedSize = -1
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final Feature defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Protobuf type.
Data.Feature
Constructor & Destructor Documentation
Feature() [1/3]
Feature (com.google.protobuf.GeneratedMessageLite.Builder builder) private
{
         super(builder);
         this.unknownFields = builder.getUnknownFields();
       }
Feature() [2/3]
Feature (boolean noInit) private
 { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}
Feature() [3/3]
Feature (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException private
References Geobuf.Data.Geometry.Builder.buildPartial(), Geobuf.Data.Geometry.Builder.mergeFrom(), Geobuf.Data.Geometry.PARSER, and Geobuf.Data.Value.PARSER.
{
         initFields();
         int mutable_bitField0_ = 0;
         com.google.protobuf.ByteString.Output unknownFieldsOutput =
             com.google.protobuf.ByteString.newOutput();
         com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
             com.google.protobuf.CodedOutputStream.newInstance(
                 unknownFieldsOutput);
         try {
           boolean done = false;
           while (!done) {
             int tag = input.readTag();
             switch (tag) {
               case 0:
                 done = true;
                 break;
               default: {
                 if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                        extensionRegistry, tag)) {
                   done = true;
                 }
                 break;
               }
               case 10: {
                 Geobuf.Data.Geometry.Builder subBuilder = null;
                 if (((bitField0_ & 0x00000001) == 0x00000001)) {
                   subBuilder = geometry_.toBuilder();
                 }
                 geometry_ = input.readMessage(Geobuf.Data.Geometry.PARSER, extensionRegistry);
                 if (subBuilder != null) {
                   subBuilder.mergeFrom(geometry_);
                   geometry_ = subBuilder.buildPartial();
                 }
                 bitField0_ |= 0x00000001;
                 break;
               }
               case 90: {
                 com.google.protobuf.ByteString bs = input.readBytes();
                 idTypeCase_ = 11;
                 idType_ = bs;
                 break;
               }
               case 96: {
                 idTypeCase_ = 12;
                 idType_ = input.readSInt64();
                 break;
               }
               case 106: {
                 if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                   values_ = new java.util.ArrayList<Geobuf.Data.Value>();
                   mutable_bitField0_ |= 0x00000008;
                 }
                 values_.add(input.readMessage(Geobuf.Data.Value.PARSER, extensionRegistry));
                 break;
               }
               case 112: {
                 if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                   properties_ = new java.util.ArrayList<java.lang.Integer>();
                   mutable_bitField0_ |= 0x00000010;
                 }
                 properties_.add(input.readUInt32());
                 break;
               }
               case 114: {
                 int length = input.readRawVarint32();
                 int limit = input.pushLimit(length);
                 if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                   properties_ = new java.util.ArrayList<java.lang.Integer>();
                   mutable_bitField0_ |= 0x00000010;
                 }
                 while (input.getBytesUntilLimit() > 0) {
                   properties_.add(input.readUInt32());
                 }
                 input.popLimit(limit);
                 break;
               }
               case 120: {
                 if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                   customProperties_ = new java.util.ArrayList<java.lang.Integer>();
                   mutable_bitField0_ |= 0x00000020;
                 }
                 customProperties_.add(input.readUInt32());
                 break;
               }
               case 122: {
                 int length = input.readRawVarint32();
                 int limit = input.pushLimit(length);
                 if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                   customProperties_ = new java.util.ArrayList<java.lang.Integer>();
                   mutable_bitField0_ |= 0x00000020;
                 }
                 while (input.getBytesUntilLimit() > 0) {
                   customProperties_.add(input.readUInt32());
                 }
                 input.popLimit(limit);
                 break;
               }
             }
           }
         } catch (com.google.protobuf.InvalidProtocolBufferException e) {
           throw e.setUnfinishedMessage(this);
         } catch (java.io.IOException e) {
           throw new com.google.protobuf.InvalidProtocolBufferException(
               e.getMessage()).setUnfinishedMessage(this);
         } finally {
           if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
             values_ = java.util.Collections.unmodifiableList(values_);
           }
           if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
             properties_ = java.util.Collections.unmodifiableList(properties_);
           }
           if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
             customProperties_ = java.util.Collections.unmodifiableList(customProperties_);
           }
           try {
             unknownFieldsCodedOutput.flush();
           } catch (java.io.IOException e) {
           // Should not happen
           } finally {
             unknownFields = unknownFieldsOutput.toByteString();
           }
           makeExtensionsImmutable();
         }
       }
Member Function Documentation
[static initializer]()
[static initializer] () static package
getCustomProperties()
int getCustomProperties (int index)
repeated uint32 custom_properties = 15 [packed = true];
arbitrary properties
Implements Geobuf.Data.FeatureOrBuilder.
{
         return customProperties_.get(index);
       }
getCustomPropertiesCount()
int getCustomPropertiesCount ()
repeated uint32 custom_properties = 15 [packed = true];
arbitrary properties
Implements Geobuf.Data.FeatureOrBuilder.
{
         return customProperties_.size();
       }
getCustomPropertiesList()
java.util.List<java.lang.Integer> getCustomPropertiesList ()
repeated uint32 custom_properties = 15 [packed = true];
arbitrary properties
Implements Geobuf.Data.FeatureOrBuilder.
{
         return customProperties_;
       }
getDefaultInstance()
static Feature getDefaultInstance () static
Referenced by Geobuf.Data.Feature.Builder.getDefaultInstanceForType(), Geobuf.Data.getFeature(), Geobuf.Data.Builder.getFeature(), Geobuf.Data.Builder.mergeFeature(), and Geobuf.Data.Feature.Builder.mergeFrom().
{
         return defaultInstance;
       }
getDefaultInstanceForType()
Feature getDefaultInstanceForType ()
{
         return defaultInstance;
       }
getGeometry()
Geobuf.Data.Geometry getGeometry ()
required .Data.Geometry geometry = 1;
Implements Geobuf.Data.FeatureOrBuilder.
{
         return geometry_;
       }
getId()
java.lang.String getId ()
optional string id = 11;
Implements Geobuf.Data.FeatureOrBuilder.
{
         java.lang.Object ref = "";
         if (idTypeCase_ == 11) {
           ref = idType_;
         }
         if (ref instanceof java.lang.String) {
           return (java.lang.String) ref;
         } else {
           com.google.protobuf.ByteString bs =
               (com.google.protobuf.ByteString) ref;
           java.lang.String s = bs.toStringUtf8();
           if (bs.isValidUtf8() && (idTypeCase_ == 11)) {
             idType_ = s;
           }
           return s;
         }
       }
getIdBytes()
com.google.protobuf.ByteString getIdBytes ()
optional string id = 11;
Implements Geobuf.Data.FeatureOrBuilder.
{
         java.lang.Object ref = "";
         if (idTypeCase_ == 11) {
           ref = idType_;
         }
         if (ref instanceof java.lang.String) {
           com.google.protobuf.ByteString b =
               com.google.protobuf.ByteString.copyFromUtf8(
                   (java.lang.String) ref);
           if (idTypeCase_ == 11) {
             idType_ = b;
           }
           return b;
         } else {
           return (com.google.protobuf.ByteString) ref;
         }
       }
getIdTypeCase()
IdTypeCase getIdTypeCase ()
References Geobuf.Data.Feature.IdTypeCase.valueOf().
                       {
         return IdTypeCase.valueOf(
             idTypeCase_);
       }
getIntId()
long getIntId ()
optional sint64 int_id = 12;
Implements Geobuf.Data.FeatureOrBuilder.
{
         if (idTypeCase_ == 12) {
           return (java.lang.Long) idType_;
         }
         return 0L;
       }
getParserForType()
.lang.Override com.google.protobuf.Parser<Feature> getParserForType ()
{
         return PARSER;
       }
getProperties()
int getProperties (int index)
repeated uint32 properties = 14 [packed = true];
pairs of key/value indexes
Implements Geobuf.Data.FeatureOrBuilder.
{
         return properties_.get(index);
       }
getPropertiesCount()
int getPropertiesCount ()
repeated uint32 properties = 14 [packed = true];
pairs of key/value indexes
Implements Geobuf.Data.FeatureOrBuilder.
{
         return properties_.size();
       }
getPropertiesList()
java.util.List<java.lang.Integer> getPropertiesList ()
repeated uint32 properties = 14 [packed = true];
pairs of key/value indexes
Implements Geobuf.Data.FeatureOrBuilder.
{
         return properties_;
       }
getSerializedSize()
int getSerializedSize ()
{
         int size = memoizedSerializedSize;
         if (size != -1) return size;
         size = 0;
         if (((bitField0_ & 0x00000001) == 0x00000001)) {
           size += com.google.protobuf.CodedOutputStream
             .computeMessageSize(1, geometry_);
         }
         if (idTypeCase_ == 11) {
           size += com.google.protobuf.CodedOutputStream
             .computeBytesSize(11, getIdBytes());
         }
         if (idTypeCase_ == 12) {
           size += com.google.protobuf.CodedOutputStream
             .computeSInt64Size(
                 12, (long)((java.lang.Long) idType_));
         }
         for (int i = 0; i < values_.size(); i++) {
           size += com.google.protobuf.CodedOutputStream
             .computeMessageSize(13, values_.get(i));
         }
         {
           int dataSize = 0;
           for (int i = 0; i < properties_.size(); i++) {
             dataSize += com.google.protobuf.CodedOutputStream
               .computeUInt32SizeNoTag(properties_.get(i));
           }
           size += dataSize;
           if (!getPropertiesList().isEmpty()) {
             size += 1;
             size += com.google.protobuf.CodedOutputStream
                 .computeInt32SizeNoTag(dataSize);
           }
           propertiesMemoizedSerializedSize = dataSize;
         }
         {
           int dataSize = 0;
           for (int i = 0; i < customProperties_.size(); i++) {
             dataSize += com.google.protobuf.CodedOutputStream
               .computeUInt32SizeNoTag(customProperties_.get(i));
           }
           size += dataSize;
           if (!getCustomPropertiesList().isEmpty()) {
             size += 1;
             size += com.google.protobuf.CodedOutputStream
                 .computeInt32SizeNoTag(dataSize);
           }
           customPropertiesMemoizedSerializedSize = dataSize;
         }
         size += unknownFields.size();
         memoizedSerializedSize = size;
         return size;
       }
getValues()
Geobuf.Data.Value getValues (int index)
repeated .Data.Value values = 13;
unique values
Implements Geobuf.Data.FeatureOrBuilder.
{
         return values_.get(index);
       }
getValuesCount()
int getValuesCount ()
repeated .Data.Value values = 13;
unique values
Implements Geobuf.Data.FeatureOrBuilder.
{
         return values_.size();
       }
getValuesList()
java.util.List<Geobuf.Data.Value> getValuesList ()
repeated .Data.Value values = 13;
unique values
Implements Geobuf.Data.FeatureOrBuilder.
{
         return values_;
       }
getValuesOrBuilder()
Geobuf.Data.ValueOrBuilder getValuesOrBuilder (int index)
repeated .Data.Value values = 13;
unique values
                      {
         return values_.get(index);
       }
getValuesOrBuilderList()
java.util.List<? extends Geobuf.Data.ValueOrBuilder> getValuesOrBuilderList ()
repeated .Data.Value values = 13;
unique values
{
         return values_;
       }
hasGeometry()
boolean hasGeometry ()
required .Data.Geometry geometry = 1;
Implements Geobuf.Data.FeatureOrBuilder.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
hasId()
boolean hasId ()
optional string id = 11;
Implements Geobuf.Data.FeatureOrBuilder.
{
         return idTypeCase_ == 11;
       }
hasIntId()
boolean hasIntId ()
optional sint64 int_id = 12;
Implements Geobuf.Data.FeatureOrBuilder.
{
         return idTypeCase_ == 12;
       }
initFields()
void initFields () private
References Geobuf.Data.Geometry.getDefaultInstance().
Referenced by Geobuf.Data.Feature.Builder.clearCustomProperties().
{
         geometry_ = Geobuf.Data.Geometry.getDefaultInstance();
         values_ = java.util.Collections.emptyList();
         properties_ = java.util.Collections.emptyList();
         customProperties_ = java.util.Collections.emptyList();
       }
isInitialized()
final boolean isInitialized ()
References Geobuf.DataOrBuilder.getGeometry(), and Geobuf.DataOrBuilder.hasGeometry().
{
         byte isInitialized = memoizedIsInitialized;
         if (isInitialized == 1) return true;
         if (isInitialized == 0) return false;
         if (!hasGeometry()) {
           memoizedIsInitialized = 0;
           return false;
         }
         if (!getGeometry().isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
         memoizedIsInitialized = 1;
         return true;
       }
newBuilder() [1/2]
static Builder newBuilder () static
References Geobuf.Data.Feature.Builder.create().
Referenced by GeobufEncoder.makeFeature(), and Geobuf.Data.Builder.mergeFeature().
 { return Builder.create(); }
newBuilder() [2/2]
static Builder newBuilder (Geobuf.Data.Feature prototype) static
References Geobuf.Data.Feature.Builder.mergeFrom().
{
         return newBuilder().mergeFrom(prototype);
       }
newBuilderForType()
Builder newBuilderForType ()
 { return newBuilder(); }
parseDelimitedFrom() [1/2]
static Geobuf.Data.Feature parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException static
References Geobuf.Data.Feature.parseDelimitedFrom().
Referenced by Geobuf.Data.Feature.parseDelimitedFrom().
{
         return PARSER.parseDelimitedFrom(input);
       }
parseDelimitedFrom() [2/2]
static Geobuf.Data.Feature parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException static
References Geobuf.Data.Feature.parseDelimitedFrom().
{
         return PARSER.parseDelimitedFrom(input, extensionRegistry);
       }
parseFrom() [1/8]
static Geobuf.Data.Feature parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.Feature.parseFrom().
Referenced by Geobuf.Data.Feature.parseFrom().
{
         return PARSER.parseFrom(data);
       }
parseFrom() [2/8]
static Geobuf.Data.Feature parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.Feature.parseFrom().
{
         return PARSER.parseFrom(data, extensionRegistry);
       }
parseFrom() [3/8]
static Geobuf.Data.Feature parseFrom (byte [] data) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.Feature.parseFrom().
{
         return PARSER.parseFrom(data);
       }
parseFrom() [4/8]
static Geobuf.Data.Feature parseFrom (byte [] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.Feature.parseFrom().
{
         return PARSER.parseFrom(data, extensionRegistry);
       }
parseFrom() [5/8]
static Geobuf.Data.Feature parseFrom (java.io.InputStream input) throws java.io.IOException static
References Geobuf.Data.Feature.parseFrom().
{
         return PARSER.parseFrom(input);
       }
parseFrom() [6/8]
static Geobuf.Data.Feature parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException static
References Geobuf.Data.Feature.parseFrom().
{
         return PARSER.parseFrom(input, extensionRegistry);
       }
parseFrom() [7/8]
static Geobuf.Data.Feature parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException static
References Geobuf.Data.Feature.parseFrom().
{
         return PARSER.parseFrom(input);
       }
parseFrom() [8/8]
static Geobuf.Data.Feature parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException static
References Geobuf.Data.Feature.parseFrom().
{
         return PARSER.parseFrom(input, extensionRegistry);
       }
toBuilder()
Builder toBuilder ()
 { return newBuilder(this); }
writeReplace()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException protected
{
         return super.writeReplace();
       }
writeTo()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
{
         getSerializedSize();
         if (((bitField0_ & 0x00000001) == 0x00000001)) {
           output.writeMessage(1, geometry_);
         }
         if (idTypeCase_ == 11) {
           output.writeBytes(11, getIdBytes());
         }
         if (idTypeCase_ == 12) {
           output.writeSInt64(
               12, (long)((java.lang.Long) idType_));
         }
         for (int i = 0; i < values_.size(); i++) {
           output.writeMessage(13, values_.get(i));
         }
         if (getPropertiesList().size() > 0) {
           output.writeRawVarint32(114);
           output.writeRawVarint32(propertiesMemoizedSerializedSize);
         }
         for (int i = 0; i < properties_.size(); i++) {
           output.writeUInt32NoTag(properties_.get(i));
         }
         if (getCustomPropertiesList().size() > 0) {
           output.writeRawVarint32(122);
           output.writeRawVarint32(customPropertiesMemoizedSerializedSize);
         }
         for (int i = 0; i < customProperties_.size(); i++) {
           output.writeUInt32NoTag(customProperties_.get(i));
         }
         output.writeRawBytes(unknownFields);
       }
Member Data Documentation
bitField0_
int bitField0_ private
CUSTOM_PROPERTIES_FIELD_NUMBER
final int CUSTOM_PROPERTIES_FIELD_NUMBER = 15 static
customProperties_
java.util.List<java.lang.Integer> customProperties_ private
customPropertiesMemoizedSerializedSize
int customPropertiesMemoizedSerializedSize = -1 private
defaultInstance
final Feature defaultInstance static private
geometry_
Geobuf.Data.Geometry geometry_ private
Referenced by Geobuf.Data.Feature.Builder.buildPartial().
GEOMETRY_FIELD_NUMBER
final int GEOMETRY_FIELD_NUMBER = 1 static
ID_FIELD_NUMBER
final int ID_FIELD_NUMBER = 11 static
idType_
java.lang.Object idType_ private
idTypeCase_
int idTypeCase_ = 0 private
INT_ID_FIELD_NUMBER
final int INT_ID_FIELD_NUMBER = 12 static
memoizedIsInitialized
byte memoizedIsInitialized = -1 private
memoizedSerializedSize
int memoizedSerializedSize = -1 private
PARSER
com.google.protobuf.Parser<Feature> PARSER static
Initial value:
=
          new com.google.protobuf.AbstractParser<Feature>() {
        public Feature parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Feature(input, extensionRegistry);
        }
      }
Referenced by Geobuf.Data.Data(), and Geobuf.Data.FeatureCollection.FeatureCollection().
properties_
java.util.List<java.lang.Integer> properties_ private
PROPERTIES_FIELD_NUMBER
final int PROPERTIES_FIELD_NUMBER = 14 static
propertiesMemoizedSerializedSize
int propertiesMemoizedSerializedSize = -1 private
serialVersionUID
final long serialVersionUID = 0L static private
unknownFields
final com.google.protobuf.ByteString unknownFields private
values_
java.util.List<Geobuf.Data.Value> values_ private
VALUES_FIELD_NUMBER
final int VALUES_FIELD_NUMBER = 13 static