jena-geo: Geobuf.Data.FeatureCollection Class Reference
Geobuf.Data.FeatureCollection Class Reference
Protobuf type.
Classes
class Builder
Protobuf type.
Public Member Functions
FeatureCollection getDefaultInstanceForType ()
.lang.Override com.google.protobuf.Parser< FeatureCollection > getParserForType ()
java.util.List< Geobuf.Data.Feature > getFeaturesList ()
repeated .Data.Feature features = 1;
java.util.List<? extends Geobuf.Data.FeatureOrBuilder > getFeaturesOrBuilderList ()
repeated .Data.Feature features = 1;
int getFeaturesCount ()
repeated .Data.Feature features = 1;
Geobuf.Data.Feature getFeatures (int index)
repeated .Data.Feature features = 1;
Geobuf.Data.FeatureOrBuilder getFeaturesOrBuilder (int index)
repeated .Data.Feature features = 1;
java.util.List< Geobuf.Data.Value > getValuesList ()
repeated .Data.Value values = 13;
java.util.List<? extends Geobuf.Data.ValueOrBuilder > getValuesOrBuilderList ()
repeated .Data.Value values = 13;
int getValuesCount ()
repeated .Data.Value values = 13;
Geobuf.Data.Value getValues (int index)
repeated .Data.Value values = 13;
Geobuf.Data.ValueOrBuilder getValuesOrBuilder (int index)
repeated .Data.Value values = 13;
java.util.List< java.lang.Integer > getCustomPropertiesList ()
repeated uint32 custom_properties = 15 [packed = true];
int getCustomPropertiesCount ()
repeated uint32 custom_properties = 15 [packed = true];
int getCustomProperties (int index)
repeated uint32 custom_properties = 15 [packed = true];
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static FeatureCollection getDefaultInstance ()
static Geobuf.Data.FeatureCollection parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.FeatureCollection parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.FeatureCollection parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.FeatureCollection parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.FeatureCollection parseFrom (java.io.InputStream input) throws java.io.IOException
static Geobuf.Data.FeatureCollection parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Geobuf.Data.FeatureCollection parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static Geobuf.Data.FeatureCollection parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Geobuf.Data.FeatureCollection parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static Geobuf.Data.FeatureCollection parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (Geobuf.Data.FeatureCollection prototype)
Static Public Attributes
static com.google.protobuf.Parser< FeatureCollection > PARSER
static final int FEATURES_FIELD_NUMBER = 1
static final int VALUES_FIELD_NUMBER = 13
static final int CUSTOM_PROPERTIES_FIELD_NUMBER = 15
Protected Member Functions
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
Static Package Functions
[static initializer]
Private Member Functions
FeatureCollection (com.google.protobuf.GeneratedMessageLite.Builder builder)
FeatureCollection (boolean noInit)
FeatureCollection (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
void initFields ()
Private Attributes
final com.google.protobuf.ByteString unknownFields
java.util.List< Geobuf.Data.Feature > features_
java.util.List< Geobuf.Data.Value > values_
java.util.List< java.lang.Integer > customProperties_
int customPropertiesMemoizedSerializedSize = -1
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final FeatureCollection defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Protobuf type.
Data.FeatureCollection
Constructor & Destructor Documentation
FeatureCollection() [1/3]
FeatureCollection (com.google.protobuf.GeneratedMessageLite.Builder builder) private
{
         super(builder);
         this.unknownFields = builder.getUnknownFields();
       }
FeatureCollection() [2/3]
FeatureCollection (boolean noInit) private
 { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}
FeatureCollection() [3/3]
FeatureCollection (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException private
References Geobuf.Data.Feature.PARSER, and Geobuf.Data.Value.PARSER.
{
         initFields();
         int mutable_bitField0_ = 0;
         com.google.protobuf.ByteString.Output unknownFieldsOutput =
             com.google.protobuf.ByteString.newOutput();
         com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
             com.google.protobuf.CodedOutputStream.newInstance(
                 unknownFieldsOutput);
         try {
           boolean done = false;
           while (!done) {
             int tag = input.readTag();
             switch (tag) {
               case 0:
                 done = true;
                 break;
               default: {
                 if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                        extensionRegistry, tag)) {
                   done = true;
                 }
                 break;
               }
               case 10: {
                 if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                   features_ = new java.util.ArrayList<Geobuf.Data.Feature>();
                   mutable_bitField0_ |= 0x00000001;
                 }
                 features_.add(input.readMessage(Geobuf.Data.Feature.PARSER, extensionRegistry));
                 break;
               }
               case 106: {
                 if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                   values_ = new java.util.ArrayList<Geobuf.Data.Value>();
                   mutable_bitField0_ |= 0x00000002;
                 }
                 values_.add(input.readMessage(Geobuf.Data.Value.PARSER, extensionRegistry));
                 break;
               }
               case 120: {
                 if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                   customProperties_ = new java.util.ArrayList<java.lang.Integer>();
                   mutable_bitField0_ |= 0x00000004;
                 }
                 customProperties_.add(input.readUInt32());
                 break;
               }
               case 122: {
                 int length = input.readRawVarint32();
                 int limit = input.pushLimit(length);
                 if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                   customProperties_ = new java.util.ArrayList<java.lang.Integer>();
                   mutable_bitField0_ |= 0x00000004;
                 }
                 while (input.getBytesUntilLimit() > 0) {
                   customProperties_.add(input.readUInt32());
                 }
                 input.popLimit(limit);
                 break;
               }
             }
           }
         } catch (com.google.protobuf.InvalidProtocolBufferException e) {
           throw e.setUnfinishedMessage(this);
         } catch (java.io.IOException e) {
           throw new com.google.protobuf.InvalidProtocolBufferException(
               e.getMessage()).setUnfinishedMessage(this);
         } finally {
           if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
             features_ = java.util.Collections.unmodifiableList(features_);
           }
           if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
             values_ = java.util.Collections.unmodifiableList(values_);
           }
           if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
             customProperties_ = java.util.Collections.unmodifiableList(customProperties_);
           }
           try {
             unknownFieldsCodedOutput.flush();
           } catch (java.io.IOException e) {
           // Should not happen
           } finally {
             unknownFields = unknownFieldsOutput.toByteString();
           }
           makeExtensionsImmutable();
         }
       }
Member Function Documentation
[static initializer]()
[static initializer] () static package
getCustomProperties()
int getCustomProperties (int index)
repeated uint32 custom_properties = 15 [packed = true];
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
         return customProperties_.get(index);
       }
getCustomPropertiesCount()
int getCustomPropertiesCount ()
repeated uint32 custom_properties = 15 [packed = true];
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
         return customProperties_.size();
       }
getCustomPropertiesList()
java.util.List<java.lang.Integer> getCustomPropertiesList ()
repeated uint32 custom_properties = 15 [packed = true];
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
         return customProperties_;
       }
getDefaultInstance()
static FeatureCollection getDefaultInstance () static
Referenced by Geobuf.Data.FeatureCollection.Builder.getDefaultInstanceForType(), Geobuf.Data.getFeatureCollection(), Geobuf.Data.Builder.getFeatureCollection(), Geobuf.Data.Builder.mergeFeatureCollection(), and Geobuf.Data.FeatureCollection.Builder.mergeFrom().
{
         return defaultInstance;
       }
getDefaultInstanceForType()
FeatureCollection getDefaultInstanceForType ()
{
         return defaultInstance;
       }
getFeatures()
Geobuf.Data.Feature getFeatures (int index)
repeated .Data.Feature features = 1;
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
         return features_.get(index);
       }
getFeaturesCount()
int getFeaturesCount ()
repeated .Data.Feature features = 1;
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
         return features_.size();
       }
getFeaturesList()
java.util.List<Geobuf.Data.Feature> getFeaturesList ()
repeated .Data.Feature features = 1;
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
         return features_;
       }
getFeaturesOrBuilder()
Geobuf.Data.FeatureOrBuilder getFeaturesOrBuilder (int index)
repeated .Data.Feature features = 1;
                      {
         return features_.get(index);
       }
getFeaturesOrBuilderList()
java.util.List<? extends Geobuf.Data.FeatureOrBuilder> getFeaturesOrBuilderList ()
repeated .Data.Feature features = 1;
{
         return features_;
       }
getParserForType()
.lang.Override com.google.protobuf.Parser<FeatureCollection> getParserForType ()
{
         return PARSER;
       }
getSerializedSize()
int getSerializedSize ()
{
         int size = memoizedSerializedSize;
         if (size != -1) return size;
         size = 0;
         for (int i = 0; i < features_.size(); i++) {
           size += com.google.protobuf.CodedOutputStream
             .computeMessageSize(1, features_.get(i));
         }
         for (int i = 0; i < values_.size(); i++) {
           size += com.google.protobuf.CodedOutputStream
             .computeMessageSize(13, values_.get(i));
         }
         {
           int dataSize = 0;
           for (int i = 0; i < customProperties_.size(); i++) {
             dataSize += com.google.protobuf.CodedOutputStream
               .computeUInt32SizeNoTag(customProperties_.get(i));
           }
           size += dataSize;
           if (!getCustomPropertiesList().isEmpty()) {
             size += 1;
             size += com.google.protobuf.CodedOutputStream
                 .computeInt32SizeNoTag(dataSize);
           }
           customPropertiesMemoizedSerializedSize = dataSize;
         }
         size += unknownFields.size();
         memoizedSerializedSize = size;
         return size;
       }
getValues()
Geobuf.Data.Value getValues (int index)
repeated .Data.Value values = 13;
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
         return values_.get(index);
       }
getValuesCount()
int getValuesCount ()
repeated .Data.Value values = 13;
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
         return values_.size();
       }
getValuesList()
java.util.List<Geobuf.Data.Value> getValuesList ()
repeated .Data.Value values = 13;
Implements Geobuf.Data.FeatureCollectionOrBuilder.
{
         return values_;
       }
getValuesOrBuilder()
Geobuf.Data.ValueOrBuilder getValuesOrBuilder (int index)
repeated .Data.Value values = 13;
                      {
         return values_.get(index);
       }
getValuesOrBuilderList()
java.util.List<? extends Geobuf.Data.ValueOrBuilder> getValuesOrBuilderList ()
repeated .Data.Value values = 13;
{
         return values_;
       }
initFields()
void initFields () private
Referenced by Geobuf.Data.FeatureCollection.Builder.clearCustomProperties(), and Geobuf.Data.Builder.clearGeometry().
{
         features_ = java.util.Collections.emptyList();
         values_ = java.util.Collections.emptyList();
         customProperties_ = java.util.Collections.emptyList();
       }
isInitialized()
final boolean isInitialized ()
{
         byte isInitialized = memoizedIsInitialized;
         if (isInitialized == 1) return true;
         if (isInitialized == 0) return false;
         for (int i = 0; i < getFeaturesCount(); i++) {
           if (!getFeatures(i).isInitialized()) {
             memoizedIsInitialized = 0;
             return false;
           }
         }
         memoizedIsInitialized = 1;
         return true;
       }
newBuilder() [1/2]
static Builder newBuilder () static
References Geobuf.Data.FeatureCollection.Builder.create().
Referenced by GeobufEncoder.makeFeatureCollection(), and Geobuf.Data.Builder.mergeFeatureCollection().
 { return Builder.create(); }
newBuilder() [2/2]
static Builder newBuilder (Geobuf.Data.FeatureCollection prototype) static
References Geobuf.Data.FeatureCollection.Builder.mergeFrom().
{
         return newBuilder().mergeFrom(prototype);
       }
newBuilderForType()
Builder newBuilderForType ()
 { return newBuilder(); }
parseDelimitedFrom() [1/2]
static Geobuf.Data.FeatureCollection parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException static
References Geobuf.Data.FeatureCollection.parseDelimitedFrom().
Referenced by Geobuf.Data.FeatureCollection.parseDelimitedFrom(), and Geobuf.Data.parseDelimitedFrom().
{
         return PARSER.parseDelimitedFrom(input);
       }
parseDelimitedFrom() [2/2]
static Geobuf.Data.FeatureCollection parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException static
References Geobuf.Data.FeatureCollection.parseDelimitedFrom().
{
         return PARSER.parseDelimitedFrom(input, extensionRegistry);
       }
parseFrom() [1/8]
static Geobuf.Data.FeatureCollection parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.FeatureCollection.parseFrom().
Referenced by Geobuf.Data.FeatureCollection.parseFrom(), and Geobuf.Data.parseFrom().
{
         return PARSER.parseFrom(data);
       }
parseFrom() [2/8]
static Geobuf.Data.FeatureCollection parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.FeatureCollection.parseFrom().
{
         return PARSER.parseFrom(data, extensionRegistry);
       }
parseFrom() [3/8]
static Geobuf.Data.FeatureCollection parseFrom (byte [] data) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.FeatureCollection.parseFrom().
{
         return PARSER.parseFrom(data);
       }
parseFrom() [4/8]
static Geobuf.Data.FeatureCollection parseFrom (byte [] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.FeatureCollection.parseFrom().
{
         return PARSER.parseFrom(data, extensionRegistry);
       }
parseFrom() [5/8]
static Geobuf.Data.FeatureCollection parseFrom (java.io.InputStream input) throws java.io.IOException static
References Geobuf.Data.FeatureCollection.parseFrom().
{
         return PARSER.parseFrom(input);
       }
parseFrom() [6/8]
static Geobuf.Data.FeatureCollection parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException static
References Geobuf.Data.FeatureCollection.parseFrom().
{
         return PARSER.parseFrom(input, extensionRegistry);
       }
parseFrom() [7/8]
static Geobuf.Data.FeatureCollection parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException static
References Geobuf.Data.FeatureCollection.parseFrom().
{
         return PARSER.parseFrom(input);
       }
parseFrom() [8/8]
static Geobuf.Data.FeatureCollection parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException static
References Geobuf.Data.FeatureCollection.parseFrom().
{
         return PARSER.parseFrom(input, extensionRegistry);
       }
toBuilder()
Builder toBuilder ()
 { return newBuilder(this); }
writeReplace()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException protected
{
         return super.writeReplace();
       }
writeTo()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
{
         getSerializedSize();
         for (int i = 0; i < features_.size(); i++) {
           output.writeMessage(1, features_.get(i));
         }
         for (int i = 0; i < values_.size(); i++) {
           output.writeMessage(13, values_.get(i));
         }
         if (getCustomPropertiesList().size() > 0) {
           output.writeRawVarint32(122);
           output.writeRawVarint32(customPropertiesMemoizedSerializedSize);
         }
         for (int i = 0; i < customProperties_.size(); i++) {
           output.writeUInt32NoTag(customProperties_.get(i));
         }
         output.writeRawBytes(unknownFields);
       }
Member Data Documentation
CUSTOM_PROPERTIES_FIELD_NUMBER
final int CUSTOM_PROPERTIES_FIELD_NUMBER = 15 static
customProperties_
java.util.List<java.lang.Integer> customProperties_ private
customPropertiesMemoizedSerializedSize
int customPropertiesMemoizedSerializedSize = -1 private
defaultInstance
final FeatureCollection defaultInstance static private
features_
java.util.List<Geobuf.Data.Feature> features_ private
Referenced by Geobuf.Data.FeatureCollection.Builder.buildPartial().
FEATURES_FIELD_NUMBER
final int FEATURES_FIELD_NUMBER = 1 static
memoizedIsInitialized
byte memoizedIsInitialized = -1 private
memoizedSerializedSize
int memoizedSerializedSize = -1 private
PARSER
com.google.protobuf.Parser<FeatureCollection> PARSER static
Initial value:
=
          new com.google.protobuf.AbstractParser<FeatureCollection>() {
        public FeatureCollection parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new FeatureCollection(input, extensionRegistry);
        }
      }
Referenced by Geobuf.Data.Data().
serialVersionUID
final long serialVersionUID = 0L static private
unknownFields
final com.google.protobuf.ByteString unknownFields private
values_
java.util.List<Geobuf.Data.Value> values_ private
VALUES_FIELD_NUMBER
final int VALUES_FIELD_NUMBER = 13 static