jena-geo: Geobuf.Data Class Reference
Geobuf.Data Class Reference
Protobuf type.
Classes
class Builder
Protobuf type.
enum DataTypeCase
class Feature
Protobuf type.
class FeatureCollection
Protobuf type.
interface FeatureCollectionOrBuilder
interface FeatureOrBuilder
class Geometry
Protobuf type.
interface GeometryOrBuilder
class Value
Protobuf type.
interface ValueOrBuilder
Public Member Functions
Data getDefaultInstanceForType ()
.lang.Override com.google.protobuf.Parser< Data > getParserForType ()
DataTypeCase getDataTypeCase ()
com.google.protobuf.ProtocolStringList getKeysList ()
repeated string keys = 1;
int getKeysCount ()
repeated string keys = 1;
java.lang.String getKeys (int index)
repeated string keys = 1;
com.google.protobuf.ByteString getKeysBytes (int index)
repeated string keys = 1;
boolean hasDimensions ()
optional uint32 dimensions = 2 [default = 2];
int getDimensions ()
optional uint32 dimensions = 2 [default = 2];
boolean hasPrecision ()
optional uint32 precision = 3 [default = 6];
int getPrecision ()
optional uint32 precision = 3 [default = 6];
boolean hasFeatureCollection ()
optional .Data.FeatureCollection feature_collection = 4;
Geobuf.Data.FeatureCollection getFeatureCollection ()
optional .Data.FeatureCollection feature_collection = 4;
boolean hasFeature ()
optional .Data.Feature feature = 5;
Geobuf.Data.Feature getFeature ()
optional .Data.Feature feature = 5;
boolean hasGeometry ()
optional .Data.Geometry geometry = 6;
Geobuf.Data.Geometry getGeometry ()
optional .Data.Geometry geometry = 6;
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static Data getDefaultInstance ()
static Geobuf.Data parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data parseFrom (java.io.InputStream input) throws java.io.IOException
static Geobuf.Data parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Geobuf.Data parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static Geobuf.Data parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Geobuf.Data parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static Geobuf.Data parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (Geobuf.Data prototype)
Static Public Attributes
static com.google.protobuf.Parser< Data > PARSER
static final int KEYS_FIELD_NUMBER = 1
static final int DIMENSIONS_FIELD_NUMBER = 2
static final int PRECISION_FIELD_NUMBER = 3
static final int FEATURE_COLLECTION_FIELD_NUMBER = 4
static final int FEATURE_FIELD_NUMBER = 5
static final int GEOMETRY_FIELD_NUMBER = 6
Protected Member Functions
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
Static Package Functions
[static initializer]
Private Member Functions
Data (com.google.protobuf.GeneratedMessageLite.Builder builder)
Data (boolean noInit)
Data (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
void initFields ()
Private Attributes
final com.google.protobuf.ByteString unknownFields
int bitField0_
int dataTypeCase_ = 0
java.lang.Object dataType_
com.google.protobuf.LazyStringList keys_
int dimensions_
int precision_
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final Data defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Protobuf type.
Data
Constructor & Destructor Documentation
Data() [1/3]
Data (com.google.protobuf.GeneratedMessageLite.Builder builder) private
{
       super(builder);
       this.unknownFields = builder.getUnknownFields();
     }
Data() [2/3]
Data (boolean noInit) private
 { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}
Data() [3/3]
Data (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException private
References Geobuf.Data.Feature.Builder.buildPartial(), Geobuf.Data.Geometry.Builder.buildPartial(), Geobuf.Data.FeatureCollection.Builder.buildPartial(), Geobuf.Data.Feature.Builder.mergeFrom(), Geobuf.Data.Geometry.Builder.mergeFrom(), Geobuf.Data.FeatureCollection.Builder.mergeFrom(), Geobuf.Data.Feature.PARSER, Geobuf.Data.Geometry.PARSER, and Geobuf.Data.FeatureCollection.PARSER.
{
       initFields();
       int mutable_bitField0_ = 0;
       com.google.protobuf.ByteString.Output unknownFieldsOutput =
           com.google.protobuf.ByteString.newOutput();
       com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
           com.google.protobuf.CodedOutputStream.newInstance(
               unknownFieldsOutput);
       try {
         boolean done = false;
         while (!done) {
           int tag = input.readTag();
           switch (tag) {
             case 0:
               done = true;
               break;
             default: {
               if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                      extensionRegistry, tag)) {
                 done = true;
               }
               break;
             }
             case 10: {
               com.google.protobuf.ByteString bs = input.readBytes();
               if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                 keys_ = new com.google.protobuf.LazyStringArrayList();
                 mutable_bitField0_ |= 0x00000001;
               }
               keys_.add(bs);
               break;
             }
             case 16: {
               bitField0_ |= 0x00000001;
               dimensions_ = input.readUInt32();
               break;
             }
             case 24: {
               bitField0_ |= 0x00000002;
               precision_ = input.readUInt32();
               break;
             }
             case 34: {
               Geobuf.Data.FeatureCollection.Builder subBuilder = null;
               if (dataTypeCase_ == 4) {
                 subBuilder = ((Geobuf.Data.FeatureCollection) dataType_).toBuilder();
               }
               dataType_ = input.readMessage(Geobuf.Data.FeatureCollection.PARSER, extensionRegistry);
               if (subBuilder != null) {
                 subBuilder.mergeFrom((Geobuf.Data.FeatureCollection) dataType_);
                 dataType_ = subBuilder.buildPartial();
               }
               dataTypeCase_ = 4;
               break;
             }
             case 42: {
               Geobuf.Data.Feature.Builder subBuilder = null;
               if (dataTypeCase_ == 5) {
                 subBuilder = ((Geobuf.Data.Feature) dataType_).toBuilder();
               }
               dataType_ = input.readMessage(Geobuf.Data.Feature.PARSER, extensionRegistry);
               if (subBuilder != null) {
                 subBuilder.mergeFrom((Geobuf.Data.Feature) dataType_);
                 dataType_ = subBuilder.buildPartial();
               }
               dataTypeCase_ = 5;
               break;
             }
             case 50: {
               Geobuf.Data.Geometry.Builder subBuilder = null;
               if (dataTypeCase_ == 6) {
                 subBuilder = ((Geobuf.Data.Geometry) dataType_).toBuilder();
               }
               dataType_ = input.readMessage(Geobuf.Data.Geometry.PARSER, extensionRegistry);
               if (subBuilder != null) {
                 subBuilder.mergeFrom((Geobuf.Data.Geometry) dataType_);
                 dataType_ = subBuilder.buildPartial();
               }
               dataTypeCase_ = 6;
               break;
             }
           }
         }
       } catch (com.google.protobuf.InvalidProtocolBufferException e) {
         throw e.setUnfinishedMessage(this);
       } catch (java.io.IOException e) {
         throw new com.google.protobuf.InvalidProtocolBufferException(
             e.getMessage()).setUnfinishedMessage(this);
       } finally {
         if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
           keys_ = keys_.getUnmodifiableView();
         }
         try {
           unknownFieldsCodedOutput.flush();
         } catch (java.io.IOException e) {
         // Should not happen
         } finally {
           unknownFields = unknownFieldsOutput.toByteString();
         }
         makeExtensionsImmutable();
       }
     }
Member Function Documentation
[static initializer]()
[static initializer] () static package
getDataTypeCase()
DataTypeCase getDataTypeCase ()
References Geobuf.Data.DataTypeCase.valueOf().
                       {
       return DataTypeCase.valueOf(
           dataTypeCase_);
     }
getDefaultInstance()
static Data getDefaultInstance () static
Referenced by Geobuf.Data.Builder.getDefaultInstanceForType(), and Geobuf.Data.Builder.mergeFrom().
{
       return defaultInstance;
     }
getDefaultInstanceForType()
Data getDefaultInstanceForType ()
{
       return defaultInstance;
     }
getDimensions()
int getDimensions ()
optional uint32 dimensions = 2 [default = 2];
max coordinate dimensions
Implements Geobuf.DataOrBuilder.
{
       return dimensions_;
     }
getFeature()
Geobuf.Data.Feature getFeature ()
optional .Data.Feature feature = 5;
Implements Geobuf.DataOrBuilder.
References Geobuf.Data.Feature.getDefaultInstance().
{
       if (dataTypeCase_ == 5) {
          return (Geobuf.Data.Feature) dataType_;
       }
       return Geobuf.Data.Feature.getDefaultInstance();
     }
getFeatureCollection()
Geobuf.Data.FeatureCollection getFeatureCollection ()
optional .Data.FeatureCollection feature_collection = 4;
Implements Geobuf.DataOrBuilder.
References Geobuf.Data.FeatureCollection.getDefaultInstance().
{
       if (dataTypeCase_ == 4) {
          return (Geobuf.Data.FeatureCollection) dataType_;
       }
       return Geobuf.Data.FeatureCollection.getDefaultInstance();
     }
getGeometry()
Geobuf.Data.Geometry getGeometry ()
optional .Data.Geometry geometry = 6;
Implements Geobuf.DataOrBuilder.
References Geobuf.Data.Geometry.getDefaultInstance().
{
       if (dataTypeCase_ == 6) {
          return (Geobuf.Data.Geometry) dataType_;
       }
       return Geobuf.Data.Geometry.getDefaultInstance();
     }
getKeys()
java.lang.String getKeys (int index)
repeated string keys = 1;
global arrays of unique keys
Implements Geobuf.DataOrBuilder.
{
       return keys_.get(index);
     }
getKeysBytes()
com.google.protobuf.ByteString getKeysBytes (int index)
repeated string keys = 1;
global arrays of unique keys
Implements Geobuf.DataOrBuilder.
{
       return keys_.getByteString(index);
     }
getKeysCount()
int getKeysCount ()
repeated string keys = 1;
global arrays of unique keys
Implements Geobuf.DataOrBuilder.
{
       return keys_.size();
     }
getKeysList()
com.google.protobuf.ProtocolStringList getKeysList ()
repeated string keys = 1;
global arrays of unique keys
Implements Geobuf.DataOrBuilder.
                       {
       return keys_;
     }
getParserForType()
.lang.Override com.google.protobuf.Parser<Data> getParserForType ()
{
       return PARSER;
     }
getPrecision()
int getPrecision ()
optional uint32 precision = 3 [default = 6];
number of digits after decimal point for coordinates
Implements Geobuf.DataOrBuilder.
{
       return precision_;
     }
getSerializedSize()
int getSerializedSize ()
References Geobuf.DataOrBuilder.getKeysList().
{
       int size = memoizedSerializedSize;
       if (size != -1) return size;
       size = 0;
       {
         int dataSize = 0;
         for (int i = 0; i < keys_.size(); i++) {
           dataSize += com.google.protobuf.CodedOutputStream
             .computeBytesSizeNoTag(keys_.getByteString(i));
         }
         size += dataSize;
         size += 1 * getKeysList().size();
       }
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         size += com.google.protobuf.CodedOutputStream
           .computeUInt32Size(2, dimensions_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         size += com.google.protobuf.CodedOutputStream
           .computeUInt32Size(3, precision_);
       }
       if (dataTypeCase_ == 4) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(4, (Geobuf.Data.FeatureCollection) dataType_);
       }
       if (dataTypeCase_ == 5) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(5, (Geobuf.Data.Feature) dataType_);
       }
       if (dataTypeCase_ == 6) {
         size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(6, (Geobuf.Data.Geometry) dataType_);
       }
       size += unknownFields.size();
       memoizedSerializedSize = size;
       return size;
     }
hasDimensions()
boolean hasDimensions ()
optional uint32 dimensions = 2 [default = 2];
max coordinate dimensions
Implements Geobuf.DataOrBuilder.
{
       return ((bitField0_ & 0x00000001) == 0x00000001);
     }
hasFeature()
boolean hasFeature ()
optional .Data.Feature feature = 5;
Implements Geobuf.DataOrBuilder.
{
       return dataTypeCase_ == 5;
     }
hasFeatureCollection()
boolean hasFeatureCollection ()
optional .Data.FeatureCollection feature_collection = 4;
Implements Geobuf.DataOrBuilder.
{
       return dataTypeCase_ == 4;
     }
hasGeometry()
boolean hasGeometry ()
optional .Data.Geometry geometry = 6;
Implements Geobuf.DataOrBuilder.
{
       return dataTypeCase_ == 6;
     }
hasPrecision()
boolean hasPrecision ()
optional uint32 precision = 3 [default = 6];
number of digits after decimal point for coordinates
Implements Geobuf.DataOrBuilder.
{
       return ((bitField0_ & 0x00000002) == 0x00000002);
     }
initFields()
void initFields () private
{
       keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
       dimensions_ = 2;
       precision_ = 6;
     }
isInitialized()
final boolean isInitialized ()
References Geobuf.DataOrBuilder.getFeature(), Geobuf.DataOrBuilder.getFeatureCollection(), Geobuf.DataOrBuilder.getGeometry(), Geobuf.DataOrBuilder.hasFeature(), Geobuf.DataOrBuilder.hasFeatureCollection(), and Geobuf.DataOrBuilder.hasGeometry().
{
       byte isInitialized = memoizedIsInitialized;
       if (isInitialized == 1) return true;
       if (isInitialized == 0) return false;
       if (hasFeatureCollection()) {
         if (!getFeatureCollection().isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
       }
       if (hasFeature()) {
         if (!getFeature().isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
       }
       if (hasGeometry()) {
         if (!getGeometry().isInitialized()) {
           memoizedIsInitialized = 0;
           return false;
         }
       }
       memoizedIsInitialized = 1;
       return true;
     }
newBuilder() [1/2]
static Builder newBuilder () static
References Geobuf.Data.Builder.create().
Referenced by GeobufEncoder.makeFeatureCollection().
 { return Builder.create(); }
newBuilder() [2/2]
static Builder newBuilder (Geobuf.Data prototype) static
References Geobuf.Data.Builder.mergeFrom().
{
       return newBuilder().mergeFrom(prototype);
     }
newBuilderForType()
Builder newBuilderForType ()
 { return newBuilder(); }
parseDelimitedFrom() [1/2]
static Geobuf.Data parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException static
References Geobuf.Data.FeatureCollection.parseDelimitedFrom().
{
       return PARSER.parseDelimitedFrom(input);
     }
parseDelimitedFrom() [2/2]
static Geobuf.Data parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException static
References Geobuf.Data.FeatureCollection.parseDelimitedFrom().
{
       return PARSER.parseDelimitedFrom(input, extensionRegistry);
     }
parseFrom() [1/8]
static Geobuf.Data parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.FeatureCollection.parseFrom().
Referenced by GeobufEncoder.GeobufFeatureSerializer.deserialize(), and GeobufDecoder.GeobufDecoder().
{
       return PARSER.parseFrom(data);
     }
parseFrom() [2/8]
static Geobuf.Data parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.FeatureCollection.parseFrom().
{
       return PARSER.parseFrom(data, extensionRegistry);
     }
parseFrom() [3/8]
static Geobuf.Data parseFrom (byte [] data) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.FeatureCollection.parseFrom().
{
       return PARSER.parseFrom(data);
     }
parseFrom() [4/8]
static Geobuf.Data parseFrom (byte [] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.FeatureCollection.parseFrom().
{
       return PARSER.parseFrom(data, extensionRegistry);
     }
parseFrom() [5/8]
static Geobuf.Data parseFrom (java.io.InputStream input) throws java.io.IOException static
References Geobuf.Data.FeatureCollection.parseFrom().
{
       return PARSER.parseFrom(input);
     }
parseFrom() [6/8]
static Geobuf.Data parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException static
References Geobuf.Data.FeatureCollection.parseFrom().
{
       return PARSER.parseFrom(input, extensionRegistry);
     }
parseFrom() [7/8]
static Geobuf.Data parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException static
References Geobuf.Data.FeatureCollection.parseFrom().
{
       return PARSER.parseFrom(input);
     }
parseFrom() [8/8]
static Geobuf.Data parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException static
References Geobuf.Data.FeatureCollection.parseFrom().
{
       return PARSER.parseFrom(input, extensionRegistry);
     }
toBuilder()
Builder toBuilder ()
 { return newBuilder(this); }
writeReplace()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException protected
{
       return super.writeReplace();
     }
writeTo()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
{
       getSerializedSize();
       for (int i = 0; i < keys_.size(); i++) {
         output.writeBytes(1, keys_.getByteString(i));
       }
       if (((bitField0_ & 0x00000001) == 0x00000001)) {
         output.writeUInt32(2, dimensions_);
       }
       if (((bitField0_ & 0x00000002) == 0x00000002)) {
         output.writeUInt32(3, precision_);
       }
       if (dataTypeCase_ == 4) {
         output.writeMessage(4, (Geobuf.Data.FeatureCollection) dataType_);
       }
       if (dataTypeCase_ == 5) {
         output.writeMessage(5, (Geobuf.Data.Feature) dataType_);
       }
       if (dataTypeCase_ == 6) {
         output.writeMessage(6, (Geobuf.Data.Geometry) dataType_);
       }
       output.writeRawBytes(unknownFields);
     }
Member Data Documentation
bitField0_
int bitField0_ private
dataType_
java.lang.Object dataType_ private
dataTypeCase_
int dataTypeCase_ = 0 private
defaultInstance
final Data defaultInstance static private
dimensions_
int dimensions_ private
DIMENSIONS_FIELD_NUMBER
final int DIMENSIONS_FIELD_NUMBER = 2 static
FEATURE_COLLECTION_FIELD_NUMBER
final int FEATURE_COLLECTION_FIELD_NUMBER = 4 static
FEATURE_FIELD_NUMBER
final int FEATURE_FIELD_NUMBER = 5 static
GEOMETRY_FIELD_NUMBER
final int GEOMETRY_FIELD_NUMBER = 6 static
keys_
com.google.protobuf.LazyStringList keys_ private
Referenced by Geobuf.Data.Builder.buildPartial().
KEYS_FIELD_NUMBER
final int KEYS_FIELD_NUMBER = 1 static
memoizedIsInitialized
byte memoizedIsInitialized = -1 private
memoizedSerializedSize
int memoizedSerializedSize = -1 private
PARSER
com.google.protobuf.Parser<Data> PARSER static
Initial value:
=
        new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    }
precision_
int precision_ private
PRECISION_FIELD_NUMBER
final int PRECISION_FIELD_NUMBER = 3 static
serialVersionUID
final long serialVersionUID = 0L static private
unknownFields
final com.google.protobuf.ByteString unknownFields private