jena-geo: LiteralUtils Class Reference
LiteralUtils Class Reference
Static Public Member Functions
static Wrapper rasterOrVector (NodeValue v)
static Coordinate worldToRaster (CoverageWrapper wrapper, Double latitude, Double longitude) throws MismatchedDimensionException, TransformException
static NodeValue cropRaster (CoverageWrapper wrapper, Double width, Double height, Double x, Double y) throws MismatchedDimensionException, TransformException
static NodeValue createEmptyRaster (Double width, Double height, Double upperleftx, Double upperlefty, Double val)
static Geometry getCorrectVectorRepresentation (Wrapper wrapper)
static Geometry toGeometry (final Envelope2D envelope)
static Geometry toGeometry (final OctagonalEnvelope envelope)
static Geometry toGeometry (final Envelope envelope)
static Geometry toGeometry (final org.opengis.geometry.Envelope envelope)
static Geometry toGeometry (final Rectangle envelope)
static GeometryWrapper createGeometry (List< Coordinate > coordinates, String geomtype, GeometryWrapper geometry)
static GeometryWrapper createGeometry (Coordinate[] coordarray, String geomtype, GeometryWrapper geometry)
Member Function Documentation
createEmptyRaster()
static NodeValue createEmptyRaster (Double width, Double height, Double upperleftx, Double upperlefty, Double val) static
References CoverageWrapper.createCoverage(), and HexWKBRastDatatype.URI.
Referenced by SmallerIntersects.exec(), and RasterIntersection.exec().
{
                 Double pixelsize;
                 WritableRaster raster;
                 if(width.intValue()<=0 || height.intValue()<=0) {
                         raster = RasterFactory.createBandedRaster(DataBuffer.TYPE_FLOAT, 2, 2, 1, null);
                 }else {
                         raster = RasterFactory.createBandedRaster(DataBuffer.TYPE_FLOAT, width.intValue(), height.intValue(), 1, null);
                 }
                 for (int y = 0; y < height; y++) {
                         for (int x = 0; x < width; x++) {
                                 raster.setSample(x, y, 0, val);
                         }
                 }
                 //CoordinateReferenceSystem crs = CommonCRS.WGS84.defaultGeographic();
                 CoordinateReferenceSystem crss;
                 Envelope2D envelope=null;
                 try {
                         crss = CRS.forCode("EPSG:4326");
                         envelope = new Envelope2D(crss, 0, 0, 30, 30);
                 } catch (FactoryException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                         envelope = new Envelope2D(CommonCRS.WGS84.defaultGeographic(), 0, 0, 30, 30);
                 }
                 GridCoverageBuilder gcb = new GridCoverageBuilder();
                 gcb.setRenderedImage(raster);
                 gcb.setEnvelope(envelope);
                 GridCoverage2D gc = (GridCoverage2D)gcb.build();
                 return CoverageWrapper.createCoverage(gc, "EPSG:4326", HexWKBRastDatatype.URI.toString()).asNodeValue();
         }
createGeometry() [1/2]
static GeometryWrapper createGeometry (List< Coordinate > coordinates, String geomtype, GeometryWrapper geometry) static
References GeometryWrapper.getGeometryDatatypeURI(), and GeometryWrapper.getSrsURI().
Referenced by LiteralUtils.createGeometry(), EnsureClosed.exec(), ShiftLongitude.exec(), AddZ.exec(), MultiplyZ.exec(), AddT.exec(), PartOfGeometryBefore.exec(), PartOfGeometryAfter.exec(), RemovePoints.exec(), Force2D.exec(), Force3D.exec(), FilterByM.exec(), Force4D.exec(), Force3DM.exec(), SwapOrdinates.exec(), and FlipCoordinates.exec().
{
                         switch(geomtype) {
                         case "Point":
                                 return GeometryWrapperFactory.createPoint(coordinates.get(0), geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "MultiPoint":
                                 return GeometryWrapperFactory.createMultiPoint(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "LineString":
                                 return GeometryWrapperFactory.createLineString(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "Polygon":
                                 return GeometryWrapperFactory.createPolygon(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "MultiLineString":
                                 List<LineString> list=new LinkedList<LineString>();
                                 list.add((LineString)GeometryWrapperFactory.createLineString(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI()).getXYGeometry());
                                 return GeometryWrapperFactory.createMultiLineString(list, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         case "MultiPolygon":
                                 List<Polygon> plist=new LinkedList<Polygon>();
                                 plist.add((Polygon)GeometryWrapperFactory.createPolygon(coordinates, geometry.getSrsURI(), geometry.getGeometryDatatypeURI()).getXYGeometry());
                                 return GeometryWrapperFactory.createMultiPolygon(plist, geometry.getSrsURI(), geometry.getGeometryDatatypeURI());
                         default:
                                 return null;
                         }
                 }
createGeometry() [2/2]
static GeometryWrapper createGeometry (Coordinate [] coordarray, String geomtype, GeometryWrapper geometry) static
References LiteralUtils.createGeometry().
{
                         return createGeometry(Arrays.asList(coordarray), geomtype, geometry);
                 }
cropRaster()
static NodeValue cropRaster (CoverageWrapper wrapper, Double width, Double height, Double x, Double y) throws MismatchedDimensionException, TransformException static
References CoverageWrapper.createCoverage(), Coordinate.getX(), Coordinate.getY(), and LiteralUtils.worldToRaster().
Referenced by RasterIntersection.exec().
{
                  GridCoverage2D raster=wrapper.getXYGeometry();
                  Coordinate coord=worldToRaster(wrapper, x, y);
                  Coordinate coord2=worldToRaster(wrapper, x+width, y+height);
                  Double xx=coord.getX();
                  Double yy=coord.getY();
                  xx=Double.valueOf(xx.intValue())-1;
                  yy=Double.valueOf(yy.intValue())-1;
                  Double widthh=coord2.getX()-x;
                  Double heightt=coord2.getY()-y;
                  ParameterBlock pbSubtracted = new ParameterBlock();
              pbSubtracted.addSource(raster.getRenderedImage());
              pbSubtracted.add(xx.floatValue());
              pbSubtracted.add(yy.floatValue());
              pbSubtracted.add(widthh.floatValue());
              pbSubtracted.add(heightt.floatValue());
              System.out.println(raster.getRenderedImage().getWidth()+" "+raster.getRenderedImage().getHeight());
              System.out.println(xx+" "+yy+" "+widthh+" "+heightt);
              RenderedOp subtractedImage = JAI.create("crop",pbSubtracted);
                         GridCoverageBuilder builder=new GridCoverageBuilder();
                         builder.setGridGeometry(raster.getGridGeometry());
                         builder.setNumBands(raster.getNumSampleDimensions());
                         builder.setExtent(raster.getGridGeometry().getExtent());
                         builder.setRenderedImage(subtractedImage);
                         GridCoverage cov=builder.build();
                         return CoverageWrapper.createCoverage((GridCoverage2D)cov, wrapper.getSrsURI(), wrapper.getRasterDatatypeURI())
                                         .asNodeValue();
         }
getCorrectVectorRepresentation()
static Geometry getCorrectVectorRepresentation (Wrapper wrapper) static
References LiteralUtils.toGeometry().
{
                 if(wrapper instanceof GeometryWrapper) {
                         return ((GeometryWrapper) wrapper).getXYGeometry();
                 }else {
                         return toGeometry(((CoverageWrapper) wrapper).getParsingGeometry().getGridGeometry().getEnvelope());
                 }
         }
rasterOrVector()
static Wrapper rasterOrVector (NodeValue v) static
References CoverageWrapper.extract(), GeometryWrapper.extract(), RasterDataType.get(), and GeometryDatatype.get().
Referenced by EqualType.exec(), IsGrayscale.exec(), IsIndexed.exec(), IsTiled.exec(), IsTranslucent.exec(), RasterEquals.exec(), EqualSRS.exec(), CentroidDistance.exec(), SRIDGetAxis1Name.exec(), SRIDGetAxis1Orientation.exec(), SRIDGetAxis2Name.exec(), SRIDGetAxis2Orientation.exec(), SRIDHasFlippedAxis.exec(), CompactnessRatio.exec(), ValueIntersects.exec(), DWithin3D.exec(), GreaterIntersects.exec(), MedianIntersects.exec(), MinimumDiameter.exec(), SmallerIntersects.exec(), EqualNorm.exec(), AreaSimilarity.exec(), BBOXFPIntersects.exec(), DFullyWithin.exec(), Crosses.exec(), Equals.exec(), EqualTopo.exec(), IntersectionPercentage.exec(), IsCollection.exec(), MinimumBoundingCircleCenter.exec(), MinimumDiameterLine.exec(), MinimumRectangle.exec(), RasterIntersection.exec(), Intersection.exec(), Difference.exec(), BBOXContains.exec(), Distance.exec(), MinimumBoundingRadius.exec(), SymDifference.exec(), BBOXDistance.exec(), MinimumClearance.exec(), BBOXRightOf.exec(), BBOXOverlapsRight.exec(), BBOXOverlapsBelow.exec(), BBOXIntersects.exec(), BBOXIsContainedBy.exec(), BBOXAbove.exec(), BBOXLeftOf.exec(), BBOXOverlapsAbove.exec(), BBOXBelow.exec(), BBOXOverlapsLeft.exec(), BBOXEquals.exec(), Union.exec(), MinimumClearanceLine.exec(), Boundary.exec(), BoundingDiagonal.exec(), ContainsProperly.exec(), IsEmpty.exec(), SRID.exec(), Intersects.exec(), Overlaps.exec(), Touches.exec(), GeometryType.exec(), DistanceSphere.exec(), DWithin.exec(), CoveredBy.exec(), Disjoint.exec(), Covers.exec(), Contains.exec(), Area.exec(), Within.exec(), MinimumBoundingCircle.exec(), and Centroid.exec().
{
                 GeometryDatatype datatype=null;
                 try {
                         datatype=GeometryDatatype.get(v.getDatatypeURI());
                 }catch(Exception e) {
                         datatype=null;
                 }
                         if(datatype==null) {
                                 RasterDataType rdatatype=RasterDataType.get(v.getDatatypeURI());
                                 if(rdatatype==null) {
                                         throw new AssertionError("No valid raster or vector geometry definition given!");
                                 }else {
                                         return CoverageWrapper.extract(v);
                                 }
                         }else{
                                 return  GeometryWrapper.extract(v);
                         }
         }
toGeometry() [1/5]
static Geometry toGeometry (final Envelope2D envelope) static
Referenced by EqualSRS.exec(), OctogonalEnvelope.exec(), MedianIntersects.exec(), MinimumDiameter.exec(), CentroidDistance.exec(), SmallerIntersects.exec(), ValueIntersects.exec(), DWithin3D.exec(), GreaterIntersects.exec(), AreaSimilarity.exec(), Crosses.exec(), BBOXFPIntersects.exec(), EqualNorm.exec(), IntersectionPercentage.exec(), MinimumBoundingCircleCenter.exec(), MinimumDiameterLine.exec(), MinimumRectangle.exec(), RasterIntersection.exec(), Equals.exec(), EqualTopo.exec(), Intersection.exec(), Difference.exec(), BBOXDistance.exec(), MinimumBoundingRadius.exec(), MinimumClearance.exec(), SymDifference.exec(), BBOXContains.exec(), Distance.exec(), BBOXIsContainedBy.exec(), BBOXOverlapsAbove.exec(), BBOXOverlapsLeft.exec(), BBOXEquals.exec(), BBOXOverlapsBelow.exec(), BBOXRightOf.exec(), BBOXIntersects.exec(), BBOXOverlapsRight.exec(), MinimumClearanceLine.exec(), Union.exec(), Boundary.exec(), ContainsProperly.exec(), Intersects.exec(), Envelope.exec(), Overlaps.exec(), Touches.exec(), CoveredBy.exec(), Disjoint.exec(), Covers.exec(), Contains.exec(), Area.exec(), Within.exec(), MinimumBoundingCircle.exec(), Centroid.exec(), and LiteralUtils.getCorrectVectorRepresentation().
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMinY())
                 }), null);
     }
toGeometry() [2/5]
static Geometry toGeometry (final OctagonalEnvelope envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMinY())
                 }), null);
     }
toGeometry() [3/5]
static Geometry toGeometry (final Envelope envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                     new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                     new Coordinate(envelope.getMinX(), envelope.getMinY())
                 }), null);
     }
toGeometry() [4/5]
static Geometry toGeometry (final org.opengis.geometry.Envelope envelope) static
{
         GeometryFactory gf = new GeometryFactory();
         return gf.createPolygon(gf.createLinearRing(
                 new Coordinate[]{
                     new Coordinate(envelope.getMinimum(0), envelope.getMinimum(1)),
                     new Coordinate(envelope.getMaximum(0), envelope.getMinimum(1)),
                     new Coordinate(envelope.getMaximum(0), envelope.getMaximum(1)),
                     new Coordinate(envelope.getMinimum(0), envelope.getMaximum(1)),
                     new Coordinate(envelope.getMinimum(0), envelope.getMinimum(1))
                 }), null);
     }
toGeometry() [5/5]
static Geometry toGeometry (final Rectangle envelope) static
{
                 GeometryFactory gf = new GeometryFactory();
                 return gf.createPolygon(gf.createLinearRing(
                         new Coordinate[]{
                             new Coordinate(envelope.getMinX(), envelope.getMinY()),
                             new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                             new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                             new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                             new Coordinate(envelope.getMinX(), envelope.getMinY())
                         }), null);
             }
worldToRaster()
static Coordinate worldToRaster (CoverageWrapper wrapper, Double latitude, Double longitude) throws MismatchedDimensionException, TransformException static
Referenced by LiteralUtils.cropRaster().
{
          GridCoverage2D raster=wrapper.getXYGeometry();
          GridGeometry2D gg2D = raster.getGridGeometry();
          MathTransform gridToCRS = gg2D.getGridToCRS(PixelInCell.CELL_CENTER);
          MathTransform crsToGrid = gridToCRS.inverse();
          DirectPosition realPos=new DirectPosition2D(latitude, longitude);
          DirectPosition gridPos = new DirectPosition2D();
          DirectPosition res=crsToGrid.transform(realPos, gridPos);
          Coordinate coord=new Coordinate(res.getCoordinate()[0],res.getCoordinate()[1]);
          return coord;
         }