jena-geo: CoverageWrapper Class Reference
CoverageWrapper Class Reference
Public Member Functions
CoverageWrapper (GridCoverage geometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo)
CoverageWrapper (GridCoverage geometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo, String geometryLiteral)
CoverageWrapper (GridCoverage geometry, String geometryDatatypeURI)
Default to WGS84 geometry and XY coordinate dimensions.
CoverageWrapper (GridCoverage geometry, String srsURI, String geometryDatatypeURI)
Default to XY coordinate dimensions.
CoverageWrapper (String srsURI, String geometryDatatypeURI)
Empty geometry with specified parameters.
CoverageWrapper (CoverageWrapper geometryWrapper)
Copy GeometryWrapper.
CoverageWrapper checkTransformSRS (CoverageWrapper targetGeometryWrapper) throws FactoryException, MismatchedDimensionException, TransformException
Transforms, if necessary, the provided target GeometryWrapper according to this GeometryWrapper SRS_URI.
CoverageWrapper transform (String srsURI) throws MismatchedDimensionException, TransformException, FactoryException
Transform the GeometryWrapper into another spatial reference system.
CoverageWrapper transform (SRSInfo srsInfo) throws MismatchedDimensionException, TransformException, FactoryException
Transform the GeometryWrapper into another spatial reference system.
CoverageWrapper convertSRS (String srsURI) throws FactoryException, MismatchedDimensionException, TransformException
Returns this geometry wrapper converted to the SRS_URI URI.
CoordinateReferenceSystem getCRS ()
GridCoverage getParsingGeometry ()
GridCoverage getGridGeometry ()
GridCoverage getXYGeometry ()
String getSrsURI ()
String getSRID ()
SRSInfo getSrsInfo ()
Boolean isSRSRecognised ()
String getRasterDatatypeURI ()
RasterDataType getRasterDatatype ()
NodeValue asNodeValue () throws DatatypeFormatException
Node asNode () throws DatatypeFormatException
Literal asLiteral () throws DatatypeFormatException
Literal asLiteral (String outputGeometryDatatypeURI) throws DatatypeFormatException
Literal asLiteral (RasterDataType datatype)
int getCoordinateDimension ()
int getSpatialDimension ()
int getTopologicalDimension ()
CoordinateSequenceDimensions getCoordinateSequenceDimensions ()
UnitsOfMeasure getUnitsOfMeasure ()
DimensionInfo getDimensionInfo ()
String getLexicalForm ()
int hashCode ()
boolean equals (Object obj)
String toString ()
Static Public Member Functions
static final CoverageWrapper extract (NodeValue geometryLiteral, GeometryIndex targetIndex)
Extract Geometry Wrapper from Geometry Literal.
static final CoverageWrapper extract (Node geometryLiteral, GeometryIndex targetIndex)
Extract Geometry Wrapper from Geometry Literal.
static final CoverageWrapper extract (NodeValue geometryLiteral)
Extract Geometry Wrapper from Geometry Literal.
static final CoverageWrapper extract (Node geometryLiteral)
Extract Geometry Wrapper from Geometry Literal.
static final CoverageWrapper extract (Literal geometryLiteral, GeometryIndex targetIndex)
Extract Geometry Wrapper from Geometry Literal.
static final CoverageWrapper extract (Literal geometryLiteral)
Extract Geometry Wrapper from Geometry Literal.
static CoverageWrapper extract (String lexicalForm, String datatypeURI)
Extract Geometry Wrapper from Geometry Literal.
static CoverageWrapper extract (String lexicalForm, String datatypeURI, GeometryIndex targetIndex)
Extract Geometry Wrapper from Geometry Literal.
static final GeometryWrapper getEmptyWKT ()
static final GeometryWrapper getEmptyGML ()
static final CoverageWrapper createGeometry (GridCoverage geometry, String srsURI, String geometryDatatypeURI)
Create Geometry GeometryWrapper.
Protected Member Functions
CoverageWrapper transform (String srsURI, Boolean storeSRSTransform) throws MismatchedDimensionException, TransformException, FactoryException
Transform the GeometryWrapper into another spatial reference system.
Private Member Functions
CoverageWrapper (GridCoverage parsingGeometry, GridCoverage xyGeometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo)
CoverageWrapper (GridCoverage parsingGeometry, GridCoverage xyGeometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo, String lexicalForm)
void checkPreparedGeometry ()
Checks whether the prepared geometry has been initialised.
Private Attributes
final DimensionInfo dimensionInfo
final SRSInfo srsInfo
final GridCoverage xyGeometry
final GridCoverage parsingGeometry
PreparedGeometry preparedGeometry
Envelope envelope
GridCoverage translateXYGeometry
final String geometryDatatypeURI
RasterDataType geometryDatatype
String lexicalForm
String utmURI = null
Double latitude = null
Static Private Attributes
transient static final GeometryFactory GEOMETRY_FACTORY = CustomGeometryFactory.theInstance()
Constructor & Destructor Documentation
CoverageWrapper() [1/8]
CoverageWrapper (GridCoverage geometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo)
Parameters
geometry In X/Y or Y/X coordinate order of the SRS URI.
srsURI
geometryDatatypeURI
dimensionInfo
References CoverageWrapper.dimensionInfo, and CoverageWrapper.geometryDatatypeURI.
Referenced by CoverageWrapper.createGeometry(), and CoverageWrapper.equals().
{
         this(geometry, srsURI, geometryDatatypeURI, dimensionInfo, null);
     }
CoverageWrapper() [2/8]
CoverageWrapper (GridCoverage geometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo, String geometryLiteral)
Parameters
geometry In X/Y or Y/X coordinate order of the SRS URI.
srsURI
geometryDatatypeURI
dimensionInfo
geometryLiteral
References CoverageWrapper.dimensionInfo, and CoverageWrapper.geometryDatatypeURI.
{
         this(geometry, geometry, srsURI.isEmpty() ? SRS_URI.DEFAULT_WKT_CRS84 : srsURI, geometryDatatypeURI, dimensionInfo, geometryLiteral);
     }
CoverageWrapper() [3/8]
CoverageWrapper (GridCoverage parsingGeometry, GridCoverage xyGeometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo) private
References CoverageWrapper.dimensionInfo, CoverageWrapper.geometryDatatypeURI, CoverageWrapper.parsingGeometry, and CoverageWrapper.xyGeometry.
{
         this(parsingGeometry, xyGeometry, srsURI, geometryDatatypeURI, dimensionInfo, null);
     }
CoverageWrapper() [4/8]
CoverageWrapper (GridCoverage parsingGeometry, GridCoverage xyGeometry, String srsURI, String geometryDatatypeURI, DimensionInfo dimensionInfo, String lexicalForm) private
References CoverageWrapper.dimensionInfo, CoverageWrapper.geometryDatatypeURI, CoverageWrapper.lexicalForm, CoverageWrapper.parsingGeometry, and CoverageWrapper.xyGeometry.
{
         this.parsingGeometry = parsingGeometry;
         this.xyGeometry = xyGeometry;
         this.preparedGeometry = null; //Initialised when required by spatial relations checkPreparedGeometry.
         this.envelope = null; //Initialised when required by getEnvelope().
         this.translateXYGeometry = null; //Initialised when required by translateGeometry().
         this.geometryDatatypeURI = geometryDatatypeURI;
         this.geometryDatatype = null; //Inilialised when required by getGeometryDatatype().
         if (srsURI.isEmpty()) {
             srsURI = SRS_URI.DEFAULT_WKT_CRS84;
         }
         this.srsInfo = SRSRegistry.getSRSInfo(srsURI);
         this.dimensionInfo = dimensionInfo;
         this.lexicalForm = lexicalForm; //If not Initialised then required by asLiteral() etc.
     }
CoverageWrapper() [5/8]
CoverageWrapper (GridCoverage geometry, String geometryDatatypeURI)
Default to WGS84 geometry and XY coordinate dimensions.
Parameters
geometry In X/Y or Y/X coordinate order of WGS84.
geometryDatatypeURI
References CoverageWrapper.geometryDatatypeURI.
{
         this(geometry, "", geometryDatatypeURI, DimensionInfo.XY_POINT);
     }
CoverageWrapper() [6/8]
CoverageWrapper (GridCoverage geometry, String srsURI, String geometryDatatypeURI)
Default to XY coordinate dimensions.
Parameters
geometry In X/Y or Y/X coordinate order of the SRS URI.
srsURI
geometryDatatypeURI
References CoverageWrapper.geometryDatatypeURI.
{
         this(geometry, srsURI, geometryDatatypeURI, DimensionInfo.XY_POINT);
     }
CoverageWrapper() [7/8]
CoverageWrapper (String srsURI, String geometryDatatypeURI)
Empty geometry with specified parameters.
Parameters
srsURI
geometryDatatypeURI
{
         this(new CustomCoordinateSequence(DimensionInfo.XY_POINT.getDimensions()), geometryDatatypeURI, srsURI);
     }
CoverageWrapper() [8/8]
CoverageWrapper (CoverageWrapper geometryWrapper)
Copy GeometryWrapper.
Parameters
geometryWrapper
References CoverageWrapper.dimensionInfo, CoverageWrapper.envelope, CoverageWrapper.geometryDatatype, CoverageWrapper.geometryDatatypeURI, CoverageWrapper.latitude, CoverageWrapper.lexicalForm, CoverageWrapper.parsingGeometry, CoverageWrapper.preparedGeometry, CoverageWrapper.srsInfo, CoverageWrapper.translateXYGeometry, CoverageWrapper.utmURI, and CoverageWrapper.xyGeometry.
{
         this.xyGeometry = geometryWrapper.xyGeometry;
         this.parsingGeometry = geometryWrapper.parsingGeometry;
         this.preparedGeometry = geometryWrapper.preparedGeometry;
         this.envelope = geometryWrapper.envelope;
         this.translateXYGeometry = geometryWrapper.translateXYGeometry;
         this.utmURI = geometryWrapper.utmURI;
         this.latitude = geometryWrapper.latitude;
         this.geometryDatatypeURI = geometryWrapper.geometryDatatypeURI;
         this.geometryDatatype = geometryWrapper.geometryDatatype;
         this.srsInfo = geometryWrapper.srsInfo;
         this.dimensionInfo = geometryWrapper.dimensionInfo;
         this.lexicalForm = geometryWrapper.lexicalForm;
     }
Member Function Documentation
asLiteral() [1/3]
Literal asLiteral () throws DatatypeFormatException
Returns
GeometryWrapper as Literal
References CoverageWrapper.getRasterDatatype().
Referenced by CoverageWrapper.asLiteral(), CoverageWrapper.asNodeValue(), and CoverageWrapper.getLexicalForm().
{
         RasterDataType datatype = getRasterDatatype(); //Datatype is only retrieved when required.
         if (lexicalForm != null) {
             return ResourceFactory.createTypedLiteral(lexicalForm, datatype);
         }
         Literal literal = asLiteral(datatype);
         lexicalForm = literal.getLexicalForm();
         return literal;
     }
asLiteral() [2/3]
Literal asLiteral (String outputGeometryDatatypeURI) throws DatatypeFormatException
Parameters
outputGeometryDatatypeURI
Returns
GeometryWrapper as Literal in datatype form.
References CoverageWrapper.asLiteral(), and RasterDataType.get().
{
         RasterDataType datatype = RasterDataType.get(outputGeometryDatatypeURI);
         return asLiteral(datatype);
     }
asLiteral() [3/3]
Literal asLiteral (RasterDataType datatype)
Parameters
datatype
Returns
GeometryWrapper as Literal
{
         String tempLexicalForm = datatype.unparse(this);
         return ResourceFactory.createTypedLiteral(tempLexicalForm, datatype);
     }
asNode()
Node asNode () throws DatatypeFormatException
Returns
GeometryWrapper as Node
References CoverageWrapper.asNodeValue().
Referenced by CoverageWrapper.extract().
{
         return asNodeValue().asNode();
     }
asNodeValue()
NodeValue asNodeValue () throws DatatypeFormatException
Returns
GeometryWrapper as NodeValue
References CoverageWrapper.asLiteral().
Referenced by CoverageWrapper.asNode(), RastFromCoverageJSON.exec(), SetBandNoDataValue.exec(), RastFromWKB.exec(), and RastFromHexWKB.exec().
{
         Literal literal = asLiteral();
         return NodeValue.makeNode(literal.getLexicalForm(), literal.getDatatype());
     }
checkPreparedGeometry()
void checkPreparedGeometry () private
Checks whether the prepared geometry has been initialised.
Done lazily as expensive.
{
         if (preparedGeometry == null) {
             this.preparedGeometry = PreparedGeometryFactory.prepare(xyGeometry);
         }
     }
checkTransformSRS()
CoverageWrapper checkTransformSRS (CoverageWrapper targetGeometryWrapper) throws FactoryException, MismatchedDimensionException, TransformException
Transforms, if necessary, the provided target GeometryWrapper according to this GeometryWrapper SRS_URI.
Parameters
targetGeometryWrapper
Returns
GeometryWrapper after transformation.
Exceptions
FactoryException
MismatchedDimensionException
TransformException
References CoverageWrapper.getSrsURI(), and CoverageWrapper.transform().
{
         CoverageWrapper transformedGeometryWrapper;
         String srsURI = srsInfo.getSrsURI();
         if (srsURI.equals(targetGeometryWrapper.srsInfo.getSrsURI())) {
             transformedGeometryWrapper = targetGeometryWrapper;
         } else {
             transformedGeometryWrapper = targetGeometryWrapper.transform(srsURI);
         }
         return transformedGeometryWrapper;
     }
convertSRS()
CoverageWrapper convertSRS (String srsURI) throws FactoryException, MismatchedDimensionException, TransformException
Returns this geometry wrapper converted to the SRS_URI URI.
Parameters
srsURI
Returns
GeometryWrapper after conversion.
Exceptions
FactoryException
MismatchedDimensionException
TransformException
References CoverageWrapper.transform().
{
         return transform(srsURI);
     }
createGeometry()
static final CoverageWrapper createGeometry (GridCoverage geometry, String srsURI, String geometryDatatypeURI) static
Create Geometry GeometryWrapper.
Parameters
geometry In X/Y order.
srsURI
geometryDatatypeURI
Returns
GeometryWrapper with SRS URI and GeometryDatatype URI.
References CoverageWrapper.CoverageWrapper(), and CoverageWrapper.xyGeometry.
{
         GridCoverage xyGeometry = geometry;
         GridCoverage parsingGeometry = GeometryReverse.check(xyGeometry, srsURI);
         DimensionInfo dimsInfo = DimensionInfo.find(geometry.getCoordinate(), xyGeometry);
         return new CoverageWrapper(parsingGeometry, xyGeometry, srsURI, geometryDatatypeURI, dimsInfo);
     }
equals()
boolean equals (Object obj)
References CoverageWrapper.CoverageWrapper(), CoverageWrapper.dimensionInfo, CoverageWrapper.equals(), CoverageWrapper.geometryDatatypeURI, CoverageWrapper.srsInfo, and CoverageWrapper.xyGeometry.
Referenced by CoverageWrapper.equals().
{
         if (this == obj) {
             return true;
         }
         if (obj == null) {
             return false;
         }
         if (getClass() != obj.getClass()) {
             return false;
         }
         final CoverageWrapper other = (CoverageWrapper) obj;
         if (!Objects.equals(this.geometryDatatypeURI, other.geometryDatatypeURI)) {
             return false;
         }
         if (!Objects.equals(this.dimensionInfo, other.dimensionInfo)) {
             return false;
         }
         if (!Objects.equals(this.srsInfo, other.srsInfo)) {
             return false;
         }
         return Objects.equals(this.xyGeometry, other.xyGeometry);
     }
extract() [1/8]
static final CoverageWrapper extract (NodeValue geometryLiteral, GeometryIndex targetIndex) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
geometryLiteral
targetIndex
Returns
Geometry Wrapper of the Geometry Literal.
References CoverageWrapper.asNode().
Referenced by MinTileX.exec(), NumXTiles.exec(), NumYTiles.exec(), PixelWidth.exec(), MinTileY.exec(), SetRotation.exec(), TileGridXOffset.exec(), TileGridYOffset.exec(), TileHeight.exec(), TileWidth.exec(), PixelSize.exec(), AddBand.exec(), SetSkew.exec(), NotSameAlignmentReason.exec(), TranslateY.exec(), PixelAsCentroid.exec(), SetBandNoDataValue.exec(), AsBinary.exec(), TranslateX.exec(), MemSize.exec(), AsHexRastWKB.exec(), DumpAsPolygons.exec(), AsTIFF.exec(), ScaleX.exec(), ScaleY.exec(), SkewY.exec(), Resize.exec(), Subtract.exec(), Add.exec(), And.exec(), Or.exec(), Xor.exec(), Mult.exec(), Div.exec(), NumBands.exec(), XorConst.exec(), OrConst.exec(), DivConst.exec(), Band.exec(), BandMetaData.exec(), AndConst.exec(), Log.exec(), BandNoDataValue.exec(), AddConst.exec(), BandPixelType.exec(), Count.exec(), SubtractConst.exec(), MultConst.exec(), Summary.exec(), NearestValue.exec(), Height.exec(), Width.exec(), MinConvexHull.exec(), SetScale.exec(), Envelope.exec(), Value.exec(), PixelAsPolygon.exec(), HasNoBand.exec(), SameAlignment.exec(), SkewX.exec(), PixelHeight.exec(), UpperLeftY.exec(), UpperLeftX.exec(), SummaryStats.exec(), PixelAsPoint.exec(), WorldToRasterCoordX.exec(), WorldToRasterCoordY.exec(), RasterToWorldCoordX.exec(), RasterToWorldCoordY.exec(), RasterToWorldCoord.exec(), WorldToRasterCoord.exec(), CoverageWrapper.extract(), and LiteralUtils.rasterOrVector().
{
         Node node = geometryLiteral.asNode();
         return extract(node, targetIndex);
     }
extract() [2/8]
static final CoverageWrapper extract (Node geometryLiteral, GeometryIndex targetIndex) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
geometryLiteral
targetIndex
Returns
Geometry Wrapper of the Geometry Literal.
References CoverageWrapper.extract().
{
         if (!geometryLiteral.isLiteral()) {
             throw new DatatypeFormatException("Not a Literal: " + geometryLiteral);
         }
         String datatypeURI = geometryLiteral.getLiteralDatatypeURI();
         String lexicalForm = geometryLiteral.getLiteralLexicalForm();
         return extract(lexicalForm, datatypeURI, targetIndex);
     }
extract() [3/8]
static final CoverageWrapper extract (NodeValue geometryLiteral) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
geometryLiteral
Returns
Geometry Wrapper of the Geometry Literal.
References CoverageWrapper.extract(), and GeometryLiteralIndex.GeometryIndex.PRIMARY.
{
         return extract(geometryLiteral, GeometryIndex.PRIMARY);
     }
extract() [4/8]
static final CoverageWrapper extract (Node geometryLiteral) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
geometryLiteral
Returns
Geometry Wrapper of the Geometry Literal.
References CoverageWrapper.extract(), and GeometryLiteralIndex.GeometryIndex.PRIMARY.
{
         return extract(geometryLiteral, GeometryIndex.PRIMARY);
     }
extract() [5/8]
static final CoverageWrapper extract (Literal geometryLiteral, GeometryIndex targetIndex) static
Extract Geometry Wrapper from Geometry Literal.
Returns null if invalid literal provided.
Parameters
geometryLiteral
targetIndex
Returns
Geometry Wrapper of the Geometry Literal.
References CoverageWrapper.extract().
{
         return extract(geometryLiteral.getLexicalForm(), geometryLiteral.getDatatypeURI(), targetIndex);
     }
extract() [6/8]
static final CoverageWrapper extract (Literal geometryLiteral) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
geometryLiteral
Returns
Geometry Wrapper of the Geometry Literal.
References CoverageWrapper.extract(), and GeometryLiteralIndex.GeometryIndex.PRIMARY.
{
         return extract(geometryLiteral, GeometryIndex.PRIMARY);
     }
extract() [7/8]
static CoverageWrapper extract (String lexicalForm, String datatypeURI) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
lexicalForm
datatypeURI
Returns
Geometry Wrapper of the Geometry Literal.
References CoverageWrapper.extract(), and GeometryLiteralIndex.GeometryIndex.PRIMARY.
{
         return extract(lexicalForm, datatypeURI, GeometryIndex.PRIMARY);
     }
extract() [8/8]
static CoverageWrapper extract (String lexicalForm, String datatypeURI, GeometryIndex targetIndex) static
Extract Geometry Wrapper from Geometry Literal.
Parameters
lexicalForm
datatypeURI
targetIndex
Returns
Geometry Wrapper of the Geometry Literal.
References RasterDataType.get(), and RasterDataType.parse().
{
         if (lexicalForm == null || datatypeURI == null) {
             throw new DatatypeFormatException("GeometryWrapper extraction: arguments cannot be null - " + lexicalForm + ", " + datatypeURI);
         }
         RasterDataType datatype = RasterDataType.get(datatypeURI);
         CoverageWrapper geometry = datatype.parse(lexicalForm, targetIndex);
         return geometry;
     }
getCoordinateDimension()
int getCoordinateDimension ()
Returns
Coordinate dimension, i.e. 2 (x,y), 3 (x,y,z or x,y,m) or 4 (x,y,z,m)
{
         return dimensionInfo.getCoordinate();
     }
getCoordinateSequenceDimensions()
CoordinateSequenceDimensions getCoordinateSequenceDimensions ()
Returns
Enum of coordinate dimensions.
{
         return dimensionInfo.getDimensions();
     }
getCRS()
CoordinateReferenceSystem getCRS ()
Returns
Coordinate/Spatial reference system of the GeometryWrapper.
{
         return srsInfo.getCrs();
     }
getDimensionInfo()
DimensionInfo getDimensionInfo ()
Returns
GeometryWrapper's coordinate, spatial and topological dimensions.
References CoverageWrapper.dimensionInfo.
{
         return dimensionInfo;
     }
getEmptyGML()
static final GeometryWrapper getEmptyGML () static
Returns
Empty GeometryWrapper in GML datatype.
References GMLDatatype.INSTANCE, and GMLDatatype.read().
{
         return GMLDatatype.INSTANCE.read("");
     }
getEmptyWKT()
static final GeometryWrapper getEmptyWKT () static
Returns
Empty GeometryWrapper in WKT datatype.
{
         return WKTDatatype.INSTANCE.read("");
     }
getGridGeometry()
GridCoverage getGridGeometry ()
Returns
Geometry with coordinates as originally provided.
References CoverageWrapper.parsingGeometry.
Referenced by NotSameAlignmentReason.exec(), SameAlignment.exec(), WKBRastDatatype.unparse(), CovJSONDatatype.unparse(), and HexWKBRastDatatype.unparse().
{
        return parsingGeometry;
    }
getLexicalForm()
String getLexicalForm ()
Returns
String literal of Geometry Wrapper.
References CoverageWrapper.asLiteral(), and CoverageWrapper.lexicalForm.
{
         if (lexicalForm != null) {
             return lexicalForm;
         } else {
             Literal literal = asLiteral();
             return literal.getLexicalForm();
         }
     }
getParsingGeometry()
GridCoverage getParsingGeometry ()
Returns
Geometry with coordinates as originally provided.
References CoverageWrapper.parsingGeometry.
Referenced by SetBandNoDataValue.exec(), Envelope.exec(), and HasNoBand.exec().
{
         return parsingGeometry;
     }
getRasterDatatype()
RasterDataType getRasterDatatype ()
Returns
GeometryDatatype of the literal.
References CoverageWrapper.geometryDatatype, and RasterDataType.get().
Referenced by CoverageWrapper.asLiteral().
{
         if (geometryDatatype == null) {
             geometryDatatype = RasterDataType.get(geometryDatatypeURI);
         }
         return geometryDatatype;
     }
getRasterDatatypeURI()
String getRasterDatatypeURI ()
Returns
Datatype URI of the literal.
References CoverageWrapper.geometryDatatypeURI.
Referenced by Add.exec(), Div.exec(), Mult.exec(), Xor.exec(), Or.exec(), And.exec(), Subtract.exec(), SubtractConst.exec(), AddConst.exec(), Log.exec(), XorConst.exec(), AndConst.exec(), MultConst.exec(), OrConst.exec(), DivConst.exec(), Envelope.exec(), RasterToWorldCoord.exec(), and WorldToRasterCoord.exec().
{
         return geometryDatatypeURI;
     }
getSpatialDimension()
int getSpatialDimension ()
Returns
Spatial dimension, i.e. 2 or 3
{
         return dimensionInfo.getSpatial();
     }
getSRID()
String getSRID ()
Returns
getSRID used in GeoSPARQL Standard page 22 to refer to srsURI. i.e. getSrsURI and getSRID are the same.
{
         return srsInfo.getSrsURI();
     }
getSrsInfo()
SRSInfo getSrsInfo ()
Returns
SRS information that the Geometry Wrapper is using.
References CoverageWrapper.srsInfo.
{
         return srsInfo;
     }
getSrsURI()
String getSrsURI ()
Returns
Coordinate/Spatial reference system URI.
Referenced by CoverageWrapper.checkTransformSRS(), Add.exec(), Xor.exec(), Mult.exec(), And.exec(), Div.exec(), Or.exec(), Subtract.exec(), XorConst.exec(), MultConst.exec(), AddConst.exec(), SubtractConst.exec(), AndConst.exec(), Log.exec(), DivConst.exec(), OrConst.exec(), Envelope.exec(), RasterToWorldCoord.exec(), and WorldToRasterCoord.exec().
{
         return srsInfo.getSrsURI();
     }
getTopologicalDimension()
int getTopologicalDimension ()
Returns
Topological dimension, i.e. 0, 1 or 2
{
         return dimensionInfo.getTopological();
     }
getUnitsOfMeasure()
UnitsOfMeasure getUnitsOfMeasure ()
Returns
Units of Measure for the GeometryWrapper SRS.
{
         return srsInfo.getUnitsOfMeasure();
     }
getXYGeometry()
GridCoverage getXYGeometry ()
Returns
Geometry with coordinates as originally provided.
References CoverageWrapper.parsingGeometry.
Referenced by MinTileX.exec(), MinTileY.exec(), PixelWidth.exec(), SetRotation.exec(), NumXTiles.exec(), TileGridXOffset.exec(), TileGridYOffset.exec(), TileHeight.exec(), TileWidth.exec(), NumYTiles.exec(), PixelSize.exec(), AddBand.exec(), SetSkew.exec(), AsBinary.exec(), TranslateX.exec(), TranslateY.exec(), PixelAsCentroid.exec(), MemSize.exec(), AsHexRastWKB.exec(), AsTIFF.exec(), DumpAsPolygons.exec(), ScaleX.exec(), ScaleY.exec(), SkewY.exec(), Resize.exec(), And.exec(), Xor.exec(), Add.exec(), Mult.exec(), Div.exec(), Subtract.exec(), NumBands.exec(), Or.exec(), XorConst.exec(), Log.exec(), Band.exec(), AndConst.exec(), BandMetaData.exec(), BandNoDataValue.exec(), BandPixelType.exec(), AddConst.exec(), MultConst.exec(), SubtractConst.exec(), Count.exec(), OrConst.exec(), DivConst.exec(), Summary.exec(), Height.exec(), NearestValue.exec(), Width.exec(), SetScale.exec(), MinConvexHull.exec(), PixelAsPolygon.exec(), Value.exec(), SkewX.exec(), UpperLeftY.exec(), PixelHeight.exec(), UpperLeftX.exec(), SummaryStats.exec(), PixelAsPoint.exec(), WorldToRasterCoordX.exec(), WorldToRasterCoordY.exec(), RasterToWorldCoordX.exec(), RasterToWorldCoordY.exec(), RasterToWorldCoord.exec(), and WorldToRasterCoord.exec().
{
       return parsingGeometry;
   }
hashCode()
int hashCode ()
{
         int hash = 3;
         hash = 23 * hash + Objects.hashCode(this.dimensionInfo);
         hash = 23 * hash + Objects.hashCode(this.srsInfo);
         hash = 23 * hash + Objects.hashCode(this.xyGeometry);
         hash = 23 * hash + Objects.hashCode(this.geometryDatatypeURI);
         return hash;
     }
isSRSRecognised()
Boolean isSRSRecognised ()
Returns
Whether the SRS URI has been recognised. Operations may fail or not perform correctly when false.
{
         return srsInfo.isSRSRecognised();
     }
toString()
String toString ()
{
         return "GeometryWrapper{" + "dimensionInfo=" + dimensionInfo + ", geometryDatatypeURI=" + geometryDatatypeURI + ", lexicalForm=" + lexicalForm + ", utmURI=" + utmURI + ", latitude=" + latitude + ", xyGeometry=" + xyGeometry + ", parsingGeometry=" + parsingGeometry + ", preparedGeometry=" + preparedGeometry + ", srsInfo=" + srsInfo + '}';
     }
transform() [1/3]
CoverageWrapper transform (String srsURI) throws MismatchedDimensionException, TransformException, FactoryException
Transform the GeometryWrapper into another spatial reference system.
Parameters
srsURI
Returns
New GeometryWrapper after transformation, or this GeometryWrapper if no transformation.
Exceptions
MismatchedDimensionException
TransformException
FactoryException
Referenced by CoverageWrapper.checkTransformSRS(), CoverageWrapper.convertSRS(), and CoverageWrapper.transform().
{
         return transform(srsURI, true);
     }
transform() [2/3]
CoverageWrapper transform (SRSInfo srsInfo) throws MismatchedDimensionException, TransformException, FactoryException
Transform the GeometryWrapper into another spatial reference system.
Parameters
srsInfo
Returns
New GeometryWrapper after transformation, or this GeometryWrapper if no transformation.
Exceptions
MismatchedDimensionException
TransformException
FactoryException
References CoverageWrapper.transform().
{
         return transform(srsInfo.getSrsURI(), true);
     }
transform() [3/3]
CoverageWrapper transform (String srsURI, Boolean storeSRSTransform) throws MismatchedDimensionException, TransformException, FactoryException protected
Transform the GeometryWrapper into another spatial reference system.
Option to store the resulting GeometryWrapper in the index.
Parameters
srsURI
storeSRSTransform
Returns
GeometryWrapper after transformation.
Exceptions
MismatchedDimensionException
TransformException
FactoryException
References CoverageWrapper.transform().
{
         if (srsInfo.getSrsURI().equals(srsURI)) {
             return this;
         }
         return GeometryTransformIndex.transform(this, srsURI, storeSRSTransform);
     }
Member Data Documentation
dimensionInfo
final DimensionInfo dimensionInfo private
Referenced by CoverageWrapper.CoverageWrapper(), CoverageWrapper.equals(), and CoverageWrapper.getDimensionInfo().
envelope
Envelope envelope private
Referenced by CoverageWrapper.CoverageWrapper().
GEOMETRY_FACTORY
transient static final GeometryFactory GEOMETRY_FACTORY = CustomGeometryFactory.theInstance() static private
geometryDatatype
RasterDataType geometryDatatype private
Referenced by CoverageWrapper.CoverageWrapper(), and CoverageWrapper.getRasterDatatype().
geometryDatatypeURI
final String geometryDatatypeURI private
Referenced by CoverageWrapper.CoverageWrapper(), CoverageWrapper.equals(), and CoverageWrapper.getRasterDatatypeURI().
latitude
Double latitude = null private
Referenced by CoverageWrapper.CoverageWrapper().
lexicalForm
String lexicalForm private
Referenced by CoverageWrapper.CoverageWrapper(), and CoverageWrapper.getLexicalForm().
parsingGeometry
final GridCoverage parsingGeometry private
Referenced by CoverageWrapper.CoverageWrapper(), CoverageWrapper.getGridGeometry(), CoverageWrapper.getParsingGeometry(), and CoverageWrapper.getXYGeometry().
preparedGeometry
PreparedGeometry preparedGeometry private
Referenced by CoverageWrapper.CoverageWrapper().
srsInfo
final SRSInfo srsInfo private
Referenced by CoverageWrapper.CoverageWrapper(), CoverageWrapper.equals(), and CoverageWrapper.getSrsInfo().
translateXYGeometry
GridCoverage translateXYGeometry private
Referenced by CoverageWrapper.CoverageWrapper().
utmURI
String utmURI = null private
Referenced by CoverageWrapper.CoverageWrapper().
xyGeometry
final GridCoverage xyGeometry private
Referenced by CoverageWrapper.CoverageWrapper(), CoverageWrapper.createGeometry(), and CoverageWrapper.equals().