jena-geo: GeoHashDatatype Class Reference
GeoHashDatatype Class Reference
WKTDatatype class allows the URI "geo:wktLiteral" to be used as a datatype and it will parse that datatype to a JTS Geometry.
Public Member Functions
String unparse (Object geometry)
This method Un-parses the JTS Geometry to the WKT literal.
GeometryWrapper read (String geometryLiteral)
String toString ()
final GeometryWrapper parse (String lexicalForm) throws DatatypeFormatException
This method Parses the Geometry Literal to the JTS Geometry.
final GeometryWrapper parse (String lexicalForm, GeometryIndex targetIndex) throws DatatypeFormatException
Static Public Member Functions
static final void registerDatatypes ()
static final GeometryDatatype get (RDFDatatype rdfDatatype)
static final GeometryDatatype get (String datatypeURI)
static final boolean checkURI (String datatypeURI)
static final boolean check (RDFDatatype rdfDatatype)
Static Public Attributes
static final String URI = PostGISGeo.GeoHash
The default WKT type URI.
static final GeoHashDatatype INSTANCE = new GeoHashDatatype()
A static instance of WKTDatatype.
Private Member Functions
GeoHashDatatype ()
private constructor - single global instance.
Detailed Description
WKTDatatype class allows the URI "geo:wktLiteral" to be used as a datatype and it will parse that datatype to a JTS Geometry.
Req 10 All RDFS Literals of type geo:wktLiteral shall consist of an optional URI identifying the coordinate reference system followed by Simple Features Well Known Text (WKT) describing a geometric value. Valid geo:wktLiterals are formed by concatenating a valid, absolute URI as defined in [RFC 2396], one or more spaces (Unicode U+0020 character) as a separator, and a WKT string as defined in Simple Features [ISO 19125-1].
Req 11 The URI
<http://www.opengis.net/def/crs/OGC/1.3/CRS84>
shall be assumed as the spatial reference system for geo:wktLiterals that do not * specify an explicit spatial reference system URI.
Constructor & Destructor Documentation
GeoHashDatatype()
GeoHashDatatype () private
private constructor - single global instance.
{
         super(URI);
     }
Member Function Documentation
check()
static final boolean check (RDFDatatype rdfDatatype) static inherited
References GeometryDatatype.checkURI().
{
         //Ensure that the registered datatypes from the type mapper are used.
         return checkURI(rdfDatatype.getURI());
     }
checkURI()
static final boolean checkURI (String datatypeURI) static inherited
References GeometryDatatype.GeometryDatatype(), and GeometryDatatype.registerDatatypes().
Referenced by GeometryDatatype.check(), and GeometryDatatype.get().
{
         registerDatatypes();
         RDFDatatype rdfDatatype = TYPE_MAPPER.getTypeByName(datatypeURI);
         if (rdfDatatype != null) {
             return rdfDatatype instanceof GeometryDatatype;
         } else {
             throw new DatatypeFormatException("Datatype not found: " + datatypeURI + " Ensure that GeoSPARQL is enabled and Datatype has been registered.");
         }
     }
get() [1/2]
static final GeometryDatatype get (RDFDatatype rdfDatatype) static inherited
References GeometryDatatype.registerDatatypes().
Referenced by GeometryWrapper.asLiteral(), GeometryWrapper.extract(), GeometryDatatype.get(), GeometryWrapper.getGeometryDatatype(), and LiteralUtils.rasterOrVector().
{
         registerDatatypes();
         System.out.println(rdfDatatype);
         Iterator it=TYPE_MAPPER.listTypes();
         while(it.hasNext()) {
                 System.out.println(it.next());
         }
         if (rdfDatatype instanceof GeometryDatatype) {
             return (GeometryDatatype) rdfDatatype;
         } else {
             throw new DatatypeFormatException("Unrecognised Geometry Datatype: " + rdfDatatype.getURI() + " Ensure that Datatype is extending GeometryDatatype.");
         }
     }
get() [2/2]
static final GeometryDatatype get (String datatypeURI) static inherited
References GeometryDatatype.checkURI(), and GeometryDatatype.get().
{
         checkURI(datatypeURI);
         RDFDatatype rdfDatatype = TYPE_MAPPER.getTypeByName(datatypeURI);
         return GeometryDatatype.get(rdfDatatype);
     }
parse() [1/2]
final GeometryWrapper parse (String lexicalForm) throws DatatypeFormatException inherited
This method Parses the Geometry Literal to the JTS Geometry.
Parameters
lexicalForm - the Geometry Literal to be parsed
Returns
geometry - if the Geometry Literal is valid.
empty geometry - if the Geometry Literal is empty.
null - if the Geometry Literal is invalid.
References GeometryLiteralIndex.GeometryIndex.PRIMARY.
Referenced by GeometryWrapper.extract(), and GeomFromGeoJSONTest.testGeomFromGeoJSON().
{
         return parse(lexicalForm, GeometryIndex.PRIMARY);
     }
parse() [2/2]
final GeometryWrapper parse (String lexicalForm, GeometryIndex targetIndex) throws DatatypeFormatException inherited
References GeometryLiteralIndex.retrieve().
{
         //Check the Geometry Literal Index to see if been previously read and cached.
         //DatatypeReader interface used to instruct index on how to obtain the GeometryWrapper.
         try {
             return GeometryLiteralIndex.retrieve(lexicalForm, this, targetIndex);
         } catch (IllegalArgumentException ex) {
             throw new DatatypeFormatException(ex.getMessage() + " - Illegal Geometry Literal: " + lexicalForm);
         }
     }
read()
GeometryWrapper read (String geometryLiteral)
{
         try {
             GeohashReferenceSystem refsys= new GeohashReferenceSystem(GeohashReferenceSystem.Format.BASE32, CommonCRS.WGS84.normalizedGeographic());
                 GeohashReferenceSystem.Coder coder=refsys.createCoder();
                         org.opengis.referencing.gazetteer.Location pos=(org.opengis.referencing.gazetteer.Location) coder.decode(geometryLiteral);
                         return GeometryWrapperFactory.createPoint(new Coordinate(pos.getPosition().getDirectPosition().getCoordinate()[0],pos.getPosition().getDirectPosition().getCoordinate()[1]), URI);
                 } catch (TransformException e) {
                         throw new AssertionError("Could not read GeoHash representation of: " + geometryLiteral);
                 }
     }
registerDatatypes()
static final void registerDatatypes () static inherited
References KMLDatatype.INSTANCE, GeoURIDatatype.INSTANCE, GPXDatatype.INSTANCE, HexWKBDatatype.INSTANCE, WKBDatatype.INSTANCE, EncodedPolylineDatatype.INSTANCE, TWKBDatatype.INSTANCE, GMLDatatype.INSTANCE, and GeoJSONDatatype.INSTANCE.
Referenced by GeometryDatatype.checkURI(), and GeometryDatatype.get().
{
         //System.out.println("Is")
         //if (!isDatatypesRegistered) {
             TYPE_MAPPER.registerDatatype(WKTDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GMLDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GeoJSONDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(KMLDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(WKBDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(TWKBDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(TopoJSONDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(GeobufDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(GeoHashDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(EncodedPolylineDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(HexWKBDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GeoURIDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(GPXDatatype.INSTANCE);
             isDatatypesRegistered = true;
         //}
     }
toString()
String toString ()
{
         return "GeoHashDatatype{" + URI + '}';
     }
unparse()
String unparse (Object geometry)
This method Un-parses the JTS Geometry to the WKT literal.
Parameters
geometry - the JTS Geometry to be un-parsed
Returns
WKT - the returned WKT Literal.
Notice that the Spatial Reference System is not specified in returned WKT literal.
{
         if (geometry instanceof GeometryWrapper) {
             Geometry geom1 = ((GeometryWrapper)geometry).getXYGeometry();
             GeohashReferenceSystem refsys;
                 try {
                         refsys = new GeohashReferenceSystem(GeohashReferenceSystem.Format.BASE32, CommonCRS.WGS84.normalizedGeographic());
                         GeohashReferenceSystem.Coder coder=refsys.createCoder();
                         if(geom1.getGeometryType().equalsIgnoreCase("Point")) {
                                 String geohash = coder.encode(Angle.toDegrees(geom1.getCoordinate().getX()), Angle.toDegrees(geom1.getCoordinate().getY()));
                                 return geohash;
                         }
                         throw new AssertionError("Object passed to GeoHashDatatype is not a Point: " + geometry);
                 } catch (TransformException e) {
                         // TODO Auto-generated catch block
                         throw new RuntimeException(e.getMessage());
                 }
         } else {
             throw new AssertionError("Object passed to GeoHashDatatype is not a GeometryWrapper: " + geometry);
         }
     }
Member Data Documentation
INSTANCE
final GeoHashDatatype INSTANCE = new GeoHashDatatype() static
A static instance of WKTDatatype.
URI
final String URI = PostGISGeo.GeoHash static
The default WKT type URI.