jena-geo: Geobuf.Data.Builder Class Reference
Geobuf.Data.Builder Class Reference
Protobuf type.
Public Member Functions
Builder clear ()
Builder clone ()
Geobuf.Data getDefaultInstanceForType ()
Geobuf.Data build ()
Geobuf.Data buildPartial ()
Builder mergeFrom (Geobuf.Data other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
DataTypeCase getDataTypeCase ()
Builder clearDataType ()
com.google.protobuf.ProtocolStringList getKeysList ()
repeated string keys = 1;
int getKeysCount ()
repeated string keys = 1;
java.lang.String getKeys (int index)
repeated string keys = 1;
com.google.protobuf.ByteString getKeysBytes (int index)
repeated string keys = 1;
Builder setKeys (int index, java.lang.String value)
repeated string keys = 1;
Builder addKeys (java.lang.String value)
repeated string keys = 1;
Builder addAllKeys (java.lang.Iterable< java.lang.String > values)
repeated string keys = 1;
Builder clearKeys ()
repeated string keys = 1;
Builder addKeysBytes (com.google.protobuf.ByteString value)
repeated string keys = 1;
boolean hasDimensions ()
optional uint32 dimensions = 2 [default = 2];
int getDimensions ()
optional uint32 dimensions = 2 [default = 2];
Builder setDimensions (int value)
optional uint32 dimensions = 2 [default = 2];
Builder clearDimensions ()
optional uint32 dimensions = 2 [default = 2];
boolean hasPrecision ()
optional uint32 precision = 3 [default = 6];
int getPrecision ()
optional uint32 precision = 3 [default = 6];
Builder setPrecision (int value)
optional uint32 precision = 3 [default = 6];
Builder clearPrecision ()
optional uint32 precision = 3 [default = 6];
boolean hasFeatureCollection ()
optional .Data.FeatureCollection feature_collection = 4;
Geobuf.Data.FeatureCollection getFeatureCollection ()
optional .Data.FeatureCollection feature_collection = 4;
Builder setFeatureCollection (Geobuf.Data.FeatureCollection value)
optional .Data.FeatureCollection feature_collection = 4;
Builder setFeatureCollection (Geobuf.Data.FeatureCollection.Builder builderForValue)
optional .Data.FeatureCollection feature_collection = 4;
Builder mergeFeatureCollection (Geobuf.Data.FeatureCollection value)
optional .Data.FeatureCollection feature_collection = 4;
Builder clearFeatureCollection ()
optional .Data.FeatureCollection feature_collection = 4;
boolean hasFeature ()
optional .Data.Feature feature = 5;
Geobuf.Data.Feature getFeature ()
optional .Data.Feature feature = 5;
Builder setFeature (Geobuf.Data.Feature value)
optional .Data.Feature feature = 5;
Builder setFeature (Geobuf.Data.Feature.Builder builderForValue)
optional .Data.Feature feature = 5;
Builder mergeFeature (Geobuf.Data.Feature value)
optional .Data.Feature feature = 5;
Builder clearFeature ()
optional .Data.Feature feature = 5;
boolean hasGeometry ()
optional .Data.Geometry geometry = 6;
Geobuf.Data.Geometry getGeometry ()
optional .Data.Geometry geometry = 6;
Builder setGeometry (Geobuf.Data.Geometry value)
optional .Data.Geometry geometry = 6;
Builder setGeometry (Geobuf.Data.Geometry.Builder builderForValue)
optional .Data.Geometry geometry = 6;
Builder mergeGeometry (Geobuf.Data.Geometry value)
optional .Data.Geometry geometry = 6;
Builder clearGeometry ()
optional .Data.Geometry geometry = 6;
Private Member Functions
Builder ()
void maybeForceBuilderInitialization ()
void ensureKeysIsMutable ()
Static Private Member Functions
static Builder create ()
Private Attributes
int dataTypeCase_ = 0
java.lang.Object dataType_
int bitField0_
com.google.protobuf.LazyStringList keys_ = com.google.protobuf.LazyStringArrayList.EMPTY
int dimensions_ = 2
int precision_ = 6
Detailed Description
Protobuf type.
Data
Constructor & Destructor Documentation
Builder()
Builder () private
{
         maybeForceBuilderInitialization();
       }
Member Function Documentation
addAllKeys()
Builder addAllKeys (java.lang.Iterable< java.lang.String > values)
repeated string keys = 1;
global arrays of unique keys
{
         ensureKeysIsMutable();
         com.google.protobuf.AbstractMessageLite.Builder.addAll(
             values, keys_);
         return this;
       }
addKeys()
Builder addKeys (java.lang.String value)
repeated string keys = 1;
global arrays of unique keys
{
         if (value == null) {
     throw new NullPointerException();
   }
   ensureKeysIsMutable();
         keys_.add(value);
         return this;
       }
addKeysBytes()
Builder addKeysBytes (com.google.protobuf.ByteString value)
repeated string keys = 1;
global arrays of unique keys
{
         if (value == null) {
     throw new NullPointerException();
   }
   ensureKeysIsMutable();
         keys_.add(value);
         return this;
       }
build()
Geobuf.Data build ()
Referenced by Geobuf.Data.Builder.setFeature(), Geobuf.Data.Builder.setFeatureCollection(), and Geobuf.Data.Builder.setGeometry().
{
         Geobuf.Data result = buildPartial();
         if (!result.isInitialized()) {
           throw newUninitializedMessageException(result);
         }
         return result;
       }
buildPartial()
Geobuf.Data buildPartial ()
References Geobuf.Data.keys_.
{
         Geobuf.Data result = new Geobuf.Data(this);
         int from_bitField0_ = bitField0_;
         int to_bitField0_ = 0;
         if (((bitField0_ & 0x00000001) == 0x00000001)) {
           keys_ = keys_.getUnmodifiableView();
           bitField0_ = (bitField0_ & ~0x00000001);
         }
         result.keys_ = keys_;
         if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
           to_bitField0_ |= 0x00000001;
         }
         result.dimensions_ = dimensions_;
         if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
           to_bitField0_ |= 0x00000002;
         }
         result.precision_ = precision_;
         if (dataTypeCase_ == 4) {
           result.dataType_ = dataType_;
         }
         if (dataTypeCase_ == 5) {
           result.dataType_ = dataType_;
         }
         if (dataTypeCase_ == 6) {
           result.dataType_ = dataType_;
         }
         result.bitField0_ = to_bitField0_;
         result.dataTypeCase_ = dataTypeCase_;
         return result;
       }
clear()
Builder clear ()
References Geobuf.Data.Builder.clear().
Referenced by Geobuf.Data.Builder.clear().
{
         super.clear();
         keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
         bitField0_ = (bitField0_ & ~0x00000001);
         dimensions_ = 2;
         bitField0_ = (bitField0_ & ~0x00000002);
         precision_ = 6;
         bitField0_ = (bitField0_ & ~0x00000004);
         dataTypeCase_ = 0;
         dataType_ = null;
         return this;
       }
clearDataType()
Builder clearDataType ()
{
         dataTypeCase_ = 0;
         dataType_ = null;
         return this;
       }
clearDimensions()
Builder clearDimensions ()
optional uint32 dimensions = 2 [default = 2];
max coordinate dimensions
{
         bitField0_ = (bitField0_ & ~0x00000002);
         dimensions_ = 2;
         return this;
       }
clearFeature()
Builder clearFeature ()
optional .Data.Feature feature = 5;
{
         if (dataTypeCase_ == 5) {
           dataTypeCase_ = 0;
           dataType_ = null;
         }
         return this;
       }
clearFeatureCollection()
Builder clearFeatureCollection ()
optional .Data.FeatureCollection feature_collection = 4;
{
         if (dataTypeCase_ == 4) {
           dataTypeCase_ = 0;
           dataType_ = null;
         }
         return this;
       }
clearGeometry()
Builder clearGeometry ()
optional .Data.Geometry geometry = 6;
References Geobuf.Data.FeatureCollection.initFields().
{
         if (dataTypeCase_ == 6) {
           dataTypeCase_ = 0;
           dataType_ = null;
         }
         return this;
       }
clearKeys()
Builder clearKeys ()
repeated string keys = 1;
global arrays of unique keys
{
         keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
         bitField0_ = (bitField0_ & ~0x00000001);
         return this;
       }
clearPrecision()
Builder clearPrecision ()
optional uint32 precision = 3 [default = 6];
number of digits after decimal point for coordinates
{
         bitField0_ = (bitField0_ & ~0x00000004);
         precision_ = 6;
         return this;
       }
clone()
Builder clone ()
References Geobuf.Data.Builder.mergeFrom().
{
         return create().mergeFrom(buildPartial());
       }
create()
static Builder create () static private
Referenced by Geobuf.Data.newBuilder().
{
         return new Builder();
       }
ensureKeysIsMutable()
void ensureKeysIsMutable () private
{
         if (!((bitField0_ & 0x00000001) == 0x00000001)) {
           keys_ = new com.google.protobuf.LazyStringArrayList(keys_);
           bitField0_ |= 0x00000001;
          }
       }
getDataTypeCase()
DataTypeCase getDataTypeCase ()
References Geobuf.Data.DataTypeCase.valueOf().
{
         return DataTypeCase.valueOf(
             dataTypeCase_);
       }
getDefaultInstanceForType()
Geobuf.Data getDefaultInstanceForType ()
References Geobuf.Data.getDefaultInstance().
{
         return Geobuf.Data.getDefaultInstance();
       }
getDimensions()
int getDimensions ()
optional uint32 dimensions = 2 [default = 2];
max coordinate dimensions
Implements Geobuf.DataOrBuilder.
{
         return dimensions_;
       }
getFeature()
Geobuf.Data.Feature getFeature ()
optional .Data.Feature feature = 5;
Implements Geobuf.DataOrBuilder.
References Geobuf.Data.Feature.getDefaultInstance().
{
         if (dataTypeCase_ == 5) {
           return (Geobuf.Data.Feature) dataType_;
         }
         return Geobuf.Data.Feature.getDefaultInstance();
       }
getFeatureCollection()
Geobuf.Data.FeatureCollection getFeatureCollection ()
optional .Data.FeatureCollection feature_collection = 4;
Implements Geobuf.DataOrBuilder.
References Geobuf.Data.FeatureCollection.getDefaultInstance().
{
         if (dataTypeCase_ == 4) {
           return (Geobuf.Data.FeatureCollection) dataType_;
         }
         return Geobuf.Data.FeatureCollection.getDefaultInstance();
       }
getGeometry()
Geobuf.Data.Geometry getGeometry ()
optional .Data.Geometry geometry = 6;
Implements Geobuf.DataOrBuilder.
References Geobuf.Data.Geometry.getDefaultInstance().
{
         if (dataTypeCase_ == 6) {
           return (Geobuf.Data.Geometry) dataType_;
         }
         return Geobuf.Data.Geometry.getDefaultInstance();
       }
getKeys()
java.lang.String getKeys (int index)
repeated string keys = 1;
global arrays of unique keys
Implements Geobuf.DataOrBuilder.
{
         return keys_.get(index);
       }
getKeysBytes()
com.google.protobuf.ByteString getKeysBytes (int index)
repeated string keys = 1;
global arrays of unique keys
Implements Geobuf.DataOrBuilder.
{
         return keys_.getByteString(index);
       }
getKeysCount()
int getKeysCount ()
repeated string keys = 1;
global arrays of unique keys
Implements Geobuf.DataOrBuilder.
{
         return keys_.size();
       }
getKeysList()
com.google.protobuf.ProtocolStringList getKeysList ()
repeated string keys = 1;
global arrays of unique keys
Implements Geobuf.DataOrBuilder.
{
         return keys_.getUnmodifiableView();
       }
getPrecision()
int getPrecision ()
optional uint32 precision = 3 [default = 6];
number of digits after decimal point for coordinates
Implements Geobuf.DataOrBuilder.
{
         return precision_;
       }
hasDimensions()
boolean hasDimensions ()
optional uint32 dimensions = 2 [default = 2];
max coordinate dimensions
Implements Geobuf.DataOrBuilder.
{
         return ((bitField0_ & 0x00000002) == 0x00000002);
       }
hasFeature()
boolean hasFeature ()
optional .Data.Feature feature = 5;
Implements Geobuf.DataOrBuilder.
{
         return dataTypeCase_ == 5;
       }
hasFeatureCollection()
boolean hasFeatureCollection ()
optional .Data.FeatureCollection feature_collection = 4;
Implements Geobuf.DataOrBuilder.
{
         return dataTypeCase_ == 4;
       }
hasGeometry()
boolean hasGeometry ()
optional .Data.Geometry geometry = 6;
Implements Geobuf.DataOrBuilder.
{
         return dataTypeCase_ == 6;
       }
hasPrecision()
boolean hasPrecision ()
optional uint32 precision = 3 [default = 6];
number of digits after decimal point for coordinates
Implements Geobuf.DataOrBuilder.
{
         return ((bitField0_ & 0x00000004) == 0x00000004);
       }
isInitialized()
final boolean isInitialized ()
References Geobuf.DataOrBuilder.getFeature(), Geobuf.DataOrBuilder.getFeatureCollection(), Geobuf.DataOrBuilder.getGeometry(), Geobuf.DataOrBuilder.hasFeature(), Geobuf.DataOrBuilder.hasFeatureCollection(), and Geobuf.DataOrBuilder.hasGeometry().
{
         if (hasFeatureCollection()) {
           if (!getFeatureCollection().isInitialized()) {
             return false;
           }
         }
         if (hasFeature()) {
           if (!getFeature().isInitialized()) {
             return false;
           }
         }
         if (hasGeometry()) {
           if (!getGeometry().isInitialized()) {
             return false;
           }
         }
         return true;
       }
maybeForceBuilderInitialization()
void maybeForceBuilderInitialization () private
{
       }
mergeFeature()
Builder mergeFeature (Geobuf.Data.Feature value)
optional .Data.Feature feature = 5;
References Geobuf.Data.Feature.Builder.buildPartial(), Geobuf.Data.Feature.getDefaultInstance(), Geobuf.Data.Feature.Builder.mergeFrom(), and Geobuf.Data.Feature.newBuilder().
{
         if (dataTypeCase_ == 5 &&
             dataType_ != Geobuf.Data.Feature.getDefaultInstance()) {
           dataType_ = Geobuf.Data.Feature.newBuilder((Geobuf.Data.Feature) dataType_)
               .mergeFrom(value).buildPartial();
         } else {
           dataType_ = value;
         }
         dataTypeCase_ = 5;
         return this;
       }
mergeFeatureCollection()
Builder mergeFeatureCollection (Geobuf.Data.FeatureCollection value)
optional .Data.FeatureCollection feature_collection = 4;
References Geobuf.Data.FeatureCollection.Builder.buildPartial(), Geobuf.Data.FeatureCollection.getDefaultInstance(), Geobuf.Data.FeatureCollection.Builder.mergeFrom(), and Geobuf.Data.FeatureCollection.newBuilder().
{
         if (dataTypeCase_ == 4 &&
             dataType_ != Geobuf.Data.FeatureCollection.getDefaultInstance()) {
           dataType_ = Geobuf.Data.FeatureCollection.newBuilder((Geobuf.Data.FeatureCollection) dataType_)
               .mergeFrom(value).buildPartial();
         } else {
           dataType_ = value;
         }
         dataTypeCase_ = 4;
         return this;
       }
mergeFrom() [1/2]
Builder mergeFrom (Geobuf.Data other)
References Geobuf.Data.getDefaultInstance(), and Geobuf.Data.Builder.keys_.
Referenced by Geobuf.Data.Builder.clone(), and Geobuf.Data.newBuilder().
{
         if (other == Geobuf.Data.getDefaultInstance()) return this;
         if (!other.keys_.isEmpty()) {
           if (keys_.isEmpty()) {
             keys_ = other.keys_;
             bitField0_ = (bitField0_ & ~0x00000001);
           } else {
             ensureKeysIsMutable();
             keys_.addAll(other.keys_);
           }
         }
         if (other.hasDimensions()) {
           setDimensions(other.getDimensions());
         }
         if (other.hasPrecision()) {
           setPrecision(other.getPrecision());
         }
         switch (other.getDataTypeCase()) {
           case FEATURE_COLLECTION: {
             mergeFeatureCollection(other.getFeatureCollection());
             break;
           }
           case FEATURE: {
             mergeFeature(other.getFeature());
             break;
           }
           case GEOMETRY: {
             mergeGeometry(other.getGeometry());
             break;
           }
           case DATATYPE_NOT_SET: {
             break;
           }
         }
         setUnknownFields(
             getUnknownFields().concat(other.unknownFields));
         return this;
       }
mergeFrom() [2/2]
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
{
         Geobuf.Data parsedMessage = null;
         try {
           parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
         } catch (com.google.protobuf.InvalidProtocolBufferException e) {
           parsedMessage = (Geobuf.Data) e.getUnfinishedMessage();
           throw e;
         } finally {
           if (parsedMessage != null) {
             mergeFrom(parsedMessage);
           }
         }
         return this;
       }
mergeGeometry()
Builder mergeGeometry (Geobuf.Data.Geometry value)
optional .Data.Geometry geometry = 6;
References Geobuf.Data.Geometry.Builder.buildPartial(), Geobuf.Data.Geometry.getDefaultInstance(), Geobuf.Data.Geometry.Builder.mergeFrom(), and Geobuf.Data.Geometry.newBuilder().
{
         if (dataTypeCase_ == 6 &&
             dataType_ != Geobuf.Data.Geometry.getDefaultInstance()) {
           dataType_ = Geobuf.Data.Geometry.newBuilder((Geobuf.Data.Geometry) dataType_)
               .mergeFrom(value).buildPartial();
         } else {
           dataType_ = value;
         }
         dataTypeCase_ = 6;
         return this;
       }
setDimensions()
Builder setDimensions (int value)
optional uint32 dimensions = 2 [default = 2];
max coordinate dimensions
Referenced by GeobufEncoder.makeFeatureCollection().
{
         bitField0_ |= 0x00000002;
         dimensions_ = value;
         return this;
       }
setFeature() [1/2]
Builder setFeature (Geobuf.Data.Feature value)
optional .Data.Feature feature = 5;
{
         if (value == null) {
           throw new NullPointerException();
         }
         dataType_ = value;
         dataTypeCase_ = 5;
         return this;
       }
setFeature() [2/2]
Builder setFeature (Geobuf.Data.Feature.Builder builderForValue)
optional .Data.Feature feature = 5;
References Geobuf.Data.Builder.build().
{
         dataType_ = builderForValue.build();
         dataTypeCase_ = 5;
         return this;
       }
setFeatureCollection() [1/2]
Builder setFeatureCollection (Geobuf.Data.FeatureCollection value)
optional .Data.FeatureCollection feature_collection = 4;
{
         if (value == null) {
           throw new NullPointerException();
         }
         dataType_ = value;
         dataTypeCase_ = 4;
         return this;
       }
setFeatureCollection() [2/2]
Builder setFeatureCollection (Geobuf.Data.FeatureCollection.Builder builderForValue)
optional .Data.FeatureCollection feature_collection = 4;
References Geobuf.Data.Builder.build().
{
         dataType_ = builderForValue.build();
         dataTypeCase_ = 4;
         return this;
       }
setGeometry() [1/2]
Builder setGeometry (Geobuf.Data.Geometry value)
optional .Data.Geometry geometry = 6;
{
         if (value == null) {
           throw new NullPointerException();
         }
         dataType_ = value;
         dataTypeCase_ = 6;
         return this;
       }
setGeometry() [2/2]
Builder setGeometry (Geobuf.Data.Geometry.Builder builderForValue)
optional .Data.Geometry geometry = 6;
References Geobuf.Data.Builder.build().
{
         dataType_ = builderForValue.build();
         dataTypeCase_ = 6;
         return this;
       }
setKeys()
Builder setKeys (int index, java.lang.String value)
repeated string keys = 1;
global arrays of unique keys
{
         if (value == null) {
     throw new NullPointerException();
   }
   ensureKeysIsMutable();
         keys_.set(index, value);
         return this;
       }
setPrecision()
Builder setPrecision (int value)
optional uint32 precision = 3 [default = 6];
number of digits after decimal point for coordinates
Referenced by GeobufEncoder.makeFeatureCollection().
{
         bitField0_ |= 0x00000004;
         precision_ = value;
         return this;
       }
Member Data Documentation
bitField0_
int bitField0_ private
dataType_
java.lang.Object dataType_ private
dataTypeCase_
int dataTypeCase_ = 0 private
dimensions_
int dimensions_ = 2 private
keys_
com.google.protobuf.LazyStringList keys_ = com.google.protobuf.LazyStringArrayList.EMPTY private
Referenced by Geobuf.Data.Builder.mergeFrom().
precision_
int precision_ = 6 private