jena-geo: Geobuf.Data.Geometry Class Reference
Geobuf.Data.Geometry Class Reference
Protobuf type.
Classes
class Builder
Protobuf type.
enum Type
Protobuf enum.
Public Member Functions
Geometry getDefaultInstanceForType ()
.lang.Override com.google.protobuf.Parser< Geometry > getParserForType ()
boolean hasType ()
required .Data.Geometry.Type type = 1;
Geobuf.Data.Geometry.Type getType ()
required .Data.Geometry.Type type = 1;
java.util.List< java.lang.Integer > getLengthsList ()
repeated uint32 lengths = 2 [packed = true];
int getLengthsCount ()
repeated uint32 lengths = 2 [packed = true];
int getLengths (int index)
repeated uint32 lengths = 2 [packed = true];
java.util.List< java.lang.Long > getCoordsList ()
repeated sint64 coords = 3 [packed = true];
int getCoordsCount ()
repeated sint64 coords = 3 [packed = true];
long getCoords (int index)
repeated sint64 coords = 3 [packed = true];
java.util.List< Geobuf.Data.Geometry > getGeometriesList ()
repeated .Data.Geometry geometries = 4;
java.util.List<? extends Geobuf.Data.GeometryOrBuilder > getGeometriesOrBuilderList ()
repeated .Data.Geometry geometries = 4;
int getGeometriesCount ()
repeated .Data.Geometry geometries = 4;
Geobuf.Data.Geometry getGeometries (int index)
repeated .Data.Geometry geometries = 4;
Geobuf.Data.GeometryOrBuilder getGeometriesOrBuilder (int index)
repeated .Data.Geometry geometries = 4;
java.util.List< Geobuf.Data.Value > getValuesList ()
repeated .Data.Value values = 13;
java.util.List<? extends Geobuf.Data.ValueOrBuilder > getValuesOrBuilderList ()
repeated .Data.Value values = 13;
int getValuesCount ()
repeated .Data.Value values = 13;
Geobuf.Data.Value getValues (int index)
repeated .Data.Value values = 13;
Geobuf.Data.ValueOrBuilder getValuesOrBuilder (int index)
repeated .Data.Value values = 13;
java.util.List< java.lang.Integer > getCustomPropertiesList ()
repeated uint32 custom_properties = 15 [packed = true];
int getCustomPropertiesCount ()
repeated uint32 custom_properties = 15 [packed = true];
int getCustomProperties (int index)
repeated uint32 custom_properties = 15 [packed = true];
final boolean isInitialized ()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
int getSerializedSize ()
Builder newBuilderForType ()
Builder toBuilder ()
Static Public Member Functions
static Geometry getDefaultInstance ()
static Geobuf.Data.Geometry parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.Geometry parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.Geometry parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.Geometry parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static Geobuf.Data.Geometry parseFrom (java.io.InputStream input) throws java.io.IOException
static Geobuf.Data.Geometry parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Geobuf.Data.Geometry parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static Geobuf.Data.Geometry parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Geobuf.Data.Geometry parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static Geobuf.Data.Geometry parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (Geobuf.Data.Geometry prototype)
Static Public Attributes
static com.google.protobuf.Parser< Geometry > PARSER
static final int TYPE_FIELD_NUMBER = 1
static final int LENGTHS_FIELD_NUMBER = 2
static final int COORDS_FIELD_NUMBER = 3
static final int GEOMETRIES_FIELD_NUMBER = 4
static final int VALUES_FIELD_NUMBER = 13
static final int CUSTOM_PROPERTIES_FIELD_NUMBER = 15
Protected Member Functions
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException
Static Package Functions
[static initializer]
Private Member Functions
Geometry (com.google.protobuf.GeneratedMessageLite.Builder builder)
Geometry (boolean noInit)
Geometry (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
void initFields ()
Private Attributes
final com.google.protobuf.ByteString unknownFields
int bitField0_
Geobuf.Data.Geometry.Type type_
java.util.List< java.lang.Integer > lengths_
int lengthsMemoizedSerializedSize = -1
java.util.List< java.lang.Long > coords_
int coordsMemoizedSerializedSize = -1
java.util.List< Geobuf.Data.Geometry > geometries_
java.util.List< Geobuf.Data.Value > values_
java.util.List< java.lang.Integer > customProperties_
int customPropertiesMemoizedSerializedSize = -1
byte memoizedIsInitialized = -1
int memoizedSerializedSize = -1
Static Private Attributes
static final Geometry defaultInstance
static final long serialVersionUID = 0L
Detailed Description
Protobuf type.
Data.Geometry
Constructor & Destructor Documentation
Geometry() [1/3]
Geometry (com.google.protobuf.GeneratedMessageLite.Builder builder) private
{
         super(builder);
         this.unknownFields = builder.getUnknownFields();
       }
Geometry() [2/3]
Geometry (boolean noInit) private
 { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}
Geometry() [3/3]
Geometry (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException private
References Geobuf.Data.Geometry.PARSER, Geobuf.Data.Value.PARSER, and Geobuf.Data.Geometry.Type.valueOf().
{
         initFields();
         int mutable_bitField0_ = 0;
         com.google.protobuf.ByteString.Output unknownFieldsOutput =
             com.google.protobuf.ByteString.newOutput();
         com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
             com.google.protobuf.CodedOutputStream.newInstance(
                 unknownFieldsOutput);
         try {
           boolean done = false;
           while (!done) {
             int tag = input.readTag();
             switch (tag) {
               case 0:
                 done = true;
                 break;
               default: {
                 if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                        extensionRegistry, tag)) {
                   done = true;
                 }
                 break;
               }
               case 8: {
                 int rawValue = input.readEnum();
                 Geobuf.Data.Geometry.Type value = Geobuf.Data.Geometry.Type.valueOf(rawValue);
                 if (value == null) {
                   unknownFieldsCodedOutput.writeRawVarint32(tag);
                   unknownFieldsCodedOutput.writeRawVarint32(rawValue);
                 } else {
                   bitField0_ |= 0x00000001;
                   type_ = value;
                 }
                 break;
               }
               case 16: {
                 if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                   lengths_ = new java.util.ArrayList<java.lang.Integer>();
                   mutable_bitField0_ |= 0x00000002;
                 }
                 lengths_.add(input.readUInt32());
                 break;
               }
               case 18: {
                 int length = input.readRawVarint32();
                 int limit = input.pushLimit(length);
                 if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                   lengths_ = new java.util.ArrayList<java.lang.Integer>();
                   mutable_bitField0_ |= 0x00000002;
                 }
                 while (input.getBytesUntilLimit() > 0) {
                   lengths_.add(input.readUInt32());
                 }
                 input.popLimit(limit);
                 break;
               }
               case 24: {
                 if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                   coords_ = new java.util.ArrayList<java.lang.Long>();
                   mutable_bitField0_ |= 0x00000004;
                 }
                 coords_.add(input.readSInt64());
                 break;
               }
               case 26: {
                 int length = input.readRawVarint32();
                 int limit = input.pushLimit(length);
                 if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                   coords_ = new java.util.ArrayList<java.lang.Long>();
                   mutable_bitField0_ |= 0x00000004;
                 }
                 while (input.getBytesUntilLimit() > 0) {
                   coords_.add(input.readSInt64());
                 }
                 input.popLimit(limit);
                 break;
               }
               case 34: {
                 if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                   geometries_ = new java.util.ArrayList<Geobuf.Data.Geometry>();
                   mutable_bitField0_ |= 0x00000008;
                 }
                 geometries_.add(input.readMessage(Geobuf.Data.Geometry.PARSER, extensionRegistry));
                 break;
               }
               case 106: {
                 if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                   values_ = new java.util.ArrayList<Geobuf.Data.Value>();
                   mutable_bitField0_ |= 0x00000010;
                 }
                 values_.add(input.readMessage(Geobuf.Data.Value.PARSER, extensionRegistry));
                 break;
               }
               case 120: {
                 if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                   customProperties_ = new java.util.ArrayList<java.lang.Integer>();
                   mutable_bitField0_ |= 0x00000020;
                 }
                 customProperties_.add(input.readUInt32());
                 break;
               }
               case 122: {
                 int length = input.readRawVarint32();
                 int limit = input.pushLimit(length);
                 if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                   customProperties_ = new java.util.ArrayList<java.lang.Integer>();
                   mutable_bitField0_ |= 0x00000020;
                 }
                 while (input.getBytesUntilLimit() > 0) {
                   customProperties_.add(input.readUInt32());
                 }
                 input.popLimit(limit);
                 break;
               }
             }
           }
         } catch (com.google.protobuf.InvalidProtocolBufferException e) {
           throw e.setUnfinishedMessage(this);
         } catch (java.io.IOException e) {
           throw new com.google.protobuf.InvalidProtocolBufferException(
               e.getMessage()).setUnfinishedMessage(this);
         } finally {
           if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
             lengths_ = java.util.Collections.unmodifiableList(lengths_);
           }
           if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
             coords_ = java.util.Collections.unmodifiableList(coords_);
           }
           if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
             geometries_ = java.util.Collections.unmodifiableList(geometries_);
           }
           if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
             values_ = java.util.Collections.unmodifiableList(values_);
           }
           if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
             customProperties_ = java.util.Collections.unmodifiableList(customProperties_);
           }
           try {
             unknownFieldsCodedOutput.flush();
           } catch (java.io.IOException e) {
           // Should not happen
           } finally {
             unknownFields = unknownFieldsOutput.toByteString();
           }
           makeExtensionsImmutable();
         }
       }
Member Function Documentation
[static initializer]()
[static initializer] () static package
getCoords()
long getCoords (int index)
repeated sint64 coords = 3 [packed = true];
delta-encoded integer values
Implements Geobuf.Data.GeometryOrBuilder.
{
         return coords_.get(index);
       }
getCoordsCount()
int getCoordsCount ()
repeated sint64 coords = 3 [packed = true];
delta-encoded integer values
Implements Geobuf.Data.GeometryOrBuilder.
{
         return coords_.size();
       }
getCoordsList()
java.util.List<java.lang.Long> getCoordsList ()
repeated sint64 coords = 3 [packed = true];
delta-encoded integer values
Implements Geobuf.Data.GeometryOrBuilder.
{
         return coords_;
       }
getCustomProperties()
int getCustomProperties (int index)
repeated uint32 custom_properties = 15 [packed = true];
Implements Geobuf.Data.GeometryOrBuilder.
{
         return customProperties_.get(index);
       }
getCustomPropertiesCount()
int getCustomPropertiesCount ()
repeated uint32 custom_properties = 15 [packed = true];
Implements Geobuf.Data.GeometryOrBuilder.
{
         return customProperties_.size();
       }
getCustomPropertiesList()
java.util.List<java.lang.Integer> getCustomPropertiesList ()
repeated uint32 custom_properties = 15 [packed = true];
Implements Geobuf.Data.GeometryOrBuilder.
{
         return customProperties_;
       }
getDefaultInstance()
static Geometry getDefaultInstance () static
Referenced by Geobuf.Data.Feature.Builder.clear(), Geobuf.Data.Feature.Builder.clearGeometry(), Geobuf.Data.Geometry.Builder.getDefaultInstanceForType(), Geobuf.Data.getGeometry(), Geobuf.Data.Builder.getGeometry(), Geobuf.Data.Feature.initFields(), Geobuf.Data.Geometry.Builder.mergeFrom(), Geobuf.Data.Feature.Builder.mergeGeometry(), and Geobuf.Data.Builder.mergeGeometry().
{
         return defaultInstance;
       }
getDefaultInstanceForType()
Geometry getDefaultInstanceForType ()
{
         return defaultInstance;
       }
getGeometries()
Geobuf.Data.Geometry getGeometries (int index)
repeated .Data.Geometry geometries = 4;
Implements Geobuf.Data.GeometryOrBuilder.
{
         return geometries_.get(index);
       }
getGeometriesCount()
int getGeometriesCount ()
repeated .Data.Geometry geometries = 4;
Implements Geobuf.Data.GeometryOrBuilder.
{
         return geometries_.size();
       }
getGeometriesList()
java.util.List<Geobuf.Data.Geometry> getGeometriesList ()
repeated .Data.Geometry geometries = 4;
Implements Geobuf.Data.GeometryOrBuilder.
{
         return geometries_;
       }
getGeometriesOrBuilder()
Geobuf.Data.GeometryOrBuilder getGeometriesOrBuilder (int index)
repeated .Data.Geometry geometries = 4;
                      {
         return geometries_.get(index);
       }
getGeometriesOrBuilderList()
java.util.List<? extends Geobuf.Data.GeometryOrBuilder> getGeometriesOrBuilderList ()
repeated .Data.Geometry geometries = 4;
{
         return geometries_;
       }
getLengths()
int getLengths (int index)
repeated uint32 lengths = 2 [packed = true];
coordinate structure in lengths
Implements Geobuf.Data.GeometryOrBuilder.
{
         return lengths_.get(index);
       }
getLengthsCount()
int getLengthsCount ()
repeated uint32 lengths = 2 [packed = true];
coordinate structure in lengths
Implements Geobuf.Data.GeometryOrBuilder.
{
         return lengths_.size();
       }
getLengthsList()
java.util.List<java.lang.Integer> getLengthsList ()
repeated uint32 lengths = 2 [packed = true];
coordinate structure in lengths
Implements Geobuf.Data.GeometryOrBuilder.
{
         return lengths_;
       }
getParserForType()
.lang.Override com.google.protobuf.Parser<Geometry> getParserForType ()
{
         return PARSER;
       }
getSerializedSize()
int getSerializedSize ()
{
         int size = memoizedSerializedSize;
         if (size != -1) return size;
         size = 0;
         if (((bitField0_ & 0x00000001) == 0x00000001)) {
           size += com.google.protobuf.CodedOutputStream
             .computeEnumSize(1, type_.getNumber());
         }
         {
           int dataSize = 0;
           for (int i = 0; i < lengths_.size(); i++) {
             dataSize += com.google.protobuf.CodedOutputStream
               .computeUInt32SizeNoTag(lengths_.get(i));
           }
           size += dataSize;
           if (!getLengthsList().isEmpty()) {
             size += 1;
             size += com.google.protobuf.CodedOutputStream
                 .computeInt32SizeNoTag(dataSize);
           }
           lengthsMemoizedSerializedSize = dataSize;
         }
         {
           int dataSize = 0;
           for (int i = 0; i < coords_.size(); i++) {
             dataSize += com.google.protobuf.CodedOutputStream
               .computeSInt64SizeNoTag(coords_.get(i));
           }
           size += dataSize;
           if (!getCoordsList().isEmpty()) {
             size += 1;
             size += com.google.protobuf.CodedOutputStream
                 .computeInt32SizeNoTag(dataSize);
           }
           coordsMemoizedSerializedSize = dataSize;
         }
         for (int i = 0; i < geometries_.size(); i++) {
           size += com.google.protobuf.CodedOutputStream
             .computeMessageSize(4, geometries_.get(i));
         }
         for (int i = 0; i < values_.size(); i++) {
           size += com.google.protobuf.CodedOutputStream
             .computeMessageSize(13, values_.get(i));
         }
         {
           int dataSize = 0;
           for (int i = 0; i < customProperties_.size(); i++) {
             dataSize += com.google.protobuf.CodedOutputStream
               .computeUInt32SizeNoTag(customProperties_.get(i));
           }
           size += dataSize;
           if (!getCustomPropertiesList().isEmpty()) {
             size += 1;
             size += com.google.protobuf.CodedOutputStream
                 .computeInt32SizeNoTag(dataSize);
           }
           customPropertiesMemoizedSerializedSize = dataSize;
         }
         size += unknownFields.size();
         memoizedSerializedSize = size;
         return size;
       }
getType()
Geobuf.Data.Geometry.Type getType ()
required .Data.Geometry.Type type = 1;
Implements Geobuf.Data.GeometryOrBuilder.
{
         return type_;
       }
getValues()
Geobuf.Data.Value getValues (int index)
repeated .Data.Value values = 13;
Implements Geobuf.Data.GeometryOrBuilder.
{
         return values_.get(index);
       }
getValuesCount()
int getValuesCount ()
repeated .Data.Value values = 13;
Implements Geobuf.Data.GeometryOrBuilder.
{
         return values_.size();
       }
getValuesList()
java.util.List<Geobuf.Data.Value> getValuesList ()
repeated .Data.Value values = 13;
Implements Geobuf.Data.GeometryOrBuilder.
{
         return values_;
       }
getValuesOrBuilder()
Geobuf.Data.ValueOrBuilder getValuesOrBuilder (int index)
repeated .Data.Value values = 13;
                      {
         return values_.get(index);
       }
getValuesOrBuilderList()
java.util.List<? extends Geobuf.Data.ValueOrBuilder> getValuesOrBuilderList ()
repeated .Data.Value values = 13;
{
         return values_;
       }
hasType()
boolean hasType ()
required .Data.Geometry.Type type = 1;
Implements Geobuf.Data.GeometryOrBuilder.
{
         return ((bitField0_ & 0x00000001) == 0x00000001);
       }
initFields()
void initFields () private
References Geobuf.Data.Geometry.Type.POINT.
Referenced by Geobuf.Data.Geometry.Builder.clearCustomProperties().
{
         type_ = Geobuf.Data.Geometry.Type.POINT;
         lengths_ = java.util.Collections.emptyList();
         coords_ = java.util.Collections.emptyList();
         geometries_ = java.util.Collections.emptyList();
         values_ = java.util.Collections.emptyList();
         customProperties_ = java.util.Collections.emptyList();
       }
isInitialized()
final boolean isInitialized ()
{
         byte isInitialized = memoizedIsInitialized;
         if (isInitialized == 1) return true;
         if (isInitialized == 0) return false;
         if (!hasType()) {
           memoizedIsInitialized = 0;
           return false;
         }
         for (int i = 0; i < getGeometriesCount(); i++) {
           if (!getGeometries(i).isInitialized()) {
             memoizedIsInitialized = 0;
             return false;
           }
         }
         memoizedIsInitialized = 1;
         return true;
       }
newBuilder() [1/2]
static Builder newBuilder () static
References Geobuf.Data.Geometry.Builder.create().
Referenced by Geobuf.Data.Feature.Builder.mergeGeometry(), Geobuf.Data.Builder.mergeGeometry(), GeobufEncoder.multiPolyToGeobuf(), GeobufEncoder.pointToGeobuf(), and GeobufEncoder.polyToGeobuf().
 { return Builder.create(); }
newBuilder() [2/2]
static Builder newBuilder (Geobuf.Data.Geometry prototype) static
References Geobuf.Data.Geometry.Builder.mergeFrom().
{
         return newBuilder().mergeFrom(prototype);
       }
newBuilderForType()
Builder newBuilderForType ()
 { return newBuilder(); }
parseDelimitedFrom() [1/2]
static Geobuf.Data.Geometry parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException static
References Geobuf.Data.Geometry.parseDelimitedFrom().
Referenced by Geobuf.Data.Geometry.parseDelimitedFrom().
{
         return PARSER.parseDelimitedFrom(input);
       }
parseDelimitedFrom() [2/2]
static Geobuf.Data.Geometry parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException static
References Geobuf.Data.Geometry.parseDelimitedFrom().
{
         return PARSER.parseDelimitedFrom(input, extensionRegistry);
       }
parseFrom() [1/8]
static Geobuf.Data.Geometry parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.Geometry.parseFrom().
Referenced by Geobuf.Data.Geometry.parseFrom().
{
         return PARSER.parseFrom(data);
       }
parseFrom() [2/8]
static Geobuf.Data.Geometry parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.Geometry.parseFrom().
{
         return PARSER.parseFrom(data, extensionRegistry);
       }
parseFrom() [3/8]
static Geobuf.Data.Geometry parseFrom (byte [] data) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.Geometry.parseFrom().
{
         return PARSER.parseFrom(data);
       }
parseFrom() [4/8]
static Geobuf.Data.Geometry parseFrom (byte [] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException static
References Geobuf.Data.Geometry.parseFrom().
{
         return PARSER.parseFrom(data, extensionRegistry);
       }
parseFrom() [5/8]
static Geobuf.Data.Geometry parseFrom (java.io.InputStream input) throws java.io.IOException static
References Geobuf.Data.Geometry.parseFrom().
{
         return PARSER.parseFrom(input);
       }
parseFrom() [6/8]
static Geobuf.Data.Geometry parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException static
References Geobuf.Data.Geometry.parseFrom().
{
         return PARSER.parseFrom(input, extensionRegistry);
       }
parseFrom() [7/8]
static Geobuf.Data.Geometry parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException static
References Geobuf.Data.Geometry.parseFrom().
{
         return PARSER.parseFrom(input);
       }
parseFrom() [8/8]
static Geobuf.Data.Geometry parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException static
References Geobuf.Data.Geometry.parseFrom().
{
         return PARSER.parseFrom(input, extensionRegistry);
       }
toBuilder()
Builder toBuilder ()
 { return newBuilder(this); }
writeReplace()
.lang.Override java.lang.Object writeReplace () throws java.io.ObjectStreamException protected
{
         return super.writeReplace();
       }
writeTo()
void writeTo (com.google.protobuf.CodedOutputStream output) throws java.io.IOException
{
         getSerializedSize();
         if (((bitField0_ & 0x00000001) == 0x00000001)) {
           output.writeEnum(1, type_.getNumber());
         }
         if (getLengthsList().size() > 0) {
           output.writeRawVarint32(18);
           output.writeRawVarint32(lengthsMemoizedSerializedSize);
         }
         for (int i = 0; i < lengths_.size(); i++) {
           output.writeUInt32NoTag(lengths_.get(i));
         }
         if (getCoordsList().size() > 0) {
           output.writeRawVarint32(26);
           output.writeRawVarint32(coordsMemoizedSerializedSize);
         }
         for (int i = 0; i < coords_.size(); i++) {
           output.writeSInt64NoTag(coords_.get(i));
         }
         for (int i = 0; i < geometries_.size(); i++) {
           output.writeMessage(4, geometries_.get(i));
         }
         for (int i = 0; i < values_.size(); i++) {
           output.writeMessage(13, values_.get(i));
         }
         if (getCustomPropertiesList().size() > 0) {
           output.writeRawVarint32(122);
           output.writeRawVarint32(customPropertiesMemoizedSerializedSize);
         }
         for (int i = 0; i < customProperties_.size(); i++) {
           output.writeUInt32NoTag(customProperties_.get(i));
         }
         output.writeRawBytes(unknownFields);
       }
Member Data Documentation
bitField0_
int bitField0_ private
coords_
java.util.List<java.lang.Long> coords_ private
COORDS_FIELD_NUMBER
final int COORDS_FIELD_NUMBER = 3 static
coordsMemoizedSerializedSize
int coordsMemoizedSerializedSize = -1 private
CUSTOM_PROPERTIES_FIELD_NUMBER
final int CUSTOM_PROPERTIES_FIELD_NUMBER = 15 static
customProperties_
java.util.List<java.lang.Integer> customProperties_ private
customPropertiesMemoizedSerializedSize
int customPropertiesMemoizedSerializedSize = -1 private
defaultInstance
final Geometry defaultInstance static private
geometries_
java.util.List<Geobuf.Data.Geometry> geometries_ private
GEOMETRIES_FIELD_NUMBER
final int GEOMETRIES_FIELD_NUMBER = 4 static
lengths_
java.util.List<java.lang.Integer> lengths_ private
LENGTHS_FIELD_NUMBER
final int LENGTHS_FIELD_NUMBER = 2 static
lengthsMemoizedSerializedSize
int lengthsMemoizedSerializedSize = -1 private
memoizedIsInitialized
byte memoizedIsInitialized = -1 private
memoizedSerializedSize
int memoizedSerializedSize = -1 private
PARSER
com.google.protobuf.Parser<Geometry> PARSER static
Initial value:
=
          new com.google.protobuf.AbstractParser<Geometry>() {
        public Geometry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Geometry(input, extensionRegistry);
        }
      }
Referenced by Geobuf.Data.Data(), Geobuf.Data.Feature.Feature(), and Geobuf.Data.Geometry.Geometry().
serialVersionUID
final long serialVersionUID = 0L static private
type_
Geobuf.Data.Geometry.Type type_ private
Referenced by Geobuf.Data.Geometry.Builder.buildPartial().
TYPE_FIELD_NUMBER
final int TYPE_FIELD_NUMBER = 1 static
unknownFields
final com.google.protobuf.ByteString unknownFields private
values_
java.util.List<Geobuf.Data.Value> values_ private
VALUES_FIELD_NUMBER
final int VALUES_FIELD_NUMBER = 13 static