jena-geo: Geobuf.DataOrBuilder Interface Reference
Geobuf.DataOrBuilder Interface Reference
Public Member Functions
com.google.protobuf.ProtocolStringList getKeysList ()
repeated string keys = 1;
int getKeysCount ()
repeated string keys = 1;
java.lang.String getKeys (int index)
repeated string keys = 1;
com.google.protobuf.ByteString getKeysBytes (int index)
repeated string keys = 1;
boolean hasDimensions ()
optional uint32 dimensions = 2 [default = 2];
int getDimensions ()
optional uint32 dimensions = 2 [default = 2];
boolean hasPrecision ()
optional uint32 precision = 3 [default = 6];
int getPrecision ()
optional uint32 precision = 3 [default = 6];
boolean hasFeatureCollection ()
optional .Data.FeatureCollection feature_collection = 4;
Geobuf.Data.FeatureCollection getFeatureCollection ()
optional .Data.FeatureCollection feature_collection = 4;
boolean hasFeature ()
optional .Data.Feature feature = 5;
Geobuf.Data.Feature getFeature ()
optional .Data.Feature feature = 5;
boolean hasGeometry ()
optional .Data.Geometry geometry = 6;
Geobuf.Data.Geometry getGeometry ()
optional .Data.Geometry geometry = 6;
Member Function Documentation
getDimensions()
int getDimensions ()
optional uint32 dimensions = 2 [default = 2];
max coordinate dimensions
Implemented in Geobuf.Data.Builder, and Geobuf.Data.
getFeature()
Geobuf.Data.Feature getFeature ()
optional .Data.Feature feature = 5;
Implemented in Geobuf.Data.Builder, and Geobuf.Data.
Referenced by Geobuf.Data.isInitialized(), and Geobuf.Data.Builder.isInitialized().
getFeatureCollection()
Geobuf.Data.FeatureCollection getFeatureCollection ()
optional .Data.FeatureCollection feature_collection = 4;
Implemented in Geobuf.Data.Builder, and Geobuf.Data.
Referenced by Geobuf.Data.isInitialized(), and Geobuf.Data.Builder.isInitialized().
getGeometry()
Geobuf.Data.Geometry getGeometry ()
optional .Data.Geometry geometry = 6;
Implemented in Geobuf.Data.Builder, and Geobuf.Data.
Referenced by Geobuf.Data.Feature.isInitialized(), Geobuf.Data.Feature.Builder.isInitialized(), Geobuf.Data.isInitialized(), and Geobuf.Data.Builder.isInitialized().
getKeys()
java.lang.String getKeys (int index)
repeated string keys = 1;
global arrays of unique keys
Implemented in Geobuf.Data.Builder, and Geobuf.Data.
getKeysBytes()
com.google.protobuf.ByteString getKeysBytes (int index)
repeated string keys = 1;
global arrays of unique keys
Implemented in Geobuf.Data.Builder, and Geobuf.Data.
getKeysCount()
int getKeysCount ()
repeated string keys = 1;
global arrays of unique keys
Implemented in Geobuf.Data.Builder, and Geobuf.Data.
getKeysList()
com.google.protobuf.ProtocolStringList getKeysList ()
repeated string keys = 1;
global arrays of unique keys
Implemented in Geobuf.Data.Builder, and Geobuf.Data.
Referenced by Geobuf.Data.getSerializedSize().
getPrecision()
int getPrecision ()
optional uint32 precision = 3 [default = 6];
number of digits after decimal point for coordinates
Implemented in Geobuf.Data.Builder, and Geobuf.Data.
hasDimensions()
boolean hasDimensions ()
optional uint32 dimensions = 2 [default = 2];
max coordinate dimensions
Implemented in Geobuf.Data.Builder, and Geobuf.Data.
hasFeature()
boolean hasFeature ()
optional .Data.Feature feature = 5;
Implemented in Geobuf.Data.Builder, and Geobuf.Data.
Referenced by Geobuf.Data.isInitialized(), and Geobuf.Data.Builder.isInitialized().
hasFeatureCollection()
boolean hasFeatureCollection ()
optional .Data.FeatureCollection feature_collection = 4;
Implemented in Geobuf.Data.Builder, and Geobuf.Data.
Referenced by Geobuf.Data.isInitialized(), and Geobuf.Data.Builder.isInitialized().
hasGeometry()
boolean hasGeometry ()
optional .Data.Geometry geometry = 6;
Implemented in Geobuf.Data.Builder, and Geobuf.Data.
Referenced by Geobuf.Data.Feature.isInitialized(), Geobuf.Data.Feature.Builder.isInitialized(), Geobuf.Data.isInitialized(), and Geobuf.Data.Builder.isInitialized().
hasPrecision()
boolean hasPrecision ()
optional uint32 precision = 3 [default = 6];
number of digits after decimal point for coordinates
Implemented in Geobuf.Data.Builder, and Geobuf.Data.