jena-geo: Geobuf.Data.Feature.Builder Class Reference
Geobuf.Data.Feature.Builder Class Reference
Protobuf type.
Public Member Functions
Builder clear ()
Builder clone ()
Geobuf.Data.Feature getDefaultInstanceForType ()
Geobuf.Data.Feature build ()
Geobuf.Data.Feature buildPartial ()
Builder mergeFrom (Geobuf.Data.Feature other)
final boolean isInitialized ()
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
IdTypeCase getIdTypeCase ()
Builder clearIdType ()
boolean hasGeometry ()
required .Data.Geometry geometry = 1;
Geobuf.Data.Geometry getGeometry ()
required .Data.Geometry geometry = 1;
Builder setGeometry (Geobuf.Data.Geometry value)
required .Data.Geometry geometry = 1;
Builder setGeometry (Geobuf.Data.Geometry.Builder builderForValue)
required .Data.Geometry geometry = 1;
Builder mergeGeometry (Geobuf.Data.Geometry value)
required .Data.Geometry geometry = 1;
Builder clearGeometry ()
required .Data.Geometry geometry = 1;
boolean hasId ()
optional string id = 11;
java.lang.String getId ()
optional string id = 11;
com.google.protobuf.ByteString getIdBytes ()
optional string id = 11;
Builder setId (java.lang.String value)
optional string id = 11;
Builder clearId ()
optional string id = 11;
Builder setIdBytes (com.google.protobuf.ByteString value)
optional string id = 11;
boolean hasIntId ()
optional sint64 int_id = 12;
long getIntId ()
optional sint64 int_id = 12;
Builder setIntId (long value)
optional sint64 int_id = 12;
Builder clearIntId ()
optional sint64 int_id = 12;
java.util.List< Geobuf.Data.Value > getValuesList ()
repeated .Data.Value values = 13;
int getValuesCount ()
repeated .Data.Value values = 13;
Geobuf.Data.Value getValues (int index)
repeated .Data.Value values = 13;
Builder setValues (int index, Geobuf.Data.Value value)
repeated .Data.Value values = 13;
Builder setValues (int index, Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
Builder addValues (Geobuf.Data.Value value)
repeated .Data.Value values = 13;
Builder addValues (int index, Geobuf.Data.Value value)
repeated .Data.Value values = 13;
Builder addValues (Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
Builder addValues (int index, Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
Builder addAllValues (java.lang.Iterable<? extends Geobuf.Data.Value > values)
repeated .Data.Value values = 13;
Builder clearValues ()
repeated .Data.Value values = 13;
Builder removeValues (int index)
repeated .Data.Value values = 13;
java.util.List< java.lang.Integer > getPropertiesList ()
repeated uint32 properties = 14 [packed = true];
int getPropertiesCount ()
repeated uint32 properties = 14 [packed = true];
int getProperties (int index)
repeated uint32 properties = 14 [packed = true];
Builder setProperties (int index, int value)
repeated uint32 properties = 14 [packed = true];
Builder addProperties (int value)
repeated uint32 properties = 14 [packed = true];
Builder addAllProperties (java.lang.Iterable<? extends java.lang.Integer > values)
repeated uint32 properties = 14 [packed = true];
Builder clearProperties ()
repeated uint32 properties = 14 [packed = true];
java.util.List< java.lang.Integer > getCustomPropertiesList ()
repeated uint32 custom_properties = 15 [packed = true];
int getCustomPropertiesCount ()
repeated uint32 custom_properties = 15 [packed = true];
int getCustomProperties (int index)
repeated uint32 custom_properties = 15 [packed = true];
Builder setCustomProperties (int index, int value)
repeated uint32 custom_properties = 15 [packed = true];
Builder addCustomProperties (int value)
repeated uint32 custom_properties = 15 [packed = true];
Builder addAllCustomProperties (java.lang.Iterable<? extends java.lang.Integer > values)
repeated uint32 custom_properties = 15 [packed = true];
Builder clearCustomProperties ()
repeated uint32 custom_properties = 15 [packed = true];
Private Member Functions
Builder ()
void maybeForceBuilderInitialization ()
void ensureValuesIsMutable ()
void ensurePropertiesIsMutable ()
void ensureCustomPropertiesIsMutable ()
Static Private Member Functions
static Builder create ()
Private Attributes
int idTypeCase_ = 0
java.lang.Object idType_
int bitField0_
Geobuf.Data.Geometry geometry_ = Geobuf.Data.Geometry.getDefaultInstance()
java.util.List< Geobuf.Data.Value > values_
java.util.List< java.lang.Integer > properties_ = java.util.Collections.emptyList()
java.util.List< java.lang.Integer > customProperties_ = java.util.Collections.emptyList()
Detailed Description
Protobuf type.
Data.Feature
Constructor & Destructor Documentation
Builder()
Builder () private
{
           maybeForceBuilderInitialization();
         }
Member Function Documentation
addAllCustomProperties()
Builder addAllCustomProperties (java.lang.Iterable<? extends java.lang.Integer > values)
repeated uint32 custom_properties = 15 [packed = true];
arbitrary properties
{
           ensureCustomPropertiesIsMutable();
           com.google.protobuf.AbstractMessageLite.Builder.addAll(
               values, customProperties_);
           return this;
         }
addAllProperties()
Builder addAllProperties (java.lang.Iterable<? extends java.lang.Integer > values)
repeated uint32 properties = 14 [packed = true];
pairs of key/value indexes
{
           ensurePropertiesIsMutable();
           com.google.protobuf.AbstractMessageLite.Builder.addAll(
               values, properties_);
           return this;
         }
addAllValues()
Builder addAllValues (java.lang.Iterable<? extends Geobuf.Data.Value > values)
repeated .Data.Value values = 13;
unique values
{
           ensureValuesIsMutable();
           com.google.protobuf.AbstractMessageLite.Builder.addAll(
               values, values_);
           return this;
         }
addCustomProperties()
Builder addCustomProperties (int value)
repeated uint32 custom_properties = 15 [packed = true];
arbitrary properties
{
           ensureCustomPropertiesIsMutable();
           customProperties_.add(value);
           return this;
         }
addProperties()
Builder addProperties (int value)
repeated uint32 properties = 14 [packed = true];
pairs of key/value indexes
{
           ensurePropertiesIsMutable();
           properties_.add(value);
           return this;
         }
addValues() [1/4]
Builder addValues (Geobuf.Data.Value value)
repeated .Data.Value values = 13;
unique values
{
           if (value == null) {
             throw new NullPointerException();
           }
           ensureValuesIsMutable();
           values_.add(value);
           return this;
         }
addValues() [2/4]
Builder addValues (int index, Geobuf.Data.Value value)
repeated .Data.Value values = 13;
unique values
{
           if (value == null) {
             throw new NullPointerException();
           }
           ensureValuesIsMutable();
           values_.add(index, value);
           return this;
         }
addValues() [3/4]
Builder addValues (Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
unique values
{
           ensureValuesIsMutable();
           values_.add(builderForValue.build());
           return this;
         }
addValues() [4/4]
Builder addValues (int index, Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
unique values
{
           ensureValuesIsMutable();
           values_.add(index, builderForValue.build());
           return this;
         }
build()
Geobuf.Data.Feature build ()
Referenced by Geobuf.Data.Feature.Builder.setGeometry().
{
           Geobuf.Data.Feature result = buildPartial();
           if (!result.isInitialized()) {
             throw newUninitializedMessageException(result);
           }
           return result;
         }
buildPartial()
Geobuf.Data.Feature buildPartial ()
References Geobuf.Data.Feature.geometry_.
Referenced by Geobuf.Data.Data(), and Geobuf.Data.Builder.mergeFeature().
{
           Geobuf.Data.Feature result = new Geobuf.Data.Feature(this);
           int from_bitField0_ = bitField0_;
           int to_bitField0_ = 0;
           if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
             to_bitField0_ |= 0x00000001;
           }
           result.geometry_ = geometry_;
           if (idTypeCase_ == 11) {
             result.idType_ = idType_;
           }
           if (idTypeCase_ == 12) {
             result.idType_ = idType_;
           }
           if (((bitField0_ & 0x00000008) == 0x00000008)) {
             values_ = java.util.Collections.unmodifiableList(values_);
             bitField0_ = (bitField0_ & ~0x00000008);
           }
           result.values_ = values_;
           if (((bitField0_ & 0x00000010) == 0x00000010)) {
             properties_ = java.util.Collections.unmodifiableList(properties_);
             bitField0_ = (bitField0_ & ~0x00000010);
           }
           result.properties_ = properties_;
           if (((bitField0_ & 0x00000020) == 0x00000020)) {
             customProperties_ = java.util.Collections.unmodifiableList(customProperties_);
             bitField0_ = (bitField0_ & ~0x00000020);
           }
           result.customProperties_ = customProperties_;
           result.bitField0_ = to_bitField0_;
           result.idTypeCase_ = idTypeCase_;
           return result;
         }
clear()
Builder clear ()
References Geobuf.Data.Feature.Builder.clear(), and Geobuf.Data.Geometry.getDefaultInstance().
Referenced by Geobuf.Data.Feature.Builder.clear().
{
           super.clear();
           geometry_ = Geobuf.Data.Geometry.getDefaultInstance();
           bitField0_ = (bitField0_ & ~0x00000001);
           values_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000008);
           properties_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000010);
           customProperties_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000020);
           idTypeCase_ = 0;
           idType_ = null;
           return this;
         }
clearCustomProperties()
Builder clearCustomProperties ()
repeated uint32 custom_properties = 15 [packed = true];
arbitrary properties
References Geobuf.Data.Feature.initFields().
{
           customProperties_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000020);
           return this;
         }
clearGeometry()
Builder clearGeometry ()
required .Data.Geometry geometry = 1;
References Geobuf.Data.Geometry.getDefaultInstance().
{
           geometry_ = Geobuf.Data.Geometry.getDefaultInstance();
           bitField0_ = (bitField0_ & ~0x00000001);
           return this;
         }
clearId()
Builder clearId ()
optional string id = 11;
{
           if (idTypeCase_ == 11) {
             idTypeCase_ = 0;
             idType_ = null;
           }
           return this;
         }
clearIdType()
Builder clearIdType ()
{
           idTypeCase_ = 0;
           idType_ = null;
           return this;
         }
clearIntId()
Builder clearIntId ()
optional sint64 int_id = 12;
{
           if (idTypeCase_ == 12) {
             idTypeCase_ = 0;
             idType_ = null;
           }
           return this;
         }
clearProperties()
Builder clearProperties ()
repeated uint32 properties = 14 [packed = true];
pairs of key/value indexes
{
           properties_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000010);
           return this;
         }
clearValues()
Builder clearValues ()
repeated .Data.Value values = 13;
unique values
{
           values_ = java.util.Collections.emptyList();
           bitField0_ = (bitField0_ & ~0x00000008);
           return this;
         }
clone()
Builder clone ()
References Geobuf.Data.Feature.Builder.mergeFrom().
{
           return create().mergeFrom(buildPartial());
         }
create()
static Builder create () static private
Referenced by Geobuf.Data.Feature.newBuilder().
{
           return new Builder();
         }
ensureCustomPropertiesIsMutable()
void ensureCustomPropertiesIsMutable () private
{
           if (!((bitField0_ & 0x00000020) == 0x00000020)) {
             customProperties_ = new java.util.ArrayList<java.lang.Integer>(customProperties_);
             bitField0_ |= 0x00000020;
            }
         }
ensurePropertiesIsMutable()
void ensurePropertiesIsMutable () private
{
           if (!((bitField0_ & 0x00000010) == 0x00000010)) {
             properties_ = new java.util.ArrayList<java.lang.Integer>(properties_);
             bitField0_ |= 0x00000010;
            }
         }
ensureValuesIsMutable()
void ensureValuesIsMutable () private
{
           if (!((bitField0_ & 0x00000008) == 0x00000008)) {
             values_ = new java.util.ArrayList<Geobuf.Data.Value>(values_);
             bitField0_ |= 0x00000008;
            }
         }
getCustomProperties()
int getCustomProperties (int index)
repeated uint32 custom_properties = 15 [packed = true];
arbitrary properties
Implements Geobuf.Data.FeatureOrBuilder.
{
           return customProperties_.get(index);
         }
getCustomPropertiesCount()
int getCustomPropertiesCount ()
repeated uint32 custom_properties = 15 [packed = true];
arbitrary properties
Implements Geobuf.Data.FeatureOrBuilder.
{
           return customProperties_.size();
         }
getCustomPropertiesList()
java.util.List<java.lang.Integer> getCustomPropertiesList ()
repeated uint32 custom_properties = 15 [packed = true];
arbitrary properties
Implements Geobuf.Data.FeatureOrBuilder.
{
           return java.util.Collections.unmodifiableList(customProperties_);
         }
getDefaultInstanceForType()
Geobuf.Data.Feature getDefaultInstanceForType ()
References Geobuf.Data.Feature.getDefaultInstance().
{
           return Geobuf.Data.Feature.getDefaultInstance();
         }
getGeometry()
Geobuf.Data.Geometry getGeometry ()
required .Data.Geometry geometry = 1;
Implements Geobuf.Data.FeatureOrBuilder.
{
           return geometry_;
         }
getId()
java.lang.String getId ()
optional string id = 11;
Implements Geobuf.Data.FeatureOrBuilder.
{
           java.lang.Object ref = "";
           if (idTypeCase_ == 11) {
             ref = idType_;
           }
           if (!(ref instanceof java.lang.String)) {
             com.google.protobuf.ByteString bs =
                 (com.google.protobuf.ByteString) ref;
             java.lang.String s = bs.toStringUtf8();
             if (idTypeCase_ == 11) {
               if (bs.isValidUtf8()) {
                 idType_ = s;
               }
             }
             return s;
           } else {
             return (java.lang.String) ref;
           }
         }
getIdBytes()
com.google.protobuf.ByteString getIdBytes ()
optional string id = 11;
Implements Geobuf.Data.FeatureOrBuilder.
{
           java.lang.Object ref = "";
           if (idTypeCase_ == 11) {
             ref = idType_;
           }
           if (ref instanceof String) {
             com.google.protobuf.ByteString b =
                 com.google.protobuf.ByteString.copyFromUtf8(
                     (java.lang.String) ref);
             if (idTypeCase_ == 11) {
               idType_ = b;
             }
             return b;
           } else {
             return (com.google.protobuf.ByteString) ref;
           }
         }
getIdTypeCase()
IdTypeCase getIdTypeCase ()
References Geobuf.Data.Feature.IdTypeCase.valueOf().
{
           return IdTypeCase.valueOf(
               idTypeCase_);
         }
getIntId()
long getIntId ()
optional sint64 int_id = 12;
Implements Geobuf.Data.FeatureOrBuilder.
{
           if (idTypeCase_ == 12) {
             return (java.lang.Long) idType_;
           }
           return 0L;
         }
getProperties()
int getProperties (int index)
repeated uint32 properties = 14 [packed = true];
pairs of key/value indexes
Implements Geobuf.Data.FeatureOrBuilder.
{
           return properties_.get(index);
         }
getPropertiesCount()
int getPropertiesCount ()
repeated uint32 properties = 14 [packed = true];
pairs of key/value indexes
Implements Geobuf.Data.FeatureOrBuilder.
{
           return properties_.size();
         }
getPropertiesList()
java.util.List<java.lang.Integer> getPropertiesList ()
repeated uint32 properties = 14 [packed = true];
pairs of key/value indexes
Implements Geobuf.Data.FeatureOrBuilder.
{
           return java.util.Collections.unmodifiableList(properties_);
         }
getValues()
Geobuf.Data.Value getValues (int index)
repeated .Data.Value values = 13;
unique values
Implements Geobuf.Data.FeatureOrBuilder.
{
           return values_.get(index);
         }
getValuesCount()
int getValuesCount ()
repeated .Data.Value values = 13;
unique values
Implements Geobuf.Data.FeatureOrBuilder.
{
           return values_.size();
         }
getValuesList()
java.util.List<Geobuf.Data.Value> getValuesList ()
repeated .Data.Value values = 13;
unique values
Implements Geobuf.Data.FeatureOrBuilder.
{
           return java.util.Collections.unmodifiableList(values_);
         }
hasGeometry()
boolean hasGeometry ()
required .Data.Geometry geometry = 1;
Implements Geobuf.Data.FeatureOrBuilder.
{
           return ((bitField0_ & 0x00000001) == 0x00000001);
         }
hasId()
boolean hasId ()
optional string id = 11;
Implements Geobuf.Data.FeatureOrBuilder.
{
           return idTypeCase_ == 11;
         }
hasIntId()
boolean hasIntId ()
optional sint64 int_id = 12;
Implements Geobuf.Data.FeatureOrBuilder.
{
           return idTypeCase_ == 12;
         }
isInitialized()
final boolean isInitialized ()
References Geobuf.DataOrBuilder.getGeometry(), and Geobuf.DataOrBuilder.hasGeometry().
{
           if (!hasGeometry()) {
             return false;
           }
           if (!getGeometry().isInitialized()) {
             return false;
           }
           return true;
         }
maybeForceBuilderInitialization()
void maybeForceBuilderInitialization () private
{
         }
mergeFrom() [1/2]
Builder mergeFrom (Geobuf.Data.Feature other)
References Geobuf.Data.Feature.getDefaultInstance(), and Geobuf.Data.Feature.Builder.values_.
Referenced by Geobuf.Data.Feature.Builder.clone(), Geobuf.Data.Data(), Geobuf.Data.Builder.mergeFeature(), and Geobuf.Data.Feature.newBuilder().
{
           if (other == Geobuf.Data.Feature.getDefaultInstance()) return this;
           if (other.hasGeometry()) {
             mergeGeometry(other.getGeometry());
           }
           if (!other.values_.isEmpty()) {
             if (values_.isEmpty()) {
               values_ = other.values_;
               bitField0_ = (bitField0_ & ~0x00000008);
             } else {
               ensureValuesIsMutable();
               values_.addAll(other.values_);
             }
           }
           if (!other.properties_.isEmpty()) {
             if (properties_.isEmpty()) {
               properties_ = other.properties_;
               bitField0_ = (bitField0_ & ~0x00000010);
             } else {
               ensurePropertiesIsMutable();
               properties_.addAll(other.properties_);
             }
           }
           if (!other.customProperties_.isEmpty()) {
             if (customProperties_.isEmpty()) {
               customProperties_ = other.customProperties_;
               bitField0_ = (bitField0_ & ~0x00000020);
             } else {
               ensureCustomPropertiesIsMutable();
               customProperties_.addAll(other.customProperties_);
             }
           }
           switch (other.getIdTypeCase()) {
             case ID: {
               idTypeCase_ = 11;
               idType_ = other.idType_;
               break;
             }
             case INT_ID: {
               setIntId(other.getIntId());
               break;
             }
             case IDTYPE_NOT_SET: {
               break;
             }
           }
           setUnknownFields(
               getUnknownFields().concat(other.unknownFields));
           return this;
         }
mergeFrom() [2/2]
Builder mergeFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
{
           Geobuf.Data.Feature parsedMessage = null;
           try {
             parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
           } catch (com.google.protobuf.InvalidProtocolBufferException e) {
             parsedMessage = (Geobuf.Data.Feature) e.getUnfinishedMessage();
             throw e;
           } finally {
             if (parsedMessage != null) {
               mergeFrom(parsedMessage);
             }
           }
           return this;
         }
mergeGeometry()
Builder mergeGeometry (Geobuf.Data.Geometry value)
required .Data.Geometry geometry = 1;
References Geobuf.Data.Geometry.Builder.buildPartial(), Geobuf.Data.Geometry.getDefaultInstance(), Geobuf.Data.Geometry.Builder.mergeFrom(), and Geobuf.Data.Geometry.newBuilder().
{
           if (((bitField0_ & 0x00000001) == 0x00000001) &&
               geometry_ != Geobuf.Data.Geometry.getDefaultInstance()) {
             geometry_ =
               Geobuf.Data.Geometry.newBuilder(geometry_).mergeFrom(value).buildPartial();
           } else {
             geometry_ = value;
           }
           bitField0_ |= 0x00000001;
           return this;
         }
removeValues()
Builder removeValues (int index)
repeated .Data.Value values = 13;
unique values
{
           ensureValuesIsMutable();
           values_.remove(index);
           return this;
         }
setCustomProperties()
Builder setCustomProperties (int index, int value)
repeated uint32 custom_properties = 15 [packed = true];
arbitrary properties
{
           ensureCustomPropertiesIsMutable();
           customProperties_.set(index, value);
           return this;
         }
setGeometry() [1/2]
Builder setGeometry (Geobuf.Data.Geometry value)
required .Data.Geometry geometry = 1;
Referenced by GeobufEncoder.makeFeature().
{
           if (value == null) {
             throw new NullPointerException();
           }
           geometry_ = value;
           bitField0_ |= 0x00000001;
           return this;
         }
setGeometry() [2/2]
Builder setGeometry (Geobuf.Data.Geometry.Builder builderForValue)
required .Data.Geometry geometry = 1;
References Geobuf.Data.Feature.Builder.build().
{
           geometry_ = builderForValue.build();
           bitField0_ |= 0x00000001;
           return this;
         }
setId()
Builder setId (java.lang.String value)
optional string id = 11;
{
           if (value == null) {
     throw new NullPointerException();
   }
   idTypeCase_ = 11;
           idType_ = value;
           return this;
         }
setIdBytes()
Builder setIdBytes (com.google.protobuf.ByteString value)
optional string id = 11;
{
           if (value == null) {
     throw new NullPointerException();
   }
   idTypeCase_ = 11;
           idType_ = value;
           return this;
         }
setIntId()
Builder setIntId (long value)
optional sint64 int_id = 12;
{
           idTypeCase_ = 12;
           idType_ = value;
           return this;
         }
setProperties()
Builder setProperties (int index, int value)
repeated uint32 properties = 14 [packed = true];
pairs of key/value indexes
{
           ensurePropertiesIsMutable();
           properties_.set(index, value);
           return this;
         }
setValues() [1/2]
Builder setValues (int index, Geobuf.Data.Value value)
repeated .Data.Value values = 13;
unique values
{
           if (value == null) {
             throw new NullPointerException();
           }
           ensureValuesIsMutable();
           values_.set(index, value);
           return this;
         }
setValues() [2/2]
Builder setValues (int index, Geobuf.Data.Value.Builder builderForValue)
repeated .Data.Value values = 13;
unique values
{
           ensureValuesIsMutable();
           values_.set(index, builderForValue.build());
           return this;
         }
Member Data Documentation
bitField0_
int bitField0_ private
customProperties_
java.util.List<java.lang.Integer> customProperties_ = java.util.Collections.emptyList() private
geometry_
Geobuf.Data.Geometry geometry_ = Geobuf.Data.Geometry.getDefaultInstance() private
idType_
java.lang.Object idType_ private
idTypeCase_
int idTypeCase_ = 0 private
properties_
java.util.List<java.lang.Integer> properties_ = java.util.Collections.emptyList() private
values_
java.util.List<Geobuf.Data.Value> values_ private
Initial value:
=
          java.util.Collections.emptyList()
Referenced by Geobuf.Data.Feature.Builder.mergeFrom().