jena-geo: GridCoverage2D Class Reference
GridCoverage2D Class Reference
Basic access to grid data values backed by a two-dimensional RenderedImage.
Public Member Functions
GridCoverage2D (GridGeometry domain, final Collection<? extends SampleDimension > range, RenderedImage data)
Constructs a grid coverage using the specified domain, range and data.
GridCoverage2D (final Envelope domain, final Collection<? extends SampleDimension > range, final RenderedImage data)
Constructs a grid coverage using the specified envelope, range and data.
GridGeometry getGridGeometry2D ()
Returns the two-dimensional part of this grid geometry.
synchronized GridCoverage forConvertedValues (final boolean converted)
Returns a grid coverage that contains real values or sample values, depending if.
double [] evaluate (final DirectPosition point, final double[] buffer) throws CannotEvaluateException
Returns a sequence of double values for a given point in the coverage.
RenderedImage render (final GridExtent sliceExtent) throws CannotEvaluateException
Returns a grid data region as a rendered image.
CoordinateReferenceSystem getCoordinateReferenceSystem ()
Returns the coordinate reference system to which the values in grid domain are referenced.
GridGeometry getGridGeometry ()
Returns information about the <cite>domain</cite> of this grid coverage.
List< SampleDimension > getSampleDimensions ()
Returns information about the <cite>range</cite> of this grid coverage.
FractionalGridCoordinates toGridCoordinates (final DirectPosition point) throws TransformException
Converts the specified geospatial position to grid coordinates.
String toString ()
Returns a string representation of this grid coverage for debugging purpose.
TreeTable toTree (final Locale locale, final int bitmask)
Returns a tree representation of some elements of this grid coverage.
Package Functions
void appendDataLayout (final TreeTable.Node root, final Vocabulary vocabulary, final TableColumn< CharSequence > column)
Appends a "data layout" branch (if it exists) to the tree representation of this coverage.
final NumberRange<?> [] getRanges ()
Returns the range of values in each sample dimension, or.
final ColorModel createColorModel (final int visibleBand, final int dataType)
Creates a color model for the expected range of sample values.
final GridCoverage getView (final boolean converted)
Returns the converted or package view, or.
final void setView (final boolean converted, final GridCoverage view)
Sets the converted or package view.
Static Package Functions
static double [] evaluate (final RenderedImage data, final int x, final int y, final double[] buffer)
Gets sample values from the given image at the given index.
Package Attributes
final long gridToImageY
final int yDimension
final GridGeometry gridGeometry
The grid extent, coordinate reference system (CRS) and conversion from cell indices to CRS.
transient GridCoverage convertedView
Private Member Functions
GridCoverage2D (final GridCoverage2D source, final List< SampleDimension > range, final MathTransform1D[] converters, final boolean isConverted)
Creates a new grid coverage for the conversion of specified source coverage.
Static Private Member Functions
static RenderedImage unwrapIfSameSize (RenderedImage data)
Returns the wrapped image if the only difference is a translation, or.
static GridGeometry addExtentIfAbsent (GridGeometry domain, final RenderedImage data)
If the given domain does not have a GridExtent, creates a new grid geometry with an extent computed from the given image.
static GridGeometry createGridGeometry (final RenderedImage data, final Envelope envelope)
Creates a grid geometry from an envelope.
static GridExtent createExtent (final int dimension, final RenderedImage data, final CoordinateReferenceSystem crs)
Creates a grid extent with the low and high coordinates of the given image.
static Collection<? extends SampleDimension > defaultIfAbsent (Collection<? extends SampleDimension > range, final RenderedImage data)
If the sample dimensions are null, creates default sample dimensions with "gray", "red, green, blue" or "cyan, magenta, yellow" names.
static void verifyBandCount (final Collection<? extends SampleDimension > range, final RenderedImage data)
Verifies that the number of bands in the image is equal to the number of sample dimensions.
Private Attributes
final RenderedImage data
The sample values stored as a.
final long gridToImageX
Offsets to apply for converting grid coverage coordinates to image pixel coordinates.
final int xDimension
Indices of extent dimensions corresponding to image x and y coordinates.
final AtomicReference< GridGeometry > gridGeometry2D
The two-dimensional components of the coordinate reference system and "grid to CRS" transform.
Static Private Attributes
static final int MIN_DIMENSION = 2
Minimal number of dimension for this coverage.
Detailed Description
Basic access to grid data values backed by a two-dimensional RenderedImage.
While images are two-dimensional, the coverage envelope may have more dimensions. In other words the rendered image can be a two-dimensional slice in a n-dimensional space. The only restriction is that the GridGeometry::getExtent() grid extent} has a GridExtent::getSize(int) size} equals to 1 in all dimensions except two of them.
Example: a remote sensing image may be valid only over some time range (the temporal period of the satellite passing over observed area). Envelopes for such grid coverage can have three dimensions: the two usual ones (horizontal extent along x and y), and a third dimension for start time and end time (temporal extent along t). This "two-dimensional" grid coverage can have any number of columns along x axis and any number of rows along y axis, but only one plan along t axis. This single plan can have a lower bound (the start time) and an upper bound (the end time).
Image size and location
The RenderedImage::getWidth() image width} and RenderedImage::getHeight() height} must be equal to the GridExtent::getSize(int) grid extent size} in the two dimensions of the slice. However the image origin (RenderedImage::getMinX() minimal x} and RenderedImage::getMinY() y} values) does not need to be equal to the GridExtent::getLow(int) grid extent low values}; a translation will be applied as needed.
Image bands
Each band in an image is represented as a SampleDimension.
Author
Martin Desruisseaux (Geomatys)
Johann Sorel (Geomatys)
Version
1.1
Since
1.1
Constructor & Destructor Documentation
GridCoverage2D() [1/3]
GridCoverage2D (final GridCoverage2D source, final List< SampleDimension > range, final MathTransform1D [] converters, final boolean isConverted) private
Creates a new grid coverage for the conversion of specified source coverage.
Parameters
source the coverage containing source values.
range the sample dimensions to assign to the converted grid coverage.
converters conversion from source to converted coverage, one transform per band.
isConverted whether this grid coverage is for converted or packed values.
References GridCoverage.createColorModel(), ConvertedGridCoverage.getDataType(), GridCoverage.gridGeometry, GridCoverage2D.gridGeometry2D, GridCoverage2D.gridToImageX, GridCoverage2D.gridToImageY, ConvertedGridCoverage.VISIBLE_BAND, GridCoverage2D.xDimension, and GridCoverage2D.yDimension.
Referenced by GridCoverage2D.forConvertedValues().
     {
         super(source.gridGeometry, range);
         final int dataType = ConvertedGridCoverage.getDataType(range, isConverted);
         final ColorModel colorModel = createColorModel(ConvertedGridCoverage.VISIBLE_BAND, dataType);
         data=null;
         //data           = (RenderedImage) BandedSampleConverter.create(source.data, null, dataType, colorModel, getRanges(), converters);
         gridToImageX   = source.gridToImageX;
         gridToImageY   = source.gridToImageY;
         xDimension     = source.xDimension;
         yDimension     = source.yDimension;
         gridGeometry2D = source.gridGeometry2D;
     }
GridCoverage2D() [2/3]
GridCoverage2D (GridGeometry domain, final Collection<? extends SampleDimension > range, RenderedImage data)
Constructs a grid coverage using the specified domain, range and data.
If the given domain does not have an extent, then a default GridExtent will be computed from given image. Otherwise the RenderedImage::getWidth() image width} and RenderedImage::getHeight() height} must be equal to the GridExtent::getSize(int) grid extent size} in the two dimensions of the slice.
The image origin (RenderedImage::getMinX() minimal x} and RenderedImage::getMinY() y} values) can be anywhere; it does not need to be the same as the GridExtent::getLow(int) grid extent low values}. Translations will be applied automatically when needed.
This constructor throws an IllegalGridGeometryException if one of the following errors is detected in the
domain
argument:
The given domain has less than two dimensions.
The given domain has more than two dimensions having an GridExtent::getSize(int) extent size} greater than 1.
The extent size along x and y axes is not equal to the image width and height.
Parameters
domain the grid extent (may be absent), CRS and conversion from cell indices. If
null
a default grid geometry will be created with no CRS and identity conversion.
range sample dimensions for each image band. The size of this list must be equal to the number of bands. If
null
, default sample dimensions will be created with no transfer function.
data the sample values as a RenderedImage, with one band for each sample dimension.
Exceptions
IllegalGridGeometryException if the
domain
does not met the above-documented conditions.
IllegalArgumentException if the image number of bands is not the same than the number of sample dimensions.
ArithmeticException if the distance between grid location and image location exceeds the
long
capacity.
References GridCoverage2D.addExtentIfAbsent(), GridCoverage2D.data, GridCoverage2D.defaultIfAbsent(), GridExtent.getLow(), GridExtent.getSize(), GridExtent.getSubspaceDimensions(), GridCoverage2D.MIN_DIMENSION, GridCoverage2D.unwrapIfSameSize(), and GridCoverage2D.verifyBandCount().
{
         super(domain = addExtentIfAbsent(domain, data = unwrapIfSameSize(data)), defaultIfAbsent(range, data));
         this.data = data;           // Non-null verified by addExtentIfAbsent(…, data).
         /*
          * Find indices of the two dimensions of the slice. Those dimensions are usually 0 for x and 1 for y,
          * but not necessarily. A two dimensional CRS will be extracted for those dimensions later if needed.
          */
         final GridExtent extent = domain.getExtent();
         final int[] imageAxes;
         try {
             imageAxes = extent.getSubspaceDimensions(MIN_DIMENSION);
         } catch (CannotEvaluateException e) {
             throw new IllegalGridGeometryException(e.getMessage(), e);
         }
         xDimension   = imageAxes[0];
         yDimension   = imageAxes[1];
         gridToImageX = subtractExact(data.getMinX(), extent.getLow(xDimension));
         gridToImageY = subtractExact(data.getMinY(), extent.getLow(yDimension));
         /*
          * Verify that the domain is consistent with image size.
          * We do not verify image location; it can be anywhere.
          */
         for (int i=0; i<MIN_DIMENSION; i++) {
             final int imageSize = (i == 0) ? data.getWidth() : data.getHeight();
             final long gridSize = extent.getSize(imageAxes[i]);
             if (imageSize != gridSize) {
                 //throw new IllegalGridGeometryException(Resources.format(Resources.Keys.MismatchedImageSize_3, i, imageSize, gridSize));
             }
         }
         verifyBandCount(range, data);
         gridGeometry2D = new AtomicReference<>();
     }
GridCoverage2D() [3/3]
GridCoverage2D (final Envelope domain, final Collection<? extends SampleDimension > range, final RenderedImage data)
Constructs a grid coverage using the specified envelope, range and data.
This convenience constructor computes a GridGeometry from the given envelope and image size. This constructor assumes that all grid axes are in the same order than CRS axes and no axis is flipped. This straightforward approach often results in the y axis to be oriented toward up, not down as commonly expected with rendered images.
This constructor is generally not recommended because of the assumptions on axis order and directions. For better control, use the constructor expecting a GridGeometry argument instead. This constructor is provided mostly as a convenience for testing purposes.
Parameters
domain the envelope encompassing all images, from upper-left corner to lower-right corner. If
null
a default grid geometry will be created with no CRS and identity conversion.
range sample dimensions for each image band. The size of this list must be equal to the number of bands. If
null
, default sample dimensions will be created with no transfer function.
data the sample values as a RenderedImage, with one band for each sample dimension.
Exceptions
IllegalArgumentException if the image number of bands is not the same than the number of sample dimensions.
See also
GridGeometry::GridGeometry(GridExtent, Envelope)
References GridCoverage2D.createGridGeometry(), GridCoverage2D.data, GridCoverage2D.defaultIfAbsent(), GridCoverage2D.gridGeometry2D, GridCoverage2D.gridToImageX, GridCoverage2D.gridToImageY, GridCoverage2D.verifyBandCount(), GridCoverage2D.xDimension, and GridCoverage2D.yDimension.
{
         super(createGridGeometry(data, domain), defaultIfAbsent(range, data));
         this.data = data;   // Non-null verified by createGridGeometry(…, data).
         xDimension   = 0;
         yDimension   = 1;
         gridToImageX = 0;
         gridToImageY = 0;
         verifyBandCount(range, data);
         gridGeometry2D = new AtomicReference<>();
     }
Member Function Documentation
addExtentIfAbsent()
static GridGeometry addExtentIfAbsent (GridGeometry domain, final RenderedImage data) static private
If the given domain does not have a GridExtent, creates a new grid geometry with an extent computed from the given image.
The new grid will start at the same location than the image and will have the same size.
This static method is a workaround for RFE #4093999 ("Relax constraint on placement of this()/super() call in constructors").
References GridCoverage2D.createExtent(), and GridCoverage2D.MIN_DIMENSION.
Referenced by GridCoverage2D.GridCoverage2D().
{
         ArgumentChecks.ensureNonNull("data", data);
         if (domain == null) {
             GridExtent extent = new GridExtent(data.getMinX(), data.getMinY(), data.getWidth(), data.getHeight());
             domain = new GridGeometry(extent, PixelInCell.CELL_CENTER, null, null);
         } else if (!domain.isDefined(GridGeometry.EXTENT)) {
             final int dimension = domain.getDimension();
             if (dimension >= MIN_DIMENSION) {
                 CoordinateReferenceSystem crs = null;
                 if (domain.isDefined(GridGeometry.CRS)) {
                     crs = domain.getCoordinateReferenceSystem();
                 }
                 final GridExtent extent = createExtent(dimension, data, crs);
                 if (domain.isDefined(GridGeometry.GRID_TO_CRS)) try {
                     domain = new GridGeometry(domain, extent, null);
                 } catch (TransformException e) {
                     throw new IllegalGridGeometryException(e);                  // Should never happen.
                 } else {
                     domain = new GridGeometry(extent, domain.envelope);
                 }
             }
         }
         return domain;
     }
appendDataLayout()
void appendDataLayout (final TreeTable.Node root, final Vocabulary vocabulary, final TableColumn< CharSequence > column) package
Appends a "data layout" branch (if it exists) to the tree representation of this coverage.
That branch will be inserted between "coverage domain" and "sample dimensions" branches.
Parameters
root root of the tree where to add a branch.
vocabulary localized resources for vocabulary.
column the single column where to write texts.
References GridCoverage2D.data, ImageUtilities.getDataTypeName(), and ImageUtilities.getTransparencyDescription().
{
         final TreeTable.Node branch = root.newChild();
         branch.setValue(column, vocabulary.getString(Vocabulary.Keys.ImageLayout));
         final NumberFormat nf = NumberFormat.getIntegerInstance(vocabulary.getLocale());
         final FieldPosition pos = new FieldPosition(0);
         final StringBuffer buffer = new StringBuffer();
 write:  for (int item=0; ; item++) try {
             switch (item) {
                 case 0: {
                     vocabulary.appendLabel(Vocabulary.Keys.Origin, buffer);
                     nf.format(data.getMinX(), buffer.append(' '),  pos);
                     nf.format(data.getMinY(), buffer.append(", "), pos);
                     break;
                 }
                 case 1: {
                     final int tx = data.getTileWidth();
                     final int ty = data.getTileHeight();
                     if (tx == data.getWidth() && ty == data.getHeight()) continue;
                     vocabulary.appendLabel(Vocabulary.Keys.TileSize, buffer);
                     nf.format(tx, buffer.append( ' ' ), pos);
                     nf.format(ty, buffer.append(" × "), pos);
                     break;
                 }
                 case 2: {
                     final String type = ImageUtilities.getDataTypeName(data.getSampleModel());
                     if (type == null) continue;
                     vocabulary.appendLabel(Vocabulary.Keys.DataType, buffer);
                     buffer.append(' ').append(type);
                     break;
                 }
                 case 3: {
                     final short t = ImageUtilities.getTransparencyDescription(data.getColorModel());
                     if (t != 0) {
                         final String desc = Resources.forLocale(vocabulary.getLocale()).getString(t);
                         branch.newChild().setValue(column, desc);
                     }
                     continue;
                 }
                 default: break write;
             }
             branch.newChild().setValue(column, buffer.toString());
             buffer.setLength(0);
         } catch (IOException e) {
             throw new UncheckedIOException(e);      // Should never happen since we are writing to StringBuilder.
         }
     }
createColorModel()
final ColorModel createColorModel (final int visibleBand, final int dataType) package inherited
Creates a color model for the expected range of sample values.
Parameters
visibleBand the band to be made visible (usually 0). All other bands (if any) will be ignored.
dataType the color model type as one java.awt.image.DataBuffer constants.
Returns
proposed color model, or
null
if none.
References ColorModelFactory.createColorModel(), and ColorModelFactory.GRAYSCALE.
Referenced by GridCoverage2D.GridCoverage2D(), and ConvertedGridCoverage.render().
{
         return ColorModelFactory.createColorModel(sampleDimensions, visibleBand, dataType, ColorModelFactory.GRAYSCALE);
     }
createExtent()
static GridExtent createExtent (final int dimension, final RenderedImage data, final CoordinateReferenceSystem crs) static private
Creates a grid extent with the low and high coordinates of the given image.
The coordinate reference system is used for extracting grid axis names, in particular the DimensionNameType#VERTICAL and DimensionNameType#TIME dimensions. The DimensionNameType#COLUMN and DimensionNameType#ROW dimensions can not be inferred from CRS analysis; they are added from knowledge that we have an image.
Parameters
dimension number of dimensions.
data the image for which to create a grid extent.
crs coordinate reference system, or
null
if none.
References GridExtent.typeFromAxes().
Referenced by GridCoverage2D.addExtentIfAbsent(), and GridCoverage2D.createGridGeometry().
{
         final long[] low  = new long[dimension];
         final long[] high = new long[dimension];
         low [0] = data.getMinX();
         low [1] = data.getMinY();
         high[0] = data.getWidth()  + low[0] - 1;        // Inclusive.
         high[1] = data.getHeight() + low[1] - 1;
         DimensionNameType[] axisTypes = GridExtent.typeFromAxes(crs, dimension);
         if (axisTypes == null) {
             axisTypes = new DimensionNameType[dimension];
         }
         if (!ArraysExt.contains(axisTypes, DimensionNameType.COLUMN)) axisTypes[0] = DimensionNameType.COLUMN;
         if (!ArraysExt.contains(axisTypes, DimensionNameType.ROW))    axisTypes[1] = DimensionNameType.ROW;
         return new GridExtent(axisTypes, low, high, true);
     }
createGridGeometry()
static GridGeometry createGridGeometry (final RenderedImage data, final Envelope envelope) static private
Creates a grid geometry from an envelope.
The grid extent is computed from the image size. This static method is a workaround for RFE #4093999 ("Relax constraint on placement of this()/super() call in constructors").
References GridCoverage2D.createExtent(), GridCoverage2D.data, and GridCoverage2D.MIN_DIMENSION.
Referenced by GridCoverage2D.GridCoverage2D().
{
         ArgumentChecks.ensureNonNull("data", data);
         CoordinateReferenceSystem crs = null;
         int dimension = MIN_DIMENSION;
         if (envelope != null) {
             dimension = envelope.getDimension();
             if (dimension < MIN_DIMENSION) {
                 throw new IllegalGridGeometryException(Resources.format(
                         Resources.Keys.GridEnvelopeMustBeNDimensional_1, MIN_DIMENSION));
             }
             crs = envelope.getCoordinateReferenceSystem();
         }
         return new GridGeometry(createExtent(dimension, data, crs), envelope);
     }
defaultIfAbsent()
static Collection<? extends SampleDimension> defaultIfAbsent (Collection<? extends SampleDimension > range, final RenderedImage data) static private
If the sample dimensions are null, creates default sample dimensions with "gray", "red, green, blue" or "cyan, magenta, yellow" names.
Referenced by GridCoverage2D.GridCoverage2D().
     {
         /*if (range == null) {
             final short[] names = ImageUtilities.bandNames(data);
             final SampleDimension[] sd = new SampleDimension[names.length];
             final NameFactory factory = DefaultFactories.forBuildin(NameFactory.class);
             for (int i=0; i<names.length; i++) {
                 final InternationalString name;
                 final short k = names[0];
                 if (k != 0) {
                     name = Vocabulary.formatInternational(k);
                 } else {
                     name = Vocabulary.formatInternational(Vocabulary.Keys.Band_1, i+1);
                 }
                 sd[i] = new SampleDimension(factory.createLocalName(null, name), null, Collections.emptyList());
             }
             range = Arrays.asList(sd);
         }*/
         return range;
     }
evaluate() [1/2]
static double [] evaluate (final RenderedImage data, final int x, final int y, final double [] buffer) static package inherited
Gets sample values from the given image at the given index.
This method does not verify explicitly if the coordinates are out of bounds; we rely on the checks performed by the image and sample model implementations.
Parameters
data the data from which to get the sample values.
x column index of the value to get.
y row index of the value to get.
buffer an array in which to store values, or
null
to create a new array.
Returns
the
buffer
array, or a newly created array if
buffer
was null.
Exceptions
ArithmeticException if an integer overflow occurred while computing indices.
IndexOutOfBoundsException if a coordinate is out of bounds.
{
         final int tx = Math.toIntExact(Math.floorDiv(x - (long) data.getTileGridXOffset(), data.getTileWidth()));
         final int ty = Math.toIntExact(Math.floorDiv(y - (long) data.getTileGridYOffset(), data.getTileHeight()));
         return data.getTile(tx, ty).getPixel(x, y, buffer);
     }
evaluate() [2/2]
double [] evaluate (final DirectPosition point, final double [] buffer) throws CannotEvaluateException
Returns a sequence of double values for a given point in the coverage.
The CRS of the given point may be any coordinate reference system, or
null
for the same CRS than this coverage. The returned sequence contains a value for each SampleDimension sample dimension}.
Parameters
point the coordinate point where to evaluate.
buffer an array in which to store values, or
null
to create a new array.
Returns
the
buffer
array, or a newly created array if
buffer
was null.
Exceptions
PointOutsideCoverageException if the evaluation failed because the input point has invalid coordinates.
CannotEvaluateException if the values can not be computed at the specified coordinate for another reason.
References GridCoverage2D.data, FractionalGridCoordinates.getCoordinateValue(), GridCoverage.gridGeometry, GridCoverage2D.gridToImageX, GridCoverage2D.gridToImageY, FractionalGridCoordinates.pointOutsideCoverage(), GridCoverage.toGridCoordinates(), GridCoverage2D.xDimension, and GridCoverage2D.yDimension.
{
         try {
             final FractionalGridCoordinates gc = toGridCoordinates(point);
             try {
                 final int x = toIntExact(addExact(gc.getCoordinateValue(xDimension), gridToImageX));
                 final int y = toIntExact(addExact(gc.getCoordinateValue(yDimension), gridToImageY));
                 return evaluate(data, x, y, buffer);
             } catch (ArithmeticException | IndexOutOfBoundsException | DisjointExtentException ex) {
                 throw (PointOutsideCoverageException) new PointOutsideCoverageException(
                         gc.pointOutsideCoverage(gridGeometry.extent), point).initCause(ex);
             }
         } catch (PointOutsideCoverageException ex) {
             ex.setOffendingLocation(point);
             throw ex;
         } catch (RuntimeException | TransformException ex) {
             throw new CannotEvaluateException(ex.getMessage(), ex);
         }
     }
forConvertedValues()
synchronized GridCoverage forConvertedValues (final boolean converted)
Returns a grid coverage that contains real values or sample values, depending if.
converted
is
true
or
false
respectively.
Parameters
converted
References ConvertedGridCoverage.converters, GridCoverage.getSampleDimensions(), GridCoverage.getView(), GridCoverage2D.GridCoverage2D(), and GridCoverage.setView().
{
         GridCoverage2D view = (GridCoverage2D) getView(converted);
         if (view == null) try {
             final List<SampleDimension> sources = getSampleDimensions();
             final List<SampleDimension> targets = new ArrayList<>(sources.size());
             final MathTransform1D[]  converters = ConvertedGridCoverage.converters(sources, targets, converted);
             if (converters != null) {
                 view = new GridCoverage2D(this, targets, converters, converted);
                 view.setView(!converted, this);
             } else {
                 view = this;
             }
             setView(converted, view);
         } catch (NoninvertibleTransformException e) {
             throw new CannotEvaluateException(e.getMessage(), e);
         }
         return view;
     }
getCoordinateReferenceSystem()
CoordinateReferenceSystem getCoordinateReferenceSystem () inherited
Returns the coordinate reference system to which the values in grid domain are referenced.
This is the CRS used when accessing a coverage with the
evaluate(…)
methods. This coordinate reference system is usually different than the coordinate system of the grid. It is the target coordinate reference system of the gridToCRS math transform.
The default implementation delegates to GridGeometry#getCoordinateReferenceSystem().
Returns
the CRS used when accessing a coverage with the
evaluate(…)
methods.
Exceptions
IncompleteGridGeometryException if the grid geometry has no CRS.
Referenced by CoverageJsonWriter.coverageToCovJSON(), and SRID.exec().
{
         return gridGeometry.getCoordinateReferenceSystem();
     }
getGridGeometry()
GridGeometry getGridGeometry () inherited
Returns information about the <cite>domain</cite> of this grid coverage.
Information includes the grid extent, CRS and conversion from cell indices to CRS.
GridGeometry
can also provide derived information like bounding box and resolution.
Returns
grid extent, CRS and conversion from cell indices to CRS.
See also
org.apache.sis.storage.GridCoverageResource::getGridGeometry()
References GridCoverage.gridGeometry.
Referenced by ConvertedGridCoverage.ConvertedGridCoverage(), CoverageJsonWriter.coverageToCovJSON(), TileGridYOffset.exec(), NumXTiles.exec(), MinTileY.exec(), TileHeight.exec(), TileGridXOffset.exec(), NumYTiles.exec(), MinTileX.exec(), TileWidth.exec(), PixelSize.exec(), NotSameAlignmentReason.exec(), TranslateX.exec(), TranslateY.exec(), EqualSRS.exec(), DWithin3D.exec(), SRIDGetAxis1Name.exec(), SRIDGetAxis1Orientation.exec(), SRIDGetAxis2Name.exec(), SRIDGetAxis2Orientation.exec(), SRIDHasFlippedAxis.exec(), EqualNorm.exec(), Crosses.exec(), ScaleX.exec(), Equals.exec(), EqualTopo.exec(), ScaleY.exec(), SkewY.exec(), Difference.exec(), Intersection.exec(), SymDifference.exec(), Or.exec(), Xor.exec(), Add.exec(), Subtract.exec(), Div.exec(), And.exec(), Mult.exec(), AndConst.exec(), AddConst.exec(), OrConst.exec(), XorConst.exec(), Log.exec(), DivConst.exec(), ContainsProperly.exec(), SubtractConst.exec(), MultConst.exec(), Summary.exec(), NearestValue.exec(), SetScale.exec(), Width.exec(), Intersects.exec(), Envelope.exec(), Height.exec(), SkewX.exec(), Overlaps.exec(), Touches.exec(), CoveredBy.exec(), SameAlignment.exec(), Disjoint.exec(), UpperLeftY.exec(), Covers.exec(), Contains.exec(), UpperLeftX.exec(), WorldToRasterCoordX.exec(), RasterToWorldCoordX.exec(), Within.exec(), WorldToRasterCoordY.exec(), RasterToWorldCoordY.exec(), RasterToWorldCoord.exec(), WorldToRasterCoord.exec(), and GridCoverage.toGridCoordinates().
{
         return gridGeometry;
     }
getGridGeometry2D()
GridGeometry getGridGeometry2D ()
Returns the two-dimensional part of this grid geometry.
If the getGridGeometry() complete geometry} is already two-dimensional, then this method returns the same geometry. Otherwise it returns a geometry for the two first axes having a GridExtent::getSize(int) size} greater than 1 in the grid envelope. Note that those axes are guaranteed to appear in the same order than in the complete geometry.
Returns
the two-dimensional part of the grid geometry.
See also
getGridGeometry()
GridGeometry::reduce(int...)
References GridCoverage.gridGeometry, GridCoverage2D.gridGeometry2D, GridCoverage2D.xDimension, and GridCoverage2D.yDimension.
{
         GridGeometry g = gridGeometry2D.get();
         if (g == null) {
             g = gridGeometry.reduce(xDimension, yDimension);
             if (!gridGeometry2D.compareAndSet(null, g)) {
                 GridGeometry other = gridGeometry2D.get();
                 if (other != null) return other;
             }
         }
         return g;
     }
getRanges()
final NumberRange<?> [] getRanges () package inherited
Returns the range of values in each sample dimension, or.
null
if none.
Referenced by ConvertedGridCoverage.render().
{
         NumberRange<?>[] ranges = null;
         for (int i=0; i<sampleDimensions.length; i++) {
             final Optional<NumberRange<?>> r = sampleDimensions[i].getSampleRange();
             if (r.isPresent()) {
                 if (ranges == null) {
                     ranges = new NumberRange<?>[sampleDimensions.length];
                 }
                 ranges[i] = r.get();
             }
         }
         return ranges;
     }
getSampleDimensions()
List<SampleDimension> getSampleDimensions () inherited
Returns information about the <cite>range</cite> of this grid coverage.
Information include names, sample value ranges, fill values and transfer functions for all bands in this grid coverage. The length of the returned list should be equal to the java.awt.image.SampleModel::getNumBands() number of bands} in the rendered image.
Returns
names, value ranges, fill values and transfer functions for all bands in this grid coverage.
See also
org.apache.sis.storage.GridCoverageResource::getSampleDimensions()
Referenced by CoverageJsonWriter.coverageToCovJSON(), ConvertedGridCoverage.create(), SetBandNoDataValue.exec(), NumBands.exec(), Subtract.exec(), And.exec(), Or.exec(), Add.exec(), BandNoDataValue.exec(), Div.exec(), Xor.exec(), BandMetaData.exec(), Mult.exec(), BandPixelType.exec(), DivConst.exec(), AddConst.exec(), Log.exec(), AndConst.exec(), OrConst.exec(), XorConst.exec(), SubtractConst.exec(), MultConst.exec(), IsEmpty.exec(), Summary.exec(), SetScale.exec(), HasNoBand.exec(), and GridCoverage2D.forConvertedValues().
{
         return UnmodifiableArrayList.wrap(sampleDimensions);
     }
getView()
final GridCoverage getView (final boolean converted) package inherited
Returns the converted or package view, or.
null
if not yet computed. It is caller responsibility to ensure that this method is invoked in a synchronized block.
References GridCoverage.convertedView, and GridCoverage.packedView.
Referenced by GridCoverage.forConvertedValues(), and GridCoverage2D.forConvertedValues().
{
         return converted ? convertedView : packedView;
     }
render()
RenderedImage render (final GridExtent sliceExtent) throws CannotEvaluateException
Returns a grid data region as a rendered image.
The
sliceExtent
argument specifies the area of interest and may be
null
for requesting the whole image. The coordinates given by RenderedImage#getMinX() and getMinY() will be the image location relative to the location specified in
sliceExtent
GridExtent::getLow(int) low coordinates} (see super-class javadoc for more discussion). The RenderedImage::getWidth() image width} and RenderedImage::getHeight() height} will be the
sliceExtent
GridExtent::getSize(int) sizes} if this method can honor exactly the request, but this method is free to return a smaller or larger image if doing so reduce the amount of data to create or copy. This implementation returns a view as much as possible, without copying sample values.
Parameters
sliceExtent area of interest, or
null
for the whole image.
Returns
the grid slice as a rendered image. Image location is relative to
sliceExtent
.
Exceptions
DisjointExtentException if the given extent does not intersect this grid coverage.
CannotEvaluateException if this method can not produce the rendered image for another reason.
See also
BufferedImage::getSubimage(int, int, int, int)
References GridCoverage2D.data, GridExtent.getDimension(), GridExtent.getHigh(), GridExtent.getLow(), GridCoverage.gridGeometry, GridCoverage2D.gridToImageX, GridCoverage2D.gridToImageY, ReshapedImage.isIdentity(), ReshapedImage.verify(), GridCoverage2D.xDimension, and GridCoverage2D.yDimension.
{
         if (sliceExtent == null) {
             return data;
         }
         final GridExtent extent = gridGeometry.extent;
         if (extent != null) {
             for (int i = min(sliceExtent.getDimension(), extent.getDimension()); --i >= 0;) {
                 if (i != xDimension && i != yDimension) {
                     if (sliceExtent.getHigh(i) < extent.getLow(i) || sliceExtent.getLow(i) > extent.getHigh(i)) {
                         throw new DisjointExtentException(extent, sliceExtent, i);
                     }
                 }
             }
         }
         try {
             /*
              * Convert the coordinates from this grid coverage coordinate system to the image coordinate system.
              * The coverage coordinates may require 64 bits integers, but after translation the (x,y) coordinates
              * should be in 32 bits integers range. Do not cast to 32 bits now however; this will be done later.
              */
             final long xmin = addExact(sliceExtent.getLow (xDimension), gridToImageX);
             final long ymin = addExact(sliceExtent.getLow (yDimension), gridToImageY);
             final long xmax = addExact(sliceExtent.getHigh(xDimension), gridToImageX);
             final long ymax = addExact(sliceExtent.getHigh(yDimension), gridToImageY);
             /*
              * BufferedImage.getSubimage() returns a new image with upper-left coordinate at (0,0),
              * which is exactly what this method contract is requesting provided that the requested
              * upper-left point is inside the image.
              */
             if (data instanceof BufferedImage) {
                 final long ix = data.getMinX();
                 final long iy = data.getMinY();
                 if (xmin >= ix && ymin >= iy) {
                     return ((BufferedImage) data).getSubimage(toIntExact(xmin), toIntExact(ymin),
                             toIntExact(min(xmax + 1, ix + data.getWidth()  - 1) - xmin),
                             toIntExact(min(ymax + 1, iy + data.getHeight() - 1) - ymin));
                 }
             }
             /*
              * Return the backing image almost as-is (with potentially just a wrapper) for avoiding to copy data.
              * As per method contract, we shall set the (x,y) location to the difference between requested region
              * and actual region of the returned image. For example if the user requested an image starting at
              * (5,5) but the image to return starts at (1,1), then we need to set its location to (-4,-4).
              *
              * Note: we could do a special case when the result has only one tile and create a BufferedImage
              * with Raster.createChild(…), but that would force us to invoke RenderedImage.getTile(…) which
              * may force data loading earlier than desired.
              */
             final ReshapedImage r = new ReshapedImage(data, xmin, ymin, xmax, ymax);
             String error; assert (error = r.verify()) != null : error;
             return r.isIdentity() ? data : r;
         } catch (ArithmeticException e) {
             throw new CannotEvaluateException(e.getMessage(), e);
         }
     }
setView()
final void setView (final boolean converted, final GridCoverage view) package inherited
Sets the converted or package view.
The given view should not be null. It is caller responsibility to ensure that this method is invoked in a synchronized block.
Referenced by GridCoverage.forConvertedValues(), and GridCoverage2D.forConvertedValues().
{
         if (converted) {
             convertedView = view;
         } else {
             packedView = view;
         }
     }
toGridCoordinates()
FractionalGridCoordinates toGridCoordinates (final DirectPosition point) throws TransformException inherited
Converts the specified geospatial position to grid coordinates.
If the given position is associated to a non-null coordinate reference system (CRS) different than the CRS of this coverage, then this method automatically transforms that position to the getCoordinateReferenceSystem() coverage CRS} before to compute grid coordinates.
This method does not put any restriction on the grid coordinates result. The result may be outside the GridGeometry::getExtent() grid extent} if the GridGeometry::getGridToCRS(PixelInCell) grid to CRS} transform allows it.
Parameters
point geospatial coordinates (in arbitrary CRS) to transform to grid coordinates.
Returns
the grid coordinates for the given geospatial coordinates.
Exceptions
IncompleteGridGeometryException if the getGridGeometry() grid geometry} does not define a "grid to CRS" transform, or if the given point has a non-null CRS but this coverage does not getCoordinateReferenceSystem() have a CRS}.
TransformException if the given coordinates can not be transformed.
See also
FractionalGridCoordinates::toPosition(MathTransform)
Since
1.1
References PointToGridCoordinates.crsToGrid, FractionalGridCoordinates.fromPosition(), GridCoverage.getGridGeometry(), GridCoverage.lastConverter, GridCoverage.render(), and PointToGridCoordinates.sourceCRS.
Referenced by GridCoverage.evaluate(), and GridCoverage2D.evaluate().
{
         final CoordinateReferenceSystem sourceCRS = point.getCoordinateReferenceSystem();
         PointToGridCoordinates converter = lastConverter;
         if (converter == null || !Objects.equals(converter.sourceCRS, sourceCRS)) {
             converter = new PointToGridCoordinates(sourceCRS, this, getGridGeometry());
             lastConverter = converter;
         }
         return FractionalGridCoordinates.fromPosition(point, converter.crsToGrid);
     }
toString()
String toString () inherited
Returns a string representation of this grid coverage for debugging purpose.
The returned string is implementation dependent and may change in any future version. Current implementation is equivalent to the following, where
<default flags>
is the same set of flags than GridGeometry#toString().
{ java return toTree(Locale.getDefault(), <default flags>="">).toString(); }
Returns
a string representation of this grid coverage for debugging purpose.
References GridCoverage.toTree().
{
         return toTree(Locale.getDefault(), GridGeometry.defaultFlags()).toString();
     }
toTree()
TreeTable toTree (final Locale locale, final int bitmask) inherited
Returns a tree representation of some elements of this grid coverage.
The tree representation is for debugging purpose only and may change in any future SIS version.
Parameters
locale the locale to use for textual labels.
bitmask combination of GridGeometry flags.
Returns
a tree representation of the specified elements.
See also
GridGeometry::toTree(Locale, int)
References GridCoverage.appendDataLayout().
Referenced by GridCoverage.toString().
{
         ArgumentChecks.ensureNonNull("locale", locale);
         final Vocabulary vocabulary = Vocabulary.getResources(locale);
         final TableColumn<CharSequence> column = TableColumn.VALUE_AS_TEXT;
         final TreeTable tree = new DefaultTreeTable(column);
         final TreeTable.Node root = tree.getRoot();
         root.setValue(column, Classes.getShortClassName(this));
         TreeTable.Node branch = root.newChild();
         branch.setValue(column, vocabulary.getString(Vocabulary.Keys.CoverageDomain));
         gridGeometry.formatTo(locale, vocabulary, bitmask, branch);
         appendDataLayout(root, vocabulary, column);
         branch = root.newChild();
         branch.setValue(column, vocabulary.getString(Vocabulary.Keys.SampleDimensions));
         branch.newChild().setValue(column, SampleDimension.toString(locale, sampleDimensions));
         return tree;
     }
unwrapIfSameSize()
static RenderedImage unwrapIfSameSize (RenderedImage data) static private
Returns the wrapped image if the only difference is a translation, or.
data
otherwise. Workaround for RFE #4093999 ("Relax constraint on placement of this()/super() call in constructors").
References GridCoverage2D.data.
Referenced by GridCoverage2D.GridCoverage2D().
{
         /*if (data instanceof ReshapedImage) {
             final RenderedImage image = ((ReshapedImage) data).image;
             if (image.getWidth() == data.getWidth() && image.getHeight() == data.getHeight()) {
                 data = image;
             }
         }*/
         return data;
     }
verifyBandCount()
static void verifyBandCount (final Collection<? extends SampleDimension > range, final RenderedImage data) static private
Verifies that the number of bands in the image is equal to the number of sample dimensions.
The number of bands is fetched from the sample model, which in theory shall never be null. However this class has a little bit of tolerance to missing sample model; it may happen when the image is used only as a matrix storage.
Referenced by GridCoverage2D.GridCoverage2D().
{
         if (range != null) {
             final SampleModel sm = data.getSampleModel();
             if (sm != null) {
                 final int nb = sm.getNumBands();
                 final int ns = range.size();
                 /*if (nb != ns) {
                     throw new IllegalArgumentException(Resources.format(Resources.Keys.MismatchedBandCount_2, nb, ns));
                 }*/
             }
         }
     }
Member Data Documentation
convertedView
transient GridCoverage convertedView package inherited
Referenced by GridCoverage.getView().
data
final RenderedImage data private
The sample values stored as a.
RenderedImage
.
Referenced by GridCoverage2D.appendDataLayout(), GridCoverage2D.createGridGeometry(), GridCoverage2D.evaluate(), GridCoverage2D.GridCoverage2D(), GridCoverage2D.render(), and GridCoverage2D.unwrapIfSameSize().
gridGeometry
final GridGeometry gridGeometry package inherited
The grid extent, coordinate reference system (CRS) and conversion from cell indices to CRS.
See also
getGridGeometry()
Referenced by GridCoverage2D.evaluate(), GridCoverage.getGridGeometry(), GridCoverage2D.getGridGeometry2D(), GridCoverage2D.GridCoverage2D(), and GridCoverage2D.render().
gridGeometry2D
final AtomicReference<GridGeometry> gridGeometry2D private
The two-dimensional components of the coordinate reference system and "grid to CRS" transform.
This is derived from gridGeometry when first needed, retaining only the components at dimension indices xDimension and yDimension. The same AtomicReference instance may be shared with convertedView and packedView.
See also
getGridGeometry2D()
Referenced by GridCoverage2D.getGridGeometry2D(), and GridCoverage2D.GridCoverage2D().
gridToImageX
final long gridToImageX private
Offsets to apply for converting grid coverage coordinates to image pixel coordinates.
This is RenderedImage#getMinX() − GridExtent::getLow(int) GridExtent.getLow}(xDimension}) for the x offset and a similar formula for the y offset.
Referenced by GridCoverage2D.evaluate(), GridCoverage2D.GridCoverage2D(), and GridCoverage2D.render().
gridToImageY
final long gridToImageY package
Referenced by GridCoverage2D.evaluate(), GridCoverage2D.GridCoverage2D(), and GridCoverage2D.render().
MIN_DIMENSION
final int MIN_DIMENSION = 2 static private
Minimal number of dimension for this coverage.
Referenced by GridCoverage2D.addExtentIfAbsent(), GridCoverage2D.createGridGeometry(), and GridCoverage2D.GridCoverage2D().
xDimension
final int xDimension private
Indices of extent dimensions corresponding to image x and y coordinates.
Typical values are 0 for
xDimension
and 1 for
yDimension
, but different values are allowed.
Referenced by GridCoverage2D.evaluate(), GridCoverage2D.getGridGeometry2D(), GridCoverage2D.GridCoverage2D(), and GridCoverage2D.render().
yDimension
final int yDimension package
Referenced by GridCoverage2D.evaluate(), GridCoverage2D.getGridGeometry2D(), GridCoverage2D.GridCoverage2D(), and GridCoverage2D.render().