jena-geo: BufferedGridCoverage Class Reference
BufferedGridCoverage Class Reference
A GridCoverage with data stored in an in-memory Java2D buffer.
Public Member Functions
BufferedGridCoverage (final GridGeometry domain, final Collection<? extends SampleDimension > range, final DataBuffer data)
Constructs a grid coverage using the specified grid geometry, sample dimensions and data buffer.
BufferedGridCoverage (final GridGeometry grid, final Collection<? extends SampleDimension > bands, final int dataType)
Constructs a grid coverage using the specified grid geometry, sample dimensions and data type.
RenderedImage render (final GridExtent sliceExtent)
Returns a two-dimensional slice of grid data as a rendered image.
GridCoverage forConvertedValues (boolean arg0)
CoordinateReferenceSystem getCoordinateReferenceSystem ()
Returns the coordinate reference system to which the values in grid domain are referenced.
GridGeometry getGridGeometry ()
Returns information about the <cite>domain</cite> of this grid coverage.
List< SampleDimension > getSampleDimensions ()
Returns information about the <cite>range</cite> of this grid coverage.
double [] evaluate (final DirectPosition point, final double[] buffer) throws CannotEvaluateException
Returns a sequence of double values for a given point in the coverage.
FractionalGridCoordinates toGridCoordinates (final DirectPosition point) throws TransformException
Converts the specified geospatial position to grid coordinates.
String toString ()
Returns a string representation of this grid coverage for debugging purpose.
TreeTable toTree (final Locale locale, final int bitmask)
Returns a tree representation of some elements of this grid coverage.
Protected Attributes
final DataBuffer data
The sample values, potentially multi-banded.
Package Functions
final NumberRange<?> [] getRanges ()
Returns the range of values in each sample dimension, or.
final ColorModel createColorModel (final int visibleBand, final int dataType)
Creates a color model for the expected range of sample values.
final GridCoverage getView (final boolean converted)
Returns the converted or package view, or.
final void setView (final boolean converted, final GridCoverage view)
Sets the converted or package view.
void appendDataLayout (TreeTable.Node root, Vocabulary vocabulary, TableColumn< CharSequence > column)
Appends a "data layout" branch (if it exists) to the tree representation of this coverage.
Static Package Functions
static double [] evaluate (final RenderedImage data, final int x, final int y, final double[] buffer)
Gets sample values from the given image at the given index.
Package Attributes
final GridGeometry gridGeometry
The grid extent, coordinate reference system (CRS) and conversion from cell indices to CRS.
transient GridCoverage convertedView
Static Private Member Functions
static long getSampleCount (final GridExtent extent, long nbSamples)
Returns the number of cells in the given extent multiplied by the number of bands.
Detailed Description
A GridCoverage with data stored in an in-memory Java2D buffer.
Those data can be shown as RenderedImage. Images are created when render(GridExtent) is invoked instead than at construction time. This delayed construction makes this class better suited to n-dimensional grids since those grids can not be wrapped into a single RenderedImage.
Author
Johann Sorel (Geomatys)
Martin Desruisseaux (Geomatys)
Version
1.1
Since
1.0
Constructor & Destructor Documentation
BufferedGridCoverage() [1/2]
BufferedGridCoverage (final GridGeometry domain, final Collection<? extends SampleDimension > range, final DataBuffer data)
Constructs a grid coverage using the specified grid geometry, sample dimensions and data buffer.
This method stores the given buffer by reference (no copy). The bands in the given buffer can be stored either in a single bank (pixel interleaved image) or in different banks (banded image). This class detects automatically which of those two sample models is used.
Note that DataBuffer does not contain any information about image size. Consequently render(GridExtent) depends on the domain GridExtent, which must be accurate. If the extent size does not reflect accurately the image size, then the image will not be rendered properly.
Parameters
domain the grid extent, CRS and conversion from cell indices to CRS.
range sample dimensions for each image band.
data the sample values, potentially multi-banded.
Exceptions
NullPointerException if an argument is
null
.
IllegalArgumentException if the data buffer has an incompatible number of banks.
IllegalGridGeometryException if the grid extent is larger than the data buffer capacity.
ArithmeticException if the grid extent is larger than 64 bits integer capacity.
References BufferedGridCoverage.data, and BufferedGridCoverage.getSampleCount().
{
         super(domain, range);
         this.data = data;
         ArgumentChecks.ensureNonNull("data", data);
         /*
          * The buffer shall either contain all values in a single bank (pixel interleaved sample model)
          * or contain as many banks as bands (banded sample model).
          */
         final int numBands = range.size();
         final int numBanks = data.getNumBanks();
         if (numBanks != 1 && numBands != numBands) {
             throw new IllegalArgumentException(Resources.format(Resources.Keys.MismatchedBandCount_2, numBands, numBands));
         }
         /*
          * Verify that the buffer has enough elements for all cells in grid extent.
          * Note that the buffer may have all elements in a single bank.
          */
         final GridExtent extent = domain.getExtent();
         final long expectedSize = getSampleCount(extent, numBands);
         final long bufferSize = JDK9.multiplyFull(data.getSize(), numBanks);
         if (bufferSize < expectedSize) {
             final StringBuilder b = new StringBuilder();
             for (int i=0; i < extent.getDimension(); i++) {
                 if (i != 0) b.append(" × ");
                 b.append(extent.getSize(i));
             }
             throw new IllegalGridGeometryException(Resources.format(
                     Resources.Keys.InsufficientBufferCapacity_3, b, numBands, expectedSize - bufferSize));
         }
     }
BufferedGridCoverage() [2/2]
BufferedGridCoverage (final GridGeometry grid, final Collection<? extends SampleDimension > bands, final int dataType)
Constructs a grid coverage using the specified grid geometry, sample dimensions and data type.
This constructor creates a single-bank DataBuffer (pixel interleaved sample model) with all sample values initialized to zero.
Parameters
grid the grid extent, CRS and conversion from cell indices to CRS.
bands sample dimensions for each image band.
dataType one of
DataBuffer.TYPE_*
constants, the native data type used to store the coverage values.
Exceptions
ArithmeticException if the grid size is too large.
References BufferedGridCoverage.getSampleCount().
{
         super(grid, bands);
         final int n = Math.toIntExact(getSampleCount(grid.getExtent(), bands.size()));
         switch (dataType) {
             case DataBuffer.TYPE_BYTE:   data = new DataBufferByte  (n); break;
             case DataBuffer.TYPE_SHORT:  data = new DataBufferShort (n); break;
             case DataBuffer.TYPE_USHORT: data = new DataBufferUShort(n); break;
             case DataBuffer.TYPE_INT:    data = new DataBufferInt   (n); break;
             case DataBuffer.TYPE_FLOAT:  data = new DataBufferFloat (n); break;
             case DataBuffer.TYPE_DOUBLE: data = new DataBufferDouble(n); break;
             default: throw new IllegalArgumentException(Errors.format(Errors.Keys.UnknownType_1, dataType));
         }
     }
Member Function Documentation
appendDataLayout()
void appendDataLayout (TreeTable.Node root, Vocabulary vocabulary, TableColumn< CharSequence > column) package inherited
Appends a "data layout" branch (if it exists) to the tree representation of this coverage.
That branch will be inserted between "coverage domain" and "sample dimensions" branches. The default implementation does nothing.
Parameters
root root of the tree where to add a branch.
vocabulary localized resources for vocabulary.
column the single column where to write texts.
Referenced by GridCoverage.toTree().
{
     }
createColorModel()
final ColorModel createColorModel (final int visibleBand, final int dataType) package inherited
Creates a color model for the expected range of sample values.
Parameters
visibleBand the band to be made visible (usually 0). All other bands (if any) will be ignored.
dataType the color model type as one java.awt.image.DataBuffer constants.
Returns
proposed color model, or
null
if none.
References ColorModelFactory.createColorModel(), and ColorModelFactory.GRAYSCALE.
Referenced by GridCoverage2D.GridCoverage2D(), and ConvertedGridCoverage.render().
{
         return ColorModelFactory.createColorModel(sampleDimensions, visibleBand, dataType, ColorModelFactory.GRAYSCALE);
     }
evaluate() [1/2]
double [] evaluate (final DirectPosition point, final double [] buffer) throws CannotEvaluateException inherited
Returns a sequence of double values for a given point in the coverage.
The CRS of the given point may be any coordinate reference system; coordinate transformations will be applied as needed. If the CRS of the point is undefined, then it is assumed to be the same as this coverage. The returned sequence includes a value for each SampleDimension sample dimension}.
The default interpolation type used when accessing grid values for points which fall between grid cells is nearest neighbor. This default interpolation method may change in future version.
The default implementation invokes render(GridExtent) for a small region around the point. Subclasses should override with more efficient implementation.
Warning: this method may change. See SIS-485.
Parameters
point the coordinate point where to evaluate.
buffer an array in which to store values, or
null
to create a new array.
Returns
the
buffer
array, or a newly created array if
buffer
was null.
Exceptions
PointOutsideCoverageException if the evaluation failed because the input point has invalid coordinates.
CannotEvaluateException if the values can not be computed at the specified coordinate for another reason. It may be thrown if the coverage data type can not be converted to
double
by an identity or widening conversion. Subclasses may relax this constraint if appropriate.
Since
1.1
References FractionalGridCoordinates.pointOutsideCoverage(), GridCoverage.render(), FractionalGridCoordinates.toExtent(), and GridCoverage.toGridCoordinates().
Referenced by ConvertedGridCoverage.evaluate().
{
         /*
          * TODO: instead of restricting to a single point, keep the automatic size (1 or 2),
          * invoke render for each plan, then interpolate. We would keep a value of 1 in the
          * size array if we want to disable interpolation in some particular axis (e.g. time).
          */
         final long[] size = new long[gridGeometry.getDimension()];
         java.util.Arrays.fill(size, 1);
         try {
             final FractionalGridCoordinates gc = toGridCoordinates(point);
             try {
                 final GridExtent subExtent = gc.toExtent(gridGeometry.extent, size);
                 return evaluate(render(subExtent), 0, 0, buffer);
             } catch (ArithmeticException | IndexOutOfBoundsException | DisjointExtentException ex) {
                 throw (PointOutsideCoverageException) new PointOutsideCoverageException(
                         gc.pointOutsideCoverage(gridGeometry.extent), point).initCause(ex);
             }
         } catch (PointOutsideCoverageException ex) {
             ex.setOffendingLocation(point);
             throw ex;
         } catch (RuntimeException | TransformException ex) {
             throw new CannotEvaluateException(ex.getMessage(), ex);
         }
     }
evaluate() [2/2]
static double [] evaluate (final RenderedImage data, final int x, final int y, final double [] buffer) static package inherited
Gets sample values from the given image at the given index.
This method does not verify explicitly if the coordinates are out of bounds; we rely on the checks performed by the image and sample model implementations.
Parameters
data the data from which to get the sample values.
x column index of the value to get.
y row index of the value to get.
buffer an array in which to store values, or
null
to create a new array.
Returns
the
buffer
array, or a newly created array if
buffer
was null.
Exceptions
ArithmeticException if an integer overflow occurred while computing indices.
IndexOutOfBoundsException if a coordinate is out of bounds.
{
         final int tx = Math.toIntExact(Math.floorDiv(x - (long) data.getTileGridXOffset(), data.getTileWidth()));
         final int ty = Math.toIntExact(Math.floorDiv(y - (long) data.getTileGridYOffset(), data.getTileHeight()));
         return data.getTile(tx, ty).getPixel(x, y, buffer);
     }
forConvertedValues()
GridCoverage forConvertedValues (boolean arg0)
{
                 // TODO Auto-generated method stub
                 return null;
         }
getCoordinateReferenceSystem()
CoordinateReferenceSystem getCoordinateReferenceSystem () inherited
Returns the coordinate reference system to which the values in grid domain are referenced.
This is the CRS used when accessing a coverage with the
evaluate(…)
methods. This coordinate reference system is usually different than the coordinate system of the grid. It is the target coordinate reference system of the gridToCRS math transform.
The default implementation delegates to GridGeometry#getCoordinateReferenceSystem().
Returns
the CRS used when accessing a coverage with the
evaluate(…)
methods.
Exceptions
IncompleteGridGeometryException if the grid geometry has no CRS.
Referenced by CoverageJsonWriter.coverageToCovJSON(), and SRID.exec().
{
         return gridGeometry.getCoordinateReferenceSystem();
     }
getGridGeometry()
GridGeometry getGridGeometry () inherited
Returns information about the <cite>domain</cite> of this grid coverage.
Information includes the grid extent, CRS and conversion from cell indices to CRS.
GridGeometry
can also provide derived information like bounding box and resolution.
Returns
grid extent, CRS and conversion from cell indices to CRS.
See also
org.apache.sis.storage.GridCoverageResource::getGridGeometry()
References GridCoverage.gridGeometry.
Referenced by ConvertedGridCoverage.ConvertedGridCoverage(), CoverageJsonWriter.coverageToCovJSON(), NumXTiles.exec(), NumYTiles.exec(), MinTileX.exec(), MinTileY.exec(), TileWidth.exec(), TileGridYOffset.exec(), TileHeight.exec(), TileGridXOffset.exec(), PixelSize.exec(), NotSameAlignmentReason.exec(), TranslateX.exec(), TranslateY.exec(), EqualSRS.exec(), DWithin3D.exec(), SRIDGetAxis1Name.exec(), SRIDGetAxis1Orientation.exec(), SRIDGetAxis2Name.exec(), SRIDGetAxis2Orientation.exec(), SRIDHasFlippedAxis.exec(), EqualNorm.exec(), Crosses.exec(), ScaleX.exec(), Equals.exec(), EqualTopo.exec(), ScaleY.exec(), SkewY.exec(), Difference.exec(), Intersection.exec(), SymDifference.exec(), Or.exec(), Xor.exec(), Add.exec(), Subtract.exec(), Div.exec(), And.exec(), Mult.exec(), AndConst.exec(), AddConst.exec(), OrConst.exec(), XorConst.exec(), MultConst.exec(), SubtractConst.exec(), Log.exec(), DivConst.exec(), ContainsProperly.exec(), Summary.exec(), Width.exec(), Height.exec(), NearestValue.exec(), Envelope.exec(), SetScale.exec(), Intersects.exec(), SameAlignment.exec(), SkewX.exec(), Overlaps.exec(), Touches.exec(), Disjoint.exec(), CoveredBy.exec(), UpperLeftY.exec(), Contains.exec(), Covers.exec(), UpperLeftX.exec(), WorldToRasterCoordX.exec(), RasterToWorldCoordY.exec(), Within.exec(), WorldToRasterCoordY.exec(), RasterToWorldCoordX.exec(), RasterToWorldCoord.exec(), WorldToRasterCoord.exec(), and GridCoverage.toGridCoordinates().
{
         return gridGeometry;
     }
getRanges()
final NumberRange<?> [] getRanges () package inherited
Returns the range of values in each sample dimension, or.
null
if none.
Referenced by ConvertedGridCoverage.render().
{
         NumberRange<?>[] ranges = null;
         for (int i=0; i<sampleDimensions.length; i++) {
             final Optional<NumberRange<?>> r = sampleDimensions[i].getSampleRange();
             if (r.isPresent()) {
                 if (ranges == null) {
                     ranges = new NumberRange<?>[sampleDimensions.length];
                 }
                 ranges[i] = r.get();
             }
         }
         return ranges;
     }
getSampleCount()
static long getSampleCount (final GridExtent extent, long nbSamples) static private
Returns the number of cells in the given extent multiplied by the number of bands.
Parameters
extent the extent for which to get the number of cells.
nbSamples number of bands.
Returns
number of cells multiplied by the number of bands.
Exceptions
ArithmeticException if the number of samples exceeds 64-bits integer capacity.
References GridExtent.getDimension(), and GridExtent.getSize().
Referenced by BufferedGridCoverage.BufferedGridCoverage().
{
         for (int i = extent.getDimension(); --i >= 0;) {
             nbSamples = Math.multiplyExact(nbSamples, extent.getSize(i));
         }
         return nbSamples;
     }
getSampleDimensions()
List<SampleDimension> getSampleDimensions () inherited
Returns information about the <cite>range</cite> of this grid coverage.
Information include names, sample value ranges, fill values and transfer functions for all bands in this grid coverage. The length of the returned list should be equal to the java.awt.image.SampleModel::getNumBands() number of bands} in the rendered image.
Returns
names, value ranges, fill values and transfer functions for all bands in this grid coverage.
See also
org.apache.sis.storage.GridCoverageResource::getSampleDimensions()
Referenced by CoverageJsonWriter.coverageToCovJSON(), ConvertedGridCoverage.create(), SetBandNoDataValue.exec(), Add.exec(), NumBands.exec(), Or.exec(), And.exec(), Subtract.exec(), Mult.exec(), Xor.exec(), Div.exec(), SubtractConst.exec(), OrConst.exec(), DivConst.exec(), Log.exec(), MultConst.exec(), AddConst.exec(), AndConst.exec(), BandPixelType.exec(), BandMetaData.exec(), BandNoDataValue.exec(), XorConst.exec(), Summary.exec(), IsEmpty.exec(), SetScale.exec(), HasNoBand.exec(), and GridCoverage2D.forConvertedValues().
{
         return UnmodifiableArrayList.wrap(sampleDimensions);
     }
getView()
final GridCoverage getView (final boolean converted) package inherited
Returns the converted or package view, or.
null
if not yet computed. It is caller responsibility to ensure that this method is invoked in a synchronized block.
References GridCoverage.convertedView, and GridCoverage.packedView.
Referenced by GridCoverage.forConvertedValues(), and GridCoverage2D.forConvertedValues().
{
         return converted ? convertedView : packedView;
     }
render()
RenderedImage render (final GridExtent sliceExtent)
Returns a two-dimensional slice of grid data as a rendered image.
This method returns a view; sample values are not copied.
Returns
the grid slice as a rendered image.
{
         try {
             final ImageRenderer renderer = new ImageRenderer(this, sliceExtent);
             renderer.setData(data);
             return renderer.image();
         } catch (IllegalArgumentException | ArithmeticException | RasterFormatException e) {
             throw new CannotEvaluateException(e.getMessage(), e);
         }
     }
setView()
final void setView (final boolean converted, final GridCoverage view) package inherited
Sets the converted or package view.
The given view should not be null. It is caller responsibility to ensure that this method is invoked in a synchronized block.
Referenced by GridCoverage.forConvertedValues(), and GridCoverage2D.forConvertedValues().
{
         if (converted) {
             convertedView = view;
         } else {
             packedView = view;
         }
     }
toGridCoordinates()
FractionalGridCoordinates toGridCoordinates (final DirectPosition point) throws TransformException inherited
Converts the specified geospatial position to grid coordinates.
If the given position is associated to a non-null coordinate reference system (CRS) different than the CRS of this coverage, then this method automatically transforms that position to the getCoordinateReferenceSystem() coverage CRS} before to compute grid coordinates.
This method does not put any restriction on the grid coordinates result. The result may be outside the GridGeometry::getExtent() grid extent} if the GridGeometry::getGridToCRS(PixelInCell) grid to CRS} transform allows it.
Parameters
point geospatial coordinates (in arbitrary CRS) to transform to grid coordinates.
Returns
the grid coordinates for the given geospatial coordinates.
Exceptions
IncompleteGridGeometryException if the getGridGeometry() grid geometry} does not define a "grid to CRS" transform, or if the given point has a non-null CRS but this coverage does not getCoordinateReferenceSystem() have a CRS}.
TransformException if the given coordinates can not be transformed.
See also
FractionalGridCoordinates::toPosition(MathTransform)
Since
1.1
References PointToGridCoordinates.crsToGrid, FractionalGridCoordinates.fromPosition(), GridCoverage.getGridGeometry(), GridCoverage.lastConverter, GridCoverage.render(), and PointToGridCoordinates.sourceCRS.
Referenced by GridCoverage.evaluate(), and GridCoverage2D.evaluate().
{
         final CoordinateReferenceSystem sourceCRS = point.getCoordinateReferenceSystem();
         PointToGridCoordinates converter = lastConverter;
         if (converter == null || !Objects.equals(converter.sourceCRS, sourceCRS)) {
             converter = new PointToGridCoordinates(sourceCRS, this, getGridGeometry());
             lastConverter = converter;
         }
         return FractionalGridCoordinates.fromPosition(point, converter.crsToGrid);
     }
toString()
String toString () inherited
Returns a string representation of this grid coverage for debugging purpose.
The returned string is implementation dependent and may change in any future version. Current implementation is equivalent to the following, where
<default flags>
is the same set of flags than GridGeometry#toString().
{ java return toTree(Locale.getDefault(), <default flags>="">).toString(); }
Returns
a string representation of this grid coverage for debugging purpose.
References GridCoverage.toTree().
{
         return toTree(Locale.getDefault(), GridGeometry.defaultFlags()).toString();
     }
toTree()
TreeTable toTree (final Locale locale, final int bitmask) inherited
Returns a tree representation of some elements of this grid coverage.
The tree representation is for debugging purpose only and may change in any future SIS version.
Parameters
locale the locale to use for textual labels.
bitmask combination of GridGeometry flags.
Returns
a tree representation of the specified elements.
See also
GridGeometry::toTree(Locale, int)
References GridCoverage.appendDataLayout().
Referenced by GridCoverage.toString().
{
         ArgumentChecks.ensureNonNull("locale", locale);
         final Vocabulary vocabulary = Vocabulary.getResources(locale);
         final TableColumn<CharSequence> column = TableColumn.VALUE_AS_TEXT;
         final TreeTable tree = new DefaultTreeTable(column);
         final TreeTable.Node root = tree.getRoot();
         root.setValue(column, Classes.getShortClassName(this));
         TreeTable.Node branch = root.newChild();
         branch.setValue(column, vocabulary.getString(Vocabulary.Keys.CoverageDomain));
         gridGeometry.formatTo(locale, vocabulary, bitmask, branch);
         appendDataLayout(root, vocabulary, column);
         branch = root.newChild();
         branch.setValue(column, vocabulary.getString(Vocabulary.Keys.SampleDimensions));
         branch.newChild().setValue(column, SampleDimension.toString(locale, sampleDimensions));
         return tree;
     }
Member Data Documentation
convertedView
transient GridCoverage convertedView package inherited
Referenced by GridCoverage.getView().
data
final DataBuffer data protected
The sample values, potentially multi-banded.
The bands may be stored either in a single bank (pixel interleaved image) or in different banks (banded image). This class detects automatically which of those two sample models is used when render(GridExtent) is invoked.
Referenced by BufferedGridCoverage.BufferedGridCoverage().
gridGeometry
final GridGeometry gridGeometry package inherited
The grid extent, coordinate reference system (CRS) and conversion from cell indices to CRS.
See also
getGridGeometry()
Referenced by GridCoverage2D.evaluate(), GridCoverage.getGridGeometry(), GridCoverage2D.getGridGeometry2D(), GridCoverage2D.GridCoverage2D(), and GridCoverage2D.render().