jena-geo: ReshapedImage Class Reference
ReshapedImage Class Reference
A view over another image with the origin relocated to a new position.
Public Member Functions
Vector< RenderedImage > getSources ()
Returns the immediate source of this image.
Object getProperty (String name)
Delegates to the wrapped image with no change.
String [] getPropertyNames ()
ColorModel getColorModel ()
SampleModel getSampleModel ()
int getTileWidth ()
int getTileHeight ()
int getMinX ()
Returns properties determined at construction time.
int getMinY ()
int getWidth ()
int getHeight ()
int getMinTileX ()
int getMinTileY ()
int getTileGridXOffset ()
Returns the x coordinate of the upper-left pixel of tile (0, 0).
int getTileGridYOffset ()
Returns the y coordinate of the upper-left pixel of tile (0, 0).
Raster getTile (final int tileX, final int tileY)
Returns the tile at the given tile indices (not to be confused with pixel indices).
Raster getData ()
Returns a copy of this image as one large tile.
Raster getData (final Rectangle aoi)
Returns a copy of an arbitrary region of this image.
WritableRaster copyData (final WritableRaster raster)
Copies an arbitrary rectangular region of this image to the supplied writable raster.
String verify ()
Verifies whether image layout information are consistent.
Rectangle getBounds ()
Returns the image location (x, y) and image size (width, height).
int getNumXTiles ()
Returns the number of tiles in the x direction.
int getNumYTiles ()
Returns the number of tiles in the y direction.
String toString ()
Returns a string representation of this image for debugging purpose.
Static Public Attributes
static final String SAMPLE_RESOLUTIONS_KEY = "SampleResolution"
Key of a property defining the resolutions of sample values in each band.
Package Functions
ReshapedImage (final RenderedImage image, final long xmin, final long ymin, final long xmax, final long ymax)
Creates a new image with the same data than the given image but located at different coordinates.
final boolean isIdentity ()
Returns.
Package Attributes
final RenderedImage image
The image to translate.
final int height
final int minY
final int minTileY
Private Member Functions
Raster offset (final Raster data)
Returns a raster with the same data than the given raster but with coordinates translated from the coordinate system of the wrapped image to the coordinate system of this image.
Raster copyData (final Rectangle aoi)
Implementation of getData(Rectangle).
Private Attributes
final int offsetX
Value to add for converting a column index from the coordinate system of the wrapped image to the coordinate system of this image.
final int offsetY
Value to add for converting a row index from the coordinate system of the wrapped image to the coordinate system of this image.
final int width
The image size in pixels.
final int minX
Coordinate of the upper-left pixel.
final int minTileX
Index in tile matrix of the upper-left tile.
Detailed Description
A view over another image with the origin relocated to a new position.
Only the pixel coordinates are changed; the tile indices stay the same. However the image view may expose less tiles than the wrapped image. This wrapper does not change image size otherwise than by an integer amount of tiles.
Author
Johann Sorel (Geomatys)
Martin Desruisseaux (Geomatys)
Version
1.1
Since
1.1
Constructor & Destructor Documentation
ReshapedImage()
ReshapedImage (final RenderedImage image, final long xmin, final long ymin, final long xmax, final long ymax) package
Creates a new image with the same data than the given image but located at different coordinates.
In addition, this constructor can reduce the number of tiles.
Parameters
image the image to move.
xmin minimal x coordinate of the requested region, inclusive.
ymin minimal y coordinate of the requested region, inclusive.
xmax maximal x coordinate of the requested region, inclusive.
ymax maximal y coordinate of the requested region, inclusive.
Exceptions
ArithmeticException if image indices would overflow 32 bits integer capacity.
References ReshapedImage.image.
{
         this.image = image;
         /*
          * Compute indices of all tiles to retain in this image. All local fields are `long` in order to force
          * 64-bits integer arithmetic, because may have temporary 32-bits integer overflow during intermediate
          * calculation but still have a final result representable as an `int`. The use of `min` and `max` are
          * paranoiac safety against long integer overflow; real clamping will be done later.
          */
         final long lowerX = image.getMinX();                        // Lower source index (inclusive)
         final long lowerY = image.getMinY();
         final long upperX = image.getWidth()  + lowerX;             // Upper image index (exclusive).
         final long upperY = image.getHeight() + lowerY;
         final long tw     = image.getTileWidth();
         final long th     = image.getTileHeight();
         final long xo     = image.getTileGridXOffset();
         final long yo     = image.getTileGridYOffset();
         final long minTX  = floorDiv(max(lowerX, xmin) - xo, tw);   // Indices of the first tile to retain.
         final long minTY  = floorDiv(max(lowerY, ymin) - yo, th);
         final long maxTX  = floorDiv(min(upperX, xmax) - xo, tw);   // Indices of the last tile to retain (inclusive).
         final long maxTY  = floorDiv(min(upperY, ymax) - yo, th);
         /*
          * Coordinates in source image of the first pixel to show in this relocated image.
          * They are the coordinates of the upper-left corner of the first tile to retain,
          * clamped to image bounds if needed. This is not yet coordinates of this image.
          */
         final long sx = max(lowerX, minTX * tw + xo);
         final long sy = max(lowerY, minTY * th + yo);
         /*
          * As per GridCoverage2D contract, we shall set the (x,y) location to the difference between
          * requested region and actual region of this image. For example if the user requested image
          * starting at (5,5) but the data starts at (1,1), then we need to set location to (-4,-4).
          */
         final long x = subtractExact(sx, xmin);
         final long y = subtractExact(sy, ymin);
         minX     = toIntExact(x);
         minY     = toIntExact(y);
         width    = toIntExact(min(upperX, (maxTX + 1) * tw + xo) - sx);
         height   = toIntExact(min(upperY, (maxTY + 1) * th + yo) - sy);
         offsetX  = toIntExact(x - sx);
         offsetY  = toIntExact(y - sy);
         minTileX = toIntExact(minTX);
         minTileY = toIntExact(minTY);
     }
Member Function Documentation
copyData() [1/2]
Raster copyData (final Rectangle aoi) private
Implementation of getData(Rectangle).
This implementation will modify the given
aoi
argument. If that argument was supplied by user, then it should first be copied by the caller.
References ReshapedImage.image, ReshapedImage.offsetX, and ReshapedImage.offsetY.
Referenced by ReshapedImage.getData().
{
         aoi.x = subtractExact(aoi.x, offsetX);      // Convert coordinate from this image to wrapped image.
         aoi.y = subtractExact(aoi.y, offsetY);
         final Raster data = image.getData(aoi);
         return data.createTranslatedChild(addExact(data.getMinX(), offsetX),
                                           addExact(data.getMinY(), offsetY));
     }
copyData() [2/2]
WritableRaster copyData (final WritableRaster raster)
Copies an arbitrary rectangular region of this image to the supplied writable raster.
The region to be copied is determined from the bounds of the supplied raster.
Parameters
raster the raster to hold a copy of this image, or
null
.
Returns
the given raster if it was not-null, or a new raster otherwise.
References ReshapedImage.image, ReshapedImage.offsetX, and ReshapedImage.offsetY.
{
         WritableRaster data;
         if (raster != null) {
             data = raster.createWritableTranslatedChild(
                     subtractExact(raster.getMinX(), offsetX),
                     subtractExact(raster.getMinY(), offsetY));
         } else {
             data = null;
         }
         data = image.copyData(data);
         if (data.getWritableParent() == raster) {
             return raster;
         }
         return data.createWritableTranslatedChild(addExact(data.getMinX(), offsetX),
                                                   addExact(data.getMinY(), offsetY));
     }
getBounds()
Rectangle getBounds () inherited
Returns the image location (x, y) and image size (width, height).
This is a convenience method encapsulating the results of 4 method calls in a single object.
Returns
the image location and image size as a new rectangle.
See also
getMinX()
getMinY()
getWidth()
getHeight()
References ImageUtilities.getBounds().
{
         return ImageUtilities.getBounds(this);
     }
getColorModel()
ColorModel getColorModel ()
References ReshapedImage.image.
 {return image.getColorModel();}
getData() [1/2]
Raster getData ()
Returns a copy of this image as one large tile.
The returned raster will not be updated if this image is changed.
Returns
a copy of this image as one large tile.
References ReshapedImage.copyData(), ReshapedImage.height, ReshapedImage.image, ReshapedImage.minX, ReshapedImage.minY, ReshapedImage.offset(), and ReshapedImage.width.
{
         /*
          * If this image contains all data, delegate to RenderedImage.getData()
          * in case some implementations provide an optimized method. Otherwise
          * ask only the sub-region covered by this image.
          */
         if (width >= image.getWidth() && height >= image.getHeight()) {
             return offset(image.getData());
         }
         return copyData(new Rectangle(minX, minY, width, height));
     }
getData() [2/2]
Raster getData (final Rectangle aoi)
Returns a copy of an arbitrary region of this image.
The returned raster will not be updated if this image is changed.
Parameters
aoi the region of this image to copy.
Returns
a copy of this image in the given area of interest.
References ReshapedImage.copyData().
{
         ArgumentChecks.ensureNonNull("aoi", aoi);
         return copyData(new Rectangle(aoi));
     }
getHeight()
int getHeight ()
References ReshapedImage.height.
 {return height;}
getMinTileX()
int getMinTileX ()
References ReshapedImage.minTileX.
 {return minTileX;}
getMinTileY()
int getMinTileY ()
References ReshapedImage.minTileY.
 {return minTileY;}
getMinX()
int getMinX ()
Returns properties determined at construction time.
References ReshapedImage.minX.
Referenced by ReshapedImage.verify().
 {return minX;}
getMinY()
int getMinY ()
References ReshapedImage.minY.
Referenced by ReshapedImage.verify().
 {return minY;}
getNumXTiles()
int getNumXTiles () inherited
Returns the number of tiles in the x direction.
The default implementation computes this value from getWidth() and getTileWidth() on the assumption that getMinX() is the coordinate of the leftmost pixels of tiles located at getMinTileX() index. This assumption can be verified by verify().
Returns
returns the number of tiles in the x direction.
Referenced by TiledImage.getTile(), PlanarImage.toString(), and PlanarImage.verify().
{
         /*
          * If assumption documented in javadoc does not hold, the calculation performed here would need to be
          * more complicated: compute tile index of minX, compute tile index of maxX, return difference plus 1.
          */
         return Numerics.ceilDiv(getWidth(), getTileWidth());
     }
getNumYTiles()
int getNumYTiles () inherited
Returns the number of tiles in the y direction.
The default implementation computes this value from getHeight() and getTileHeight() on the assumption that getMinY() is the coordinate of the uppermost pixels of tiles located at getMinTileY() index. This assumption can be verified by verify().
Returns
returns the number of tiles in the y direction.
Referenced by TiledImage.getTile(), PlanarImage.toString(), and PlanarImage.verify().
{
         return Numerics.ceilDiv(getHeight(), getTileHeight());
     }
getProperty()
Object getProperty (String name)
Delegates to the wrapped image with no change.
References ReshapedImage.image.
 {return image.getProperty(name);}
getPropertyNames()
String [] getPropertyNames ()
References ReshapedImage.image.
 {return image.getPropertyNames();}
getSampleModel()
SampleModel getSampleModel ()
References ReshapedImage.image.
 {return image.getSampleModel();}
getSources()
Vector<RenderedImage> getSources ()
Returns the immediate source of this image.
{
         final Vector<RenderedImage> sources = new Vector<>(1);
         sources.add(image);
         return sources;
     }
getTile()
Raster getTile (final int tileX, final int tileY)
Returns the tile at the given tile indices (not to be confused with pixel indices).
Parameters
tileX the x index of the requested tile in the tile array.
tileY the y index of the requested tile in the tile array.
Returns
the tile specified by the specified indices.
References ReshapedImage.image, and ReshapedImage.offset().
{
         return offset(image.getTile(tileX, tileY));
     }
getTileGridXOffset()
int getTileGridXOffset ()
Returns the x coordinate of the upper-left pixel of tile (0, 0).
That tile (0, 0) may not actually exist.
References ReshapedImage.image, and ReshapedImage.offsetX.
Referenced by ReshapedImage.verify().
{
         return addExact(image.getTileGridXOffset(), offsetX);
     }
getTileGridYOffset()
int getTileGridYOffset ()
Returns the y coordinate of the upper-left pixel of tile (0, 0).
That tile (0, 0) may not actually exist.
References ReshapedImage.image, and ReshapedImage.offsetY.
Referenced by ReshapedImage.verify().
{
         return addExact(image.getTileGridYOffset(), offsetY);
     }
getTileHeight()
int getTileHeight ()
References ReshapedImage.image.
Referenced by ReshapedImage.verify().
 {return image.getTileHeight();}
getTileWidth()
int getTileWidth ()
References ReshapedImage.image.
Referenced by ReshapedImage.verify().
 {return image.getTileWidth();}
getWidth()
int getWidth ()
References ReshapedImage.width.
 {return width;}
isIdentity()
final boolean isIdentity () package
Returns.
true
if this image does not move and does not subset the wrapped image.
Referenced by GridCoverage2D.render().
{
         // The use of >= is a paranoiac check, but the > case should never happen actually.
         return offsetX == 0 && offsetY == 0 && width >= image.getWidth() && height >= image.getHeight();
     }
offset()
Raster offset (final Raster data) private
Returns a raster with the same data than the given raster but with coordinates translated from the coordinate system of the wrapped image to the coordinate system of this image.
The returned raster will have the given raster as its parent.
References ReshapedImage.offsetX, and ReshapedImage.offsetY.
Referenced by ReshapedImage.getData(), and ReshapedImage.getTile().
{
         return data.createTranslatedChild(addExact(data.getMinX(), offsetX),
                                           addExact(data.getMinY(), offsetY));
     }
toString()
String toString () inherited
Returns a string representation of this image for debugging purpose.
This string representation may change in any future SIS version.
Returns
a string representation of this image for debugging purpose only.
References ColorModelFactory.formatDescription(), ImageUtilities.getDataTypeName(), PlanarImage.getNumXTiles(), PlanarImage.getNumYTiles(), and PlanarImage.verify().
{
         final StringBuilder buffer = new StringBuilder(100).append(Classes.getShortClassName(this))
                 .append('[').append(getWidth()).append("  ").append(getHeight()).append(" pixels");
         final SampleModel sm = getSampleModel();
         if (sm != null) {
             buffer.append("  ").append(sm.getNumBands()).append(" bands");
             final String type = ImageUtilities.getDataTypeName(sm);
             if (type != null) {
                 buffer.append(" of type ").append(type);
             }
         }
         /*
          * Write details about color model only if there is "useful" information for a geospatial raster.
          * The main category of interest are "color palette" versus "gray scale" versus everything else,
          * and whether the image may have transparent pixels.
          */
         final ColorModel cm = getColorModel();
 colors: if (cm != null) {
             buffer.append("; ");
             if (cm instanceof IndexColorModel) {
                 buffer.append(((IndexColorModel) cm).getMapSize()).append(" indexed colors");
             } else {
                 ColorModelFactory.formatDescription(cm.getColorSpace(), buffer);
             }
             final String transparency;
             switch (cm.getTransparency()) {
                 case ColorModel.OPAQUE:      transparency = "opaque"; break;
                 case ColorModel.TRANSLUCENT: transparency = "translucent"; break;
                 case ColorModel.BITMASK:     transparency = "bitmask transparency"; break;
                 default: break colors;
             }
             buffer.append("; ").append(transparency);
         }
         /*
          * Tiling information last because it is usually a secondary aspect compared to above information.
          * If a warning is emitted, it will usually be a tiling problem so it is useful to keep it close.
          */
         final int tx = getNumXTiles();
         final int ty = getNumYTiles();
         if (tx != 1 || ty != 1) {
             buffer.append("; ").append(tx).append("  ").append(ty).append(" tiles");
         }
         final String error = verify();
         if (error != null) {
             buffer.append(";  mismatched ").append(error);
         }
         return buffer.append(']').toString();
     }
verify()
String verify ()
Verifies whether image layout information are consistent.
References ReshapedImage.getMinX(), ReshapedImage.getMinY(), ReshapedImage.getTileGridXOffset(), ReshapedImage.getTileGridYOffset(), ReshapedImage.getTileHeight(), ReshapedImage.getTileWidth(), ReshapedImage.image, ReshapedImage.minTileX, ReshapedImage.minTileY, ReshapedImage.offsetX, and ReshapedImage.offsetY.
Referenced by GridCoverage2D.render().
{
         final String error = super.verify();
         if (error == null) {
             if (getMinX() != image.getMinX() + (minTileX - image.getMinTileX()) * getTileWidth()  + offsetX) return "minX";
             if (getMinY() != image.getMinY() + (minTileY - image.getMinTileY()) * getTileHeight() + offsetY) return "minY";
             if (getTileGridXOffset() != super.getTileGridXOffset()) return "tileGridXOffset";
             if (getTileGridYOffset() != super.getTileGridYOffset()) return "tileGridYOffset";
         }
         return error;
     }
Member Data Documentation
height
final int height package
Referenced by ReshapedImage.getData(), and ReshapedImage.getHeight().
image
final RenderedImage image package
The image to translate.
Referenced by ReshapedImage.copyData(), ReshapedImage.getColorModel(), ReshapedImage.getData(), ReshapedImage.getProperty(), ReshapedImage.getPropertyNames(), ReshapedImage.getSampleModel(), ReshapedImage.getTile(), ReshapedImage.getTileGridXOffset(), ReshapedImage.getTileGridYOffset(), ReshapedImage.getTileHeight(), ReshapedImage.getTileWidth(), ReshapedImage.ReshapedImage(), and ReshapedImage.verify().
minTileX
final int minTileX private
Index in tile matrix of the upper-left tile.
Computed at construction time in order to detect integer overflows early.
Referenced by ReshapedImage.getMinTileX(), and ReshapedImage.verify().
minTileY
final int minTileY package
Referenced by ReshapedImage.getMinTileY(), and ReshapedImage.verify().
minX
final int minX private
Coordinate of the upper-left pixel.
Computed at construction time in order to detect integer overflows early.
Referenced by ReshapedImage.getData(), and ReshapedImage.getMinX().
minY
final int minY package
Referenced by ReshapedImage.getData(), and ReshapedImage.getMinY().
offsetX
final int offsetX private
Value to add for converting a column index from the coordinate system of the wrapped image to the coordinate system of this image.
For a conversion in opposite direction, that value shall be subtracted.
Referenced by ReshapedImage.copyData(), ReshapedImage.getTileGridXOffset(), ReshapedImage.offset(), and ReshapedImage.verify().
offsetY
final int offsetY private
Value to add for converting a row index from the coordinate system of the wrapped image to the coordinate system of this image.
For a conversion in opposite direction, that value shall be subtracted.
Referenced by ReshapedImage.copyData(), ReshapedImage.getTileGridYOffset(), ReshapedImage.offset(), and ReshapedImage.verify().
SAMPLE_RESOLUTIONS_KEY
final String SAMPLE_RESOLUTIONS_KEY = "SampleResolution" static inherited
Key of a property defining the resolutions of sample values in each band.
This property is recommended for images having sample values as floating point numbers. For example if sample values were computed by value = integer scale factor, then the resolution is the scale factor. This information is used for choosing the number of fraction digits to show when writing sample values in text format.
Values should be instances of
float[]
or
double[]
. The array length should be the number of bands.
width
final int width private
The image size in pixels.
May be smaller than image size by an integer amount of tiles.
Referenced by ReshapedImage.getData(), and ReshapedImage.getWidth().