jena-geo: ColorModelFactory Class Reference
ColorModelFactory Class Reference
A factory for ColorModel objects built from a sequence of colors.
Public Member Functions
int hashCode ()
Public as an implementation side-effect.
boolean equals (final Object other)
Public as an implementation side-effect.
Static Public Member Functions
static ColorModel createColorModel (final SampleDimension[] bands, final int visibleBand, final int type, Function< Category, Color[]> colors)
Returns a color model interpolated for the ranges in the given sample dimensions.
static ColorModel createColorModel (final Map<? extends NumberRange<?>, ? extends Color[]> categories, final int visibleBand, final int numBands, final int type)
Returns a color model interpolated for the given ranges and colors.
static IndexColorModel createIndexColorModel (final int[] ARGB, final int numBands, final int visibleBand, int transparent)
Returns a tolerant index color model for the specified ARGB code.
static ColorModel createGrayScale (final int dataType, final int numComponents, final int visibleBand, final double minimum, final double maximum)
Creates a color model for opaque images storing pixels as real numbers.
static void formatDescription (final ColorSpace cs, final StringBuilder buffer)
Appends a description of the given color space in the given buffer.
static< T extends ColorModel > T unique (T cm)
Returns a unique instance of the given color model.
static int getBitCount (final int mapSize)
Returns a bit count for an IndexColorModel mapping.
static void expand (final int[] colors, final int[] ARGB, final int lower, final int upper)
Copies.
Static Public Attributes
static final Color TRANSPARENT = new Color(0, true)
The fully transparent color.
static final Function< Category, Color[]> GRAYSCALE
Applies a gray scale to quantitative category and transparent colors to qualitative categories.
Static Package Functions
static boolean isStandardRange (final int dataType, double minimum, final double maximum)
Returns.
Package Attributes
final double maximum
Private Member Functions
ColorModelFactory (final Map<? extends NumberRange<?>, ? extends Color[]> categories, final int visibleBand, final int numBands, final int type)
Constructs a new.
ColorModel createColorModel ()
Constructs the color model from the.
Static Private Member Functions
static int getTransferType (final int mapSize)
Returns a suggested type for an IndexColorModel of.
static int [] toARGB (final Color[] colors)
Returns the ARGB codes for the given colors.
static int roundByte (final float value)
Rounds a float value and clamps the result between 0 and 255 inclusive.
Private Attributes
final double minimum
The minimum (inclusive) and maximum (exclusive) sample values.
final int [] pieceStarts
In a color map defined by a piecewise function, indices where to store the first interpolated value in the color map.
final int [][] ARGB
The Alpha-Red-Green-Blue codes for all segments of the piecewise function.
final int visibleBand
The visible band (usually 0) used for the construction of a single instance of a ColorModel.
final int numBands
The number of bands (usually 1) used for the construction of a single instance of a ColorModel.
final int type
The color model type.
Static Private Attributes
static final WeakHashSet< ColorModelPatch > CACHE = new WeakHashSet<>(ColorModelPatch.class)
Shared instances of ColorModels.
static final Map< ColorModelFactory, ColorModel > PIECEWISES = new WeakValueHashMap<>(ColorModelFactory.class)
A pool of color models previously created by createColorModel().
static final Comparator< Map.Entry< NumberRange<?>, Color[]> > RANGE_COMPARATOR
Comparator for sorting ranges by their minimal value.
Detailed Description
A factory for ColorModel objects built from a sequence of colors.
Author
Martin Desruisseaux (IRD, Geomatys)
Johann Sorel (Geomatys)
Version
1.1
Since
1.0
Constructor & Destructor Documentation
ColorModelFactory()
ColorModelFactory (final Map<? extends NumberRange<?>, ? extends Color[]> categories, final int visibleBand, final int numBands, final int type) private
Constructs a new.
ColorModelFactory
. This object will be used as a key in a Map, so this is not really a
ColorModelFactory
but a kind of "@code ColorModelKey @endcode " instead. However, since this constructor is private, user does not need to know that.
References ColorModelFactory.maximum, ColorModelFactory.minimum, ColorModelFactory.numBands, ColorModelFactory.RANGE_COMPARATOR, ColorModelFactory.toARGB(), ColorModelFactory.type, and ColorModelFactory.visibleBand.
Referenced by ColorModelFactory.createColorModel(), and ColorModelFactory.equals().
     {
         this.visibleBand = visibleBand;
         this.numBands    = numBands;
         this.type        = type;
         @SuppressWarnings({"unchecked", "rawtypes"})
         final Map.Entry<NumberRange<?>, Color[]>[] entries = categories.entrySet().toArray(new Map.Entry[categories.size()]);
         Arrays.sort(entries, RANGE_COMPARATOR);
         int     count   = 0;
         int[]   starts  = new int[entries.length + 1];
         int[][] codes   = new int[entries.length][];
         double  minimum = Double.POSITIVE_INFINITY;
         double  maximum = Double.NEGATIVE_INFINITY;
         for (final Map.Entry<NumberRange<?>, Color[]> entry : entries) {
             final NumberRange<?> range = entry.getKey();
             final double min = range.getMinDouble(true);
             final double max = range.getMaxDouble(false);
             if (min < minimum) minimum = min;
             if (max > maximum) maximum = max;
             final int lower = Math.round((float) min);
             final int upper = Math.round((float) max);
             if (lower < upper) {
                 if (lower < 0 || upper > 0x10000) {
                     starts = ArraysExt.EMPTY_INT;
                     codes  = null;
                     count  = 0;
                 } else if (codes != null) {
                     if (count != 0) {
                         final int before = starts[count];
                         if (before != lower) {
                             if (before > lower) {
                                 // TODO: remove the overlapped colors in previous range.
                             } else {
                                 // TODO: we could reduce the amount of copies.
                                 codes  = Arrays.copyOf(codes,   codes.length + 1);
                                 starts = Arrays.copyOf(starts, starts.length + 1);
                                 codes[count++] = ArraysExt.EMPTY_INT;
                             }
                         }
                     }
                     codes [  count] = toARGB(entry.getValue());
                     starts[  count] = lower;
                     starts[++count] = upper;
                 }
             }
         }
         if (minimum >= maximum) {
             minimum = 0;
             maximum = 1;
         }
         /*
          * The length of 'pieceStarts' may differ from the expected length if there is holes between categories.
          * We need to adjust the array length since it will determine the number of categories. Note that there
          * is one more element than the number of categories.
          */
         if (starts.length != 0) {
             starts = ArraysExt.resize(starts, count + 1);
         }
         this.minimum     = minimum;
         this.maximum     = maximum;
         this.pieceStarts = starts;
         this.ARGB        = codes;
     }
Member Function Documentation
createColorModel() [1/3]
ColorModel createColorModel () private
Constructs the color model from the.
#codes
and ARGB data. This method is invoked the first time the color model is created, or when the value in the cache has been discarded.
References ColorModelFactory.ARGB, ColorModelFactory.createGrayScale(), ColorModelFactory.createIndexColorModel(), ColorModelFactory.expand(), ColorModelFactory.maximum, ColorModelFactory.minimum, ColorModelFactory.numBands, ColorModelFactory.pieceStarts, ColorModelFactory.type, ColorModelFactory.unique(), and ColorModelFactory.visibleBand.
Referenced by GridCoverage.createColorModel(), ColorModelFactory.createColorModel(), and GridCoverageBuilder2.setValues().
{
         /*
          * If the requested type is any type not supported by IndexColorModel,
          * fallback on a generic (but very slow!) color model.
          */
         if (type != DataBuffer.TYPE_BYTE && type != DataBuffer.TYPE_USHORT) {
             return createGrayScale(type, numBands, visibleBand, minimum, maximum);
         }
         /*
          * If there is no category, constructs a gray scale palette.
          */
         final int categoryCount = pieceStarts.length - 1;
         if (numBands == 1 && categoryCount <= 0) {
             final ColorSpace cs = ColorSpace.getInstance(ColorSpace.CS_GRAY);
             final int[] nBits = {
                 DataBuffer.getDataTypeSize(type)
             };
             return unique(new ComponentColorModel(cs, nBits, false, true, Transparency.OPAQUE, type));
         }
         /*
          * Interpolates the colors in the color palette. Colors that do not fall
          * in the range of a category will be set to a transparent color.
          */
         final int[] colorMap;
         int transparent = -1;
         if (categoryCount <= 0) {
             colorMap = ArraysExt.range(0, 256);
         } else {
             colorMap = new int[pieceStarts[categoryCount]];
             for (int i=0; i<categoryCount; i++) {
                 final int[] colors = ARGB[i];
                 final int   lower  = pieceStarts[i  ];
                 final int   upper  = pieceStarts[i+1];
                 if (transparent < 0 && colors.length == 0) {
                     transparent = lower;
                 }
                 expand(colors, colorMap, lower, upper);
             }
         }
         return createIndexColorModel(colorMap, numBands, visibleBand, transparent);
     }
createColorModel() [2/3]
static ColorModel createColorModel (final SampleDimension [] bands, final int visibleBand, final int type, Function< Category, Color[]> colors) static
Returns a color model interpolated for the ranges in the given sample dimensions.
This method builds up the color model from each category in the visible sample dimension. Returned instances of ColorModel are shared among all callers in the running virtual machine.
Parameters
bands the sample dimensions for which to create a color model.
visibleBand the band to be made visible (usually 0). All other bands (if any) will be ignored.
type the color model type. One of DataBuffer#TYPE_BYTE, DataBuffer#TYPE_USHORT, DataBuffer#TYPE_INT, DataBuffer#TYPE_FLOAT or DataBuffer#TYPE_DOUBLE.
colors the colors to use for each category. The function may return
null
, which means transparent.
Returns
a color model suitable for java.awt.image.RenderedImage objects with values in the given ranges.
References ColorModelFactory.createColorModel().
     {
         ArgumentChecks.ensureNonNull("bands",  bands);
         ArgumentChecks.ensureNonNull("colors", colors);
         final Map<NumberRange<?>, Color[]> ranges = new LinkedHashMap<>();
         for (final Category category : bands[visibleBand].getCategories()) {
             ranges.put(category.getSampleRange(), colors.apply(category));
         }
         return createColorModel(ranges, visibleBand, bands.length, type);
     }
createColorModel() [3/3]
static ColorModel createColorModel (final Map<? extends NumberRange<?>, ? extends Color[]> categories, final int visibleBand, final int numBands, final int type) static
Returns a color model interpolated for the given ranges and colors.
This method builds up the color model from each set of colors associated to ranges in the given map. Returned instances of ColorModel are shared among all callers in the running virtual machine.
Parameters
categories the colors associated to ranges of sample values.
visibleBand the band to be made visible (usually 0). All other bands, if any will be ignored.
numBands the number of bands for the color model (usually 1). The returned color model will render only the
visibleBand
and ignore the others, but the existence of all
numBands
will be at least tolerated. Supplemental bands, even invisible, are useful for processing.
type the color model type. One of DataBuffer#TYPE_BYTE, DataBuffer#TYPE_USHORT, DataBuffer#TYPE_INT, DataBuffer#TYPE_FLOAT or DataBuffer#TYPE_DOUBLE.
Returns
a color model suitable for java.awt.image.RenderedImage objects with values in the given ranges.
References ColorModelFactory.ColorModelFactory(), ColorModelFactory.createColorModel(), and ColorModelFactory.PIECEWISES.
     {
         ArgumentChecks.ensureNonNull("categories", categories);
         ArgumentChecks.ensureBetween("visibleBand", 0, numBands - 1, visibleBand);
         final ColorModelFactory key = new ColorModelFactory(categories, visibleBand, numBands, type);
         synchronized (PIECEWISES) {
             ColorModel model = PIECEWISES.get(key);
             if (model == null) {
                 model = key.createColorModel();
                 PIECEWISES.put(key, model);
             }
             return model;
         }
     }
createGrayScale()
static ColorModel createGrayScale (final int dataType, final int numComponents, final int visibleBand, final double minimum, final double maximum) static
Creates a color model for opaque images storing pixels as real numbers.
The color model can have an arbitrary number of bands, but in current implementation only one band is used.
Warning: the use of this color model is very slow. It should be used only when no standard color model can be used.
Parameters
dataType the color model type as one of
DataBuffer.TYPE_*
constants.
numComponents the number of components.
visibleBand the band to use for computing colors.
minimum the minimal sample value expected.
maximum the maximal sample value expected.
Returns
the color model for the given range of values.
See also
RasterFactory::createGrayScaleImage(int, int, int, int, int, double, double)
References ColorModelFactory.isStandardRange(), and ColorModelFactory.unique().
Referenced by ColorModelFactory.createColorModel(), and RasterFactory.createGrayScaleImage().
     {
         final ColorModel cm;
         if (numComponents == 1 && isStandardRange(dataType, minimum, maximum)) {
             final ColorSpace cs = ColorSpace.getInstance(ColorSpace.CS_GRAY);
             cm = new ComponentColorModel(cs, false, true, Transparency.OPAQUE, dataType);
         } else {
             final ScaledColorSpace cs = new ScaledColorSpace(numComponents, visibleBand, minimum, maximum);
             cm = new ScaledColorModel(cs, dataType);
         }
         return unique(cm);
     }
createIndexColorModel()
static IndexColorModel createIndexColorModel (final int [] ARGB, final int numBands, final int visibleBand, int transparent) static
Returns a tolerant index color model for the specified ARGB code.
This color model accepts image with the specified number of bands.
This methods caches previously created instances using weak references, because index color model may be big (up to 256 kb).
Parameters
ARGB an array of ARGB values.
numBands the number of bands.
visibleBand the band to display.
transparent the transparent pixel, or -1 for auto-detection.
Returns
An index color model for the specified array.
References ColorModelFactory.getBitCount(), ColorModelFactory.getTransferType(), ColorModelFactory.type, and ColorModelFactory.unique().
Referenced by ColorModelFactory.createColorModel().
{
         /*
          * No need to scan the ARGB values in search of a transparent pixel;
          * the IndexColorModel constructor does that for us.
          */
         final int length = ARGB.length;
         final int bits = getBitCount(length);
         final int type = getTransferType(length);
         final IndexColorModel cm;
         if (numBands == 1) {
             cm = new IndexColorModel(bits, length, ARGB, 0, true, transparent, type);
         } else {
             cm = new MultiBandsIndexColorModel(bits, length, ARGB, 0, true, transparent,
                                                type, numBands, visibleBand);
         }
         return unique(cm);
     }
equals()
boolean equals (final Object other)
Public as an implementation side-effect.
Parameters
other the other object to compare for equality.
Returns
whether the two objects are equal.
References ColorModelFactory.ARGB, ColorModelFactory.ColorModelFactory(), ColorModelFactory.maximum, ColorModelFactory.minimum, ColorModelFactory.numBands, ColorModelFactory.pieceStarts, ColorModelFactory.type, and ColorModelFactory.visibleBand.
{
         if (other == this) {
             return true;
         }
         if (other instanceof ColorModelFactory) {
             final ColorModelFactory that = (ColorModelFactory) other;
             return this.type        == that.type
                 && this.numBands    == that.numBands
                 && this.visibleBand == that.visibleBand
                 && this.minimum     == that.minimum         // Should never be NaN.
                 && this.maximum     == that.maximum
                 && Arrays.equals(pieceStarts, that.pieceStarts)
                 && Arrays.deepEquals(ARGB, that.ARGB);
         }
         return false;
     }
expand()
static void expand (final int [] colors, final int [] ARGB, final int lower, final int upper) static
Copies.
colors
into
ARGB
array from index
lower
inclusive to index
upper
exclusive. If
upper-lower
is not equal to the length of
colors
array, then colors will be interpolated.
Parameters
colors colors to copy into the
ARGB
array.
ARGB array of integer to write ARGB values into.
lower index (inclusive) of the first element of
ARGB
to change.
upper index (exclusive) of the last element of
ARGB
to change.
References ColorModelFactory.roundByte().
Referenced by ColorModelFactory.createColorModel().
{
         switch (colors.length) {
             case 1: Arrays.fill(ARGB, lower, upper, colors[0]);         // fall through
             case 0: return;
         }
         switch (upper - lower) {
             case 1: ARGB[lower] = colors[0];                            // fall through
             case 0: return;
         }
         /*
          * Prepares the coefficients for the iteration.
          * The non-final ones will be updated inside the loop.
          */
         final double scale = (double) (colors.length - 1) / (double) (upper - lower - 1);
         final int maxBase = colors.length - 2;
         float index = 0;
         int   base  = 0;
         for (int i=lower;;) {
             final int C0 = colors[base    ];
             final int C1 = colors[base + 1];
             final int A0 = (C0 >>> 24) & 0xFF,   A1 = ((C1 >>> 24) & 0xFF) - A0;
             final int R0 = (C0 >>> 16) & 0xFF,   R1 = ((C1 >>> 16) & 0xFF) - R0;
             final int G0 = (C0 >>>  8) & 0xFF,   G1 = ((C1 >>>  8) & 0xFF) - G0;
             final int B0 = (C0       ) & 0xFF,   B1 = ((C1       ) & 0xFF) - B0;
             final int oldBase = base;
             do {
                 final float delta = index - base;
                 ARGB[i] = (roundByte(A0 + delta*A1) << 24) |
                           (roundByte(R0 + delta*R1) << 16) |
                           (roundByte(G0 + delta*G1) <<  8) |
                           (roundByte(B0 + delta*B1));
                 if (++i == upper) {
                     return;
                 }
                 index = (float) ((i - lower) * scale);
                 base = Math.min(maxBase, (int) (index + Math.ulp(index)));          // Really want rounding toward 0.
             } while (base == oldBase);
         }
     }
formatDescription()
static void formatDescription (final ColorSpace cs, final StringBuilder buffer) static
Appends a description of the given color space in the given buffer.
This is used for
toString()
method implementations.
Parameters
cs the color space to describe, or
null
.
buffer where to append the description.
Referenced by PlanarImage.toString().
{
         if (cs != null) {
             if (cs instanceof ScaledColorSpace) {
                 ((ScaledColorSpace) cs).formatRange(buffer.append("showing "));
             } else if (cs.getType() == ColorSpace.TYPE_GRAY) {
                 buffer.append("grayscale");
             }
         }
     }
getBitCount()
static int getBitCount (final int mapSize) static
Returns a bit count for an IndexColorModel mapping.
mapSize
colors. It is guaranteed that the following relation is hold:
{ java (1 << getBitCount(mapSize)) >= mapSize }
Parameters
mapSize the number of colors in the map.
Returns
the number of bits to use.
Referenced by ColorModelFactory.createIndexColorModel().
{
         final int count = Integer.SIZE - Integer.numberOfLeadingZeros(mapSize - 1);
         assert (1 << count) >= mapSize : mapSize;
         assert (1 << (count-1)) < mapSize : mapSize;
         return Math.max(1, count);
     }
getTransferType()
static int getTransferType (final int mapSize) static private
Returns a suggested type for an IndexColorModel of.
mapSize
colors. This method returns DataBuffer#TYPE_BYTE or DataBuffer#TYPE_USHORT.
Parameters
mapSize the number of colors in the map.
Returns
the suggested transfer type.
Referenced by ColorModelFactory.createIndexColorModel().
{
         return (mapSize <= 256) ? DataBuffer.TYPE_BYTE : DataBuffer.TYPE_USHORT;
     }
hashCode()
int hashCode ()
Public as an implementation side-effect.
Returns
a hash code.
References ColorModelFactory.ARGB, ColorModelFactory.numBands, ColorModelFactory.pieceStarts, and ColorModelFactory.visibleBand.
{
         final int categoryCount = pieceStarts.length - 1;
         int code = 962745549 + (numBands*31 + visibleBand)*31 + categoryCount;
         for (int i=0; i<categoryCount; i++) {
             code += Arrays.hashCode(ARGB[i]);
         }
         return code;
     }
isStandardRange()
static boolean isStandardRange (final int dataType, double minimum, final double maximum) static package
Returns.
true
if the given range of values is the standard range for the given data type. In such case it may be possible to use a Java standard color model, which sometime benefit from acceleration in Java2D rendering pipe.
This method does not clamp the given values to the maximum range supported by the given type. For example even if
TYPE_BYTE
can not represent values outside the [0 255] range, we do not clamp the minimum and maximum values to that range because it would change the visual appearance (because of different color scale).
Parameters
dataType one of DataBuffer constants.
minimum the minimal sample value expected.
maximum the maximal sample value expected.
Returns
whether the given minimum and maximum are the standard range for the given type.
Referenced by ColorModelFactory.createGrayScale(), and RasterFactory.createGrayScaleImage().
{
         final boolean signed;
         switch (dataType) {
             case DataBuffer.TYPE_BYTE:
             case DataBuffer.TYPE_USHORT: signed = false; break;
             case DataBuffer.TYPE_SHORT:
             case DataBuffer.TYPE_INT:    signed = true; break;
             case DataBuffer.TYPE_FLOAT:
             case DataBuffer.TYPE_DOUBLE: return ((float) minimum) == 0f && ((float) maximum) == 1f;
             default: return false;
         }
         final int numBits = DataBuffer.getDataTypeSize(dataType);
         final double upper;     // Exclusive (e.g. 256 or 65536)
         if (signed) {
             upper = 1L << (numBits - 1);        // E.g. 128 for TYPE_BYTE.
             minimum += upper;                   // Convert e.g. -128 to 0.
         } else {
             upper = 1L << numBits;              // E.g. 256 for TYPE_BYTE.
         }
         /*
          * Since sample values are integers, take a tolerance of 1. But for the upper bounds,
          * we take a slightly larger tolerance in case the caller confused "inclusive" versus
          * "exclusive" values. For example 255.5  1.5 accepts the |254.001  256.999] range.
          */
         return Math.abs(minimum) < 1 && Math.abs(maximum - (upper - 0.5)) < 1.5;
     }
roundByte()
static int roundByte (final float value) static private
Rounds a float value and clamps the result between 0 and 255 inclusive.
Parameters
value the value to round.
Returns
the rounded and clamped value.
Referenced by ColorModelFactory.expand().
{
         return Math.min(Math.max(Math.round(value), 0), 255);
     }
toARGB()
static int [] toARGB (final Color [] colors) static private
Returns the ARGB codes for the given colors.
If all colors are transparent, returns an empty array.
Parameters
colors the colors to convert to ARGB codes, or
null
.
Returns
ARGB codes for the given colors. Never
null
but may be empty.
References ColorModelFactory.ARGB.
Referenced by ColorModelFactory.ColorModelFactory().
{
         if (colors != null) {
             int combined = 0;
             final int[] ARGB = new int[colors.length];
             for (int i=0; i<ARGB.length; i++) {
                 final Color color = colors[i];
                 if (color != null) {
                     int c = color.getRGB();                         // Note: getRGB() is really getARGB().
                     combined |= c;
                     ARGB[i]   = c;
                 }
             }
             if ((combined & 0xFF000000) != 0) {
                 return ARGB;
             }
         }
         return ArraysExt.EMPTY_INT;
     }
unique()
static <T extends ColorModel> T unique (T cm) static
Returns a unique instance of the given color model.
This method is automatically invoked by
create()
methods in this class. This
unique(ColorModel)
method is public for use by color models created by other ways.
Parameters
<T> the type of the color model to share.
cm the color model for which to get a unique instance.
Returns
a unique (shared) instance of the given color model.
References ColorModelFactory.CACHE, and ColorModelPatch< T extends ColorModel >.cm.
Referenced by ColorModelFactory.createColorModel(), ColorModelFactory.createGrayScale(), and ColorModelFactory.createIndexColorModel().
{
         ColorModelPatch<T> c = new ColorModelPatch<>(cm);
         c = CACHE.unique(c);
         return c.cm;
     }
Member Data Documentation
ARGB
final int [][] ARGB private
The Alpha-Red-Green-Blue codes for all segments of the piecewise function.
This is
null
if pieceStarts is empty.
Referenced by ColorModelFactory.createColorModel(), ColorModelFactory.equals(), ColorModelFactory.hashCode(), and ColorModelFactory.toARGB().
CACHE
final WeakHashSet<ColorModelPatch> CACHE = new WeakHashSet<>(ColorModelPatch.class) static private
Shared instances of ColorModels.
Maintaining shared instance is not that much interesting for most kind of color models, except IndexColorModel which can potentially be quite big. This class works for all color models because they were no technical reasons to restrict, but the real interest is to share index color models.
See also
#unique(ColorModel)
Referenced by ColorModelFactory.unique().
GRAYSCALE
final Function<Category,Color[]> GRAYSCALE static
Initial value:
=
            (category) -> category.isQuantitative() ? new Color[] {Color.BLACK, Color.WHITE} : null
Applies a gray scale to quantitative category and transparent colors to qualitative categories.
This is a possible argument for createColorModel(SampleDimension[], int, int, Function).
Referenced by GridCoverage.createColorModel(), and GridCoverageBuilder2.setValues().
maximum
final double maximum package
Referenced by ColorModelFactory.ColorModelFactory(), ColorModelFactory.createColorModel(), and ColorModelFactory.equals().
minimum
final double minimum private
The minimum (inclusive) and maximum (exclusive) sample values.
Referenced by ColorModelFactory.ColorModelFactory(), ColorModelFactory.createColorModel(), and ColorModelFactory.equals().
numBands
final int numBands private
The number of bands (usually 1) used for the construction of a single instance of a ColorModel.
Referenced by ColorModelFactory.ColorModelFactory(), ColorModelFactory.createColorModel(), ColorModelFactory.equals(), and ColorModelFactory.hashCode().
pieceStarts
final int [] pieceStarts private
In a color map defined by a piecewise function, indices where to store the first interpolated value in the color map.
The number of pieces (segments) is
pieceStarts.length
. The last element of this array is the index after the end of the last piece. The indices are integers. Never
null
but may be empty.
Note: indices as unsigned short are not sufficient since in the worst case the last next index will be 65536, which would be converted to 0 as a short, causing several exception afterward.
Referenced by ColorModelFactory.createColorModel(), ColorModelFactory.equals(), and ColorModelFactory.hashCode().
PIECEWISES
final Map<ColorModelFactory,ColorModel> PIECEWISES = new WeakValueHashMap<>(ColorModelFactory.class) static private
A pool of color models previously created by createColorModel().
Note: we use java.lang.ref.WeakReference weak references} instead of java.lang.ref.SoftReference soft references} because the intent is not to cache the values. The intent is to share existing instances in order to reduce memory usage. Rational:
ColorModel may consume a lot of memory. A 16 bits indexed color model can consume up to 256 kb. We do not want to retain such large objects longer than necessary. We want to share existing instances without preventing the garbage collector to collect them.
createColorModel() is reasonably fast if invoked only occasionally, so it is not worth consuming 256 kb for saving the few milliseconds requiring for building a new color model. Client code should retains their own reference to a ColorModel if they plan to reuse it often in a short period of time.
Referenced by ColorModelFactory.createColorModel().
RANGE_COMPARATOR
final Comparator<Map.Entry<NumberRange<?>, Color[]> > RANGE_COMPARATOR static private
Initial value:
=
            (r1, r2) -> Double.compare(r1.getKey().getMinDouble(true),
                                       r2.getKey().getMinDouble(true))
Comparator for sorting ranges by their minimal value.
Referenced by ColorModelFactory.ColorModelFactory().
TRANSPARENT
final Color TRANSPARENT = new Color(0, true) static
The fully transparent color.
type
final int type private
The color model type.
One of the following types:
DataBuffer#TYPE_BYTE or DataBuffer#TYPE_USHORT: will create a IndexColorModel (unless grayscale).
DataBuffer#TYPE_FLOAT or DataBuffer#TYPE_DOUBLE: will create a ComponentColorModel.
DataBuffer#TYPE_INT: should create a PackedColorModel according java.awt.image.Raster javadoc (for compatibility with
Raster.createPackedRaster()
), but we nevertheless create ComponentColorModel for the 1-banded sample model created by RasterFactory.
Todo:
The user may want to set explicitly the number of bits each pixel occupies. We need to think about an API to allows that.
Referenced by ColorModelFactory.ColorModelFactory(), ColorModelFactory.createColorModel(), ColorModelFactory.createIndexColorModel(), and ColorModelFactory.equals().
visibleBand
final int visibleBand private
The visible band (usually 0) used for the construction of a single instance of a ColorModel.
Referenced by ColorModelFactory.ColorModelFactory(), ColorModelFactory.createColorModel(), ColorModelFactory.equals(), and ColorModelFactory.hashCode().