jena-geo: MultiBandsIndexColorModel Class Reference
MultiBandsIndexColorModel Class Reference
An IndexColorModel tolerant with image having more than one band.
Public Member Functions
MultiBandsIndexColorModel (final int bits, final int size, final int[] cmap, final int start, final boolean hasAlpha, final int transparent, final int transferType, final int numBands, final int visibleBand)
Constructs an index color model with the specified properties.
Object getDataElements (final int RGB, Object pixel)
Converts a RGB color to a representation of a pixel in this color model.
int [] getComponents (final Object pixel, final int[] components, final int offset)
Returns an array of unnormalized color/alpha components for a specified pixel in this color model.
int getRed (final Object inData)
Returns the red color component for the specified pixel, scaled from 0 to 255 in the default RGB.
int getGreen (final Object inData)
Returns the green color component for the specified pixel, scaled from 0 to 255 in the default RGB.
int getBlue (final Object inData)
Returns the blue color component for the specified pixel, scaled from 0 to 255 in the default RGB.
int getAlpha (final Object inData)
Returns the alpha component for the specified pixel, scaled from 0 to 255.
WritableRaster createCompatibleWritableRaster (final int width, final int height)
Creates a.
SampleModel createCompatibleSampleModel (final int width, final int height)
Creates a.
boolean isCompatibleRaster (final Raster raster)
Returns.
boolean isCompatibleSampleModel (final SampleModel sm)
Checks if the specified.
Package Attributes
final int numBands
The number of bands.
final int visibleBand
The visible band.
Private Member Functions
int pixel (final Object inData)
Returns the pixel value as an integer.
Detailed Description
An IndexColorModel tolerant with image having more than one band.
This class can support only the types supported by
IndexColorModel
parent class. As of Java 10 they are restricted to DataBuffer#TYPE_BYTE and
DataBuffer#TYPE_USHORT
.
Reminder: getNumComponents() will returns 3 or 4 no matter how many bands were specified to the constructor. This is not specific to this class;
IndexColorModel
behave that way. So we can't rely on this method for checking the number of bands.
Author
Martin Desruisseaux (IRD, Geomatys)
Andrea Aime (TOPP)
Version
1.0
Since
1.0
Constructor & Destructor Documentation
MultiBandsIndexColorModel()
MultiBandsIndexColorModel (final int bits, final int size, final int [] cmap, final int start, final boolean hasAlpha, final int transparent, final int transferType, final int numBands, final int visibleBand)
Constructs an index color model with the specified properties.
Parameters
bits the number of bits each pixel occupies.
size the size of the color component arrays.
cmap the array of color components.
start the starting offset of the first color component.
hasAlpha indicates whether alpha values are contained in the
cmap
array.
transparent The index of the fully transparent pixel.
transferType The data type of the array used to represent pixel values.
numBands the number of bands.
visibleBand the band to display.
Exceptions
IllegalArgumentException if
bits
is less than 1 or greater than 16.
IllegalArgumentException if
size
is less than 1.
IllegalArgumentException if
transferType
is not one of
DataBuffer.TYPE_BYTE
or
DataBuffer.TYPE_USHORT
.
References MultiBandsIndexColorModel.numBands, and MultiBandsIndexColorModel.visibleBand.
     {
         super(bits, size, cmap, start, hasAlpha, transparent, transferType);
         this.numBands    = numBands;
         this.visibleBand = visibleBand;
     }
Member Function Documentation
createCompatibleSampleModel()
SampleModel createCompatibleSampleModel (final int width, final int height)
Creates a.
SampleModel
with the specified width and height that has a data layout compatible with this
ColorModel
.
References RasterFactory.unique().
{
         return RasterFactory.unique(new BandedSampleModel(transferType, width, height, numBands));
     }
createCompatibleWritableRaster()
WritableRaster createCompatibleWritableRaster (final int width, final int height)
Creates a.
WritableRaster
with the specified width and height that has a data layout (
SampleModel
) compatible with this
ColorModel
.
The difference with standard implementation is that this method creates a banded raster on the assumption that the number of bands is greater than 1. By contrast, the standard implementation provides various optimizations for one-banded raster.
{
         return Raster.createBandedRaster(transferType, width, height, numBands, null);
     }
getAlpha()
int getAlpha (final Object inData)
Returns the alpha component for the specified pixel, scaled from 0 to 255.
References MultiBandsIndexColorModel.pixel().
{
         return getAlpha(pixel(inData));
     }
getBlue()
int getBlue (final Object inData)
Returns the blue color component for the specified pixel, scaled from 0 to 255 in the default RGB.
ColorSpace
.
References MultiBandsIndexColorModel.pixel().
{
         return getBlue(pixel(inData));
     }
getComponents()
int [] getComponents (final Object pixel, final int [] components, final int offset)
Returns an array of unnormalized color/alpha components for a specified pixel in this color model.
This method is the converse of getDataElements(int, Object).
References MultiBandsIndexColorModel.pixel().
{
         return getComponents(pixel(components), components, offset);
     }
getDataElements()
Object getDataElements (final int RGB, Object pixel)
Converts a RGB color to a representation of a pixel in this color model.
This method returns an array with a length equal to the number of bands specified to the constructor (
IndexColorModel
would returns an array of length 1). All array elements are set to the same value. Replicating the pixel value is a somewhat arbitrary choice, but this choice makes this image appears as a gray scale image if the underlying DataBuffer were displayed again with a RGB color model instead of this one. Such a gray scale image seems more neutral than an image where only the Red component would vary.
All other
getDataElement(…)
methods in this color model are ultimately defined in terms of this method, so overriding this method if needed should be enough.
References MultiBandsIndexColorModel.numBands, and MultiBandsIndexColorModel.pixel().
{
         if (pixel == null) {
             switch (transferType) {
                 case DataBuffer.TYPE_SHORT:  // Handled as a matter of principle.
                 case DataBuffer.TYPE_USHORT: pixel = new short[numBands]; break;
                 case DataBuffer.TYPE_BYTE:   pixel = new byte [numBands]; break;
                 case DataBuffer.TYPE_INT:    pixel = new int  [numBands]; break;
             }
         }
         pixel = super.getDataElements(RGB, pixel);
         switch (transferType) {
             case DataBuffer.TYPE_BYTE: {
                 final byte[] array = (byte[]) pixel;
                 Arrays.fill(array, 1, numBands, array[0]);
                 break;
             }
             case DataBuffer.TYPE_SHORT:      // Handled as a matter of principle.
             case DataBuffer.TYPE_USHORT: {
                 final short[] array = (short[]) pixel;
                 Arrays.fill(array, 1, numBands, array[0]);
                 break;
             }
             case DataBuffer.TYPE_INT: {
                 final int[] array = (int[]) pixel;
                 Arrays.fill(array, 1, numBands, array[0]);
                 break;
             }
         }
         return pixel;
     }
getGreen()
int getGreen (final Object inData)
Returns the green color component for the specified pixel, scaled from 0 to 255 in the default RGB.
ColorSpace
.
References MultiBandsIndexColorModel.pixel().
{
         return getGreen(pixel(inData));
     }
getRed()
int getRed (final Object inData)
Returns the red color component for the specified pixel, scaled from 0 to 255 in the default RGB.
ColorSpace
.
References MultiBandsIndexColorModel.pixel().
{
         return getRed(pixel(inData));
     }
isCompatibleRaster()
boolean isCompatibleRaster (final Raster raster)
Returns.
true
if
raster
is compatible with this
ColorModel
. This method performs the same checks than the standard implementation except for the number of bands, which is required to be equal to numBands instead than 1. The actual checks are delegated to isCompatibleSampleModel(SampleModel) instead than duplicated in this method.
References MultiBandsIndexColorModel.isCompatibleSampleModel().
{
         return isCompatibleSampleModel(raster.getSampleModel());
     }
isCompatibleSampleModel()
boolean isCompatibleSampleModel (final SampleModel sm)
Checks if the specified.
SampleModel
is compatible with this
ColorModel
. This method performs the same checks than the standard implementation except for the number of bands and for not accepting
MultiPixelPackedSampleModel
.
Referenced by MultiBandsIndexColorModel.isCompatibleRaster().
{
         return (sm instanceof ComponentSampleModel)                  &&
                 sm.getTransferType()                 == transferType &&
                 sm.getNumBands()                     == numBands     &&
                 (1 << sm.getSampleSize(visibleBand)) >= getMapSize();
     }
pixel()
int pixel (final Object inData) private
Returns the pixel value as an integer.
References MultiBandsIndexColorModel.visibleBand.
Referenced by MultiBandsIndexColorModel.getAlpha(), MultiBandsIndexColorModel.getBlue(), MultiBandsIndexColorModel.getComponents(), MultiBandsIndexColorModel.getDataElements(), MultiBandsIndexColorModel.getGreen(), and MultiBandsIndexColorModel.getRed().
{
         switch (transferType) {
             case DataBuffer.TYPE_BYTE:   return  Byte.toUnsignedInt( ((byte[]) inData)[visibleBand]);
             case DataBuffer.TYPE_USHORT: return Short.toUnsignedInt(((short[]) inData)[visibleBand]);
             case DataBuffer.TYPE_SHORT:  return                     ((short[]) inData)[visibleBand];
             case DataBuffer.TYPE_INT:    return                       ((int[]) inData)[visibleBand];
             default: throw new UnsupportedOperationException();
         }
     }
Member Data Documentation
numBands
final int numBands package
The number of bands.
Referenced by ColorModelPatch< T extends ColorModel >.equals(), MultiBandsIndexColorModel.getDataElements(), and MultiBandsIndexColorModel.MultiBandsIndexColorModel().
visibleBand
final int visibleBand package
The visible band.
Referenced by ColorModelPatch< T extends ColorModel >.equals(), MultiBandsIndexColorModel.MultiBandsIndexColorModel(), and MultiBandsIndexColorModel.pixel().