jena-geo: TileOpExecutor.Cursor< RI extends RenderedImage, A > Class Template Reference
TileOpExecutor.Cursor< RI extends RenderedImage, A > Class Template Reference
Tile indices of the next tile to process in a multi-threaded computation.
Public Member Functions
String toString ()
Returns a string representation of this cursor for debugging purposes.
Package Functions
Cursor (final RI image, final Collector<?, A,?> collector, final boolean stopOnError)
Creates a new cursor initialized to the indices of the first tile.
final int getNumWorkers ()
Returns the suggested number of worker threads to create, excluding the current thread.
final boolean next (final Worker< RI,?, A > indices)
Sets the given worker to the indices of the next tile.
final void accumulate (final A result)
Invoked when a thread finished to process all its tiles for combining its result with the result of previous threads.
final< R > R finish (final Future<?>[] workers, final Collector<?, A, R > collector, final Consumer< LogRecord > errorHandler)
Invoked after the current thread finished to process all its tiles.
final void recordError (final Worker< RI,?, A > indices, final Throwable ex)
Stores the given exception in a log record.
Package Attributes
final RI image
The image from which to read tiles or where to write tiles.
Private Attributes
final int numXTiles
The number of tiles in a row of the area of interest.
final BinaryOperator< A > combiner
The operation to execute after a thread finished to process all its tiles, for combining its result with the result of another thread.
A accumulator
The cumulated result of all threads.
LogRecord errors
The errors that occurred while computing a tile, or.
final boolean stopOnError
Whether to stop of the first error.
Detailed Description
Tile indices of the next tile to process in a multi-threaded computation.
When a computation is splitted between many threads, all workers will share a reference to the same Cursor instance for fetching the indices of the next tile in iteration order no matter if requested by the same or different threads. We do that on the assumption that if calls to RenderedImage#getTile(int, int) causes read operations from a file, iteration order corresponds to consecutive tiles in the file and those tiles are loaded more efficiently with sequential read operations.
Current implementation uses row major iteration. A future version could use an image property giving the preferred iteration order (possibly as a list or an array of tile indices). When there is no indication about the preferred iteration order, a future version could possible uses Hilbert iterator for processing nearby tiles together (assuming they are more likely to have been computed at a near instant).
Parameters
<RI> RenderedImage or WritableRenderedImage.
<A> type of the thread-local object (the accumulator) for holding intermediate results.
Constructor & Destructor Documentation
Cursor()
Cursor (final RI image, final Collector<?, A,?> collector, final boolean stopOnError) package
Creates a new cursor initialized to the indices of the first tile.
Parameters
image the image to read or the image where to write.
collector provides the combiner of thread-local objects of type A.
stopOnError whether to stop of the first error or to process all tiles before to report the error.
{
             this.image       = image;
             this.combiner    = collector.combiner();
             this.numXTiles   = Math.incrementExact(Math.subtractExact(maxTileX, minTileX));
             this.stopOnError = stopOnError;
         }
Member Function Documentation
accumulate()
final void accumulate (final A result) package
Invoked when a thread finished to process all its tiles for combining its result with the result of previous threads.
This method does nothing if the given result is null.
Parameters
result the result computed in current thread (may be
null
).
Referenced by TileOpExecutor.Worker< WritableRenderedImage, WritableRaster, A >.run().
{
             if (result != null) {
                 synchronized (this) {
                     accumulator = (accumulator == null) ? result : combiner.apply(accumulator, result);
                 }
             }
         }
finish()
final<R> R finish (final Future<?> [] workers, final Collector<?, A, R > collector, final Consumer< LogRecord > errorHandler) package
Invoked after the current thread finished to process all its tiles.
If some other threads are still computing their tiles, this method waits for those threads to complete (each thread has at most one tile to complete). After all threads completed, this method computes the final result and reports the errors if any.
Parameters
<R> the final type of the result. This is often the same type than A.
workers handlers of all worker threads other than the current threads. Content of this array may be modified by this method.
collector provides the finisher to use for computing final result of type R.
errorHandler where to report exceptions, or
null
for throwing them.
Returns
the final result computed by finisher (may be
null
).
Exceptions
ImagingOpException if an exception occurred during Worker#executeOnCurrentTile() and the
errorHandler
is
null
.
RuntimeException if an exception occurred elsewhere (for example in the combiner or finisher).
{
             /*
              * Before to wait for other threads to complete their work, we need to remove from executor queue all
              * workers that did not yet started their run. Those threads may be waiting for an executor thread to
              * become available, which may never happen if all threads are waiting for a non-running task.
              */
             for (int i=0; i<workers.length; i++) {
                 if (CommonExecutor.unschedule(workers[i])) {
                     workers[i] = null;
                 }
             }
             for (final Future<?> task : workers) try {
                 if (task != null) task.get();
             } catch (ExecutionException ex) {
                 /*
                  * This is not an exception that occurred in Worker.executeOnCurrentTile(), RenderedImage.getTile(…)
                  * or similar methods, otherwise it would have been handled by Worker.run(). This is an error or an
                  * exception that occurred elsewhere, for example in the combiner, in which case we do not wrap it
                  * in an ImagingOpException.
                  */
                 throw Worker.rethrowOrWrap(ex.getCause());
             } catch (InterruptedException ex) {
                 /*
                  * If someone does not want to let us wait, do not wait for other worker threads neither.
                  * We will report that interruption as an error.
                  */
                 synchronized (this) {
                     if (errors == null) {
                         errors = new LogRecord(Level.WARNING, ex.toString());
                         errors.setThrown(ex);
                     } else {
                         errors.getThrown().addSuppressed(ex);
                     }
                 }
                 break;
             }
             /*
              * Computes final result. The synchronization below should not be necessary since all threads
              * finished their work, unless an `InterruptedException` has been caught above in which case
              * it is possible that a few threads are still running.
              */
             final R result;
             synchronized (this) {
                 result = collector.finisher().apply(accumulator);
                 if (errors != null) {
                     if (errorHandler != null) {
                         errorHandler.accept(errors);
                     } else {
                         final Throwable ex = trimImagingWrapper(errors.getThrown());
                         final String message = new SimpleFormatter().formatMessage(errors);
                         throw (ImagingOpException) new ImagingOpException(message).initCause(ex);
                     }
                 }
             }
             return result;
         }
getNumWorkers()
final int getNumWorkers () package
Returns the suggested number of worker threads to create, excluding the current thread.
This method always returns a value at least one 1 less than the number of tiles because the current thread will be itself a worker.
Referenced by TileOpExecutor.ReadWork< A >.execute(), and TileOpExecutor.WriteWork< A >.execute().
{
             return Math.max((int) Math.min(CommonExecutor.PARALLELISM, numXTiles * (((long) maxTileY) - minTileY + 1) - 1), 0);
         }
next()
final boolean next (final Worker< RI,?, A > indices) package
Sets the given worker to the indices of the next tile.
This method is invoked by all worker thread before each new tile to process. We return tiles in iteration order, regardless which thread is requesting for next tile, for the reasons documented in Cursor javadoc.
Parameters
indices the worker where to update Worker#tx and Worker#ty indices.
Returns
true
if the tile at the updated indices should be processed, or
false
if there is no more tile to process.
Referenced by TileOpExecutor.Worker< WritableRenderedImage, WritableRaster, A >.run().
{
             final int index = getAndIncrement();
             if (index >= 0) {
                 indices.tx = Math.addExact(minTileX, index % numXTiles);
                 indices.ty = Math.addExact(minTileY, index / numXTiles);
                 return indices.ty <= maxTileY;
             }
             return false;
         }
recordError()
final void recordError (final Worker< RI,?, A > indices, final Throwable ex) package
Stores the given exception in a log record.
We use a log record in order to initialize the timestamp and thread ID to the values they had at the time the first error occurred.
Parameters
indices the worker thread where the exception occurred. Its Worker#tx and Worker#ty indices should identify the problematic tile.
ex the exception that occurred.
Referenced by TileOpExecutor.Worker< WritableRenderedImage, WritableRaster, A >.run().
{
             if (stopOnError) {
                 set(Integer.MIN_VALUE);         // Will cause other threads to stop fetching tiles.
             }
             synchronized (this) {
                 if (errors == null) {
                     errors = Resources.forLocale((Locale) null).getLogRecord(Level.WARNING,
                              Resources.Keys.CanNotProcessTile_2, indices.tx, indices.ty);
                     errors.setThrown(ex);
                 } else {
                     errors.getThrown().addSuppressed(ex);
                 }
             }
         }
toString()
String toString ()
Returns a string representation of this cursor for debugging purposes.
{
             final int index = get();
             String tile = "done";
             if (index >= 0) {
                 final int tx = Math.addExact(minTileX, index % numXTiles);
                 final int ty = Math.addExact(minTileY, index / numXTiles);
                 if (ty <= maxTileY) {
                     tile = "(" + tx + ", " + ty + ')';
                 }
             }
             return Strings.toString(getClass(),
                     "image",      Classes.getShortClassName(image),
                     "numWorkers", getNumWorkers(),
                     "tile",       tile);
         }
Member Data Documentation
accumulator
A accumulator private
The cumulated result of all threads.
Every time a thread finishes its work, it calls accumulate(Object) for combining its result with previous value that may exist in this field.
See also
combiner
#accumulate(Object)
Referenced by TileOpExecutor.Worker< WritableRenderedImage, WritableRaster, A >.Worker().
combiner
final BinaryOperator<A> combiner private
The operation to execute after a thread finished to process all its tiles, for combining its result with the result of another thread.
See also
accumulator
#accumulate(Object)
errors
LogRecord errors private
The errors that occurred while computing a tile, or.
null
if none.
See also
stopOnError
#recordError(Worker, Throwable)
image
final RI image package
The image from which to read tiles or where to write tiles.
In the later case, must be an instance of WritableRenderedImage.
Referenced by TileOpExecutor.ReadWork< A >.executeOnCurrentTile(), and TileOpExecutor.WriteWork< A >.executeOnCurrentTile().
numXTiles
final int numXTiles private
The number of tiles in a row of the area of interest.
See also
#next(Worker)
stopOnError
final boolean stopOnError private
Whether to stop of the first error.
If
true
the error will be reported as soon as possible. If
false
, processing of all tiles will be completed before the error is reported.
See also
errors
#recordError(Worker, Throwable)