jena-geo: PlanarImage Class Reference
PlanarImage Class Reference abstract
Base class of RenderedImage implementations in Apache SIS.
Public Member Functions
Vector< RenderedImage > getSources ()
Returns the immediate sources of image data for this image.
Object getProperty (String key)
Gets a property from this image.
String [] getPropertyNames ()
Returns the names of all recognized properties, or.
Rectangle getBounds ()
Returns the image location (x, y) and image size (width, height).
int getMinX ()
Returns the minimum x coordinate (inclusive) of this image.
int getMinY ()
Returns the minimum y coordinate (inclusive) of this image.
int getMinTileX ()
Returns the minimum tile index in the x direction.
int getMinTileY ()
Returns the minimum tile index in the y direction.
int getNumXTiles ()
Returns the number of tiles in the x direction.
int getNumYTiles ()
Returns the number of tiles in the y direction.
int getTileGridXOffset ()
Returns the x coordinate of the upper-left pixel of tile (0, 0).
int getTileGridYOffset ()
Returns the y coordinate of the upper-left pixel of tile (0, 0).
Raster getData ()
Returns a copy of this image as one large tile.
Raster getData (final Rectangle aoi)
Returns a copy of an arbitrary region of this image.
WritableRaster copyData (WritableRaster raster)
Copies an arbitrary rectangular region of this image to the supplied writable raster.
String verify ()
Verifies whether image layout information are consistent.
String toString ()
Returns a string representation of this image for debugging purpose.
Static Public Attributes
static final String SAMPLE_RESOLUTIONS_KEY = "SampleResolution"
Key of a property defining the resolutions of sample values in each band.
Protected Member Functions
PlanarImage ()
Creates a new rendered image.
Private Member Functions
WritableRaster createWritableRaster (final Rectangle aoi)
Creates a raster with the same sample model than this image and with the given size and location.
void copyData (final Rectangle aoi, final WritableRaster raster)
Implementation of getData(), getData(Rectangle) and copyData(WritableRaster).
Detailed Description
Base class of RenderedImage implementations in Apache SIS.
The "Planar" part in the class name emphases that this image is a representation of two-dimensional data and should not contain an image with three-dimensional effects. Planar images can be used as data storage for org.apache.sis.coverage.grid.GridCoverage2D.
Note: inspirational source
This class takes some inspiration from the
javax.media.jai.PlanarImage
class defined in the <cite>Java Advanced Imaging</cite> (<abbr>JAI</abbr>) library. That excellent library was 20 years in advance on thematic like defining a chain of image operations, multi-threaded execution, distribution over a computer network, etc. But unfortunately the <abbr>JAI</abbr> library does not seems to be maintained anymore. We do not try to reproduce the full set of JAI functionalities here, but we progressively reproduce some little bits of functionalities as they are needed by Apache SIS.
This base class does not store any state, but assumes that numbering of pixel coordinates and tile indices start at zero. Subclasses need to implement at least the following methods:
getWidth() — the image width in pixels.
getHeight() — the image height in pixels.
getTileWidth() — the tile width in pixels.
getTileHeight() — the tile height in pixels.
getTile(int,int) — the tile at given tile indices.
If pixel coordinates or tile indices do not start at zero, then subclasses shall also override the following methods:
getMinX() — the minimum x coordinate (inclusive) of the image.
getMinY() — the minimum y coordinate (inclusive) of the image.
getMinTileX() — the minimum tile index in the x direction.
getMinTileY() — the minimum tile index in the y direction.
Default implementations are provided for getNumXTiles(), getNumYTiles(), getTileGridXOffset(), getTileGridYOffset(), getData(), getData(Rectangle) and copyData(WritableRaster) in terms of above methods.
Writable images
Some subclasses may implement the WritableRenderedImage interface. If this image is writable, then the WritableRenderedImage​.getWritableTile(…) and releaseWritableTile(…) methods should be invoked in
try ... finally
blocks like below:
{ java WritableRenderedImage image = ...; WritableRaster tile = image.getWritableTile(tileX, tileY); try { // Do some process on the tile. } finally { image.releaseWritableTile(tileX, tileY); } }
This is recommended because implementations may count the number of acquisitions and releases for deciding when to notify the java.awt.image.TileObservers. Some implementations may also acquire and release synchronization locks in the
getWritableTile(…)
and
releaseWritableTile(…)
methods. Apache SIS does not yet define a synchronization policy for WritableRenderedImage, but such policy may be defined in a future version.
Author
Johann Sorel (Geomatys)
Martin Desruisseaux (Geomatys)
Version
1.1
Since
1.1
Constructor & Destructor Documentation
PlanarImage()
PlanarImage () protected
Creates a new rendered image.
{
     }
Member Function Documentation
copyData() [1/2]
WritableRaster copyData (WritableRaster raster)
Copies an arbitrary rectangular region of this image to the supplied writable raster.
The region to be copied is determined from the bounds of the supplied raster. The supplied raster must have a SampleModel that is compatible with this image. If the raster is
null
, an raster is created by this method.
Parameters
raster the raster to hold a copy of this image, or
null
.
Returns
the given raster if it was not-null, or a new raster otherwise.
References PlanarImage.createWritableRaster(), and ImageUtilities.getBounds().
Referenced by PlanarImage.getData().
{
         final Rectangle aoi;
         if (raster != null) {
             aoi = raster.getBounds();
         } else {
             aoi = ImageUtilities.getBounds(this);
             raster = createWritableRaster(aoi);
         }
         copyData(aoi, raster);
         return raster;
     }
copyData() [2/2]
void copyData (final Rectangle aoi, final WritableRaster raster) private
Implementation of getData(), getData(Rectangle) and copyData(WritableRaster).
It is caller responsibility to ensure that all arguments are non-null and that the rectangle is contained inside both this image and the given raster.
Parameters
aoi the region of this image to copy.
raster the raster to hold a copy of this image, or
null
.
For copying data using data type specified by raster.
For detecting if buffer size is sufficient.
Invoked for each tile to copy to target raster.
References ImageUtilities.prepareTransferRegion(), and TileOpExecutor.readFrom().
{
         /*
          * Iterate over all tiles that interesect the area of interest. For each tile,
          * copy a few rows in a temporary buffer, then copy that buffer to destination.
          * The buffer will be reused for each transfer, unless its size is insufficient.
          * Note that `tb` should never be empty since we restrict iteration to the tiles
          * that intersect the given area of interest.
          */
         final TileOpExecutor executor = new TileOpExecutor(this, aoi) { private Object buffer; private int bufferCapacity;
             @Override protected void readFrom(final Raster tile) {
                 final Rectangle tb = aoi.intersection(tile.getBounds());        // Bounds of transfer buffer.
                 final int afterLastRow = ImageUtilities.prepareTransferRegion(tb, tile.getTransferType());
                 final int transferCapacity = tb.width * tb.height;
                 if (transferCapacity > bufferCapacity) {
                     bufferCapacity = transferCapacity;
                     buffer = null;                          // Will be allocated by Raster.getDataElements(…).
                 }
                 while (tb.y < afterLastRow) {
                     final int height = Math.min(tb.height, afterLastRow - tb.y);
                     buffer = tile.getDataElements(tb.x, tb.y, tb.width, height, buffer);
                     raster.setDataElements(tb.x, tb.y, tb.width, height, buffer);
                     tb.y += height;
                 }
             }
         };
         executor.readFrom(this);
     }
createWritableRaster()
WritableRaster createWritableRaster (final Rectangle aoi) private
Creates a raster with the same sample model than this image and with the given size and location.
This method does not verify argument validity.
Referenced by PlanarImage.copyData(), and PlanarImage.getData().
{
         SampleModel sm = getSampleModel();
         if (sm.getWidth() != aoi.width || sm.getHeight() != aoi.height) {
             sm = sm.createCompatibleSampleModel(aoi.width, aoi.height);
         }
         return Raster.createWritableRaster(sm, aoi.getLocation());
     }
getBounds()
Rectangle getBounds ()
Returns the image location (x, y) and image size (width, height).
This is a convenience method encapsulating the results of 4 method calls in a single object.
Returns
the image location and image size as a new rectangle.
See also
getMinX()
getMinY()
#getWidth()
#getHeight()
References ImageUtilities.getBounds().
{
         return ImageUtilities.getBounds(this);
     }
getData() [1/2]
Raster getData ()
Returns a copy of this image as one large tile.
The returned raster will not be updated if this image is changed.
Returns
a copy of this image as one large tile.
References PlanarImage.copyData(), PlanarImage.createWritableRaster(), and ImageUtilities.getBounds().
{
         final Rectangle aoi = ImageUtilities.getBounds(this);
         final WritableRaster raster = createWritableRaster(aoi);
         copyData(aoi, raster);
         return raster;
     }
getData() [2/2]
Raster getData (final Rectangle aoi)
Returns a copy of an arbitrary region of this image.
The returned raster will not be updated if this image is changed.
Parameters
aoi the region of this image to copy.
Returns
a copy of this image in the given area of interest.
Exceptions
IllegalArgumentException if the given rectangle is not contained in this image bounds.
References PlanarImage.copyData(), PlanarImage.createWritableRaster(), and ImageUtilities.getBounds().
{
         ArgumentChecks.ensureNonNull("aoi", aoi);
         if (!ImageUtilities.getBounds(this).contains(aoi)) {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.OutsideDomainOfValidity));
         }
         final WritableRaster raster = createWritableRaster(aoi);
         copyData(aoi, raster);
         return raster;
     }
getMinTileX()
int getMinTileX ()
Returns the minimum tile index in the x direction.
The default implementation returns zero. Subclasses shall override this method if the tile grid starts at another index.
Returns
the minimum tile index in the x direction.
Referenced by PlanarImage.getTileGridXOffset(), and PlanarImage.verify().
{
         return 0;
     }
getMinTileY()
int getMinTileY ()
Returns the minimum tile index in the y direction.
The default implementation returns zero. Subclasses shall override this method if the tile grid starts at another index.
Returns
the minimum tile index in the y direction.
Referenced by PlanarImage.getTileGridYOffset(), and PlanarImage.verify().
{
         return 0;
     }
getMinX()
int getMinX ()
Returns the minimum x coordinate (inclusive) of this image.
Default implementation returns zero. Subclasses shall override this method if the image starts at another coordinate.
Returns
the minimum x coordinate (column) of this image.
Referenced by PlanarImage.getTileGridXOffset(), and PlanarImage.verify().
{
         return 0;
     }
getMinY()
int getMinY ()
Returns the minimum y coordinate (inclusive) of this image.
The default implementation returns zero. Subclasses shall override this method if the image starts at another coordinate.
Returns
the minimum y coordinate (row) of this image.
Referenced by PlanarImage.getTileGridYOffset(), and PlanarImage.verify().
{
         return 0;
     }
getNumXTiles()
int getNumXTiles ()
Returns the number of tiles in the x direction.
The default implementation computes this value from getWidth() and getTileWidth() on the assumption that getMinX() is the coordinate of the leftmost pixels of tiles located at getMinTileX() index. This assumption can be verified by verify().
Returns
returns the number of tiles in the x direction.
Referenced by TiledImage.getTile(), PlanarImage.toString(), and PlanarImage.verify().
{
         /*
          * If assumption documented in javadoc does not hold, the calculation performed here would need to be
          * more complicated: compute tile index of minX, compute tile index of maxX, return difference plus 1.
          */
         return Numerics.ceilDiv(getWidth(), getTileWidth());
     }
getNumYTiles()
int getNumYTiles ()
Returns the number of tiles in the y direction.
The default implementation computes this value from getHeight() and getTileHeight() on the assumption that getMinY() is the coordinate of the uppermost pixels of tiles located at getMinTileY() index. This assumption can be verified by verify().
Returns
returns the number of tiles in the y direction.
Referenced by TiledImage.getTile(), PlanarImage.toString(), and PlanarImage.verify().
{
         return Numerics.ceilDiv(getHeight(), getTileHeight());
     }
getProperty()
Object getProperty (String key)
Gets a property from this image.
The property to get is identified by the specified key. Some keys supported by Apache SIS are:
Recognized property keys
Keys Values
{ SAMPLE_RESOLUTIONS_KEY} Resolutions of sample values in each band.
This method returns Image#UndefinedProperty if the specified property is not defined. The default implementation returns Image#UndefinedProperty in all cases.
Parameters
key the name of the property to get.
Returns
the property value, or Image#UndefinedProperty if none.
{
         return Image.UndefinedProperty;
     }
getPropertyNames()
String [] getPropertyNames ()
Returns the names of all recognized properties, or.
null
if this image has no properties.
The default implementation returns
null
.
Returns
names of all recognized properties, or
null
if none.
{
         return null;
     }
getSources()
Vector<RenderedImage> getSources ()
Returns the immediate sources of image data for this image.
This method returns
null
if the image has no information about its immediate sources. It returns an empty vector if the image object has no immediate sources.
The default implementation returns
null
. Note that this is not equivalent to an empty vector.
Returns
the immediate sources, or
null
if unknown.
{
         return null;
     }
getTileGridXOffset()
int getTileGridXOffset ()
Returns the x coordinate of the upper-left pixel of tile (0, 0).
That tile (0, 0) may not actually exist.
The default implementation computes this value from getMinX(), getMinTileX() and getTileWidth().
Returns
the x offset of the tile grid relative to the origin.
References PlanarImage.getMinTileX(), and PlanarImage.getMinX().
Referenced by PlanarImage.verify().
{
         // We may have temporary `int` overflow after multiplication but exact result after addition.
         return Math.toIntExact(getMinX() - JDK9.multiplyFull(getMinTileX(), getTileWidth()));
     }
getTileGridYOffset()
int getTileGridYOffset ()
Returns the y coordinate of the upper-left pixel of tile (0, 0).
That tile (0, 0) may not actually exist.
The default implementation computes this value from getMinY(), getMinTileY() and getTileHeight().
Returns
the y offset of the tile grid relative to the origin.
References PlanarImage.getMinTileY(), and PlanarImage.getMinY().
Referenced by PlanarImage.verify().
{
         return Math.toIntExact(getMinY() - JDK9.multiplyFull(getMinTileY(), getTileHeight()));
     }
toString()
String toString ()
Returns a string representation of this image for debugging purpose.
This string representation may change in any future SIS version.
Returns
a string representation of this image for debugging purpose only.
References ColorModelFactory.formatDescription(), ImageUtilities.getDataTypeName(), PlanarImage.getNumXTiles(), PlanarImage.getNumYTiles(), and PlanarImage.verify().
{
         final StringBuilder buffer = new StringBuilder(100).append(Classes.getShortClassName(this))
                 .append('[').append(getWidth()).append(" × ").append(getHeight()).append(" pixels");
         final SampleModel sm = getSampleModel();
         if (sm != null) {
             buffer.append(" × ").append(sm.getNumBands()).append(" bands");
             final String type = ImageUtilities.getDataTypeName(sm);
             if (type != null) {
                 buffer.append(" of type ").append(type);
             }
         }
         /*
          * Write details about color model only if there is "useful" information for a geospatial raster.
          * The main category of interest are "color palette" versus "gray scale" versus everything else,
          * and whether the image may have transparent pixels.
          */
         final ColorModel cm = getColorModel();
 colors: if (cm != null) {
             buffer.append("; ");
             if (cm instanceof IndexColorModel) {
                 buffer.append(((IndexColorModel) cm).getMapSize()).append(" indexed colors");
             } else {
                 ColorModelFactory.formatDescription(cm.getColorSpace(), buffer);
             }
             final String transparency;
             switch (cm.getTransparency()) {
                 case ColorModel.OPAQUE:      transparency = "opaque"; break;
                 case ColorModel.TRANSLUCENT: transparency = "translucent"; break;
                 case ColorModel.BITMASK:     transparency = "bitmask transparency"; break;
                 default: break colors;
             }
             buffer.append("; ").append(transparency);
         }
         /*
          * Tiling information last because it is usually a secondary aspect compared to above information.
          * If a warning is emitted, it will usually be a tiling problem so it is useful to keep it close.
          */
         final int tx = getNumXTiles();
         final int ty = getNumYTiles();
         if (tx != 1 || ty != 1) {
             buffer.append("; ").append(tx).append(" × ").append(ty).append(" tiles");
         }
         final String error = verify();
         if (error != null) {
             buffer.append("; ⚠ mismatched ").append(error);
         }
         return buffer.append(']').toString();
     }
verify()
String verify ()
Verifies whether image layout information are consistent.
This method verifies that the coordinates of image upper-left corner are equal to the coordinates of the upper-left corner of the tile in the upper-left corner, and that image size is equal to the sum of the sizes of all tiles. Compatibility of sample model and color model is also verified.
The default implementation may return the following identifiers, in that order (i.e. this method returns the identifier of the first test that fail):
"SampleModel"
— Sample model is incompatible with color model.
"tileWidth"
— tile width is greater than sample model width.
"tileHeight"
— tile height is greater than sample model height.
"numXTiles"
— number of tiles on the X axis is inconsistent with image width.
"numYTiles"
— number of tiles on the Y axis is inconsistent with image height.
"tileX"
— { minTileX} and/or
tileGridXOffset
is inconsistent.
"tileY"
— { minTileY} and/or
tileGridYOffset
is inconsistent.
Subclasses may perform additional checks. For example some subclasses also check specifically for
"minX"
,
"minY"
,
"tileGridXOffset"
and
"tileGridYOffset"
.
Returns
null
if image layout information are consistent, or the name of inconsistent attribute if a problem is found.
References PlanarImage.getMinTileX(), PlanarImage.getMinTileY(), PlanarImage.getMinX(), PlanarImage.getMinY(), PlanarImage.getNumXTiles(), PlanarImage.getNumYTiles(), PlanarImage.getTileGridXOffset(), and PlanarImage.getTileGridYOffset().
Referenced by PlanarImage.toString().
{
         final int tileWidth  = getTileWidth();
         final int tileHeight = getTileHeight();
         final SampleModel sm = getSampleModel();
         if (sm != null) {
             final ColorModel cm = getColorModel();
             if (cm != null) {
                 if (!cm.isCompatibleSampleModel(sm)) return "SampleModel";
             }
             /*
              * The SampleModel size represents the physical layout of pixels in the data buffer,
              * while the Raster may be a virtual view over a sub-region of a parent raster.
              */
             if (sm.getWidth()  < tileWidth)  return "tileWidth";
             if (sm.getHeight() < tileHeight) return "tileHeight";
         }
         if (JDK9.multiplyFull(getNumXTiles(), tileWidth)  != getWidth())  return "numXTiles";
         if (JDK9.multiplyFull(getNumYTiles(), tileHeight) != getHeight()) return "numYTiles";
         if (JDK9.multiplyFull(getMinTileX(),  tileWidth)  + getTileGridXOffset() != getMinX()) return "tileX";
         if (JDK9.multiplyFull(getMinTileY(),  tileHeight) + getTileGridYOffset() != getMinY()) return "tileY";
         return null;
     }
Member Data Documentation
SAMPLE_RESOLUTIONS_KEY
final String SAMPLE_RESOLUTIONS_KEY = "SampleResolution" static
Key of a property defining the resolutions of sample values in each band.
This property is recommended for images having sample values as floating point numbers. For example if sample values were computed by value = integer × scale factor, then the resolution is the scale factor. This information is used for choosing the number of fraction digits to show when writing sample values in text format.
Values should be instances of
float[]
or
double[]
. The array length should be the number of bands.