jena-geo: HexWKBRastDatatype Class Reference
HexWKBRastDatatype Class Reference
Public Member Functions
HexWKBRastDatatype ()
String unparse (Object geometry)
CoverageWrapper read (String geometryLiteral)
String toString ()
final CoverageWrapper parse (String lexicalForm) throws DatatypeFormatException
This method Parses the Geometry Literal to the JTS Geometry.
final CoverageWrapper parse (String lexicalForm, GeometryIndex targetIndex) throws DatatypeFormatException
Static Public Member Functions
static final void registerDatatypes ()
static final RasterDataType get (RDFDatatype rdfDatatype)
static final RasterDataType get (String datatypeURI)
static final boolean checkURI (String datatypeURI)
static final boolean check (RDFDatatype rdfDatatype)
Static Public Attributes
static final String URI = PostGISGeo.HexWKBRaster
static final HexWKBRastDatatype INSTANCE =new HexWKBRastDatatype()
Constructor & Destructor Documentation
HexWKBRastDatatype()
HexWKBRastDatatype ()
{
                 super(URI);
         }
Member Function Documentation
check()
static final boolean check (RDFDatatype rdfDatatype) static inherited
References RasterDataType.checkURI().
{
         //Ensure that the registered datatypes from the type mapper are used.
         return checkURI(rdfDatatype.getURI());
     }
checkURI()
static final boolean checkURI (String datatypeURI) static inherited
References RasterDataType.registerDatatypes().
Referenced by RasterDataType.check(), and RasterDataType.get().
{
         registerDatatypes();
         RDFDatatype rdfDatatype = TYPE_MAPPER.getTypeByName(datatypeURI);
         if (rdfDatatype != null) {
             return rdfDatatype instanceof GeometryDatatype;
         } else {
             throw new DatatypeFormatException("Datatype not found: " + datatypeURI + " Ensure that GeoSPARQL is enabled and Datatype has been registered.");
         }
     }
get() [1/2]
static final RasterDataType get (RDFDatatype rdfDatatype) static inherited
Referenced by CoverageWrapper.asLiteral(), CoverageWrapper.extract(), RasterDataType.get(), CoverageWrapper.getRasterDatatype(), and LiteralUtils.rasterOrVector().
{
         if (rdfDatatype instanceof RasterDataType) {
             return (RasterDataType) rdfDatatype;
         } else {
             throw new DatatypeFormatException("Unrecognised Raster Datatype: " + rdfDatatype.getURI() + " Ensure that Datatype is extending GeometryDatatype.");
         }
     }
get() [2/2]
static final RasterDataType get (String datatypeURI) static inherited
References RasterDataType.checkURI(), and RasterDataType.get().
{
         checkURI(datatypeURI);
         RDFDatatype rdfDatatype = TYPE_MAPPER.getTypeByName(datatypeURI);
         return RasterDataType.get(rdfDatatype);
     }
parse() [1/2]
final CoverageWrapper parse (String lexicalForm) throws DatatypeFormatException inherited
This method Parses the Geometry Literal to the JTS Geometry.
Parameters
lexicalForm - the Geometry Literal to be parsed
Returns
geometry - if the Geometry Literal is valid.
empty geometry - if the Geometry Literal is empty.
null - if the Geometry Literal is invalid.
References GeometryLiteralIndex.GeometryIndex.PRIMARY.
Referenced by CoverageWrapper.extract().
{
         return parse(lexicalForm, GeometryIndex.PRIMARY);
     }
parse() [2/2]
final CoverageWrapper parse (String lexicalForm, GeometryIndex targetIndex) throws DatatypeFormatException inherited
References GeometryLiteralIndex.retrieve().
{
         //Check the Geometry Literal Index to see if been previously read and cached.
         //DatatypeReader interface used to instruct index on how to obtain the GeometryWrapper.
         try {
             return GeometryLiteralIndex.retrieve(lexicalForm, this, targetIndex);
         } catch (IllegalArgumentException ex) {
                 ex.printStackTrace();
             throw new DatatypeFormatException(ex.getMessage() + " - Illegal Geometry Literal: " + lexicalForm);
         }
     }
read()
CoverageWrapper read (String geometryLiteral)
References WKBRasterReader.readCoverage().
{
                 WKBRasterReader reader2=new WKBRasterReader();
                 GridCoverage2D coverage;
                 try {
                         //BufferedImage img=reader2.read(WKBReader.hexToBytes(geometryLiteral));
                         //CRS.forCode("EPSG:4326").getCoordinateSystem().
                         coverage = reader2.readCoverage(WKBReader.hexToBytes(geometryLiteral),null);
                         //System.out.println(coverage);
                         return new CoverageWrapper(coverage, URI);
                 } catch (IOException | FactoryException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                         throw new RuntimeException(e.getMessage());
                 }
         }
registerDatatypes()
static final void registerDatatypes () static inherited
References CovJSONDatatype.INSTANCE, WKBRastDatatype.INSTANCE, and HexWKBRastDatatype.INSTANCE.
Referenced by RasterDataType.checkURI().
{
         if (!isDatatypesRegistered) {
             TYPE_MAPPER.registerDatatype(CovJSONDatatype.INSTANCE);
                 //TYPE_MAPPER.registerDatatype(GeoTIFFDatatype.INSTANCE);
             //TYPE_MAPPER.registerDatatype(GMLCOVDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(HexWKBRastDatatype.INSTANCE);
             TYPE_MAPPER.registerDatatype(WKBRastDatatype.INSTANCE);
             isDatatypesRegistered = true;
         }
     }
toString()
String toString ()
{
         return "HexWKBRasterDatatype{" + URI + '}';
     }
unparse()
String unparse (Object geometry)
References CoverageWrapper.getGridGeometry(), and WKBRasterWriter.write().
{
                 if (geometry instanceof CoverageWrapper) {
             CoverageWrapper geometryWrapper = (CoverageWrapper) geometry;
             WKBRasterWriter writer=new WKBRasterWriter();
                         String rasterWKB;
                         try {
                                 rasterWKB = WKBWriter.toHex(writer.write(geometryWrapper.getGridGeometry())).toString();
                                 return rasterWKB.toString();
                         } catch (IOException | FactoryException e) {
                                 throw new AssertionError(e.getMessage());
                         }
         } else {
             throw new AssertionError("Object passed to HexWKBRasterDatatype is not a GeometryWrapper: " + geometry);
         }
         }
Member Data Documentation
INSTANCE
final HexWKBRastDatatype INSTANCE =new HexWKBRastDatatype() static
Referenced by SampleRasters.displayRasterSummary(), RasterDataType.registerDatatypes(), AbsTest.testAbs(), AddTest.testAdd(), AddConstTest.testAddConst(), AndTest.testAnd(), AsCoverageJSONTest.testAsCoverageJSON(), AsHexRastWKBTest.testAsHexRastWKB(), AsRastWKBTest.testAsRastWKB(), BandMetadataTest.testBandMetaData(), BinarizeTest.testBinarize(), ClampTest.testClamp(), ConstantTest.testConstant(), CropTest.testCrop(), DivTest.testDiv(), DivConstTest.testDivConst(), EqualTest.testEqual(), ExpTest.testExp(), IDCTTest.testIDCT(), DCTTest.testIDCT(), LogTest.testLog(), MakeEmptyRasterTest.testMakeEmptyRaster(), MaxTest.testMax(), MaxFilterTest.testMaxFilter(), MeanTest.testMean(), MedianFilterTest.testMedianFilter(), MemSizeTest.testMemSize(), MinTest.testMin(), MinFilterTest.testMinFilter(), MinTileXTest.testMinTileX(), MinTileYTest.testMinTileY(), MultTest.testMult(), MultConstTest.testMultConst(), NotTest.testNot(), NumBandsTest.testNumBands(), NumXTilesTest.testNumXTiles(), NumYTilesTest.testNumYTiles(), OrTest.testOr(), RastFromHexWKBTest.testRasterFromHexWKB(), HeightTest.testRasterHeight(), HasNoBandTest.testRasterHeight(), IsEmptyTest.testRasterIsEmptyFalse(), RasterToWorldCoordTest.testRasterToWorldCoord(), RasterToWorldCoordXTest.testRasterToWorldCoordX(), RasterToWorldCoordYTest.testRasterToWorldCoordY(), ValueTest.testRasterValue(), WidthTest.testRasterWidth(), ScaleXTest.testScaleX(), ScaleYTest.testScaleY(), SkewXTest.testSkewX(), SkewYTest.testSkewY(), SubtractTest.testSubtract(), SubtractFromConstTest.testSubtractConst(), SubtractConstTest.testSubtractConst(), SummaryTest.testSummary(), ThresholdTest.testThreshold(), TileGridXOffsetTest.testTileGridXOffset(), TileGridYOffsetTest.testTileGridYOffset(), TileHeightTest.testTileHeight(), TileWidthTest.testTileWidth(), TranslateXTest.testTranslateX(), TranslateYTest.testTranslateY(), UpperLeftXTest.testUpperLeftX(), UpperLeftYTest.testUpperLeftY(), WorldToRasterCoordTest.testWorldToRasterCoord(), WorldToRasterCoordXTest.testWorldToRasterCoordX(), WorldToRasterCoordYTest.testWorldToRasterCoordY(), and XorTest.testXor().
URI
final String URI = PostGISGeo.HexWKBRaster static
Referenced by RastFromWKB.exec(), RastFromHexWKB.exec(), and MakeEmptyRaster.exec().