jena-geo: Geobuf.Data.Geometry.Type Enum Reference
Geobuf.Data.Geometry.Type Enum Reference
Protobuf enum.
Public Member Functions
final int getNumber ()
Static Public Member Functions
static Type valueOf (int value)
static com.google.protobuf.Internal.EnumLiteMap< Type > internalGetValueMap ()
Public Attributes
POINT =(0, 0)
POINT = 0;
MULTIPOINT =(1, 1)
MULTIPOINT = 1;
LINESTRING =(2, 2)
LINESTRING = 2;
MULTILINESTRING =(3, 3)
MULTILINESTRING = 3;
POLYGON =(4, 4)
POLYGON = 4;
MULTIPOLYGON =(5, 5)
MULTIPOLYGON = 5;
GEOMETRYCOLLECTION =(6, 6)
GEOMETRYCOLLECTION = 6;
Static Public Attributes
static final int POINT_VALUE = 0
POINT = 0;
static final int MULTIPOINT_VALUE = 1
MULTIPOINT = 1;
static final int LINESTRING_VALUE = 2
LINESTRING = 2;
static final int MULTILINESTRING_VALUE = 3
MULTILINESTRING = 3;
static final int POLYGON_VALUE = 4
POLYGON = 4;
static final int MULTIPOLYGON_VALUE = 5
MULTIPOLYGON = 5;
static final int GEOMETRYCOLLECTION_VALUE = 6
GEOMETRYCOLLECTION = 6;
Private Member Functions
Type (int index, int value)
Private Attributes
final int value
Static Private Attributes
static com.google.protobuf.Internal.EnumLiteMap< Type > internalValueMap
Detailed Description
Protobuf enum.
Data.Geometry.Type
Constructor & Destructor Documentation
Type()
Type (int index, int value) private
{
           this.value = value;
         }
Member Function Documentation
getNumber()
final int getNumber ()
 { return value; }
internalGetValueMap()
static com.google.protobuf.Internal.EnumLiteMap<Type> internalGetValueMap () static
{
           return internalValueMap;
         }
valueOf()
static Type valueOf (int value) static
Referenced by Geobuf.Data.Geometry.Geometry().
{
           switch (value) {
             case 0: return POINT;
             case 1: return MULTIPOINT;
             case 2: return LINESTRING;
             case 3: return MULTILINESTRING;
             case 4: return POLYGON;
             case 5: return MULTIPOLYGON;
             case 6: return GEOMETRYCOLLECTION;
             default: return null;
           }
         }
Member Data Documentation
GEOMETRYCOLLECTION
GEOMETRYCOLLECTION =(6, 6)
GEOMETRYCOLLECTION = 6;
GEOMETRYCOLLECTION_VALUE
static final int GEOMETRYCOLLECTION_VALUE = 6 static
GEOMETRYCOLLECTION = 6;
internalValueMap
static com.google.protobuf.Internal.EnumLiteMap<Type> internalValueMap static private
Initial value:
=
              new com.google.protobuf.Internal.EnumLiteMap<Type>() {
                public Type findValueByNumber(int number) {
                  return Type.valueOf(number);
                }
              }
LINESTRING
LINESTRING =(2, 2)
LINESTRING = 2;
LINESTRING_VALUE
static final int LINESTRING_VALUE = 2 static
LINESTRING = 2;
MULTILINESTRING
MULTILINESTRING =(3, 3)
MULTILINESTRING = 3;
MULTILINESTRING_VALUE
static final int MULTILINESTRING_VALUE = 3 static
MULTILINESTRING = 3;
MULTIPOINT
MULTIPOINT =(1, 1)
MULTIPOINT = 1;
MULTIPOINT_VALUE
static final int MULTIPOINT_VALUE = 1 static
MULTIPOINT = 1;
MULTIPOLYGON
MULTIPOLYGON =(5, 5)
MULTIPOLYGON = 5;
Referenced by GeobufFeature.GeobufFeature(), and GeobufEncoder.multiPolyToGeobuf().
MULTIPOLYGON_VALUE
static final int MULTIPOLYGON_VALUE = 5 static
MULTIPOLYGON = 5;
POINT
POINT =(0, 0)
POINT = 0;
Referenced by Geobuf.Data.Geometry.Builder.clear(), Geobuf.Data.Geometry.Builder.clearType(), Geobuf.Data.Geometry.initFields(), and GeobufEncoder.pointToGeobuf().
POINT_VALUE
static final int POINT_VALUE = 0 static
POINT = 0;
POLYGON
POLYGON =(4, 4)
POLYGON = 4;
Referenced by GeobufEncoder.polyToGeobuf().
POLYGON_VALUE
static final int POLYGON_VALUE = 4 static
POLYGON = 4;
value
final int value private