jena-geo: BandedSampleConverter.Writable Class Reference
BandedSampleConverter.Writable Class Reference
A.
Public Member Functions
synchronized void addTileObserver (final TileObserver observer)
Adds an observer to be notified when a tile is checked out for writing.
synchronized void removeTileObserver (final TileObserver observer)
Removes an observer from the list of observers notified when a tile is checked out for writing.
WritableRaster getWritableTile (final int tileX, final int tileY)
Checks out a tile for writing.
void releaseWritableTile (final int tileX, final int tileY)
Relinquishes the right to write to a tile.
void setData (final Raster data)
Sets a region of the image to the contents of the given raster.
Object getProperty (final String key)
Gets a property from this image.
String [] getPropertyNames ()
Returns the names of all recognized properties, or.
ColorModel getColorModel ()
Returns the color model associated with all rasters of this image.
int getWidth ()
Returns the width (in pixels) of this image.
int getHeight ()
Returns the height (in pixels) of this image.
int getMinX ()
Returns the minimum x coordinate (inclusive) of this image.
int getMinY ()
Returns the minimum y coordinate (inclusive) of this image.
int getMinTileX ()
Returns the minimum tile index in the x direction.
int getMinTileY ()
Returns the minimum tile index in the y direction.
Static Public Member Functions
static BandedSampleConverter create (final RenderedImage source, ImageLayout layout, final int targetType, final ColorModel colorModel, final NumberRange<?>[] ranges, final MathTransform1D... converters)
Creates a new image of the given data type which will compute values using the given converters.
Protected Member Functions
boolean markTileWritable (final int tileX, final int tileY, final boolean writing)
Sets or clears whether a tile is checked out for writing and notifies the listener if needed.
Raster computeTile (final int tileX, final int tileY, WritableRaster target) throws TransformException
Computes the tile at specified indices.
Package Functions
Writable (final WritableRenderedImage source, final BandedSampleModel sampleModel, final ColorModel colorModel, final NumberRange<?>[] ranges, final MathTransform1D[] converters, final MathTransform1D[] inverses)
Creates a new writable image which will compute values using the given converters.
Private Attributes
final MathTransform1D [] inverses
The converters for computing the source values from a converted value.
volatile TileObserver [] observers
The observers, or.
Detailed Description
A.
BandedSampleConverter
capable to retro-propagate the changes to the source coverage. This class contains the inverse of all MathTransform1D given to the parent class.
Constructor & Destructor Documentation
Writable()
Writable (final WritableRenderedImage source, final BandedSampleModel sampleModel, final ColorModel colorModel, final NumberRange<?> [] ranges, final MathTransform1D [] converters, final MathTransform1D [] inverses) package
Creates a new writable image which will compute values using the given converters.
References BandedSampleConverter.Writable.inverses.
         {
             super(source, sampleModel, colorModel, ranges, converters);
             this.inverses = inverses;
         }
Member Function Documentation
addTileObserver()
synchronized void addTileObserver (final TileObserver observer)
Adds an observer to be notified when a tile is checked out for writing.
If the observer is already present, it will receive multiple notifications.
Parameters
observer the observer to notify.
References BandedSampleConverter.Writable.observers.
{
             observers = WriteSupport.addTileObserver(observers, observer);
         }
computeTile()
Raster computeTile (final int tileX, final int tileY, WritableRaster target) throws TransformException protected inherited
Computes the tile at specified indices.
Parameters
tileX the column index of the tile to compute.
tileY the row index of the tile to compute.
target if the tile already exists but needs to be updated, the tile to update. Otherwise
null
.
Returns
computed tile for the given indices (can not be null).
Exceptions
TransformException if an error occurred while converting a sample value.
{
         if (target == null) {
             target = createTile(tileX, tileY);
         }
         Transferer.create(getSource(0), target).compute(converters);
         return target;
     }
create()
static BandedSampleConverter create (final RenderedImage source, ImageLayout layout, final int targetType, final ColorModel colorModel, final NumberRange<?> [] ranges, final MathTransform1D... converters) static inherited
Creates a new image of the given data type which will compute values using the given converters.
The number of bands is the length of the
converters
array, which must be greater than 0 and not greater than the number of bands in the source image.
Parameters
source the image for which to convert sample values.
layout object to use for computing tile size, or
null
for the default.
targetType the type of this image resulting from conversion of given image.
colorModel the color model for the expected range of values, or
null
.
ranges the expected range of values for each band, or
null
if unknown.
converters the transfer functions to apply on each band of the source image.
Returns
the image which compute converted values from the given source.
References BandedSampleConverter.BandedSampleConverter(), and RasterFactory.unique().
Referenced by ConvertedGridCoverage.render().
     {
         ArgumentChecks.ensureNonNull("source", source);
         ArgumentChecks.ensureNonNull("converters", converters);
         final int numBands = converters.length;
         ArgumentChecks.ensureSizeBetween("converters", 1, source.getSampleModel().getNumBands(), numBands);
         if (layout == null) {
             layout = ImageLayout.DEFAULT;
         }
         final Dimension tile = layout.suggestTileSize(source);
         final BandedSampleModel sampleModel = RasterFactory.unique(
                 new BandedSampleModel(targetType, tile.width, tile.height, numBands));
         /*
          * If the source image is writable, then changes in the converted image may be retro-propagated
          * to that source image. If we fail to compute the required inverse transforms, log a notice at
          * a low level because this is not a serious problem; writable BandedSampleConverter is a plus
          * but not a requirement.
          */
         if (source instanceof WritableRenderedImage) try {
             final MathTransform1D[] inverses = new MathTransform1D[numBands];
             for (int i=0; i<numBands; i++) {
                 inverses[i] = converters[i].inverse();
             }
             return new Writable((WritableRenderedImage) source, sampleModel, colorModel, ranges, converters, inverses);
         } catch (NoninvertibleTransformException e) {
             Logging.recoverableException(Logging.getLogger(Modules.RASTER), BandedSampleConverter.class, "create", e);
         }
         return new BandedSampleConverter(source, sampleModel, colorModel, ranges, converters);
     }
getColorModel()
ColorModel getColorModel () inherited
Returns the color model associated with all rasters of this image.
If the sample values of this image are floating point numbers, then a gray scale color model is computed from the expected range of values.
Returns
the color model of this image, or
null
if none.
References BandedSampleConverter.colorModel.
{
         return colorModel;
     }
getHeight()
int getHeight () inherited
Returns the height (in pixels) of this image.
This is the the same value than the source image (not necessarily zero).
Returns
the height (number of rows) of this image.
{
         return getSource(0).getHeight();
     }
getMinTileX()
int getMinTileX () inherited
Returns the minimum tile index in the x direction.
This is the the same value than the source image (not necessarily zero).
Returns
the minimum tile index in the x direction.
{
         return getSource(0).getMinTileX();
     }
getMinTileY()
int getMinTileY () inherited
Returns the minimum tile index in the y direction.
This is the the same value than the source image (not necessarily zero).
Returns
the minimum tile index in the y direction.
{
         return getSource(0).getMinTileY();
     }
getMinX()
int getMinX () inherited
Returns the minimum x coordinate (inclusive) of this image.
This is the the same value than the source image (not necessarily zero).
Returns
the minimum x coordinate (column) of this image.
{
         return getSource(0).getMinX();
     }
getMinY()
int getMinY () inherited
Returns the minimum y coordinate (inclusive) of this image.
This is the the same value than the source image (not necessarily zero).
Returns
the minimum y coordinate (row) of this image.
{
         return getSource(0).getMinY();
     }
getProperty()
Object getProperty (final String key) inherited
Gets a property from this image.
Current implementation recognizes: { #SAMPLE_RESOLUTIONS_KEY}.
{
         if (SAMPLE_RESOLUTIONS_KEY.equals(key) && sampleResolutions != null) {
             return sampleResolutions.clone();
         }
         return super.getProperty(key);
     }
getPropertyNames()
String [] getPropertyNames () inherited
Returns the names of all recognized properties, or.
null
if this image has no properties.
{
         if (sampleResolutions != null) {
             return new String[] {
                 SAMPLE_RESOLUTIONS_KEY
             };
         }
         return super.getPropertyNames();
     }
getWidth()
int getWidth () inherited
Returns the width (in pixels) of this image.
This is the the same value than the source image (not necessarily zero).
Returns
the width (number of columns) of this image.
{
         return getSource(0).getWidth();
     }
getWritableTile()
WritableRaster getWritableTile (final int tileX, final int tileY)
Checks out a tile for writing.
Parameters
tileX the x index of the tile.
tileY the y index of the tile.
Returns
the specified tile as a writable tile.
References BandedSampleConverter.Writable.markTileWritable().
{
             final WritableRaster tile = (WritableRaster) getTile(tileX, tileY);
             markTileWritable(tileX, tileY, true);
             return tile;
         }
markTileWritable()
boolean markTileWritable (final int tileX, final int tileY, final boolean writing) protected
Sets or clears whether a tile is checked out for writing and notifies the listener if needed.
Parameters
tileX the x index of the tile to acquire or release.
tileY the y index of the tile to acquire or release.
writing
References BandedSampleConverter.Writable.observers.
Referenced by BandedSampleConverter.Writable.getWritableTile(), and BandedSampleConverter.Writable.releaseWritableTile().
{
             final boolean notify = super.markTileWritable(tileX, tileY, writing);
             if (notify) {
                 WriteSupport.fireTileUpdate(observers, this, tileX, tileY, writing);
             }
             return notify;
         }
releaseWritableTile()
void releaseWritableTile (final int tileX, final int tileY)
Relinquishes the right to write to a tile.
If the tile goes from having one writer to having no writers, the values are inverse converted and written in the original image. If the caller continues to write to the tile, the results are undefined.
Parameters
tileX the x index of the tile.
tileY the y index of the tile.
References BandedSampleConverter.Writable.markTileWritable(), and BandedSampleConverter.Writable.setData().
{
             if (markTileWritable(tileX, tileY, false)) {
                 setData(getTile(tileX, tileY));
             }
         }
removeTileObserver()
synchronized void removeTileObserver (final TileObserver observer)
Removes an observer from the list of observers notified when a tile is checked out for writing.
If the observer was not registered, nothing happens. If the observer was registered for multiple notifications, it will now be registered for one fewer.
Parameters
observer the observer to stop notifying.
References BandedSampleConverter.Writable.observers.
{
             observers = WriteSupport.removeTileObserver(observers, observer);
         }
setData()
void setData (final Raster data)
Sets a region of the image to the contents of the given raster.
The raster is assumed to be in the same coordinate space as this image. The operation is clipped to the bounds of this image.
Parameters
data the values to write in this image.
References ImageUtilities.clipBounds(), TileOpExecutor.getTileIndices(), and TileOpExecutor.writeTo().
Referenced by BandedSampleConverter.Writable.releaseWritableTile().
{
             final Rectangle bounds = data.getBounds();
             final WritableRenderedImage target = (WritableRenderedImage) getSource(0);
             ImageUtilities.clipBounds(target, bounds);
             final TileOpExecutor executor = new TileOpExecutor(target, bounds) {
                 @Override protected void writeTo(final WritableRaster target) throws TransformException {
                     final Rectangle aoi = target.getBounds().intersection(bounds);
                     Transferer.create(data, target, aoi).compute(inverses);
                 }
             };
             executor.writeTo(target);
             /*
              * Request to recompute the tiles of this `BandedSampleConverter` because if the values
              * in the source image are integers, then converting back to floating point values may
              * produce slightly different results.
              */
             markDirtyTiles(executor.getTileIndices());
         }
Member Data Documentation
inverses
final MathTransform1D [] inverses private
The converters for computing the source values from a converted value.
Referenced by BandedSampleConverter.Writable.Writable().
observers
volatile TileObserver [] observers private
The observers, or.
null
if none. This is a copy-on-write array: values are never modified after construction (new arrays are created).
This field is declared volatile because it is read without synchronization by markTileWritable(int, int, boolean). Since this is a copy-on-write array, it is okay to omit synchronization for that method but we still need the memory effect.
Referenced by BandedSampleConverter.Writable.addTileObserver(), BandedSampleConverter.Writable.markTileWritable(), and BandedSampleConverter.Writable.removeTileObserver().