jena-geo: RasterFactory Class Reference
RasterFactory Class Reference
Creates rasters from given properties.
Static Public Member Functions
static BufferedImage createGrayScaleImage (final int dataType, final int width, final int height, final int numComponents, final int visibleBand, final double minimum, final double maximum)
Creates an opaque image with a gray scale color model.
static WritableRaster createRaster (final DataBuffer buffer, final int width, final int height, final int pixelStride, final int scanlineStride, int[] bankIndices, final int[] bandOffsets, final Point location)
Wraps the given data buffer in a raster.
static int getDataType (final Class<?> sample, final boolean unsigned)
Returns the DataBuffer constant for the given type.
static int getDataType (final NumberRange<?> range, final boolean keepFloat)
Returns the DataBuffer constant for the given range of values.
static DataBuffer wrap (final int dataType, final Buffer... data)
Wraps the backing arrays of given NIO buffers into Java2D buffers.
Package Functions
static< T extends SampleModel > T unique (final T sampleModel)
Returns a unique instance of the given sample model.
Private Member Functions
RasterFactory ()
Do not allow instantiation of this class.
Static Private Attributes
static final WeakHashSet< SampleModel > POOL = new WeakHashSet<>(SampleModel.class)
Shared instances of SampleModels.
Detailed Description
Creates rasters from given properties.
Contains also convenience methods for creating BufferedImage since that kind of images wraps a single raster.
Author
Martin Desruisseaux (IRD, Geomatys)
Version
1.1
Since
1.0
Constructor & Destructor Documentation
RasterFactory()
RasterFactory () private
Do not allow instantiation of this class.
{
     }
Member Function Documentation
createGrayScaleImage()
static BufferedImage createGrayScaleImage (final int dataType, final int width, final int height, final int numComponents, final int visibleBand, final double minimum, final double maximum) static
Creates an opaque image with a gray scale color model.
The image can have an arbitrary number of bands, but in current implementation only one band is used.
Warning: displaying this image is very slow, except in a few special cases. It should be used only when no standard color model can be used.
Parameters
dataType the color model type as one of
DataBuffer.TYPE_*
constants.
width the desired image width.
height the desired image height.
numComponents the number of components.
visibleBand the band to use for computing colors.
minimum the minimal sample value expected.
maximum the maximal sample value expected.
Returns
the color space for the given range of values.
References ColorModelFactory.createGrayScale(), and ColorModelFactory.isStandardRange().
     {
         switch (dataType) {
             case DataBuffer.TYPE_BYTE:
             case DataBuffer.TYPE_USHORT: {
                 if (numComponents == 1 && ColorModelFactory.isStandardRange(dataType, minimum, maximum)) {
                     return new BufferedImage(width, height, (dataType == DataBuffer.TYPE_BYTE)
                                 ? BufferedImage.TYPE_BYTE_GRAY : BufferedImage.TYPE_USHORT_GRAY);
                 }
                 break;
             }
         }
         final ColorModel cm = ColorModelFactory.createGrayScale(dataType, numComponents, visibleBand, minimum, maximum);
         return new BufferedImage(cm, cm.createCompatibleWritableRaster(width, height), false, null);
     }
createRaster()
static WritableRaster createRaster (final DataBuffer buffer, final int width, final int height, final int pixelStride, final int scanlineStride, int [] bankIndices, final int [] bandOffsets, final Point location) static
Wraps the given data buffer in a raster.
The sample model type is selected according the number of bands and the pixel stride. The number of bands is determined by
bandOffsets.length
, which should be one of followings:
For banded sample model, all
bandOffsets
can be zero.
For interleaved sample model (
buffer.getNumBanks()
= 1), each band needs a different offset. They may be 0, 1, 2, 3….
Parameters
buffer buffer that contains the sample values.
width raster width in pixels.
height raster height in pixels.
pixelStride number of data elements between two samples for the same band on the same line.
scanlineStride number of data elements between a given sample and the corresponding sample in the same column of the next line.
bankIndices bank indices for each band, or
null
for 0, 1, 2, 3….
bandOffsets number of data elements from the first element of the bank to the first sample of the band.
location the upper-left corner of the raster, or
null
for (0,0).
Returns
a raster built from given properties.
Exceptions
NullPointerException if
buffer
is
null
.
RasterFormatException if the width or height is less than or equal to zero, or if there is an integer overflow.
See also
WritableRaster::createInterleavedRaster(DataBuffer, int, int, int, int, int[], Point)
WritableRaster::createBandedRaster(DataBuffer, int, int, int, int[], int[], Point)
References RasterFactory.unique().
     {
         /*
          * We do not verify the argument validity. Since this class is internal, caller should have done verification
          * itself. Furthermore those arguments are verified by WritableRaster constructors anyway.
          */
         final int dataType = buffer.getDataType();
         /*
          * This SampleModel variable is a workaround for WritableRaster static methods not supporting all data types.
          * If 'dataType' is unsupported, then we create a SampleModel ourselves in the 'switch' statements below and
          * use it for creating a WritableRaster at the end of this method. This variable, together with the 'switch'
          * statements, may be removed in a future SIS version if all types become supported by the JDK.
          */
         @Workaround(library = "JDK", version = "10")
         final SampleModel model;
         if (buffer.getNumBanks() == 1 && (bankIndices == null || bankIndices[0] == 0)) {
             /*
              * Sample data are stored for all bands in a single bank of the DataBuffer, in an interleaved fashion.
              * Each sample of a pixel occupies one data element of the DataBuffer, with a different offset since
              * the buffer beginning. The number of bands is inferred from bandOffsets.length.
              */
             switch (dataType) {
                 case DataBuffer.TYPE_BYTE:
                 case DataBuffer.TYPE_USHORT: {
                     // 'scanlineStride' and 'pixelStride' really interchanged in that method signature.
                     return WritableRaster.createInterleavedRaster(buffer, width, height, scanlineStride, pixelStride, bandOffsets, location);
                 }
                 case DataBuffer.TYPE_INT: {
                     if (bandOffsets.length == 1 && pixelStride == 1) {
                         /*
                          * From JDK javadoc: "To create a 1-band Raster of type TYPE_INT, use createPackedRaster()".
                          * However this would require the creation of a PackedColorModel subclass. For SIS purposes,
                          * it is easier to create a banded sample model.
                          */
                         return WritableRaster.createBandedRaster(buffer, width, height, scanlineStride, new int[1], bandOffsets, location);
                     }
                     // else fallthrough.
                 }
                 default: {
                     model = new PixelInterleavedSampleModel(dataType, width, height, pixelStride, scanlineStride, bandOffsets);
                     break;
                 }
             }
         } else {
             /*
              * Sample data are stored in different banks (arrays) for each band. If all pixels are consecutive (pixelStride = 1),
              * we have the classical banded sample model. Otherwise the type is not well identified; neither interleaved or banded.
              */
             if (bankIndices == null) {
                 bankIndices = ArraysExt.range(0, bandOffsets.length);
             }
             if (pixelStride == 1) {
                 switch (dataType) {
                     case DataBuffer.TYPE_BYTE:
                     case DataBuffer.TYPE_USHORT:
                     case DataBuffer.TYPE_INT: {
                         // This constructor supports only above-cited types.
                         return WritableRaster.createBandedRaster(buffer, width, height, scanlineStride, bankIndices, bandOffsets, location);
                     }
                     default: {
                         model = new BandedSampleModel(dataType, width, height, scanlineStride, bankIndices, bandOffsets);
                         break;
                     }
                 }
             } else {
                 model = new ComponentSampleModel(dataType, width, height, pixelStride, scanlineStride, bankIndices, bandOffsets);
             }
         }
         return WritableRaster.createWritableRaster(unique(model), buffer, location);
     }
getDataType() [1/2]
static int getDataType (final Class<?> sample, final boolean unsigned) static
Returns the DataBuffer constant for the given type.
The given
sample
class should be a primitive type such as Float#TYPE. Wrappers class are also accepted.
Parameters
sample the primitive type or its wrapper class. May be
null
.
unsigned whether the type should be considered unsigned.
Returns
the DataBuffer type, or DataBuffer#TYPE_UNDEFINED.
Referenced by ConvertedGridCoverage.getDataType().
{
         switch (Numbers.getEnumConstant(sample)) {
             case Numbers.BYTE:    return unsigned ? DataBuffer.TYPE_BYTE      : DataBuffer.TYPE_SHORT;
             case Numbers.SHORT:   return unsigned ? DataBuffer.TYPE_USHORT    : DataBuffer.TYPE_SHORT;
             case Numbers.INTEGER: return unsigned ? DataBuffer.TYPE_UNDEFINED : DataBuffer.TYPE_INT;
             case Numbers.FLOAT:   return DataBuffer.TYPE_FLOAT;
             case Numbers.DOUBLE:  return DataBuffer.TYPE_DOUBLE;
             default:              return DataBuffer.TYPE_UNDEFINED;
         }
     }
getDataType() [2/2]
static int getDataType (final NumberRange<?> range, final boolean keepFloat) static
Returns the DataBuffer constant for the given range of values.
If
keepFloat
is
false
, then this method tries to return an integer type regardless if the range uses a floating point type. Range checks for integers assume ties rounding to positive infinity.
Parameters
range the range of values, or
null
.
keepFloat whether to avoid integer types if the range uses floating point numbers.
Returns
the DataBuffer type or DataBuffer#TYPE_UNDEFINED if the given range was null.
{
         if (range == null) {
             return DataBuffer.TYPE_UNDEFINED;
         }
         final byte nt = Numbers.getEnumConstant(range.getElementType());
         if (keepFloat) {
             if (nt >= Numbers.DOUBLE)   return DataBuffer.TYPE_DOUBLE;
             if (nt >= Numbers.FRACTION) return DataBuffer.TYPE_FLOAT;
         }
         final double min = range.getMinDouble();
         final double max = range.getMaxDouble();
         if (nt < Numbers.BYTE || nt > Numbers.FLOAT || nt == Numbers.LONG) {
             /*
              * Value type is long, double, BigInteger, BigDecimal or unknown type.
              * If conversions to 32 bits integers would lost integer digits, or if
              * a bound is NaN, stick to the most conservative data buffer type.
              *
              * Range check assumes ties rounding to positive infinity.
              */
             if (!(min >= -MAX_INTEGER_CONVERTIBLE_TO_FLOAT - 0.5 && max < MAX_INTEGER_CONVERTIBLE_TO_FLOAT + 0.5)) {
                 return DataBuffer.TYPE_DOUBLE;
             }
         }
         /*
          * Check most common types first. If the range could be both signed and unsigned short,
          * give precedence to unsigned short because it works better with IndexColorModel.
          * If a bounds is NaN, fallback on TYPE_FLOAT.
          */
         if (min >= -0.5 && max < 0xFFFF + 0.5) {
             return (max < 0xFF + 0.5) ? DataBuffer.TYPE_BYTE : DataBuffer.TYPE_USHORT;
         } else if (min >= Short.MIN_VALUE - 0.5 && max < Short.MAX_VALUE + 0.5) {
             return DataBuffer.TYPE_SHORT;
         } else if (min >= Integer.MIN_VALUE - 0.5 && max < Integer.MAX_VALUE + 0.5) {
             return DataBuffer.TYPE_INT;
         }
         return DataBuffer.TYPE_FLOAT;
     }
unique()
static<T extends SampleModel> T unique (final T sampleModel) package
Returns a unique instance of the given sample model.
This method can be invoked after a new sample has been created in order to share the same instance for many similar
Raster
instances.
Parameters
<T> the type of the given
sampleModel
.
sampleModel the sample model to make unique.
Returns
a unique instance of the given sample model. May be
sampleModel
itself.
References RasterFactory.POOL.
Referenced by BandedSampleConverter.create(), MultiBandsIndexColorModel.createCompatibleSampleModel(), and RasterFactory.createRaster().
{
         return POOL.unique(sampleModel);
     }
wrap()
static DataBuffer wrap (final int dataType, final Buffer... data) static
Wraps the backing arrays of given NIO buffers into Java2D buffers.
This method wraps the underlying array of primitive types; data are not copied. For each buffer, the data starts at Buffer::position() buffer position} and ends at Buffer::limit() limit}.
Parameters
dataType type of buffer to create as one of DataBuffer constants.
data the data, one for each band.
Returns
buffer of the given type, or
null
if
dataType
is unrecognized.
Exceptions
UnsupportedOperationException if a buffer is not backed by an accessible array.
ReadOnlyBufferException if a buffer is backed by an array but is read-only.
ArrayStoreException if the type of a backing array is not
dataType
.
ArithmeticException if a buffer position overflows the 32 bits integer capacity.
RasterFormatException if buffers do not have the same amount of remaining values.
{
         final int numBands = data.length;
         final Object[] arrays;
         switch (dataType) {
             case DataBuffer.TYPE_USHORT: // fall through
             case DataBuffer.TYPE_SHORT:  arrays = new short [numBands][]; break;
             case DataBuffer.TYPE_INT:    arrays = new int   [numBands][]; break;
             case DataBuffer.TYPE_BYTE:   arrays = new byte  [numBands][]; break;
             case DataBuffer.TYPE_FLOAT:  arrays = new float [numBands][]; break;
             case DataBuffer.TYPE_DOUBLE: arrays = new double[numBands][]; break;
             default: return null;
         }
         final int[] offsets = new int[numBands];
         int length = 0;
         for (int i=0; i<numBands; i++) {
             final Buffer buffer = data[i];
             ArgumentChecks.ensureNonNullElement("data", i, buffer);
             arrays [i] = buffer.array();
             offsets[i] = Math.addExact(buffer.arrayOffset(), buffer.position());
             final int r = buffer.remaining();
             if (i == 0) length = r;
             else if (length != r) {
                 throw new RasterFormatException(Resources.format(Resources.Keys.MismatchedBandSize));
             }
         }
         switch (dataType) {
             case DataBuffer.TYPE_BYTE:   return new DataBufferByte  (  (byte[][]) arrays, length, offsets);
             case DataBuffer.TYPE_SHORT:  return new DataBufferShort ( (short[][]) arrays, length, offsets);
             case DataBuffer.TYPE_USHORT: return new DataBufferUShort( (short[][]) arrays, length, offsets);
             case DataBuffer.TYPE_INT:    return new DataBufferInt   (   (int[][]) arrays, length, offsets);
             case DataBuffer.TYPE_FLOAT:  return new DataBufferFloat ( (float[][]) arrays, length, offsets);
             case DataBuffer.TYPE_DOUBLE: return new DataBufferDouble((double[][]) arrays, length, offsets);
             default: return null;
         }
     }
Member Data Documentation
POOL
final WeakHashSet<SampleModel> POOL = new WeakHashSet<>(SampleModel.class) static private
Shared instances of SampleModels.
See also
#unique(SampleModel)
Referenced by RasterFactory.unique().