jena-geo: ConvertedGridCoverage Class Reference
ConvertedGridCoverage Class Reference
Decorates a GridCoverage in order to convert sample values on the fly.
Public Member Functions
double [] evaluate (final DirectPosition point, double[] buffer) throws CannotEvaluateException
Returns a sequence of double values for a given point in the coverage.
RenderedImage render (final GridExtent sliceExtent)
Creates a converted view over source data for the given extent.
GridCoverage forConvertedValues (final boolean converted)
Returns this coverage or the source coverage depending on whether.
CoordinateReferenceSystem getCoordinateReferenceSystem ()
Returns the coordinate reference system to which the values in grid domain are referenced.
GridGeometry getGridGeometry ()
Returns information about the <cite>domain</cite> of this grid coverage.
List< SampleDimension > getSampleDimensions ()
Returns information about the <cite>range</cite> of this grid coverage.
FractionalGridCoordinates toGridCoordinates (final DirectPosition point) throws TransformException
Converts the specified geospatial position to grid coordinates.
String toString ()
Returns a string representation of this grid coverage for debugging purpose.
TreeTable toTree (final Locale locale, final int bitmask)
Returns a tree representation of some elements of this grid coverage.
Static Public Member Functions
static int getDataType (final List< SampleDimension > targets, final boolean converted)
Returns the DataBuffer constant for range of values of given sample dimensions.
Package Functions
final NumberRange<?> [] getRanges ()
Returns the range of values in each sample dimension, or.
final ColorModel createColorModel (final int visibleBand, final int dataType)
Creates a color model for the expected range of sample values.
final GridCoverage getView (final boolean converted)
Returns the converted or package view, or.
final void setView (final boolean converted, final GridCoverage view)
Sets the converted or package view.
void appendDataLayout (TreeTable.Node root, Vocabulary vocabulary, TableColumn< CharSequence > column)
Appends a "data layout" branch (if it exists) to the tree representation of this coverage.
Static Package Functions
static GridCoverage create (final GridCoverage source, final boolean converted) throws NoninvertibleTransformException
Returns a coverage of converted values computed from a coverage of packed values, or conversely.
static MathTransform1D [] converters (final List< SampleDimension > sources, final List< SampleDimension > targets, final boolean converted) throws NoninvertibleTransformException
Returns the transforms for converting sample values from given sources to the.
static double [] evaluate (final RenderedImage data, final int x, final int y, final double[] buffer)
Gets sample values from the given image at the given index.
Package Attributes
final GridGeometry gridGeometry
The grid extent, coordinate reference system (CRS) and conversion from cell indices to CRS.
transient GridCoverage convertedView
Static Package Attributes
static final int VISIBLE_BAND = 0
The band to make visible when the image is shown on screen.
Private Member Functions
ConvertedGridCoverage (final GridCoverage source, final List< SampleDimension > range, final MathTransform1D[] converters, final boolean isConverted)
Creates a new coverage with the same grid geometry than the given coverage but converted sample dimensions.
Private Attributes
final GridCoverage source
The coverage containing source values.
final MathTransform1D [] converters
Conversions from source values to converted values.
final boolean isConverted
Whether this grid coverage is for converted values.
final int dataType
One of DataBuffer constants the describe the sample values type of images produced by render(GridExtent).
Detailed Description
Decorates a GridCoverage in order to convert sample values on the fly.
There is two strategies about when to convert sample values:
In calls to render(GridExtent), sample values are converted when first needed on a tile-by-tile basis then cached for future reuse. Note however that discarding the returned image may result in the lost of cached tiles.
In calls to evaluate(DirectPosition, double[]), the conversion is applied on-the-fly each time in order to avoid the potentially costly tile computations.
Author
Johann Sorel (Geomatys)
Martin Desruisseaux (Geomatys)
Version
1.1
Since
1.0
Constructor & Destructor Documentation
ConvertedGridCoverage()
ConvertedGridCoverage (final GridCoverage source, final List< SampleDimension > range, final MathTransform1D [] converters, final boolean isConverted) private
Creates a new coverage with the same grid geometry than the given coverage but converted sample dimensions.
Parameters
source the coverage containing source values.
range the sample dimensions to assign to the converted grid coverage.
converters conversion from source to converted coverage, one transform per band.
isConverted whether this grid coverage is for converted or packed values.
References ConvertedGridCoverage.converters, ConvertedGridCoverage.getDataType(), GridCoverage.getGridGeometry(), ConvertedGridCoverage.isConverted, and ConvertedGridCoverage.source.
Referenced by ConvertedGridCoverage.create().
     {
         super(source.getGridGeometry(), range);
         this.source      = source;
         this.converters  = converters;
         this.isConverted = isConverted;
         this.dataType    = getDataType(range, isConverted);
     }
Member Function Documentation
appendDataLayout()
void appendDataLayout (TreeTable.Node root, Vocabulary vocabulary, TableColumn< CharSequence > column) package inherited
Appends a "data layout" branch (if it exists) to the tree representation of this coverage.
That branch will be inserted between "coverage domain" and "sample dimensions" branches. The default implementation does nothing.
Parameters
root root of the tree where to add a branch.
vocabulary localized resources for vocabulary.
column the single column where to write texts.
Referenced by GridCoverage.toTree().
{
     }
converters()
static MathTransform1D [] converters (final List< SampleDimension > sources, final List< SampleDimension > targets, final boolean converted) throws NoninvertibleTransformException static package
Returns the transforms for converting sample values from given sources to the.
converted
status of those sources. This method opportunistically adds the target sample dimensions in
target
list.
Parameters
sources GridCoverage#getSampleDimensions() of
source
coverage.
targets where to add SampleDimension#forConvertedValues(boolean) results.
converted
     {
         final int               numBands   = sources.size();
         final MathTransform1D   identity   = (MathTransform1D) MathTransforms.identity(1);
         final MathTransform1D[] converters = new MathTransform1D[numBands];
         Arrays.fill(converters, identity);
         for (int i = 0; i < numBands; i++) {
             final SampleDimension src = sources.get(i);
             final SampleDimension tgt = src.forConvertedValues(converted);
             targets.add(tgt);
             if (src != tgt) {
                 MathTransform1D tr = src.getTransferFunction().orElse(identity);
                 Optional<MathTransform1D> complete = tgt.getTransferFunction();
                 if (complete.isPresent()) {
                     tr = MathTransforms.concatenate(tr, complete.get().inverse());
                 }
                 converters[i] = tr;
             }
         }
         for (final MathTransform1D converter : converters) {
             if (!converter.isIdentity()) return converters;
         }
         return null;
     }
create()
static GridCoverage create (final GridCoverage source, final boolean converted) throws NoninvertibleTransformException static package
Returns a coverage of converted values computed from a coverage of packed values, or conversely.
If the given coverage is already converted, then this method returns
coverage
unchanged.
Parameters
source the coverage containing values to convert.
converted
References ConvertedGridCoverage.ConvertedGridCoverage(), ConvertedGridCoverage.converters, GridCoverage.getSampleDimensions(), and ConvertedGridCoverage.source.
Referenced by GridCoverage.forConvertedValues().
{
         final List<SampleDimension> sources = source.getSampleDimensions();
         final List<SampleDimension> targets = new ArrayList<>(sources.size());
         final MathTransform1D[]  converters = converters(sources, targets, converted);
         return (converters != null) ? new ConvertedGridCoverage(source, targets, converters, converted) : source;
     }
createColorModel()
final ColorModel createColorModel (final int visibleBand, final int dataType) package inherited
Creates a color model for the expected range of sample values.
Parameters
visibleBand the band to be made visible (usually 0). All other bands (if any) will be ignored.
dataType the color model type as one java.awt.image.DataBuffer constants.
Returns
proposed color model, or
null
if none.
References ColorModelFactory.createColorModel(), and ColorModelFactory.GRAYSCALE.
Referenced by GridCoverage2D.GridCoverage2D(), and ConvertedGridCoverage.render().
{
         return ColorModelFactory.createColorModel(sampleDimensions, visibleBand, dataType, ColorModelFactory.GRAYSCALE);
     }
evaluate() [1/2]
double [] evaluate (final DirectPosition point, double [] buffer) throws CannotEvaluateException
Returns a sequence of double values for a given point in the coverage.
This method delegates to the source coverage, then convert values.
Parameters
point the coordinate point where to evaluate.
buffer an array in which to store values, or
null
to create a new array.
Returns
the
buffer
array, or a newly created array if
buffer
was null.
Exceptions
CannotEvaluateException if the values can not be computed.
References GridCoverage.evaluate().
{
         try {
             buffer = source.evaluate(point, buffer);
             for (int i=0; i<converters.length; i++) {
                 buffer[i] = converters[i].transform(buffer[i]);
             }
         } catch (TransformException ex) {
             throw new CannotEvaluateException(ex.getMessage(), ex);
         }
         return buffer;
     }
evaluate() [2/2]
static double [] evaluate (final RenderedImage data, final int x, final int y, final double [] buffer) static package inherited
Gets sample values from the given image at the given index.
This method does not verify explicitly if the coordinates are out of bounds; we rely on the checks performed by the image and sample model implementations.
Parameters
data the data from which to get the sample values.
x column index of the value to get.
y row index of the value to get.
buffer an array in which to store values, or
null
to create a new array.
Returns
the
buffer
array, or a newly created array if
buffer
was null.
Exceptions
ArithmeticException if an integer overflow occurred while computing indices.
IndexOutOfBoundsException if a coordinate is out of bounds.
{
         final int tx = Math.toIntExact(Math.floorDiv(x - (long) data.getTileGridXOffset(), data.getTileWidth()));
         final int ty = Math.toIntExact(Math.floorDiv(y - (long) data.getTileGridYOffset(), data.getTileHeight()));
         return data.getTile(tx, ty).getPixel(x, y, buffer);
     }
forConvertedValues()
GridCoverage forConvertedValues (final boolean converted)
Returns this coverage or the source coverage depending on whether.
converted
matches the kind of content of this coverage.
References ConvertedGridCoverage.source.
{
         return (converted == isConverted) ? this : source;
     }
getCoordinateReferenceSystem()
CoordinateReferenceSystem getCoordinateReferenceSystem () inherited
Returns the coordinate reference system to which the values in grid domain are referenced.
This is the CRS used when accessing a coverage with the
evaluate()
methods. This coordinate reference system is usually different than the coordinate system of the grid. It is the target coordinate reference system of the gridToCRS math transform.
The default implementation delegates to GridGeometry#getCoordinateReferenceSystem().
Returns
the CRS used when accessing a coverage with the
evaluate()
methods.
Exceptions
IncompleteGridGeometryException if the grid geometry has no CRS.
{
         return gridGeometry.getCoordinateReferenceSystem();
     }
getDataType()
static int getDataType (final List< SampleDimension > targets, final boolean converted) static
Returns the DataBuffer constant for range of values of given sample dimensions.
Parameters
targets the sample dimensions for which to get the data type.
converted whether the image will hold converted or packed values.
Returns
the DataBuffer type.
References RasterFactory.getDataType().
Referenced by ConvertedGridCoverage.ConvertedGridCoverage(), and GridCoverage2D.GridCoverage2D().
{
         NumberRange<?> union = null;
         for (final SampleDimension dimension : targets) {
             final Optional<NumberRange<?>> c = dimension.getSampleRange();
             if (c.isPresent()) {
                 final NumberRange<?> range = c.get();
                 if (union == null) {
                     union = range;
                 } else {
                     union = union.unionAny(range);
                 }
             }
         }
         return RasterFactory.getDataType(union, converted);
     }
getGridGeometry()
GridGeometry getGridGeometry () inherited
Returns information about the <cite>domain</cite> of this grid coverage.
Information includes the grid extent, CRS and conversion from cell indices to CRS.
GridGeometry
can also provide derived information like bounding box and resolution.
Returns
grid extent, CRS and conversion from cell indices to CRS.
See also
org.apache.sis.storage.GridCoverageResource::getGridGeometry()
References GridCoverage.gridGeometry.
Referenced by ConvertedGridCoverage.ConvertedGridCoverage(), and GridCoverage.toGridCoordinates().
{
         return gridGeometry;
     }
getRanges()
final NumberRange<?> [] getRanges () package inherited
Returns the range of values in each sample dimension, or.
null
if none.
Referenced by ConvertedGridCoverage.render().
{
         NumberRange<?>[] ranges = null;
         for (int i=0; i<sampleDimensions.length; i++) {
             final Optional<NumberRange<?>> r = sampleDimensions[i].getSampleRange();
             if (r.isPresent()) {
                 if (ranges == null) {
                     ranges = new NumberRange<?>[sampleDimensions.length];
                 }
                 ranges[i] = r.get();
             }
         }
         return ranges;
     }
getSampleDimensions()
List<SampleDimension> getSampleDimensions () inherited
Returns information about the <cite>range</cite> of this grid coverage.
Information include names, sample value ranges, fill values and transfer functions for all bands in this grid coverage. The length of the returned list should be equal to the java.awt.image.SampleModel::getNumBands() number of bands} in the rendered image.
Returns
names, value ranges, fill values and transfer functions for all bands in this grid coverage.
See also
org.apache.sis.storage.GridCoverageResource::getSampleDimensions()
Referenced by ConvertedGridCoverage.create(), and GridCoverage2D.forConvertedValues().
{
         return UnmodifiableArrayList.wrap(sampleDimensions);
     }
getView()
final GridCoverage getView (final boolean converted) package inherited
Returns the converted or package view, or.
null
if not yet computed. It is caller responsibility to ensure that this method is invoked in a synchronized block.
References GridCoverage.convertedView, and GridCoverage.packedView.
Referenced by GridCoverage.forConvertedValues(), and GridCoverage2D.forConvertedValues().
{
         return converted ? convertedView : packedView;
     }
render()
RenderedImage render (final GridExtent sliceExtent)
Creates a converted view over source data for the given extent.
Values will be converted when first requested on a tile-by-tile basis. Note that if the returned image is discarded, then the cache of converted tiles will be discarded too.
Returns
the grid slice as a rendered image with converted view.
References BandedSampleConverter.create(), GridCoverage.createColorModel(), GridCoverage.getRanges(), and GridCoverage.render().
{
         RenderedImage image = source.render(sliceExtent);
         /*
          * That image should never be null. But if an implementation wants to do so, respect that.
          */
         if (image != null) {
             final ColorModel colorModel = createColorModel(VISIBLE_BAND, dataType);
             image = BandedSampleConverter.create(image, null, dataType, colorModel, getRanges(), converters);
         }
         return image;
     }
setView()
final void setView (final boolean converted, final GridCoverage view) package inherited
Sets the converted or package view.
The given view should not be null. It is caller responsibility to ensure that this method is invoked in a synchronized block.
Referenced by GridCoverage.forConvertedValues(), and GridCoverage2D.forConvertedValues().
{
         if (converted) {
             convertedView = view;
         } else {
             packedView = view;
         }
     }
toGridCoordinates()
FractionalGridCoordinates toGridCoordinates (final DirectPosition point) throws TransformException inherited
Converts the specified geospatial position to grid coordinates.
If the given position is associated to a non-null coordinate reference system (CRS) different than the CRS of this coverage, then this method automatically transforms that position to the getCoordinateReferenceSystem() coverage CRS} before to compute grid coordinates.
This method does not put any restriction on the grid coordinates result. The result may be outside the GridGeometry::getExtent() grid extent} if the GridGeometry::getGridToCRS(PixelInCell) grid to CRS} transform allows it.
Parameters
point geospatial coordinates (in arbitrary CRS) to transform to grid coordinates.
Returns
the grid coordinates for the given geospatial coordinates.
Exceptions
IncompleteGridGeometryException if the getGridGeometry() grid geometry} does not define a "grid to CRS" transform, or if the given point has a non-null CRS but this coverage does not getCoordinateReferenceSystem() have a CRS}.
TransformException if the given coordinates can not be transformed.
See also
FractionalGridCoordinates::toPosition(MathTransform)
Since
1.1
References PointToGridCoordinates.crsToGrid, FractionalGridCoordinates.fromPosition(), GridCoverage.getGridGeometry(), GridCoverage.lastConverter, GridCoverage.render(), and PointToGridCoordinates.sourceCRS.
Referenced by GridCoverage.evaluate(), and GridCoverage2D.evaluate().
{
         final CoordinateReferenceSystem sourceCRS = point.getCoordinateReferenceSystem();
         PointToGridCoordinates converter = lastConverter;
         if (converter == null || !Objects.equals(converter.sourceCRS, sourceCRS)) {
             converter = new PointToGridCoordinates(sourceCRS, this, getGridGeometry());
             lastConverter = converter;
         }
         return FractionalGridCoordinates.fromPosition(point, converter.crsToGrid);
     }
toString()
String toString () inherited
Returns a string representation of this grid coverage for debugging purpose.
The returned string is implementation dependent and may change in any future version. Current implementation is equivalent to the following, where
<default flags>
is the same set of flags than GridGeometry#toString().
{ java return toTree(Locale.getDefault(), <default flags>="">).toString(); }
Returns
a string representation of this grid coverage for debugging purpose.
References GridCoverage.toTree().
{
         return toTree(Locale.getDefault(), GridGeometry.defaultFlags()).toString();
     }
toTree()
TreeTable toTree (final Locale locale, final int bitmask) inherited
Returns a tree representation of some elements of this grid coverage.
The tree representation is for debugging purpose only and may change in any future SIS version.
Parameters
locale the locale to use for textual labels.
bitmask combination of GridGeometry flags.
Returns
a tree representation of the specified elements.
See also
GridGeometry::toTree(Locale, int)
References GridCoverage.appendDataLayout().
Referenced by GridCoverage.toString().
{
         ArgumentChecks.ensureNonNull("locale", locale);
         final Vocabulary vocabulary = Vocabulary.getResources(locale);
         final TableColumn<CharSequence> column = TableColumn.VALUE_AS_TEXT;
         final TreeTable tree = new DefaultTreeTable(column);
         final TreeTable.Node root = tree.getRoot();
         root.setValue(column, Classes.getShortClassName(this));
         TreeTable.Node branch = root.newChild();
         branch.setValue(column, vocabulary.getString(Vocabulary.Keys.CoverageDomain));
         gridGeometry.formatTo(locale, vocabulary, bitmask, branch);
         appendDataLayout(root, vocabulary, column);
         branch = root.newChild();
         branch.setValue(column, vocabulary.getString(Vocabulary.Keys.SampleDimensions));
         branch.newChild().setValue(column, SampleDimension.toString(locale, sampleDimensions));
         return tree;
     }
Member Data Documentation
convertedView
transient GridCoverage convertedView package inherited
Referenced by GridCoverage.getView().
converters
final MathTransform1D [] converters private
Conversions from source values to converted values.
The length of this array shall be equal to the number of bands.
Referenced by ConvertedGridCoverage.ConvertedGridCoverage(), ConvertedGridCoverage.create(), and GridCoverage2D.forConvertedValues().
dataType
final int dataType private
One of DataBuffer constants the describe the sample values type of images produced by render(GridExtent).
gridGeometry
final GridGeometry gridGeometry package inherited
The grid extent, coordinate reference system (CRS) and conversion from cell indices to CRS.
See also
getGridGeometry()
Referenced by GridCoverage2D.evaluate(), GridCoverage.getGridGeometry(), GridCoverage2D.getGridGeometry2D(), GridCoverage2D.GridCoverage2D(), and GridCoverage2D.render().
isConverted
final boolean isConverted private
Whether this grid coverage is for converted values.
If
false
, then this coverage is for packed values.
Referenced by ConvertedGridCoverage.ConvertedGridCoverage().
source
final GridCoverage source private
The coverage containing source values.
Sample values will be converted from that coverage using the converters.
Referenced by ConvertedGridCoverage.ConvertedGridCoverage(), ConvertedGridCoverage.create(), and ConvertedGridCoverage.forConvertedValues().
VISIBLE_BAND
final int VISIBLE_BAND = 0 static package
The band to make visible when the image is shown on screen.
All other bands, if any, will be computed their result ignored at display time.
Referenced by GridCoverage2D.GridCoverage2D().