jena-geo: TemporalRangeWrapper Class Reference
TemporalRangeWrapper Class Reference
Static Public Member Functions
static TemporalRange extract (String lexicalForm, String datatypeURI) throws DatatypeFormatException
Member Function Documentation
extract()
static TemporalRange extract (String lexicalForm, String datatypeURI) throws DatatypeFormatException static
References TemporalRangeDatatype.INSTANCE, and TemporalRangeDatatype.parse().
Referenced by After.exec(), Starts.exec(), Before.exec(), EqualsPeriod.exec(), PeriodContains.exec(), Finishes.exec(), During.exec(), PeriodEnd.exec(), Minus.exec(), and PeriodStart.exec().
{
         if (lexicalForm == null || datatypeURI == null) {
             throw new DatatypeFormatException("GeometryWrapper extraction: arguments cannot be null - " + lexicalForm + ", " + datatypeURI);
         }
         TemporalRangeDatatype datatype = TemporalRangeDatatype.INSTANCE;
         TemporalRange geometry = (TemporalRange) datatype.parse(lexicalForm);
         return geometry;
     }