jena-geo: ImageUtilities Class Reference
ImageUtilities Class Reference
Utility methods related to images and their color model or sample model.
Static Public Member Functions
static Rectangle getBounds (final RenderedImage image)
Returns the bounds of the given image as a new rectangle.
static void clipBounds (final RenderedImage image, final Rectangle aoi)
Clips the given rectangle to the bounds of the given image.
static int getVisibleBand (final RenderedImage image)
If the given image is showing only one band, returns the index of that band.
static int getDataType (final RenderedImage image)
Returns the data type of the given image.
static int getDataType (final Raster raster)
Returns the data type of the given raster.
static String getDataTypeName (final SampleModel sm)
Returns the name of the DataBuffer type used by the given sample model.
static short getTransparencyDescription (final ColorModel cm)
Returns the key of a localizable text that describes the transparency.
static short [] bandNames (final RenderedImage image)
Returns names of bands based on inspection of the color model.
static int prepareTransferRegion (final Rectangle bounds, final int dataType)
Suggests the height of a transfer region for a tile of the given size.
Static Public Attributes
static final int DEFAULT_TILE_SIZE = 256
Default width and height of tiles, in pixels.
static final int SUGGESTED_TILE_CACHE_SIZE = 10 * (1024 * 1024) / (DEFAULT_TILE_SIZE * DEFAULT_TILE_SIZE)
Suggested size for a tile cache in number of tiles.
Static Package Functions
[static initializer]
Private Member Functions
ImageUtilities ()
Do not allow instantiation of this class.
Static Private Attributes
static final int BUFFER_SIZE = 32 * DEFAULT_TILE_SIZE * Byte.SIZE
Approximate size of the buffer to use for copying data from/to a raster, in bits.
static final String [] TYPE_NAMES = new String[DataBuffer.TYPE_DOUBLE + 1]
Names of DataBuffer types.
Detailed Description
Utility methods related to images and their color model or sample model.
Those methods only fetch information, they do not create new rasters or sample/color models (see
*Factory
classes for creating those objects).
Author
Martin Desruisseaux (Geomatys)
Version
1.1
Since
1.1
Constructor & Destructor Documentation
ImageUtilities()
ImageUtilities () private
Do not allow instantiation of this class.
{
     }
Member Function Documentation
[static initializer]()
[static initializer] () static package
bandNames()
static short [] bandNames (final RenderedImage image) static
Returns names of bands based on inspection of the color model.
The bands are identified by Vocabulary.Keys values for red, green, blue, cyan, magenta, yellow, black, gray, etc. If a band can not be identified, then its corresponding value is 0.
Parameters
image the image for which to get band names (can not be null).
Returns
Vocabulary.Keys identifying the bands.
{
         final SampleModel sm = image.getSampleModel();
         final int n;
         if (sm != null) {
             n = sm.getNumBands();
         } else {
             // Should not happen since SampleModel is essential, but we try to be robust.
             n = image.getTile(image.getMinTileX(), image.getMinTileY()).getNumBands();
         }
         final short[] keys = new short[n];
         final ColorModel cm = image.getColorModel();
         if (cm instanceof IndexColorModel) {
             /*
              * IndexColorModel normally uses exactly one band. But SIS has a custom subtype which
              * allows to use an arbitrary band for displaying purpose and ignore all other bands.
              */
             int visibleBand = 0;
             if (cm instanceof MultiBandsIndexColorModel) {
                 visibleBand = ((MultiBandsIndexColorModel) cm).visibleBand;
             }
             /*if (visibleBand < n) {
                 keys[visibleBand] = Vocabulary.Keys.ColorIndex;
             }*/
         } else if (cm != null) {
             final ColorSpace cs = cm.getColorSpace();
             if (cs != null) {
                 /*
                  * Get one of the following sets of color names (ignoring order for now):
                  *
                  *   - Red, Green, Blue
                  *   - Cyan, Magenta, Yellow, Black
                  *   - Gray
                  */
                 switch (cs.getType()) {
                     case ColorSpace.TYPE_CMYK: {
                         if (n >= 4)  keys[3] = Vocabulary.Keys.Black;
                         // Fallthrough
                     }
                     case ColorSpace.TYPE_CMY: {
                         switch (n) {
                             default: keys[2] = Vocabulary.Keys.Yellow;      // Fallthrough everywhere.
                             case 2:  keys[1] = Vocabulary.Keys.Magenta;
                             case 1:  keys[0] = Vocabulary.Keys.Cyan;
                             case 0:  break;
                         }
                         break;
                     }
                     case ColorSpace.TYPE_RGB: {
                         switch (n) {
                             default: keys[2] = Vocabulary.Keys.Blue;        // Fallthrough everywhere.
                             case 2:  keys[1] = Vocabulary.Keys.Green;
                             case 1:  keys[0] = Vocabulary.Keys.Red;
                             case 0:  break;
                         }
                         break;
                     }
                     case ColorSpace.TYPE_GRAY: {
                         if (n != 0)  keys[0] = Vocabulary.Keys.Gray;
                         break;
                     }
                 }
                 /*
                  * If the color model has more components than the number of colors,
                  * then the additional component is an alpha channel.
                  */
                 final int nc = cm.getNumColorComponents();
                 if (nc < n && nc < cm.getNumComponents()) {
                     keys[nc] = Vocabulary.Keys.Transparency;
                 }
                 /*
                  * In current version we do not try to adapt the bands order to the masks.
                  * A few tests suggest that the following methods provide the same values:
                  *
                  *   - PackedColorModel.getMasks()
                  *   - SinglePixelPackedSampleModel.getBitMasks()
                  *
                  * For a BufferedImage.TYPE_INT_ARGB, both methods give in that order:
                  *
                  *    masks[0]:  00FF0000     (red)
                  *    masks[1]:  0000FF00     (green)
                  *    masks[2]:  000000FF     (blue)
                  *    masks[3]:  FF000000     (alpha)  —  this last element is absent with TYPE_INT_RGB.
                  *
                  * For a BufferedImage.TYPE_INT_BGR, both methods give in that order:
                  *
                  *    masks[0]:  000000FF     (red)
                  *    masks[1]:  0000FF00     (green)
                  *    masks[2]:  00FF0000     (blue)
                  *
                  * So it looks like that SampleModel already normalizes the color components
                  * to (Red, Green, Blue) order, at least when the image has been created with
                  * a standard constructor. However we do not know yet what would be the behavior
                  * if masks are not the same. For now we just log a warning.
                  */
                 int[] m1 = null;
                 int[] m2 = null;
                 if (cm instanceof PackedColorModel) {
                     m1 = ((PackedColorModel) cm).getMasks();
                 }
                 if (sm instanceof SinglePixelPackedSampleModel) {
                     m2 = ((SinglePixelPackedSampleModel) sm).getBitMasks();
                 }
                 if (!Arrays.equals(m1, m2)) {
                     // If this logging happen, we should revisit this method and improve it.
                     Logging.getLogger(Modules.RASTER).warning("Band names may be in wrong order.");
                 }
             }
         }
         return keys;
     }
clipBounds()
static void clipBounds (final RenderedImage image, final Rectangle aoi) static
Clips the given rectangle to the bounds of the given image.
Parameters
image the image.
aoi a region of interest to clip to the image bounds.
Referenced by BandedSampleConverter.Writable.setData().
{
         int low = aoi.x;
         int min = image.getMinX();
         if (low < min) aoi.x = min;
         aoi.width = Numerics.clamp(Math.min(
                 ((long) min) + image.getWidth(),
                 ((long) low) + aoi.width) - aoi.x);
         low = aoi.y;
         min = image.getMinY();
         if (low < min) aoi.y = min;
         aoi.height = Numerics.clamp(Math.min(
                 ((long) min) + image.getHeight(),
                 ((long) low) + aoi.height) - aoi.y);
     }
getBounds()
static Rectangle getBounds (final RenderedImage image) static
Returns the bounds of the given image as a new rectangle.
Parameters
image the image for which to get the bounds.
Returns
the bounds of the given image.
See also
Raster::getBounds()
Referenced by PlanarImage.copyData(), PlanarImage.getBounds(), and PlanarImage.getData().
{
         return new Rectangle(image.getMinX(), image.getMinY(), image.getWidth(), image.getHeight());
     }
getDataType() [1/2]
static int getDataType (final RenderedImage image) static
Returns the data type of the given image.
Parameters
image the image for which to get the data type, or
null
.
Returns
the data type, or DataBuffer#TYPE_UNDEFINED if unknown.
Referenced by BandedSampleConverter.BandedSampleConverter().
{
         if (image != null) {
             final SampleModel sm = image.getSampleModel();
             if (sm != null) return sm.getDataType();            // Should never be null, but we are paranoiac.
         }
         return DataBuffer.TYPE_UNDEFINED;
     }
getDataType() [2/2]
static int getDataType (final Raster raster) static
Returns the data type of the given raster.
Parameters
raster the raster for which to get the data type, or
null
.
Returns
the data type, or DataBuffer#TYPE_UNDEFINED if unknown.
{
         if (raster != null) {
             final DataBuffer buffer = raster.getDataBuffer();
             if (buffer != null) {
                 return buffer.getDataType();
             }
         }
         return DataBuffer.TYPE_UNDEFINED;
     }
getDataTypeName()
static String getDataTypeName (final SampleModel sm) static
Returns the name of the DataBuffer type used by the given sample model.
Parameters
sm the sample model for which to get the data type name, or
null
.
Returns
name of the given constant, or
null
if unknown.
Referenced by GridCoverage2D.appendDataLayout(), and PlanarImage.toString().
{
         if (sm != null) {
             final int type = sm.getDataType();
             if (type >= 0 && type < TYPE_NAMES.length) {
                 return TYPE_NAMES[type];
             }
         }
         return null;
     }
getTransparencyDescription()
static short getTransparencyDescription (final ColorModel cm) static
Returns the key of a localizable text that describes the transparency.
This method returns one of the following values:
Resources.Keys#ImageAllowsTransparency
Resources.Keys#ImageHasAlphaChannel
Resources.Keys#ImageIsOpaque
0 if the transparency is unknown.
Parameters
cm the color model from which to get the transparency, or
null
.
Returns
a Resources.Keys value for the transparency, or 0 if unknown.
Referenced by GridCoverage2D.appendDataLayout().
{
         if (cm != null) {
             if (cm.hasAlpha()) {
                 return Resources.Keys.ImageHasAlphaChannel;
             }
             switch (cm.getTransparency()) {
                 case ColorModel.TRANSLUCENT:
                 case ColorModel.BITMASK: return Resources.Keys.ImageAllowsTransparency;
                 case ColorModel.OPAQUE:  return Resources.Keys.ImageIsOpaque;
             }
         }
         return 0;
     }
getVisibleBand()
static int getVisibleBand (final RenderedImage image) static
If the given image is showing only one band, returns the index of that band.
Otherwise returns 0. Image showing only one band are SIS-specific (usually an image show all its bands).
Parameters
image the image for which to get the visible band, or
null
.
Returns
index of the visible band, or -1 if there is none or more than one.
{
         if (image != null) {
             final ColorModel cm = image.getColorModel();
             if (cm != null) {
                 final ColorSpace cs = cm.getColorSpace();
                 if (cs instanceof ScaledColorSpace) {
                     return ((ScaledColorSpace) cs).visibleBand;
                 }
                 if (cm instanceof MultiBandsIndexColorModel) {
                     return ((MultiBandsIndexColorModel) cm).visibleBand;
                 }
                 if (cm.getNumComponents() == 1) {
                     return 0;
                 }
             }
         }
         return -1;
     }
prepareTransferRegion()
static int prepareTransferRegion (final Rectangle bounds, final int dataType) static
Suggests the height of a transfer region for a tile of the given size.
The given region should be contained inside Raster#getBounds(). This method modifies Rectangle#height in-place. The Rectangle#width value is never modified, so caller can iterate on all raster rows without the need to check if the row is incomplete.
Parameters
bounds on input, the region of interest. On output, the suggested transfer region bounds.
dataType one of DataBuffer constant. It is okay if an unknown constant is used since this information is used only as a hint for adjusting the BUFFER_SIZE value.
Returns
the maximum y value plus 1. This can be used as stop condition for iterating over rows.
Exceptions
ArithmeticException if the maximum y value overflows 32 bits integer capacity.
RasterFormatException if the given bounds is empty.
References ImageUtilities.BUFFER_SIZE.
Referenced by PlanarImage.copyData().
{
         if (bounds.isEmpty()) {
             throw new RasterFormatException(Resources.format(Resources.Keys.EmptyTileOrImageRegion));
         }
         final int afterLastRow = Math.addExact(bounds.y, bounds.height);
         int size;
         try {
             size = DataBuffer.getDataTypeSize(dataType);
         } catch (IllegalArgumentException e) {
             size = Short.SIZE;  // Arbitrary value is okay because this is only a hint for choosing a buffer size.
         }
         bounds.height = Math.max(1, Math.min(BUFFER_SIZE / (size * bounds.width), bounds.height));
         return afterLastRow;
     }
Member Data Documentation
BUFFER_SIZE
final int BUFFER_SIZE = 32 * DEFAULT_TILE_SIZE * Byte.SIZE static private
Approximate size of the buffer to use for copying data from/to a raster, in bits.
The actual buffer size may be smaller or larger, depending on the actual tile size. This value does not need to be very large. The current value is 8 kb.
See also
prepareTransferRegion(Rectangle, int)
Referenced by ImageUtilities.prepareTransferRegion().
DEFAULT_TILE_SIZE
final int DEFAULT_TILE_SIZE = 256 static
Default width and height of tiles, in pixels.
SUGGESTED_TILE_CACHE_SIZE
final int SUGGESTED_TILE_CACHE_SIZE = 10 * (1024 * 1024) / (DEFAULT_TILE_SIZE * DEFAULT_TILE_SIZE) static
Suggested size for a tile cache in number of tiles.
This value can be used for very simple caching mechanism, keeping the most recently used tiles up to 10 Mb of memory. This is not for sophisticated caching mechanism; instead the "real" caching should be done by org.apache.sis.image.ComputedImage.
TYPE_NAMES
final String [] TYPE_NAMES = new String[DataBuffer.TYPE_DOUBLE + 1] static private
Names of DataBuffer types.