jena-geo: DefaultMutableTreeNode Class Reference
DefaultMutableTreeNode Class Reference
General-purpose node in a tree data structure.
Public Member Functions
DefaultMutableTreeNode ()
Creates a tree node that has no parent and no children, but which allows children.
DefaultMutableTreeNode (Object userObject)
Creates a tree node with no parent, no children, but which allows children, and initializes it with the specified user object.
DefaultMutableTreeNode (Object userObject, boolean allowsChildren)
Creates a tree node with no parent, no children, initialized with the specified user object, and that allows children only if specified.
Locale getLocale ()
Returns the locale to use for the value returned by toString().
String toString ()
Returns the string value of the #userObject user object}, or.
Object getUserObject ()
Returns this node's user object.
Enumeration<? extends javax.swing.tree.TreeNode > children ()
Returns the children of this node as an.
Static Private Attributes
static final long serialVersionUID = -8782548896062360341L
Serial number for compatibility with different versions.
Detailed Description
General-purpose node in a tree data structure.
This default implementation implements the Geotk MutableTreeNode interface, which inherits a
getUserObject()
method. This method is provided in the Swing javax.swing.tree.DefaultMutableTreeNode implementation but seems to have been forgotten in all Swing interfaces.
In addition, the toString() method has been overridden in order to process InternationalString specially: if the value returned by getLocale() is non-null, then that value is used for getting a String from the
InternationalString
object.
Author
Martin Desruisseaux (IRD, Geomatys)
Version
3.17
Since
2.0
Constructor & Destructor Documentation
DefaultMutableTreeNode() [1/3]
DefaultMutableTreeNode ()
Creates a tree node that has no parent and no children, but which allows children.
{
         super(); // NOSONAR: Class name intentionally shadow superclass name.
     }
DefaultMutableTreeNode() [2/3]
DefaultMutableTreeNode (Object userObject)
Creates a tree node with no parent, no children, but which allows children, and initializes it with the specified user object.
Parameters
userObject an Object provided by the user that constitutes the node's data
{
         super(userObject);
     }
DefaultMutableTreeNode() [3/3]
DefaultMutableTreeNode (Object userObject, boolean allowsChildren)
Creates a tree node with no parent, no children, initialized with the specified user object, and that allows children only if specified.
Parameters
userObject an Object provided by the user that constitutes the node's data
allowsChildren if true, the node is allowed to have child nodes – otherwise, it is always a leaf node
{
         super(userObject, allowsChildren);
     }
Member Function Documentation
children()
Enumeration<? extends javax.swing.tree.TreeNode> children () inherited
Returns the children of this node as an.
Enumeration
.
Returns
The children.
Referenced by Trees.copy(), and TreeFormat.hasTreeTableNode().
getLocale()
Locale getLocale ()
Returns the locale to use for the value returned by toString().
The default implementation returns the locale of the #getParent() parent}, if any, or
null
otherwise.
Since
3.17
Referenced by NamedTreeNode.toString().
{
         javax.swing.tree.TreeNode parent = getParent();
         while (parent != null) {
             if (parent instanceof org.apache.sis.util.Localized) {
                 return ((org.apache.sis.util.Localized) parent).getLocale();
             }
             parent = parent.getParent();
         }
         return null;
     }
getUserObject()
Object getUserObject () inherited
Returns this node's user object.
Returns
the Object stored at this node by the user
toString()
String toString ()
Returns the string value of the #userObject user object}, or.
null
if none. This method is invoked by javax.swing.JTree for populating the tree widget. The string can be localized if the following conditions are meet:
the user object is an instance of InternationalString,
the locale returned by getLocale() is non-null.
In such case, this method returns the value of InternationalString#toString(Locale).
Returns
The localized string value of the #userObject user object}, or
null
if none.
Implements TreeNode.
{
         if (userObject instanceof InternationalString) {
             final Locale locale = getLocale();
             if (locale != null) {
                 return ((InternationalString) userObject).toString(locale);
             }
         }
         return super.toString();
     }
Member Data Documentation
serialVersionUID
final long serialVersionUID = -8782548896062360341L static private
Serial number for compatibility with different versions.