jena-geo: TiledImage Class Reference
TiledImage Class Reference
A rendered image which can contain an arbitrary number of tiles.
Public Member Functions
TiledImage (final ColorModel colorModel, final int width, final int height, final int minTileX, final int minTileY, final Raster... tiles)
Creates a new tiled image.
ColorModel getColorModel ()
Returns the color model, or.
SampleModel getSampleModel ()
Returns the sample model.
int getMinX ()
Returns the minimum x coordinate (inclusive) of this image.
int getMinY ()
Returns the minimum y coordinate (inclusive) of this image.
int getWidth ()
Returns the number of pixels along X axis in the whole rendered image.
int getHeight ()
Returns the number of pixels along Y axis in the whole rendered image.
int getTileWidth ()
Returns the tile width in pixels.
int getTileHeight ()
Returns the tile height in pixels.
int getMinTileX ()
Returns the minimum tile index in the X direction.
int getMinTileY ()
Returns the minimum tile index in the Y direction.
Raster getTile (int tileX, int tileY)
Returns the tile at the given location in tile coordinates.
Vector< RenderedImage > getSources ()
Returns the immediate sources of image data for this image.
Object getProperty (String key)
Gets a property from this image.
String [] getPropertyNames ()
Returns the names of all recognized properties, or.
Rectangle getBounds ()
Returns the image location (x, y) and image size (width, height).
int getNumXTiles ()
Returns the number of tiles in the x direction.
int getNumYTiles ()
Returns the number of tiles in the y direction.
int getTileGridXOffset ()
Returns the x coordinate of the upper-left pixel of tile (0, 0).
int getTileGridYOffset ()
Returns the y coordinate of the upper-left pixel of tile (0, 0).
Raster getData ()
Returns a copy of this image as one large tile.
Raster getData (final Rectangle aoi)
Returns a copy of an arbitrary region of this image.
WritableRaster copyData (WritableRaster raster)
Copies an arbitrary rectangular region of this image to the supplied writable raster.
String verify ()
Verifies whether image layout information are consistent.
String toString ()
Returns a string representation of this image for debugging purpose.
Static Public Attributes
static final String SAMPLE_RESOLUTIONS_KEY = "SampleResolution"
Key of a property defining the resolutions of sample values in each band.
Package Attributes
final int height
final int minTileY
Private Attributes
final ColorModel colorModel
The color model, or.
final int width
Number of pixels along X or Y axis in the whole rendered image.
final int minTileX
Index of the first tile in the image.
final Raster [] tiles
The tiles.
Detailed Description
A rendered image which can contain an arbitrary number of tiles.
Tiles are stored in memory. This class may become public in a future version, but not yet because managing large tiled images would require a more sophisticated class than current implementation.
This class should not perform any computation; all tiles are given at construction time. This requirement makes this class thread-safe and concurrent without the need for synchronization.
Author
Rémi Maréchal (Geomatys)
Martin Desruisseaux (Geomatys)
Version
1.1
Since
1.1
Constructor & Destructor Documentation
TiledImage()
TiledImage (final ColorModel colorModel, final int width, final int height, final int minTileX, final int minTileY, final Raster... tiles)
Creates a new tiled image.
The first tile in the given array must be the one located at the minimal tile indices. All tiles must have the same size and the same sample model and must be sorted in row-major fashion (this is not verified in current version, but may be in the future).
Parameters
colorModel the color model, or
null
if none.
width number of pixels along X axis in the whole rendered image.
height number of pixels along Y axis in the whole rendered image.
minTileX minimum tile index in the X direction.
minTileY minimum tile index in the Y direction.
tiles the tiles. Must contains at least one element.
References TiledImage.colorModel, TiledImage.height, TiledImage.minTileX, TiledImage.minTileY, TiledImage.tiles, and TiledImage.width.
     {
         ArgumentChecks.ensureStrictlyPositive("width",  width);
         ArgumentChecks.ensureStrictlyPositive("height", height);
         ArgumentChecks.ensureNonEmpty        ("tiles",  tiles);
         this.colorModel = colorModel;
         this.width      = width;
         this.height     = height;
         this.minTileX   = minTileX;
         this.minTileY   = minTileY;
         this.tiles      = tiles;
     }
Member Function Documentation
copyData()
WritableRaster copyData (WritableRaster raster) inherited
Copies an arbitrary rectangular region of this image to the supplied writable raster.
The region to be copied is determined from the bounds of the supplied raster. The supplied raster must have a SampleModel that is compatible with this image. If the raster is
null
, an raster is created by this method.
Parameters
raster the raster to hold a copy of this image, or
null
.
Returns
the given raster if it was not-null, or a new raster otherwise.
References PlanarImage.createWritableRaster(), and ImageUtilities.getBounds().
Referenced by PlanarImage.getData().
{
         final Rectangle aoi;
         if (raster != null) {
             aoi = raster.getBounds();
         } else {
             aoi = ImageUtilities.getBounds(this);
             raster = createWritableRaster(aoi);
         }
         copyData(aoi, raster);
         return raster;
     }
getBounds()
Rectangle getBounds () inherited
Returns the image location (x, y) and image size (width, height).
This is a convenience method encapsulating the results of 4 method calls in a single object.
Returns
the image location and image size as a new rectangle.
See also
getMinX()
getMinY()
getWidth()
getHeight()
References ImageUtilities.getBounds().
{
         return ImageUtilities.getBounds(this);
     }
getColorModel()
ColorModel getColorModel ()
Returns the color model, or.
null
if none.
References TiledImage.colorModel.
{
         return colorModel;
     }
getData() [1/2]
Raster getData () inherited
Returns a copy of this image as one large tile.
The returned raster will not be updated if this image is changed.
Returns
a copy of this image as one large tile.
References PlanarImage.copyData(), PlanarImage.createWritableRaster(), and ImageUtilities.getBounds().
{
         final Rectangle aoi = ImageUtilities.getBounds(this);
         final WritableRaster raster = createWritableRaster(aoi);
         copyData(aoi, raster);
         return raster;
     }
getData() [2/2]
Raster getData (final Rectangle aoi) inherited
Returns a copy of an arbitrary region of this image.
The returned raster will not be updated if this image is changed.
Parameters
aoi the region of this image to copy.
Returns
a copy of this image in the given area of interest.
Exceptions
IllegalArgumentException if the given rectangle is not contained in this image bounds.
References PlanarImage.copyData(), PlanarImage.createWritableRaster(), and ImageUtilities.getBounds().
{
         ArgumentChecks.ensureNonNull("aoi", aoi);
         if (!ImageUtilities.getBounds(this).contains(aoi)) {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.OutsideDomainOfValidity));
         }
         final WritableRaster raster = createWritableRaster(aoi);
         copyData(aoi, raster);
         return raster;
     }
getHeight()
int getHeight ()
Returns the number of pixels along Y axis in the whole rendered image.
References TiledImage.height.
{
         return height;
     }
getMinTileX()
int getMinTileX ()
Returns the minimum tile index in the X direction.
References TiledImage.minTileX.
{
         return minTileX;
     }
getMinTileY()
int getMinTileY ()
Returns the minimum tile index in the Y direction.
References TiledImage.minTileY.
{
         return minTileY;
     }
getMinX()
int getMinX ()
Returns the minimum x coordinate (inclusive) of this image.
{
         return tiles[0].getMinX();
     }
getMinY()
int getMinY ()
Returns the minimum y coordinate (inclusive) of this image.
{
         return tiles[0].getMinY();
     }
getNumXTiles()
int getNumXTiles () inherited
Returns the number of tiles in the x direction.
The default implementation computes this value from getWidth() and getTileWidth() on the assumption that getMinX() is the coordinate of the leftmost pixels of tiles located at getMinTileX() index. This assumption can be verified by verify().
Returns
returns the number of tiles in the x direction.
Referenced by TiledImage.getTile(), PlanarImage.toString(), and PlanarImage.verify().
{
         /*
          * If assumption documented in javadoc does not hold, the calculation performed here would need to be
          * more complicated: compute tile index of minX, compute tile index of maxX, return difference plus 1.
          */
         return Numerics.ceilDiv(getWidth(), getTileWidth());
     }
getNumYTiles()
int getNumYTiles () inherited
Returns the number of tiles in the y direction.
The default implementation computes this value from getHeight() and getTileHeight() on the assumption that getMinY() is the coordinate of the uppermost pixels of tiles located at getMinTileY() index. This assumption can be verified by verify().
Returns
returns the number of tiles in the y direction.
Referenced by TiledImage.getTile(), PlanarImage.toString(), and PlanarImage.verify().
{
         return Numerics.ceilDiv(getHeight(), getTileHeight());
     }
getProperty()
Object getProperty (String key) inherited
Gets a property from this image.
The property to get is identified by the specified key. Some keys supported by Apache SIS are:
Recognized property keys
Keys Values
{ SAMPLE_RESOLUTIONS_KEY} Resolutions of sample values in each band.
This method returns Image#UndefinedProperty if the specified property is not defined. The default implementation returns Image#UndefinedProperty in all cases.
Parameters
key the name of the property to get.
Returns
the property value, or Image#UndefinedProperty if none.
{
         return Image.UndefinedProperty;
     }
getPropertyNames()
String [] getPropertyNames () inherited
Returns the names of all recognized properties, or.
null
if this image has no properties.
The default implementation returns
null
.
Returns
names of all recognized properties, or
null
if none.
{
         return null;
     }
getSampleModel()
SampleModel getSampleModel ()
Returns the sample model.
{
         return tiles[0].getSampleModel();
     }
getSources()
Vector<RenderedImage> getSources () inherited
Returns the immediate sources of image data for this image.
This method returns
null
if the image has no information about its immediate sources. It returns an empty vector if the image object has no immediate sources.
The default implementation returns
null
. Note that this is not equivalent to an empty vector.
Returns
the immediate sources, or
null
if unknown.
{
         return null;
     }
getTile()
Raster getTile (int tileX, int tileY)
Returns the tile at the given location in tile coordinates.
References PlanarImage.getNumXTiles(), and PlanarImage.getNumYTiles().
{
         final int numXTiles = getNumXTiles();
         final int numYTiles = getNumYTiles();
         if ((tileX -= minTileX) < 0 || tileX >= numXTiles ||
             (tileY -= minTileY) < 0 || tileY >= numYTiles)
         {
             throw new IndexOutOfBoundsException();
         }
         return tiles[tileX + tileY * numXTiles];
     }
getTileGridXOffset()
int getTileGridXOffset () inherited
Returns the x coordinate of the upper-left pixel of tile (0, 0).
That tile (0, 0) may not actually exist.
The default implementation computes this value from getMinX(), getMinTileX() and getTileWidth().
Returns
the x offset of the tile grid relative to the origin.
References PlanarImage.getMinTileX(), and PlanarImage.getMinX().
Referenced by PlanarImage.verify().
{
         // We may have temporary `int` overflow after multiplication but exact result after addition.
         return Math.toIntExact(getMinX() - JDK9.multiplyFull(getMinTileX(), getTileWidth()));
     }
getTileGridYOffset()
int getTileGridYOffset () inherited
Returns the y coordinate of the upper-left pixel of tile (0, 0).
That tile (0, 0) may not actually exist.
The default implementation computes this value from getMinY(), getMinTileY() and getTileHeight().
Returns
the y offset of the tile grid relative to the origin.
References PlanarImage.getMinTileY(), and PlanarImage.getMinY().
Referenced by PlanarImage.verify().
{
         return Math.toIntExact(getMinY() - JDK9.multiplyFull(getMinTileY(), getTileHeight()));
     }
getTileHeight()
int getTileHeight ()
Returns the tile height in pixels.
All tiles must have the same height.
{
         return tiles[0].getHeight();
     }
getTileWidth()
int getTileWidth ()
Returns the tile width in pixels.
All tiles must have the same width.
{
         return tiles[0].getWidth();
     }
getWidth()
int getWidth ()
Returns the number of pixels along X axis in the whole rendered image.
References TiledImage.width.
{
         return width;
     }
toString()
String toString () inherited
Returns a string representation of this image for debugging purpose.
This string representation may change in any future SIS version.
Returns
a string representation of this image for debugging purpose only.
References ColorModelFactory.formatDescription(), ImageUtilities.getDataTypeName(), PlanarImage.getNumXTiles(), PlanarImage.getNumYTiles(), and PlanarImage.verify().
{
         final StringBuilder buffer = new StringBuilder(100).append(Classes.getShortClassName(this))
                 .append('[').append(getWidth()).append(" × ").append(getHeight()).append(" pixels");
         final SampleModel sm = getSampleModel();
         if (sm != null) {
             buffer.append(" × ").append(sm.getNumBands()).append(" bands");
             final String type = ImageUtilities.getDataTypeName(sm);
             if (type != null) {
                 buffer.append(" of type ").append(type);
             }
         }
         /*
          * Write details about color model only if there is "useful" information for a geospatial raster.
          * The main category of interest are "color palette" versus "gray scale" versus everything else,
          * and whether the image may have transparent pixels.
          */
         final ColorModel cm = getColorModel();
 colors: if (cm != null) {
             buffer.append("; ");
             if (cm instanceof IndexColorModel) {
                 buffer.append(((IndexColorModel) cm).getMapSize()).append(" indexed colors");
             } else {
                 ColorModelFactory.formatDescription(cm.getColorSpace(), buffer);
             }
             final String transparency;
             switch (cm.getTransparency()) {
                 case ColorModel.OPAQUE:      transparency = "opaque"; break;
                 case ColorModel.TRANSLUCENT: transparency = "translucent"; break;
                 case ColorModel.BITMASK:     transparency = "bitmask transparency"; break;
                 default: break colors;
             }
             buffer.append("; ").append(transparency);
         }
         /*
          * Tiling information last because it is usually a secondary aspect compared to above information.
          * If a warning is emitted, it will usually be a tiling problem so it is useful to keep it close.
          */
         final int tx = getNumXTiles();
         final int ty = getNumYTiles();
         if (tx != 1 || ty != 1) {
             buffer.append("; ").append(tx).append(" × ").append(ty).append(" tiles");
         }
         final String error = verify();
         if (error != null) {
             buffer.append("; ⚠ mismatched ").append(error);
         }
         return buffer.append(']').toString();
     }
verify()
String verify () inherited
Verifies whether image layout information are consistent.
This method verifies that the coordinates of image upper-left corner are equal to the coordinates of the upper-left corner of the tile in the upper-left corner, and that image size is equal to the sum of the sizes of all tiles. Compatibility of sample model and color model is also verified.
The default implementation may return the following identifiers, in that order (i.e. this method returns the identifier of the first test that fail):
"SampleModel"
— Sample model is incompatible with color model.
"tileWidth"
— tile width is greater than sample model width.
"tileHeight"
— tile height is greater than sample model height.
"numXTiles"
— number of tiles on the X axis is inconsistent with image width.
"numYTiles"
— number of tiles on the Y axis is inconsistent with image height.
"tileX"
— { minTileX} and/or
tileGridXOffset
is inconsistent.
"tileY"
— { minTileY} and/or
tileGridYOffset
is inconsistent.
Subclasses may perform additional checks. For example some subclasses also check specifically for
"minX"
,
"minY"
,
"tileGridXOffset"
and
"tileGridYOffset"
.
Returns
null
if image layout information are consistent, or the name of inconsistent attribute if a problem is found.
References PlanarImage.getMinTileX(), PlanarImage.getMinTileY(), PlanarImage.getMinX(), PlanarImage.getMinY(), PlanarImage.getNumXTiles(), PlanarImage.getNumYTiles(), PlanarImage.getTileGridXOffset(), and PlanarImage.getTileGridYOffset().
Referenced by PlanarImage.toString().
{
         final int tileWidth  = getTileWidth();
         final int tileHeight = getTileHeight();
         final SampleModel sm = getSampleModel();
         if (sm != null) {
             final ColorModel cm = getColorModel();
             if (cm != null) {
                 if (!cm.isCompatibleSampleModel(sm)) return "SampleModel";
             }
             /*
              * The SampleModel size represents the physical layout of pixels in the data buffer,
              * while the Raster may be a virtual view over a sub-region of a parent raster.
              */
             if (sm.getWidth()  < tileWidth)  return "tileWidth";
             if (sm.getHeight() < tileHeight) return "tileHeight";
         }
         if (JDK9.multiplyFull(getNumXTiles(), tileWidth)  != getWidth())  return "numXTiles";
         if (JDK9.multiplyFull(getNumYTiles(), tileHeight) != getHeight()) return "numYTiles";
         if (JDK9.multiplyFull(getMinTileX(),  tileWidth)  + getTileGridXOffset() != getMinX()) return "tileX";
         if (JDK9.multiplyFull(getMinTileY(),  tileHeight) + getTileGridYOffset() != getMinY()) return "tileY";
         return null;
     }
Member Data Documentation
colorModel
final ColorModel colorModel private
The color model, or.
null
if none.
Referenced by TiledImage.getColorModel(), and TiledImage.TiledImage().
height
final int height package
Referenced by TiledImage.getHeight(), and TiledImage.TiledImage().
minTileX
final int minTileX private
Index of the first tile in the image.
Should be a non-trivial value for increasing the chances to detect error in index calculation.
Referenced by TiledImage.getMinTileX(), and TiledImage.TiledImage().
minTileY
final int minTileY package
Referenced by TiledImage.getMinTileY(), and TiledImage.TiledImage().
SAMPLE_RESOLUTIONS_KEY
final String SAMPLE_RESOLUTIONS_KEY = "SampleResolution" static inherited
Key of a property defining the resolutions of sample values in each band.
This property is recommended for images having sample values as floating point numbers. For example if sample values were computed by value = integer × scale factor, then the resolution is the scale factor. This information is used for choosing the number of fraction digits to show when writing sample values in text format.
Values should be instances of
float[]
or
double[]
. The array length should be the number of bands.
tiles
final Raster [] tiles private
The tiles.
They must all use the same sample model.
Referenced by TiledImage.TiledImage().
width
final int width private
Number of pixels along X or Y axis in the whole rendered image.
Referenced by TiledImage.getWidth(), and TiledImage.TiledImage().