jena-geo: ProjectedShape Class Reference
ProjectedShape Class Reference
Applies an arbitrary MathTransform2D (typically a projection) on a Shape.
Public Member Functions
boolean contains (final double x, final double y)
Tests if the specified coordinate is inside the boundary of this shape.
boolean contains (final Point2D p)
Tests if a specified Point2D is inside the boundary of this shape.
boolean contains (final double x, final double y, final double width, final double height)
Tests if the interior of this shape entirely contains the specified rectangular area.
boolean contains (final Rectangle2D r)
Tests if the interior of this shape entirely contains the specified rectangle.
boolean intersects (double x, double y, double width, double height)
Tests if the interior of this shape intersects the interior of a specified rectangular area.
boolean intersects (final Rectangle2D r)
Tests if the interior of this shape intersects the interior of a specified rectangle.
Rectangle getBounds ()
Returns an integer rectangle that completely encloses this shape.
Rectangle2D getBounds2D ()
Returns a high precision and more accurate bounding box of the shape than the getBounds method.
PathIterator getPathIterator (final AffineTransform at)
Returns an iterator object that iterates along the shape boundary and provides access to the geometry of the shape outline.
PathIterator getPathIterator (final AffineTransform at, final double flatness)
Returns an iterator object that iterates along the shape boundary and provides access to a flattened view of the shape outline geometry.
int hashCode ()
Returns a hash code value for this shape.
boolean equals (final Object object)
Compares this shape with the given object for equality.
Static Public Member Functions
static Shape wrap (final Shape shape, final MathTransform2D projection)
Returns a new shape wrapping the given shape and applying the given transform on the fly.
Protected Member Functions
ProjectedShape (final Shape shape, final MathTransform2D projection)
Creates a new shape as a transform of the given shape.
Protected Attributes
final Shape shape
The original shape to transform.
final MathTransform2D projection
The operation to apply on the original shape.
Private Member Functions
MathTransform2D inverse () throws NoninvertibleTransformException
Returns the inverse of projection.
MathTransform2D concatenate (final AffineTransform at)
Returns the concatenation of the projection} with the given affine transform.
Private Attributes
transient MathTransform2D inverse
The inverse of projection, computed when first needed.
transient Point2D.Double point
A temporary point.
transient Rectangle2D.Double rectangle
A temporary rectangle.
Static Private Attributes
static final long serialVersionUID = -583674918489345612L
For cross-version compatibility.
Detailed Description
Applies an arbitrary MathTransform2D (typically a projection) on a Shape.
A
ProjectedShape
instance is a view over a shape, i.e. the shape coordinates are transformed on the fly, never copied. Consequently this class consumes very few memory, but may consume more CPU if the same shape is rendered many time.
{
lines and curves}
Straight line segments may become curves after the transform. This class can create quadratic or cubic curves approximating the original line segments.
Author
Rémi Maréchal (Geomatys)
Martin Desruisseaux (Geomatys)
Version
3.20
See also
TransformedShape
Since
3.20
Constructor & Destructor Documentation
ProjectedShape()
ProjectedShape (final Shape shape, final MathTransform2D projection) protected
Creates a new shape as a transform of the given shape.
This constructor is for subclasses only. Users should invoke the static wrap(Shape, MathTransform2D) method instead.
Parameters
shape The original shape to transform.
projection The operation to apply on the given shape.
References ProjectedShape.projection, and ProjectedShape.shape.
Referenced by ProjectedShape.equals(), and ProjectedShape.wrap().
{
         ArgumentChecks.ensureNonNull("shape", shape);
         ArgumentChecks.ensureNonNull("projection", projection);
         this.shape = shape;
         this.projection = projection;
     }
Member Function Documentation
concatenate()
MathTransform2D concatenate (final AffineTransform at) private
Returns the concatenation of the projection} with the given affine transform.
Parameters
at The affine transform to concatenate, or
null
if none.
References ProjectedShape.projection.
Referenced by ProjectedShape.getPathIterator().
{
         MathTransform2D concatenated = projection;
         if (at != null && !at.isIdentity()) {
             concatenated = MathTransforms.concatenate(concatenated, new AffineTransform2D(at));
         }
         return concatenated;
     }
contains() [1/4]
boolean contains (final double x, final double y)
Tests if the specified coordinate is inside the boundary of this shape.
This method might conservatively return
false
if the point can not be transformed.
The default implementation delegates to contains(Point2D).
Parameters
x The x ordinate of the point to be tested.
y The y ordinate of the point to be tested.
Returns
true
if this shape contains the given point.
References ProjectedShape.point.
Referenced by ProjectedShape.contains().
{
         Point2D.Double p = point;
         if (p == null) {
             point = p = new Point2D.Double();
         }
         p.x = x;
         p.y = y;
         return contains(p);
     }
contains() [2/4]
boolean contains (final Point2D p)
Tests if a specified Point2D is inside the boundary of this shape.
This method might conservatively return
false
if the point can not be transformed.
Parameters
p The point to be tested.
Returns
true
if this shape contains the given point.
References ProjectedShape.inverse(), and ProjectedShape.point.
{
         try {
             return shape.contains(inverse().transform(p, point));
         } catch (TransformException exception) {
             Logging.recoverableException(null, ProjectedShape.class, "contains", exception);
             return false;
         }
     }
contains() [3/4]
boolean contains (final double x, final double y, final double width, final double height)
Tests if the interior of this shape entirely contains the specified rectangular area.
This method might conservatively return
false
if some points can not be transformed.
The default implementation delegates to contains(Rectangle2D).
Parameters
x The minimal x ordinate of the rectangle to be tested.
y The minimal y ordinate of the rectangle to be tested.
width The width of the rectangle to be tested.
height The height of the rectangle to be tested.
Returns
true
if this shape contains the given rectangle.
References ProjectedShape.contains(), and ProjectedShape.rectangle.
{
         Rectangle2D.Double r = rectangle;
         if (r == null) {
             rectangle = r = new Rectangle2D.Double();
         }
         r.x = x;
         r.y = y;
         r.width = width;
         r.height = height;
         return contains(r);
     }
contains() [4/4]
boolean contains (final Rectangle2D r)
Tests if the interior of this shape entirely contains the specified rectangle.
This method might conservatively return
false
if some points can not be transformed.
Parameters
r The rectangle to be tested.
Returns
true
if this shape contains the given rectangle.
References ProjectedShape.rectangle.
{
         try {
             return shape.contains(Shapes2D.transform(inverse(), r, rectangle));
         } catch (TransformException exception) {
             Logging.recoverableException(null, ProjectedShape.class, "contains", exception);
             return false; // Consistent with the Shape interface contract.
         }
     }
equals()
boolean equals (final Object object)
Compares this shape with the given object for equality.
Parameters
object The object to compare with this shape.
References ProjectedShape.ProjectedShape(), ProjectedShape.projection, and ProjectedShape.shape.
{
         if (object instanceof ProjectedShape) {
             final ProjectedShape other = (ProjectedShape) object;
             return shape.equals(other.shape) && projection.equals(other.projection);
         }
         return false;
     }
getBounds()
Rectangle getBounds ()
Returns an integer rectangle that completely encloses this shape.
The default implementation delegates to getBounds2D() and cast the resulting rectangle.
{
         final Rectangle bounds = new Rectangle();
         bounds.setRect(bounds);
         return bounds;
     }
getBounds2D()
Rectangle2D getBounds2D ()
Returns a high precision and more accurate bounding box of the shape than the getBounds method.
This method returns an infinite rectangle if some points can not be transformed.
References XRectangle2D.INFINITY.
{
         try {
             return Shapes2D.transform(projection, shape.getBounds2D(), null);
         } catch (TransformException exception) {
             Logging.recoverableException(null, ProjectedShape.class, "getBounds2D", exception);
             return XRectangle2D.INFINITY;
         }
     }
getPathIterator() [1/2]
PathIterator getPathIterator (final AffineTransform at)
Returns an iterator object that iterates along the shape boundary and provides access to the geometry of the shape outline.
References ProjectedShape.concatenate().
{
         final MathTransform2D concatenated = concatenate(at);
         if (concatenated.isIdentity()) {
             return shape.getPathIterator(at);
         }
         return new ProjectedPathIterator(shape.getPathIterator(null), concatenated);
     }
getPathIterator() [2/2]
PathIterator getPathIterator (final AffineTransform at, final double flatness)
Returns an iterator object that iterates along the shape boundary and provides access to a flattened view of the shape outline geometry.
References ProjectedShape.concatenate().
{
         final MathTransform2D concatenated = concatenate(at);
         if (concatenated.isIdentity()) {
             return shape.getPathIterator(at, flatness);
         }
         return new FlatteningPathIterator(new ProjectedPathIterator(shape.getPathIterator(null), concatenated), flatness);
     }
hashCode()
int hashCode ()
Returns a hash code value for this shape.
{
         return shape.hashCode() ^ projection.hashCode() ^ (int) serialVersionUID;
     }
intersects() [1/2]
boolean intersects (double x, double y, double width, double height)
Tests if the interior of this shape intersects the interior of a specified rectangular area.
This method might conservatively return
true
if some points can not be transformed.
The default implementation delegates to intersects(Rectangle2D).
Parameters
x The minimal x ordinate of the rectangle to be tested.
y The minimal y ordinate of the rectangle to be tested.
width The width of the rectangle to be tested.
height The height of the rectangle to be tested.
Returns
true
if this shape intersects the given rectangle.
References ProjectedShape.rectangle.
{
         Rectangle2D.Double r = rectangle;
         if (r == null) {
             rectangle = r = new Rectangle2D.Double();
         }
         r.x = x;
         r.y = y;
         r.width = width;
         r.height = height;
         return intersects(r);
     }
intersects() [2/2]
boolean intersects (final Rectangle2D r)
Tests if the interior of this shape intersects the interior of a specified rectangle.
This method might conservatively return
true
if some points can not be transformed.
Parameters
r The rectangle to be tested.
Returns
true
if this shape intersects the given rectangle.
References ProjectedShape.rectangle.
{
         try {
             return shape.intersects(Shapes2D.transform(inverse(), r, rectangle));
         } catch (TransformException exception) {
             Logging.recoverableException(null, ProjectedShape.class, "intersects", exception);
             return true; // Consistent with the Shape interface contract.
         }
     }
inverse()
MathTransform2D inverse () throws NoninvertibleTransformException private
Returns the inverse of projection.
This method initializes also the point and rectangle fields as a side-effect, since they will be needed together with the inverse transform.
References ProjectedShape.point, and ProjectedShape.rectangle.
Referenced by ProjectedShape.contains().
{
         if (inverse == null) {
             inverse = projection.inverse();
             if (point     == null) point     = new Point2D    .Double();
             if (rectangle == null) rectangle = new Rectangle2D.Double();
         }
         return inverse;
     }
wrap()
static Shape wrap (final Shape shape, final MathTransform2D projection) static
Returns a new shape wrapping the given shape and applying the given transform on the fly.
If the transform is
null
or an MathTransform2D::isIdentity() identity} transform, then this method returns the given shape unchanged. Otherwise if the transform is AffineTransform affine}, then this method wraps the given shape in an TransformedShape. Otherwise this method wraps the given shape in a
ProjectedShape
.
Parameters
shape The original shape to transform.
projection The operation to apply on the given shape.
Returns
A view over the given shape, transformed by the given transform.
References ProjectedShape.ProjectedShape(), and ProjectedShape.shape.
{
         if (projection == null || projection.isIdentity()) {
             return shape;
         }
         if (projection instanceof AffineTransform) {
             return new TransformedShape(shape, (AffineTransform) projection);
         }
         return new ProjectedShape(shape, projection);
     }
Member Data Documentation
inverse
transient MathTransform2D inverse private
The inverse of projection, computed when first needed.
point
transient Point2D.Double point private
A temporary point.
Referenced by ProjectedShape.contains(), and ProjectedShape.inverse().
projection
final MathTransform2D projection protected
The operation to apply on the original shape.
Referenced by ProjectedShape.concatenate(), ProjectedShape.equals(), and ProjectedShape.ProjectedShape().
rectangle
transient Rectangle2D.Double rectangle private
A temporary rectangle.
Referenced by ProjectedShape.contains(), ProjectedShape.intersects(), and ProjectedShape.inverse().
serialVersionUID
final long serialVersionUID = -583674918489345612L static private
For cross-version compatibility.
shape
final Shape shape protected
The original shape to transform.
Referenced by ProjectedShape.equals(), ProjectedShape.ProjectedShape(), and ProjectedShape.wrap().