jena-geo: SerializedKey Class Reference
SerializedKey Class Reference
A proxy for the serialization of Hints#Key.
Public Member Functions
String toString ()
Returns the fully qualified name of the field (including the class name).
Protected Member Functions
Object readResolve () throws ObjectStreamException
On deserialization, replace this proxy by the static constant.
Package Functions
SerializedKey (final RenderingHints.Key key) throws NotSerializableException
Creates a new proxy for the given key.
Private Attributes
final Class<?> definer
The class that define the key constants.
final String field
The static field name to query for getting the key constant.
Static Private Attributes
static final long serialVersionUID = -7330917618436040846L
For cross-version compatibility.
Detailed Description
A proxy for the serialization of Hints#Key.
Author
Martin Desruisseaux (Geomatys)
Version
3.05
Since
3.05
Constructor & Destructor Documentation
SerializedKey()
SerializedKey (final RenderingHints.Key key) throws NotSerializableException package
Creates a new proxy for the given key.
Exceptions
NotSerializableException If the given key is not declared as a static constant in its Class::getEnclosingClass() enclosing class}.
References Hints.fieldOf(), Errors.format(), and Errors.Keys.UnknownType_1.
{
         final Field f = Hints.fieldOf(key);
         if (f == null) {
             throw new NotSerializableException(Errors.format(
                     Errors.Keys.UnknownType_1, Classes.getShortClassName(key)));
         }
         definer = f.getDeclaringClass();
         field   = f.getName();
     }
Member Function Documentation
readResolve()
Object readResolve () throws ObjectStreamException protected
On deserialization, replace this proxy by the static constant.
Returns
The resolved key.
Exceptions
ObjectStreamException If the key has not been found. This exception should not occur is the key is deserialized using the same Geotk version than the one that serialized the key.
References Errors.format(), and Errors.Keys.IllegalKey_1.
{
         try {
             return definer.getField(field).get(null);
         } catch (ReflectiveOperationException cause) {
             final InvalidClassException e = new InvalidClassException(definer.getName(),
                     Errors.format(Errors.Keys.IllegalKey_1, this));
             e.initCause(cause);
             throw e;
         }
     }
toString()
String toString ()
Returns the fully qualified name of the field (including the class name).
References SerializedKey.field.
{
         return definer.getCanonicalName() + '.' + field;
     }
Member Data Documentation
definer
final Class<?> definer private
The class that define the key constants.
field
final String field private
The static field name to query for getting the key constant.
Referenced by SerializedKey.toString().
serialVersionUID
final long serialVersionUID = -7330917618436040846L static private
For cross-version compatibility.