jena-geo: TreeTableNode Interface Reference
TreeTableNode Interface Reference
Defines the requirements for an object that can be used as a tree node in a org.jdesktop.swingx.JXTreeTable.
Public Member Functions
int getColumnCount ()
Returns the number of columns supported by this.
Class<?> getColumnClass (int column)
Returns the most specific superclass of values that can be stored in the given column.
Object getValueAt (int column)
Gets the value for this node that corresponds to a particular tabular column.
void setValueAt (Object value, int column)
Sets the value for the given column.
boolean isEditable (int column)
Determines whether the specified column is editable.
Object getUserObject ()
Returns this node's user object.
Enumeration<? extends javax.swing.tree.TreeNode > children ()
Returns the children of this node as an.
String toString ()
Returns a string representation of this node suitable for a user interface.
Detailed Description
Defines the requirements for an object that can be used as a tree node in a org.jdesktop.swingx.JXTreeTable.
This interface is used as a placeholder for the org.jdesktop.swingx.treetable.TreeTableNode interface defined in SwingX, in order to identify the code where we would use the later interface if we were allowed to introduce <cite>SwingX</cite> dependencies.
The first dependency to <cite>SwingX</cite> appears in the geotk-widgets-swing module, which provides an org.geotoolkit.gui.swing.TreeTableModelAdapter adapter} from this interface to the SwingX org.jdesktop.swingx.treetable.TreeTableModel tree table model}.
Author
Martin Desruisseaux (Geomatys)
Version
3.04
See also
org.jdesktop.swingx.JXTreeTable
org.geotoolkit.gui.swing.TreeTableModelAdapter
Since
3.04
Deprecated:
The org.apache.sis.util.collection.TreeTable tree model in Apache SIS} is no longer based on Swing tree interfaces. Swing dependencies will be phased out since Swing itself is likely to be replaced by JavaFX in future JDK versions.
Member Function Documentation
children()
Enumeration<? extends javax.swing.tree.TreeNode> children () inherited
Returns the children of this node as an.
Enumeration
.
Returns
The children.
Referenced by Trees.copy(), and TreeFormat.hasTreeTableNode().
getColumnClass()
Class<?> getColumnClass (int column)
Returns the most specific superclass of values that can be stored in the given column.
Parameters
column The column to query.
Returns
The most specific superclass of legal values in the queried column.
Exceptions
IndexOutOfBoundsException If the given column is not a valid column index.
getColumnCount()
int getColumnCount ()
Returns the number of columns supported by this.
TreeTableNode
.
Returns
The number of columns this node supports.
Referenced by TreeFormat.format().
getUserObject()
Object getUserObject () inherited
Returns this node's user object.
Returns
the Object stored at this node by the user
getValueAt()
Object getValueAt (int column)
Gets the value for this node that corresponds to a particular tabular column.
Parameters
column The column to query.
Returns
The value for the queried column.
Exceptions
IndexOutOfBoundsException If the given column is not a valid column index.
Referenced by TreeFormat.format().
isEditable()
boolean isEditable (int column)
Determines whether the specified column is editable.
Parameters
column The column to query.
Returns
true
if the column is editable, false otherwise.
Exceptions
IndexOutOfBoundsException If the given column is not a valid column index.
setValueAt()
void setValueAt (Object value, int column)
Sets the value for the given column.
Parameters
value The value to set.
column The column to set the value on.
Exceptions
IndexOutOfBoundsException If the given column is not a valid column index.
toString()
String toString () inherited
Returns a string representation of this node suitable for a user interface.
javax.swing.JTree uses this method for formatting the text to display in the widget.
Returns
The text to display in the
JTree
for this node.
Implemented in NamedTreeNode, and DefaultMutableTreeNode.
Referenced by Trees.copy().