jena-geo: TileOpExecutor.WriteWork< A > Class Template Reference
TileOpExecutor.WriteWork< A > Class Template Reference
Worker which will write tiles.
Public Member Functions
final void run ()
Invoked by java.util.concurrent.ExecutorService#execute(Runnable) for processing all tiles.
Protected Member Functions
void executeOnCurrentTile ()
Invoked by Worker#run() for processing the tile at current indices.
Protected Attributes
final Cursor< RI, A > cursor
An iterator over the indices of the next tiles to fetch.
int tx
Indices of the tile to fetch.
final BiConsumer< A, ? super RT > processor
The process to execute on each Raster or WritableRaster.
final A accumulator
A thread-local variable which is given to each invocation of the processor.
Package Functions
static< A, R > R execute (final TileOpExecutor executor, final WritableRenderedImage target, final Collector<? super WritableRaster, A, R > collector, final Consumer< LogRecord > errorHandler)
Implementation of executeOnWritable(WritableRenderedImage, Collector, Consumer).
Static Package Functions
static ImagingOpException rethrowOrWrap (final Throwable ex)
If the given exception can be propagated as an error or unchecked exception, throws it.
Package Attributes
int ty
Private Member Functions
WriteWork (final Cursor< WritableRenderedImage, A > cursor, final Collector<? super WritableRaster, A, ?> collector)
Creates a new worker for traversing the tiles identified by the given cursor.
Detailed Description
Worker which will write tiles.
Exactly one
WriteWork
instance is created for each thread which will perform the operation on WritableRaster tiles. The same
WriteWork
instance can process an arbitrary amount of tiles.
Parameters
<A> type of the thread-local object (the accumulator) for holding intermediate results.
Constructor & Destructor Documentation
WriteWork()
WriteWork (final Cursor< WritableRenderedImage, A > cursor, final Collector<? super WritableRaster, A, ?> collector) private
Creates a new worker for traversing the tiles identified by the given cursor.
Parameters
cursor iterator over the indices of the tiles to fetch.
collector provides the process to execute on each tile.
{
             super(cursor, collector);
         }
Member Function Documentation
execute()
static<A,R> R execute (final TileOpExecutor executor, final WritableRenderedImage target, final Collector<? super WritableRaster, A, R > collector, final Consumer< LogRecord > errorHandler) package
Implementation of executeOnWritable(WritableRenderedImage, Collector, Consumer).
See the Javadoc of that method for details.
References TileOpExecutor.Worker< RI extends RenderedImage, RT extends Raster, A >.cursor, TileOpExecutor.Cursor< RI extends RenderedImage, A >.getNumWorkers(), and TileOpExecutor.Worker< WritableRenderedImage, WritableRaster, A >.run().
Referenced by TileOpExecutor.executeOnWritable().
         {
             final Cursor<WritableRenderedImage,A> cursor = executor.new Cursor<>(target, collector, false);
             final Future<?>[] workers = new Future<?>[cursor.getNumWorkers()];
             for (int i=0; i<workers.length; i++) {
                 workers[i] = CommonExecutor.instance().submit(new WriteWork<>(cursor, collector));
             }
             final WriteWork<A> worker = new WriteWork<>(cursor, collector);
             worker.run();
             return cursor.finish(workers, collector, errorHandler);
         }
executeOnCurrentTile()
void executeOnCurrentTile () protected
Invoked by Worker#run() for processing the tile at current indices.
Exceptions
RuntimeException if any error occurred during the process.
References TileOpExecutor.Worker< RI extends RenderedImage, RT extends Raster, A >.accumulator, TileOpExecutor.Worker< RI extends RenderedImage, RT extends Raster, A >.cursor, TileOpExecutor.Cursor< RI extends RenderedImage, A >.image, TileOpExecutor.Worker< RI extends RenderedImage, RT extends Raster, A >.processor, TileOpExecutor.Worker< RI extends RenderedImage, RT extends Raster, A >.tx, and TileOpExecutor.Worker< RI extends RenderedImage, RT extends Raster, A >.ty.
{
             final WritableRenderedImage image = cursor.image;
             final int tx = super.tx;                                // Protect from changes (paranoiac safety).
             final int ty = super.ty;
             final WritableRaster tile = image.getWritableTile(tx, ty);
             try {
                 processor.accept(accumulator, tile);
             } finally {
                 image.releaseWritableTile(tx, ty);
             }
         }
rethrowOrWrap()
static ImagingOpException rethrowOrWrap (final Throwable ex) static package inherited
If the given exception can be propagated as an error or unchecked exception, throws it.
Otherwise wraps it in an ImagingOpException with intentionally no error message (for allowing trimImagingWrapper(Throwable) to recognize and unwrap it).
Parameters
ex the exception to propagate if possible.
Returns
the exception to throw if the given exception can not be propagated.
{
             Throwable cause = ex.getCause();
             if (cause instanceof RuntimeException) {
                 throw (RuntimeException) cause;
             }
             if (cause instanceof Error) {
                 throw (Error) cause;
             }
             /*
              * May occur after call to `TileOpExecutor.readFrom(…)` or `TileOpExecutor.writeTo(…)`,
              * in which case that exception will be removed by `trimImagingWrapper(…)` method and
              * replaced by another exception providing a more complete error message.
              *
              * Should not happen in other contexts because the other exception handlers where this
              * `rethrowOrWrap(…)` method is invoked expect (indirectly) only unchecked exceptions.
              */
             return (ImagingOpException) new ImagingOpException(null).initCause(cause != null ? cause : ex);
         }
run()
final void run () inherited
Invoked by java.util.concurrent.ExecutorService#execute(Runnable) for processing all tiles.
This method delegates to executeOnCurrentTile() as long as there is tiles to process. Exceptions are handled (wrapped in a LogRecord or propagated).
References TileOpExecutor.Cursor< RI extends RenderedImage, A >::accumulate(), TileOpExecutor.Worker< RI extends RenderedImage, RT extends Raster, A >::executeOnCurrentTile(), TileOpExecutor.Cursor< RI extends RenderedImage, A >::next(), TileOpExecutor.Cursor< RI extends RenderedImage, A >::recordError(), and TileOpExecutor::trimImagingWrapper().
Referenced by TileOpExecutor.WriteWork< A >::execute().
{
             while (cursor.next(this)) try {
                 executeOnCurrentTile();
             } catch (Exception ex) {
                 cursor.recordError(this, trimImagingWrapper(ex));
             }
             cursor.accumulate(accumulator);
         }
Member Data Documentation
accumulator
final A accumulator protected inherited
A thread-local variable which is given to each invocation of the processor.
Processor implementation can use this instance for storing or updating information. No synchronization is needed since this instance is not shared by other threads. This value may be
null
if no such object is needed.
cursor
final Cursor<RI,A> cursor protected inherited
An iterator over the indices of the next tiles to fetch.
The same instance will be shared by all Worker instances created by the same call to ReadWork.execute(…) or WriteWork.execute(…).
processor
final BiConsumer<A, ? super RT> processor protected inherited
The process to execute on each Raster or WritableRaster.
Each invocation of that process will also receive the accumulator value, which is an instance unique to each thread.
tx
int tx protected inherited
Indices of the tile to fetch.
Those indices are updated by Cursor#next(Worker).
ty
int ty package inherited