jena-geo: HintsPending Class Reference
HintsPending Class Reference
Additional hints that are using in geotoolkit-pending.
Public Member Functions
Hints clone ()
Returns a new map of hints with the same content than this map.
String toString ()
Returns a string representation of the hints.
Static Public Member Functions
static Object getSystemDefault (final RenderingHints.Key key)
Returns the system-wide default value for the given key.
static Object putSystemDefault (final RenderingHints.Key key, final Object value)
Adds or modifies a system-wide default value.
static Object removeSystemDefault (final RenderingHints.Key key)
Removes the specified hints from the set of system default values.
Static Public Attributes
static final Key UPDATE_ID_ON_INSERT = new Key(Boolean.class)
When adding features in a datastore, it is not always necessary to have the returned id of the inserted feature.
static final Key PROPERTY_IS_IDENTIFIER = new Key(Boolean.class)
Used to identify a PropertyDescriptor if he is part of the FeatureID.
static final Key KEY_IGNORE_SMALL_FEATURES = new Key(double[].class)
This flag indicates that the featurestore can ignore features which are smaller than the given resolution.
static final ClassKey NAME_FACTORY
static final ClassKey CITATION_FACTORY
static final ClassKey CRS_AUTHORITY_FACTORY
static final ClassKey CS_AUTHORITY_FACTORY
static final ClassKey DATUM_AUTHORITY_FACTORY
static final ClassKey CRS_FACTORY
static final ClassKey CS_FACTORY
static final ClassKey DATUM_FACTORY
static final ClassKey COORDINATE_OPERATION_FACTORY
static final ClassKey COORDINATE_OPERATION_AUTHORITY_FACTORY
static final ClassKey MATH_TRANSFORM_FACTORY
static final Key DEFAULT_COORDINATE_REFERENCE_SYSTEM
static final FileKey CRS_AUTHORITY_EXTRA_DIRECTORY = new FileKey(false)
static final Key EPSG_DATA_SOURCE = new DataSourceKey()
static final OptionKey DATUM_SHIFT_METHOD
static final Key LENIENT_DATUM_SHIFT = new Key(Boolean.class)
static final Key FORCE_LONGITUDE_FIRST_AXIS_ORDER = new Key(Boolean.class)
static final Key FORCE_AXIS_ORDER_HONORING = new Key(String.class)
static final Key FORCE_STANDARD_AXIS_DIRECTIONS = new Key(Boolean.class)
static final Key FORCE_STANDARD_AXIS_UNITS = new Key(Boolean.class)
static final Key VERSION = new Key("org.apache.sis.util.Version")
static final Key JAI_INSTANCE = new Key("javax.media.jai.JAI")
The javax.media.jai.JAI instance to use.
static final Key TILE_ENCODING = new Key(String.class)
static final Key COVERAGE_PROCESSING_VIEW = new Key("org.geotoolkit.coverage.grid.ViewType")
static final Key SAMPLE_DIMENSION_TYPE = new Key("org.geotoolkit.coverage.SampleDimensionType")
static final ClassKey TEMPORAL_FACTORY = new ClassKey("org.opengis.temporal.TemporalFactory")
static final ClassKey POSITION_FACTORY = new ClassKey("org.opengis.geometry.PositionFactory")
static final ClassKey PRIMITIVE_FACTORY = new ClassKey("org.opengis.geometry.primitive.PrimitiveFactory")
static final ClassKey GEOMETRY_FACTORY = new ClassKey("org.opengis.geometry.coordinate.GeometryFactory")
static final ClassKey COMPLEX_FACTORY = new ClassKey("org.opengis.geometry.complex.ComplexFactory")
static final ClassKey AGGREGATE_FACTORY = new ClassKey("org.opengis.geometry.aggregate.AggregateFactory")
static final ClassKey FEATURE_TYPE_FACTORY = new ClassKey("org.geotoolkit.feature.type.FeatureTypeFactory")
static final ClassKey FEATURE_FACTORY = new ClassKey("org.geotoolkit.feature.FeatureFactory")
static final ClassKey FILTER_FACTORY = new ClassKey("org.opengis.filter.FilterFactory")
static final ClassKey STYLE_FACTORY = new ClassKey("org.opengis.style.StyleFactory")
Static Package Functions
static String nameOf (final RenderingHints.Key key)
Tries to find the name of the given key, using reflection.
static Field fieldOf (final RenderingHints.Key key)
Tries to find the field of the given key, using reflection.
Private Member Functions
HintsPending ()
Detailed Description
Additional hints that are using in geotoolkit-pending.
Since
2.1
Version
$Id$
Author
Martin Desruisseaux
Jody Garnett
Constructor & Destructor Documentation
HintsPending()
HintsPending () private
 {}
Member Function Documentation
clone()
Hints clone () inherited
Returns a new map of hints with the same content than this map.
Since
2.5
References Hints.clone().
Referenced by Hints.clone(), ReferencingFactoryContainer.getCurrentHints(), and ReferencingFactoryContainer.ReferencingFactoryContainer().
{
         return (Hints) super.clone();
     }
fieldOf()
static Field fieldOf (final RenderingHints.Key key) static package inherited
Tries to find the field of the given key, using reflection.
This method searches for a constant declared in the enclosing class, which is typically one of:
org.geotoolkit.factory.Hints
(this class)
javax.media.jai.JAI
(assuming JAI is on the classpath)
java.awt.RenderingHints
(actually sun.awt.SunHints at least on Sun JDK)
Parameters
key The key for which a field is wanted, or
null
.
Returns
The key field as declared in the static constants.
References Hints.getEnclosingClass().
Referenced by Hints.nameOf(), and SerializedKey.SerializedKey().
{
         Field field = null;
         if (key != null) {
             Class<?> c = getEnclosingClass(key);
             if (c == null || (field = fieldOf(c, key)) == null) {
                 if (key instanceof Key && c != (c = ((Key) key).getValueClass())) {
                     field = fieldOf(c, key);
                 }
             }
         }
         return field;
     }
getSystemDefault()
static Object getSystemDefault (final RenderingHints.Key key) static inherited
Returns the system-wide default value for the given key.
The Geotk library initially contains no system default, so
getSystemDefault(key)
returns null for all keys. Users can add default values using putSystemDefault.
To get a map of all system defaults, use
new Hints()
.
Parameters
key The hints key.
Returns
The system-wide default value for the given key, or
null
if the key did not have a mapping.
Since
2.4
{
         return GLOBAL.get(key);
     }
nameOf()
static String nameOf (final RenderingHints.Key key) static package inherited
Tries to find the name of the given key, using reflection.
Parameters
key The key for which a name is wanted, or
null
.
Returns
The key name as declared in the static constants.
References Hints.fieldOf().
Referenced by Hints.format(), Hints.putSystemDefault(), and Hints.Key.toString().
{
         if (key == null) {
             return null;
         }
         if (!(key instanceof Key)) {
             final Field field = fieldOf(key);
             if (field != null) {
                 return field.getName();
             }
         }
         return key.toString();
     }
putSystemDefault()
static Object putSystemDefault (final RenderingHints.Key key, final Object value) static inherited
Adds or modifies a system-wide default value.
Hints
instances created after this method call will be initialized to the union of all values specified with
putSystemDefault
and not yet removeSystemDefault removed}.
If the given value is different than the previous one, then this method notifies every listeners registered with Factories#addChangeListener(ChangeListener).
Parameters
key The hint key.
value The hint value to be used as the system-wide default for the given key.
Returns
The previous value for the given key, or
null
if none.
Exceptions
IllegalArgumentException if Hints.Key#isCompatibleValue(Object) returns
false
for the given value.
Since
2.4
References Factories.fireConfigurationChanged(), Errors.format(), Errors.Keys.IllegalArgument_2, and Hints.nameOf().
{
         if (!key.isCompatibleValue(value)) {
             throw new IllegalArgumentException(Errors.format(
                     Errors.Keys.IllegalArgument_2, nameOf(key), value));
         }
         final Object old = GLOBAL.put(key, value);
         if (!Objects.equals(value, old)) {
             Factories.fireConfigurationChanged(Hints.class);
         }
         return old;
     }
removeSystemDefault()
static Object removeSystemDefault (final RenderingHints.Key key) static inherited
Removes the specified hints from the set of system default values.
If the a value was present for the given key, then this method notifies every listeners registered with Factories#addChangeListener(ChangeListener).
Parameters
key The hints key that needs to be removed.
Returns
The value to which the key had previously been mapped, or
null
if the key did not have a mapping.
Since
2.4
References Factories.fireConfigurationChanged().
{
         final Object old = GLOBAL.remove(key);
         if (old != null) {
             Factories.fireConfigurationChanged(Hints.class);
         }
         return old;
     }
toString()
String toString () inherited
Returns a string representation of the hints.
The default implementation formats the set of hints as a tree.
Since
2.4
{
         return toString(this);
     }
Member Data Documentation
AGGREGATE_FACTORY
final ClassKey AGGREGATE_FACTORY = new ClassKey("org.opengis.geometry.aggregate.AggregateFactory") static inherited
CITATION_FACTORY
final ClassKey CITATION_FACTORY static inherited
Initial value:
= new ClassKey(
            "org.opengis.metadata.citation.CitationFactory")
COMPLEX_FACTORY
final ClassKey COMPLEX_FACTORY = new ClassKey("org.opengis.geometry.complex.ComplexFactory") static inherited
COORDINATE_OPERATION_AUTHORITY_FACTORY
final ClassKey COORDINATE_OPERATION_AUTHORITY_FACTORY static inherited
Initial value:
= new ClassKey(
            "org.opengis.referencing.operation.CoordinateOperationAuthorityFactory")
Referenced by Factories.getCoordinateOperationAuthorityFactory().
COORDINATE_OPERATION_FACTORY
final ClassKey COORDINATE_OPERATION_FACTORY static inherited
Initial value:
= new ClassKey(
            "org.opengis.referencing.operation.CoordinateOperationFactory")
COVERAGE_PROCESSING_VIEW
final Key COVERAGE_PROCESSING_VIEW = new Key("org.geotoolkit.coverage.grid.ViewType") static inherited
CRS_AUTHORITY_EXTRA_DIRECTORY
final FileKey CRS_AUTHORITY_EXTRA_DIRECTORY = new FileKey(false) static inherited
Referenced by PropertyEpsgFactory.PropertyEpsgFactory().
CRS_AUTHORITY_FACTORY
final ClassKey CRS_AUTHORITY_FACTORY static inherited
Initial value:
= new ClassKey(
            "org.opengis.referencing.crs.CRSAuthorityFactory")
Referenced by Factories.getCRSAuthorityFactory().
CRS_FACTORY
final ClassKey CRS_FACTORY static inherited
Initial value:
= new ClassKey(
            "org.opengis.referencing.crs.CRSFactory")
Referenced by ReferencingFactoryContainer.ReferencingFactoryContainer().
CS_AUTHORITY_FACTORY
final ClassKey CS_AUTHORITY_FACTORY static inherited
Initial value:
= new ClassKey(
            "org.opengis.referencing.cs.CSAuthorityFactory")
CS_FACTORY
final ClassKey CS_FACTORY static inherited
Initial value:
= new ClassKey(
            "org.opengis.referencing.cs.CSFactory")
Referenced by ReferencingFactoryContainer.ReferencingFactoryContainer().
DATUM_AUTHORITY_FACTORY
final ClassKey DATUM_AUTHORITY_FACTORY static inherited
Initial value:
= new ClassKey(
            "org.opengis.referencing.datum.DatumAuthorityFactory")
DATUM_FACTORY
final ClassKey DATUM_FACTORY static inherited
Initial value:
= new ClassKey(
            "org.opengis.referencing.datum.DatumFactory")
Referenced by ReferencingFactoryContainer.ReferencingFactoryContainer().
DATUM_SHIFT_METHOD
final OptionKey DATUM_SHIFT_METHOD static inherited
Initial value:
= new OptionKey(
            "Molodensky", "Abridged Molodensky",
            "Molodenski", "Abridged_Molodenski",
            "Geocentric", "*")
DEFAULT_COORDINATE_REFERENCE_SYSTEM
final Key DEFAULT_COORDINATE_REFERENCE_SYSTEM static inherited
Initial value:
= new Key(
            "org.opengis.referencing.crs.CoordinateReferenceSystem")
EPSG_DATA_SOURCE
final Key EPSG_DATA_SOURCE = new DataSourceKey() static inherited
FEATURE_FACTORY
final ClassKey FEATURE_FACTORY = new ClassKey("org.geotoolkit.feature.FeatureFactory") static inherited
FEATURE_TYPE_FACTORY
final ClassKey FEATURE_TYPE_FACTORY = new ClassKey("org.geotoolkit.feature.type.FeatureTypeFactory") static inherited
FILTER_FACTORY
final ClassKey FILTER_FACTORY = new ClassKey("org.opengis.filter.FilterFactory") static inherited
FORCE_AXIS_ORDER_HONORING
final Key FORCE_AXIS_ORDER_HONORING = new Key(String.class) static inherited
FORCE_LONGITUDE_FIRST_AXIS_ORDER
final Key FORCE_LONGITUDE_FIRST_AXIS_ORDER = new Key(Boolean.class) static inherited
FORCE_STANDARD_AXIS_DIRECTIONS
final Key FORCE_STANDARD_AXIS_DIRECTIONS = new Key(Boolean.class) static inherited
FORCE_STANDARD_AXIS_UNITS
final Key FORCE_STANDARD_AXIS_UNITS = new Key(Boolean.class) static inherited
GEOMETRY_FACTORY
final ClassKey GEOMETRY_FACTORY = new ClassKey("org.opengis.geometry.coordinate.GeometryFactory") static inherited
JAI_INSTANCE
final Key JAI_INSTANCE = new Key("javax.media.jai.JAI") static inherited
The javax.media.jai.JAI instance to use.
KEY_IGNORE_SMALL_FEATURES
final Key KEY_IGNORE_SMALL_FEATURES = new Key(double[].class) static
This flag indicates that the featurestore can ignore features which are smaller than the given resolution.
FeatureStore are supposed to try to conform to this request only if it doesnt requiere to much work. For exemple when exploring a quad tree, tiles can be ignored when there bbox is to small or when the feature bbox can be read before.
Default value is null.
LENIENT_DATUM_SHIFT
final Key LENIENT_DATUM_SHIFT = new Key(Boolean.class) static inherited
MATH_TRANSFORM_FACTORY
final ClassKey MATH_TRANSFORM_FACTORY static inherited
Initial value:
= new ClassKey(
            "org.opengis.referencing.operation.MathTransformFactory")
Referenced by ReferencingFactoryContainer.declaredFactoryHints(), and ReferencingFactoryContainer.ReferencingFactoryContainer().
NAME_FACTORY
final ClassKey NAME_FACTORY static inherited
Initial value:
= new ClassKey(
            "org.opengis.util.NameFactory")
POSITION_FACTORY
final ClassKey POSITION_FACTORY = new ClassKey("org.opengis.geometry.PositionFactory") static inherited
PRIMITIVE_FACTORY
final ClassKey PRIMITIVE_FACTORY = new ClassKey("org.opengis.geometry.primitive.PrimitiveFactory") static inherited
PROPERTY_IS_IDENTIFIER
final Key PROPERTY_IS_IDENTIFIER = new Key(Boolean.class) static
Used to identify a PropertyDescriptor if he is part of the FeatureID.
SAMPLE_DIMENSION_TYPE
final Key SAMPLE_DIMENSION_TYPE = new Key("org.geotoolkit.coverage.SampleDimensionType") static inherited
STYLE_FACTORY
final ClassKey STYLE_FACTORY = new ClassKey("org.opengis.style.StyleFactory") static inherited
TEMPORAL_FACTORY
final ClassKey TEMPORAL_FACTORY = new ClassKey("org.opengis.temporal.TemporalFactory") static inherited
TILE_ENCODING
final Key TILE_ENCODING = new Key(String.class) static inherited
UPDATE_ID_ON_INSERT
final Key UPDATE_ID_ON_INSERT = new Key(Boolean.class) static
When adding features in a datastore, it is not always necessary to have the returned id of the inserted feature.
JDBC featurestore for exemple are much more efficient when inserting datas in batch mode. setting this value to false may bring a huge performance gain.
Default value is true.
VERSION
final Key VERSION = new Key("org.apache.sis.util.Version") static inherited