jena-geo: BiCubicInterpolation1 Class Reference
BiCubicInterpolation1 Class Reference
Define a standard biCubic interpolation.
Public Member Functions
BiCubicInterpolation1 (PixelIterator pixelIterator, ResampleBorderComportement rbc, double[] fillValue)
.
BiCubicInterpolation1 (PixelIterator pixelIterator)
.
double [] getMinMaxValue (Rectangle area)
.
double interpolate (double x, double y, int b)
Returns interpolate value from x, y pixel coordinates and band index.
double [] interpolate (double x, double y)
Return interpolate value from x, y pixel coordinate.
int getNumBands ()
Return number of bands from object that iterate.
Static Public Member Functions
static Interpolation create (PixelIterator pixelIterator, InterpolationCase interpolationCase, int lanczosWindow)
static Interpolation create (PixelIterator pixelIterator, InterpolationCase interpolationCase, int lanczosWindow, ResampleBorderComportement rbc, double[] fillValue)
Protected Member Functions
double interpolate1D (double t0, double t, double... f)
double checkValue (double value)
boolean checkInterpolate (double x, double y)
Verify coordinates are within iterate area boundary.
void setInterpolateMin (double x, double y)
Return appropriate interpolation minX and minY coordinates from x, y interpolate coordinates.
Protected Attributes
final PixelIterator pixelIterator
Current.
final int numBands
Number of bands from object that iterate.
final Rectangle boundary
Boundary from object that iterate.
Rectangle precMinMax
last search of min max value area.
double [] minMax
final double [] data
Table to keep all pixels values used to interpolate.
int minX
Lower corner X coordinates from interpolation area.
int minY
Lower corner Y coordinates from interpolation area.
final int windowSide
Side of area interpolation.
final double [] result
Interpolation results table.
final double [] fillValue
Contains value use when pixel transformation is out of source image boundary.
final ResampleBorderComportement borderChoice
Define comportement of the destination image border.
final double bminX
Define boundary which accept extrapolation.
final int boundMinX
Define boundary which don't accept extrapolation.
Package Functions
Rectangle getBoundary ()
Returns.
Package Attributes
final double bminY
final double bmaxX
final double bmaxY
final int boundMinY
final int boundMaxX
final int boundMaxY
Detailed Description
Define a standard biCubic interpolation.
Author
Rémi Marechal (Geomatys).
Constructor & Destructor Documentation
BiCubicInterpolation1() [1/2]
BiCubicInterpolation1 (PixelIterator pixelIterator, ResampleBorderComportement rbc, double [] fillValue)
.
{
         super(pixelIterator, rbc, fillValue);
     }
BiCubicInterpolation1() [2/2]
BiCubicInterpolation1 (PixelIterator pixelIterator)
.
{
         super(pixelIterator);
     }
Member Function Documentation
checkInterpolate()
boolean checkInterpolate (double x, double y) protected inherited
Verify coordinates are within iterate area boundary.
Parameters
x pixel x coordinate.
y pixel y coordinate.
Returns
true
if value should be interpolate at the given coordinates else
false
.
Exceptions
IllegalArgumentException if pixel coordinates are out of iterate area boundary.
References ResampleBorderComportement.EXTRAPOLATION.
Referenced by Resample.fillImageByAffineTransform(), Resample.fillImageByGrid(), Resample.fillImageByTransform(), and Resample.fillImagePx().
{
         //-- accept extrapolation
         if (borderChoice.equals(ResampleBorderComportement.EXTRAPOLATION)) return true;
         if (x < bminX || x > bmaxX || y < bminY || y > bmaxY) return false; //-- no interpolation available
 //        if (borderChoice.equals(ResampleBorderComportement.EXTRAPOLATION)) return true;
         return (!(x < boundMinX || x > boundMaxX
                || y < boundMinY || y > boundMaxY));
     }
checkValue()
double checkValue (double value) protected inherited
Verify value is in [minValue; maxValue] interval.
If value < minValue value = minValue. If value > maxValue value = maxValue.
Parameters
value double which will be verify.
Returns
References BiCubicInterpolation.maxValue, and BiCubicInterpolation.minValue.
Referenced by BiCubicInterpolation1.interpolate1D(), and BiCubicInterpolation2.interpolate1D().
{
         if (value < minValue) {
             value = minValue;
         } else if (value > maxValue) {
             value = maxValue;
         }
         return value;
     }
create() [1/2]
static Interpolation create (PixelIterator pixelIterator, InterpolationCase interpolationCase, int lanczosWindow) static inherited
Return Interpolation object.
Note : if lanczos interpolation doesn't choose lanczosWindow parameter has no impact.
Parameters
pixelIterator Iterator which iterate to compute interpolation.
interpolationCase case of interpolation.
lanczosWindow only use about Lanczos interpolation.
Returns
interpolation asked by caller.
See also
LanczosInterpolation::LanczosInterpolation(org.geotoolkit.image.iterator.PixelIterator, int)
References ResampleBorderComportement.FILL_VALUE.
Referenced by Resample.Resample().
{
         return create(pixelIterator, interpolationCase, lanczosWindow, ResampleBorderComportement.FILL_VALUE, null);
     }
create() [2/2]
static Interpolation create (PixelIterator pixelIterator, InterpolationCase interpolationCase, int lanczosWindow, ResampleBorderComportement rbc, double [] fillValue) static inherited
Return Interpolation object.
Note : if lanczos interpolation doesn't choose lanczosWindow parameter has no impact.
Parameters
pixelIterator Iterator which iterate to compute interpolation.
interpolationCase case of interpolation.
lanczosWindow only use about Lanczos interpolation.
rbc comportement of the destination image border.
fillValue contains value use when pixel transformation is out of source image boundary.
Returns
interpolation asked by caller.
See also
LanczosInterpolation::LanczosInterpolation(org.geotoolkit.image.iterator.PixelIterator, int)
{
         switch (interpolationCase) {
             case NEIGHBOR : return new NeighborInterpolation(pixelIterator, fillValue);
             case BILINEAR : return new BilinearInterpolation(pixelIterator, rbc, fillValue);
             case BICUBIC  : return new BiCubicInterpolation1(pixelIterator, rbc, fillValue);
             case BICUBIC2 : return new BiCubicInterpolation2(pixelIterator, rbc, fillValue);
             case LANCZOS  : return new LanczosInterpolation(pixelIterator, lanczosWindow, rbc, fillValue);
             default       : throw  new IllegalArgumentException("interpolation not supported yet");
         }
     }
getBoundary()
Rectangle getBoundary () package inherited
Returns.
Rectangle
which is Image or Raster boundary within this Interpolator.
Returns
Rectangle
which is Image or Raster boundary within this Interpolator.
See also
Resample::getSourcePixelValue(double, double)
References Interpolation.boundary.
Referenced by Interpolation.getMinMaxValue(), Interpolation.Interpolation(), and Resample.Resample().
{
         return boundary;
     }
getMinMaxValue()
double [] getMinMaxValue (Rectangle area) inherited
.
{
         throw new UnsupportedOperationException("Not supported yet.");
     }
getNumBands()
int getNumBands () inherited
Return number of bands from object that iterate.
Returns
number of bands from object that iterate.
See also
Resample::getSourcePixelValue(double, double)
References Interpolation.numBands.
Referenced by SeparableInterpolation.interpolate(), Interpolation.Interpolation(), and Resample.Resample().
{
         return numBands;
     }
interpolate() [1/2]
double interpolate (double x, double y, int b) inherited
Returns interpolate value from x, y pixel coordinates and band index.
Parameters
x pixel x coordinate.
y pixel y coordinate.
b band index.
Returns
interpolate value from x, y pixel coordinates and band index.
References SeparableInterpolation.fillRow(), Interpolation.getNumBands(), SeparableInterpolation.interpolate1D(), Interpolation.minX, Interpolation.minY, Interpolation.setInterpolateMin(), and Interpolation.windowSide.
{
         ArgumentChecks.ensureBetween("band index", 0, getNumBands(), b);
         setInterpolateMin(x, y);
         for (int dy = 0; dy < windowSide; dy++) {
             fillRow(dy, b);
             cols[dy] = interpolate1D(minX, x, rows);
         }
         return interpolate1D(minY, y, cols);
     }
interpolate() [2/2]
double [] interpolate (double x, double y) inherited
Return interpolate value from x, y pixel coordinate.
Parameters
x pixel x coordinate.
y pixel y coordinate.
Returns
interpolate value from x, y pixel coordinate.
References SeparableInterpolation.fillRow(), SeparableInterpolation.interpolate1D(), Interpolation.minX, Interpolation.minY, Interpolation.numBands, Interpolation.result, Interpolation.setInterpolateMin(), and Interpolation.windowSide.
{
 //        if (!checkInterpolate(x, y)) return fillValue;
         setInterpolateMin(x, y);
         for (int b = 0; b < numBands; b++) {
             for (int dy = 0; dy < windowSide; dy++) {
                 fillRow(dy, b);
                 cols[dy] = interpolate1D(minX, x, rows);
             }
             result[b] = interpolate1D(minY, y, cols);
         }
         return result;
     }
interpolate1D()
double interpolate1D (double t0, double t, double... f) protected
Cubic interpolation from 4 values.
With always t0 &lt= t&lt= t0 + 3
For example : cubic interpolation between 4 pixels.
t = 0 1 2 3
f(t) = |f0|f1|f2|f3|
In this example t0 = 0.
Another example :
t = -5 -4 -3 -2
f(t) = |f0|f1|f2|f3|
In this example parameter t0 = -5.
Parameters
t0 f(t0) = f[0].Current position from first pixel interpolation.
t position of interpolation.
f pixel values from t = {0, 1, 2, 3}.
Returns
cubic interpolation at t position.
References BiCubicInterpolation.checkValue().
{
         assert (f.length == 4) : "impossible to interpolate with less or more than 4 values";
         final double a1 =  f[3]/3 - 3*f[2]/2 + 3*f[1]   - 11*f[0]/6;
         final double a2 = -f[3]/2 + 2*f[2]   - 5*f[1]/2 + f[0];
         final double a3 =  f[3]/6 - f[2]/2   + f[1]/2   - f[0]/6;
         final double x  = t-t0;
         return checkValue(f[0] + (a1 + (a2 + a3*x)*x)*x);
     }
setInterpolateMin()
void setInterpolateMin (double x, double y) protected inherited
Return appropriate interpolation minX and minY coordinates from x, y interpolate coordinates.
MinX and minY represent lower corner coordinates from interpolation area.
Parameters
x pixel x coordinate.
y pixel y coordinate.
Exceptions
IllegalArgumentException if there are necessary pixels out of boundary.
Referenced by SeparableInterpolation.interpolate(), and LanczosInterpolation.interpolate().
{
         final int boundW = boundary.width;
         final int boundH = boundary.height;
         final int bx     = boundary.x;
         final int by     = boundary.y;
         minX  = (int) x;
         minY  = (int) y;
         //-- Adjust truncation.
         if (x < minX) minX--;
         if (y < minY) minY--;
         //-- Adjust area interpolation on x, y center.
         minX -= (windowSide >>> 1) - 1;
         minY -= (windowSide >>> 1) - 1;
         //-- Adjust area from lower corner.
         minX = Math.max(minX, bx);
         minY = Math.max(minY, by);
         //-- Adjust area from upper corner.
         final int maxDiffX = minX + windowSide - (bx + boundW);
         final int maxDiffY = minY + windowSide - (by + boundH);
         if (maxDiffX > 0) minX -= maxDiffX;
         if (maxDiffY > 0) minY -= maxDiffY;
     }
Member Data Documentation
bmaxX
final double bmaxX package inherited
Referenced by NeighborInterpolation.checkInterpolate().
bmaxY
final double bmaxY package inherited
Referenced by NeighborInterpolation.checkInterpolate().
bminX
final double bminX protected inherited
Define boundary which accept extrapolation.
bminY
final double bminY package inherited
borderChoice
final ResampleBorderComportement borderChoice protected inherited
Define comportement of the destination image border.
Referenced by Interpolation.Interpolation().
boundary
final Rectangle boundary protected inherited
Boundary from object that iterate.
Referenced by BiCubicInterpolation.BiCubicInterpolation(), Interpolation.getBoundary(), and LanczosInterpolation.LanczosInterpolation().
boundMaxX
final int boundMaxX package inherited
boundMaxY
final int boundMaxY package inherited
boundMinX
final int boundMinX protected inherited
Define boundary which don't accept extrapolation.
boundMinY
final int boundMinY package inherited
data
final double [] data protected inherited
Table to keep all pixels values used to interpolate.
fillValue
final double [] fillValue protected inherited
Contains value use when pixel transformation is out of source image boundary.
Referenced by Interpolation.Interpolation().
minMax
double [] minMax protected inherited
Double table which contain minimum and maximum value, and x, y associate coordinates for each image band.
Referenced by Interpolation.getMinMaxValue(), Interpolation.Interpolation(), and Rescaler.Rescaler().
minX
int minX protected inherited
Lower corner X coordinates from interpolation area.
Referenced by SeparableInterpolation.fillRow(), SeparableInterpolation.interpolate(), and LanczosInterpolation.interpolate().
minY
int minY protected inherited
Lower corner Y coordinates from interpolation area.
Referenced by SeparableInterpolation.fillRow(), SeparableInterpolation.interpolate(), and LanczosInterpolation.interpolate().
numBands
final int numBands protected inherited
Number of bands from object that iterate.
Referenced by Interpolation.getMinMaxValue(), Interpolation.getNumBands(), SeparableInterpolation.interpolate(), Interpolation.Interpolation(), and Rescaler.Rescaler().
pixelIterator
final PixelIterator pixelIterator protected inherited
Current.
PixelIterator
which is interpolate.
Referenced by BiCubicInterpolation.BiCubicInterpolation(), BilinearInterpolation.BilinearInterpolation(), SeparableInterpolation.fillRow(), NeighborInterpolation.interpolate(), LanczosInterpolation.interpolate(), Interpolation.Interpolation(), and LanczosInterpolation.LanczosInterpolation().
precMinMax
Rectangle precMinMax protected inherited
last search of min max value area.
result
final double [] result protected inherited
Interpolation results table.
Referenced by NeighborInterpolation.interpolate(), and SeparableInterpolation.interpolate().
windowSide
final int windowSide protected inherited
Side of area interpolation.
Referenced by SeparableInterpolation.fillRow(), SeparableInterpolation.interpolate(), LanczosInterpolation.interpolate(), Interpolation.Interpolation(), and SeparableInterpolation.SeparableInterpolation().