jena-geo: ImageUtils Class Reference
ImageUtils Class Reference
Aggregate some methods to create BufferedImage or WritableLargeRenderedImage more easily.
Classes
class ComponentScaledColorModel
Static Public Member Functions
static BufferedImage createPaletteImage (final int width, final int height, final SampleType type, final int numband, final int[] java2DColorMap)
Returns a BufferedImage with an internaly palette ColorSpace, created from given parameters.
static BufferedImage createARGBInterleavedImage (final int width, final int height, final SampleType type, final boolean isAlphaPremultiplied)
Returns a BufferedImage of 4 bandswith an internaly AlphaRGB ColorSpace and created from given parameters.
static BufferedImage createRGBInterleavedImage (final int width, final int height, final SampleType type)
Returns a BufferedImage of 3 bands, with an internaly RGB ColorSpace and created from given parameters.
static BufferedImage createARGBBandedImage (final int width, final int height, final SampleType type, final boolean isAlphaPremultiplied)
Returns a BufferedImage of 4 bands, with an internaly AlphaRGB ColorSpace and created from given parameters.
static BufferedImage createRGBBandedImage (final int width, final int height, final SampleType type)
Returns a BufferedImage of 3 bands with an internaly RGB ColorSpace, created from given parameters.
static BufferedImage createGreyScaledBandedImage (final int width, final int height, final SampleType type, final int numBand)
Returns a BufferedImage with an internaly gray scaled ColorSpace, created from given parameters.
static BufferedImage createGreyScaledInterleavedImage (final int width, final int height, final SampleType type, final int numBand)
Returns a BufferedImage with an internaly gray scaled ColorSpace, created from given parameters.
static WritableLargeRenderedImage createPaletteLargeImage (final int width, final int height, final SampleType type, final int numBand, final int[] java2DColorMap)
Returns a WritableLargeRenderedImage with an internaly palette ColorSpace, created from given parameters.
static WritableLargeRenderedImage createARGBLargeImage (final int width, final int height, final SampleType type, final boolean isAlphaPremultiplied)
Returns a WritableLargeRenderedImage with an internaly AlphaRGB ColorSpace and 4 bands, created from given parameters.
static WritableLargeRenderedImage createRGBLargeImage (final int width, final int height, final SampleType type)
Returns a WritableLargeRenderedImage of 3 bands with an internaly RGB ColorSpace, created from given parameters.
static WritableLargeRenderedImage createGreyScaledLargeImage (final int width, final int height, final SampleType type, final int numBand)
Returns a WritableLargeRenderedImage with an internaly gray scaled ColorSpace, created from given parameters.
static WritableLargeRenderedImage createLargeImage (final int width, final int height, final SampleType type, final int numBand, final PhotometricInterpretation pI, final boolean hasAlpha, final boolean isAlphaPremultiplied, final int[] java2DColorMap)
Returns a WritableLargeRenderedImage created from given parameters.
static WritableLargeRenderedImage createLargeImage (final int minx, final int miny, final int width, final int height, final Dimension tileSize, final SampleType type, final int numBand, final int tilegridXOffset, final int tilegridYOffset, final PhotometricInterpretation pI, final boolean hasAlpha, final boolean isAlphaPremultiplied, final int[] java2DColorMap)
Returns a WritableLargeRenderedImage created from given parameters.
static BufferedImage createImage (final int width, final int height, final SampleType type, final int numBand, final PhotometricInterpretation pI, final PlanarConfiguration pC, final boolean hasAlpha, final boolean isAlphaPremultiplied, final int[] java2DColorMap)
Returns a BufferedImage created from given parameters.
static ImageTypeSpecifier buildImageTypeSpecifier (final SampleType type, final int numBand, final PhotometricInterpretation pI, final PlanarConfiguration pC, final boolean hasAlpha, final boolean isAlphaPremultiplied, final int[] java2DColorMap) throws UnsupportedOperationException
Returns an appropriate ImageTypeSpecifier built from given parameters.
static ColorModel createColorModel (final SampleType type, final int numBand, final PhotometricInterpretation pI, final boolean hasAlpha, final boolean isAlphaPremultiplied, final int[] java2DColorMap)
Returns ColorModel create from given parameters.
static short getPhotometricInterpretation (final ColorModel cm)
Define photometric interpretation tiff tag in function of ColorModel properties.
static PhotometricInterpretation getEnumPhotometricInterpretation (final ColorModel cm)
Define photometric interpretation tiff tag in function of ColorModel properties.
static short getPlanarConfiguration (final SampleModel sm)
Define appropriate tiff tag value for planar configuration from SampleModel properties.
static PlanarConfiguration getEnumPlanarConfiguration (final SampleModel sm)
Define appropriate PlanarConfiguration enum from its integer planarConfiguration into tiff specification.
static int getSampleFormat (final SampleModel sm)
Define appropriate tiff tag value for planar configuration from SampleModel properties.
static ImageTypeSpecifier buildImageTypeSpecifier (final int sampleBitsSize, final int numBand, final short photometricInterpretation, final short sampleFormat, final short planarConfiguration, final boolean hasAlpha, final boolean isAlphaPremultiplied, final int[] java2DColorMap) throws UnsupportedOperationException
Return an appropriate ImageTypeSpecifier built from given parameter.
static SampleModel createSampleModel (final PlanarConfiguration planarConfiguration, final SampleType sampleType, final int width, final int height, final int numBand) throws UnsupportedOperationException
Create and returns appropriate SampleModel built from given parameters.
static ColorModel createColorModel (final int sampleBitsSize, final int numBand, final short photometricInterpretation, final short sampleFormat, final boolean hasAlpha, final boolean isAlphaPremultiplied, final int[] java2DColorMap) throws UnsupportedOperationException
Create and returns an adapted ColorModel from given parameters.
static ColorModel createColorModel (final int sampleBitsSize, final int numBand, final short photometricInterpretation, final short sampleFormat, final Double minSampleValue, final Double maxSampleValue, final boolean hasAlpha, final boolean isAlphaPreMultiplied, int[] java2DColorMap) throws UnsupportedOperationException
Create and returns an adapted ColorModel from given parameters.
Static Private Attributes
static final short SAMPLEFORMAT_IEEEFP = 3
Define buffer type as IEEE floating point data.
static final short SAMPLEFORMAT_INT = 2
Define buffer type as signed integer point data.
static final short SAMPLEFORMAT_UINT = 1
Define buffer type as unsigned integer point data.
static final short PHOTOMETRIC_MINISBLACK = 1
Define image properties for bilevel and grayscale images: 0 is imaged as black.
static final short PHOTOMETRIC_RGB = 2
Define image properties for RGB image.
static final short PHOTOMETRIC_PALETTE = 3
Define image with Palette color.
static final short PLANAR_INTERLEAVED = 1
Integer that define planar configuration as interleaved.
static final short PLANAR_BANDED = 2
Integer that define planar configuration as banded.
Detailed Description
Aggregate some methods to create BufferedImage or WritableLargeRenderedImage more easily.
Author
Remi Marechal (Geomatys).
See also
PhotometricInterpretation
PlanarConfiguration
SampleType
WritableLargeRenderedImage
Member Function Documentation
buildImageTypeSpecifier() [1/2]
static ImageTypeSpecifier buildImageTypeSpecifier (final SampleType type, final int numBand, final PhotometricInterpretation pI, final PlanarConfiguration pC, final boolean hasAlpha, final boolean isAlphaPremultiplied, final int [] java2DColorMap) throws UnsupportedOperationException static
Returns an appropriate ImageTypeSpecifier built from given parameters.
Parameters
type type of internal data.
numBand band number.
pI define type of ColorModel, for example RGB, palette etc.
pC define type of internal SampleModel, banded or interleaved.
hasAlpha
isAlphaPremultiplied
java2DColorMap array which define map when PhotometricInterpretation is type palette, or should be
null
.
Returns
ImageTypeSpecifier built from given parameters.
Exceptions
UnsupportedOperationException if problem during internal ColorModel creation.
IllegalArgumentException if colorMap argument is
null
when PhotometricInterpretation is type palette.
See also
SampleType
PhotometricInterpretation
PlanarConfiguration
References PlanarConfiguration.BANDED, ImageUtils.PHOTOMETRIC_MINISBLACK, ImageUtils.PHOTOMETRIC_PALETTE, ImageUtils.PHOTOMETRIC_RGB, ImageUtils.SAMPLEFORMAT_IEEEFP, ImageUtils.SAMPLEFORMAT_INT, and ImageUtils.SAMPLEFORMAT_UINT.
Referenced by ImageUtils.createImage().
{
         final int sampleBitSize;
         final short sampleFormat;
         switch (type) {
             case BYTE : {
                 sampleBitSize = java.lang.Byte.SIZE;
                 sampleFormat  = SAMPLEFORMAT_UINT;
                 break;
             }
             case  SHORT : {
                 sampleBitSize = java.lang.Short.SIZE;
                 sampleFormat  = SAMPLEFORMAT_INT;
                 break;
             }
             case USHORT : {
                 sampleBitSize = java.lang.Short.SIZE;
                 sampleFormat  = SAMPLEFORMAT_UINT;
                 break;
             }
             case INTEGER : {
                 sampleBitSize = java.lang.Integer.SIZE;
                 sampleFormat  = SAMPLEFORMAT_UINT;
                 break;
             }
             case FLOAT  : {
                 sampleBitSize = java.lang.Float.SIZE;
                 sampleFormat  = SAMPLEFORMAT_IEEEFP;
                 break;
             }
             case DOUBLE : {
                 sampleBitSize = java.lang.Double.SIZE;
                 sampleFormat  = SAMPLEFORMAT_IEEEFP;
                 break;
             }
             default : throw new IllegalArgumentException("Unknow sample type.");
         }
         final short photometricInterpret;
         switch(pI) {
             case GRAYSCALE : {
                 photometricInterpret = PHOTOMETRIC_MINISBLACK;
                 break;
             }
             case RGB : {
                 photometricInterpret = PHOTOMETRIC_RGB;
                 break;
             }
             case PALETTE : {
                 photometricInterpret = PHOTOMETRIC_PALETTE;
                 if (java2DColorMap == null) throw new IllegalArgumentException("colorMap should not be null with palette photometric interpretation.");
                 break;
             }
             default : throw new IllegalArgumentException("Unknow photometric Interpretation.");
         }
         final short planarConfig = (pC.equals(PlanarConfiguration.BANDED)) ? PLANAR_BANDED : PLANAR_INTERLEAVED;
         return buildImageTypeSpecifier(sampleBitSize, numBand,
                                         photometricInterpret, sampleFormat, planarConfig,
                                         hasAlpha, isAlphaPremultiplied,
                                         java2DColorMap);
     }
buildImageTypeSpecifier() [2/2]
static ImageTypeSpecifier buildImageTypeSpecifier (final int sampleBitsSize, final int numBand, final short photometricInterpretation, final short sampleFormat, final short planarConfiguration, final boolean hasAlpha, final boolean isAlphaPremultiplied, final int [] java2DColorMap) throws UnsupportedOperationException static
Return an appropriate ImageTypeSpecifier built from given parameter.
Parameters
sampleBitsSize bit size for each sample.
numBand expected band number
photometricInterpretation
sampleFormat
planarConfiguration define planar configuration of asked ImageTypeSpecifier, 1 for interveaved 2 for banded sampleModel.
hasAlpha
isAlphaPremultiplied
java2DColorMap
Returns
ImageTypeSpecifier.
References ImageUtils.createColorModel(), ImageUtils.createSampleModel(), PlanarConfiguration.valueOf(), and SampleType.valueOf().
{
         final ColorModel cm = createColorModel(sampleBitsSize, numBand,
                                                 photometricInterpretation, sampleFormat,
                                                 hasAlpha, isAlphaPremultiplied,
                                                 java2DColorMap);
         final SampleModel sm = ImageUtils.createSampleModel(PlanarConfiguration.valueOf(planarConfiguration),
                                                             SampleType.valueOf(sampleBitsSize, sampleFormat),
                                                             1, 1, numBand);
         return new ImageTypeSpecifier(cm, sm);
     }
createARGBBandedImage()
static BufferedImage createARGBBandedImage (final int width, final int height, final SampleType type, final boolean isAlphaPremultiplied) static
Returns a BufferedImage of 4 bands, with an internaly AlphaRGB ColorSpace and created from given parameters.
Moreover : the type of internal image SampleModel is banded.
In other words the internal planar configuration is PlanarConfiguration#BANDED type.
Image will CONTAIN alpha canal.
Parameters
width image width.
height image height.
type type of internal data.
isAlphaPremultiplied
Returns
created AlphaRGB BufferedImage.
Exceptions
UnsupportedOperationException if problem during internal ColorModel creation.
See also
SampleType
PlanarConfiguration::BANDED
PhotometricInterpretation::RGB
References PlanarConfiguration.BANDED, ImageUtils.createImage(), and PhotometricInterpretation.RGB.
{
         return createImage(width, height, type, 4, PhotometricInterpretation.RGB, PlanarConfiguration.BANDED,true, isAlphaPremultiplied, null);
     }
createARGBInterleavedImage()
static BufferedImage createARGBInterleavedImage (final int width, final int height, final SampleType type, final boolean isAlphaPremultiplied) static
Returns a BufferedImage of 4 bandswith an internaly AlphaRGB ColorSpace and created from given parameters.
Moreover :
the type of internal image SampleModel is interleaved.
In other words the internal planar configuration is PlanarConfiguration#INTERLEAVED type.
Image will CONTAIN alpha canal.
Parameters
width image width.
height image height.
type type of internal data.
isAlphaPremultiplied
Returns
created AlphaRGB BufferedImage.
Exceptions
UnsupportedOperationException if problem during internal ColorModel creation.
See also
SampleType
PlanarConfiguration::INTERLEAVED
PhotometricInterpretation::RGB
References ImageUtils.createImage(), PlanarConfiguration.INTERLEAVED, and PhotometricInterpretation.RGB.
{
         return createImage(width, height,
                            type, 4,
                            PhotometricInterpretation.RGB, PlanarConfiguration.INTERLEAVED,
                            true, isAlphaPremultiplied, null);
     }
createARGBLargeImage()
static WritableLargeRenderedImage createARGBLargeImage (final int width, final int height, final SampleType type, final boolean isAlphaPremultiplied) static
Returns a WritableLargeRenderedImage with an internaly AlphaRGB ColorSpace and 4 bands, created from given parameters.
Moreover :
the type of internal image SampleModel is interleaved.
In other words the internal planar configuration is PlanarConfiguration#INTERLEAVED type.
Image will CONTAIN alpha canal.
Parameters
width image width.
height image height.
type type of internal data.
isAlphaPremultiplied
Returns
created ARGB WritableLargeRenderedImage.
Exceptions
UnsupportedOperationException if problem during internal ColorModel creation.
IllegalArgumentException if colorMap argument is
null
when PhotometricInterpretation is type palette.
See also
SampleType
WritableLargeRenderedImage
PhotometricInterpretation::RGB
References ImageUtils.createColorModel(), ImageUtils.createSampleModel(), and PhotometricInterpretation.RGB.
{
         final ColorModel cm  = createColorModel(type, 4, PhotometricInterpretation.RGB, true, isAlphaPremultiplied, null);
         final SampleModel sm = createSampleModel(INTERLEAVED, type, width, height, 4);
         return new WritableLargeRenderedImage(width, height, cm, sm);
     }
createColorModel() [1/3]
static ColorModel createColorModel (final SampleType type, final int numBand, final PhotometricInterpretation pI, final boolean hasAlpha, final boolean isAlphaPremultiplied, final int [] java2DColorMap) static
Returns ColorModel create from given parameters.
Parameters
type type of data within ColorModel.
numBand band nmber.
pI define type of ColorModel, for example RGB, palette etc.
hasAlpha
isAlphaPremultiplied
java2DColorMap array which define map when PhotometricInterpretation is type palette, or should be
null
.
Returns
created ColorModel.
Exceptions
UnsupportedOperationException if problem during ColorModel creation.
IllegalArgumentException if colorMap argument is
null
when PhotometricInterpretation is type palette.
See also
SampleType
PhotometricInterpretation
References ImageUtils.PHOTOMETRIC_MINISBLACK, ImageUtils.PHOTOMETRIC_PALETTE, ImageUtils.PHOTOMETRIC_RGB, ImageUtils.SAMPLEFORMAT_IEEEFP, ImageUtils.SAMPLEFORMAT_INT, and ImageUtils.SAMPLEFORMAT_UINT.
Referenced by ImageUtils.buildImageTypeSpecifier(), ImageUtils.createARGBLargeImage(), ImageUtils.createColorModel(), ImageUtils.createGreyScaledLargeImage(), ImageUtils.createLargeImage(), ImageUtils.createPaletteLargeImage(), and ImageUtils.createRGBLargeImage().
{
          final int sampleBitSize;
         final short sampleFormat;
         switch (type) {
             case BYTE : {
                 sampleBitSize = java.lang.Byte.SIZE;
                 sampleFormat  = SAMPLEFORMAT_UINT;
                 break;
             }
             case SHORT  : {
                 sampleBitSize = java.lang.Short.SIZE;
                 sampleFormat  = SAMPLEFORMAT_INT;
                 break;
             }
             case USHORT : {
                 sampleBitSize = java.lang.Short.SIZE;
                 sampleFormat  = SAMPLEFORMAT_UINT;
                 break;
             }
             case INTEGER : {
                 sampleBitSize = java.lang.Integer.SIZE;
                 sampleFormat  = SAMPLEFORMAT_UINT;
                 break;
             }
             case FLOAT  : {
                 sampleBitSize = java.lang.Float.SIZE;
                 sampleFormat  = SAMPLEFORMAT_IEEEFP;
                 break;
             }
             case DOUBLE : {
                 sampleBitSize = java.lang.Double.SIZE;
                 sampleFormat  = SAMPLEFORMAT_IEEEFP;
                 break;
             }
             default : throw new IllegalArgumentException("Unknow sample type.");
         }
         final short photometricInterpret;
         switch(pI) {
             case GRAYSCALE : {
                 photometricInterpret = PHOTOMETRIC_MINISBLACK;
                 break;
             }
             case RGB : {
                 photometricInterpret = PHOTOMETRIC_RGB;
                 break;
             }
             case PALETTE : {
                 photometricInterpret = PHOTOMETRIC_PALETTE;
                 if (java2DColorMap == null) throw new IllegalArgumentException("colorMap should not be null with palette photometric interpretation.");
                 break;
             }
             default : throw new IllegalArgumentException("Unknow photometric Interpretation.");
         }
         return createColorModel(sampleBitSize, numBand,
                                 photometricInterpret, sampleFormat,
                                 hasAlpha, isAlphaPremultiplied,
                                 java2DColorMap);
     }
createColorModel() [2/3]
static ColorModel createColorModel (final int sampleBitsSize, final int numBand, final short photometricInterpretation, final short sampleFormat, final boolean hasAlpha, final boolean isAlphaPremultiplied, final int [] java2DColorMap) throws UnsupportedOperationException static
Create and returns an adapted ColorModel from given parameters.
Parameters
sampleBitsSize
numBand
photometricInterpretation
sampleFormat
hasAlpha
isAlphaPremultiplied
java2DColorMap associate color map array in case where a palette color model is define.
Returns
an adapted ColorModel from given parameters.
Exceptions
IllegalArgumentException if photometric interpretation is define as palette (photometricInterpretation == 3) and colorMap is
null
.
References ImageUtils.createColorModel().
{
         return createColorModel(sampleBitsSize, numBand,
                                 photometricInterpretation, sampleFormat,
                                 null, null,
                                 hasAlpha, isAlphaPremultiplied,
                                 java2DColorMap);
     }
createColorModel() [3/3]
static ColorModel createColorModel (final int sampleBitsSize, final int numBand, final short photometricInterpretation, final short sampleFormat, final Double minSampleValue, final Double maxSampleValue, final boolean hasAlpha, final boolean isAlphaPreMultiplied, int [] java2DColorMap) throws UnsupportedOperationException static
Create and returns an adapted ColorModel from given parameters.
Parameters
sampleBitsSize
numBand
photometricInterpretation
sampleFormat
minSampleValue minimum raster sample value to build needed ColorSpace, may be
null
, if null the default choosen value will be Double#MIN_VALUE.
maxSampleValue maximum raster sample value to build needed ColorSpace, may be
null
, if null the default choosen value will be Double#MAX_VALUE.
hasAlpha define if the color has a alpha component.
isAlphaPreMultiplied define if the alpha has been premultiplied in the pixel values.
java2DColorMap associate color map array in case where a palette color model is define.
Returns
an adapted ColorModel from given parameters.
Exceptions
IllegalArgumentException if photometric interpretation is define as palette (photometricInterpretation == 3) and colorMap is
null
.
IllegalArgumentException if minSampleValue or maxSampleValue is(are) equals to Double#NaN.
See also
ScaledColorSpace
References ImageUtils.SAMPLEFORMAT_INT.
{
         if (minSampleValue != null) {
             if (Double.isNaN(minSampleValue))
                 throw new IllegalArgumentException("invalid minimum raster sample value, it should not be Double.NAN");
         }
         if (maxSampleValue != null) {
             if (Double.isNaN(maxSampleValue))
                 throw new IllegalArgumentException("invalid minimum raster sample value, it should not be Double.NAN");
         }
         final int dataBufferType;
         if (sampleFormat == 3) {
             /*
              * Case to defferency 32 bits Float to 32 bits Integer.
              */
             switch (sampleBitsSize) {
                 case Float.SIZE  : dataBufferType = DataBuffer.TYPE_FLOAT; break;
                 case Double.SIZE : dataBufferType = DataBuffer.TYPE_DOUBLE; break;
                 default : {
                     throw new UnsupportedOperationException( "unsupported bitsPerSample size : "+sampleBitsSize);
                 }
             }
         } else {
            /*
             * We require exact value, because the reading process read all sample values
             * in one contiguous read operation.
             */
            switch (sampleBitsSize) {
                case java.lang.Byte.SIZE  : dataBufferType = DataBuffer.TYPE_BYTE;   break;
                case java.lang.Short.SIZE : dataBufferType = (sampleFormat == SAMPLEFORMAT_INT)
                                                             ? DataBuffer.TYPE_SHORT
                                                             : DataBuffer.TYPE_USHORT; break;
                case Integer.SIZE         : dataBufferType = DataBuffer.TYPE_INT;    break;
                case Double.SIZE          : dataBufferType = DataBuffer.TYPE_DOUBLE; break;
                default : {
                     throw new UnsupportedOperationException( "unsupported bitsPerSample size : "+sampleBitsSize);
                }
            }
         }
         final ColorSpace cs;
         switch (photometricInterpretation) {
             case 0 :   //--minIsWhite
             case 1 : { //-- minIsBlack
                 if (numBand > 1
                  || dataBufferType == DataBuffer.TYPE_FLOAT
                  || dataBufferType == DataBuffer.TYPE_DOUBLE) {
                     final double minCs = (minSampleValue != null) ? minSampleValue : Double.MIN_VALUE;
                     final double maxCs = (maxSampleValue != null) ? maxSampleValue : Double.MAX_VALUE;
                     cs = ColorModelFactory.createColorSpace(numBand, 0, minCs, maxCs);//-- attention au choix de la bande !!!!
                 } else {
                     cs = ColorSpace.getInstance(ColorSpace.CS_GRAY);
                 }
                 break;
             }
             case 2 : { //-- RGB
                 cs = ColorSpace.getInstance(ColorSpace.CS_sRGB);
                 break;
             }
             case 3 : {//-- palette
                 if (java2DColorMap == null)
                      throw new IllegalArgumentException("Impossible to build palette color model with null color map array.");
                 final ColorModel cm = new IndexColorModel(sampleBitsSize, java2DColorMap.length, java2DColorMap, 0, true, -1, dataBufferType);
                 /*
                  * Create a SampleModel with size of 1x1 volontary just to know image properties.
                  * Image with correctively size will be create later with getDestination() in #read(int index, param) method.
                  */
                 return cm;
             }
             default : {
                 throw new UnsupportedOperationException( "photometricInterpretation : "+photometricInterpretation);
             }
         }
         final int[] bits = new int[numBand];
         Arrays.fill(bits, sampleBitsSize);
         return new ComponentScaledColorModel(cs, bits, hasAlpha, isAlphaPreMultiplied,
                 hasAlpha ? Transparency.TRANSLUCENT : Transparency.OPAQUE, dataBufferType);
     }
createGreyScaledBandedImage()
static BufferedImage createGreyScaledBandedImage (final int width, final int height, final SampleType type, final int numBand) static
Returns a BufferedImage with an internaly gray scaled ColorSpace, created from given parameters.
Moreover :
the type of internal image SampleModel is banded.
In other words the internal planar configuration is PlanarConfiguration#BANDED type.
Image will NOT CONTAIN any alpha canal.
Parameters
width image width.
height image height.
type type of internal data.
numBand band number.
Returns
created gray scaled BufferedImage.
Exceptions
UnsupportedOperationException if problem during internal ColorModel creation.
See also
SampleType
PlanarConfiguration::banded
PhotometricInterpretation::GRAYSCALE
References PlanarConfiguration.BANDED, ImageUtils.createImage(), and PhotometricInterpretation.GRAYSCALE.
{
         return createImage(width, height,
                             type, numBand,
                             PhotometricInterpretation.GRAYSCALE, PlanarConfiguration.BANDED,
                             false, false, null);
     }
createGreyScaledInterleavedImage()
static BufferedImage createGreyScaledInterleavedImage (final int width, final int height, final SampleType type, final int numBand) static
Returns a BufferedImage with an internaly gray scaled ColorSpace, created from given parameters.
Moreover :
the type of internal image SampleModel is pixel interleaved.
In other words the internal planar configuration is PlanarConfiguration#INTERLEAVED type.
Image will NOT CONTAIN any alpha canal.
Parameters
width image width.
height image height.
type type of internal data.
numBand band number.
Returns
created gray scaled BufferedImage.
Exceptions
UnsupportedOperationException if problem during internal ColorModel creation.
See also
SampleType
PlanarConfiguration::INTERLEAVED
PhotometricInterpretation::GRAYSCALE
References ImageUtils.createImage(), PhotometricInterpretation.GRAYSCALE, and PlanarConfiguration.INTERLEAVED.
{
         return createImage(width, height,
                             type, numBand,
                             PhotometricInterpretation.GRAYSCALE, PlanarConfiguration.INTERLEAVED,
                             false, false, null);
     }
createGreyScaledLargeImage()
static WritableLargeRenderedImage createGreyScaledLargeImage (final int width, final int height, final SampleType type, final int numBand) static
Returns a WritableLargeRenderedImage with an internaly gray scaled ColorSpace, created from given parameters.
Moreover :
the type of internal image SampleModel is interleaved.
In other words the internal planar configuration is PlanarConfiguration#INTERLEAVED type.
Image will NOT CONTAIN alpha canal.
Parameters
width image width.
height image height.
type type of internal data.
numBand band number.
Returns
created gray Scaled WritableLargeRenderedImage.
Exceptions
UnsupportedOperationException if problem during internal ColorModel creation.
IllegalArgumentException if colorMap argument is
null
when PhotometricInterpretation is type palette.
See also
SampleType
WritableLargeRenderedImage
PhotometricInterpretation::GRAYSCALE
References ImageUtils.createColorModel(), ImageUtils.createSampleModel(), and PhotometricInterpretation.GRAYSCALE.
{
         final ColorModel cm  = createColorModel(type, numBand, PhotometricInterpretation.GRAYSCALE, false, false, null);
         final SampleModel sm = createSampleModel(INTERLEAVED, type, width, height, numBand);
         return new WritableLargeRenderedImage(width, height, cm, sm);
     }
createImage()
static BufferedImage createImage (final int width, final int height, final SampleType type, final int numBand, final PhotometricInterpretation pI, final PlanarConfiguration pC, final boolean hasAlpha, final boolean isAlphaPremultiplied, final int [] java2DColorMap) static
Returns a BufferedImage created from given parameters.
Parameters
width image width.
height image height.
type type of internal data.
numBand band number.
pI define type of ColorModel, for example RGB, palette etc.
pC define type of internal SampleModel, banded or interleaved.
hasAlpha
isAlphaPremultiplied
java2DColorMap array which define map when PhotometricInterpretation is type palette, or should be
null
.
Returns
created BufferedImage.
Exceptions
UnsupportedOperationException if problem during internal ColorModel creation.
IllegalArgumentException if colorMap argument is
null
when PhotometricInterpretation is type palette.
See also
SampleType
PhotometricInterpretation
PlanarConfiguration
References ImageUtils.buildImageTypeSpecifier().
Referenced by ImageUtils.createARGBBandedImage(), ImageUtils.createARGBInterleavedImage(), ImageUtils.createGreyScaledBandedImage(), ImageUtils.createGreyScaledInterleavedImage(), ImageUtils.createPaletteImage(), ImageUtils.createRGBBandedImage(), and ImageUtils.createRGBInterleavedImage().
{
         final ImageTypeSpecifier imgTypeSpec = buildImageTypeSpecifier(type, numBand,
                                                                         pI, pC,
                                                                         hasAlpha, isAlphaPremultiplied,
                                                                         java2DColorMap);
         return imgTypeSpec.createBufferedImage(width, height);
     }
createLargeImage() [1/2]
static WritableLargeRenderedImage createLargeImage (final int width, final int height, final SampleType type, final int numBand, final PhotometricInterpretation pI, final boolean hasAlpha, final boolean isAlphaPremultiplied, final int [] java2DColorMap) static
Returns a WritableLargeRenderedImage created from given parameters.
Moreover : the type of internal image SampleModel is pixel interleaved.
In other words the internal planar configuration is PlanarConfiguration#INTERLEAVED type.
Parameters
width image width.
height image height.
type type of internal data.
numBand band number.
pI define type of ColorModel, for example RGB, palette etc.
hasAlpha
isAlphaPremultiplied
java2DColorMap array which define map when PhotometricInterpretation is type palette, or should be
null
.
Returns
created WritableLargeRenderedImage.
Exceptions
UnsupportedOperationException if problem during internal ColorModel creation.
IllegalArgumentException if colorMap argument is
null
when PhotometricInterpretation is type palette.
See also
SampleType
PhotometricInterpretation
WritableLargeRenderedImage
References ImageUtils.createColorModel(), and ImageUtils.createSampleModel().
{
         final ColorModel cm = createColorModel(type, numBand, pI, hasAlpha, isAlphaPremultiplied, java2DColorMap);
         final SampleModel sm = createSampleModel(INTERLEAVED, type, width, height, numBand);
         return new WritableLargeRenderedImage(width, height, cm, sm);
     }
createLargeImage() [2/2]
static WritableLargeRenderedImage createLargeImage (final int minx, final int miny, final int width, final int height, final Dimension tileSize, final SampleType type, final int numBand, final int tilegridXOffset, final int tilegridYOffset, final PhotometricInterpretation pI, final boolean hasAlpha, final boolean isAlphaPremultiplied, final int [] java2DColorMap) static
Returns a WritableLargeRenderedImage created from given parameters.
Moreover : the type of internal image SampleModel is pixel interleaved.
In other words the internal planar configuration is PlanarConfiguration#INTERLEAVED type.
Parameters
minx minimum image coordinate in X direction.
miny minimum image coordinate in Y direction.
width image width.
height image height.
tileSize size of internal image tiles.
type type of internal data.
numBand band number.
tilegridXOffset
tilegridYOffset
pI define type of ColorModel, for example RGB, palette etc.
hasAlpha
isAlphaPremultiplied
java2DColorMap array which define map when PhotometricInterpretation is type palette, or should be
null
.
Returns
created WritableLargeRenderedImage.
Exceptions
UnsupportedOperationException if problem during internal ColorModel creation.
IllegalArgumentException if colorMap argument is
null
when PhotometricInterpretation is type palette.
See also
SampleType
PhotometricInterpretation
WritableLargeRenderedImage
References ImageUtils.createColorModel(), and ImageUtils.createSampleModel().
{
         final ColorModel cm  = createColorModel(type, numBand, pI, hasAlpha, isAlphaPremultiplied, java2DColorMap);
         final SampleModel sm = createSampleModel(INTERLEAVED, type, width, height, numBand);
         return new WritableLargeRenderedImage(minx, miny, width, height, tileSize, tilegridXOffset, tilegridYOffset, cm, sm);
     }
createPaletteImage()
static BufferedImage createPaletteImage (final int width, final int height, final SampleType type, final int numband, final int [] java2DColorMap) static
Returns a BufferedImage with an internaly palette ColorSpace, created from given parameters.
Moreover :
the type of internal image SampleModel is interleaved.
In other words the internal planar configuration is PlanarConfiguration#INTERLEAVED type.
Image will NOT CONTAIN any alpha canal.
Parameters
width image width.
height image height.
type type of internal data.
numband band number of internaly image rasters.
java2DColorMap array which define map when PhotometricInterpretation is type palette.
Returns
created palette BufferedImage.
Exceptions
IllegalArgumentException if colorMap argument is
null
.
See also
SampleType
PhotometricInterpretation::PALETTE
References ImageUtils.createImage(), PlanarConfiguration.INTERLEAVED, and PhotometricInterpretation.PALETTE.
{
         return createImage(width, height,
                             type, numband,
                             PhotometricInterpretation.PALETTE, PlanarConfiguration.INTERLEAVED,
                             false, false,
                             java2DColorMap);
     }
createPaletteLargeImage()
static WritableLargeRenderedImage createPaletteLargeImage (final int width, final int height, final SampleType type, final int numBand, final int [] java2DColorMap) static
Returns a WritableLargeRenderedImage with an internaly palette ColorSpace, created from given parameters.
Moreover :
the type of internal image SampleModel is pixel interleaved.
In other words the internal planar configuration is PlanarConfiguration#INTERLEAVED type.
Image will NOT CONTAIN any alpha canal.
Parameters
width image width.
height image height.
type type of internal data.
numBand band number.
java2DColorMap array which define map when PhotometricInterpretation is type palette.
Returns
created palette WritableLargeRenderedImage.
Exceptions
UnsupportedOperationException if problem during internal ColorModel creation.
IllegalArgumentException if colorMap argument is
null
.
See also
SampleType
WritableLargeRenderedImage
PhotometricInterpretation::PALETTE
References ImageUtils.createColorModel(), ImageUtils.createSampleModel(), and PhotometricInterpretation.PALETTE.
{
         final ColorModel cm  = createColorModel(type, numBand, PhotometricInterpretation.PALETTE, false, false, java2DColorMap);
         final SampleModel sm = createSampleModel(INTERLEAVED, type, width, height, numBand);
         return new WritableLargeRenderedImage(width, height, cm, sm);
     }
createRGBBandedImage()
static BufferedImage createRGBBandedImage (final int width, final int height, final SampleType type) static
Returns a BufferedImage of 3 bands with an internaly RGB ColorSpace, created from given parameters.
Moreover :
the type of internal image SampleModel is banded.
In other words the internal planar configuration is PlanarConfiguration#BANDED type.
Image will NOT CONTAIN any alpha canal.
Parameters
width image width.
height image height.
type type of internal data.
Returns
created RGB BufferedImage.
Exceptions
UnsupportedOperationException if problem during internal ColorModel creation.
See also
SampleType
PlanarConfiguration::BANDED
PhotometricInterpretation::RGB
References PlanarConfiguration.BANDED, ImageUtils.createImage(), and PhotometricInterpretation.RGB.
{
         return createImage(width, height,
                             type, 3,
                             PhotometricInterpretation.RGB, PlanarConfiguration.BANDED,
                             false, false, null);
     }
createRGBInterleavedImage()
static BufferedImage createRGBInterleavedImage (final int width, final int height, final SampleType type) static
Returns a BufferedImage of 3 bands, with an internaly RGB ColorSpace and created from given parameters.
Moreover :
the type of internal image SampleModel is interleaved.
In other words the internal planar configuration is PlanarConfiguration#INTERLEAVED type.
Image will NOT CONTAIN any alpha canal.
Parameters
width image width.
height image height.
type type of internal data.
Returns
created RGB BufferedImage.
Exceptions
UnsupportedOperationException if problem during internal ColorModel creation.
See also
SampleType
PlanarConfiguration::INTERLEAVED
PhotometricInterpretation::RGB
References ImageUtils.createImage(), PlanarConfiguration.INTERLEAVED, and PhotometricInterpretation.RGB.
{
         return createImage(width, height,
                 type, 3, PhotometricInterpretation.RGB, PlanarConfiguration.INTERLEAVED,
                 false, false, null);
     }
createRGBLargeImage()
static WritableLargeRenderedImage createRGBLargeImage (final int width, final int height, final SampleType type) static
Returns a WritableLargeRenderedImage of 3 bands with an internaly RGB ColorSpace, created from given parameters.
Moreover :
the type of internal image SampleModel is interleaved.
In other words the internal planar configuration is PlanarConfiguration#INTERLEAVED type.
Image will NOT CONTAIN alpha canal.
Parameters
width image width.
height image height.
type type of internal data.
Returns
created RGB WritableLargeRenderedImage.
Exceptions
UnsupportedOperationException if problem during internal ColorModel creation.
IllegalArgumentException if colorMap argument is
null
when PhotometricInterpretation is type palette.
See also
SampleType
WritableLargeRenderedImage
PhotometricInterpretation::RGB
References ImageUtils.createColorModel(), ImageUtils.createSampleModel(), and PhotometricInterpretation.RGB.
{
         final ColorModel cm  = createColorModel(type, 3, PhotometricInterpretation.RGB, false, false, null);
         final SampleModel sm = createSampleModel(INTERLEAVED, type, width, height, 3);
         return new WritableLargeRenderedImage(width, height, cm, sm);
     }
createSampleModel()
static SampleModel createSampleModel (final PlanarConfiguration planarConfiguration, final SampleType sampleType, final int width, final int height, final int numBand) throws UnsupportedOperationException static
Create and returns appropriate SampleModel built from given parameters.
Note : 2 kind of SampleModel may be returned with differents internales configurations.
1 - PixelInterleavedSampleModel :
pixelstride = numband
scanlineStride = width * pixelstride.
2 - BandedSampleModel :
scanlineStride = width
Parameters
planarConfiguration define planar configuration of asked SampleModel, 1 for PixelInterleavedSampleModel and 2 for BandedSampleModel
sampleType Data type of internal image raster.
width image width
height image height
numBand image numband
Returns
ImageTypeSpecifier.
See also
PLANAR_INTERLEAVED
PLANAR_BANDED
References SampleType.valueOf().
Referenced by ImageUtils.buildImageTypeSpecifier(), ImageUtils.createARGBLargeImage(), ImageUtils.ComponentScaledColorModel.createCompatibleSampleModel(), ImageUtils.createGreyScaledLargeImage(), ImageUtils.createLargeImage(), ImageUtils.createPaletteLargeImage(), ImageUtils.createRGBLargeImage(), and LargeRenderedImage.LargeRenderedImage().
{
         final int[] bandOff = new int[numBand];
         switch (planarConfiguration) {
             case INTERLEAVED : {
                 int b = -1;
                 while (++b < numBand) bandOff[b] = b;
                 return new PixelInterleavedSampleModel(SampleType.valueOf(sampleType), width, height, numBand, numBand * width, bandOff);
             }
             case BANDED : {
                 final int[] bankIndices = new int[numBand];
                 int b = -1;
                 while (++b < numBand) bankIndices[b] = b;
                 return new BandedSampleModel(SampleType.valueOf(sampleType), width, height, width, bankIndices, bandOff);
             }
             default : throw new IllegalArgumentException("unknow planarConfiguration type. Expected 1 for interleaved or 2 for banded. Found : "+planarConfiguration);
         }
     }
getEnumPhotometricInterpretation()
static PhotometricInterpretation getEnumPhotometricInterpretation (final ColorModel cm) static
Define photometric interpretation tiff tag in function of ColorModel properties.
Parameters
cm image color model.
Returns
1 for gray, 2 for RGB, 3 for indexed colormodel.
References ImageUtils.getPhotometricInterpretation(), and PhotometricInterpretation.valueOf().
{
         return PhotometricInterpretation.valueOf(getPhotometricInterpretation(cm));
     }
getEnumPlanarConfiguration()
static PlanarConfiguration getEnumPlanarConfiguration (final SampleModel sm) static
Define appropriate PlanarConfiguration enum from its integer planarConfiguration into tiff specification.
Parameters
sm needed SampleModel to define planar configuration.
Returns
PlanarConfiguration#INTERLEAVED for an interleaved sampleModel or PlanarConfiguration#BANDED.
See also
PLANAR_INTERLEAVED
PLANAR_BANDED
getPlanarConfiguration(java.awt.image.SampleModel)
References ImageUtils.getPlanarConfiguration(), and PlanarConfiguration.valueOf().
{
         return PlanarConfiguration.valueOf(getPlanarConfiguration(sm));
     }
getPhotometricInterpretation()
static short getPhotometricInterpretation (final ColorModel cm) static
Define photometric interpretation tiff tag in function of ColorModel properties.
Parameters
cm image color model.
Returns
1 for gray, 2 for RGB, 3 for indexed colormodel.
References ImageUtils.PHOTOMETRIC_MINISBLACK, ImageUtils.PHOTOMETRIC_PALETTE, and ImageUtils.PHOTOMETRIC_RGB.
Referenced by ImageUtils.getEnumPhotometricInterpretation().
{
         final ColorSpace cs = cm.getColorSpace();
         //-- to do : if we need we can also define 1 for an ScaledColorSpace --//
         if (cs.equals(ColorSpace.getInstance(ColorSpace.CS_GRAY)) || cs.getClass().getSimpleName().equals("ScaledColorSpace")) {
             // return 0 or 1
             // return 0 for min is white
             // return 1 for min is black
             return PHOTOMETRIC_MINISBLACK;
         } else if (cm instanceof IndexColorModel) {
             return PHOTOMETRIC_PALETTE;
         } else if (cs.isCS_sRGB()) {
             return PHOTOMETRIC_RGB;
         } else {
             throw new IllegalStateException("unknow photometricInterpretation : unknow color model type.");
         }
     }
getPlanarConfiguration()
static short getPlanarConfiguration (final SampleModel sm) static
Define appropriate tiff tag value for planar configuration from SampleModel properties.
Parameters
sm needed SampleModel to define planar configuration.
Returns
1 for pixel interleaved or 2 for band interleaved.
See also
PLANAR_INTERLEAVED
PLANAR_BANDED
References ImageUtils.PLANAR_BANDED, and ImageUtils.PLANAR_INTERLEAVED.
Referenced by ImageUtils.getEnumPlanarConfiguration(), and LargeRenderedImage.LargeRenderedImage().
{
         final int numband  = sm.getNumBands();
         if (numband > 1 && sm instanceof ComponentSampleModel) {
             final ComponentSampleModel csm = (ComponentSampleModel) sm;
             final int[] bankIndice = csm.getBankIndices();
             if (csm.getPixelStride() != 1 || bankIndice.length == 1) return PLANAR_INTERLEAVED;
             int b = 0;
             while (++b < bankIndice.length) if (bankIndice[b] == bankIndice[b - 1]) return PLANAR_INTERLEAVED;
             return PLANAR_BANDED;
         }
         return PLANAR_INTERLEAVED;
     }
getSampleFormat()
static int getSampleFormat (final SampleModel sm) static
Define appropriate tiff tag value for planar configuration from SampleModel properties.
Parameters
sm needed SampleModel to define planar configuration.
Returns
1 for integer format, 2 for integer signed format or 3 for floating format (IEEE).
See also
SAMPLEFORMAT_UINT
SAMPLEFORMAT_INT
SAMPLEFORMAT_IEEEFP
References ImageUtils.SAMPLEFORMAT_IEEEFP, ImageUtils.SAMPLEFORMAT_INT, and ImageUtils.SAMPLEFORMAT_UINT.
{
         //-- bitpersamples
         final int[] sampleSize = sm.getSampleSize();// sample size in bits
         int samplePerPixel = sampleSize.length;
         assert samplePerPixel == sm.getNumBands() : "samplePerPixel = "+samplePerPixel+". sm.getnumDataElement = "+sm.getNumBands();
         for (int i = 1; i < samplePerPixel; i++) {
             if (sampleSize[i-1] != sampleSize[i]) {
                 throw new IllegalStateException("different sample size is not supported in tiff format.");
             }
         }
         assert sampleSize[0] <= 0xFFFF : "BitsPerSample exceed short max value";
         final int dataType = sm.getDataType();
         switch (dataType) {
             case DataBuffer.TYPE_FLOAT  :
             case DataBuffer.TYPE_DOUBLE : {
                 return SAMPLEFORMAT_IEEEFP; //-- type floating point --//
             }
             case DataBuffer.TYPE_BYTE  :
             case DataBuffer.TYPE_SHORT :
             case DataBuffer.TYPE_INT   : {
                 return SAMPLEFORMAT_INT; //-- type signed 8, 16, 32 bits Int --//
             }
             default : { return SAMPLEFORMAT_UINT;} //-- type UInt or UShort--//
         }
     }
Member Data Documentation
PHOTOMETRIC_MINISBLACK
final short PHOTOMETRIC_MINISBLACK = 1 static private
Define image properties for bilevel and grayscale images: 0 is imaged as black.
Referenced by ImageUtils.buildImageTypeSpecifier(), ImageUtils.createColorModel(), and ImageUtils.getPhotometricInterpretation().
PHOTOMETRIC_PALETTE
final short PHOTOMETRIC_PALETTE = 3 static private
Define image with Palette color.
In this model, a color is described with a single component. The value of the component is used as an index into the red, green and blue curves in the ColorMap field to retrieve an RGB triplet that defines the color. When PhotometricInterpretation = 3 is used, ColorMap must be present and SamplesPerPixel must be 1.
Referenced by ImageUtils.buildImageTypeSpecifier(), ImageUtils.createColorModel(), and ImageUtils.getPhotometricInterpretation().
PHOTOMETRIC_RGB
final short PHOTOMETRIC_RGB = 2 static private
Define image properties for RGB image.
RGB value of (0,0,0) represents black, and (255,255,255) represents white, assuming 8-bit components. The components are stored in the indicated order: first Red, then Green, then Blue.
Referenced by ImageUtils.buildImageTypeSpecifier(), ImageUtils.createColorModel(), and ImageUtils.getPhotometricInterpretation().
PLANAR_BANDED
final short PLANAR_BANDED = 2 static private
Integer that define planar configuration as banded.
For example in a RGB image, within the first band, pixel value will be order like follow : RRRRRRRR... and next band : GGGGGGG... and last : BBBBBBB.
Referenced by ImageUtils.getPlanarConfiguration().
PLANAR_INTERLEAVED
final short PLANAR_INTERLEAVED = 1 static private
Integer that define planar configuration as interleaved.
For example in a RGB image, within the same band, pixel value will be order like follow : RGBRGBRGB ...
Referenced by ImageUtils.getPlanarConfiguration().
SAMPLEFORMAT_IEEEFP
final short SAMPLEFORMAT_IEEEFP = 3 static private
Define buffer type as IEEE floating point data.
Referenced by ImageUtils.buildImageTypeSpecifier(), ImageUtils.createColorModel(), and ImageUtils.getSampleFormat().
SAMPLEFORMAT_INT
final short SAMPLEFORMAT_INT = 2 static private
Define buffer type as signed integer point data.
Referenced by ImageUtils.buildImageTypeSpecifier(), ImageUtils.createColorModel(), and ImageUtils.getSampleFormat().
SAMPLEFORMAT_UINT
final short SAMPLEFORMAT_UINT = 1 static private
Define buffer type as unsigned integer point data.
Referenced by ImageUtils.buildImageTypeSpecifier(), ImageUtils.createColorModel(), and ImageUtils.getSampleFormat().