jena-geo: PlanarConfiguration Enum Reference
PlanarConfiguration Enum Reference
Define internaly SampleModel planar configuration.
Static Public Member Functions
static PlanarConfiguration valueOf (int planardConfiguration)
Mapping between ImageUtils#getPlanarConfiguration(java.awt.image.ColorModel) and org.geotoolkit.image.internal.PlanarConfiguration enum.
static int valueOf (final PlanarConfiguration planardConfiguration)
Mapping between org.geotoolkit.image.internal.PlanarConfiguration enum and ImageUtils#getPlanarConfiguration(java.awt.image.ColorModel).
Public Attributes
INTERLEAVED
Integer that define planar configuration as interleaved.
Detailed Description
Define internaly SampleModel planar configuration.
Define how datas are ordonnance within SampleModel.
Author
Remi Marechal (Geomatys).
Member Function Documentation
valueOf() [1/2]
static PlanarConfiguration valueOf (int planardConfiguration) static
Mapping between ImageUtils#getPlanarConfiguration(java.awt.image.ColorModel) and org.geotoolkit.image.internal.PlanarConfiguration enum.
Parameters
planardConfiguration integer compute by ImageUtils#getPlanarConfiguration(java.awt.image.SampleModel).
Returns
org.geotoolkit.image.internal.SampleType or
null
if type undefined.
Referenced by ImageUtils.buildImageTypeSpecifier(), ImageUtils.getEnumPlanarConfiguration(), and LargeRenderedImage.LargeRenderedImage().
{
         switch (planardConfiguration) {
             case 1 : return INTERLEAVED;
             case 2 : return BANDED;
             default: return null;
         }
     }
valueOf() [2/2]
static int valueOf (final PlanarConfiguration planardConfiguration) static
Mapping between org.geotoolkit.image.internal.PlanarConfiguration enum and ImageUtils#getPlanarConfiguration(java.awt.image.ColorModel).
Parameters
planardConfiguration org.geotoolkit.image.internal.SampleType.
Returns
the same integer as it compute by ImageUtils#getPlanarConfiguration(java.awt.image.SampleModel).
Exceptions
IllegalArgumentException if planar configuration is unknow.
{
         switch (planardConfiguration) {
             case INTERLEAVED : return 1;
             case BANDED      : return 2;
             default: throw new IllegalArgumentException("unknow planar configuration.");
         }
     }
Member Data Documentation
INTERLEAVED
INTERLEAVED
Integer that define planar configuration as interleaved.
For example in a RGB image, within the same band, pixel value will be order like follow : RGBRGBRGB ...
Referenced by ImageUtils.createARGBInterleavedImage(), ImageUtils.createGreyScaledInterleavedImage(), ImageUtils.createPaletteImage(), and ImageUtils.createRGBInterleavedImage().