jena-geo: ScaledColorSpace Class Reference
ScaledColorSpace Class Reference
Color space for images storing pixels as real numbers.
Public Member Functions
float [] toRGB (final float[] samples)
Returns a RGB color for a sample value.
float [] fromRGB (final float[] color)
Returns a sample value for the specified RGB color.
float [] toCIEXYZ (final float[] values)
Returns a CIEXYZ color for a sample value.
float [] fromCIEXYZ (final float[] color)
Returns a sample value for the specified CIEXYZ color.
float getMinValue (final int component)
Returns the minimum value for the specified RGB component.
float getMaxValue (final int component)
Returns the maximum value for the specified RGB component.
String toString ()
Returns a string representation of this color space.
int hashCode ()
Returns a hash code value for this color space.
boolean equals (final Object obj)
Compares this color space with the given object for equality.
Package Functions
ScaledColorSpace (final int numComponents, final int visibleBand, final double minimum, final double maximum)
Creates a color model for the given range of values.
final void formatRange (final StringBuilder buffer)
Formats the range of values in the given buffer.
Package Attributes
final double scale
The scaling factor from sample values to RGB values.
final double offset
The offset to subtract from sample values before to apply the scale} factor.
final int visibleBand
Index of the band to display, from 0 inclusive to getNumComponents() exclusive.
Static Private Attributes
static final long serialVersionUID = -6635165959083590494L
For cross-version compatibility.
Detailed Description
Color space for images storing pixels as real numbers.
This color space can have an arbitrary number of bands, but only one band is shown. Current implementation produces grayscale image only, but it may change in future.
The use of this color space is very slow. It should be used only when no standard color space can be used.
Author
Martin Desruisseaux (IRD, Geomatys)
Version
1.1
See also
ScaledColorModel
ColorModelFactory::createGrayScale(int, int, int, double, double)
Since
1.0
Constructor & Destructor Documentation
ScaledColorSpace()
ScaledColorSpace (final int numComponents, final int visibleBand, final double minimum, final double maximum) package
Creates a color model for the given range of values.
The given range does not need to be exact; values outside that range will be clamped.
Parameters
numComponents the number of components.
visibleBand the band to use for computing colors.
minimum the minimal sample value expected, inclusive.
maximum the maximal sample value expected, exclusive.
References ScaledColorModel.RANGE, and ScaledColorSpace.visibleBand.
Referenced by ScaledColorSpace.equals().
{
         super(TYPE_GRAY, numComponents);
         this.visibleBand = visibleBand;
         scale  = ScaledColorModel.RANGE / (maximum - minimum);
         offset = minimum;
     }
Member Function Documentation
equals()
boolean equals (final Object obj)
Compares this color space with the given object for equality.
References ScaledColorSpace.offset, ScaledColorSpace.scale, ScaledColorSpace.ScaledColorSpace(), and ScaledColorSpace.visibleBand.
{
         if (obj instanceof ScaledColorSpace) {
             final ScaledColorSpace that = (ScaledColorSpace) obj;
             return Numerics.equals(scale,  that.scale)             &&
                    Numerics.equals(offset, that.offset)            &&
                    visibleBand         ==  that.visibleBand        &&
                    getNumComponents()  ==  that.getNumComponents() &&
                    getType()           ==  that.getType();
         }
         return false;
     }
formatRange()
final void formatRange (final StringBuilder buffer) package
Formats the range of values in the given buffer.
This method is used for toString() implementation and may change in any future version.
Parameters
buffer where to append the range of values.
References ScaledColorSpace.getMaxValue(), and ScaledColorSpace.getMinValue().
Referenced by ScaledColorSpace.toString().
{
         buffer.append('[').append(getMinValue(visibleBand))
             .append(" … ").append(getMaxValue(visibleBand))
             .append(" in band ").append(visibleBand).append(']');
     }
fromCIEXYZ()
float [] fromCIEXYZ (final float [] color)
Returns a sample value for the specified CIEXYZ color.
Parameters
color normalized CIEXYZ values between 0 and 1.
Returns
sample values in the raster.
References ScaledColorModel.RANGE, ScaledColorSpace.scale, and ScaledColorSpace.visibleBand.
{
         final float[] values = new float[getNumComponents()];
         values[visibleBand] = (float) ((color[0] / 0.9642f + color[1] + color[2] / 0.8249f)
                             / (3d/ScaledColorModel.RANGE * scale) + offset);
         return values;
     }
fromRGB()
float [] fromRGB (final float [] color)
Returns a sample value for the specified RGB color.
Parameters
color normalized RGB values between 0 and 1.
Returns
sample values in the raster.
References ScaledColorModel.RANGE, ScaledColorSpace.scale, and ScaledColorSpace.visibleBand.
{
         final float[] values = new float[getNumComponents()];
         values[visibleBand] = (float) ((color[0] + color[1] + color[2])
                             / (3d/ScaledColorModel.RANGE * scale) + offset);
         return values;
     }
getMaxValue()
float getMaxValue (final int component)
Returns the maximum value for the specified RGB component.
Parameters
component the component index.
Returns
maximum normalized component value.
References ScaledColorSpace.offset, and ScaledColorModel.RANGE.
Referenced by ScaledColorSpace.formatRange().
{
         return (float) (ScaledColorModel.RANGE / scale + offset);
     }
getMinValue()
float getMinValue (final int component)
Returns the minimum value for the specified RGB component.
Parameters
component the component index.
Returns
minimum normalized component value.
References ScaledColorSpace.offset.
Referenced by ScaledColorSpace.formatRange().
{
         return (float) offset;
     }
hashCode()
int hashCode ()
Returns a hash code value for this color space.
References ScaledColorSpace.visibleBand.
{
         return Long.hashCode(Double.doubleToLongBits(scale)
                       + 31 * Double.doubleToLongBits(offset))
                       +  7 * getNumComponents() + visibleBand;
     }
toCIEXYZ()
float [] toCIEXYZ (final float [] values)
Returns a CIEXYZ color for a sample value.
Parameters
values sample values in the raster.
Returns
color as normalized CIEXYZ values between 0 and 1.
References ScaledColorSpace.toRGB().
{
         final float[] codes = toRGB(values);
         codes[0] *= 0.9642f;
         codes[2] *= 0.8249f;
         return codes;
     }
toRGB()
float [] toRGB (final float [] samples)
Returns a RGB color for a sample value.
Parameters
samples sample values in the raster.
Returns
color as normalized RGB values between 0 and 1.
References ScaledColorModel.RANGE.
Referenced by ScaledColorSpace.toCIEXYZ().
{
         float value = Math.min(1, (float) ((samples[visibleBand] - offset) * (1d/ScaledColorModel.RANGE * scale)));
         if (!(value >= 0)) value = 0;                   // Use '!' for replacing NaN.
         return new float[] {value, value, value};
     }
toString()
String toString ()
Returns a string representation of this color space.
Returns
a string representation for debugging purpose.
References ScaledColorSpace.formatRange().
{
         final StringBuilder buffer = new StringBuilder(20).append(getClass().getSimpleName());
         formatRange(buffer);
         return buffer.toString();
     }
Member Data Documentation
offset
final double offset package
The offset to subtract from sample values before to apply the scale} factor.
Referenced by ScaledColorSpace.equals(), ScaledColorSpace.getMaxValue(), ScaledColorSpace.getMinValue(), and ScaledColorModel.getRGB().
scale
final double scale package
The scaling factor from sample values to RGB values.
The target RGB values will be in range 0 to 255 inclusive. Note that the target range is different than the range of ColorSpace normalized values; methods in this class has to divide values by { ScaledColorModel::RANGE}.
Referenced by ScaledColorSpace.equals(), ScaledColorSpace.fromCIEXYZ(), ScaledColorSpace.fromRGB(), and ScaledColorModel.getRGB().
serialVersionUID
final long serialVersionUID = -6635165959083590494L static private
For cross-version compatibility.
visibleBand
final int visibleBand package
Index of the band to display, from 0 inclusive to getNumComponents() exclusive.
Referenced by ScaledColorSpace.equals(), ScaledColorSpace.fromCIEXYZ(), ScaledColorSpace.fromRGB(), ScaledColorModel.getAlpha(), ScaledColorModel.getRGB(), ScaledColorSpace.hashCode(), and ScaledColorSpace.ScaledColorSpace().