jena-geo: TileOpExecutor Class Reference
TileOpExecutor Class Reference
A read or write action to execute on each tile of an image.
Classes
class Cursor
Tile indices of the next tile to process in a multi-threaded computation.
class ReadWork
Worker which will read tiles.
class Worker
Base class of workers which will read or write tiles.
class WriteWork
Worker which will write tiles.
Public Member Functions
TileOpExecutor (final RenderedImage image, final Rectangle aoi)
Creates a new operation for tiles in the specified region of the specified image.
final boolean isMultiTiled ()
Returns.
final Rectangle getTileIndices ()
Returns the range of indices of tiles to be processed by this.
final void readFrom (final RenderedImage source)
Executes the read action sequentially on tiles of the specified source image.
final void writeTo (final WritableRenderedImage target)
Executes the write action sequentially on tiles of the specified target image.
final void parallelReadFrom (final RenderedImage source)
Executes the read action in parallel on tiles of the specified source image.
final void parallelWriteTo (final WritableRenderedImage target)
Executes the write action in parallel on tiles of the specified target image.
final< A, R > R executeOnReadable (final RenderedImage source, final Collector<? super Raster, A, R > collector, final Consumer< LogRecord > errorHandler)
Executes a specified read action in parallel on all tiles of the specified image.
final< A, R > R executeOnWritable (final WritableRenderedImage target, final Collector<? super WritableRaster, A, R > collector, final Consumer< LogRecord > errorHandler)
Executes a specified write action in parallel on all tiles of the specified image.
Protected Member Functions
void readFrom (Raster source) throws Exception
Executes the read operation on the given tile.
void writeTo (WritableRaster target) throws Exception
Executes the write operation on the given tile.
Package Attributes
final int minTileY
final int maxTileX
final int maxTileY
Static Private Member Functions
static< RT extends Raster > Collector< RT, Void, Void > executor (final BiConsumer< Void, RT > action)
Returns a collector to be used only as an executor: the accumulator is null and the combiner does nothing.
static Throwable trimImagingWrapper (Throwable ex)
If the given exception is a wrapper providing no useful information, returns its non-null cause.
Private Attributes
final int minTileX
Minimum/maximum index of tiles to process, inclusive.
Detailed Description
A read or write action to execute on each tile of an image.
The operation may be executed in a single thread or can be multi-threaded (each tile processed fully in a single thread). If the operation is to be executed in a single thread, or if the subclass is concurrent (it usually means that it does not hold any mutable state), then subclasses can override and invoke the methods in one of the following rows:
Methods to use in single-thread or with concurrent implementations
Override Then invoke (single thread) Or invoke (multi-thread)
readFrom(Raster) readFrom(RenderedImage) parallelReadFrom(RenderedImage)
writeTo(WritableRaster) writeTo(WritableRenderedImage) parallelWriteTo(WritableRenderedImage)
If the operation should be multi-threaded and produce a result, then invoke executeOnReadable(…) or executeOnWritable(…) method. Those methods are inspired from java.util.stream.Stream#collect(Collector) API.
Author
Martin Desruisseaux (Geomatys)
Version
1.1
Since
1.1
Constructor & Destructor Documentation
TileOpExecutor()
TileOpExecutor (final RenderedImage image, final Rectangle aoi)
Creates a new operation for tiles in the specified region of the specified image.
It is caller responsibility to ensure that
aoi
is contained inside
image
bounds.
Parameters
image the image from which tiles will be fetched.
aoi region of interest, or
null
for the whole image.
Exceptions
ArithmeticException if some tile indices are too large.
{
         if (aoi != null) {
             final int  tileWidth       = image.getTileWidth();
             final int  tileHeight      = image.getTileHeight();
             final long tileGridXOffset = image.getTileGridXOffset();   // We want 64 bits arithmetic in operations below.
             final long tileGridYOffset = image.getTileGridYOffset();
             minTileX = Math.toIntExact(Math.floorDiv(aoi.x                     - tileGridXOffset, tileWidth ));
             minTileY = Math.toIntExact(Math.floorDiv(aoi.y                     - tileGridYOffset, tileHeight));
             maxTileX = Math.toIntExact(Math.floorDiv(aoi.x + (aoi.width  - 1L) - tileGridXOffset, tileWidth ));
             maxTileY = Math.toIntExact(Math.floorDiv(aoi.y + (aoi.height - 1L) - tileGridYOffset, tileHeight));
         } else {
             minTileX = image.getMinTileX();
             minTileY = image.getMinTileY();
             maxTileX = Math.addExact(minTileX, image.getNumXTiles() - 1);
             maxTileY = Math.addExact(minTileY, image.getNumYTiles() - 1);
         }
     }
Member Function Documentation
executeOnReadable()
final<A,R> R executeOnReadable (final RenderedImage source, final Collector<? super Raster, A, R > collector, final Consumer< LogRecord > errorHandler)
Executes a specified read action in parallel on all tiles of the specified image.
The action is specified by 3 or 4 properties of the given
collector
:
Collector#supplier() creates a new instance of type A for each thread (those instances may be
null
if such objects are not needed). That object does not need to be thread-safe since each instance will be used by only one thread. Note however that the thread may use that object for processing any number of Raster tiles, including zero.
Collector#accumulator() provides the consumer to execute on each tile. That consumer will receive two arguments: the above-cited supplied instance of A (unique to each thread, may be
null
), and the Raster instance to process. That consumer returns no value; instead the supplied instance of A should be modified in-place if desired.
Collector#combiner() provides a function which, given two instances of A computed by two different threads, combines them in a single instance of A. This combiner will be invoked after a thread finished to process all its Raster tiles, and only if the two objects to combine are not null. This combiner does not need to be thread-safe.
Collector#finisher() is invoked exactly once in current thread after the processing of all tiles have been completed in all threads. This function converts the final value of A into the type R to be returned. It is often an identity function.
Errors management
If an error occurred during the processing of a tile, then there is a choice:
If the
errorHandler
is
null
, then all threads will finish the tiles they were processing at the time the error occurred, but will not take any other tile (i.e. remaining tiles will be left unprocessed). The exception that occurred is wrapped in an ImagingOpException and thrown.
If the
errorHandler
is non-null, then the exception is wrapped in a LogRecord and the processing continues with other tiles. If more exceptions happen, those subsequent exceptions will be added to the first one by Exception#addSuppressed(Throwable). After all tiles have been processed, the error handler will be invoked with that LogRecord. That
LogRecord
has the level, message and exception properties set, but not the source class name, source method name or logger name. The error handler should set those properties itself.
Concurrency requirements
The RenderedImage#getTile(int, int) implementation of the given image must support concurrency.
Parameters
<A> the type of the thread-local object to be given to each thread.
<R> the type of the final result. This is often the same as A.
source the image to read. This is usually the image specified at construction time, but other images are okay if they share the same pixel and tile coordinate systems.
collector the action to execute on each Raster, together with supplier and combiner of thread-local objects of type A. See above javadoc for more information.
errorHandler where to report exceptions, or
null
for throwing them.
Returns
the final result computed by finisher (may be
null
).
Exceptions
ImagingOpException if an exception occurred during RenderedImage#getTile(int, int) or readFrom(Raster) execution, and
errorHandler
is
null
.
RuntimeException if an exception occurred elsewhere (for example in the combiner or finisher).
References TileOpExecutor.ReadWork< A >.execute().
Referenced by TileOpExecutor.parallelReadFrom().
     {
         ArgumentChecks.ensureNonNull("source", source);
         ArgumentChecks.ensureNonNull("collector", collector);
         return ReadWork.execute(this, source, collector, errorHandler);
     }
executeOnWritable()
final<A,R> R executeOnWritable (final WritableRenderedImage target, final Collector<? super WritableRaster, A, R > collector, final Consumer< LogRecord > errorHandler)
Executes a specified write action in parallel on all tiles of the specified image.
The action is specified by 3 or 4 properties of the given
collector
:
Collector#supplier() creates a new instance of type A for each thread (those instances may be
null
if such objects are not needed). That object does not need to be thread-safe since each instance will be used by only one thread. Note however that the thread may use that object for processing any number of WritableRaster tiles, including zero.
Collector#accumulator() provides the consumer to execute on each tile. That consumer will receive two arguments: the above-cited supplied instance of A (unique to each thread, may be
null
), and the WritableRaster instance to process. That consumer returns no value; instead the supplied instance of A should be modified in-place if desired.
Collector#combiner() provides a function which, given two instances of A computed by two different threads, combines them in a single instance of A. This combiner will be invoked after a thread finished to process all its WritableRaster tiles, and only if the two objects to combine are not null. This combiner does not need to be thread-safe.
Collector#finisher() is invoked exactly once in current thread after the processing of all tiles have been completed in all threads. This function converts the final value of A into the type R to be returned. It is often an identity function.
Errors management
If an error occurred during the processing of a tile, the exception is remembered and the processing continues with other tiles. If more exceptions happen, those subsequent exceptions will be added to the first one by Exception#addSuppressed(Throwable). After all tiles have been processed, there is a choice:
If the
errorHandler
is
null
, the exception is wrapped in an ImagingOpException and thrown.
If the
errorHandler
is non-null, the exception is wrapped in a LogRecord and given to the handler. That
LogRecord
has the level, message and exception properties set, but not the source class name, source method name or logger name. The error handler should set those properties itself.
Concurrency requirements
The WritableRenderedImage#getWritableTile(int, int) and WritableRenderedImage#releaseWritableTile(int, int) implementations of the given image must support concurrency.
Parameters
<A> the type of the thread-local object to be given to each thread.
<R> the type of the final result. This is often the same as A.
target the image where to write. This is usually the image specified at construction time, but other images are okay if they share the same pixel and tile coordinate systems.
collector the action to execute on each WritableRaster, together with supplier and combiner of thread-local objects of type A. See above javadoc for more information.
errorHandler where to report exceptions, or
null
for throwing them.
Returns
the final result computed by finisher. This is often
null
because the purpose of calling
executeOnWritable(…)
is more often to update existing tiles instead than to compute a value.
Exceptions
ImagingOpException if an exception occurred during WritableRenderedImage#getWritableTile(int, int), writeTo(WritableRaster) or WritableRenderedImage#releaseWritableTile(int, int) execution, and
errorHandler
is
null
.
RuntimeException if an exception occurred elsewhere (for example in the combiner or finisher).
References TileOpExecutor.WriteWork< A >.execute().
Referenced by TileOpExecutor.parallelWriteTo().
     {
         ArgumentChecks.ensureNonNull("target", target);
         ArgumentChecks.ensureNonNull("collector", collector);
         return WriteWork.execute(this, target, collector, errorHandler);
     }
executor()
static <RT extends Raster> Collector<RT,Void,Void> executor (final BiConsumer< Void, RT > action) static private
Returns a collector to be used only as an executor: the accumulator is null and the combiner does nothing.
Parameters
<RT> either Raster or WritableRaster.
action the action to execute on each tile.
Returns
a collector which will merely act as an executor for the given action.
Referenced by TileOpExecutor.parallelReadFrom(), and TileOpExecutor.parallelWriteTo().
{
         return Collector.<RT,Void>of(() -> null, action, (old,ignore) -> old);
     }
getTileIndices()
final Rectangle getTileIndices ()
Returns the range of indices of tiles to be processed by this.
TileOpExecutor
.
Returns
range of tile indices to be processed.
Referenced by BandedSampleConverter.Writable.setData().
{
         return new Rectangle(minTileX, minTileY, maxTileX - minTileX + 1, maxTileY - minTileY + 1);
     }
isMultiTiled()
final boolean isMultiTiled ()
Returns.
true
if the region of interest covers at least two tiles. Returns
false
if the region of interest covers a single tile or no tile at all.
Returns
whether the operation will be executed on two tiles or more.
Referenced by TileOpExecutor.parallelReadFrom(), and TileOpExecutor.parallelWriteTo().
{
         /*
          * Following expression is negative if at least one (max - min) value is negative
          * (empty case), and 0 if all (max - min) values are zero (singleton case).
          */
         return ((maxTileX - minTileX) | (maxTileY - minTileY)) > 0;
     }
parallelReadFrom()
final void parallelReadFrom (final RenderedImage source)
Executes the read action in parallel on tiles of the specified source image.
The given source should be the same than the image specified at construction time. Only tiles intersecting the area of interest will be processed. For each tile, the readFrom(Raster) method will be invoked in an arbitrary thread (may be the current one).
Errors management
If a tile processing throws an exception, then the other threads will finish computing their current tile but no other tiles will be fetched; remaining tiles are not processed. This policy is suited to the cases where the caller will not return any result in case of error.
Concurrency requirements
Subclasses must override readFrom(Raster) with a concurrent implementation. The RenderedImage#getTile(int, int) implementation of the given image must also support concurrency.
Parameters
source the image to read. This is usually the image specified at construction time, but other images are okay if they share the same pixel and tile coordinate systems.
Exceptions
ImagingOpException if an exception occurred during RenderedImage#getTile(int, int) or readFrom(Raster) execution. This exception wraps the original exception as its ImagingOpException::getCause() cause}.
References TileOpExecutor.executeOnReadable(), TileOpExecutor.executor(), TileOpExecutor.isMultiTiled(), TileOpExecutor.readFrom(), and TileOpExecutor.Worker< RI extends RenderedImage, RT extends Raster, A >.rethrowOrWrap().
{
         if (isMultiTiled()) {
             executeOnReadable(source, executor((ignore,tile) -> {
                 try {
                     readFrom(tile);
                 } catch (Exception ex) {
                     throw Worker.rethrowOrWrap(ex);             // Will be caught again by Worker.run().
                 }
             }), null);
         } else {
             readFrom(source);
         }
     }
parallelWriteTo()
final void parallelWriteTo (final WritableRenderedImage target)
Executes the write action in parallel on tiles of the specified target image.
The given target should be the same than the image specified at construction time. Only tiles intersecting the area of interest will be processed. For each tile, the writeTo(WritableRaster) method will be invoked in an arbitrary thread (may be the current one).
Errors management
If a tile processing throws an exception, then this method continues processing other tiles and will throw the wrapper exception only after all tiles have been processed. This policy is suited to the cases where the target image will continue to exist after this method call and we want to have a relatively consistent state.
Concurrency requirements
Subclasses must override writeTo(WritableRaster) with a concurrent implementation. The WritableRenderedImage#getWritableTile(int, int) and WritableRenderedImage#releaseWritableTile(int, int) implementations of the given image must also support concurrency.
Parameters
target the image where to write. This is usually the image specified at construction time, but other images are okay if they share the same pixel and tile coordinate systems.
Exceptions
ImagingOpException if an exception occurred during WritableRenderedImage#getWritableTile(int, int), writeTo(WritableRaster) or WritableRenderedImage#releaseWritableTile(int, int) execution. This exception wraps the original exception as its ImagingOpException::getCause() cause}.
References TileOpExecutor.executeOnWritable(), TileOpExecutor.executor(), TileOpExecutor.isMultiTiled(), TileOpExecutor.Worker< RI extends RenderedImage, RT extends Raster, A >.rethrowOrWrap(), and TileOpExecutor.writeTo().
{
         if (isMultiTiled()) {
             executeOnWritable(target, executor((ignore,tile) -> {
                 try {
                     writeTo(tile);
                 } catch (Exception ex) {
                     throw Worker.rethrowOrWrap(ex);             // Will be caught again by Worker.run().
                 }
             }), null);
         } else {
             writeTo(target);
         }
     }
readFrom() [1/2]
void readFrom (Raster source) throws Exception protected
Executes the read operation on the given tile.
The default implementation does nothing. This method should be overridden if the user intends to call readFrom(RenderedImage) for execution in a single thread, or parallelReadFrom(RenderedImage) for multi-threaded execution. In the single thread case, it is okay for this method to modify some mutable states in the subclass. In the multi-thread case, the subclass implementation shall be immutable or concurrent.
Parameters
source the tile to read.
Exceptions
Exception if an error occurred while processing the tile.
Referenced by PlanarImage.copyData(), TileOpExecutor.parallelReadFrom(), and TileOpExecutor.readFrom().
{
     }
readFrom() [2/2]
final void readFrom (final RenderedImage source)
Executes the read action sequentially on tiles of the specified source image.
The given source should be the same than the image specified at construction time. Only tiles intersecting the area of interest will be processed. For each tile, the readFrom(Raster) method will be invoked in current thread.
If a tile processing throws an exception, then this method stops immediately; remaining tiles are not processed. This policy is suited to the cases where the caller will not return any result in case of error.
This method does not parallelize tile operations, because it is invoked in contexts where it should apply on exactly one tile most of the times.
Parameters
source the image to read. This is usually the image specified at construction time, but other images are okay if they share the same pixel and tile coordinate systems.
Exceptions
ImagingOpException if an exception occurred during RenderedImage#getTile(int, int) or readFrom(Raster) execution. This exception wraps the original exception as its ImagingOpException::getCause() cause}.
References TileOpExecutor.maxTileX, TileOpExecutor.maxTileY, TileOpExecutor.readFrom(), and TileOpExecutor.trimImagingWrapper().
{
         for (int ty = minTileY; ty <= maxTileY; ty++) {
             for (int tx = minTileX; tx <= maxTileX; tx++) try {
                 readFrom(source.getTile(tx, ty));
             } catch (Exception ex) {
                 Throwable e = trimImagingWrapper(ex);
                 if (!(e instanceof ImagingOpException)) {
                     e = new ImagingOpException(Resources.format(Resources.Keys.CanNotProcessTile_2, tx, ty)).initCause(ex);
                 }
                 throw (ImagingOpException) e;
             }
         }
     }
trimImagingWrapper()
static Throwable trimImagingWrapper (Throwable ex) static private
If the given exception is a wrapper providing no useful information, returns its non-null cause.
Otherwise returns the given exception, possibly Exceptions::unwrap(Exception) unwrapped}.
Referenced by TileOpExecutor.Cursor< RI, A >.finish(), TileOpExecutor.readFrom(), TileOpExecutor.Worker< WritableRenderedImage, WritableRaster, A >.run(), and TileOpExecutor.writeTo().
{
         while (ex.getClass() == ImagingOpException.class && ex.getMessage() == null && ex.getSuppressed().length == 0) {
             final Throwable cause = ex.getCause();
             if (cause == null) return ex;
             ex = cause;
         }
         if (ex instanceof Exception) {
             ex = Exceptions.unwrap((Exception) ex);
         }
         return ex;
     }
writeTo() [1/2]
void writeTo (WritableRaster target) throws Exception protected
Executes the write operation on the given tile.
The default implementation does nothing. This method should be overridden if the user intends to call writeTo(WritableRenderedImage) for execution in a single thread, or parallelWriteTo(WritableRenderedImage) for multi-threaded execution. In the single thread case, it is okay for this method to modify some mutable states in the subclass. In the multi-thread case, the subclass implementation shall be immutable or concurrent.
Parameters
target the tile where to write.
Exceptions
Exception if an error occurred while computing the values to write.
Referenced by TileOpExecutor.parallelWriteTo(), BandedSampleConverter.Writable.setData(), and TileOpExecutor.writeTo().
{
     }
writeTo() [2/2]
final void writeTo (final WritableRenderedImage target)
Executes the write action sequentially on tiles of the specified target image.
The given target should be the same than the image specified at construction time. Only tiles intersecting the area of interest will be processed. For each tile, the writeTo(WritableRaster) method will be invoked in current thread.
If a tile processing throws an exception, then this method continues processing other tiles and will throw the wrapper exception only after all tiles have been processed. This policy is suited to the cases where the target image will continue to exist after this method call and we want to have a relatively consistent state.
This method does not parallelize tile operations, because it is invoked in contexts where it should apply on exactly one tile most of the times.
Parameters
target the image where to write. This is usually the image specified at construction time, but other images are okay if they share the same pixel and tile coordinate systems.
Exceptions
ImagingOpException if an exception occurred during WritableRenderedImage#getWritableTile(int, int), writeTo(WritableRaster) or WritableRenderedImage#releaseWritableTile(int, int) execution. This exception wraps the original exception as its ImagingOpException::getCause() cause}.
References TileOpExecutor.maxTileX, TileOpExecutor.maxTileY, TileOpExecutor.trimImagingWrapper(), and TileOpExecutor.writeTo().
{
         ImagingOpException error = null;
         for (int ty = minTileY; ty <= maxTileY; ty++) {
             for (int tx = minTileX; tx <= maxTileX; tx++) try {
                 final WritableRaster tile = target.getWritableTile(tx, ty);
                 try {
                     writeTo(tile);
                 } finally {
                     target.releaseWritableTile(tx, ty);
                 }
             } catch (Exception ex) {
                 final Throwable e = trimImagingWrapper(ex);
                 if (error != null) {
                     error.addSuppressed(e);
                 } else if (e instanceof ImagingOpException) {
                     error = (ImagingOpException) e;
                 } else {
                     error = new ImagingOpException(Resources.format(Resources.Keys.CanNotUpdateTile_2, tx, ty));
                     error.initCause(e);
                 }
             }
         }
         if (error != null) {
             throw error;
         }
     }
Member Data Documentation
maxTileX
final int maxTileX package
Referenced by TileOpExecutor.readFrom(), and TileOpExecutor.writeTo().
maxTileY
final int maxTileY package
Referenced by TileOpExecutor.Cursor< RI, A >.next(), TileOpExecutor.readFrom(), and TileOpExecutor.writeTo().
minTileX
final int minTileX private
Minimum/maximum index of tiles to process, inclusive.
minTileY
final int minTileY package