jena-geo: GridCoverage Class Reference
GridCoverage Class Reference abstract
Base class of coverages with domains defined as a set of grid points.
Public Member Functions
CoordinateReferenceSystem getCoordinateReferenceSystem ()
Returns the coordinate reference system to which the values in grid domain are referenced.
GridGeometry getGridGeometry ()
Returns information about the <cite>domain</cite> of this grid coverage.
List< SampleDimension > getSampleDimensions ()
Returns information about the <cite>range</cite> of this grid coverage.
synchronized GridCoverage forConvertedValues (final boolean converted)
Returns a grid coverage that contains real values or sample values, depending if.
double [] evaluate (final DirectPosition point, final double[] buffer) throws CannotEvaluateException
Returns a sequence of double values for a given point in the coverage.
FractionalGridCoordinates toGridCoordinates (final DirectPosition point) throws TransformException
Converts the specified geospatial position to grid coordinates.
abstract RenderedImage render (GridExtent sliceExtent) throws CannotEvaluateException
Returns a two-dimensional slice of grid data as a rendered image.
String toString ()
Returns a string representation of this grid coverage for debugging purpose.
TreeTable toTree (final Locale locale, final int bitmask)
Returns a tree representation of some elements of this grid coverage.
Protected Member Functions
GridCoverage (final GridGeometry domain, final Collection<? extends SampleDimension > range)
Constructs a grid coverage using the specified grid geometry and sample dimensions.
Package Functions
final NumberRange<?> [] getRanges ()
Returns the range of values in each sample dimension, or.
final ColorModel createColorModel (final int visibleBand, final int dataType)
Creates a color model for the expected range of sample values.
final GridCoverage getView (final boolean converted)
Returns the converted or package view, or.
final void setView (final boolean converted, final GridCoverage view)
Sets the converted or package view.
void appendDataLayout (TreeTable.Node root, Vocabulary vocabulary, TableColumn< CharSequence > column)
Appends a "data layout" branch (if it exists) to the tree representation of this coverage.
Static Package Functions
static double [] evaluate (final RenderedImage data, final int x, final int y, final double[] buffer)
Gets sample values from the given image at the given index.
Package Attributes
final GridGeometry gridGeometry
The grid extent, coordinate reference system (CRS) and conversion from cell indices to CRS.
transient GridCoverage convertedView
Private Attributes
final SampleDimension [] sampleDimensions
List of sample dimension (band) information for the grid coverage.
transient GridCoverage packedView
View over this grid coverage after conversion of sample values, or.
transient volatile PointToGridCoordinates lastConverter
The last coordinate operation used by toGridCoordinates(DirectPosition).
Detailed Description
Base class of coverages with domains defined as a set of grid points.
The essential property of coverage is to be able to generate a value for any point within its domain. Since a grid coverage is represented by a grid of values, the value returned by the coverage for a point is that of the grid value whose location is nearest the point.
Author
Martin Desruisseaux (IRD, Geomatys)
Johann Sorel (Geomatys)
Version
1.1
Since
1.0
Constructor & Destructor Documentation
GridCoverage()
GridCoverage (final GridGeometry domain, final Collection<? extends SampleDimension > range) protected
Constructs a grid coverage using the specified grid geometry and sample dimensions.
The grid geometry defines the "domain" (inputs) of the coverage function, and the sample dimensions define the "range" (output) of that function.
Parameters
domain the grid extent, CRS and conversion from cell indices to CRS.
range sample dimensions for each image band.
{
         ArgumentChecks.ensureNonNull("domain", domain);
         //ArgumentChecks.ensureNonNull("range",  range);
         gridGeometry = domain;
         sampleDimensions=new SampleDimension[0];
         /*sampleDimensions = range.toArray(new SampleDimension[range.size()]);
         for (int i=0; i<sampleDimensions.length; i++) {
             ArgumentChecks.ensureNonNullElement("range", i, sampleDimensions[i]);
         }*/
     }
Member Function Documentation
appendDataLayout()
void appendDataLayout (TreeTable.Node root, Vocabulary vocabulary, TableColumn< CharSequence > column) package
Appends a "data layout" branch (if it exists) to the tree representation of this coverage.
That branch will be inserted between "coverage domain" and "sample dimensions" branches. The default implementation does nothing.
Parameters
root root of the tree where to add a branch.
vocabulary localized resources for vocabulary.
column the single column where to write texts.
Referenced by GridCoverage.toTree().
{
     }
createColorModel()
final ColorModel createColorModel (final int visibleBand, final int dataType) package
Creates a color model for the expected range of sample values.
Parameters
visibleBand the band to be made visible (usually 0). All other bands (if any) will be ignored.
dataType the color model type as one java.awt.image.DataBuffer constants.
Returns
proposed color model, or
null
if none.
References ColorModelFactory.createColorModel(), and ColorModelFactory.GRAYSCALE.
Referenced by GridCoverage2D.GridCoverage2D(), and ConvertedGridCoverage.render().
{
         return ColorModelFactory.createColorModel(sampleDimensions, visibleBand, dataType, ColorModelFactory.GRAYSCALE);
     }
evaluate() [1/2]
double [] evaluate (final DirectPosition point, final double [] buffer) throws CannotEvaluateException
Returns a sequence of double values for a given point in the coverage.
The CRS of the given point may be any coordinate reference system; coordinate transformations will be applied as needed. If the CRS of the point is undefined, then it is assumed to be the same as this coverage. The returned sequence includes a value for each SampleDimension sample dimension}.
The default interpolation type used when accessing grid values for points which fall between grid cells is nearest neighbor. This default interpolation method may change in future version.
The default implementation invokes render(GridExtent) for a small region around the point. Subclasses should override with more efficient implementation.
Warning: this method may change. See SIS-485.
Parameters
point the coordinate point where to evaluate.
buffer an array in which to store values, or
null
to create a new array.
Returns
the
buffer
array, or a newly created array if
buffer
was null.
Exceptions
PointOutsideCoverageException if the evaluation failed because the input point has invalid coordinates.
CannotEvaluateException if the values can not be computed at the specified coordinate for another reason. It may be thrown if the coverage data type can not be converted to
double
by an identity or widening conversion. Subclasses may relax this constraint if appropriate.
Since
1.1
References FractionalGridCoordinates.pointOutsideCoverage(), GridCoverage.render(), FractionalGridCoordinates.toExtent(), and GridCoverage.toGridCoordinates().
Referenced by ConvertedGridCoverage.evaluate().
{
         /*
          * TODO: instead of restricting to a single point, keep the automatic size (1 or 2),
          * invoke render for each plan, then interpolate. We would keep a value of 1 in the
          * size array if we want to disable interpolation in some particular axis (e.g. time).
          */
         final long[] size = new long[gridGeometry.getDimension()];
         java.util.Arrays.fill(size, 1);
         try {
             final FractionalGridCoordinates gc = toGridCoordinates(point);
             try {
                 final GridExtent subExtent = gc.toExtent(gridGeometry.extent, size);
                 return evaluate(render(subExtent), 0, 0, buffer);
             } catch (ArithmeticException | IndexOutOfBoundsException | DisjointExtentException ex) {
                 throw (PointOutsideCoverageException) new PointOutsideCoverageException(
                         gc.pointOutsideCoverage(gridGeometry.extent), point).initCause(ex);
             }
         } catch (PointOutsideCoverageException ex) {
             ex.setOffendingLocation(point);
             throw ex;
         } catch (RuntimeException | TransformException ex) {
             throw new CannotEvaluateException(ex.getMessage(), ex);
         }
     }
evaluate() [2/2]
static double [] evaluate (final RenderedImage data, final int x, final int y, final double [] buffer) static package
Gets sample values from the given image at the given index.
This method does not verify explicitly if the coordinates are out of bounds; we rely on the checks performed by the image and sample model implementations.
Parameters
data the data from which to get the sample values.
x column index of the value to get.
y row index of the value to get.
buffer an array in which to store values, or
null
to create a new array.
Returns
the
buffer
array, or a newly created array if
buffer
was null.
Exceptions
ArithmeticException if an integer overflow occurred while computing indices.
IndexOutOfBoundsException if a coordinate is out of bounds.
{
         final int tx = Math.toIntExact(Math.floorDiv(x - (long) data.getTileGridXOffset(), data.getTileWidth()));
         final int ty = Math.toIntExact(Math.floorDiv(y - (long) data.getTileGridYOffset(), data.getTileHeight()));
         return data.getTile(tx, ty).getPixel(x, y, buffer);
     }
forConvertedValues()
synchronized GridCoverage forConvertedValues (final boolean converted)
Returns a grid coverage that contains real values or sample values, depending if.
converted
is
true
or
false
respectively. If there is no SampleDimension::getTransferFunction() transfer function} defined by the getSampleDimensions() sample dimensions}, then this method returns
this
. In all cases, the returned grid coverage r has the following properties:
The list returned by
r.getSampleDimensions()
is equal to the list returned by this. getSampleDimensions()} with each element e replaced by e. SampleDimension::forConvertedValues(boolean) forConvertedValues}(converted).
The RenderedImage produced by
r.render(extent)
is equivalent to the image returned by this. render(GridExtent) render}(extent) with all sample values converted using the transfer function if
converted
is
true
, or the inverse of transfer function if
converted
is
false
.
Parameters
converted
References ConvertedGridCoverage.create(), GridCoverage.getView(), and GridCoverage.setView().
{
         GridCoverage view = getView(converted);
         if (view == null) try {
             view = ConvertedGridCoverage.create(this, converted);
             setView(converted, view);
         } catch (NoninvertibleTransformException e) {
             throw new CannotEvaluateException(e.getMessage(), e);
         }
         return view;
     }
getCoordinateReferenceSystem()
CoordinateReferenceSystem getCoordinateReferenceSystem ()
Returns the coordinate reference system to which the values in grid domain are referenced.
This is the CRS used when accessing a coverage with the
evaluate()
methods. This coordinate reference system is usually different than the coordinate system of the grid. It is the target coordinate reference system of the gridToCRS math transform.
The default implementation delegates to GridGeometry#getCoordinateReferenceSystem().
Returns
the CRS used when accessing a coverage with the
evaluate()
methods.
Exceptions
IncompleteGridGeometryException if the grid geometry has no CRS.
{
         return gridGeometry.getCoordinateReferenceSystem();
     }
getGridGeometry()
GridGeometry getGridGeometry ()
Returns information about the <cite>domain</cite> of this grid coverage.
Information includes the grid extent, CRS and conversion from cell indices to CRS.
GridGeometry
can also provide derived information like bounding box and resolution.
Returns
grid extent, CRS and conversion from cell indices to CRS.
See also
org.apache.sis.storage.GridCoverageResource::getGridGeometry()
References GridCoverage.gridGeometry.
Referenced by ConvertedGridCoverage.ConvertedGridCoverage(), and GridCoverage.toGridCoordinates().
{
         return gridGeometry;
     }
getRanges()
final NumberRange<?> [] getRanges () package
Returns the range of values in each sample dimension, or.
null
if none.
Referenced by ConvertedGridCoverage.render().
{
         NumberRange<?>[] ranges = null;
         for (int i=0; i<sampleDimensions.length; i++) {
             final Optional<NumberRange<?>> r = sampleDimensions[i].getSampleRange();
             if (r.isPresent()) {
                 if (ranges == null) {
                     ranges = new NumberRange<?>[sampleDimensions.length];
                 }
                 ranges[i] = r.get();
             }
         }
         return ranges;
     }
getSampleDimensions()
List<SampleDimension> getSampleDimensions ()
Returns information about the <cite>range</cite> of this grid coverage.
Information include names, sample value ranges, fill values and transfer functions for all bands in this grid coverage. The length of the returned list should be equal to the java.awt.image.SampleModel::getNumBands() number of bands} in the rendered image.
Returns
names, value ranges, fill values and transfer functions for all bands in this grid coverage.
See also
org.apache.sis.storage.GridCoverageResource::getSampleDimensions()
Referenced by ConvertedGridCoverage.create(), and GridCoverage2D.forConvertedValues().
{
         return UnmodifiableArrayList.wrap(sampleDimensions);
     }
getView()
final GridCoverage getView (final boolean converted) package
Returns the converted or package view, or.
null
if not yet computed. It is caller responsibility to ensure that this method is invoked in a synchronized block.
References GridCoverage.convertedView, and GridCoverage.packedView.
Referenced by GridCoverage.forConvertedValues(), and GridCoverage2D.forConvertedValues().
{
         return converted ? convertedView : packedView;
     }
render()
abstract RenderedImage render (GridExtent sliceExtent) throws CannotEvaluateException abstract
Returns a two-dimensional slice of grid data as a rendered image.
The given
sliceExtent
argument specifies the coordinates of the slice in all dimensions that are not in the two-dimensional image. For example if this grid coverage has (x,y,z,t) dimensions and we want to render an image of data in the (x,y) dimensions, then the given
sliceExtent
shall contain the (z,t) coordinates of the desired slice. Those coordinates are specified in a grid extent where GridExtent::getLow(int) low coordinate} = GridExtent::getHigh(int) high coordinate} in the z and t dimensions. The two dimensions of the data to be shown (x and y in our example) shall be the only dimensions having a GridExtent::getSize(int) size} greater than 1 cell.
If the
sliceExtent
argument is
null
, then the default value is getGridGeometry()}. GridGeometry::getExtent() getExtent()}. This means that
gridExtent
is optional for two-dimensional grid coverages or grid coverages where all dimensions except two have a size of 1 cell. If the grid extent contains more than 2 dimensions with a size greater than one cell, then a SubspaceNotSpecifiedException is thrown.
How to compute a slice extent from a slice point in "real world" coordinates
The
sliceExtent
is specified to this method as grid indices. If the z and t values are not grid indices but are relative to some Coordinate Reference System (CRS) instead, then the slice extent can be computed as below. First, a <cite>slice point</cite> containing the z and t coordinates should be constructed as a DirectPosition in one of the following ways:
The
slicePoint
has a CRS with two dimensions less than this grid coverage CRS.
The
slicePoint
has the same CRS than this grid coverage, but the two coordinates to exclude are set to Double#NaN.
Then:
sliceExtent = getGridGeometry()}.derive(). GridDerivation::slice(DirectPosition) slice}(slicePoint). GridDerivation::getIntersection() getIntersection()};
If the
slicePoint
CRS is different than this grid coverage CRS (except for the number of dimensions), a coordinate transformation will be applied as needed.
Characteristics of the returned image
Image dimensions x and y map to the first and second dimension respectively of the two-dimensional
sliceExtent
GridExtent::getSubspaceDimensions(int) subspace}. The coordinates given by RenderedImage#getMinX() and getMinY() will be the image location relative to the location specified in
sliceExtent
GridExtent::getLow(int) low coordinates}. For example in the case of image RenderedImage::getMinX() minimum X coordinate}:
A value of 0 means that the image left border is exactly where requested by
sliceExtent.getLow(xDimension)
.
A positive value means that the returned image is shifted to the right compared to specified extent. This implies that the image has less data than requested on left side. It may happen if the specified extent is partially outside grid coverage extent.
A negative value means that the returned image is shifted to the left compared to specified extent. This implies that the image has more data than requested on left side. It may happen if the image is tiled, the specified
sliceExtent
covers many tiles, and expanding the specified extent is necessary for returning an integer amount of tiles.
Similar discussion applies to the RenderedImage::getMinY() minimum Y coordinate}. The RenderedImage::getWidth() image width} and RenderedImage::getHeight() height} will be the
sliceExtent
GridExtent::getSize(int) sizes} if this method can honor exactly the request, or otherwise may be adjusted for the same reasons than x and y location discussed above.
Implementations should return a view as much as possible, without copying sample values.
GridCoverage
subclasses can use the ImageRenderer class as a helper tool for that purpose. This method does not mandate any behavior regarding tiling (size of tiles, their numbering system, etc.). Some implementations may defer data loading until RenderedImage::getTile(int, int) a tile is requested}.
Parameters
sliceExtent a subspace of this grid coverage extent where all dimensions except two have a size of 1 cell. May be
null
if this grid coverage has only two dimensions with a size greater than 1 cell.
Returns
the grid slice as a rendered image. Image location is relative to
sliceExtent
.
Exceptions
SubspaceNotSpecifiedException if the given argument is not sufficient for reducing the grid to a two-dimensional slice.
DisjointExtentException if the given extent does not intersect this grid coverage.
CannotEvaluateException if this method can not produce the rendered image for another reason.
Referenced by GridCoverage.evaluate(), ConvertedGridCoverage.render(), and GridCoverage.toGridCoordinates().
setView()
final void setView (final boolean converted, final GridCoverage view) package
Sets the converted or package view.
The given view should not be null. It is caller responsibility to ensure that this method is invoked in a synchronized block.
Referenced by GridCoverage.forConvertedValues(), and GridCoverage2D.forConvertedValues().
{
         if (converted) {
             convertedView = view;
         } else {
             packedView = view;
         }
     }
toGridCoordinates()
FractionalGridCoordinates toGridCoordinates (final DirectPosition point) throws TransformException
Converts the specified geospatial position to grid coordinates.
If the given position is associated to a non-null coordinate reference system (CRS) different than the CRS of this coverage, then this method automatically transforms that position to the getCoordinateReferenceSystem() coverage CRS} before to compute grid coordinates.
This method does not put any restriction on the grid coordinates result. The result may be outside the GridGeometry::getExtent() grid extent} if the GridGeometry::getGridToCRS(PixelInCell) grid to CRS} transform allows it.
Parameters
point geospatial coordinates (in arbitrary CRS) to transform to grid coordinates.
Returns
the grid coordinates for the given geospatial coordinates.
Exceptions
IncompleteGridGeometryException if the getGridGeometry() grid geometry} does not define a "grid to CRS" transform, or if the given point has a non-null CRS but this coverage does not getCoordinateReferenceSystem() have a CRS}.
TransformException if the given coordinates can not be transformed.
See also
FractionalGridCoordinates::toPosition(MathTransform)
Since
1.1
References PointToGridCoordinates.crsToGrid, FractionalGridCoordinates.fromPosition(), GridCoverage.getGridGeometry(), GridCoverage.lastConverter, GridCoverage.render(), and PointToGridCoordinates.sourceCRS.
Referenced by GridCoverage.evaluate(), and GridCoverage2D.evaluate().
{
         final CoordinateReferenceSystem sourceCRS = point.getCoordinateReferenceSystem();
         PointToGridCoordinates converter = lastConverter;
         if (converter == null || !Objects.equals(converter.sourceCRS, sourceCRS)) {
             converter = new PointToGridCoordinates(sourceCRS, this, getGridGeometry());
             lastConverter = converter;
         }
         return FractionalGridCoordinates.fromPosition(point, converter.crsToGrid);
     }
toString()
String toString ()
Returns a string representation of this grid coverage for debugging purpose.
The returned string is implementation dependent and may change in any future version. Current implementation is equivalent to the following, where
<default flags>
is the same set of flags than GridGeometry#toString().
{ java return toTree(Locale.getDefault(), <default flags>="">).toString(); }
Returns
a string representation of this grid coverage for debugging purpose.
References GridCoverage.toTree().
{
         return toTree(Locale.getDefault(), GridGeometry.defaultFlags()).toString();
     }
toTree()
TreeTable toTree (final Locale locale, final int bitmask)
Returns a tree representation of some elements of this grid coverage.
The tree representation is for debugging purpose only and may change in any future SIS version.
Parameters
locale the locale to use for textual labels.
bitmask combination of GridGeometry flags.
Returns
a tree representation of the specified elements.
See also
GridGeometry::toTree(Locale, int)
References GridCoverage.appendDataLayout().
Referenced by GridCoverage.toString().
{
         ArgumentChecks.ensureNonNull("locale", locale);
         final Vocabulary vocabulary = Vocabulary.getResources(locale);
         final TableColumn<CharSequence> column = TableColumn.VALUE_AS_TEXT;
         final TreeTable tree = new DefaultTreeTable(column);
         final TreeTable.Node root = tree.getRoot();
         root.setValue(column, Classes.getShortClassName(this));
         TreeTable.Node branch = root.newChild();
         branch.setValue(column, vocabulary.getString(Vocabulary.Keys.CoverageDomain));
         gridGeometry.formatTo(locale, vocabulary, bitmask, branch);
         appendDataLayout(root, vocabulary, column);
         branch = root.newChild();
         branch.setValue(column, vocabulary.getString(Vocabulary.Keys.SampleDimensions));
         branch.newChild().setValue(column, SampleDimension.toString(locale, sampleDimensions));
         return tree;
     }
Member Data Documentation
convertedView
transient GridCoverage convertedView package
Referenced by GridCoverage.getView().
gridGeometry
final GridGeometry gridGeometry package
The grid extent, coordinate reference system (CRS) and conversion from cell indices to CRS.
See also
getGridGeometry()
Referenced by GridCoverage2D.evaluate(), GridCoverage.getGridGeometry(), GridCoverage2D.getGridGeometry2D(), GridCoverage2D.GridCoverage2D(), and GridCoverage2D.render().
lastConverter
transient volatile PointToGridCoordinates lastConverter private
The last coordinate operation used by toGridCoordinates(DirectPosition).
This is cached for avoiding the costly process of fetching a coordinate operation in the common case where the coordinate reference systems did not changed.
Referenced by GridCoverage.toGridCoordinates().
packedView
transient GridCoverage packedView private
View over this grid coverage after conversion of sample values, or.
null
if not yet created. May be
this
if we determined that there is no conversion or the conversion is identity.
See also
forConvertedValues(boolean)
Referenced by GridCoverage.getView().
sampleDimensions
final SampleDimension [] sampleDimensions private
List of sample dimension (band) information for the grid coverage.
Information include such things as description, the no data values, minimum and maximum values, etc. A coverage must have at least one sample dimension. The content of this array shall never be modified.
See also
getSampleDimensions()