jena-geo: ImageDimension Class Reference
ImageDimension Class Reference
An image dimension, including the number of bands.
Public Member Functions
ImageDimension (final RenderedImage image)
Creates a new dimension initialized to the dimension of the given image.
ImageDimension (final Raster raster)
Creates a new dimension initialized to the dimension of the given raster.
long getNumSampleValues ()
Returns the number of sample values.
long getMemoryUsage ()
Returns the number of bytes required in order to memorize getNumSampleValues all sample values}.
boolean equals (final Object object)
Checks whether two dimension objects have equal values.
int hashCode ()
Returns the hash code for this dimension.
String toString ()
Returns a string representation of this dimension.
Public Attributes
int numBands
The number of bands in the image or raster.
Private Attributes
final int dataType
The image data type.
Static Private Attributes
static final long serialVersionUID = -4349573462196081362L
For compatibility between different version of this class.
Detailed Description
An image dimension, including the number of bands.
Author
Martin Desruisseaux (Geomatys)
Version
3.00
Since
2.4
Constructor & Destructor Documentation
ImageDimension() [1/2]
ImageDimension (final RenderedImage image)
Creates a new dimension initialized to the dimension of the given image.
Parameters
image The image from which to fetch the dimensions.
Referenced by ImageDimension.equals().
{
         super(image.getWidth(), image.getHeight());
         final SampleModel model = image.getSampleModel();
         numBands = model.getNumBands();
         dataType = model.getDataType();
     }
ImageDimension() [2/2]
ImageDimension (final Raster raster)
Creates a new dimension initialized to the dimension of the given raster.
Parameters
raster The raster from which to fetch the dimensions.
{
         super(raster.getWidth(), raster.getHeight());
         numBands = raster.getNumBands();
         dataType = raster.getDataBuffer().getDataType();
     }
Member Function Documentation
equals()
boolean equals (final Object object)
Checks whether two dimension objects have equal values.
Parameters
object The object to compare with this dimension for equality.
References ImageDimension.dataType, ImageDimension.ImageDimension(), and ImageDimension.numBands.
{
         if (!super.equals(object)) {
             return false;
         }
         if (object instanceof ImageDimension) {
             final ImageDimension that = (ImageDimension) object;
             return this.numBands == that.numBands && this.dataType == that.dataType;
         }
         return true; // For preserving reflexivity.
     }
getMemoryUsage()
long getMemoryUsage ()
Returns the number of bytes required in order to memorize getNumSampleValues all sample values}.
The sample values size is determined by the image or raster given at construction time.
Returns
The number bytes requires for storing the image.
References ImageDimension.getNumSampleValues().
{
         return getNumSampleValues() * (DataBuffer.getDataTypeSize(dataType) / Byte.SIZE);
     }
getNumSampleValues()
long getNumSampleValues ()
Returns the number of sample values.
This is the product of width, height and numBands.
Returns
The number of sample values.
References ImageDimension.numBands.
Referenced by ImageDimension.getMemoryUsage().
{
         return (long) width * (long) height * (long) numBands;
     }
hashCode()
int hashCode ()
Returns the hash code for this dimension.
References ImageDimension.numBands.
{
         return super.hashCode() + 31*numBands;
     }
toString()
String toString ()
Returns a string representation of this dimension.
{
         return Classes.getShortClassName(this) +
                 "[width=" + width + ", height=" + height + ", numBands=" + numBands + ']';
     }
Member Data Documentation
dataType
final int dataType private
The image data type.
Referenced by ImageDimension.equals().
numBands
int numBands
The number of bands in the image or raster.
Referenced by ImageDimension.equals(), ImageDimension.getNumSampleValues(), and ImageDimension.hashCode().
serialVersionUID
final long serialVersionUID = -4349573462196081362L static private
For compatibility between different version of this class.