jena-geo: NamedTreeNode Class Reference
NamedTreeNode Class Reference
A tree node with a name which may be different than the #userObject user object}.
Public Member Functions
NamedTreeNode (final CharSequence name)
Creates a tree node that has no parent and no children, but which allows children.
NamedTreeNode (final CharSequence name, final Object userObject)
Creates a tree node with no parent, no children, but which allows children, and initializes it with the specified user object.
NamedTreeNode (final CharSequence name, Object userObject, boolean allowsChildren)
Creates a tree node with no parent, no children, initialized with the specified user object, and that allows children only if specified.
CharSequence getName ()
Returns the name of this node as an instance of String or InternationalString.
void setName (final CharSequence name)
Sets the name of this node.
String toString ()
Returns the name given at construction time.
Locale getLocale ()
Returns the locale to use for the value returned by toString().
Object getUserObject ()
Returns this node's user object.
Enumeration<? extends javax.swing.tree.TreeNode > children ()
Returns the children of this node as an.
Static Private Member Functions
static CharSequence freeze (final CharSequence name)
Ensures that the given name is either an instance of InternationalString, String or.
Private Attributes
CharSequence name
The node label to be returned by toString().
Static Private Attributes
static final long serialVersionUID = -5052321314347001298L
Serial number for compatibility with different versions.
Detailed Description
A tree node with a name which may be different than the #userObject user object}.
Because the javax.swing.JTree component invokes the toString() method for populating the tree widget, this class is useful when the label to display is different than the value of
userObject.toString()
.
{
}
Every constructors in this class expect a name of type CharSequence. The names are typically instances of String, but instances of InternationalString are also accepted. In the later case, the toString() method may return a localized string depending on the return value of the getLocale() method. By default, the later is the locale of the #getParent() parent} node.
Author
Martin Desruisseaux (IRD, Geomatys)
Version
3.17
Since
2.0
Constructor & Destructor Documentation
NamedTreeNode() [1/3]
NamedTreeNode (final CharSequence name)
Creates a tree node that has no parent and no children, but which allows children.
Parameters
name The node name to be returned by toString().
References NamedTreeNode.freeze().
{
         super();
         this.name = freeze(name);
     }
NamedTreeNode() [2/3]
NamedTreeNode (final CharSequence name, final Object userObject)
Creates a tree node with no parent, no children, but which allows children, and initializes it with the specified user object.
Parameters
name The node name to be returned by toString().
userObject an Object provided by the user that constitutes the node's data
References NamedTreeNode.freeze().
{
         super(userObject);
         this.name = freeze(name);
     }
NamedTreeNode() [3/3]
NamedTreeNode (final CharSequence name, Object userObject, boolean allowsChildren)
Creates a tree node with no parent, no children, initialized with the specified user object, and that allows children only if specified.
Parameters
name The node name to be returned by toString().
userObject an Object provided by the user that constitutes the node's data
allowsChildren if true, the node is allowed to have child nodes. Otherwise, it is always a leaf node
References NamedTreeNode.freeze().
{
         super(userObject, allowsChildren);
         this.name = freeze(name);
     }
Member Function Documentation
children()
Enumeration<? extends javax.swing.tree.TreeNode> children () inherited
Returns the children of this node as an.
Enumeration
.
Returns
The children.
Referenced by Trees.copy(), and TreeFormat.hasTreeTableNode().
freeze()
static CharSequence freeze (final CharSequence name) static private
Ensures that the given name is either an instance of InternationalString, String or.
null
. This is mostly a safety against change of StringBuilder content.
References NamedTreeNode.name.
Referenced by NamedTreeNode.NamedTreeNode(), and NamedTreeNode.setName().
{
         if (name == null || name instanceof InternationalString) {
             return name;
         }
         return name.toString();
     }
getLocale()
Locale getLocale () inherited
Returns the locale to use for the value returned by toString().
The default implementation returns the locale of the #getParent() parent}, if any, or
null
otherwise.
Since
3.17
Referenced by NamedTreeNode.toString().
{
         javax.swing.tree.TreeNode parent = getParent();
         while (parent != null) {
             if (parent instanceof org.apache.sis.util.Localized) {
                 return ((org.apache.sis.util.Localized) parent).getLocale();
             }
             parent = parent.getParent();
         }
         return null;
     }
getName()
CharSequence getName ()
Returns the name of this node as an instance of String or InternationalString.
Returns
The name, or
null
if none.
Since
3.17
References NamedTreeNode.name.
{
         return name;
     }
getUserObject()
Object getUserObject () inherited
Returns this node's user object.
Returns
the Object stored at this node by the user
setName()
void setName (final CharSequence name)
Sets the name of this node.
While this method accepts null value (because Swing javax.swing.tree.DefaultMutableTreeNode#toString() is designed that way), it is highly recommended to set only non-null values.
Parameters
name The new name of this node.
Since
3.17
References NamedTreeNode.freeze().
{
         this.name = freeze(name);
     }
toString()
String toString ()
Returns the name given at construction time.
If that name is an instance of InternationalString and the getLocale() method returns a non-null value, then the InternationalString#toString(Locale) value is returned.
Implements TreeNode.
References DefaultMutableTreeNode.getLocale(), and NamedTreeNode.name.
{
         if (name instanceof InternationalString) {
             final Locale locale = getLocale();
             return (locale != null) ? ((InternationalString) name).toString(locale) : name.toString();
         }
         return (String) name; // May be null.
     }
Member Data Documentation
name
CharSequence name private
The node label to be returned by toString().
Referenced by NamedTreeNode.freeze(), NamedTreeNode.getName(), and NamedTreeNode.toString().
serialVersionUID
final long serialVersionUID = -5052321314347001298L static private
Serial number for compatibility with different versions.