jena-geo: Factories Class Reference
Factories Class Reference
Static methods relative to the factories.
Static Public Member Functions
static synchronized void addChangeListener (final ChangeListener listener)
Adds the specified listener to the list of objects to inform when a system-wide configuration changed.
static synchronized void removeChangeListener (final ChangeListener listener)
Removes the specified listener from the list of objects to inform when a system-wide configuration changed.
static< T > Iterator< T > orderForClassLoader (final ClassLoader classLoader, final Iterator< T > iterator)
Returns an iterator giving precedence to classes loaded by the given class loader or one of its parents/children.
static CRSAuthorityFactory getCRSAuthorityFactory (final String authority) throws FactoryRegistryException
static CoordinateOperationAuthorityFactory getCoordinateOperationAuthorityFactory (final String authority) throws FactoryRegistryException
Static Package Functions
static void fireConfigurationChanged (final Class<?> source)
Informs every listeners that a system-wide configuration changed.
Private Member Functions
Factories ()
Do not allow instantiation of this class.
Static Private Member Functions
static< T extends AuthorityFactory > T getAuthorityFactory (final Class< T > category, final String authority, final Hints.ClassKey key) throws FactoryRegistryException
Returns the first implementation of a factory matching the specified hints.
Static Private Attributes
static ChangeListener [] listeners
Object to inform about hints changes.
Detailed Description
Static methods relative to the factories.
There are many aspects in the way Geotk manages factories on a system-wide basis:
Default settings: They are handled as the default hint values set on a system-wide basis by Hints.get/put/removeSystemDefault methods. The default values can be provided in application code.
Integration plugins: If hosting Geotk in a alternate plugin system such as Spring or OSGi, application may needs to register additional "Factory Iterators" for Geotk to search using the addFactoryIteratorProvider method.
Author
Martin Desruisseaux (IRD, Geomatys)
Jody Garnett (Refractions)
Version
3.20
Since
2.4
Deprecated:
Will be replaced by a more standard dependency injection mechanism.
Constructor & Destructor Documentation
Factories()
Factories () private
Do not allow instantiation of this class.
{
     }
Member Function Documentation
addChangeListener()
static synchronized void addChangeListener (final ChangeListener listener) static
Adds the specified listener to the list of objects to inform when a system-wide configuration changed.
The methods which may fire a ChangeEvent change event} are:
Hints#putSystemDefault(RenderingHints.Key, Object)
Hints#removeSystemDefault(RenderingHints.Key)
addFactoryIteratorProvider(FactoryIteratorProvider)
removeFactoryIteratorProvider(FactoryIteratorProvider)
Parameters
listener The listener to add.
References Listeners.addListener().
{
         listeners = Listeners.addListener(listener, listeners);
     }
fireConfigurationChanged()
static void fireConfigurationChanged (final Class<?> source) static package
Informs every listeners that a system-wide configuration changed.
This method is invoked by the static methods that are annotated with Configuration. Users should not need to invoke this method themselves.
Parameters
source The source of this event.
References Listeners.fireChanged(), and Factories.listeners.
Referenced by Hints.putSystemDefault(), and Hints.removeSystemDefault().
{
         final ChangeListener[] list;
         synchronized (Factories.class) {
             list = listeners;
         }
         Listeners.fireChanged(source, list);
     }
getAuthorityFactory()
static <T extends AuthorityFactory> T getAuthorityFactory (final Class< T > category, final String authority, final Hints.ClassKey key) throws FactoryRegistryException static private
Returns the first implementation of a factory matching the specified hints.
If no implementation matches, a new one is created if possible or an exception is thrown otherwise. If more than one implementation is registered and an #setVendorOrdering ordering is set}, then the preferred implementation is returned. Otherwise an arbitrary one is selected.
Parameters
category The authority factory type.
authority The desired authority (e.g. "EPSG").
key The hint key to use for searching an implementation.
Returns
The first authority factory that matches the supplied hints.
Exceptions
FactoryRegistryException if no implementation was found or can be created for the specified interface.
Referenced by Factories.getCoordinateOperationAuthorityFactory(), and Factories.getCRSAuthorityFactory().
     {
         try {
             return ((MultiAuthoritiesFactory) CRS.getAuthorityFactory(null)).getAuthorityFactory(category, authority, null);
         } catch (FactoryException e) {
             throw new FactoryRegistryException(e.getMessage(), e);
         }
     }
getCoordinateOperationAuthorityFactory()
static CoordinateOperationAuthorityFactory getCoordinateOperationAuthorityFactory (final String authority) throws FactoryRegistryException static
References Hints.COORDINATE_OPERATION_AUTHORITY_FACTORY, and Factories.getAuthorityFactory().
     {
         return getAuthorityFactory(CoordinateOperationAuthorityFactory.class, authority,
                 Hints.COORDINATE_OPERATION_AUTHORITY_FACTORY);
     }
getCRSAuthorityFactory()
static CRSAuthorityFactory getCRSAuthorityFactory (final String authority) throws FactoryRegistryException static
References Hints.CRS_AUTHORITY_FACTORY, and Factories.getAuthorityFactory().
     {
         return getAuthorityFactory(CRSAuthorityFactory.class, authority, Hints.CRS_AUTHORITY_FACTORY);
     }
orderForClassLoader()
static <T> Iterator<T> orderForClassLoader (final ClassLoader classLoader, final Iterator< T > iterator) static
Returns an iterator giving precedence to classes loaded by the given class loader or one of its parents/children.
This method is used as a safety when there is a risk that many copies of the same library (for example in a web container) register the same JDK service.
{
}
The
geotk-coverageio
module defines new javax.imageio.ImageReader implementations, which are automatically discovered by the standard JDK through the
META-INF/services/
mechanism. If a web container contains two copies of the Geotoolkit.org library - one for each web application - then all image formats like org.geotoolkit.image.io.plugin.NetcdfImageReader will be registered twice, because the JVM will find two
NetcdfImageReader.Spi
classes loaded by two different class loaders.
The service provider instance returned by javax.imageio.spi.IIORegistry may be somewhat random in the above scenario. This leads to subtle and hard-to-identify bugs. This method reduces the risk by giving precedence to SPI classes loaded by the same class loader than the application. However users are still encouraged to load, for each running JVM, only one copy of the Geotoolkit.org library to be shared by all applications.
Parameters
<T> The type of elements in the iterator.
classLoader The desired class loader, or
null
for the bootstrap class loader.
iterator The iterator to wrap.
Returns
An iterator giving precedences to classes loaded by the given class loader or one of its parents/children.
Since
3.20
{
         if (classLoader == null || iterator == null || (iterator instanceof OrderedIterator<?> &&
                 ((OrderedIterator<?>) iterator).classLoader == classLoader))
         {
             return iterator;
         }
         return new OrderedIterator<>(classLoader, iterator);
     }
removeChangeListener()
static synchronized void removeChangeListener (final ChangeListener listener) static
Removes the specified listener from the list of objects to inform when a system-wide configuration changed.
Parameters
listener The listener to remove.
References Listeners.removeListener().
{
         listeners = Listeners.removeListener(listener, listeners);
     }
Member Data Documentation
listeners
ChangeListener [] listeners static private
Object to inform about hints changes.
We use the Swing utility listener list since it is lightweight and thread-safe. Note that it doesn't involve any dependency to the remaining of Swing library. (Note: this assumption may change with JDK8 modularization)
Referenced by Factories.fireConfigurationChanged().