jena-geo: BufferedImages Class Reference
BufferedImages Class Reference
Static Public Member Functions
static BufferedImage createImage (final int width, final int height, RenderedImage reference) throws IllegalArgumentException
Create a new image of the same type with a different size.
static BufferedImage createImage (final int width, final int height, final int nbBand, final int dataType) throws IllegalArgumentException
static WritableRaster createRaster (int width, int height, int nbBand, int dataType, Point upperLeft) throws IllegalArgumentException
static ColorModel createGrayScaleColorModel (int dataType, int nbBand, int visibleBand, double min, double max)
static DataBuffer toDataBuffer (Object data) throws IllegalArgumentException
Convert a primitive array to a DataBuffer.
static boolean isAll (RenderedImage img, double[] pixel)
Compare the pixles of given image to reference pixel and return true if all pixels share those same samples.
static void setAll (WritableRenderedImage img, double[] pixel)
Detailed Description
Author
Johann Sorel (Geomatys)
Member Function Documentation
createGrayScaleColorModel()
static ColorModel createGrayScaleColorModel (int dataType, int nbBand, int visibleBand, double min, double max) static
Referenced by BufferedImages.createImage().
{
         final ColorSpace colors = ColorModelFactory.createColorSpace(nbBand, visibleBand, min, max);
         final ColorModel cm = new ComponentColorModel(colors, false, false, Transparency.OPAQUE, dataType);
         return cm;
     }
createImage() [1/2]
static BufferedImage createImage (final int width, final int height, RenderedImage reference) throws IllegalArgumentException static
Create a new image of the same type with a different size.
Parameters
width
height
reference
Returns
Exceptions
IllegalArgumentException
{
         final WritableRaster raster = reference.getTile(0, 0).createCompatibleWritableRaster(width, height);
         final ColorModel cm = reference.getColorModel();
         final BufferedImage resultImage = new BufferedImage(cm,raster,cm.isAlphaPremultiplied(),new Hashtable<>());
         return resultImage;
     }
createImage() [2/2]
static BufferedImage createImage (final int width, final int height, final int nbBand, final int dataType) throws IllegalArgumentException static
References BufferedImages.createGrayScaleColorModel(), and BufferedImages.createRaster().
{
         final Point upperLeft = new Point(0,0);
         final WritableRaster raster = createRaster(width, height, nbBand, dataType, upperLeft);
         //TODO try to reuse java colormodel if possible
         //create a temporary fallback colormodel which will always work
         //extract grayscale min/max from sample dimension
         final ColorModel graycm = createGrayScaleColorModel(dataType,nbBand,0,0,1);
         final BufferedImage resultImage = new BufferedImage(graycm, raster, false, new Hashtable<>());
         return resultImage;
     }
createRaster()
static WritableRaster createRaster (int width, int height, int nbBand, int dataType, Point upperLeft) throws IllegalArgumentException static
Referenced by BufferedImages.createImage().
{
         final WritableRaster raster;
         if(nbBand == 1){
             if(dataType == DataBuffer.TYPE_BYTE || dataType == DataBuffer.TYPE_USHORT || dataType == DataBuffer.TYPE_INT){
                 raster = WritableRaster.createBandedRaster(dataType, width, height, nbBand, upperLeft);
             }else{
                 //create it ourself
                 final DataBuffer buffer;
                 if(dataType == DataBuffer.TYPE_SHORT) buffer = new DataBufferShort(width*height);
                 else if(dataType == DataBuffer.TYPE_FLOAT) buffer = new DataBufferFloat(width*height);
                 else if(dataType == DataBuffer.TYPE_DOUBLE) buffer = new DataBufferDouble(width*height);
                 else throw new IllegalArgumentException("Type not supported "+dataType);
                 final int[] zero = new int[1];
                 //TODO create our own raster factory to avoid JAI
                 raster = RasterFactory.createBandedRaster(buffer, width, height, width, zero, zero, upperLeft);
             }
         }else{
             if(dataType == DataBuffer.TYPE_BYTE || dataType == DataBuffer.TYPE_USHORT){
                 raster = WritableRaster.createInterleavedRaster(dataType, width, height, nbBand, upperLeft);
             }else{
                 //create it ourself
                 final DataBuffer buffer;
                 if(dataType == DataBuffer.TYPE_SHORT) buffer = new DataBufferShort(width*height*nbBand);
                 else if(dataType == DataBuffer.TYPE_INT) buffer = new DataBufferInt(width*height*nbBand);
                 else if(dataType == DataBuffer.TYPE_FLOAT) buffer = new DataBufferFloat(width*height*nbBand);
                 else if(dataType == DataBuffer.TYPE_DOUBLE) buffer = new DataBufferDouble(width*height*nbBand);
                 else throw new IllegalArgumentException("Type not supported "+dataType);
                 final int[] bankIndices = new int[nbBand];
                 final int[] bandOffsets = new int[nbBand];
                 for(int i=1;i<nbBand;i++){
                     bandOffsets[i] = bandOffsets[i-1] + width*height;
                 }
                 //TODO create our own raster factory to avoid JAI
                 raster = RasterFactory.createBandedRaster(buffer, width, height, width, bankIndices, bandOffsets, upperLeft);
             }
         }
         return raster;
     }
isAll()
static boolean isAll (RenderedImage img, double [] pixel) static
Compare the pixles of given image to reference pixel and return true if all pixels share those same samples.
Parameters
img image to test
pixel reference pixel to compare with
Returns
true if all pixels is image are equal to reference pixel.
{
         final PixelIterator ite = PixelIterator.create(img);
         final double[] buffer = new double[pixel.length];
         while (ite.next()) {
             ite.getPixel(buffer);
             if (!Arrays.equals(pixel, buffer)) {
                 return false;
             }
         }
         return true;
     }
setAll()
static void setAll (WritableRenderedImage img, double [] pixel) static
{
         final WritablePixelIterator ite = WritablePixelIterator.create(img);
         while (ite.next()) {
             ite.setPixel(pixel);
         }
     }
toDataBuffer()
static DataBuffer toDataBuffer (Object data) throws IllegalArgumentException static
Convert a primitive array to a DataBuffer.
This DataBuffer can then be used to create a WritableRaster.
The array is directly used by the buffer, they are not copied.
Parameters
data primitive array object with 1 or 2 dimensions.
Returns
DataBuffer never null
Exceptions
IllegalArgumentException if the array type is not supported.
{
         if(data instanceof byte[]){
             return new DataBufferByte((byte[])data,Array.getLength(data));
         }else if(data instanceof short[]){
             return new DataBufferShort((short[])data,Array.getLength(data));
         }else if(data instanceof int[]){
             return new DataBufferInt((int[])data,Array.getLength(data));
         }else if(data instanceof float[]){
             return new DataBufferFloat((float[])data,Array.getLength(data));
         }else if(data instanceof double[]){
             return new DataBufferDouble((double[])data,Array.getLength(data));
         }
         else if(data instanceof byte[][]){
             return new DataBufferByte((byte[][])data,Array.getLength(Array.get(data, 0)));
         }else if(data instanceof short[][]){
             return new DataBufferShort((short[][])data,Array.getLength(Array.get(data, 0)));
         }else if(data instanceof int[][]){
             return new DataBufferInt((int[][])data,Array.getLength(Array.get(data, 0)));
         }else if(data instanceof float[][]){
             return new DataBufferFloat((float[][])data,Array.getLength(Array.get(data, 0)));
         }else if(data instanceof double[][]){
             return new DataBufferDouble((double[][])data,Array.getLength(Array.get(data, 0)));
         }
         else{
             throw new IllegalArgumentException("Unexpected array type "+data.getClass());
         }
     }