jena-geo: Hints Class Reference
Hints Class Reference
A set of hints providing control on factories to be used.
Classes
class ClassKey
A key for value that may be specified either as instance of.
class DataSourceKey
Key for hints to be specified as a javax.sql.DataSource.
class FileKey
Key for hints to be specified as a Path.
class IntegerKey
A hint used to capture a configuration setting as an integer.
class Key
The type for keys used to control various aspects of the factory creation.
class OptionKey
Key that allows the choice of several options.
Public Member Functions
Hints ()
Constructs a map of hints initialized with the system-wide default values.
Hints (final RenderingHints.Key key, final Object value)
Constructs a new map of hints with the specified key/value pair.
Hints (final RenderingHints.Key key1, final Object value1, final RenderingHints.Key key2, final Object value2)
Constructs a new map of hints with two key/value pairs.
Hints (final RenderingHints.Key key1, final Object value1, final RenderingHints.Key key2, final Object value2, final Object... pairs)
Constructs a new map of hints from key/value pairs.
Hints (final Map<? extends RenderingHints.Key, ?> hints)
Constructs a new object with keys and values from the given map (which may be null).
Hints (final RenderingHints hints)
Constructs a new object with keys and values from the given map (which may be null).
Hints clone ()
Returns a new map of hints with the same content than this map.
String toString ()
Returns a string representation of the hints.
Static Public Member Functions
static Object getSystemDefault (final RenderingHints.Key key)
Returns the system-wide default value for the given key.
static Object putSystemDefault (final RenderingHints.Key key, final Object value)
Adds or modifies a system-wide default value.
static Object removeSystemDefault (final RenderingHints.Key key)
Removes the specified hints from the set of system default values.
Static Public Attributes
static final ClassKey NAME_FACTORY
static final ClassKey CITATION_FACTORY
static final ClassKey CRS_AUTHORITY_FACTORY
static final ClassKey CS_AUTHORITY_FACTORY
static final ClassKey DATUM_AUTHORITY_FACTORY
static final ClassKey CRS_FACTORY
static final ClassKey CS_FACTORY
static final ClassKey DATUM_FACTORY
static final ClassKey COORDINATE_OPERATION_FACTORY
static final ClassKey COORDINATE_OPERATION_AUTHORITY_FACTORY
static final ClassKey MATH_TRANSFORM_FACTORY
static final Key DEFAULT_COORDINATE_REFERENCE_SYSTEM
static final FileKey CRS_AUTHORITY_EXTRA_DIRECTORY = new FileKey(false)
static final Key EPSG_DATA_SOURCE = new DataSourceKey()
static final OptionKey DATUM_SHIFT_METHOD
static final Key LENIENT_DATUM_SHIFT = new Key(Boolean.class)
static final Key FORCE_LONGITUDE_FIRST_AXIS_ORDER = new Key(Boolean.class)
static final Key FORCE_AXIS_ORDER_HONORING = new Key(String.class)
static final Key FORCE_STANDARD_AXIS_DIRECTIONS = new Key(Boolean.class)
static final Key FORCE_STANDARD_AXIS_UNITS = new Key(Boolean.class)
static final Key VERSION = new Key("org.apache.sis.util.Version")
static final Key JAI_INSTANCE = new Key("javax.media.jai.JAI")
The javax.media.jai.JAI instance to use.
static final Key TILE_ENCODING = new Key(String.class)
static final Key COVERAGE_PROCESSING_VIEW = new Key("org.geotoolkit.coverage.grid.ViewType")
static final Key SAMPLE_DIMENSION_TYPE = new Key("org.geotoolkit.coverage.SampleDimensionType")
static final ClassKey TEMPORAL_FACTORY = new ClassKey("org.opengis.temporal.TemporalFactory")
static final ClassKey POSITION_FACTORY = new ClassKey("org.opengis.geometry.PositionFactory")
static final ClassKey PRIMITIVE_FACTORY = new ClassKey("org.opengis.geometry.primitive.PrimitiveFactory")
static final ClassKey GEOMETRY_FACTORY = new ClassKey("org.opengis.geometry.coordinate.GeometryFactory")
static final ClassKey COMPLEX_FACTORY = new ClassKey("org.opengis.geometry.complex.ComplexFactory")
static final ClassKey AGGREGATE_FACTORY = new ClassKey("org.opengis.geometry.aggregate.AggregateFactory")
static final ClassKey FEATURE_TYPE_FACTORY = new ClassKey("org.geotoolkit.feature.type.FeatureTypeFactory")
static final ClassKey FEATURE_FACTORY = new ClassKey("org.geotoolkit.feature.FeatureFactory")
static final ClassKey FILTER_FACTORY = new ClassKey("org.opengis.filter.FilterFactory")
static final ClassKey STYLE_FACTORY = new ClassKey("org.opengis.style.StyleFactory")
Package Functions
Hints (final boolean dummy)
Creates an empty set of hints.
Static Package Functions
static String nameOf (final RenderingHints.Key key)
Tries to find the name of the given key, using reflection.
static Field fieldOf (final RenderingHints.Key key)
Tries to find the field of the given key, using reflection.
Static Private Member Functions
static String toString (final Map<?,?> hints)
Returns a string representation of the specified hints.
static String format (final Map<?,?> hints)
Formats the specified hints.
static void format (final TableAppender table, final Map<?,?> hints, final String indent) throws IOException
Formats recursively the tree.
static Class<?> getEnclosingClass (final RenderingHints.Key key)
Returns the enclosing class of the given key, or.
static String nameOf (final Class<?> type, final RenderingHints.Key key)
If the given key is declared in the given class, returns its name.
static Field fieldOf (final Class<?> type, final RenderingHints.Key key)
If the given key is declared in the given class, returns its field.
Static Private Attributes
static final Map< RenderingHints.Key, Object > GLOBAL = new ConcurrentHashMap<>(8, 0.75f, 1)
A set of system-wide hints to use by default.
Detailed Description
A set of hints providing control on factories to be used.
They provides a way to control low-level details. When hints are used in conjunction with FactoryRegistry factory registry} (the Geotk service discovery mechanism), we have the complete Geotk plugin system. By using hints to allow application code to effect service discovery, we allow client code to retarget the Geotk library for their needs.
The following example fetch a CoordinateOperationFactory coordinate operation factory} which is tolerant to the lack of Bursa-Wolf parameters:
{ java Hints hints = new Hints(Hints.LENIENT_DATUM_SHIFT, Boolean.TRUE); CoordinateOperationFactory factory = FactoryFinder.getCoordinateOperationFactory(hints); }
Hints may be ignored if they do not apply to the object to be instantiated.
Author
Martin Desruisseaux (IRD, Geomatys)
Jody Garnett (Refractions)
Version
3.18
See also
Factory
FactoryRegistry
Since
2.0
Constructor & Destructor Documentation
Hints() [1/7]
Hints (final boolean dummy) package
Creates an empty set of hints.
This constructor is for EmptyHints usage only. All public constructors are expected to create hints initialized to the system-wide default. If an empty set of hints is really needed, use EmptyHints#clone().
Parameters
dummy Ignored.
{
         super(null);
     }
Hints() [2/7]
Hints ()
Constructs a map of hints initialized with the system-wide default values.
The default values are those that were given to putSystemDefault and not yet removed with removeSystemDefault.
Since
2.5
Referenced by EmptyHints.clone().
                    {
         super(GLOBAL);
     }
Hints() [3/7]
Hints (final RenderingHints.Key key, final Object value)
Constructs a new map of hints with the specified key/value pair.
First, an initial map is created as with the Hints() no-argument constructor}. This map may not be empty. Then, the given key-value pair is added. If a default value was present for the given key, then the given value replaces the default one.
Parameters
key The key of the particular hint property.
value The value of the hint property specified with
key
.
{
         // Don't use 'super(key,value)' because it doesn't check validity.
         this();
         put(key, value);
     }
Hints() [4/7]
Hints (final RenderingHints.Key key1, final Object value1, final RenderingHints.Key key2, final Object value2)
Constructs a new map of hints with two key/value pairs.
First, an initial map is created as with the Hints() no-argument constructor}. This map may not be empty. Then, the given key-value pairs are added. If a default value was present for a given key, then the given value replaces the default one.
Parameters
key1 The key for the first pair.
value1 The value for the first pair.
key2 The key2 for the second pair.
value2 The value2 for the second pair.
Since
2.4
     {
         this(key1, value1);
         put (key2, value2);
     }
Hints() [5/7]
Hints (final RenderingHints.Key key1, final Object value1, final RenderingHints.Key key2, final Object value2, final Object... pairs)
Constructs a new map of hints from key/value pairs.
First, an initial map is created as with the Hints() no-argument constructor}. This map may not be empty. Then, the given key-value pairs are added. If a default value was present for a given key, then the given value replaces the default one.
Parameters
key1 The key for the first pair.
value1 The value for the first pair.
key2 The key2 for the second pair.
value2 The value2 for the second pair.
pairs Additional pairs of keys and values.
Since
2.4
References Errors.format(), and Errors.Keys.OddArrayLength_1.
     {
         this(key1, value1, key2, value2);
         if ((pairs.length & 1) != 0) {
             throw new IllegalArgumentException(Errors.format(
                     Errors.Keys.OddArrayLength_1, pairs.length));
         }
         for (int i=0; i<pairs.length;) {
             put(pairs[i++], pairs[i++]);
         }
     }
Hints() [6/7]
Hints (final Map<? extends RenderingHints.Key, ?> hints)
Constructs a new object with keys and values from the given map (which may be null).
First, an initial map is created as with the Hints() no-argument constructor}. This map may not be empty. Then, the given key-value pairs are added. If a default value was presents for a given key, then the given value replace the default one.
Parameters
hints A map of key/value pairs to initialize the hints, or
null
if none.
{
         this();
         if (hints != null) {
             putAll(hints);
         }
     }
Hints() [7/7]
Hints (final RenderingHints hints)
Constructs a new object with keys and values from the given map (which may be null).
First, an initial map is created as with the Hints() no-argument constructor}. This map may not be empty. Then, the given key-value pairs are added. If a default value was presents for a given key, then the given value replace the default one.
Parameters
hints A map of key/value pairs to initialize the hints, or
null
if none.
Since
2.5
{
         this();
         if (hints != null) {
             putAll(hints);
         }
     }
Member Function Documentation
clone()
Hints clone ()
Returns a new map of hints with the same content than this map.
Since
2.5
References Hints.clone().
Referenced by Hints.clone(), ReferencingFactoryContainer.getCurrentHints(), and ReferencingFactoryContainer.ReferencingFactoryContainer().
{
         return (Hints) super.clone();
     }
fieldOf() [1/2]
static Field fieldOf (final RenderingHints.Key key) static package
Tries to find the field of the given key, using reflection.
This method searches for a constant declared in the enclosing class, which is typically one of:
org.geotoolkit.factory.Hints
(this class)
javax.media.jai.JAI
(assuming JAI is on the classpath)
java.awt.RenderingHints
(actually sun.awt.SunHints at least on Sun JDK)
Parameters
key The key for which a field is wanted, or
null
.
Returns
The key field as declared in the static constants.
References Hints.getEnclosingClass().
Referenced by Hints.nameOf(), and SerializedKey.SerializedKey().
{
         Field field = null;
         if (key != null) {
             Class<?> c = getEnclosingClass(key);
             if (c == null || (field = fieldOf(c, key)) == null) {
                 if (key instanceof Key && c != (c = ((Key) key).getValueClass())) {
                     field = fieldOf(c, key);
                 }
             }
         }
         return field;
     }
fieldOf() [2/2]
static Field fieldOf (final Class<?> type, final RenderingHints.Key key) static private
If the given key is declared in the given class, returns its field.
Otherwise returns
null
.
{
         final Field[] fields = type.getFields();
         for (int i=0; i<fields.length; i++) {
             final Field f = fields[i];
             /*
              * Note: to be strict, the line below should ensure that the field is final in
              * addition of static. Unfortunately the JAI static fields are not final in JAI 1.1.
              */
             if (Modifier.isStatic(f.getModifiers())) {
                 final Object v;
                 try {
                     v = f.get(null);
                 } catch (IllegalAccessException e) {
                     continue;
                 }
                 if (v == key) {
                     return f;
                 }
             }
         }
         return null;
     }
format() [1/2]
static String format (final Map<?,?> hints) static private
Formats the specified hints.
This method is just the starting point for format(Writer, Map, String, Map) below.
Referenced by Hints.toString().
{
         final TableAppender table;
         try {
             table = new TableAppender(" ");
             format(table, hints, "  ");
         } catch (IOException e) {
             // Should never happen, since we are writing in a buffer.
             throw new AssertionError(e);
         }
         return table.toString();
     }
format() [2/2]
static void format (final TableAppender table, final Map<?,?> hints, final String indent) throws IOException static private
Formats recursively the tree.
This method invoke itself.
References Hints.nameOf().
{
         for (final Map.Entry<?,?> entry : hints.entrySet()) {
             final Object k = entry.getKey();
             String key = (k instanceof RenderingHints.Key) ?
                     Hints.nameOf((RenderingHints.Key) k) : String.valueOf(k);
             Object value = entry.getValue();
             table.append(indent);
             table.append(key);
             char separator = ':';
             table.nextColumn();
             table.append(separator);
             table.append(' ');
             table.append(String.valueOf(value));
             table.nextLine();
         }
     }
getEnclosingClass()
static Class<?> getEnclosingClass (final RenderingHints.Key key) static private
Returns the enclosing class of the given key, or.
null
if none. A special case is applied for
sun.awt.SunHints
, which maps to RenderingHints.
Referenced by Hints.fieldOf(), and Hints.Key.toString().
{
         Class<?> c = key.getClass().getEnclosingClass();
         if (c != null && c.getName().startsWith("sun.")) {
             c = RenderingHints.class;
         }
         return c;
     }
getSystemDefault()
static Object getSystemDefault (final RenderingHints.Key key) static
Returns the system-wide default value for the given key.
The Geotk library initially contains no system default, so
getSystemDefault(key)
returns null for all keys. Users can add default values using putSystemDefault.
To get a map of all system defaults, use
new Hints()
.
Parameters
key The hints key.
Returns
The system-wide default value for the given key, or
null
if the key did not have a mapping.
Since
2.4
{
         return GLOBAL.get(key);
     }
nameOf() [1/2]
static String nameOf (final RenderingHints.Key key) static package
Tries to find the name of the given key, using reflection.
Parameters
key The key for which a name is wanted, or
null
.
Returns
The key name as declared in the static constants.
References Hints.fieldOf().
Referenced by Hints.format(), Hints.putSystemDefault(), and Hints.Key.toString().
{
         if (key == null) {
             return null;
         }
         if (!(key instanceof Key)) {
             final Field field = fieldOf(key);
             if (field != null) {
                 return field.getName();
             }
         }
         return key.toString();
     }
nameOf() [2/2]
static String nameOf (final Class<?> type, final RenderingHints.Key key) static private
If the given key is declared in the given class, returns its name.
Otherwise returns
null
.
References Hints.fieldOf().
{
         final Field f = fieldOf(type, key);
         return (f != null) ? f.getName() : null;
     }
putSystemDefault()
static Object putSystemDefault (final RenderingHints.Key key, final Object value) static
Adds or modifies a system-wide default value.
Hints
instances created after this method call will be initialized to the union of all values specified with
putSystemDefault
and not yet removeSystemDefault removed}.
If the given value is different than the previous one, then this method notifies every listeners registered with Factories#addChangeListener(ChangeListener).
Parameters
key The hint key.
value The hint value to be used as the system-wide default for the given key.
Returns
The previous value for the given key, or
null
if none.
Exceptions
IllegalArgumentException if Hints.Key#isCompatibleValue(Object) returns
false
for the given value.
Since
2.4
References Factories.fireConfigurationChanged(), Errors.format(), Errors.Keys.IllegalArgument_2, and Hints.nameOf().
{
         if (!key.isCompatibleValue(value)) {
             throw new IllegalArgumentException(Errors.format(
                     Errors.Keys.IllegalArgument_2, nameOf(key), value));
         }
         final Object old = GLOBAL.put(key, value);
         if (!Objects.equals(value, old)) {
             Factories.fireConfigurationChanged(Hints.class);
         }
         return old;
     }
removeSystemDefault()
static Object removeSystemDefault (final RenderingHints.Key key) static
Removes the specified hints from the set of system default values.
If the a value was present for the given key, then this method notifies every listeners registered with Factories#addChangeListener(ChangeListener).
Parameters
key The hints key that needs to be removed.
Returns
The value to which the key had previously been mapped, or
null
if the key did not have a mapping.
Since
2.4
References Factories.fireConfigurationChanged().
{
         final Object old = GLOBAL.remove(key);
         if (old != null) {
             Factories.fireConfigurationChanged(Hints.class);
         }
         return old;
     }
toString() [1/2]
String toString ()
Returns a string representation of the hints.
The default implementation formats the set of hints as a tree.
Since
2.4
{
         return toString(this);
     }
toString() [2/2]
static String toString (final Map<?,?> hints) static private
Returns a string representation of the specified hints.
This is used by Hints#toString in order to share the code provided in this class.
References Hints.format().
{
         return format(hints);
     }
Member Data Documentation
AGGREGATE_FACTORY
final ClassKey AGGREGATE_FACTORY = new ClassKey("org.opengis.geometry.aggregate.AggregateFactory") static
CITATION_FACTORY
final ClassKey CITATION_FACTORY static
Initial value:
= new ClassKey(
            "org.opengis.metadata.citation.CitationFactory")
COMPLEX_FACTORY
final ClassKey COMPLEX_FACTORY = new ClassKey("org.opengis.geometry.complex.ComplexFactory") static
COORDINATE_OPERATION_AUTHORITY_FACTORY
final ClassKey COORDINATE_OPERATION_AUTHORITY_FACTORY static
Initial value:
= new ClassKey(
            "org.opengis.referencing.operation.CoordinateOperationAuthorityFactory")
Referenced by Factories.getCoordinateOperationAuthorityFactory().
COORDINATE_OPERATION_FACTORY
final ClassKey COORDINATE_OPERATION_FACTORY static
Initial value:
= new ClassKey(
            "org.opengis.referencing.operation.CoordinateOperationFactory")
COVERAGE_PROCESSING_VIEW
final Key COVERAGE_PROCESSING_VIEW = new Key("org.geotoolkit.coverage.grid.ViewType") static
CRS_AUTHORITY_EXTRA_DIRECTORY
final FileKey CRS_AUTHORITY_EXTRA_DIRECTORY = new FileKey(false) static
Referenced by PropertyEpsgFactory.PropertyEpsgFactory().
CRS_AUTHORITY_FACTORY
final ClassKey CRS_AUTHORITY_FACTORY static
Initial value:
= new ClassKey(
            "org.opengis.referencing.crs.CRSAuthorityFactory")
Referenced by Factories.getCRSAuthorityFactory().
CRS_FACTORY
final ClassKey CRS_FACTORY static
Initial value:
= new ClassKey(
            "org.opengis.referencing.crs.CRSFactory")
Referenced by ReferencingFactoryContainer.ReferencingFactoryContainer().
CS_AUTHORITY_FACTORY
final ClassKey CS_AUTHORITY_FACTORY static
Initial value:
= new ClassKey(
            "org.opengis.referencing.cs.CSAuthorityFactory")
CS_FACTORY
final ClassKey CS_FACTORY static
Initial value:
= new ClassKey(
            "org.opengis.referencing.cs.CSFactory")
Referenced by ReferencingFactoryContainer.ReferencingFactoryContainer().
DATUM_AUTHORITY_FACTORY
final ClassKey DATUM_AUTHORITY_FACTORY static
Initial value:
= new ClassKey(
            "org.opengis.referencing.datum.DatumAuthorityFactory")
DATUM_FACTORY
final ClassKey DATUM_FACTORY static
Initial value:
= new ClassKey(
            "org.opengis.referencing.datum.DatumFactory")
Referenced by ReferencingFactoryContainer.ReferencingFactoryContainer().
DATUM_SHIFT_METHOD
final OptionKey DATUM_SHIFT_METHOD static
Initial value:
= new OptionKey(
            "Molodensky", "Abridged Molodensky",
            "Molodenski", "Abridged_Molodenski",
            "Geocentric", "*")
DEFAULT_COORDINATE_REFERENCE_SYSTEM
final Key DEFAULT_COORDINATE_REFERENCE_SYSTEM static
Initial value:
= new Key(
            "org.opengis.referencing.crs.CoordinateReferenceSystem")
EPSG_DATA_SOURCE
final Key EPSG_DATA_SOURCE = new DataSourceKey() static
FEATURE_FACTORY
final ClassKey FEATURE_FACTORY = new ClassKey("org.geotoolkit.feature.FeatureFactory") static
FEATURE_TYPE_FACTORY
final ClassKey FEATURE_TYPE_FACTORY = new ClassKey("org.geotoolkit.feature.type.FeatureTypeFactory") static
FILTER_FACTORY
final ClassKey FILTER_FACTORY = new ClassKey("org.opengis.filter.FilterFactory") static
FORCE_AXIS_ORDER_HONORING
final Key FORCE_AXIS_ORDER_HONORING = new Key(String.class) static
FORCE_LONGITUDE_FIRST_AXIS_ORDER
final Key FORCE_LONGITUDE_FIRST_AXIS_ORDER = new Key(Boolean.class) static
FORCE_STANDARD_AXIS_DIRECTIONS
final Key FORCE_STANDARD_AXIS_DIRECTIONS = new Key(Boolean.class) static
FORCE_STANDARD_AXIS_UNITS
final Key FORCE_STANDARD_AXIS_UNITS = new Key(Boolean.class) static
GEOMETRY_FACTORY
final ClassKey GEOMETRY_FACTORY = new ClassKey("org.opengis.geometry.coordinate.GeometryFactory") static
GLOBAL
final Map<RenderingHints.Key,Object> GLOBAL = new ConcurrentHashMap<>(8, 0.75f, 1) static private
A set of system-wide hints to use by default.
Only one thread is expected to write (while more are allowed).
JAI_INSTANCE
final Key JAI_INSTANCE = new Key("javax.media.jai.JAI") static
The javax.media.jai.JAI instance to use.
LENIENT_DATUM_SHIFT
final Key LENIENT_DATUM_SHIFT = new Key(Boolean.class) static
MATH_TRANSFORM_FACTORY
final ClassKey MATH_TRANSFORM_FACTORY static
Initial value:
= new ClassKey(
            "org.opengis.referencing.operation.MathTransformFactory")
Referenced by ReferencingFactoryContainer.declaredFactoryHints(), and ReferencingFactoryContainer.ReferencingFactoryContainer().
NAME_FACTORY
final ClassKey NAME_FACTORY static
Initial value:
= new ClassKey(
            "org.opengis.util.NameFactory")
POSITION_FACTORY
final ClassKey POSITION_FACTORY = new ClassKey("org.opengis.geometry.PositionFactory") static
PRIMITIVE_FACTORY
final ClassKey PRIMITIVE_FACTORY = new ClassKey("org.opengis.geometry.primitive.PrimitiveFactory") static
SAMPLE_DIMENSION_TYPE
final Key SAMPLE_DIMENSION_TYPE = new Key("org.geotoolkit.coverage.SampleDimensionType") static
STYLE_FACTORY
final ClassKey STYLE_FACTORY = new ClassKey("org.opengis.style.StyleFactory") static
TEMPORAL_FACTORY
final ClassKey TEMPORAL_FACTORY = new ClassKey("org.opengis.temporal.TemporalFactory") static
TILE_ENCODING
final Key TILE_ENCODING = new Key(String.class) static
VERSION
final Key VERSION = new Key("org.apache.sis.util.Version") static