jena-geo: TileRasterCache Class Reference
TileRasterCache Class Reference
Contain java.awt.image.Raster and different raster properties.
Public Member Functions
boolean equals (Object obj)
Package Functions
TileRasterCache (int gridX, int gridY, long weight, Raster raster)
Object to wrap java.awt.image.Raster and different raster properties.
int getGridX ()
Return stocked java.awt.image.Raster mosaic coordinate in X direction.
int getGridY ()
Return stocked java.awt.image.Raster mosaic coordinate in Y direction.
Raster getRaster ()
Return stocked java.awt.image.Raster.
long getWeight ()
Return stocked java.awt.image.Raster weight.
Private Attributes
final int gridX
final int gridY
final long weight
final Raster raster
Detailed Description
Contain java.awt.image.Raster and different raster properties.
Author
Remi Marechal (Geomatys).
Constructor & Destructor Documentation
TileRasterCache()
TileRasterCache (int gridX, int gridY, long weight, Raster raster) package
Object to wrap java.awt.image.Raster and different raster properties.
Parameters
gridX raster position in X direction.
gridY raster position in Y direction.
weight raster weight.
raster
References TileRasterCache.gridX, TileRasterCache.gridY, TileRasterCache.raster, and TileRasterCache.weight.
Referenced by TileRasterCache.equals().
{
         this.gridX  = gridX;
         this.gridY  = gridY;
         this.weight = weight;
         this.raster = raster;
     }
Member Function Documentation
equals()
boolean equals (Object obj)
References TileRasterCache.getGridX(), TileRasterCache.getGridY(), TileRasterCache.getRaster(), and TileRasterCache.TileRasterCache().
{
         if (!(obj instanceof TileRasterCache)) return false;
         TileRasterCache lr = (TileRasterCache) obj;
         return (gridX == lr.getGridX() && gridY == lr.getGridY() && raster == lr.getRaster());
     }
getGridX()
int getGridX () package
Return stocked java.awt.image.Raster mosaic coordinate in X direction.
Returns
stocked java.awt.image.Raster mosaic coordinate in X direction.
References TileRasterCache.gridX.
Referenced by TileRasterCache.equals().
                    {
         return gridX;
     }
getGridY()
int getGridY () package
Return stocked java.awt.image.Raster mosaic coordinate in Y direction.
Returns
stocked java.awt.image.Raster mosaic coordinate in Y direction.
References TileRasterCache.gridY.
Referenced by TileRasterCache.equals().
                    {
         return gridY;
     }
getRaster()
Raster getRaster () package
Return stocked java.awt.image.Raster.
Returns
stocked java.awt.image.Raster.
References TileRasterCache.raster.
Referenced by TileRasterCache.equals(), and ImageTilesCache.getRaster().
{
         return raster;
     }
getWeight()
long getWeight () package
Return stocked java.awt.image.Raster weight.
Returns
stocked java.awt.image.Raster weight.
References TileRasterCache.weight.
                      {
         return weight;
     }
Member Data Documentation
gridX
final int gridX private
Referenced by TileRasterCache.getGridX(), and TileRasterCache.TileRasterCache().
gridY
final int gridY private
Referenced by TileRasterCache.getGridY(), and TileRasterCache.TileRasterCache().
raster
final Raster raster private
Referenced by TileRasterCache.getRaster(), and TileRasterCache.TileRasterCache().
weight
final long weight private
Referenced by TileRasterCache.getWeight(), and TileRasterCache.TileRasterCache().