jena-geo: TransformedShape Class Reference
TransformedShape Class Reference
Applies an arbitrary AffineTransform on a Shape.
Public Member Functions
TransformedShape ()
Constructs a.
TransformedShape (final AffineTransform transform)
Constructs a.
TransformedShape (final Shape shape)
Constructs a view of the given shape initialized to the identity transform.
TransformedShape (final Shape shape, final AffineTransform transform)
Constructs a.
Shape getOriginalShape ()
Returns the original shape for which this.
void setOriginalShape (final Shape shape)
Sets the shape for which this.
void getMatrix (final float[] matrix, int offset)
Returns the 6 coefficients values as.
void setTransform (final float[] matrix, int offset)
Sets the transform from a flat matrix.
boolean contains (final double x, final double y)
Tests if the specified coordinate is inside the boundary of this shape.
boolean contains (final Point2D p)
Tests if a specified Point2D is inside the boundary of this shape.
boolean contains (final double x, final double y, final double width, final double height)
Tests if the interior of this shape entirely contains the specified rectangular area.
boolean contains (final Rectangle2D r)
Tests if the interior of this shape entirely contains the specified rectangle.
boolean intersects (double x, double y, double width, double height)
Tests if the interior of this shape intersects the interior of a specified rectangular area.
boolean intersects (final Rectangle2D r)
Tests if the interior of this shape intersects the interior of a specified rectangle.
Rectangle getBounds ()
Returns an integer rectangle that completely encloses this shape.
Rectangle2D getBounds2D ()
Returns a high precision and more accurate bounding box of the shape than the getBounds method.
PathIterator getPathIterator (AffineTransform at)
Returns an iterator object that iterates along the shape boundary and provides access to the geometry of the shape outline.
PathIterator getPathIterator (AffineTransform at, final double flatness)
Returns an iterator object that iterates along the shape boundary and provides access to a flattened view of the shape outline geometry.
int hashCode ()
Returns a hash code value for this shape.
boolean equals (final Object object)
Compares this shape with the given object for equality.
Private Member Functions
void initTransientFields ()
Initializes the transient fields.
void readObject (final ObjectInputStream in) throws IOException, ClassNotFoundException
Invoked on deserialization.
Private Attributes
Shape shape
The original shape for which this.
transient Point2D.Double point
A temporary point.
transient Rectangle2D.Double rectangle
A temporary rectangle.
Static Private Attributes
static final long serialVersionUID = 3541606381365714951L
For cross-version compatibility.
Detailed Description
Applies an arbitrary AffineTransform on a Shape.
A
TransformedShape
instance is a view over a shape, i.e. the shape coordinates are transformed on the fly, never copied.
The shape to be transformed is specified by setOriginalShape(Shape). The transform to apply is specified by the inherited
AffineTransform
, which can be modified at any time using all its usual methods. Every changes to the original shape or to the inherited transform take immediate effect since this class is only a view.
{
Note
This class is final because extending directly AffineTransform is not a good example of object-oriented programming, since a transformed shape is not a special kind of affine transform. We did that as a convenience for allowing frequent modifications of the transform by direct access to the AffineTransform methods, but this is not an example that shoud be replicated.}
{
cost}
When getPathIterator(AffineTransform) iterating over the shape boundary}, the only performance cost is a #concatenate(AffineTransform) matrix multiplication} applied before the iterator is created - the cost of the iteration itself usually stay unchanged.
{
}
The Arrow2D class is unconditionally oriented toward 0° arithmetic. In order to draw a field of arrows in arbitrary directions, the code below can be used:
{ java protected void paint(Graphics2D graphics) { Arrow2D arrow = new Arrow2D(...); TransformedShape orientedArrow = new TransformedShape(arrow); for (int i=0; i<numArrows; i++) { double scale = ... double orientation = Math.toRadians(...); orientedArrow.setToScale(scale, scale); orientedArrow.rotate(orientation); graphics.fill(orientedArrow); } } }
An alternative to this
TransformedShape
class would be to change directly the java.awt.Graphics2D transform. The main difference between those alternatives is that when using
TransformedShape
, the transform does not apply to the line thickness or paint texture. The preferred alternative depends on the desired rendering effect, for example if line thickness needs to be specified in pixel units or in "<cite>real world</cite>" units.
Author
Martin Desruisseaux (IRD, Geomatys)
Version
3.20
See also
ProjectedShape
Since
2.0
Constructor & Destructor Documentation
TransformedShape() [1/4]
TransformedShape ()
Constructs a.
TransformedShape
initialized to the identity transform with no original shape. The setOriginalShape(Shape) method must be invoked at least once before this object can be used.
References TransformedShape.initTransientFields().
{
         initTransientFields();
     }
TransformedShape() [2/4]
TransformedShape (final AffineTransform transform)
Constructs a.
TransformedShape
initialized to the given transform with no original shape. The setOriginalShape(Shape) method must be invoked at least once before this object can be used.
Parameters
transform The initial affine transform.
References TransformedShape.initTransientFields().
{
         super(transform);
         initTransientFields();
     }
TransformedShape() [3/4]
TransformedShape (final Shape shape)
Constructs a view of the given shape initialized to the identity transform.
Parameters
shape The shape to wrap in the new
TransformedShape
instance.
References TransformedShape.initTransientFields(), and TransformedShape.shape.
{
         ensureNonNull("shape", shape);
         this.shape = shape;
         initTransientFields();
     }
TransformedShape() [4/4]
TransformedShape (final Shape shape, final AffineTransform transform)
Constructs a.
TransformedShape
initialized to the given transform and shape.
Parameters
shape The shape to wrap in the new
TransformedShape
instance.
transform The initial affine transform.
Since
3.20
References TransformedShape.initTransientFields(), and TransformedShape.shape.
{
         super(transform);
         ensureNonNull("shape", shape);
         this.shape = shape;
         initTransientFields();
     }
Member Function Documentation
contains() [1/4]
boolean contains (final double x, final double y)
Tests if the specified coordinate is inside the boundary of this shape.
This method might conservatively return
false
if the transform is not invertible.
The default implementation delegates to contains(Point2D).
Parameters
x The x ordinate of the point to be tested.
y The y ordinate of the point to be tested.
Returns
true
if this shape contains the given point.
References TransformedShape.point.
Referenced by TransformedShape.contains().
{
         final Point2D.Double p = point;
         p.x = x;
         p.y = y;
         return contains(p);
     }
contains() [2/4]
boolean contains (final Point2D p)
Tests if a specified Point2D is inside the boundary of this shape.
This method might conservatively return
false
if the transform is not invertible.
Parameters
p The point to be tested.
Returns
true
if this shape contains the given point.
References TransformedShape.point.
{
         try {
             return shape.contains(inverseTransform(p, point));
         } catch (NoninvertibleTransformException exception) {
             Logging.recoverableException(null, TransformedShape.class, "contains", exception);
             return false;
         }
     }
contains() [3/4]
boolean contains (final double x, final double y, final double width, final double height)
Tests if the interior of this shape entirely contains the specified rectangular area.
This method might conservatively return
false
if the transform is not invertible or if the calculation of
originalShape.contains(...)
is too expensive.
The default implementation delegates to contains(Rectangle2D).
Parameters
x The minimal x ordinate of the rectangle to be tested.
y The minimal y ordinate of the rectangle to be tested.
width The width of the rectangle to be tested.
height The height of the rectangle to be tested.
Returns
true
if this shape contains the given rectangle.
References TransformedShape.contains(), and TransformedShape.rectangle.
{
         final Rectangle2D.Double r = rectangle;
         r.x = x;
         r.y = y;
         r.width = width;
         r.height = height;
         return contains(r);
     }
contains() [4/4]
boolean contains (final Rectangle2D r)
Tests if the interior of this shape entirely contains the specified rectangle.
This method might conservatively return
false
if the transform is not invertible or if the calculation of
originalShape.contains(...)
is too expensive.
Parameters
r The rectangle to be tested.
Returns
true
if this shape contains the given rectangle.
References TransformedShape.rectangle.
{
         try {
             return shape.contains(AffineTransforms2D.inverseTransform(this, r, rectangle));
         } catch (NoninvertibleTransformException exception) {
             Logging.recoverableException(null, TransformedShape.class, "contains", exception);
             return false; // Consistent with the Shape interface contract.
         }
     }
equals()
boolean equals (final Object object)
Compares this shape with the given object for equality.
Do not compare
TransformedShape
instances with plain AffineTransform instances, because the "<cite>be symmetric</cite>" part of the Object#equals(Object) contract can not be enforced.
Parameters
object The object to compare with this shape.
Since
3.20
References TransformedShape.equals().
Referenced by TransformedShape.equals().
{
         if (object instanceof TransformedShape && super.equals(object)) {
             return Objects.equals(shape, ((TransformedShape) object).shape);
         }
         return false;
     }
getBounds()
Rectangle getBounds ()
Returns an integer rectangle that completely encloses this shape.
{
         // Delegates to getBounds2D(), not getBounds(), because a scale greater than 1
         // will use the fraction digits of a number that would be otherwise rounded.
         return (Rectangle) AffineTransforms2D.transform(this, shape.getBounds2D(), new Rectangle());
     }
getBounds2D()
Rectangle2D getBounds2D ()
Returns a high precision and more accurate bounding box of the shape than the getBounds method.
{
         return AffineTransforms2D.transform(this, shape.getBounds2D(), null);
     }
getMatrix()
void getMatrix (final float [] matrix, int offset)
Returns the 6 coefficients values as.
float
numbers. The coefficients are stored in the same order than getMatrix(double[]), with the first coefficient stored in
matrix[offset]
and the last coefficient stored in
matrix[offset+5]
Parameters
matrix The matrix where to store the coefficient values.
offset Index of the first element where to write in the
matrix
array.
{
         matrix[  offset] = (float) getScaleX();     // m00
         matrix[++offset] = (float) getShearY();     // m10
         matrix[++offset] = (float) getShearX();     // m01
         matrix[++offset] = (float) getScaleY();     // m11
         matrix[++offset] = (float) getTranslateX(); // m02
         matrix[++offset] = (float) getTranslateY(); // m12
     }
getOriginalShape()
Shape getOriginalShape ()
Returns the original shape for which this.
TransformedShape
is a view.
Returns
The shape wrapped by this
TransformedShape
instance.
References TransformedShape.shape.
{
         return shape;
     }
getPathIterator() [1/2]
PathIterator getPathIterator (AffineTransform at)
Returns an iterator object that iterates along the shape boundary and provides access to the geometry of the shape outline.
{
         if (!isIdentity()) {
             if (at == null || at.isIdentity()) {
                 return shape.getPathIterator(this);
             }
             at = new AffineTransform(at);
             at.concatenate(this);
         }
         return shape.getPathIterator(at);
     }
getPathIterator() [2/2]
PathIterator getPathIterator (AffineTransform at, final double flatness)
Returns an iterator object that iterates along the shape boundary and provides access to a flattened view of the shape outline geometry.
{
         if (!isIdentity()) {
             if (at == null || at.isIdentity()) {
                 return shape.getPathIterator(this, flatness);
             }
             at = new AffineTransform(at);
             at.concatenate(this);
         }
         return shape.getPathIterator(at, flatness);
     }
hashCode()
int hashCode ()
Returns a hash code value for this shape.
Since
3.20
{
         int code = super.hashCode() ^ (int) serialVersionUID;
         if (shape != null) {
             code ^= shape.hashCode();
         }
         return code;
     }
initTransientFields()
void initTransientFields () private
Initializes the transient fields.
Invoked on construction and on deserialization.
References TransformedShape.point, and TransformedShape.rectangle.
Referenced by TransformedShape.readObject(), and TransformedShape.TransformedShape().
{
         point = new Point2D.Double();
         rectangle = new Rectangle2D.Double();
     }
intersects() [1/2]
boolean intersects (double x, double y, double width, double height)
Tests if the interior of this shape intersects the interior of a specified rectangular area.
This method might conservatively return
true
if the transform is not invertible or if the calculation of
originalShape.intersects(...)
is too expensive.
The default implementation delegates to intersects(Rectangle2D).
Parameters
x The minimal x ordinate of the rectangle to be tested.
y The minimal y ordinate of the rectangle to be tested.
width The width of the rectangle to be tested.
height The height of the rectangle to be tested.
Returns
true
if this shape intersects the given rectangle.
References TransformedShape.rectangle.
{
         final Rectangle2D.Double r = rectangle;
         r.x = x;
         r.y = y;
         r.width = width;
         r.height = height;
         return intersects(r);
     }
intersects() [2/2]
boolean intersects (final Rectangle2D r)
Tests if the interior of this shape intersects the interior of a specified rectangle.
This method might conservatively return
true
if the transform is not invertible or if the calculation of
originalShape.intersects(...)
is too expensive.
Parameters
r The rectangle to be tested.
Returns
true
if this shape intersects the given rectangle.
References TransformedShape.rectangle.
{
         try {
             return shape.intersects(AffineTransforms2D.inverseTransform(this, r, rectangle));
         } catch (NoninvertibleTransformException exception) {
             Logging.recoverableException(null, TransformedShape.class, "intersects", exception);
             return true; // Consistent with the Shape interface contract.
         }
     }
readObject()
void readObject (final ObjectInputStream in) throws IOException, ClassNotFoundException private
Invoked on deserialization.
References TransformedShape.initTransientFields().
{
         in.readObject();
         initTransientFields();
     }
setOriginalShape()
void setOriginalShape (final Shape shape)
Sets the shape for which this.
TransformedShape
will be a view.
Parameters
shape The shape to wrap in this
TransformedShape
instance.
References TransformedShape.shape.
{
         ensureNonNull("shape", shape);
         this.shape = shape;
     }
setTransform()
void setTransform (final float [] matrix, int offset)
Sets the transform from a flat matrix.
The coefficients are read in the same order than they were stored by getMatrix.
Parameters
matrix The flat matrix.
offset Index of the first element to use in
matrix
array.
{
         setTransform(matrix[  offset], matrix[++offset], matrix[++offset],
                      matrix[++offset], matrix[++offset], matrix[++offset]);
     }
Member Data Documentation
point
transient Point2D.Double point private
A temporary point.
Referenced by TransformedShape.contains(), and TransformedShape.initTransientFields().
rectangle
transient Rectangle2D.Double rectangle private
A temporary rectangle.
Referenced by TransformedShape.contains(), TransformedShape.initTransientFields(), and TransformedShape.intersects().
serialVersionUID
final long serialVersionUID = 3541606381365714951L static private
For cross-version compatibility.
shape
Shape shape private
The original shape for which this.
TransformedShape
is a view.
Referenced by TransformedShape.getOriginalShape(), TransformedShape.setOriginalShape(), and TransformedShape.TransformedShape().