jena-geo: Mask Class Reference
Mask Class Reference
Applies a mask (typically a javax.media.jai.operator.BinarizeDescriptor binary image}) on an source image.
Public Member Functions
Mask (final RenderedImage source, final RenderedImage mask, final ImageLayout layout, final Map<?,?> configuration, final double[] newValues)
Constructs a new mask for the given image.
Vector< RenderedImage > getSources ()
Returns the source images.
Static Public Attributes
static final String OPERATION_NAME = "org.geotoolkit.Mask"
The name of this operation in the JAI registry.
Protected Member Functions
void computeRect (final PlanarImage[] sources, final WritableRaster dest, final Rectangle destRect)
Computes a rectangle of outputs.
Static Private Member Functions
static ImageLayout layout (final RenderedImage source, ImageLayout layout)
If the user didn't specified explicitly a sample or a color model, creates default ones.
Private Attributes
final double [] newValues
The values to copy to the destination images for every masked pixels, or.
Detailed Description
Applies a mask (typically a javax.media.jai.operator.BinarizeDescriptor binary image}) on an source image.
For every pixel in the source image there is a choice:
If the corresponding pixel in the mask is 0, then the source pixel is copied unchanged to the destination image.
Otherwise there is a choice:
If replacement values were explicitly given to this image operation, then those values are copied to the destination image.
Otherwise the value from the mask is used as the replacement values.
Example:
Input output
,
Author
Martin Desruisseaux (Geomatys)
Version
3.00
Since
3.00
Constructor & Destructor Documentation
Mask()
Mask (final RenderedImage source, final RenderedImage mask, final ImageLayout layout, final Map<?,?> configuration, final double [] newValues)
Constructs a new mask for the given image.
While this constructor is public, it should usually not be invoked directly. You should use javax.media.jai.JAI} factory methods instead.
Parameters
source The source image.
mask The mask. If it has smaller bounds than the source image, then every pixels outside the mask are treated as if they were zero.
layout The image layout.
configuration The image properties and rendering hints.
newValues The values to copy to the destination images for every masked pixels, or
null
for using the mask values. If non-null, then the array length must be equals to the number of bands in the destination image.
References Mask.layout().
     {
         super(source, mask, layout(source, layout), configuration, false);
         this.newValues = (newValues == null) ? null :
                 Arrays.copyOf(newValues, source.getSampleModel().getNumBands());
         permitInPlaceOperation();
     }
Member Function Documentation
computeRect()
void computeRect (final PlanarImage [] sources, final WritableRaster dest, final Rectangle destRect) protected
Computes a rectangle of outputs.
Parameters
sources The source images. Should be an array of length 2.
dest The raster to be filled in.
destRect The region within the raster to be filled.
References SampleValues.copyAsInts(), TransfertRectIter.create(), and Mask.newValues.
     {
         assert sources.length == 2;
         final PlanarImage source = sources[0];
         final PlanarImage mask   = sources[1];
         final RectIter mit = RectIterFactory.create(mask, destRect);
         final WritableRectIter iter = TransfertRectIter.create(source, dest, destRect);
         final boolean needCopy = (iter instanceof TransfertRectIter);
         if (iter.finishedLines()) {
             return;
         }
         /*
          * Below is a copy-and-paste of the same code for the 3 transfer types. While the
          * textual code look identical except for the 2 first lines, many methods that are
          * actually invoked are different because of method overloading.
          */
         final int numBands = getNumBands();
         switch (sampleModel.getDataType()) {
             /*
              * Every integer types.
              */
             default: {
                 final int[] replacement = SampleValues.copyAsInts(newValues);
                 final int[] buffer = new int[numBands];
                 do {
                     mit.startPixels();
                     iter.startPixels();
                     if (!iter.finishedPixels()) {
                         do {
                             final int m = mit.getSample();
                             mit.nextPixel();
                             if (m != 0) {
                                 // Found a value to mask.
                                 final int[] samples;
                                 if (replacement != null) {
                                     samples = replacement;
                                 } else {
                                     Arrays.fill(samples = buffer, m);
                                 }
                                 iter.setPixel(samples);
                                 continue;
                             }
                             // Found a unmasked value to copy.
                             if (!needCopy) continue;
                             iter.setPixel(iter.getPixel(buffer));
                         } while (!iter.nextPixelDone());
                     }
                     mit.nextLine();
                 } while (!iter.nextLineDone());
             }
         }
     }
getSources()
Vector<RenderedImage> getSources ()
Returns the source images.
{
         return super.getSources();
     }
layout()
static ImageLayout layout (final RenderedImage source, ImageLayout layout) static private
If the user didn't specified explicitly a sample or a color model, creates default ones.
This method is actually a workaround for RFE #4093999 in Sun's bug database ("Relax constraint on placement of this()/super() call in constructors").
Parameters
layout The user-supplied layout.
Returns
A layout with at least a color model.
Referenced by Mask.Mask().
{
         if (layout == null) {
             layout = new ImageLayout();
         } else if ((layout.getValidMask() & (SAMPLE_MODEL_MASK | COLOR_MODEL_MASK)) == 0) {
             layout = (ImageLayout) layout.clone();
         } else {
             return layout;
         }
         return layout.setSampleModel(source.getSampleModel()).setColorModel(source.getColorModel());
     }
Member Data Documentation
newValues
final double [] newValues private
The values to copy to the destination images for every masked pixels, or.
null
for using the mask values. If non-null, then the array length must be equals to the number of bands in the destination image.
Referenced by Mask.computeRect().
OPERATION_NAME
final String OPERATION_NAME = "org.geotoolkit.Mask" static
The name of this operation in the JAI registry.
This is {}.