jena-geo: IIOListeners Class Reference
IIOListeners Class Reference
A container of image I/O listeners.
Classes
class List
The list of listeners, as a subclass which can copy its value from an other list of listeners.
Public Member Functions
IIOListeners ()
Creates a new instance of.
void setListeners (final IIOListeners other)
Sets the list of listeners in this object to the same listeners than the given object.
void addIIOReadProgressListener (final IIOReadProgressListener listener)
Adds an.
void removeIIOReadProgressListener (final IIOReadProgressListener listener)
void addIIOReadUpdateListener (final IIOReadUpdateListener listener)
void removeIIOReadUpdateListener (final IIOReadUpdateListener listener)
void addIIOReadWarningListener (final IIOReadWarningListener listener)
void removeIIOReadWarningListener (final IIOReadWarningListener listener)
void addIIOWriteProgressListener (final IIOWriteProgressListener listener)
void removeIIOWriteProgressListener (final IIOWriteProgressListener listener)
void addIIOWriteWarningListener (final IIOWriteWarningListener listener)
void removeIIOWriteWarningListener (final IIOWriteWarningListener listener)
EventListener [] getReadListeners ()
EventListener [] getWriteListeners ()
void addListenersTo (final ImageReader reader)
void addListenersTo (final ImageWriter writer)
void removeListenersFrom (final ImageReader reader)
void removeListenersFrom (final ImageWriter writer)
Private Member Functions
EventListener [] getListeners (final Class<?>[] categories)
Returns all listeners of the given classes.
void manageListeners (final ImageReader reader, final boolean add)
void manageListeners (final ImageWriter writer, final boolean add)
Private Attributes
final List listeners = new List()
List of listeners.
Static Private Attributes
static final long serialVersionUID = 3747976429353858766L
For compatibility with different versions.
static final Class<?> [] READ
The listener categories for read operations.
static final Class<?> [] WRITE
The listener categories for read operations.
Detailed Description
A container of image I/O listeners.
This class provides a set of
addFooListener(...)
and
removeFooListener(...)
methods for adding and removing various listeners, and a
addListenersTo(...)
method for copying listeners to the an image reader. This class is convenient when
ImageReader.addFooListener(...)
can't be invoked directly because the ImageReader instance is not yet know or available.
Author
Martin Desruisseaux (IRD, Geomatys)
Version
3.10
Since
2.1
Constructor & Destructor Documentation
IIOListeners()
IIOListeners ()
Creates a new instance of.
IIOListeners
.
{
     }
Member Function Documentation
addIIOReadProgressListener()
void addIIOReadProgressListener (final IIOReadProgressListener listener)
Adds an.
IIOReadProgressListener
to the list of registered progress listeners.
Parameters
listener The listener to add.
{
         listeners.add(IIOReadProgressListener.class, listener);
     }
addIIOReadUpdateListener()
void addIIOReadUpdateListener (final IIOReadUpdateListener listener)
{
         listeners.add(IIOReadUpdateListener.class, listener);
     }
addIIOReadWarningListener()
void addIIOReadWarningListener (final IIOReadWarningListener listener)
{
         listeners.add(IIOReadWarningListener.class, listener);
     }
addIIOWriteProgressListener()
void addIIOWriteProgressListener (final IIOWriteProgressListener listener)
{
         listeners.add(IIOWriteProgressListener.class, listener);
     }
addIIOWriteWarningListener()
void addIIOWriteWarningListener (final IIOWriteWarningListener listener)
{
         listeners.add(IIOWriteWarningListener.class, listener);
     }
addListenersTo() [1/2]
void addListenersTo (final ImageReader reader)
References IIOListeners.manageListeners().
{
         manageListeners(reader, true);
     }
addListenersTo() [2/2]
void addListenersTo (final ImageWriter writer)
References IIOListeners.manageListeners().
{
         manageListeners(writer, true);
     }
getListeners()
EventListener [] getListeners (final Class<?> [] categories) private
Returns all listeners of the given classes.
Referenced by IIOListeners.getReadListeners(), and IIOListeners.getWriteListeners().
{
         int   count = 0;
         final Object[] list = listeners.getListenerList();
         final EventListener[] listeners = new EventListener[list.length/2];
    add: for (int i=0; i<list.length; i+=2) {
             final Class<?> type = (Class<?>) list[i];
             for (int j=categories.length; --j>=0;) {
                 if (type.equals(categories[i])) {
                     /*
                      * Found a listener in one of the specified categories.
                      * Ensure that it was not already added in the list.
                      */
                     final EventListener candidate = (EventListener) list[i+1];
                     for (int k=count; --k>=0;) {
                         if (listeners[k] == candidate) {
                             // Avoid duplication.
                             continue add;
                         }
                     }
                     listeners[count++] = candidate;
                     continue add;
                 }
             }
         }
         return ArraysExt.resize(listeners, count);
     }
getReadListeners()
EventListener [] getReadListeners ()
References IIOListeners.getListeners().
{
         return getListeners(READ);
     }
getWriteListeners()
EventListener [] getWriteListeners ()
References IIOListeners.getListeners().
{
         return getListeners(WRITE);
     }
manageListeners() [1/2]
void manageListeners (final ImageReader reader, final boolean add) private
Referenced by IIOListeners.addListenersTo(), and IIOListeners.removeListenersFrom().
{
         final Object[] listeners = this.listeners.getListenerList();
         for (int i=0; i<listeners.length;) {
             final Object classe   = listeners[i++];
             final Object listener = listeners[i++];
             if (classe == IIOReadProgressListener.class) {
                 final IIOReadProgressListener l = (IIOReadProgressListener) listener;
                 reader.removeIIOReadProgressListener(l); // Ensure singleton
                 if (add) reader.addIIOReadProgressListener(l);
                 continue;
             }
             if (classe == IIOReadUpdateListener.class) {
                 final IIOReadUpdateListener l = (IIOReadUpdateListener) listener;
                 reader.removeIIOReadUpdateListener(l); // Ensure singleton
                 if (add) reader.addIIOReadUpdateListener(l);
                 continue;
             }
             if (classe == IIOReadWarningListener.class) {
                 final IIOReadWarningListener l = (IIOReadWarningListener) listener;
                 reader.removeIIOReadWarningListener(l); // Ensure singleton
                 if (add) reader.addIIOReadWarningListener(l);
                 continue;
             }
         }
     }
manageListeners() [2/2]
void manageListeners (final ImageWriter writer, final boolean add) private
{
         final Object[] listeners = this.listeners.getListenerList();
         for (int i=0; i<listeners.length;) {
             final Object classe   = listeners[i++];
             final Object listener = listeners[i++];
             if (classe == IIOWriteProgressListener.class) {
                 final IIOWriteProgressListener l = (IIOWriteProgressListener) listener;
                 writer.removeIIOWriteProgressListener(l); // Ensure singleton
                 if (add) writer.addIIOWriteProgressListener(l);
                 continue;
             }
             if (classe == IIOWriteWarningListener.class) {
                 final IIOWriteWarningListener l = (IIOWriteWarningListener) listener;
                 writer.removeIIOWriteWarningListener(l); // Ensure singleton
                 if (add) writer.addIIOWriteWarningListener(l);
                 continue;
             }
         }
     }
removeIIOReadProgressListener()
void removeIIOReadProgressListener (final IIOReadProgressListener listener)
{
         listeners.remove(IIOReadProgressListener.class, listener);
     }
removeIIOReadUpdateListener()
void removeIIOReadUpdateListener (final IIOReadUpdateListener listener)
{
         listeners.remove(IIOReadUpdateListener.class, listener);
     }
removeIIOReadWarningListener()
void removeIIOReadWarningListener (final IIOReadWarningListener listener)
{
         listeners.remove(IIOReadWarningListener.class, listener);
     }
removeIIOWriteProgressListener()
void removeIIOWriteProgressListener (final IIOWriteProgressListener listener)
{
         listeners.remove(IIOWriteProgressListener.class, listener);
     }
removeIIOWriteWarningListener()
void removeIIOWriteWarningListener (final IIOWriteWarningListener listener)
{
         listeners.remove(IIOWriteWarningListener.class, listener);
     }
removeListenersFrom() [1/2]
void removeListenersFrom (final ImageReader reader)
References IIOListeners.manageListeners().
{
         manageListeners(reader, false);
     }
removeListenersFrom() [2/2]
void removeListenersFrom (final ImageWriter writer)
References IIOListeners.manageListeners().
{
         manageListeners(writer, false);
     }
setListeners()
void setListeners (final IIOListeners other)
Sets the list of listeners in this object to the same listeners than the given object.
Any listeners previously hold by this
IIOListeners
are discarded.
Parameters
other The other object from which to copy the list of listeners.
Since
3.10
References IIOListeners.listeners, and IIOListeners.List.setTo().
{
         listeners.setTo(other.listeners);
     }
Member Data Documentation
listeners
final List listeners = new List() private
List of listeners.
Referenced by IIOListeners.setListeners().
READ
final Class<?> [] READ static private
Initial value:
= {
        IIOReadProgressListener.class,
        IIOReadWarningListener .class,
        IIOReadUpdateListener  .class
    }
The listener categories for read operations.
serialVersionUID
final long serialVersionUID = 3747976429353858766L static private
For compatibility with different versions.
WRITE
final Class<?> [] WRITE static private
Initial value:
= {
        IIOWriteProgressListener.class,
        IIOWriteWarningListener .class
    }
The listener categories for read operations.