jena-geo: Trees Class Reference
Trees Class Reference
Convenience static methods for trees operations.
Static Public Member Functions
static Object getUserObject (final TreeNode node)
Returns the user object from the given tree node.
static TreePath [] getPathsToUserObject (final TreeModel model, final Object value)
Returns the path to the specified org.geotoolkit.gui.swing.tree.TreeNode::getUserObject user object}.
static MutableTreeNode objectToSwing (final Object object)
Returns a tree representation of the given object.
static MutableTreeNode xmlToSwing (final Node node)
Creates a Swing root tree node from a XML root tree node.
static MutableTreeNode copy (final TreeNode node)
Returns a copy of the tree starting at the given node.
static MutableTreeNode copy (final TreeNode node, final TreeNodeFilter filter)
Returns a copy of a subset of the tree starting at the given node.
static String toString (final TreeModel tree)
Returns a graphical representation of the specified tree model.
static String toString (final TreeNode node)
Returns a graphical representation of the specified tree.
Private Member Functions
Trees ()
Do not allows instantiation of this class.
Static Private Member Functions
static Object [] getPathsToUserObject (final TreeModel model, final Object value, Object[] path, final int length, final List< TreePath > list)
Implementation of the path search.
Detailed Description
Convenience static methods for trees operations.
This class provides methods for performing a copy copy} of a tree and for xmlToSwing converting from XML}. It can also #print print} a tree in a format like the following example:
{ text Node #1 ├───Node #2 │ └───Node #4 └───Node #3 }
Author
Martin Desruisseaux (IRD, Geomatys)
Version
3.18
Since
2.0
Deprecated:
The org.apache.sis.util.collection.TreeTable tree model in Apache SIS} is no longer based on Swing tree interfaces. Swing dependencies will be phased out since Swing itself is likely to be replaced by JavaFX in future JDK versions.
Constructor & Destructor Documentation
Trees()
Trees () private
Do not allows instantiation of this class.
                     {
     }
Member Function Documentation
copy() [1/2]
static MutableTreeNode copy (final TreeNode node) static
Returns a copy of the tree starting at the given node.
The references to the org.geotoolkit.gui.swing.tree.TreeNode::getUserObject() user objects} (if any) and the org.geotoolkit.gui.swing.tree.TreeNode::toString() string representations} are copied verbalism.
Parameters
node The tree to copy (may be
null
).
Returns
A mutable copy of the given tree, or
null
if the given tree was null.
Since
2.5
Referenced by Trees.copy().
{
         return copy(node, null);
     }
copy() [2/2]
static MutableTreeNode copy (final TreeNode node, final TreeNodeFilter filter) static
Returns a copy of a subset of the tree starting at the given node.
The references to the org.geotoolkit.gui.swing.tree.TreeNode::getUserObject() user objects} in the copied nodes can be modified by the filter.
Parameters
node The tree to copy (may be
null
).
filter An object filtering the node to copy, or
null
if none.
Returns
A mutable copy of the given tree, or
null
if the given tree was null or if the given node is not TreeNodeFilter::accept accepted} by the filter.
Since
3.04
References TreeNodeFilter.accept(), TreeNode.children(), TreeNodeFilter.convertUserObject(), Trees.copy(), Trees.getUserObject(), and TreeNode.toString().
{
         if (node == null || (filter != null && !filter.accept(node))) {
             return null;
         }
         final String label = node.toString();
         Object userObject = getUserObject(node);
         if (filter != null) {
             userObject = filter.convertUserObject(node, userObject);
         }
         final boolean allowsChildren = node.getAllowsChildren();
         final DefaultMutableTreeNode target;
         if (userObject == null || userObject == label) {
             target = new DefaultMutableTreeNode(label, allowsChildren);
         } else {
             target = new NamedTreeNode(label, userObject, allowsChildren);
         }
         @SuppressWarnings("unchecked")
         final Enumeration<? extends TreeNode> children = node.children();
         if (children != null) {
             while (children.hasMoreElements()) {
                 final MutableTreeNode child = copy(children.nextElement(), filter);
                 if (child != null) {
                     target.add(child);
                 }
             }
         }
         return target;
     }
getPathsToUserObject() [1/2]
static TreePath [] getPathsToUserObject (final TreeModel model, final Object value) static
Returns the path to the specified org.geotoolkit.gui.swing.tree.TreeNode::getUserObject user object}.
For each tree node which are actually instance of Geotk org.geotoolkit.gui.swing.tree.TreeNode, this method compares the specified
value
against the user object returned by the org.geotoolkit.gui.swing.tree.TreeNode#getUserObject method.
Parameters
model The tree model to inspect.
value User object to compare to org.geotoolkit.gui.swing.tree.TreeNode#getUserObject.
Returns
The paths to the specified value, or an empty array if none.
Referenced by Trees.getPathsToUserObject().
{
         final List<TreePath> paths = new ArrayList<>(8);
         final Object[] path = new Object[8];
         path[0] = model.getRoot();
         getPathsToUserObject(model, value, path, 1, paths);
         return paths.toArray(new TreePath[paths.size()]);
     }
getPathsToUserObject() [2/2]
static Object [] getPathsToUserObject (final TreeModel model, final Object value, Object [] path, final int length, final List< TreePath > list) static private
Implementation of the path search.
This method invokes itself recursively.
Parameters
model The tree model in which to search for a path.
value The expected org.geotoolkit.gui.swing.tree.TreeNode#getUserObject().
path The path found up to date.
length The number of valid elements in the
path
array.
list Where to add new TreePath as they are found.
Returns
path
, or a new array if it was necessary to increase its size.
References Trees.getPathsToUserObject().
     {
         final Object parent = path[length-1];
         if (parent instanceof org.geotoolkit.gui.swing.tree.TreeNode) {
             final Object nodeValue = ((org.geotoolkit.gui.swing.tree.TreeNode) parent).getUserObject();
             if (nodeValue == value || (value!=null && value.equals(nodeValue))) {
                 list.add(new TreePath(ArraysExt.resize(path, length)));
             }
         }
         final int count = model.getChildCount(parent);
         for (int i=0; i<count; i++) {
             if (length >= path.length) {
                 path = Arrays.copyOf(path, length << 1);
             }
             path[length] = model.getChild(parent, i);
             path = getPathsToUserObject(model, value, path, length+1, list);
         }
         return path;
     }
getUserObject()
static Object getUserObject (final TreeNode node) static
Returns the user object from the given tree node.
If the given node is an instance of Geotk org.geotoolkit.gui.swing.tree.TreeNode, then its getUserObject() method is invoked. Otherwise if the given node is an instance of Java javax.swing.tree.DefaultMutableTreeNode, then its getUserObject() method is invoked. Otherwise this method returns
null
.
Parameters
node The node for which to get the user object, or
null
.
Returns
The user object, or
null
if none.
Since
3.00
Referenced by Trees.copy().
{
         if (node instanceof org.geotoolkit.gui.swing.tree.TreeNode) {
             return ((org.geotoolkit.gui.swing.tree.TreeNode) node).getUserObject();
         }
         if (node instanceof javax.swing.tree.DefaultMutableTreeNode) {
             return ((javax.swing.tree.DefaultMutableTreeNode) node).getUserObject();
         }
         return null;
     }
objectToSwing()
static MutableTreeNode objectToSwing (final Object object) static
Returns a tree representation of the given object.
This method processes the following types especially:
If the given object is an instance of Node, then this method delegates to xmlToSwing(Node).
If the given object is an instance of Iterable, Map or an array, then a node is created with the name of the implemented interface (for example
"List"
or
"Set"
) and each iterated elements is added as a child of the above-cited node.
If the given object is an instance of java.util.Map.Entry, then this method returns a NamedTreeNode which contain the entry key as the NamedTreeNode::getName() name} and the entry value as TreeNode::getUserObject() user object}.
Otherwise this method returns a single DefaultMutableTreeNode which contain the given object as TreeNode::getUserObject() user object}.
Together with toString(TreeNode), this method provides a convenient way to print the content of a XML document for debugging purpose.
Parameters
object The array, collection or single object to format.
Returns
The given object as a Swing tree.
Since
3.17
References Trees.xmlToSwing().
{
         final DefaultMutableTreeNode node;
         Iterator<?> iterator = null;
         Class<?> baseInterface = null;
         if (object instanceof Iterable<?>) {
             baseInterface = Iterable.class;
             iterator = ((Iterable<?>) object).iterator();
         } else if (object instanceof Map<?,?>) {
             baseInterface = Map.class;
             iterator = ((Map<?,?>) object).entrySet().iterator();
         }
         if (iterator != null) {
             final Class<?>[] types = Classes.getLeafInterfaces(object.getClass(), baseInterface);
             node = new DefaultMutableTreeNode(Classes.getShortName(types.length != 0 ? types[0] : null));
             while (iterator.hasNext()) {
                 node.add(objectToSwing(iterator.next()));
             }
         } else {
             if (object.getClass().isArray()) {
                 node = new DefaultMutableTreeNode("Array");
                 final int length = Array.getLength(object);
                 for (int i=0; i<length; i++) {
                     node.add(objectToSwing(Array.get(object, i)));
                 }
             } else if (object instanceof Node) {
                 return xmlToSwing((Node) object);
             } else {
                 if (object instanceof Map.Entry<?,?>) {
                     final Map.Entry<?,?> entry = (Map.Entry<?,?>) object;
                     node = new NamedTreeNode(String.valueOf(entry.getKey()), entry.getValue());
                 } else {
                     node = new DefaultMutableTreeNode(object);
                 }
                 node.setAllowsChildren(false);
             }
         }
         return node;
     }
toString() [1/2]
static String toString (final TreeModel tree) static
Returns a graphical representation of the specified tree model.
This representation can be printed to the System::out standard output stream} (for example) if it uses a monospaced font and supports unicode.
Parameters
tree The tree to format.
Returns
A string representation of the tree.
References TreeFormat.format(), and TreeFormat.setTableFormatEnabled().
Referenced by DefaultTreeModel.toString().
{
         final TreeFormat tf = new TreeFormat();
         tf.setTableFormatEnabled(true);
         final StringBuilder buffer = new StringBuilder();
         tf.format(tree, buffer);
         return buffer.toString();
     }
toString() [2/2]
static String toString (final TreeNode node) static
Returns a graphical representation of the specified tree.
This representation can be printed to the System::out standard output stream} (for example) if it uses a monospaced font and supports unicode.
Parameters
node The root node of the tree to format.
Returns
A string representation of the tree.
References TreeFormat.format(), and TreeFormat.setTableFormatEnabled().
{
         final TreeFormat tf = new TreeFormat();
         tf.setTableFormatEnabled(true);
         final StringBuilder buffer = new StringBuilder();
         tf.format(node, buffer);
         return buffer.toString();
     }
xmlToSwing()
static MutableTreeNode xmlToSwing (final Node node) static
Creates a Swing root tree node from a XML root tree node.
Together with toString(TreeNode), this method provides a convenient way to print the content of a XML document for debugging purpose.
Parameters
node The XML root node.
Returns
The given XML node as a Swing node.
Referenced by Trees.objectToSwing().
{
         String label = node.getNodeName();
         final String value = node.getNodeValue();
         if (value != null) {
             label += "=\"" + value + '"';
         }
         final DefaultMutableTreeNode root = new NamedTreeNode(label, node);
         final NamedNodeMap attributes = node.getAttributes();
         if (attributes != null) {
             final int length = attributes.getLength();
             for (int i=0; i<length; i++) {
                 final Node attribute = attributes.item(i);
                 if (attribute != null) {
                     label = attribute.getNodeName() + "=\"" + attribute.getNodeValue() + '"';
                     root.add(new NamedTreeNode(label, attribute, false));
                 }
             }
         }
         for (Node child=node.getFirstChild(); child!=null; child=child.getNextSibling()) {
             root.add(xmlToSwing(child));
         }
         return root;
     }