jena-geo: MutableTreeNode Interface Reference
MutableTreeNode Interface Reference
Defines the requirements for a tree node object that can change.
Public Member Functions
Object getUserObject ()
Returns this node's user object.
Enumeration<? extends javax.swing.tree.TreeNode > children ()
Returns the children of this node as an.
String toString ()
Returns a string representation of this node suitable for a user interface.
Detailed Description
Defines the requirements for a tree node object that can change.
It may changes by adding or removing child nodes, or by changing the contents of a user object stored in the node.
This interface inherits the getUserObject() method from Geotk TreeNode. This is needed because the Swing javax.swing.tree.MutableTreeNode interface defines a setUserObject(Object) method but doesn't define or inherit any
getUserObject()
.
Author
Martin Desruisseaux (IRD)
Version
3.00
Since
2.0
Member Function Documentation
children()
Enumeration<? extends javax.swing.tree.TreeNode> children () inherited
Returns the children of this node as an.
Enumeration
.
Returns
The children.
Referenced by Trees.copy(), and TreeFormat.hasTreeTableNode().
getUserObject()
Object getUserObject () inherited
Returns this node's user object.
Returns
the Object stored at this node by the user
toString()
String toString () inherited
Returns a string representation of this node suitable for a user interface.
javax.swing.JTree uses this method for formatting the text to display in the widget.
Returns
The text to display in the
JTree
for this node.
Implemented in NamedTreeNode, and DefaultMutableTreeNode.
Referenced by Trees.copy().