jena-geo: TreeFormat Class Reference
TreeFormat Class Reference
A formatter for a tree of nodes.
Public Member Functions
TreeFormat ()
Creates a new format.
int getIndentation ()
Returns the number of spaces to add on the left margin for each indentation level.
void setIndentation (final int indentation) throws IllegalArgumentException
Sets the number of spaces to add on the left margin for each indentation level.
int getVerticalLinePosition ()
Returns the position of the vertical line, relative to the position of the root label.
void setVerticalLinePosition (final int verticalLinePosition) throws IllegalArgumentException
Sets the position of the vertical line, relative to the position of the root label.
String getLineSeparator ()
Returns the current line separator.
void setLineSeparator (final String separator)
Sets the line separator.
char getColumnSeparator ()
Returns the character used as column separator.
void setColumnSeparator (final char separator)
Sets the column character to insert between the columns in a TreeTableNode.
boolean isTableFormatEnabled ()
Returns.
void setTableFormatEnabled (final boolean enabled)
Sets whatever this.
void format (final TreeModel tree, final Appendable toAppendTo) throws IOException
Writes a graphical representation of the specified tree model in the given buffer.
final void format (final TreeModel tree, final StringBuilder toAppendTo)
Convenience method which delegate to the above format(TreeModel, Appendable) method, but without throwing IOException.
void format (final TreeNode node, final Appendable toAppendTo) throws IOException
Writes a graphical representation of the specified tree in the given buffer.
final void format (final TreeNode node, final StringBuilder toAppendTo)
Convenience method which delegate to the above format(TreeNode, Appendable) method, but without throwing IOException.
void format (final Iterable<?> nodes, final Appendable toAppendTo) throws IOException
Writes a graphical representation of the specified elements in the given buffer.
final void format (final Iterable<?> nodes, final StringBuilder toAppendTo)
Convenience method which delegate to the above format(Iterable, Appendable) method, but without throwing IOException.
StringBuffer format (final Object tree, final StringBuffer toAppendTo, final FieldPosition pos)
Writes a graphical representation of the specified tree in the given buffer.
Package Attributes
transient String treeLine
transient String treeCross
transient String treeEnd
Private Member Functions
void clearTreeSymbols ()
Clears the symbols used when writing the tree.
void ensureInitialized ()
Computes the.
String toString (final Object value) throws IOException
Returns a string representation of the given value, or.
boolean [] format (final TreeModel model, final Object node, final Appendable toAppendTo, final int level, boolean[] last) throws IOException
Appends to the given buffer the string representation of the given node and all its children.
Static Private Member Functions
static boolean hasTreeTableNode (final TreeNode node)
Returns.
Private Attributes
int indentation
The number of spaces to add on the left margin for each indentation level.
int verticalLinePosition
The position of the vertical line, relative to the position of the root label.
String lineSeparator
The line separator to use for formatting the tree.
char columnSeparator = '…'
The column separator to use if the table format is enabled.
boolean isTableFormatEnabled
transient String treeBlank
The tree symbols to write in the left margin, or.
transient Writer lineWriter
The writer to use for formatting a possible multi-line text to a monoline text.
transient StringBuffer lineBuffer
The buffer which is backing lineWriter.
Detailed Description
A formatter for a tree of nodes.
Deprecated:
The org.apache.sis.util.collection.TreeTable tree model in Apache SIS} is no longer based on Swing tree interfaces. Swing dependencies will be phased out since Swing itself is likely to be replaced by JavaFX in future JDK versions.
Constructor & Destructor Documentation
TreeFormat()
TreeFormat ()
Creates a new format.
{
         indentation = 4;
         lineSeparator = System.lineSeparator();
     }
Member Function Documentation
clearTreeSymbols()
void clearTreeSymbols () private
Clears the symbols used when writing the tree.
They will be computed again when first needed.
Referenced by TreeFormat.setIndentation(), and TreeFormat.setVerticalLinePosition().
{
         treeBlank = null;
         treeLine  = null;
         treeCross = null;
         treeEnd   = null;
     }
ensureInitialized()
void ensureInitialized () private
Computes the.
tree*
fields, if needed. This is done only when first needed.
References TreeFormat.indentation, and TreeFormat.verticalLinePosition.
Referenced by TreeFormat.format().
{
         if (treeBlank == null) {
             final int indentation = this.indentation;
             final int verticalLinePosition = this.verticalLinePosition;
             final char[] buffer = new char[indentation];
             for (int k=0; k<4; k++) {
                 final char vc, hc;
                 if ((k & 2) == 0) {
                     // No horizontal line
                     vc = (k & 1) == 0 ? '\u00A0' : '\u2502';
                     hc = '\u00A0';
                 } else {
                     // With a horizontal line
                     vc = (k & 1) == 0 ? '\u2514' : '\u251C';
                     hc = '\u2500';
                 }
                 Arrays.fill(buffer, 0, verticalLinePosition, '\u00A0');
                 buffer[verticalLinePosition] = vc;
                 Arrays.fill(buffer, verticalLinePosition + 1, indentation, hc);
                 final String symbols = String.valueOf(buffer);
                 switch (k) {
                     case 0: treeBlank = symbols; break;
                     case 1: treeLine  = symbols; break;
                     case 2: treeEnd   = symbols; break;
                     case 3: treeCross = symbols; break;
                     default: throw new AssertionError(k);
                 }
             }
         }
     }
format() [1/8]
boolean [] format (final TreeModel model, final Object node, final Appendable toAppendTo, final int level, boolean [] last) throws IOException private
Appends to the given buffer the string representation of the given node and all its children.
This method invokes itself recursively.
Parameters
model The tree to format.
node The node of the tree to format.
toAppendTo Where to write the string representation.
level Indentation level. The first level is 0.
last
References TreeTableNode.getColumnCount(), TreeTableNode.getValueAt(), and TreeFormat.toString().
Referenced by TreeFormat.format(), and Trees.toString().
     {
         for (int i=0; i<level; i++) {
             final boolean isLast = last[i];
             toAppendTo.append((i != level-1)
                     ? (isLast ? treeBlank : treeLine)
                     : (isLast ? treeEnd   : treeCross));
         }
         if ((node instanceof TreeTableNode) && (toAppendTo instanceof TableAppender)) {
             final TreeTableNode tableNode = (TreeTableNode) node;
             final int columnCount = tableNode.getColumnCount();
             for (int i=0; i<columnCount; i++) {
                 if (i != 0) {
                     ((TableAppender) toAppendTo.append(columnSeparator)).nextColumn(columnSeparator);
                 }
                 final Object value = tableNode.getValueAt(i);
                 if (value != null) {
                     toAppendTo.append(toString(value));
                 }
             }
         } else {
             toAppendTo.append(toString(node));
         }
         toAppendTo.append(lineSeparator);
         if (level >= last.length) {
             last = Arrays.copyOf(last, level*2);
         }
         final int count = model.getChildCount(node);
         for (int i=0; i<count; i++) {
             last[level] = (i == count-1);
             last = format(model, model.getChild(node, i), toAppendTo, level+1, last);
         }
         return last;
     }
format() [2/8]
void format (final TreeModel tree, final Appendable toAppendTo) throws IOException
Writes a graphical representation of the specified tree model in the given buffer.
This method iterates recursively over all children. Each children is fetched by a call to TreeModel#getChild(Object, int) and its string representation (expected to uses a single line) is created by a call to String#valueOf(Object).
Parameters
tree The tree to format.
toAppendTo Where to format the tree.
Exceptions
IOException If an error occurred while writing in the given appender.
See also
Trees::toString(TreeModel)
References TreeFormat.ensureInitialized(), TreeFormat.format(), and TreeFormat.hasTreeTableNode().
{
         final Object root = tree.getRoot();
         if (root != null) {
             Writer buffer = null;
             Appendable out = toAppendTo;
             if (isTableFormatEnabled && (root instanceof TreeNode) && hasTreeTableNode((TreeNode) root)) {
                 final Writer writer;
                 if (toAppendTo instanceof Writer) {
                     writer = (Writer) toAppendTo;
                 } else {
                     writer = buffer = new StringWriter();
                 }
                 out = new TableAppender(new LineWriter(writer, lineSeparator), " ");
             }
             ensureInitialized();
             format(tree, root, out, 0, new boolean[64]);
             if (out != toAppendTo) {
                 ((Flushable) out).flush(); // Needed for writing the table content.
             }
             if (buffer != null) {
                 toAppendTo.append(buffer.toString());
             }
         }
     }
format() [3/8]
final void format (final TreeModel tree, final StringBuilder toAppendTo)
Convenience method which delegate to the above format(TreeModel, Appendable) method, but without throwing IOException.
The I/O exception should never occur since we are writing in a StringBuilder.
{
Note
Strictly speaking, an IOException could still occur in the user overrides the above format method and performs some I/O operation outside the given StringBuilder. However this is not the intended usage of this class and implementors should avoid such unexpected I/O operation.}
Parameters
tree The tree to format.
toAppendTo Where to format the tree.
References TreeFormat.format().
{
         try {
             format(tree, (Appendable) toAppendTo);
         } catch (IOException e) {
             // Should never occur, unless the user overriden the above 'format'
             // method in a weird way. This is why we don't use AssertionError.
             throw new BackingStoreException(e);
         }
     }
format() [4/8]
void format (final TreeNode node, final Appendable toAppendTo) throws IOException
Writes a graphical representation of the specified tree in the given buffer.
The default implementation delegates to format(TreeModel, Appendable).
Parameters
node The root node of the tree to format.
toAppendTo Where to format the tree.
Exceptions
IOException If an error occurred while writing in the given appender.
See also
Trees::toString(TreeNode)
References TreeFormat.format().
{
         // Use the Swing implementation in order to avoid recursivity
         // in the debugguer if the tree model is formatted as a tree.
         format(new DefaultTreeModel(node, true), toAppendTo);
     }
format() [5/8]
final void format (final TreeNode node, final StringBuilder toAppendTo)
Convenience method which delegate to the above format(TreeNode, Appendable) method, but without throwing IOException.
The I/O exception should never occur since we are writing in a StringBuilder.
{
Note
Strictly speaking, an IOException could still occur in the user overrides the above format method and performs some I/O operation outside the given StringBuilder. However this is not the intended usage of this class and implementors should avoid such unexpected I/O operation.}
Parameters
node The root node of the tree to format.
toAppendTo Where to format the tree.
References TreeFormat.format().
{
         try {
             format(node, (Appendable) toAppendTo);
         } catch (IOException e) {
             // Should never occur, unless the user overriden the above 'format'
             // method in a weird way. This is why we don't use AssertionError.
             throw new BackingStoreException(e);
         }
     }
format() [6/8]
void format (final Iterable<?> nodes, final Appendable toAppendTo) throws IOException
Writes a graphical representation of the specified elements in the given buffer.
This method iterates over the given collection and invokes the String#valueOf(Object) method for each element. The
String
value can span multiple lines.
{
label}
This method formats only the given child elements. It does not format anything for the root. It is up to the caller to format a root label on its own line before to invoke this method.
{
}
This method does not perform any check on the element types. In particular, elements of type TreeModel, TreeNode or inner Iterable are not processed recursively. It is up to the
toString()
implementation of each element to invoke this
format
method recursively if they wish (this method is safe for this purpose).
Parameters
nodes A collection of nodes to format.
toAppendTo Where to format the tree.
Exceptions
IOException If an error occurred while writing in the given appender.
See also
Trees::toString(String, Iterable)
References TreeFormat.ensureInitialized(), TreeFormat.treeBlank, TreeFormat.treeCross, TreeFormat.treeEnd, and TreeFormat.treeLine.
{
         ensureInitialized();
         final Iterator<?> it = nodes.iterator();
         boolean hasNext = it.hasNext();
         while (hasNext) {
             final CharSequence[] lines = CharSequences.splitOnEOL(String.valueOf(it.next()));
             hasNext = it.hasNext();
             final String next;
             String margin;
             if (hasNext) {
                 margin = treeCross;
                 next   = treeLine;
             } else {
                 margin = treeEnd;
                 next   = treeBlank;
             }
             for (final CharSequence line : lines) {
                 if (line.length() != 0) {
                     toAppendTo.append(margin).append(line).append(lineSeparator);
                     margin = next;
                 }
             }
         }
     }
format() [7/8]
final void format (final Iterable<?> nodes, final StringBuilder toAppendTo)
Convenience method which delegate to the above format(Iterable, Appendable) method, but without throwing IOException.
The I/O exception should never occur since we are writing in a StringBuilder.
{
Note
Strictly speaking, an IOException could still occur in the user overrides the above format method and performs some I/O operation outside the given StringBuilder. However this is not the intended usage of this class and implementors should avoid such unexpected I/O operation.}
Parameters
nodes A collection of nodes to format.
toAppendTo Where to format the tree.
References TreeFormat.format().
{
         try {
             format(nodes, (Appendable) toAppendTo);
         } catch (IOException e) {
             // Should never occur, unless the user overriden the above 'format'
             // method in a weird way. This is why we don't use AssertionError.
             throw new BackingStoreException(e);
         }
     }
format() [8/8]
StringBuffer format (final Object tree, final StringBuffer toAppendTo, final FieldPosition pos)
Writes a graphical representation of the specified tree in the given buffer.
The default implementation delegates to one of the following method depending on the type of the given tree:
format(TreeModel, Appendable)
format(TreeNode, Appendable)
format(Iterable, Appendable)
Parameters
tree The tree to format.
toAppendTo Where to format the tree.
pos Ignored in current implementation.
Returns
The given buffer, returned for convenience.
References TreeFormat.format(), Errors.format(), and Errors.Keys.IllegalArgumentClass_3.
{
         ArgumentChecks.ensureNonNull("tree", tree);
         try {
             if (tree instanceof TreeModel) {
                 format((TreeModel) tree, toAppendTo);
             } else if (tree instanceof TreeNode) {
                 format((TreeNode) tree, toAppendTo);
             } else if (tree instanceof Iterable<?>) {
                 format((Iterable<?>) tree, toAppendTo);
             } else {
                 throw new IllegalArgumentException(Errors.format(Errors.Keys.IllegalArgumentClass_3,
                         "tree", tree.getClass(), TreeModel.class));
             }
         } catch (IOException e) {
             // Should never happen when writing into a StringBuffer.
             throw new AssertionError(e);
         }
         return toAppendTo;
     }
getColumnSeparator()
char getColumnSeparator ()
Returns the character used as column separator.
This character will be inserted between the columns only if the isTableFormatEnabled() table format is enabled} and the tree to format contains TreeTableNode elements.
The default value if '…'.
Returns
The column separator.
Since
3.19
References TreeFormat.columnSeparator.
{
         return columnSeparator;
     }
getIndentation()
int getIndentation ()
Returns the number of spaces to add on the left margin for each indentation level.
The default value is 4.
Returns
The current indentation.
References TreeFormat.indentation.
{
         return indentation;
     }
getLineSeparator()
String getLineSeparator ()
Returns the current line separator.
The default value is system-dependent.
Returns
The current line separator.
References TreeFormat.lineSeparator.
{
         return lineSeparator;
     }
getVerticalLinePosition()
int getVerticalLinePosition ()
Returns the position of the vertical line, relative to the position of the root label.
The default value is 0, which means that the vertical line is drawn below the first letter of the root label.
Returns
The current vertical line position.
References TreeFormat.verticalLinePosition.
{
         return verticalLinePosition;
     }
hasTreeTableNode()
static boolean hasTreeTableNode (final TreeNode node) static private
Returns.
true
if the given tree should be formatted as a tree table. The current implementation returns
true
if the given tree contains at least one node of kind TreeTableNode.
Parameters
node The root node to inspect.
Returns
false
if at least one tree table node was found.
References TreeNode.children().
Referenced by TreeFormat.format().
{
         if (node instanceof TreeTableNode) {
             return true;
         }
         final Enumeration<?> e = node.children();
         if (e != null) while (e.hasMoreElements()) {
             if (hasTreeTableNode((TreeNode) e.nextElement())) {
                 return true;
             }
         }
         return false;
     }
isTableFormatEnabled()
boolean isTableFormatEnabled ()
Returns.
true
if this
TreeFormat
is allowed to format the tree using many columns. The default value is
false
. Setting this property to
true
is useful only if the tree to format contains TreeTableNode elements.
Returns
true
if this
TreeFormat
object is allowed to format many columns.
Since
3.19
{
         return isTableFormatEnabled;
     }
setColumnSeparator()
void setColumnSeparator (final char separator)
Sets the column character to insert between the columns in a TreeTableNode.
Parameters
separator The column separator.
Since
3.19
{
         columnSeparator = separator;
     }
setIndentation()
void setIndentation (final int indentation) throws IllegalArgumentException
Sets the number of spaces to add on the left margin for each indentation level.
If the new indentation is smaller than the getVerticalLinePosition() vertical line position}, then the later is also set to the given indentation value.
Parameters
indentation The new indentation.
Exceptions
IllegalArgumentException If the given value is negative.
References TreeFormat.clearTreeSymbols(), and TreeFormat.indentation.
{
         ArgumentChecks.ensurePositive("indentation", indentation);
         this.indentation = indentation;
         if (verticalLinePosition > indentation) {
             verticalLinePosition = indentation;
         }
         clearTreeSymbols();
     }
setLineSeparator()
void setLineSeparator (final String separator)
Sets the line separator.
Parameters
separator The new line separator.
{
         ArgumentChecks.ensureNonNull("separator", separator);
         lineSeparator = separator;
     }
setTableFormatEnabled()
void setTableFormatEnabled (final boolean enabled)
Sets whatever this.
TreeFormat
is allowed to format the tree as a table.
NOTE: parsing of table format is not yet implemented.
Parameters
enabled
Referenced by Trees.toString().
{
         isTableFormatEnabled = enabled;
     }
setVerticalLinePosition()
void setVerticalLinePosition (final int verticalLinePosition) throws IllegalArgumentException
Sets the position of the vertical line, relative to the position of the root label.
The given value can not be greater than the getIndentation() indentation}.
Parameters
verticalLinePosition The new vertical line position.
Exceptions
IllegalArgumentException If the given value is negative or greater than the indentation.
References TreeFormat.clearTreeSymbols(), and TreeFormat.verticalLinePosition.
{
         ArgumentChecks.ensureBetween("verticalLinePosition", 0, indentation, verticalLinePosition);
         this.verticalLinePosition = verticalLinePosition;
         clearTreeSymbols();
     }
toString()
String toString (final Object value) throws IOException private
Returns a string representation of the given value, or.
null
if the value is null. Tabulations are replaced by a single space, and line feeds are replaced by the Unicode "carriage return" character. This is necessary in order to avoid conflict with the characters expected by TableWriter.
References TreeFormat.lineWriter.
Referenced by TreeFormat.format().
{
         Writer writer = lineWriter;
         if (writer == null) {
             final StringWriter buffer = new StringWriter();
             lineWriter = writer = new ExpandedTabWriter(new LineWriter(buffer, " \u00B6 "));
             lineBuffer = buffer.getBuffer();
         }
         writer.write(String.valueOf(value));
         writer.flush();
         final String text = lineBuffer.toString();
         writer.write('\n'); // Reset tabulation count and discart trailing spaces.
         lineBuffer.setLength(0);
         return text;
     }
Member Data Documentation
columnSeparator
char columnSeparator = '…' private
The column separator to use if the table format is enabled.
Since
3.19
Referenced by TreeFormat.getColumnSeparator().
indentation
int indentation private
The number of spaces to add on the left margin for each indentation level.
The default value is 4.
Referenced by TreeFormat.ensureInitialized(), TreeFormat.getIndentation(), and TreeFormat.setIndentation().
isTableFormatEnabled
boolean isTableFormatEnabled private
true
for enabling the formating of tree tables. The default value is
false
.
Since
3.19
lineBuffer
transient StringBuffer lineBuffer private
The buffer which is backing lineWriter.
Since
3.19
lineSeparator
String lineSeparator private
The line separator to use for formatting the tree.
Referenced by TreeFormat.getLineSeparator().
lineWriter
transient Writer lineWriter private
The writer to use for formatting a possible multi-line text to a monoline text.
Will be created only when first needed.
Since
3.19
Referenced by TreeFormat.toString().
treeBlank
transient String treeBlank private
The tree symbols to write in the left margin, or.
null
if not yet computed. The default symbols are as below:
treeBlank =
"    "
treeLine =
"│   "
treeCross =
"├───"
treeEnd =
"└───"
Referenced by TreeFormat.format().
treeCross
transient String treeCross package
Referenced by TreeFormat.format().
treeEnd
transient String treeEnd package
Referenced by TreeFormat.format().
treeLine
transient String treeLine package
Referenced by TreeFormat.format().
verticalLinePosition
int verticalLinePosition private
The position of the vertical line, relative to the position of the root label.
The default value is 0, which means that the vertical line is drawn below the first letter of the root label.
Referenced by TreeFormat.ensureInitialized(), TreeFormat.getVerticalLinePosition(), and TreeFormat.setVerticalLinePosition().