jena-geo: SampleType Enum Reference
SampleType Enum Reference
Define internaly ColorModel data type.
Static Public Member Functions
static SampleType valueOf (int dataType)
Mapping between java.awt.image.SampleModel#getDataType() and org.geotoolkit.image.internal.SampleType enum.
static int valueOf (final SampleType sampleType)
Mapping between org.geotoolkit.image.internal.SampleType enum and java.awt.image.SampleModel#getDataType().
static SampleType valueOf (final int bitPerSample, final int sampleFormat)
Mapping between bits per sample and sample format with SampleType.
Public Attributes
BYTE
Data type Byte.
SHORT
Data type Short.
USHORT
Data type Short.
INTEGER
Data type Integer.
FLOAT
Data type Float.
Detailed Description
Define internaly ColorModel data type.
Author
Remi Marechal (Geomatys).
Member Function Documentation
valueOf() [1/3]
static SampleType valueOf (int dataType) static
Mapping between java.awt.image.SampleModel#getDataType() and org.geotoolkit.image.internal.SampleType enum.
Parameters
dataType integer from java.awt.image.DataBuffer constants
Returns
org.geotoolkit.image.internal.SampleType or null if type undefined.
Referenced by ImageUtils.buildImageTypeSpecifier(), ImageUtils.ComponentScaledColorModel.createCompatibleSampleModel(), ImageUtils.createSampleModel(), and LargeRenderedImage.LargeRenderedImage().
{
         switch (dataType) {
             case DataBuffer.TYPE_BYTE     : return BYTE;
             case DataBuffer.TYPE_SHORT    : return SHORT;
             case DataBuffer.TYPE_USHORT   : return USHORT;
             case DataBuffer.TYPE_INT      : return INTEGER;
             case DataBuffer.TYPE_FLOAT    : return FLOAT;
             case DataBuffer.TYPE_DOUBLE   : return DOUBLE;
             case DataBuffer.TYPE_UNDEFINED: //fall through
             default: return null;
         }
     }
valueOf() [2/3]
static int valueOf (final SampleType sampleType) static
Mapping between org.geotoolkit.image.internal.SampleType enum and java.awt.image.SampleModel#getDataType().
Parameters
sampleType enum from SampleType constantes.
Returns
DataBuffer#* or DataBuffer#TYPE_UNDEFINED if unknow SampleType.
{
         switch (sampleType) {
             case BYTE    : return DataBuffer.TYPE_BYTE;
             case SHORT   : return DataBuffer.TYPE_SHORT;
             case USHORT  : return DataBuffer.TYPE_USHORT;
             case INTEGER : return DataBuffer.TYPE_INT;
             case FLOAT   : return DataBuffer.TYPE_FLOAT;
             case DOUBLE  : return DataBuffer.TYPE_DOUBLE;
             default      : return DataBuffer.TYPE_UNDEFINED;
         }
     }
valueOf() [3/3]
static SampleType valueOf (final int bitPerSample, final int sampleFormat) static
Mapping between bits per sample and sample format with SampleType.
expected bitPerSamples values :
8(Byte)
16(Short or UShort)
32 (Int or Float)
64 (Double)
expected sampleFormat values :
1 for unsigned integer datas
2 for signed integer datas
3 for IEEE floating point<br>
Example :
UShort data : bitspersample = 16, sampleFormat = 1
Float data : bitspersample = 32, sampleformat = 3
Note : for bitpersample = 8, and bitspersample = 64, sampleFormat is ignored the only available SampleType are respectively SampleType#BYTE and SampleType#DOUBLE. Moreover for each unknow combination bitPerSample, sampleFormat this method return
null
.
Parameters
bitPerSample bitPerSample bit number by sample.
sampleFormat integer to define floating, signed or unsigned type data.
Returns
org.geotoolkit.image.internal.SampleType or null if type undefined.
{
         switch (bitPerSample) {
             case 8 : return BYTE;
             case 16 : {
                 switch (sampleFormat) {
                     case 1 : return USHORT;
                     case 2 : return SHORT;
                     default : return null;
                 }
             }
             case 32 : {
                 return (sampleFormat == 3) ? FLOAT : INTEGER;
             }
             case 64: return DOUBLE;
             default: return null;
         }
     }
Member Data Documentation
BYTE
BYTE
Data type Byte.
FLOAT
FLOAT
Data type Float.
INTEGER
INTEGER
Data type Integer.
SHORT
SHORT
Data type Short.
USHORT
USHORT
Data type Short.