jena-geo: ImageUtilities Class Reference
ImageUtilities Class Reference
A set of static methods working on images.
Static Public Member Functions
static Rectangle getBounds (final RenderedImage image)
Returns the bounds of the given image as a new rectangle.
static ImageLayout getImageLayout (final RenderedImage image)
Suggests an ImageLayout for the specified image.
static RenderingHints getRenderingHints (final RenderedImage image)
Suggests a set of RenderingHints for the specified image.
static boolean isTiled (final RenderedImage image)
Returns.
static Dimension toTileSize (final Dimension size)
Suggests a tile size for the specified image size.
static ImageLayout createIntersection (final ImageLayout layout, final List<? extends RenderedImage > sources)
Computes a new ImageLayout which is the intersection of the specified.
static Interpolation toInterpolation (final Object type) throws IllegalArgumentException
Casts the specified object to an object.
static String getInterpolationName (Interpolation interp)
Returns the interpolation name for the specified interpolation object.
static boolean isFloatType (final int type)
Returns.
static int typeForBoth (final int t1, final int t2)
Returns a data type capable to hold the values of the two given data types.
static int typeForRange (final double minimum, final double maximum)
Suggests the smallest type capable to hold the given range of values.
static double minimum (final int dataType)
Returns the minimum allowed value for a certain data type.
static double maximum (final int dataType)
Returns the maximum allowed value for a certain data type.
static void fill (final WritableRenderedImage image, final Number value)
Sets every samples in the given image to the given value.
static void fill (final WritableRaster raster, Rectangle region, final Number value)
Sets every samples in the given region of the given raster to the given value.
static RenderedImage replaceColorModel (RenderedImage image, final ColorModel cm)
Replaces the color model in the given image by the given one.
Static Public Attributes
static final int MIN_TILE_SIZE = 256
The minimum tile size.
Private Member Functions
ImageUtilities ()
Do not allow creation of instances of this class.
Static Private Member Functions
static ImageLayout getImageLayout (final RenderedImage image, final boolean initToImage)
Returns an ImageLayout for the specified image.
static int toTileSize (final int imageSize, final int tileSize)
Suggests a tile size close to.
static void fill (final DataBuffer buffer, final Number value)
Sets the content of all banks in the given data buffer to the specified value.
Static Private Attributes
static final Dimension DEFAULT_TILE_SIZE = new Dimension(512, 512)
The default tile size.
static final int STRIPE_SIZE = 64
Maximum tile width or height before to consider a tile as a stripe.
static final String [] INTERPOLATION_NAMES
List of valid names.
static final int [] INTERPOLATION_TYPES
Interpolation types (provided by Java Advanced Imaging) for INTERPOLATION_NAMES.
Detailed Description
A set of static methods working on images.
Some of those methods are useful, but not really rigorous. This is why they do not appear in any "official" package, but instead in this private one.
                 <strong>Do not rely on this API!</strong>
It may change in incompatible way in any future version.
Author
Martin Desruisseaux (IRD, Geomatys)
Simone Giannecchini (Geosolutions)
Version
3.20
Since
1.2
Constructor & Destructor Documentation
ImageUtilities()
ImageUtilities () private
Do not allow creation of instances of this class.
{
     }
Member Function Documentation
createIntersection()
static ImageLayout createIntersection (final ImageLayout layout, final List<? extends RenderedImage > sources) static
Computes a new ImageLayout which is the intersection of the specified.
ImageLayout
and all
RenderedImage
s in the supplied list. If the minX, minY, width and height properties are not defined in the
layout
, then they will be inherited from the first source for consistency with javax.media.jai.OpImage constructor.
Parameters
layout The original layout. This object will not be modified.
sources The list of sources RenderedImage.
Returns
A new
ImageLayout
, or the original
layout
if no change was needed.
References ImageUtilities.toTileSize().
Referenced by Combine.Combine().
     {
         ImageLayout result = layout;
         if (result == null) {
             result = new ImageLayout();
         }
         final int n = sources.size();
         if (n != 0) {
             // If layout is not set, OpImage uses the layout of the *first*
             // source image according OpImage constructor javadoc.
             RenderedImage source = sources.get(0);
             int minXL = result.getMinX  (source);
             int minYL = result.getMinY  (source);
             int maxXL = result.getWidth (source) + minXL;
             int maxYL = result.getHeight(source) + minYL;
             for (int i=0; i<n; i++) {
                 source = sources.get(i);
                 final int minX = source.getMinX  ();
                 final int minY = source.getMinY  ();
                 final int maxX = source.getWidth () + minX;
                 final int maxY = source.getHeight() + minY;
                 int mask = 0;
                 if (minXL < minX) mask |= (1|4); // set minX and width
                 if (minYL < minY) mask |= (2|8); // set minY and height
                 if (maxXL > maxX) mask |= (4);   // Set width
                 if (maxYL > maxY) mask |= (8);   // Set height
                 if (mask != 0) {
                     if (layout == result) {
                         result = (ImageLayout) layout.clone();
                     }
                     if ((mask & 1) != 0) result.setMinX   (minXL=minX);
                     if ((mask & 2) != 0) result.setMinY   (minYL=minY);
                     if ((mask & 4) != 0) result.setWidth ((maxXL=maxX) - minXL);
                     if ((mask & 8) != 0) result.setHeight((maxYL=maxY) - minYL);
                 }
             }
             // If the bounds changed, adjust the tile size.
             if (result != layout) {
                 source = sources.get(0);
                 if (result.isValid(ImageLayout.TILE_WIDTH_MASK)) {
                     final int oldSize = result.getTileWidth(source);
                     final int newSize = toTileSize(result.getWidth(source), oldSize);
                     if (oldSize != newSize) {
                         result.setTileWidth(newSize);
                     }
                 }
                 if (result.isValid(ImageLayout.TILE_HEIGHT_MASK)) {
                     final int oldSize = result.getTileHeight(source);
                     final int newSize = toTileSize(result.getHeight(source), oldSize);
                     if (oldSize != newSize) {
                         result.setTileHeight(newSize);
                     }
                 }
             }
         }
         return result;
     }
fill() [1/3]
static void fill (final WritableRenderedImage image, final Number value) static
Sets every samples in the given image to the given value.
This method is typically used for clearing an image content.
Parameters
image The image to fill.
value The value to be given to every samples.
Referenced by SilhouetteMask.computeImage(), ImageUtilities.fill(), and SimpleBufferedImageOp.filter().
{
         int y = image.getMinTileY();
         for (int ny = image.getNumYTiles(); --ny >= 0; y++) {
             int x = image.getMinTileX();
             for (int nx = image.getNumXTiles(); --nx >= 0; x++) {
                 final WritableRaster raster = image.getWritableTile(x, y);
                 try {
                     fill(raster.getDataBuffer(), value);
                 } finally {
                     image.releaseWritableTile(x, y);
                 }
             }
         }
     }
fill() [2/3]
static void fill (final WritableRaster raster, Rectangle region, final Number value) static
Sets every samples in the given region of the given raster to the given value.
Parameters
raster The raster where to set the sample values.
region The region in the given rectangle where the values should be set.
value The value to be given to every samples that are inside the given region.
References ImageUtilities.fill().
{
         final Rectangle bounds = raster.getBounds();
         if (region.contains(bounds)) {
             fill(raster.getDataBuffer(), value);
         } else {
             region = region.intersection(bounds);
             final double[] background = new double[raster.getNumBands()];
             Arrays.fill(background, value.doubleValue());
             ImageUtil.fillBackground(raster, region, background);
         }
     }
fill() [3/3]
static void fill (final DataBuffer buffer, final Number value) static private
Sets the content of all banks in the given data buffer to the specified value.
We do not allow setting of different value for individual bank because the data buffer "banks" do not necessarily match the image "bands".
We do not provide version for setting only a portion of the data buffer in order to avoid the complexity of considering the number of bits per pixel, the pixel stride and the line stride - the risk of bug would be too high, we are better to stick to the Java API for that.
Parameters
buffer The data buffer to fill.
value The values to be given to every elements in the data buffer.
References Errors.format(), and Errors.Keys.UnsupportedDataType.
{
         final int[] offsets = buffer.getOffsets();
         final int size = buffer.getSize();
         if (buffer instanceof DataBufferByte) {
             final DataBufferByte data = (DataBufferByte) buffer;
             final byte n = value.byteValue();
             for (int i=0; i<offsets.length; i++) {
                 final int offset = offsets[i];
                 Arrays.fill(data.getData(i), offset, offset + size, n);
             }
         } else if (buffer instanceof DataBufferShort) {
             final DataBufferShort data = (DataBufferShort) buffer;
             final short n = value.shortValue();
             for (int i=0; i<offsets.length; i++) {
                 final int offset = offsets[i];
                 Arrays.fill(data.getData(i), offset, offset + size, n);
             }
         } else if (buffer instanceof DataBufferUShort) {
             final DataBufferUShort data = (DataBufferUShort) buffer;
             final short n = value.shortValue();
             for (int i=0; i<offsets.length; i++) {
                 final int offset = offsets[i];
                 Arrays.fill(data.getData(i), offset, offset + size, n);
             }
         } else if (buffer instanceof DataBufferInt) {
             final DataBufferInt data = (DataBufferInt) buffer;
             final int n = value.intValue();
             for (int i=0; i<offsets.length; i++) {
                 final int offset = offsets[i];
                 Arrays.fill(data.getData(i), offset, offset + size, n);
             }
         } else if (buffer instanceof DataBufferFloat) {
             final DataBufferFloat data = (DataBufferFloat) buffer;
             final float n = value.floatValue();
             for (int i=0; i<offsets.length; i++) {
                 final int offset = offsets[i];
                 Arrays.fill(data.getData(i), offset, offset + size, n);
             }
         } else if (buffer instanceof DataBufferDouble) {
             final DataBufferDouble data = (DataBufferDouble) buffer;
             final double n = value.doubleValue();
             for (int i=0; i<offsets.length; i++) {
                 final int offset = offsets[i];
                 Arrays.fill(data.getData(i), offset, offset + size, n);
             }
         } else {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.UnsupportedDataType));
         }
     }
getBounds()
static Rectangle getBounds (final RenderedImage image) static
Returns the bounds of the given image as a new rectangle.
Note that if the image is actually and instance of PlanarImage and the caller will not modify the rectangle values, then PlanarImage#getBounds() can be used instead.
Parameters
image The image for which to get the bounds.
Returns
The bounds of the given image.
See also
Raster::getBounds()
PlanarImage::getBounds()
Referenced by SimpleBufferedImageOp.getBounds2D().
{
         return new Rectangle(image.getMinX(), image.getMinY(), image.getWidth(), image.getHeight());
     }
getImageLayout() [1/2]
static ImageLayout getImageLayout (final RenderedImage image) static
Suggests an ImageLayout for the specified image.
All parameters are initially set equal to those of the given RenderedImage, and then the toTileSize tile size is updated according the image size}. This method never returns
null
.
Parameters
image The image for which to suggest a layout.
Returns
The suggested image layout.
Referenced by ImageUtilities.getRenderingHints().
{
         return getImageLayout(image, true);
     }
getImageLayout() [2/2]
static ImageLayout getImageLayout (final RenderedImage image, final boolean initToImage) static private
Returns an ImageLayout for the specified image.
If
initToImage
is
true
, then all parameters are initially set equal to those of the given RenderedImage and the returned layout is never
null
(except if the image is null).
Parameters
image The image for which to suggest a layout.
Returns
The suggested image layout.
References ImageUtilities.DEFAULT_TILE_SIZE, ImageUtilities.STRIPE_SIZE, and ImageUtilities.toTileSize().
{
         if (image == null) {
             return null;
         }
         ImageLayout layout = initToImage ? new ImageLayout(image) : null;
         if ((image.getNumXTiles() == 1 || image.getTileWidth () <= STRIPE_SIZE) &&
             (image.getNumYTiles() == 1 || image.getTileHeight() <= STRIPE_SIZE))
         {
             // If the image was already tiled, reuse the same tile size.
             // Otherwise, compute default tile size.  If a default tile
             // size can't be computed, it will be left unset.
             if (layout != null) {
                 layout = layout.unsetTileLayout();
             }
             Dimension defaultSize = JAI.getDefaultTileSize();
             if (defaultSize == null) {
                 defaultSize = DEFAULT_TILE_SIZE;
             }
             int s;
             if ((s=toTileSize(image.getWidth(), defaultSize.width)) != 0) {
                 if (layout == null) {
                     layout = new ImageLayout();
                 }
                 layout = layout.setTileWidth(s);
                 layout.setTileGridXOffset(image.getMinX());
             }
             if ((s=toTileSize(image.getHeight(), defaultSize.height)) != 0) {
                 if (layout == null) {
                     layout = new ImageLayout();
                 }
                 layout = layout.setTileHeight(s);
                 layout.setTileGridYOffset(image.getMinY());
             }
         }
         return layout;
     }
getInterpolationName()
static String getInterpolationName (Interpolation interp) static
Returns the interpolation name for the specified interpolation object.
This method tries to infer the name from the object's class name.
Parameters
interp The interpolation object, or
null
for "nearest" (which is an other way to say "no interpolation").
Returns
The interpolation name.
{
         if (interp == null) {
             interp = Interpolation.getInstance(Interpolation.INTERP_NEAREST);
         }
         final String prefix = "Interpolation";
         for (Class<?> classe = interp.getClass(); classe!=null; classe=classe.getSuperclass()) {
             String name = Classes.getShortName(classe);
             int index = name.lastIndexOf(prefix);
             if (index >= 0) {
                 return name.substring(index + prefix.length());
             }
         }
         return Classes.getShortClassName(interp);
     }
getRenderingHints()
static RenderingHints getRenderingHints (final RenderedImage image) static
Suggests a set of RenderingHints for the specified image.
The rendering hints may include the following parameters:
JAI#KEY_IMAGE_LAYOUT with a proposed tile size.
This method may returns
null
if no rendering hints is proposed.
Parameters
image The image for which to suggest rendering hints.
Returns
The suggested rendering hints for the given image.
References ImageUtilities.getImageLayout().
{
         final ImageLayout layout = getImageLayout(image, false);
         return (layout != null) ? new RenderingHints(JAI.KEY_IMAGE_LAYOUT, layout) : null;
     }
isFloatType()
static boolean isFloatType (final int type) static
Returns.
true
if the given type is TYPE_FLOAT or TYPE_DOUBLE.
Parameters
type The type to test.
Returns
true
if the given type is one of floating point types.
{
         return (type == TYPE_FLOAT) || (type == TYPE_DOUBLE);
     }
isTiled()
static boolean isTiled (final RenderedImage image) static
Returns.
true
if the given image is tiled.
Parameters
image The image to test.
Returns
true
if the given image is tiled.
Since
3.20
{
         return (image.getTileWidth()  < image.getWidth()) ||
                (image.getTileHeight() < image.getHeight());
     }
maximum()
static double maximum (final int dataType) static
Returns the maximum allowed value for a certain data type.
This method does not returns positive infinity for float and double values, despite that they are valid values.
{
on floating point types}
If the given type is TYPE_FLOAT or TYPE_DOUBLE (you can use isFloatType for checking that), then there is some chances that what you really want is the maximal <cite>normalized value</cite>. In such case, you should invoke ColorSpace#getMaxValue instead. This doesn't apply to the alpha channel, where the maximal value is always 1 (fully opaque).
Parameters
dataType The data type to suggest a maximum value for.
Returns
The maximum value for the given data type.
Referenced by ImageUtilities.typeForRange().
{
         switch (dataType) {
             case TYPE_BYTE:   return 0xFF;
             case TYPE_USHORT: return 0xFFFF;
             case TYPE_SHORT:  return Short  .MAX_VALUE;
             case TYPE_INT:    return Integer.MAX_VALUE;
             case TYPE_FLOAT:  return Float  .MAX_VALUE;
             case TYPE_DOUBLE: return Double .MAX_VALUE;
             default: throw new IllegalArgumentException(String.valueOf(dataType));
         }
     }
minimum()
static double minimum (final int dataType) static
Returns the minimum allowed value for a certain data type.
This method does not returns negative infinity for float and double values, despite that they are valid values.
{
on floating point types}
If the given type is TYPE_FLOAT or TYPE_DOUBLE (you can use isFloatType for checking that), then there is some chances that what you really want is the minimal <cite>normalized value</cite>. In such case, you should invoke ColorSpace#getMinValue instead. This doesn't apply to the alpha channel, where the minimal value is always 0 (fully transparent).
Parameters
dataType The data type to suggest a minimum value for.
Returns
The minimum value for the given data type.
Referenced by ImageUtilities.typeForRange().
{
         switch (dataType) {
             case TYPE_BYTE:   // Fall through
             case TYPE_USHORT: return  0;
             case TYPE_SHORT:  return  Short  .MIN_VALUE;
             case TYPE_INT:    return  Integer.MIN_VALUE;
             case TYPE_FLOAT:  return -Float  .MAX_VALUE;
             case TYPE_DOUBLE: return -Double .MAX_VALUE;
             default: throw new IllegalArgumentException(String.valueOf(dataType));
         }
     }
replaceColorModel()
static RenderedImage replaceColorModel (RenderedImage image, final ColorModel cm) static
Replaces the color model in the given image by the given one.
The sample values are transfered with no change. This method is not suitable for anything that change the pixel layout, the number of bands, etc.
Parameters
image The image in which to change the color model.
cm The new color model.
Returns
An image with the new color model.
{
         if (image instanceof BufferedImage) {
             final BufferedImage b = (BufferedImage) image;
             image = new BufferedImage(cm, b.getRaster(), b.isAlphaPremultiplied(), null);
         } else {
             final ImageLayout layout = new ImageLayout();
             layout.setColorModel(cm);
             image = new NullOpImage(image, layout, null, NullOpImage.OP_COMPUTE_BOUND);
         }
         return image;
     }
toInterpolation()
static Interpolation toInterpolation (final Object type) throws IllegalArgumentException static
Casts the specified object to an object.
Parameters
type The interpolation type as an Interpolation or a CharSequence object.
Returns
The interpolation object for the specified type.
Exceptions
IllegalArgumentException if the specified interpolation type is not a know one.
References Errors.format(), and Errors.Keys.UnknownInterpolation_1.
{
         if (type instanceof Interpolation) {
             return (Interpolation) type;
         } else if (type instanceof CharSequence) {
             final String name = type.toString();
             final int length = INTERPOLATION_NAMES.length;
             for (int i=0; i<length; i++) {
                 if (INTERPOLATION_NAMES[i].equalsIgnoreCase(name)) {
                     return Interpolation.getInstance(INTERPOLATION_TYPES[i]);
                 }
             }
         }
         throw new IllegalArgumentException(Errors.format(Errors.Keys.UnknownInterpolation_1, type));
     }
toTileSize() [1/2]
static Dimension toTileSize (final Dimension size) static
Suggests a tile size for the specified image size.
On input,
size
is the image size. On output, it is the tile size. This method write the result directly in the supplied object and returns
size
for convenience.
This method it aimed to computing a tile size such that the tile grid would have overlapped the image bound in order to avoid having tiles crossing the image bounds and being therefore partially empty. This method will never returns a tile size smaller than { MIN_TILE_SIZE}. If this method can't suggest a size, then it left the corresponding
size
field (width or height) unchanged.
The width and height fields are processed independently in the same way. The following discussion use the
width
field as an example.
This method inspects different tile sizes close to the JAI::getDefaultTileSize() default tile size}. Let
width
be the default tile width. Values are tried in the following order:
width
,
width+1
,
width-1
,
width+2
,
width-2
,
width+3
,
width-3
, etc. until one of the following happen:
A suitable tile size is found. More specifically, a size is found which is a divisor of the specified image size, and is the closest one of the default tile size. The Dimension field (
width
or
height
) is set to this value.
An arbitrary limit (both a minimum and a maximum tile size) is reached. In this case, this method may set the Dimension field to a value that maximize the remainder of image size / tile size (in other words, the size that left as few empty pixels as possible).
Parameters
size The image size.
Returns
Suggested tile size for the given image size.
References ImageUtilities.DEFAULT_TILE_SIZE.
Referenced by ImageUtilities.createIntersection(), and ImageUtilities.getImageLayout().
{
         Dimension defaultSize = JAI.getDefaultTileSize();
         if (defaultSize == null) {
             defaultSize = DEFAULT_TILE_SIZE;
         }
         int s;
         if ((s=toTileSize(size.width,  defaultSize.width )) != 0) size.width  = s;
         if ((s=toTileSize(size.height, defaultSize.height)) != 0) size.height = s;
         return size;
     }
toTileSize() [2/2]
static int toTileSize (final int imageSize, final int tileSize) static private
Suggests a tile size close to.
tileSize
for the specified
imageSize
. This method it aimed to computing a tile size such that the tile grid would have overlapped the image bound in order to avoid having tiles crossing the image bounds and being therefore partially empty. This method will never returns a tile size smaller than { MIN_TILE_SIZE}. If this method can't suggest a size, then it returns 0.
Parameters
imageSize The image size.
tileSize The preferred tile size, which is often { DEFAULT_TILE_SIZE}.
{
         final int MAX_TILE_SIZE = Math.min(tileSize*2, imageSize);
         final int stop = Math.max(tileSize-MIN_TILE_SIZE, MAX_TILE_SIZE-tileSize);
         int sopt = 0;  // An "optimal" tile size, to be used if no exact dividor is found.
         int rmax = 0;  // The remainder of 'imageSize / sopt'. We will try to maximize this value.
         /*
          * Inspects all tile sizes in the range [GEOTOOLKIT_MIN_TILE_SIZE .. MAX_TIME_SIZE]. We will begin
          * with a tile size equal to the specified 'tileSize'. Next we will try tile sizes of
          * 'tileSize+1', 'tileSize-1', 'tileSize+2', 'tileSize-2', 'tileSize+3', 'tileSize-3',
          * etc. until a tile size if found suitable.
          *
          * More generally, the loop below tests the 'tileSize+i' and 'tileSize-i' values. The
          * 'stop' constant was computed assuming that MIN_TIME_SIZE < tileSize < MAX_TILE_SIZE.
          * If a tile size is found which is a dividor of the image size, than that tile size (the
          * closest one to 'tileSize') is returned. Otherwise, the loop continue until all values
          * in the range [GEOTOOLKIT_MIN_TILE_SIZE .. MAX_TIME_SIZE] were tested. In this process, we
          * remind the tile size that gave the greatest reminder (rmax). In other words, this is the
          * tile size with the smallest amount of empty pixels.
          */
         for (int i=0; i<=stop; i++) {
             int s;
             if ((s = tileSize+i) <= MAX_TILE_SIZE) {
                 final int r = imageSize % s;
                 if (r == 0) {
                     // Found a size >= to 'tileSize' which is a dividor of image size.
                     return s;
                 }
                 if (r > rmax) {
                     rmax = r;
                     sopt = s;
                 }
             }
             if ((s = tileSize-i) >= MIN_TILE_SIZE) {
                 final int r = imageSize % s;
                 if (r == 0) {
                     // Found a size <= to 'tileSize' which is a dividor of image size.
                     return s;
                 }
                 if (r > rmax) {
                     rmax = r;
                     sopt = s;
                 }
             }
         }
         /*
          * No dividor were found in the range [GEOTOOLKIT_MIN_TILE_SIZE .. MAX_TIME_SIZE]. At this point
          * 'sopt' is an "optimal" tile size (the one that left as few empty pixel as possible),
          * and 'rmax' is the amount of non-empty pixels using this tile size. We will use this
          * "optimal" tile size only if it fill at least 75% of the tile. Otherwise, we arbitrarily
          * consider that it doesn't worth to use a "non-standard" tile size. The purpose of this
          * arbitrary test is again to avoid too many small tiles (assuming that
          */
         return (rmax >= tileSize - tileSize/4) ? sopt : 0;
     }
typeForBoth()
static int typeForBoth (final int t1, final int t2) static
Returns a data type capable to hold the values of the two given data types.
Parameters
t1 The first data type.
t2 The second data type.
Returns
A data type capable to hold the values of the two given data types.
{
         final int min = Math.min(t1, t2);
         final int max = Math.max(t1, t2);
         if (min == max) {
             return max;
         }
         if (min >= TYPE_BYTE && max <= TYPE_DOUBLE) {
             return (min == TYPE_USHORT && max == TYPE_SHORT) ? TYPE_INT : max;
         }
         return TYPE_UNDEFINED;
     }
typeForRange()
static int typeForRange (final double minimum, final double maximum) static
Suggests the smallest type capable to hold the given range of values.
Parameters
minimum The minimal value to hold, inclusive.
maximum The maximal value to hold, inclusive.
Returns
The data type, or DataBuffer#TYPE_UNDEFINED if the given range is invalid, contains NaN or infinity values.
References ImageUtilities.maximum(), and ImageUtilities.minimum().
{
         if (maximum >= minimum) {
             for (int type=TYPE_BYTE; type<=TYPE_DOUBLE; type++) {
                 if (minimum >= minimum(type) && maximum <= maximum(type)) {
                     return type;
                 }
             }
         }
         return TYPE_UNDEFINED;
     }
Member Data Documentation
DEFAULT_TILE_SIZE
final Dimension DEFAULT_TILE_SIZE = new Dimension(512, 512) static private
The default tile size.
This default tile size can be overridden with a call to JAI#setDefaultTileSize.
Referenced by ImageUtilities.getImageLayout(), and ImageUtilities.toTileSize().
INTERPOLATION_NAMES
final String [] INTERPOLATION_NAMES static private
Initial value:
= {
        "Nearest",
        "NearestNeighbor",
        "Bilinear",
        "Bicubic",
        "Bicubic2"
    }
List of valid names.
Note: the "Optimal" type is not implemented because currently not provided by JAI.
INTERPOLATION_TYPES
final int [] INTERPOLATION_TYPES static private
Initial value:
= {
        Interpolation.INTERP_NEAREST,
        Interpolation.INTERP_NEAREST,
        Interpolation.INTERP_BILINEAR,
        Interpolation.INTERP_BICUBIC,
        Interpolation.INTERP_BICUBIC_2
    }
Interpolation types (provided by Java Advanced Imaging) for INTERPOLATION_NAMES.
MIN_TILE_SIZE
final int MIN_TILE_SIZE = 256 static
The minimum tile size.
STRIPE_SIZE
final int STRIPE_SIZE = 64 static private
Maximum tile width or height before to consider a tile as a stripe.
It tile width or height are smaller or equals than this size, then the image will be re-tiled. That is done because there are many formats that use stripes as an alternative to tiles, an example is TIFF. A stripe can be a performance issue, users can have stripes as large as 20000 columns x 8 rows. If we just want to see a chunk of 512x512, this is a lot of unneeded data to load.
Referenced by ImageUtilities.getImageLayout().