jena-geo: ColorUtilities Class Reference
ColorUtilities Class Reference
A set of static methods for handling of colors informations.
Static Public Member Functions
static int getIntFromColor (int r, int g, int b, int a)
Creates an sRGB color with the specified red, green, blue, and alpha values in the range (0 - 255).
static double [] toDoubleValues (final Color color, final int numBands)
Returns the color components in an array of.
static String toString (final Color color)
Returns a string representation of the given color.
static Color [] subarray (final Color[] palette, int lower, int upper)
Returns a subarray of the specified color array.
static void expand (final Color[] colors, final int[] ARGB, final int lower, final int upper)
Copies.
static int roundByte (final double value)
Rounds a float value and clamp the result between 0 and 255 inclusive.
static IndexColorModel getIndexColorModel (final int[] ARGB)
Returns an index color model for specified ARGB codes.
static float [] XYZtoLAB (final float[] color)
Transforms a color from XYZ color space to LAB.
static float colorDistance (final float[] lab1, final float[] lab2)
Computes the distance E (CIE 1994) between two colors in LAB color space.
static int getTransparentPixel (final IndexColorModel colors)
Returns the most transparent pixel in the specified color model.
static int getColorIndex (final IndexColorModel colors, final Color color, final int exclude)
Returns the index of the specified color, excluding the specified one.
static boolean isGrayPalette (final IndexColorModel model, boolean ignoreTransparents)
Tells if a specific IndexColorModel contains only gray color, ignoring alpha information.
Static Public Attributes
static final IndexColorModel BINARY_COLOR_MODEL
An index color model having only two colors, black and white.
Private Member Functions
ColorUtilities ()
Do not allow creation of instances of this class.
Detailed Description
A set of static methods for handling of colors informations.
Some of those methods are useful, but not really rigorous. This is why they do not appear in any "official" package, but instead in this private one.
                 <strong>Do not rely on this API!</strong>
It may change in incompatible way in any future version.
Author
Martin Desruisseaux (IRD, Geomatys)
Simone Giannecchini (Geosolutions)
Since
1.2
Constructor & Destructor Documentation
ColorUtilities()
ColorUtilities () private
Do not allow creation of instances of this class.
{
     }
Member Function Documentation
colorDistance()
static float colorDistance (final float [] lab1, final float [] lab2) static
Computes the distance E (CIE 1994) between two colors in LAB color space.
Reference: http://www.brucelindbloom.com/index.html?ColorDifferenceCalc.html
Parameters
lab1 The first LAB color.
lab2 The second LAB color.
Returns
The CIE94 distance between the two supplied colors.
Referenced by ColorUtilities.getColorIndex(), and ColorUtilities.getTransparentPixel().
{
         double sum;
         if (false) {
             // Computes distance using CIE94 formula.
             // NOTE: this formula sometime fails because of negative
             //       value in the first Math.sqrt(...) expression.
             final double dL = (double) lab1[0] - lab2[0];
             final double da = (double) lab1[1] - lab2[1];
             final double db = (double) lab1[2] - lab2[2];
             final double C1 = Math.hypot(lab1[1], lab1[2]);
             final double C2 = Math.hypot(lab2[1], lab2[2]);
             final double dC = C1 - C2;
             final double dH = Math.sqrt(da*da + db*db - dC*dC);
             final double sL = dL / 2;
             final double sC = dC / (1 + 0.048*C1);
             final double sH = dH / (1 + 0.014*C1);
             sum = sL*sL + sC*sC + sH*sH;
         } else {
             // Computes distance using delta E formula.
             sum = 0;
             for (int i=Math.min(lab1.length, lab2.length); --i>=0;) {
                 final double delta = lab1[i] - lab2[i];
                 sum += delta*delta;
             }
         }
         return (float) Math.sqrt(sum);
     }
expand()
static void expand (final Color [] colors, final int [] ARGB, final int lower, final int upper) static
Copies.
colors
into array
ARGB
from index
lower
inclusive to index
upper
exclusive. If
upper-lower
is not equal to the length of
colors
array, then colors will be interpolated.
Parameters
colors Colors to copy into the
ARGB
array.
ARGB Array of integer to write ARGB values to.
lower Index (inclusive) of the first element of
ARGB
to change.
upper Index (exclusive) of the last element of
ARGB
to change.
Referenced by IndexedPalette.createARGB().
{
         final int[] codes = new int[colors.length];
         for (int i=0; i<codes.length; i++) {
             codes[i] = colors[i].getRGB();      // Note: getRGB() is really getARGB().
         }
         ColorModelFactory.expand(codes, ARGB, lower, upper);
     }
getColorIndex()
static int getColorIndex (final IndexColorModel colors, final Color color, final int exclude) static
Returns the index of the specified color, excluding the specified one.
If the color is not explicitly found, a close color is returned. This method never returns a negative value (0 is returned if the color model has no colors).
Parameters
colors The color model in which to look for a color index.
color The color to search for.
exclude An index to exclude from the search (usually the background or the getTransparentPixel transparent} pixel), or -1 if none.
Returns
The index of the color, or 0.
References ColorUtilities.colorDistance(), and ColorUtilities.XYZtoLAB().
Referenced by DeferredPlanarImage.getDefaultDataBuffer().
     {
         final ColorSpace space = colors.getColorSpace();
         final float[] RGB = {
             color.getRed()   / 255f,
             color.getGreen() / 255f,
             color.getBlue()  / 255f
         };
         final float[] REF = XYZtoLAB(space.toCIEXYZ(RGB));
         float delta = Float.POSITIVE_INFINITY;
         int index = 0;
         assert REF != RGB;
         for (int i=colors.getMapSize(); --i>=0;) {
             if (i != exclude) {
                 RGB[0] = colors.getRed  (i) / 255f;
                 RGB[1] = colors.getGreen(i) / 255f;
                 RGB[2] = colors.getBlue (i) / 255f;
                 final float d = colorDistance(XYZtoLAB(space.toCIEXYZ(RGB)), REF);
                 assert d >= 0 : i; // Check mostly for NaN value
                 if (d <= delta) {
                     delta = d;
                     index = i;
                 }
             }
         }
         return index;
     }
getIndexColorModel()
static IndexColorModel getIndexColorModel (final int [] ARGB) static
Returns an index color model for specified ARGB codes.
If the specified array has not transparent color (i.e. all alpha values are 255), then the returned color model will be opaque. Otherwise, if the specified array has one and only one color with alpha value of 0, the returned color model will have only this transparent color. Otherwise, the returned color model will be translucent.
Parameters
ARGB An array of ARGB values.
Returns
An index color model for the specified array.
{
         return ColorModelFactory.createIndexColorModel(ARGB, 1, 0, -1);
     }
getIntFromColor()
static int getIntFromColor (int r, int g, int b, int a) static
Creates an sRGB color with the specified red, green, blue, and alpha values in the range (0 - 255).
Parameters
r the red component.
g the green component.
b the blue component.
a the alpha component.
Returns
The RGB color from the given components.
{
         return ((a & 0xFF) << 24) |
                ((r & 0xFF) << 16) |
                ((g & 0xFF) <<  8) |
                 (b & 0xFF);
     }
getTransparentPixel()
static int getTransparentPixel (final IndexColorModel colors) static
Returns the most transparent pixel in the specified color model.
If many colors has the same alpha value, than the darkest one is returned. This method never returns a negative value (0 is returned if the color model has no colors).
Parameters
colors The color model in which to look for a transparent color.
Returns
The index of a transparent color, or 0.
References ColorUtilities.colorDistance(), and ColorUtilities.XYZtoLAB().
Referenced by DeferredPlanarImage.getDefaultDataBuffer().
{
         int index = colors.getTransparentPixel();
         if (index < 0) {
             index = 0;
             int   alpha = Integer.MAX_VALUE;
             float delta = Float.POSITIVE_INFINITY;
             final ColorSpace space = colors.getColorSpace();
             final float[] RGB   = new float[3];
             final float[] BLACK = XYZtoLAB(space.toCIEXYZ(RGB)); // Black in Lab color space.
             assert BLACK != RGB;
             for (int i=colors.getMapSize(); --i>=0;) {
                 final int a = colors.getAlpha(i);
                 if (a <= alpha) {
                     RGB[0] = colors.getRed  (i)/255f;
                     RGB[1] = colors.getGreen(i)/255f;
                     RGB[2] = colors.getBlue (i)/255f;
                     final float d = colorDistance(XYZtoLAB(space.toCIEXYZ(RGB)), BLACK);
                     assert d >= 0 : i; // Check mostly for NaN value
                     if (a<alpha || d<delta) {
                         alpha = a;
                         delta = d;
                         index = i;
                     }
                 }
             }
         }
         return index;
     }
isGrayPalette()
static boolean isGrayPalette (final IndexColorModel model, boolean ignoreTransparents) static
Tells if a specific IndexColorModel contains only gray color, ignoring alpha information.
Parameters
model index color model to be inspected.
ignoreTransparents
{
         if (!model.hasAlpha()) {
             // We will not check transparent pixels if there is none in the color model.
             ignoreTransparents = false;
         }
         final int mapSize = model.getMapSize();
         for (int i=0; i<mapSize; i++) {
             if (ignoreTransparents) {
                 // If this entry is transparent and we were asked
                 // to ignore fully transparents pixels, let's leave.
                 if (model.getAlpha(i) == 0) {
                     continue;
                 }
             }
             // Get the color for this pixel only if it is requested.
             // If gray, all components are the same.
             final int green = model.getGreen(i);
             if (green != model.getRed(i) || green != model.getBlue(i)) {
                 return false;
             }
         }
         return true;
     }
roundByte()
static int roundByte (final double value) static
Rounds a float value and clamp the result between 0 and 255 inclusive.
Parameters
value The value to round.
Returns
The rounded and clamped value.
{
         return (int) Math.min(Math.max(Math.round(value), 0), 255);
     }
subarray()
static Color [] subarray (final Color [] palette, int lower, int upper) static
Returns a subarray of the specified color array.
The
lower
and
upper
index will be clamb into the
palette
range. If they are completely out of range, or if they would result in an empty array, then
null
is returned.
This method is used by org.geotoolkit.coverage.SampleDimension as an heuristic approach for distributing palette colors into a list of categories.
Parameters
palette The color array (may be
null
).
lower The lower index, inclusive.
upper The upper index, inclusive.
Returns
The subarray (may be
palette
if the original array already fit), or
null
if the
lower
and
upper
index are out of
palette
bounds.
{
         if (palette != null) {
             lower = Math.max(lower, 0);
             upper = Math.min(upper, palette.length);
             if (lower >= upper) {
                 return null;
             }
             if (lower != 0 || upper != palette.length) {
                 return Arrays.copyOfRange(palette, lower, upper);
             }
         }
         return palette;
     }
toDoubleValues()
static double [] toDoubleValues (final Color color, final int numBands) static
Returns the color components in an array of.
double
values. This is mostly for usage with JAI operators which require sample values as
double
no matter the actual image data type.
Parameters
color The color for which to extract the component values.
numBands The length of the array to be returned. If greater than 4, then the extra values will be initialized to 0.
Returns
The color components in an array of the given length.
Referenced by FloodFill.fill().
{
         final double[] values = new double[numBands];
         switch (numBands) {
             default: values[3] = color.getAlpha();
             case 3:  values[2] = color.getBlue();
             case 2:  values[1] = color.getGreen();
             case 1:  values[0] = color.getRed();
             case 0:  break;
         }
         return values;
     }
toString()
static String toString (final Color color) static
Returns a string representation of the given color.
This method omits the alpha component if the color is opaque.
Parameters
color The color.
Returns
A string representation of the given color.
Since
3.14
{
         int ARGB = color.getRGB();
         final boolean isOpaque = (ARGB & 0xFF000000) == 0xFF000000;
         int size;
         if (isOpaque) {
             ARGB &= 0xFFFFFF;
             size = 6;
         } else {
             size = 8;
         }
         final String code = Integer.toHexString(ARGB).toUpperCase(Locale.US);
         size -= code.length();
         final StringBuilder buffer = new StringBuilder();
         buffer.append('#');
         while (--size >= 0) {
             buffer.append('0');
         }
         return buffer.append(code).toString();
     }
XYZtoLAB()
static float [] XYZtoLAB (final float [] color) static
Transforms a color from XYZ color space to LAB.
The color are transformed in place. This method returns
color
for convenience.
Reference: http://www.brucelindbloom.com/index.html?ColorDifferenceCalc.html
Parameters
color The XYZ color to convert.
Returns
The LAB color.
Referenced by ColorUtilities.getColorIndex(), and ColorUtilities.getTransparentPixel().
{
         color[0] /= 0.9642;   // Other refeference: 0.95047;
         color[1] /= 1.0000;   //                    1.00000;
         color[2] /= 0.8249;   //                    1.08883;
         for (int i=0; i<3; i++) {
             final float c = color[i];
             color[i] = (float)((c > 216/24389f) ? Math.pow(c, 1.0/3) : ((24389/27.0)*c + 16)/116);
         }
         final float L = 116 *  color[1] - 16;
         final float a = 500 * (color[0] - color[1]);
         final float b = 200 * (color[1] - color[2]);
         assert !Float.isNaN(L) && !Float.isNaN(a) && !Float.isNaN(b);
         color[0] = L;
         color[1] = a;
         color[2] = b;
         return color;
     }
Member Data Documentation
BINARY_COLOR_MODEL
final IndexColorModel BINARY_COLOR_MODEL static
Initial value:
= new IndexColorModel(
            1, 2, new int[] {0, -1}, 0, false, -1, DataBuffer.TYPE_BYTE)
An index color model having only two colors, black and white.
Referenced by SilhouetteMask.layout().