jena-geo: PaletteFactory Class Reference
PaletteFactory Class Reference
A factory for IndexColorModel index color models} created from RGB values listed in files.
Public Member Functions
PaletteFactory (final File directory, final String extension, final Charset charset, final Locale locale)
Constructs a palette factory which will load the palette definition files from the specified directory.
PaletteFactory (final PaletteFactory fallback, final ClassLoader loader, final File directory, final String extension, final Charset charset, final Locale locale)
Constructs a palette factory using an optional ClassLoader class loader} for loading palette definition files.
PaletteFactory (final PaletteFactory fallback, final Class<?> loader, final File directory, final String extension, final Charset charset, final Locale locale)
Constructs a palette factory using an optional Class class} for loading palette definition files.
synchronized void setWarningLocale (final Locale warningLocale)
Sets the locale to use for formatting warning or error messages.
synchronized Locale getWarningLocale ()
Returns the locale set by the last invocation to setWarningLocale(Locale) in the current thread.
Set< String > getAvailableNames ()
Returns the set of available palette names.
Color [] getColors (final String name) throws IOException
Loads colors from a definition file.
Palette getPalette (final String name, final int size)
Returns the palette of the specified name and size.
Palette getPalettePadValueFirst (final String name, final int size)
Returns a palette with a <cite>pad value</cite> at index 0.
Palette getPalettePadValueLast (final String name, final int size)
Returns a palette with <cite>pad value</cite> at the last index.
Palette getPalette (final String name, final int lower, final int upper, final int size, final int numBands, final int visibleBand)
Returns the palette of the specified name and size.
Palette getContinuousPalette (final String name, final float minimum, final float maximum, final int dataType, final int numBands, final int visibleBand)
Creates a palette suitable for floating point values.
Static Public Member Functions
static synchronized PaletteFactory getDefault ()
Gets the default palette factory.
static synchronized void scanForPlugins (final ClassLoader loader)
Lookups for custom palette factories on the classpath.
Protected Member Functions
PaletteFactory ()
Constructs a default palette factory using this #getClass object class} for loading palette definition files.
InputStream getResourceAsStream (final String name)
Returns an input stream for reading the specified resource.
Protected Attributes
final WeakHashSet< Palette > palettes = new WeakHashSet<>(Palette.class)
The set of palettes already created and not yet garbage-collected.
Package Functions
final IndexedResourceBundle getErrorResources ()
Returns the resources for formatting error messages.
Package Attributes
final Set< Palette > protectedPalettes = new HashSet<>()
The set of palettes protected from garbage collection.
Private Member Functions
synchronized ThreadLocal< Locale > warningLocales ()
Gets the warningLocales} from the fallback or create a new one.
boolean getAvailableNames (final Collection< String > names)
Adds available palette names to the specified collection.
LineNumberReader getPaletteReader (String name)
Returns a buffered reader for the specified palette.
LineNumberReader getReader (final String name, final String caller)
Returns a buffered reader for the specified filename.
LineNumberReader getReader (final InputStream stream)
Wraps the specified input stream into a reader.
Color [] getColors (final LineNumberReader input, final String name) throws IOException
Reads the colors declared in the specified input stream.
IIOException syntaxError (final LineNumberReader input, final String name, final Exception cause)
Prepares an exception for the specified cause, which may be.
int byteValue (final int value) throws ParseException
Ensures that the specified value is inside the.
Static Private Member Functions
static String startWithDot (String extension)
Ensures that the given string starts with a dot.
static void readNames (final BufferedReader in, final Collection< String > names) throws IOException
Copies the content of the specified reader to the specified collection.
Private Attributes
PaletteFactory fallback
The fallback factory, or.
final ClassLoader classloader
The class loader from which to load the palette definition files.
final Class<?> loader
An alternative to classloader for loading resources.
final File directory
The base directory from which to search for palette definition files.
final String extension
The file extension.
final Charset charset
The charset to use for parsing files, or.
final Locale locale
The locale to use for parsing files, or.
transient ThreadLocal< Locale > warningLocales
The locale to use for formatting error messages, or.
Static Private Attributes
static final String LIST_FILE = "list.txt"
The file which contains a list of available color palettes.
static final File DEFAULT_DIRECTORY = new File("colors")
The default sub-directory, relative to the.
static PaletteFactory defaultFactory
The default palette factory.
Detailed Description
A factory for IndexColorModel index color models} created from RGB values listed in files.
The palette definition files are text files containing an arbitrary number of lines, each line containing RGB components ranging from 0 to 255 inclusive. An optional fourth column may be provided for alpha components. Empty lines and lines starting with the
'#'
character are ignored. Example:
{ text
RGB codes for SeaWiFs images
(chlorophylle-a concentration)
033 000 096 032 000 097 031 000 099 030 000 101 029 000 102 028 000 104 026 000 106 025 000 107 etc... }
The number of RGB codes doesn't have to match the target IndexColorModel::getMapSize color map size}. RGB codes will be automatically interpolated as needed. For example it is legal to declare only 2 colors, Color::BLUE blue} and Color::RED red} for instance. If an image needs 256 colors, then all needed colors will be interpolated from blue to red, with blue at index 0 and red at index 255.
The getDefault() default instance} provides the following color palettes. More details about those palettes are provided in this page.
{
custom palettes}
To add custom palettes, create a subclass of
PaletteFactory
like below:
{ java public class MyPalettes extends PaletteFactory { public MyPalettes() { // The call below uses the default options for convenience, // but we could use an other constructor with more parameters. super(); } }
// Optionally, we could override getResourceAsStream(String) if we wanted // to fetch the color codes from a custom source (e.g. from a database). }
In the directory that contain the
MyPalettes.class
file, create a "@code colors @endcode " sub-directory and put the palette definitions (as text files with the "@code .pal @endcode " suffix) in that directory. The directory and the file suffix can be changed using one of the constructors expecting arguments.
Finally, declare the fully-qualified name of
MyPalettes
in the following file:
{ text META-INF/services/org.geotoolkit.image.io.PaletteFactory }
Author
Martin Desruisseaux (IRD, Geomatys)
Version
3.17
Since
1.2
Constructor & Destructor Documentation
PaletteFactory() [1/4]
PaletteFactory () protected
Constructs a default palette factory using this #getClass object class} for loading palette definition files.
The default directory is
"colors"
relative to the directory of the subclass extending this class. The character encoding is ISO-8859-1 and the locale is Locale::US US}.
This constructor is protected because is it merely a convenience for subclasses registering themselves as a service in the following file (see class javadoc for more details):
{ text META-INF/services/org.geotoolkit.image.io.PaletteFactory }
Users should invoke getDefault instead, which will return a shared instance of this class together with any custom factories found on the class path.
Since
2.5
References PaletteFactory.DEFAULT_DIRECTORY.
Referenced by PaletteFactory.getDefault().
{
         this.classloader = null;
         this.loader      = getClass();
         this.directory   = DEFAULT_DIRECTORY;
         this.extension   = ".pal";
         this.charset     = Charset.forName("ISO-8859-1");
         this.locale      = Locale.US;
     }
PaletteFactory() [2/4]
PaletteFactory (final File directory, final String extension, final Charset charset, final Locale locale)
Constructs a palette factory which will load the palette definition files from the specified directory.
No ClassLoader class loader} is used, i.e. the palettes are read as ordinary file relative to the current working directory (not the classpath).
Parameters
directory The base directory for palette definition files relative to current directory, or
null
for
"."
.
extension File name extension, or
null
if there is no extension to add to filename. If non-null, this extension will be automatically appended to filename. It should starts with the
'.'
character.
charset The charset to use for parsing files, or
null
for the default.
locale The locale to use for parsing files, or
null
for the default.
Since
2.5
References PaletteFactory.charset, PaletteFactory.directory, PaletteFactory.locale, and PaletteFactory.startWithDot().
     {
         this.classloader = null;
         this.loader      = null;
         this.directory   = directory;
         this.extension   = startWithDot(extension);
         this.charset     = charset;
         this.locale      = locale;
     }
PaletteFactory() [3/4]
PaletteFactory (final PaletteFactory fallback, final ClassLoader loader, final File directory, final String extension, final Charset charset, final Locale locale)
Constructs a palette factory using an optional ClassLoader class loader} for loading palette definition files.
If
loader
is non-null, the definitions will be read using ClassLoader#getResource(String), which imply that the
directory
argument is relative to the root packages on the classpath.
Parameters
fallback An optional fallback factory, or
null
if there is none. The fallback factory will be queried if a palette was not found in the current factory.
loader An optional class loader to use for loading the palette definition files. If
null
, loading will occurs from the system current working directory.
directory The base directory for palette definition files. It may be a Java package if a
loader
were specified. If
null
, then
"."
is assumed.
extension File name extension, or
null
if there is no extension to add to filename. If non-null, this extension will be automatically appended to filename. It should starts with the
'.'
character.
charset The charset to use for parsing files, or
null
for the default.
locale The locale to use for parsing files, or
null
for the default.
References PaletteFactory.charset, PaletteFactory.directory, PaletteFactory.fallback, PaletteFactory.loader, PaletteFactory.locale, and PaletteFactory.startWithDot().
     {
         this.fallback    = fallback;
         this.classloader = loader;
         this.loader      = null;
         this.directory   = directory;
         this.extension   = startWithDot(extension);
         this.charset     = charset;
         this.locale      = locale;
     }
PaletteFactory() [4/4]
PaletteFactory (final PaletteFactory fallback, final Class<?> loader, final File directory, final String extension, final Charset charset, final Locale locale)
Constructs a palette factory using an optional Class class} for loading palette definition files.
If
loader
is non-null, the definitions will be read using Class#getResource(String), which imply that the
directory
argument is relative to the package of the
PaletteFactory
subclass.
Using a Class class} instead of a ClassLoader class loader} can avoid security issue on some platforms (some platforms do not allow to load resources from a
ClassLoader
because it would make possible to load from the root package).
Parameters
fallback An optional fallback factory, or
null
if there is none. The fallback factory will be queried if a palette was not found in the current factory.
loader An optional class to use for loading the palette definition files. If
null
, loading will occurs from the system current working directory.
directory The base directory for palette definition files. It may be a Java package if a
loader
were specified. If
null
, then
"."
is assumed.
extension File name extension, or
null
if there is no extension to add to filename. If non-null, this extension will be automatically appended to filename. It should starts with the
'.'
character.
charset The charset to use for parsing files, or
null
for the default.
locale The locale to use for parsing files. or
null
for the default.
Since
2.2
References PaletteFactory.charset, PaletteFactory.directory, PaletteFactory.fallback, PaletteFactory.loader, PaletteFactory.locale, and PaletteFactory.startWithDot().
     {
         this.fallback    = fallback;
         this.classloader = null;
         this.loader      = loader;
         this.directory   = directory;
         this.extension   = startWithDot(extension);
         this.charset     = charset;
         this.locale      = locale;
     }
Member Function Documentation
byteValue()
int byteValue (final int value) throws ParseException private
Ensures that the specified value is inside the.
[0..255]
range. If the value is outside that range, a ParseException is thrown.
References PaletteFactory.getErrorResources(), and Errors.Keys.RgbOutOfRange_1.
Referenced by PaletteFactory.getColors().
{
         if (value>=0 && value<256) {
             return value;
         }
         throw new ParseException(getErrorResources().getString(
                 Errors.Keys.RgbOutOfRange_1, value), 0);
     }
getAvailableNames() [1/2]
Set<String> getAvailableNames ()
Returns the set of available palette names.
Any item in this set can be specified as argument to the getPalette(String, int) method.
If this method can not infer the names of available palettes, then it returns
null
. Note that this is not the same than an empty set, which means "there is no palette". The null return value means that the set is unknown.
Returns
The list of available palette name, or
null
if this method is unable to fetch this information.
Referenced by PaletteFactory.getAvailableNames().
{
         final Set<String> names = new LinkedHashSet<>();
         return getAvailableNames(names) ? names : null;
     }
getAvailableNames() [2/2]
boolean getAvailableNames (final Collection< String > names) private
Adds available palette names to the specified collection.
Parameters
names The collection where to add the name of the palettes.
Returns
true
if this method has been able to find some informations about palettes.
References PaletteFactory.getAvailableNames(), PaletteFactory.getReader(), and PaletteFactory.readNames().
{
         /*
          * Queries the fallback first, in order to make the "standard" palettes appear first.
          */
         boolean found = (fallback != null) && fallback.getAvailableNames(names);
         /*
          * First, parse the content of every "list.txt" files found on the classpath. Those files
          * are optional. But if they are present, we assume that their content are accurate (this
          * will not be verified).
          */
         try {
             BufferedReader in = getReader(LIST_FILE, "getAvailableNames");
             if (in != null) {
                 readNames(in, names);
                 found = true;
             }
             /*
              * We can iterate only with ClassLoader because there is no Class.getResources(...)
              * method. Note that this iteration (when performed) is not completely redundant with
              * the above call to 'getReader' because the user may have overridden
              * PaletteFactory.getResourceAsStream(String).
              */
             if (classloader != null) {
                 final String filename = new File(directory, LIST_FILE).getPath().replace(File.separatorChar, '/');
                 for (final Enumeration<URL> it=classloader.getResources(filename); it.hasMoreElements();) {
                     final URL url = it.nextElement();
                     in = getReader(url.openStream());
                     readNames(in, names);
                     found = true;
                 }
             }
         } catch (IOException e) {
             /*
              * Logs a warning but do not stop. The only consequence is that the names list
              * will be incomplete. We log the message as if it came from getAvailableNames(),
              * because it is the public method that invoked this one.
              */
             Logging.unexpectedException(null, PaletteFactory.class, "getAvailableNames", e);
         }
         /*
          * After the "list.txt" files, check if the resources can be read as a directory.
          * It may happen if the classpath point toward a directory of .class files rather
          * than a JAR file.
          */
         File dir = (directory != null) ? directory : new File(".");
         try {
             if (classloader != null) {
                 dir = IOUtilities.toFile(classloader.getResource(dir.getPath()), null);
             } else if (loader != null) {
                 dir = IOUtilities.toFile(loader.getResource(dir.getPath()), null);
             }
         } catch (IOException e) {
             /*
              * The URL to the palette files can not be converted to a File object.
              * Consequently we can not scan the list of files in the directory.
              * Returns only the palettes which were explicitly declared.
              */
             return found;
         }
         if (dir == null) {
             return found;
         }
         final String[] list = dir.list(new DefaultFileFilter('*' + extension));
         if (list == null) {
             return found; // Not a directory.
         }
         final int extLg = extension.length();
         for (final String filename : list) {
             final int lg = filename.length();
             if (lg > extLg && filename.regionMatches(true, lg - extLg, extension, 0, extLg)) {
                 names.add(filename.substring(0, lg-extLg));
             }
         }
         return true;
     }
getColors() [1/2]
Color [] getColors (final LineNumberReader input, final String name) throws IOException private
Reads the colors declared in the specified input stream.
Colors must be encoded on 3 or 4 columns. If 3 columns, it is assumed RGB values. If 4 columns, it is assumed RGBA values. Values must be in the 0-255 ranges. Empty lines and lines starting by
'#'
are ignored.
Parameters
input The stream to read.
name The palette name to read. Used for formatting error message only.
Returns
The colors.
Exceptions
IOException if an I/O error occurred.
IIOException if a syntax error occurred.
References PaletteFactory.byteValue(), LineFormat.getValues(), LineFormat.setLine(), and PaletteFactory.syntaxError().
Referenced by IndexedPalette.createARGB(), PaletteFactory.getColors(), and Palette.getLegend().
{
         int[] values = null;
         final LineFormat reader = (locale!=null) ? new LineFormat(locale) : new LineFormat();
         final List<Color> colors = new ArrayList<>();
         String line; while ((line=input.readLine()) != null) try {
             line = line.trim();
             if (line.isEmpty())            continue;
             if (line.charAt(0) == '#')     continue;
             if (reader.setLine(line) == 0) continue;
             values = reader.getValues(values);
             int A=255,R,G,B;
             switch (values.length) {
                 case 4: A = byteValue(values[3]); // fall through
                 case 3: B = byteValue(values[2]);
                         G = byteValue(values[1]);
                         R = byteValue(values[0]);
                         break;
                 default: {
                     throw syntaxError(input, name, null);
                 }
             }
             final Color color;
             try {
                 color = new Color(R, G, B, A);
             } catch (IllegalArgumentException exception) {
                 /*
                  * Color constructor checks the RGBA value and throws an IllegalArgumentException
                  * if they are not in the 0-255 range. Intercept this exception and rethrows as a
                  * checked IIOException, since we want to notify the user that the palette file is
                  * badly formatted. (additional note: it is somewhat redundant with byteValue(int)
                  * work. Let keep it as a safety).
                  */
                 throw syntaxError(input, name, exception);
             }
             colors.add(color);
         } catch (ParseException exception) {
             throw syntaxError(input, name, exception);
         }
         return colors.toArray(new Color[colors.size()]);
     }
getColors() [2/2]
Color [] getColors (final String name) throws IOException
Loads colors from a definition file.
If no colors were found in the current palette factory, then the fallback (if any fallback was specified to the constructor) will be queried.
{
case for single color}
If the given name starts with the
'#'
character, then the string is decoded as a color using the Color#decode(String) method (i.e., the string is interpreted as a hexadecimal RGB value) and the decoded color is returned in an array of length 1.
Parameters
name The name of the palette to load.
Returns
The set of colors, or
null
if no palette was found for the given name.
Exceptions
IOException if an error occurs during reading.
References PaletteFactory.fallback, PaletteFactory.getColors(), and PaletteFactory.getPaletteReader().
{
         final Color[] colors;
         if (name.startsWith("#")) try {
             colors = new Color[] {Color.decode(name)};
         } catch (NumberFormatException e) {
             return null;
         } else {
             try (LineNumberReader reader = getPaletteReader(name)) {
                 if (reader == null) {
                     return (fallback != null) ? fallback.getColors(name) : null;
                 }
                 colors = getColors(reader, name);
             }
         }
         return colors;
     }
getContinuousPalette()
Palette getContinuousPalette (final String name, final float minimum, final float maximum, final int dataType, final int numBands, final int visibleBand)
Creates a palette suitable for floating point values.
Parameters
name The palette name.
minimum The minimal sample value expected.
maximum The maximal sample value expected.
dataType The data type as a java.awt.image.DataBuffer#TYPE_INT, java.awt.image.DataBuffer#TYPE_FLOAT or java.awt.image.DataBuffer#TYPE_DOUBLE constant.
numBands The number of bands (usually 1).
visibleBand The band to use for color computations (usually 0).
Returns
A palette suitable for floating point values.
Since
2.4
Todo:
Current implementation ignores the name and builds a gray scale in all cases. Future version may improve on that.
References PaletteFactory.palettes.
     {
         Palette palette = new ContinuousPalette(this, name, minimum, maximum, dataType, numBands, visibleBand);
         palette = palettes.unique(palette);
         return palette;
     }
getDefault()
static synchronized PaletteFactory getDefault () static
Gets the default palette factory.
The returned factory can provide the palettes listed in the class javadoc, together with the palettes defined by any custom factories registered in the way defined by the class javadoc.
{
Note
The scan for custom factories is performed only when this method is first invoked. If a new scan is desired (for example because new JAR files are added on the classpath, then scanForPlugins(null) should be invoked explicitly.}
If custom factories are found and if they define some palettes of the same name than the ones provided by the build-in factory, then the custom palettes have precedence over the build-in ones.
Returns
The default palette factory.
References PaletteFactory.defaultFactory, PaletteFactory.PaletteFactory(), and PaletteFactory.scanForPlugins().
Referenced by PaletteFactory.scanForPlugins().
{
         if (defaultFactory == null) {
             defaultFactory = new PaletteFactory();
             scanForPlugins(null);
         }
         return defaultFactory;
     }
getErrorResources()
final IndexedResourceBundle getErrorResources () package
Returns the resources for formatting error messages.
References Errors.getResources(), and PaletteFactory.getWarningLocale().
Referenced by PaletteFactory.byteValue(), IndexedPalette.createARGB(), Palette.ensureInsideBounds(), IndexedPalette.IndexedPalette(), Palette.Palette(), and PaletteFactory.syntaxError().
{
         return Errors.getResources(getWarningLocale());
     }
getPalette() [1/2]
Palette getPalette (final String name, final int size)
Returns the palette of the specified name and size.
The default implementation is equivalents to:
{ java return getPalette(name, 0, size, size, 1, 0); }
This method does not test the validity of the
name
argument. If there is no palette for the given name, then a java.io.FileNotFoundException will be thrown by the getter methods in the returned palette.
Parameters
name The name of the palette to load.
size The IndexColorModel index color model} size.
Returns
The palette.
Since
2.4
Referenced by PaletteFactory.getPalettePadValueFirst(), and PaletteFactory.getPalettePadValueLast().
{
         return getPalette(name, 0, size, size, 1, 0);
     }
getPalette() [2/2]
Palette getPalette (final String name, final int lower, final int upper, final int size, final int numBands, final int visibleBand)
Returns the palette of the specified name and size.
The RGB colors will be distributed in the range
lower
inclusive to
upper
exclusive. Remaining pixel values (if any) will be left to a black or transparent color by default.
This method does not test the validity of the
name
argument. If there is no palette for the given name, then a java.io.FileNotFoundException will be thrown by the getter methods in the returned palette.
Parameters
name The name of the palette to load.
lower Index of the first valid element (inclusive) in the IndexColorModel index color model} to be created.
upper Index of the last valid element (exclusive) in the IndexColorModel index color model} to be created.
size The size of the IndexColorModel index color model} to be created. This is the value to be returned by IndexColorModel#getMapSize().
numBands The number of bands (usually 1).
visibleBand The band to use for color computations (usually 0).
Returns
The palette.
Since
2.4
References PaletteFactory.palettes.
     {
         Palette palette = new IndexedPalette(this, name, lower, upper, size, numBands, visibleBand);
         palette = palettes.unique(palette);
         return palette;
     }
getPalettePadValueFirst()
Palette getPalettePadValueFirst (final String name, final int size)
Returns a palette with a <cite>pad value</cite> at index 0.
The default implementation is equivalents to:
{ java return getPalette(name, 1, size, size, 1, 0); }
This method does not test the validity of the
name
argument. If there is no palette for the given name, then a java.io.FileNotFoundException will be thrown by the getter methods in the returned palette.
Parameters
name The name of the palette to load.
size The IndexColorModel index color model} size.
Returns
The palette.
Since
2.4
References PaletteFactory.getPalette().
{
         return getPalette(name, 1, size, size, 1, 0);
     }
getPalettePadValueLast()
Palette getPalettePadValueLast (final String name, final int size)
Returns a palette with <cite>pad value</cite> at the last index.
The default implementation is equivalents to:
{ java return getPalette(name, 0, size-1, size, 1, 0); }
This method does not test the validity of the
name
argument. If there is no palette for the given name, then a java.io.FileNotFoundException will be thrown by the getter methods in the returned palette.
Parameters
name The name of the palette to load.
size The IndexColorModel index color model} size.
Returns
The palette.
Since
2.4
References PaletteFactory.getPalette().
{
         return getPalette(name, 0, size-1, size, 1, 0);
     }
getPaletteReader()
LineNumberReader getPaletteReader (String name) private
Returns a buffered reader for the specified palette.
Parameters
The palette's name to load. This name doesn't need to contains a path or an extension. Path and extension are set according value specified at construction time.
Returns
A buffered reader to read
name
, or
null
if the resource is not found.
References PaletteFactory.extension, and PaletteFactory.getReader().
Referenced by PaletteFactory.getColors().
{
         if (extension != null && !name.endsWith(extension)) {
             name += extension;
         }
         return getReader(name, "getPalette");
     }
getReader() [1/2]
LineNumberReader getReader (final String name, final String caller) private
Returns a buffered reader for the specified filename.
Parameters
The filename. Path and extension are set according value specified at construction time.
Returns
A buffered reader to read
name
, or
null
if the resource is not found.
References PaletteFactory.getResourceAsStream().
Referenced by PaletteFactory.getAvailableNames(), and PaletteFactory.getPaletteReader().
{
         final File   file = new File(directory, name);
         final String path = file.getPath().replace(File.separatorChar, '/');
         InputStream stream;
         try {
             stream = getResourceAsStream(path);
             if (stream == null) {
                 if (file.canRead()) try {
                     stream = new FileInputStream(file);
                 } catch (FileNotFoundException e) {
                     /*
                      * Should not occurs, since we checked for file existence. This is not a fatal
                      * error however, since this method is allowed to returns null if the resource
                      * is not available.
                      */
                     Logging.unexpectedException(null, PaletteFactory.class, caller, e);
                     return null;
                 } else {
                     return null;
                 }
             }
         } catch (SecurityException e) {
             Logging.recoverableException(null, PaletteFactory.class, caller, e);
             return null;
         }
         return getReader(stream);
     }
getReader() [2/2]
LineNumberReader getReader (final InputStream stream) private
Wraps the specified input stream into a reader.
{
         return new LineNumberReader((charset != null) ?
                 new InputStreamReader(stream, charset) : new InputStreamReader(stream));
     }
getResourceAsStream()
InputStream getResourceAsStream (final String name) protected
Returns an input stream for reading the specified resource.
The default implementation delegates to either Class or ClassLoader
getResourceAsStream(String)
method, depending on the type of the
loader
argument given to the constructor. Subclasses may override this method if a more elaborated mechanism is wanted for fetching resources. This is sometime required in the context of applications using particular class loaders.
Parameters
name The name of the resource to load, constructed as
directory
+
name
extension
where directory and extension were specified to the constructor, while
name
was given to the getPalette method.
Returns
The input stream, or
null
if the resources was not found.
Since
2.3
Referenced by PaletteFactory.getReader().
{
         if (loader != null) {
             return loader.getResourceAsStream(name);
         }
         if (classloader != null) {
             return classloader.getResourceAsStream(name);
         }
         return null;
     }
getWarningLocale()
synchronized Locale getWarningLocale ()
Returns the locale set by the last invocation to setWarningLocale(Locale) in the current thread.
Returns
The current locale to use for warning messages.
Since
2.4
References PaletteFactory.warningLocales().
Referenced by PaletteFactory.getErrorResources().
{
         final ThreadLocal<Locale> warningLocales = this.warningLocales;
         if (warningLocales != null) {
             return warningLocales.get();
         }
         return null;
     }
readNames()
static void readNames (final BufferedReader in, final Collection< String > names) throws IOException static private
Copies the content of the specified reader to the specified collection.
The reader is closed after this operation.
Referenced by PaletteFactory.getAvailableNames().
     {
         String line;
         while ((line = in.readLine()) != null) {
             line = line.trim();
             if (!line.isEmpty() && line.charAt(0) != '#') {
                 names.add(line);
             }
         }
         in.close();
     }
scanForPlugins()
static synchronized void scanForPlugins (final ClassLoader loader) static
Lookups for custom palette factories on the classpath.
This method is automatically invoked by getDefault() and doesn't need to be invoked explicitly, unless new JAR files have been added on the classpath or unless some specific class loader needs to be used.
Custom factories shall be declared in the following file:
{ text META-INF/services/org.geotoolkit.image.io.PaletteFactory }
Newly discovered factories have precedence over the old ones.
Parameters
loader The class loader to use, or
null
for the default one.
Since
2.4
References PaletteFactory.defaultFactory, PaletteFactory.fallback, and PaletteFactory.getDefault().
Referenced by PaletteFactory.getDefault().
{
         final Set<Class<? extends PaletteFactory>> existings = new HashSet<>();
         for (PaletteFactory p=getDefault(); p!=null; p=p.fallback) {
             existings.add(p.getClass());
         }
         final ServiceLoader<PaletteFactory> factories = (loader == null) ?
                 ServiceLoader.load(PaletteFactory.class) :
                 ServiceLoader.load(PaletteFactory.class, loader);
         for (final PaletteFactory factory : factories) {
             /*
              * Adds the scanned factory to the chain. There is no public method for doing that
              * because PaletteFactory is quasi-immutable except for this method which modifies
              * the fallback field. It is okay in this context since we just created the factory
              * instance.
              */
             if (existings.add(factory.getClass())) {
                 PaletteFactory tail = factory;
                 while (tail.fallback != null) {
                     tail = tail.fallback;
                 }
                 tail.fallback = defaultFactory;
                 defaultFactory = factory;
             }
         }
     }
setWarningLocale()
synchronized void setWarningLocale (final Locale warningLocale)
Sets the locale to use for formatting warning or error messages.
This is typically the javax.imageio.ImageReader::getLocale image reader locale}. This locale is informative only; there is no guarantee that this locale will be really used.
This method sets the locale for the current thread only. It is safe to use this palette factory concurrently in many threads, each with their own locale.
Parameters
warningLocale The locale for warning or error messages, or
null
for the Locale::getDefault() default locale}.
Since
2.4
References PaletteFactory.warningLocales().
{
         if (warningLocale != null) {
             if (warningLocales == null) {
                 warningLocales = warningLocales();
             }
             warningLocales.set(warningLocale);
         } else if (warningLocales != null) {
             warningLocales.remove();
         }
     }
startWithDot()
static String startWithDot (String extension) static private
Ensures that the given string starts with a dot.
References PaletteFactory.extension.
Referenced by PaletteFactory.PaletteFactory().
{
         if (extension != null && !extension.startsWith(".")) {
             extension = '.' + extension;
         }
         return extension;
     }
syntaxError()
IIOException syntaxError (final LineNumberReader input, final String name, final Exception cause) private
Prepares an exception for the specified cause, which may be.
null
.
References PaletteFactory.getErrorResources(), and Errors.Keys.IllegalLineInFile_2.
Referenced by PaletteFactory.getColors().
{
         String message = getErrorResources().getString(Errors.Keys.IllegalLineInFile_2,
                 name, input.getLineNumber());
         if (cause != null) {
             message += cause.getLocalizedMessage();
         }
         return new IIOException(message, cause);
     }
warningLocales()
synchronized ThreadLocal<Locale> warningLocales () private
Gets the warningLocales} from the fallback or create a new one.
This method invokes itself recursively in order to assign the same ThreadLocal to every factories in the chain.
References PaletteFactory.warningLocales.
Referenced by PaletteFactory.getWarningLocale(), and PaletteFactory.setWarningLocale().
{
         if (warningLocales == null) {
             warningLocales = (fallback != null) ? fallback.warningLocales() : new ThreadLocal<Locale>();
         }
         return warningLocales;
     }
Member Data Documentation
charset
final Charset charset private
The charset to use for parsing files, or.
null
for the current default.
Referenced by PaletteFactory.PaletteFactory().
classloader
final ClassLoader classloader private
The class loader from which to load the palette definition files.
If
null
and loader is null as well, then loading will occurs from the system current working directory.
DEFAULT_DIRECTORY
final File DEFAULT_DIRECTORY = new File("colors") static private
The default sub-directory, relative to the.
PaletteFactory
class directory.
Referenced by PaletteFactory.PaletteFactory().
defaultFactory
PaletteFactory defaultFactory static private
The default palette factory.
Referenced by PaletteFactory.getDefault(), and PaletteFactory.scanForPlugins().
directory
final File directory private
The base directory from which to search for palette definition files.
If
null
, then the working directory (
"."
) is assumed.
Referenced by PaletteFactory.PaletteFactory().
extension
final String extension private
The file extension.
Referenced by PaletteFactory.getPaletteReader(), and PaletteFactory.startWithDot().
fallback
PaletteFactory fallback private
The fallback factory, or.
null
if there is none. The fallback factory will be queried if a palette was not found in current factory.
This field should be considered as final. It is modified by scanForPlugins only.
Referenced by PaletteFactory.getColors(), PaletteFactory.PaletteFactory(), and PaletteFactory.scanForPlugins().
LIST_FILE
final String LIST_FILE = "list.txt" static private
The file which contains a list of available color palettes.
This file is optional. If such file exists in the same directory than the one that contains the palettes, this file will be used by getAvailableNames().
loader
final Class<?> loader private
An alternative to classloader for loading resources.
At most one of
classloader
and
loader
can be non-null. If both are
null
, then loading will occurs from the system current working directory.
Referenced by PaletteFactory.PaletteFactory().
locale
final Locale locale private
The locale to use for parsing files, or.
null
for the current default.
Referenced by PaletteFactory.PaletteFactory().
palettes
final WeakHashSet<Palette> palettes = new WeakHashSet<>(Palette.class) protected
The set of palettes already created and not yet garbage-collected.
The
getPalette
method implementations shall return WeakHashSet::unique unique}
Palette
instances as below:
{ java public Palette getPalette(...) { Palette palette = ...; palette = palettes.unique(palette); // Ensure that the instance is unique. return palette; } }
The purpose is to share existing ColorModel instances when possible, since they may be big (up to 256 kilobytes for an IndexColorModel with 16 bits integers). This mechanism works provided that Palette#createImageTypeSpecifier() lazily create the color model only when first invoked.
Since
3.11
Referenced by PaletteFactory.getContinuousPalette(), and PaletteFactory.getPalette().
protectedPalettes
final Set<Palette> protectedPalettes = new HashSet<>() package
The set of palettes protected from garbage collection.
We protect a palette as long as it holds a reference to a color model - this is necessary in order to prevent multiple creation of the same IndexColorModel. The references are cleaned by PaletteDisposer.
Referenced by PaletteDisposer.dispose(), and PaletteDisposer.PaletteDisposer().
warningLocales
transient ThreadLocal<Locale> warningLocales private
The locale to use for formatting error messages, or.
null
for the current default. This locale is informative only; there is no guarantee that this locale will be really used.
Referenced by PaletteFactory.warningLocales().