jena-geo: DeferredPlanarImage Class Reference
DeferredPlanarImage Class Reference
A tiled image to be used by renderer when the actual image may take a while to compute.
Classes
class Entry
An entry in the buffers map.
Public Member Functions
DeferredPlanarImage (final RenderedImage source)
Constructs a new instance of.
Vector< RenderedImage > getSources ()
Returns the source images.
synchronized Raster getTile (final int tileX, final int tileY)
Returns the specified tile, or a default one if the requested tile is not yet available.
void tileComputed (final Object eventSource, final TileRequest[] requests, final PlanarImage image, final int tileX, final int tileY, final Raster tile)
Invoked when a tile has been computed.
void tileCancelled (final Object eventSource, final TileRequest[] requests, final PlanarImage image, final int tileX, final int tileY)
Invoked when a tile computation has been canceled.
void tileComputationFailure (final Object eventSource, final TileRequest[] requests, final PlanarImage image, final int tileX, final int tileY, final Throwable cause)
Invoked when a tile computation failed.
void tileUpdate (final WritableRenderedImage source, final int tileX, final int tileY, final boolean willBeWritable)
Invoked if the underlying image is writable and one of its tile changed.
synchronized void addTileObserver (final TileObserver observer)
Adds an observer.
synchronized void removeTileObserver (final TileObserver observer)
Removes an observer.
WritableRaster getWritableTile (final int tileX, final int tileY)
Checks out a tile for writing.
void releaseWritableTile (final int tileX, final int tileY)
Relinquishes the right to write to a tile.
synchronized boolean hasTileWriters ()
Returns whether any tile is checked out for writing.
synchronized boolean isTileWritable (final int tileX, final int tileY)
Returns whether a tile is currently checked out for writing.
synchronized Point [] getWritableTileIndices ()
Returns an array of Point objects indicating which tiles are checked out for writing.
void setData (Raster r)
Sets a rectangle of the image to the contents of the raster.
synchronized void dispose ()
Provides a hint that this image will no longer be accessed from a reference in user space.
Private Member Functions
int getTileIndice (final int tileX, final int tileY)
Returns the index in requests and pendings array for the given tile.
void fireTileUpdate (final int tileX, final int tileY, final boolean willBeWritable)
A tile is about to be updated (it is either about to be grabbed for writing, or it is being released from writing).
Static Private Member Functions
static Vector< RenderedImage > toVector (final RenderedImage image)
Wraps the specified image in a vector.
static synchronized DataBuffer getDefaultDataBuffer (final SampleModel sampleModel, final ColorModel colorModel)
Returns a databuffer for the specified sample model.
static void fill (final DataBuffer buffer, final int bank, final int value)
Sets all values in the specified bank to the specified value.
Private Attributes
final int delay
The delay (in milliseconds) to wait for a tile.
final PlanarImage image
The source image.
TileObserver [] observers
The tile observers, or.
transient TileRequest [] requests
The TileRequests for a given tile.
transient boolean [] waitings
Tells if a tile is request is waiting.
transient Raster [] pendings
Tells if a tile is in process of being computed.
Static Private Attributes
static final Logger LOGGER = Logging.getLogger("org.geotoolkit.image")
The logger for information messages.
static final int BOX_THICKNESS = 2
The thickness (in pixels) of the box to draw around deferred tiles, or 0 for disabling this feature.
static Map< Entry, DataBuffer > buffers
Empty DataBuffer for a set of SampleModel.
static final long DELAY = 500
The maximum delay (in milliseconds) to wait for a tile with one million pixels (e.g.
Detailed Description
A tiled image to be used by renderer when the actual image may take a while to compute.
This image wraps an arbitrary RenderedImage rendered image}, which may (or may not) be some image expensive to compute. When a tile is requested (through a call to getTile but the tile is not available in the wrapped image, then this class returns some default (usually black) tile and start the real tile computation in a background thread. When the actual tile is available, this class fire a tileUpdate event, thus given a chance to a renderer to repaint again this image with the new tiles.
Example of use:
{ java public class Renderer extends JPanel implements TileObserver { private DeferredPlanarImage image;
public Renderer(RenderedImage toPaint) { image = new DeferredPlanarImage(toPaint); image.addTileObserver(this); }
public void tileUpdate(WritableRenderedImage source, int tileX, int tileY, boolean willBeWritable) { repaint(); }
public void paint(Graphics gr) { ((Graphics2D) gr).drawRenderedImage(image); } } }
Author
Rémi Eve (IRD)
Martin Desruisseaux (IRD)
Version
3.00
Since
2.3
Constructor & Destructor Documentation
DeferredPlanarImage()
DeferredPlanarImage (final RenderedImage source)
Constructs a new instance of.
DeferredPlanarImage
.
Parameters
source The source image.
References DeferredPlanarImage.toVector().
{
         super(new ImageLayout(source), toVector(source), null);
         image = getSourceImage(0);
         image.addTileComputationListener(this);
         if (image instanceof WritableRenderedImage) {
             ((WritableRenderedImage) image).addTileObserver(this);
         }
         delay = (int) Math.min(DELAY * tileWidth * tileHeight / 1000000, DELAY);
     }
Member Function Documentation
addTileObserver()
synchronized void addTileObserver (final TileObserver observer)
Adds an observer.
This observer will be notified everytime a tile initially empty become available. If the observer is already present, it will receive multiple notifications.
Parameters
observer The observer to add.
References DeferredPlanarImage.observers.
{
         if (observer != null) {
             if (observers == null) {
                 observers = new TileObserver[] {observer};
             } else {
                 observers = ArraysExt.append(observers, observer);
             }
         }
     }
dispose()
synchronized void dispose ()
Provides a hint that this image will no longer be accessed from a reference in user space.
NOTE: this method dispose the image given to the constructor as well. This is because
DeferredPlanarImage
is used as a "view" of an other image, and the user shouldn't know that he is not using directly the other image.
References DeferredPlanarImage.image, DeferredPlanarImage.pendings, DeferredPlanarImage.requests, and DeferredPlanarImage.waitings.
{
         if (image instanceof WritableRenderedImage) {
             ((WritableRenderedImage) image).removeTileObserver(this);
         }
         image.removeTileComputationListener(this);
         requests = null;
         waitings = null;
         pendings = null;
         super.dispose();
         image.dispose();
     }
fill()
static void fill (final DataBuffer buffer, final int bank, final int value) static private
Sets all values in the specified bank to the specified value.
Parameters
buffer The databuffer in which to set all sample values.
bank Index of the bank to set.
value The value.
{
         switch (buffer.getDataType()) {
             case TYPE_BYTE :  Arrays.fill(((DataBufferByte)   buffer).getData(bank),   (byte) value); break;
             case TYPE_SHORT:  Arrays.fill(((DataBufferShort)  buffer).getData(bank),  (short) value); break;
             case TYPE_USHORT: Arrays.fill(((DataBufferUShort) buffer).getData(bank),  (short) value); break;
             case TYPE_INT:    Arrays.fill(((DataBufferInt)    buffer).getData(bank),          value); break;
             case TYPE_FLOAT:  Arrays.fill(((DataBufferFloat)  buffer).getData(bank),  (float) value); break;
             case TYPE_DOUBLE: Arrays.fill(((DataBufferDouble) buffer).getData(bank), (double) value); break;
             default: throw new RasterFormatException(String.valueOf(buffer));
         }
     }
fireTileUpdate()
void fireTileUpdate (final int tileX, final int tileY, final boolean willBeWritable) private
A tile is about to be updated (it is either about to be grabbed for writing, or it is being released from writing).
References DeferredPlanarImage.LOGGER, and DeferredPlanarImage.observers.
Referenced by DeferredPlanarImage.getTile(), DeferredPlanarImage.tileComputed(), and DeferredPlanarImage.tileUpdate().
{
         final TileObserver[] observers = this.observers; // Avoid the need for synchronization.
         if (observers != null) {
             final int length = observers.length;
             for (int i=0; i<length; i++) {
                 try {
                     observers[i].tileUpdate(this, tileX, tileY, willBeWritable);
                 } catch (RuntimeException cause) {
                     /*
                      * An exception occurred in the user code. Unfortunately, we are probably not in
                      * the mean user thread (e.g. the Swing thread).  This method is often invoked
                      * from some JAI's worker thread, which we don't want to corrupt. Log a warning
                      * for the user and lets the JAI's worker thread continue its work.
                      */
                     String message = cause.getLocalizedMessage();
                     if (message == null) {
                         message = Classes.getShortClassName(cause);
                     }
                     final LogRecord record = new LogRecord(Level.WARNING, message);
                     record.setSourceClassName(observers[i].getClass().getCanonicalName());
                     record.setSourceMethodName("tileUpdate");
                     record.setThrown(cause);
                     record.setLoggerName(LOGGER.getName());
                     LOGGER.log(record);
                 }
             }
         }
     }
getDefaultDataBuffer()
static synchronized DataBuffer getDefaultDataBuffer (final SampleModel sampleModel, final ColorModel colorModel) static private
Returns a databuffer for the specified sample model.
If the image uses an IndexColorModel and a IndexColorModel::getTransparentPixel transparent pixel} is defined, then raster sample values are initialized to the transparent pixel.
References DeferredPlanarImage.Entry.box, DeferredPlanarImage.BOX_THICKNESS, DeferredPlanarImage.buffers, DeferredPlanarImage.Entry.Entry(), DeferredPlanarImage.Entry.fill, ColorUtilities.getColorIndex(), and ColorUtilities.getTransparentPixel().
Referenced by DeferredPlanarImage.getTile().
     {
         int fill = 0;
         int box  = 0;
         if (colorModel instanceof IndexColorModel) {
             final IndexColorModel colors = (IndexColorModel) colorModel;
             fill = ColorUtilities.getTransparentPixel(colors);
             if (BOX_THICKNESS > 0 && Math.min(sampleModel.getWidth(), sampleModel.getHeight()) >= 64) {
                 box = ColorUtilities.getColorIndex(colors, Color.DARK_GRAY, fill);
             } else {
                 // Avoid drawing the box if tiles are too small.
                 box = fill;
             }
         }
         final Entry entry = new Entry(sampleModel, fill, box);
         if (buffers == null) {
             buffers = new WeakValueHashMap<>(Entry.class);
         }
         DataBuffer buffer = buffers.get(entry);
         if (buffer != null) {
             return buffer;
         }
         /*
          * No suitable data buffer existed prior to this call. Create a new one and fill it
          * with the transparent color. Note that no filling is needed if the transparent value
          * is 0, since the data buffer is already initialized to 0.
          */
         buffer = sampleModel.createDataBuffer();
         if (fill > 0) {
             for (int bank=buffer.getNumBanks(); --bank>=0;) {
                 fill(buffer, bank, fill);
             }
         }
         /*
          * Draw a box around the tile. This is just a visual clue about tile location.
          * Current implementation draw a box only for type byte with a single band.
          */
         if (BOX_THICKNESS > 0 && box != fill) {
             if (sampleModel.getNumBands() == 1) {
                 final int width = sampleModel.getWidth();
                 int thickness = BOX_THICKNESS;
                 int offset = (width + 1) * thickness;
                 switch (buffer.getDataType()) {
                     case TYPE_BYTE: {
                         final byte[] array = ((DataBufferByte) buffer).getData(0);
                         Arrays.fill(array, 0, offset, (byte) box);
                         Arrays.fill(array, array.length-offset, array.length, (byte) box);
                         thickness *= 2;
                         while ((offset += width) < array.length) {
                             Arrays.fill(array, offset-thickness, offset, (byte) box);
                         }
                         break;
                     }
                 }
             }
         }
         buffers.put(entry, buffer);
         return buffer;
     }
getSources()
Vector<RenderedImage> getSources ()
Returns the source images.
{
         return super.getSources();
     }
getTile()
synchronized Raster getTile (final int tileX, final int tileY)
Returns the specified tile, or a default one if the requested tile is not yet available.
If the requested tile is not immediately available, then an empty tile is returned and a notification will be sent later through TileObserver when the real tile will be available.
Parameters
tileX Tile X index.
tileY Tile Y index.
Returns
The requested tile.
References Loggings.Keys.DeferredTilePainting_2, DeferredPlanarImage.delay, DeferredPlanarImage.fireTileUpdate(), Loggings.format(), DeferredPlanarImage.getDefaultDataBuffer(), DeferredPlanarImage.getTileIndice(), DeferredPlanarImage.image, DeferredPlanarImage.pendings, DeferredPlanarImage.requests, and DeferredPlanarImage.waitings.
{
         if (requests == null) {
             requests = new TileRequest[getNumXTiles() * getNumYTiles()];
         }
         final int tileIndex = getTileIndice(tileX, tileY);
         TileRequest request = requests[tileIndex];
         if (request == null) {
             request = image.queueTiles(new Point[]{new Point(tileX, tileY)});
             requests[tileIndex] = request;
         }
         switch (request.getTileStatus(tileX, tileY)) {
             default: {
                 LOGGER.warning("Unknow tile status");
                 // Fall through
             }
             case TileRequest.TILE_STATUS_CANCELLED:  // Fall through
             case TileRequest.TILE_STATUS_FAILED:     // Fall through
             case TileRequest.TILE_STATUS_COMPUTED:   return image.getTile(tileX, tileY);
             case TileRequest.TILE_STATUS_PENDING:    // Fall through
             case TileRequest.TILE_STATUS_PROCESSING: break;
         }
         /*
          * The tile is not yet available. A background thread should be computing it right
          * now. Wait a little bit in case the tile computation is very fast. If we can get
          * the tile in a very short time, it would be more efficient than invoking some
          * 'repaint()' method later.
          */
         if (pendings != null) {
             if (pendings[tileIndex] != null) {
                 return pendings[tileIndex];
             }
         }
         if (delay != 0) {
             if (waitings == null) {
                 waitings = new boolean[requests.length];
             }
             waitings[tileIndex] = true;
             try {
                 wait(delay);
             } catch (InterruptedException exception) {
                 // Somebody doesn't want to lets us sleep. Go back to work.
             }
             waitings[tileIndex] = false;
             switch (request.getTileStatus(tileX, tileY)) {
                 default: return image.getTile(tileX, tileY);
                 case TileRequest.TILE_STATUS_PENDING:    // Fall through
                 case TileRequest.TILE_STATUS_PROCESSING: break;
             }
         }
         /*
          * The tile is not yet available and seems to take a long time to compute.
          * Flag that this tile will need to be repainted later and returns an empty tile.
          */
         if (LOGGER.isLoggable(Level.FINER)) {
             final LogRecord record = Loggings.format(Level.FINER,
                     Loggings.Keys.DeferredTilePainting_2, tileX, tileY);
             record.setSourceClassName(DeferredPlanarImage.class.getName());
             record.setSourceMethodName("getTile");
             record.setLoggerName(LOGGER.getName());
             LOGGER.log(record);
         }
         if (pendings == null) {
             pendings = new Raster[requests.length];
         }
         final Point      origin = new Point(tileXToX(tileX), tileYToY(tileY));
         final DataBuffer buffer = getDefaultDataBuffer(sampleModel, colorModel);
         final Raster     raster = Raster.createRaster(sampleModel, buffer, origin);
         pendings[tileIndex] = raster;
         fireTileUpdate(tileX, tileY, true);
         return raster;
     }
getTileIndice()
int getTileIndice (final int tileX, final int tileY) private
Returns the index in requests and pendings array for the given tile.
The
x
index varies fastest.
Referenced by DeferredPlanarImage.getTile(), DeferredPlanarImage.getWritableTileIndices(), DeferredPlanarImage.isTileWritable(), and DeferredPlanarImage.tileComputed().
{
         assert tileX >= getMinTileX() && tileX <= getMaxTileX() : tileX;
         assert tileY >= getMinTileY() && tileY <= getMaxTileY() : tileY;
         return (tileY - getMinTileY()) * getNumXTiles() +
                (tileX - getMinTileX());
     }
getWritableTile()
WritableRaster getWritableTile (final int tileX, final int tileY)
Checks out a tile for writing.
Since
DeferredPlanarImage
are not really writable, this method throws an UnsupportedOperationException.
{
         throw new UnsupportedOperationException();
     }
getWritableTileIndices()
synchronized Point [] getWritableTileIndices ()
Returns an array of Point objects indicating which tiles are checked out for writing.
Returns null if none are checked out.
References DeferredPlanarImage.getTileIndice(), and DeferredPlanarImage.pendings.
{
         final Raster[] pendings = this.pendings;
         Point[] indices = null;
         if (pendings != null) {
             int count = 0;
             final int minX = getMinTileX();
             final int minY = getMinTileY();
             final int numX = getNumXTiles();
             final int length = pendings.length;
             for (int i=0; i<length; i++) {
                 if (pendings[i] != null) {
                     if (indices == null) {
                         indices = new Point[length - i];
                     }
                     final int x = i % numX + minX;
                     final int y = i / numX + minY;
                     assert getTileIndice(x,y) == i : i;
                     indices[count++] = new Point(x,y);
                 }
             }
             if (indices != null) {
                 indices = ArraysExt.resize(indices, count);
             }
         }
         return indices;
     }
hasTileWriters()
synchronized boolean hasTileWriters ()
Returns whether any tile is checked out for writing.
References DeferredPlanarImage.pendings.
{
         final Raster[] pendings = this.pendings;
         if (pendings != null) {
             final int length = pendings.length;
             for (int i=0; i<length; i++) {
                 if (pendings[i] != null) {
                     return true;
                 }
             }
         }
         return false;
     }
isTileWritable()
synchronized boolean isTileWritable (final int tileX, final int tileY)
Returns whether a tile is currently checked out for writing.
References DeferredPlanarImage.getTileIndice(), and DeferredPlanarImage.pendings.
{
         final Raster[] pendings = this.pendings;
         return pendings != null && pendings[getTileIndice(tileX, tileY)] != null;
     }
releaseWritableTile()
void releaseWritableTile (final int tileX, final int tileY)
Relinquishes the right to write to a tile.
Since
DeferredPlanarImage
are not really writable, this method throws an IllegalStateException (the state is really illegal since getWritableTile should never have succeeded).
{
         throw new IllegalStateException();
     }
removeTileObserver()
synchronized void removeTileObserver (final TileObserver observer)
Removes an observer.
If the observer was not registered, nothing happens. If the observer was registered for multiple notifications, it will now be registered for one fewer.
Parameters
observer The observer to remove.
References DeferredPlanarImage.observers.
{
         if (observers != null) {
             for (int i=observers.length; --i>=0;) {
                 if (observers[i] == observer) {
                     observers = ArraysExt.remove(observers, i, 1);
                     break;
                 }
             }
         }
     }
setData()
void setData (Raster r)
Sets a rectangle of the image to the contents of the raster.
Since
DeferredPlanarImage
are not really writable, this method throws an UnsupportedOperationException.
{
         throw new UnsupportedOperationException();
     }
tileCancelled()
void tileCancelled (final Object eventSource, final TileRequest [] requests, final PlanarImage image, final int tileX, final int tileY)
Invoked when a tile computation has been canceled.
The default implementation does nothing.
Parameters
eventSource The caller of this method.
requests The relevant tile computation requests as returned by the method used to queue the tile.
image The image for which tiles are being computed as specified to the TileScheduler.
tileX The X index of the tile in the tile array.
tileY The Y index of the tile in the tile array.
     {
     }
tileComputationFailure()
void tileComputationFailure (final Object eventSource, final TileRequest [] requests, final PlanarImage image, final int tileX, final int tileY, final Throwable cause)
Invoked when a tile computation failed.
Default implementation log a warning and lets the program continue as usual. We are not throwing an exception since this failure will alter the visual rendering, but will not otherwise harm the system.
Parameters
eventSource The caller of this method.
requests The relevant tile computation requests as returned by the method used to queue the tile.
image The image for which tiles are being computed as specified to the TileScheduler.
tileX The X index of the tile in the tile array.
tileY The Y index of the tile in the tile array.
cause The cause of the failure.
References DeferredPlanarImage.LOGGER.
     {
         final LogRecord record = new LogRecord(Level.WARNING, cause.getLocalizedMessage());
         record.setSourceClassName(DeferredPlanarImage.class.getName());
         record.setSourceMethodName("getTile");
         record.setThrown(cause);
         record.setLoggerName(LOGGER.getName());
         LOGGER.log(record);
     }
tileComputed()
void tileComputed (final Object eventSource, final TileRequest [] requests, final PlanarImage image, final int tileX, final int tileY, final Raster tile)
Invoked when a tile has been computed.
Parameters
eventSource The caller of this method.
requests The relevant tile computation requests as returned by the method used to queue the tile.
image The image for which tiles are being computed as specified to the TileScheduler.
tileX The X index of the tile in the tile array.
tileY The Y index of the tile in the tile array.
tile The computed tile.
References DeferredPlanarImage.fireTileUpdate(), DeferredPlanarImage.getTileIndice(), DeferredPlanarImage.pendings, and DeferredPlanarImage.waitings.
     {
         synchronized (this) {
             final int tileIndice = getTileIndice(tileX, tileY);
             if (waitings != null && waitings[tileIndice]) {
                 /*
                  * Notify the 'getTile(...)' method in only ONE thread that a tile is available.
                  * If tiles computation occurs in two or more background thread, then there is no
                  * guarantee that the notified thread is really the one waiting for this particular
                  * tile. However, this is not a damageable problem; the delay hint may just not be
                  * accuratly respected (the actual delay may be shorter for wrongly notified tile).
                  */
                 notify();
             }
             if (pendings == null || pendings[tileIndice] == null) {
                 return;
             }
             pendings[tileIndice] = null;
         }
         fireTileUpdate(tileX, tileY, false);
     }
tileUpdate()
void tileUpdate (final WritableRenderedImage source, final int tileX, final int tileY, final boolean willBeWritable)
Invoked if the underlying image is writable and one of its tile changed.
This method forward the call to every registered listener.
References DeferredPlanarImage.fireTileUpdate().
     {
         fireTileUpdate(tileX, tileY, willBeWritable);
     }
toVector()
static Vector<RenderedImage> toVector (final RenderedImage image) static private
Wraps the specified image in a vector.
Todo:
Should be inlined in the constructor if only Sun was to fix RFE #4093999 ("Relax constraint on placement of this()/super() call in constructors").
Referenced by DeferredPlanarImage.DeferredPlanarImage().
{
         final Vector<RenderedImage> vector = new Vector<>(1);
         vector.add(image);
         return vector;
     }
Member Data Documentation
BOX_THICKNESS
final int BOX_THICKNESS = 2 static private
The thickness (in pixels) of the box to draw around deferred tiles, or 0 for disabling this feature.
Current implementation draw a box only for DataBufferByte with only one band.
Referenced by DeferredPlanarImage.getDefaultDataBuffer().
buffers
Map<Entry,DataBuffer> buffers static private
Empty DataBuffer for a set of SampleModel.
Will be created only when first needed.
Referenced by DeferredPlanarImage.getDefaultDataBuffer().
DELAY
final long DELAY = 500 static private
The maximum delay (in milliseconds) to wait for a tile with one million pixels (e.g.
a 1000×1000 tile). The actual delay will be shorter if the tiles are smaller; for example the delay is four time smaller for a 500×500 tile. When a requested tile is not yet available, the getTile method will wait for a maximum of
DELAY
milliseconds in case the tile computation would be very fast. Set the delay to 0 in order to disable this feature.
{
Note
Must be of type long even if int would be sufficient, if order to force widening conversions.}
delay
final int delay private
The delay (in milliseconds) to wait for a tile.
When a requested tile is not yet available, the getTile method will wait for a maximum of
delay
milliseconds in case the tile computation would be very fast. Set the delay to 0 in order to disable this feature.
Referenced by DeferredPlanarImage.getTile().
image
final PlanarImage image private
The source image.
Referenced by DeferredPlanarImage.dispose(), and DeferredPlanarImage.getTile().
LOGGER
final Logger LOGGER = Logging.getLogger("org.geotoolkit.image") static private
The logger for information messages.
Referenced by DeferredPlanarImage.fireTileUpdate(), and DeferredPlanarImage.tileComputationFailure().
observers
TileObserver [] observers private
The tile observers, or.
null
if none.
Referenced by DeferredPlanarImage.addTileObserver(), DeferredPlanarImage.fireTileUpdate(), and DeferredPlanarImage.removeTileObserver().
pendings
transient Raster [] pendings private
Tells if a tile is in process of being computed.
Tile index are computed by getTileIndex. This array will be constructed only when first needed.
Referenced by DeferredPlanarImage.dispose(), DeferredPlanarImage.getTile(), DeferredPlanarImage.getWritableTileIndices(), DeferredPlanarImage.hasTileWriters(), DeferredPlanarImage.isTileWritable(), and DeferredPlanarImage.tileComputed().
requests
transient TileRequest [] requests private
The TileRequests for a given tile.
Tile index are computed by getTileIndex. This array will be constructed only when first needed.
Referenced by DeferredPlanarImage.dispose(), and DeferredPlanarImage.getTile().
waitings
transient boolean [] waitings private
Tells if a tile is request is waiting.
Tile index are computed by getTileIndex. This array will be constructed only when first needed.
Referenced by DeferredPlanarImage.dispose(), DeferredPlanarImage.getTile(), and DeferredPlanarImage.tileComputed().