jena-geo: SimpleBufferedImageOp Class Reference
SimpleBufferedImageOp Class Reference abstract
An implementation of BufferedImageOp where the result is expected to be an image of the same size than the input.
Public Member Functions
abstract RenderedImage filter (final BufferedImage src)
Applies the operation on the given image.
BufferedImage filter (final BufferedImage src, BufferedImage dest)
Applies the operation on the given image.
BufferedImage createCompatibleDestImage (final BufferedImage src, ColorModel destCM)
Creates destination image with the correct size and number of bands.
Rectangle2D getBounds2D (final BufferedImage src)
Returns the bounding box of the filtered destination image.
Point2D getPoint2D (final Point2D srcPt, final Point2D dstPt)
Returns the location of the corresponding destination point given a point in the source image.
RenderingHints getRenderingHints ()
Returns the rendering hints for this operation.
Protected Member Functions
SimpleBufferedImageOp ()
Creates a new operation.
Static Private Attributes
static final long serialVersionUID = 6973234963094057672L
For cross-version compatibility.
Detailed Description
An implementation of BufferedImageOp where the result is expected to be an image of the same size than the input.
This class is not public because we rely on JAI when we can. It is used only when an operation can not be easily described in a single JAI parameter block.
{
}
This class must be serializable because the operation may be sent over the network for execution on a remote server.
Author
Martin Desruisseaux (Geomatys)
Version
3.01
Since
3.00
Constructor & Destructor Documentation
SimpleBufferedImageOp()
SimpleBufferedImageOp () protected
Creates a new operation.
References SimpleBufferedImageOp.filter().
{
     }
Member Function Documentation
createCompatibleDestImage()
BufferedImage createCompatibleDestImage (final BufferedImage src, ColorModel destCM)
Creates destination image with the correct size and number of bands.
Referenced by SimpleBufferedImageOp.filter().
{
         if (destCM == null) {
             destCM = src.getColorModel();
         }
         final WritableRaster raster = destCM.createCompatibleWritableRaster(src.getWidth(), src.getHeight());
         return new BufferedImage(destCM, raster, false, null);
     }
filter() [1/2]
abstract RenderedImage filter (final BufferedImage src) abstract
Applies the operation on the given image.
Parameters
src The image to be filtered.
Returns
The result of the filtering operation.
Referenced by SimpleBufferedImageOp.filter(), and SimpleBufferedImageOp.SimpleBufferedImageOp().
filter() [2/2]
BufferedImage filter (final BufferedImage src, BufferedImage dest)
Applies the operation on the given image.
The default implementation invokes filter(BufferedImage) and convert the result to a BufferedImage.
Parameters
src The image to be filtered.
dest Where to store the result, or
null
.
Returns
The result of the filtering operation.
References SimpleBufferedImageOp.createCompatibleDestImage(), ImageUtilities.fill(), SimpleBufferedImageOp.filter(), and SimpleBufferedImageOp.getBounds2D().
{
         final RenderedImage result = filter(src);
         if (dest != result) {
             if (dest == null) {
                 if (result instanceof BufferedImage) {
                     return (BufferedImage) result;
                 }
                 if (result instanceof PlanarImage) {
                     return ((PlanarImage) result).getAsBufferedImage();
                 }
                 dest = createCompatibleDestImage(src, null);
             } else {
                 final Rectangle2D bounds = getBounds2D(src);
                 if (dest.getWidth() != bounds.getWidth() || dest.getHeight() != bounds.getHeight()) {
                     throw new IllegalArgumentException();
                 }
             }
             ImageUtilities.fill(dest, 0);
             final Graphics2D gr = dest.createGraphics();
             gr.drawRenderedImage(result, new AffineTransform());
             gr.dispose();
         }
         return dest;
     }
getBounds2D()
Rectangle2D getBounds2D (final BufferedImage src)
Returns the bounding box of the filtered destination image.
The default implementation returns the same bounds than the source image.
References ImageUtilities.getBounds().
Referenced by SimpleBufferedImageOp.filter().
{
         return ImageUtilities.getBounds(src);
     }
getPoint2D()
Point2D getPoint2D (final Point2D srcPt, final Point2D dstPt)
Returns the location of the corresponding destination point given a point in the source image.
The default implementation returns the same coordinates than the source point.
{
         if (dstPt == null) {
             return (Point2D) srcPt.clone();
         }
         dstPt.setLocation(srcPt);
         return dstPt;
     }
getRenderingHints()
RenderingHints getRenderingHints ()
Returns the rendering hints for this operation.
The default implementation returns an empty map.
{
         return new RenderingHints(null);
     }
Member Data Documentation
serialVersionUID
final long serialVersionUID = 6973234963094057672L static private
For cross-version compatibility.