jena-geo: TreeNode Interface Reference
TreeNode Interface Reference
Defines the requirements for an object that can be used as a tree node in a javax.swing.JTree.
Public Member Functions
Object getUserObject ()
Returns this node's user object.
Enumeration<? extends javax.swing.tree.TreeNode > children ()
Returns the children of this node as an.
String toString ()
Returns a string representation of this node suitable for a user interface.
Detailed Description
Defines the requirements for an object that can be used as a tree node in a javax.swing.JTree.
This interface adds the
getUserObject()
to Swing interface, which seems to have been forgotten in J2SE.
Author
Martin Desruisseaux (IRD)
Version
3.03
Since
2.0
Member Function Documentation
children()
Enumeration<? extends javax.swing.tree.TreeNode> children ()
Returns the children of this node as an.
Enumeration
.
Returns
The children.
Referenced by Trees.copy(), and TreeFormat.hasTreeTableNode().
getUserObject()
Object getUserObject ()
Returns this node's user object.
Returns
the Object stored at this node by the user
toString()
String toString ()
Returns a string representation of this node suitable for a user interface.
javax.swing.JTree uses this method for formatting the text to display in the widget.
Returns
The text to display in the
JTree
for this node.
Implemented in NamedTreeNode, and DefaultMutableTreeNode.
Referenced by Trees.copy().