jena-geo: ImageTilesCache Class Reference
ImageTilesCache Class Reference
Stock all java.awt.image.Raster contained from define java.awt.image.RenderedImage.
Public Member Functions
long getUsedCapacity ()
Get currently used amount of memory, this is just an estimation.
Package Functions
ImageTilesCache (RenderedImage ri, ReferenceQueue queue, LargeCache cache) throws IOException
void add (int tileX, int tileY, WritableRaster raster) throws IOException
Add a java.awt.image.Raster in list and check list to don't exceed memory capacity.
void remove (int tileX, int tileY)
Remove java.awt.image.Raster at tileX tileY mosaic coordinates.
Raster getRaster (int tileX, int tileY) throws IOException, IllegalArgumentException
Return java.awt.image.Raster at tileX tileY mosaic coordinates.
void removeTiles () throws IOException
Remove all file and directory relevant to this cached image.
void capacityChanged () throws IOException
Affect a new memory capacity and update java.awt.image.Raster list from new memory capacity set.
Static Package Functions
[static initializer]
Private Member Functions
ReadWriteLock getLock (final Point key)
when you use the lock keep it until release
void add (Point tileCorner, WritableRaster raster) throws IOException
long getRasterWeight (final Raster raster)
Define the weight of a java.awt.image.Raster.
void writeRaster (final TileRasterCache lRaster) throws IOException
Write java.awt.image.Raster within org.geotoolkit.image.io.large.TileRasterCache object on hard disk at appropriate quad tree emplacement.
void releaseReader (ImageReader imageReader)
Release ImageReader and his input.
void releaseWriter (ImageWriter imgWriter)
Release ImageWriter and his output.
WritableRaster checkRaster (WritableRaster raster, Point tileCorner)
void checkMap () throws IOException
Private Attributes
final LargeCache cache
ColorModel cm
final int minTileX
final int minTileY
final int numTilesX
final int numTilesY
final QuadTreeDirectory qTD
final int riMinX
final int riMinY
final int riTileWidth
final int riTileHeight
final int dataTypeWeight
final boolean isWritableRenderedImage
final WeakValueHashMap< Point, ReadWriteLock > locks = new WeakValueHashMap<>(Point.class)
Tile by Tile locks.
final AtomicLong usedCapacity = new AtomicLong(0)
Contains tiles of pointed image.
final Map< Point, TileRasterCache > tiles
Static Private Attributes
static final Logger LOGGER = Logging.getLogger("org.geotoolkit.image.io.large")
Logger to show problem during Tile deletion.
static final Path TEMPORARY_PATH = Paths.get(System.getProperty("java.io.tmpdir"))
static final String FORMAT = "geotiff"
static final ImageReaderSpi READER_SPI
static final ImageWriterSpi WRITER_SPI
static final Point WPOINT = new Point(0, 0)
Detailed Description
Stock all java.awt.image.Raster contained from define java.awt.image.RenderedImage.
It's a map whose key is tile location, and value is the value the tile data. We use a java.util.LinkedHashMap, so when we need to remove an element, we will take the oldest one.
Author
Rémi Maréchal (Geomatys).
Alexis Manin (Geomatys).
Johann Sorel (Geomatys).
Constructor & Destructor Documentation
ImageTilesCache()
ImageTilesCache (RenderedImage ri, ReferenceQueue queue, LargeCache cache) throws IOException package
List which contain java.awt.image.Raster from java.awt.image.RenderedImage owner.
If some of java.awt.image.Raster weight within list exceed memory capacity, java.awt.image.Raster are stored on hard disk at appropriate quad tree emplacement in temporary system directory.
Note : java.awt.image.Raster are stored in tiff format to avoid onerous, compression decompression, cost during disk writing reading.
Parameters
ri java.awt.image.RenderedImage which contain all raster in list.
memoryCapacity storage capacity in Byte.
enableSwap flag that enable memory swapping on filesystem.
Exceptions
java.io.IOException if impossible to create javax.imageio.ImageReader or javax.imageio.ImageWriter.
References ImageTilesCache.cache, and LargeCache.isEnableSwap().
{
         super(ri, queue);
         //cache properties.
         this.cache = cache;
         this.isWritableRenderedImage = ri instanceof WritableRenderedImage;
         if (ri instanceof WritableLargeRenderedImage ) {
             if (!cache.isEnableSwap())
                 throw new IllegalArgumentException("With WritableRenderedImage LargeCache must swap.");
         }
         //image owner properties.
         this.cm            = ri.getColorModel();
         this.numTilesX     = ri.getNumXTiles();
         this.numTilesY     = ri.getNumYTiles();
         this.riMinX        = ri.getMinX();
         this.riMinY        = ri.getMinY();
         this.riTileWidth   = ri.getTileWidth();
         this.riTileHeight  = ri.getTileHeight();
         this.minTileX      = ri.getMinTileX();
         this.minTileY      = ri.getMinTileY();
         //quad tree directory architecture.
         if (cache.isEnableSwap()) {
             ArgumentChecks.ensureNonNull("READER_SPI", READER_SPI);
             ArgumentChecks.ensureNonNull("WRITER_SPI", WRITER_SPI);
             final Path dirPath = Files.createTempDirectory(TEMPORARY_PATH, "img");
             this.qTD = new QuadTreeDirectory(dirPath, numTilesX, numTilesY, FORMAT, true);
         } else {
             this.qTD = null;
         }
         final int datatype = ri.getSampleModel().getDataType();
         switch (datatype) {
             case DataBuffer.TYPE_BYTE      : dataTypeWeight = 1; break;
             case DataBuffer.TYPE_SHORT     : dataTypeWeight = 2; break;
             case DataBuffer.TYPE_USHORT    : dataTypeWeight = 2; break;
             case DataBuffer.TYPE_INT       : dataTypeWeight = 4; break;
             case DataBuffer.TYPE_FLOAT     : dataTypeWeight = 4; break;
             case DataBuffer.TYPE_DOUBLE    : dataTypeWeight = 8; break;
             case DataBuffer.TYPE_UNDEFINED : dataTypeWeight = 8; break;
             default : throw new IllegalStateException("unknown raster data type");
         }
     }
Member Function Documentation
[static initializer]()
[static initializer] () static package
add() [1/2]
void add (int tileX, int tileY, WritableRaster raster) throws IOException package
Add a java.awt.image.Raster in list and check list to don't exceed memory capacity.
Parameters
tileX mosaic index in X direction of raster will be stocked.
tileY mosaic index in Y direction of raster will be stocked.
raster raster will be stocked in list.
Exceptions
java.io.IOException if an error occurs during writing.
References ImageTilesCache.checkRaster().
Referenced by LargeCache.add(), LargeCache.addTiles(), and ImageTilesCache.getRaster().
{
         final Point tileCorner = new Point(tileX - minTileX, tileY - minTileY);
         add(tileCorner, checkRaster(raster, tileCorner));
     }
add() [2/2]
void add (Point tileCorner, WritableRaster raster) throws IOException private
References ImageTilesCache.checkMap(), LargeCache.getCacheSizePerImage(), ImageTilesCache.getLock(), ImageTilesCache.getRasterWeight(), and ImageTilesCache.tiles.
{
         final long rasterWeight = getRasterWeight(raster);
         if (rasterWeight > cache.getCacheSizePerImage()) throw new IOException("Raster too large : " + rasterWeight
                 + " bytes, but maximum cache capacity is "+ cache.getCacheSizePerImage() +" bytes");
         final ReadWriteLock tileLock = getLock(tileCorner);
         tileLock.writeLock().lock();
         try {
             synchronized(tiles){
                 tiles.put(tileCorner, new TileRasterCache(tileCorner.x, tileCorner.y, rasterWeight, raster));
             }
         } finally {
             tileLock.writeLock().unlock();
         }
         //remove or cache on disk oldest raster
         checkMap();
     }
capacityChanged()
void capacityChanged () throws IOException package
Affect a new memory capacity and update java.awt.image.Raster list from new memory capacity set.
Parameters
memoryCapacity new memory capacity.
Exceptions
java.io.IOException if capacity is too low from raster weight.
java.io.IOException if cache capacity is too low from raster weight, or if impossible to write raster on disk.
References ImageTilesCache.checkMap().
{
         checkMap();
     }
checkMap()
void checkMap () throws IOException private
Check that cache weight do not exceed memory capacity.
If memory capacity is exceeded, write as many java.awt.image.Raster objects needed to not exceed memory capacity anymore.
References LargeCache.getCacheSizePerImage(), ImageTilesCache.getLock(), LargeCache.isEnableSwap(), ImageTilesCache.tiles, and ImageTilesCache.writeRaster().
Referenced by ImageTilesCache.add(), and ImageTilesCache.capacityChanged().
{
         final long maxCacheSize = cache.getCacheSizePerImage();
         if (usedCapacity.get() < maxCacheSize) return;
         final boolean swap = cache.isEnableSwap();
         Point[] pts;
         synchronized(tiles){
             pts = tiles.keySet().toArray(new Point[0]);
         }
         int i=0;
         for(long currentCapacity = usedCapacity.get(); currentCapacity>maxCacheSize && i<pts.length; currentCapacity = usedCapacity.get(),i++){
             Point key = pts[i];
             if(key==null) continue;
             final ReadWriteLock rwl = getLock(key);
             if (rwl.writeLock().tryLock()) {
                 try {
                     final TileRasterCache tr;
                     synchronized (tiles) {
                         tr = tiles.remove(key);
                     }
                     if (tr != null && swap) {
                         writeRaster(tr);
                     }
                 } finally {
                     rwl.writeLock().unlock();
                 }
             }
         }
     }
checkRaster()
WritableRaster checkRaster (WritableRaster raster, Point tileCorner) private
Verify that java.awt.image.Raster coordinate is agree from java.awt.image.RenderedImage location.
If location is correct return java.awt.image.Raster else return new java.awt.image.Raster with correct
location but with same internal value from java.awt.image.Raster.
Parameters
raster raster will be checked.
tileCorner tile location within renderedImage owner.
Returns
raster with correct coordinate from its image owner.
References ImageTilesCache.riMinX, and ImageTilesCache.riMinY.
Referenced by ImageTilesCache.add(), and ImageTilesCache.getRaster().
{
         final int mx = riTileWidth  * tileCorner.x + riMinX;
         final int my = riTileHeight * tileCorner.y + riMinY;
         if (raster.getMinX() != mx || raster.getMinY() != my) {
             return Raster.createWritableRaster(raster.getSampleModel(), raster.getDataBuffer(), new Point(mx, my));
         }
         return raster;
     }
getLock()
ReadWriteLock getLock (final Point key) private
when you use the lock keep it until release
Parameters
key
Returns
References ImageTilesCache.locks.
Referenced by ImageTilesCache.add(), ImageTilesCache.checkMap(), ImageTilesCache.getRaster(), and ImageTilesCache.remove().
{
         ReadWriteLock lock;
         synchronized(locks){
             lock = locks.get(key);
             if (lock == null) {
                 lock = new ReentrantReadWriteLock();
                 locks.put(key, lock);
             }
         }
         return lock;
     }
getRaster()
Raster getRaster (int tileX, int tileY) throws IOException, IllegalArgumentException package
Return java.awt.image.Raster at tileX tileY mosaic coordinates.
Parameters
tileX mosaic index in X direction.
tileY mosaic index in Y direction.
Returns
Raster at tileX tileY mosaic coordinates.
Exceptions
java.io.IOException if an error occurs during reading..
IllegalArgumentException if raster not found in memory mode.
References ImageTilesCache.add(), ImageTilesCache.checkRaster(), ImageTilesCache.getLock(), QuadTreeDirectory.getPath(), TileRasterCache.getRaster(), and ImageTilesCache.tiles.
Referenced by LargeCache.getTile(), and LargeCache.getTiles().
{
         final Point tileCorner = new Point(tileX - minTileX, tileY - minTileY);
         // Check if queried raster is cached.
         final ReadWriteLock tileLock = getLock(tileCorner);
         tileLock.readLock().lock();
         try {
             final TileRasterCache lRaster;
             synchronized(tiles){
                 lRaster= tiles.get(tileCorner);
             }
             if (lRaster != null) {
                 return lRaster.getRaster();
             }
         } finally {
             tileLock.readLock().unlock();
         }
         if (qTD == null) {
             // raster not found in memory
             throw new IllegalArgumentException("Tile (" + tileX + ", " + tileY + ") not found in memory.");
         } else {
             //-- lock in writing
             tileLock.writeLock().lock();
             try {
                 //-- asked again getRaster() in case another thread already enter
                 //-- into this scope and has loaded tile from file system.
                 final TileRasterCache lRaster;
                 synchronized (tiles) {
                     lRaster= tiles.get(tileCorner);
                 }
                 if (lRaster != null) {
                     return lRaster.getRaster();
                 }
                 // If not, we must take it from input quad-tree.
                 final Path tileFile = Paths.get(qTD.getPath(tileCorner.x, tileCorner.y));
                 if (Files.exists(tileFile)) {
                     // TODO : Use a "pool" of readers, instead of creating one each time ?
                     final ImageReader imgReader = READER_SPI.createReaderInstance();
                     final BufferedImage buff;
                     try {
                         imgReader.setInput(tileFile);
                         buff = imgReader.read(0);
                     }catch (Exception ex){
                         throw ex;
                     }finally {
                         imgReader.dispose();
                     }
                     //add in cache list.
                     final WritableRaster checkedRaster = checkRaster(buff.getRaster(), tileCorner);
                     add(tileCorner, checkedRaster);
                     return checkedRaster;
                 }
             } finally {
                tileLock.writeLock().unlock();
             }
         }
         throw new IOException("Tile (" + tileX + ", " + tileY + ") unknown. Cannot get raster.");
     }
getRasterWeight()
long getRasterWeight (final Raster raster) private
Define the weight of a java.awt.image.Raster.
Parameters
raster raster which will be weigh.
Returns
raster weight.
References ImageTilesCache.dataTypeWeight.
Referenced by ImageTilesCache.add().
{
         final SampleModel rsm = raster.getSampleModel();
         final int width = (rsm instanceof ComponentSampleModel) ? ((ComponentSampleModel) rsm).getScanlineStride() : raster.getWidth()*rsm.getNumDataElements();
         return width * raster.getHeight() * dataTypeWeight;
     }
getUsedCapacity()
long getUsedCapacity ()
Get currently used amount of memory, this is just an estimation.
Returns
memory used.
{
         return usedCapacity.get();
     }
releaseReader()
void releaseReader (ImageReader imageReader) private
Release ImageReader and his input.
TODO replace with XImageIO utility methods
Parameters
imageReader
{
         if(imageReader != null) {
             Object writerOutput = imageReader.getInput();
             if(writerOutput instanceof OutputStream){
                 try {
                     ((OutputStream)writerOutput).close();
                 } catch (IOException ex) {
                     LOGGER.log(Level.INFO, ex.getMessage(),ex);
                 }
             }else if(writerOutput instanceof ImageOutputStream){
                 try {
                     ((ImageOutputStream)writerOutput).close();
                 } catch (IOException ex) {
                     LOGGER.log(Level.INFO, ex.getMessage(),ex);
                 }
             }
             imageReader.dispose();
         }
     }
releaseWriter()
void releaseWriter (ImageWriter imgWriter) private
Release ImageWriter and his output.
TODO replace with XImageIO utility methods
Parameters
imgWriter
Referenced by ImageTilesCache.writeRaster().
{
         if(imgWriter != null) {
             Object writerOutput = imgWriter.getOutput();
             if(writerOutput instanceof OutputStream){
                 try {
                     ((OutputStream)writerOutput).close();
                 } catch (IOException ex) {
                     LOGGER.log(Level.INFO, ex.getMessage(),ex);
                 }
             }else if(writerOutput instanceof ImageOutputStream){
                 try {
                     ((ImageOutputStream)writerOutput).close();
                 } catch (IOException ex) {
                     LOGGER.log(Level.INFO, ex.getMessage(),ex);
                 }
             }
             imgWriter.dispose();
         }
     }
remove()
void remove (int tileX, int tileY) package
Remove java.awt.image.Raster at tileX tileY mosaic coordinates.
Parameters
tileX mosaic index in X direction.
tileY mosaic index in Y direction.
References IOUtilities.deleteOnExit(), ImageTilesCache.getLock(), QuadTreeDirectory.getPath(), and ImageTilesCache.tiles.
Referenced by LargeCache.LargeCache(), LargeCache.remove(), and LargeCache.removeTiles().
{
         final Point tileCorner = new Point(tileX - minTileX, tileY - minTileY);
         final ReadWriteLock tileLock = getLock(tileCorner);
         tileLock.writeLock().lock();
         try {
             synchronized(tiles){
                 tiles.remove(tileCorner);
             }
             if (qTD != null) {
                 //quad tree
                 final Path removeFile = Paths.get(qTD.getPath(tileCorner.x, tileCorner.y));
                 //delete on hard disk if exist.
                 try {
                     Files.deleteIfExists(removeFile);
                 } catch (IOException e) {
                     //delete failed try to delete it when JVM shutdown
                     LOGGER.log(Level.FINE,"Tile delete failed : "+ e.getLocalizedMessage(), e);
                     IOUtilities.deleteOnExit(removeFile);
                 }
             }
         } finally {
             tileLock.writeLock().unlock();
         }
     }
removeTiles()
void removeTiles () throws IOException package
Remove all file and directory relevant to this cached image.
References QuadTreeDirectory.cleanDirectory(), and ImageTilesCache.tiles.
Referenced by LargeCache.LargeCache(), and LargeCache.removeTiles().
{
         //rendered image won't be used after this
         synchronized(tiles){
             tiles.clear();
             if (qTD != null) {
                 qTD.cleanDirectory();
             }
         }
     }
writeRaster()
void writeRaster (final TileRasterCache lRaster) throws IOException private
Write java.awt.image.Raster within org.geotoolkit.image.io.large.TileRasterCache object on hard disk at appropriate quad tree emplacement.
Parameters
lRaster object which contain raster.
Exceptions
java.io.IOException if impossible to write raster on disk.
References QuadTreeDirectory.getPath(), ImageTilesCache.releaseWriter(), and ImageTilesCache.WPOINT.
Referenced by ImageTilesCache.checkMap().
{
         final Path tileFile = Paths.get(qTD.getPath(lRaster.getGridX(), lRaster.getGridY()));
         if (isWritableRenderedImage || !Files.exists(tileFile)) {
             final BufferedImage toWrite = new BufferedImage(
                     cm, RasterFactory.createWritableRaster(lRaster.getRaster().getSampleModel(), lRaster.getRaster().getDataBuffer(), WPOINT),
                     cm.isAlphaPremultiplied(), null);
             // TODO : Optimize using a "writer pool" instead of creating one each time ?
             final ImageWriter imgWriter = WRITER_SPI.createWriterInstance();
             try {
                 imgWriter.setOutput(tileFile);
                 imgWriter.write(toWrite);
                 imgWriter.dispose();
             } finally {
                 releaseWriter(imgWriter);
             }
         }
     }
Member Data Documentation
cache
final LargeCache cache private
Referenced by ImageTilesCache.ImageTilesCache().
cm
ColorModel cm private
dataTypeWeight
final int dataTypeWeight private
Referenced by ImageTilesCache.getRasterWeight().
FORMAT
final String FORMAT = "geotiff" static private
isWritableRenderedImage
final boolean isWritableRenderedImage private
locks
final WeakValueHashMap<Point,ReadWriteLock> locks = new WeakValueHashMap<>(Point.class) private
Tile by Tile locks.
Referenced by ImageTilesCache.getLock().
LOGGER
final Logger LOGGER = Logging.getLogger("org.geotoolkit.image.io.large") static private
Logger to show problem during Tile deletion.
See also
checkMap()
minTileX
final int minTileX private
minTileY
final int minTileY private
numTilesX
final int numTilesX private
numTilesY
final int numTilesY private
qTD
final QuadTreeDirectory qTD private
READER_SPI
final ImageReaderSpi READER_SPI static private
riMinX
final int riMinX private
Referenced by ImageTilesCache.checkRaster().
riMinY
final int riMinY private
Referenced by ImageTilesCache.checkRaster().
riTileHeight
final int riTileHeight private
riTileWidth
final int riTileWidth private
TEMPORARY_PATH
final Path TEMPORARY_PATH = Paths.get(System.getProperty("java.io.tmpdir")) static private
tiles
final Map<Point, TileRasterCache> tiles private
Initial value:
= new LinkedHashMap<Point, TileRasterCache>(16, 0.75f, true){
        @Override
        public TileRasterCache put(Point key, TileRasterCache value) {
            final TileRasterCache last = super.put(key, value);
            if(last!=null) usedCapacity.addAndGet(-last.getWeight());
            if(value!=null) usedCapacity.addAndGet(value.getWeight());
            return last;
        }
        @Override
        public void clear() {
            super.clear();
            usedCapacity.set(0);
        }
        @Override
        public TileRasterCache remove(Object key) {
            final TileRasterCache last = super.remove(key);
            if(last!=null) usedCapacity.addAndGet(-last.getWeight());
            return last;
        }
    }
Referenced by ImageTilesCache.add(), ImageTilesCache.checkMap(), ImageTilesCache.getRaster(), ImageTilesCache.remove(), and ImageTilesCache.removeTiles().
usedCapacity
final AtomicLong usedCapacity = new AtomicLong(0) private
Contains tiles of pointed image.
TODO : Replace LargeRaster type with simple raster ? (Raster weight will be embed in org.geotoolkit.image.io.large.CachedTile
accesOrder = true : this ensure the must used element are at the top This behavior is used by the flush to remove the oldest used tiles first
We subclass the map to keep track of the used memory.
WPOINT
final Point WPOINT = new Point(0, 0) static private
Referenced by ImageTilesCache.writeRaster().
WRITER_SPI
final ImageWriterSpi WRITER_SPI static private