jena-geo: LargeCache Class Reference
LargeCache Class Reference
Manage RenderedImage and its Raster to don't exceed JVM memory capacity.
Public Member Functions
void add (RenderedImage ri, int tileX, int tileY, Raster raster)
.
void remove (RenderedImage ri, int tileX, int tileY)
.
Raster getTile (RenderedImage ri, int tileX, int tileY)
.
void removeTiles (RenderedImage ri)
.
void addTiles (RenderedImage ri, Point[] points, Raster[] rasters, Object o)
.
Raster [] getTiles (RenderedImage ri, Point[] points)
.
void setMemoryCapacity (long l)
.
long getMemoryCapacity ()
.
Raster [] getTiles (RenderedImage ri)
.
void setMemoryThreshold (float f)
.
float getMemoryThreshold ()
.
void setTileComparator (Comparator cmprtr)
.
Comparator getTileComparator ()
.
void flush ()
.
void memoryControl ()
.
void setTileCapacity (int i)
.
int getTileCapacity ()
.
void add (RenderedImage ri, int i, int i1, Raster raster, Object o)
.
Static Public Member Functions
static synchronized LargeCache getInstance ()
Package Functions
boolean isEnableSwap ()
long getCacheSizePerImage ()
Private Member Functions
LargeCache (long memoryCapacity, boolean enableSwap)
ImageTilesCache getOrCreateLargeMap (final RenderedImage source) throws IOException
Return the cache system associated to the given rendered image.
void updateLList ()
Affect a new memory capacity and update Raster list from new memory capacity set.
Private Attributes
final ReferenceQueue< RenderedImage > phantomQueue = new ReferenceQueue<>()
volatile long memoryCapacity
final boolean enableSwap
final WeakHashMap< RenderedImage, ImageTilesCache > tileManagers = new WeakHashMap<>()
Contains a tile manager for each cached rendered image.
final Set< ImageTilesCache > largemaps = new HashSet<>()
Static Private Attributes
static final Logger LOGGER = Logging.getLogger("org.geotoolkit.image.io.large")
static LargeCache INSTANCE
Detailed Description
Manage RenderedImage and its Raster to don't exceed JVM memory capacity.
TODO : make memory be entirely managed by the cache, instead of allow a portion of memory to each org.geotoolkit.image.io.large.ImageTilesCache. The aim is to just delegate tile manipulation to them, and get the total control over memory here. Maybe a priority system would be useful to determine which tile to release first (based on the number of times a tile has been queried ?)
Author
Rémi Maréchal (Geomatys)
Alexis Manin (Geomatys)
Constructor & Destructor Documentation
LargeCache()
LargeCache (long memoryCapacity, boolean enableSwap) private
References LargeCache.enableSwap, LargeCache.memoryCapacity, ImageTilesCache.remove(), ImageTilesCache.removeTiles(), and LargeCache.updateLList().
Referenced by LargeCache.getInstance().
{
         this.memoryCapacity = memoryCapacity;
         this.enableSwap = enableSwap;
         final Thread phantomCleaner = new Thread(new Runnable() {
             @Override
             public void run() {
                 while (true) {
                     try {
                         final ImageTilesCache removed = (ImageTilesCache) phantomQueue.remove();
                         largemaps.remove(removed);
                         removed.removeTiles();
                         // Re-distribute freed memory amount between remaining caches.
                         updateLList();
                     } catch (InterruptedException e) {
                         LOGGER.log(Level.WARNING, "Reference cleaner has been interrupted ! It could cause severe memory leaks.");
                         return;
                     } catch (Throwable t) {
                         LOGGER.log(Level.WARNING, "An image reference cannot be released. It's likely to cause memory leaks !");
                     }
                 }
             }
         });
         phantomCleaner.setName("LargeCache cleaner deamon");
         phantomCleaner.setDaemon(true);
         phantomCleaner.start();
     }
Member Function Documentation
add() [1/2]
void add (RenderedImage ri, int tileX, int tileY, Raster raster)
.
References ImageTilesCache.add(), and LargeCache.getOrCreateLargeMap().
Referenced by WritableLargeRenderedImage.fillWritableImage(), and WritableLargeRenderedImage.setData().
{
         // TODO : check existing tile, flush it before replacing it, or do nothing.
         if (!(raster instanceof WritableRaster)) {
             throw new IllegalArgumentException("raster must be WritableRaster instance");
         }
         try {
             final ImageTilesCache lL = getOrCreateLargeMap(ri);
             lL.add(tileX, tileY, (WritableRaster) raster);
         } catch (IOException ex) {
             throw new RuntimeException("impossible to add raster (write raster on disk)", ex);
         }
     }
add() [2/2]
void add (RenderedImage ri, int i, int i1, Raster raster, Object o)
.
{
         throw new UnsupportedOperationException("Not supported yet.");
     }
addTiles()
void addTiles (RenderedImage ri, Point [] points, Raster [] rasters, Object o)
.
References ImageTilesCache.add(), and LargeCache.getOrCreateLargeMap().
{
         if (points.length != rasters.length)
             throw new IllegalArgumentException("point and raster tables must have same length.");
         final ImageTilesCache lL;
         try {
             lL = getOrCreateLargeMap(ri);
         } catch (IOException e) {
             throw new RuntimeException("There is no cache system for the given image, and we cannot create any.", e);
         }
         for (int id = 0, l = points.length; id < l; id++) {
             if (!(rasters[id] instanceof WritableRaster))
                 throw new IllegalArgumentException("raster must be WritableRaster instance");
             try {
                 lL.add(points[id].x, points[id].y, (WritableRaster) rasters[id]);
             } catch (IOException ex) {
                 throw new RuntimeException("impossible to add raster (write raster on disk)", ex);
             }
         }
     }
flush()
void flush ()
.
{
         throw new UnsupportedOperationException("Not supported yet.");
     }
getCacheSizePerImage()
long getCacheSizePerImage () package
References LargeCache.tileManagers.
Referenced by ImageTilesCache.add(), and ImageTilesCache.checkMap().
{
         synchronized(tileManagers){
             return memoryCapacity / (tileManagers.size() + 1);
         }
     }
getInstance()
static synchronized LargeCache getInstance () static
Construct tile cache mechanic.
Stock Raster while memory capacity does not exceed else write in temporary file.
Returns
TileCache
References ImageCacheConfiguration.getCacheMemorySize(), LargeCache.INSTANCE, ImageCacheConfiguration.isCacheSwapEnable(), and LargeCache.LargeCache().
Referenced by LargeRenderedImage.LargeRenderedImage(), and WritableLargeRenderedImage.WritableLargeRenderedImage().
{
         if(INSTANCE==null){
             final long memoryCapacity = ImageCacheConfiguration.getCacheMemorySize();
             final boolean enableSwap  = ImageCacheConfiguration.isCacheSwapEnable();
             INSTANCE = new LargeCache(memoryCapacity, enableSwap);
         }
         return INSTANCE;
     }
getMemoryCapacity()
long getMemoryCapacity ()
.
References LargeCache.memoryCapacity.
{
         return memoryCapacity;
     }
getMemoryThreshold()
float getMemoryThreshold ()
.
{
         throw new UnsupportedOperationException("Not supported yet.");
     }
getOrCreateLargeMap()
ImageTilesCache getOrCreateLargeMap (final RenderedImage source) throws IOException private
Return the cache system associated to the given rendered image.
If there's no such thing, it will be created / referenced then returned.
Parameters
source The image we want data from.
Returns
The found or creeated cache system.
Exceptions
IOException If the image did not have any cache system, and we cannot create one.
References LargeCache.tileManagers, and LargeCache.updateLList().
Referenced by LargeCache.add(), and LargeCache.addTiles().
{
         ImageTilesCache lL;
         synchronized (source) {
             synchronized(tileManagers){
                 lL = tileManagers.get(source);
             }
             if (lL == null) {
                 try {
                     lL = new ImageTilesCache(source, phantomQueue, this);
                 } catch (IOException ex) {
                     throw new RuntimeException("impossible to create cache list", ex);
                 }
                 synchronized(tileManagers){
                     tileManagers.put(source, lL);
                     largemaps.add(lL);
                 }
                 updateLList();
             }
         }
         return lL;
     }
getTile()
Raster getTile (RenderedImage ri, int tileX, int tileY)
.
Exceptions
java.lang.IllegalArgumentException if TileCache is in memoryMode only and the requested raster is not found on cache.
java.lang.RuntimeException if raster can't be retrieve from cache (nested IOException).
References ImageTilesCache.getRaster(), and LargeCache.tileManagers.
Referenced by WritableLargeRenderedImage.getData(), and WritableLargeRenderedImage.getTile().
{
         final ImageTilesCache cache;
         synchronized(tileManagers){
             cache = tileManagers.get(ri);
         }
         if (cache == null){
             throw new IllegalArgumentException("renderedImage doesn't exist in this "+LargeCache.class.getName());
         }
         try {
             return cache.getRaster(tileX, tileY);
         } catch (IOException ex) {
             throw (RuntimeException)(new ImagingOpException(ex.getMessage()).initCause(ex));
         }
     }
getTileCapacity()
int getTileCapacity ()
.
{
         throw new UnsupportedOperationException("Not supported yet.");
     }
getTileComparator()
Comparator getTileComparator ()
.
{
         throw new UnsupportedOperationException("Not supported yet.");
     }
getTiles() [1/2]
Raster [] getTiles (RenderedImage ri, Point [] points)
.
References ImageTilesCache.getRaster(), and LargeCache.tileManagers.
{
         final ImageTilesCache lL;
         synchronized(tileManagers){
             lL = tileManagers.get(ri);
         }
         if (lL == null)
             throw new IllegalArgumentException("renderedImage don't exist in this "+LargeCache.class.getName());
         final int l = points.length;
         final Raster[] rasters = new Raster[l];
         for (int id = 0; id < l; id++) {
             try {
                 rasters[id] = lL.getRaster(points[id].x, points[id].y);
             } catch (IOException ex) {
                 LOGGER.log(Level.WARNING, "Unreadable tile : "+points[id], ex);
             }
         }
         return rasters;
     }
getTiles() [2/2]
Raster [] getTiles (RenderedImage ri)
.
{
         throw new UnsupportedOperationException("Not supported yet.");
 //        if (!tileManagers.containsKey(ri))
 //            throw new IllegalArgumentException("renderedImage don't exist in this "+LargeCache.class.getName());
 //        try {
 //            return tileManagers.get(ri).getTiles();
 //        } catch (IOException ex) {
 //            Logging.getLogger("org.geotoolkit.image.io.large").log(Level.SEVERE, null, ex);
 //        }
 //        return null;
     }
isEnableSwap()
boolean isEnableSwap () package
References LargeCache.enableSwap.
Referenced by ImageTilesCache.checkMap(), and ImageTilesCache.ImageTilesCache().
{
         return enableSwap;
     }
memoryControl()
void memoryControl ()
.
{
         throw new UnsupportedOperationException("Not supported yet.");
     }
remove()
void remove (RenderedImage ri, int tileX, int tileY)
.
References ImageTilesCache.remove(), and LargeCache.tileManagers.
Referenced by WritableLargeRenderedImage.setData().
{
         final ImageTilesCache lL;
         synchronized(tileManagers){
             lL = tileManagers.get(ri);
         }
         if (lL == null){
             throw new IllegalArgumentException("renderedImage don't exist in this "+LargeCache.class.getName());
         }
         lL.remove(tileX, tileY);
     }
removeTiles()
void removeTiles (RenderedImage ri)
.
References ImageTilesCache.remove(), ImageTilesCache.removeTiles(), LargeCache.tileManagers, and LargeCache.updateLList().
Referenced by WritableLargeRenderedImage.finalize().
{
         final ImageTilesCache lL;
         // De-reference image
         synchronized(tileManagers){
             lL = tileManagers.remove(ri);
         }
         // Clear cache.
         if (lL != null) {
             try {
                 lL.removeTiles();
             } catch (IOException ex) {
                 throw new RuntimeException("Raster too large for remaining memory capacity", ex);
             }
             updateLList();
         }
     }
setMemoryCapacity()
void setMemoryCapacity (long l)
.
References LargeCache.updateLList().
{
         this.memoryCapacity = l;
         updateLList();
     }
setMemoryThreshold()
void setMemoryThreshold (float f)
.
{
         throw new UnsupportedOperationException("Not supported yet.");
     }
setTileCapacity()
void setTileCapacity (int i)
.
{
         throw new UnsupportedOperationException("Not supported yet.");
     }
setTileComparator()
void setTileComparator (Comparator cmprtr)
.
{
         throw new UnsupportedOperationException("Not supported yet.");
     }
updateLList()
void updateLList () private
Affect a new memory capacity and update Raster list from new memory capacity set.
TODO : delete this method when memory capacity will be entirely managed by org.geotoolkit.image.io.large.LargeCache.
Parameters
listMemoryCapacity new memory capacity.
References LargeCache.tileManagers.
Referenced by LargeCache.getOrCreateLargeMap(), LargeCache.LargeCache(), LargeCache.removeTiles(), and LargeCache.setMemoryCapacity().
{
         Object[] array;
         synchronized(tileManagers){
             array = tileManagers.values().toArray();
         }
         for (Object lL : array) {
             try {
                 ((ImageTilesCache)lL).capacityChanged();
             } catch (IOException ex) {
                 throw new RuntimeException("Raster too large for remaining memory capacity", ex);
             }
         }
     }
Member Data Documentation
enableSwap
final boolean enableSwap private
Referenced by LargeCache.isEnableSwap(), and LargeCache.LargeCache().
INSTANCE
LargeCache INSTANCE static private
Referenced by LargeCache.getInstance().
largemaps
final Set<ImageTilesCache> largemaps = new HashSet<>() private
LOGGER
final Logger LOGGER = Logging.getLogger("org.geotoolkit.image.io.large") static private
memoryCapacity
volatile long memoryCapacity private
Referenced by LargeCache.getMemoryCapacity(), and LargeCache.LargeCache().
phantomQueue
final ReferenceQueue<RenderedImage> phantomQueue = new ReferenceQueue<>() private
tileManagers
final WeakHashMap<RenderedImage, ImageTilesCache> tileManagers = new WeakHashMap<>() private
Contains a tile manager for each cached rendered image.
A tile manager job is to swap / cache image tiles as we ask it.
Note : we can not use ReentrantReadWriteLock with WeakHashMap because get and iteration methods may modify the content of the map. This is because the weak references are tested when a get occurs.
Referenced by LargeCache.getCacheSizePerImage(), LargeCache.getOrCreateLargeMap(), LargeCache.getTile(), LargeCache.getTiles(), LargeCache.remove(), LargeCache.removeTiles(), and LargeCache.updateLList().