jena-geo: QuadTreeDirectory Class Reference
QuadTreeDirectory Class Reference
Create tree directory made, starting from tree root directory, define by user.
Public Member Functions
QuadTreeDirectory (final Path treeRootPath, final int nbrElementX, final int nbrElementY, final String extension, final boolean isDeleteOnExit) throws IOException
Create tree directory made, starting from tree root directory, define by user.
Path getTreeRootPath ()
Root directory where tiles are stored.
String getPath (int x, int y)
Return appropriate path of element at X, Y position.
Protected Member Functions
void finalize () throws Throwable
Package Functions
void cleanDirectory () throws IOException
Delete root directory recursively.
Private Member Functions
void create4rchitecture (final Path path, int numXTiles, int numYTiles) throws IOException
void createDirectory (final Path path) throws IOException
Create directory at place define by StringBuilder path.A verification is done to be sure that folder has been.
String getPath (StringBuilder path, int mintx, int minty, int maxtx, int maxty, int tileX, int tileY)
boolean intersect (int minx, int miny, int maxx, int maxy, int tx, int ty)
final void checkDirectory (final Path toCheck) throws IOException
Path getExistingParent (Path child)
Search a parent folder for input file, one which actually exists on the file system.
Private Attributes
final int nbrElementX
final int nbrElementY
final Path treeRootPath
final String extension
final boolean isDeleteOnExit
Static Private Attributes
static final Logger LOGGER = Logging.getLogger("org.geotoolkit.image.io.large")
static final String D00 = "00"
static final String D01 = "01"
static final String D10 = "10"
static final String D11 = "11"
Detailed Description
Create tree directory made, starting from tree root directory, define by user.
Author
Remi Marechal (Geomatys).
Constructor & Destructor Documentation
QuadTreeDirectory()
QuadTreeDirectory (final Path treeRootPath, final int nbrElementX, final int nbrElementY, final String extension, final boolean isDeleteOnExit) throws IOException
Create tree directory made, starting from tree root directory, define by user.
Parameters
treeRootPath tree root directory path.
nbrElementX global elements number in X direction.
nbrElementY global elements number in Y direction.
extension extension format of element will be stocked. May be null.
isDeleteOnExit true if user want delete all tree directory at end of JVM else false.
References QuadTreeDirectory.create4rchitecture(), QuadTreeDirectory.createDirectory(), QuadTreeDirectory.isDeleteOnExit, QuadTreeDirectory.nbrElementX, QuadTreeDirectory.nbrElementY, and QuadTreeDirectory.treeRootPath.
{
         ArgumentChecks.ensureNonNull("Quad-tree root file.", treeRootPath);
         ArgumentChecks.ensureStrictlyPositive("Quad-tree X axis dimension", nbrElementX);
         ArgumentChecks.ensureStrictlyPositive("Quad-tree Y axis dimension", nbrElementY);
         this.treeRootPath       = treeRootPath;
         this.nbrElementX        = nbrElementX;
         this.nbrElementY        = nbrElementY;
         this.extension = (extension == null) ? "" : (extension.substring(0, 1).equalsIgnoreCase(".")) ? extension : "." + extension;
         this.isDeleteOnExit = isDeleteOnExit;
         // Check if given path is valid, because if it's not, the all quad-tree is compromised.
         createDirectory(treeRootPath);
         create4rchitecture(treeRootPath, nbrElementX, nbrElementY);
         LOGGER.log(Level.FINE, "Quad-tree have been successfully initialized for path" + treeRootPath);
     }
Member Function Documentation
checkDirectory()
final void checkDirectory (final Path toCheck) throws IOException private
References QuadTreeDirectory.getExistingParent().
Referenced by QuadTreeDirectory.createDirectory().
{
         final Path path = toCheck.toAbsolutePath();
         if (Files.isRegularFile(toCheck)) {
             throw new IOException("Current path represents a file, but a directory is needed here : "+path);
         }
         if (Files.notExists(toCheck)) {
             final Path parent = getExistingParent(toCheck);
             if (parent != null && Files.isWritable(parent)) {
                 throw new IOException("Cannot create folder : "+path+", because application does not possess writing authorisation on parent folder : "+ parent.toString());
             } else {
                 throw new IOException("Cannot create folder : "+path+" for some unknown reason");
             }
         }
         if (!Files.isWritable(toCheck) || !Files.isReadable(toCheck)) {
             throw new IOException("Given directory ("+ path +") for Quad-tree does not possess sufficient rights.");
         }
     }
cleanDirectory()
void cleanDirectory () throws IOException package
Delete root directory recursively.
References IOUtilities.deleteRecursively().
Referenced by QuadTreeDirectory.finalize(), and ImageTilesCache.removeTiles().
{
         IOUtilities.deleteRecursively(treeRootPath);
     }
create4rchitecture()
void create4rchitecture (final Path path, int numXTiles, int numYTiles) throws IOException private
References QuadTreeDirectory.createDirectory().
Referenced by QuadTreeDirectory.QuadTreeDirectory().
{
         LOGGER.log(Level.FINE, "Begin creation of an entire quadTree level");
         createDirectory(path);
         if (numXTiles <= 2 && numYTiles <= 2) return;
         final int nxt = (numXTiles + 1) / 2;
         final int nyt = (numYTiles + 1) / 2;
         if (numXTiles <= 2) {
             //cut in height
             //create 2 directories
             create4rchitecture(path.resolve(D00), numXTiles, nyt); //00
             create4rchitecture(path.resolve(D01), numXTiles, numYTiles - nyt); //01
         } else if (numYTiles <= 2) {
             //cut in width
             //create 2 directories
             create4rchitecture(path.resolve(D00), nxt, numYTiles); //00
             create4rchitecture(path.resolve(D10), numXTiles - nxt, numYTiles); //10
         } else {
             //create 4 directories
             create4rchitecture(path.resolve(D00), nxt, nyt); //00
             create4rchitecture(path.resolve(D10), numXTiles-nxt, nyt); //10
             create4rchitecture(path.resolve(D01), nxt, numYTiles-nyt); //01
             create4rchitecture(path.resolve(D11), numXTiles-nxt, numYTiles-nyt); //11
             LOGGER.log(Level.FINE, "QuadTree level finely created.");
         }
     }
createDirectory()
void createDirectory (final Path path) throws IOException private
Create directory at place define by StringBuilder path.A verification is done to be sure that folder has been.
References QuadTreeDirectory.checkDirectory(), and IOUtilities.deleteOnExit().
Referenced by QuadTreeDirectory.create4rchitecture(), and QuadTreeDirectory.QuadTreeDirectory().
{
         if (Files.isRegularFile(path)) {
             throw new IOException("Current path represents a file, but a directory is needed here : "+path);
         }
         // If not exists, we try to create directory.
         if (Files.notExists(path)) {
             Files.createDirectories(path);
             if (isDeleteOnExit) {
                 IOUtilities.deleteOnExit(path);
             }
         }
         checkDirectory(path);
     }
finalize()
void finalize () throws Throwable protected
References QuadTreeDirectory.cleanDirectory().
{
         if (isDeleteOnExit) {
             cleanDirectory();
         }
         super.finalize();
     }
getExistingParent()
Path getExistingParent (Path child) private
Search a parent folder for input file, one which actually exists on the file system.
Parameters
child The file to search parent for.
Returns
the first exising parent folder of the given file, or null if we cannot find any.
Referenced by QuadTreeDirectory.checkDirectory().
{
         final Path parent = child.getParent();
         if (parent != null && Files.notExists(parent)) {
             return getExistingParent(parent);
         }
         return parent;
     }
getPath() [1/2]
String getPath (int x, int y)
Return appropriate path of element at X, Y position.
Parameters
x x direction element position.
y y direction element position.
Returns
appropriate path of element at X, Y position.
Referenced by QuadTreeDirectory.getPath(), ImageTilesCache.getRaster(), ImageTilesCache.remove(), and ImageTilesCache.writeRaster().
{
         return getPath(new StringBuilder(treeRootPath.toString()), 0, 0, nbrElementX-1, nbrElementY-1, x, y);
     }
getPath() [2/2]
String getPath (StringBuilder path, int mintx, int minty, int maxtx, int maxty, int tileX, int tileY) private
References QuadTreeDirectory.getPath(), and QuadTreeDirectory.intersect().
{
         final int dx = maxtx-mintx;
         final int dy = maxty-minty;
         if (dx <= 1 && dy <= 1) {
             path.append("/");
             path.append(tileX);
             path.append("_");
             path.append(tileY);
             path.append(extension);
             return (path.toString());
         }
         final int demx = mintx + dx / 2 + 1;
         final int demy = minty + dy / 2 + 1;
         path.append("/");
         if (dx <= 1) {
             //2 sub-directories in height.
             if (intersect(mintx, minty, maxtx, demy-1, tileX, tileY)) {
                 path.append(D00);
                 return getPath(path, mintx, minty, maxtx, demy-1, tileX, tileY);
             } else if (intersect(mintx, demy, maxtx, maxty, tileX, tileY)) {
                 path.append(D01);
                 return getPath(path, mintx, demy, maxtx, maxty, tileX, tileY);
             }
         } else if (dy <= 1) {
             //2 sub-directories in width.
             if (intersect(mintx, minty, demx-1, maxty, tileX, tileY)) {
                 path.append(D00);
                 return getPath(path, mintx, minty, demx-1, maxty, tileX, tileY);
             } else if (intersect( demx, minty, maxtx, maxty, tileX, tileY)) {
                 path.append(D10);
                 return getPath(path, demx, minty, maxtx, maxty, tileX, tileY);
             }
         } else {
             //4 cases.
             if (intersect(mintx, minty, demx-1, demy-1, tileX, tileY)) {
                 path.append(D00);
                 return getPath(path, mintx, minty, demx-1, demy-1, tileX, tileY);
             } else if (intersect(demx, minty, maxtx, demy-1, tileX, tileY)) {
                 path.append(D10);
                 return getPath(path, demx, minty, maxtx, demy-1, tileX, tileY);
             } else if (intersect(mintx, demy, demx-1, maxty, tileX, tileY)) {
                 path.append(D01);
                 return getPath(path, mintx, demy, demx-1, maxty, tileX, tileY);
             } else if (intersect(demx, demy, maxtx, maxty, tileX, tileY)) {
                 path.append(D11);
                 return getPath(path, demx, demy, maxtx, maxty, tileX, tileY);
             }
         }
         throw new IllegalStateException("Undefined path. Asked tile ("+tileX+", "+tileY+") is out of bounds.");
     }
getTreeRootPath()
Path getTreeRootPath ()
Root directory where tiles are stored.
Returns
root directory
References QuadTreeDirectory.treeRootPath.
{
         return treeRootPath;
     }
intersect()
boolean intersect (int minx, int miny, int maxx, int maxy, int tx, int ty) private
Referenced by QuadTreeDirectory.getPath().
{
         return (tx >= minx) && (tx <= maxx) && (ty >= miny) && (ty <= maxy);
     }
Member Data Documentation
D00
final String D00 = "00" static private
D01
final String D01 = "01" static private
D10
final String D10 = "10" static private
D11
final String D11 = "11" static private
extension
final String extension private
isDeleteOnExit
final boolean isDeleteOnExit private
Referenced by QuadTreeDirectory.QuadTreeDirectory().
LOGGER
final Logger LOGGER = Logging.getLogger("org.geotoolkit.image.io.large") static private
nbrElementX
final int nbrElementX private
Referenced by QuadTreeDirectory.QuadTreeDirectory().
nbrElementY
final int nbrElementY private
Referenced by QuadTreeDirectory.QuadTreeDirectory().
treeRootPath
final Path treeRootPath private
Referenced by QuadTreeDirectory.getTreeRootPath(), and QuadTreeDirectory.QuadTreeDirectory().