jena-geo: BilinearInterpolation Class Reference
BilinearInterpolation Class Reference
Define Bilinear Interpolation.
Public Member Functions
BilinearInterpolation (PixelIterator pixelIterator, ResampleBorderComportement rbc, double[] fillValue)
Create a Bilinear Interpolator.
BilinearInterpolation (PixelIterator pixelIterator)
Create a Bilinear Interpolator.
double interpolate (double x, double y, int b)
Returns interpolate value from x, y pixel coordinates and band index.
double [] interpolate (double x, double y)
Return interpolate value from x, y pixel coordinate.
double [] getMinMaxValue (Rectangle area)
int getNumBands ()
Return number of bands from object that iterate.
Static Public Member Functions
static Interpolation create (PixelIterator pixelIterator, InterpolationCase interpolationCase, int lanczosWindow)
static Interpolation create (PixelIterator pixelIterator, InterpolationCase interpolationCase, int lanczosWindow, ResampleBorderComportement rbc, double[] fillValue)
Protected Member Functions
double interpolate1D (double t0, double t, double... f)
Compute linear interpolation between 2 values.
boolean checkInterpolate (double x, double y)
Verify coordinates are within iterate area boundary.
void setInterpolateMin (double x, double y)
Return appropriate interpolation minX and minY coordinates from x, y interpolate coordinates.
Protected Attributes
final PixelIterator pixelIterator
Current.
final int numBands
Number of bands from object that iterate.
final Rectangle boundary
Boundary from object that iterate.
Rectangle precMinMax
last search of min max value area.
double [] minMax
final double [] data
Table to keep all pixels values used to interpolate.
int minX
Lower corner X coordinates from interpolation area.
int minY
Lower corner Y coordinates from interpolation area.
final int windowSide
Side of area interpolation.
final double [] result
Interpolation results table.
final double [] fillValue
Contains value use when pixel transformation is out of source image boundary.
final ResampleBorderComportement borderChoice
Define comportement of the destination image border.
final double bminX
Define boundary which accept extrapolation.
final int boundMinX
Define boundary which don't accept extrapolation.
Package Functions
Rectangle getBoundary ()
Returns.
Package Attributes
final double bminY
final double bmaxX
final double bmaxY
final int boundMinY
final int boundMaxX
final int boundMaxY
Detailed Description
Define Bilinear Interpolation.
Bilinear interpolation is computed from 4 pixels at nearest integer value.
Author
Rémi Marechal (Geomatys).
Constructor & Destructor Documentation
BilinearInterpolation() [1/2]
BilinearInterpolation (PixelIterator pixelIterator, ResampleBorderComportement rbc, double [] fillValue)
Create a Bilinear Interpolator.
Parameters
pixelIterator Iterator used to interpolation.
borderChoice define comportement of the destination image border.
fillValue contains value use when pixel transformation is out of source image boundary.
{
         super(pixelIterator, 2, rbc, fillValue);
     }
BilinearInterpolation() [2/2]
BilinearInterpolation (PixelIterator pixelIterator)
Create a Bilinear Interpolator.
Define border comportement at ResampleBorderComportement#FILL_VALUE and fillValue is an arrays of the same length than band number from source image and filled by Double#NaN value.
Parameters
pixelIterator Iterator used to interpolation.
References ResampleBorderComportement.FILL_VALUE, and Interpolation.pixelIterator.
{
         this(pixelIterator, ResampleBorderComportement.FILL_VALUE, null);
     }
Member Function Documentation
checkInterpolate()
boolean checkInterpolate (double x, double y) protected inherited
Verify coordinates are within iterate area boundary.
Parameters
x pixel x coordinate.
y pixel y coordinate.
Returns
true
if value should be interpolate at the given coordinates else
false
.
Exceptions
IllegalArgumentException if pixel coordinates are out of iterate area boundary.
References ResampleBorderComportement.EXTRAPOLATION.
Referenced by Resample.fillImageByAffineTransform(), Resample.fillImageByGrid(), Resample.fillImageByTransform(), and Resample.fillImagePx().
{
         //-- accept extrapolation
         if (borderChoice.equals(ResampleBorderComportement.EXTRAPOLATION)) return true;
         if (x < bminX || x > bmaxX || y < bminY || y > bmaxY) return false; //-- no interpolation available
 //        if (borderChoice.equals(ResampleBorderComportement.EXTRAPOLATION)) return true;
         return (!(x < boundMinX || x > boundMaxX
                || y < boundMinY || y > boundMaxY));
     }
create() [1/2]
static Interpolation create (PixelIterator pixelIterator, InterpolationCase interpolationCase, int lanczosWindow) static inherited
Return Interpolation object.
Note : if lanczos interpolation doesn't choose lanczosWindow parameter has no impact.
Parameters
pixelIterator Iterator which iterate to compute interpolation.
interpolationCase case of interpolation.
lanczosWindow only use about Lanczos interpolation.
Returns
interpolation asked by caller.
See also
LanczosInterpolation::LanczosInterpolation(org.geotoolkit.image.iterator.PixelIterator, int)
References ResampleBorderComportement.FILL_VALUE.
Referenced by Resample.Resample().
{
         return create(pixelIterator, interpolationCase, lanczosWindow, ResampleBorderComportement.FILL_VALUE, null);
     }
create() [2/2]
static Interpolation create (PixelIterator pixelIterator, InterpolationCase interpolationCase, int lanczosWindow, ResampleBorderComportement rbc, double [] fillValue) static inherited
Return Interpolation object.
Note : if lanczos interpolation doesn't choose lanczosWindow parameter has no impact.
Parameters
pixelIterator Iterator which iterate to compute interpolation.
interpolationCase case of interpolation.
lanczosWindow only use about Lanczos interpolation.
rbc comportement of the destination image border.
fillValue contains value use when pixel transformation is out of source image boundary.
Returns
interpolation asked by caller.
See also
LanczosInterpolation::LanczosInterpolation(org.geotoolkit.image.iterator.PixelIterator, int)
{
         switch (interpolationCase) {
             case NEIGHBOR : return new NeighborInterpolation(pixelIterator, fillValue);
             case BILINEAR : return new BilinearInterpolation(pixelIterator, rbc, fillValue);
             case BICUBIC  : return new BiCubicInterpolation1(pixelIterator, rbc, fillValue);
             case BICUBIC2 : return new BiCubicInterpolation2(pixelIterator, rbc, fillValue);
             case LANCZOS  : return new LanczosInterpolation(pixelIterator, lanczosWindow, rbc, fillValue);
             default       : throw  new IllegalArgumentException("interpolation not supported yet");
         }
     }
getBoundary()
Rectangle getBoundary () package inherited
Returns.
Rectangle
which is Image or Raster boundary within this Interpolator.
Returns
Rectangle
which is Image or Raster boundary within this Interpolator.
See also
Resample::getSourcePixelValue(double, double)
References Interpolation.boundary.
Referenced by Interpolation.getMinMaxValue(), Interpolation.Interpolation(), and Resample.Resample().
{
         return boundary;
     }
getMinMaxValue()
double [] getMinMaxValue (Rectangle area) inherited
Find minimum and maximum pixels values for each band.
Moreover double table result has length equal to 6 * band number.
min0 : min from band 0.
minX0 : x coordinate from min value from band 0.
minY0 : y coordinate from min value from band 0.
max0 : max from band 0.
maxX0 : x coordinate from max value from band 0.
maxY0 : y coordinate from max value from band 0.
minn : min from nth band.
minXn : x coordinate from min value from nth band.
minYn : y coordinate from min value from nth band.
maxn : max from nth band.
maxXn : x coordinate from max value from nth band.
maxYn : y coordinate from max value from nth band.
Table is organize like this :
[min0, minX0, minY0, max0, maxX0, maxY0 ... minn, minXn, minYn, maxn, maxXn, maxYn]
If Rectangle area parameter is
null
method will search minimum and maximum on all iterate object.
Note : This code is adapted for BiLinear and Neighbor interpolation. About another interpolation min and max values method isn't implemented yet.
Parameters
area area within search min and max values.
Returns
double array witch represent minimum and maximum pixels values for each band.
References Interpolation.getBoundary(), Interpolation.minMax, and Interpolation.numBands.
Referenced by Rescaler.Rescaler().
{
         if (minMax != null) {
             if ((area == null && precMinMax.equals(boundary))
               || area.equals(precMinMax)) return minMax;
         }
         //-- compute minMax values
         minMax = new double[6 * numBands];
         //-- initialize min and max value for each band
         for (int band = 0;band<numBands; band++) {
             final int minBandOrdinate = 6 * band;
             //-- min value, x, y coordinates
             minMax[minBandOrdinate]     = Double.POSITIVE_INFINITY;
             //-- max value, x, y coordinates
             minMax[minBandOrdinate + 3] = Double.NEGATIVE_INFINITY;
         }
         /*
          * If area is null iterate on all image area.
          */
         if (area == null) {
             double[] pixel = null;
             while(pixelIterator.next()) {
                 pixel = pixelIterator.getPixel(pixel);
                 for (int band = 0; band < pixel.length; band++) {
                     final int minBandOrdinate = 6 * band;
                     final Point position = pixelIterator.getPosition();
                     if (pixel[band] < minMax[minBandOrdinate]) {
                         //-- min value, x, y coordinates
                         minMax[minBandOrdinate] = pixel[band];
                         minMax[minBandOrdinate + 1] = position.x;
                         minMax[minBandOrdinate + 2] = position.y;
                     }
                     if (pixel[band] > minMax[minBandOrdinate + 3]) {
                         //-- max value, x, y coordinates
                         minMax[minBandOrdinate + 3] = pixel[band];
                         minMax[minBandOrdinate + 4] = position.x;
                         minMax[minBandOrdinate + 5] = position.y;
                     }
                 }
             }
         } else if (!getBoundary().contains(area)) {
                 throw new IllegalArgumentException("impossible to define min and max in area out of Iterate object boundary");
         } else {
             double value;
             final int maxAreaX = area.x + area.width;
             final int maxAreaY = area.y + area.height;
             for (int y = area.y; y < maxAreaY; y++) {
                 for (int x = area.x; x < maxAreaX; x++) {
                     /*
                      * Call moveTo at each pixel coordinates because we don't know Iterator implementation.
                      * Iterate row by row or raster by raster has different comportements.
                      */
                     pixelIterator.moveTo(x, y);
                     for (int band = 0; band < numBands; band++) {
                         value = pixelIterator.getSampleDouble(band);
                         final int minBandOrdinate = 6 * band;
                         if (value < minMax[minBandOrdinate]) {
                             //-- min value, x, y coordinates
                             minMax[minBandOrdinate] = value;
                             minMax[minBandOrdinate + 1] = x;
                             minMax[minBandOrdinate + 2] = y;
                         }
                         if (value > minMax[minBandOrdinate + 3]) {
                             //-- max value, x, y coordinates
                             minMax[minBandOrdinate + 3] = value;
                             minMax[minBandOrdinate + 4] = x;
                             minMax[minBandOrdinate + 5] = y;
                         }
                     }
                 }
             }
         }
         precMinMax = (area == null) ? boundary : area;
         return minMax;
     }
getNumBands()
int getNumBands () inherited
Return number of bands from object that iterate.
Returns
number of bands from object that iterate.
See also
Resample::getSourcePixelValue(double, double)
References Interpolation.numBands.
Referenced by SeparableInterpolation.interpolate(), Interpolation.Interpolation(), and Resample.Resample().
{
         return numBands;
     }
interpolate() [1/2]
double interpolate (double x, double y, int b) inherited
Returns interpolate value from x, y pixel coordinates and band index.
Parameters
x pixel x coordinate.
y pixel y coordinate.
b band index.
Returns
interpolate value from x, y pixel coordinates and band index.
References SeparableInterpolation.fillRow(), Interpolation.getNumBands(), SeparableInterpolation.interpolate1D(), Interpolation.minX, Interpolation.minY, Interpolation.setInterpolateMin(), and Interpolation.windowSide.
{
         ArgumentChecks.ensureBetween("band index", 0, getNumBands(), b);
         setInterpolateMin(x, y);
         for (int dy = 0; dy < windowSide; dy++) {
             fillRow(dy, b);
             cols[dy] = interpolate1D(minX, x, rows);
         }
         return interpolate1D(minY, y, cols);
     }
interpolate() [2/2]
double [] interpolate (double x, double y) inherited
Return interpolate value from x, y pixel coordinate.
Parameters
x pixel x coordinate.
y pixel y coordinate.
Returns
interpolate value from x, y pixel coordinate.
References SeparableInterpolation.fillRow(), SeparableInterpolation.interpolate1D(), Interpolation.minX, Interpolation.minY, Interpolation.numBands, Interpolation.result, Interpolation.setInterpolateMin(), and Interpolation.windowSide.
{
 //        if (!checkInterpolate(x, y)) return fillValue;
         setInterpolateMin(x, y);
         for (int b = 0; b < numBands; b++) {
             for (int dy = 0; dy < windowSide; dy++) {
                 fillRow(dy, b);
                 cols[dy] = interpolate1D(minX, x, rows);
             }
             result[b] = interpolate1D(minY, y, cols);
         }
         return result;
     }
interpolate1D()
double interpolate1D (double t0, double t, double... f) protected
Compute linear interpolation between 2 values.
{
         assert (f.length == 2) : " bilinear interpolation table not conform";
         return (t-t0)*(f[1]-f[0]) + f[0];
     }
setInterpolateMin()
void setInterpolateMin (double x, double y) protected inherited
Return appropriate interpolation minX and minY coordinates from x, y interpolate coordinates.
MinX and minY represent lower corner coordinates from interpolation area.
Parameters
x pixel x coordinate.
y pixel y coordinate.
Exceptions
IllegalArgumentException if there are necessary pixels out of boundary.
Referenced by SeparableInterpolation.interpolate(), and LanczosInterpolation.interpolate().
{
         final int boundW = boundary.width;
         final int boundH = boundary.height;
         final int bx     = boundary.x;
         final int by     = boundary.y;
         minX  = (int) x;
         minY  = (int) y;
         //-- Adjust truncation.
         if (x < minX) minX--;
         if (y < minY) minY--;
         //-- Adjust area interpolation on x, y center.
         minX -= (windowSide >>> 1) - 1;
         minY -= (windowSide >>> 1) - 1;
         //-- Adjust area from lower corner.
         minX = Math.max(minX, bx);
         minY = Math.max(minY, by);
         //-- Adjust area from upper corner.
         final int maxDiffX = minX + windowSide - (bx + boundW);
         final int maxDiffY = minY + windowSide - (by + boundH);
         if (maxDiffX > 0) minX -= maxDiffX;
         if (maxDiffY > 0) minY -= maxDiffY;
     }
Member Data Documentation
bmaxX
final double bmaxX package inherited
Referenced by NeighborInterpolation.checkInterpolate().
bmaxY
final double bmaxY package inherited
Referenced by NeighborInterpolation.checkInterpolate().
bminX
final double bminX protected inherited
Define boundary which accept extrapolation.
bminY
final double bminY package inherited
borderChoice
final ResampleBorderComportement borderChoice protected inherited
Define comportement of the destination image border.
Referenced by Interpolation.Interpolation().
boundary
final Rectangle boundary protected inherited
Boundary from object that iterate.
Referenced by BiCubicInterpolation.BiCubicInterpolation(), Interpolation.getBoundary(), and LanczosInterpolation.LanczosInterpolation().
boundMaxX
final int boundMaxX package inherited
boundMaxY
final int boundMaxY package inherited
boundMinX
final int boundMinX protected inherited
Define boundary which don't accept extrapolation.
boundMinY
final int boundMinY package inherited
data
final double [] data protected inherited
Table to keep all pixels values used to interpolate.
fillValue
final double [] fillValue protected inherited
Contains value use when pixel transformation is out of source image boundary.
Referenced by Interpolation.Interpolation().
minMax
double [] minMax protected inherited
Double table which contain minimum and maximum value, and x, y associate coordinates for each image band.
Referenced by Interpolation.getMinMaxValue(), Interpolation.Interpolation(), and Rescaler.Rescaler().
minX
int minX protected inherited
Lower corner X coordinates from interpolation area.
Referenced by SeparableInterpolation.fillRow(), SeparableInterpolation.interpolate(), and LanczosInterpolation.interpolate().
minY
int minY protected inherited
Lower corner Y coordinates from interpolation area.
Referenced by SeparableInterpolation.fillRow(), SeparableInterpolation.interpolate(), and LanczosInterpolation.interpolate().
numBands
final int numBands protected inherited
Number of bands from object that iterate.
Referenced by Interpolation.getMinMaxValue(), Interpolation.getNumBands(), SeparableInterpolation.interpolate(), Interpolation.Interpolation(), and Rescaler.Rescaler().
pixelIterator
final PixelIterator pixelIterator protected inherited
Current.
PixelIterator
which is interpolate.
Referenced by BiCubicInterpolation.BiCubicInterpolation(), BilinearInterpolation.BilinearInterpolation(), SeparableInterpolation.fillRow(), NeighborInterpolation.interpolate(), LanczosInterpolation.interpolate(), Interpolation.Interpolation(), and LanczosInterpolation.LanczosInterpolation().
precMinMax
Rectangle precMinMax protected inherited
last search of min max value area.
result
final double [] result protected inherited
Interpolation results table.
Referenced by NeighborInterpolation.interpolate(), and SeparableInterpolation.interpolate().
windowSide
final int windowSide protected inherited
Side of area interpolation.
Referenced by SeparableInterpolation.fillRow(), SeparableInterpolation.interpolate(), LanczosInterpolation.interpolate(), Interpolation.Interpolation(), and SeparableInterpolation.SeparableInterpolation().