jena-geo: SampleValues Class Reference
SampleValues Class Reference abstract
A sample value suitable for use in a java.util.HashSet.
Classes
class Double
Implementation backed by.
class Float
Implementation backed by.
class Integer
Implementation backed by.
Public Member Functions
abstract double getSample (int band)
Get band sample value.
abstract SampleValues instance ()
Returns a new instance of the same type than this.
abstract SampleValues getPixel (final Raster source, final int x, final int y)
Gets the pixel from the given raster and stores the values in this object.
abstract void setPixel (final WritableRaster dest, final int x, final int y)
Sets the pixel of the given raster to the values in this object.
Static Public Member Functions
static SampleValues getInstance (final int transferType, final int numBands)
Returns a new instance for the given number of bands.
static SampleValues getInstance (final int transferType, final double[] values)
Returns a new instance for the given type wrapping the given sample values.
static int [] copyAsInts (final double[] data)
Returns a copy of the given array where each value has been Math::round(double) rounded} to the.
Package Functions
SampleValues ()
Creates a.
Detailed Description
A sample value suitable for use in a java.util.HashSet.
Author
Martin Desruisseaux (Geomatys)
Version
3.01
Since
3.01
Constructor & Destructor Documentation
SampleValues()
SampleValues () package
Creates a.
SampleValues
.
                    {
     }
Member Function Documentation
copyAsInts()
static int [] copyAsInts (final double [] data) static
Returns a copy of the given array where each value has been Math::round(double) rounded} to the.
int
type.
Parameters
data the array to copy, or
null
.
Returns
a copy of the given array with values rounded to the
int
type, or
null
if the given array was null.
Referenced by Mask.computeRect(), and SampleValues.Integer.Integer().
{
         if (data == null) return null;
         final int[] result = new int[data.length];
         for (int i=0; i<data.length; i++) {
             result[i] = Math.toIntExact(Math.round(data[i]));
         }
         return result;
     }
getInstance() [1/2]
static SampleValues getInstance (final int transferType, final int numBands) static
Returns a new instance for the given number of bands.
The transfer type must be one of the DataBuffer constants.
Referenced by SilhouetteMask.computeImage(), and FloodFill.fill().
{
         switch (transferType) {
             case DataBuffer.TYPE_DOUBLE: return new Double (numBands);
             case DataBuffer.TYPE_FLOAT:  return new Float  (numBands);
             default:                     return new Integer(numBands);
         }
     }
getInstance() [2/2]
static SampleValues getInstance (final int transferType, final double [] values) static
Returns a new instance for the given type wrapping the given sample values.
The transfer type must be one of the DataBuffer constants.
References SampleValues.getPixel(), SampleValues.getSample(), SampleValues.instance(), and SampleValues.setPixel().
{
         switch (transferType) {
             case DataBuffer.TYPE_DOUBLE: return new Double (values);
             case DataBuffer.TYPE_FLOAT:  return new Float  (values);
             default:                     return new Integer(values);
         }
     }
getPixel()
abstract SampleValues getPixel (final Raster source, final int x, final int y) abstract
Gets the pixel from the given raster and stores the values in this object.
Parameters
source The raster from which to get the pixel value.
x The x pixel ordinate.
y The y pixel ordinate.
Returns
Always
this
.
Referenced by SilhouetteMask.computeImage(), FloodFill.fill(), SampleValues.getInstance(), SampleValues.Double.getPixel(), SampleValues.Float.getPixel(), and SampleValues.Integer.getPixel().
getSample()
abstract double getSample (int band) abstract
Get band sample value.
Parameters
band band index
Returns
band value at index
Referenced by SampleValues.getInstance().
instance()
abstract SampleValues instance () abstract
Returns a new instance of the same type than this.
SampleValues
object. This new instance is initialized to zero sample values.
Referenced by FloodFill.fill(), and SampleValues.getInstance().
setPixel()
abstract void setPixel (final WritableRaster dest, final int x, final int y) abstract
Sets the pixel of the given raster to the values in this object.
Parameters
dest The raster in which to set the pixel value.
x The x pixel ordinate.
y The y pixel ordinate.
Referenced by SilhouetteMask.computeImage(), FloodFill.fill(), and SampleValues.getInstance().