jena-geo: GridFactory Class Reference
GridFactory Class Reference
Creates image ResampleGrid objects for the given MathTransform2D.
Public Member Functions
GridFactory (final double tolerance)
Creates a new factory.
Object create (final MathTransform2D transform, final Rectangle domain) throws TransformException
Implementation of the public create(CharSequence name, MathTransform2D, Rectangle) method, invoked only if the Warp object was not found in the cache.
Static Private Member Functions
static double roundIfAlmostInteger (final double value)
Work around for rounding error.
static Dimension depth (final MathTransform2D transform, final Point2D.Double point, final DoubleDimension2D tolerance, final double xmin, final double xmax, final double ymin, final double ymax, final Matrix2 upperLeft, final Matrix2 upperRight, final Matrix2 lowerLeft, final Matrix2 lowerRight) throws TransformException, ArithmeticException
Computes the number of subdivisions (in power of 2) to apply in order to get a good.
static void incrementNonAffineDimension (boolean he, boolean ve, Dimension depth)
Increments the width, the height or both values in the given dimension, depending on which dimension are not affine.
static Matrix2 derivative (final MathTransform2D transform, final Point2D point) throws TransformException
Computes the derivative of the given transform at the given location, and returns the result as a 2×2 matrix.
static boolean equals (final Matrix2 center, final Matrix2 corner, final DoubleDimension2D tolerance)
Returns.
Private Attributes
final double tolerance
The maximal error allowed, in units of destination CRS (usually pixels).
Static Private Attributes
static final int MIN_SIZE = 4
The minimal size, in pixels.
static final double EPS = 1.1920929E-7
A small tolerance factor for comparisons of floating point numbers.
Detailed Description
Creates image ResampleGrid objects for the given MathTransform2D.
The generated grid contain transformed coordinated from <cite>target</cite> to <cite>source</cite> CRS. (i.e. the image grid shall transform coordinates from target to source CRS). Consequently, consider invoking
transform.inverse()
if the grid object is going to be used in an image reprojection.
{
pixels corner or center}
The semantic of <cite>Java Advanced Imaging</cite>
Resample
operation is to apply the transforms as below:
Offset all input coordinates by 0.5 in order to get the coordinates of pixel centers.
Apply the transform.
Offset all output coordinates by -0.5 in order to compensate for the input offset.
This semantic implies that the GridGeometry::getGridToCRS() grid to CRS} transforms were computed using PixelOrientation#UPPER_LEFT, as in Java2D usage.
Author
Martin Desruisseaux (Geomatys).
Remi Marechal (Geomatys).
Constructor & Destructor Documentation
GridFactory()
GridFactory (final double tolerance)
Creates a new factory.
Parameters
tolerance The maximal error allowed, in units of destination CRS (usually pixels). This is the maximal difference allowed between a coordinate transformed using the original transform, and the same coordinate transformed using the warp created by this factory.
References GridFactory.tolerance.
{
         ensurePositive("tolerance", tolerance);
         this.tolerance = tolerance;
     }
Member Function Documentation
create()
Object create (final MathTransform2D transform, final Rectangle domain) throws TransformException
Implementation of the public create(CharSequence name, MathTransform2D, Rectangle) method, invoked only if the Warp object was not found in the cache.
References GridFactory.depth(), GridFactory.derivative(), GridFactory.roundIfAlmostInteger(), XAffineTransform.roundIfAlmostInteger(), and GridFactory.tolerance.
Referenced by Resample.fillImage().
     {
         final double xmin = domain.getMinX();
         final double xmax = domain.getMaxX();
         final double ymin = domain.getMinY();
         final double ymax = domain.getMaxY();
         final Point2D.Double point = new Point2D.Double(); // Multi-purpose buffer.
         final Matrix2 upperLeft, upperRight, lowerLeft, lowerRight;
         try {
             point.x = xmin; point.y = ymax; upperLeft  = derivative(transform, point);
             point.x = xmax; point.y = ymax; upperRight = derivative(transform, point);
             point.x = xmin; point.y = ymin; lowerLeft  = derivative(transform, point);
             point.x = xmax; point.y = ymin; lowerRight = derivative(transform, point);
         } catch (TransformException e) {
             /*
              * Typically happen when the transform does not support the derivative function,
              * in which case we will fallback on the generic (but slow) adapter.
              */
             Logging.recoverableException(null, GridFactory.class, "create", e);
             throw new TransformException("grid creation : derivative function not supported by current Mathtransform", e);
         }
         /*
          * The tolerance factor is scaled as below. The explanation below is for
          * a one-dimensional case, but the two dimensional case works on the same
          * principle.
          *
          * Let assume that we computed the derivative of y=f(x) at two locations: x₁ and x₃.
          * The derivative values (the slopes of the y=f(x) function) at those locations are
          * m₁ and m₃.
          *
          *          /          _/
          *         / x₁      _/ x₂      ─── x₃
          *        / m₁=1    /  m₂≈½        m₃=0
          *
          * WarpGrid will interpolate the y values between x₁ and x₃. The interpolated results
          * should be exact at locations x₁ and x₃ and have some errors between those two end
          * points.
          *
          * HYPOTHESIS:
          *  1) We presume that the greatest error will be located mid-way between x₁ and x₃.
          *     The x₂ point above represents that location.
          *  2) We presume that the derivative between x₁ and x₃ varies continuously from m₁ to m₃.
          *     The derivative at x₂ may be something close to m₂ ≈ (m₁ + m₃) / 2, but we don't
          *     actually known.
          *
          * Let compute linear approximations of y=f(x) using the two slopes m₁ and m₃. If
          * the hypothesis #2 is true, then the real y values are somewhere between the two
          * approximations. The formulas below use the x₁ point, but we would get the same
          * final equation if we used the x₃ instead (we don't use both x₁ and x₃ since
          * solving such equation produce 0=0).
          *
          * Given f₁(x) = y₁ + (x - x₁)*m₁
          *   and f₃(x) = y₁ + (x - x₁)*m₃
          *
          * then the error ε = f₃(x) - f₁(x) at location x=x₂ is (x₂-x₁) * (m₃-m₁).
          * Given x₂ = (x₁+x₃)/2, we get ε = (x₃-x₁)/2 * (m₃-m₁).
          *
          * If we rearange the terms, we get:  (m₃-m₁) = 2*ε / (x₃-x₁).
          * The (m₃ - m₁) value is the maximal difference to be accepted
          * in the coefficients of the derivative matrix to be compared.
          */
         final Dimension depth;
         try {
             final double tol = 2 * tolerance;
             depth = depth(transform, point,
                     new DoubleDimension2D(tol / (xmax - xmin), tol / (ymax - ymin)),
                     xmin, xmax, ymin, ymax, upperLeft, upperRight, lowerLeft, lowerRight);
         } catch (ArithmeticException e) {
             /*
              * The method does not converge.
              */
             Logging.recoverableException(null, GridFactory.class, "create", e);
             throw new ArithmeticException("grid creation : current mathtransform does not converge.");
         }
         if (depth.width == 0 && depth.height == 0) {
             /*
              * The transform is approximatively affine. Compute the matrix coefficients using
              * the points projected on the four borders of the domain, in order to get a kind
              * of average coefficient values. We don't use the derivative matrix in the center
              * location, because it may not be the best "average" value and some map projection
              * implementations use approximation derived from spherical formulas. The difference
              * is big enough for causing test failure.
              */
             final double xcnt = domain.getCenterX();
             final double ycnt = domain.getCenterY();
             double m00, m10, m01, m11;
             Point2D p;
             // TODO: we must check for the cases where xmin > xmax after transformation,
             //       and handle that as an Envelope the cross the anti-meridian.
             point.x=xmax; point.y=ycnt; p=transform.transform(point, point); m00  = p.getX(); m10  = p.getY();
             point.x=xmin; point.y=ycnt; p=transform.transform(point, point); m00 -= p.getX(); m10 -= p.getY();
             point.x=xcnt; point.y=ymax; p=transform.transform(point, point); m01  = p.getX(); m11  = p.getY();
             point.x=xcnt; point.y=ymin; p=transform.transform(point, point); m01 -= p.getX(); m11 -= p.getY();
             point.x=xcnt; point.y=ycnt; p=transform.transform(point, point);
             final double width  = domain.getWidth();
             final double height = domain.getHeight();
             final AffineTransform tr = new AffineTransform(
                     roundIfAlmostInteger(m00 / width),  roundIfAlmostInteger(m10 / width),
                     roundIfAlmostInteger(m01 / height), roundIfAlmostInteger(m11 / height),
                     roundIfAlmostInteger(p.getX()),     roundIfAlmostInteger(p.getY()));
             /*
              * Note: we rounded the scale and shear factors because they will impact
              * the translation computation below (we may get a number like 1E-13 when
              * the expected value is zero).
              */
             tr.translate(-xcnt, -ycnt);
             XAffineTransform.roundIfAlmostInteger(tr, EPS);
             return tr;
         }
         /*
          * Non-affine transform. Create a grid using the cell size computed (indirectly)
          * by the 'depth' method.
          */
         final int xStep     =  domain.width  / (1 << depth.width);
         final int yStep     =  domain.height / (1 << depth.height);
         /*
          * Grid width equals xNumCells + 1.
          * xNumCells is the number of sub-division on x axis.
          */
         final int xNumCells = (domain.width  + xStep-1) / xStep;
         /*
          * Grid height equals yNumCells + 1.
          * xNumCells is the number of sub-division on y axis.
          */
         final int yNumCells = (domain.height + yStep-1) / yStep;
         final double[] warpPositions = new double[((xNumCells+1) * (yNumCells+1)) << 1];
         final int xup = domain.x + xNumCells * xStep;
         final int yup = domain.y + yNumCells * yStep;
         int p = 0;
         for (int y=domain.y; y <= yup; y += yStep) {
             for (int x=domain.x; x <= xup; x += xStep) {
                 warpPositions[p++] = x;
                 warpPositions[p++] = y;
             }
         }
         /*
          * Note: The 0.5 offset is handled by precedently mathtransform concatenation
          * effectuate by user at resample implementation, so we don't need to apply it ourself in 'gridPositions'.
          */
         transform.transform(warpPositions, 0, warpPositions, 0, p/2);
         return new ResampleGrid(domain.x,domain.y, xStep, yStep, xNumCells + 1, yNumCells + 1, warpPositions);
     }
depth()
static Dimension depth (final MathTransform2D transform, final Point2D.Double point, final DoubleDimension2D tolerance, final double xmin, final double xmax, final double ymin, final double ymax, final Matrix2 upperLeft, final Matrix2 upperRight, final Matrix2 lowerLeft, final Matrix2 lowerRight) throws TransformException, ArithmeticException static private
Computes the number of subdivisions (in power of 2) to apply in order to get a good.
WarpGrid
approximation. The
width
and
height
fields in the returned value have the following meaning:
0 means that the transform is approximatively affine in the region of interest.
1 means that we should split the grid in two parts horizontally and/or vertically.
2 means that we should split the grid in four parts horizontally and/or vertically.
etc.
Parameters
transform The transform for which to compute the depth.
point Any
Point2D.Double
instance, to be overwritten by this method. This is provided in argument only to reduce the amount of object allocations.
tolerance The tolerance value to use in comparisons of matrix coefficients, along the X axis and along the Y axis. The distance between the location of the matrix being compared is half the size of the region of interest.
xmin The minimal x ordinate.
xmax The maximal x ordinate.
ymin The minimal y ordinate.
ymax The maximal y ordinate.
upperLeft The transform derivative at
(xmin,ymax)
.
upperRight The transform derivative at
(xmax,ymax)
.
lowerLeft The transform derivative at
(xmin,ymin)
.
lowerRight The transform derivative at
(xmax,ymin)
.
Returns
The number of subdivision along each axes.
Exceptions
TransformException If a derivative can not be computed.
ArithmeticException If this method does not converge.
References GridFactory.derivative(), GridFactory.equals(), Errors.format(), GridFactory.incrementNonAffineDimension(), and Errors.Keys.NoConvergence.
Referenced by GridFactory.create().
     {
         if (!(xmax - xmin >= MIN_SIZE) || !(ymax - ymin >= MIN_SIZE)) { // Use ! for catching NaN.
             throw new ArithmeticException(Errors.format(Errors.Keys.NoConvergence));
         }
         /*
          * All derivatives will be compared to the derivative at (centerX, centerY).
          * Consequently, the distance between the derivatives are half the distance
          * between [x|y]min and [x|y]max (approximatively - we ignore the diagonal).
          * Consequently, the tolerance threshold can be augmented by the same factor.
          */
         final double oldTolX = tolerance.width;
         final double oldTolY = tolerance.height;
         tolerance.width  *= 2;
         tolerance.height *= 2;
         final double centerX = point.x = 0.5 * (xmin + xmax);
         final double centerY = point.y = 0.5 * (ymin + ymax);
         final Matrix2 center = derivative(transform, point);
         point.x = xmin;    point.y = centerY; final Matrix2 centerLeft  = derivative(transform, point);
         point.x = xmax;    point.y = centerY; final Matrix2 centerRight = derivative(transform, point);
         point.x = centerX; point.y = ymin;    final Matrix2 centerLower = derivative(transform, point);
         point.x = centerX; point.y = ymax;    final Matrix2 centerUpper = derivative(transform, point);
         final boolean cl = equals(center, centerLeft,  tolerance);
         final boolean cr = equals(center, centerRight, tolerance);
         final boolean cb = equals(center, centerLower, tolerance);
         final boolean cu = equals(center, centerUpper, tolerance);
         int nx=0, ny=0;
         /*
          *   upperLeft  ┌──────┬─ centerUpper
          *              │      │
          *   centerLeft ├──────┼─ center
          */
         if (!cl || !cu || !equals(center, upperLeft, tolerance)) {
             final Dimension depth = depth(transform, point, tolerance,
                     xmin, centerX, centerY, ymax,
                     upperLeft, centerUpper, centerLeft, center);
             incrementNonAffineDimension(cl, cu, depth);
             nx = depth.width;
             ny = depth.height;
         }
         /*
          *   centerUpper ─┬──────┐ upperRight
          *                │      │
          *   center      ─┼──────┤ centerRight
          */
         if (!cr || !cu || !equals(center, upperRight, tolerance)) {
             final Dimension depth = depth(transform, point, tolerance,
                     centerX, xmax, centerY, ymax,
                     centerUpper, upperRight, center, centerRight);
             incrementNonAffineDimension(cr, cu, depth);
             nx = Math.max(nx, depth.width);
             ny = Math.max(ny, depth.height);
         }
         /*
          *   centerLeft ├──────┼─ center
          *              │      │
          *   lowerLeft  └──────┴─ centerLower
          */
         if (!cl || !cb || !equals(center, lowerLeft, tolerance)) {
             final Dimension depth = depth(transform, point, tolerance,
                     xmin, centerX, ymin, centerY,
                     centerLeft, center, lowerLeft, centerLower);
             incrementNonAffineDimension(cl, cb, depth);
             nx = Math.max(nx, depth.width);
             ny = Math.max(ny, depth.height);
         }
         /*
          *   center      ─┼──────┤ centerRight
          *                │      │
          *   centerLower ─┴──────┘ lowerRight
          */
         if (!cr || !cb || !equals(center, lowerRight, tolerance)) {
             final Dimension depth = depth(transform, point, tolerance,
                     centerX, xmax, ymin, centerY,
                     center, centerRight, centerLower, lowerRight);
             incrementNonAffineDimension(cr, cb, depth);
             nx = Math.max(nx, depth.width);
             ny = Math.max(ny, depth.height);
         }
         tolerance.width  = oldTolX;
         tolerance.height = oldTolY;
         return new Dimension(nx, ny);
     }
derivative()
static Matrix2 derivative (final MathTransform2D transform, final Point2D point) throws TransformException static private
Computes the derivative of the given transform at the given location, and returns the result as a 2×2 matrix.
This method invokes the MathTransform2D#derivative(Point2D) and convert or cast the result to a Matrix2 instance.
In the Geotk implementation, the matrix returned by the
derivative(Point2D)
methods are already instances of Matrix2. Consequently in most cases this method will just cast the result.
Parameters
transform The transform for which to compute the derivative.
point The location where to compute the derivative.
Returns
The derivative at the given location as a 2×2 matrix.
Exceptions
TransformException If the derivative can not be computed.
Referenced by GridFactory.create(), and GridFactory.depth().
     {
         final Matrix matrix = transform.derivative(point);
         return (matrix instanceof Matrix2) ? (Matrix2) matrix : new Matrix2(
                 matrix.getElement(0,0), matrix.getElement(0,1),
                 matrix.getElement(1,0), matrix.getElement(1,1));
     }
equals()
static boolean equals (final Matrix2 center, final Matrix2 corner, final DoubleDimension2D tolerance) static private
Returns.
true
if the given matrix are equals, up to the given tolerance threshold. The threshold can be different for the X and Y axis. This allows the condition to break the loop sooner (resulting in smaller grids) inside the
depth
method.
References DoubleDimension2D.height, and DoubleDimension2D.width.
Referenced by GridFactory.depth().
{
         return Math.abs(center.m00 - corner.m00) <= tolerance.width  &&
                Math.abs(center.m01 - corner.m01) <= tolerance.width  &&
                Math.abs(center.m10 - corner.m10) <= tolerance.height &&
                Math.abs(center.m11 - corner.m11) <= tolerance.height;
     }
incrementNonAffineDimension()
static void incrementNonAffineDimension (boolean he, boolean ve, Dimension depth) static private
Increments the width, the height or both values in the given dimension, depending on which dimension are not affine.
This method most be invoked using the following pattern, where
center
is the matrix of the transform derivative in the center of the region of interest. Note: the order of operations in the
if
statement matter!
java
   he = center.equals(matrixOnTheSameHorizontalLine,  tolerance);
   ve = center.equals(matrixOnTheSameVerticalLine,    tolerance);
   if (!he || !ve || center.equals(matrixOnADiagonal, tolerance)) {
       incrementNonAffineDimension(he, ve, depth);
   }
Parameters
he
Referenced by GridFactory.depth().
{
         if (he == ve) {
             // Both dimensions are not affine: either (he, ve)==false (the obvious case),
             // or (he,ve) == true in which case this method have been invoked only if the
             // last center.equals(...) test in the 'if' statement returned false.
             depth.width++;
             depth.height++;
         } else if (ve) {
             // Implies (he == false): horizontal dimension is not affine.
             // Don't touch to the vertical dimension since it is affine.
             depth.width++;
         } else {
             // Implies (he == true): horizontal dimension is affine, don't touch it.
             depth.height++;
         }
     }
roundIfAlmostInteger()
static double roundIfAlmostInteger (final double value) static private
Work around for rounding error.
The tolerance threshold is arbitrary. This method is mostly for catching the cases were we expected an identity transform from the source grid to the target grid (for example the x axis in a Mercator projection).
References GridFactory.EPS.
Referenced by GridFactory.create().
{
         final double rounded = Math.round(value);
         if (rounded != 0 && Math.abs(rounded - value) <= EPS) {
             return rounded;
         }
         return value;
     }
Member Data Documentation
EPS
final double EPS = 1.1920929E-7 static private
A small tolerance factor for comparisons of floating point numbers.
We use the smallest accuracy possible for the
float
type for integer numbers different than zero, as computed by:
{ java Math.nextUp(1f) - 1f; }
Since WarpAffine will convert the
double
coefficients to
float
, a tolerance factor not greater than this value should avoid the lost of information. We still use it in order to fix the coefficients that are close to zero, especially shear factors. (e.g. 1E-13 for a shear factor that was expected to be zero).
Referenced by GridFactory.roundIfAlmostInteger().
MIN_SIZE
final int MIN_SIZE = 4 static private
The minimal size, in pixels.
If the cell size is lower than this threshold, we will abandon the attempt to create a ResampleGrid.
tolerance
final double tolerance private
The maximal error allowed, in units of destination CRS (usually pixels).
This is the maximal difference allowed between a coordinate transformed using the original transform, and the same coordinate transformed using the warp.
Referenced by GridFactory.create(), and GridFactory.GridFactory().