jena-geo: Resample Class Reference
Resample Class Reference
Fill target image from source image pixels interpolation at coordinate define by transformation of target pixel coordinate by.
Public Member Functions
Resample (MathTransform mathTransform, WritableRenderedImage imageDest, Interpolation interpol, double[] fillValue) throws NoninvertibleTransformException, TransformException
Resample (MathTransform mathTransform, WritableRenderedImage imageDest, Rectangle resampleArea, Interpolation interpol, double[] fillValue) throws NoninvertibleTransformException, TransformException
Resample (MathTransform mathTransform, WritableRenderedImage imageDest, RenderedImage imageSrc, InterpolationCase interpolation) throws TransformException
Resample (MathTransform mathTransform, WritableRenderedImage imageDest, RenderedImage imageSrc, InterpolationCase interpolation, ResampleBorderComportement rbc, double[] fillValue) throws TransformException
Resample (MathTransform mathTransform, WritableRenderedImage imageDest, RenderedImage imageSrc, InterpolationCase interpolation, int lanczosWindow, ResampleBorderComportement rbc, double[] fillValue) throws TransformException
Resample (MathTransform mathTransform, WritableRenderedImage imageDest, Rectangle resampleArea, RenderedImage imageSrc, InterpolationCase interpolation, int lanczosWindow, ResampleBorderComportement rbc, double[] fillValue) throws TransformException
Resample (MathTransform mathTransform, WritableRenderedImage imageDest, Rectangle resampleArea, Interpolation interpol, double[] fillValue, ResampleBorderComportement rbc) throws NoninvertibleTransformException, TransformException
void fillImage () throws TransformException
Fill destination image from source image pixel interpolation.
void fillImage (boolean canUseGrid) throws TransformException
void fillImagePx () throws TransformException
Please use fillImageByTransform() method.
Interpolation getInterpol ()
Returns Interpolation object use to resample.
Protected Attributes
final double [] clamp
Minimum and maximum values authorized for pixels.
Package Functions
ResampleGrid getGrid ()
Returns the needed grid use to resample if exist or.
Package Attributes
final WritablePixelIterator destIterator
Iterator use to fill destination image from interpolation of source image pixel value.
ResampleBorderComportement rbc
On the border of the destination image, projection of destination border pixel coordinates should be out of source image boundary.
ResampleGrid theGrid
Grid use to resample image if exist.
Private Member Functions
void fillImageByGrid () throws TransformException
Fill destination image from pre-computed grid.
void fillImageByAffineTransform (AffineTransform destCoordToSource) throws TransformException
Fill image without any grid, all pixels coordinates are transform by given MathTransform.
void fillImageByTransform () throws TransformException
Fill image without any grid, all pixels coordinates are transform by given MathTransform.
Static Private Member Functions
static double [] getClamp (int dataType)
Private Attributes
MathTransform destToSourceMathTransform
Transform multi-dimensional point (in our case pixel coordinate) from target image.
final WritableRenderedImage imageDest
Image in which image source pixel interpolation result is push.
final Interpolation interpol
Sort of interpolation use to interpolate image source pixels.
final int numBands
Image number bands.
final double [] srcCoords
Table which contain x, y coordinates after MathTransform transformation.
final double [] destCoords
Table which contain x, y coordinates after MathTransform transformation.
double [] fillValue
Contains value use when destination pixel coordinates transformation are out of source image boundary.
Static Private Attributes
static final double [] CLAMP_BYTE = new double[]{0, 255}
static final double [] CLAMP_SHORT = new double[]{Short.MIN_VALUE, Short.MAX_VALUE}
static final double [] CLAMP_USHORT = new double[]{0, 0xFFFF}
static final double [] CLAMP_INT = new double[]{Integer.MIN_VALUE, Integer.MAX_VALUE}
Detailed Description
Fill target image from source image pixels interpolation at coordinate define by transformation of target pixel coordinate by.
MathTransform
.
Author
Rémi Marechal (Geomatys).
Martin Desruisseaux (Geomatys).
Constructor & Destructor Documentation
Resample() [1/7]
Resample (MathTransform mathTransform, WritableRenderedImage imageDest, Interpolation interpol, double [] fillValue) throws NoninvertibleTransformException, TransformException
Fill destination image from interpolation of source pixels.
Source pixel coordinate is obtained from invert transformation of destination pixel coordinates.
The default border comportement is ResampleBorderComportement#EXTRAPOLATION.
Moreover : the specified MathTransform should be from CENTER of target image point to CENTER of source image point.
The used MathTransform is consider with PixelInCell#CELL_CENTER configuration.
Parameters
mathTransform Transformation use to transform target point to source point.
imageDest image will be fill by image source pixel interpolation.
interpol Interpolation use to interpolate source image pixels.
fillValue contains value use when pixel transformation is out of source image boundary.
Exceptions
NoninvertibleTransformException if it is impossible to invert
MathTransform
parameter.
References Resample.fillValue, Resample.imageDest, and Resample.interpol.
{
         this(mathTransform, imageDest, null, interpol, fillValue);
     }
Resample() [2/7]
Resample (MathTransform mathTransform, WritableRenderedImage imageDest, Rectangle resampleArea, Interpolation interpol, double [] fillValue) throws NoninvertibleTransformException, TransformException
Fill destination image area from interpolation of source pixels.
Source pixel coordinate is obtained from invert transformation of destination pixel coordinates.
The default border comportement is ResampleBorderComportement#EXTRAPOLATION.
Moreover : the specified MathTransform should be from CENTER of target image point to CENTER of source image point.
The used MathTransform is consider with PixelInCell#CELL_CENTER configuration.
Parameters
mathTransform Transformation use to transform target point to source point.
imageDest image will be fill by image source pixel interpolation.
resampleArea destination image area within pixels are resample.
interpol Interpolation use to interpolate source image pixels.
fillValue contains value use when pixel transformation is out of source image boundary.
Exceptions
NoninvertibleTransformException if it is impossible to invert
MathTransform
parameter.
References ResampleBorderComportement.EXTRAPOLATION, Resample.fillValue, Resample.imageDest, and Resample.interpol.
{
         this(mathTransform, imageDest, resampleArea, interpol, fillValue, ResampleBorderComportement.EXTRAPOLATION);
     }
Resample() [3/7]
Resample (MathTransform mathTransform, WritableRenderedImage imageDest, RenderedImage imageSrc, InterpolationCase interpolation) throws TransformException
Fill destination image area from interpolation of source pixels from imageSrc.
Source pixel coordinates is obtained from invert transformation of destination pixel coordinates.
In case where interpolation equals InterpolationCase::LANCZOS lanczos interpolation} the default choosen lanczos window is initialized by value 2.
The default border comportement is define as ResampleBorderComportement#FILL_VALUE
In case where pixel transformation is out of source image boundary the default choosen fill value is Double#NaN.
Moreover : the specified MathTransform should be from CENTER of target image point to CENTER of source image point.
The used MathTransform is consider as PixelInCell#CELL_CENTER configuration.
Parameters
mathTransform Transformation use to transform target point to source point.
imageDest image will be fill by image source pixel interpolation.
imageSrc source image which contain pixel values which will be interpolate.
interpolation case of interpolation.
Exceptions
NoninvertibleTransformException if it is impossible to invert
MathTransform
parameter.
See also
ResampleBorderComportement
LanczosInterpolation::LanczosInterpolation(org.geotoolkit.image.iterator.PixelIterator, int)
References ResampleBorderComportement.FILL_VALUE, and Resample.imageDest.
{
         this(mathTransform, imageDest, null, imageSrc, interpolation, 2, ResampleBorderComportement.FILL_VALUE, new double[imageDest.getSampleModel().getNumBands()]);
     }
Resample() [4/7]
Resample (MathTransform mathTransform, WritableRenderedImage imageDest, RenderedImage imageSrc, InterpolationCase interpolation, ResampleBorderComportement rbc, double [] fillValue) throws TransformException
Fill destination image area from interpolation of source pixels from imageSrc.
Source pixel coordinates is obtained from invert transformation of destination pixel coordinates.
In case where interpolation equals InterpolationCase::LANCZOS lanczos interpolation} the default choosen lanczos window is initialized by value 2.
Moreover : the specified MathTransform should be from CENTER of target image point to CENTER of source image point.
The used MathTransform is consider as PixelInCell#CELL_CENTER configuration.
Parameters
mathTransform Transformation use to transform target point to source point.
imageDest image will be fill by image source pixel interpolation.
imageSrc source image which contain pixel values which will be interpolate.
interpolation case of interpolation.
rbc comportement of the destination image border.
fillValue contains value use when pixel transformation is out of source image boundary.
Exceptions
NoninvertibleTransformException if it is impossible to invert
MathTransform
parameter.
See also
ResampleBorderComportement
References Resample.fillValue, Resample.imageDest, and Resample.rbc.
{
         this(mathTransform, imageDest, null, imageSrc, interpolation, 2, rbc, fillValue);
     }
Resample() [5/7]
Resample (MathTransform mathTransform, WritableRenderedImage imageDest, RenderedImage imageSrc, InterpolationCase interpolation, int lanczosWindow, ResampleBorderComportement rbc, double [] fillValue) throws TransformException
Fill destination image area from interpolation of source pixels from imageSrc.
Source pixel coordinates is obtained from invert transformation of destination pixel coordinates.
Moreover : the specified MathTransform should be from CENTER of target image point to CENTER of source image point.
The used MathTransform is consider as PixelInCell#CELL_CENTER configuration.
Parameters
mathTransform Transformation use to transform target point to source point.
imageDest image will be fill by image source pixel interpolation.
imageSrc source image which contain pixel values which will be interpolate.
interpolation case of interpolation.
lanczosWindow only use about Lanczos interpolation.
rbc comportement of the destination image border.
fillValue contains value use when pixel transformation is out of source image boundary, or
null
.
Exceptions
NoninvertibleTransformException if it is impossible to invert
MathTransform
parameter.
See also
ResampleBorderComportement
References Resample.fillValue, Resample.imageDest, and Resample.rbc.
{
         this(mathTransform, imageDest, null, imageSrc, interpolation, lanczosWindow, rbc, fillValue);
     }
Resample() [6/7]
Resample (MathTransform mathTransform, WritableRenderedImage imageDest, Rectangle resampleArea, RenderedImage imageSrc, InterpolationCase interpolation, int lanczosWindow, ResampleBorderComportement rbc, double [] fillValue) throws TransformException
Fill destination image area from interpolation of source pixels from imageSrc.
Source pixel coordinates is obtained from invert transformation of destination pixel coordinates.
Moreover : the specified MathTransform should be from CENTER of target image point to CENTER of source image point.
The used MathTransform is consider as PixelInCell#CELL_CENTER configuration. fillValue parameter should be
null
, in case where fillValue is null, when destination coordinates pixel transformation is out of source boundary the destination pixel has no setted sample values.
In other words resampling has no impact on destination pixel samples values when transformation is outside source image boundary.
Parameters
mathTransform Transformation use to transform target point to source point.
imageDest image will be fill by image source pixel interpolation.
resampleArea destination image area within pixels are resample.
imageSrc source image which contain pixel values which will be interpolate.
interpolation case of interpolation.
lanczosWindow only use about Lanczos interpolation.
rbc comportement of the destination image border.
fillValue contains value use when pixel transformation is out of source image boundary.
Exceptions
NoninvertibleTransformException if it is impossible to invert
MathTransform
parameter.
See also
ResampleBorderComportement
References Interpolation.create(), ResampleBorderComportement.CROP, Resample.fillValue, Resample.getClamp(), Resample.imageDest, InterpolationCase.NEIGHBOR, and Resample.rbc.
{
         ArgumentChecks.ensureNonNull("mathTransform", mathTransform);
         ArgumentChecks.ensureNonNull("imageSrc", imageSrc);
         ArgumentChecks.ensureNonNull("ResampleBorderComportement", rbc);
         ArgumentChecks.ensureNonNull("imageDest", imageDest);
         /*
         * If a user give a destination image he should hope that his image boundary stay unchanged.
         */
         if (rbc == ResampleBorderComportement.CROP)
             throw new IllegalArgumentException("It is impossible to define appropriate border comportement with a given image and crop request.");
         this.imageDest = imageDest;
         this.numBands = imageSrc.getSampleModel().getNumBands();
         this.fillValue = fillValue;
         if (fillValue != null)
             if (fillValue.length != numBands)
                 throw new IllegalArgumentException("fillValue table length and numbands are different : "+fillValue.length+" numbands = "+this.numBands);
         assert(numBands == imageDest.getWritableTile(imageDest.getMinTileX(), imageDest.getMinTileY()).getNumBands())
                 : "destination image numbands different from source image numbands";
         this.destIterator              = new WritablePixelIterator.Builder().setRegionOfInterest(resampleArea).createWritable(this.imageDest);
         this.destToSourceMathTransform = mathTransform;
         srcCoords  = new double[2];
         destCoords = new double[2];
         //-- interpolation creation --//
         PixelIterator pix = PixelIterator.create(imageSrc);
         Rectangle boundary = pix.getDomain();
         if (lanczosWindow > boundary.width || lanczosWindow > boundary.height) {
             //image is too small for interpolation, switch to neareast neighor
             lanczosWindow = 1;
             interpolation = InterpolationCase.NEIGHBOR;
         }
         interpol = Interpolation.create(pix, interpolation, lanczosWindow, rbc, fillValue);
         this.rbc   = rbc;
         this.clamp = getClamp(imageDest.getSampleModel().getDataType());
     }
Resample() [7/7]
Resample (MathTransform mathTransform, WritableRenderedImage imageDest, Rectangle resampleArea, Interpolation interpol, double [] fillValue, ResampleBorderComportement rbc) throws NoninvertibleTransformException, TransformException
Fill destination image area from interpolation of source pixels.
Source pixel coordinate is obtained from invert transformation of destination pixel coordinates.
Moreover : the specified MathTransform should be from CENTER of target image point to CENTER of source image point.
The used MathTransform is consider with PixelInCell#CELL_CENTER configuration.
Parameters
mathTransform Transformation use to transform target point to source point.
imageDest image will be fill by image source pixel interpolation.
resampleArea destination image area within pixels are resample.
interpol Interpolation use to interpolate source image pixels.
fillValue contains value use when pixel transformation is out of source image boundary.
rbc comportement of the destination image border.
Exceptions
NoninvertibleTransformException if it is impossible to invert
MathTransform
parameter.
See also
ResampleBorderComportement
References ResampleBorderComportement.CROP, Resample.fillValue, Interpolation.getBoundary(), Resample.getClamp(), Interpolation.getNumBands(), Resample.imageDest, Resample.interpol, and Resample.rbc.
{
         ArgumentChecks.ensureNonNull("mathTransform", mathTransform);
         ArgumentChecks.ensureNonNull("interpolation", interpol);
         ArgumentChecks.ensureNonNull("imageDest", imageDest);
         final Rectangle bound    = interpol.getBoundary();
         /*
          * If a user give a destination image he should hope that his image boundary stay unchanged.
          */
         if (rbc == ResampleBorderComportement.CROP)
             throw new IllegalArgumentException("It is impossible to define appropriate border comportement with a given image and crop request.");
         this.imageDest = imageDest;
         this.numBands  = interpol.getNumBands();
         this.fillValue = fillValue;
         if (fillValue != null)
             if (fillValue.length != numBands)
                 throw new IllegalArgumentException("fillValue table length and numbands are different : "+fillValue.length+" numbands = "+this.numBands);
         assert(numBands == imageDest.getWritableTile(imageDest.getMinTileX(), imageDest.getMinTileY()).getNumBands())
                 : "destination image numbands different from source image numbands";
         this.destIterator              = new WritablePixelIterator.Builder().setRegionOfInterest(resampleArea).createWritable(this.imageDest);
         this.destToSourceMathTransform = mathTransform;
         this.interpol                  = interpol;
         srcCoords  = new double[2];
         destCoords = new double[2];
         this.rbc   = rbc;
         this.clamp = getClamp(imageDest.getSampleModel().getDataType());
     }
Member Function Documentation
fillImage() [1/2]
void fillImage () throws TransformException
Fill destination image from source image pixel interpolation.
{
         fillImage(true);
     }
fillImage() [2/2]
void fillImage (boolean canUseGrid) throws TransformException
References GridFactory.create(), Resample.fillImageByAffineTransform(), Resample.fillImageByGrid(), and Resample.fillImageByTransform().
{
         if (canUseGrid && destToSourceMathTransform instanceof MathTransform2D) {
             try {
                 final GridFactory gridFact = new GridFactory(0.125);
                 final Object object = gridFact.create((MathTransform2D) destToSourceMathTransform, destIterator.getDomain());
                 if (object instanceof AffineTransform) {
                     fillImageByAffineTransform((AffineTransform) object);
                 } else {
                     theGrid = (ResampleGrid) object;
                     fillImageByGrid();
                 }
                 return;
             } catch (TransformException ex) {
                 //-- leave to fall back
             } catch (ArithmeticException e) {
                 //-- leave to fall back
             }
         }
         fillImageByTransform();
     }
fillImageByAffineTransform()
void fillImageByAffineTransform (AffineTransform destCoordToSource) throws TransformException private
Fill image without any grid, all pixels coordinates are transform by given MathTransform.
Exceptions
TransformException
References Interpolation.checkInterpolate(), XMath.clamp(), Interpolation.interpolate(), and Resample.numBands.
Referenced by Resample.fillImage().
{
         while (destIterator.next()) {
             //-- Compute source coordinate from destination coordinate and mathtransform.
             final Point position = destIterator.getPosition();
             destCoords[0] = position.x;
             destCoords[1] = position.y;
             destCoordToSource.transform(destCoords, 0, srcCoords, 0, 1);
             //-- if destination coordinate transformation is out of source boundary.
             if (!interpol.checkInterpolate(srcCoords[0], srcCoords[1])) {
                 if (fillValue != null) destIterator.setPixel(fillValue);
             } else {
                 for (int band = 0; band < numBands; band++) {
                     double sample = interpol.interpolate(srcCoords[0], srcCoords[1], band);
                     if (clamp != null) sample = XMath.clamp(sample, clamp[0], clamp[1]);
                     destIterator.setSample(band, sample);
                 }
             }
         }
     }
fillImageByGrid()
void fillImageByGrid () throws TransformException private
Fill destination image from pre-computed grid.
Exceptions
TransformException
References Interpolation.checkInterpolate(), XMath.clamp(), ResampleGrid.getGrid(), ResampleGrid.getGridHeight(), ResampleGrid.getGridWidth(), ResampleGrid.getMinGridX(), ResampleGrid.getMinGridXIndex(), ResampleGrid.getMinGridY(), ResampleGrid.getMinGridYIndex(), ResampleGrid.getStepX(), ResampleGrid.getStepY(), Interpolation.interpolate(), and Resample.numBands.
Referenced by Resample.fillImage().
{
         final double[] theGridArray  = theGrid.getGrid();
         final int stepX              = theGrid.getStepX();
         final int stepY              = theGrid.getStepY();
         final int minGridX           = theGrid.getMinGridX();
         final int minGridY           = theGrid.getMinGridY();
         final int minGridXIndex      = theGrid.getMinGridXIndex();
         final int minGridYIndex      = theGrid.getMinGridYIndex();
         //-- destination area traveled by destination iterator.
         Rectangle rectBound  = destIterator.getDomain();
         //-- destination raster dimensions.
         final int tileWidth  = imageDest.getTileWidth();
         final int tileHeight = imageDest.getTileHeight();
         //-- destination raster index which will be traveled.
         final int destMinRastXIndex = imageDest.getMinTileX() + (rectBound.x - imageDest.getMinX()) / tileWidth;
         final int destMinRastYIndex = imageDest.getMinTileY() + (rectBound.y - imageDest.getMinY()) / tileHeight;
         final int destMaxRastX      = imageDest.getMinTileX() + (rectBound.x + rectBound.width + tileWidth - 1) / tileWidth;
         final int destMaxRastY      = imageDest.getMinTileY() + (rectBound.y + rectBound.height + tileHeight - 1) / tileHeight;
         //-- grid dimensions.
         final int gridWidth         = theGrid.getGridWidth();
         final int gridHeight        = theGrid.getGridHeight();
         final int gridLineStride    = gridWidth << 1;
         //-- current raster coordinate in Y direction.
         int rY    = destMinRastYIndex * tileHeight;
         int rMaxY = rY + tileHeight;
         for (int idRy = destMinRastYIndex; idRy < destMaxRastY; idRy++) {
             //-- define intersection between current raster and area traveled by destination iterator in Y direction.
             final int interMinRastY = StrictMath.max(rY, rectBound.y);
             final int interMaxRastY = StrictMath.min(rMaxY, rectBound.y + rectBound.height);
             //-- define minimum and maximum needed grid index in Y direction.
             final int gCMinY = (int) ((interMinRastY - minGridY) / stepY) + minGridYIndex;
             /*
              * Max grid index in Y direction equal Math.ceil(intersectionY / stepY) + 1.
              * With + 1 because gridHeight = sub-division on Y axis + 1;
              */
             final int gCMaxY = (int) ((interMaxRastY - minGridY + stepY - 1) / stepY) + minGridYIndex + 1;
             assert gCMaxY <= gridHeight : "Computed max grid index should be lesser or equal than grid height. Expected max grid index : "+gridHeight+", found : "+gCMaxY;
             //-- current raster coordinate in X direction.
             int rX    = destMinRastXIndex * tileWidth;
             int rMaxX = rX + tileWidth;
             for (int idRx = destMinRastXIndex; idRx < destMaxRastX; idRx++) {
                 //-- define intersection between current raster and area traveled by destination iterator in X direction.
                 final int interMinRastX = StrictMath.max(rX, rectBound.x);
                 final int interMaxRastX = StrictMath.min(rMaxX, rectBound.x + rectBound.width);
                 //-- define minimum and maximum needed grid index in X direction.
                 final int gCMinX = (int) (interMinRastX - minGridY / stepX) + minGridXIndex;
                 /*
                  * Max grid index in X direction equal Math.ceil(intersectionX / stepX) + 1.
                  * With + 1 because gridWidth = sub-division on X axis + 1;
                  */
                 final int gCMaxX = (int) ((interMaxRastX - minGridX + stepX - 1) / stepX) + minGridXIndex + 1;
                 assert gCMaxX <= gridWidth : "Computed max grid index in X direction should be lesser or equal than grid width. Expected max grid index : "+gridWidth+", found : "+gCMaxX;
                 //------------------------- grid working -------------------------//
                 //-- index des points a interpoler dans la grille
                 int id10, id11;
                 double v00X, v10X, v01X, v11X;
                 double v00Y, v10Y, v01Y, v11Y;
                 //-- travel destination pixel coordinates.
                 //-- intersection between area iterated on raster and current grid cell projected into raster space.
                 final int interMinY = StrictMath.max(interMinRastY, gCMinY * stepY);
                 final int interMinX = StrictMath.max(interMinRastX, gCMinX * stepX);
                 final int interMaxY = StrictMath.min(interMaxRastY, gCMaxY * stepY);
                 final int interMaxX = StrictMath.min(interMaxRastX, gCMaxX * stepX);
                 //-- define grid array index.
                 int rowId0 = gCMinY * gridLineStride + (gCMinX << 1);
                 int maxRowId0 = (gCMaxY - 2) * gridLineStride + (gCMinX << 1);
                 int rowId1 = rowId0 + gridLineStride;
                 int py = interMinY;
                 //-- Define pixel coordinate in Y direction to pass at next grid cell.
                 int nextGIdY = (gCMinY + 1) * stepY;// + (stepY >>> 1);
                 //-- current grid index in X direction.
                 int gx = gCMinX;
                 //-- current grid index in Y direction.
                 int gy = gCMinY;
                 while (py < interMaxY) {
                     if (py == nextGIdY) {
                         rowId0 += gridLineStride;
                         rowId0 = StrictMath.min(rowId0, maxRowId0);
                         rowId1 = rowId0 + gridLineStride;
                         gy = StrictMath.min(++gy, gridHeight - 2);
                         nextGIdY += stepY;
                     }
                     id10 = rowId0 + 2;
                     id11 = rowId1 + 2;
                     gx   = gCMinX;
                     int px = interMinX;
                     //-- Define pixel coordinate in X direction to pass at next grid cell.
                     int nextGIdX = (gCMinX + 1) * stepX;// + (stepX >>> 1);
                     /*
                      * To define source image coordinate we use bilinear interpolation
                      * from precedently computed values from grid.
                      * Bilinear interpolation is computing like follow in 3 steps.
                      * First we compute "A" value from v00 and v01 (grid values),
                      * t0y which is v00 position in grid and ty the destination
                      * pixel coordinate projected into grid space by followed formula : A = (ty - t0y) * (v10 - v00) + v00.
                      *
                      * Secondly, with the same formula we compute B.
                      *
                      * And finally, we compute coordinates by same precedently formula
                      * with precedently computing results A and B but on X axis.
                      *
                      * P = (tX - t0X) * (B - A) + A
                      *
                      *              t0X           tX
                      *               |            |            |
                      *             ____           |          ____
                      *   t0y ------|v00|--------- C ---------|v10|----
                      *               |            |            |
                      *               |            |            |
                      *               |            |            |
                      *               |            |            |
                      *      ty ----  A ---------- P ---------- B-----
                      *               |            |            |
                      *               |            |            |
                      *               |            |            |
                      *               |            |            |
                      *             ____           |          ____
                      *       ------|v01|--------- D ---------|v11|----
                      *               |            |            |
                      *
                      * During iteration in X direction into the grid we note that v00 become v10 and v01 -> v11, and thereby A = B.
                      * To avoid some of unneccessary computing we affect B to A and
                      * we just re-compute B value and only interpolation in X direction (C and D values).
                      */
                     //-- vX
                     v00X = theGridArray[rowId0];     v10X = theGridArray[id10];
                     v01X = theGridArray[rowId1];     v11X = theGridArray[id11];
                     //-- vY
                     v00Y = theGridArray[rowId0 | 1]; v10Y = theGridArray[id10 | 1];
                     v01Y = theGridArray[rowId1 | 1]; v11Y = theGridArray[id11 | 1];
                     //-- destination image pixel coordinate into grid space in Y direction.
                     final double destY = (py + imageDest.getMinY()) / ((double) stepY);
                     final double ty_t0y = (destY - gy); //-- ty - toy
                     //-- constant value on X source coordinate.
                     double coeff0X = ty_t0y * (v01X - v00X);
                     double coeff1X = ty_t0y * (v11X - v10X);
                     //-- constant value on Y source coordinate.
                     double coeff0Y = ty_t0y * (v01Y - v00Y);
                     double coeff1Y = ty_t0y * (v11Y - v10Y);
                     while (px < interMaxX) {
                         if (px == nextGIdX) {
                             nextGIdX += stepX;
                             if (++gx <= gridWidth - 2) {
                                 id10 += 2;
                                 id11 += 2;
                                 v00X = v10X;
                                 v01X = v11X;
                                 v10X = theGridArray[id10];
                                 v11X = theGridArray[id11];
                                 v00Y = v10Y;
                                 v01Y = v11Y;
                                 v10Y = theGridArray[id10 | 1];
                                 v11Y = theGridArray[id11 | 1];
                                 //-- coefficient exchange
                                 //-- on destination X axis coordinate
                                 coeff0X = coeff1X;
                                 coeff1X = ty_t0y * (v11X - v10X);
                                 //-- on destination Y axis coordinate
                                 coeff0Y = coeff1Y;
                                 coeff1Y = ty_t0y * (v11Y - v10Y);
                             } else {
                                 gx--;
                             }
                         }
                         //-- coordinate interpolation
                         final double destX = (px + imageDest.getMinX()) / ((double) stepX); //-- remonter cette addition pour eviter n *
                         final double tx_t0x = (destX - gx);//-- tx - t0x
                         //-- Compute interpolation from destination image pixel coordinate and
                         //-- computed source coordinates from grid.
                         //-- interpolation on X coordinates
                         final double srcX = tx_t0x * (coeff1X + v10X - v00X) + (1 - tx_t0x) * coeff0X + v00X;
                         //-- interpolation on Y coordinates
                         final double srcY = tx_t0x * (coeff1Y + v10Y - v00Y) + (1 - tx_t0x) * coeff0Y + v00Y;
                         //-- pixel value interpolation
                         //-- if destination coordinate transformation is out of source boundary.
                         destIterator.next();
                         if (!interpol.checkInterpolate(srcX, srcY)) {
                             if (fillValue != null) {
                                 destIterator.setPixel(fillValue);
                             }
                         } else {
                             for (int band=0; band<numBands; band++) {
                                 double sample = interpol.interpolate(srcX, srcY, band);
                                 if (clamp != null) sample = XMath.clamp(sample, clamp[0], clamp[1]);
                                 destIterator.setSample(band, sample);
                             }
                         }
                         px++;
                     }
                     py++;
                 }
                 //------------------------- grid working -------------------------//
                 rX += tileWidth;
                 rMaxX += tileWidth;
             }
             rY    += tileHeight;
             rMaxY += tileHeight;
         }
     }
fillImageByTransform()
void fillImageByTransform () throws TransformException private
Fill image without any grid, all pixels coordinates are transform by given MathTransform.
Exceptions
TransformException
References Interpolation.checkInterpolate(), XMath.clamp(), Interpolation.interpolate(), and Resample.numBands.
Referenced by Resample.fillImage().
{
         while (destIterator.next()) {
             //-- Compute source coordinate from destination coordinate and mathtransform.
             final Point position = destIterator.getPosition();
             destCoords[0] = position.x;
             destCoords[1] = position.y;
             try {
                 destToSourceMathTransform.transform(destCoords, 0, srcCoords, 0, 1);
             } catch (ProjectionException ex) {
                 //coordinate can not be computed in source crs
                 srcCoords[0] = Double.NaN;
                 srcCoords[1] = Double.NaN;
             }
             //-- if destination coordinate transformation is out of source boundary.
             if (!interpol.checkInterpolate(srcCoords[0], srcCoords[1])) {
                 if (fillValue != null) destIterator.setPixel(fillValue);
             } else {
                 for (int band = 0; band < numBands; band++) {
                     double sample = interpol.interpolate(srcCoords[0], srcCoords[1], band);
                     if (clamp != null) sample = XMath.clamp(sample, clamp[0], clamp[1]);
                     destIterator.setSample(band, sample);
                 }
             }
         }
     }
fillImagePx()
void fillImagePx () throws TransformException
Please use fillImageByTransform() method.
Exceptions
TransformException
Deprecated:
replace by fillImageByTransform().
References Interpolation.checkInterpolate(), XMath.clamp(), Interpolation.interpolate(), and Resample.numBands.
{
         while (destIterator.next()) {
             //-- Compute source coordinate from destination coordinate and mathtransform.
             final Point position = destIterator.getPosition();
             destCoords[0] = position.x;
             destCoords[1] = position.y;
             destToSourceMathTransform.transform(destCoords, 0, srcCoords, 0, 1);
             //-- if destination coordinate transformation is out of source boundary.
             if (!interpol.checkInterpolate(srcCoords[0], srcCoords[1])) {
                 if (fillValue != null) destIterator.setPixel(fillValue);
             } else {
                 for (int band = 0; band < numBands; band++) {
                     double sample = interpol.interpolate(srcCoords[0], srcCoords[1], band);
                     if (clamp != null) sample = XMath.clamp(sample, clamp[0], clamp[1]);
                     destIterator.setSample(band, sample);
                 }
             }
         }
     }
getClamp()
static double [] getClamp (int dataType) static private
References Resample.CLAMP_BYTE, Resample.CLAMP_INT, Resample.CLAMP_SHORT, and Resample.CLAMP_USHORT.
Referenced by Resample.Resample().
{
         switch (dataType) {
             /* Because DataBuffer.TYPE_BYTE is define as UByte. */
             case DataBuffer.TYPE_BYTE   : return CLAMP_BYTE;
             case DataBuffer.TYPE_SHORT  : return CLAMP_SHORT;
             case DataBuffer.TYPE_USHORT : return CLAMP_USHORT;
             case DataBuffer.TYPE_INT    : return CLAMP_INT;
             default                     : return null;
         }
     }
getGrid()
ResampleGrid getGrid () package
Returns the needed grid use to resample if exist or.
null
if none.
Returns
needed grid use to resample if exist or
null
if none.
References Resample.theGrid.
{
         return theGrid;
     }
getInterpol()
Interpolation getInterpol ()
Returns Interpolation object use to resample.
Returns
Interpolation object use to resample.
References Resample.interpol.
{
         return interpol;
     }
Member Data Documentation
clamp
final double [] clamp protected
Minimum and maximum values authorized for pixels.
All interpolated value outside this interval will be clamped.
CLAMP_BYTE
final double [] CLAMP_BYTE = new double[]{0, 255} static private
Referenced by Resample.getClamp().
CLAMP_INT
final double [] CLAMP_INT = new double[]{Integer.MIN_VALUE, Integer.MAX_VALUE} static private
Referenced by Resample.getClamp().
CLAMP_SHORT
final double [] CLAMP_SHORT = new double[]{Short.MIN_VALUE, Short.MAX_VALUE} static private
Referenced by Resample.getClamp().
CLAMP_USHORT
final double [] CLAMP_USHORT = new double[]{0, 0xFFFF} static private
Referenced by Resample.getClamp().
destCoords
final double [] destCoords private
Table which contain x, y coordinates after MathTransform transformation.
destIterator
final WritablePixelIterator destIterator package
Iterator use to fill destination image from interpolation of source image pixel value.
destToSourceMathTransform
MathTransform destToSourceMathTransform private
Transform multi-dimensional point (in our case pixel coordinate) from target image.
CoordinateReferenceSystem
to source image
CoordinateReferenceSystem
. TODO : require a 2D transform, so we can directly convert positions from image iterator instead of requiring an array buffer.
fillValue
double [] fillValue private
Contains value use when destination pixel coordinates transformation are out of source image boundary.
Referenced by Resample.Resample().
imageDest
final WritableRenderedImage imageDest private
Image in which image source pixel interpolation result is push.
Referenced by Resample.Resample().
interpol
final Interpolation interpol private
Sort of interpolation use to interpolate image source pixels.
Referenced by Resample.getInterpol(), and Resample.Resample().
numBands
final int numBands private
Image number bands.
Note : source and target image have same bands number.
Referenced by Resample.fillImageByAffineTransform(), Resample.fillImageByGrid(), Resample.fillImageByTransform(), and Resample.fillImagePx().
rbc
ResampleBorderComportement rbc package
On the border of the destination image, projection of destination border pixel coordinates should be out of source image boundary.
This enum explain the expected comportement define by user. By default is ResampleBorderComportement#EXTRAPOLATION, which allow interpolation outside of source pixel validity area.
Referenced by Resample.Resample().
srcCoords
final double [] srcCoords private
Table which contain x, y coordinates after MathTransform transformation.
theGrid
ResampleGrid theGrid package
Grid use to resample image if exist.
See also
GridFactory::create(org.opengis.referencing.operation.MathTransform2D, java.awt.Rectangle)
Referenced by Resample.getGrid().