jena-geo: SampleValues.Double Class Reference
SampleValues.Double Class Reference
Implementation backed by.
Public Member Functions
double getSample (int band)
SampleValues instance ()
SampleValues getPixel (final Raster source, final int x, final int y)
void setPixel (final WritableRaster dest, final int x, final int y)
int hashCode ()
boolean equals (final Object other)
String toString ()
Static Public Member Functions
static SampleValues getInstance (final int transferType, final int numBands)
Returns a new instance for the given number of bands.
static SampleValues getInstance (final int transferType, final double[] values)
Returns a new instance for the given type wrapping the given sample values.
static int [] copyAsInts (final double[] data)
Returns a copy of the given array where each value has been Math::round(double) rounded} to the.
Package Functions
Double (final int numBands)
Creates a new instance for the given number of bands.
Double (final double[] samples)
Creates a new instance initialized to the given value.
Package Attributes
final double [] samples
The values.
Detailed Description
Implementation backed by.
double
values.
Constructor & Destructor Documentation
Double() [1/2]
Double (final int numBands) package
Creates a new instance for the given number of bands.
Referenced by SampleValues.Double.instance().
{
             samples = new double[numBands];
         }
Double() [2/2]
Double (final double [] samples) package
Creates a new instance initialized to the given value.
{
             this.samples = samples.clone();
         }
Member Function Documentation
copyAsInts()
static int [] copyAsInts (final double [] data) static inherited
Returns a copy of the given array where each value has been Math::round(double) rounded} to the.
int
type.
Parameters
data the array to copy, or
null
.
Returns
a copy of the given array with values rounded to the
int
type, or
null
if the given array was null.
Referenced by Mask.computeRect(), and SampleValues.Integer.Integer().
{
         if (data == null) return null;
         final int[] result = new int[data.length];
         for (int i=0; i<data.length; i++) {
             result[i] = Math.toIntExact(Math.round(data[i]));
         }
         return result;
     }
equals()
boolean equals (final Object other)
{
             return (other instanceof Double) && Arrays.equals(samples, ((Double) other).samples);
         }
getInstance() [1/2]
static SampleValues getInstance (final int transferType, final int numBands) static inherited
Returns a new instance for the given number of bands.
The transfer type must be one of the DataBuffer constants.
Referenced by SilhouetteMask.computeImage(), and FloodFill.fill().
{
         switch (transferType) {
             case DataBuffer.TYPE_DOUBLE: return new Double (numBands);
             case DataBuffer.TYPE_FLOAT:  return new Float  (numBands);
             default:                     return new Integer(numBands);
         }
     }
getInstance() [2/2]
static SampleValues getInstance (final int transferType, final double [] values) static inherited
Returns a new instance for the given type wrapping the given sample values.
The transfer type must be one of the DataBuffer constants.
References SampleValues.getPixel(), SampleValues.getSample(), SampleValues.instance(), and SampleValues.setPixel().
{
         switch (transferType) {
             case DataBuffer.TYPE_DOUBLE: return new Double (values);
             case DataBuffer.TYPE_FLOAT:  return new Float  (values);
             default:                     return new Integer(values);
         }
     }
getPixel()
SampleValues getPixel (final Raster source, final int x, final int y)
References SampleValues.getPixel().
{
             source.getPixel(x, y, samples);
             return this;
         }
getSample()
double getSample (int band)
{
             return samples[band];
         }
hashCode()
int hashCode ()
{
             return Arrays.hashCode(samples);
         }
instance()
SampleValues instance ()
References SampleValues.Double.Double().
{
             return new Double(samples.length);
         }
setPixel()
void setPixel (final WritableRaster dest, final int x, final int y)
{
             dest.setPixel(x, y, samples);
         }
toString()
String toString ()
{
             return Arrays.toString(samples);
         }
Member Data Documentation
samples
final double [] samples package
The values.