jena-geo: SampleModels Class Reference
SampleModels Class Reference
A set of static methods working on SampleModel.
Static Public Member Functions
static int getDataTypeSize (final SampleModel model)
Returns the size (in bits) of the data type for the given sample model.
static int getScanlineStride (final SampleModel model) throws IllegalArgumentException
Returns the <cite>scan line stride</cite> of the given sample model.
static float getPixelStride (final SampleModel model) throws IllegalArgumentException
Returns the <cite>pixel stride</cite> of the given sample model.
static int getPixelBitStride (final SampleModel model) throws IllegalArgumentException
Returns the <cite>pixel stride</cite> of the given sample model in bits.
Private Member Functions
SampleModels ()
Do not allow instantiation of this class.
Detailed Description
A set of static methods working on SampleModel.
Author
Martin Desruisseaux (Geomatys)
Version
3.07
Since
3.07
Constructor & Destructor Documentation
SampleModels()
SampleModels () private
Do not allow instantiation of this class.
{
     }
Member Function Documentation
getDataTypeSize()
static int getDataTypeSize (final SampleModel model) static
Returns the size (in bits) of the data type for the given sample model.
This is a convenience method for:
{ java return DataBuffer.getDataTypeSize(model.getDataType()); }
Parameters
model The sample model for which to get the size of data type.
Returns
The size of data type, in bits.
See also
DataBuffer::getDataTypeSize(int)
Referenced by SampleModels.getPixelBitStride(), and SampleModels.getPixelStride().
{
         return DataBuffer.getDataTypeSize(model.getDataType());
     }
getPixelBitStride()
static int getPixelBitStride (final SampleModel model) throws IllegalArgumentException static
Returns the <cite>pixel stride</cite> of the given sample model in bits.
This is the number of bits between two samples for the same band on the same scanline.
Parameters
model The sample model from which to get the pixel stride.
Returns
The pixel stride in bits.
Exceptions
IllegalArgumentException If the given model is not of a known type.
References Errors.format(), SampleModels.getDataTypeSize(), and Errors.Keys.UnknownType_1.
{
         if (model instanceof ComponentSampleModel) {
             return ((ComponentSampleModel) model).getPixelStride() * getDataTypeSize(model);
         }
         if (model instanceof SinglePixelPackedSampleModel) {
             return getDataTypeSize(model);
         }
         if (model instanceof MultiPixelPackedSampleModel) {
             return ((MultiPixelPackedSampleModel) model).getPixelBitStride();
         }
         throw new IllegalArgumentException(Errors.format(
                 Errors.Keys.UnknownType_1, Classes.getShortClassName(model)));
     }
getPixelStride()
static float getPixelStride (final SampleModel model) throws IllegalArgumentException static
Returns the <cite>pixel stride</cite> of the given sample model.
The pixel stride is the number of data array elements between two samples for the same band on the same scanline.
If the given model is an instance of MultiPixelPackedSampleModel, then the stride can be fractional. Note that the returned value still exact since the ratio of an integer with a power of 2 has exact representations in IEEE 754.
Parameters
model The sample model from which to get the pixel stride.
Returns
The pixel stride, rounded toward positive infinity if necessary.
Exceptions
IllegalArgumentException If the given model is not of a known type.
References Errors.format(), SampleModels.getDataTypeSize(), and Errors.Keys.UnknownType_1.
{
         if (model instanceof ComponentSampleModel) {
             return ((ComponentSampleModel) model).getPixelStride();
         }
         if (model instanceof SinglePixelPackedSampleModel) {
             return 1;
         }
         if (model instanceof MultiPixelPackedSampleModel) {
             return ((MultiPixelPackedSampleModel) model).getPixelBitStride() / (float) getDataTypeSize(model);
         }
         throw new IllegalArgumentException(Errors.format(
                 Errors.Keys.UnknownType_1, Classes.getShortClassName(model)));
     }
getScanlineStride()
static int getScanlineStride (final SampleModel model) throws IllegalArgumentException static
Returns the <cite>scan line stride</cite> of the given sample model.
The scanline stride is the number of data array elements between a given sample and the corresponding sample in the same column of the next scanline.
Parameters
model The sample model from which to get the scan line stride.
Returns
The scan line stride.
Exceptions
IllegalArgumentException If the given model is not of a known type.
References Errors.format(), and Errors.Keys.UnknownType_1.
{
         if (model instanceof ComponentSampleModel) {
             return ((ComponentSampleModel) model).getScanlineStride();
         }
         if (model instanceof SinglePixelPackedSampleModel) {
             return ((SinglePixelPackedSampleModel) model).getScanlineStride();
         }
         if (model instanceof MultiPixelPackedSampleModel) {
             return ((MultiPixelPackedSampleModel) model).getScanlineStride();
         }
         throw new IllegalArgumentException(Errors.format(
                 Errors.Keys.UnknownType_1, Classes.getShortClassName(model)));
     }