jena-geo: Synchronizer Class Reference
Synchronizer Class Reference
Copies the content of a table from a database to an other database.
Classes
enum Policy
The kind of synchronization.
Public Member Functions
Synchronizer (final Connection source, final Connection target, final Writer out)
Creates a synchronizer from the given source database to the given target database.
Synchronizer (final String source, final String target) throws SQLException
Creates a synchronizer from the given source database to the given target database.
void copy (final Policy onExisting, final Map< String, String > tables) throws SQLException, IOException
Copies or replaces the content of the specified tables.
void copy (final Policy onExisting, final String... tables) throws SQLException, IOException
Copies or replaces the content of the specified tables, without conditions.
void close () throws SQLException
Closes the database connections.
Public Attributes
String sourceCatalog
The source and target catalogs, or.
String sourceSchema
The source and target schemas, or.
volatile boolean cancel
Sets to.
Package Attributes
final Connection target
transient DatabaseMetaData targetMetadata
String targetCatalog
String targetSchema
Static Package Attributes
static final Level UPDATE = Level.FINE
Private Member Functions
String [] getPrimaryKeys (final String table) throws SQLException
Returns the primary keys in the target database for the given table.
void delete (final String table, final String condition) throws SQLException
Deletes the content of the specified table in the target database.
void insert (final String table, final String condition, final Policy onExisting) throws SQLException, IOException
Copies the content of the specified table from source to the target database.
TableAppender createMismatchTable (final String table, final String[] pkColumns) throws IOException
Creates an initially empty (except for the header) table of mismatches.
void copy (final String table, final Map< String, String > tables, final Policy onExisting) throws SQLException, IOException
Copies or replaces the content of the specified table.
Static Private Member Functions
static void appendTableName (final StringBuilder buffer, final String schema, final String table, final String quote)
Appends a table name to the given buffer using the given quote character.
static boolean contains (final int[] array, final int value)
Returns.
static int getColumnIndex (final ResultSetMetaData metadata, final String column) throws SQLException
Returns the index of the specified column, or 0 if not found.
static int [] getColumnIndex (final ResultSetMetaData metadata, final String[] columns) throws SQLException
Returns the index of the specified columns.
static void log (final Level level, final String method, final String message)
Writes an event to the logger.
Private Attributes
final Connection source
The connection to the source and target databases.
transient DatabaseMetaData sourceMetadata
The metadata for the source and target databases.
final Writer out
Where to print reports.
boolean pretend
If.
Static Private Attributes
static final Level SELECT = Level.FINE
Logging level to use for SQL operations.
Detailed Description
Copies the content of a table from a database to an other database.
This class is used when there is two copies of a database (typically an experimental copy and an operational copy) and we want to copy the content of the experimental database to the operational database.
Mandatory parameters:
Connection to the source and target databases
List of tables to synchronize
Optional parameters:
Policy: Whatever to empty the tables before to re-insert all entries. Used when table content need to be replaced, not just updated with new entries.
pretend: Whatever to print the SQL statements to standard output instead than executing them.
Author
Martin Desruisseaux (Geomatys)
Cédric Briançon (Geomatys)
Version
3.19
Since
3.19
Constructor & Destructor Documentation
Synchronizer() [1/2]
Synchronizer (final Connection source, final Connection target, final Writer out)
Creates a synchronizer from the given source database to the given target database.
Parameters
source The connection to the source database.
target The connection to the target database.
out Where to print reports.
References Synchronizer.out, Synchronizer.source, and Synchronizer.target.
{
         this.source = source;
         this.target = target;
         this.out    = out;
     }
Synchronizer() [2/2]
Synchronizer (final String source, final String target) throws SQLException
Creates a synchronizer from the given source database to the given target database.
The reports will be sent to the standard output stream.
Parameters
source The URL to the source database.
target The URL to the target database.
Exceptions
SQLException If the connection to a database can not be established.
References IOUtilities.standardWriter().
{
         this.source = DriverManager.getConnection(source);
         this.target = DriverManager.getConnection(target);
         this.out    = IOUtilities.standardWriter();
         this.source.setReadOnly(true);
     }
Member Function Documentation
appendTableName()
static void appendTableName (final StringBuilder buffer, final String schema, final String table, final String quote) static private
Appends a table name to the given buffer using the given quote character.
The schema is optional and can be null.
Referenced by Synchronizer.delete(), and Synchronizer.insert().
     {
         buffer.append(quote);
         if (schema != null) {
             buffer.append(schema).append(quote).append('.').append(quote);
         }
         buffer.append(table).append(quote);
     }
close()
void close () throws SQLException
Closes the database connections.
Exceptions
SQLException If an error occurred while closing the connections.
{
         sourceMetadata = null;
         targetMetadata = null;
         target.close();
         source.close();
     }
contains()
static boolean contains (final int [] array, final int value) static private
Returns.
true
if the given array contains the given value. This is usually an inefficient way to make this checks when invoked in a loop. But for this class, the given array will be very short (often only one element, usually not more than three), so it should be sufficient.
Parameters
array The array where to check for a value. Elements doesn't need to be sorted (and often they are not).
value The value to search in the given array.
Referenced by Synchronizer.insert().
{
         for (int i=0; i<array.length; i++) {
             if (array[i] == value) {
                 return true;
             }
         }
         return false;
     }
copy() [1/3]
void copy (final String table, final Map< String, String > tables, final Policy onExisting) throws SQLException, IOException private
Copies or replaces the content of the specified table.
The Map::keySet map keys} shall contains the set of every tables to take in account; table not listed in this set will be untouched. The associated values are the SLQ conditions to put in the
WHERE
clauses.
This method process
table
as well as dependencies found in
tables
. Processed dependencies are removed from the
tables
map.
Parameters
table The table to process.
tables The (table, condition) mapping. This map will be modified.
onExisting What to do with existing entries before to write new ones.
Exceptions
SQLException if an error occurred while reading or writing in the database.
IOException if an error occurred while writing reports on this operation.
References Synchronizer.Policy.DELETE_BEFORE_INSERT, Synchronizer.insert(), Synchronizer.targetCatalog, and Synchronizer.targetSchema.
Referenced by Synchronizer.copy().
     {
         String condition = tables.remove(table);
         if (condition != null) {
             condition = condition.trim();
             if (condition.isEmpty()) {
                 condition = null;
             }
         }
         if (onExisting == Policy.DELETE_BEFORE_INSERT) {
             delete(table, condition);
         }
         /*
          * Before to insert any new records, check if this table has some foreigner keys
          * toward other table.  If such tables are found, we will process them before to
          * add any record to the current table.
          */
         final String catalog = targetCatalog;
         final String schema  = targetSchema;
         try (ResultSet dependencies = targetMetadata.getImportedKeys(catalog, schema, table)) {
             while (dependencies.next()) {
                 String dependency = dependencies.getString("PKTABLE_CAT");
                 if (catalog!=null && !catalog.equals(dependency)) {
                     continue;
                 }
                 dependency = dependencies.getString("PKTABLE_SCHEM");
                 if (schema!=null && !schema.equals(dependency)) {
                     continue;
                 }
                 dependency = dependencies.getString("PKTABLE_NAME");
                 if (tables.containsKey(dependency)) {
                     copy(dependency, tables, onExisting);
                 }
             }
         }
         insert(table, condition, onExisting);
     }
copy() [2/3]
void copy (final Policy onExisting, final Map< String, String > tables) throws SQLException, IOException
Copies or replaces the content of the specified tables.
The Map::keySet map keys} shall contains the set of every tables to take in account; table not listed in this set will be untouched. The associated values are the SLQ conditions to put in the
WHERE
clauses.
Parameters
onExisting What to do with existing entries before to write new ones.
tables The (table, condition) mapping. This map will be modified.
Exceptions
SQLException if an error occurred while reading or writing in the database.
IOException if an error occurred while writing reports on this operation.
References Synchronizer.copy(), Synchronizer.targetCatalog, and Synchronizer.targetSchema.
     {
         final String catalog = targetCatalog;
         final String schema  = targetSchema;
         sourceMetadata = source.getMetaData();
         targetMetadata = target.getMetaData();
 search: while (!tables.isEmpty()) {
 nextTable: for (final String table : tables.keySet()) {
                 if (cancel) break search;
                 // Skips all tables that have dependencies.
                 try (ResultSet dependents = targetMetadata.getExportedKeys(catalog, schema, table)) {
                     while (dependents.next()) {
                         if ((catalog==null || catalog.equals(dependents.getString("FKTABLE_CAT"))) &&
                             (schema ==null || schema .equals(dependents.getString("FKTABLE_SCHEM"))))
{
                             final String dependent = dependents.getString("FKTABLE_NAME");
                             if (tables.containsKey(dependent)) {
                                 continue nextTable;
                             }
                         }
                     }
                 }
                 // We have found a table which have no dependencies (a leaf).
                 copy(table, tables, onExisting);
                 continue search;
             }
             // We have been unable to find any leaf. Take a chance: process the first table.
             // An exception is likely to be throw, but we will have tried.
             for (final String table : tables.keySet()) {
                 copy(table, tables, onExisting);
                 continue search;
             }
         }
     }
copy() [3/3]
void copy (final Policy onExisting, final String... tables) throws SQLException, IOException
Copies or replaces the content of the specified tables, without conditions.
Parameters
onExisting What to do with existing entries before to write new ones.
tables The list of tables to update.
Exceptions
SQLException if an error occurred while reading or writing in the database.
IOException if an error occurred while writing reports on this operation.
References Synchronizer.copy().
{
         final Map<String,String> map = new LinkedHashMap<>(hashMapCapacity(tables.length));
         for (final String table : tables) {
             map.put(table, null);
         }
         copy(onExisting, map);
     }
createMismatchTable()
TableAppender createMismatchTable (final String table, final String [] pkColumns) throws IOException private
Creates an initially empty (except for the header) table of mismatches.
Parameters
table The table name.
pkColumns The column names.
Returns
A new table of mismatch.
Exceptions
IOException if an error occurred while writing to the output stream.
Referenced by Synchronizer.insert().
     {
         final String lineSeparator = System.lineSeparator();
         out.write(lineSeparator);
         out.write(table);
         out.write(lineSeparator);
         final TableAppender mismatchs = new TableAppender(out);
         mismatchs.nextLine('\u2500');
         for (int j=0; j<pkColumns.length; j++) {
             mismatchs.append(pkColumns[j]);
             mismatchs.nextColumn();
         }
         mismatchs.append("Colonne");
         mismatchs.nextColumn();
         mismatchs.append("Valeur à copier");
         mismatchs.nextColumn();
         mismatchs.append("Valeur existante");
         mismatchs.nextLine();
         mismatchs.nextLine('\u2500');
         return mismatchs;
     }
delete()
void delete (final String table, final String condition) throws SQLException private
Deletes the content of the specified table in the target database.
Parameters
table The name of the table in which to delete the records.
condition A SQL condition (to be put after a
WHERE
clause) for the records to be deleted, or
null
for deleting the whole table.
Exceptions
SQLException if a reading or writing operation failed.
References Synchronizer.appendTableName(), Synchronizer.log(), and Synchronizer.UPDATE.
{
         final String quote = targetMetadata.getIdentifierQuoteString();
         final StringBuilder buffer = new StringBuilder("DELETE FROM ");
         appendTableName(buffer, targetSchema, table, quote);
         if (condition != null) {
             buffer.append(" WHERE ").append(condition);
         }
         final String sql = buffer.toString();
         try (Statement targetStatement = target.createStatement()) {
             final int count = pretend ? 0 : targetStatement.executeUpdate(sql);
             log(UPDATE, "delete", sql + '\n' + count + " lignes supprimées.");
         }
     }
getColumnIndex() [1/2]
static int getColumnIndex (final ResultSetMetaData metadata, final String column) throws SQLException static private
Returns the index of the specified column, or 0 if not found.
Parameters
metadata The metadata to search into.
name The column to search for.
Returns
The index of the specified column.
Referenced by Synchronizer.getColumnIndex(), and Synchronizer.insert().
     {
         final int count = metadata.getColumnCount();
         for (int i=1; i<=count; i++) {
             if (column.equals(metadata.getColumnName(i))) {
                 return i;
             }
         }
         return 0;
     }
getColumnIndex() [2/2]
static int [] getColumnIndex (final ResultSetMetaData metadata, final String [] columns) throws SQLException static private
Returns the index of the specified columns.
If a column is not found, its corresponding index will be left to 0.
References Synchronizer.getColumnIndex().
     {
         final int[] index = new int[columns.length];
         for (int i=0; i<columns.length; i++) {
             index[i] = getColumnIndex(metadata, columns[i]);
         }
         return index;
     }
getPrimaryKeys()
String [] getPrimaryKeys (final String table) throws SQLException private
Returns the primary keys in the target database for the given table.
If the primary keys span over more than one column, then the columns are returned in sequence order. If the table has no primary key, then this method returns an array of length 0.
References Synchronizer.targetCatalog, and Synchronizer.targetSchema.
Referenced by Synchronizer.insert().
{
         final String catalog = targetCatalog;
         final String schema  = targetSchema;
         String[] columns;
         try (ResultSet results = targetMetadata.getPrimaryKeys(catalog, schema, table)) {
             columns = CharSequences.EMPTY_ARRAY;
             while (results.next()) {
                 if (catalog!=null && !catalog.equals(results.getString("TABLE_CAT"))) {
                     continue;
                 }
                 if (schema!=null && !schema.equals(results.getString("TABLE_SCHEM"))) {
                     continue;
                 }
                 if (!table.equals(results.getString("TABLE_NAME"))) {
                     continue;
                 }
                 final String column = results.getString("COLUMN_NAME");
                 final int index = results.getShort("KEY_SEQ");
                 if (index > columns.length) {
                     columns = Arrays.copyOf(columns, index);
                 }
                 columns[index - 1] = column;
             }
         }
         return columns;
     }
insert()
void insert (final String table, final String condition, final Policy onExisting) throws SQLException, IOException private
Copies the content of the specified table from source to the target database.
If a record already exists for the same primary key, the action will be determined by the given policy.
Parameters
table The name of the table to copy.
condition A SQL condition (to be put after a
WHERE
clause) for the records to be copied, or
null
for copying the whole table.
onExisting What to do with existing entries before to write new ones.
Exceptions
SQLException if a reading or writing operation failed.
IOException if an error occurred while writing reports on this operation.
References Synchronizer.appendTableName(), Synchronizer.contains(), Synchronizer.createMismatchTable(), Synchronizer.Policy.DELETE_BEFORE_INSERT, Synchronizer.getColumnIndex(), Synchronizer.getPrimaryKeys(), Synchronizer.Policy.INSERT_OR_UPDATE, Synchronizer.log(), Synchronizer.targetSchema, and Synchronizer.UPDATE.
Referenced by Synchronizer.copy().
     {
         /*
          * Creates the SQL statement for the SELECT query, opens the source ResultSet and
          * gets the metadata (especially the column names). This ResultSet will stay open
          * until the end of this method. We will use the column names later in order to
          * build the INSERT statement for the target database.
          */
         final String quoteSource = sourceMetadata.getIdentifierQuoteString();
         final StringBuilder buffer = new StringBuilder("SELECT * FROM ");
         appendTableName(buffer, sourceSchema, table, quoteSource);
         if (condition != null) {
             buffer.append(" WHERE ").append(condition);
         }
         String sql = buffer.toString();
         PreparedStatement existing = null;
         TableAppender mismatchs = null;
         try (Statement sourceStatement = source.createStatement();
              ResultSet sourceResultSet = sourceStatement.executeQuery(sql))
         {
             final ResultSetMetaData metadata = sourceResultSet.getMetaData();
             final String[] sourceColumns = new String[metadata.getColumnCount()];
             for (int i=0; i<sourceColumns.length;) {
                 sourceColumns[i] = metadata.getColumnName(++i);
             }
             log(SELECT, "insert", sql);
             /*
              * Gets the primary keys of the target table. We don't check for primary keys in the
              * source table since it may be a view. Then gets the index (counting from 1) in the
              * source table for those primary keys.
              */
             final String[] pkColumns = getPrimaryKeys(table);
             final int[] pkSourceIndex = new int[pkColumns.length];
             for (int i=0; i<pkColumns.length; i++) {
                 final String name = pkColumns[i];
                 if ((pkSourceIndex[i] = getColumnIndex(metadata, name)) == 0) {
                     throw new SQLException("Primary key \"" + name + "\" defined in the target \"" +
                             table + "\" table is not found in the source table.");
                 }
             }
             final int[] nonpkSourceIndex = new int[sourceColumns.length - pkSourceIndex.length];
             for (int i=0,j=0; i<sourceColumns.length;) {
                 if (!contains(pkSourceIndex, ++i)) {
                     nonpkSourceIndex[j++] = i;
                 }
             }
             assert !contains(nonpkSourceIndex, 0);
             /*
              * Creates the SQL statement for the SELECT or UPDATE query in the target database.
              * This is used in order to search for existing entries before to insert a new one.
              * This operation can be performed only if the target table contains at least one
              * primary key column.
              */
             final boolean update = nonpkSourceIndex.length != 0 && onExisting == Policy.INSERT_OR_UPDATE;
             final String quoteTarget = targetMetadata.getIdentifierQuoteString();
             if (pkColumns.length != 0 && onExisting != Policy.DELETE_BEFORE_INSERT) {
                 buffer.setLength(0);
                 appendTableName(buffer.append(update ? "UPDATE " : "SELECT * FROM "), targetSchema, table, quoteTarget);
                 if (update) {
                     buffer.append(" SET ");
                     boolean afterFirst = false;
                     for (int i=0; i<nonpkSourceIndex.length; i++) {
                         if (afterFirst) buffer.append(',');
                         else afterFirst = true;
                         final String name = sourceColumns[nonpkSourceIndex[i] - 1];
                         buffer.append(quoteTarget).append(name).append(quoteTarget).append("=?");
                     }
                 }
                 String separator = " WHERE ";
                 for (int i=0; i<pkColumns.length; i++) {
                     final String name = pkColumns[i];
                     buffer.append(separator).append(quoteTarget).append(name).append(quoteTarget).append("=?");
                     separator = " AND ";
                 }
                 sql = buffer.toString();
                 existing = target.prepareStatement(sql);
             }
             /*
              * Creates the target prepared statement for the INSERT queries. The parameters will
              * need to be filled in the same order than the column from the source SELECT query.
              */
             buffer.setLength(0);
             appendTableName(buffer.append("INSERT INTO "), targetSchema, table, quoteTarget);
             buffer.append(" (");
             for (int i=0; i<sourceColumns.length; i++) {
                 if (i != 0) buffer.append(',');
                 buffer.append(quoteTarget).append(sourceColumns[i]).append(quoteTarget);
             }
             buffer.append(") VALUES (");
             for (int i=0; i<sourceColumns.length; i++) {
                 if (i != 0) buffer.append(',');
                 buffer.append('?');
             }
             sql = buffer.append(')').toString();
             try (PreparedStatement insertStatement = target.prepareStatement(sql)) {
                 /*
                  * Reads all records from the source table and check if a corresponding records exists
                  * in the target table. If such record exists and have identical content, then nothing
                  * is done. If the content is not identical, then a warning is printed.
                  */
                 int[] sourceToTarget = null;
                 final Object[] primaryKeyValues = new Object[pkColumns.length];
                 while (sourceResultSet.next()) {
                     if (cancel) break;
                     if (existing != null) {
                         int param = 0;
                         if (update) {
                             for (int i=0; i<nonpkSourceIndex.length; i++) {
                                 final Object value = sourceResultSet.getObject(nonpkSourceIndex[i]);
                                 existing.setObject(++param, value);
                             }
                         }
                         for (int i=0; i<pkSourceIndex.length; i++) {
                             final Object value = sourceResultSet.getObject(pkSourceIndex[i]);
                             existing.setObject(++param, value);
                             primaryKeyValues[i] = value;
                         }
                         int count = 0;
                         if (update) {
                             count = existing.executeUpdate();
                         } else {
                             try (ResultSet targetResultSet = existing.executeQuery()) {
                                 if (sourceToTarget == null) {
                                     sourceToTarget = getColumnIndex(targetResultSet.getMetaData(), sourceColumns);
                                 }
                                 while (targetResultSet.next()) {
                                     for (int i=0; i<sourceToTarget.length; i++) {
                                         final int index = sourceToTarget[i];
                                         if (index == 0) {
                                             // Compares only the columns present in both tables.
                                             continue;
                                         }
                                         final String source = sourceResultSet.getString(i+1);
                                         final String target = targetResultSet.getString(index);
                                         if (!Objects.equals(source, target)) {
                                             if (mismatchs == null) {
                                                 mismatchs = createMismatchTable(table, pkColumns);
                                             } else {
                                                 mismatchs.nextLine();
                                             }
                                             for (int j=0; j<primaryKeyValues.length; j++) {
                                                 mismatchs.append(String.valueOf(primaryKeyValues[j]));
                                                 mismatchs.nextColumn();
                                             }
                                             mismatchs.append(sourceColumns[i]); mismatchs.nextColumn();
                                             mismatchs.append(source);           mismatchs.nextColumn();
                                             mismatchs.append(target);           mismatchs.nextLine();
                                         }
                                     }
                                     count++;
                                 }
                             }
                         }
                         if (count != 0) {
                             continue;
                         }
                     }
                     /*
                      * At this point, we know that we have a new element.
                      * Now insert the new record in the target table.
                      */
                     for (int i=1; i<=sourceColumns.length; i++) {
                         insertStatement.setObject(i, sourceResultSet.getObject(i));
                     }
                     final int count = pretend ? 1 : insertStatement.executeUpdate();
                     if (count == 1) {
                         log(UPDATE, "insert", insertStatement.toString());
                     } else {
                         log(Level.WARNING, "insert", count + " enregistrements ajoutés.");
                     }
                 }
             }
         } finally {
             if (existing != null) {
                 existing.close();
             }
         }
         if (mismatchs != null) {
             mismatchs.nextLine('\u2500');
             mismatchs.flush();
         }
     }
log()
static void log (final Level level, final String method, final String message) static private
Writes an event to the logger.
Referenced by Synchronizer.delete(), and Synchronizer.insert().
{
         final LogRecord record = new LogRecord(level, message);
         record.setSourceClassName(Synchronizer.class.getName());
         record.setSourceMethodName(method);
         Logging.getLogger("org.geotoolkit.sql").log(record);
     }
Member Data Documentation
cancel
volatile boolean cancel
Sets to.
true
for canceling the operation.
out
final Writer out private
Where to print reports.
Referenced by Synchronizer.Synchronizer().
pretend
boolean pretend private
If.
true
, no changes will be applied to the database. The
DELETE
and
INSERT
statements will not be executed. This is useful for testing purpose, or for getting the reports or log record without performing the action.
SELECT
final Level SELECT = Level.FINE static private
Logging level to use for SQL operations.
source
final Connection source private
The connection to the source and target databases.
Referenced by Synchronizer.Synchronizer().
sourceCatalog
String sourceCatalog
The source and target catalogs, or.
null
if none.
sourceMetadata
transient DatabaseMetaData sourceMetadata private
The metadata for the source and target databases.
Will be fetched when first needed.
sourceSchema
String sourceSchema
The source and target schemas, or.
null
if none.
target
final Connection target package
Referenced by Synchronizer.Synchronizer().
targetCatalog
String targetCatalog package
Referenced by Synchronizer.copy(), and Synchronizer.getPrimaryKeys().
targetMetadata
transient DatabaseMetaData targetMetadata package
targetSchema
String targetSchema package
Referenced by Synchronizer.copy(), Synchronizer.getPrimaryKeys(), and Synchronizer.insert().
UPDATE
final Level UPDATE = Level.FINE static package
Referenced by Synchronizer.delete(), and Synchronizer.insert().