jena-geo: IGNF Class Reference
IGNF Class Reference
The IGNF authority factory.
Public Member Functions
IGNF ()
Creates a new authority factory.
Citation getAuthority ()
Returns the IGNF authority.
Set< String > getAuthorityCodes (Class<? extends IdentifiedObject > type)
Returns the list of supported codes.
InternationalString getDescriptionText (String code) throws FactoryException
Returns the CRS name for the given code.
IdentifiedObject createObject (final String code) throws FactoryException
Creates an object from the specified code.
synchronized CoordinateReferenceSystem createCoordinateReferenceSystem (final String code) throws FactoryException
Creates a coordinate reference system from the specified code.
Citation getVendor ()
Returns the vendor responsible for creating this factory implementation.
String getBackingStoreDescription () throws FactoryException
Returns a description of the underlying backing store, or.
Static Public Attributes
static final Logger LOGGER = Logging.getLogger("org.geotoolkit.referencing.factory")
The logger for event related to Geotk factories.
Protected Member Functions
void dispose (final boolean shutdown)
Releases resources immediately instead of waiting for the garbage collector.
String trimAuthority (String code)
Trims the authority scope, if presents.
final NoSuchAuthorityCodeException noSuchAuthorityCode (final Class<?> type, final String code)
Creates an exception for an unknown authority code.
Static Protected Member Functions
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException
Makes sure that an argument is non-null.
Protected Attributes
final NameFactory nameFactory
The name factory to use for creating GenericName.
final ReferencingFactoryContainer factories
The underlying factories used for objects creation.
Static Package Functions
[static initializer]
Private Attributes
final Map< String, Object > crsMap = new TreeMap<>()
The map of pre-defined CRS.
final Set< String > codes
The authority codes, as an unmodifiable view over the keys in the crsMap.
Static Private Attributes
static final Citation AUTHORITY
Detailed Description
The IGNF authority factory.
Author
Martin Desruisseaux (Geomatys)
Version
3.20
Since
3.14
Constructor & Destructor Documentation
IGNF()
IGNF ()
Creates a new authority factory.
                   {
         crsMap.put("MILLER", "Miller_Cylindrical");
         codes = Collections.unmodifiableSet(crsMap.keySet());
     }
Member Function Documentation
[static initializer]()
[static initializer] () static package
createCoordinateReferenceSystem()
synchronized CoordinateReferenceSystem createCoordinateReferenceSystem (final String code) throws FactoryException
Creates a coordinate reference system from the specified code.
Exceptions
FactoryException if the object creation failed.
References DirectAuthorityFactory.factories, ReferencingFactoryContainer.getCRSFactory(), ReferencingFactoryContainer.getMathTransformFactory(), DirectAuthorityFactory.noSuchAuthorityCode(), PredefinedCS.PROJECTED, and DirectAuthorityFactory.trimAuthority().
Referenced by IGNF.createObject().
     {
         final String key = trimAuthority(code).toUpperCase();
         final Object value = crsMap.get(key);
         if (value == null) {
             throw noSuchAuthorityCode(CoordinateReferenceSystem.class, code);
         }
         if (value instanceof CoordinateReferenceSystem) {
             return (CoordinateReferenceSystem) value;
         }
         /*
          * Following code is currently for IGNF:MILLER only.
          */
         // Creates the datum
         final Map<String,Object> properties = new HashMap<>(4);
         properties.put(DefaultGeodeticDatum.NAME_KEY, new NamedIdentifier(Citations.OGC, "GRS80"));
         final DefaultGeodeticDatum datum = new DefaultGeodeticDatum(properties,
                 CommonCRS.ETRS89.ellipsoid(), CommonCRS.ETRS89.primeMeridian());
         // Creates the projection.
         final ParameterValueGroup param = factories.getMathTransformFactory().getDefaultParameters((String) value);
         param.parameter("semi_major").setValue(6378137);
         param.parameter("semi_minor").setValue(6378137);
         final Identifier[] identifiers = {
             new NamedIdentifier(AUTHORITY, "MILLER"),
             new ImmutableIdentifier(Citations.EPSG, "EPSG", "310642901"), // Unofficial
             new ImmutableIdentifier(Citations.EPSG, "EPSG", "54003") // Unofficial
         };
         properties.clear();
         properties.put(ProjectedCRS.NAME_KEY, identifiers[0]);
         properties.put(ProjectedCRS.IDENTIFIERS_KEY, identifiers);
         final ProjectedCRS crs = factories.getCRSFactory().createProjectedCRS(properties,
                 new DefaultGeographicCRS(IdentifiedObjects.getProperties(datum), datum, CommonCRS.defaultGeographic().getCoordinateSystem()),
                 new DefiningConversion("Miller", param), PredefinedCS.PROJECTED);
         crsMap.put(key, crs);
         return crs;
     }
createObject()
IdentifiedObject createObject (final String code) throws FactoryException
Creates an object from the specified code.
The default implementation delegates to createCoordinateReferenceSystem createCoordinateReferenceSystem}(code).
Exceptions
FactoryException if the object creation failed.
References IGNF.createCoordinateReferenceSystem().
Referenced by IGNF.getDescriptionText().
{
         return createCoordinateReferenceSystem(code);
     }
dispose()
void dispose (final boolean shutdown) protected inherited
Releases resources immediately instead of waiting for the garbage collector.
Once a factory has been disposed, further
create(...)
invocations may throw a FactoryException. Disposing a previously-disposed factory, however, has no effect.
{
         // To be overridden by subclasses.
     }
ensureNonNull()
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException static protected inherited
Makes sure that an argument is non-null.
This is a convenience method for subclass methods.
Parameters
name Argument name.
object User argument.
Exceptions
InvalidParameterValueException if
object
is null.
References Errors.format(), and Errors.Keys.NullArgument_1.
Referenced by DirectAuthorityFactory.DirectAuthorityFactory(), DirectPostgisFactory.getPrimaryKey(), WKTParsingAuthorityFactory.getWKT(), PropertyAuthorityFactory.load(), and WKTParsingAuthorityFactory.WKTParsingAuthorityFactory().
     {
         if (object == null) {
             throw new InvalidParameterValueException(Errors.format(
                     Errors.Keys.NullArgument_1, name), name, object);
         }
     }
getAuthority()
Citation getAuthority ()
Returns the IGNF authority.
References IGNF.AUTHORITY.
{
         return AUTHORITY;
     }
getAuthorityCodes()
Set<String> getAuthorityCodes (Class<? extends IdentifiedObject > type)
Returns the list of supported codes.
References IGNF.codes.
{
         return type.isAssignableFrom(ProjectedCRS.class) ? codes : Collections.<String>emptySet();
     }
getBackingStoreDescription()
String getBackingStoreDescription () throws FactoryException inherited
Returns a description of the underlying backing store, or.
null
if unknown. This is for example the database software used for storing the data. The default implementation returns always
null
.
Returns
The description of the underlying backing store, or
null
.
Exceptions
FactoryException if a failure occurs while fetching the engine description.
{
         return null;
     }
getDescriptionText()
InternationalString getDescriptionText (String code) throws FactoryException
Returns the CRS name for the given code.
References IGNF.createObject().
{
         return new SimpleInternationalString(createObject(code).getName().getCode());
     }
getVendor()
Citation getVendor () inherited
Returns the vendor responsible for creating this factory implementation.
Many implementations from different vendors may be available for the same factory interface.
The default for Geotk implementations is to return Citations::GEOTOOLKIT Geotoolkit.org}.
Returns
The vendor for this factory implementation.
See also
Citations::GEOTOOLKIT
References DirectAuthorityFactory.getAuthority().
{
         return new SimpleCitation(getClass().getName().startsWith("org.geotoolkit.") ? "Geotk" : "Unknown");
     }
noSuchAuthorityCode()
final NoSuchAuthorityCodeException noSuchAuthorityCode (final Class<?> type, final String code) protected inherited
Creates an exception for an unknown authority code.
This convenience method is provided for implementation of
createXXX
methods.
Parameters
type The GeoAPI interface that was to be created (e.g.
CoordinateReferenceSystem.class
).
code The unknown authority code.
Returns
An exception initialized with an error message built from the specified informations.
References Errors.format(), DirectAuthorityFactory.getAuthority(), Errors.Keys.NoSuchAuthorityCode_3, and DirectAuthorityFactory.trimAuthority().
Referenced by IGNF.createCoordinateReferenceSystem(), DirectPostgisFactory.getPrimaryKey(), and WKTParsingAuthorityFactory.getWKT().
{
         final InternationalString authority = getAuthority().getTitle();
         return new NoSuchAuthorityCodeException(Errors.format(Errors.Keys.NoSuchAuthorityCode_3,
                    code, authority, type), authority.toString(), trimAuthority(code), code);
     }
trimAuthority()
String trimAuthority (String code) protected inherited
Trims the authority scope, if presents.
For example if this factory is an EPSG authority factory and the specified code start with the
"EPSG:"
prefix, then the prefix is removed. Otherwise, the string is returned unchanged (except for leading and trailing spaces).
Parameters
code The code to trim.
Returns
The code without the authority scope.
Referenced by IGNF.createCoordinateReferenceSystem(), and DirectAuthorityFactory.noSuchAuthorityCode().
{
         /*
          * IMPLEMENTATION NOTE: This method is overridden in PropertyAuthorityFactory. If
          * implementation below is modified, it is probably worth to revisit the overridden
          * method as well.
          */
         code = code.trim();
         final GenericName name  = nameFactory.parseGenericName(null, code);
         if (name instanceof ScopedName) {
             final GenericName scope = ((ScopedName) name).path();
             if (Citations.identifierMatches(getAuthority(), scope.toString())) {
                 return name.tip().toString().trim();
             }
         }
         return code;
     }
Member Data Documentation
AUTHORITY
final Citation AUTHORITY static private
Referenced by IGNF.getAuthority().
codes
final Set<String> codes private
The authority codes, as an unmodifiable view over the keys in the crsMap.
Referenced by IGNF.getAuthorityCodes().
crsMap
final Map<String,Object> crsMap = new TreeMap<>() private
The map of pre-defined CRS.
Will be created when first needed. Keys are IGNF codes. Values are initially projection names, to be replaced by the actual CRS when first created.
factories
final ReferencingFactoryContainer factories protected inherited
The underlying factories used for objects creation.
Referenced by IGNF.createCoordinateReferenceSystem(), and DirectAuthorityFactory.DirectAuthorityFactory().
LOGGER
final Logger LOGGER = Logging.getLogger("org.geotoolkit.referencing.factory") static inherited
The logger for event related to Geotk factories.
Referenced by DirectPostgisFactory.getAuthorities(), PropertyAuthorityFactory.log(), and PropertyAuthorityFactory.PropertyAuthorityFactory().
nameFactory
final NameFactory nameFactory protected inherited
The name factory to use for creating GenericName.
Since
3.00
Referenced by WKTParsingAuthorityFactory.trimAuthority().