jena-geo: Registry Class Reference
Registry Class Reference
A set of static methods for managing JAI's OperationRegistry operation registry}.
Static Public Member Functions
static boolean registerGeotoolkitServices (final OperationRegistry registry)
Unconditionally registers all JAI operations provided in the org.geotoolkit.image.jai package.
static synchronized void setNativeAccelerationAllowed (final String operation, final boolean allowed, final JAI jai)
Allows or disallows native acceleration for the specified operation on the given JAI instance.
static void setNativeAccelerationAllowed (final String operation, final boolean allowed)
Allows or disallows native acceleration for the specified operation on the JAI::getDefaultInstance default JAI instance}.
static synchronized< T extends ImageReaderWriterSpi > void setNativeCodecAllowed (final String format, final Class< T > category, final boolean allowed)
Allows or disallows native acceleration for the specified image format.
static synchronized void setDefaultCodecPreferences ()
Sets the default preferred order for JAI and Java standard codec.
Private Member Functions
Registry ()
Do not allows instantiation of this class.
Static Private Member Functions
static void log (final String method, final LogRecord record)
Logs the specified record.
Detailed Description
A set of static methods for managing JAI's OperationRegistry operation registry}.
Also provides convenience methods for setting the preferred order between standard and JAI javax.imageio.ImageReader/javax.imageio.ImageWriter.
Author
Martin Desruisseaux (IRD, Geomatys)
Version
3.00
Since
2.2
Constructor & Destructor Documentation
Registry()
Registry () private
Do not allows instantiation of this class.
{
     }
Member Function Documentation
log()
static void log (final String method, final LogRecord record) static private
Logs the specified record.
Referenced by Registry.registerGeotoolkitServices(), Registry.setNativeAccelerationAllowed(), and Registry.setNativeCodecAllowed().
{
         record.setSourceClassName(Registry.class.getName());
         record.setSourceMethodName(method);
         final Logger logger = Logging.getLogger("org.geotoolkit.image.jai");
         record.setLoggerName(logger.getName());
         logger.log(record);
     }
registerGeotoolkitServices()
static boolean registerGeotoolkitServices (final OperationRegistry registry) static
Unconditionally registers all JAI operations provided in the org.geotoolkit.image.jai package.
This method usually don't need to be invoked, since JAI should parse automatically the
META-INF/registryFile.jai
file at startup time. However, this default mechanism may fail when the Geotk JAR file is unreachable from the JAI class loader, in which case the org.geotoolkit.coverage.processing package will invoke this method as a fallback.
Note to module maintainer: if this method is updated, remember to update the
META-INF/registryFile.jai
file accordingly.
Parameters
registry The operation registry to register with.
Returns
true
if all registrations have been successful.
References Loggings.Keys.CantRegisterJaiOperation_1, Loggings.format(), Loggings.getResources(), Registry.log(), NodataFilter.OPERATION_NAME, Hysteresis.OPERATION_NAME, SilhouetteMask.OPERATION_NAME, Combine.OPERATION_NAME, and Loggings.Keys.RegisteredJaiOperations.
Referenced by Setup.initialize().
{
         LogRecord record;
         String op = PRODUCT_NAME;
         try {
             op = Combine.OPERATION_NAME;
             registry.registerDescriptor(new CombineDescriptor());
             RIFRegistry.register(registry, op, PRODUCT_NAME, new CombineCRIF());
             op = Hysteresis.OPERATION_NAME;
             registry.registerDescriptor(new HysteresisDescriptor());
             RIFRegistry.register(registry, op, PRODUCT_NAME, new HysteresisCRIF());
             op = NodataFilter.OPERATION_NAME;
             registry.registerDescriptor(new NodataFilterDescriptor());
             RIFRegistry.register(registry, op, PRODUCT_NAME, new NodataFilterCRIF());
             op = SilhouetteMask.OPERATION_NAME;
             registry.registerDescriptor(new SilhouetteMaskDescriptor());
             RIFRegistry.register(registry, op, PRODUCT_NAME, new SilhouetteMaskCRIF());
             record  = Loggings.format(Level.CONFIG, Loggings.Keys.RegisteredJaiOperations);
             op = null;
         } catch (IllegalArgumentException exception) {
             /*
              * Logs a message with the WARNING level, because DefaultProcessing class initialization
              * is likely to fails (since it tries to load operations declared in META-INF/services,
              * and some of them depend on JAI operations).
              */
             record = Loggings.getResources(null).getLogRecord(Level.WARNING,
                     Loggings.Keys.CantRegisterJaiOperation_1, op);
             record.setThrown(exception);
         }
         log("registerGeotoolkitServices", record);
         return op == null;
     }
setDefaultCodecPreferences()
static synchronized void setDefaultCodecPreferences () static
Sets the default preferred order for JAI and Java standard codec.
This method invokes setNativeCodecAllowed for some well-known formats.
TIP: Experience suggests that on some platforms, new codecs appear magically after an AWT window has been created (e.g. "Standard TIFF image reader"). If this method is to be invoked for a graphical application, it is recommended to invoke this method after the java.awt.Window} has been created but before it is made visible.
See also
org.geotoolkit.image.io
org.geotoolkit.lang.Setup
Since
3.00
References Registry.setNativeCodecAllowed().
Referenced by Setup.initialize().
{
         /*
          * NOTE: If the rules below are modified, then the rules in
          *       the following method shall be modified accordingly:
          *
          * org.geotoolkit.internal.image.io.Formats.getReaderByFormatName(String)
          */
         setNativeCodecAllowed("GIF",   ImageReaderSpi.class, false);
         setNativeCodecAllowed("GIF",   ImageWriterSpi.class, false);
         setNativeCodecAllowed("PNG",   ImageReaderSpi.class, false);
         setNativeCodecAllowed("PNG",   ImageWriterSpi.class, false);
         setNativeCodecAllowed("BMP",   ImageReaderSpi.class, false);
         setNativeCodecAllowed("BMP",   ImageWriterSpi.class, false);
         setNativeCodecAllowed("WBMP",  ImageReaderSpi.class, false);
         setNativeCodecAllowed("WBMP",  ImageWriterSpi.class, false);
         setNativeCodecAllowed("JPEG",  ImageReaderSpi.class, false);
         setNativeCodecAllowed("JPEG",  ImageWriterSpi.class, false);
         setNativeCodecAllowed("TIFF",  ImageReaderSpi.class, true);
         setNativeCodecAllowed("TIFF",  ImageWriterSpi.class, true);
     }
setNativeAccelerationAllowed() [1/2]
static synchronized void setNativeAccelerationAllowed (final String operation, final boolean allowed, final JAI jai) static
Allows or disallows native acceleration for the specified operation on the given JAI instance.
By default, JAI uses hardware accelerated methods when available. For example, it makes use of MMX instructions on Intel processors. Unfortunately, some native methods crash the Java Virtual Machine under some circumstances. For example on JAI 1.1.2, the
"Affine"
operation on an image with float data type, bilinear interpolation and an javax.media.jai.ImageLayout rendering hint cause an exception in medialib native code. Disabling the native acceleration (i.e using the pure Java version) is a convenient workaround until Sun fix the bug.
{
Note
The current implementation assumes that factories for native implementations are declared in the com.sun.media.jai.mlib package, while factories for pure Java implementations are declared in the com.sun.media.jai.opimage package. It works for Sun's 1.1.2 implementation, but may change in future versions. If this method doesn't recognize the package, it does nothing.}
Parameters
operation The operation name (e.g.
"Affine"
).
allowed
References Loggings.format(), Registry.log(), and Loggings.Keys.NativeAccelerationState_2.
Referenced by Registry.setNativeAccelerationAllowed().
     {
         final String product = "com.sun.media.jai";
         final OperationRegistry registry = jai.getOperationRegistry();
         @SuppressWarnings("unchecked")
         final List<RenderedImageFactory> factories = registry.getOrderedFactoryList(
                 RenderedRegistryMode.MODE_NAME, operation, product);
         if (factories != null) {
             RenderedImageFactory   javaFactory = null;
             RenderedImageFactory nativeFactory = null;
             Boolean               currentState = null;
             for (final RenderedImageFactory factory : factories) {
                 final String pack = factory.getClass().getPackage().getName();
                 if (pack.equals("com.sun.media.jai.mlib")) {
                     nativeFactory = factory;
                     if (javaFactory != null) {
                         currentState = Boolean.FALSE;
                     }
                 }
                 if (pack.equals("com.sun.media.jai.opimage")) {
                     javaFactory = factory;
                     if (nativeFactory != null) {
                         currentState = Boolean.TRUE;
                     }
                 }
             }
             if (currentState != null && currentState.booleanValue() != allowed) {
                 RIFRegistry.unsetPreference(registry, operation, product,
                         allowed ? javaFactory : nativeFactory,
                         allowed ? nativeFactory : javaFactory);
                 RIFRegistry.setPreference(registry, operation, product,
                         allowed ? nativeFactory : javaFactory,
                         allowed ? javaFactory : nativeFactory);
                 final LogRecord record = Loggings.format(Level.CONFIG,
                         Loggings.Keys.NativeAccelerationState_2,
                         operation, Integer.valueOf(allowed ? 1 : 0));
                 log("setNativeAccelerationAllowed", record);
             }
         }
     }
setNativeAccelerationAllowed() [2/2]
static void setNativeAccelerationAllowed (final String operation, final boolean allowed) static
Allows or disallows native acceleration for the specified operation on the JAI::getDefaultInstance default JAI instance}.
This method is a shortcut for setNativeAccelerationAllowed(String,boolean,JAI) setNativeAccelerationAllowed}(operation, allowed, JAI.getDefaultInstance()).
Parameters
operation The operation name (e.g.
"Affine"
).
allowed
References Registry.setNativeAccelerationAllowed().
{
         setNativeAccelerationAllowed(operation, allowed, JAI.getDefaultInstance());
     }
setNativeCodecAllowed()
static synchronized<T extends ImageReaderWriterSpi> void setNativeCodecAllowed (final String format, final Class< T > category, final boolean allowed) static
Allows or disallows native acceleration for the specified image format.
By default, the image I/O extension for JAI provides native acceleration for PNG and JPEG. Unfortunately, those native codecs have bug in their 1.0 version. Invoking this method will force the use of standard codecs provided in J2SE 1.4.
{
Note
The current implementation assumes that JAI codec class name start with "com.sun.media" package name. It works for JAI Image I/O 1.1 implementation, but may change in future versions. If this method doesn't recognize the class name, then it does nothing.}
Parameters
<T> The category (
ImageReaderSpi
or
ImageWriterSpi
).
format The format name (e.g.
"png"
).
category
References Loggings.format(), Registry.log(), and Loggings.Keys.NativeCodecState_3.
Referenced by Registry.setDefaultCodecPreferences().
     {
         T standard = null;
         T codeclib = null;
         final ServiceRegistry registry = IIORegistry.getDefaultInstance();
         for (final Iterator<T> it = registry.getServiceProviders(category, false); it.hasNext();) {
             final T provider = it.next();
             final String[] formats = provider.getFormatNames();
             for (int i=0; i<formats.length; i++) {
                 if (formats[i].equalsIgnoreCase(format)) {
                     /*
                      * NOTE: The following method uses the same rule for identifying JAI codecs.
                      *       If we change the way to identify those codecs here, we should do the
                      *       same for the other method.
                      *
                      * org.geotoolkit.internal.image.io.Formats.getReaderByFormatName(String)
                      */
                     final String classname = provider.getClass().getName();
                     if (classname.startsWith("com.sun.media.")) {
                         codeclib = provider;
                         break;
                     }
                     if (classname.startsWith("com.sun.imageio.")) {
                         standard = provider;
                         break;
                     }
                 }
             }
         }
         if (standard != null && codeclib != null) {
             final boolean changed;
             if (allowed) {
                 changed = registry.setOrdering(category, codeclib, standard);
             } else {
                 changed = registry.setOrdering(category, standard, codeclib);
             }
             if (changed) {
                 final LogRecord record = Loggings.format(Level.CONFIG,
                         Loggings.Keys.NativeCodecState_3,
                         format, Integer.valueOf(allowed ? 1 : 0),
                         Integer.valueOf(ImageWriterSpi.class.isAssignableFrom(category) ? 1 : 0));
                 log("setNativeCodecAllowed", record);
             }
         }
     }