jena-geo: IndexedPalette Class Reference
IndexedPalette Class Reference
A set of RGB colors created by a PaletteFactory palette factory} from a name.
Public Member Functions
int hashCode ()
Returns a hash value for this palette.
boolean equals (final Object object)
Compares this palette with the specified object for equality.
String toString ()
Returns a string representation of this palette.
synchronized ColorModel getColorModel () throws FileNotFoundException, IOException
Returns the color model for this palette.
synchronized ImageTypeSpecifier getImageTypeSpecifier () throws FileNotFoundException, IOException
Returns the image type specifier for this palette.
RenderedImage getImage (final Dimension size) throws IOException
Returns the color palette as an image of the specified size.
RenderedImage getLegend (final Dimension size) throws IOException
Returns the color palette as a smoothed image of the specified size, together with the palette name.
Static Public Member Functions
static boolean isGrayPalette (final int[] ARGB)
Tells if the given ARGB array contains only opaque gray colors, with values matching the index value.
Static Public Attributes
static final int MAX_UNSIGNED = 0xFFFF
The maximal allowed value, corresponding to the maximum value for unsigned 16 bits integer.
Protected Member Functions
IndexedPalette (final PaletteFactory factory, final String name, final int lower, final int upper, int size, final int numBands, final int visibleBand)
Creates a palette with the specified name and size.
ImageTypeSpecifier createImageTypeSpecifier () throws IOException
Creates the image type specifier for this palette.
Protected Attributes
final int lower
Index of the first valid element (inclusive) in the IndexColorModel index color model} to be created.
final int upper
Index of the last valid element (exclusive) in the IndexColorModel index color model} to be created.
final int size
The size of the IndexColorModel index color model} to be created.
final String name
The name of this palette.
final int numBands
The number of bands in the ColorModel color model}.
final int visibleBand
The band to display, in the range 0 inclusive to numBands exclusive.
Package Functions
final double getScale ()
Returns the scale from <cite>normalized values</cite> (values in the range [0..1]) to values in the range of this palette.
final double getOffset ()
Returns the offset from <cite>normalized values</cite> (values in the range [0..1]) to values in the range of this palette.
final void ensureInsideBounds (final int value, final int min, final int max) throws IllegalArgumentException
Ensures that the specified values in inside the expected bounds (inclusives).
Package Attributes
final PaletteFactory factory
The originating factory.
Private Member Functions
int [] createARGB () throws IOException
Creates and returns ARGB values for the IndexColorModel index color model} to be created.
Detailed Description
A set of RGB colors created by a PaletteFactory palette factory} from a name.
A palette can creates an IndexColorModel index color model} or an ImageTypeSpecifier image type specifier} from the RGB colors.
Author
Antoine Hnawia (IRD)
Martin Desruisseaux (IRD, Geomatys)
Version
3.11
Since
3.11 (derived from 2.4)
Constructor & Destructor Documentation
IndexedPalette()
IndexedPalette (final PaletteFactory factory, final String name, final int lower, final int upper, int size, final int numBands, final int visibleBand) protected
Creates a palette with the specified name and size.
The RGB colors will be distributed in the range
lower
inclusive to
upper
exclusive. Remaining pixel values (if any) will be left to a black or transparent color by default.
Parameters
factory The originating factory.
name The palette name.
lower Index of the first valid element (inclusive) in the IndexColorModel index color model} to be created.
upper Index of the last valid element (exclusive) in the IndexColorModel index color model} to be created.
size The size of the IndexColorModel index color model} to be created. This is the value to be returned by IndexColorModel#getMapSize().
numBands The number of bands (usually 1).
visibleBand The band to use for color computations (usually 0).
References Palette.ensureInsideBounds(), PaletteFactory.getErrorResources(), Errors.Keys.IllegalRange_2, IndexedPalette.lower, IndexedPalette.MAX_UNSIGNED, IndexedPalette.size, and IndexedPalette.upper.
Referenced by IndexedPalette.equals().
     {
         super(factory, name, numBands, visibleBand);
         final int minAllowed, maxAllowed; // inclusives
         if (lower < 0) {
             minAllowed = Short.MIN_VALUE;
             maxAllowed = Short.MAX_VALUE;
             size       = (size <= 0x100) ? 0x100 : (MAX_UNSIGNED + 1);
             // 'size-1' must be FF or FFFF in order to rool negative values.
         } else {
             minAllowed = 0;
             maxAllowed = MAX_UNSIGNED;
         }
         ensureInsideBounds(lower, minAllowed, maxAllowed);
         ensureInsideBounds(upper, minAllowed, maxAllowed + 1);
         ensureInsideBounds(size,  upper,      MAX_UNSIGNED + 1);
         if (lower >= upper) {
             throw new IllegalArgumentException(factory.getErrorResources().getString(
                     Errors.Keys.IllegalRange_2, lower, upper));
         }
         this.lower = lower;
         this.upper = upper;
         this.size  = size;
     }
Member Function Documentation
createARGB()
int [] createARGB () throws IOException private
Creates and returns ARGB values for the IndexColorModel index color model} to be created.
This method is invoked automatically the first time the color model is required, or when it need to be rebuilt.
Exceptions
FileNotFoundException If the RGB values need to be read from a file and this file (typically inferred from name) is not found.
IOException If an other find of I/O error occurred.
IIOException If an other kind of error prevent this method to complete.
References Palette.colors, ColorUtilities.expand(), Palette.factory, Errors.Keys.FileDoesNotExist_1, PaletteFactory.getColors(), PaletteFactory.getErrorResources(), IndexedPalette.lower, Palette.name, and IndexedPalette.size.
Referenced by IndexedPalette.createImageTypeSpecifier().
{
         final Color[] colors = factory.getColors(name);
         if (colors == null) {
             throw new FileNotFoundException(factory.getErrorResources().getString(
                     Errors.Keys.FileDoesNotExist_1, name));
         }
         final int[] ARGB = new int[size];
         if (lower >= 0) {
             ColorUtilities.expand(colors, ARGB, lower, upper);
         } else {
             ColorUtilities.expand(colors, ARGB, 0, upper - lower);
             final int negativeStart = size + lower;
             final int negativeCount = -lower;
             final int[] negatives = new int[negativeCount];
             System.arraycopy(ARGB, 0, negatives, 0, negativeCount);
             System.arraycopy(ARGB, negativeCount, ARGB, 0, negativeStart);
             System.arraycopy(negatives, 0, ARGB, negativeStart, negativeCount);
         }
         return ARGB;
     }
createImageTypeSpecifier()
ImageTypeSpecifier createImageTypeSpecifier () throws IOException protected
Creates the image type specifier for this palette.
This method tries to reuse existing color model if possible, since it may consume a significant amount of memory.
Exceptions
IOException If the RGB values can not be read from the file.
References IndexedPalette.createARGB(), IndexedPalette.isGrayPalette(), Palette.numBands, and Palette.visibleBand.
{
         final int[] ARGB = createARGB();
         final int bits = ColorModelFactory.getBitCount(ARGB.length);
         final int type = (bits <= 8) ? DataBuffer.TYPE_BYTE : DataBuffer.TYPE_USHORT;
         final boolean packed = (bits==1 || bits==2 || bits==4);
         final boolean dense  = (packed || bits==8 || bits==16);
         final boolean isGray = isGrayPalette(ARGB);
         if (!isGray && dense && (1 << bits) == ARGB.length && numBands == 1) {
             final byte[] A = new byte[ARGB.length];
             final byte[] R = new byte[ARGB.length];
             final byte[] G = new byte[ARGB.length];
             final byte[] B = new byte[ARGB.length];
             for (int i=0; i<ARGB.length; i++) {
                 int code = ARGB[i];
                 B[i] = (byte) ((code       ) & 0xFF);
                 G[i] = (byte) ((code >>>= 8) & 0xFF);
                 R[i] = (byte) ((code >>>= 8) & 0xFF);
                 A[i] = (byte) ((code >>>= 8) & 0xFF);
             }
             return ImageTypeSpecifier.createIndexed(R,G,B,A, bits, type);
         }
         /*
          * The "ImageTypeSpecifier.createIndexed(...)" method is too strict. The IndexColorModel
          * constructor is more flexible. This block mimic the "ImageTypeSpecifier.createIndexed"
          * work without the constraints imposed by "createIndexed". Being more flexible consume
          * less memory for the color palette, since we don't force it to be 64 kb in the USHORT
          * data type case.
          */
         final ColorModel cm;
         final SampleModel sm;
         if (isGray) {
             final ColorSpace cs = ColorSpace.getInstance(ColorSpace.CS_GRAY);
             cm = new ComponentColorModel(cs, new int[] {bits}, false, true, ColorModel.OPAQUE, type);
             sm = cm.createCompatibleSampleModel(1, 1);
         } else {
             cm = ColorModelFactory.createIndexColorModel(ARGB, numBands, visibleBand, -1);
             if (packed && numBands == 1) {
                 sm = new MultiPixelPackedSampleModel(type, 1, 1, bits);
             } else {
                 final int[] bandOffsets = new int[numBands];
                 for (int i=1; i<bandOffsets.length; i++) {
                     bandOffsets[i] = i;
                 }
                 sm = new PixelInterleavedSampleModel(type, 1, 1, numBands, numBands, bandOffsets);
             }
         }
         return new ImageTypeSpecifier(cm, sm);
     }
ensureInsideBounds()
final void ensureInsideBounds (final int value, final int min, final int max) throws IllegalArgumentException package inherited
Ensures that the specified values in inside the expected bounds (inclusives).
Exceptions
IllegalArgumentException if the specified values are outside the bounds.
References PaletteFactory.getErrorResources(), and Errors.Keys.ValueOutOfBounds_3.
Referenced by IndexedPalette.IndexedPalette(), and Palette.Palette().
     {
         if (value < min || value > max) {
             throw new IllegalArgumentException(factory.getErrorResources().getString(
                     Errors.Keys.ValueOutOfBounds_3, value, min, max));
         }
     }
equals()
boolean equals (final Object object)
Compares this palette with the specified object for equality.
References IndexedPalette.IndexedPalette(), IndexedPalette.lower, IndexedPalette.size, and IndexedPalette.upper.
{
         if (object == this) {
             return true;
         }
         if (super.equals(object)) {
             final IndexedPalette that = (IndexedPalette) object;
             return this.lower == that.lower &&
                    this.upper == that.upper &&
                    this.size  == that.size;
         }
         return false;
     }
getColorModel()
synchronized ColorModel getColorModel () throws FileNotFoundException, IOException inherited
Returns the color model for this palette.
This method tries to reuse existing color model if possible, since it may consume a significant amount of memory.
Returns
The color model for this palette.
Exceptions
FileNotFoundException If the RGB values need to be read from a file and this file (typically inferred from name) is not found.
IOException If an other kind of I/O error occurred.
References Palette.getImageTypeSpecifier().
Referenced by Palette.getImage().
{
         if (colors != null) {
             final ColorModel candidate = colors.get();
             if (candidate != null) {
                 return candidate;
             }
         }
         return getImageTypeSpecifier().getColorModel();
     }
getImage()
RenderedImage getImage (final Dimension size) throws IOException inherited
Returns the color palette as an image of the specified size.
This is useful for looking visually at a color palette.
This method uses the color model created by getColorModel() and does not write any text in the image. Consequently the colors in the returned image should be identical to the colors of the data rendered using this
Palette
.
Parameters
size The image size. The palette will be vertical if size. Dimension::height height} > size. Dimension::width width }
Returns
The color palette as an image of the given size.
Exceptions
IOException if the color values can't be read.
References Palette.getColorModel(), Palette.getOffset(), and Palette.getScale().
{
         final IndexColorModel colors = (IndexColorModel) getColorModel();
         final WritableRaster  raster = colors.createCompatibleWritableRaster(size.width, size.height);
         final BufferedImage   image  = new BufferedImage(colors, raster, false, null);
         int xmin   = raster.getMinX();
         int ymin   = raster.getMinY();
         int width  = raster.getWidth();
         int height = raster.getHeight();
         final boolean horizontal = size.width >= size.height;
         // Computation will be performed as if the image were horizontal.
         // If it is not, interchanges x and y values.
         if (!horizontal) {
             int tmp;
             tmp = xmin;  xmin  = ymin;   ymin   = tmp;
             tmp = width; width = height; height = tmp;
         }
         final int xmax = xmin + width;
         final int ymax = ymin + height;
         final double scale  = getScale() / width;
         final double offset = getOffset();
         for (int x=xmin; x<xmax; x++) {
             final double value = offset + scale*(x-xmin);
             for (int y=ymin; y<ymax; y++) {
                 if (horizontal) {
                     raster.setSample(x, y, 0, value);
                 } else {
                     raster.setSample(y, x, 0, value);
                 }
             }
         }
         return image;
     }
getImageTypeSpecifier()
synchronized ImageTypeSpecifier getImageTypeSpecifier () throws FileNotFoundException, IOException inherited
Returns the image type specifier for this palette.
The default implementation first check if the specified still in the cache. If not, then the createImageTypeSpecifier() method is invoked and its result is stored in the cache for future reuse.
Returns
The image type specified for this palette.
Exceptions
FileNotFoundException If the RGB values need to be read from a file and this file (typically inferred from name) is not found.
IOException If an other kind of I/O error occurred.
References Palette.createImageTypeSpecifier().
Referenced by Palette.getColorModel().
{
         if (specifier != null) {
             final ImageTypeSpecifier candidate = specifier.get();
             if (candidate != null) {
                 return candidate;
             }
         }
         if (samples != null && colors != null) {
             final ColorModel candidate = colors.get();
             if (candidate != null) {
                 final ImageTypeSpecifier its = new ImageTypeSpecifier(candidate, samples);
                 specifier = new WeakReference<>(its);
                 return its;
             }
         }
         final ImageTypeSpecifier its = createImageTypeSpecifier();
         samples   = its.getSampleModel();
         colors    = new PaletteDisposer(this, its.getColorModel());
         specifier = new WeakReference<>(its);
         return its;
     }
getLegend()
RenderedImage getLegend (final Dimension size) throws IOException inherited
Returns the color palette as a smoothed image of the specified size, together with the palette name.
The image returned by this method differs from getImage(Dimension) in three ways:
The image returned by this method uses a different color model than the images to be produced by this
Palette
.
The colors in this image are interpolated in order to produce a smooth image. Consequently, some colors in the returned image may not exist in the palette.
The palette name is written in the returned image.
WARNING: Some colors in the returned image may be misleading - they may have no geophysical meaning. Consider for instance an image of Sea Surface Temperature with colors ranging from blue (cold) to red (hot). The correct way to interpolate is to first interpolate the temperature, then use the color map for fetching the color associated to that temperature. With this approach, interpolation between cold and hot water will produce warm water, often displayed in yellow or green. But
getLegend
method will produce purple colors - because it performed the interpolation in ARGB space - which is wrong.
Parameters
size The image size.
Returns
The color palette as an image of the given size.
Exceptions
IOException if the color values can't be read.
Since
3.21
References PaletteFactory.getColors().
{
         final BufferedImage image = new BufferedImage(size.width, size.height, BufferedImage.TYPE_INT_ARGB);
         final Graphics2D g = (Graphics2D) image.getGraphics();
         final Color[] colors = factory.getColors(name);
         final float[] fractions = new float[colors.length];
         for (int i=0; i<colors.length; i++) {
             fractions[i] = (float) i / (colors.length - 1);
         }
         final float centerY = size.height * 0.5f;
         g.setPaint(new LinearGradientPaint(
                 0, centerY,          // The gradiant axis start in user space.
                 size.width, centerY, // The gradient axis end in user space.
                 fractions,           // Numbers ranging from 0 to 1 specifying the distribution of colors along the grandient.
                 colors));            // Colors corresponding to each fractional values.
         g.fillRect(0, 0, size.width, size.height);
         g.setColor(Color.WHITE);
         final Font font = new Font("Dialog", Font.BOLD, 13);
         final Rectangle2D nameBounds = g.getFontMetrics(font).getStringBounds(name, g);
         g.setFont(font);
         g.drawString(name,
                 (float) (size.width  - nameBounds.getWidth())  / 2,
                 (float) (size.height + nameBounds.getHeight()) / 2);
         g.dispose();
         return image;
     }
getOffset()
final double getOffset () package
Returns the offset from <cite>normalized values</cite> (values in the range [0..1]) to values in the range of this palette.
References IndexedPalette.lower.
{
         return lower;
     }
getScale()
final double getScale () package
Returns the scale from <cite>normalized values</cite> (values in the range [0..1]) to values in the range of this palette.
References IndexedPalette.lower.
{
         return upper - lower;
     }
hashCode()
int hashCode ()
Returns a hash value for this palette.
References IndexedPalette.size.
{
         return super.hashCode() + 31*(lower + 31*(upper + 31*size));
     }
isGrayPalette()
static boolean isGrayPalette (final int [] ARGB) static
Tells if the given ARGB array contains only opaque gray colors, with values matching the index value.
Parameters
ARGB The colors to be inspected.
Returns
true
if the palette is grayscale,
false
otherwise.
Referenced by IndexedPalette.createImageTypeSpecifier().
{
         final boolean shift = (ARGB.length >= 0x100);
         for (int i=0; i<ARGB.length; i++) {
             int code = ARGB[i];
             if ((code & 0xFF000000) != 0xFF000000) {
                 return false; // Non-opaque color.
             }
             int expected = i;
             if (shift) {
                 expected >>>= 8;
             }
             if (((code       ) & 0xFF) != expected ||
                 ((code >>>  8) & 0xFF) != expected ||
                 ((code >>> 16) & 0xFF) != expected)
             {
                 return false;
             }
         }
         return true;
     }
toString()
String toString ()
Returns a string representation of this palette.
Used for debugging purpose only.
References Palette.name.
{
         return name + " [" + lower + " \u2026 " + (upper-1) + "] size=" + size;
     }
Member Data Documentation
factory
final PaletteFactory factory package inherited
The originating factory.
Referenced by IndexedPalette.createARGB(), PaletteDisposer.dispose(), Palette.Palette(), and PaletteDisposer.PaletteDisposer().
lower
final int lower protected
Index of the first valid element (inclusive) in the IndexColorModel index color model} to be created.
Pixels in the range 0 inclusive to
lower
exclusive will be reserved for "no data" values.
Strictly speaking, this index should be non-negative because IndexColorModel does not support negative index. However this
Palette
implementation accepts negative values provided that upper is not greater than { Short::MAX_VALUE}. If this condition holds, then
Palette
will transpose negative values as positive values in the range
0x80000
to
0xFFFF
inclusive. Be aware that such approach consume the maximal amount of memory, i.e. 256 kilobytes for each color model.
See also
SpatialImageReader::getRawDataType(int)
Referenced by IndexedPalette.createARGB(), IndexedPalette.equals(), IndexedPalette.getOffset(), IndexedPalette.getScale(), and IndexedPalette.IndexedPalette().
MAX_UNSIGNED
final int MAX_UNSIGNED = 0xFFFF static
The maximal allowed value, corresponding to the maximum value for unsigned 16 bits integer.
DO NOT EDIT: this value MUST be
0xFFFF
.
Referenced by IndexedPalette.IndexedPalette().
name
final String name protected inherited
The name of this palette.
Referenced by IndexedPalette.createARGB(), Palette.equals(), ContinuousPalette.toString(), and IndexedPalette.toString().
numBands
final int numBands protected inherited
The number of bands in the ColorModel color model}.
The value is 1 in the vast majority of cases.
Referenced by ContinuousPalette.createImageTypeSpecifier(), IndexedPalette.createImageTypeSpecifier(), Palette.equals(), and Palette.Palette().
size
final int size protected
The size of the IndexColorModel index color model} to be created.
This is the value to be returned by IndexColorModel#getMapSize(). This value is always positive.
Referenced by IndexedPalette.createARGB(), IndexedPalette.equals(), IndexedPalette.hashCode(), and IndexedPalette.IndexedPalette().
upper
final int upper protected
Index of the last valid element (exclusive) in the IndexColorModel index color model} to be created.
Pixels in the range
upper
inclusive to size exclusive will be reserved for "no data" values. This value is always greater than lower (note that it may be negative).
Referenced by IndexedPalette.equals(), and IndexedPalette.IndexedPalette().
visibleBand
final int visibleBand protected inherited
The band to display, in the range 0 inclusive to numBands exclusive.
This is used when an image contains more than one band but only one band can be used for computing the colors to display. For example IndexColorModel works on only one band.
Referenced by ContinuousPalette.createImageTypeSpecifier(), IndexedPalette.createImageTypeSpecifier(), Palette.equals(), Palette.hashCode(), and Palette.Palette().