jena-geo: TemporalUtilities Class Reference
TemporalUtilities Class Reference
Utilities related to ISO 19108 objects.
Static Public Member Functions
static Instant createInstant (final Date time) throws FactoryNotFoundException
Creates an instant for the given date.
static Period createPeriod (final Date begin, final Date end) throws FactoryNotFoundException
Creates a period for the given begin and end dates.
static PeriodDuration createPeriodDuration (final InternationalString years, final InternationalString months, final InternationalString weeks, final InternationalString days, final InternationalString hours, final InternationalString minutes, final InternationalString seconds) throws FactoryNotFoundException
Creates a period duration for the given fields.
static LogRecord createLog (final FactoryNotFoundException e)
Creates a record for a message to be logged in case of missing factory.
Private Member Functions
TemporalUtilities ()
Do not allow instantiation of this path.
Static Private Member Functions
static Instant createInstant (final TemporalFactory factory, final Date date)
Creates an instant for the given date using the given factory.
Static Private Attributes
static volatile boolean warningLogged
Detailed Description
Utilities related to ISO 19108 objects.
This class may disappear after we reviewed the GeoAPI-pending temporal interfaces.
Author
Martin Desruisseaux (Geomatys)
Guilhem Legal (Geomatys)
Version
3.21
Since
3.20
Constructor & Destructor Documentation
TemporalUtilities()
TemporalUtilities () private
Do not allow instantiation of this path.
{
     }
Member Function Documentation
createInstant() [1/2]
static Instant createInstant (final TemporalFactory factory, final Date date) static private
Creates an instant for the given date using the given factory.
Referenced by TemporalUtilities.createInstant(), and TemporalUtilities.createPeriod().
{
         return factory.createInstant(date);
     }
createInstant() [2/2]
static Instant createInstant (final Date time) throws FactoryNotFoundException static
Creates an instant for the given date.
Parameters
time The date for which to create instant.
Returns
The instant.
Exceptions
FactoryNotFoundException If the temporal factory is not available on the classpath.
References TemporalUtilities.createInstant().
{
         return createInstant(DefaultFactories.forBuildin(TemporalFactory.class), time);
     }
createLog()
static LogRecord createLog (final FactoryNotFoundException e) static
Creates a record for a message to be logged in case of missing factory.
Note that the caller should still set the source class, source method and logger name.
Parameters
e The exception thrown by one of the above
createFoo
methods.
Returns
The record to log.
References Errors.format(), and Errors.Keys.MissingModule_1.
{
         Level level = Level.FINE;
         if (!warningLogged) {
             warningLogged = true;
             level = Level.WARNING;
         }
         final LogRecord record = new LogRecord(level, Errors.format(
                 Errors.Keys.MissingModule_1, "geotk-temporal"));
         record.setMessage(Exceptions.formatChainedMessages(null, record.getMessage(), e));
         return record;
     }
createPeriod()
static Period createPeriod (final Date begin, final Date end) throws FactoryNotFoundException static
Creates a period for the given begin and end dates.
The given arguments can be null if the TemporalFactory#createPosition(Date) method accepts null dates, which stand for undetermined position.
Parameters
begin The begin date, inclusive.
end The end date, inclusive.
Returns
The period.
Exceptions
FactoryNotFoundException If the temporal factory is not available on the classpath.
References TemporalUtilities.createInstant().
{
         final TemporalFactory factory = DefaultFactories.forBuildin(TemporalFactory.class);
         return factory.createPeriod(createInstant(factory, begin), createInstant(factory, end));
     }
createPeriodDuration()
static PeriodDuration createPeriodDuration (final InternationalString years, final InternationalString months, final InternationalString weeks, final InternationalString days, final InternationalString hours, final InternationalString minutes, final InternationalString seconds) throws FactoryNotFoundException static
Creates a period duration for the given fields.
The given arguments can be null if the TemporalFactory#createPeriodDuration() method accepts null values.
Parameters
years the number of years for this period duration.
months the number of months for this period duration.
weeks the number of weeks for this period duration.
days the number of days for this period duration.
hours the number of hours for this period duration.
minutes the number of minutes for this period duration.
seconds the number of seconds for this period duration.
Returns
The period duration.
Exceptions
FactoryNotFoundException If the temporal factory is not available on the classpath.
Since
3.21
     {
         final TemporalFactory factory = DefaultFactories.forBuildin(TemporalFactory.class);
         return factory.createPeriodDuration(years, months, weeks, days, hours, minutes, seconds);
     }
Member Data Documentation
warningLogged
volatile boolean warningLogged static private
true
if a warning has already been logged. This is used in order to log at the warning level only once, in order to avoid polluting the logger. All warnings after the first one will be logged at the fine level.