jena-geo: Identifier3D Class Reference
Identifier3D Class Reference
Identifier for a 3D CRS built from a 2D horizontal component and a 1D vertical component.
Public Member Functions
int hashCode ()
Overridden for consistency with equals(Object).
boolean equals (final Object object)
Compares this object with the given one for equality.
Static Public Member Functions
static Map< String,?> addHorizontalCRS (Map< String,?> properties, final SingleCRS horizontalCRS)
Given the properties of a CRS, replaces the value of the.
Public Attributes
final SingleCRS horizontalCRS
The horizontal component of the 3D CRS identified by this object.
Private Member Functions
Identifier3D (final Identifier identifier, final SingleCRS horizontalCRS)
Creates a new identifier with the same values than the given identifier, and store the given horizontal component for information purpose.
Static Private Attributes
static final long serialVersionUID = -1799606724741505296L
For cross-version compatibility.
Detailed Description
Identifier for a 3D CRS built from a 2D horizontal component and a 1D vertical component.
This identifier is created by org.geotoolkit.referencing.factory.ReferencingFactoryContainer in order to allow the org.geotoolkit.referencing.operation.AuthorityBackedFactory class to find the original 2D component of a monolithic (not a compound) 3D CRS.
This class is a hack. It exists for the following reasons:
We can not just rebuilt a new 2D CRS from a 3D one, because the EPSG code would be lost. We need the EPSG code of the 2D component for
AuthorityBackedFactory
work.
We can not let the 3D (horizontal + ellipsoidal height) CRS as a
ComponentCRS
because the
DefaultCoordinateOperationFactory
processing chain needs to pass those 3D CRS as monolithic objects. This is because some transformation steps need to process the three dimensions together; the ellipsoidal height shall never be separated from the geographical coordinates.
This hack should not be visible in public API, and may change in incompatible way in any future version.
Author
Martin Desruisseaux (Geomatys)
Version
3.16
See also
org.geotoolkit.referencing.operation.AuthorityBackedFactory::getHorizontalCRS
Since
3.16
Constructor & Destructor Documentation
Identifier3D()
Identifier3D (final Identifier identifier, final SingleCRS horizontalCRS) private
Creates a new identifier with the same values than the given identifier, and store the given horizontal component for information purpose.
Parameters
identifier The identifier to copy.
horizontalCRS The horizontal component of the 3D CRS.
References Identifier3D.horizontalCRS.
Referenced by Identifier3D.addHorizontalCRS(), and Identifier3D.equals().
{
         super(identifier);
         this.horizontalCRS = horizontalCRS;
         assert horizontalCRS.getDatum() instanceof GeodeticDatum : horizontalCRS;
     }
Member Function Documentation
addHorizontalCRS()
static Map<String,?> addHorizontalCRS (Map< String,?> properties, final SingleCRS horizontalCRS) static
Given the properties of a CRS, replaces the value of the.
"name"
key by an
Identifier3D
instance declaring the given horizontal CRS.
Parameters
properties The properties of a CRS.
horizontalCRS The horizontal component of the 3D CRS.
Returns
The properties with the given horizontal CRS injected in the name identifier.
References Identifier3D.Identifier3D().
Referenced by ReferencingFactoryContainer.toGeodetic3D().
{
         final Map<String,Object> copy = new HashMap<>(properties);
         final Identifier id = (Identifier) copy.get(NAME_KEY);
         copy.put(NAME_KEY, new Identifier3D(id, horizontalCRS));
         return copy;
     }
equals()
boolean equals (final Object object)
Compares this object with the given one for equality.
This method needs to take the horizontal CRS in account, because CRS using this identifier may be stored in org.geotoolkit.util.collection.WeakHashSet.
References Identifier3D.equals(), Identifier3D.horizontalCRS, and Identifier3D.Identifier3D().
Referenced by Identifier3D.equals().
{
         if (super.equals(object)) {
             final Identifier3D other = (Identifier3D) object;
             return Objects.equals(horizontalCRS, other.horizontalCRS);
         }
         return false;
     }
hashCode()
int hashCode ()
Overridden for consistency with equals(Object).
{
         return super.hashCode() + 31 * horizontalCRS.hashCode();
     }
Member Data Documentation
horizontalCRS
final SingleCRS horizontalCRS
The horizontal component of the 3D CRS identified by this object.
It must be a CRS backed by a geodetic datum.
Referenced by Identifier3D.equals(), and Identifier3D.Identifier3D().
serialVersionUID
final long serialVersionUID = -1799606724741505296L static private
For cross-version compatibility.