jena-geo: Dialect Enum Reference
Dialect Enum Reference
The SQL dialect used by a connection.
Public Member Functions
final String createURL (final Path path) throws SQLException
Constructs the full path to a database in the given directory.
final Path getPath (final String databaseURL)
Given a database URL, gets the path to the database.
final boolean isDriverRegistered ()
Returns.
boolean supportsEnumType (final DatabaseMetaData metadata) throws SQLException
Returns.
boolean supportsCommitStatement (final DatabaseMetaData metadata) throws SQLException
Returns.
int maxRowsPerInsert (final DatabaseMetaData metadata) throws SQLException
Returns the maximum number of rows allowed per.
boolean needsCreateLanguage (final DatabaseMetaData metadata) throws SQLException
Returns.
void shutdown (Connection connection, String databaseURL, boolean setReadOnly) throws SQLException
Closes the given connection (if non-null) and shutdowns the database.
Static Public Member Functions
static Dialect guess (final DatabaseMetaData metadata) throws SQLException
Returns the presumed SQL dialect.
static Dialect forURL (final String databaseURL)
Returns the dialect for the given JDBC URL, or.
Public Attributes
ANSI =(null, null, null)
The database is presumed to use ANSI SQL syntax.
DERBY
The database uses Derby syntax.
HSQL
The database uses HSQL syntax.
POSTGRESQL
The database uses PostgreSQL syntax.
ORACLE =("oracle.jdbc.driver.OracleDriver", "jdbc:oracle:", null)
The database uses Oracle syntax.
ACCESS =(null, null, null)
The database uses Access SQL syntax.
final String driverClass
The driver class name, or.
final String protocol
The prefix of the JDBC URL, or.
Private Member Functions
Dialect (final String driverClass, final String protocol, final String[] subProtocols)
Creates a new dialect enum.
Private Attributes
final String [] subProtocols
The sub-protocols, or.
Static Private Attributes
static final Dialect [] SPECIFIC = ArraysExt.remove(values(), ANSI.ordinal(), 1)
The list of dialect to try to recognize.
Detailed Description
The SQL dialect used by a connection.
This class defines also a few driver-specific operations that can not (to our knowledge) be inferred from the DatabaseMetaData.
Author
Martin Desruisseaux (Geomatys)
Version
3.20
Since
3.00
Constructor & Destructor Documentation
Dialect()
Dialect (final String driverClass, final String protocol, final String [] subProtocols) private
Creates a new dialect enum.
{
         this.driverClass  = driverClass;
         this.protocol     = protocol;
         this.subProtocols = subProtocols;
     }
Member Function Documentation
createURL()
final String createURL (final Path path) throws SQLException
Constructs the full path to a database in the given directory.
The Path::getFileName()#toString() name} of the given
path
shall be the database name (without extension), and the Path::getParent() parent} of the
path
shall be the directory where the database is saved.
Parameters
path The path (without extension) to the database.
Returns
The URL.
Exceptions
SQLException If the database doesn't support local database.
{
         if (subProtocols == null) {
             throw new SQLException();
         }
         // We do not use File.toURI() because HSQL doesn't seem to
         // expect an encoded URL (e.g. "%20" instead of spaces).}
         final StringBuilder url = new StringBuilder(protocol).append(subProtocols[0]).append(':');
         final String p = path.toAbsolutePath().toString().replace(File.separatorChar, '/');
         if (!p.startsWith("/")) {
             url.append('/');
         }
         return url.append(p).toString();
     }
forURL()
static Dialect forURL (final String databaseURL) static
Returns the dialect for the given JDBC URL, or.
null
if unknown.
Parameters
databaseURL The JDBC URL for which to get the dialect.
Returns
The dialect for the given JDBC URL.
Since
3.10
References Dialect.protocol.
Referenced by DefaultDataSource.setLoginTimeout().
{
         if (databaseURL != null) {
             for (final Dialect candidate : SPECIFIC) {
                 final String baseURL = candidate.protocol;
                 if (baseURL != null && databaseURL.regionMatches(true, 0, baseURL, 0, baseURL.length())) {
                     return candidate;
                 }
             }
         }
         return null;
     }
getPath()
final Path getPath (final String databaseURL)
Given a database URL, gets the path to the database.
This is the converse of createURL(Path).
Parameters
databaseURL The database URL.
Returns
The path, or
null
if the given URL is not recognized.
{
         int offset = protocol.length();
         if (databaseURL != null && databaseURL.regionMatches(true, 0, protocol, 0, offset)) {
             if (subProtocols != null) {
                 final int s = databaseURL.indexOf(':', offset);
                 if (s >= 0) {
                     final String p = databaseURL.substring(offset, s);
                     for (int i=0; i<subProtocols.length; i++) {
                         if (p.equalsIgnoreCase(subProtocols[i])) {
                             if (i != 0) {
                                 // As per 'subProtocols' javadoc, only the first sub-protocol
                                 // is the file protocol. All other sub-protocols are ignored.
                                 // In particular, the second sub-protocol is the "memory" one,
                                 // which can not be mapped to a file.
                                 return null;
                             }
                             offset = s + 1;
                         }
                     }
                 }
             }
             return Paths.get(databaseURL.substring(offset));
         }
         return null;
     }
guess()
static Dialect guess (final DatabaseMetaData metadata) throws SQLException static
Returns the presumed SQL dialect.
Current implementation is very primitive and try to guess only a few cases.
Parameters
metadata The database metadata.
Returns
The presumed SQL syntax.
Exceptions
SQLException if an error occurred while querying the metadata.
Referenced by ScriptRunner.ScriptRunner().
{
         String product = metadata.getDatabaseProductName();
         if (product != null) {
             product = product.trim().toUpperCase(Locale.US);
             for (final Dialect candidate : SPECIFIC) {
                 if (product.contains(candidate.name())) {
                     return candidate;
                 }
             }
         }
         return ANSI;
     }
isDriverRegistered()
final boolean isDriverRegistered ()
Returns.
true
if the driver for this
Dialect
is found in the set of DriverManager::getDrivers() registered drivers}. This method may conservatively returns
false
if the registration state can not be determined.
Returns
true
if the driver for this
Dialect
is registered.
Since
3.10
{
         if (driverClass != null) {
             final int stop = driverClass.lastIndexOf('.')+1;
             final Enumeration<Driver> drivers = DriverManager.getDrivers();
             while (drivers.hasMoreElements()) {
                 final Driver drv = drivers.nextElement();
                 if (drv.getClass().getName().regionMatches(0, driverClass, 0, stop)) {
                     return true;
                 }
             }
         }
         return false;
     }
maxRowsPerInsert()
int maxRowsPerInsert (final DatabaseMetaData metadata) throws SQLException
Returns the maximum number of rows allowed per.
"INSERTS"
statement. This method returns 1 if the database does not support multi-rows insertion. For other database, this method returns an arbitrary "reasonable" value, since attempts to insert too many rows with a single statement on Derby database cause a StackOverflowError.
Parameters
metadata The database metadata
Returns
Maximal number of rows per
"INSERT"
statements.
Exceptions
SQLException If an error occurred while querying the metadata.
Since
3.20
{
         return 100; // Arbitrary value choosen from empirical trials.
     }
needsCreateLanguage()
boolean needsCreateLanguage (final DatabaseMetaData metadata) throws SQLException
Returns.
true
if the following instruction shall be executed (assuming that the PostgreSQL
"plpgsql"
language is desired):
sql
 CREATE TRUSTED PROCEDURAL LANGUAGE 'plpgsql'
   HANDLER plpgsql_call_handler
   VALIDATOR plpgsql_validator;
This method returns
true
only for PostgreSQL dialect on database prior to version 9. Starting at version 9, the language is installed by default.
Parameters
metadata The database metadata
Returns
true
if the language shall be created explicitly.
Exceptions
SQLException If an error occurred while querying the metadata.
Since
3.16
{
         return false;
     }
shutdown()
void shutdown (Connection connection, String databaseURL, boolean setReadOnly) throws SQLException
Closes the given connection (if non-null) and shutdowns the database.
The boolean arguments specify some optional operations that can be applied before or after the shutdown, and will be ignored by database that do not support those operations.
Parameters
connection The connection to use for shutting down the database, or
null
if unavailable.
databaseURL The URL to the database, or
null
if unavailable.
setReadOnly
Referenced by DefaultDataSource.setLoginTimeout().
{
         if (connection != null) {
             connection.close();
         }
     }
supportsCommitStatement()
boolean supportsCommitStatement (final DatabaseMetaData metadata) throws SQLException
Returns.
true
if the database supports the
"COMMIT"
statements.
Parameters
metadata The database metadata
Returns
true
if the database supports
"COMMIT"
statement.
Exceptions
SQLException If an error occurred while querying the metadata.
Since
3.20
{
         return false;
     }
supportsEnumType()
boolean supportsEnumType (final DatabaseMetaData metadata) throws SQLException
Returns.
true
if the database supports enums. The default implementation returns
false
, because enums are not a standard feature.
Parameters
metadata The database metadata
Returns
true
if the database supports enums.
Exceptions
SQLException If an error occurred while querying the metadata.
Since
3.14
{
         return false;
     }
Member Data Documentation
ACCESS
ACCESS =(null, null, null)
The database uses Access SQL syntax.
ANSI
ANSI =(null, null, null)
The database is presumed to use ANSI SQL syntax.
Referenced by ScriptRunner.ScriptRunner().
DERBY
DERBY
Initial value:
=("org.apache.derby.jdbc.EmbeddedDriver", "jdbc:derby:", new String[] {
            "directory", "memory", "classpath", "jar"})
    {
        @Override
        public void shutdown(final Connection connection, String databaseURL, final boolean setReadOnly) throws SQLException {
            super.shutdown(connection, databaseURL, setReadOnly);
            final int p = databaseURL.indexOf(';');
            if (p >= 0) {
                databaseURL = databaseURL.substring(0, p);
            }
            databaseURL += ";shutdown=true";
            try {
                DriverManager.getConnection(databaseURL).close();
            } catch (SQLException e) {
            }
        }
    }
The database uses Derby syntax.
This is ANSI, with some constraints that PostgreSQL doesn't have (for example column with
UNIQUE
constraint must explicitly be specified as
NOT NULL
).
driverClass
final String driverClass
The driver class name, or.
null
if unknown.
HSQL
HSQL
The database uses HSQL syntax.
This is ANSI, but does not allow
INSERT
statements inserting many lines. It also have a
SHUTDOWN
command which is specific to HSQLDB.
Since
3.10
ORACLE
ORACLE =("oracle.jdbc.driver.OracleDriver", "jdbc:oracle:", null)
The database uses Oracle syntax.
This is ANSI, but without
"AS"
keyword.
Since
3.18
POSTGRESQL
POSTGRESQL
Initial value:
=("org.postgresql.Driver", "jdbc:postgresql:", null) {
        @Override
        public boolean supportsEnumType(final DatabaseMetaData metadata) throws SQLException {
            final int version = metadata.getDatabaseMajorVersion();
            return (version == 8) ? metadata.getDatabaseMinorVersion() >= 4 : version >= 8;
        }
        @Override
        public boolean needsCreateLanguage(final DatabaseMetaData metadata) throws SQLException {
            return metadata.getDatabaseMajorVersion() < 9;
        }
    }
The database uses PostgreSQL syntax.
This is ANSI, but provided an a separated enum because it allows a few additional commands like
VACUUM
.
While enums were introduced in PostgreSQL 8.3, we require PostgreSQL 8.4 because we need the
CAST ... WITH INOUT
feature.
protocol
final String protocol
The prefix of the JDBC URL, or.
null
if unknown. If non-null, this string begins with
"jdbc:"
and ends with
":"
.
Referenced by Dialect.forURL().
SPECIFIC
static final Dialect [] SPECIFIC = ArraysExt.remove(values(), ANSI.ordinal(), 1) static private
The list of dialect to try to recognize.
This is the list of all available dialects minus the generic ones (ANSI). The enum name must be part of the database product name (ignoring case).
subProtocols
final String [] subProtocols private
The sub-protocols, or.
null
if none. If non-null, then the first protocol shall be the file protocol, and the second protocol (if any) the memory protocol. The strings shall not have training
':'
.