jena-geo: TransfertRectIter Class Reference
TransfertRectIter Class Reference
A WritableRectIter writable iterator} that read pixel values from an image, and write pixel values to a different image.
Public Member Functions
void startLines ()
Sets the iterator to the first line of its bounding rectangle.
void startPixels ()
Sets the iterator to the leftmost pixel of its bounding rectangle.
void startBands ()
Sets the iterator to the first band of the image.
void jumpLines (int num)
Jumps downward num lines from the current position.
void jumpPixels (int num)
Jumps rightward num pixels from the current position.
void nextLine ()
Sets the iterator to the next line of the image.
void nextPixel ()
Sets the iterator to the next pixel in image (that is, move rightward).
void nextBand ()
Sets the iterator to the next band in the image.
boolean nextLineDone ()
Sets the iterator to the next line in the image, and returns.
boolean nextPixelDone ()
Sets the iterator to the next pixel in the image (that is, move rightward).
boolean nextBandDone ()
Sets the iterator to the next band in the image, and returns.
boolean finishedLines ()
Returns.
boolean finishedPixels ()
Returns.
boolean finishedBands ()
Returns.
int [] getPixel (int[] array)
Returns the samples of the current pixel from the image in an array of int.
float [] getPixel (float[] array)
Returns the samples of the current pixel from the image in an array of float.
double [] getPixel (double[] array)
Returns the samples of the current pixel from the image in an array of double.
int getSample ()
Returns the current sample as an integer.
int getSample (int b)
Returns the specified sample of the current pixel as an integer.
float getSampleFloat ()
Returns the current sample as a float.
float getSampleFloat (int b)
Returns the specified sample of the current pixel as a float.
double getSampleDouble ()
Returns the current sample as a double.
double getSampleDouble (int b)
Returns the specified sample of the current pixel as a double.
void setPixel (int[] array)
Sets all samples of the current pixel to a set of int values.
void setPixel (float[] array)
Sets all samples of the current pixel to a set of float values.
void setPixel (double[] array)
Sets all samples of the current pixel to a set of double values.
void setSample (int s)
Sets the current sample to an integral value.
void setSample (float s)
Sets the current sample to a float value.
void setSample (double s)
Sets the current sample to a double value.
void setSample (int b, int s)
Sets the specified sample of the current pixel to an integral value.
void setSample (int b, float s)
Sets the specified sample of the current pixel to a float value.
void setSample (int b, double s)
Sets the specified sample of the current pixel to a double value.
Static Public Member Functions
static WritableRectIter create (final RectIter src, final WritableRectIter dst)
Creates a.
static WritableRectIter create (RenderedImage src, WritableRenderedImage dst, Rectangle bounds)
Creates a.
static WritableRectIter create (RenderedImage src, WritableRaster dst, Rectangle bounds)
Creates a.
static WritableRectIter create (Raster src, WritableRaster dst, Rectangle bounds)
Creates a.
Protected Member Functions
TransfertRectIter (final RectIter src, final WritableRectIter dst)
Constructs a.
Protected Attributes
final RectIter src
The iterator to use for reading from the source.
final WritableRectIter dst
The iterator to use for writing to the destination destination.
Static Private Member Functions
static Raster uniqueTile (final RenderedImage image, final Rectangle bounds)
If the given bounds encompass only one tile of the given image, returns that tile.
Static Private Attributes
static final String ERROR = "Size mismatch"
The string for error message.
Detailed Description
A WritableRectIter writable iterator} that read pixel values from an image, and write pixel values to a different image.
Every
get
methods read values from the <cite>source</cite> image specified at create creation time}. Every
set
methods write values to the <cite>destination</cite> image specified at create creation time}, which may or may not be the same than the <cite>source</cite> image. This is different than the usual WritableRectIter contract, which read and write values in the same image.
The
create(...)
methods return an instance of
TransfertRectIter
only if the source and target rasters are different. Callers can use this contract for optimizing their code. For example implementations of javax.media.jai.PointOpImage that copy some pixel values from source to target rasters can skip the copy phase if the iterator is not an instance of
TransfertRectIter
.
Author
Martin Desruisseaux (IRD, Geomatys)
Version
3.11
Since
2.3
Constructor & Destructor Documentation
TransfertRectIter()
TransfertRectIter (final RectIter src, final WritableRectIter dst) protected
Constructs a.
TransfertRectIter
object.
Parameters
src The iterator to use for reading from the source.
dst The iterator to use for writing to the destination destination.
Since
3.11
References TransfertRectIter.dst, and TransfertRectIter.src.
Referenced by TransfertRectIter.create().
{
         this.src = src;
         this.dst = dst;
     }
Member Function Documentation
create() [1/4]
static WritableRectIter create (final RectIter src, final WritableRectIter dst) static
Creates a.
WritableRectIter
for the specified source and destination iterator. The two iterators must iterate over a rectangle of the same size, otherwise a RasterFormatException will be thrown during the iteration.
Parameters
src The source iterator.
dst The destination iterator.
Returns
An iterator that read samples from
src
and write samples to
dst
. If
src == dst
, then the destination iterator itself is returned.
References TransfertRectIter.dst, and TransfertRectIter.TransfertRectIter().
Referenced by Mask.computeRect(), and TransfertRectIter.create().
{
         if (src == dst) {
             return dst;
         }
         return new TransfertRectIter(src, dst);
     }
create() [2/4]
static WritableRectIter create (RenderedImage src, WritableRenderedImage dst, Rectangle bounds) static
Creates a.
WritableRectIter
for the specified source and destination images. The given rectangle must be in the bounds of both images (this will not be verified).
Parameters
src The source image.
dst The destination image.
bounds The region of the images to iterate over.
Returns
An iterator that read samples from
src
and write samples to
dst
. It will be an instance of
TransfertRectIter
if and only if the source and destination images are not the same.
Since
3.00
References TransfertRectIter.create(), and TransfertRectIter.TransfertRectIter().
{
         if (dst instanceof BufferedImage) {
             /*
              * BufferedImage are always backed by a single raster. Consequently we are better to
              * delegate the work to create(RenderedImage, WritableRaster, Rectangle), which will
              * detects if the source uses the same raster than the destination.
              */
             return create(src, ((BufferedImage) dst).getRaster(), bounds);
         }
         WritableRectIter iter = RectIterFactory.createWritable(dst, bounds);
         if (src != dst) {
             iter = new TransfertRectIter(RectIterFactory.create(src, bounds), iter);
         }
         return iter;
     }
create() [3/4]
static WritableRectIter create (RenderedImage src, WritableRaster dst, Rectangle bounds) static
Creates a.
WritableRectIter
for the specified source image and destination raster. The given rectangle must be in the bounds of both arguments (this will not be verified).
Parameters
src The source image.
dst The destination raster.
bounds The region of the image or raster to iterate over.
Returns
An iterator that read samples from
src
and write samples to
dst
. It will be an instance of
TransfertRectIter
if and only if the source and destination rasters are not the same.
Since
3.00
References TransfertRectIter.create(), TransfertRectIter.TransfertRectIter(), and TransfertRectIter.uniqueTile().
{
         final Raster tile = uniqueTile(src, bounds);
         if (tile == dst) {
             return create(tile, dst, bounds);
         }
         return new TransfertRectIter(RectIterFactory.create(src, bounds),
                 RectIterFactory.createWritable(dst, bounds));
     }
create() [4/4]
static WritableRectIter create (Raster src, WritableRaster dst, Rectangle bounds) static
Creates a.
WritableRectIter
for the specified source and destination rasters. The given rectangle must be in the bounds of both rasters (this will not be verified).
Parameters
src The source raster.
dst The destination raster.
bounds The region of the rasters to iterate over.
Returns
An iterator that read sample from
src
and write sample to
dst
. It will be an instance of
TransfertRectIter
if and only if the source and destination rasters are not the same.
Since
3.00
References TransfertRectIter.TransfertRectIter().
{
         WritableRectIter iter = RectIterFactory.createWritable(dst, bounds);
         if (src != dst) {
             iter = new TransfertRectIter(RectIterFactory.create(src, bounds), iter);
         }
         return iter;
     }
finishedBands()
boolean finishedBands ()
Returns.
true
if the max band in the image has been exceeded.
Returns
true
if the iteration over bands is finished.
{
         boolean check = src.finishedBands();
         if (check == dst.finishedBands()) {
             return check;
         }
         throw new RasterFormatException(ERROR);
     }
finishedLines()
boolean finishedLines ()
Returns.
true
if the bottom row of the bounding rectangle has been passed.
Returns
true
if the iteration over lines is finished.
{
         boolean check = src.finishedLines();
         if (check == dst.finishedLines()) {
             return check;
         }
         throw new RasterFormatException(ERROR);
     }
finishedPixels()
boolean finishedPixels ()
Returns.
true
if the right edge of the bounding rectangle has been passed.
Returns
true
if the iteration over pixels is finished.
{
         boolean check = src.finishedPixels();
         if (check == dst.finishedPixels()) {
             return check;
         }
         throw new RasterFormatException(ERROR);
     }
getPixel() [1/3]
int [] getPixel (int [] array)
Returns the samples of the current pixel from the image in an array of int.
Parameters
array The array where to store the sample values.
Returns
The array of sample values.
{
         return src.getPixel(array);
     }
getPixel() [2/3]
float [] getPixel (float [] array)
Returns the samples of the current pixel from the image in an array of float.
Parameters
array The array where to store the sample values.
Returns
The array of sample values.
{
         return src.getPixel(array);
     }
getPixel() [3/3]
double [] getPixel (double [] array)
Returns the samples of the current pixel from the image in an array of double.
Parameters
array The array where to store the sample values.
Returns
The array of sample values.
{
         return src.getPixel(array);
     }
getSample() [1/2]
int getSample ()
Returns the current sample as an integer.
Returns
The current sample value.
{
         return src.getSample();
     }
getSample() [2/2]
int getSample (int b)
Returns the specified sample of the current pixel as an integer.
Parameters
b The band for which to get the sample value.
Returns
The sample value at the given band.
{
         return src.getSample(b);
     }
getSampleDouble() [1/2]
double getSampleDouble ()
Returns the current sample as a double.
Returns
The current sample value.
{
         return src.getSampleDouble();
     }
getSampleDouble() [2/2]
double getSampleDouble (int b)
Returns the specified sample of the current pixel as a double.
Parameters
b The band for which to get the sample value.
Returns
The sample value at the given band.
{
         return src.getSampleDouble(b);
     }
getSampleFloat() [1/2]
float getSampleFloat ()
Returns the current sample as a float.
Returns
The current sample value.
{
         return src.getSampleFloat();
     }
getSampleFloat() [2/2]
float getSampleFloat (int b)
Returns the specified sample of the current pixel as a float.
Parameters
b The band for which to get the sample value.
Returns
The sample value at the given band.
{
         return src.getSampleFloat(b);
     }
jumpLines()
void jumpLines (int num)
Jumps downward num lines from the current position.
Parameters
num The number of lines to jump.
{
         src.jumpLines(num);
         dst.jumpLines(num);
     }
jumpPixels()
void jumpPixels (int num)
Jumps rightward num pixels from the current position.
Parameters
num The number of pixels to jump.
{
         src.jumpPixels(num);
         dst.jumpPixels(num);
     }
nextBand()
void nextBand ()
Sets the iterator to the next band in the image.
{
         src.nextBand();
         dst.nextBand();
     }
nextBandDone()
boolean nextBandDone ()
Sets the iterator to the next band in the image, and returns.
true
if the max band has been exceeded.
Returns
true
if the iteration over bands is finished.
{
         boolean check = src.nextBandDone();
         if (check == dst.nextBandDone()) {
             return check;
         }
         throw new RasterFormatException(ERROR);
     }
nextLine()
void nextLine ()
Sets the iterator to the next line of the image.
{
         src.nextLine();
         dst.nextLine();
     }
nextLineDone()
boolean nextLineDone ()
Sets the iterator to the next line in the image, and returns.
true
if the bottom row of the bounding rectangle has been passed.
Returns
true
if the iteration over lines is finished.
{
         boolean check = src.nextLineDone();
         if (check == dst.nextLineDone()) {
             return check;
         }
         throw new RasterFormatException(ERROR);
     }
nextPixel()
void nextPixel ()
Sets the iterator to the next pixel in image (that is, move rightward).
{
         src.nextPixel();
         dst.nextPixel();
     }
nextPixelDone()
boolean nextPixelDone ()
Sets the iterator to the next pixel in the image (that is, move rightward).
Returns
true
if the iteration over pixels is finished.
{
         boolean check = src.nextPixelDone();
         if (check == dst.nextPixelDone()) {
             return check;
         }
         throw new RasterFormatException(ERROR);
     }
setPixel() [1/3]
void setPixel (int [] array)
Sets all samples of the current pixel to a set of int values.
Parameters
array The new pixel values.
{
         dst.setPixel(array);
     }
setPixel() [2/3]
void setPixel (float [] array)
Sets all samples of the current pixel to a set of float values.
Parameters
array The new pixel values.
{
         dst.setPixel(array);
     }
setPixel() [3/3]
void setPixel (double [] array)
Sets all samples of the current pixel to a set of double values.
Parameters
array The new pixel values.
{
         dst.setPixel(array);
     }
setSample() [1/6]
void setSample (int s)
Sets the current sample to an integral value.
Parameters
s The new sample value.
{
         dst.setSample(s);
     }
setSample() [2/6]
void setSample (float s)
Sets the current sample to a float value.
Parameters
s The new sample value.
{
         dst.setSample(s);
     }
setSample() [3/6]
void setSample (double s)
Sets the current sample to a double value.
Parameters
s The new sample value.
{
         dst.setSample(s);
     }
setSample() [4/6]
void setSample (int b, int s)
Sets the specified sample of the current pixel to an integral value.
Parameters
b The band for which to set the sample value.
s The new sample value.
{
         dst.setSample(b, s);
     }
setSample() [5/6]
void setSample (int b, float s)
Sets the specified sample of the current pixel to a float value.
Parameters
b The band for which to set the sample value.
s The new sample value.
{
         dst.setSample(b, s);
     }
setSample() [6/6]
void setSample (int b, double s)
Sets the specified sample of the current pixel to a double value.
Parameters
b The band for which to set the sample value.
s The new sample value.
{
         dst.setSample(b, s);
     }
startBands()
void startBands ()
Sets the iterator to the first band of the image.
{
         src.startBands();
         dst.startBands();
     }
startLines()
void startLines ()
Sets the iterator to the first line of its bounding rectangle.
{
         src.startLines();
         dst.startLines();
     }
startPixels()
void startPixels ()
Sets the iterator to the leftmost pixel of its bounding rectangle.
{
         src.startPixels();
         dst.startPixels();
     }
uniqueTile()
static Raster uniqueTile (final RenderedImage image, final Rectangle bounds) static private
If the given bounds encompass only one tile of the given image, returns that tile.
Otherwise returns
null
. The given bounds would be inside the image bounds; this will not be verified.
Parameters
image The image for which to get a singleton tile.
bounds The bounds of the region of interest, or
null
for the whole image.
Returns
The raster inside the given bounds, or
null
if there is more than one raster in those bounds.
Referenced by TransfertRectIter.create().
{
         if (bounds == null) {
             if (image.getNumXTiles() == 1 && image.getNumYTiles() == 1) {
                 return image.getTile(image.getMinTileX(), image.getMinTileY());
             }
         } else {
             int x = bounds.x;
             final int width   = image.getTileWidth();
             final int xOffset = image.getTileGridXOffset();
             final int tx = PlanarImage.XToTileX(x, xOffset, width);
             x -= PlanarImage.tileXToX(tx, xOffset, width);
             if (x + bounds.width <= width) {
                 int y = bounds.y;
                 final int height  = image.getTileHeight();
                 final int yOffset = image.getTileGridYOffset();
                 final int ty = PlanarImage.YToTileY(y, yOffset, height);
                 y -= PlanarImage.tileYToY(ty, yOffset, height);
                 if (y + bounds.height <= height) {
                     return image.getTile(tx, ty);
                 }
             }
         }
         return null;
     }
Member Data Documentation
dst
final WritableRectIter dst protected
The iterator to use for writing to the destination destination.
Since
3.11
Referenced by TransfertRectIter.create(), and TransfertRectIter.TransfertRectIter().
ERROR
final String ERROR = "Size mismatch" static private
The string for error message.
Todo:
Localize.
src
final RectIter src protected
The iterator to use for reading from the source.
Since
3.11
Referenced by TransfertRectIter.TransfertRectIter().