jena-geo: Writer Class Reference
Writer Class Reference
Formats objects in the JSON format.
Public Member Functions
Writer (final Appendable out)
Creates a new writer for the given standard which will write in the given stream.
void format (final Object object) throws ClassCastException, IOException
Formats the given object in the output stream specified at construction time.
Static Package Attributes
static final int UNICODE_LENGTH = 4
The length of an escaped Unicode character.
Private Member Functions
void indent () throws IOException
Writes the left margin at the beginning of a new line.
void formatEntries (final Iterator< Map.Entry< String, Object >> it) throws IOException
Formats all (key, value) pairs of the given map, in iteration order.
void formatArray (final Iterator<?> it) throws IOException
Formats an array of values.
void formatValue (final Object value) throws IOException
Formats a single value.
void escape (final String text) throws IOException
Appends the given text, escaping characters if needed.
Static Private Member Functions
static MetadataStandard getStandard (final Object value)
Suggests a metadata standard for the given object.
Private Attributes
final Appendable out
Where to write the formatted output.
final String lineSeparator
The line-separator to use.
MetadataStandard standard
The ISO standard to use for listing the object properties.
int margin
Number of spaces to write before the first no-space character.
final Map< Object, Object > guard = new IdentityHashMap<>()
Guard against infinite recursivity.
Static Private Attributes
static final int INDENTATION = 4
Number of spaces to use for the indentation.
Detailed Description
Formats objects in the JSON format.
Author
Martin Desruisseaux (Geomatys)
Todo:
We have an ambiguity when writing
Party.name
: nothing distinguish an individual name from an organization name, since the
Party
type is lost at JSON writing time. We propose to format as
"individual.name"
and
"organisation.name"
in those particular cases.
Constructor & Destructor Documentation
Writer()
Writer (final Appendable out)
Creates a new writer for the given standard which will write in the given stream.
Parameters
out Where to format the object.
References Writer.out.
{
         this.out      = out;
         lineSeparator = System.lineSeparator();
     }
Member Function Documentation
escape()
void escape (final String text) throws IOException private
Appends the given text, escaping characters if needed.
References Writer.UNICODE_LENGTH.
Referenced by Writer.formatEntries(), and Writer.formatValue().
{
         int previous = 0;
         final int length = text.length();
         for (int i=0; i<length; i++) {
             final char c = text.charAt(i); // No need for codepoint API in this method.
             final char r;
             switch (c) {
                 case '"' : // Fallthrough
                 case '\\': r =  c;  break;
                 case '\b': r = 'b'; break;
                 case '\f': r = 'f'; break;
                 case '\n': r = 'n'; break;
                 case '\r': r = 'r'; break;
                 case '\t': r = 't'; break;
                 default: {
                     if (!Character.isISOControl(c)) {
                         continue; // Nothing to escape.
                     }
                     r = 'u';
                     break;
                 }
             }
             out.append(text, previous, i);
             out.append('\\').append(r);
             if (r == 'u') {
                 final String h = Integer.toHexString(c);
                 for (int p=h.length(); p<UNICODE_LENGTH; p++) {
                     out.append('0');
                 }
                 out.append(h);
             }
             previous = i+1;
         }
         out.append(text, previous, length);
     }
format()
void format (final Object object) throws ClassCastException, IOException
Formats the given object in the output stream specified at construction time.
Parameters
object The object to format.
Exceptions
ClassCastException If the given object is not an instance of a recognized standard.
IOException If an error occurred while writing to the output stream.
References Writer.formatEntries(), Writer.getStandard(), and Writer.standard.
Referenced by JSON.format(), and Writer.formatValue().
{
         if (guard.put(object, Boolean.TRUE) == null) {
             final MetadataStandard previous = standard;
             standard = getStandard(object);
             formatEntries(standard.asValueMap(object, null, KeyNamePolicy.UML_IDENTIFIER,
                     ValueExistencePolicy.NON_EMPTY).entrySet().iterator());
             standard = previous;
             if (guard.remove(object) != Boolean.TRUE) { // Identity check is okay here.
                 throw new ConcurrentModificationException();
             }
         } else {
             // We have a recursivity, buy we can not express that in JSON.
             out.append(null);
         }
     }
formatArray()
void formatArray (final Iterator<?> it) throws IOException private
Formats an array of values.
Parameters
it An iterator over the array elements to format.
Exceptions
IOException If an error occurred while writing to the output stream.
References Writer.formatValue().
Referenced by Writer.formatEntries().
{
         out.append('[');
         boolean hasNext = it.hasNext();
         while (hasNext) {
             final Object element = it.next();
             hasNext = it.hasNext();
             formatValue(element);
             if (hasNext) {
                 out.append(',');
             }
         }
         out.append(']');
     }
formatEntries()
void formatEntries (final Iterator< Map.Entry< String, Object >> it) throws IOException private
Formats all (key, value) pairs of the given map, in iteration order.
Parameters
it An iterator over the metadata properties to format.
Exceptions
IOException If an error occurred while writing to the output stream.
References Writer.escape(), Writer.formatArray(), Writer.formatValue(), Writer.indent(), and Writer.INDENTATION.
Referenced by Writer.format().
{
         out.append('{').append(lineSeparator);
         margin += INDENTATION;
         for (boolean hasNext = it.hasNext(); hasNext;) {
             final Map.Entry<String,Object> entry = it.next();
             hasNext = it.hasNext();
             indent();
             out.append('"');
             escape(entry.getKey());
             out.append("\": ");
             final Object value = entry.getValue();
             if (value == null) {
                 out.append(null);
             } else if (value instanceof Collection<?>) {
                 formatArray(((Collection<?>) value).iterator());
             } else {
                 formatValue(value);
             }
             if (hasNext) {
                 out.append(',');
             }
             out.append(lineSeparator);
         }
         margin -= INDENTATION;
         indent();
         out.append('}');
     }
formatValue()
void formatValue (final Object value) throws IOException private
Formats a single value.
Parameters
value The value to format.
Exceptions
IOException If an error occurred while writing to the output stream.
References Writer.escape(), and Writer.format().
Referenced by Writer.formatArray(), and Writer.formatEntries().
{
         if (standard.isMetadata(value.getClass())) {
             format(value);
         } else {
             final String text;
             final boolean quote;
             if (value instanceof ControlledVocabulary) {
                 text  = Types.getCodeName((ControlledVocabulary) value);
                 quote = true;
             } else if (value instanceof Date) {
                 text  = Long.toString(((Date) value).getTime());
                 quote = false;
             } else if (value instanceof Angle) {
                 text  = Double.toString(((Angle) value).degrees());
                 quote = false;
             } else {
                 text  = value.toString();
                 quote = !(value instanceof Number || value instanceof Boolean);
             }
             if (quote) out.append('"');
             escape(text);
             if (quote) out.append('"');
         }
     }
getStandard()
static MetadataStandard getStandard (final Object value) static private
Suggests a metadata standard for the given object.
Referenced by Writer.format().
{
         return (value instanceof AbstractMetadata) ? ((AbstractMetadata) value).getStandard() : MetadataStandard.ISO_19115;
     }
indent()
void indent () throws IOException private
Writes the left margin at the beginning of a new line.
Referenced by Writer.formatEntries().
{
         out.append(CharSequences.spaces(margin));
     }
Member Data Documentation
guard
final Map<Object,Object> guard = new IdentityHashMap<>() private
Guard against infinite recursivity.
INDENTATION
final int INDENTATION = 4 static private
Number of spaces to use for the indentation.
Referenced by Writer.formatEntries().
lineSeparator
final String lineSeparator private
The line-separator to use.
margin
int margin private
Number of spaces to write before the first no-space character.
This value is increased or decreased when an object definition begins or stops.
out
final Appendable out private
Where to write the formatted output.
Referenced by Writer.Writer().
standard
MetadataStandard standard private
The ISO standard to use for listing the object properties.
Referenced by Writer.format().
UNICODE_LENGTH
final int UNICODE_LENGTH = 4 static package
The length of an escaped Unicode character.
Referenced by Writer.escape(), and Reader.unescape().