jena-geo: TemporaryFile Class Reference
TemporaryFile Class Reference
Manages temporary files created by the Geotk library.
Public Member Functions
void dispose ()
Deletes this file.
String toString ()
Returns the file path.
Static Public Member Functions
static synchronized Path getSharedTemporaryDirectory ()
Returns the temporary directory.
static Path createTempFile (String prefix, String suffix, Path directory) throws IOException
Creates a new temporary file and register it immediately for deletion on JVM shutdown.
static boolean delete (final File file)
Deletes the given temporary file.
static boolean delete (final Path file)
Deletes the given temporary file.
Static Package Functions
[static initializer]
Registers a shutdown hook which will delete every files not yet deleted.
Private Member Functions
TemporaryFile (final Path file)
Creates a new reference to a temporary file.
boolean delete ()
Deletes the current file.
Static Private Member Functions
static boolean deleteAll ()
Deletes every files, no matter if they have been garbage-collected or not.
Private Attributes
final String path
The path to the file to delete.
Static Private Attributes
static final Map< String, TemporaryFile > REFERENCES = new HashMap<>()
The temporary files not yet deleted.
static Path sharedTemporaryDirectory
The temporary directory, or.
Detailed Description
Manages temporary files created by the Geotk library.
This class provides a createTempFile method which similar to the one provided in the standard File class, except that the file may be deleted earlier. More specifically if the File object has been garbage-collected, then the corresponding file in the file system is deleted immediately instead than waiting for the JVM shutdown.
{
Note
This class extends PhantomReference for implementation convenience. Callers should ignore that detail.}
Author
Martin Desruisseaux (Geomatys)
Version
3.16
Since
3.03
Constructor & Destructor Documentation
TemporaryFile()
TemporaryFile (final Path file) private
Creates a new reference to a temporary file.
References ReferenceQueueConsumer< T >.DEFAULT, and ReferenceQueueConsumer< T >.queue.
Referenced by TemporaryFile.createTempFile().
{
         super(file, ReferenceQueueConsumer.DEFAULT.queue);
         path = file.toString();
     }
Member Function Documentation
[static initializer]()
[static initializer] () static package
Registers a shutdown hook which will delete every files not yet deleted.
createTempFile()
static Path createTempFile (String prefix, String suffix, Path directory) throws IOException static
Creates a new temporary file and register it immediately for deletion on JVM shutdown.
Parameters
prefix The prefix string to be used in generating the file's name.
suffix The suffix string to be used in generating the file's name (usually with a leading dot), or
null
for
".tmp"
.
directory The directory in which the file is to be created, or
null
.
Returns
The temporary file.
Exceptions
IOException If the file can not be created.
References TemporaryFile.path, TemporaryFile.REFERENCES, and TemporaryFile.TemporaryFile().
{
         Path tmpFile;
         if (directory == null) {
             tmpFile = Files.createTempFile(prefix, suffix);
         } else {
             tmpFile = Files.createTempFile(directory, prefix, suffix);
         }
         final TemporaryFile ref = new TemporaryFile(tmpFile);
         synchronized (REFERENCES) {
             if (REFERENCES.put(ref.path, ref) != null) {
                 // Should never happen since File.createTempFile ensures unique filename.
                 // Not that there is a slight risks that this failure happens if the user
                 // invoked File.delete() instead than TemporaryFile.delete(tmpFile).
                 throw new AssertionError(ref);
             }
         }
         return tmpFile;
     }
delete() [1/3]
static boolean delete (final File file) static
Deletes the given temporary file.
This method should be invoked instead of File#delete() in order to unregister the given file.
Parameters
file The file to delete.
Returns
true
if the file has been deleted.
References TemporaryFile.delete(), and TemporaryFile.REFERENCES.
Referenced by TemporaryFile.delete().
{
         synchronized (REFERENCES) {
             final TemporaryFile ref = REFERENCES.remove(file.getPath());
             if (ref != null) {
                 ref.clear();
             }
         }
         return file.delete(); // Must be after the removal from the list.
     }
delete() [2/3]
static boolean delete (final Path file) static
Deletes the given temporary file.
This method should be invoked instead of File#delete() in order to unregister the given file.
Parameters
file The file to delete.
Returns
true
if the file has been deleted.
References IOUtilities.deleteSilently(), and TemporaryFile.REFERENCES.
{
         synchronized (REFERENCES) {
             final TemporaryFile ref = REFERENCES.remove(file.toString());
             if (ref != null) {
                 ref.clear();
             }
         }
         return IOUtilities.deleteSilently(file);
     }
delete() [3/3]
boolean delete () private
Deletes the current file.
This is invoked by dispose() when a File object has been garbage-collected.
Returns
true
if the file has been successfully deleted.
References IOUtilities.deleteSilently(), and TemporaryFile.REFERENCES.
{
         synchronized (REFERENCES) {
             if (REFERENCES.remove(path) == this) {
                 final Path filePath = Paths.get(this.path);
                 IOUtilities.deleteSilently(filePath);
                 return new File(this.path).delete();
             }
         }
         return false; // Already deleted by the shutdown hook.
     }
deleteAll()
static boolean deleteAll () static private
Deletes every files, no matter if they have been garbage-collected or not.
This method should be invoking during shutdown only.
Returns
true
if at least one file has been successfully deleted.
References IOUtilities.deleteSilently(), and TemporaryFile.REFERENCES.
{
         boolean deleted = false;
         final Map<String,TemporaryFile> references = REFERENCES;
         if (references != null) { // Safety check against weird behavior at shutdown time.
             synchronized (references) {
                 for (final TemporaryFile ref : references.values()) {
                     deleted |= IOUtilities.deleteSilently(Paths.get(ref.path));
                     ref.clear();
                 }
                 references.clear();
             }
         }
         return deleted;
     }
dispose()
void dispose ()
Deletes this file.
This method is invoked automatically when a File object has been garbage-collected.
References Loggings.format(), and Loggings.Keys.TemporaryFileGc_1.
{
         if (delete()) {
             /*
              * Logs the message at the WARNING level because execution of this code
              * means that the application failed to delete itself the temporary file.
              */
             Logging.log(TemporaryFile.class, "delete",
                     Loggings.format(Level.WARNING, Loggings.Keys.TemporaryFileGc_1, this));
         }
     }
getSharedTemporaryDirectory()
static synchronized Path getSharedTemporaryDirectory () static
Returns the temporary directory.
Returns
The temporary directory to use.
References TemporaryFile.sharedTemporaryDirectory.
{
         Path directory = sharedTemporaryDirectory;
         if (directory == null) {
             directory = Paths.get(System.getProperty("java.io.tmpdir", "/tmp"), "Geotoolkit.org");
             if (!Files.isDirectory(directory)) {
                 try {
                     Files.createDirectories(directory);
                 } catch (IOException e) {
                     // If we can't create the Geotoolkit subdirectory,
                     // stay in the usual tmp directory.
                     directory = directory.getParent();
                 }
             }
             sharedTemporaryDirectory = directory;
         }
         return directory;
     }
toString()
String toString ()
Returns the file path.
Returns
The file path.
References TemporaryFile.path.
{
         return path;
     }
Member Data Documentation
path
final String path private
The path to the file to delete.
We do not keep directly a reference to File since we want to allow the garbage collector to collect the file. Note that Sun implementation of File#deleteOnExit() in JDK 6 also retains the path instead than the
File
.
Referenced by TemporaryFile.createTempFile(), and TemporaryFile.toString().
REFERENCES
final Map<String,TemporaryFile> REFERENCES = new HashMap<>() static private
The temporary files not yet deleted.
Keys are the string returned by File#getPath().
Referenced by TemporaryFile.createTempFile(), TemporaryFile.delete(), and TemporaryFile.deleteAll().
sharedTemporaryDirectory
Path sharedTemporaryDirectory static private
The temporary directory, or.
null
if none.
Referenced by TemporaryFile.getSharedTemporaryDirectory().