jena-geo: CRSUtilities Class Reference
CRSUtilities Class Reference
A set of static methods working on OpenGIS® CoordinateReferenceSystem coordinate reference system} objects.
Static Public Member Functions
static int getDimensionOf (final CoordinateReferenceSystem crs, final Class<? extends CoordinateReferenceSystem > type) throws IllegalArgumentException
Returns the dimension of the first coordinate reference system of the given type.
static CoordinateReferenceSystem getCRS2D (CoordinateReferenceSystem crs) throws TransformException
Returns a two-dimensional coordinate reference system representing the two first dimensions of the specified coordinate reference system.
static Envelope appendMissingDimensions (final Envelope envelope, final CompoundCRS crs)
Returns an envelope containing all dimensions of the given CRS, padding additional dimensions with NaN values if necessary.
static Unit< Angle > getAngularUnit (final CoordinateSystem coordinateSystem)
Returns the angular unit of the specified coordinate system.
static Quantity<?> getHorizontalResolution (final CoordinateReferenceSystem crs, double... resolution)
Computes the resolution of the horizontal component, or.
static CoordinateReferenceSystem shiftAxisRange (final CoordinateReferenceSystem crs, final AxesConvention type)
Delegates to the.
static int firstHorizontalAxis (final CoordinateReferenceSystem crs)
Retrieve index of the first axis of the geographic component in the input CoordinateReferenceSystem.
static Class<? extends IdentifiedObject > getReferencingGroup (final Class<? extends IdentifiedObject > type)
Returns the group of referencing objects to which the given type belong.
Private Member Functions
CRSUtilities ()
Do not allow creation of instances of this class.
Detailed Description
A set of static methods working on OpenGIS® CoordinateReferenceSystem coordinate reference system} objects.
Some of those methods are useful, but not really rigorous. This is why they do not appear in the "official" package, but instead in this private one.
Do not rely on this API! It may change in incompatible way in any future release.
Version
3.21
Since
2.0
Constructor & Destructor Documentation
CRSUtilities()
CRSUtilities () private
Do not allow creation of instances of this class.
{
     }
Member Function Documentation
appendMissingDimensions()
static Envelope appendMissingDimensions (final Envelope envelope, final CompoundCRS crs) static
Returns an envelope containing all dimensions of the given CRS, padding additional dimensions with NaN values if necessary.
This method is a workaround for the current Geotk behavior, which is to thrown an exception when re-projecting an envelope to another CRS having more dimensions. This method will hopefully be deleted in a future version.
Parameters
envelope The envelope to expand.
crs The target CRS.
Returns
An envelope having the dimensions of the given CRS.
{
         final List<CoordinateReferenceSystem> toAdd = new ArrayList<>(4);
         final CoordinateReferenceSystem currentCRS = envelope.getCoordinateReferenceSystem();
         final CoordinateSystem currentCS = currentCRS.getCoordinateSystem();
         for (final SingleCRS subCRS : CRS.getSingleComponents(crs)) {
             final CoordinateSystem subCS = subCRS.getCoordinateSystem();
             if (subCS.getDimension() == 1 && AxisDirections.indexOfColinear(currentCS, subCS) < 0) {
                 toAdd.add(subCRS);
             }
         }
         if (toAdd.isEmpty()) {
             return envelope;
         }
         toAdd.add(0, currentCRS);
         final GeneralEnvelope expanded;
         try {
             expanded = new GeneralEnvelope(CRS.compound(toAdd.toArray(new CoordinateReferenceSystem[toAdd.size()])));
         } catch (FactoryException e) {
             throw new IllegalArgumentException("Illegal CRS.", e);
         }
         expanded.setToNaN();
         expanded.subEnvelope(0, envelope.getDimension()).setEnvelope(envelope);
         return expanded;
     }
firstHorizontalAxis()
static int firstHorizontalAxis (final CoordinateReferenceSystem crs) static
Retrieve index of the first axis of the geographic component in the input CoordinateReferenceSystem.
Parameters
crs CoordinateReferenceSystem which is analyzed.
Returns
Index of the first horizontal axis in this CRS
Exceptions
IllegalArgumentException if input CRS has no horizontal component.
Todo:
Inaccurate implementation: a Cartesian or spherical CS does not mean that the axes is horizontal.
Referenced by ReferencingUtilities.convertResolution().
{
         int tempOrdinate = 0;
         for (CoordinateReferenceSystem component : CRS.getSingleComponents(crs)) {
             final CoordinateSystem cs = component.getCoordinateSystem();
             if ((cs instanceof CartesianCS)
                     || (cs instanceof SphericalCS)
                     || (cs instanceof EllipsoidalCS)) // Inaccurate check: see TODO in javadoc.
             {
                 return tempOrdinate;
             }
             tempOrdinate += cs.getDimension();
         }
         throw new IllegalArgumentException("crs doesn't have any horizontal crs");
     }
getAngularUnit()
static Unit<Angle> getAngularUnit (final CoordinateSystem coordinateSystem) static
Returns the angular unit of the specified coordinate system.
The preference will be given to the longitude axis, if found.
{
         Unit<Angle> unit = Units.DEGREE;
         for (int i=coordinateSystem.getDimension(); --i>=0;) {
             final CoordinateSystemAxis axis = coordinateSystem.getAxis(i);
             final Unit<?> candidate = axis.getUnit();
             if (Units.isAngular(candidate)) {
                 unit = candidate.asType(Angle.class);
                 if (AxisDirection.EAST.equals(AxisDirections.absolute(axis.getDirection()))) {
                     break; // Found the longitude axis.
                 }
             }
         }
         return unit;
     }
getCRS2D()
static CoordinateReferenceSystem getCRS2D (CoordinateReferenceSystem crs) throws TransformException static
Returns a two-dimensional coordinate reference system representing the two first dimensions of the specified coordinate reference system.
If
crs
is already a two-dimensional CRS, then it is returned unchanged. Otherwise, if it is a CompoundCRS, then the head coordinate reference system is examined.
Parameters
crs The coordinate system, or
null
.
Returns
A two-dimensional coordinate reference system that represents the two first dimensions of
crs
, or
null
if
crs
was
null
.
Exceptions
TransformException if
crs
can't be reduced to a two-coordinate system. We use this exception class since this method is usually invoked in the context of a transformation process.
Deprecated:
The logic behind this method is not safe at all. It will only check the first component of the input CRS, so a CRS whose 2 dimensional axis is not in first position, it will return a null value. If the aim is to retrieve the horizontal component of a crs, please prefer CRS#getHorizontalComponent(org.opengis.referencing.crs.CoordinateReferenceSystem). On the other hand, if you aim to retrieve a 2D CRS, whatever its signification, you should use a custoam approach better fitting your need.
References Errors.Keys.CantReduceToTwoDimensions_1, and Errors.format().
Referenced by ReferencingUtilities.combine(), and ReferencingUtilities.convertResolution().
     {
         if (crs != null) {
             final CoordinateReferenceSystem original = crs;
             while (crs.getCoordinateSystem().getDimension() != 2) {
                 if (crs instanceof CompoundCRS) {
                     crs = ((CompoundCRS) crs).getComponents().get(0);
                     // Continue the loop, examining only the first component.
                 } else {
                     crs = CRS.getHorizontalComponent(crs);
                     if (crs == null) {
                         throw new TransformException(Errors.format(
                                 Errors.Keys.CantReduceToTwoDimensions_1, original.getName()));
                     }
                 }
             }
         }
         return crs;
     }
getDimensionOf()
static int getDimensionOf (final CoordinateReferenceSystem crs, final Class<? extends CoordinateReferenceSystem > type) throws IllegalArgumentException static
Returns the dimension of the first coordinate reference system of the given type.
The
type
argument must be a sub-interface of CoordinateReferenceSystem. If no such dimension is found, then this method returns
-1
.
Parameters
crs The coordinate reference system (CRS) to examine.
type The CRS type to look for. Must be a subclass of CoordinateReferenceSystem.
Returns
The dimension range of the specified CRS type, or
-1
if none.
Exceptions
IllegalArgumentException if the
type
is not legal.
     {
         if (type.isAssignableFrom(crs.getClass())) {
             return 0;
         }
         if (crs instanceof CompoundCRS) {
             int offset = 0;
             for (final CoordinateReferenceSystem ci : ((CompoundCRS) crs).getComponents()) {
                 final int index = getDimensionOf(ci, type);
                 if (index >= 0) {
                     return index + offset;
                 }
                 offset += ci.getCoordinateSystem().getDimension();
             }
         }
         return -1;
     }
getHorizontalResolution()
static Quantity<?> getHorizontalResolution (final CoordinateReferenceSystem crs, double... resolution) static
Computes the resolution of the horizontal component, or.
null
if it can not be computed.
Parameters
crs The full (potentially multi-dimensional) CRS.
resolution The resolution along each CRS dimension, or
null
if none. The array length shall be equals to the CRS dimension.
Returns
The horizontal resolution, or
null
.
Since
3.18
{
         if (resolution != null) {
             final SingleCRS horizontalCRS = CRS.getHorizontalComponent(crs);
             if (horizontalCRS != null) {
                 final CoordinateSystem hcs = horizontalCRS.getCoordinateSystem();
                 final Unit<?> unit = ReferencingUtilities.getUnit(hcs);
                 if (unit != null) {
                     final int s = AxisDirections.indexOfColinear(crs.getCoordinateSystem(), hcs);
                     if (s >= 0) {
                         final int dim = hcs.getDimension();
                         double min = Double.POSITIVE_INFINITY;
                         for (int i=s; i<dim; i++) {
                             final double r = resolution[i];
                             if (r > 0 && r < min) min = r;
                         }
                         if (min != Double.POSITIVE_INFINITY) {
                             return Quantities.create(min, unit);
                         }
                     }
                 }
             }
         }
         return null;
     }
getReferencingGroup()
static Class<? extends IdentifiedObject> getReferencingGroup (final Class<? extends IdentifiedObject > type) static
Returns the group of referencing objects to which the given type belong.
The
type
argument can be a GeoAPI interface or an implementation class. The value returned by this method will be one of CoordinateReferenceSystem, CoordinateSystem, CoordinateSystemAxis, Datum, Ellipsoid, PrimeMeridian or IdentifiedObject classes. If the given type is assignable to more than one group, then this method returns
IdentifiedObject
class.
Parameters
type The type for which to get the referencing group, or
null
.
Returns
The group to which the given type belong, or
null
if the given argument was
null
.
{
         Class<? extends IdentifiedObject> found = null;
         if (type != null) {
 search:     for (int i=0; ; i++) {
                 final Class<? extends IdentifiedObject> candidate;
                 switch (i) {
                     case 0:  candidate = CoordinateReferenceSystem.class; break;
                     case 1:  candidate = CoordinateSystem.class;          break;
                     case 2:  candidate = CoordinateSystemAxis.class;      break;
                     case 3:  candidate = Datum.class;                     break;
                     case 4:  candidate = Ellipsoid.class;                 break;
                     case 5:  candidate = PrimeMeridian.class;             break;
                     default: break search;
                 }
                 if (candidate.isAssignableFrom(type)) {
                     if (found != null) {
                         return IdentifiedObject.class;
                     }
                     found = candidate;
                 }
             }
             if (found == null) {
                 return IdentifiedObject.class;
             }
         }
         return found;
     }
shiftAxisRange()
static CoordinateReferenceSystem shiftAxisRange (final CoordinateReferenceSystem crs, final AxesConvention type) static
Delegates to the.
shiftAxisRange
method of the appropriate class. This method is not in public API because the call to
castOrCopy
may involve useless objects creation. Developers are encouraged to invoke
castOrCopy
themselves, then replace their old reference by the new one before to invoke
shiftAxisRange
, because they Geotk implementations cache the result of
shiftAxisRange
calls.
Parameters
crs The CRS on which to apply the shift, or
null
.
type The desired range of ordinate values.
Returns
The shifted CRS, or
crs
if no range shift applied.
Since
3.20
{
         if (crs instanceof GeographicCRS) {
             final DefaultGeographicCRS impl = DefaultGeographicCRS.castOrCopy((GeographicCRS) crs);
             final DefaultGeographicCRS shifted = impl.forConvention(type);
             if (shifted != impl) return shifted;
         } else if (crs instanceof CompoundCRS) {
             final DefaultCompoundCRS impl = DefaultCompoundCRS.castOrCopy((CompoundCRS) crs);
             final DefaultCompoundCRS shifted = impl.forConvention(type);
             if (shifted != impl) return shifted;
         }
         return crs;
     }