jena-geo: Setup Class Reference
Setup Class Reference
A central place where to perform initialization and shutdown of all Geotk services.
Static Public Member Functions
static synchronized void setEPSG (final DataSource source)
Sets the data source for the EPSG database.
static synchronized DataSource getEPSG ()
Returns the EPSG data source.
static synchronized void initialize (final Properties properties) throws IllegalStateException
Performs the initialization of all Geotk services.
static synchronized void shutdown ()
Shutdowns all Geotk services.
Private Member Functions
Setup ()
Do not allow instantiation of this class.
Static Private Member Functions
static String get (final Properties properties, final String key, final String def)
Returns the value for the given key in the given properties map, or the default value if none.
Static Private Attributes
static int state
The setup state.
static DataSource EPSG
Data source for the EPSG database, or.
Detailed Description
A central place where to perform initialization and shutdown of all Geotk services.
Users are not required to perform explicit initialization and shutdown for most services (except a few cases like <cite>World File Image Readers</cite>), since services are automatically discovered when needed (using ServiceLoader) and disposed on JVM termination (using Runtime::addShutdownHook shutdown hook}). However the above-cited mechanism is not sufficient when an application is undeployed and re-deployed in a JEE environment without restarting the JVM. For example the org.geotoolkit.image.io.plugin Geotk Image I/O plugins} needs to be IIORegistry::deregisterServiceProvider(Object) deregistered} during the <cite>undeploy</cite> phase before they get IIORegistry::registerServiceProvider(Object) registered} again during the <cite>re-deploy</cite> phase. Explicit invocations of initialize(Properties) and shutdown() methods can improve the system stability in such cases.
The amount of works performed by this class depends on the modules available in the classpath. The table below lists the work performed by current implementation. Users wanting more control can perform those tasks themselves instead than relying on the methods defined in this
Setup
class.
Module Methods invoked by initialize(Properties) Work done by shutdown()
geotk-utility
If
platform != "server"
:
Logging::forceMonolineConsoleOutput Logging.forceMonolineConsoleOutput}(null)
geotk-coverage
org.geotoolkit.image.jai.Registry#setDefaultCodecPreferences()
Remove from the JAI javax.media.jai.OperationRegistry every plugins defined in any
org.geotoolkit
package.
geotk-coverageio
org.geotoolkit.image.io.plugin.WorldFileImageReader.Spi::registerDefaults WorldFileImageReader.Spi.registerDefaults}(null)
org.geotoolkit.image.io.plugin.WorldFileImageWriter.Spi::registerDefaults WorldFileImageWriter.Spi.registerDefaults}(null)
Remove from IIORegistry every plugins defined in any
org.geotoolkit
package.
geotk-coverageio-netcdf
If
netcdfCacheLimit != 0
:
ucar.nc2.dataset.NetcdfDataset#initNetcdfFileCache(int,int,int)
ucar.nc2.dataset.NetcdfDataset#shutdown().
{
on floating point types}
In current implementation, invoking initialize(Properties) with a property entry
platform=server
also disable the usage of java.util.prefs.Preferences::systemRoot() system preferences}. This is a temporary workaround for the JDK 6 behavior on Unix system, which display "<cite>WARNING: Couldn't flush system prefs</cite>" if the
etc/.java
directory has not been created during the Java installation process.
This workaround may be removed in a future version if JDK 7 uses its new
java.nio.file
package for performing a better work with system preferences.
Author
Martin Desruisseaux (Geomatys)
Constructor & Destructor Documentation
Setup()
Setup () private
Do not allow instantiation of this class.
                     {
     }
Member Function Documentation
get()
static String get (final Properties properties, final String key, final String def) static private
Returns the value for the given key in the given properties map, or the default value if none.
The given properties map is allowed to be
null
.
{
         return (properties != null) ? properties.getProperty(key, def) : def;
     }
getEPSG()
static synchronized DataSource getEPSG () static
Returns the EPSG data source.
References Installation.EPSG, and Setup.EPSG.
Referenced by Setup.initialize().
{
         if (EPSG == null) try {
             final Properties properties = Installation.EPSG.getDataSource();
             if (properties != null) {
                 final String url = properties.getProperty("URL");
                 if (url != null) {
                     EPSG = new DefaultDataSource(url);
                     final String user = properties.getProperty("user");
                     if (user != null) {
                         EPSG = new AuthenticatedDataSource(EPSG, user, properties.getProperty("password"), false);
                     }
                 }
             }
         } catch (IOException e) {
             throw new UncheckedIOException(e);
         }
         return EPSG;
     }
initialize()
static synchronized void initialize (final Properties properties) throws IllegalStateException static
Performs the initialization of all Geotk services.
This method is typically invoked only once. If it is invoked more than once and shutdown() has not been invoked, then every calls after the first method call are ignored.
The
properties
map allows some control on the initialization process. Current implementation recognizes the entries listed in the table below. Any entry not listed in this table are silently ignored.
Key Valid values Default Meaning
platform
server
|
desktop
desktop
Whatever the library is run for a desktop application or a server.
netcdfCacheLimit
Positive integer 0 Maximum number of elements in the NetCDF cache (0 for no cache).
force
true
|
false
false
If
true
, attempt a re-initialization after a shutdown.
Parameters
properties Optional set of properties controlling the initialization process, or
null
.
Exceptions
IllegalStateException If the Geotk library has been shutdown() shutdown} and the given properties map doesn't contain a
force=true
entry.
References Setup.getEPSG().
{
         if (state == 1) {
             return;
         }
         final boolean reinit = (state == 2);
         if (reinit && !Boolean.parseBoolean(get(properties, "force", "false"))) {
             throw new IllegalStateException();
         }
         state = 1;
         if ("server".equalsIgnoreCase(get(properties, "platform", "desktop"))) {
         } else {
             MonolineFormatter.install();
         }
         Initializer.setDefault(Setup::getEPSG);
         /*
          * Following are normally not needed, since the factory registry scans automatically
          * the classpath when first needed. However some factories may have been unregistered
          * during the shutdown process, so we need to scan the classpath to re-register them.
          */
         if (reinit) {
             DefaultFactories.fireClasspathChanged();
         }
         /*
          * Now performs every module-specific initialization.
          */
         for (final SetupService service : ServiceLoader.load(SetupService.class)) {
             service.initialize(properties, reinit);
         }
     }
setEPSG()
static synchronized void setEPSG (final DataSource source) static
Sets the data source for the EPSG database.
Parameters
source data source for the EPSG database, or
null
if none.
{
         EPSG = source;
     }
shutdown()
static synchronized void shutdown () static
Shutdowns all Geotk services.
This method can be safely invoked even if the initialize(Properties) method has never been invoked.
The Geotk library should not be used anymore after this method call.
References Threads.shutdown().
{
         if (state != 2) {
             state = 2;
             Initializer.setDefault(null);
             for (final SetupService service : ServiceLoader.load(SetupService.class)) {
                 service.shutdown();
             }
             /*
              * The following method should be invoked only when we think there is not any code still
              * runnning that may invoke Threads.executor(boolean). It is actually hard to ensure that,
              * but a search on Threads.SHUTDOWN_HOOKS and Threads.executeDisposal(Runnable) is helpful.
              */
             Threads.shutdown();
         }
     }
Member Data Documentation
EPSG
DataSource EPSG static private
Data source for the EPSG database, or.
null
if none.
Referenced by Setup.getEPSG().
state
int state static private
The setup state.
0: initial state.
1: initialize(Properties) has been invoked.
2: shutdown() has been invoked.