jena-geo: Palette Class Reference
Palette Class Reference abstract
A set of RGB colors created by a PaletteFactory palette factory} from a name}.
Public Member Functions
synchronized ColorModel getColorModel () throws FileNotFoundException, IOException
Returns the color model for this palette.
synchronized ImageTypeSpecifier getImageTypeSpecifier () throws FileNotFoundException, IOException
Returns the image type specifier for this palette.
RenderedImage getImage (final Dimension size) throws IOException
Returns the color palette as an image of the specified size.
RenderedImage getLegend (final Dimension size) throws IOException
Returns the color palette as a smoothed image of the specified size, together with the palette name.
int hashCode ()
Returns a hash value for this palette.
boolean equals (final Object object)
Compares this palette with the specified object for equality.
Protected Member Functions
Palette (final PaletteFactory factory, final String name, final int numBands, final int visibleBand)
Creates a palette with the specified name.
abstract ImageTypeSpecifier createImageTypeSpecifier () throws FileNotFoundException, IOException
Creates a new image type specifier for this palette.
Protected Attributes
final String name
The name of this palette.
final int numBands
The number of bands in the ColorModel color model}.
final int visibleBand
The band to display, in the range 0 inclusive to numBands exclusive.
Package Functions
final void ensureInsideBounds (final int value, final int min, final int max) throws IllegalArgumentException
Ensures that the specified values in inside the expected bounds (inclusives).
double getScale ()
Returns the scale from <cite>normalized values</cite> (values in the range [0..1]) to values in the range of this palette.
double getOffset ()
Returns the offset from <cite>normalized values</cite> (values in the range [0..1]) to values in the range of this palette.
Package Attributes
final PaletteFactory factory
The originating factory.
Private Attributes
transient SampleModel samples
The sample model to be given to ImageTypeSpecifier.
transient Reference< ColorModel > colors
A weak reference to the color model.
transient Reference< ImageTypeSpecifier > specifier
A weak reference to the image specifier to be returned by getImageTypeSpecifier.
Detailed Description
A set of RGB colors created by a PaletteFactory palette factory} from a name}.
A palette can creates a ColorModel color model} (often IndexColorModel indexed}) or an ImageTypeSpecifier image type specifier} from the RGB colors.
{
<code>IndexColorModel</code> instances}
The color model is retained by the palette as a WeakReference weak reference} (not as a java.lang.ref.SoftReference soft reference}) because it may consume up to 256 kilobytes. The purpose of the weak reference is to share existing instances in order to reduce memory usage; the purpose is not to provide caching.
Author
Martin Desruisseaux (IRD)
Antoine Hnawia (IRD)
Quentin Boileau (Geomatys)
Version
3.21
Since
2.4
Constructor & Destructor Documentation
Palette()
Palette (final PaletteFactory factory, final String name, final int numBands, final int visibleBand) protected
Creates a palette with the specified name.
Parameters
factory The originating factory.
name The palette name.
numBands The number of bands (usually 1) to assign to numBands.
visibleBand The visible band (usually 0) to assign to visibleBand.
References Palette.ensureInsideBounds(), Palette.factory, PaletteFactory.getErrorResources(), Errors.Keys.NullArgument_1, Palette.numBands, and Palette.visibleBand.
Referenced by Palette.equals().
     {
         ArgumentChecks.ensureNonNull("factory", factory); // Can't use factory.getErrorResources() here.
         if (name == null) {
             throw new NullArgumentException(factory.getErrorResources().getString(
                     Errors.Keys.NullArgument_1, "name"));
         }
         ensureInsideBounds(numBands, 0, 255); // This maximal value is somewhat arbitrary.
         ensureInsideBounds(visibleBand, 0, numBands-1);
         this.factory     = factory;
         this.name        = name.trim();
         this.numBands    = numBands;
         this.visibleBand = visibleBand;
     }
Member Function Documentation
createImageTypeSpecifier()
abstract ImageTypeSpecifier createImageTypeSpecifier () throws FileNotFoundException, IOException abstract protected
Creates a new image type specifier for this palette.
This method is invoked by getImageTypeSpecifier() when the specifier is not present in the cache.
Returns
The image type specified for this palette.
Exceptions
FileNotFoundException If the RGB values need to be read from a file and this file (typically inferred from name) is not found.
IOException If an other kind of I/O error occurred.
Since
3.11
Referenced by Palette.getImageTypeSpecifier().
ensureInsideBounds()
final void ensureInsideBounds (final int value, final int min, final int max) throws IllegalArgumentException package
Ensures that the specified values in inside the expected bounds (inclusives).
Exceptions
IllegalArgumentException if the specified values are outside the bounds.
References PaletteFactory.getErrorResources(), and Errors.Keys.ValueOutOfBounds_3.
Referenced by IndexedPalette.IndexedPalette(), and Palette.Palette().
     {
         if (value < min || value > max) {
             throw new IllegalArgumentException(factory.getErrorResources().getString(
                     Errors.Keys.ValueOutOfBounds_3, value, min, max));
         }
     }
equals()
boolean equals (final Object object)
Compares this palette with the specified object for equality.
This method shall compare only the values given to the constructor. It shall not trig the ColorModel construction, because this
equals
method is used by PaletteFactory#palettes in order to check if an existing
Palette
instance can be reused.
Parameters
object The object to compare with this palette for equality.
Returns
true
if the given object is equal to this palette.
References Palette.name, Palette.numBands, Palette.Palette(), and Palette.visibleBand.
{
         if (object != null && getClass() == object.getClass()) {
             final Palette that = (Palette) object;
             return this.numBands    == that.numBands    &&
                    this.visibleBand == that.visibleBand &&
                    Objects.equals(this.name, that.name);
             /*
              * Note: we do not compare PaletteFactory on purpose, since two instances could be
              * identical except for the locale to use for formatting error messages.   Because
              * Palettes are used as keys in the PaletteFactory.palettes pool, we don't want to
              * get duplicated palettes only because they format error messages differently.
              */
         }
         return false;
     }
getColorModel()
synchronized ColorModel getColorModel () throws FileNotFoundException, IOException
Returns the color model for this palette.
This method tries to reuse existing color model if possible, since it may consume a significant amount of memory.
Returns
The color model for this palette.
Exceptions
FileNotFoundException If the RGB values need to be read from a file and this file (typically inferred from name) is not found.
IOException If an other kind of I/O error occurred.
References Palette.getImageTypeSpecifier().
Referenced by Palette.getImage().
{
         if (colors != null) {
             final ColorModel candidate = colors.get();
             if (candidate != null) {
                 return candidate;
             }
         }
         return getImageTypeSpecifier().getColorModel();
     }
getImage()
RenderedImage getImage (final Dimension size) throws IOException
Returns the color palette as an image of the specified size.
This is useful for looking visually at a color palette.
This method uses the color model created by getColorModel() and does not write any text in the image. Consequently the colors in the returned image should be identical to the colors of the data rendered using this
Palette
.
Parameters
size The image size. The palette will be vertical if size. Dimension::height height} > size. Dimension::width width }
Returns
The color palette as an image of the given size.
Exceptions
IOException if the color values can't be read.
References Palette.getColorModel(), Palette.getOffset(), and Palette.getScale().
{
         final IndexColorModel colors = (IndexColorModel) getColorModel();
         final WritableRaster  raster = colors.createCompatibleWritableRaster(size.width, size.height);
         final BufferedImage   image  = new BufferedImage(colors, raster, false, null);
         int xmin   = raster.getMinX();
         int ymin   = raster.getMinY();
         int width  = raster.getWidth();
         int height = raster.getHeight();
         final boolean horizontal = size.width >= size.height;
         // Computation will be performed as if the image were horizontal.
         // If it is not, interchanges x and y values.
         if (!horizontal) {
             int tmp;
             tmp = xmin;  xmin  = ymin;   ymin   = tmp;
             tmp = width; width = height; height = tmp;
         }
         final int xmax = xmin + width;
         final int ymax = ymin + height;
         final double scale  = getScale() / width;
         final double offset = getOffset();
         for (int x=xmin; x<xmax; x++) {
             final double value = offset + scale*(x-xmin);
             for (int y=ymin; y<ymax; y++) {
                 if (horizontal) {
                     raster.setSample(x, y, 0, value);
                 } else {
                     raster.setSample(y, x, 0, value);
                 }
             }
         }
         return image;
     }
getImageTypeSpecifier()
synchronized ImageTypeSpecifier getImageTypeSpecifier () throws FileNotFoundException, IOException
Returns the image type specifier for this palette.
The default implementation first check if the specified still in the cache. If not, then the createImageTypeSpecifier() method is invoked and its result is stored in the cache for future reuse.
Returns
The image type specified for this palette.
Exceptions
FileNotFoundException If the RGB values need to be read from a file and this file (typically inferred from name) is not found.
IOException If an other kind of I/O error occurred.
References Palette.createImageTypeSpecifier().
Referenced by Palette.getColorModel().
{
         if (specifier != null) {
             final ImageTypeSpecifier candidate = specifier.get();
             if (candidate != null) {
                 return candidate;
             }
         }
         if (samples != null && colors != null) {
             final ColorModel candidate = colors.get();
             if (candidate != null) {
                 final ImageTypeSpecifier its = new ImageTypeSpecifier(candidate, samples);
                 specifier = new WeakReference<>(its);
                 return its;
             }
         }
         final ImageTypeSpecifier its = createImageTypeSpecifier();
         samples   = its.getSampleModel();
         colors    = new PaletteDisposer(this, its.getColorModel());
         specifier = new WeakReference<>(its);
         return its;
     }
getLegend()
RenderedImage getLegend (final Dimension size) throws IOException
Returns the color palette as a smoothed image of the specified size, together with the palette name.
The image returned by this method differs from getImage(Dimension) in three ways:
The image returned by this method uses a different color model than the images to be produced by this
Palette
.
The colors in this image are interpolated in order to produce a smooth image. Consequently, some colors in the returned image may not exist in the palette.
The palette name is written in the returned image.
WARNING: Some colors in the returned image may be misleading - they may have no geophysical meaning. Consider for instance an image of Sea Surface Temperature with colors ranging from blue (cold) to red (hot). The correct way to interpolate is to first interpolate the temperature, then use the color map for fetching the color associated to that temperature. With this approach, interpolation between cold and hot water will produce warm water, often displayed in yellow or green. But
getLegend
method will produce purple colors - because it performed the interpolation in ARGB space - which is wrong.
Parameters
size The image size.
Returns
The color palette as an image of the given size.
Exceptions
IOException if the color values can't be read.
Since
3.21
References PaletteFactory.getColors().
{
         final BufferedImage image = new BufferedImage(size.width, size.height, BufferedImage.TYPE_INT_ARGB);
         final Graphics2D g = (Graphics2D) image.getGraphics();
         final Color[] colors = factory.getColors(name);
         final float[] fractions = new float[colors.length];
         for (int i=0; i<colors.length; i++) {
             fractions[i] = (float) i / (colors.length - 1);
         }
         final float centerY = size.height * 0.5f;
         g.setPaint(new LinearGradientPaint(
                 0, centerY,          // The gradiant axis start in user space.
                 size.width, centerY, // The gradient axis end in user space.
                 fractions,           // Numbers ranging from 0 to 1 specifying the distribution of colors along the grandient.
                 colors));            // Colors corresponding to each fractional values.
         g.fillRect(0, 0, size.width, size.height);
         g.setColor(Color.WHITE);
         final Font font = new Font("Dialog", Font.BOLD, 13);
         final Rectangle2D nameBounds = g.getFontMetrics(font).getStringBounds(name, g);
         g.setFont(font);
         g.drawString(name,
                 (float) (size.width  - nameBounds.getWidth())  / 2,
                 (float) (size.height + nameBounds.getHeight()) / 2);
         g.dispose();
         return image;
     }
getOffset()
double getOffset () package
Returns the offset from <cite>normalized values</cite> (values in the range [0..1]) to values in the range of this palette.
Referenced by Palette.getImage().
{
         return 0;
     }
getScale()
double getScale () package
Returns the scale from <cite>normalized values</cite> (values in the range [0..1]) to values in the range of this palette.
Referenced by Palette.getImage().
                       {
         return 1;
     }
hashCode()
int hashCode ()
Returns a hash value for this palette.
See equals(Object) for information about which attributes can be used in the computation.
References Palette.visibleBand.
{
         return name.hashCode() + 31*numBands + visibleBand;
     }
Member Data Documentation
colors
transient Reference<ColorModel> colors private
A weak reference to the color model.
This color model may consume a significant amount of memory (up to 256 kb). Consequently, we will prefer WeakReference over java.lang.ref.SoftReference. The purpose of this weak reference is to share existing instances, not to cache it since it is cheap to rebuild.
Referenced by IndexedPalette.createARGB().
factory
final PaletteFactory factory package
The originating factory.
Referenced by IndexedPalette.createARGB(), PaletteDisposer.dispose(), Palette.Palette(), and PaletteDisposer.PaletteDisposer().
name
final String name protected
The name of this palette.
Referenced by IndexedPalette.createARGB(), Palette.equals(), ContinuousPalette.toString(), and IndexedPalette.toString().
numBands
final int numBands protected
The number of bands in the ColorModel color model}.
The value is 1 in the vast majority of cases.
Referenced by ContinuousPalette.createImageTypeSpecifier(), IndexedPalette.createImageTypeSpecifier(), Palette.equals(), and Palette.Palette().
samples
transient SampleModel samples private
The sample model to be given to ImageTypeSpecifier.
specifier
transient Reference<ImageTypeSpecifier> specifier private
A weak reference to the image specifier to be returned by getImageTypeSpecifier.
We use weak reference because the image specifier contains a reference to the color model and we don't want to prevent it to be garbage collected. See colors for an explanation about why we use weak instead of soft references.
visibleBand
final int visibleBand protected
The band to display, in the range 0 inclusive to numBands exclusive.
This is used when an image contains more than one band but only one band can be used for computing the colors to display. For example IndexColorModel works on only one band.
Referenced by ContinuousPalette.createImageTypeSpecifier(), IndexedPalette.createImageTypeSpecifier(), Palette.equals(), Palette.hashCode(), and Palette.Palette().