jena-geo: Listeners Class Reference
Listeners Class Reference
Utility methods related to listeners.
Static Public Member Functions
static ChangeListener [] addListener (final ChangeListener listener, ChangeListener[] listeners)
Adds the given listener to the given list of listeners.
static ChangeListener [] removeListener (final ChangeListener listener, ChangeListener[] listeners)
Removes the given listener from the given list of listeners.
static void fireChanged (final Object source, final ChangeListener[] listeners)
Notifies all registered listeners that the given object changed.
Private Member Functions
Listeners ()
Do not allow instantiation of this class.
Detailed Description
Utility methods related to listeners.
This method provides a single place where we manage Swing listeners used in a non-Swing context. If a future Geotk version, we may replace Swing listeners by JavaFX observable. In such case, we can just search for usage of this
Listeners
class.
Author
Martin Desruisseaux (Geomatys)
Version
3.20
Since
3.20
Constructor & Destructor Documentation
Listeners()
Listeners () private
Do not allow instantiation of this class.
{
     }
Member Function Documentation
addListener()
static ChangeListener [] addListener (final ChangeListener listener, ChangeListener [] listeners) static
Adds the given listener to the given list of listeners.
If the given listener is added more than once, then it will be notified more than once.
Parameters
listener The listener to add.
listeners The list of listeners to add to, or
null
if it does not yet exist.
Returns
The new list of listeners.
Referenced by AbstractParameterValue< Double >.addChangeListener(), and Factories.addChangeListener().
{
         ArgumentChecks.ensureNonNull("listener", listener);
         final int length;
         if (listeners == null) {
             length = 0;
             listeners = new ChangeListener[1];
         } else {
             length = listeners.length;
             listeners = Arrays.copyOf(listeners, length + 1);
         }
         listeners[length] = listener;
         return listeners;
     }
fireChanged()
static void fireChanged (final Object source, final ChangeListener [] listeners) static
Notifies all registered listeners that the given object changed.
Parameters
source The event source.
listeners The list of listeners to notify, or
null
if none.
Referenced by Factories.fireConfigurationChanged(), and AbstractParameterValue< Double >.fireValueChanged().
{
         if (listeners != null) {
             final ChangeEvent event = new ChangeEvent(source);
             for (final ChangeListener listener : listeners) {
                 listener.stateChanged(event);
             }
         }
     }
removeListener()
static ChangeListener [] removeListener (final ChangeListener listener, ChangeListener [] listeners) static
Removes the given listener from the given list of listeners.
If the given listener does not appear in the given list, this method does nothing. If it appears more than once, then only the first occurrence is removed.
Parameters
listener The listener to add.
listeners The list of listeners from which to remove the listener, or
null
if none.
Returns
The new list of listeners, or
null
if the last listener has been removed.
Referenced by AbstractParameterValue< Double >.removeChangeListener(), and Factories.removeChangeListener().
{
         if (listeners != null) {
             for (int i=0; i<listeners.length; i++) {
                 if (listeners[i] == listener) {
                     listeners = ArraysExt.remove(listeners, i, 1);
                     if (listeners.length == 0) {
                         listeners = null;
                     }
                     break;
                 }
             }
         }
         return listeners;
     }