jena-geo: Polynom Class Reference
Polynom Class Reference
The coefficients of a polynomial equation.
Public Member Functions
Polynom (final double[] c)
Constructs a polynomial equation with the specified coefficients.
final double y (final double x)
Evaluates the polynomial equation for the specified x value.
double [] roots ()
Finds the roots of the polynomial equation.
int hashCode ()
Returns a hash value for this polynom.
boolean equals (final Object object)
Compares this polynom with the specified object for equality.
String toString ()
Returns a string representation of this polynom.
Static Public Member Functions
static double [] roots (final double[] c)
Finds the roots of a polynomial equation.
Static Private Member Functions
static double [] quadraticRoots (double c0, double c1, double c2)
Finds the roots of a quadratic equation.
static double [] cubicRoots (double c0, double c1, double c2, double c3)
Finds the roots of a cubic equation.
Private Attributes
final double [] c
The coefficients for the polynomial equation.
transient double [] roots
The roots of the polynomial equation.
Static Private Attributes
static final long serialVersionUID = 6825019711186108990L
Serial version UID for compatibility with different versions.
Detailed Description
The coefficients of a polynomial equation.
The equation must be in the form
y = c0 + c1×x + c2×x2 + c3×x3 + ... + cn×xn.
The static method roots(double[]) can be used for computing the root of a polynomial equation without creating a
Polynom
object.
Author
Martin Desruisseaux (IRD)
Ken Turkiwski (for algorithmic inspiration)
Version
3.00
Since
2.0
Constructor & Destructor Documentation
Polynom()
Polynom (final double [] c)
Constructs a polynomial equation with the specified coefficients.
Parameters
c The coefficients. This array is copied.
Referenced by Polynom.equals().
{
         int n = c.length;
         while (n != 0 && c[--n] == 0) {
             // Empty on purpose.
         }
         if (n == 0) {
             this.c = ArraysExt.EMPTY_DOUBLE;
         } else {
             this.c = new double[n];
             System.arraycopy(c, 0, this.c, 0, n);
         }
     }
Member Function Documentation
cubicRoots()
static double [] cubicRoots (double c0, double c1, double c2, double c3) static private
Finds the roots of a cubic equation.
More specifically, this method solves the following equation:
c0 + c1*x + c2*x2 + c3*x3 == 0
Returns
The roots. The length may be 1 or 3.
References Polynom.roots().
Referenced by Polynom.roots().
{
         c2 /= c3;
         c1 /= c3;
         c0 /= c3;
         final double Q  = (c2*c2 - 3*c1) / 9;
         final double R = (2*c2*c2*c2 - 9*c2*c1 + 27*c0) / 54;
         final double Qcubed = Q*Q*Q;
         final double d = Qcubed - R*R;
         c2 /= 3;
         if (d >= 0) {
             final double theta = acos(R / sqrt(Qcubed)) / 3;
             final double scale = -2 * sqrt(Q);
             final double[] roots = new double[] {
                 scale * cos(theta              ) - c2,
                 scale * cos(theta + PI*2/3) - c2,
                 scale * cos(theta + PI*4/3) - c2
             };
             assert abs(roots[0]*roots[1]*roots[2] + c0  ) < 1E-6;
             assert abs(roots[0]+roots[1]+roots[2] + c2*3) < 1E-6;
             assert abs(roots[0]*roots[1] +
                        roots[0]*roots[2] +
                        roots[1]*roots[2] - c1) < 1E-6;
             return roots;
         } else {
             double e = cbrt(sqrt(-d) + abs(R));
             if (R > 0) {
                 e = -e;
             }
             return new double[] {
                 (e + Q/e) - c2
             };
         }
     }
equals()
boolean equals (final Object object)
Compares this polynom with the specified object for equality.
Parameters
object The object to compare with this polynom.
Returns
true
if both objects are equal.
References Polynom.c, Polynom.equals(), and Polynom.Polynom().
Referenced by Polynom.equals().
{
         if (object != null && object.getClass() == getClass()) {
             final Polynom that = (Polynom) object;
             return Arrays.equals(this.c, that.c);
         }
         return false;
     }
hashCode()
int hashCode ()
Returns a hash value for this polynom.
{
         return Arrays.hashCode(c) ^ (int) serialVersionUID;
     }
quadraticRoots()
static double [] quadraticRoots (double c0, double c1, double c2) static private
Finds the roots of a quadratic equation.
More specifically, this method solves the following equation:
c0 + c1*x + c2*x2 == 0
Returns
The roots. The length may be 1 or 2.
Referenced by Polynom.roots().
{
         double d = c1*c1 - 4*c2*c0;
         if (d > 0) {
             // Two real, distinct roots
             d = sqrt(d);
             if (c1 < 0) {
                 d = -d;
             }
             final double q = 0.5*(d - c1);
             return new double[] {
                 q/c2,
                 (q!=0) ? c0/q : -0.5*(d + c1)/c2
             };
         } else if (d == 0) {
             // One real double root
             return new double[] {
                 -c1 / (2*c2)
             };
         } else {
             // Two complex conjugate roots
             return ArraysExt.EMPTY_DOUBLE;
         }
     }
roots() [1/2]
double [] roots ()
Finds the roots of the polynomial equation.
Returns
The roots.
Referenced by Polynom.cubicRoots().
{
         if (roots == null) {
             roots = roots(c);
         }
         return roots.clone();
     }
roots() [2/2]
static double [] roots (final double [] c) static
Finds the roots of a polynomial equation.
More specifically, this method solve the following equation:
c[0] + c[1]*x + c[2]*x2 + c[3]*x3 + ... + c[n]*xn == 0
where n is the array length minus 1.
Parameters
c The coefficients for the polynomial equation.
Returns
The roots. This array may have any length up to
n-1
.
Exceptions
UnsupportedOperationException if there is more coefficients than this method can handle.
References Polynom.cubicRoots(), and Polynom.quadraticRoots().
{
         int n = c.length;
         while (n != 0 && c[--n] == 0) {
             // Empty on purpose.
         }
         switch (n) {
             case 0:  return ArraysExt.EMPTY_DOUBLE;
             case 1:  return new double[] {-c[0]/c[1]};
             case 2:  return quadraticRoots(c[0], c[1], c[2]);
             case 3:  return cubicRoots(c[0], c[1], c[2], c[3]);
             default: throw new UnsupportedOperationException(String.valueOf(n));
         }
     }
toString()
String toString ()
Returns a string representation of this polynom.
{
         final StringBuilder buffer = new StringBuilder(Classes.getShortClassName(this));
         buffer.append('[');
         for (int i=0; i<c.length; i++) {
             if (i != 0) {
                 buffer.append(", ");
             }
             buffer.append(c[i]);
         }
         return buffer.append(']').toString();
     }
y()
final double y (final double x)
Evaluates the polynomial equation for the specified x value.
More specifically, this method computes
c0 + c1×x + c2×x2 + c3×x3 + ... + cn×xn.
Parameters
x The value where to evaluate the polynomial equation.
Returns
The result of the evaluation at the given value.
{
         double sum = 0;
         for (int i=c.length; --i>=0;) {
             sum = sum*x + c[i];
         }
         return sum;
     }
Member Data Documentation
c
final double [] c private
The coefficients for the polynomial equation.
Referenced by Polynom.equals().
roots
transient double [] roots private
The roots of the polynomial equation.
Will be computed only when first requested.
serialVersionUID
final long serialVersionUID = 6825019711186108990L static private
Serial version UID for compatibility with different versions.