jena-geo: FloatParameter Class Reference
FloatParameter Class Reference
A parameter value as a floating point (double precision) number.
Public Member Functions
FloatParameter (final ParameterDescriptor< Double > descriptor)
Constructs a parameter from the specified descriptor.
FloatParameter (final ParameterDescriptor< Double > descriptor, final double value)
Constructs a parameter from the specified descriptor and value.
Unit<?> getUnit ()
Returns the unit of measure of the doubleValue() parameter value}.
double doubleValue (final Unit<?> unit) throws IllegalArgumentException
Returns the numeric value of the coordinate operation parameter in the specified unit of measure.
double doubleValue ()
Returns the numeric value represented by this operation parameter.
int intValue () throws IllegalStateException
Returns the numeric value casted to integer.
boolean booleanValue () throws IllegalStateException
Returns.
String stringValue () throws IllegalStateException
Returns the string representation of the value.
double [] doubleValueList (final Unit<?> unit) throws IllegalArgumentException
Wraps the value in an array of length 0 or 1.
double [] doubleValueList ()
Wraps the value in an array of length 0 or 1.
int [] intValueList () throws InvalidParameterTypeException
Wraps the value in an array of length 1.
URI valueFile () throws InvalidParameterTypeException
Always throws an exception, since this parameter is not an URI.
Double getValue ()
Returns the parameter value as a Double, or.
void setValue (final double value, final Unit<?> unit) throws InvalidParameterValueException
Sets the parameter value as a floating point and its associated unit.
void setValue (final double value) throws InvalidParameterValueException
Sets the parameter value as a floating point.
void setValue (final int value) throws InvalidParameterValueException
Sets the parameter value as an integer.
void setValue (final boolean value) throws InvalidParameterValueException
Sets the parameter value as a boolean.
void setValue (final Object value) throws InvalidParameterValueException
Sets the parameter value as a Double object.
void setValue (final double[] values, final Unit<?> unit) throws InvalidParameterValueException
If the length of the given array is 1, delegates to setValue(double, Unit).
boolean equals (final Object object)
Compares the specified object with this parameter for equality.
int hashCode ()
Returns a hash value for this parameter.
FloatParameter clone ()
Returns a clone of this parameter.
ParameterDescriptor< T > getDescriptor ()
Returns the abstract definition of this parameter.
void addChangeListener (final ChangeListener listener)
Adds the specified listener to the list of objects to inform when the value changed.
void removeChangeListener (final ChangeListener listener)
Removes the specified listener from the list of objects to inform when the value changed.
Protected Member Functions
final void fireValueChanged ()
Informs every listeners that the value changed.
Static Private Member Functions
static double defaultValue (final ParameterDescriptor< Double > descriptor)
Returns the default value from the given parameter descriptor, or.
static String getClassTypeError ()
Format an error message for illegal method call for the current value type.
Private Attributes
double value
The value, or.
Unit<?> unit
The unit of measure for the value, or.
Static Private Attributes
static final long serialVersionUID = 9027797654033417816L
Serial number for inter-operability with different versions.
Detailed Description
A parameter value as a floating point (double precision) number.
This class provides the same functionalities than Parameter, except that:
Values are always floating point numbers of type
double
.
When those conditions are meet,
FloatParameter
is slightly more efficient than
Parameter
since it avoid the creation of Double wrapper objects.
{
note for subclasses}
Except for the constructors, the equals(Object) and the hashCode() methods, all read and write operations ultimately delegates to the following methods:
All getter methods will invoke doubleValue() and - if needed - getUnit(), then performs their processing on the values returned by those methods.
All setter methods will first check the argument validity, then pass the values to the setValue(double, Unit) method.
Consequently, the above-cited methods provide single points that subclasses can override for modifying the behavior of all getter and setter methods.
Author
Martin Desruisseaux (IRD, Geomatys)
Version
3.20
See also
DefaultParameterDescriptor
ParameterGroup
Since
2.0
Deprecated:
Replaced by org.apache.sis.parameter.DefaultParameterValue.
Constructor & Destructor Documentation
FloatParameter() [1/2]
FloatParameter (final ParameterDescriptor< Double > descriptor)
Constructs a parameter from the specified descriptor.
Parameters
descriptor The abstract definition of this parameter.
Exceptions
IllegalArgumentException if the value class is not
Double.class
.
References FloatParameter.defaultValue(), Errors.format(), and Errors.Keys.IllegalClass_2.
Referenced by FloatParameter.equals().
{
         super(descriptor);
         final Class<Double> type = descriptor.getValueClass();
         final Class<Double> expected = Double.class;
         if (!expected.equals(type) && !Double.TYPE.equals(type)) {
             throw new IllegalArgumentException(Errors.format(
                     Errors.Keys.IllegalClass_2, type, expected));
         }
         value = defaultValue(descriptor);
         unit  = descriptor.getUnit();
     }
FloatParameter() [2/2]
FloatParameter (final ParameterDescriptor< Double > descriptor, final double value)
Constructs a parameter from the specified descriptor and value.
This convenience constructor is equivalents to the one-argument constructor followed by a call to setValue(double).
Parameters
descriptor The abstract definition of this parameter.
value The parameter value.
Exceptions
IllegalArgumentException if the value class is not
Double.class
.
References FloatParameter.setValue().
{
         this(descriptor);
         setValue(value);
     }
Member Function Documentation
addChangeListener()
void addChangeListener (final ChangeListener listener) inherited
Adds the specified listener to the list of objects to inform when the value changed.
Notes:
Change listeners are not serialized
Change listeners are not included in clone() cloned} object.
Parameters
listener The listener to add.
References Listeners::addListener(), and AbstractParameterValue< T >::listeners.
{
         listeners = Listeners.addListener(listener, listeners);
     }
booleanValue()
boolean booleanValue () throws IllegalStateException
Returns.
true
if the value is different from 0, or
false
otherwise.
Returns
The boolean value represented by this parameter.
Exceptions
IllegalStateException if the value is not defined and there is no default value.
References FloatParameter.doubleValue(), Errors.format(), and Errors.Keys.NoParameter_1.
{
         final double value = doubleValue();
         if (Double.isNaN(value)) {
             throw new IllegalStateException(Errors.format(Errors.Keys.NoParameter_1, getName(descriptor)));
         }
         return value != 0;
     }
clone()
FloatParameter clone ()
Returns a clone of this parameter.
References FloatParameter.clone().
Referenced by FloatParameter.clone().
{
         return (FloatParameter) super.clone();
     }
defaultValue()
static double defaultValue (final ParameterDescriptor< Double > descriptor) static private
Returns the default value from the given parameter descriptor, or.
NaN
if none.
Referenced by FloatParameter.FloatParameter(), and FloatParameter.setValue().
{
         final Number value = (Number) descriptor.getDefaultValue();
         return (value != null) ? value.doubleValue() : Double.NaN;
     }
doubleValue() [1/2]
double doubleValue (final Unit<?> unit) throws IllegalArgumentException
Returns the numeric value of the coordinate operation parameter in the specified unit of measure.
This convenience method applies unit conversions on the fly as needed.
Parameters
unit The unit of measure for the value to be returned.
Returns
The numeric value represented by this parameter after conversion to
unit
, or Double#NaN if none.
Exceptions
IllegalArgumentException if the specified unit is invalid for this parameter.
References FloatParameter.doubleValue(), Errors.format(), FloatParameter.getUnit(), and Errors.Keys.IncompatibleUnit_1.
{
         ensureNonNull("unit", unit);
         final Unit<?> thisUnit = getUnit();
         if (thisUnit == null) {
             throw unitlessParameter(descriptor);
         }
         final short expectedID = getUnitMessageID(thisUnit);
         if (getUnitMessageID(unit) != expectedID) {
             throw new IllegalArgumentException(Errors.format(expectedID, unit));
         }
         try {
             return thisUnit.getConverterToAny(unit).convert(doubleValue());
         } catch (IncommensurableException e) {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.IncompatibleUnit_1, unit), e);
         }
     }
doubleValue() [2/2]
double doubleValue ()
Returns the numeric value represented by this operation parameter.
The units of measurement are specified by getUnit().
{
note for subclasses}
All getter methods will invoke this
doubleValue()
method. Subclasses can override this method if they need to compute the value dynamically.
Returns
The numeric value represented by this parameter, or Double#NaN if none.
References FloatParameter.value.
Referenced by FloatParameter.booleanValue(), FloatParameter.doubleValue(), FloatParameter.doubleValueList(), FloatParameter.getValue(), FloatParameter.intValue(), and FloatParameter.stringValue().
{
         return value;
     }
doubleValueList() [1/2]
double [] doubleValueList (final Unit<?> unit) throws IllegalArgumentException
Wraps the value in an array of length 0 or 1.
Parameters
unit The unit of measure for the value to be returned.
Returns
The sequence of values represented by this parameter after conversion to type
double
and conversion to
unit
.
Exceptions
IllegalArgumentException if the specified unit is invalid for this parameter.
References FloatParameter.doubleValue().
{
         final double value = doubleValue(unit);
         return Double.isNaN(value) ? ArraysExt.EMPTY_DOUBLE: new double[] {value};
     }
doubleValueList() [2/2]
double [] doubleValueList ()
Wraps the value in an array of length 0 or 1.
Returns
The sequence of values represented by this parameter.
References FloatParameter.doubleValue().
{
         final double value = doubleValue();
         return Double.isNaN(value) ? ArraysExt.EMPTY_DOUBLE: new double[] {value};
     }
equals()
boolean equals (final Object object)
Compares the specified object with this parameter for equality.
Parameters
object The object to compare to
this
.
Returns
true
if both objects are equal.
References FloatParameter.FloatParameter(), and FloatParameter.value.
{
         if (super.equals(object)) {
             final FloatParameter that = (FloatParameter) object;
             return Double.doubleToLongBits(this.value) ==
                    Double.doubleToLongBits(that.value);
         }
         return false;
     }
fireValueChanged()
final void fireValueChanged () protected inherited
Informs every listeners that the value changed.
References Listeners::fireChanged(), and AbstractParameterValue< T >::listeners.
Referenced by FloatParameter::setValue().
{
         Listeners.fireChanged(this, listeners);
     }
getClassTypeError()
static String getClassTypeError () static private
Format an error message for illegal method call for the current value type.
References Errors.format(), and Errors.Keys.IllegalOperationForValueClass_1.
Referenced by FloatParameter.intValue(), FloatParameter.setValue(), and FloatParameter.valueFile().
{
         return Errors.format(Errors.Keys.IllegalOperationForValueClass_1, Double.class);
     }
getDescriptor()
ParameterDescriptor<T> getDescriptor () inherited
Returns the abstract definition of this parameter.
{
         return (ParameterDescriptor<T>) super.getDescriptor();
     }
getUnit()
Unit<?> getUnit ()
Returns the unit of measure of the doubleValue() parameter value}.
The default value is ParameterDescriptor#getUnit().
{
note for subclasses}
All getter methods which need unit information will invoke this
getUnit()
method. Subclasses can override this method if they need to compute the unit dynamically.
Returns
The unit of measure, or
null
if none.
References FloatParameter.unit.
Referenced by FloatParameter.doubleValue().
{
         return unit;
     }
getValue()
Double getValue ()
Returns the parameter value as a Double, or.
null
if none.
Returns
The parameter value as an object, or
null
if the current value is Double#NaN.
References FloatParameter.doubleValue().
{
         final double value = doubleValue();
         return Double.isNaN(value) ? null : Double.valueOf(value);
     }
hashCode()
int hashCode ()
Returns a hash value for this parameter.
Returns
The hash code value. This value doesn't need to be the same in past or future versions of this class.
References Utilities.hash().
{
         return Utilities.hash(value, super.hashCode());
     }
intValue()
int intValue () throws IllegalStateException
Returns the numeric value casted to integer.
If the current doubleValue() double value} can not be casted without precision loss, then this method throws an exception.
Returns
The numeric value represented by this parameter after conversion to type
int
.
Exceptions
InvalidParameterTypeException If the value can not be casted to integer.
IllegalStateException if the value is not defined and there is no default value.
References FloatParameter.doubleValue(), Errors.format(), FloatParameter.getClassTypeError(), and Errors.Keys.NoParameter_1.
Referenced by FloatParameter.intValueList().
{
         final double value = doubleValue();
         final int integer = (int) value;
         if (integer == value) {
             return integer;
         }
         final String name = getName(descriptor);
         if (Double.isNaN(value)) {
             // If a default value existed, it should has been copied by the constructor or setter methods.
             throw new IllegalStateException(Errors.format(Errors.Keys.NoParameter_1, name));
         }
         throw new InvalidParameterTypeException(getClassTypeError(), name);
     }
intValueList()
int [] intValueList () throws InvalidParameterTypeException
Wraps the value in an array of length 1.
Returns
The sequence of values represented by this parameter.
Exceptions
InvalidParameterTypeException If the value can not be casted to integer.
References FloatParameter.intValue().
{
         return new int[] {intValue()};
     }
removeChangeListener()
void removeChangeListener (final ChangeListener listener) inherited
Removes the specified listener from the list of objects to inform when the value changed.
Parameters
listener The listener to remove.
References AbstractParameterValue< T >::listeners, and Listeners::removeListener().
{
         listeners = Listeners.removeListener(listener, listeners);
     }
setValue() [1/6]
void setValue (final double value, final Unit<?> unit) throws InvalidParameterValueException
Sets the parameter value as a floating point and its associated unit.
The default implementation verifies the arguments validity, then stores the given values.
{
note for subclasses}
This method is invoked by all other
setXXX(…)
methods. Subclasses can override this method if they want to perform more processing on the value before its storage, or to be notified about value changes.
Parameters
value The parameter value.
unit The new unit of measurement.
Exceptions
InvalidParameterValueException if the value is illegal for some reason (for example a value out of range).
References FloatParameter.defaultValue(), AbstractParameterValue< Double >.fireValueChanged(), Errors.format(), Errors.Keys.IncompatibleUnit_1, FloatParameter.unit, and FloatParameter.value.
Referenced by FloatParameter.FloatParameter(), and FloatParameter.setValue().
{
         double converted = value;
         @SuppressWarnings("unchecked") // Checked by constructor.
         final ParameterDescriptor<Double> descriptor = (ParameterDescriptor<Double>) this.descriptor;
         final Unit<?> targetUnit = descriptor.getUnit();
         if (targetUnit != unit) {
             if (targetUnit == null) {
                 throw unitlessParameter(descriptor);
             } else {
                 ensureNonNull("unit", unit);
                 final short expectedID = getUnitMessageID(targetUnit);
                 if (getUnitMessageID(unit) != expectedID) {
                     throw new InvalidParameterValueException(Errors.format(expectedID, unit),
                             descriptor.getName().getCode(), value);
                 }
                 try {
                     converted = unit.getConverterToAny(targetUnit).convert(value);
                 } catch (IncommensurableException e) {
                     throw new IllegalArgumentException(Errors.format(Errors.Keys.IncompatibleUnit_1, unit), e);
                 }
             }
         }
         /*
          * Really store the original value, not the converted one, because we store the given
          * unit as well. Conversions will be applied on the fly by the getter method if needed.
          */
         if (Double.isNaN(value)) {
             this.value = defaultValue(descriptor);
         } else {
             ensureValidValue(descriptor, converted);
             this.value = value;
         }
         this.unit = unit; // Store only after successful validation.
         fireValueChanged();
     }
setValue() [2/6]
void setValue (final double value) throws InvalidParameterValueException
Sets the parameter value as a floating point.
The default implementation delegates to setValue(double, Unit).
Parameters
value The parameter value.
Exceptions
InvalidParameterValueException if the value is illegal for some reason (for example a value out of range).
References FloatParameter.setValue().
{
         setValue(value, unit);
     }
setValue() [3/6]
void setValue (final int value) throws InvalidParameterValueException
Sets the parameter value as an integer.
The default implementation delegates to setValue(double).
Parameters
value The parameter value.
Exceptions
InvalidParameterValueException if the value is illegal for some reason (for example a value out of range).
References FloatParameter.setValue().
{
         setValue((double) value);
     }
setValue() [4/6]
void setValue (final boolean value) throws InvalidParameterValueException
Sets the parameter value as a boolean.
The default implementation delegates to setValue(double) with value 1 for
true
or 0 or
false
.
Parameters
value The parameter value.
Exceptions
InvalidParameterValueException if the boolean type is inappropriate for this parameter.
References FloatParameter.setValue().
{
         setValue(value ? 1.0 : 0.0);
     }
setValue() [5/6]
void setValue (final Object value) throws InvalidParameterValueException
Sets the parameter value as a Double object.
The default implementation ensures that the given value is a Number, then delegates to setValue(double).
Parameters
value The parameter value, or
null
for Double#NaN.
Exceptions
InvalidParameterValueException if the type of
value
is inappropriate for this parameter, or if the value is illegal for some other reason (for example the value is numeric and out of range).
References FloatParameter.getClassTypeError(), and FloatParameter.setValue().
{
         final double number;
         if (value == null) {
             number = Double.NaN;
         } else if (value instanceof Number) {
             number = ((Number) value).doubleValue();
         } else {
             throw new InvalidParameterValueException(getClassTypeError(), getName(descriptor), value);
         }
         setValue(number);
     }
setValue() [6/6]
void setValue (final double [] values, final Unit<?> unit) throws InvalidParameterValueException
If the length of the given array is 1, delegates to setValue(double, Unit).
Otherwise throws an exception, since this parameter does not accept arbitrary arrays.
References FloatParameter.getClassTypeError(), and FloatParameter.setValue().
{
         ensureNonNull("values", values);
         if (values.length == 1) {
             setValue(values[0], unit);
         } else {
             throw new InvalidParameterValueException(getClassTypeError(), getName(descriptor), values);
         }
     }
stringValue()
String stringValue () throws IllegalStateException
Returns the string representation of the value.
Returns
The string value represented by this parameter.
Exceptions
IllegalStateException if the value is not defined and there is no default value.
References FloatParameter.doubleValue(), Errors.format(), and Errors.Keys.NoParameter_1.
{
         final double value = doubleValue();
         if (Double.isNaN(value)) {
             throw new IllegalStateException(Errors.format(Errors.Keys.NoParameter_1, getName(descriptor)));
         }
         return String.valueOf(value);
     }
valueFile()
URI valueFile () throws InvalidParameterTypeException
Always throws an exception, since this parameter is not an URI.
Returns
Never return.
Exceptions
InvalidParameterTypeException The value is not a reference to a file or an URI.
References FloatParameter.getClassTypeError().
{
         throw new InvalidParameterTypeException(getClassTypeError(), getName(descriptor));
     }
Member Data Documentation
serialVersionUID
final long serialVersionUID = 9027797654033417816L static private
Serial number for inter-operability with different versions.
unit
Unit<?> unit private
The unit of measure for the value, or.
null
if it doesn't apply. Except for the constructors, the equals(Object) and the hashCode() methods, this field is read only by getUnit() and written by setValue(double, Unit).
Referenced by FloatParameter.getUnit(), and FloatParameter.setValue().
value
double value private
The value, or.
NaN
if undefined. Except for the constructors, the equals(Object) and the hashCode() methods, this field is read only by doubleValue() and written by setValue(double, Unit).
Referenced by FloatParameter.doubleValue(), FloatParameter.equals(), and FloatParameter.setValue().