jena-geo: DefaultDataSource Class Reference
DefaultDataSource Class Reference
A data source which get the connection from a DriverManager.
Public Member Functions
DefaultDataSource (final String url)
Creates a data source for the given URL.
Connection getConnection () throws SQLException
Delegates to DriverManager.
Connection getConnection (String username, String password) throws SQLException
Delegates to DriverManager.
PrintWriter getLogWriter ()
Delegates to DriverManager.
void setLogWriter (final PrintWriter out)
Delegates to DriverManager.
int getLoginTimeout ()
Delegates to DriverManager.
void setLoginTimeout (final int seconds)
Delegates to DriverManager.
Public Attributes
final String url
The URL to use for connecting to the database.
Static Public Attributes
static final Logger LOGGER = Logging.getLogger("org.geotoolkit.sql")
The logger where to report the JDBC driver version.
Static Package Functions
static Connection log (final Connection connection, final Class<?> source) throws SQLException
Logs the driver version if this is the first time we get a connection for that driver.
Static Private Attributes
static final Set< String > DRIVERS = new HashSet<>()
The driver names of the connection returned by.
Detailed Description
A data source which get the connection from a DriverManager.
Author
Martin Desruisseaux (Geomatys)
Guilhem Legal (Geomatys)
Version
3.18
Since
3.00
Constructor & Destructor Documentation
DefaultDataSource()
DefaultDataSource (final String url)
Creates a data source for the given URL.
Parameters
url The URL to use for connecting to the database.
References DefaultDataSource.url.
Referenced by DefaultDataSource.setLoginTimeout().
{
         ArgumentChecks.ensureNonNull("url", url);
         this.url = url;
     }
Member Function Documentation
getConnection() [1/2]
Connection getConnection () throws SQLException
Delegates to DriverManager.
Exceptions
SQLException If the connection can not be established.
References DefaultDataSource.log().
{
         return log(DriverManager.getConnection(url), DefaultDataSource.class);
     }
getConnection() [2/2]
Connection getConnection (String username, String password) throws SQLException
Delegates to DriverManager.
Exceptions
SQLException If the connection can not be established.
References DefaultDataSource.log().
{
         return log(DriverManager.getConnection(url, username, password), DefaultDataSource.class);
     }
getLoginTimeout()
int getLoginTimeout ()
Delegates to DriverManager.
{
         return DriverManager.getLoginTimeout();
     }
getLogWriter()
PrintWriter getLogWriter ()
Delegates to DriverManager.
{
         return DriverManager.getLogWriter();
     }
log()
static Connection log (final Connection connection, final Class<?> source) throws SQLException static package
Logs the driver version if this is the first time we get a connection for that driver.
References DefaultDataSource.DRIVERS, Loggings.format(), and Loggings.Keys.JdbcDriverVersion_3.
Referenced by DefaultDataSource.getConnection().
{
         if (LOGGER.isLoggable(Level.CONFIG)) {
             final DatabaseMetaData metadata = connection.getMetaData();
             final String name = metadata.getDriverName();
             final boolean log;
             synchronized (DRIVERS) {
                 log = DRIVERS.add(name);
             }
             if (log) {
                 final LogRecord record = Loggings.format(Level.CONFIG, Loggings.Keys.JdbcDriverVersion_3,
                         name, metadata.getDriverMajorVersion(), metadata.getDriverMinorVersion());
                 record.setLoggerName(LOGGER.getName());
                 record.setSourceClassName(source.getName());
                 record.setSourceMethodName("getConnection");
                 LOGGER.log(record);
             }
         }
         return connection;
     }
setLoginTimeout()
void setLoginTimeout (final int seconds)
Delegates to DriverManager.
It is better to avoid calling this method since it has a system-wide effect.
References DefaultDataSource.DefaultDataSource(), Dialect.forURL(), DefaultDataSource.LOGGER, Dialect.shutdown(), and DefaultDataSource.url.
{
         DriverManager.setLoginTimeout(seconds);
     }
setLogWriter()
void setLogWriter (final PrintWriter out)
Delegates to DriverManager.
It is better to avoid calling this method since it has a system-wide effect.
{
         DriverManager.setLogWriter(out);
     }
Member Data Documentation
DRIVERS
final Set<String> DRIVERS = new HashSet<>() static private
The driver names of the connection returned by.
DefaultDataSource
. This is used for logging purpose only.
Referenced by DefaultDataSource.log().
LOGGER
final Logger LOGGER = Logging.getLogger("org.geotoolkit.sql") static
The logger where to report the JDBC driver version.
Note that the logger name intentionally hides the
"internal"
part of the package name.
Referenced by DefaultDataSource.setLoginTimeout().
url
final String url
The URL to use for connecting to the database.
This field can not be
null
.
Referenced by DefaultDataSource.DefaultDataSource(), and DefaultDataSource.setLoginTimeout().