jena-geo: FactoryMethod Class Reference
FactoryMethod Class Reference
The method used for creating an instance of some specific class using a factory.
Public Member Functions
boolean equals (final Object other)
Returns.
int hashCode ()
Defined for consistency with equals but not used.
Package Functions
Object create (Map< String,?> properties) throws FactoryException
Invokes the.
Static Package Functions
static FactoryMethod find (final Class<?> type, final Object[] factories)
Creates a new.
Static Package Attributes
static final FactoryMethod NULL = new FactoryMethod(null, null)
A dummy.
Private Member Functions
FactoryMethod (final Method method, final Object factory)
Creates a new.
Static Private Member Functions
static Class<?> bounds (Type type)
Returns the upper bounds of the given type.
Private Attributes
final Method method
The method to invoke on a factory.
final Object factory
The factory instance on which to invoke the method.
Detailed Description
The method used for creating an instance of some specific class using a factory.
This is used by MetadataFactory only.
Factory method starts with create, and their first parameter type is
Map
,
Map<String,?>
or
Map<String,Object>
.
Author
Martin Desruisseaux (Geomatys)
Version
3.03
Since
3.03
Constructor & Destructor Documentation
FactoryMethod()
FactoryMethod (final Method method, final Object factory) private
Creates a new.
FactoryMethod
object.
Parameters
method The method to invoke on a factory.
factory The factory instance on which to invoke the method.
References FactoryMethod.factory, and FactoryMethod.method.
Referenced by FactoryMethod.equals(), and FactoryMethod.find().
{
         this.method  = method;
         this.factory = factory;
     }
Member Function Documentation
bounds()
static Class<?> bounds (Type type) static private
Returns the upper bounds of the given type.
The type must be either a (} or a WildcardType}. We assume that no other type can occur in this implementation.
Referenced by FactoryMethod.find().
{
         while (type instanceof WildcardType) {
             final Type[] types = ((WildcardType) type).getUpperBounds();
             if (types.length == 1) {
                 type = types[0];
             }
         }
         return (Class<?>) type;
     }
create()
Object create (Map< String,?> properties) throws FactoryException package
Invokes the.
Factory.create(Map, ...)
method with the given properties. The values in the given map that are assignable to the parameter type expected by the factory method are extracted from the map and assigned to the parameter array.
In the special case where this
FactoryMethod
is NULL, this method returns
null
.
Referenced by MetadataFactory.create().
{
         if (method == null) {
             return null;
         }
         final Class<?>[] types = method.getParameterTypes();
         final Object[] parameters = new Object[types.length];
         if (types.length > 1) {
             final Map<String,Object> reduced = new LinkedHashMap<>(properties);
             properties = reduced;
             for (int i=1; i<types.length; i++) {
                 final Class<?> expected = types[i];
                 for (final Iterator<Object> it=reduced.values().iterator(); it.hasNext();) {
                     final Object value = it.next();
                     if (expected.isInstance(value)) {
                         parameters[i] = value;
                         it.remove();
                         break;
                     }
                 }
             }
         }
         parameters[0] = properties;
         try {
             return method.invoke(factory, parameters);
         } catch (IllegalAccessException e) {
             // Should never happen, because we asked for public methods only.
             throw new AssertionError(e);
         } catch (InvocationTargetException e) {
             final Throwable cause = e.getCause();
             if (cause instanceof FactoryException) {
                 throw (FactoryException) cause;
             }
             throw new FactoryException(cause.getLocalizedMessage(), cause);
         }
     }
equals()
boolean equals (final Object other)
Returns.
true
if the given object is equals to this factory method.
References FactoryMethod.factory, FactoryMethod.FactoryMethod(), and FactoryMethod.method.
Referenced by MetadataFactory.create().
{
         if (other instanceof FactoryMethod) {
             final FactoryMethod that = (FactoryMethod) other;
             return method.equals(that.method) && factory == that.factory;
         }
         return false;
     }
find()
static FactoryMethod find (final Class<?> type, final Object [] factories) static package
Creates a new.
FactoryMethod
instance for creating an object of the given type from the given factory. The first suitable factory is used. If no suitable factory is found, then this method returns
null
.
Parameters
type The type of the object to create.
factories The factories to try.
Returns
A new
FactoryMethod
, or
null
if none.
References FactoryMethod.bounds(), and FactoryMethod.FactoryMethod().
Referenced by MetadataFactory.create().
{
         for (final Object factory : factories) {
             for (final Method method : factory.getClass().getMethods()) {
                 if (method.isSynthetic() || method.isAnnotationPresent(Deprecated.class)) {
                     // Ignores synthetic and deprecated methods.
                     continue;
                 }
                 final String name = method.getName();
                 if (!name.startsWith("create")) {
                     continue;
                 }
                 if (!type.isAssignableFrom(method.getReturnType())) {
                     continue;
                 }
                 Type[] types = method.getGenericParameterTypes();
                 if (types.length == 0) {
                     continue;
                 }
                 /*
                  * We have found a "create" method with a suitable return type. Now check
                  * the parameters. The first one must be either the Map raw parameter type,
                  * the Map<String,?> type or the Map<String,Object> one.
                  */
                 final Type mapType = types[0];
                 if (mapType != Map.class) {
                     if (!(mapType instanceof ParameterizedType)) {
                         continue;
                     }
                     types = ((ParameterizedType) mapType).getActualTypeArguments();
                     if (types.length != 2 ||
                             !bounds(types[0]).isAssignableFrom(String.class) ||
                             !bounds(types[1]).isAssignableFrom(Object.class))
                     {
                         continue;
                     }
                     return new FactoryMethod(method, factory);
                 }
             }
         }
         return null;
     }
hashCode()
int hashCode ()
Defined for consistency with equals but not used.
{
         return method.hashCode() ^ System.identityHashCode(factory);
     }
Member Data Documentation
factory
final Object factory private
The factory instance on which to invoke the method.
Referenced by FactoryMethod.equals(), and FactoryMethod.FactoryMethod().
method
final Method method private
The method to invoke on a factory.
Referenced by FactoryMethod.equals(), and FactoryMethod.FactoryMethod().
NULL
final FactoryMethod NULL = new FactoryMethod(null, null) static package
A dummy.
FactoryMethod
used by MetadataFactory as a sentinel values when we have determined that there is no factory method available.
Referenced by MetadataFactory.create().