jena-geo: DirectoryWatcher Class Reference
DirectoryWatcher Class Reference
Watch for file-system modification for a given folder.
Public Member Functions
DirectoryWatcher () throws IOException
Prepare watcher for NON-recursive survey.
DirectoryWatcher (final boolean recursive) throws IOException
Initialize watching service.
void setFileFilter (final DirectoryStream.Filter< Path > filter)
Provide a filter to specify if a file must processed or ignored at change.
DirectoryStream.Filter< Path > getFileFilter ()
synchronized void register (Path... paths) throws IOException, SecurityException
Register a directory to the WatchService.
synchronized void unregister (Path... paths)
void start ()
void stop ()
synchronized void close () throws IOException
void addPathChangeListener (final PathChangeListener listener)
void removePathChangeListener (final PathChangeListener toForget)
Public Attributes
final boolean recursive
True if we listen changes of all the file tree, or only for the direct children of the registered folders.
Protected Member Functions
Path getUnregisteredParent (final Path target)
void firePathChanged (Path target, WatchEvent.Kind kind, boolean isDirectory, int count) throws Exception
Each time the watch service will catch an event on a file/folder, it will use this method.
Protected Attributes
final HashSet< Path > roots = new HashSet<>()
final HashSet< Path > unregistered = new HashSet<>()
DirectoryStream.Filter< Path > fileFilter = null
Filter used to determine which files must be ignored and which must be used.
final EventListenerList listeners = new EventListenerList()
Private Member Functions
final void registerDir (final Path dir) throws IOException, SecurityException
Register a directory along with all its sub-directories to the WatchService.
void watch ()
Start to survey the registered folders (see register(java.nio.file.Path...)}.
Private Attributes
final WatchService service
final Thread watchThread
final Object fileFilterLock = new Object()
Static Private Attributes
static final Logger LOGGER = Logging.getLogger("org.geotoolkit.io")
Detailed Description
Watch for file-system modification for a given folder.
There's a recursive mode to allow watch of all sub-directories as well. If the recursive mode is activated, when a new directory is created in the watched one, it will be registered for watching, as all its sub-directories.
Watched folders are registered for the standard event types defined by java.nio.file.StandardWatchEventKinds.
Use of the class :
Build a new watcher, with a boolean argument to specify if we want recursive survey (true) or not (false) : final DirectoryWatcher watcher = new DirectoryWatcher(true) {..your implementation...};
Give it the separate folders to work on : final Path toWatch1, toWatch2; watcher.register(toWatch1, toWatch2);
Your watcher is ready to go, call the start()} method to launch the survey. /!\ It launches an asynchronous survey in a separate thread.
To stop|pause the watching, you just have to call stop()} method.
Finally, when you're done with survey, please close your watcher using close()}.
N.B : Thread-safe implementation.
Author
Alexis Manin (Geomatys)
Constructor & Destructor Documentation
DirectoryWatcher() [1/2]
DirectoryWatcher () throws IOException
Prepare watcher for NON-recursive survey.
Exceptions
IOException
{
         this(false);
     }
DirectoryWatcher() [2/2]
DirectoryWatcher (final boolean recursive) throws IOException
Initialize watching service.
Parameters
recursive True if we want to watch over the entire file tree, false if we want to be notified only for direct childrens of root folder(s).
Exceptions
IOException If an error occurred while building underlying java.nio.file.WatchService.
References DirectoryWatcher.recursive, and DirectoryWatcher.watch().
{
         service = FileSystems.getDefault().newWatchService();
         this.recursive = recursive;
         watchThread = new Thread(new Runnable() {
             @Override
             public void run() {
                 watch();
             }
         });
         watchThread.setDaemon(true);
     }
Member Function Documentation
addPathChangeListener()
void addPathChangeListener (final PathChangeListener listener)
{
         ArgumentChecks.ensureNonNull("Event listener", listener);
         listeners.add(PathChangeListener.class, listener);
     }
close()
synchronized void close () throws IOException
References DirectoryWatcher.roots, and DirectoryWatcher.stop().
{
         stop();
         synchronized (roots) {
             roots.clear();
         }
         service.close();
     }
firePathChanged()
void firePathChanged (Path target, WatchEvent.Kind kind, boolean isDirectory, int count) throws Exception protected
Each time the watch service will catch an event on a file/folder, it will use this method.
It allows user defining its own processes over file changes.
N.B : If an exception is thrown by a listener, it is stored and thrown back after all listeners have been executed. If another listener throw an exception, it is stored via java.lang.Exception#addSuppressed(Throwable).
Parameters
target The file which have been triggered for changes.
kind The kind of change which applied on the file. Most likely one of the java.nio.file.StandardWatchEventKinds.
isDirectory A boolean which is set to true if the input path is a directory, false otherwise.
count Number of times the same event occurred.
Exceptions
java.lang.Exception if a listener throw an exception.
Referenced by DirectoryWatcher.watch().
{
         final PathChangedEvent evt = new PathChangedEvent(this, target, kind, isDirectory, count);
         Exception traced = null;
         for (PathChangeListener l : listeners.getListeners(PathChangeListener.class)) {
             try {
                 l.pathChanged(evt);
             } catch (Exception e) {
                 if (traced == null) {
                     traced = e;
                 } else {
                     traced.addSuppressed(e);
                 }
             }
         }
         if (traced != null) {
             throw traced;
         }
     }
getFileFilter()
DirectoryStream.Filter<Path> getFileFilter ()
Returns
the filter used to know if we must process or not a file. Null if no filtering applied.
References DirectoryWatcher.fileFilter, and DirectoryWatcher.fileFilterLock.
{
         synchronized (fileFilterLock) {
             return fileFilter;
         }
     }
getUnregisteredParent()
Path getUnregisteredParent (final Path target) protected
References DirectoryWatcher.unregistered.
Referenced by DirectoryWatcher.watch().
{
         synchronized (unregistered) {
             for (Path path : unregistered) {
                 if (target.startsWith(path) || path.equals(target)) {
                     return path;
                 }
             }
         }
         return null;
     }
register()
synchronized void register (Path... paths) throws IOException, SecurityException
Register a directory to the WatchService.
If it does not exists, we'll try to create it.
Parameters
paths A list of folders to watch. If one does not exists, we will try to create it.
Exceptions
java.io.IOException If an input folder does not exists and cannot be created, or if an error occurred trying to register it or one of its children.
java.nio.file.FileAlreadyExistsException If an input path denotes a file and not a folder.
SecurityException If an input directory cannot be watched due to a lack of permission.
References DirectoryWatcher.registerDir().
{
         for (Path toWatch : paths) {
             if (!roots.contains(toWatch)) {
                 if (!Files.isDirectory(toWatch)) {
                     Files.createDirectories(toWatch);
                 }
                 registerDir(toWatch);
                 roots.add(toWatch);
             }
             // In case someone asked for its removal before.
             unregistered.remove(toWatch);
         }
     }
registerDir()
final void registerDir (final Path dir) throws IOException, SecurityException private
Register a directory along with all its sub-directories to the WatchService.
Referenced by DirectoryWatcher.register(), and DirectoryWatcher.watch().
{
         dir.register(service, ENTRY_CREATE, ENTRY_DELETE, ENTRY_MODIFY);
         if (recursive) {
             Files.walkFileTree(dir, new SimpleFileVisitor<Path>() {
                 @Override
                 public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs)
                         throws IOException {
                     dir.register(service, ENTRY_CREATE, ENTRY_DELETE, ENTRY_MODIFY);
                     return FileVisitResult.CONTINUE;
                 }
             });
         }
     }
removePathChangeListener()
void removePathChangeListener (final PathChangeListener toForget)
{
         ArgumentChecks.ensureNonNull("Event listener", toForget);
         listeners.remove(PathChangeListener.class, toForget);
     }
setFileFilter()
void setFileFilter (final DirectoryStream.Filter< Path > filter)
Provide a filter to specify if a file must processed or ignored at change.
Parameters
filter A PathMatcher whose java.nio.file.PathMatcher#matches(java.nio.file.Path) method return true if we must process the path in parameter. If null, all changed files are processed.
References DirectoryWatcher.fileFilterLock.
{
         synchronized (fileFilterLock) {
             fileFilter = filter;
         }
     }
start()
void start ()
{
         watchThread.start();
     }
stop()
void stop ()
Referenced by DirectoryWatcher.close().
{
         watchThread.interrupt();
     }
unregister()
synchronized void unregister (Path... paths)
{
         for (Path dir : paths) {
             unregistered.add(dir);
             // in case it's a previously registered folder which is queried for removal, and not one of its children.
             roots.remove(dir);
         }
     }
watch()
void watch () private
Start to survey the registered folders (see register(java.nio.file.Path...)}.
References DirectoryWatcher.fileFilterLock, DirectoryWatcher.firePathChanged(), DirectoryWatcher.getUnregisteredParent(), DirectoryWatcher.registerDir(), DirectoryWatcher.roots, and DirectoryWatcher.unregistered.
Referenced by DirectoryWatcher.DirectoryWatcher().
{
         final Thread currentThread = Thread.currentThread();
         while (!currentThread.isInterrupted()) {
             final WatchKey key;
             try {
                 key = service.take();
             } catch (ClosedWatchServiceException e) {
                 LOGGER.log(Level.INFO, "Folder watcher has been closed !");
                 break;
             } catch (InterruptedException e) {
                 LOGGER.log(Level.INFO, "Folder watcher has been interrupted !");
                 currentThread.interrupt();
                 break;
             }
             // Do the check here, because we don't know how many time we have waited for an event, nor what happened.
             if (currentThread.isInterrupted()) {
                 break;
             }
             // If could happen if we've cancelled if and it was already waiting for new events. We just have to ignore it.
             if (!key.isValid()) {
                 continue;
             }
             // TODO : Change if an implementation of watchable other than path appears in the jvm.
             final Path watchedPath = (Path) key.watchable();
             try {
                 // Check if we must stop following the current folder.
                 final Path dereferenced = getUnregisteredParent(watchedPath);
                 if (dereferenced != null) {
                     key.cancel();
                     // If current event path represents the exact path to remove, not just a children, we can forget about it.
                     if (dereferenced.equals(watchedPath)) {
                         synchronized (unregistered) {
                             unregistered.remove(dereferenced);
                         }
                     }
                     continue;
                 }
                 for (WatchEvent event : key.pollEvents()) {
                     WatchEvent.Kind kind = event.kind();
                     // Watch service received too many events from the system and cannot handle them.
                     if (kind == OVERFLOW) {
                         LOGGER.log(Level.INFO, "Too many changes happened to the watched directory. Unable to catch them all.");
                         continue;
                     }
                     try {
                         Path target;
                         final Object context = event.context();
                         if (context instanceof Path) {
                             target = (Path) context;
                         } else if (context instanceof File) {
                             target = ((File) context).toPath();
                         } else {
                             // Create an exception to be able to retrieve code fragment from message, which will allow to quickly add new cases if needed.
                             final IllegalArgumentException e = new IllegalArgumentException("Watch event is of unknown type (need Path or File).");
                             LOGGER.log(Level.INFO, "Watch event skipped.", e);
                             continue;
                         }
                         target = watchedPath.resolve(target);
                         final boolean isDirectory = Files.isDirectory(target);
                         // Add the new directory to the watched ones if we're on recursive mode.
                         if (isDirectory && recursive && kind == ENTRY_CREATE) {
                             try {
                                 registerDir(target);
                             } catch (IOException e) {
                                 LOGGER.log(Level.WARNING, "Newly created folder cannot be watched : " + target, e);
                             }
                         }
                         final boolean matchFileFilter;
                         synchronized (fileFilterLock) {
                             matchFileFilter = (fileFilter == null || fileFilter.accept(target));
                         }
                         if (matchFileFilter) {
                             firePathChanged(target, kind, isDirectory, event.count());
                         }
                     } catch (Exception e) {
                         // We don't want the entire mechanism to be destroyed for a simple error on a file.
                         LOGGER.log(Level.WARNING, "An error occurred while processing " + event.context() + " for the event " + kind, e);
                     }
                 }
             } finally {
             /* Finished work with key, reset it. If we cannot, it means the bound directory is not watched anymore, we can
                remove it from our list of surveyed folders.
              */
                 if (!key.reset()) {
                     synchronized (roots) {
                         roots.remove(watchedPath);
                     }
                 }
             }
         }
     }
Member Data Documentation
fileFilter
DirectoryStream.Filter<Path> fileFilter = null protected
Filter used to determine which files must be ignored and which must be used.
Referenced by DirectoryWatcher.getFileFilter().
fileFilterLock
final Object fileFilterLock = new Object() private
Referenced by DirectoryWatcher.getFileFilter(), DirectoryWatcher.setFileFilter(), and DirectoryWatcher.watch().
listeners
final EventListenerList listeners = new EventListenerList() protected
LOGGER
final Logger LOGGER = Logging.getLogger("org.geotoolkit.io") static private
recursive
final boolean recursive
True if we listen changes of all the file tree, or only for the direct children of the registered folders.
Referenced by DirectoryWatcher.DirectoryWatcher().
roots
final HashSet<Path> roots = new HashSet<>() protected
Referenced by DirectoryWatcher.close(), and DirectoryWatcher.watch().
service
final WatchService service private
unregistered
final HashSet<Path> unregistered = new HashSet<>() protected
Referenced by DirectoryWatcher.getUnregisteredParent(), and DirectoryWatcher.watch().
watchThread
final Thread watchThread private