jena-geo: IndentedLineWriter Class Reference
IndentedLineWriter Class Reference
A writer that put some spaces in front of every lines.
Classes
class Formatter
The Apache SIS formatter on which to delegate the work, with delegation of onLineBegin(boolean) calls to the Geotk beginNewLine().
Public Member Functions
IndentedLineWriter (final Writer out)
Constructs a stream which will add spaces in front of each line.
IndentedLineWriter (final Writer out, final int width)
Constructs a stream which will the given amount of spaces in front of each line.
int getIdentation ()
Returns the current indentation.
void setIndentation (final int width)
Sets the indentation to the specified value.
String getMargin ()
Returns the margin which is written at the beginning of every line.
void setMargin (final String margin)
Sets the margin to be written at the beginning of every line.
String toString ()
Returns a string representation if this writer.
Protected Member Functions
void beginNewLine () throws IOException
Invoked when a new line is beginning.
Package Functions
final void beginNewLine (final Writer writeTo) throws IOException
Bridge between the Apache SIS and the Geotk API.
String content ()
Returns the content of the wrapped writer, or.
Static Package Functions
static String content (final Writer out)
Returns the content of the given writer, or.
Private Member Functions
IndentedLineWriter (final Formatter formatter)
Workaround for RFE #4093999 ("Relax constraint on placement of this()/super() call in constructors")
Private Attributes
String margin = ""
A string with a length equal to the indentation.
Detailed Description
A writer that put some spaces in front of every lines.
The indentation is initially set to 0 spaces. Users must invoke setIndentation(int) or setMargin(String) in order to set a different value.
Author
Martin Desruisseaux (IRD, Geomatys)
Version
3.18
Since
2.4
Deprecated:
Moved to Apache SIS as LineAppender.
Constructor & Destructor Documentation
IndentedLineWriter() [1/3]
IndentedLineWriter (final Formatter formatter) private
Workaround for RFE #4093999 ("Relax constraint on placement of this()/super() call in constructors")
References IndentedLineWriter.Formatter.enclosing.
{
         super(IO.asWriter(formatter));
         formatter.enclosing = this;
     }
IndentedLineWriter() [2/3]
IndentedLineWriter (final Writer out)
Constructs a stream which will add spaces in front of each line.
The setIndentation(int) or setMargin(String) method must be invoked after this constructor in order to specify the amount of spaces to add.
Parameters
out The underlying stream to write to.
{
         this(new Formatter(out));
     }
IndentedLineWriter() [3/3]
IndentedLineWriter (final Writer out, final int width)
Constructs a stream which will the given amount of spaces in front of each line.
This is a convenience method invoking setIndentation(int) right after the construction.
Parameters
out The underlying stream to write to.
width The indentation.
Since
3.00
{
         this(out);
         setIndentation(width);
     }
Member Function Documentation
beginNewLine() [1/2]
final void beginNewLine (final Writer writeTo) throws IOException package
Bridge between the Apache SIS and the Geotk API.
Referenced by IndentedLineWriter.Formatter.onLineBegin().
{
         final Writer old = out;
         out = writeTo;
         try {
             beginNewLine();
         } finally {
             out = old;
         }
     }
beginNewLine() [2/2]
void beginNewLine () throws IOException protected
Invoked when a new line is beginning.
The default implementation writes the amount of spaces specified by the last call to setIndentation.
Exceptions
IOException If an I/O error occurs
{
         out.write(margin);
     }
content() [1/2]
static String content (final Writer out) static package inherited
Returns the content of the given writer, or.
null
if none.
{
         if (out instanceof StringWriter) {
             return out.toString();
         }
         if (out instanceof FilterWriter) {
             return ((FilterWriter) out).content();
         }
         final CharSequence cs = IO.content(out);
         if (cs != null) {
             return cs.toString();
         }
         return null;
     }
content() [2/2]
String content () package inherited
Returns the content of the wrapped writer, or.
null
if none.
Referenced by FilterWriter.toString().
                      {
         return content(out);
     }
getIdentation()
int getIdentation ()
Returns the current indentation.
This is either the value given to the last call to setIndentation(int) method, or the length of the string given to the setMargin(String) method.
Returns
The current indentation.
{
         synchronized (lock) {
             return margin.length();
         }
     }
getMargin()
String getMargin ()
Returns the margin which is written at the beginning of every line.
The default value is an empty string. This value can be modified either explicitely by a call to setMargin(String), or implicitly by a call to setIndentation(int).
Returns
The string which is inserted at the beginning of every lines.
Since
3.18
{
         synchronized (lock) {
             return margin;
         }
     }
setIndentation()
void setIndentation (final int width)
Sets the indentation to the specified value.
This method will setMargin(String) defines a margin} as the given number of white spaces.
Parameters
width The number of space to insert at the beginning of every line.
Referenced by PropertyEpsgFactory.reportDuplicates().
{
         synchronized (lock) {
             margin = CharSequences.spaces(width).toString();
         }
     }
setMargin()
void setMargin (final String margin)
Sets the margin to be written at the beginning of every line.
Parameters
margin The string to be inserted at the beginning of every lines.
Since
3.18
{
         ArgumentChecks.ensureNonNull("margin", margin);
         synchronized (lock) {
             this.margin = margin;
         }
     }
toString()
String toString () inherited
Returns a string representation if this writer.
References FilterWriter.content().
{
         String s = content(out);
         if (s == null) {
             s = super.toString();
         }
         return s;
     }
Member Data Documentation
margin
String margin = "" private
A string with a length equal to the indentation.