jena-geo: DerbySqlScriptRunner Class Reference
DerbySqlScriptRunner Class Reference
An sql script runner replacing the boolean used in postgres by small Interger used by derby.
Public Member Functions
DerbySqlScriptRunner (final Connection c) throws SQLException
String getEncoding ()
Returns the encoding of SQL scripts, or.
void setEncoding (final String encoding)
Sets the encoding of SQL scripts.
boolean accept (final File directory, final String name)
Returns.
int run (final File file) throws IOException, SQLException
Run the SQL script read from the given file or directory.
final int run (final InputStream in) throws IOException, SQLException
Run the script from the given input stream.
final int run (final LineNumberReader in) throws IOException, SQLException
Run the script from the given reader.
final int run (final String statement) throws IOException, SQLException
Convenience method invoking run(LineNumberReader) for the given SQL statement.
void close (final boolean vacuum) throws SQLException
Closes the statement used by this runner.
String getCurrentPosition ()
Returns the current position (current file and current line in that file).
String toString ()
Returns a string representation of this runner for debugging purpose.
Static Public Attributes
static final char END_OF_STATEMENT = ';'
The character at the end of statements.
static final char QUOTE = '\''
The quote character expected to be found in the SQL script.
static final char IDENTIFIER_QUOTE = '"'
The quote character for identifiers expected to be found in the SQL script.
Protected Member Functions
int execute (final StringBuilder sb) throws SQLException, IOException
execute SQL code.
Connection getConnection () throws SQLException
Returns the connection.
String selectVersion (final String[] versions)
If there is many versions of the SQL script, select the version to run.
Protected Attributes
final String identifierQuote
The quote character for identifiers actually used in the database.
final List< String > suffixes = new ArrayList<>()
The expected variable part of suffixes in files, in the order to be run.
final Dialect dialect
The presumed dialect spoken by the database.
final Map< String, String > replacements = new HashMap<>()
A mapping of words to replace.
Package Functions
final int run (final File directory, String[] files) throws IOException, SQLException
Runs the SQL scripts read from the given files in the given directory.
int runFile (final File file) throws IOException, SQLException
Run the SQL script from a single file.
Detailed Description
An sql script runner replacing the boolean used in postgres by small Interger used by derby.
Author
Guilhem Legal (Geomatys)
Constructor & Destructor Documentation
DerbySqlScriptRunner()
DerbySqlScriptRunner (final Connection c) throws SQLException
{
         super(c);
     }
Member Function Documentation
accept()
boolean accept (final File directory, final String name) inherited
Returns.
true
if the file of the given name is a SQL script. The default implementation returns
true
if the filename ends with the
".sql"
extension and if it does not start with
"."
(which is for hidden files on Unix system).
Subclasses can override this method if they need to filter the files differently.
Parameters
directory The directory that contains the file, or
null
if none (for example if the file is an entry in a ZIP file).
name The name of the file to test.
Returns
true
if a file of the given name is likely to be a SQL script.
{
         final int e = name.lastIndexOf('.');
         return (e > 0) && (name.charAt(0) != '.') && name.regionMatches(true, e+1, "sql", 0, 3);
     }
close()
void close (final boolean vacuum) throws SQLException inherited
Closes the statement used by this runner.
Note that this method does not close the connection given to the constructor; this connection still needs to be closed explicitly by the caller.
This method does not shutdown the database. For database shutdown, see driver-specific methods like HSQL#shutdown(Connection, boolean).
Parameters
vacuum
{
         if (statement != null) {
             switch (dialect) {
                 case POSTGRESQL: {
                     if (vacuum) {
                         statement.executeUpdate("VACUUM FULL ANALYZE");
                     }
                     break;
                 }
             }
             statement.close();
         }
     }
execute()
int execute (final StringBuilder sb) throws SQLException, IOException protected
execute SQL code.
escape the postgres specific operation and replace the boolean by small int.
the code of this method must be review.
Parameters
sb
Returns
Exceptions
SQLException
IOException
{
         String query = sb.toString();
         /*
          * we transform the boolean value in smallint value
          */
         query        = query.replace("'false'", "'FALSE'");
         query        = query.replace("'true'", "'TRUE'");
         // use a regex to replace the 2 line above
         query        = query.replace("false", "0");
         query        = query.replace("true", "1");
         // remove the 2 line under
         query        = query.replace("'FALSE'", "'false'");
         query        = query.replace("'TRUE'", "'true'");
         /*
          * we transform the boolean column in smallint one
          */
         query        = query.replace("boolean", "smallint");
         /*
          * we remove the sequence part in column
          */
         if (query.contains("nextval(")) {
             query = query.replaceAll("DEFAULT nextval\\(.*regclass\\)", "");
         }
         /*
          * timestamp type can not be without timezone
          */
         query = query.replace("timestamp without time zone", "timestamp");
         /*
          * Postgis type does not work with derby
          * This is a dirty hack
          */
         query = query.replace("postgis.geometry", "character varying(40)");
         if (!query.startsWith("SET check_function_bodies")
                 && !query.startsWith("SET client_min_messages")
                 && !query.startsWith("SET search_path")
                 && !query.startsWith("SET client_encoding")
                 && !query.startsWith("SET standard_conforming_strings")
                 && !query.startsWith("SET escape_string_warning")
                 && !query.startsWith("SET default_tablespace")
                 && !query.startsWith("SET default_with_oids")
                 && !query.startsWith("CREATE INDEX")
                 && !query.startsWith("SELECT pg_catalog.setval")
                 && !"".equals(query)) {
             try {
                 return super.execute(new StringBuilder(query));
             } catch (SQLException ex) {
                 Logger.getAnonymousLogger().warning("SQL exception while executing:" + query);
                 throw ex;
             }
         } else {
             return 0;
         }
     }
getConnection()
Connection getConnection () throws SQLException protected inherited
Returns the connection.
Returns
The connection, or
null
if none.
Exceptions
SQLException If the connection can not be obtained.
Since
3.11
{
         return (statement != null) ? statement.getConnection() : null;
     }
getCurrentPosition()
String getCurrentPosition () inherited
Returns the current position (current file and current line in that file).
The returned string may also contains the SQL statement under execution. The main purpose of this method is to provides informations on the position where an exception occurred.
Returns
A string representation of the current position.
References Vocabulary.Keys.FilePosition_2, and Vocabulary.format().
{
         String position = null;
         if (currentFile != null) {
             position = Vocabulary.format(Vocabulary.Keys.FilePosition_2, currentFile, currentLine);
         }
         if (currentSQL != null) {
             final StringBuilder buffer = new StringBuilder();
             if (position != null) {
                 buffer.append(position).append('\n');
             }
             position = buffer.append("SQL: ").append(currentSQL).toString();
         }
         return position;
     }
getEncoding()
String getEncoding () inherited
Returns the encoding of SQL scripts, or.
null
for the platform default. The default value is
null
.
Returns
The encoding of SQL scripts.
References ScriptRunner.encoding.
{
         return encoding;
     }
run() [1/5]
int run (final File file) throws IOException, SQLException inherited
Run the SQL script read from the given file or directory.
If the argument is a file, then it is read directly using the getEncoding() current encoding}. Otherwise if it is a directory, then the directory content is read and filtered by the accept method.
Parameters
file The file or directory of the script(s) to run.
Returns
The number of rows added or modified as a result of the script(s) execution.
Exceptions
IOException If an error occurred while reading the input.
SQLException If an error occurred while executing a SQL statement.
References ScriptRunner.runFile().
Referenced by ScriptRunner.run(), and ScriptRunner.runFile().
{
         if (file.isDirectory()) {
             return run(file, file.list(this));
         } else {
             return runFile(file);
         }
     }
run() [2/5]
final int run (final File directory, String [] files) throws IOException, SQLException package inherited
Runs the SQL scripts read from the given files in the given directory.
Parameters
directory The directory of the script(s) to run.
files The filename of the script(s) to run in the above directory.
Returns
The number of rows added or modified as a result of the script(s) execution.
Exceptions
IOException If an error occurred while reading the input.
SQLException If an error occurred while executing a SQL statement.
References ScriptRunner.runFile(), and ScriptRunner.selectVersion().
{
         if (files.length == 0) {
             return 0;
         }
         /*
          * Find the prefix and suffix that are common to every files.
          */
         String prefix = null, suffix = null;
         for (final String file : files) {
             prefix = CharSequences.commonPrefix(prefix, file).toString();
             suffix = CharSequences.commonSuffix(suffix, file).toString();
         }
         final int pl = prefix.length();
         final int sl = suffix.length();
         /*
          * Assuming that the part between the prefix and suffix contains the version number,
          * get the version of every files. We will then select one version, by default the
          * one having the highest major/minor version numbers.
          */
         final Set<String> uniques = new LinkedHashSet<>();
         final Map<String,Integer> order = new HashMap<>();
         final String[] versions = new String[files.length];
         for (int i=0; i<files.length; i++) {
             final String file = files[i];
             String version = file.substring(pl, file.length() - sl);
             final int size = suffixes.size();
             for (int j=0; j<size; j++) {
                 final String s = suffixes.get(j);
                 if (version.endsWith(s)) {
                     version = version.substring(0, version.length() - s.length());
                     order.put(file, j);
                     break;
                 }
             }
             versions[i] = version;
             uniques.add(version);
         }
         final String select = selectVersion(uniques.toArray(new String[uniques.size()]));
         /*
          * Filters the files, keeping only those having the expected version number.
          * Then sorts those files in the order declared in the suffixes list.
          */
         int count = 0;
         for (int i=0; i<files.length; i++) {
             if (select.equals(versions[i])) {
                 files[count++] = files[i];
             }
         }
         files = ArraysExt.resize(files, count);
         Arrays.sort(files, new Comparator<String>() {
             @Override public int compare(final String o1, final String o2) {
                 final Integer i1 = order.get(o1);
                 final Integer i2 = order.get(o2);
                 if (i1 == null) return +1;
                 if (i2 == null) return -1;
                 return i1 - i2;
             }
         });
         /*
          * Now run the selected files.
          */
         count = 0;
         for (final String file : files) {
             count += runFile(new File(directory, file));
         }
         return count;
     }
run() [3/5]
final int run (final InputStream in) throws IOException, SQLException inherited
Run the script from the given input stream.
Lines are read and grouped up to the terminal { END_OF_STATEMENT} character, then sent to the database.
Parameters
in The stream to read. This stream will be closed at the end.
Returns
The number of rows added or modified as a result of the script execution.
Exceptions
IOException If an error occurred while reading the input.
SQLException If an error occurred while executing a SQL statement.
References ScriptRunner.run().
{
         final Reader reader;
         if (encoding == null) {
             reader = new InputStreamReader(in);
         } else {
             reader = new InputStreamReader(in, encoding);
         }
         try (LineNumberReader lr = new LineNumberReader(reader)) {
             return run(lr);
         }
     }
run() [4/5]
final int run (final LineNumberReader in) throws IOException, SQLException inherited
Run the script from the given reader.
Lines are read and grouped up to the terminal { END_OF_STATEMENT} character, then sent to the database.
Parameters
in The stream to read. This stream will be closed at the end.
Returns
The number of rows added or modified as a result of the script execution.
Exceptions
IOException If an error occurred while reading the input.
SQLException If an error occurred while executing a SQL statement.
References ScriptRunner.END_OF_STATEMENT, ScriptRunner.execute(), Errors.format(), ScriptRunner.IDENTIFIER_QUOTE, Errors.Keys.MissingCharacter_1, and ScriptRunner.QUOTE.
{
         // Determine once for ever if it is worth to look for SQL keyword replacements,
         // and if we need to take the trouble to look two words ahead (e.g. "CREATE TABLE").
         final boolean noReplace = replacements.isEmpty();
         boolean replaceTwoWords = false;
         for (final String replace : replacements.keySet()) {
             if (replace.indexOf(' ') >= 0) {
                 replaceTwoWords = true;
                 break;
             }
         }
         // Variables which will change during the iterations.
         int count = 0;
         final StringBuilder buffer = new StringBuilder();
         String line;
         boolean insideText = false;
         boolean insideIdentifier = false;
         while ((line = in.readLine()) != null) {
             int i = buffer.length();
             if (i == 0) {
                 final String trimed = line.trim();
                 if (trimed.isEmpty() || trimed.startsWith(COMMENT)) {
                     // Ignore empty lines and comment lines, but only if they appear before any
                     // other kind of line (i.e. before the begining of the real SQL statement).
                     continue;
                 }
                 currentLine = in.getLineNumber();
             } else {
                 i++;
                 buffer.append('\n');
             }
             /*
              * If we find the "$$" string, copy verbatism (without any attempt to parse the
              * lines) until the next occurrence of "$$". This simple algorithm does not allow
              * more than one block of "$$ ... $$" on the same line.
              */
             for (final String escape : ESCAPES) {
                 int pos = line.indexOf(escape);
                 if (pos >= 0) {
                     pos += escape.length();
                     while ((pos = line.indexOf(escape, pos)) < 0) {
                         buffer.append(line).append('\n');
                         line = in.readLine();
                         if (line == null) {
                             throw new EOFException();
                         }
                         pos = 0;
                     }
                     pos += escape.length();
                     buffer.append(line.substring(0, pos));
                     i = buffer.length(); // Will resume the parsing from that position.
                     line = line.substring(pos);
                     break;
                 }
             }
             buffer.append(line);
             int length = buffer.length();
 scanLine:   for (; i<length; i++) {
                 final char c = buffer.charAt(i);
                 switch (c) {
                     /*
                      * Found a character for an identifier like "Coordinate Operations".
                      * Check if we have found the opening or the closing character. Then
                      * replace the standard quote character by the database-specific one.
                      */
                     case IDENTIFIER_QUOTE: {
                         if (!insideText) {
                             insideIdentifier = !insideIdentifier;
                             buffer.replace(i, i+1, identifierQuote);
                             i += identifierQuote.length() - 1;
                         }
                         continue;
                     }
                     /*
                      * Found a character for a text like 'This is a value'. Check if we have
                      * found the opening or closing character, ignoring the '' escape sequence.
                      */
                     case QUOTE: {
                         if (!insideIdentifier) {
                             if (!insideText) {
                                 insideText = true;
                             } else if (i+1 == length || buffer.charAt(i+1) != QUOTE) {
                                 insideText = false;
                             } else {
                                 // Found a double ' character, which means to escape it.
                                 i++;
                             }
                         }
                         continue;
                     }
                     /*
                      * Found the end of statement. Remove that character if it is the last non-white
                      * character, since SQL statement in JDBC are not expected to contain it.
                      */
                     case END_OF_STATEMENT: {
                         if (!insideText && !insideIdentifier) {
                             int stop = i;
                             while (++i < length) {
                                 if (!Character.isSpaceChar(buffer.charAt(i))) {
                                     stop = length;
                                     break;
                                 }
                             }
                             buffer.setLength(stop);
                             count += execute(buffer);
                             buffer.setLength(0);
                             break scanLine;
                         }
                         continue;
                     }
                 }
                 /*
                  * Any other kind of character. If we find the beginning of an identifier
                  * (arbitrarily assuming similar syntax than Java identifier rules), check
                  * for the end of the word and replace if needed.
                  */
                 if (!noReplace && !insideText && !insideIdentifier && Character.isJavaIdentifierStart(c)) {
                     final int start = i;
                     while (++i < length && Character.isJavaIdentifierPart(buffer.charAt(i)));
                     String word = buffer.substring(start, i);
                     String replace = replacements.get(word);
                     if (replaceTwoWords && replace == null && i<length && Character.isSpaceChar(buffer.charAt(i))) {
                         final int mark = i;
                         if (++i < length && Character.isJavaIdentifierStart(buffer.charAt(i))) {
                             while (++i < length && Character.isJavaIdentifierPart(buffer.charAt(i)));
                             word = buffer.substring(start, i);
                             replace = replacements.get(word);
                         }
                         if (replace == null) {
                             i = mark;
                         }
                     }
                     if (replace != null) {
                         buffer.replace(start, i, replace);
                         i = start + replace.length();
                         length = buffer.length();
                     }
                     i--;
                 }
             }
         }
         in.close();
         line = buffer.toString().trim();
         if (!line.isEmpty() && !line.startsWith(COMMENT)) {
             throw new EOFException(Errors.format(Errors.Keys.MissingCharacter_1, END_OF_STATEMENT));
         }
         return count;
     }
run() [5/5]
final int run (final String statement) throws IOException, SQLException inherited
Convenience method invoking run(LineNumberReader) for the given SQL statement.
Parameters
statement The SQL statement to execute.
Returns
The number of rows added or modified as a result of the statement execution.
Exceptions
IOException If an error occurred while reading the input (should never happen).
SQLException If an error occurred while executing a SQL statement.
Since
3.16
References ScriptRunner.run().
{
         return run(new LineNumberReader(new StringReader(statement)));
     }
runFile()
int runFile (final File file) throws IOException, SQLException package inherited
Run the SQL script from a single file.
Parameters
file The file of the script to run.
Returns
The number of rows added or modified as a result of the script execution.
Exceptions
IOException If an error occurred while reading the input.
SQLException If an error occurred while executing a SQL statement.
References ScriptRunner.encoding, and ScriptRunner.run().
Referenced by ScriptRunner.run().
{
         final String encoding = this.encoding;
         final Reader reader;
         if (encoding == null) {
             reader = new FileReader(file);
         } else {
             reader = new InputStreamReader(new FileInputStream(file), encoding);
         }
         final int count;
         try (LineNumberReader in = new LineNumberReader(reader)) {
             currentFile = file; count = run(in);
             currentFile = null; // Clear on success only.
         }
         return count;
     }
selectVersion()
String selectVersion (final String [] versions) protected inherited
If there is many versions of the SQL script, select the version to run.
The default implementation tries to parse the version number and to select the greatest one.
Parameters
versions The version found in a directory.
Returns
The version to run.
Referenced by ScriptRunner.run().
{
         final StringBuilder buffer = new StringBuilder();
         Version max = null;
         String selected = versions[versions.length - 1];
         for (final String version : versions) {
             final int length = version.length();
             for (int i=0; i<length; i++) {
                 char c = version.charAt(i);
                 if (c >= '0' && c <= '9') {
                     buffer.setLength(0);
                     while (i < length) {
                         c = version.charAt(i++);
                         if (!Character.isLetterOrDigit(c)) {
                             c = '.';
                         }
                         buffer.append(c);
                     }
                     Version candidate = new Version(buffer.toString());
                     if (max == null || max.compareTo(candidate) <= 0) {
                         max = candidate;
                         selected = version;
                     }
                 }
             }
         }
         return selected;
     }
setEncoding()
void setEncoding (final String encoding) inherited
Sets the encoding of SQL scripts.
Typical values are
"UTF-8"
and
"ISO-8859-1"
. For SQL scripts provided by the EPSG, the encoding shall be
"ISO-8859-1"
.
Parameters
encoding The encoding of SQL scripts, or
null
for the platform default.
References ScriptRunner.encoding.
{
         this.encoding = encoding;
     }
toString()
String toString () inherited
Returns a string representation of this runner for debugging purpose.
Current implementation returns the current position in the script being executed, and the SQL statement. This method may be invoked after a SQLException occurred in order to determine the line in the SQL script that caused the error.
Returns
The current position in the script being executed.
{
         final StringBuilder buffer = new StringBuilder(getClass().getSimpleName()).append('[');
         if (currentFile != null) {
             buffer.append(currentFile.getName()).append(" : ").append(currentLine);
         }
         buffer.append(']');
         if (currentSQL != null) {
             buffer.append('\n').append(currentSQL);
         }
         return buffer.toString();
     }
Member Data Documentation
dialect
final Dialect dialect protected inherited
The presumed dialect spoken by the database.
END_OF_STATEMENT
final char END_OF_STATEMENT = ';' static inherited
The character at the end of statements.
Referenced by ScriptRunner.run().
IDENTIFIER_QUOTE
final char IDENTIFIER_QUOTE = '"' static inherited
The quote character for identifiers expected to be found in the SQL script.
Referenced by ScriptRunner.run().
identifierQuote
final String identifierQuote protected inherited
The quote character for identifiers actually used in the database.
QUOTE
final char QUOTE = '\'' static inherited
The quote character expected to be found in the SQL script.
Referenced by ScriptRunner.run().
replacements
final Map<String,String> replacements = new HashMap<>() protected inherited
A mapping of words to replace.
The replacement is performed only if the word is not found in an identifier or a string. The default implementation let this map empty, but subclasses may fill it at construction time.
This is used for example in order to map the table names in the EPSG scripts to table names as they were in the MS-Access flavor of EPSG database. It may also contains the mapping between SQL keywords used in the SQL scripts to SQL keywords understood by the database (for example Derby does not support the
TEXT
data type, which need to be replaced by
VARCHAR
).
suffixes
final List<String> suffixes = new ArrayList<>() protected inherited
The expected variable part of suffixes in files, in the order to be run.
For example the EPSG scripts are made of the following files:
{ text EPSG_v6_14.mdb_Data_PostgreSQL.sql EPSG_v6_14.mdb_FKeys_PostgreSQL.sql EPSG_v6_14.mdb_Tables_PostgreSQL.sql }
In such cases, the list shall contains
"Tables"
,
"Data"
and
"FKeys"
in that order, because this is the order that the script files are expected to be run.