jena-geo: LineFormat Class Reference
LineFormat Class Reference
Parses a line of text data.
Public Member Functions
LineFormat ()
Constructs a new line parser for numbers in the default locale.
LineFormat (final Locale locale)
Constructs a new line parser for numbers in the specified locale.
LineFormat (final Format format)
Constructs a new line parser using the specified format for every columns.
LineFormat (Format[] formats)
Constructs a new line parser using the specified format objects.
Class<?> getElementType (final Predicate< Class > filter)
Returns the type of all elements to be parsed by the formats given to the constructor.
void clear ()
Clears this parser.
int setLine (final String line) throws ParseException
Parses the specified line.
int setLine (final String line, int lower, final int upper) throws ParseException
Parses a substring of the specified line.
int getValueCount ()
Returns the number of elements found in the last line parsed by setLine(String).
void setValues (final Object values) throws IllegalArgumentException
Sets all values in the current line.
void setValue (final int index, final Object value) throws ArrayIndexOutOfBoundsException
Sets or adds a value to current line.
Object getValue (final int index) throws ArrayIndexOutOfBoundsException
Returns the value at the specified index.
double [] getValues (double[] array) throws ParseException
Copies all values to the specified array.
float [] getValues (float[] array) throws ParseException
Copies all values to the specified array.
long [] getValues (long[] array) throws ParseException
Copies all values to the specified array.
int [] getValues (int[] array) throws ParseException
Copies all values to the specified array.
short [] getValues (short[] array) throws ParseException
Copies all values to the specified array.
byte [] getValues (byte[] array) throws ParseException
Copies all values to the specified array.
String toString ()
Returns a string representation of current line.
StringBuffer format (final Object values, final StringBuffer toAppendTo, final FieldPosition position)
Formats an object and appends the resulting text to a given string buffer.
Object [] parseObject (final String source, final ParsePosition position)
Parses text from a string to produce an object.
Object [] parseObject (final String source) throws ParseException
Parses text from the beginning of the given string to produce an object.
LineFormat clone ()
Returns a clone of this parser.
Private Member Functions
Number getNumber (final int index) throws ParseException
Returns.
void checkLength (final int expected) throws ParseException
Ensures that the number of columns just parsed is equal to the number of columns expected.
ParseException notAnInteger (final int i)
Creates an exception for a value not being an integer.
StringBuffer toString (StringBuffer buffer)
Formats a string representation of current line.
void writeObject (final ObjectOutputStream out) throws IOException
Invoked on serialization.
void readObject (final ObjectInputStream in) throws IOException, ClassNotFoundException
Invoked on deserialization.
Static Private Member Functions
static int getLineEnd (final String source, int offset, final boolean s)
Returns the index of the end of the specified line.
Private Attributes
transient int count
Number of valid data in the data array.
Object [] data
Data read last time setLine(String) has been invoked.
final Format [] formats
Array of formats to use for parsing a line.
transient ParsePosition position = new ParsePosition(0)
The ParsePosition used for specifying the substring to parse.
int [] limits
Index of the the first character parsed in each column.
String line
The line specified in the last call to setLine(String).
transient ObjectConverter<?, ? extends Number > toNumber
A converter from arbitrary objects to numbers.
Static Private Attributes
static final long serialVersionUID = 1257759127594136266L
For cross-version compatibility.
static final Predicate< Class > NUMBER = Number.class::isAssignableFrom
Returns a Predicate accepting only classes Class::isAssignableFrom assignable to} Number.
Detailed Description
Parses a line of text data.
This class is mostly used for parsing lines in a matrix or a table. Each column may contains numbers, dates, or other objects parseable by some Format implementations. The example below reads dates in the first column and numbers in all remaining columns.
{ java final LineParser parser = new LineFormat(new Format[] { DateFormat.getDateTimeInstance(), NumberFormat.getNumberInstance() }); }
LineFormat
may be used for reading a matrix with an unknown number of columns, while requiring that all lines have the same number of columns. The example below gets the number of columns while reading the first line, and ensure that all subsequent lines have the same number of columns. If one line violates this condition, then a ParseException will be thrown. The check if performed by the getValues(double[]) method when the
data
array is non-nul.
{ java double[] data = null; final BufferedReader in = new BufferedReader(new FileReader("MATRIX.TXT")); for (String line; (line = in.readLine()) != null;) { parser.setLine(line); data = parser.getValues(data); // ... process 'data' here ... }); in.close(); }
This code can work as well with dates instead of numbers. In this case, the values returned will be microseconds elapsed since January 1st, 1970.
A ParseException may be thrown because a string can't be parsed, because an object can't be converted into a number or because a line don't have the expected number of columns. In all case, it is possible to gets the index of the first problem found using ParseException#getErrorOffset.
{
}
Instances of
LineFormat
are not thread-safe, since the underlying Format implementations are not guaranteed to be thread-safe neither.
Author
Martin Desruisseaux (IRD)
Version
4.00
Since
1.2
Constructor & Destructor Documentation
LineFormat() [1/4]
LineFormat ()
Constructs a new line parser for numbers in the default locale.
Referenced by LineFormat.clone().
{
         this(NumberFormat.getNumberInstance());
     }
LineFormat() [2/4]
LineFormat (final Locale locale)
Constructs a new line parser for numbers in the specified locale.
For example Locale#US may be used for reading numbers using the dot as decimal separator.
Parameters
locale The locale.
{
         this(NumberFormat.getNumberInstance(locale));
     }
LineFormat() [3/4]
LineFormat (final Format format)
Constructs a new line parser using the specified format for every columns.
Parameters
format The format to use.
References Errors.format(), and Errors.Keys.NullFormat_2.
{
         if (format == null) {
             throw new NullArgumentException(Errors.format(Errors.Keys.NullFormat_2, 0, 1));
         }
         this.data    = new Object[16];
         this.limits  = new int[data.length + 1];
         this.formats = new Format[] {format};
     }
LineFormat() [4/4]
LineFormat (Format [] formats)
Constructs a new line parser using the specified format objects.
For example the first column will be parsed using
formats[0]
; the second column will be parsed using
formats[1]
, etc. If there is more columns than formats, then the last format object is reused for all remaining columns.
Parameters
formats The formats to use for parsing.
References Errors.Keys.EmptyArray, Errors.format(), and Errors.Keys.NullFormat_2.
{
         if (formats.length == 0) {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.EmptyArray));
         }
         this.formats = formats = formats.clone();
         this.data    = new Object[formats.length];
         this.limits  = new int   [formats.length + 1];
         for (int i=0; i<formats.length; i++) {
             if (formats[i] == null) {
                 throw new NullArgumentException(Errors.format(
                         Errors.Keys.NullFormat_2, i+1, formats.length));
             }
         }
     }
Member Function Documentation
checkLength()
void checkLength (final int expected) throws ParseException private
Ensures that the number of columns just parsed is equal to the number of columns expected.
If a mismatch is found, then an exception is thrown.
Parameters
expected The expected number of columns.
Exceptions
ParseException If the number of columns parsed is not equal to the number expected.
References Errors.format(), Errors.Keys.LineTooLong_3, and Errors.Keys.LineTooShort_2.
Referenced by LineFormat.getValues().
{
         if (count != expected) {
             final int lower = limits[Math.min(count, expected  )];
             final int upper = limits[Math.min(count, expected+1)];
             throw new ParseException(Errors.format(count<expected ?
                                      Errors.Keys.LineTooShort_2 : Errors.Keys.LineTooLong_3,
                                      count, expected, line.substring(lower,upper).trim()), lower);
         }
     }
clear()
void clear ()
Clears this parser.
Next call to getValueCount will returns 0.
{
         toNumber = null;
         line     = null;
         count    = 0;
         Arrays.fill(data, null);
     }
clone()
LineFormat clone ()
Returns a clone of this parser.
In current implementation, this clone is not for usage in concurrent thread, since the underlying formats are not cloned.
References LineFormat.clone(), LineFormat.data, LineFormat.limits, and LineFormat.LineFormat().
Referenced by LineFormat.clone().
{
         final LineFormat copy = (LineFormat) super.clone();
         copy.data   = data.clone();
         copy.limits = limits.clone();
         return copy;
     }
format()
StringBuffer format (final Object values, final StringBuffer toAppendTo, final FieldPosition position)
Formats an object and appends the resulting text to a given string buffer.
This method invokes setValues setValues}(values), then formats all columns using the Format object specified at construction time. Columns are separated by tabulation.
Parameters
values The values to format.
position Ignored in default implementation.
Returns
All columns formatted on a single line.
Since
2.4
References LineFormat.setValues(), and LineFormat.toString().
Referenced by LineFormat.getElementType().
     {
         setValues(values);
         return toString(toAppendTo);
     }
getElementType()
Class<?> getElementType (final Predicate< Class > filter)
Returns the type of all elements to be parsed by the formats given to the constructor.
The default implementation infers the parent type using reflection. For example if the constructor was given a java.text.DateFormat instance, then this method will returns java.util.Date}.class.
Parameters
filter The type of colunms to include in the search, or
null
if no filtering should be applied. This argument is often ClassFilter::NUMBER}.negate() in order to search for base type of non-numerical columns.
Returns
The base type of columns, or
null
if no non-filtered column was found.
Since
3.00
References LineFormat.format().
Referenced by LineFormat.getNumber().
{
         Class<?> type = null;
         final Class<?>[] arguments = new Class<?>[] {String.class};
         for (final Format format : formats) {
             final Class<?> candidate;
             try {
                 candidate = format.getClass().getMethod("parse", arguments).getReturnType();
             } catch (NoSuchMethodException e) {
                 /*
                  * We are going to work only with the Format.parseObject(String) method anyway.
                  * So if there is no parse(String) method, the safest approach is to give up and
                  * assume that the return type can be anything.
                  */
                 return Object.class;
             }
             if (type == null) {
                 type = candidate;
             } else if (candidate != null && (filter == null || filter.test(candidate))) {
                 type = Classes.findCommonClass(type, candidate);
             }
         }
         return type;
     }
getLineEnd()
static int getLineEnd (final String source, int offset, final boolean s) static private
Returns the index of the end of the specified line.
Referenced by LineFormat.parseObject().
{
         final int length = source.length();
         while (offset < length) {
             final char c = source.charAt(offset);
             if ((c == '\r' || c == '\n') == s) {
                 break;
             }
             offset++;
         }
         return offset;
     }
getNumber()
Number getNumber (final int index) throws ParseException private
Returns.
data[index]
as a number.
Parameters
index Index of the value to returns.
Returns
The value as a Number.
Exceptions
ParseException if the value can not be converted to a Number.
References Errors.format(), LineFormat.getElementType(), and Errors.Keys.UnparsableNumber_1.
Referenced by LineFormat.getValues().
{
         final Object candidate = data[index];
         if (candidate instanceof Number) {
             return ((Number) candidate);
         }
         try {
             if (toNumber == null) {
                 final Class<?> type = getElementType(NUMBER.negate());
                 toNumber = ObjectConverters.find(type, Number.class);
             }
             @SuppressWarnings({"unchecked","rawtypes"})
             final Number n = (Number) ((ObjectConverter) toNumber).apply(candidate);
             return n;
         } catch (UnconvertibleObjectException cause) {
             ParseException exception = new ParseException(Errors.format(
                     Errors.Keys.UnparsableNumber_1, data[index]), limits[index]);
             exception.initCause(cause);
             throw exception;
         }
     }
getValue()
Object getValue (final int index) throws ArrayIndexOutOfBoundsException
Returns the value at the specified index.
The index should be in the range 0 inclusively to getValueCount exclusively.
Parameters
index Index of the value to fetch.
Returns
The value at the specified index.
Exceptions
ArrayIndexOutOfBoundsException If the index is outside the expected range.
{
         if (index < count) {
             return data[index];
         }
         throw new ArrayIndexOutOfBoundsException(index);
     }
getValueCount()
int getValueCount ()
Returns the number of elements found in the last line parsed by setLine(String).
Returns
Number of elements found in the last parsed line.
References LineFormat.count.
{
         return count;
     }
getValues() [1/6]
double [] getValues (double [] array) throws ParseException
Copies all values to the specified array.
This method is typically invoked after setLine(String) for fetching the values just parsed. If
array
is null, this method creates and returns a new array with a length equal to number of elements parsed. If
array
is not null, then this method will thrown an exception if the array length is not exactly equal to the number of elements parsed.
Parameters
array The array to copy values into.
Returns
array
if it was not null, or a new array otherwise.
Exceptions
ParseException If
array
was not null and its length is not equal to the number of elements parsed, or if at least one element can't be parsed.
References LineFormat.checkLength(), LineFormat.count, and LineFormat.getNumber().
Referenced by PaletteFactory.getColors().
{
         if (array != null) {
             checkLength(array.length);
         } else {
             array = new double[count];
         }
         for (int i=0; i<count; i++) {
             array[i] = getNumber(i).doubleValue();
         }
         return array;
     }
getValues() [2/6]
float [] getValues (float [] array) throws ParseException
Copies all values to the specified array.
This method is typically invoked after setLine(String) for fetching the values just parsed. If
array
is null, this method creates and returns a new array with a length equal to number of elements parsed. If
array
is not null, then this method will thrown an exception if the array length is not exactly equal to the number of elements parsed.
Parameters
array The array to copy values into.
Returns
array
if it was not null, or a new array otherwise.
Exceptions
ParseException If
array
was not null and its length is not equal to the number of elements parsed, or if at least one element can't be parsed.
References LineFormat.checkLength(), LineFormat.count, and LineFormat.getNumber().
{
         if (array != null) {
             checkLength(array.length);
         } else {
             array = new float[count];
         }
         for (int i=0; i<count; i++) {
             array[i] = getNumber(i).floatValue();
         }
         return array;
     }
getValues() [3/6]
long [] getValues (long [] array) throws ParseException
Copies all values to the specified array.
This method is typically invoked after setLine(String) for fetching the values just parsed. If
array
is null, this method creates and returns a new array with a length equal to number of elements parsed. If
array
is not null, then this method will thrown an exception if the array length is not exactly equal to the number of elements parsed.
Parameters
array The array to copy values into.
Returns
array
if it was not null, or a new array otherwise.
Exceptions
ParseException If
array
was not null and its length is not equal to the number of elements parsed, or if at least one element can't be parsed.
References LineFormat.checkLength(), LineFormat.count, LineFormat.getNumber(), and LineFormat.notAnInteger().
{
         if (array != null) {
             checkLength(array.length);
         } else {
             array = new long[count];
         }
         for (int i=0; i<count; i++) {
             final Number n = getNumber(i);
             if ((array[i] = n.longValue()) != n.doubleValue()) {
                 throw notAnInteger(i);
             }
         }
         return array;
     }
getValues() [4/6]
int [] getValues (int [] array) throws ParseException
Copies all values to the specified array.
This method is typically invoked after setLine(String) for fetching the values just parsed. If
array
is null, this method creates and returns a new array with a length equal to number of elements parsed. If
array
is not null, then this method will thrown an exception if the array length is not exactly equal to the number of elements parsed.
Parameters
array The array to copy values into.
Returns
array
if it was not null, or a new array otherwise.
Exceptions
ParseException If
array
was not null and its length is not equal to the number of elements parsed, or if at least one element can't be parsed.
References LineFormat.checkLength(), LineFormat.count, LineFormat.getNumber(), and LineFormat.notAnInteger().
{
         if (array != null) {
             checkLength(array.length);
         } else {
             array = new int[count];
         }
         for (int i=0; i<count; i++) {
             final Number n = getNumber(i);
             if ((array[i] = n.intValue()) != n.doubleValue()) {
                 throw notAnInteger(i);
             }
         }
         return array;
     }
getValues() [5/6]
short [] getValues (short [] array) throws ParseException
Copies all values to the specified array.
This method is typically invoked after setLine(String) for fetching the values just parsed. If
array
is null, this method creates and returns a new array with a length equal to number of elements parsed. If
array
is not null, then this method will thrown an exception if the array length is not exactly equal to the number of elements parsed.
Parameters
array The array to copy values into.
Returns
array
if it was not null, or a new array otherwise.
Exceptions
ParseException If
array
was not null and its length is not equal to the number of elements parsed, or if at least one element can't be parsed.
References LineFormat.checkLength(), LineFormat.count, LineFormat.getNumber(), and LineFormat.notAnInteger().
{
         if (array != null) {
             checkLength(array.length);
         } else {
             array = new short[count];
         }
         for (int i=0; i<count; i++) {
             final Number n = getNumber(i);
             if ((array[i] = n.shortValue()) != n.doubleValue()) {
                 throw notAnInteger(i);
             }
         }
         return array;
     }
getValues() [6/6]
byte [] getValues (byte [] array) throws ParseException
Copies all values to the specified array.
This method is typically invoked after setLine(String) for fetching the values just parsed. If
array
is null, this method creates and returns a new array with a length equal to number of elements parsed. If
array
is not null, then this method will thrown an exception if the array length is not exactly equal to the number of elements parsed.
Parameters
array The array to copy values into.
Returns
array
if it was not null, or a new array otherwise.
Exceptions
ParseException If
array
was not null and its length is not equal to the number of elements parsed, or if at least one element can't be parsed.
References LineFormat.checkLength(), LineFormat.count, LineFormat.getNumber(), and LineFormat.notAnInteger().
{
         if (array != null) {
             checkLength(array.length);
         } else {
             array = new byte[count];
         }
         for (int i=0; i<count; i++) {
             final Number n = getNumber(i);
             if ((array[i] = n.byteValue()) != n.doubleValue()) {
                 throw notAnInteger(i);
             }
         }
         return array;
     }
notAnInteger()
ParseException notAnInteger (final int i) private
Creates an exception for a value not being an integer.
Parameters
i The value index.
Returns
The exception.
References Errors.format(), and Errors.Keys.NotAnInteger_1.
Referenced by LineFormat.getValues().
{
         return new ParseException(Errors.format(Errors.Keys.NotAnInteger_1,
                 line.substring(limits[i], limits[i+1])), limits[i]);
     }
parseObject() [1/2]
Object [] parseObject (final String source, final ParsePosition position)
Parses text from a string to produce an object.
Parameters
source The text to parse.
position The position where to begin the parsing.
Returns
The values in each column.
Since
2.4
References LineFormat.getLineEnd(), and LineFormat.setLine().
{
         final int lower = position.getIndex();
         final int upper = getLineEnd(source, lower, true);
         try {
             setLine(source.substring(lower, upper));
             position.setIndex(getLineEnd(source, upper, false));
             return Arrays.copyOf(data, count);
         } catch (ParseException e) {
             position.setErrorIndex(e.getErrorOffset());
             return null; // As of java.text.Format contract.
         }
     }
parseObject() [2/2]
Object [] parseObject (final String source) throws ParseException
Parses text from the beginning of the given string to produce an object.
Parameters
source The text to parse.
Returns
The values in each column.
Since
2.4
References LineFormat.getLineEnd(), and LineFormat.setLine().
{
         setLine(source.substring(0, getLineEnd(source, 0, true)));
         return Arrays.copyOf(data, count);
     }
readObject()
void readObject (final ObjectInputStream in) throws IOException, ClassNotFoundException private
Invoked on deserialization.
Restores the fields that are inferred from the serialized ones.
{
         in.defaultReadObject();
         count = data.length;
         position = new ParsePosition(0);
     }
setLine() [1/2]
int setLine (final String line) throws ParseException
Parses the specified line.
The content is immediately parsed and values can be obtained using one of the
getValues(...)
method.
Parameters
line The line to parse.
Returns
The number of elements parsed in the specified line. The same information can be obtained with getValueCount.
Exceptions
ParseException If at least one column can't be parsed.
Referenced by PaletteFactory.getColors(), and LineFormat.parseObject().
{
         return setLine(line, 0, line.length());
     }
setLine() [2/2]
int setLine (final String line, int lower, final int upper) throws ParseException
Parses a substring of the specified line.
The content is immediately parsed and values can be obtained using one of the
getValues(...)
method.
Parameters
line The line to parse.
lower Index of the first character in
line
to parse.
upper Index after the last character in
line
to parse.
Returns
The number of elements parsed in the specified line. The same information can be obtained with getValueCount.
Exceptions
ParseException If at least one column can't be parsed.
References LineFormat.count, Errors.format(), LineFormat.line, and Errors.Keys.ParseException_2.
{
         /*
          * Retient la ligne que l'utilisateur nous demande
          * de lire et oublie toutes les anciennes valeurs.
          */
         this.line = line;
         Arrays.fill(data, null);
         count = 0;
         /*
          * Procde au balayage de toutes les valeurs qui se trouvent sur la ligne spcifie.
          * Le balayage s'arrtera lorsque {@code lower} aura atteint {@code upper}.
          */
 load:   while (true) {
             while (true) {
                 if (lower >= upper) {
                     break load;
                 }
                 if (!Character.isWhitespace(line.charAt(lower))) break;
                 lower++;
             }
             /*
              * Procde  la lecture de la donne. Si la lecture choue, on produira un message d'erreur
              * qui apparatra ventuellement en HTML afin de pouvoir souligner la partie fautive.
              */
             position.setIndex(lower);
             final Object datum = formats[Math.min(count, formats.length-1)].parseObject(line, position);
             final int next = position.getIndex();
             if (datum == null || next <= lower) {
                 final int error = position.getErrorIndex();
                 int end = error;
                 while (end < upper && !Character.isWhitespace(line.charAt(end))) end++;
                 throw new ParseException(Errors.format(Errors.Keys.ParseException_2,
                           line.substring(lower, end).trim(),
                           line.substring(error, Math.min(error+1, end))), error);
             }
             /*
              * Mmorise la nouvelle donne, en agrandissant
              * l'espace rserve en mmoire si c'est ncessaire.
              */
             if (count >= data.length) {
                 data   = Arrays.copyOf(data, count + Math.min(count, 256));
                 limits = Arrays.copyOf(limits, data.length + 1);
             }
             limits[count] = lower;
             data[count++] = datum;
             lower = next;
         }
         limits[count] = lower;
         return count;
     }
setValue()
void setValue (final int index, final Object value) throws ArrayIndexOutOfBoundsException
Sets or adds a value to current line.
The index should be in the range 0 to getValueCount inclusively. If the index is equal to getValueCount, then
value
will be appended as a new column after existing data.
Parameters
index Index of the value to add or modify.
value The new value.
Exceptions
ArrayIndexOutOfBoundsException If the index is outside the expected range.
References Errors.format(), and Errors.Keys.NullArgument_1.
{
         if (index > count) {
             throw new ArrayIndexOutOfBoundsException(index);
         }
         if (value == null) {
             throw new NullArgumentException(Errors.format(Errors.Keys.NullArgument_1, "value"));
         }
         if (index == count) {
             if (index == data.length) {
                 data = Arrays.copyOf(data, index + Math.min(index, 256));
                 limits = Arrays.copyOf(limits, data.length + 1);
             }
             count++;
         }
         data[index] = value;
     }
setValues()
void setValues (final Object values) throws IllegalArgumentException
Sets all values in the current line.
The
values
argument must be an array, which may be of primitive type.
Parameters
values The array to set as values.
Exceptions
IllegalArgumentException if
values
is not an array.
Since
2.4
Referenced by LineFormat.format().
{
         final int length = Array.getLength(values);
         data   = ArraysExt.resize(data,   length);
         limits = ArraysExt.resize(limits, length + 1);
         for (int i=0; i<length; i++) {
             data[i] = Array.get(values, i);
         }
         count = length;
     }
toString() [1/2]
String toString ()
Returns a string representation of current line.
All columns are formatted using the Format object specified at construction time. Columns are separated by tabulation.
Referenced by LineFormat.format().
{
         return toString(new StringBuffer()).toString();
     }
toString() [2/2]
StringBuffer toString (StringBuffer buffer) private
Formats a string representation of current line.
All columns are formatted using the Format object specified at construction time. Columns are separated by tabulation.
References LineFormat.count.
{
         final FieldPosition field = new FieldPosition(0);
         for (int i=0; i<count; i++) {
             if (i != 0) {
                 buffer.append('\t');
             }
             buffer = formats[Math.min(formats.length-1, i)].format(data[i], buffer, field);
         }
         return buffer;
     }
writeObject()
void writeObject (final ObjectOutputStream out) throws IOException private
Invoked on serialization.
Trims the data array to the minimum requested length.
{
         data = ArraysExt.resize(data, count);
         limits = ArraysExt.resize(limits, count + 1);
     }
Member Data Documentation
count
transient int count private
Number of valid data in the data array.
This is the number of data found last time setLine(String) has been invoked.
Referenced by LineFormat.getValueCount(), LineFormat.getValues(), LineFormat.setLine(), and LineFormat.toString().
data
Object [] data private
Data read last time setLine(String) has been invoked.
Those data are returned by methods like getValues(float[]).
Referenced by LineFormat.clone().
formats
final Format [] formats private
Array of formats to use for parsing a line.
Each format object in this array match one column. For example
data[4]
will be parsed with
format[4]
. If the data array is longer than format, then the last format is reused for all remaining columns.
limits
int [] limits private
Index of the the first character parsed in each column.
For example
index[0]
contains the index of the first character read for
data[0]
, etc. This array length must be equal to data}.length + 1. The last element will be the line length.
Referenced by LineFormat.clone().
line
String line private
The line specified in the last call to setLine(String).
Referenced by LineFormat.setLine().
NUMBER
final Predicate<Class> NUMBER = Number.class::isAssignableFrom static private
Returns a Predicate accepting only classes Class::isAssignableFrom assignable to} Number.
position
transient ParsePosition position = new ParsePosition(0) private
The ParsePosition used for specifying the substring to parse.
serialVersionUID
final long serialVersionUID = 1257759127594136266L static private
For cross-version compatibility.
toNumber
transient ObjectConverter<?, ? extends Number> toNumber private
A converter from arbitrary objects to numbers.
Will be fetch only when first needed. The source type will be inferred from
format.parse(String)
return types.