jena-geo: InternalUtilities Class Reference
InternalUtilities Class Reference
Various utility methods not to be put in public API.
Static Public Member Functions
static boolean epsilonEqual (final double v1, final double v2, final ComparisonMode mode)
Returns.
static boolean epsilonEqual (final double v1, final double v2)
Returns.
static boolean debugEquals (final Object o1, final Object o2) throws AssertionError
Compares the given objects in ComparisonMode#DEBUG mode.
static double adjustForRoundingError (final double value, double scale, final int maxULP)
Rounds the specified value, providing that the difference between the original value and the rounded value is not greater than the specified amount of floating point units.
static double adjustForRoundingError (final double value)
Work-around for rounding error.
static void configure (final NumberFormat format, double value, final int maxPrecision)
Sets the NumberFormat::getMinimumFractionDigits() minimum fraction digits} and NumberFormat::getMaximumFractionDigits() maximum fraction digits} of the given format objects for "acceptable" formatting of the given value.
static int parseColor (String color) throws NumberFormatException
Gets the ARGB values for the given hexadecimal value.
Static Public Attributes
static final double COMPARISON_THRESHOLD = 1E-14
Relative difference tolerated when comparing floating point numbers using ComparisonMode#APPROXIMATE.
static final double LINEAR_TOLERANCE = 1.0
Default tolerance threshold for comparing ordinate values in a projected CRS, assuming that the unit of measurement is metre.
static final double ANGULAR_TOLERANCE = LINEAR_TOLERANCE / (1852 * 60)
Default tolerance threshold for comparing ordinate values in a geographic CRS, assuming that the unit of measurement is decimal degrees and using the standard nautical mile length.
Private Member Functions
InternalUtilities ()
Do not allow instantiation of this class.
Static Private Attributes
static final double EPS = 1E-8
Workaround for rounding errors.
static final int ULP_TOLERANCE = 4
Floating point tolerance in <cite>Unit in Last Place</cite> (ULP).
Detailed Description
Various utility methods not to be put in public API.
Author
Martin Desruisseaux (Geomatys)
Version
3.20
Since
3.18 (derived from 3.00)
Constructor & Destructor Documentation
InternalUtilities()
InternalUtilities () private
Do not allow instantiation of this class.
{
     }
Member Function Documentation
adjustForRoundingError() [1/2]
static double adjustForRoundingError (final double value, double scale, final int maxULP) static
Rounds the specified value, providing that the difference between the original value and the rounded value is not greater than the specified amount of floating point units.
This method can be used for hiding floating point error likes 2.9999999996.
Parameters
value The value to round.
scale The scale by which to multiply the value before to round it.
maxULP The maximal change allowed in ULPs (Unit in the Last Place).
Returns
The rounded value, of
value
if it was not close enough to an integer.
Since
3.20
Referenced by InternalUtilities.adjustForRoundingError().
{
         scale = Math.abs(scale);
         final double target = Math.rint(value * scale) / scale;
         return (Math.abs(value - target) <= maxULP*Math.ulp(value)) ? target : value;
     }
adjustForRoundingError() [2/2]
static double adjustForRoundingError (final double value) static
Work-around for rounding error.
This method invokes double, int) with arbitrary values that may change in any future version. Current values were determined empirically from practical experience with IFREMER and other data.
Parameters
value The value to fix.
Returns
The "fixed" value.
Since
3.20
References InternalUtilities.adjustForRoundingError().
{
         return adjustForRoundingError(value, 360, ULP_TOLERANCE);
     }
configure()
static void configure (final NumberFormat format, double value, final int maxPrecision) static
Sets the NumberFormat::getMinimumFractionDigits() minimum fraction digits} and NumberFormat::getMaximumFractionDigits() maximum fraction digits} of the given format objects for "acceptable" formatting of the given value.
The work performed by this method is heuristic and may change in any future version.
Parameters
format The format to configure.
value The sample value to use for formatting the given format.
maxPrecision The maximal precision to use (e.g. 6).
Since
3.20
{
         value = abs(value);
         if (format instanceof DecimalFormat) {
             value *= ((DecimalFormat) format).getMultiplier();
         }
         int precision;
         for (precision=0; precision<maxPrecision; precision++) {
             final double check = rint(value*1E+4) % 1E+4;
             if (!(check > value*EPS)) { // 'step' may be NaN
                 break;
             }
             value *= 10;
         }
         format.setMinimumFractionDigits(precision);
         format.setMaximumFractionDigits(precision);
     }
debugEquals()
static boolean debugEquals (final Object o1, final Object o2) throws AssertionError static
Compares the given objects in ComparisonMode#DEBUG mode.
Parameters
o1 The first object to compare.
o2 The second object to compare.
Returns
true
if the given objects are equal.
Exceptions
AssertionError If the given objects are not equal and the cause can be specified in the exception message.
Since
3.20
{
         return Utilities.deepEquals(o1, o2, ComparisonMode.DEBUG);
     }
epsilonEqual() [1/2]
static boolean epsilonEqual (final double v1, final double v2, final ComparisonMode mode) static
Returns.
true
if the given values are approximatively equal given the comparison mode.
Parameters
v1 The first value to compare.
v2 The second value to compare.
mode The comparison mode to use for comparing the numbers.
Returns
true
If both values are approximatively equal.
Since
3.18
References Utilities.equals().
{
         switch (mode) {
             default: return org.geotoolkit.util.Utilities.equals(v1, v2);
             case APPROXIMATE: return epsilonEqual(v1, v2);
             case DEBUG: {
                 final boolean equal = epsilonEqual(v1, v2);
                 assert equal : "v1=" + v1 + " v2=" + v2 + " Δv=" + abs(v1-v2);
                 return equal;
             }
         }
     }
epsilonEqual() [2/2]
static boolean epsilonEqual (final double v1, final double v2) static
Returns.
true
if the given values are approximatively equal, up to the COMPARISON_THRESHOLD comparison threshold}.
Parameters
v1 The first value to compare.
v2 The second value to compare.
Returns
true
If both values are approximatively equal.
Since
3.18
{
         final double threshold = COMPARISON_THRESHOLD * max(abs(v1), abs(v2));
         if (threshold == Double.POSITIVE_INFINITY || Double.isNaN(threshold)) {
             return Double.doubleToLongBits(v1) == Double.doubleToLongBits(v2);
         }
         return abs(v1 - v2) <= threshold;
     }
parseColor()
static int parseColor (String color) throws NumberFormatException static
Gets the ARGB values for the given hexadecimal value.
If the given code begins with the
'#'
character, then this method accepts the following hexadecimal patterns:
"#AARRGGBB"
: an explicit ARGB code used verbatim.
"#RRGGBB"
: a fully opaque RGB color.
"#ARGB"
: an abbreviation for
"#AARRGGBB"
.
"#RGB"
: an abbreviation for
"#RRGGBB"
. For example #0BC means #00BBCC.
Parameters
color The color code to parse.
Exceptions
NumberFormatException If the given code can not be parsed.
Returns
The ARGB code.
See also
java.awt.Color::decode(String)
Since
3.19
References Errors.format(), and Errors.Keys.IllegalArgument_2.
{
         color = color.trim();
         if (color.startsWith("#")) {
             final String code = color.substring(1);
             // Parses as a long in order to accept ARGB codes in the 80000000 to FF000000 range.
             // The check for the string length will ensure that we are not outside those bounds.
             int value = (int) Long.parseLong(code, 16);
             switch (code.length()) {
                 case 3: value |= 0xF000; // Fallthrough
                 case 4: {
                     int t;
                     return (((t=(value & 0xF000)) | (t << 4)) << 12) |
                            (((t=(value & 0x0F00)) | (t << 4)) <<  8) |
                            (((t=(value & 0x00F0)) | (t << 4)) <<  4) |
                            (((t=(value & 0x000F)) | (t << 4)));
                 }
                 case 6: value |= 0xFF000000; // Fallthrough
                 case 8: return value;
             }
         } else {
             /*
              * Parses the string as an opaque color unless an alpha value was provided.
              * This matches closing the default java.awt.Color.decode(String) behavior,
              * which considers every colors as opaque. We relax slightly the condition
              * by allowing non-zero alpha values. The inconvenient is that specifying
              * a fully transparent color is not possible with syntax - please use the
              * above "#" syntax instead.
              */
             final long n = Long.decode(color);
             int value = (int) n;
             if (value == n) {
                 if ((value & 0xFF000000) == 0) {
                     value |= 0xFF000000;
                 }
                 return value;
             }
         }
         throw new NumberFormatException(Errors.format(
                 Errors.Keys.IllegalArgument_2, "color", color));
     }
Member Data Documentation
ANGULAR_TOLERANCE
final double ANGULAR_TOLERANCE = LINEAR_TOLERANCE / (1852 * 60) static
Default tolerance threshold for comparing ordinate values in a geographic CRS, assuming that the unit of measurement is decimal degrees and using the standard nautical mile length.
Since
3.20
COMPARISON_THRESHOLD
final double COMPARISON_THRESHOLD = 1E-14 static
Relative difference tolerated when comparing floating point numbers using ComparisonMode#APPROXIMATE.
Historically, this was the relative tolerance threshold for considering two matrixes as org.geotoolkit.referencing.operation.matrix.XMatrix::equals(Object, ComparisonMode) equal}. This value has been determined empirically in order to allow org.apache.sis.referencing.operation.transform.MathTransforms to detect the cases where two org.apache.sis.referencing.operation.transform.LinearTransform are equal for practical purpose. This threshold can be used as below:
{ java Matrix m1 = ...; Matrix m2 = ...; if (MatrixUtilities.epsilonEqual(m1, m2, EQUIVALENT_THRESHOLD, true)) { // Consider that matrixes are equal. } }
By extension, the same threshold value is used for comparing other floating point values.
Since
3.20
EPS
final double EPS = 1E-8 static private
Workaround for rounding errors.
LINEAR_TOLERANCE
final double LINEAR_TOLERANCE = 1.0 static
Default tolerance threshold for comparing ordinate values in a projected CRS, assuming that the unit of measurement is metre.
This is not a tolerance for testing map projection accuracy.
Since
3.20
ULP_TOLERANCE
final int ULP_TOLERANCE = 4 static private
Floating point tolerance in <cite>Unit in Last Place</cite> (ULP).
Used in order to determine if an integer can be rounded.