jena-geo: Axes Class Reference
Axes Class Reference
Predefined axes.
Static Public Attributes
static final DefaultCoordinateSystemAxis LONGITUDE
Default axis info for longitudes.
static final DefaultCoordinateSystemAxis LATITUDE
Default axis info for latitudes.
static final DefaultCoordinateSystemAxis ELLIPSOIDAL_HEIGHT
The default axis for height values above the ellipsoid in a org.opengis.referencing.crs.GeographicCRS geographic CRS}.
static final DefaultCoordinateSystemAxis X
Default axis info for x values in a org.opengis.referencing.cs.CartesianCS Cartesian CS}.
static final DefaultCoordinateSystemAxis Y
Default axis info for y values in a org.opengis.referencing.cs.CartesianCS Cartesian CS}.
static final DefaultCoordinateSystemAxis Z
Default axis info for z values in a org.opengis.referencing.cs.CartesianCS Cartesian CS}.
static final DefaultCoordinateSystemAxis EASTING
Default axis info for Easting values in a org.opengis.referencing.crs.ProjectedCRS projected CRS}.
static final DefaultCoordinateSystemAxis NORTHING
Default axis info for Northing values in a org.opengis.referencing.crs.ProjectedCRS projected CRS}.
static final DefaultCoordinateSystemAxis COLUMN
A default axis for column indices in a org.geotoolkit.coverage.grid.GridCoverage grid coverage}.
static final DefaultCoordinateSystemAxis ROW
A default axis for row indices in a org.geotoolkit.coverage.grid.GridCoverage grid coverage}.
Static Package Functions
static CoordinateSystemAxis usingUnit (final CoordinateSystemAxis a, final Unit<?> newUnit) throws IncommensurableException
Returns a new axis with the same properties than current axis except for the units.
Private Member Functions
Axes ()
Static Private Member Functions
static DefaultCoordinateSystemAxis create (final int name, final String abbreviation, final AxisDirection direction, final Unit<?> unit)
Constructs an axis with a name and an abbreviation as a resource bundle key.
Detailed Description
Predefined axes.
Warning: this is a temporary class which may disappear in future Geotk version, after we migrated functionality to Apache SIS.
Author
Martin Desruisseaux (IRD, Geomatys)
Constructor & Destructor Documentation
Axes()
Axes () private
                    {
     }
Member Function Documentation
create()
static DefaultCoordinateSystemAxis create (final int name, final String abbreviation, final AxisDirection direction, final Unit<?> unit) static private
Constructs an axis with a name and an abbreviation as a resource bundle key.
To be used for construction of pre-defined constants only.
Parameters
name The resource bundle key for the name, or
-1
if none.
abbreviation The #getAbbreviation abbreviation} used for this coordinate system axes.
direction The #getDirection direction} of this coordinate system axis.
unit The #getUnit unit of measure} used for this coordinate system axis.
References Vocabulary.formatInternational().
     {
         final Map<String,Object> properties = new HashMap<>(4);
         if (name >= 0) {
             final InternationalString n = Vocabulary.formatInternational(name);
             properties.put(IdentifiedObject.NAME_KEY, n.toString(null));
             properties.put(IdentifiedObject.ALIAS_KEY, n);
         } else {
             properties.put(IdentifiedObject.NAME_KEY, abbreviation);
         }
         final DefaultCoordinateSystemAxis axis = new DefaultCoordinateSystemAxis(properties, abbreviation, direction, unit);
         return axis;
     }
usingUnit()
static CoordinateSystemAxis usingUnit (final CoordinateSystemAxis a, final Unit<?> newUnit) throws IncommensurableException static package
Returns a new axis with the same properties than current axis except for the units.
Parameters
newUnit The unit for the new axis.
Returns
An axis using the specified unit.
Exceptions
IncommensurableException If the specified unit is incompatible with the expected one.
References PredefinedCS.getProperties().
Referenced by PredefinedCS.axisUsingUnit().
     {
         final Unit<?> unit = a.getUnit();
         if (unit.equals(newUnit)) {
             return a;
         }
         final UnitConverter converter = unit.getConverterToAny(newUnit);
         final Map<String,Object> properties = new HashMap<>(PredefinedCS.getProperties(a, null));
         properties.put(DefaultCoordinateSystemAxis.MINIMUM_VALUE_KEY, converter.convert(a.getMinimumValue()));
         properties.put(DefaultCoordinateSystemAxis.MAXIMUM_VALUE_KEY, converter.convert(a.getMaximumValue()));
         properties.put(DefaultCoordinateSystemAxis.RANGE_MEANING_KEY, a.getRangeMeaning()); // TODO: should be provided by getProperties
         return new DefaultCoordinateSystemAxis(properties, a.getAbbreviation(), a.getDirection(), newUnit);
     }
Member Data Documentation
COLUMN
final DefaultCoordinateSystemAxis COLUMN static
Initial value:
= create(
            Vocabulary.Keys.Column, "i", AxisDirection.COLUMN_POSITIVE, Units.UNITY)
A default axis for column indices in a org.geotoolkit.coverage.grid.GridCoverage grid coverage}.
Increasing values go toward AxisDirection::COLUMN_POSITIVE positive column number}.
The abbreviation is lower case "<var>i</var>".
EASTING
final DefaultCoordinateSystemAxis EASTING static
Initial value:
= create(
            Vocabulary.Keys.Easting, "E", AxisDirection.EAST, Units.METRE)
Default axis info for Easting values in a org.opengis.referencing.crs.ProjectedCRS projected CRS}.
Increasing coordinates values go AxisDirection::EAST East} and units are Units::METRE metres}.
The ISO 19111 name is "<cite>easting</cite>" and the abbreviation is upper case "<var>E</var>".
This axis is usually part of a EASTING, NORTHING set.
ELLIPSOIDAL_HEIGHT
final DefaultCoordinateSystemAxis ELLIPSOIDAL_HEIGHT static
Initial value:
= create(
            Vocabulary.Keys.EllipsoidalHeight, "h", AxisDirection.UP, Units.METRE)
The default axis for height values above the ellipsoid in a org.opengis.referencing.crs.GeographicCRS geographic CRS}.
Increasing coordinates values go AxisDirection::UP up} and units are Units::METRE metres}.
The ISO 19111 name is "<cite>ellipsoidal heigt</cite>" and the abbreviation is lower case "<var>h</var>".
This axis is usually part of a GEODETIC_LONGITUDE, GEODETIC_LATITUDE, ELLIPSOIDAL_HEIGHT set.
See also
#ALTITUDE
#GEOCENTRIC_RADIUS
#GRAVITY_RELATED_HEIGHT
#DEPTH
Referenced by ReferencingFactoryContainer.toGeodetic3D().
LATITUDE
final DefaultCoordinateSystemAxis LATITUDE static
Initial value:
= create(
            Vocabulary.Keys.Latitude, "\u03C6", AxisDirection.NORTH, Units.DEGREE)
Default axis info for latitudes.
Increasing coordinates values go AxisDirection::NORTH North} and units are Units::DEGREE decimal degrees}.
The abbreviation is "&phi;" (phi).
This axis is usually part of a LONGITUDE, LATITUDE, ALTITUDE set.
LONGITUDE
final DefaultCoordinateSystemAxis LONGITUDE static
Initial value:
= create(
            Vocabulary.Keys.Longitude, "\u03BB", AxisDirection.EAST, Units.DEGREE)
Default axis info for longitudes.
Increasing coordinates values go AxisDirection::EAST East} and units are Units::DEGREE decimal degrees}.
The abbreviation is "&lambda;" (lambda).
This axis is usually part of a LONGITUDE, LATITUDE, ALTITUDE set.
NORTHING
final DefaultCoordinateSystemAxis NORTHING static
Initial value:
= create(
            Vocabulary.Keys.Northing, "N", AxisDirection.NORTH, Units.METRE)
Default axis info for Northing values in a org.opengis.referencing.crs.ProjectedCRS projected CRS}.
Increasing coordinates values go AxisDirection::NORTH North} and units are Units::METRE metres}.
The ISO 19111 name is "<cite>northing</cite>" and the abbreviation is upper case "<var>N</var>".
This axis is usually part of a EASTING, NORTHING set.
ROW
final DefaultCoordinateSystemAxis ROW static
Initial value:
= create(
            Vocabulary.Keys.Row, "j", AxisDirection.ROW_POSITIVE, Units.UNITY)
A default axis for row indices in a org.geotoolkit.coverage.grid.GridCoverage grid coverage}.
Increasing values go toward AxisDirection::ROW_POSITIVE positive row number}.
The abbreviation is lower case "<var>j</var>".
X
final DefaultCoordinateSystemAxis X static
Initial value:
= create(
            -1, "x", AxisDirection.EAST, Units.METRE)
Default axis info for x values in a org.opengis.referencing.cs.CartesianCS Cartesian CS}.
Increasing coordinates values go AxisDirection::EAST East} and units are Units::METRE metres}.
The abbreviation is lower case "<var>x</var>".
This axis is usually part of a X, Y, Z set.
See also
EASTING
#WESTING
#GEOCENTRIC_X
#DISPLAY_X
COLUMN
Y
final DefaultCoordinateSystemAxis Y static
Initial value:
= create(
            -1, "y", AxisDirection.NORTH, Units.METRE)
Default axis info for y values in a org.opengis.referencing.cs.CartesianCS Cartesian CS}.
Increasing coordinates values go AxisDirection::NORTH North} and units are Units::METRE metres}.
The abbreviation is lower case "<var>y</var>".
This axis is usually part of a X, Y, Z set.
See also
NORTHING
#SOUTHING
#GEOCENTRIC_Y
#DISPLAY_Y
ROW
Z
final DefaultCoordinateSystemAxis Z static
Initial value:
= create(
            -1, "z", AxisDirection.UP, Units.METRE)
Default axis info for z values in a org.opengis.referencing.cs.CartesianCS Cartesian CS}.
Increasing coordinates values go AxisDirection::UP up} and units are Units::METRE metres}.
The abbreviation is lower case "<var>z</var>".
This axis is usually part of a X, Y, Z set.