jena-geo: ValueRestriction Class Reference
ValueRestriction Class Reference
Restrictions that apply on a metadata property.
Public Member Functions
final ValueRestriction violation (final Object value)
If the given value violate at least one restriction, returns the restrictions that are violated.
boolean equals (final Object other)
Compares the given object with this restriction for equality.
int hashCode ()
Returns a hash code value for this restriction.
String toString ()
Returns a string representation of this restriction.
Static Public Member Functions
static ValueRestriction create (final ExtendedElementInformation info)
Converts the given.
Public Attributes
final Obligation obligation
Whatever the property is Obligation::MANDATORY mandatory} or Obligation::FORBIDDEN forbidden}, or.
final NumberRange<?> range
The range of valid values, or.
final Set<?> validValues
An enumeration of valid values, or.
Protected Member Functions
ValueRestriction (final Obligation obligation, final NumberRange<?> range, final Set<?> validValues)
Creates a new.
Static Package Attributes
static final ValueRestriction PENDING = new ValueRestriction(null, null, null)
A sentinel value meaning that the restriction has not yet been calculated.
Static Private Member Functions
static ValueRestriction create (final Obligation obligation, final NumberRange<?> range, final Set<?> validValues)
Creates a new.
Static Private Attributes
static final long serialVersionUID = 888961503200860655L
For cross-versions compatibility.
static final WeakHashSet< ValueRestriction > POOL = new WeakHashSet<>(ValueRestriction.class)
The instances created in this JVM.
Detailed Description
Restrictions that apply on a metadata property.
Instances of
ValueRestriction
are created only for properties having at least one non-null obligation}, range} or validValues valid values enumeration} restriction.
For a given metadata instances (typically an AbstractMetadata subclasses, but other types are allowed), instances of
ValueRestriction
are obtained indirectly by the MetadataStandard.asRestrictionMap(...) method.
ValueRestriction
objects do not contain the type of values (except indirectly through NumberRange#getElementType() or org.geotoolkit.util.collection.CheckedCollection#getElementType()) because this particular requirement is specified by other means, like MetadataStandard.asTypeMap(...).
Author
Martin Desruisseaux (Geomatys)
Version
3.05
See also
MetadataStandard::asRestrictionMap(Object, NullValuePolicy, KeyNamePolicy)
Since
3.04
Deprecated:
Moved to Apache SIS as org.apache.sis.metadata.MetadataStandard#asInformationMap.
Constructor & Destructor Documentation
ValueRestriction()
ValueRestriction (final Obligation obligation, final NumberRange<?> range, final Set<?> validValues) protected
Creates a new.
Restriction
instance. This constructor does not clone any argument; this is caller responsibility to provide immutable instance of them, especially
validValues
.
{
Note
This constructor is not public in order to force subclassing. Subclasses shall choose a policy regarding whatever the arguments are cloned. This base class does not clone them because the same set of valid values (for example) is often shared for many metdata attributes.}
Parameters
obligation Whatever the property is mandatory or forbidden, or
null
if unknown.
range The range of valid values, or
null
if none.
validValues An enumeration of valid values, or
null
if none.
Since
3.05
References ValueRestriction.obligation, ValueRestriction.range, and ValueRestriction.validValues.
Referenced by ValueRestriction.create(), and ValueRestriction.equals().
{
         this.obligation  = obligation;
         this.range       = range;
         this.validValues = validValues;
     }
Member Function Documentation
create() [1/2]
static ValueRestriction create (final Obligation obligation, final NumberRange<?> range, final Set<?> validValues) static private
Creates a new.
ValueRestriction
instance. If all arguments are
null
, then this method returns
null
meaning "<cite>no restriction</cite>".
Parameters
obligation Whatever the property is mandatory or forbidden, or
null
if unknown.
range The range of valid values, or
null
if none.
validValues An enumeration of valid values, or
null
if none.
Returns
The restriction, or
null
if none.
References ValueRestriction.ValueRestriction().
Referenced by ValueRestriction.create(), and ValueRestriction.violation().
{
         if (range == null && validValues == null && obligation != Obligation.MANDATORY && obligation != Obligation.FORBIDDEN) {
             return null;
         }
         return POOL.unique(new ValueRestriction(obligation, range, validValues));
     }
create() [2/2]
static ValueRestriction create (final ExtendedElementInformation info) static
Converts the given.
ExtendedElementInformation
to a
ValueRestriction
.
References ValueRestriction.create().
{
         if (info != null) {
             final Obligation o = info.getObligation();
             final InternationalString domain = info.getDomainValue();
             return create((o != null) ? Obligation.valueOf(o.name()) : null,
                     (domain instanceof NumberRange<?>) ? (NumberRange<?>) domain : null,
                     (domain instanceof Set<?>) ? (Set<?>) domain : null);
         }
         return null;
     }
equals()
boolean equals (final Object other)
Compares the given object with this restriction for equality.
Parameters
other The object to compare with this restriction for equality.
Returns
true
if both objects are equal.
References ValueRestriction.equals(), ValueRestriction.obligation, ValueRestriction.range, ValueRestriction.validValues, and ValueRestriction.ValueRestriction().
Referenced by ValueRestriction.equals().
{
         if (other != null && other.getClass() == getClass()) {
             final ValueRestriction that = (ValueRestriction) other;
             return (this.obligation == that.obligation) &&
                    Objects.equals(this.range,       that.range) &&
                    Objects.equals(this.validValues, that.validValues);
         }
         return false;
     }
hashCode()
int hashCode ()
Returns a hash code value for this restriction.
{
         int code = (int) serialVersionUID;
         if (obligation != null) {
             code ^= obligation.hashCode();
         }
         if (range != null) {
             code ^= range.hashCode();
         }
         if (validValues != null) {
             code ^= validValues.hashCode();
         }
         return code;
     }
toString()
String toString ()
Returns a string representation of this restriction.
{
         final StringBuilder buffer = new StringBuilder(Classes.getShortClassName(this)).append('[');
         String separator = "";
         if (obligation != null) {
             buffer.append(obligation.name());
             separator = ", ";
         }
         if (range != null) {
             buffer.append(separator).append("range=").append(range);
             separator = ", ";
         }
         if (validValues != null) {
             buffer.append(separator).append("validValues=").append(validValues);
         }
         return buffer.append(']').toString();
     }
violation()
final ValueRestriction violation (final Object value)
If the given value violate at least one restriction, returns the restrictions that are violated.
Otherwise returns
null
.
Parameters
value The value to test (may be
null
).
Returns
null
if the given value does not violate the restrictions.
References ValueRestriction.create(), ValueRestriction.obligation, ValueRestriction.range, and ValueRestriction.validValues.
{
         Obligation obligation = this.obligation;
         NumberRange<?>  range = this.range;
         Set<?>    validValues = this.validValues;
         boolean       changed = false;
         /*
          * If the value does not violate the obligation, set the obligation to null.
          */
         if (obligation != ((value == null) ? Obligation.MANDATORY : Obligation.FORBIDDEN)) {
             obligation = null;
             changed = true;
         }
         /*
          * If the value is not outside the range, set the range to null.
          */
         if (value == null || range == null || (value instanceof Number && range.containsAny((Number) value))) {
             range = null;
             changed = true;
         }
         /*
          * If the value is a member of the set of valid values, set the valid values to null.
          */
         if (value == null || validValues == null || validValues.contains(value)) {
             validValues = null;
             changed = true;
         }
         return changed ? create(obligation, range, validValues) : this;
     }
Member Data Documentation
obligation
final Obligation obligation
Whatever the property is Obligation::MANDATORY mandatory} or Obligation::FORBIDDEN forbidden}, or.
null
if there is no known restriction.
The Obligation::OPTIONAL optional} obligation is considered equivalent to an absence of restriction and is replaced by
null
if MetadataStandard.asRestrictionMap(...) has been invoked with a metadata instance, since the metadata is not violating this obligation. If
asRestrictionMap(...)
has been invoked with a Class argument instead, then the obligation is provided verbatism since we are not testing violation of restrictions.
Referenced by ValueRestriction.equals(), ValueRestriction.ValueRestriction(), and ValueRestriction.violation().
PENDING
final ValueRestriction PENDING = new ValueRestriction(null, null, null) static package
A sentinel value meaning that the restriction has not yet been calculated.
POOL
final WeakHashSet<ValueRestriction> POOL = new WeakHashSet<>(ValueRestriction.class) static private
The instances created in this JVM.
In many case, the same restriction will be shared by many attributes (e.g. restricting the range of values to 0 .. 100 for percentage).
range
final NumberRange<?> range
The range of valid values, or.
null
if the values are not restricted by a range. This restriction is typically exclusive with the validValues enumeration of valid values} (i.e. only one of
range
or
validValues
is non-null), but this is not enforced by this
ValueRestriction
class.
Referenced by ValueRestriction.equals(), ValueRestriction.ValueRestriction(), and ValueRestriction.violation().
serialVersionUID
final long serialVersionUID = 888961503200860655L static private
For cross-versions compatibility.
validValues
final Set<?> validValues
An enumeration of valid values, or.
null
if the values are not restricted that way. This restriction is typically exclusive with the range range of valid values} (i.e. only one of
range
or
validValues
is non-null), but this is not enforced by this
ValueRestriction
class.
Since
3.05
Referenced by ValueRestriction.equals(), ValueRestriction.ValueRestriction(), and ValueRestriction.violation().