jena-geo: AbstractParameterValue< T > Class Template Reference
AbstractParameterValue< T > Class Template Reference abstract
The base class of ParameterValue implementations.
Public Member Functions
ParameterDescriptor< T > getDescriptor ()
Returns the abstract definition of this parameter.
void addChangeListener (final ChangeListener listener)
Adds the specified listener to the list of objects to inform when the value changed.
void removeChangeListener (final ChangeListener listener)
Removes the specified listener from the list of objects to inform when the value changed.
AbstractParameterValue< T > clone ()
Returns a clone of this parameter.
boolean equals (final Object object)
Compares the specified object with this parameter for equality.
int hashCode ()
Returns a hash value for this parameter.
String formatTo (final Formatter formatter)
Formats the inner part of this parameter as Well Known Text (WKT).
Protected Member Functions
AbstractParameterValue (final ParameterDescriptor< T > descriptor)
Constructs a parameter value from the specified descriptor.
final void fireValueChanged ()
Informs every listeners that the value changed.
Static Protected Member Functions
static IllegalStateException unitlessParameter (final GeneralParameterDescriptor descriptor)
Returns an exception initialized with a "Unitless parameter" error message for the specified descriptor.
static String getName (final GeneralParameterDescriptor descriptor)
Convenience method returning the name of the specified descriptor.
Protected Attributes
final GeneralParameterDescriptor descriptor
The abstract definition of this parameter or group of parameters.
Package Functions
static< T > T ensureValidValue (final ParameterDescriptor< T > descriptor, final Object value) throws InvalidParameterValueException
Ensures that the given value is valid according the specified parameter descriptor.
Static Package Functions
static short getUnitMessageID (final Unit<?> unit)
Returns the unit type as one of error message code.
Private Attributes
transient ChangeListener [] listeners
The listeners, or.
Static Private Attributes
static final long serialVersionUID = 4166422894375776520L
Serial number for inter-operability with different versions.
Detailed Description
The base class of ParameterValue implementations.
This base class provides support for ChangeListener notifications. Those change listeners are not included in the serialization neither in clone() cloned} objects.
Parameters
<T> The value type.
Deprecated:
Replaced by Apache SIS parameters.
Constructor & Destructor Documentation
AbstractParameterValue()
AbstractParameterValue (final ParameterDescriptor< T > descriptor) protected
Constructs a parameter value from the specified descriptor.
Parameters
descriptor The abstract definition of this parameter.
{
         super(descriptor);
     }
Member Function Documentation
addChangeListener()
void addChangeListener (final ChangeListener listener)
Adds the specified listener to the list of objects to inform when the value changed.
Notes:
Change listeners are not serialized
Change listeners are not included in clone() cloned} object.
Parameters
listener The listener to add.
{
         listeners = Listeners.addListener(listener, listeners);
     }
clone()
AbstractParameterValue<T> clone ()
Returns a clone of this parameter.
The clone does not include any change listener.
Implements Cloneable.
Referenced by AbstractParameterValue< Double >.clone().
{
         @SuppressWarnings("unchecked")
         final AbstractParameterValue<T> copy = (AbstractParameterValue<T>) super.clone();
         copy.listeners = null;
         return copy;
     }
ensureValidValue()
static<T> T ensureValidValue (final ParameterDescriptor< T > descriptor, final Object value) throws InvalidParameterValueException package inherited
Ensures that the given value is valid according the specified parameter descriptor.
This convenience method ensures that
value
is assignable to the ParameterDescriptor::getValueClass() expected class}, is between the ParameterDescriptor::getMinimumValue() minimum} and ParameterDescriptor::getMaximumValue() maximum} values and is one of the ParameterDescriptor::getValidValues() set of valid values}. If the value fails any of those tests, then an exception is thrown.
This method is similar to Parameters#isValid(ParameterValue) except that the exception contains an error message formatted with a description of the failure raison.
Parameters
<T> The type of parameter value. The given
value
should typically be an instance of this class. This is not required by this method signature but is checked by this method implementation.
descriptor The parameter descriptor to check against.
value The value to check, or
null
.
Returns
The value casted to the descriptor parameterized type, or the ParameterDescriptor::getDefaultValue() default value} if the given value was null while the parameter is mandatory.
Exceptions
InvalidParameterValueException if the parameter value is invalid.
References Errors.format(), AbstractParameter.getName(), Errors.Keys.IllegalArgument_2, Errors.Keys.IllegalOperationForValueClass_1, and Errors.Keys.ValueOutOfBounds_3.
Referenced by Parameter< T >.setValue().
     {
         if (value == null) {
             if (descriptor.getMinimumOccurs() != 0) {
                 return descriptor.getDefaultValue();
             }
             return null;
         }
         final String error;
         /*
          * Note: the implementation below is similar (except for different error message) to the
          * one in Parameters.isValidValue(ParameterDescriptor, Object). If one implementation is
          * modified, the other should be updated accordingly. The main difference is that null
          * values are replaced by the default value instead than being a conformance error.
          */
         final Class<T> type = descriptor.getValueClass();
         if (!type.isInstance(value)) {
             error = Errors.format(Errors.Keys.IllegalOperationForValueClass_1, value.getClass());
         } else {
             final T typedValue = type.cast(value);
             final Comparable<T> minimum = descriptor.getMinimumValue();
             final Comparable<T> maximum = descriptor.getMaximumValue();
             if ((minimum != null && minimum.compareTo(typedValue) > 0) ||
                 (maximum != null && maximum.compareTo(typedValue) < 0))
             {
                 error = Errors.format(Errors.Keys.ValueOutOfBounds_3, value, minimum, maximum);
             } else {
                 final Set<T> validValues = descriptor.getValidValues();
                 if (validValues!=null && !validValues.contains(value)) {
                     error = Errors.format(Errors.Keys.IllegalArgument_2, getName(descriptor), value);
                 } else {
                     /*
                      * Passed every tests - the value is valid.
                      */
                     return typedValue;
                 }
             }
         }
         throw new InvalidParameterValueException(error, getName(descriptor), value);
     }
equals()
boolean equals (final Object object) inherited
Compares the specified object with this parameter for equality.
Parameters
object The object to compare to
this
.
Returns
true
if both objects are equal.
References AbstractParameter.AbstractParameter(), AbstractParameter.descriptor, and AbstractParameter.equals().
Referenced by AbstractParameter.equals().
{
         if (object != null && object.getClass() == getClass()) {
             final AbstractParameter that = (AbstractParameter) object;
             return Objects.equals(this.descriptor, that.descriptor);
         }
         return false;
     }
fireValueChanged()
final void fireValueChanged () protected
Informs every listeners that the value changed.
Referenced by Parameter< T >.setSafeValue().
{
         Listeners.fireChanged(this, listeners);
     }
formatTo()
String formatTo (final Formatter formatter) inherited
Formats the inner part of this parameter as Well Known Text (WKT).
References AbstractParameter.Bridge< T >.formatTo().
{
         if (this instanceof ParameterValue<?>) {
             return new Bridge((ParameterValue<?>) this).formatTo(formatter);
         }
         return "PARAMETER";
     }
getDescriptor()
ParameterDescriptor<T> getDescriptor ()
Returns the abstract definition of this parameter.
{
         return (ParameterDescriptor<T>) super.getDescriptor();
     }
getName()
static String getName (final GeneralParameterDescriptor descriptor) static protected inherited
Convenience method returning the name of the specified descriptor.
This method is used mostly for output to be read by human, not for processing. Consequently, we may consider to returns a localized name in a future version.
Referenced by Parameter< T >.booleanValue(), Parameter< T >.doubleValue(), Parameter< T >.doubleValueList(), ParameterGroup.ensureValidOccurs(), AbstractParameter.ensureValidValue(), Parameter< T >.intValue(), Parameter< T >.intValueList(), Parameters.isValidValue(), Parameter< T >.stringValue(), AbstractParameter.unitlessParameter(), and Parameter< T >.valueFile().
{
         return descriptor.getName().getCode();
     }
getUnitMessageID()
static short getUnitMessageID (final Unit<?> unit) static package inherited
Returns the unit type as one of error message code.
Used for checking unit with a better error message formatting if needed.
References Errors.Keys.IncompatibleUnit_1, Errors.Keys.NonAngularUnit_1, Errors.Keys.NonLinearUnit_1, Errors.Keys.NonScaleUnit_1, and Errors.Keys.NonTemporalUnit_1.
Referenced by Parameter< T >.doubleValue(), Parameter< T >.doubleValueList(), and Parameter< T >.setValue().
{
         if (Units.isLinear  (unit)) return Errors.Keys.NonLinearUnit_1;
         if (Units.isAngular (unit)) return Errors.Keys.NonAngularUnit_1;
         if (Units.isTemporal(unit)) return Errors.Keys.NonTemporalUnit_1;
         if (Units.isScale   (unit)) return Errors.Keys.NonScaleUnit_1;
         return Errors.Keys.IncompatibleUnit_1;
     }
hashCode()
int hashCode () inherited
Returns a hash value for this parameter.
This value doesn't need to be the same in past or future versions of this class.
{
         return descriptor.hashCode() ^ (int) serialVersionUID;
     }
removeChangeListener()
void removeChangeListener (final ChangeListener listener)
Removes the specified listener from the list of objects to inform when the value changed.
Parameters
listener The listener to remove.
{
         listeners = Listeners.removeListener(listener, listeners);
     }
unitlessParameter()
static IllegalStateException unitlessParameter (final GeneralParameterDescriptor descriptor) static protected inherited
Returns an exception initialized with a "Unitless parameter" error message for the specified descriptor.
References Errors.format(), AbstractParameter.getName(), and Errors.Keys.UnitlessParameter_1.
Referenced by Parameter< T >.doubleValue(), Parameter< T >.doubleValueList(), and Parameter< T >.setValue().
{
         return new IllegalStateException(Errors.format(
                 Errors.Keys.UnitlessParameter_1, getName(descriptor)));
     }
Member Data Documentation
descriptor
final GeneralParameterDescriptor descriptor protected inherited
The abstract definition of this parameter or group of parameters.
Referenced by AbstractParameter.AbstractParameter(), ParameterGroup.addGroup(), Parameter< T >.booleanValue(), Parameter< T >.doubleValue(), Parameter< T >.doubleValueList(), ParameterGroup.ensureValidOccurs(), AbstractParameter.equals(), Parameter< T >.getClassTypeError(), AbstractParameter.getDescriptor(), ParameterGroup.groups(), Parameter< T >.intValue(), Parameter< T >.intValueList(), Parameter< T >.Parameter(), ParameterGroup.parameter(), Parameter< T >.setValue(), Parameter< T >.stringValue(), Parameter< T >.valueFile(), and ParameterGroup.values().
listeners
transient ChangeListener [] listeners private
The listeners, or.
null
if none.
Referenced by AbstractParameterValue< Double >.addChangeListener(), AbstractParameterValue< Double >.clone(), AbstractParameterValue< Double >.fireValueChanged(), and AbstractParameterValue< Double >.removeChangeListener().
serialVersionUID
final long serialVersionUID = 4166422894375776520L static private
Serial number for inter-operability with different versions.