jena-geo: CRS Class Reference
CRS Class Reference
Utility class for making use of the CoordinateReferenceSystem Coordinate Reference System} and associated org.opengis.util.Factory} implementations.
Static Public Member Functions
static CoordinateOperationFactory getCoordinateOperationFactory (final boolean lenient)
static Version getVersion (final String authority) throws FactoryRegistryException
static CompoundCRS getCompoundCRS (final CompoundCRS crs, final SingleCRS... components)
Returns the first compound CRS which contains only the given components, in any order.
static CoordinateReferenceSystem getOrCreateSubCRS (CoordinateReferenceSystem crs, int lower, int upper)
static Datum getDatum (final CoordinateReferenceSystem crs)
static double [] deltaTransform (final MathTransform transform, final DirectPosition origin, final double... vector) throws TransformException
Transforms the given relative distance using the given transform.
Private Member Functions
CRS ()
Do not allow instantiation of this class.
Static Private Member Functions
static int decomposeCRS (CoordinateReferenceSystem crs, int lower, int upper, final List< CoordinateReferenceSystem > parts)
Internal use only.
static boolean isGeodetic3D (final Datum geodetic, final Datum vertical)
Returns.
Detailed Description
Utility class for making use of the CoordinateReferenceSystem Coordinate Reference System} and associated org.opengis.util.Factory} implementations.
This utility class is made up of static functions working with arbitrary implementations of GeoAPI interfaces.
The methods defined in this class can be grouped in three categories:
Methods working with factories, like decode(String).
Methods providing informations, like isHorizontalCRS(CoordinateReferenceSystem).
Methods performing coordinate transformations, like transform(CoordinateOperation,Envelope) Note that many of those methods are also defined in the Envelopes class.
Author
Martin Desruisseaux (IRD, Geomatys)
Jody Garnett (Refractions)
Andrea Aime (TOPP)
Version
3.19
See also
IdentifiedObjects
Envelopes
Since
2.1
Constructor & Destructor Documentation
CRS()
CRS () private
Do not allow instantiation of this class.
                   {
     }
Member Function Documentation
decomposeCRS()
static int decomposeCRS (CoordinateReferenceSystem crs, int lower, int upper, final List< CoordinateReferenceSystem > parts) static private
Internal use only.
Fill a list of CoordinateReferenceSystem with CRS parts in the given lower/upper range.
Parameters
crs CoordinateReferenceSystem to decompose
lower dimension start range
upper dimension start range
parts used to stack CoordinateReferenceSystem when decomposing CRS.
Returns
number of dimensions used, -1 if the current crs could not be decomposed to match lower/upper bounds
Referenced by CRS.getOrCreateSubCRS().
{
         final int dimension = crs.getCoordinateSystem().getDimension();
         if (lower == 0 && dimension <= upper) {
             // Dimension is smaller or exactly match, no need to decompse the crs
             parts.add(crs);
             return dimension;
         } else if (lower >= dimension){
             // Skip this CRS
             return dimension;
         }
         // CRS can not be decomposed
         if (!(crs instanceof CompoundCRS)) return -1;
         int nbDimRead = 0;
         final List<CoordinateReferenceSystem> components = ((CompoundCRS) crs).getComponents();
         for (CoordinateReferenceSystem component : components) {
             int res = decomposeCRS(component, lower, upper, parts);
             if (res == -1) {
                 // Sub element could not be decomposed
                 return -1;
             }
             nbDimRead += res;
             lower = Math.max(0, lower-res);
             upper = Math.max(0, upper-res);
             if (upper == 0) break;
         }
         return nbDimRead;
     }
deltaTransform()
static double [] deltaTransform (final MathTransform transform, final DirectPosition origin, final double... vector) throws TransformException static
Transforms the given relative distance using the given transform.
A relative distance vector is transformed without applying the translation components. However it needs to be computed at a particular location, given by the
origin
parameter in units of the source CRS.
Parameters
transform The transformation to apply.
origin The position where to compute the delta transform in the source CRS.
vector The distance vector to be delta transformed.
Returns
The result of the delta transformation.
Exceptions
TransformException if the transformation failed.
See also
AffineTransform::deltaTransform(Point2D, Point2D)
Since
3.10 (derived from 2.3)
References Errors.format(), and Errors.Keys.MismatchedDimension_3.
     {
         ensureNonNull("transform", transform);
         final int sourceDim = transform.getSourceDimensions();
         final int targetDim = transform.getTargetDimensions();
         final double[] result = new double[targetDim];
         if (vector.length != sourceDim) {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.MismatchedDimension_3,
                     "vector", vector.length, sourceDim));
         }
         if (transform instanceof AffineTransform) {
             ((AffineTransform) transform).deltaTransform(vector, 0, result, 0, 1);
         } else {
             /*
              * If the optimized case in the previous "if" statement can't be used,
              * use a more generic (but more costly) algorithm.
              */
             final double[] coordinates = new double[2 * Math.max(sourceDim, targetDim)];
             for (int i=0; i<sourceDim; i++) {
                 final double c = origin.getOrdinate(i);
                 final double d = vector[i] * 0.5;
                 coordinates[i] = c - d;
                 coordinates[i + sourceDim] = c + d;
             }
             transform.transform(coordinates, 0, coordinates, 0, 2);
             for (int i=0; i<targetDim; i++) {
                 result[i] = coordinates[i + targetDim] - coordinates[i];
             }
         }
         return result;
     }
getCompoundCRS()
static CompoundCRS getCompoundCRS (final CompoundCRS crs, final SingleCRS... components) static
Returns the first compound CRS which contains only the given components, in any order.
First, this method gets the SingleCRS components of the given compound CRS. If all those components are #equalsIgnoreMetadata equal, ignoring metadata} and order, to the
SingleCRS
components given to this method, then the given
CompoundCRS
is returned. Otherwise if the given
CompoundCRS
contains nested
CompoundCRS
, then those nested CRS are inspected recursively by the same algorithm. Otherwise, this method returns
null
.
This method is useful for extracting metadata about the 3D spatial CRS part in a 4D spatio-temporal CRS. For example given the following CRS:
{ wkt COMPD_CS["Mercator + height + time", COMPD_CS["Mercator + height", PROJCS["Mercator", ...etc...] VERT_CS["Ellipsoidal height", ...etc...]] TemporalCRS["Modified Julian", ...etc...]] }
Then the following code will returns the nested
COMPD_CS["Mercator + height"]
without prior knowledge of the CRS component order (the time CRS could be first, and the vertical CRS could be before the horizontal one):
{ java CompoundCRS crs = ...; SingleCRS horizontalCRS = getHorizontalCRS(crs); VerticalCRS verticalCRS = getVerticalCRS(crs); if (horizontalCRS != null && verticalCRS != null) { CompoundCRS spatialCRS = getCompoundCRS(crs, horizontalCRS, verticalCRS); if (spatialCRS != null) { // ... } } }
Parameters
crs The compound CRS to compare with the given component CRS, or
null
.
components The CRS which must be components of the returned CRS.
Returns
A CRS which contains the given components, or
null
if none.
See also
DefaultCompoundCRS::getSingleCRS()
Since
3.16
Referenced by ReferencingUtilities.intersectEnvelopes(), and ReferencingFactoryContainer.toGeodetic3D().
{
         final List<SingleCRS> actualComponents = org.apache.sis.referencing.CRS.getSingleComponents(crs);
         if (actualComponents.size() == components.length) {
             int firstValid = 0;
             final SingleCRS[] toSearch = components.clone();
 compare:    for (final SingleCRS component : actualComponents) {
                 for (int i=firstValid; i<toSearch.length; i++) {
                     if (Utilities.equalsIgnoreMetadata(component, toSearch[i])) {
                         /*
                          * Found a match: remove it from the search list. Note that we copy the
                          * remaining components to the end of the array (which is unusual) rather
                          * than to the begining (as usual), in order to reduce the length of the
                          * part to copy on the assumption that the components given to this method
                          * are most likely in the same order than the elements in the CompoundCRS.
                          */
                         System.arraycopy(toSearch, firstValid, toSearch, firstValid+1, i - firstValid);
                         toSearch[firstValid++] = null;
                         continue compare;
                     }
                 }
                 // No match found. We can stop the loop now.
                 firstValid = -1;
                 break;
             }
             /*
              * If we found all the requested components and nothing more,
              * returns the CRS.
              */
             if (firstValid == toSearch.length) {
                 return crs;
             }
         }
         /*
          * Search recursively in the sub-components.
          */
         for (final CoordinateReferenceSystem component : crs.getComponents()) {
             if (component instanceof CompoundCRS) {
                 final CompoundCRS candidate = getCompoundCRS((CompoundCRS) component, components);
                 if (candidate != null) {
                     return candidate;
                 }
             }
         }
         return null;
     }
getCoordinateOperationFactory()
static CoordinateOperationFactory getCoordinateOperationFactory (final boolean lenient) static
{
         return DefaultFactories.forBuildin(CoordinateOperationFactory.class);
     }
getDatum()
static Datum getDatum (final CoordinateReferenceSystem crs) static
References CRS.isGeodetic3D().
{
         Datum datum = null;
         if (crs instanceof SingleCRS) {
             datum = ((SingleCRS) crs).getDatum();
         } else if (crs instanceof CompoundCRS) {
             for (final CoordinateReferenceSystem component : ((CompoundCRS) crs).getComponents()) {
                 final Datum candidate = getDatum(component);
                 if (datum != null && !datum.equals(candidate)) {
                     if (isGeodetic3D(datum, candidate)) {
                         continue;                               // Keep the current datum unchanged.
                     }
                     if (isGeodetic3D(candidate, datum)) {
                         continue;
                     }
                     return null;                                // Can't build a 3D geodetic datum.
                 }
                 datum = candidate;
             }
         }
         return datum;
     }
getOrCreateSubCRS()
static CoordinateReferenceSystem getOrCreateSubCRS (CoordinateReferenceSystem crs, int lower, int upper) static
Todo:
Duplicate of org.geotoolkit.referencing.factory.ReferencingFactoryContainer?
See also
https://issues.apache.org/jira/browse/SIS-162
References CRS.decomposeCRS(), Errors.format(), and Errors.Keys.IndexOutOfBounds_1.
{
         if (crs == null) return crs;
         int dimension = crs.getCoordinateSystem().getDimension();
         if (lower < 0 || lower > upper || upper > dimension) {
             throw new IndexOutOfBoundsException(Errors.format(
                     Errors.Keys.IndexOutOfBounds_1, lower < 0 ? lower : upper));
         }
         // Dimension exactly matches, no need to decompse the CRS
         if (lower == 0 && dimension == upper) return crs;
         // CRS can not be decomposed
         if (!(crs instanceof CompoundCRS)) return null;
         final List<CoordinateReferenceSystem> parts = new ArrayList<>(1);
         final int res = decomposeCRS(crs, lower, upper, parts);
         if (res == -1) {
             // CRS could not be divided
             return null;
         }
         final int size = parts.size();
         if (size == 1) {
             return parts.get(0);
         } else try {
             return org.apache.sis.referencing.CRS.compound(parts.toArray(new CoordinateReferenceSystem[size]));
         } catch (FactoryException e) {
             throw new IllegalArgumentException("Illegal CRS.", e);
         }
     }
getVersion()
static Version getVersion (final String authority) throws FactoryRegistryException static
{
         final String version;
         try {
             version = NameMeaning.getVersion(org.apache.sis.referencing.CRS.getAuthorityFactory(authority).getAuthority());
         } catch (FactoryException e) {
             throw new FactoryRegistryException(e.getLocalizedMessage(), e);
         }
         return (version != null) ? new Version(version) : null;
     }
isGeodetic3D()
static boolean isGeodetic3D (final Datum geodetic, final Datum vertical) static private
Returns.
true
if the given datum can form a three-dimensional geodetic datum.
Parameters
geodetic The presumed geodetic datum.
vertical The presumed vertical datum.
Returns
If the given datum can form a 3D geodetic datum.
Deprecated:
This is not right: we can not said that we have a match if we do not known on which geodetic datum the ellipsoidal height is.
Referenced by CRS.getDatum().
{
         return (geodetic instanceof GeodeticDatum) && (vertical instanceof VerticalDatum) &&
                 VerticalDatumTypes.ELLIPSOIDAL.equals(((VerticalDatum) vertical).getVerticalDatumType());
     }