jena-geo: Parameters Class Reference
Parameters Class Reference
Helper methods for working with the parameter API from org.opengis.parameter package.
Static Public Member Functions
static boolean isValid (final ParameterValue<?> value)
static ConformanceResult isValid (final GeneralParameterValue value, final GeneralParameterDescriptor descriptor)
static ParameterValue<?> getOrCreate (final ParameterDescriptor<?> parameter, final ParameterValueGroup group) throws ParameterNotFoundException
static List< GeneralParameterValue > search (final GeneralParameterValue parameter, final String name, int maxDepth)
static void copy (final GeneralParameterValue parameters, final Map<? super String, Object > destination)
static boolean ensureSet (final ParameterValueGroup parameters, final String name, final double value, final Unit<?> unit, boolean force) throws ParameterNotFoundException
static Map< String, Object > toMap (final ParameterValueGroup source)
Convert a ParameterValueGroup in a Map of values.
static ParameterValueGroup toParameter (final Map< String, ?> params, final ParameterDescriptorGroup desc)
Transform a Map in a ParameterValueGroup.
static ParameterValueGroup toParameter (final Map< String, ?> params, final ParameterDescriptorGroup desc, final boolean checkMandatory) throws ParameterNotFoundException, UnconvertibleObjectException
Transform a Map in a ParameterValueGroup.
static GeneralParameterValue getParameterOrGroup (ParameterValueGroup group, String name)
Get the first parameter for this name, do not create parameter if missing.
Static Public Attributes
static final ParameterDescriptorGroup EMPTY_GROUP
An empty parameter group.
Private Member Functions
Parameters ()
Do not allow instantiation of this utility class.
Static Private Member Functions
static< T > InternationalString isValidValue (final ParameterDescriptor< T > descriptor, final Object value, final boolean localized)
Checks a parameter value against its descriptor, and returns an error message if it is not conformant.
static GeneralParameterValue isValid (final GeneralParameterValue value, final GeneralParameterDescriptor descriptor, final DefaultConformanceResult result)
Checks a parameter value against the conditions specified by the given descriptor.
static String getName (final GeneralParameterDescriptor parameter, final ParameterDescriptorGroup group)
Returns the name of the given parameter, using the authority code space expected by the given group if possible.
static void search (final GeneralParameterValue parameter, final String name, final int maxDepth, final Collection< GeneralParameterValue > list)
Implementation of the search algorithm.
static StringBuilder copy (final GeneralParameterValue parameters, final Map<? super String, Object > destination, StringBuilder buffer, int base, final boolean isRoot)
static void copy (final ParameterValueGroup source, final ParameterValueGroup target)
static boolean containsKey (Map< String,?> params, GeneralParameterDescriptor desc)
Check if given descriptor name or aliases are contained in the map.
Static Private Attributes
static final double EPS = 1E-8
Small number for floating point comparisons.
static final InternationalString EXPLAIN
The explanation for conformance results.
Detailed Description
Helper methods for working with the parameter API from org.opengis.parameter package.
This class provides methods for search searching}, ensureSet setting a value}, etc. from a parameter name. Names in simple
String
form are preferred over the full
ParameterDescriptor
object because:
The parameter descriptor may not be always available. For example a user may looks for the
"semi_major"
axis length (because it is documented in OGC specification under that name) but doesn't know and doesn't care about who is providing the implementation. In such case, he doesn't have the parameter's descriptor. He only have the parameter's name, and creating a descriptor from that name (a descriptor independent of any implementation) is tedious.
Parameter descriptors are implementation-dependent. For example if a user searches for the above-cited
"semi_major"
axis length using the org.geotoolkit.referencing.operation.provider.MapProjection::SEMI_MAJOR Geotk's descriptor} for that parameter, we will fail to find this parameter in any alternative ParameterValueGroup implementations. This is against GeoAPI's inter-operability goal.
When a method in this class expects a full
ParameterDescriptor
object in argument (for example value(ParameterDescriptor, ParameterValueGroup)), the ParameterDescriptor::getName descriptor name} and alias are used for the search - this class does not look for strictly equal
ParameterDescriptor
objects.
Author
Jody Garnett (Refractions)
Martin Desruisseaux (IRD, Geomatys)
Version
3.20
Since
2.1
Constructor & Destructor Documentation
Parameters()
Parameters () private
Do not allow instantiation of this utility class.
{
     }
Member Function Documentation
containsKey()
static boolean containsKey (Map< String,?> params, GeneralParameterDescriptor desc) static private
Check if given descriptor name or aliases are contained in the map.
Referenced by Parameters.toParameter().
{
         //check the name
         if (params.containsKey(desc.getName().getCode())) {
             return true;
         }
         //check alias
         for (GenericName alias : desc.getAlias()) {
             if (params.containsKey(alias.tip().toString())) {
                 return true;
             }
         }
         return false;
     }
copy() [1/3]
static void copy (final GeneralParameterValue parameters, final Map<? super String, Object > destination) static
Referenced by Parameters.copy(), and Parameters.toParameter().
{
         copy(parameters, destination, null, 0, true);
     }
copy() [2/3]
static StringBuilder copy (final GeneralParameterValue parameters, final Map<? super String, Object > destination, StringBuilder buffer, int base, final boolean isRoot) static private
References Parameters.copy(), Errors.format(), and Errors.Keys.InconsistentValue.
     {
         final String name = parameters.getDescriptor().getName().getCode();
         if (parameters instanceof ParameterValue<?>) {
             final Object value = ((ParameterValue<?>) parameters).getValue();
             String key = name;
             if (base > 0) {
                 buffer.setLength(base);
                 key = buffer.append(name).toString();
             }
             final Object old = destination.put(key, value);
             if (old != null && !old.equals(value)) {
                 // This code will fails to detect if a null value was explicitly supplied
                 // previously. We assume that such case is uncommon and not a big deal.
                 throw new IllegalArgumentException(Errors.format(Errors.Keys.InconsistentValue));
             }
         }
         if (parameters instanceof ParameterValueGroup) {
             if (!isRoot) {
                 if (buffer == null) {
                     buffer = new StringBuilder(32);
                 }
                 buffer.setLength(base);
                 base = buffer.append(name).append(DefaultNameSpace.DEFAULT_SEPARATOR).length();
             }
             for (final GeneralParameterValue value : ((ParameterValueGroup) parameters).values()) {
                 buffer = copy(value, destination, buffer, base, false);
             }
         }
         return buffer;
     }
copy() [3/3]
static void copy (final ParameterValueGroup source, final ParameterValueGroup target) static private
References Parameters.copy().
{
         for (final GeneralParameterValue param : source.values()) {
             final String name = param.getDescriptor().getName().getCode();
             if (param instanceof ParameterValueGroup) {
                 copy((ParameterValueGroup) param, target.addGroup(name));
             } else {
                 target.parameter(name).setValue(((ParameterValue<?>) param).getValue());
             }
         }
     }
ensureSet()
static boolean ensureSet (final ParameterValueGroup parameters, final String name, final double value, final Unit<?> unit, boolean force) throws ParameterNotFoundException static
References Parameters.EPS, Errors.format(), and Errors.Keys.ValueAlreadyDefined_1.
     {
         final ParameterValue<?> parameter = parameters.parameter(name);
         try {
             final double current = parameter.doubleValue(unit);
             if (Math.abs(current / value - 1) <= EPS) {
                 return false;
             }
             if (Double.isNaN(current)) {
                 force = true;
             }
         } catch (IllegalStateException exception) {
             // No value was set for this parameter, and there is no default value.
             force = true;
         }
         // A value was set, but is different than the expected value.
         if (force) {
             parameter.setValue(value, unit);
         } else {
             Logging.log(Parameters.class, "ensureSet", new LogRecord(Level.FINE,
                     Errors.format(Errors.Keys.ValueAlreadyDefined_1, name)));
         }
         return true;
     }
getName()
static String getName (final GeneralParameterDescriptor parameter, final ParameterDescriptorGroup group) static private
Returns the name of the given parameter, using the authority code space expected by the given group if possible.
Parameters
parameter The parameter for which the name is wanted.
group The group to use for determining the authority code space.
Returns
The name of the given parameter.
Since
3.05
Referenced by Parameters.isValid().
{
         String name = IdentifiedObjects.getName(parameter, group.getName().getAuthority());
         if (name == null) {
             name = parameter.getName().getCode();
         }
         return name;
     }
getOrCreate()
static ParameterValue<?> getOrCreate (final ParameterDescriptor<?> parameter, final ParameterValueGroup group) throws ParameterNotFoundException static
Referenced by Parameters.toParameter().
     {
         return castOrWrap(group).getOrCreate(parameter);
     }
getParameterOrGroup()
static GeneralParameterValue getParameterOrGroup (ParameterValueGroup group, String name) static
Get the first parameter for this name, do not create parameter if missing.
{
         for(GeneralParameterValue p : group.values()){
             if(p.getDescriptor().getName().getCode().equalsIgnoreCase(name)){
                 return p;
             }
         }
         return null;
     }
isValid() [1/3]
static boolean isValid (final ParameterValue<?> value) static
References Parameters.isValidValue().
Referenced by DataStoreFactory.canProcess(), and Parameters.isValid().
                                                                  { // LGPL
         return isValidValue(value.getDescriptor(), value.getValue(), false) == null;
     }
isValid() [2/3]
static ConformanceResult isValid (final GeneralParameterValue value, final GeneralParameterDescriptor descriptor) static
References Parameters.EXPLAIN, Descriptions.formatInternational(), Parameters.isValid(), and Descriptions.Keys.NonConformParameter_2.
     {
         /*
          * Create a conformance result initialized to a successful check.
          */
         final DefaultConformanceResult result = new DefaultConformanceResult(
                 descriptor.getName().getAuthority(), EXPLAIN, true);
         final GeneralParameterValue failure = isValid(value, descriptor, result);
         /*
          * If the validity test failed, update the conformance result accordingly.
          */
         if (failure != null) {
             final Identifier name = failure.getDescriptor().getName();
             result.setExplanation(Descriptions.formatInternational(
                     Descriptions.Keys.NonConformParameter_2, name, result.getExplanation()));
             result.setSpecification(name.getAuthority());
             result.setPass(Boolean.FALSE);
         }
         return result;
     }
isValid() [3/3]
static GeneralParameterValue isValid (final GeneralParameterValue value, final GeneralParameterDescriptor descriptor, final DefaultConformanceResult result) static private
Checks a parameter value against the conditions specified by the given descriptor.
In case of failure, the explanation message of the given
result
is updated with the cause, and this method returns the descriptor of the parameter that failed the check.
Parameters
value The parameter to test.
descriptor The descriptor to use for fetching the conditions.
result The conformance result to update in case of failure.
Returns
null
in case of success, or the faulty parameter in case of failure.
References Errors.formatInternational(), Parameters.getName(), Errors.Keys.IllegalOccursForParameter_4, Errors.Keys.IllegalOperationForValueClass_1, Parameters.isValid(), Parameters.isValidValue(), Errors.Keys.NoParameter_1, and Errors.Keys.UnexpectedParameter_1.
     {
         if (descriptor instanceof ParameterDescriptor<?>) {
             /*
              * For a single parameter (the most common case), the value shall be an instance
              * of ParameterValue. If it is not, then the error message will be formatted at
              * the end of this method.
              */
             if (value instanceof ParameterValue<?>) {
                 final InternationalString failure = isValidValue((ParameterDescriptor<?>) descriptor,
                         ((ParameterValue<?>) value).getValue(), true);
                 if (failure != null) {
                     result.setExplanation(failure);
                     return value;
                 }
                 return null; // The test pass.
             }
         } else if (descriptor instanceof ParameterDescriptorGroup) {
             /*
              * For a group, the value shall be an instance of ParameterValueGroup. If it
              * is not, then the error message will be formatted at the end of this method.
              */
             if (value instanceof ParameterValueGroup) {
                 final Map<GeneralParameterDescriptor,Integer> count = new HashMap<>();
                 final ParameterDescriptorGroup group = (ParameterDescriptorGroup) descriptor;
                 for (final GeneralParameterValue element : ((ParameterValueGroup) value).values()) {
                     final String name = getName(element.getDescriptor(), group);
                     final GeneralParameterDescriptor desc;
                     try {
                         desc = group.descriptor(name);
                     } catch (ParameterNotFoundException e) {
                         result.setExplanation(Errors.formatInternational(
                                 Errors.Keys.UnexpectedParameter_1, name));
                         return value;
                     }
                     final GeneralParameterValue failure = isValid(element, desc, result);
                     if (failure != null) {
                         return failure;
                     }
                     // Count the occurrence of parameters.
                     Integer old = count.put(desc, 1);
                     if (old != null) {
                         count.put(desc, old + 1);
                     }
                 }
                 /*
                  * All parameters pass their individual test.
                  * Now check their cardinality.
                  */
                 for (final GeneralParameterDescriptor desc : group.descriptors()) {
                     final Integer nw = count.get(desc);
                     final int n = (nw != null) ? nw : 0;
                     final int min = desc.getMinimumOccurs();
                     final int max = desc.getMaximumOccurs();
                     if (n < min || n > max) {
                         final String name = desc.getName().getCode();
                         final short key;
                         final Object[] param;
                         if (n == 0) {
                             key = Errors.Keys.NoParameter_1;
                             param = new Object[] {name};
                         } else {
                             key = Errors.Keys.IllegalOccursForParameter_4;
                             param = new Object[] {name, nw, min, max};
                         }
                         result.setExplanation(Errors.formatInternational(key, param));
                         return value;
                     }
                 }
                 return null; // The test pass.
             }
         }
         /*
          * If we reach this point, the type of the parameter value is not consistent
          * with the type of the descriptor. Format the error message.
          */
         final Class<? extends GeneralParameterValue> type;
         if (value instanceof ParameterValue<?>) {
             type = ParameterValue.class;
         } else if (value instanceof ParameterValueGroup) {
             type = ParameterValueGroup.class;
         } else {
             type = GeneralParameterValue.class;
         }
         result.setExplanation(Errors.formatInternational(Errors.Keys.IllegalOperationForValueClass_1, type));
         return value;
     }
isValidValue()
static <T> InternationalString isValidValue (final ParameterDescriptor< T > descriptor, final Object value, final boolean localized) static private
Checks a parameter value against its descriptor, and returns an error message if it is not conformant.
This method is similar to AbstractParameter#ensureValidValue. If one implementation is modified, the other one should be updated accordingly.
Parameters
<T> The expected type of value.
value The parameter to test.
localized
References Parameters.EXPLAIN, Errors.formatInternational(), AbstractParameter.getName(), Errors.Keys.IllegalArgument_2, Errors.Keys.IllegalClass_2, Errors.Keys.NoParameter_1, and Errors.Keys.ValueOutOfBounds_3.
Referenced by Parameters.isValid().
     {
         /*
          * Accept null values only if explicitly authorized.
          */
         if (value == null) {
             if (descriptor.getMinimumOccurs() == 0) {
                 return null; // Test pass.
             }
             return localized ? Errors.formatInternational(Errors.Keys.NoParameter_1,
                     AbstractParameter.getName(descriptor)) : EXPLAIN;
         }
         /*
          * Check the type.
          */
         final Class<?> type = value.getClass();
         final Class<T> expected = descriptor.getValueClass();
         if (!expected.isAssignableFrom(type)) {
             return localized ? Errors.formatInternational(Errors.Keys.IllegalClass_2,
                     type, expected) : EXPLAIN;
         }
         final T typedValue = expected.cast(value);
         /*
          * Check the range (if any).
          */
         final Comparable<T> minimum = descriptor.getMinimumValue();
         final Comparable<T> maximum = descriptor.getMaximumValue();
         if ((minimum != null && minimum.compareTo(typedValue) > 0) ||
             (maximum != null && maximum.compareTo(typedValue) < 0))
         {
             return localized ? Errors.formatInternational(Errors.Keys.ValueOutOfBounds_3,
                     value, minimum, maximum) : EXPLAIN;
         }
         /*
          * Check the enumeration (if any).
          */
         final Set<T> validValues = descriptor.getValidValues();
         if (validValues!=null && !validValues.contains(value)) {
             return localized ? Errors.formatInternational(Errors.Keys.IllegalArgument_2,
                     AbstractParameter.getName(descriptor), value) : EXPLAIN;
         }
         return null; // Test pass.
     }
search() [1/2]
static List<GeneralParameterValue> search (final GeneralParameterValue parameter, final String name, int maxDepth) static
Referenced by Parameters.search().
     {
         final List<GeneralParameterValue> list = new ArrayList<>();
         search(parameter, name, maxDepth, list);
         return list;
     }
search() [2/2]
static void search (final GeneralParameterValue parameter, final String name, final int maxDepth, final Collection< GeneralParameterValue > list) static private
Implementation of the search algorithm.
The result is stored in the supplied set.
References Parameters.search().
     {
         if (maxDepth >= 0) {
             if (IdentifiedObjects.isHeuristicMatchForName(parameter.getDescriptor(), name)) {
                 list.add(parameter);
             }
             if ((maxDepth != 0) && (parameter instanceof ParameterValueGroup)) {
                 for (final GeneralParameterValue value : ((ParameterValueGroup) parameter).values()) {
                     search(value, name, maxDepth-1, list);
                 }
             }
         }
     }
toMap()
static Map<String,Object> toMap (final ParameterValueGroup source) static
Convert a ParameterValueGroup in a Map of values.
Map keys will be parameter names, and their associated value are indeed map values. For nested Parameter group, a list of maps will be created inside the output map. Theorically, this allows infinite group depth.
Parameters
source : Group of parametrs to convert.
Returns
A map which contains all parameters and groups of input Parameter group.
{
         ArgumentChecks.ensureNonNull("source", source);
         final HashMap<String, Object> result = new HashMap<>();
         String parameterName;
         for (GeneralParameterValue value : source.values()) {
             parameterName = value.getDescriptor().getName().getCode();
             if (value instanceof ParameterValue) {
                 result.put(parameterName, ((ParameterValue) value).getValue());
             } else if (value instanceof ParameterValueGroup) {
                 Collection<Map<String, Object>> subGroup = (List<Map<String, Object>>) result.get(parameterName);
                 if (subGroup == null) {
                     subGroup = new ArrayList<>();
                     result.put(parameterName, subGroup);
                 }
                 subGroup.add(toMap((ParameterValueGroup) value));
             }
         }
         return result;
     }
toParameter() [1/2]
static ParameterValueGroup toParameter (final Map< String, ?> params, final ParameterDescriptorGroup desc) static
Transform a Map in a ParameterValueGroup.
A default parameter is first created and all key found in the map that match the descriptor will be completed.
Referenced by DataStores.canProcess(), DataStores.create(), DataStores.open(), and Parameters.toParameter().
{
         ArgumentChecks.ensureNonNull("params", params);
         ArgumentChecks.ensureNonNull("desc", desc);
         return toParameter(params, desc, true);
     }
toParameter() [2/2]
static ParameterValueGroup toParameter (final Map< String, ?> params, final ParameterDescriptorGroup desc, final boolean checkMandatory) throws ParameterNotFoundException, UnconvertibleObjectException static
Transform a Map in a ParameterValueGroup.
A default parameter is first created and all key found in the map that match the descriptor will be completed.
Parameters
params The map containing entries to put in a ParameterValueGroup
desc The descriptor for the group to create.
checkMandatory if True, a parameter will be returned only if the map provide all mandatory parameters with no default value.
Returns
A parameter value group matching input descriptor, filled with input map value. Return null if input map is incompatible with input descriptor.
Exceptions
ParameterNotFoundException If the map does not contains all needed mandatory parameters required by this descriptor.
UnconvertibleObjectException If an error occurred while putting a value from input map to target Parameter group.
References Parameters.containsKey(), Parameters.copy(), Parameters.getOrCreate(), and Parameters.toParameter().
{
         ArgumentChecks.ensureNonNull("params", params);
         ArgumentChecks.ensureNonNull("desc", desc);
         if (checkMandatory) {
             for (GeneralParameterDescriptor de : desc.descriptors()) {
                 if (de.getMinimumOccurs() > 0 && !containsKey(params, de)) {
                     if (de instanceof ParameterDescriptor && ((ParameterDescriptor) de).getDefaultValue() == null) {
                         //a mandatory parameter is not present
                         throw new ParameterNotFoundException("A mandatory parameter "+de.getName()+" was not found in the input parameters.", de.getName().getCode());
                     }
                 }
             }
         }
         final ParameterValueGroup parameter = desc.createValue();
         GeneralParameterDescriptor subDesc;
         for (final Map.Entry<String, ?> entry : params.entrySet()) {
             try {
                 subDesc = desc.descriptor(entry.getKey());
             } catch (ParameterNotFoundException ex) {
                 //do nothing, the map may contain other values for other uses
                 continue;
             }
             if (subDesc instanceof ParameterDescriptorGroup) {
                 if (entry.getValue() instanceof Map) {
                     parameter.values().add(
                             toParameter((Map) entry.getValue(), (ParameterDescriptorGroup) subDesc, checkMandatory));
                 } else if (entry.getValue() instanceof Collection) {
                     final List values = new ArrayList((Collection) entry.getValue());
                     final int nbGroups = values.size();
                     //already exist groups
                     int nbParamGroups = parameter.groups(entry.getKey()).size();
                     //create missing groups
                     if (nbGroups > nbParamGroups) {
                         int toAdd = nbGroups - nbParamGroups;
                         for (int i = 0; i < toAdd; i++) {
                             parameter.addGroup(entry.getKey());
                         }
                     }
                     // convert and copy map values into parameter groups
                     final List<ParameterValueGroup> paramGroups = parameter.groups(entry.getKey());
                     for (int i = 0; i < nbGroups; i++) {
                         Object valObj = values.get(i);
                         if (valObj instanceof Map) {
                             ParameterValueGroup newGroup = toParameter((Map) valObj, (ParameterDescriptorGroup) subDesc, checkMandatory);
                             copy(newGroup, paramGroups.get(i));
                         } else {
                             throw new IllegalArgumentException("Illegal value for parameter " + entry.getKey() + ". It's a parameter group, so we should have a nested map as input.");
                         }
                     }
                 } else {
                     throw new IllegalArgumentException("Illegal value for parameter " + entry.getKey() + ". It's a parameter group, so we should have a nested map as input.");
                 }
             } else if (subDesc instanceof ParameterDescriptor) {
                 final ParameterDescriptor pdesc = (ParameterDescriptor) subDesc;
                 try {
                     final ParameterValue param = Parameters.getOrCreate(pdesc, parameter);
                     param.setValue(
                             ObjectConverters.convert(entry.getValue(), pdesc.getValueClass()));
                 } catch (ParameterNotFoundException e) {
                     // If mandatory check is activated, possible errors at this point have already been checked.
                     continue;
                 }
             } else {
                 throw new IllegalArgumentException("Unsupported parameter type.");
             }
         }
         return parameter;
     }
Member Data Documentation
EMPTY_GROUP
final ParameterDescriptorGroup EMPTY_GROUP static
Initial value:
=
            new org.apache.sis.parameter.DefaultParameterDescriptorGroup(
                    Collections.singletonMap(ParameterDescriptorGroup.NAME_KEY,
                    Vocabulary.format(Vocabulary.Keys.Empty)), 1, 1)
An empty parameter group.
This group contains no parameters.
Deprecated:
Will be removed.
EPS
final double EPS = 1E-8 static private
Small number for floating point comparisons.
Referenced by Parameters.ensureSet().
EXPLAIN
final InternationalString EXPLAIN static private
Initial value:
=
            Descriptions.formatInternational(Descriptions.Keys.ConformanceMeansValidParameters)
The explanation for conformance results.
Referenced by Parameters.isValid(), and Parameters.isValidValue().