jena-geo: JSON Class Reference
JSON Class Reference
Reads and writes objects using the <cite>JavaScript Object Notation</cite> (JSON).
Static Public Member Functions
static Object parse (final CharSequence json, final Class<?> type) throws ParseException
Parses the given JSON string as an ISO 19115 metadata object.
static String format (final Object object) throws ClassCastException
Formats the given object in a string.
static void format (final Object object, final Appendable out) throws ClassCastException, IOException
Formats the given object in a string.
Private Member Functions
JSON ()
Do not allow instantiation of this class.
Detailed Description
Reads and writes objects using the <cite>JavaScript Object Notation</cite> (JSON).
In this library, JSON is considered as a subset of YAML.
Author
Martin Desruisseaux (Geomatys)
Todo:
We have an ambiguity when writing
Party.name
: nothing distinguish an individual name from an organization name, since the
Party
type is lost at JSON writing time. We propose to format as
"individual.name"
and
"organisation.name"
in those particular cases.
Constructor & Destructor Documentation
JSON()
JSON () private
Do not allow instantiation of this class.
                    {
     }
Member Function Documentation
format() [1/2]
static String format (final Object object) throws ClassCastException static
Formats the given object in a string.
See org.geotoolkit.io.yaml package} javadoc for a description of valid objects.
Parameters
object The object to format.
Returns
A JSON representation of the given object.
Exceptions
ClassCastException If the given object is not an instance of a recognized standard.
References Writer.format().
{
         ArgumentChecks.ensureNonNull("object", object);
         final StringBuilder buffer = new StringBuilder();
         final Writer writer = new Writer(buffer);
         try {
             writer.format(object);
         } catch (IOException e) {
             throw new AssertionError(e); // Should never happen, since we are writing in a StringBuilder.
         }
         return buffer.toString();
     }
format() [2/2]
static void format (final Object object, final Appendable out) throws ClassCastException, IOException static
Formats the given object in a string.
See org.geotoolkit.io.yaml package} javadoc for a description of valid objects.
Parameters
object The object to format.
out Where to write the JSON object.
Exceptions
ClassCastException If the given object is not an instance of a recognized standard.
IOException if an error occurred while writing in
out
.
References Writer.format().
{
         ArgumentChecks.ensureNonNull("object", object);
         ArgumentChecks.ensureNonNull("out", out);
         final Writer writer = new Writer(out);
         writer.format(object);
     }
parse()
static Object parse (final CharSequence json, final Class<?> type) throws ParseException static
Parses the given JSON string as an ISO 19115 metadata object.
Parameters
json The string to parse.
type The type of the object to parse (typically org.opengis.metadata.Metadata}.class).
Returns
The parsed object, usually as an instance of
type
but not always. For example this method may return a java.util.List of instances of
type
if the given
json
string defines an array.
Exceptions
ParseException If the parsing failed.
References Reader.parse().
{
         return new Reader(json).parse(type);
     }