jena-geo: Reader Class Reference
Reader Class Reference
Reads objects from the JSON format.
Package Functions
Reader (final CharSequence text)
Creates a new reader.
final Object parse (final Class<?> type) throws ParseException
Parses the value.
Static Package Functions
static CharSequence unescape (final CharSequence text, int start, final int stop) throws ParseException
Replaces the escape sequences in a subregion of the given character string.
Private Member Functions
void skipIgnorables ()
Advances the position} to the next non-ignorable character.
boolean skipListSeparator (final char endOfSequence) throws ParseException
Skips the list separator (a coma) if present.
char nextTokenStart () throws ParseException
Returns the first non-whitespace character, or thrown an exception if none.
CharSequence nextToken (final boolean isQuoted) throws ParseException
Returns the next token with un-escaped characters.
Private Attributes
final MetadataFactory factory
The factory to use for creating objects.
final CharSequence text
The text to parse.
int position
The current parse position.
final int length
Index after the last character to parse.
Detailed Description
Reads objects from the JSON format.
Author
Martin Desruisseaux (Geomatys)
Constructor & Destructor Documentation
Reader()
Reader (final CharSequence text) package
Creates a new reader.
Parameters
text The text to parse.
References MetadataFactory.DEFAULT, and Reader.text.
{
         this.factory = MetadataFactory.DEFAULT; // Fixed for now, may be configurable in a future version.
         this.text    = text;
         this.length  = text.length();
     }
Member Function Documentation
nextToken()
CharSequence nextToken (final boolean isQuoted) throws ParseException private
Returns the next token with un-escaped characters.
After this method call, the position} has been set to the first character after the returned token.
Parameters
isQuoted
References Reader.position, and Reader.unescape().
Referenced by Reader.parse().
{
         int i = position;
         if (isQuoted) {
             position++; // Skip the '"' character.
             do if ((i = CharSequences.indexOf(text, '"', i+1, length)) < 0) {
                 throw new ParseException("Unexpected end of text.", length);
             } while (text.charAt(i-1) == '\\');
         } else {
             while (++i < length) {
                 final char c = text.charAt(i);
                 if (c == ',' || c == ':' || c == '\r' || c == '\n') {
                     break;
                 }
             }
         }
         CharSequence token = unescape(text, position, i);
         if (isQuoted) {
             i++;
         } else if ("null".contentEquals(token)) {
             token = null;
         }
         position = i;
         return token;
     }
nextTokenStart()
char nextTokenStart () throws ParseException private
Returns the first non-whitespace character, or thrown an exception if none.
References Reader.skipIgnorables().
Referenced by Reader.parse(), and Reader.skipListSeparator().
{
         skipIgnorables();
         if (position < length) {
             return text.charAt(position);
         }
         throw new ParseException("Unexpected end of text.", length);
     }
parse()
final Object parse (final Class<?> type) throws ParseException package
Parses the value.
This method tries to return the value as an object of the given type, but the type may sometime be different (for example a String or a List).
Parameters
type The value type.
Returns
The parsed value, often (but not always) as an instance of
type
.
Exceptions
ParseException If an error occurred while parsing.
References MetadataFactory.create(), MetadataFactory.getDefinition(), Reader.nextToken(), Reader.nextTokenStart(), Reader.position, Reader.skipIgnorables(), and Reader.skipListSeparator().
Referenced by JSON.parse().
{
         skipIgnorables();
         if (position >= length) {
             return null;
         }
         final char c = text.charAt(position);
         if (c == '[') {
             /*
              * We have an array of values. Parse all values and return them in a list.
              */
             position++; // Skip the '[' character.
             final List<Object> values = new ArrayList<>();
             boolean hasNext = (nextTokenStart() != ']');
             while (hasNext) {
                 values.add(parse(type));
                 hasNext = skipListSeparator(']');
             }
             position++; // Skip the ']' character.
             return values;
         }
         if (c != '{') {
             /*
              * We have a string, number or boolean. Find the end of value, either by looking
              * for the closing " or by looking for the separator (comma or line separator).
              */
             Object token = nextToken(c == '"');
             if (token != null) {
                 if (Number.class.isAssignableFrom(type) || type == Boolean.class) {
                     token = Numbers.valueOf(token.toString(), type);
                 }
             }
             return token;
         }
         /*
          * We have an object. Parse everything until the closing bracket.
          */
         final int objectStart = position++; // Skip the '{' character.
         final Map<String,Class<?>> definition = factory.getDefinition(type);
         final Map<String,Object> properties = new HashMap<>();
         boolean hasNext = (nextTokenStart() != '}');
         while (hasNext) {
             final int entryStart = position;
             final CharSequence token = nextToken(nextTokenStart() == '"');
             if (nextTokenStart() != ':') {
                 throw new ParseException("Expected \"key: value\" pair.", position);
             }
             position++; // Skip the ':' character.
             final String key = String.valueOf(token);
             Class<?> childType = definition.get(key);
             if (childType == null) {
                 childType = String.class; // TODO
             }
             if (properties.put(key, parse(childType)) != null) {
                 throw new ParseException("Duplicated key: \"" + key + "\".", entryStart);
             }
             hasNext = skipListSeparator('}');
         }
         position++; // Skip the '}' character.
         return factory.create(type, definition, properties, objectStart);
     }
skipIgnorables()
void skipIgnorables () private
Advances the position} to the next non-ignorable character.
This method skips all white-spaces.
Referenced by Reader.nextTokenStart(), and Reader.parse().
{
         position = CharSequences.skipLeadingWhitespaces(text, position, length);
     }
skipListSeparator()
boolean skipListSeparator (final char endOfSequence) throws ParseException private
Skips the list separator (a coma) if present.
Other characters (in particular the
endOfSequence
character) are not skipped.
Parameters
endOfSequence The character ending the sequence.
Returns
true
if there is more elements in the list.
Exceptions
ParseException If an illegal character is found.
References Reader.nextTokenStart().
Referenced by Reader.parse().
{
         final char c = nextTokenStart();
         if (c == ',') {
             position++; // Skip the ',' character.
             return true;
         } else if (c == endOfSequence) {
             return false;
         } else {
             throw new ParseException("Illegal character: " + c, position);
         }
     }
unescape()
static CharSequence unescape (final CharSequence text, int start, final int stop) throws ParseException static package
Replaces the escape sequences in a subregion of the given character string.
This method replaces the escape sequences defined by the Java language and JSON. For any unknown escape sequence, this method just removes the backslash.
References Writer.UNICODE_LENGTH.
Referenced by Reader.nextToken().
{
         int i = CharSequences.indexOf(text, '\\', start, stop);
         if (i < 0) {
             return text.subSequence(start, stop);
         }
         final StringBuilder buffer = new StringBuilder(stop - start - 1);
         do {
             buffer.append(text, start, i);
             if (++i >= stop) {
                 throw new ParseException("Unexpected end of text.", stop);
             }
             final char c = text.charAt(i);
             final char r;
             start = ++i;
             switch (c) {
                 default:  r =  c;   break;
                 case 'b': r = '\b'; break;
                 case 'f': r = '\f'; break;
                 case 'n': r = '\n'; break;
                 case 'r': r = '\r'; break;
                 case 't': r = '\t'; break;
                 case 'u': {
                     final int s = Math.min(start + Writer.UNICODE_LENGTH, stop);
                     while (i < s && Characters.isHexadecimal(text.charAt(i))) i++;
                     final String u = text.subSequence(start, i).toString();
                     try {
                         r = (char) Integer.parseInt(u, 16);
                     } catch (NumberFormatException e) {
                         throw new ParseException("Invalid character code: " + u, start);
                     }
                     start = i;
                     break;
                 }
             }
             buffer.append(r);
         } while ((i = CharSequences.indexOf(text, '\\', start, stop)) >= 0);
         return buffer.append(text, start, stop).toString();
     }
Member Data Documentation
factory
final MetadataFactory factory private
The factory to use for creating objects.
length
final int length private
Index after the last character to parse.
position
int position private
The current parse position.
Referenced by Reader.nextToken(), and Reader.parse().
text
final CharSequence text private
The text to parse.
Referenced by Reader.Reader().