jena-geo: ZipUtilities Class Reference
ZipUtilities Class Reference
Utility methods related to I/O Zip operations.
Static Public Member Functions
static void zipNIO (Path zipPath, final Path... resouces) throws IOException
Zip resources list into zip file using Java NIO API.
static void unzipNIO (Path zipPath, final Path target, boolean withRootDirectory) throws IOException
Unzip zipped file into target path using Java NIO API.
static void zip (final Path zip, final Checksum checksum, final Path... resources) throws IOException
static void zip (final Path zip, final int method, final int level, final Checksum checksum, final Path... resources) throws IOException
static List< Path > unzip (final Path zip, final Checksum checksum) throws IOException
static List< Path > unzip (final Path zip, final Path resource, final Checksum checksum) throws IOException
Private Member Functions
ZipUtilities ()
Static Private Member Functions
static FileSystem createZipFileSystem (Path zipPath, boolean create) throws IOException
Returns a zip file system.
static void zipCore (int method, int level, BufferedOutputStream buf, Path[] resources) throws IOException
Intermediate operation during ip creation.
static void zipCore (final ZipOutputStream zout, final int method, final int level, final String entryPath, final Iterator< Path > resources) throws IOException
static List< Path > unzipCore (final InputStream zip, final Path resource) throws IOException
Static Private Attributes
static final int BUFFER_SIZE = 8192
The default buffer size for copy operations.
Detailed Description
Utility methods related to I/O Zip operations.
Author
Quentin Boileau (Geomatys)
Constructor & Destructor Documentation
ZipUtilities()
ZipUtilities () private
{
     }
Member Function Documentation
createZipFileSystem()
static FileSystem createZipFileSystem (Path zipPath, boolean create) throws IOException static private
Returns a zip file system.
Parameters
zipPath to construct the file system from
create true if the zip file should be created
Returns
a zip file system
Exceptions
IOException
Referenced by ZipUtilities.unzipNIO(), and ZipUtilities.zipNIO().
{
         // convert the filename to a URI
         final URI uri = URI.create("jar:" + zipPath.toUri());
         final Map<String, String> env = new HashMap<>();
         if (create) {
             env.put("create", "true");
         }
         return FileSystems.newFileSystem(uri, env);
     }
unzip() [1/2]
static List<Path> unzip (final Path zip, final Checksum checksum) throws IOException static
This method extracts a ZIP archive into the directory which contents it.
Parameters
zip The archive parameter as File, URL, URI, InputStream or String path. This argument cannot be null.
checksum Checksum object (instance of Alder32 or CRC32).
Exceptions
IOException
References ZipUtilities.zip().
{
         return unzip(zip, zip.getParent(), checksum);
     }
unzip() [2/2]
static List<Path> unzip (final Path zip, final Path resource, final Checksum checksum) throws IOException static
This method extract a ZIP archive into the specified location.
ZIP resource parameter
Parameters
zip The archive parameter can be instance of InputStream, File, URL, URI or a String path. This argument cannot be null.
resource The resource where archive content will be extracted. This resource location can be specified as instance of File or a String path. This argument cannot be null.
checksum Checksum object (instance of Alder32 or CRC32).
Exceptions
IOException
References ZipUtilities.unzipCore(), and ZipUtilities.zip().
{
         try (InputStream inStream = Files.newInputStream(zip)) {
             if (checksum != null) {
                 try (CheckedInputStream cis = new CheckedInputStream(inStream, checksum)) {
                     try (BufferedInputStream buf = new BufferedInputStream(cis)) {
                         return unzipCore(buf, resource);
                     }
                 }
             } else {
                 try (BufferedInputStream buf = new BufferedInputStream(inStream)) {
                     return unzipCore(buf, resource);
                 }
             }
         }
     }
unzipCore()
static List<Path> unzipCore (final InputStream zip, final Path resource) throws IOException static private
This method extract a ZIP archive from an InputStream, into directory whose path is indicated by resource object.
Parameters
zip InputStream on ZIP resource that contains resources to extract.
resource The resource where files will be extracted. Must be instance of File or a String path. This argument cannot be null.
Exceptions
IOException
References IOUtilities.copy(), and ZipUtilities.zip().
Referenced by ZipUtilities.unzip().
{
         final List<Path> unzipped = new ArrayList<>();
         try (ZipInputStream zis = new ZipInputStream(zip)) {
             ZipEntry entry;
             while ((entry = zis.getNextEntry()) != null) {
                 final Path file = resource.resolve(entry.getName());
                 if (entry.isDirectory()) {
                     Files.createDirectories(file);
                     continue;
                 }
                 Files.createDirectories(file.getParent());
                 unzipped.add(file);
                 try (OutputStream fos = Files.newOutputStream(file)) {
                     IOUtilities.copy(zis, fos);
                 }
             }
         }
         return unzipped;
     }
unzipNIO()
static void unzipNIO (Path zipPath, final Path target, boolean withRootDirectory) throws IOException static
Unzip zipped file into target path using Java NIO API.
Parameters
zipPath
target
withRootDirectory create folder into target path named after zip filename
Exceptions
IOException
References ZipUtilities.createZipFileSystem(), and IOUtilities.filenameWithoutExtension().
{
         if(Files.notExists(target)) {
             Files.createDirectories(target);
         }
         final Path deflateDirectory;
         if (withRootDirectory) {
             final String folderName = IOUtilities.filenameWithoutExtension(zipPath);
             deflateDirectory = Files.createDirectories(target.resolve(folderName));
         } else {
             deflateDirectory = target;
         }
         try (FileSystem zipFS = createZipFileSystem(zipPath, false)) {
             final Path root = zipFS.getPath("/");
             Files.walkFileTree(root, new CopyFileVisitor(deflateDirectory, StandardCopyOption.REPLACE_EXISTING));
         }
     }
zip() [1/2]
static void zip (final Path zip, final Checksum checksum, final Path... resources) throws IOException static
This method allows to put resources into zip archive specified resource, without compression
Parameters
zip The resource which files will be archived into. This argument must be instance of File, String (representing a path), or OutputStream. Cannot be null.
checksum Checksum object (instance of Alder32 or CRC32).
resources The files to compress. Tese objects can be File instances or String representing files paths, URL, URI or InputStream. Cannot be null.
Exceptions
IOException
Referenced by ZipUtilities.unzip(), ZipUtilities.unzipCore(), and ZipUtilities.zip().
{
         zip(zip, ZipOutputStream.STORED, 0, checksum, resources);
     }
zip() [2/2]
static void zip (final Path zip, final int method, final int level, final Checksum checksum, final Path... resources) throws IOException static
This method allows to put resources into zip archive specified resource.
Parameters
zip The resource which files will be archived into. This argument must be instance of File, String (representing a path), or OutputStream. Cannot be null.
method The compression method is a static int constant from ZipOutputSteam with two theorical possible values :
ZipOutputStream#DEFLATED to compress archive.
ZipOutputStream#STORED to let the archive uncompressed (unsupported).
level The compression level is an integer between 0 (not compressed) to 9 (best compression).
checksum Checksum object (instance of Alder32 or CRC32).
resources The files to compress. Tese objects can be File instances or String representing files paths, URL, URI or InputStream. Cannot be null.
Exceptions
IOException
References ZipUtilities.zip(), and ZipUtilities.zipCore().
{
         try (OutputStream outStream = Files.newOutputStream(zip)) {
             if (checksum != null) {
                 try (CheckedOutputStream cos = new CheckedOutputStream(outStream, checksum)) {
                     try (BufferedOutputStream buf = new BufferedOutputStream(cos)) {
                         zipCore(method, level, buf, resources);
                     }
                 }
             } else {
                 try (BufferedOutputStream buf = new BufferedOutputStream(outStream)) {
                     zipCore(method, level, buf, resources);
                 }
             }
         }
     }
zipCore() [1/2]
static void zipCore (int method, int level, BufferedOutputStream buf, Path [] resources) throws IOException static private
Intermediate operation during ip creation.
Parameters
method
level
buf
resources
Exceptions
IOException
Referenced by ZipUtilities.zip(), and ZipUtilities.zipCore().
{
         try (final ZipOutputStream zout = new ZipOutputStream(buf)) {
             zout.setMethod(method);
             zout.setLevel(level);
             zipCore(zout, method, level, "", Arrays.asList(resources).iterator());
         }
     }
zipCore() [2/2]
static void zipCore (final ZipOutputStream zout, final int method, final int level, final String entryPath, final Iterator< Path > resources) throws IOException static private
This method creates an OutputStream with ZIP archive from the list of resources parameter.
Parameters
zout OutputStrem on ZIP archive that will contain archives of resource files.
method The compression method is a static int constant from ZipOutputSteeam with two theorical possible values :
ZipOutputStream#DEFLATED to compress archive.
ZipOutputStream#STORED to let the archive uncompressed (unsupported).
level The compression level is an integer between 0 (not compressed) to 9 (best compression).
resources Iterator other Path to compress
Exceptions
IOException
References IOUtilities.copy(), and ZipUtilities.zipCore().
{
         final CRC32 crc = new CRC32();
         final ByteBuffer byteBuffer = ByteBuffer.allocate(BUFFER_SIZE);
         boolean stored = false;
         if (ZipOutputStream.STORED == method) {
             stored = true;
         } else if (ZipOutputStream.DEFLATED != method) {
             throw new IllegalArgumentException("This compression method is not supported.");
         }
         if (Double.isNaN(level) || Double.isInfinite(level) || level > 9 || level < 0) {
             throw new IllegalArgumentException("Illegal compression level.");
         }
         while (resources.hasNext()) {
             final Path resource = resources.next();
             final String fileName = resource.getFileName().toString();
             final ZipEntry entry = new ZipEntry(entryPath + fileName);
             if (stored) {
                 final long size = Files.size(resource);
                 entry.setCompressedSize(size);
                 entry.setSize(size);
                 entry.setCrc(crc.getValue());
             }
             if (Files.isDirectory(resource)) {
                 try( DirectoryStream<Path> children = Files.newDirectoryStream(resource)) {
                     final String nextEntryPath = entryPath + fileName + '/';
                     zipCore(zout, method, level, nextEntryPath, children.iterator());
                     continue;
                 }
             }
             zout.putNextEntry(entry);
             if (stored) {
                 try (SeekableByteChannel sbc = Files.newByteChannel(resource, StandardOpenOption.READ)) {
                     crc.reset();
                     int bytesRead;
                     while ((bytesRead = sbc.read(byteBuffer)) != -1) {
                         crc.update(byteBuffer.array(), 0, bytesRead);
                     }
                 }
             }
             try (InputStream is = Files.newInputStream(resource)){
                 IOUtilities.copy(is, zout);
             } finally {
                 zout.closeEntry();
             }
         }
     }
zipNIO()
static void zipNIO (Path zipPath, final Path... resouces) throws IOException static
Zip resources list into zip file using Java NIO API.
Parameters
zipPath
resouces
Exceptions
IOException
References ZipUtilities.createZipFileSystem().
{
         Files.deleteIfExists(zipPath);
         try (FileSystem zipFs = createZipFileSystem(zipPath, true)) {
             final Path zipRoot = zipFs.getPath("/");
             for (Path resouce : resouces) {
                 final Path nResouce = resouce.normalize();
                 if (Files.isRegularFile(nResouce, LinkOption.NOFOLLOW_LINKS)) {
                     final Path dest = zipRoot.resolve(nResouce.getFileName().toString());
                     Files.copy(nResouce, dest, StandardCopyOption.REPLACE_EXISTING);
                 } else {
                     Files.walkFileTree(nResouce, new CopyFileVisitor(zipRoot, StandardCopyOption.REPLACE_EXISTING));
                 }
             }
         }
     }
Member Data Documentation
BUFFER_SIZE
final int BUFFER_SIZE = 8192 static private
The default buffer size for copy operations.