jena-geo: NewZealandMapGrid Class Reference
NewZealandMapGrid Class Reference
<cite>New Zealand Map Grid</cite> (NZMG) projection (EPSG code 9811).
Public Member Functions
Matrix transform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
Converts the specified (λ,φ) coordinate (units in radians) and stores the result in.
Static Public Member Functions
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values)
Creates an NZMG projection from the given parameters.
Protected Member Functions
NewZealandMapGrid (final OperationMethod method, final Parameters parameters)
Constructs a new map projection from the supplied parameters.
void inverseTransform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff) throws ProjectionException
Transforms the specified (x,y) coordinates and stores the result in.
Package Functions
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor)
final double msfn (final double sinφ, final double cosφ)
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
final double ssfn (double φ, double sinφ)
Computes part of function (3-1) from Snyder.
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ)
Computes the derivative of the ssfn(double, double) method divided by.
final double qsfn (final double sinφ)
Calculates q, Snyder equation (3-12).
final double dqsfn_dφ (final double sinφ, final double cosφ)
Gets the derivative of the qsfn(double) method.
Static Package Functions
static boolean isSpherical (final Parameters parameters)
Static Package Attributes
static final double ANGLE_TOLERANCE = 1E-6
Maximum difference allowed when comparing longitudes or latitudes in radians.
static final double ITERATION_TOLERANCE = 1E-10
Difference allowed in iterative computations.
static final int MAXIMUM_ITERATIONS = 15
Maximum number of iterations for iterative computations.
static final double EPSILON = 1E-7
Maximum difference allowed when comparing real numbers (other cases).
Static Private Attributes
static final long serialVersionUID = 8394817836243729133L
For compatibility with different versions during deserialization.
static final Complex [] A
Coefficients for forward and inverse projection.
static final Complex [] B
Coefficients for inverse projection.
static final double [] TPHI
Coefficients for inverse projection.
static final double [] TPSI
Coefficients for forward projection.
Detailed Description
<cite>New Zealand Map Grid</cite> (NZMG) projection (EPSG code 9811).
See any of the following providers for a list of programmatic parameters:
org.geotoolkit.referencing.operation.provider.NewZealandMapGrid
{
}
This is an implementation of algorithm published by Land Information New Zealand. The algorithm is documented here.
{
Note
This class makes extensive use of Complex type which may be costly unless the compiler can inline on the stack. We assume that Jave 6 and above can do this optimization.}
Author
Justin Deoliveira (Refractions)
Martin Desruisseaux (IRD, Geomatys)
Since
2.2
Constructor & Destructor Documentation
NewZealandMapGrid()
NewZealandMapGrid (final OperationMethod method, final Parameters parameters) protected
Constructs a new map projection from the supplied parameters.
Parameters
parameters The parameters of the projection to be created.
References UnitaryProjection.getAndStore(), and NewZealandMapGrid.LATITUDE_OF_ORIGIN.
Referenced by NewZealandMapGrid.create().
{
         super(method, parameters, null);
         final MatrixSIS normalize = getContextualParameters().getMatrix(MatrixRole.NORMALIZATION);
         normalize.convertBefore(1, 180/PI * 3600E-5, null);
         normalize.convertBefore(1, null, -getAndStore(parameters, org.geotoolkit.referencing.operation.provider.NewZealandMapGrid.LATITUDE_OF_ORIGIN));
     }
Member Function Documentation
create()
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values) static
Creates an NZMG projection from the given parameters.
The descriptor argument is usually org.geotoolkit.referencing.operation.provider.NewZealandMapGrid#PARAMETERS, but is not restricted to. If a different descriptor is supplied, it is user's responsibility to ensure that it is suitable to a NZMG projection.
Parameters
descriptor Typically
NewZealandMapGrid.PARAMETERS
.
values The parameter values of the projection to create.
Returns
The map projection.
Since
3.00
References NewZealandMapGrid.NewZealandMapGrid().
Referenced by NewZealandMapGrid.createMathTransform().
     {
         final Parameters parameters = Parameters.castOrWrap(values);
         final NewZealandMapGrid projection = new NewZealandMapGrid(descriptor, parameters);
         try {
             return (MathTransform2D) projection.createMapProjection(
                     org.apache.sis.internal.system.DefaultFactories.forBuildin(
                             org.opengis.referencing.operation.MathTransformFactory.class));
         } catch (org.opengis.util.FactoryException e) {
             throw new IllegalArgumentException(e); // TODO
         }
     }
dqsfn_dφ()
final double dqsfn_dφ (final double sinφ, final double cosφ) package inherited
Gets the derivative of the qsfn(double) method.
Parameters
sinφ The sine of latitude.
cosφ The cosines of latitude.
Returns
The
qsfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by LambertAzimuthalEqualArea.transform().
{
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         double esinφ2 = eccentricity * sinφ;
         esinφ2 *= esinφ2;
         return (1 - eccentricitySquared) * (cosφ / (1 - esinφ2)) * (1 + ((1 + esinφ2) / (1 - esinφ2)));
     }
dssfn_dφ()
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ) package inherited
Computes the derivative of the ssfn(double, double) method divided by.
ssfn
. Callers must multiply the return value by
ssfn
in order to get the actual value.
Parameters
φ The latitude.
sinφ the sine of latitude.
cosφ The cosine of latitude.
Returns
The
dssfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         assert !(abs(cosφ - cos(φ)) > ARGUMENT_TOLERANCE) : φ;
         return (1/cosφ) - (eccentricitySquared*cosφ)/(1-eccentricitySquared*sinφ*sinφ);
         /*
          * NOTE: 0.5*(t + 1/t)   =   1/cosφ
          */
     }
getAndStore()
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor) package inherited
Referenced by CassiniOrMercator.CassiniOrMercator(), Krovak.Krovak(), LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), NewZealandMapGrid.NewZealandMapGrid(), Orthographic.Orthographic(), and Stereographic.Stereographic().
{
         final double value = parameters.doubleValue(descriptor);    // Apply a unit conversion if needed.
         final Double defaultValue = descriptor.getDefaultValue();
         if (defaultValue == null || !defaultValue.equals(value)) {
             org.apache.sis.internal.referencing.provider.MapProjection.validate(descriptor, value);
             String name = IdentifiedObjects.getName(descriptor, parameters.getDescriptor().getName().getAuthority());
             if (name == null) {
                 name = descriptor.getName().getCode();
             }
             getContextualParameters().parameter(name).setValue(value);
         }
         return value;
     }
inverseTransform()
void inverseTransform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff) throws ProjectionException protected
Transforms the specified (x,y) coordinates and stores the result in.
dstPts
(angles in radians).
References Complex.add(), Complex.addMultiply(), Complex.copy(), Complex.divide(), Complex.imag, Complex.multiply(), Complex.power(), and Complex.real.
     {
         // See implementation note in class javadoc.
         final Complex z = new Complex(srcPts[srcOff+1], srcPts[srcOff]);
         final Complex power = new Complex(z);
         final Complex theta = new Complex();
         theta.multiply(B[0], z);
         for (int j=1; j<B.length; j++) {
             power.multiply(power, z);
             theta.addMultiply(theta, B[j], power);
         }
         // Increasing the number of iterations through this loop decreases
         // the error in the calculation, but 3 iterations gives 10-3 accuracy.
         final Complex num   = new Complex();
         final Complex denom = new Complex();
         final Complex t     = new Complex();
         for (int j=0; j<3; j++) {
             power.power(theta, 2);
             num.addMultiply(z, A[1], power);
             for (int k=2; k<A.length; k++) {
                 power.multiply(power, theta);
                 t.multiply(A[k], power);
                 t.multiply(t, k);
                 num.add(num, t);
             }
             power.real = 1;
             power.imag = 0;
             denom.copy(A[0]);
             for (int k=1; k<A.length; k++) {
                 power.multiply(power, theta);
                 t.multiply(A[k], power);
                 t.multiply(t, k+1);
                 denom.add(denom, t);
             }
             theta.divide(num, denom);
         }
         final double dpsi = theta.real;
         double dpsi_pow_i = dpsi;
         double dphi = TPHI[0] * dpsi;
         for (int i=1; i<TPHI.length; i++) {
             dpsi_pow_i *= dpsi;
             dphi += (TPHI[i] * dpsi_pow_i);
         }
         dstPts[dstOff  ] = theta.imag;
         dstPts[dstOff+1] = dphi;
     }
isSpherical()
static boolean isSpherical (final Parameters parameters) static package inherited
References UnitaryProjection.inverseTransform().
Referenced by CassiniSoldner.create(), Stereographic.create(), LambertAzimuthalEqualArea.create(), and LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
{
         return parameters.parameter("semi_major").doubleValue() == parameters.parameter("semi_minor").doubleValue();
     }
msfn()
final double msfn (final double sinφ, final double cosφ) package inherited
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
Special cases:
If φ is 0°, then this method returns 1.
If φ is ±90°, then this method returns 0 provided that we are not in the spherical case (otherwise we get Double#NaN).
Parameters
sinφ The sine of the φ latitude in radians.
cosφ The cosine of the φ latitude in radians.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic().
                                                               {               // == cosφ / rν(sinφ)
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         return cosφ / sqrt(1.0 - (sinφ*sinφ) * eccentricitySquared);
     }
qsfn()
final double qsfn (final double sinφ) package inherited
Calculates q, Snyder equation (3-12).
This equation has the following properties:
Input in the [-1 ... +1] range.
Output in the [-2 ... +2] range.
Output is 0 when input is 0.
Output of the same sign than input.
qsfn(-sinφ) == -qsfn(sinφ)
.
Parameters
sinφ Sine of the latitude q is calculated for.
Returns
q from Snyder equation (3-12).
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.transform().
{
         if (eccentricity < EPSILON) {
             return 2 * sinφ;
         }
         /*
          * Above check was required because the expression below would simplify to
          * sinφ - 0.5/0*log(1) where the right terms are infinity multiplied by
          * zero, thus producing NaN.
          */
         final double esinφ = eccentricity * sinφ;
         return (1 - eccentricitySquared) * (sinφ / (1 - esinφ*esinφ) + atanh(esinφ)/eccentricity);
     }
ssfn()
final double ssfn (double φ, double sinφ) package inherited
Computes part of function (3-1) from Snyder.
This is numerically equivalent to #tsfn tsfn}(-φ, sinφ), but is defined as a separated function for clarity and because the function properties are not the same.
Parameters
φ The latitude in radians.
sinφ The sine of the φ argument. This is provided explicitly because in many cases, the caller has already computed this value.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic(), EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         sinφ *= eccentricity;
         return tan(PI/4 + 0.5*φ) * pow((1-sinφ) / (1+sinφ), 0.5*eccentricity);
     }
transform()
Matrix transform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
Converts the specified (λ,φ) coordinate (units in radians) and stores the result in.
dstPts
(linear distance on a unit sphere).
Since
3.20 (derived from 3.00)
References Complex.addMultiply(), Errors.Keys.CantComputeDerivative, Errors.format(), Complex.imag, Complex.multiply(), and Complex.real.
     {
         if (dstPts != null) {
             final double dphi = srcPts[srcOff + 1];
             double dphi_pow_i = dphi;
             double dpsi       = 0;
             for (int i=0; i<TPSI.length; i++) {
                 dpsi += (TPSI[i] * dphi_pow_i);
                 dphi_pow_i *= dphi;
             }
             // See implementation note in class javadoc.
             final Complex theta = new Complex(dpsi, srcPts[srcOff]);
             final Complex power = new Complex(theta);
             final Complex z     = new Complex();
             z.multiply(A[0], power);
             for (int i=1; i<A.length; i++) {
                 power.multiply(power, theta);
                 z.addMultiply(z, A[i], power);
             }
             dstPts[dstOff  ] = z.imag;
             dstPts[dstOff+1] = z.real;
         }
         if (derivate) {
             throw new ProjectionException(Errors.format(Errors.Keys.CantComputeDerivative));
         }
         return null;
     }
Member Data Documentation
A
final Complex [] A static private
Initial value:
= {
        new Complex(  0.7557853228,  0.0         ),
        new Complex(  0.249204646,   0.003371507 ),
        new Complex( -0.001541739,   0.041058560 ),
        new Complex( -0.10162907,    0.01727609  ),
        new Complex( -0.26623489,   -0.36249218  ),
        new Complex( -0.6870983,    -1.1651967   )
    }
Coefficients for forward and inverse projection.
ANGLE_TOLERANCE
final double ANGLE_TOLERANCE = 1E-6 static package inherited
Maximum difference allowed when comparing longitudes or latitudes in radians.
A tolerance of 1E-6 is about 0.2 second of arcs, which is about 6 kilometers (computed from the standard length of nautical mile).
Some formulas use this tolerance value for testing sinus or cosinus of an angle. In the sinus case, this is justified because sin(θ) ≅ θ when θ is small. Similar reasoning applies to cosinus with cos(θ) ≅ θ + π/2 when θ is small.
Referenced by Stereographic.create(), Orthographic.inverseTransform(), LambertAzimuthalEqualArea.inverseTransform(), Orthographic.Orthographic(), and Stereographic.Stereographic().
B
final Complex [] B static private
Initial value:
= {
        new Complex(  1.3231270439,   0.0         ),
        new Complex( -0.577245789,   -0.007809598 ),
        new Complex(  0.508307513,   -0.112208952 ),
        new Complex( -0.15094762,     0.18200602  ),
        new Complex(  1.01418179,     1.64497696  ),
        new Complex(  1.9660549,      2.5127645   )
    }
Coefficients for inverse projection.
EPSILON
final double EPSILON = 1E-7 static package inherited
Maximum difference allowed when comparing real numbers (other cases).
The value defined here is consistent with the one that was used in LambertAzimuthalEqualArea for the same purpose (not to be confused with the current
EPSILON
constant defined in the above-mentioned class, which has been renamed), and the modified value used in AlbersEqualArea.
ITERATION_TOLERANCE
final double ITERATION_TOLERANCE = 1E-10 static package inherited
Difference allowed in iterative computations.
A value of 1E-10 causes the cphi2 function to compute the latitude at a precision of 1E-10 radians, which is slightly smaller than one millimetre.
Referenced by CassiniOrMercator.inv_mlfn(), and Stereographic.inverseTransform().
MAXIMUM_ITERATIONS
final int MAXIMUM_ITERATIONS = 15 static package inherited
Maximum number of iterations for iterative computations.
Referenced by CassiniOrMercator.inv_mlfn(), Stereographic.inverseTransform(), and Krovak.inverseTransform().
serialVersionUID
final long serialVersionUID = 8394817836243729133L static private
For compatibility with different versions during deserialization.
TPHI
final double [] TPHI static private
Initial value:
= new double[] {
        1.5627014243, 0.5185406398, -0.03333098, -0.1052906, -0.0368594, 0.007317,
        0.01220, 0.00394, -0.0013
    }
Coefficients for inverse projection.
TPSI
final double [] TPSI static private
Initial value:
= new double[] {
        0.6399175073, -0.1358797613, 0.063294409, -0.02526853, 0.0117879,
        -0.0055161, 0.0026906, -0.001333, 0.00067, -0.00034
    }
Coefficients for forward projection.