jena-geo: EquatorialStereographic Class Reference
EquatorialStereographic Class Reference
The USGS equatorial case of the Stereographic} projection.
Classes
class Spherical
Provides the transform equations for the spherical case of the Equatorial Stereographic projection.
Public Member Functions
Matrix transform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
boolean equals (final Object object, final ComparisonMode mode)
Compares the given object with this transform for equivalence.
Static Public Member Functions
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values)
Creates a Stereographic projection from the given parameters.
Protected Member Functions
EquatorialStereographic (final OperationMethod method, final Parameters parameters)
Constructs an equatorial stereographic projection (EPSG equations).
void inverseTransform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff) throws ProjectionException
Transforms the specified (x,y) coordinates and stores the result in.
Package Functions
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor)
final double msfn (final double sinφ, final double cosφ)
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
final double ssfn (double φ, double sinφ)
Computes part of function (3-1) from Snyder.
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ)
Computes the derivative of the ssfn(double, double) method divided by.
final double qsfn (final double sinφ)
Calculates q, Snyder equation (3-12).
final double dqsfn_dφ (final double sinφ, final double cosφ)
Gets the derivative of the qsfn(double) method.
Static Package Functions
static boolean isSpherical (final Parameters parameters)
Package Attributes
final double φ0
The latitude of origin, in radians.
final double sinφ0
Constants used for the oblique projections.
final double cosφ0
final double cosχ1
Static Package Attributes
static final double EPSILON = 1E-6
Maximum difference allowed when comparing real numbers.
static final double ANGLE_TOLERANCE = 1E-6
Maximum difference allowed when comparing longitudes or latitudes in radians.
static final double ITERATION_TOLERANCE = 1E-10
Difference allowed in iterative computations.
static final int MAXIMUM_ITERATIONS = 15
Maximum number of iterations for iterative computations.
Static Private Attributes
static final long serialVersionUID = -5098015759558831875L
For cross-version compatibility.
Detailed Description
The USGS equatorial case of the Stereographic} projection.
This is a special case of oblique stereographic projection for a latitude of origin set to 0°.
Author
André Gosselin (MPO)
Martin Desruisseaux (MPO, IRD, Geomatys)
Rueben Schulz (UBC)
Rémi Maréchal (Geomatys)
Constructor & Destructor Documentation
EquatorialStereographic()
EquatorialStereographic (final OperationMethod method, final Parameters parameters) protected
Constructs an equatorial stereographic projection (EPSG equations).
Parameters
parameters The parameters of the projection to be created.
References Stereographic.φ0.
{
         super(method, parameters);
         assert φ0 == 0 : φ0;
     }
Member Function Documentation
create()
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values) static inherited
Creates a Stereographic projection from the given parameters.
The descriptor argument is usually org.geotoolkit.referencing.operation.provider.Stereographic#PARAMETERS, but is not restricted to. If a different descriptor is supplied, it is user's responsibility to ensure that it is suitable to a Stereographic projection.
Parameters
descriptor Typically
Stereographic.PARAMETERS
.
values The parameter values of the projection to create.
Returns
The map projection.
References UnitaryProjection.ANGLE_TOLERANCE, UnitaryProjection.isSpherical(), Stereographic.LATITUDE_OF_ORIGIN, and Stereographic.Stereographic().
Referenced by Stereographic.createMathTransform().
     {
         final Parameters parameters = Parameters.castOrWrap(values);
         final double latitudeOfOrigin = toRadians(parameters.doubleValue(org.geotoolkit.referencing.operation.provider.Stereographic.LATITUDE_OF_ORIGIN));
         final DefaultMathTransformFactory factory = DefaultFactories.forBuildin(MathTransformFactory.class, DefaultMathTransformFactory.class);
         try {
             final NormalizedProjection projection;
             if (abs(latitudeOfOrigin - PI/2) < ANGLE_TOLERANCE) {
                 projection = new PolarStereographic(factory.getOperationMethod(PolarStereographicA.NAME), parameters);
             } else {
                 final boolean isSpherical = isSpherical(parameters);
                 if (abs(latitudeOfOrigin) < ANGLE_TOLERANCE) {
                     if (isSpherical) {
                         projection = new EquatorialStereographic.Spherical(descriptor, parameters);
                     } else {
                         projection = new EquatorialStereographic(descriptor, parameters);
                     }
                 } else if (isSpherical) {
                     projection = new Stereographic.Spherical(descriptor, parameters);
                 } else {
                     projection = new Stereographic(descriptor, parameters);
                 }
             }
             return (MathTransform2D) projection.createMapProjection(factory);
         } catch (FactoryException e) {
             throw new IllegalArgumentException(e); // TODO
         }
     }
dqsfn_dφ()
final double dqsfn_dφ (final double sinφ, final double cosφ) package inherited
Gets the derivative of the qsfn(double) method.
Parameters
sinφ The sine of latitude.
cosφ The cosines of latitude.
Returns
The
qsfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by LambertAzimuthalEqualArea.transform().
{
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         double esinφ2 = eccentricity * sinφ;
         esinφ2 *= esinφ2;
         return (1 - eccentricitySquared) * (cosφ / (1 - esinφ2)) * (1 + ((1 + esinφ2) / (1 - esinφ2)));
     }
dssfn_dφ()
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ) package inherited
Computes the derivative of the ssfn(double, double) method divided by.
ssfn
. Callers must multiply the return value by
ssfn
in order to get the actual value.
Parameters
φ The latitude.
sinφ the sine of latitude.
cosφ The cosine of latitude.
Returns
The
dssfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         assert !(abs(cosφ - cos(φ)) > ARGUMENT_TOLERANCE) : φ;
         return (1/cosφ) - (eccentricitySquared*cosφ)/(1-eccentricitySquared*sinφ*sinφ);
         /*
          * NOTE: 0.5*(t + 1/t)   =   1/cosφ
          */
     }
equals()
boolean equals (final Object object, final ComparisonMode mode) inherited
Compares the given object with this transform for equivalence.
References Stereographic.Stereographic(), and Stereographic.φ0.
{
         if (super.equals(object, mode)) {
             final Stereographic that = (Stereographic) object;
             return epsilonEqual(this.φ0, that.φ0, mode);
             // All other fields are derived from the latitude of origin.
         }
         return false;
     }
getAndStore()
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor) package inherited
Referenced by CassiniOrMercator.CassiniOrMercator(), Krovak.Krovak(), LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), NewZealandMapGrid.NewZealandMapGrid(), Orthographic.Orthographic(), and Stereographic.Stereographic().
{
         final double value = parameters.doubleValue(descriptor);    // Apply a unit conversion if needed.
         final Double defaultValue = descriptor.getDefaultValue();
         if (defaultValue == null || !defaultValue.equals(value)) {
             org.apache.sis.internal.referencing.provider.MapProjection.validate(descriptor, value);
             String name = IdentifiedObjects.getName(descriptor, parameters.getDescriptor().getName().getAuthority());
             if (name == null) {
                 name = descriptor.getName().getCode();
             }
             getContextualParameters().parameter(name).setValue(value);
         }
         return value;
     }
inverseTransform()
void inverseTransform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff) throws ProjectionException protected inherited
Transforms the specified (x,y) coordinates and stores the result in.
dstPts
(angles in radians).
References Stereographic.EPSILON, Errors.format(), UnitaryProjection.ITERATION_TOLERANCE, UnitaryProjection.MAXIMUM_ITERATIONS, and Errors.Keys.NoConvergence.
     {
         /*
          * (x,y) is multiplied by (cosχ1 / k0), so ρ below is multiplied by the same factor
          * compared to Proj4 code. This allow a few simplifications in the formulas. For example
          * in the computation of ce: atan2(ρ*cosχ1, k0)
          * simplifies to:            atan(ρ).
          */
         final double x = srcPts[srcOff  ];
         final double y = srcPts[srcOff+1];
         final double ρ = hypot(x, y);
         final double ce    = 2 * atan(ρ);
         final double cosce = cos(ce);
         final double since = sin(ce);
         final double χ   = (ρ < EPSILON) ? χ1 : asin(cosce*sinχ1 + (y*since*cosχ1 / ρ));
         final double tp    = tan(PI/4 + 0.5*χ);
         // parts of (21-36) used to calculate longitude
         final double t  = x*since;
         final double ct = ρ*cosχ1*cosce - y*sinχ1*since;
         // Compute latitude using iterative technique (3-4)
         final double halfe = 0.5*eccentricity;
         double φ = χ;
         for (int i=MAXIMUM_ITERATIONS;;) {
             final double esinφ = eccentricity * sin(φ);
             final double next = 2*atan(tp*pow((1+esinφ)/(1-esinφ), halfe)) - PI/2;
             if (abs(φ - (φ=next)) < ITERATION_TOLERANCE) {
                 break;
             }
             if (--i < 0) {
                 throw new ProjectionException(Errors.format(Errors.Keys.NoConvergence));
             }
         }
         dstPts[dstOff  ] = atan2(t, ct);
         dstPts[dstOff+1] = φ;
     }
isSpherical()
static boolean isSpherical (final Parameters parameters) static package inherited
References UnitaryProjection.inverseTransform().
Referenced by CassiniSoldner.create(), Stereographic.create(), LambertAzimuthalEqualArea.create(), and LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
{
         return parameters.parameter("semi_major").doubleValue() == parameters.parameter("semi_minor").doubleValue();
     }
msfn()
final double msfn (final double sinφ, final double cosφ) package inherited
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
Special cases:
If φ is 0°, then this method returns 1.
If φ is ±90°, then this method returns 0 provided that we are not in the spherical case (otherwise we get Double#NaN).
Parameters
sinφ The sine of the φ latitude in radians.
cosφ The cosine of the φ latitude in radians.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic().
                                                               {               // == cosφ / rν(sinφ)
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         return cosφ / sqrt(1.0 - (sinφ*sinφ) * eccentricitySquared);
     }
qsfn()
final double qsfn (final double sinφ) package inherited
Calculates q, Snyder equation (3-12).
This equation has the following properties:
Input in the [-1 ... +1] range.
Output in the [-2 ... +2] range.
Output is 0 when input is 0.
Output of the same sign than input.
qsfn(-sinφ) == -qsfn(sinφ)
.
Parameters
sinφ Sine of the latitude q is calculated for.
Returns
q from Snyder equation (3-12).
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.transform().
{
         if (eccentricity < EPSILON) {
             return 2 * sinφ;
         }
         /*
          * Above check was required because the expression below would simplify to
          * sinφ - 0.5/0*log(1) where the right terms are infinity multiplied by
          * zero, thus producing NaN.
          */
         final double esinφ = eccentricity * sinφ;
         return (1 - eccentricitySquared) * (sinφ / (1 - esinφ*esinφ) + atanh(esinφ)/eccentricity);
     }
ssfn()
final double ssfn (double φ, double sinφ) package inherited
Computes part of function (3-1) from Snyder.
This is numerically equivalent to #tsfn tsfn}(-φ, sinφ), but is defined as a separated function for clarity and because the function properties are not the same.
Parameters
φ The latitude in radians.
sinφ The sine of the φ argument. This is provided explicitly because in many cases, the caller has already computed this value.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic(), EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         sinφ *= eccentricity;
         return tan(PI/4 + 0.5*φ) * pow((1-sinφ) / (1+sinφ), 0.5*eccentricity);
     }
transform()
Matrix transform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
Since
3.20 (derived from 3.00)
References Assertions.checkTransform(), UnitaryProjection.dssfn_dφ(), and UnitaryProjection.ssfn().
     {
         final double λ    = srcPts[srcOff];
         final double φ    = srcPts[srcOff + 1];
         final double sinφ = sin(φ);
         final double sinλ = sin(λ);
         final double cosλ = cos(λ);
         final double ssfn = ssfn(φ, sinφ);
         /*
          * The multiplication by k0 is performed by the "denormalize" affine transform.
          */
         if (dstPts != null) {
             final double χ    = 2*atan(ssfn) - PI/2;
             final double cosχ = cos(χ);
             final double A    = 1 + cosχ*cosλ;    // typo in (12-29)
             final double x    = (cosχ * sinλ) / A;
             final double y    = sin(χ) / A;
             assert super.transform(srcPts, srcOff, dstPts, dstOff, false) == null
                 && Assertions.checkTransform(dstPts, dstOff, x, y);
             dstPts[dstOff]   = x;
             dstPts[dstOff+1] = y;
         }
         if (!derivate) {
             return null;
         }
         //
         // End of map projection. Now compute the derivative.
         //
         final double A        = (1 + ssfn*ssfn);
         final double dχ_dφ    = 2*dssfn_dφ(φ, sinφ, cos(φ))*ssfn / A;
         final double sinχ     = (ssfn*ssfn - 1) / A;
         final double cosχ     = 2*ssfn / A;
         final double cosχcosλ = cosχ*cosλ;
         final double cosχsinλ = cosχ*sinλ;
         final double sinχcosλ = sinχ*cosλ;
         final double F = 1 + cosχcosλ;
         return new Matrix2(
                 (cosχsinλ*cosχsinλ/F + cosχcosλ)        / F,
                 (sinχcosλ*cosχsinλ/F - sinχ*sinλ)*dχ_dφ / F,
                  cosχsinλ*sinχ / (F*F),
                 (sinχcosλ*sinχ/F + cosχ)*dχ_dφ / F);
     }
Member Data Documentation
ANGLE_TOLERANCE
final double ANGLE_TOLERANCE = 1E-6 static package inherited
Maximum difference allowed when comparing longitudes or latitudes in radians.
A tolerance of 1E-6 is about 0.2 second of arcs, which is about 6 kilometers (computed from the standard length of nautical mile).
Some formulas use this tolerance value for testing sinus or cosinus of an angle. In the sinus case, this is justified because sin(θ) ≅ θ when θ is small. Similar reasoning applies to cosinus with cos(θ) ≅ θ + π/2 when θ is small.
Referenced by Stereographic.create(), Orthographic.inverseTransform(), LambertAzimuthalEqualArea.inverseTransform(), Orthographic.Orthographic(), and Stereographic.Stereographic().
cosφ0
final double cosφ0 package inherited
cosχ1
final double cosχ1 package inherited
Referenced by Stereographic.Stereographic(), and Stereographic.transform().
EPSILON
final double EPSILON = 1E-6 static package inherited
Maximum difference allowed when comparing real numbers.
Referenced by EquatorialStereographic.Spherical.inverseTransform(), and Stereographic.inverseTransform().
ITERATION_TOLERANCE
final double ITERATION_TOLERANCE = 1E-10 static package inherited
Difference allowed in iterative computations.
A value of 1E-10 causes the cphi2 function to compute the latitude at a precision of 1E-10 radians, which is slightly smaller than one millimetre.
Referenced by CassiniOrMercator.inv_mlfn(), and Stereographic.inverseTransform().
MAXIMUM_ITERATIONS
final int MAXIMUM_ITERATIONS = 15 static package inherited
Maximum number of iterations for iterative computations.
Referenced by CassiniOrMercator.inv_mlfn(), Stereographic.inverseTransform(), and Krovak.inverseTransform().
serialVersionUID
final long serialVersionUID = -5098015759558831875L static private
For cross-version compatibility.
sinφ0
final double sinφ0 package inherited
Constants used for the oblique projections.
All those constants are completely determined by φ0. Consequently, there is no need to test them in hashCode or equals(Object, ComparisonMode) methods.
φ0
final double φ0 package inherited
The latitude of origin, in radians.
Referenced by Stereographic.equals(), EquatorialStereographic.EquatorialStereographic(), and Stereographic.Spherical.inverseTransform().