jena-geo: MetadataFactory Class Reference
MetadataFactory Class Reference
Create metadata objects of the given Class using the properties given in a Map.
Public Member Functions
MetadataFactory ()
Creates a new factory implementing the MetadataStandard::ISO_19115 ISO 19115} standard and using the referencing factories known to FactoryFinder.
MetadataFactory (final MetadataStandard... standards)
Creates a new factory for the given metadata standards and the referencing factories known to FactoryFinder.
MetadataFactory (final Set<?> factories, final MetadataStandard... standards)
Creates a new factory for the given metadata standards.
Package Functions
public< T > T create (final Class< T > type, final Map< String,?> properties) throws FactoryException
Creates a new metadata of the given type, initialized with the property values given in the properties map.
Static Private Member Functions
static Set<?> factories ()
Returns the factories declared in FactoryFinder.
Private Attributes
final Object [] factories
An optional set of factories to try before to create the metadata objects directly.
final MetadataStandard [] standards
The standards implemented by this factory.
final Map< Class<?>, FactoryMethod > factoryMethods
The methods to use for instantiating object of the classes in the keys.
Detailed Description
Create metadata objects of the given Class using the properties given in a Map.
For any given type, this class tries to instantiate the metadata object in two ways:
First, if a collection of factories has been given to the constructor, then this method will search for a
create(Map, ...)
method returning an object assignable to the requested one. For example if the user requests a org.opengis.referencing.crs.VerticalCRS and this
MetadataFactory
has been given a org.opengis.referencing.crs.CRSFactory at construction time, then the
CRSFactory.createVerticalCRS(Map, ...)
method will be used.
If no suitable factory is found, then
MetadataFactory
will try to instantiate a metadata implementation directly using Class#newInstance(). The class can be an interface like org.opengis.metadata.citation.Citation or its implementation class like org.apache.sis.metadata.iso.citation.DefaultCitation. The keys in the map shall be the KeyNamePolicy::UML_IDENTIFIER UML identifiers} or the KeyNamePolicy::JAVABEANS_PROPERTY Java Beans name} of metadata properties, for example
"title"
for the value to be returned by org.opengis.metadata.citation.Citation#getTitle().
Author
Martin Desruisseaux (Geomatys)
Version
3.03
Since
3.03
Constructor & Destructor Documentation
MetadataFactory() [1/3]
MetadataFactory ()
Creates a new factory implementing the MetadataStandard::ISO_19115 ISO 19115} standard and using the referencing factories known to FactoryFinder.
References MetadataFactory.factories().
{
         this(factories(), MetadataStandard.ISO_19115);
     }
MetadataFactory() [2/3]
MetadataFactory (final MetadataStandard... standards)
Creates a new factory for the given metadata standards and the referencing factories known to FactoryFinder.
Parameters
standards The metadata standards implemented by this factory.
References MetadataFactory.factories(), and MetadataFactory.standards.
{
         this(factories(), standards);
     }
MetadataFactory() [3/3]
MetadataFactory (final Set<?> factories, final MetadataStandard... standards)
Creates a new factory for the given metadata standards.
The given collection of factories will be used if possible before to instantiate a metadata object directly.
Parameters
factories The factories to try before to instantiate the metadata directly, or
null
if none.
standards The metadata standards implemented by this factory.
{
         if (!isNullOrEmpty(factories)) {
             this.factories = factories.toArray();
             factoryMethods = new HashMap<>();
         } else {
             this.factories = null;
             factoryMethods = null;
         }
         this.standards = standards.clone();
     }
Member Function Documentation
create()
public<T> T create (final Class< T > type, final Map< String,?> properties) throws FactoryException package
Creates a new metadata of the given type, initialized with the property values given in the properties map.
Parameters
<T> The parameterized type of the
type
argument.
type The interface or implementation type of the metadata object to be created.
properties The property values to be given to the metadata object.
Returns
A new metadata object of the given class or implementation, filled with the given values.
Exceptions
FactoryException If the metadata object can not be created.
References FactoryMethod.create(), FactoryMethod.equals(), MetadataFactory.factoryMethods, FactoryMethod.find(), Errors.format(), FactoryMethod.NULL, and Errors.Keys.UnknownType_1.
{
         /*
          * First, check if there is a factory method for the given type.
          */
         if (factoryMethods != null) {
             FactoryMethod method;
             synchronized (factoryMethods) {
                 method = factoryMethods.get(type);
                 if (method == null) {
                     method = FactoryMethod.find(type, factories);
                     if (method == null) {
                         method = FactoryMethod.NULL;
                     } else {
                         // Found a method. Check if we already created an equal instance previously.
                         // If yes, we can safely share the instance since FactoryMethod are immutable.
                         for (final FactoryMethod existing : factoryMethods.values()) {
                             if (method.equals(existing)) {
                                 method = existing;
                                 break;
                             }
                         }
                     }
                     factoryMethods.put(type, method);
                 }
             }
             final Object metadata = method.create(properties);
             if (metadata != null) {
                 return type.cast(metadata);
             }
         }
         /*
          * At this point, we have not found any suitable factory method.
          * Try to instantiate the implementation class directly.
          */
         ReflectiveOperationException failure = null;
         for (final MetadataStandard standard : standards) {
             if (standard.isMetadata(type)) {
                 Class<?> impl = standard.getImplementation(type);
                 if (impl == null) {
                     impl = type; // Will try to instantiate the type directly.
                 }
                 final Object metadata;
                 try {
                     metadata = impl.newInstance();
                 } catch (ReflectiveOperationException e) {
                     if (failure == null) {
                         failure = e;
                     }
                     continue;
                 } catch (Exception e) {
                     /*
                      * We catch all Exceptions because Class.newInstance() propagates all of them,
                      * including the checked ones (it bypasses the compile-time exception checking).
                      */
                     throw new FactoryException(e.getLocalizedMessage(), e);
                 }
                 final Map<String,Object> asMap = standard.asValueMap(metadata, null,
                         KeyNamePolicy.JAVABEANS_PROPERTY, ValueExistencePolicy.NON_EMPTY);
                 try {
                     asMap.putAll(properties);
                 } catch (RuntimeException e) {
                     throw new FactoryException(e.getLocalizedMessage(), e);
                 }
                 return type.cast(metadata);
             }
         }
         throw new FactoryException(Errors.format(Errors.Keys.UnknownType_1, type), failure);
     }
factories()
static Set<?> factories () static private
Returns the factories declared in FactoryFinder.
Referenced by MetadataFactory.MetadataFactory().
{
         final Set<Object> factories = new LinkedHashSet<>();
         for (int i=0; ; i++) {
             final ObjectFactory factory;
             switch (i) {
                 /*
                  * We declare only the factories having create(Map<String,?>, ...) methods.
                  * We pickup the DatumFactory first because in the particular case of Geotk
                  * implementation, CRS and CS factories are also Datum factory and we don't
                  * want them to hide the default DatumFactory.
                  */
                 case 0: factory = DefaultFactories.forBuildin(DatumFactory.class); break;
                 case 1: factory = DefaultFactories.forBuildin(CSFactory.class); break;
                 case 2: factory = DefaultFactories.forBuildin(CRSFactory.class); break;
                 default: return factories;
             }
             factories.add(factory);
         }
     }
Member Data Documentation
factories
final Object [] factories private
An optional set of factories to try before to create the metadata objects directly.
This is
null
if there is no such factory.
factoryMethods
final Map<Class<?>, FactoryMethod> factoryMethods private
The methods to use for instantiating object of the classes in the keys.
This is
null
if
factories
is null.
Referenced by MetadataFactory.create().
standards
final MetadataStandard [] standards private
The standards implemented by this factory.
Referenced by MetadataFactory.MetadataFactory().