jena-geo: Krovak Class Reference
Krovak Class Reference
<cite>Krovak Oblique Conformal Conic</cite> projection (EPSG code 9819).
Public Member Functions
Matrix transform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
Converts the specified (λ,φ) coordinate (units in radians) and stores the result in.
boolean equals (final Object object, final ComparisonMode mode)
Compares the given object with this transform for equivalence.
Static Public Member Functions
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values)
Creates a Krovak projection from the given parameters.
Protected Member Functions
Krovak (final OperationMethod method, final Parameters parameters)
Constructs a new map projection from the supplied parameters.
void inverseTransform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff) throws ProjectionException
Transforms the specified (x,y) coordinates and stores the result in.
int computeHashCode ()
Package Functions
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor)
final double msfn (final double sinφ, final double cosφ)
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
final double ssfn (double φ, double sinφ)
Computes part of function (3-1) from Snyder.
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ)
Computes the derivative of the ssfn(double, double) method divided by.
final double qsfn (final double sinφ)
Calculates q, Snyder equation (3-12).
final double dqsfn_dφ (final double sinφ, final double cosφ)
Gets the derivative of the qsfn(double) method.
Static Package Functions
static boolean isSpherical (final Parameters parameters)
Package Attributes
final double cosAzim
final double tanS2
final double alfa
final double hae
final double k1
final double ka
final double ro0
Static Package Attributes
static final double ANGLE_TOLERANCE = 1E-6
Maximum difference allowed when comparing longitudes or latitudes in radians.
static final int MAXIMUM_ITERATIONS = 15
Maximum number of iterations for iterative computations.
static final double EPSILON = 1E-7
Maximum difference allowed when comparing real numbers (other cases).
Static Private Member Functions
static Map< ParameterRole, ParameterDescriptor< Double > > roles ()
Private Attributes
final double sinAzim
Sinus and cosine of the azimuth.
final double n
Useful variables calculated from parameters defined by user.
Static Private Attributes
static final long serialVersionUID = -8359105634355342212L
For cross-version compatibility.
static final double ITERATION_TOLERANCE = 1E-11
When to stop the iteration.
Detailed Description
<cite>Krovak Oblique Conformal Conic</cite> projection (EPSG code 9819).
See the Krovak on POSC for an overview. See any of the following providers for a list of programmatic parameters:
org.geotoolkit.referencing.operation.provider.Krovak
{
}
This projection is used in the Czech Republic and Slovakia under the name "Krovak" projection. The geographic coordinates on the ellipsoid are first reduced to conformal coordinates on the conformal (Gaussian) sphere. These spherical coordinates are then projected onto the oblique cone and converted to grid coordinates. The pseudo standard parallel is defined on the conformal sphere after its rotation, to obtain the oblique aspect of the projection. It is then the parallel on this sphere at which the map projection is true to scale; on the ellipsoid it maps as a complex curve.
The compulsory parameters are just the ellipsoid characteristics. All other parameters are optional and have defaults to match the common usage with Krovak projection.
org.opengis.referencing.crs.ProjectedCRS Projected CRS} using the Krovak projection are usually defined with (southing, westing) axis orientations. ESRI uses those orientations by default. However in Geotk, every projection must have (easting, northing) orientations - axis reversal are handled by the concatenation of affine transforms. Consequently in order to get the usual axis order, a Krovak projected CRS must defines axis order explicitly (as required by the OGC standard) like in the example below:
{ wkt PROJCS["S-JTSK (Ferro) / Krovak", GEOCS[...], PROJECTION["Krovak"], PARAMETER["semi_major", 6377397.155], PARAMETER["semi_minor", 6356078.963], UNIT["metre", 1], AXIS["y", SOUTH], AXIS["x", WEST]] }
The default Krovak projection implemented by this class - having (easting, northing) axis orientations - is cold Krovak GIS version.
{
}
Proj-4.4.7 available at www.remotesensing.org/proj
Relevant files is:
PJ_krovak.c
"Coordinate Conversions and Transformations including Formulas" available at, http://www.remotesensing.org/geotiff/proj_list/guid7.html
Author
Jan Jezek (HSRS)
Martin Desruisseaux (IRD, Geomatys)
Rémi Maréchal (Geomatys)
Since
2.4
Constructor & Destructor Documentation
Krovak()
Krovak (final OperationMethod method, final Parameters parameters) protected
Constructs a new map projection from the supplied parameters.
Parameters
parameters The parameters of the projection to be created.
References Krovak.alfa, Krovak.cosAzim, UnitaryProjection.getAndStore(), Krovak.hae, Krovak.k1, Krovak.ka, Krovak.n, Krovak.ro0, Krovak.roles(), Krovak.sinAzim, and Krovak.tanS2.
Referenced by Krovak.create(), and Krovak.equals().
{
         super(method, parameters, roles());
         double latitudeOfOrigin = getAndStore(parameters, LATITUDE_OF_CENTRE);
         latitudeOfOrigin = toRadians(latitudeOfOrigin);
         final double pseudoStandardParallel = toRadians(getAndStore(parameters, PSEUDO_STANDARD_PARALLEL));
         final double azimuth = toRadians(getAndStore(parameters, AZIMUTH));
         sinAzim = sin(azimuth);
         cosAzim = cos(azimuth);
         n       = sin(pseudoStandardParallel);
         tanS2   = tan(pseudoStandardParallel/2 + PI/4);
         final double sinLat, cosLat, cosL2, u0;
         sinLat = sin(latitudeOfOrigin);
         cosLat = cos(latitudeOfOrigin);
         cosL2  = cosLat * cosLat;
         alfa   = sqrt(1 + ((eccentricitySquared * (cosL2*cosL2)) / (1 - eccentricitySquared)));
         hae    = alfa * eccentricity / 2;
         u0     = asin(sinLat / alfa);
         final double g, esl;
         esl = eccentricity * sinLat;
         g   = pow((1 - esl) / (1 + esl), (alfa * eccentricity) / 2);
         k1  = pow(tan(latitudeOfOrigin/2 + PI/4), alfa) * g / tan(u0/2 + PI/4);
         ka  = pow(1/k1, -1/alfa);
         ro0 = pow(tanS2, -n);
         final double radius = sqrt(1 - eccentricitySquared) / (1 - (eccentricitySquared * (sinLat*sinLat))); // TODO: radiusOfConformanceSphere.
         final double rop = radius / (ro0 * tan(pseudoStandardParallel));
         /*
          * At this point, all parameters have been processed. Now process to their
          * validation and the initialization of (de)normalize affine transforms.
          */
         getContextualParameters().getMatrix(MatrixRole.NORMALIZATION).convertAfter(0, -alfa, null);
         getContextualParameters().getMatrix(MatrixRole.DENORMALIZATION).convertBefore(0, -rop, null);
         getContextualParameters().getMatrix(MatrixRole.DENORMALIZATION).convertBefore(1, -rop, null);
     }
Member Function Documentation
computeHashCode()
int computeHashCode () protected
References Krovak.n, and Krovak.sinAzim.
{
         return hash(sinAzim, hash(n, super.computeHashCode()));
     }
create()
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values) static
Creates a Krovak projection from the given parameters.
The descriptor argument is usually org.geotoolkit.referencing.operation.provider.Krovak#PARAMETERS, but is not restricted to. If a different descriptor is supplied, it is user's responsibility to ensure that it is suitable to a Krovak projection.
Parameters
descriptor Typically
Krovak.PARAMETERS
.
values The parameter values of the projection to create.
Returns
The map projection.
Since
3.00
References Krovak.Krovak().
Referenced by Krovak.createMathTransform().
     {
         final Krovak projection;
         final Parameters parameters = Parameters.castOrWrap(values);
         projection = new Krovak(descriptor, parameters);
         try {
             return (MathTransform2D) projection.createMapProjection(
                     org.apache.sis.internal.system.DefaultFactories.forBuildin(
                             org.opengis.referencing.operation.MathTransformFactory.class));
         } catch (org.opengis.util.FactoryException e) {
             throw new IllegalArgumentException(e); // TODO
         }
     }
dqsfn_dφ()
final double dqsfn_dφ (final double sinφ, final double cosφ) package inherited
Gets the derivative of the qsfn(double) method.
Parameters
sinφ The sine of latitude.
cosφ The cosines of latitude.
Returns
The
qsfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by LambertAzimuthalEqualArea.transform().
{
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         double esinφ2 = eccentricity * sinφ;
         esinφ2 *= esinφ2;
         return (1 - eccentricitySquared) * (cosφ / (1 - esinφ2)) * (1 + ((1 + esinφ2) / (1 - esinφ2)));
     }
dssfn_dφ()
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ) package inherited
Computes the derivative of the ssfn(double, double) method divided by.
ssfn
. Callers must multiply the return value by
ssfn
in order to get the actual value.
Parameters
φ The latitude.
sinφ the sine of latitude.
cosφ The cosine of latitude.
Returns
The
dssfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         assert !(abs(cosφ - cos(φ)) > ARGUMENT_TOLERANCE) : φ;
         return (1/cosφ) - (eccentricitySquared*cosφ)/(1-eccentricitySquared*sinφ*sinφ);
         /*
          * NOTE: 0.5*(t + 1/t)   =   1/cosφ
          */
     }
equals()
boolean equals (final Object object, final ComparisonMode mode)
Compares the given object with this transform for equivalence.
References Krovak.alfa, Krovak.cosAzim, Krovak.hae, Krovak.k1, Krovak.ka, Krovak.Krovak(), Krovak.n, Krovak.ro0, Krovak.sinAzim, and Krovak.tanS2.
{
         if (super.equals(object, mode)) {
             final Krovak that = (Krovak) object;
             return epsilonEqual(sinAzim, that.sinAzim, mode) &&
                    epsilonEqual(cosAzim, that.cosAzim, mode) &&
                    epsilonEqual(n,       that.n,       mode) &&
                    epsilonEqual(tanS2,   that.tanS2,   mode) &&
                    epsilonEqual(alfa,    that.alfa,    mode) &&
                    epsilonEqual(hae,     that.hae,     mode) &&
                    epsilonEqual(k1,      that.k1,      mode) &&
                    epsilonEqual(ka,      that.ka,      mode) &&
                    epsilonEqual(ro0,     that.ro0,     mode);
         }
         return false;
     }
getAndStore()
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor) package inherited
Referenced by CassiniOrMercator.CassiniOrMercator(), Krovak.Krovak(), LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), NewZealandMapGrid.NewZealandMapGrid(), Orthographic.Orthographic(), and Stereographic.Stereographic().
{
         final double value = parameters.doubleValue(descriptor);    // Apply a unit conversion if needed.
         final Double defaultValue = descriptor.getDefaultValue();
         if (defaultValue == null || !defaultValue.equals(value)) {
             org.apache.sis.internal.referencing.provider.MapProjection.validate(descriptor, value);
             String name = IdentifiedObjects.getName(descriptor, parameters.getDescriptor().getName().getAuthority());
             if (name == null) {
                 name = descriptor.getName().getCode();
             }
             getContextualParameters().parameter(name).setValue(value);
         }
         return value;
     }
inverseTransform()
void inverseTransform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff) throws ProjectionException protected
Transforms the specified (x,y) coordinates and stores the result in.
dstPts
(angles in radians).
References Krovak.alfa, Krovak.cosAzim, Errors.format(), Krovak.ITERATION_TOLERANCE, Krovak.ka, UnitaryProjection.MAXIMUM_ITERATIONS, Krovak.n, Errors.Keys.NoConvergence, Krovak.ro0, Krovak.sinAzim, and Krovak.tanS2.
     {
         final double x = srcPts[srcOff];
         final double y = srcPts[srcOff + 1];
         // x -> southing, y -> westing
         final double ρ    = hypot(x, y);
         final double D    = atan2(x, y) / n;
         final double S    = 2 * (atan(pow(ro0/ρ, 1/n) * tanS2) - PI/4);
         final double cosS = cos(S);
         final double U    = asin(cosAzim*sin(S) - sinAzim*cosS*cos(D));
         final double kau  = ka * pow(tan(U/2 + PI/4), 1/alfa);
         final double Δv   = asin(cosS * sin(D)/cos(U));
         double φ = 0;
         // iteration calculation
         for (int i=MAXIMUM_ITERATIONS;;) {
             final double φ1 = φ;
             final double esf = eccentricity * sin(φ1);
             φ = 2 * (atan(kau * pow((1 + esf) / (1 - esf), eccentricity/2)) - PI/4);
             if (abs(φ1 - φ) <= ITERATION_TOLERANCE) {
                 break;
             }
             if (--i < 0) {
                 throw new ProjectionException(Errors.format(Errors.Keys.NoConvergence));
             }
         }
         dstPts[dstOff  ] = Δv;
         dstPts[dstOff+1] = φ;
     }
isSpherical()
static boolean isSpherical (final Parameters parameters) static package inherited
References UnitaryProjection.inverseTransform().
Referenced by CassiniSoldner.create(), Stereographic.create(), LambertAzimuthalEqualArea.create(), and LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
{
         return parameters.parameter("semi_major").doubleValue() == parameters.parameter("semi_minor").doubleValue();
     }
msfn()
final double msfn (final double sinφ, final double cosφ) package inherited
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
Special cases:
If φ is 0°, then this method returns 1.
If φ is ±90°, then this method returns 0 provided that we are not in the spherical case (otherwise we get Double#NaN).
Parameters
sinφ The sine of the φ latitude in radians.
cosφ The cosine of the φ latitude in radians.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic().
                                                               {               // == cosφ / rν(sinφ)
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         return cosφ / sqrt(1.0 - (sinφ*sinφ) * eccentricitySquared);
     }
qsfn()
final double qsfn (final double sinφ) package inherited
Calculates q, Snyder equation (3-12).
This equation has the following properties:
Input in the [-1 ... +1] range.
Output in the [-2 ... +2] range.
Output is 0 when input is 0.
Output of the same sign than input.
qsfn(-sinφ) == -qsfn(sinφ)
.
Parameters
sinφ Sine of the latitude q is calculated for.
Returns
q from Snyder equation (3-12).
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.transform().
{
         if (eccentricity < EPSILON) {
             return 2 * sinφ;
         }
         /*
          * Above check was required because the expression below would simplify to
          * sinφ - 0.5/0*log(1) where the right terms are infinity multiplied by
          * zero, thus producing NaN.
          */
         final double esinφ = eccentricity * sinφ;
         return (1 - eccentricitySquared) * (sinφ / (1 - esinφ*esinφ) + atanh(esinφ)/eccentricity);
     }
roles()
static Map<ParameterRole, ParameterDescriptor<Double> > roles () static private
Referenced by Krovak.Krovak().
{
         final EnumMap<ParameterRole, ParameterDescriptor<Double>> roles = new EnumMap<>(ParameterRole.class);
         roles.put(ParameterRole.CENTRAL_MERIDIAN, LONGITUDE_OF_CENTRE);
         roles.put(ParameterRole.SCALE_FACTOR,     SCALE_FACTOR);
         roles.put(ParameterRole.FALSE_EASTING,    FALSE_EASTING);
         roles.put(ParameterRole.FALSE_NORTHING,   FALSE_NORTHING);
         return roles;
     }
ssfn()
final double ssfn (double φ, double sinφ) package inherited
Computes part of function (3-1) from Snyder.
This is numerically equivalent to #tsfn tsfn}(-φ, sinφ), but is defined as a separated function for clarity and because the function properties are not the same.
Parameters
φ The latitude in radians.
sinφ The sine of the φ argument. This is provided explicitly because in many cases, the caller has already computed this value.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic(), EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         sinφ *= eccentricity;
         return tan(PI/4 + 0.5*φ) * pow((1-sinφ) / (1+sinφ), 0.5*eccentricity);
     }
transform()
Matrix transform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
Converts the specified (λ,φ) coordinate (units in radians) and stores the result in.
dstPts
(linear distance on a unit sphere). In addition, opportunistically computes the projection derivative if
derivate
is
true
.
Since
3.20 (derived from 3.00)
References Krovak.alfa, Krovak.cosAzim, Krovak.hae, Krovak.k1, Krovak.n, and Krovak.sinAzim.
     {
         final double Δv    = srcPts[srcOff];
         final double φ     = srcPts[srcOff+1];
         final double sinΔv = sin(Δv);
         final double cosΔv = cos(Δv);
         final double esinφ = eccentricity * sin(φ);
         final double tan1  = tan(φ/2 + PI/4);
         final double gφ    = pow((1-esinφ) / (1+esinφ), hae);
         final double V     = pow(tan1, alfa) / k1 * gφ;
         final double U     = 2 * (atan(V) - PI/4);
         final double sinU  = sin(U);
         final double cosU  = cos(U);
         final double sinS  = cosAzim*sinU + sinAzim*cosU*cosΔv;
         final double cosS  = sqrt(1 - sinS*sinS);
         final double S     = asin(sinS);
         final double Ɛt    = cosU*sinΔv / cosS;
         final double Ɛ     = n * asin(Ɛt);
         final double cosƐ  = cos(Ɛ);
         final double sinƐ  = sin(Ɛ);
         final double tan2  = tan(S/2 + PI/4);
         final double ρ     = pow(tan2, n);
         if (dstPts != null) {
             // x and y are reverted.
             dstPts[dstOff  ] = sinƐ / ρ;
             dstPts[dstOff+1] = cosƐ / ρ;
         }
         if (!derivate) {
             return null;
         }
         //
         // End of map projection. Now compute the derivative.
         //
         final double dgφ    = eccentricitySquared*cos(φ) / (1 - esinφ*esinφ);
         final double dU_dφ  = alfa * (1/tan1 + tan1 - 2*dgφ) / (1/V + V);
         final double dS_dλ  = (-sinAzim*cosU*sinΔv) / cosS;
         final double dS_dφ  = (-sinAzim*sinU*cosΔv + cosAzim*cosU)*dU_dφ / cosS;
         final double t      = n / (cosS*cosS*sqrt(1 - Ɛt*Ɛt));
         final double dƐ_dλ  = cosU  * t * (dS_dλ*sinΔv*sinS +       cosΔv*cosS);
         final double dƐ_dφ  = sinΔv * t * (dS_dφ*sinS*cosU - dU_dφ*sinU*cosS);
         final double m      = (-n/2) * (1/tan2 + tan2);
         return new Matrix2(
                 (m*dS_dλ * sinƐ + dƐ_dλ * cosƐ) / ρ,
                 (m*dS_dφ * sinƐ + dƐ_dφ * cosƐ) / ρ,
                 (m*dS_dλ * cosƐ - dƐ_dλ * sinƐ) / ρ,
                 (m*dS_dφ * cosƐ - dƐ_dφ * sinƐ) / ρ);
     }
Member Data Documentation
alfa
final double alfa package
Referenced by Krovak.equals(), Krovak.inverseTransform(), Krovak.Krovak(), and Krovak.transform().
ANGLE_TOLERANCE
final double ANGLE_TOLERANCE = 1E-6 static package inherited
Maximum difference allowed when comparing longitudes or latitudes in radians.
A tolerance of 1E-6 is about 0.2 second of arcs, which is about 6 kilometers (computed from the standard length of nautical mile).
Some formulas use this tolerance value for testing sinus or cosinus of an angle. In the sinus case, this is justified because sin(θ) ≅ θ when θ is small. Similar reasoning applies to cosinus with cos(θ) ≅ θ + π/2 when θ is small.
Referenced by Stereographic.create(), Orthographic.inverseTransform(), LambertAzimuthalEqualArea.inverseTransform(), Orthographic.Orthographic(), and Stereographic.Stereographic().
cosAzim
final double cosAzim package
Referenced by Krovak.equals(), Krovak.inverseTransform(), Krovak.Krovak(), and Krovak.transform().
EPSILON
final double EPSILON = 1E-7 static package inherited
Maximum difference allowed when comparing real numbers (other cases).
The value defined here is consistent with the one that was used in LambertAzimuthalEqualArea for the same purpose (not to be confused with the current
EPSILON
constant defined in the above-mentioned class, which has been renamed), and the modified value used in AlbersEqualArea.
hae
final double hae package
Referenced by Krovak.equals(), Krovak.Krovak(), and Krovak.transform().
ITERATION_TOLERANCE
final double ITERATION_TOLERANCE = 1E-11 static private
When to stop the iteration.
Referenced by Krovak.inverseTransform().
k1
final double k1 package
Referenced by Krovak.equals(), Krovak.Krovak(), and Krovak.transform().
ka
final double ka package
Referenced by Krovak.equals(), Krovak.inverseTransform(), and Krovak.Krovak().
MAXIMUM_ITERATIONS
final int MAXIMUM_ITERATIONS = 15 static package inherited
Maximum number of iterations for iterative computations.
Referenced by CassiniOrMercator.inv_mlfn(), Stereographic.inverseTransform(), and Krovak.inverseTransform().
n
final double n private
Useful variables calculated from parameters defined by user.
They depend on the latitude of origin, the latitude of pseudo standard parallel and the eccentricity.
Referenced by Krovak.computeHashCode(), Krovak.equals(), Krovak.inverseTransform(), Krovak.Krovak(), and Krovak.transform().
ro0
final double ro0 package
Referenced by Krovak.equals(), Krovak.inverseTransform(), and Krovak.Krovak().
serialVersionUID
final long serialVersionUID = -8359105634355342212L static private
For cross-version compatibility.
sinAzim
final double sinAzim private
Sinus and cosine of the azimuth.
The azimuth is measured at the centre line passing through the centre of the projection, and is equal to the co-latitude of the cone axis at point of intersection with the ellipsoid.
Referenced by Krovak.computeHashCode(), Krovak.equals(), Krovak.inverseTransform(), Krovak.Krovak(), and Krovak.transform().
tanS2
final double tanS2 package
Referenced by Krovak.equals(), Krovak.inverseTransform(), and Krovak.Krovak().