jena-geo: Histogram Class Reference
Histogram Class Reference
Histogram querying class.
Public Member Functions
Histogram (long[] buckets, double start, double end)
double getStart ()
double getEnd ()
long [] getBuckets ()
long getSum ()
Calculate sum of all values in the buckets.
double getBucketSize ()
Get the span of a bucket.
double [] getBucketRange (int index)
double getValueAt (double ratio)
Estimate the thredhold value for a given ratio .
Private Attributes
final long [] buckets
final double start
final double end
long sum = -1
Detailed Description
Histogram querying class.
Author
Johann Sorel (Geomatys)
Constructor & Destructor Documentation
Histogram()
Histogram (long [] buckets, double start, double end)
References Histogram.buckets, Histogram.end, and Histogram.start.
{
         this.buckets = buckets;
         this.start = start;
         this.end = end;
     }
Member Function Documentation
getBucketRange()
double [] getBucketRange (int index)
References Histogram.getBucketSize().
{
         final double span = getBucketSize();
         return new double[]{start+index*span, start+(index+1)*span};
     }
getBuckets()
long [] getBuckets ()
References Histogram.buckets.
{
         return buckets;
     }
getBucketSize()
double getBucketSize ()
Get the span of a bucket.
Returns
bucket span
Referenced by Histogram.getBucketRange(), and Histogram.getValueAt().
{
         return (end-start) / buckets.length;
     }
getEnd()
double getEnd ()
References Histogram.end.
{
         return end;
     }
getStart()
double getStart ()
References Histogram.start.
{
         return start;
     }
getSum()
long getSum ()
Calculate sum of all values in the buckets.
Returns
number of values in the histogram (sum of all buckets)
References Histogram.sum.
Referenced by Histogram.getValueAt().
{
         if(sum!=-1) return sum;
         //calculate sum
         long s = 0;
         for(long l : buckets) s+=l;
         sum = s;
         return sum;
     }
getValueAt()
double getValueAt (double ratio)
Estimate the thredhold value for a given ratio .
Parameters
ratio [0-1]
References Histogram.end, Histogram.getBucketSize(), Histogram.getSum(), and Histogram.start.
{
         if(ratio<=0) return start;
         if(ratio>=1) return end;
         final long sum = getSum();
         double remain = sum * ratio;
         for(int i=0;i<buckets.length;i++){
             if(buckets[i]>remain){
                 //this bucket contain the searched %
                 //linear interpolatation
                 final double span = getBucketSize();
                 final double bucketStart = start+i*span;
                 final double bucketEnd = start+(i+1)*span;
                 ratio = 1.0 - (((double)buckets[i]-remain) / (double)buckets[i]);
                 return bucketStart + (bucketEnd-bucketStart) * ratio;
             }else{
                 remain -= buckets[i];
             }
         }
         //we should be reach here, because of double rounding values it might happen
         //if the % value is very close to 1
         return end;
     }
Member Data Documentation
buckets
final long [] buckets private
Referenced by Histogram.getBuckets(), and Histogram.Histogram().
end
final double end private
Referenced by Histogram.getEnd(), Histogram.getValueAt(), and Histogram.Histogram().
start
final double start private
Referenced by Histogram.getStart(), Histogram.getValueAt(), and Histogram.Histogram().
sum
long sum = -1 private
Referenced by Histogram.getSum().