jena-geo: CassiniSoldner Class Reference
CassiniSoldner Class Reference
<cite>Cassini-Soldner</cite> projection (EPSG code 9806).
Classes
class Spherical
Provides the transform equations for the spherical case of the Cassini-Soldner projection.
Public Member Functions
Matrix transform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
Converts the specified (λ,φ) coordinate (units in radians) and stores the result in.
Static Public Member Functions
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values)
Creates a Cassini-Soldner projection from the given parameters.
Protected Member Functions
CassiniSoldner (final OperationMethod method, final Parameters parameters)
Constructs a new map projection from the supplied parameters.
void inverseTransform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff) throws ProjectionException
Transforms the specified (x,y) coordinates and stores the result in.
Package Functions
final double mlfn (final double φ, double sinφ, double cosφ)
Calculates the meridian distance.
final double dmlfn_dφ (final double sinφ2, final double cosφ2)
Gets the derivative of this mlfn(double, double, double) method.
final double inv_mlfn (final double delta) throws ProjectionException
Calculates the latitude (.
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor)
final double msfn (final double sinφ, final double cosφ)
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
final double ssfn (double φ, double sinφ)
Computes part of function (3-1) from Snyder.
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ)
Computes the derivative of the ssfn(double, double) method divided by.
final double qsfn (final double sinφ)
Calculates q, Snyder equation (3-12).
final double dqsfn_dφ (final double sinφ, final double cosφ)
Gets the derivative of the qsfn(double) method.
Static Package Functions
static boolean isSpherical (final Parameters parameters)
Package Attributes
final double en1
final double en2
final double en3
final double en4
Static Package Attributes
static final double C2 = 0.08333333333333333333
static final double C3 = 0.41666666666666666666
static final double C4 = 0.33333333333333333333
static final double C5 = 0.66666666666666666666
static final double ASSERTION_DOMAIN = 5 * (PI/180)
Maximal difference (in radians) from central meridian for enabling assertions.
static final double C02 = 0.25
static final double C04 = 0.046875
static final double C06 = 0.01953125
static final double C08 = 0.01068115234375
static final double C22 = 0.75
static final double C44 = 0.46875
static final double C46 = 0.01302083333333333333
static final double C48 = 0.00712076822916666666
static final double C66 = 0.36458333333333333333
static final double C68 = 0.00569661458333333333
static final double C88 = 0.3076171875
static final double ANGLE_TOLERANCE = 1E-6
Maximum difference allowed when comparing longitudes or latitudes in radians.
static final double ITERATION_TOLERANCE = 1E-10
Difference allowed in iterative computations.
static final int MAXIMUM_ITERATIONS = 15
Maximum number of iterations for iterative computations.
static final double EPSILON = 1E-7
Maximum difference allowed when comparing real numbers (other cases).
Static Private Attributes
static final long serialVersionUID = 4710150547701615178L
For cross-version compatibility.
static final double C1 = 0.16666666666666666666
Constants used for the forward and inverse transform for the elliptical case of the Cassini-Soldner.
Detailed Description
<cite>Cassini-Soldner</cite> projection (EPSG code 9806).
See the Cassini projection on MathWorld for an overview. See any of the following providers for a list of programmatic parameters:
org.geotoolkit.referencing.operation.provider.CassiniSoldner
{
}
The Cassini-Soldner Projection is the ellipsoidal version of the Cassini projection for the sphere. It is not conformal but as it is relatively simple to construct it was extensively used in the last century and is still useful for mapping areas with limited longitudinal extent. It has now largely been replaced by the conformal TransverseMercator Transverse Mercator} which it resembles. Like this, it has a straight central meridian along which the scale is true, all other meridians and parallels are curved, and the scale distortion increases rapidly with increasing distance from the central meridian.
Author
Mauro Bartolomeoli
Martin Desruisseaux (Geomatys)
Rémi Maréchal (Geomatys)
Since
3.00
Constructor & Destructor Documentation
CassiniSoldner()
CassiniSoldner (final OperationMethod method, final Parameters parameters) protected
Constructs a new map projection from the supplied parameters.
Parameters
parameters The parameters of the projection to be created.
Referenced by CassiniSoldner.create().
{
         super(method, parameters);
     }
Member Function Documentation
create()
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values) static
Creates a Cassini-Soldner projection from the given parameters.
The descriptor argument is usually org.geotoolkit.referencing.operation.provider.CassiniSoldner#PARAMETERS, but is not restricted to. If a different descriptor is supplied, it is user's responsibility to ensure that it is suitable to a Cassini-Soldner projection.
Parameters
descriptor Typically
CassiniSoldner.PARAMETERS
.
values The parameter values of the projection to create.
Returns
The map projection.
Since
3.00
References CassiniSoldner.CassiniSoldner(), and UnitaryProjection.isSpherical().
Referenced by CassiniSoldner.createMathTransform().
     {
         final CassiniSoldner projection;
         final Parameters parameters = Parameters.castOrWrap(values);
         if (isSpherical(parameters)) {
             projection = new Spherical(descriptor, parameters);
         } else {
             projection = new CassiniSoldner(descriptor, parameters);
         }
         try {
             return (MathTransform2D) projection.createMapProjection(
                     org.apache.sis.internal.system.DefaultFactories.forBuildin(
                             org.opengis.referencing.operation.MathTransformFactory.class));
         } catch (org.opengis.util.FactoryException e) {
             throw new IllegalArgumentException(e); // TODO
         }
     }
dmlfn_dφ()
final double dmlfn_dφ (final double sinφ2, final double cosφ2) package inherited
Gets the derivative of this mlfn(double, double, double) method.
Returns
The derivative at the specified latitude.
Referenced by CassiniSoldner.transform().
{
         return en0 +
                en1 * (sinφ2 -   cosφ2) + sinφ2*(
                en2 * (sinφ2 - 3*cosφ2) + sinφ2*(
                en3 * (sinφ2 - 5*cosφ2) + sinφ2*
                en4 * (    1 - 7*cosφ2)));
     }
dqsfn_dφ()
final double dqsfn_dφ (final double sinφ, final double cosφ) package inherited
Gets the derivative of the qsfn(double) method.
Parameters
sinφ The sine of latitude.
cosφ The cosines of latitude.
Returns
The
qsfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by LambertAzimuthalEqualArea.transform().
{
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         double esinφ2 = eccentricity * sinφ;
         esinφ2 *= esinφ2;
         return (1 - eccentricitySquared) * (cosφ / (1 - esinφ2)) * (1 + ((1 + esinφ2) / (1 - esinφ2)));
     }
dssfn_dφ()
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ) package inherited
Computes the derivative of the ssfn(double, double) method divided by.
ssfn
. Callers must multiply the return value by
ssfn
in order to get the actual value.
Parameters
φ The latitude.
sinφ the sine of latitude.
cosφ The cosine of latitude.
Returns
The
dssfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         assert !(abs(cosφ - cos(φ)) > ARGUMENT_TOLERANCE) : φ;
         return (1/cosφ) - (eccentricitySquared*cosφ)/(1-eccentricitySquared*sinφ*sinφ);
         /*
          * NOTE: 0.5*(t + 1/t)   =   1/cosφ
          */
     }
getAndStore()
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor) package inherited
Referenced by CassiniOrMercator.CassiniOrMercator(), Krovak.Krovak(), LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), NewZealandMapGrid.NewZealandMapGrid(), Orthographic.Orthographic(), and Stereographic.Stereographic().
{
         final double value = parameters.doubleValue(descriptor);    // Apply a unit conversion if needed.
         final Double defaultValue = descriptor.getDefaultValue();
         if (defaultValue == null || !defaultValue.equals(value)) {
             org.apache.sis.internal.referencing.provider.MapProjection.validate(descriptor, value);
             String name = IdentifiedObjects.getName(descriptor, parameters.getDescriptor().getName().getAuthority());
             if (name == null) {
                 name = descriptor.getName().getCode();
             }
             getContextualParameters().parameter(name).setValue(value);
         }
         return value;
     }
inv_mlfn()
final double inv_mlfn (final double delta) throws ProjectionException package inherited
Calculates the latitude (.
φ
) from a meridian distance. Determines φ to a tenth of { ITERATION_TOLERANCE} radians.
Parameters
delta meridian distance to calculate latitude for.
Returns
The latitude of the meridian distance.
Exceptions
ProjectionException if the iteration does not converge.
References Errors.format(), UnitaryProjection.ITERATION_TOLERANCE, UnitaryProjection.MAXIMUM_ITERATIONS, CassiniOrMercator.mlfn(), and Errors.Keys.NoConvergence.
Referenced by CassiniSoldner.inverseTransform().
{
         final double k = 1/(1 - eccentricitySquared);
         double φ = delta;
         int i=MAXIMUM_ITERATIONS;
         do { // rarely goes over 5 iterations
             final double s = sin(φ);
             double t = 1 - eccentricitySquared * (s*s);
             t = (mlfn(φ, s, cos(φ)) - delta) * (t * sqrt(t)) * k;
             φ -= t;
             if (abs(t) < ITERATION_TOLERANCE/10) {
                 return φ;
             }
         } while (--i >= 0);
         throw new ProjectionException(Errors.format(Errors.Keys.NoConvergence));
     }
inverseTransform()
void inverseTransform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff) throws ProjectionException protected
Transforms the specified (x,y) coordinates and stores the result in.
dstPts
(angles in radians).
References CassiniSoldner.C3, CassiniSoldner.C4, CassiniSoldner.C5, and CassiniOrMercator.inv_mlfn().
     {
         final double x  = srcPts[srcOff];
         final double y  = srcPts[srcOff + 1];
         final double φ1 = inv_mlfn(y);
         final double tn = tan(φ1);
         final double t  = tn * tn;
         double n = sin(φ1);
         double r = 1 / (1 - eccentricitySquared * (n*n));
         n = sqrt(r);
         r *= (1 - eccentricitySquared)*n;
         final double dd  = x / n;
         final double d2  = dd*dd;
         dstPts[dstOff  ] = dd*(1 + t*d2*(-C4+(1 + 3*t)*d2*C5)) / cos(φ1);
         dstPts[dstOff+1] = φ1 - (n*tn/r)*d2*(0.5-(1 + 3*t)*d2*C3);
     }
isSpherical()
static boolean isSpherical (final Parameters parameters) static package inherited
References UnitaryProjection.inverseTransform().
Referenced by CassiniSoldner.create(), Stereographic.create(), LambertAzimuthalEqualArea.create(), and LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
{
         return parameters.parameter("semi_major").doubleValue() == parameters.parameter("semi_minor").doubleValue();
     }
mlfn()
final double mlfn (final double φ, double sinφ, double cosφ) package inherited
Calculates the meridian distance.
This is the distance along the central meridian from the equator to
φ
. Accurate to < 1E-5 metres when used in conjuction with typical major axis values.
Special cases:
If φ is 0°, then this method returns 0.
Parameters
φ latitude to calculate meridian distance for.
sinφ sin(φ).
cosφ cos(φ).
Returns
Meridian distance for the given latitude.
References CassiniOrMercator.en4.
Referenced by CassiniOrMercator.CassiniOrMercator(), CassiniOrMercator.inv_mlfn(), and CassiniSoldner.transform().
{
         cosφ *= sinφ;
         sinφ *= sinφ;
         return en0*φ - cosφ*(en1 + sinφ*(en2 + sinφ*(en3 + sinφ*en4)));
     }
msfn()
final double msfn (final double sinφ, final double cosφ) package inherited
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
Special cases:
If φ is 0°, then this method returns 1.
If φ is ±90°, then this method returns 0 provided that we are not in the spherical case (otherwise we get Double#NaN).
Parameters
sinφ The sine of the φ latitude in radians.
cosφ The cosine of the φ latitude in radians.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic().
                                                               {               // == cosφ / rν(sinφ)
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         return cosφ / sqrt(1.0 - (sinφ*sinφ) * eccentricitySquared);
     }
qsfn()
final double qsfn (final double sinφ) package inherited
Calculates q, Snyder equation (3-12).
This equation has the following properties:
Input in the [-1 ... +1] range.
Output in the [-2 ... +2] range.
Output is 0 when input is 0.
Output of the same sign than input.
qsfn(-sinφ) == -qsfn(sinφ)
.
Parameters
sinφ Sine of the latitude q is calculated for.
Returns
q from Snyder equation (3-12).
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.transform().
{
         if (eccentricity < EPSILON) {
             return 2 * sinφ;
         }
         /*
          * Above check was required because the expression below would simplify to
          * sinφ - 0.5/0*log(1) where the right terms are infinity multiplied by
          * zero, thus producing NaN.
          */
         final double esinφ = eccentricity * sinφ;
         return (1 - eccentricitySquared) * (sinφ / (1 - esinφ*esinφ) + atanh(esinφ)/eccentricity);
     }
ssfn()
final double ssfn (double φ, double sinφ) package inherited
Computes part of function (3-1) from Snyder.
This is numerically equivalent to #tsfn tsfn}(-φ, sinφ), but is defined as a separated function for clarity and because the function properties are not the same.
Parameters
φ The latitude in radians.
sinφ The sine of the φ argument. This is provided explicitly because in many cases, the caller has already computed this value.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic(), EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         sinφ *= eccentricity;
         return tan(PI/4 + 0.5*φ) * pow((1-sinφ) / (1+sinφ), 0.5*eccentricity);
     }
transform()
Matrix transform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
Converts the specified (λ,φ) coordinate (units in radians) and stores the result in.
dstPts
(linear distance on a unit sphere). In addition, opportunistically computes the projection derivative if
derivate
is
true
.
Since
3.20 (derived from 3.00)
References CassiniSoldner.C2, CassiniSoldner.C3, CassiniOrMercator.dmlfn_dφ(), CassiniOrMercator.en2, and CassiniOrMercator.mlfn().
     {
         final double λ = srcPts[srcOff];
         final double φ = srcPts[srcOff + 1];
         final double sinφ   = sin(φ);
         final double cosφ   = cos(φ);
         final double tanφ   = sinφ / cosφ;
         final double sinφ2  = sinφ*sinφ;
         final double cosφ2  = cosφ*cosφ;
         final double tanφ2  = tanφ * tanφ;
         final double λcosφ  = λ * cosφ;
         final double λcosφ2 = λcosφ * λcosφ;
         final double rn2    = 1 - eccentricitySquared * sinφ2;
         final double rn     = sqrt(rn2);
         final double c      = cosφ2 * eccentricitySquared / (1 - eccentricitySquared);
         if (dstPts != null) {
             dstPts[dstOff  ] = λcosφ*(1 - λcosφ2*tanφ2*(C1 - (8 - tanφ2 + 8*c)*λcosφ2*C2)) / rn;
             dstPts[dstOff+1] = mlfn(φ, sinφ, cosφ) + tanφ*λcosφ2*(0.5 + (5 - tanφ2 + 6*c)*λcosφ2*C3) / rn;
         }
         if (!derivate) {
             return null;
         }
         //
         // End of map projection. Now compute the derivative.
         //
         final double sincosφ = sinφ*cosφ;
         final double λ2sinφ2 = λ*λ * sinφ2;
         final double λ2cosφ2 = λ*λ * cosφ2;
         final double en2     = eccentricitySquared / rn2;
         final double a = (-C2 * (8*(c + 1) - tanφ2)) * λ2cosφ2;
         final double b = ( C3 * (6* c + 5  - tanφ2)) * λ2cosφ2 + 0.5;
         final double D = ( C1 + a*(1 - tanφ2*(1 - C2*cosφ*(8*c + 1/cosφ2)))) * λ2cosφ2;
         return new Matrix2(
                   (cosφ/rn) * (1 - λ2sinφ2*(5*a + 3*C1)),
                 (λ*sinφ/rn) * (1 - λ2sinφ2*(  a +   C1)) * (en2*cosφ2 - 2*D - 1),
              (λ*sincosφ/rn) * (4*b - 1),
                (λ2cosφ2/rn) * (b*(en2*sinφ2 - 2*tanφ2 + 1/cosφ2) - C3*λ2sinφ2*(24*c + 12)) + dmlfn_dφ(sinφ2, cosφ2));
     }
Member Data Documentation
ANGLE_TOLERANCE
final double ANGLE_TOLERANCE = 1E-6 static package inherited
Maximum difference allowed when comparing longitudes or latitudes in radians.
A tolerance of 1E-6 is about 0.2 second of arcs, which is about 6 kilometers (computed from the standard length of nautical mile).
Some formulas use this tolerance value for testing sinus or cosinus of an angle. In the sinus case, this is justified because sin(θ) ≅ θ when θ is small. Similar reasoning applies to cosinus with cos(θ) ≅ θ + π/2 when θ is small.
Referenced by Stereographic.create(), Orthographic.inverseTransform(), LambertAzimuthalEqualArea.inverseTransform(), Orthographic.Orthographic(), and Stereographic.Stereographic().
ASSERTION_DOMAIN
final double ASSERTION_DOMAIN = 5 * (PI/180) static package inherited
Maximal difference (in radians) from central meridian for enabling assertions.
When assertions are enabled, projections using spherical formulas are followed by projections using the ellipsoidal formulas, and the results are compared. If a distance greater than the tolerance level is found, then an AssertionError will be thrown.
Referenced by CassiniSoldner.Spherical.checkInverseTransform().
C02
final double C02 = 0.25 static package inherited
Referenced by CassiniOrMercator.CassiniOrMercator().
C04
final double C04 = 0.046875 static package inherited
Referenced by CassiniOrMercator.CassiniOrMercator().
C06
final double C06 = 0.01953125 static package inherited
Referenced by CassiniOrMercator.CassiniOrMercator().
C08
final double C08 = 0.01068115234375 static package inherited
Referenced by CassiniOrMercator.CassiniOrMercator().
C1
final double C1 = 0.16666666666666666666 static private
Constants used for the forward and inverse transform for the elliptical case of the Cassini-Soldner.
C2
final double C2 = 0.08333333333333333333 static package
Referenced by CassiniSoldner.transform().
C22
final double C22 = 0.75 static package inherited
Referenced by CassiniOrMercator.CassiniOrMercator().
C3
final double C3 = 0.41666666666666666666 static package
Referenced by CassiniSoldner.inverseTransform(), and CassiniSoldner.transform().
C4
final double C4 = 0.33333333333333333333 static package
Referenced by CassiniSoldner.inverseTransform().
C44
final double C44 = 0.46875 static package inherited
Referenced by CassiniOrMercator.CassiniOrMercator().
C46
final double C46 = 0.01302083333333333333 static package inherited
Referenced by CassiniOrMercator.CassiniOrMercator().
C48
final double C48 = 0.00712076822916666666 static package inherited
Referenced by CassiniOrMercator.CassiniOrMercator().
C5
final double C5 = 0.66666666666666666666 static package
Referenced by CassiniSoldner.inverseTransform().
C66
final double C66 = 0.36458333333333333333 static package inherited
Referenced by CassiniOrMercator.CassiniOrMercator().
C68
final double C68 = 0.00569661458333333333 static package inherited
Referenced by CassiniOrMercator.CassiniOrMercator().
C88
final double C88 = 0.3076171875 static package inherited
Referenced by CassiniOrMercator.CassiniOrMercator().
en1
final double en1 package inherited
en2
final double en2 package inherited
Referenced by CassiniSoldner.transform().
en3
final double en3 package inherited
en4
final double en4 package inherited
Referenced by CassiniOrMercator.mlfn().
EPSILON
final double EPSILON = 1E-7 static package inherited
Maximum difference allowed when comparing real numbers (other cases).
The value defined here is consistent with the one that was used in LambertAzimuthalEqualArea for the same purpose (not to be confused with the current
EPSILON
constant defined in the above-mentioned class, which has been renamed), and the modified value used in AlbersEqualArea.
ITERATION_TOLERANCE
final double ITERATION_TOLERANCE = 1E-10 static package inherited
Difference allowed in iterative computations.
A value of 1E-10 causes the cphi2 function to compute the latitude at a precision of 1E-10 radians, which is slightly smaller than one millimetre.
Referenced by CassiniOrMercator.inv_mlfn(), and Stereographic.inverseTransform().
MAXIMUM_ITERATIONS
final int MAXIMUM_ITERATIONS = 15 static package inherited
Maximum number of iterations for iterative computations.
Referenced by CassiniOrMercator.inv_mlfn(), Stereographic.inverseTransform(), and Krovak.inverseTransform().
serialVersionUID
final long serialVersionUID = 4710150547701615178L static private
For cross-version compatibility.