jena-geo: Stereographic Class Reference
Stereographic Class Reference
<cite>Stereographic</cite> projection using USGS formulas.
Classes
class Spherical
Provides the transform equations for the spherical case of the Stereographic projection.
Public Member Functions
Matrix transform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
Converts the specified (λ,φ) coordinate (units in radians) and stores the result in.
boolean equals (final Object object, final ComparisonMode mode)
Compares the given object with this transform for equivalence.
Static Public Member Functions
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values)
Creates a Stereographic projection from the given parameters.
Protected Member Functions
Stereographic (final OperationMethod method, final Parameters parameters)
Constructs an oblique stereographic projection (USGS equations).
void inverseTransform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff) throws ProjectionException
Transforms the specified (x,y) coordinates and stores the result in.
Package Functions
Stereographic (final OperationMethod method, final Parameters parameters, double latitudeOfOrigin)
Constructs an oblique stereographic projection.
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor)
final double msfn (final double sinφ, final double cosφ)
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
final double ssfn (double φ, double sinφ)
Computes part of function (3-1) from Snyder.
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ)
Computes the derivative of the ssfn(double, double) method divided by.
final double qsfn (final double sinφ)
Calculates q, Snyder equation (3-12).
final double dqsfn_dφ (final double sinφ, final double cosφ)
Gets the derivative of the qsfn(double) method.
Static Package Functions
static boolean isSpherical (final Parameters parameters)
Package Attributes
final double φ0
The latitude of origin, in radians.
final double sinφ0
Constants used for the oblique projections.
final double cosφ0
final double cosχ1
Static Package Attributes
static final double EPSILON = 1E-6
Maximum difference allowed when comparing real numbers.
static final double ANGLE_TOLERANCE = 1E-6
Maximum difference allowed when comparing longitudes or latitudes in radians.
static final double ITERATION_TOLERANCE = 1E-10
Difference allowed in iterative computations.
static final int MAXIMUM_ITERATIONS = 15
Maximum number of iterations for iterative computations.
Private Attributes
final double χ1
Constants computed from the latitude of origin and the eccentricity.
final double sinχ1
Constants used for the oblique projections.
Static Private Attributes
static final long serialVersionUID = 948619442800459872L
For compatibility with different versions during deserialization.
Detailed Description
<cite>Stereographic</cite> projection using USGS formulas.
This is slightly different than the <cite>Oblique Stereographic</cite> provided in Apache SIS, which uses the formulas published in the EPSG guide.
{
}
John P. Snyder (Map Projections - A Working Manual,
U.S. Geological Survey Professional Paper 1395, 1987)
"Coordinate Conversions and Transformations including Formulas",
EPSG Guidance Note Number 7, Version 19.
Gerald Evenden. "Supplementary PROJ.4 Notes - Oblique Stereographic Alternative"
Krakiwsky, E.J., D.B. Thomson, and R.R. Steeves. 1977.
A Manual for Geodetic Coordinate Transformations in the Maritimes.
Geodesy and Geomatics Engineering, UNB. Technical Report No. 48.
Thomson, D.B., M.P. Mepham and R.R. Steeves. 1977.
The Stereographic Double Projection.
Geodesy and Geomatics Engineereng, UNB. Technical Report No. 46.
Author
Gerald Evenden (USGS)
André Gosselin (MPO)
Martin Desruisseaux (MPO, IRD, Geomatys)
Rueben Schulz (UBC)
Rémi Maréchal (Geomatys)
See also
Some Random Stereographic Issues
Constructor & Destructor Documentation
Stereographic() [1/2]
Stereographic (final OperationMethod method, final Parameters parameters) protected
Constructs an oblique stereographic projection (USGS equations).
Parameters
parameters The parameters of the projection to be created.
References Stereographic.cosχ1, and UnitaryProjection.msfn().
Referenced by Stereographic.create(), and Stereographic.equals().
{
         this(method, parameters, Double.NaN);
         double k0 = 2*msfn(sinφ0, cosφ0) / cosχ1;   // part of (14 - 15)
         if (eccentricity == 0) {
             k0 = 2; // For fixing rounding errors.
         }
         /*
          * k0 above should be equal to 2 in both the spherical and equatorial cases
          * (but the simplification happen through different paths).
          *
          * At this point, all parameters have been processed. Now process to their
          * validation and the initialization of (de)normalize affine transforms.
          */
         getContextualParameters().getMatrix(MatrixRole.DENORMALIZATION).convertBefore(0, k0, null);
         getContextualParameters().getMatrix(MatrixRole.DENORMALIZATION).convertBefore(1, k0, null);
     }
Stereographic() [2/2]
Stereographic (final OperationMethod method, final Parameters parameters, double latitudeOfOrigin) package
Constructs an oblique stereographic projection.
Parameters
parameters The parameters of the projection to be created.
latitudeOfOrigin the latitude of origin, in decimal degrees.
References UnitaryProjection.ANGLE_TOLERANCE, UnitaryProjection.getAndStore(), Stereographic.LATITUDE_OF_ORIGIN, and UnitaryProjection.ssfn().
{
         super(method, parameters, null);
         if (Double.isNaN(latitudeOfOrigin)) {
             latitudeOfOrigin = getAndStore(parameters, org.geotoolkit.referencing.operation.provider.Stereographic.LATITUDE_OF_ORIGIN);
         }
         double phi0 = toRadians(latitudeOfOrigin);
         if (abs(phi0) < ANGLE_TOLERANCE) { // Equatorial
             phi0    = 0;
             cosφ0 = 1;
             sinφ0 = 0;
             χ1    = 0;
             cosχ1 = 1;
             sinχ1 = 0;
         } else {  // Oblique
             cosφ0 = cos(phi0);
             sinφ0 = sin(phi0);
             χ1    = 2 * atan(ssfn(phi0, sinφ0)) - PI/2;
             cosχ1 = cos(χ1);
             sinχ1 = sin(χ1);
         }
         this.φ0 = phi0;
     }
Member Function Documentation
create()
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values) static
Creates a Stereographic projection from the given parameters.
The descriptor argument is usually org.geotoolkit.referencing.operation.provider.Stereographic#PARAMETERS, but is not restricted to. If a different descriptor is supplied, it is user's responsibility to ensure that it is suitable to a Stereographic projection.
Parameters
descriptor Typically
Stereographic.PARAMETERS
.
values The parameter values of the projection to create.
Returns
The map projection.
References UnitaryProjection.ANGLE_TOLERANCE, UnitaryProjection.isSpherical(), Stereographic.LATITUDE_OF_ORIGIN, and Stereographic.Stereographic().
Referenced by Stereographic.createMathTransform().
     {
         final Parameters parameters = Parameters.castOrWrap(values);
         final double latitudeOfOrigin = toRadians(parameters.doubleValue(org.geotoolkit.referencing.operation.provider.Stereographic.LATITUDE_OF_ORIGIN));
         final DefaultMathTransformFactory factory = DefaultFactories.forBuildin(MathTransformFactory.class, DefaultMathTransformFactory.class);
         try {
             final NormalizedProjection projection;
             if (abs(latitudeOfOrigin - PI/2) < ANGLE_TOLERANCE) {
                 projection = new PolarStereographic(factory.getOperationMethod(PolarStereographicA.NAME), parameters);
             } else {
                 final boolean isSpherical = isSpherical(parameters);
                 if (abs(latitudeOfOrigin) < ANGLE_TOLERANCE) {
                     if (isSpherical) {
                         projection = new EquatorialStereographic.Spherical(descriptor, parameters);
                     } else {
                         projection = new EquatorialStereographic(descriptor, parameters);
                     }
                 } else if (isSpherical) {
                     projection = new Stereographic.Spherical(descriptor, parameters);
                 } else {
                     projection = new Stereographic(descriptor, parameters);
                 }
             }
             return (MathTransform2D) projection.createMapProjection(factory);
         } catch (FactoryException e) {
             throw new IllegalArgumentException(e); // TODO
         }
     }
dqsfn_dφ()
final double dqsfn_dφ (final double sinφ, final double cosφ) package inherited
Gets the derivative of the qsfn(double) method.
Parameters
sinφ The sine of latitude.
cosφ The cosines of latitude.
Returns
The
qsfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by LambertAzimuthalEqualArea.transform().
{
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         double esinφ2 = eccentricity * sinφ;
         esinφ2 *= esinφ2;
         return (1 - eccentricitySquared) * (cosφ / (1 - esinφ2)) * (1 + ((1 + esinφ2) / (1 - esinφ2)));
     }
dssfn_dφ()
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ) package inherited
Computes the derivative of the ssfn(double, double) method divided by.
ssfn
. Callers must multiply the return value by
ssfn
in order to get the actual value.
Parameters
φ The latitude.
sinφ the sine of latitude.
cosφ The cosine of latitude.
Returns
The
dssfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         assert !(abs(cosφ - cos(φ)) > ARGUMENT_TOLERANCE) : φ;
         return (1/cosφ) - (eccentricitySquared*cosφ)/(1-eccentricitySquared*sinφ*sinφ);
         /*
          * NOTE: 0.5*(t + 1/t)   =   1/cosφ
          */
     }
equals()
boolean equals (final Object object, final ComparisonMode mode)
Compares the given object with this transform for equivalence.
References Stereographic.Stereographic(), and Stereographic.φ0.
{
         if (super.equals(object, mode)) {
             final Stereographic that = (Stereographic) object;
             return epsilonEqual(this.φ0, that.φ0, mode);
             // All other fields are derived from the latitude of origin.
         }
         return false;
     }
getAndStore()
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor) package inherited
Referenced by CassiniOrMercator.CassiniOrMercator(), Krovak.Krovak(), LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), NewZealandMapGrid.NewZealandMapGrid(), Orthographic.Orthographic(), and Stereographic.Stereographic().
{
         final double value = parameters.doubleValue(descriptor);    // Apply a unit conversion if needed.
         final Double defaultValue = descriptor.getDefaultValue();
         if (defaultValue == null || !defaultValue.equals(value)) {
             org.apache.sis.internal.referencing.provider.MapProjection.validate(descriptor, value);
             String name = IdentifiedObjects.getName(descriptor, parameters.getDescriptor().getName().getAuthority());
             if (name == null) {
                 name = descriptor.getName().getCode();
             }
             getContextualParameters().parameter(name).setValue(value);
         }
         return value;
     }
inverseTransform()
void inverseTransform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff) throws ProjectionException protected
Transforms the specified (x,y) coordinates and stores the result in.
dstPts
(angles in radians).
References Stereographic.EPSILON, Errors.format(), UnitaryProjection.ITERATION_TOLERANCE, UnitaryProjection.MAXIMUM_ITERATIONS, and Errors.Keys.NoConvergence.
     {
         /*
          * (x,y) is multiplied by (cosχ1 / k0), so ρ below is multiplied by the same factor
          * compared to Proj4 code. This allow a few simplifications in the formulas. For example
          * in the computation of ce: atan2(ρ*cosχ1, k0)
          * simplifies to:            atan(ρ).
          */
         final double x = srcPts[srcOff  ];
         final double y = srcPts[srcOff+1];
         final double ρ = hypot(x, y);
         final double ce    = 2 * atan(ρ);
         final double cosce = cos(ce);
         final double since = sin(ce);
         final double χ   = (ρ < EPSILON) ? χ1 : asin(cosce*sinχ1 + (y*since*cosχ1 / ρ));
         final double tp    = tan(PI/4 + 0.5*χ);
         // parts of (21-36) used to calculate longitude
         final double t  = x*since;
         final double ct = ρ*cosχ1*cosce - y*sinχ1*since;
         // Compute latitude using iterative technique (3-4)
         final double halfe = 0.5*eccentricity;
         double φ = χ;
         for (int i=MAXIMUM_ITERATIONS;;) {
             final double esinφ = eccentricity * sin(φ);
             final double next = 2*atan(tp*pow((1+esinφ)/(1-esinφ), halfe)) - PI/2;
             if (abs(φ - (φ=next)) < ITERATION_TOLERANCE) {
                 break;
             }
             if (--i < 0) {
                 throw new ProjectionException(Errors.format(Errors.Keys.NoConvergence));
             }
         }
         dstPts[dstOff  ] = atan2(t, ct);
         dstPts[dstOff+1] = φ;
     }
isSpherical()
static boolean isSpherical (final Parameters parameters) static package inherited
References UnitaryProjection.inverseTransform().
Referenced by CassiniSoldner.create(), Stereographic.create(), LambertAzimuthalEqualArea.create(), and LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
{
         return parameters.parameter("semi_major").doubleValue() == parameters.parameter("semi_minor").doubleValue();
     }
msfn()
final double msfn (final double sinφ, final double cosφ) package inherited
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
Special cases:
If φ is 0°, then this method returns 1.
If φ is ±90°, then this method returns 0 provided that we are not in the spherical case (otherwise we get Double#NaN).
Parameters
sinφ The sine of the φ latitude in radians.
cosφ The cosine of the φ latitude in radians.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic().
                                                               {               // == cosφ / rν(sinφ)
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         return cosφ / sqrt(1.0 - (sinφ*sinφ) * eccentricitySquared);
     }
qsfn()
final double qsfn (final double sinφ) package inherited
Calculates q, Snyder equation (3-12).
This equation has the following properties:
Input in the [-1 ... +1] range.
Output in the [-2 ... +2] range.
Output is 0 when input is 0.
Output of the same sign than input.
qsfn(-sinφ) == -qsfn(sinφ)
.
Parameters
sinφ Sine of the latitude q is calculated for.
Returns
q from Snyder equation (3-12).
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.transform().
{
         if (eccentricity < EPSILON) {
             return 2 * sinφ;
         }
         /*
          * Above check was required because the expression below would simplify to
          * sinφ - 0.5/0*log(1) where the right terms are infinity multiplied by
          * zero, thus producing NaN.
          */
         final double esinφ = eccentricity * sinφ;
         return (1 - eccentricitySquared) * (sinφ / (1 - esinφ*esinφ) + atanh(esinφ)/eccentricity);
     }
ssfn()
final double ssfn (double φ, double sinφ) package inherited
Computes part of function (3-1) from Snyder.
This is numerically equivalent to #tsfn tsfn}(-φ, sinφ), but is defined as a separated function for clarity and because the function properties are not the same.
Parameters
φ The latitude in radians.
sinφ The sine of the φ argument. This is provided explicitly because in many cases, the caller has already computed this value.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic(), EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         sinφ *= eccentricity;
         return tan(PI/4 + 0.5*φ) * pow((1-sinφ) / (1+sinφ), 0.5*eccentricity);
     }
transform()
Matrix transform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
Converts the specified (λ,φ) coordinate (units in radians) and stores the result in.
dstPts
(linear distance on a unit sphere). In addition, opportunistically computes the projection derivative if
derivate
is
true
.
Since
3.20 (derived from 3.00)
References Stereographic.cosχ1, UnitaryProjection.dssfn_dφ(), Stereographic.sinχ1, and UnitaryProjection.ssfn().
     {
         final double λ    = srcPts[srcOff];
         final double φ    = srcPts[srcOff + 1];
         final double sinφ = sin(φ);
         final double sinλ = sin(λ);
         final double cosλ = cos(λ);
         final double ssfn = ssfn(φ, sinφ);
         if (dstPts != null) {
             final double χ    = 2*atan(ssfn) - PI/2;
             final double sinχ = sin(χ);
             final double cosχ = cos(χ);
             final double cosχ_cosλ = cosχ * cosλ;
             final double A = 1 + sinχ1*sinχ + cosχ1*cosχ_cosλ;
             dstPts[dstOff  ] = (cosχ * sinλ) / A;
             dstPts[dstOff+1] = (cosχ1 * sinχ - sinχ1 * cosχ_cosλ) / A;
         }
         /*
          * The multiplication by (k0 / cosχ1) is performed by the "denormalize" affine transform.
          */
         if (!derivate) {
             return null;
         }
         //
         // End of map projection. Now compute the derivative.
         //
         final double cosφ = cos(φ);
         final double sd   = ssfn - 1/ssfn;
         final double s2p  = 1 + ssfn*ssfn;
         final double dχφ  = 2*dssfn_dφ(φ, sinφ, cosφ) * ssfn;
         final double A    = s2p/ssfn + sd*sinχ1 + 2*cosλ*cosχ1;
         final double dAλ  = -2*cosχ1*sinλ / A; // The "/A" is actually not part of the derivative.
         final double dAφ  = (2*sinχ1 - sd*cosλ*cosχ1) / (s2p*A); // Same as above comment.
         final double d    = (cosχ1*sd - 2*cosλ*sinχ1);
         return new Matrix2(
                 2*(cosλ - sinλ*dAλ) / A,
                 -sinλ*dχφ * (sd/s2p + 2*dAφ) / A,
                 (2*sinλ*sinχ1 - dAλ*d) / A,
                 dχφ * ((2*cosχ1 + sinχ1*cosλ*sd)/s2p - dAφ*d) / A);
     }
Member Data Documentation
ANGLE_TOLERANCE
final double ANGLE_TOLERANCE = 1E-6 static package inherited
Maximum difference allowed when comparing longitudes or latitudes in radians.
A tolerance of 1E-6 is about 0.2 second of arcs, which is about 6 kilometers (computed from the standard length of nautical mile).
Some formulas use this tolerance value for testing sinus or cosinus of an angle. In the sinus case, this is justified because sin(θ) ≅ θ when θ is small. Similar reasoning applies to cosinus with cos(θ) ≅ θ + π/2 when θ is small.
Referenced by Stereographic.create(), Orthographic.inverseTransform(), LambertAzimuthalEqualArea.inverseTransform(), Orthographic.Orthographic(), and Stereographic.Stereographic().
cosφ0
final double cosφ0 package
cosχ1
final double cosχ1 package
Referenced by Stereographic.Stereographic(), and Stereographic.transform().
EPSILON
final double EPSILON = 1E-6 static package
Maximum difference allowed when comparing real numbers.
Referenced by EquatorialStereographic.Spherical.inverseTransform(), and Stereographic.inverseTransform().
ITERATION_TOLERANCE
final double ITERATION_TOLERANCE = 1E-10 static package inherited
Difference allowed in iterative computations.
A value of 1E-10 causes the cphi2 function to compute the latitude at a precision of 1E-10 radians, which is slightly smaller than one millimetre.
Referenced by CassiniOrMercator.inv_mlfn(), and Stereographic.inverseTransform().
MAXIMUM_ITERATIONS
final int MAXIMUM_ITERATIONS = 15 static package inherited
Maximum number of iterations for iterative computations.
Referenced by CassiniOrMercator.inv_mlfn(), Stereographic.inverseTransform(), and Krovak.inverseTransform().
serialVersionUID
final long serialVersionUID = 948619442800459872L static private
For compatibility with different versions during deserialization.
sinφ0
final double sinφ0 package
Constants used for the oblique projections.
All those constants are completely determined by φ0. Consequently, there is no need to test them in hashCode or equals(Object, ComparisonMode) methods.
sinχ1
final double sinχ1 private
Constants used for the oblique projections.
All those constants are completely determined by φ0 and eccentricity. Consequently, there is no need to test them in hashCode or equals(Object, ComparisonMode) methods.
Referenced by Stereographic.transform().
φ0
final double φ0 package
The latitude of origin, in radians.
Referenced by Stereographic.equals(), EquatorialStereographic.EquatorialStereographic(), and Stereographic.Spherical.inverseTransform().
χ1
final double χ1 private
Constants computed from the latitude of origin and the eccentricity.
It is equal to φ0 in the spherical and equatorial case.