jena-geo: Orthographic Class Reference
Orthographic Class Reference
<cite>Orthographic</cite> projection.
Public Member Functions
ParameterDescriptorGroup getParameterDescriptors ()
Returns the parameter descriptors for this unitary projection.
Matrix transform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
Converts the specified (λ,φ) coordinate (units in radians) and stores the result in.
boolean equals (final Object object, final ComparisonMode mode)
Compares the given object with this transform for equivalence.
Static Public Member Functions
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values)
Creates an Orthographic projection from the given parameters.
Protected Member Functions
Orthographic (final OperationMethod method, final Parameters parameters)
Constructs a new map projection from the supplied parameters.
void inverseTransform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff) throws ProjectionException
Transforms the specified (x,y) coordinates and stores the result in.
Package Functions
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor)
final double msfn (final double sinφ, final double cosφ)
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
final double ssfn (double φ, double sinφ)
Computes part of function (3-1) from Snyder.
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ)
Computes the derivative of the ssfn(double, double) method divided by.
final double qsfn (final double sinφ)
Calculates q, Snyder equation (3-12).
final double dqsfn_dφ (final double sinφ, final double cosφ)
Gets the derivative of the qsfn(double) method.
Static Package Functions
static boolean isSpherical (final Parameters parameters)
Static Package Attributes
static final double ANGLE_TOLERANCE = 1E-6
Maximum difference allowed when comparing longitudes or latitudes in radians.
static final double ITERATION_TOLERANCE = 1E-10
Difference allowed in iterative computations.
static final int MAXIMUM_ITERATIONS = 15
Maximum number of iterations for iterative computations.
Private Attributes
final byte type
0 if equatorial, 1 if polar, any other value if oblique.
final double latitudeOfOrigin
The latitude of origin, in radians.
final double sinφ0
The sine of the latitudeOfOrigin.
final double cosφ0
The cosine of the latitudeOfOrigin.
Static Private Attributes
static final long serialVersionUID = 5036668705538661687L
For compatibility with different versions during deserialization.
static final double EPSILON = 1E-6
Maximum difference allowed when comparing real numbers.
Detailed Description
<cite>Orthographic</cite> projection.
See the Orthographic projection on MathWorld for an overview. See any of the following providers for a list of programmatic parameters:
org.geotoolkit.referencing.operation.provider.Orthographic
{
}
This is a perspective azimuthal (planar) projection that is neither conformal nor equal-area. It resembles a globe and only one hemisphere can be seen at a time, since it is a perspective projection from infinite distance. While not useful for accurate measurements, this projection is useful for pictorial views of the world. Only the spherical form is given here.
{
}
Proj-4.4.7 available at www.remotesensing.org/proj.
Relevant files are:
PJ_ortho.c
,
pj_fwd.c
and
pj_inv.c
.
John P. Snyder (Map Projections - A Working Manual,
U.S. Geological Survey Professional Paper 1395, 1987)
Author
Rueben Schulz (UBC)
Martin Desruisseaux (Geomatys)
Rémi Maréchal (Geomatys)
Since
2.0
Constructor & Destructor Documentation
Orthographic()
Orthographic (final OperationMethod method, final Parameters parameters) protected
Constructs a new map projection from the supplied parameters.
Parameters
parameters The parameters of the projection to be created.
References UnitaryProjection.ANGLE_TOLERANCE, UnitaryProjection.getAndStore(), Orthographic.LATITUDE_OF_CENTRE, and Orthographic.latitudeOfOrigin.
Referenced by Orthographic.create(), and Orthographic.equals().
{
         super(method, parameters, null);
         double latitudeOfOrigin = toRadians(getAndStore(parameters, org.geotoolkit.referencing.operation.provider.Orthographic.LATITUDE_OF_CENTRE));
         boolean north = false;
         boolean south = false;
         /*
          * Detect the special cases (equatorial or polar). In the polar case, we use the
          * same formulas for the North pole than the ones for the South pole, with only
          * the sign of y reversed.
          */
         if (abs(abs(latitudeOfOrigin) - PI/2) <= ANGLE_TOLERANCE) {
             // Polar case. The latitude of origin must be set to a positive value even for the
             // South case because the "normalize" affine transform will reverse the sign of φ.
             if (latitudeOfOrigin >= 0) {
                 north = true;
             } else {
                 south = true;
             }
             latitudeOfOrigin = PI/2;
             type = 1;
         } else if (latitudeOfOrigin == 0) {
             type = 0; // Equatorial case
         } else {
             type = 2; // Oblique case.
         }
         this.latitudeOfOrigin = latitudeOfOrigin;
         sinφ0 = sin(latitudeOfOrigin);
         cosφ0 = cos(latitudeOfOrigin);
         /*
          * At this point, all parameters have been processed. Now process to their
          * validation and the initialization of (de)normalize affine transforms.
          */
         if (south) {
             getContextualParameters().getMatrix(MatrixRole.NORMALIZATION).convertAfter(1, -1, null);
         }
         final MatrixSIS denormalize = getContextualParameters().getMatrix(MatrixRole.DENORMALIZATION);
         if (eccentricity != 0) {
             /*
              * In principle the elliptical case is not supported. If nevertheless the user gave
              * an ellipsoid, use the same Earth radius than the one computed in Equirectangular.
              */
             double p = sin(abs(latitudeOfOrigin));
             p = sqrt(1 - eccentricitySquared) / (1 - (p*p)*eccentricitySquared); // TODO: radiusOfConformanceSphere.
             denormalize.convertBefore(0, p, null);
             denormalize.convertBefore(1, p, null);
         }
         if (north) {
             denormalize.convertBefore(1, -1, null);
         }
     }
Member Function Documentation
create()
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values) static
Creates an Orthographic projection from the given parameters.
The descriptor argument is usually org.geotoolkit.referencing.operation.provider.Orthographic#PARAMETERS, but is not restricted to. If a different descriptor is supplied, it is user's responsibility to ensure that it is suitable to an Orthographic projection.
Parameters
descriptor Typically
Orthographic.PARAMETERS
.
values The parameter values of the projection to create.
Returns
The map projection.
Since
3.00
References Orthographic.Orthographic().
Referenced by Orthographic.createMathTransform().
     {
         final Parameters parameters = Parameters.castOrWrap(values);
         final Orthographic projection = new Orthographic(descriptor, parameters);
         try {
             return (MathTransform2D) projection.createMapProjection(
                     org.apache.sis.internal.system.DefaultFactories.forBuildin(
                             org.opengis.referencing.operation.MathTransformFactory.class));
         } catch (org.opengis.util.FactoryException e) {
             throw new IllegalArgumentException(e); // TODO
         }
     }
dqsfn_dφ()
final double dqsfn_dφ (final double sinφ, final double cosφ) package inherited
Gets the derivative of the qsfn(double) method.
Parameters
sinφ The sine of latitude.
cosφ The cosines of latitude.
Returns
The
qsfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by LambertAzimuthalEqualArea.transform().
{
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         double esinφ2 = eccentricity * sinφ;
         esinφ2 *= esinφ2;
         return (1 - eccentricitySquared) * (cosφ / (1 - esinφ2)) * (1 + ((1 + esinφ2) / (1 - esinφ2)));
     }
dssfn_dφ()
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ) package inherited
Computes the derivative of the ssfn(double, double) method divided by.
ssfn
. Callers must multiply the return value by
ssfn
in order to get the actual value.
Parameters
φ The latitude.
sinφ the sine of latitude.
cosφ The cosine of latitude.
Returns
The
dssfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         assert !(abs(cosφ - cos(φ)) > ARGUMENT_TOLERANCE) : φ;
         return (1/cosφ) - (eccentricitySquared*cosφ)/(1-eccentricitySquared*sinφ*sinφ);
         /*
          * NOTE: 0.5*(t + 1/t)   =   1/cosφ
          */
     }
equals()
boolean equals (final Object object, final ComparisonMode mode)
Compares the given object with this transform for equivalence.
References Orthographic.latitudeOfOrigin, and Orthographic.Orthographic().
{
         if (super.equals(object, mode)) {
             final Orthographic that = (Orthographic) object;
             return epsilonEqual(latitudeOfOrigin, that.latitudeOfOrigin, mode);
             // All other fields are derived from the latitude of origin.
         }
         return false;
     }
getAndStore()
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor) package inherited
Referenced by CassiniOrMercator.CassiniOrMercator(), Krovak.Krovak(), LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), NewZealandMapGrid.NewZealandMapGrid(), Orthographic.Orthographic(), and Stereographic.Stereographic().
{
         final double value = parameters.doubleValue(descriptor);    // Apply a unit conversion if needed.
         final Double defaultValue = descriptor.getDefaultValue();
         if (defaultValue == null || !defaultValue.equals(value)) {
             org.apache.sis.internal.referencing.provider.MapProjection.validate(descriptor, value);
             String name = IdentifiedObjects.getName(descriptor, parameters.getDescriptor().getName().getAuthority());
             if (name == null) {
                 name = descriptor.getName().getCode();
             }
             getContextualParameters().parameter(name).setValue(value);
         }
         return value;
     }
getParameterDescriptors()
ParameterDescriptorGroup getParameterDescriptors ()
Returns the parameter descriptors for this unitary projection.
Note that the returned descriptor is about the unitary projection, not the full one.
References Orthographic.PARAMETERS.
{
         return org.geotoolkit.referencing.operation.provider.Orthographic.PARAMETERS;
     }
inverseTransform()
void inverseTransform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff) throws ProjectionException protected
Transforms the specified (x,y) coordinates and stores the result in.
dstPts
(angles in radians).
References UnitaryProjection.ANGLE_TOLERANCE, Orthographic.cosφ0, Orthographic.latitudeOfOrigin, and Orthographic.sinφ0.
     {
         double x = srcPts[srcOff  ];
         double y = srcPts[srcOff+1];
         final double ρ = hypot(x, y);
         double sinc = ρ;
         if (sinc > 1) {
             if (sinc - 1 > ANGLE_TOLERANCE) {
                 dstPts[dstOff  ] = Double.NaN;
                 dstPts[dstOff+1] = Double.NaN;
                 return;
             }
             sinc = 1;
         }
         double φ;
         if (ρ <= EPSILON) {
             φ = latitudeOfOrigin;
             x = 0;
         } else {
             if (type != 1) {
                 final double cosc = sqrt(1 - sinc * sinc);
                 if (type != 0) {
                     // Oblique case
                     φ = (cosc * sinφ0) + (y * sinc * cosφ0 / ρ);
                     x  *= sinc * cosφ0;
                     y   = (cosc - sinφ0 * φ) * ρ; // equivalent to part of (20-15)
                 } else {
                     // Equatorial case
                     φ = y * sinc / ρ;
                     x  *= sinc;
                     y   = cosc * ρ;
                 }
                 φ = (abs(φ) >= 1) ? copySign(PI/2, φ) : asin(φ);
             } else {
                 // South pole case, applicable to North case because of (de)normalize transforms.
                 φ = acos(sinc); // equivalent to asin(cos(c)) over the range [0:1]
             }
             x = atan2(x, y);
         }
         dstPts[dstOff  ] = x;
         dstPts[dstOff+1] = φ;
     }
isSpherical()
static boolean isSpherical (final Parameters parameters) static package inherited
References UnitaryProjection.inverseTransform().
Referenced by CassiniSoldner.create(), Stereographic.create(), LambertAzimuthalEqualArea.create(), and LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
{
         return parameters.parameter("semi_major").doubleValue() == parameters.parameter("semi_minor").doubleValue();
     }
msfn()
final double msfn (final double sinφ, final double cosφ) package inherited
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
Special cases:
If φ is 0°, then this method returns 1.
If φ is ±90°, then this method returns 0 provided that we are not in the spherical case (otherwise we get Double#NaN).
Parameters
sinφ The sine of the φ latitude in radians.
cosφ The cosine of the φ latitude in radians.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic().
                                                               {               // == cosφ / rν(sinφ)
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         return cosφ / sqrt(1.0 - (sinφ*sinφ) * eccentricitySquared);
     }
qsfn()
final double qsfn (final double sinφ) package inherited
Calculates q, Snyder equation (3-12).
This equation has the following properties:
Input in the [-1 ... +1] range.
Output in the [-2 ... +2] range.
Output is 0 when input is 0.
Output of the same sign than input.
qsfn(-sinφ) == -qsfn(sinφ)
.
Parameters
sinφ Sine of the latitude q is calculated for.
Returns
q from Snyder equation (3-12).
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.transform().
{
         if (eccentricity < EPSILON) {
             return 2 * sinφ;
         }
         /*
          * Above check was required because the expression below would simplify to
          * sinφ - 0.5/0*log(1) where the right terms are infinity multiplied by
          * zero, thus producing NaN.
          */
         final double esinφ = eccentricity * sinφ;
         return (1 - eccentricitySquared) * (sinφ / (1 - esinφ*esinφ) + atanh(esinφ)/eccentricity);
     }
ssfn()
final double ssfn (double φ, double sinφ) package inherited
Computes part of function (3-1) from Snyder.
This is numerically equivalent to #tsfn tsfn}(-φ, sinφ), but is defined as a separated function for clarity and because the function properties are not the same.
Parameters
φ The latitude in radians.
sinφ The sine of the φ argument. This is provided explicitly because in many cases, the caller has already computed this value.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic(), EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         sinφ *= eccentricity;
         return tan(PI/4 + 0.5*φ) * pow((1-sinφ) / (1+sinφ), 0.5*eccentricity);
     }
transform()
Matrix transform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
Converts the specified (λ,φ) coordinate (units in radians) and stores the result in.
dstPts
(linear distance on a unit sphere). In addition, opportunistically computes the projection derivative if
derivate
is
true
.
Since
3.20 (derived from 3.00)
References Errors.format(), and Errors.Keys.PointOutsideHemisphere.
     {
         final double λ = srcPts[srcOff];
         final double φ = srcPts[srcOff + 1];
         if (Math.abs(φ-latitudeOfOrigin) > (Math.PI/2.0)) {
             if (derivate) {
                 throw new ProjectionException(Errors.format(Errors.Keys.PointOutsideHemisphere));
             } else {
                 dstPts[dstOff  ] = Double.NaN;
                 dstPts[dstOff+1] = Double.NaN;
                 return null;
             }
         }
         final double cosφ = cos(φ);
         final double cosλ = cos(λ);
         final double sinλ = sin(λ);
         final double threshold, y;
         switch (type) {
             default: { // Oblique
                 final double sinφ = sin(φ);
                 threshold = sinφ0*sinφ + cosφ0*cosφ*cosλ;
                 y = cosφ0*sinφ - sinφ0*cosφ*cosλ;
                 break;
             }
             case 0: { // Equatorial
                 threshold = cosφ * cosλ;
                 y = sin(φ);
                 break;
             }
             case 1: { // Polar (South case, applicable to North because of (de)normalize transforms)
                 threshold = φ;
                 y = cosφ * cosλ;
                 break;
             }
         }
         if (threshold < -EPSILON) {
             if (derivate) {
                 throw new ProjectionException(Errors.format(Errors.Keys.PointOutsideHemisphere));
             } else {
                 dstPts[dstOff  ] = Double.NaN;
                 dstPts[dstOff+1] = Double.NaN;
                 return null;
             }
         }
         if (dstPts != null) {
             dstPts[dstOff  ] = cosφ * sinλ;
             dstPts[dstOff+1] = y;
         }
         if (!derivate) {
             return null;
         }
         //
         // End of map projection. Now compute the derivative.
         //
         final double m00, m01, m10, m11;
         final double sinφ = sin(φ);
         m00 =  cosφ * cosλ;
         m01 = -sinφ * sinλ;
         switch (type) {
             default: { // Oblique
                 m10 = sinφ0 * cosφ * sinλ;
                 m11 = cosφ0 * cosφ + sinφ0*cosλ*sinφ;
                 break;
             }
             case 0: { // Equatorial
                 m10 = 0;
                 m11 = cosφ;
                 break;
             }
             case 1: { // Polar (South case, applicable to North because of (de)normalize transforms)
                 m10 = -cosφ * sinλ;
                 m11 = -sinφ * cosλ;
                 break;
             }
         }
         return new Matrix2(m00, m01, m10, m11);
     }
Member Data Documentation
ANGLE_TOLERANCE
final double ANGLE_TOLERANCE = 1E-6 static package inherited
Maximum difference allowed when comparing longitudes or latitudes in radians.
A tolerance of 1E-6 is about 0.2 second of arcs, which is about 6 kilometers (computed from the standard length of nautical mile).
Some formulas use this tolerance value for testing sinus or cosinus of an angle. In the sinus case, this is justified because sin(θ) ≅ θ when θ is small. Similar reasoning applies to cosinus with cos(θ) ≅ θ + π/2 when θ is small.
Referenced by Stereographic.create(), Orthographic.inverseTransform(), LambertAzimuthalEqualArea.inverseTransform(), Orthographic.Orthographic(), and Stereographic.Stereographic().
cosφ0
final double cosφ0 private
The cosine of the latitudeOfOrigin.
Referenced by Orthographic.inverseTransform().
EPSILON
final double EPSILON = 1E-6 static private
Maximum difference allowed when comparing real numbers.
ITERATION_TOLERANCE
final double ITERATION_TOLERANCE = 1E-10 static package inherited
Difference allowed in iterative computations.
A value of 1E-10 causes the cphi2 function to compute the latitude at a precision of 1E-10 radians, which is slightly smaller than one millimetre.
Referenced by CassiniOrMercator.inv_mlfn(), and Stereographic.inverseTransform().
latitudeOfOrigin
final double latitudeOfOrigin private
The latitude of origin, in radians.
Referenced by Orthographic.equals(), Orthographic.inverseTransform(), and Orthographic.Orthographic().
MAXIMUM_ITERATIONS
final int MAXIMUM_ITERATIONS = 15 static package inherited
Maximum number of iterations for iterative computations.
Referenced by CassiniOrMercator.inv_mlfn(), Stereographic.inverseTransform(), and Krovak.inverseTransform().
serialVersionUID
final long serialVersionUID = 5036668705538661687L static private
For compatibility with different versions during deserialization.
sinφ0
final double sinφ0 private
The sine of the latitudeOfOrigin.
Referenced by Orthographic.inverseTransform().
type
final byte type private
0 if equatorial, 1 if polar, any other value if oblique.
In the equatorial case, latitudeOfOrigin is zero, sinφ0 is zero and cosφ0 is one.