jena-geo: DirectPostgisFactory Class Reference
DirectPostgisFactory Class Reference
An authority factory creating CRS from the { TABLE} table in a spatial SQL database.
Public Member Functions
DirectPostgisFactory (final Connection connection) throws SQLException
Creates a factory using the given connection.
String getBackingStoreDescription () throws FactoryException
Returns a description of the underlying backing store.
Citation getPrimaryKeyAuthority ()
Returns the authority which is responsible for the maintenance of the primary keys.
synchronized Set< String > getAuthorityCodes (final Class<? extends IdentifiedObject > category) throws FactoryException
Returns the authority codes defined in the database for the given type.
synchronized Integer getPrimaryKey (final Class<? extends IdentifiedObject > type, String code) throws NoSuchAuthorityCodeException, FactoryException
Returns the primary key for the specified authority code.
synchronized Citation getAuthority ()
Returns the authority.
InternationalString getDescriptionText (final String code) throws NoSuchAuthorityCodeException, FactoryException
Gets a description of the object corresponding to a code.
synchronized IdentifiedObject createObject (final String code) throws NoSuchAuthorityCodeException, FactoryException
Returns an arbitrary object from a code.
synchronized CoordinateReferenceSystem createCoordinateReferenceSystem (final String code) throws NoSuchAuthorityCodeException, FactoryException
Returns a coordinate reference system from a code.
Citation getVendor ()
Returns the vendor responsible for creating this factory implementation.
Static Public Attributes
static final String TABLE = "spatial_ref_sys"
The standard name of the table containing CRS definitions, which is {}.
static final String PRIMARY_KEY = "srid"
The primary key column, which is {}.
static final String AUTHORITY_COLUMN = "auth_name"
The standard name ({}) of the column containing the authority names.
static final String CODE_COLUMN = "auth_srid"
The standard name ({}) of the column containing the authority codes.
static final String WKT_COLUMN = "srtext"
The standard name ({}) of the column containing the WKT definitions.
static final Logger LOGGER = Logging.getLogger("org.geotoolkit.referencing.factory")
The logger for event related to Geotk factories.
Protected Member Functions
synchronized void dispose (final boolean shutdown)
Closes the JDBC connection used by this factory.
String trimAuthority (String code)
Trims the authority scope, if presents.
final NoSuchAuthorityCodeException noSuchAuthorityCode (final Class<?> type, final String code)
Creates an exception for an unknown authority code.
Static Protected Member Functions
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException
Makes sure that an argument is non-null.
Protected Attributes
final NameFactory nameFactory
The name factory to use for creating GenericName.
final ReferencingFactoryContainer factories
The underlying factories used for objects creation.
Package Functions
final synchronized Citation [] getAuthorities ()
Returns all authority names declared in the CRS table.
Static Package Functions
[static initializer]
static FactoryException databaseFailure (final Class<?> type, final String code, final Throwable exception)
Wraps an Exception into a FactoryException.
static Class<?> getWKTClassOf (String element)
Returns the class of the specified WKT element.
static String getWKTNameOf (final Class<?> type)
Returns the WKT name of the specified object type.
Package Attributes
Citation authority
The authority for this factory.
Citation [] authorities
The authorities for this factory, usually as an array of length 1.
final Map< String, String > definitions
The properties object for our properties file.
Private Member Functions
Map< String, Boolean > getAuthorityNames () throws FactoryException
Returns the authority names found in the database.
Private Attributes
transient Map< String, Boolean > authorityUsePK
Authorities found in the database.
Detailed Description
An authority factory creating CRS from the { TABLE} table in a spatial SQL database.
This class is called Direct<u>Postgis</u>Factory because of some assumptions more suitable to PostGIS, like the default getAuthority() authority} if none were explicitly defined. But this class should be usable with other OGC compliant spatial database as well.
This factory doesn't cache any result. Any call to a
createFoo
method will trig a new WKT parsing. For adding caching service, this factory needs to be wrapped in a org.geotoolkit.referencing.factory.CachingAuthorityFactory instance. The AuthorityFactoryProvider convenience class can be used for that purpose.
Author
Martin Desruisseaux (Geomatys)
Version
3.10
Since
3.10 (derived from 2.5)
Constructor & Destructor Documentation
DirectPostgisFactory()
DirectPostgisFactory (final Connection connection) throws SQLException
Creates a factory using the given connection.
The connection is Connection::close() closed} when this factory is dispose(boolean) disposed}.
Note: we recommend to avoid keeping the connection open for a long time. An easy way to get the connection created only when first needed and closed automatically after a short timeout is to instantiate this
DirectPostgisFactory
class only in a org.geotoolkit.referencing.factory.ThreadedAuthorityFactory. This approach also gives concurrency and caching services in bonus.
Parameters
connection The connection to the database.
Exceptions
SQLException If an error occurred while fetching metadata from the database.
{
         super(new SpatialRefSysMap(connection));
     }
Member Function Documentation
[static initializer]()
[static initializer] () static package inherited
createCoordinateReferenceSystem()
synchronized CoordinateReferenceSystem createCoordinateReferenceSystem (final String code) throws NoSuchAuthorityCodeException, FactoryException inherited
Returns a coordinate reference system from a code.
If the object type is know at compile time, it is recommended to invoke the most precise method instead of this one.
Parameters
code Value allocated by authority.
Exceptions
NoSuchAuthorityCodeException if the specified
code
was not found.
FactoryException if the object creation failed for some other reason.
References WKTParsingAuthorityFactory.getParser(), and WKTParsingAuthorityFactory.getWKT().
Referenced by WKTParsingAuthorityFactory.createObject(), and PropertyEpsgFactory.reportInstantiationFailures().
     {
         final Parser parser = getParser();
         final String wkt = getWKT(CoordinateReferenceSystem.class, code, parser);
         return parser.createFromWKT(wkt);
     }
createObject()
synchronized IdentifiedObject createObject (final String code) throws NoSuchAuthorityCodeException, FactoryException inherited
Returns an arbitrary object from a code.
If the object type is know at compile time, it is recommended to invoke the most precise method instead of this one.
Parameters
code Value allocated by authority.
Exceptions
NoSuchAuthorityCodeException if the specified
code
was not found.
FactoryException if the object creation failed for some other reason.
References WKTParsingAuthorityFactory.createCoordinateReferenceSystem().
     {
         return createCoordinateReferenceSystem(code);
     }
databaseFailure()
static FactoryException databaseFailure (final Class<?> type, final String code, final Throwable exception) static package inherited
Wraps an Exception into a FactoryException.
The given exception is typically a java.sql.SQLException.
Parameters
type The type of the object being created, or
null
if unknown.
code The code of the object being created, or
null
if unknown.
exception The exception that occurred while querying the backing store.
Returns
A factory exception wrapping the given exception.
References Errors.Keys.DatabaseFailure_2, Errors.format(), Vocabulary.format(), and Vocabulary.Keys.Unknown.
Referenced by DirectPostgisFactory.getAuthorityCodes(), DirectPostgisFactory.getAuthorityNames(), DirectPostgisFactory.getBackingStoreDescription(), DirectPostgisFactory.getPrimaryKey(), and WKTParsingAuthorityFactory.getWKT().
{
         String message = exception.getLocalizedMessage();
         if (code != null) {
             String typeName;
             if (type != null) {
                 typeName = type.getSimpleName();
             } else {
                 typeName = Vocabulary.format(Vocabulary.Keys.Unknown);
             }
             message = Errors.format(Errors.Keys.DatabaseFailure_2, typeName, code) + ": " + message;
         }
         return new FactoryException(message, exception);
     }
dispose()
synchronized void dispose (final boolean shutdown) protected
Closes the JDBC connection used by this factory.
References WKTParsingAuthorityFactory.authorities, WKTParsingAuthorityFactory.authority, and WKTParsingAuthorityFactory.definitions.
{
         try {
             ((SpatialRefSysMap) definitions).dispose();
         } catch (SQLException exception) {
             Logging.unexpectedException(null, DirectPostgisFactory.class, "dispose", exception);
         }
         authority   = null;
         authorities = null;
         super.dispose(shutdown);
     }
ensureNonNull()
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException static protected inherited
Makes sure that an argument is non-null.
This is a convenience method for subclass methods.
Parameters
name Argument name.
object User argument.
Exceptions
InvalidParameterValueException if
object
is null.
References Errors.format(), and Errors.Keys.NullArgument_1.
Referenced by DirectAuthorityFactory.DirectAuthorityFactory(), DirectPostgisFactory.getPrimaryKey(), WKTParsingAuthorityFactory.getWKT(), PropertyAuthorityFactory.load(), and WKTParsingAuthorityFactory.WKTParsingAuthorityFactory().
     {
         if (object == null) {
             throw new InvalidParameterValueException(Errors.format(
                     Errors.Keys.NullArgument_1, name), name, object);
         }
     }
getAuthorities()
final synchronized Citation [] getAuthorities () package
Returns all authority names declared in the CRS table.
If some authorities use the same codes than the primary key, then those authorities are returned first, ordered by the most common ones. The last element in the array is the authority returned by getPrimaryKeyAuthority().
Returns
All authorities found in the database.
References WKTParsingAuthorityFactory.authorities, WKTParsingAuthorityFactory.authority, DirectPostgisFactory.getAuthorityNames(), DirectPostgisFactory.getPrimaryKeyAuthority(), and DirectAuthorityFactory.LOGGER.
{
         Citation[] authorities = this.authorities;
         if (authorities == null) {
             final Citation pkAuthority = getPrimaryKeyAuthority();
             int count = 0;
             try {
                 final Set<String> names = getAuthorityNames().keySet();
                 authorities = new Citation[names.size() + 1];
                 for (final String name : names) {
                     final Citation authority = (name != null) ? Citations.fromName(name) : pkAuthority;
                     /*
                      * If the authority is not one of the predefined constants (in which case the
                      * class would have been CitationConstant), then add the name to the list of
                      * identifiers.
                      */
                     if (authority.getClass() == DefaultCitation.class) {
                         ((DefaultCitation) authority).getIdentifiers().add(new DefaultIdentifier(name));
                     }
                     authorities[count++] = authority;
                 }
             } catch (FactoryException exception) {
                 Logging.unexpectedException(LOGGER, DirectPostgisFactory.class, "getAuthority", exception);
                 authorities = new Citation[] {getPrimaryKeyAuthority()};
             }
             authorities[count] = pkAuthority;
             this.authorities = authorities;
         }
         return authorities;
     }
getAuthority()
synchronized Citation getAuthority () inherited
Returns the authority.
The default implementation returns the first citation given to the constructor, or a modified version of that citation if many of them were given to the constructor. In the later case, the returned citation will have a set of Citation::getIdentifiers() identifiers} which is the union of identifiers of all citations given to the constructor.
References WKTParsingAuthorityFactory.authority, WKTParsingAuthorityFactory.getAuthorities(), and WKTParsingAuthorityFactory.getPrimaryKeyAuthority().
Referenced by DirectPostgisFactory.getBackingStoreDescription().
{
         if (authority == null) {
             Citation[] authorities = getAuthorities();
             final Citation pkAuthority = getPrimaryKeyAuthority();
             if (pkAuthority != null) {
                 for (int i=0; i<authorities.length; i++) {
                     if (pkAuthority.equals(authorities[i])) {
                         authorities = ArraysExt.remove(authorities, i, 1);
                         break;
                     }
                 }
             }
             switch (authorities.length) {
                 case 0: authority = new SimpleCitation("Unknown"); break;
                 case 1: authority = authorities[0]; break;
                 default: {
                     final DefaultCitation c = new DefaultCitation(authorities[0]);
                     final Collection<Identifier> identifiers = c.getIdentifiers();
                     for (int i=1; i<authorities.length; i++) {
                         identifiers.addAll(authorities[i].getIdentifiers());
                     }
                     c.transitionTo(DefaultCitation.State.FINAL);
                     authority = c;
                     break;
                 }
             }
         }
         return authority;
     }
getAuthorityCodes()
synchronized Set<String> getAuthorityCodes (final Class<? extends IdentifiedObject > category) throws FactoryException
Returns the authority codes defined in the database for the given type.
Parameters
category The type of objects to search for (typically CoordinateReferenceSystem}.class).
Returns
The set of available codes.
Exceptions
FactoryException if an error occurred while querying the database.
References WKTParsingAuthorityFactory.databaseFailure(), and WKTParsingAuthorityFactory.definitions.
     {
         try {
             return ((SpatialRefSysMap) definitions).getAuthorityCodes(category);
         } catch (SQLException exception) {
             throw databaseFailure(category, null, exception);
         }
     }
getAuthorityNames()
Map<String,Boolean> getAuthorityNames () throws FactoryException private
Returns the authority names found in the database.
Keys are authority names, and values are whatever the authority codes match primary keys or not.
Returns
All authority names found in the database.
Exceptions
FactoryException if an access to the database failed.
References DirectPostgisFactory.authorityUsePK, WKTParsingAuthorityFactory.databaseFailure(), and WKTParsingAuthorityFactory.definitions.
Referenced by DirectPostgisFactory.getAuthorities(), and DirectPostgisFactory.getPrimaryKey().
{
         assert Thread.holdsLock(this);
         if (authorityUsePK == null) {
             try {
                 authorityUsePK = ((SpatialRefSysMap) definitions).getAuthorityNames();
             } catch (SQLException exception) {
                 throw databaseFailure(null, null, exception);
             }
         }
         return authorityUsePK;
     }
getBackingStoreDescription()
String getBackingStoreDescription () throws FactoryException
Returns a description of the underlying backing store.
References WKTParsingAuthorityFactory.authority, Vocabulary.Keys.DatabaseEngine, WKTParsingAuthorityFactory.databaseFailure(), Vocabulary.Keys.DatabaseUrl, WKTParsingAuthorityFactory.definitions, WKTParsingAuthorityFactory.getAuthority(), Vocabulary.getLabel(), Vocabulary.getResources(), Vocabulary.Keys.Version_1, and Vocabulary.Keys.VersionOf_1.
{
         final Citation   authority = getAuthority();
         final TableAppender    table = new TableAppender(" ");
         final Vocabulary resources = Vocabulary.getResources(null);
         CharSequence cs;
         if ((cs=authority.getEdition()) != null) {
             final String identifier = org.apache.sis.metadata.iso.citation.Citations.getIdentifier(authority);
             table.append(resources.getString(Vocabulary.Keys.VersionOf_1, identifier));
             table.append(':');
             table.nextColumn();
             table.append(cs.toString());
             table.nextLine();
         }
         try {
             String s;
             final DatabaseMetaData metadata = ((SpatialRefSysMap) definitions).connection.getMetaData();
             if ((s=metadata.getDatabaseProductName()) != null) {
                 table.append(resources.getLabel(Vocabulary.Keys.DatabaseEngine));
                 table.nextColumn();
                 table.append(s);
                 if ((s = metadata.getDatabaseProductVersion()) != null) {
                     table.append(' ');
                     table.append(resources.getString(Vocabulary.Keys.Version_1, s));
                 }
                 table.nextLine();
             }
             if ((s = metadata.getURL()) != null) {
                 table.append(resources.getLabel(Vocabulary.Keys.DatabaseUrl));
                 table.nextColumn();
                 table.append(s);
                 table.nextLine();
             }
         } catch (SQLException exception) {
             throw databaseFailure(null, null, exception);
         }
         return table.toString();
     }
getDescriptionText()
InternationalString getDescriptionText (final String code) throws NoSuchAuthorityCodeException, FactoryException inherited
Gets a description of the object corresponding to a code.
Parameters
code Value allocated by authority.
Returns
A description of the object, or
null
if the object corresponding to the specified
code
has no description.
Exceptions
NoSuchAuthorityCodeException if the specified
code
was not found.
FactoryException if the query failed for some other reason.
References WKTParsingAuthorityFactory.getWKT().
     {
         final String wkt;
         synchronized (this) {
             wkt = getWKT(IdentifiedObject.class, code, null);
         }
         int start = wkt.indexOf('"');
         if (start >= 0) {
             final int end = wkt.indexOf('"', ++start);
             if (end >= 0) {
                 return new SimpleInternationalString(wkt.substring(start, end).trim());
             }
         }
         return null;
     }
getPrimaryKey()
synchronized Integer getPrimaryKey (final Class<? extends IdentifiedObject > type, String code) throws NoSuchAuthorityCodeException, FactoryException
Returns the primary key for the specified authority code.
If the supplied code contains an <cite>authority</cite> part as in
"EPSG:4326"
, then this method searches for a row with the given authority (
"EPSG"
) in the { AUTHORITY_COLUMN} column and the given integer code (
4326
) in the { CODE_COLUMN} column. If such row is found, then the value of its { PRIMARY_KEY} column is returned.
If the supplied code does not contain an <cite>authority</cite> part (e.g.
"4326"
), then this method parses the code as an integer. This is consistent with common practice where the spatial CRS table contains entries from a single authority with primary keys identical to the authority codes. This is also consistent with the codes returned by the getAuthorityCodes(Class) method.
Parameters
type The type of the object being created (usually CoordinateReferenceSystem}.class).
code The authority code to convert to primary key value.
Returns
The primary key for the supplied code. There is no guarantee that this key exists (this method may or may not query the database).
Exceptions
NoSuchAuthorityCodeException if a code can't be parsed as an integer or can't be found in the database.
FactoryException if an error occurred while querying the database.
See also
getPrimaryKeyAuthority()
References WKTParsingAuthorityFactory.authority, WKTParsingAuthorityFactory.databaseFailure(), WKTParsingAuthorityFactory.definitions, DirectAuthorityFactory.ensureNonNull(), DirectPostgisFactory.getAuthorityNames(), and DirectAuthorityFactory.noSuchAuthorityCode().
     {
         ensureNonNull("code", code);
         code = code.trim();
         final int separator = code.lastIndexOf(DefaultNameSpace.DEFAULT_SEPARATOR);
         final String authority  = (separator >= 0) ? code.substring(0, separator).trim() : "";
         final String identifier = code.substring(separator+1).trim();
         int srid;
         try {
             srid = Integer.parseInt(identifier);
         } catch (NumberFormatException cause) {
             NoSuchAuthorityCodeException e = noSuchAuthorityCode(IdentifiedObject.class, code);
             e.initCause(cause);
             throw e;
         }
         if (authority.isEmpty() || Boolean.TRUE.equals(getAuthorityNames().get(authority))) {
             return srid;
         }
         final Integer c;
         try {
             c = ((SpatialRefSysMap) definitions).getPrimaryKey(code, authority, srid);
         } catch (SQLException exception) {
             throw databaseFailure(type, code, exception);
         }
         if (c == null) {
             throw noSuchAuthorityCode(type, code);
         }
         return c;
     }
getPrimaryKeyAuthority()
Citation getPrimaryKeyAuthority ()
Returns the authority which is responsible for the maintenance of the primary keys.
Note that <cite>primary keys</cite> are not necessarily the same than authority codes. The primary keys are stored in the { PRIMARY_KEY} column, while the authority codes are defined by the { AUTHORITY_COLUMN} : { CODE_COLUMN} tuples.
The default implementation returns Citations#POSTGIS in all cases.
Returns
The authority which is responsible for the maintenance of primary keys.
See also
#getPrimaryKey(Class, String)
Referenced by DirectPostgisFactory.getAuthorities().
{
         return new SimpleCitation("PostGIS");
     }
getVendor()
Citation getVendor () inherited
Returns the vendor responsible for creating this factory implementation.
Many implementations from different vendors may be available for the same factory interface.
The default for Geotk implementations is to return Citations::GEOTOOLKIT Geotoolkit.org}.
Returns
The vendor for this factory implementation.
See also
Citations::GEOTOOLKIT
References DirectAuthorityFactory.getAuthority().
{
         return new SimpleCitation(getClass().getName().startsWith("org.geotoolkit.") ? "Geotk" : "Unknown");
     }
getWKTClassOf()
static Class<?> getWKTClassOf (String element) static package inherited
Returns the class of the specified WKT element.
For example this method returns ProjectedCRS}.class for element "@code PROJCS @endcode ".
This method is the converse of getNameOf.
Parameters
element The WKT element name.
Returns
The GeoAPI class of the specified element, or
null
if unknown.
References WKTParsingAuthorityFactory.getWKTNameOf(), and WKTParsingAuthorityFactory.Codes.type.
Referenced by WKTParsingAuthorityFactory.Codes.baseToDerived().
{
         if (element == null) {
             return null;
         }
         element = element.trim().toUpperCase(Locale.US);
         final Class<?> type = TYPES.get(element);
         assert type == null || type.equals(MathTransform.class) || element.equals(getWKTNameOf(type)) : type;
         return type;
     }
getWKTNameOf()
static String getWKTNameOf (final Class<?> type) static package inherited
Returns the WKT name of the specified object type.
For example this method returns "@code PROJCS @endcode " for type ProjectedCRS}.class.
This method is the converse of getClassOf.
Parameters
type The GeoAPI class of the specified element.
Returns
The WKT element name, or
null
if unknown.
Referenced by SpatialRefSysMap.getAuthorityCodes(), and WKTParsingAuthorityFactory.getWKTClassOf().
{
         if (type != null) {
             for (final Map.Entry<String,Class<?>> entry : TYPES.entrySet()) {
                 final Class<?> candidate = entry.getValue();
                 if (candidate.isAssignableFrom(type)) {
                     return entry.getKey();
                 }
             }
         }
         return null;
     }
noSuchAuthorityCode()
final NoSuchAuthorityCodeException noSuchAuthorityCode (final Class<?> type, final String code) protected inherited
Creates an exception for an unknown authority code.
This convenience method is provided for implementation of
createXXX
methods.
Parameters
type The GeoAPI interface that was to be created (e.g.
CoordinateReferenceSystem.class
).
code The unknown authority code.
Returns
An exception initialized with an error message built from the specified informations.
References Errors.format(), DirectAuthorityFactory.getAuthority(), Errors.Keys.NoSuchAuthorityCode_3, and DirectAuthorityFactory.trimAuthority().
Referenced by IGNF.createCoordinateReferenceSystem(), DirectPostgisFactory.getPrimaryKey(), and WKTParsingAuthorityFactory.getWKT().
{
         final InternationalString authority = getAuthority().getTitle();
         return new NoSuchAuthorityCodeException(Errors.format(Errors.Keys.NoSuchAuthorityCode_3,
                    code, authority, type), authority.toString(), trimAuthority(code), code);
     }
trimAuthority()
String trimAuthority (String code) protected inherited
Trims the authority scope, if presents.
If more than one authority were given at WKTParsingAuthorityFactory construction time}, then any of them may appears as the scope in the supplied code.
Parameters
code The code to trim.
Returns
The code without the authority scope.
References WKTParsingAuthorityFactory.getAuthorities(), and DirectAuthorityFactory.nameFactory.
Referenced by WKTParsingAuthorityFactory.Parser.complete(), and WKTParsingAuthorityFactory.getPrimaryKey().
{
         code = code.trim();
         final GenericName name  = nameFactory.parseGenericName(null, code);
         if (name instanceof ScopedName) {
             final GenericName scope = ((ScopedName) name).path();
             final String candidate = scope.toString();
             final Citation[] authorities = getAuthorities();
             for (int i=0; i<authorities.length; i++) {
                 if (Citations.identifierMatches(authorities[i], candidate)) {
                     return name.tip().toString().trim();
                 }
             }
         }
         return code;
     }
Member Data Documentation
authorities
Citation [] authorities package inherited
The authorities for this factory, usually as an array of length 1.
Referenced by WKTParsingAuthorityFactory.Parser.complete(), DirectPostgisFactory.dispose(), DirectPostgisFactory.getAuthorities(), WKTParsingAuthorityFactory.getAuthorities(), PropertyAuthorityFactory.load(), PropertyAuthorityFactory.PropertyAuthorityFactory(), and PropertyEpsgFactory.PropertyEpsgFactory().
authority
Citation authority package inherited
The authority for this factory.
Will be computed by getAuthority() when first needed.
Referenced by DirectPostgisFactory.dispose(), DirectPostgisFactory.getAuthorities(), WKTParsingAuthorityFactory.getAuthority(), DirectPostgisFactory.getBackingStoreDescription(), DirectPostgisFactory.getPrimaryKey(), and PropertyAuthorityFactory.load().
AUTHORITY_COLUMN
final String AUTHORITY_COLUMN = "auth_name" static
The standard name ({}) of the column containing the authority names.
authorityUsePK
transient Map<String,Boolean> authorityUsePK private
Authorities found in the database.
Will be computed only when first needed. Keys are authority names, and values are whatever the authority codes match primary keys or not.
Referenced by DirectPostgisFactory.getAuthorityNames().
CODE_COLUMN
final String CODE_COLUMN = "auth_srid" static
The standard name ({}) of the column containing the authority codes.
definitions
final Map<String,String> definitions package inherited
The properties object for our properties file.
Keys are the authority code for a coordinate reference system and the associated value is a WKT string for the CRS.
Referenced by DirectPostgisFactory.dispose(), PropertyAuthorityFactory.dispose(), DirectPostgisFactory.getAuthorityCodes(), DirectPostgisFactory.getAuthorityNames(), DirectPostgisFactory.getBackingStoreDescription(), DirectPostgisFactory.getPrimaryKey(), PropertyAuthorityFactory.load(), and WKTParsingAuthorityFactory.WKTParsingAuthorityFactory().
factories
final ReferencingFactoryContainer factories protected inherited
The underlying factories used for objects creation.
Referenced by IGNF.createCoordinateReferenceSystem(), and DirectAuthorityFactory.DirectAuthorityFactory().
LOGGER
final Logger LOGGER = Logging.getLogger("org.geotoolkit.referencing.factory") static inherited
The logger for event related to Geotk factories.
Referenced by DirectPostgisFactory.getAuthorities(), PropertyAuthorityFactory.log(), and PropertyAuthorityFactory.PropertyAuthorityFactory().
nameFactory
final NameFactory nameFactory protected inherited
The name factory to use for creating GenericName.
Since
3.00
Referenced by WKTParsingAuthorityFactory.trimAuthority().
PRIMARY_KEY
final String PRIMARY_KEY = "srid" static
The primary key column, which is {}.
TABLE
final String TABLE = "spatial_ref_sys" static
The standard name of the table containing CRS definitions, which is {}.
WKT_COLUMN
final String WKT_COLUMN = "srtext" static
The standard name ({}) of the column containing the WKT definitions.