jena-geo: Parameter< T > Class Template Reference
Parameter< T > Class Template Reference
A parameter value used by an operation method.
Public Member Functions
Parameter (final ParameterDescriptor< T > descriptor)
Constructs a parameter value from the specified descriptor.
Parameter (final ParameterDescriptor< T > descriptor, final T value) throws InvalidParameterValueException
Constructs a parameter value from the specified descriptor and value.
Unit<?> getUnit ()
Returns the unit of measure of the doubleValue() parameter value}.
double doubleValue (final Unit<?> unit) throws IllegalArgumentException, IllegalStateException
Returns the numeric value of the coordinate operation parameter in the specified unit of measure.
double doubleValue () throws IllegalStateException
Returns the numeric value represented by this operation parameter.
int intValue () throws IllegalStateException
Returns the positive integer value of an operation parameter, usually used for a count.
boolean booleanValue () throws IllegalStateException
Returns the boolean value of an operation parameter.
String stringValue () throws IllegalStateException
Returns the string value of an operation parameter.
double [] doubleValueList (final Unit<?> unit) throws IllegalArgumentException, IllegalStateException
Returns an ordered sequence of numeric values in the specified unit of measure.
double [] doubleValueList () throws IllegalStateException
Returns an ordered sequence of two or more numeric values of an operation parameter list, where each value has the same associated Unit unit of measure}.
int [] intValueList () throws IllegalStateException
Returns an ordered sequence of two or more integer values of an operation parameter list, usually used for counts.
URI valueFile () throws IllegalStateException
Returns a reference to a file or a part of a file containing one or more parameter values.
T getValue ()
Returns the parameter value as an object.
void setValue (final double value, final Unit<?> unit) throws InvalidParameterValueException
Sets the parameter value as a floating point and its associated unit.
void setValue (final double value) throws InvalidParameterValueException
Sets the parameter value as a floating point.
void setValue (final int value) throws InvalidParameterValueException
Sets the parameter value as an integer.
void setValue (final boolean value) throws InvalidParameterValueException
Sets the parameter value as a boolean.
void setValue (final Object value) throws InvalidParameterValueException
Sets the parameter value as an object.
void setValue (double[] values, final Unit<?> unit) throws InvalidParameterValueException
Sets the parameter value as an array of floating point and their associated unit.
boolean equals (final Object object)
Compares the specified object with this parameter for equality.
int hashCode ()
Returns a hash value for this parameter.
Parameter< T > clone ()
Returns a clone of this parameter.
ParameterDescriptor< T > getDescriptor ()
Returns the abstract definition of this parameter.
void addChangeListener (final ChangeListener listener)
Adds the specified listener to the list of objects to inform when the value changed.
void removeChangeListener (final ChangeListener listener)
Removes the specified listener from the list of objects to inform when the value changed.
String formatTo (final Formatter formatter)
Formats the inner part of this parameter as Well Known Text (WKT).
Protected Member Functions
void setSafeValue (final T value, final Unit<?> unit)
Invoked by all.
final void fireValueChanged ()
Informs every listeners that the value changed.
Static Protected Member Functions
static IllegalStateException unitlessParameter (final GeneralParameterDescriptor descriptor)
Returns an exception initialized with a "Unitless parameter" error message for the specified descriptor.
static String getName (final GeneralParameterDescriptor descriptor)
Convenience method returning the name of the specified descriptor.
Protected Attributes
final GeneralParameterDescriptor descriptor
The abstract definition of this parameter or group of parameters.
Package Functions
static< T > T ensureValidValue (final ParameterDescriptor< T > descriptor, final Object value) throws InvalidParameterValueException
Ensures that the given value is valid according the specified parameter descriptor.
Static Package Functions
static short getUnitMessageID (final Unit<?> unit)
Returns the unit type as one of error message code.
Private Member Functions
String getClassTypeError ()
Formats an error message for illegal method call for the current value type.
Private Attributes
T value
The value, or.
Unit<?> unit
The unit of measure for the value, or.
Static Private Attributes
static final long serialVersionUID = -5837826787089486776L
Serial number for inter-operability with different versions.
Detailed Description
A parameter value used by an operation method.
Most CRS parameter values are numeric and can be obtained by the intValue() or doubleValue() methods. But other types of parameter values are possible and can be handled by the more generic getValue() and setValue(Object) methods. The type and constraints on parameter values are given by the getDescriptor() descriptor}.
Instances of
ParameterValue
are created by the ParameterDescriptor#createValue() method. The parameter type can be fetch with the following idiom:
{ java Class<? extends T> valueClass = parameter.getDescriptor().getValueClass(); }
{
note for subclasses}
Except for the constructors, the equals(Object) and the hashCode() methods, all read and write operations ultimately delegates to the following methods:
All getter methods will invoke getValue() and - if needed - getUnit(), then performs their processing on the values returned by those methods.
All setter methods will first convert (if needed) and verify the argument validity, then pass the values to the setSafeValue(Object, Unit) method.
Consequently, the above-cited methods provide single points that subclasses can override for modifying the behavior of all getter and setter methods.
Parameters
<T> The value type.
Author
Martin Desruisseaux (IRD, Geomatys)
Jody Garnett (Refractions)
See also
DefaultParameterDescriptor
ParameterGroup
Since
2.0
Deprecated:
Moved to Apache SIS org.apache.sis.parameter.DefaultParameterValue.
Constructor & Destructor Documentation
Parameter() [1/2]
Parameter (final ParameterDescriptor< T > descriptor)
Constructs a parameter value from the specified descriptor.
The value will be initialized to the default value, if any.
Parameters
descriptor The abstract definition of this parameter.
{
         super(descriptor);
         value = descriptor.getDefaultValue();
         unit  = descriptor.getUnit();
     }
Parameter() [2/2]
Parameter (final ParameterDescriptor< T > descriptor, final T value) throws InvalidParameterValueException
Constructs a parameter value from the specified descriptor and value.
Parameters
descriptor The abstract definition of this parameter.
value The parameter value.
Exceptions
InvalidParameterValueException if the type of
value
is inappropriate for this parameter, or if the value is illegal for some other reason (for example the value is numeric and out of range).
References AbstractParameter.descriptor, and Parameter< T >.setValue().
     {
         super(descriptor);
         unit = descriptor.getUnit();
         setValue(value);
     }
Member Function Documentation
addChangeListener()
void addChangeListener (final ChangeListener listener) inherited
Adds the specified listener to the list of objects to inform when the value changed.
Notes:
Change listeners are not serialized
Change listeners are not included in clone() cloned} object.
Parameters
listener The listener to add.
{
         listeners = Listeners.addListener(listener, listeners);
     }
booleanValue()
boolean booleanValue () throws IllegalStateException
Returns the boolean value of an operation parameter.
A boolean value does not have an associated unit of measure.
Returns
The boolean value represented by this parameter.
Exceptions
InvalidParameterTypeException if the value is not a boolean type.
IllegalStateException if the value is not defined and there is no default value.
See also
setValue(boolean)
References AbstractParameter.descriptor, Errors.format(), Parameter< T >.getClassTypeError(), AbstractParameter.getName(), Parameter< T >.getValue(), and Errors.Keys.NoParameter_1.
{
         final T value = getValue();
         if (value instanceof Boolean) {
             return ((Boolean) value).booleanValue();
         }
         final String name = getName(descriptor);
         if (value == null) {
             throw new IllegalStateException(Errors.format(Errors.Keys.NoParameter_1, name));
         }
         throw new InvalidParameterTypeException(getClassTypeError(), name);
     }
clone()
Parameter<T> clone ()
Returns a clone of this parameter.
Implements Cloneable.
{
         return (Parameter<T>) super.clone();
     }
doubleValue() [1/2]
double doubleValue (final Unit<?> unit) throws IllegalArgumentException, IllegalStateException
Returns the numeric value of the coordinate operation parameter in the specified unit of measure.
This convenience method applies unit conversions on the fly as needed.
Parameters
unit The unit of measure for the value to be returned.
Returns
The numeric value represented by this parameter after conversion to type
double
and conversion to
unit
.
Exceptions
IllegalArgumentException if the specified unit is invalid for this parameter.
InvalidParameterTypeException if the value is not a numeric type.
IllegalStateException if the value is not defined and there is no default value.
See also
getUnit()
#setValue(double,Unit)
#doubleValueList(Unit)
References AbstractParameter.descriptor, Parameter< T >.doubleValue(), Errors.format(), Parameter< T >.getUnit(), AbstractParameter.getUnitMessageID(), Errors.Keys.IncompatibleUnit_1, and AbstractParameter.unitlessParameter().
{
         final Unit<?> actual = getUnit();
         if (actual == null) {
             throw unitlessParameter(descriptor);
         }
         ensureNonNull("unit", unit);
         final short expectedID = getUnitMessageID(actual);
         if (getUnitMessageID(unit) != expectedID) {
             throw new IllegalArgumentException(Errors.format(expectedID, unit));
         }
         try {
             return actual.getConverterToAny(unit).convert(doubleValue());
         } catch (IncommensurableException e) {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.IncompatibleUnit_1, unit), e);
         }
     }
doubleValue() [2/2]
double doubleValue () throws IllegalStateException
Returns the numeric value represented by this operation parameter.
The units of measurement are specified by getUnit().
{
Note
The behavior of this method is slightly different than the equivalent method in the FloatParameter class, since this method throws an exception instead than returning NaN if no value has been explicitely set. This method behaves that way for consistency will other methods defined in this class, since all of them except getValue() throw an exception in such case.}
Returns
The numeric value represented by this parameter after conversion to type
double
. This method returns Double#NaN only if such "value" has been explicitely set.
Exceptions
InvalidParameterTypeException if the value is not a numeric type.
IllegalStateException if the value is not defined and there is no default value.
See also
getUnit()
setValue(double)
doubleValueList()
References AbstractParameter.descriptor, Errors.format(), Parameter< T >.getClassTypeError(), AbstractParameter.getName(), Parameter< T >.getValue(), and Errors.Keys.NoParameter_1.
Referenced by Parameter< T >.doubleValue(), and Parameter< T >.intValue().
{
         final T value = getValue();
         if (value instanceof Number) {
             return ((Number) value).doubleValue();
         }
         final String name = getName(descriptor);
         if (value == null) {
             // This is the kind of exception expected by org.geotoolkit.io.wkt.Formatter.
             // If a default value existed, it should has been copied by the constructor or setter methods.
             throw new IllegalStateException(Errors.format(Errors.Keys.NoParameter_1, name));
         }
         // Reminder: the following is a specialization of IllegalStateException.
         throw new InvalidParameterTypeException(getClassTypeError(), name);
     }
doubleValueList() [1/2]
double [] doubleValueList (final Unit<?> unit) throws IllegalArgumentException, IllegalStateException
Returns an ordered sequence of numeric values in the specified unit of measure.
This convenience method apply unit conversion on the fly as needed.
Parameters
unit The unit of measure for the value to be returned.
Returns
The sequence of values represented by this parameter after conversion to type
double
and conversion to
unit
.
Exceptions
IllegalArgumentException if the specified unit is invalid for this parameter.
InvalidParameterTypeException if the value is not an array of
double
s.
IllegalStateException if the value is not defined and there is no default value.
See also
getUnit()
#setValue(double[],Unit)
#doubleValue(Unit)
References AbstractParameter.descriptor, Parameter< T >.doubleValueList(), Errors.format(), Parameter< T >.getUnit(), AbstractParameter.getUnitMessageID(), Errors.Keys.IncompatibleUnit_1, and AbstractParameter.unitlessParameter().
{
         final Unit<?> actual = getUnit();
         if (actual == null) {
             throw unitlessParameter(descriptor);
         }
         ensureNonNull("unit", unit);
         final short expectedID = getUnitMessageID(actual);
         if (getUnitMessageID(unit) != expectedID) {
             throw new IllegalArgumentException(Errors.format(expectedID, unit));
         }
         final UnitConverter converter;
         try {
             converter = actual.getConverterToAny(unit);
         } catch (IncommensurableException e) {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.IncompatibleUnit_1, unit), e);
         }
         final double[] values = doubleValueList().clone();
         for (int i=0; i<values.length; i++) {
             values[i] = converter.convert(values[i]);
         }
         return values;
     }
doubleValueList() [2/2]
double [] doubleValueList () throws IllegalStateException
Returns an ordered sequence of two or more numeric values of an operation parameter list, where each value has the same associated Unit unit of measure}.
Returns
The sequence of values represented by this parameter.
Exceptions
InvalidParameterTypeException if the value is not an array of
double
s.
IllegalStateException if the value is not defined and there is no default value.
See also
getUnit()
setValue(Object)
doubleValue()
References AbstractParameter.descriptor, Errors.format(), Parameter< T >.getClassTypeError(), AbstractParameter.getName(), Parameter< T >.getValue(), Errors.Keys.NoParameter_1, and Parameter< T >.value.
Referenced by Parameter< T >.doubleValueList().
{
         final T value = getValue();
         if (value instanceof double[]) {
             return (double[]) value;
         }
         final String name = getName(descriptor);
         if (value == null) {
             throw new IllegalStateException(Errors.format(Errors.Keys.NoParameter_1, name));
         }
         throw new InvalidParameterTypeException(getClassTypeError(), name);
     }
ensureValidValue()
static<T> T ensureValidValue (final ParameterDescriptor< T > descriptor, final Object value) throws InvalidParameterValueException package inherited
Ensures that the given value is valid according the specified parameter descriptor.
This convenience method ensures that
value
is assignable to the ParameterDescriptor::getValueClass() expected class}, is between the ParameterDescriptor::getMinimumValue() minimum} and ParameterDescriptor::getMaximumValue() maximum} values and is one of the ParameterDescriptor::getValidValues() set of valid values}. If the value fails any of those tests, then an exception is thrown.
This method is similar to Parameters#isValid(ParameterValue) except that the exception contains an error message formatted with a description of the failure raison.
Parameters
<T> The type of parameter value. The given
value
should typically be an instance of this class. This is not required by this method signature but is checked by this method implementation.
descriptor The parameter descriptor to check against.
value The value to check, or
null
.
Returns
The value casted to the descriptor parameterized type, or the ParameterDescriptor::getDefaultValue() default value} if the given value was null while the parameter is mandatory.
Exceptions
InvalidParameterValueException if the parameter value is invalid.
References Errors.format(), AbstractParameter.getName(), Errors.Keys.IllegalArgument_2, Errors.Keys.IllegalOperationForValueClass_1, and Errors.Keys.ValueOutOfBounds_3.
Referenced by Parameter< T >.setValue().
     {
         if (value == null) {
             if (descriptor.getMinimumOccurs() != 0) {
                 return descriptor.getDefaultValue();
             }
             return null;
         }
         final String error;
         /*
          * Note: the implementation below is similar (except for different error message) to the
          * one in Parameters.isValidValue(ParameterDescriptor, Object). If one implementation is
          * modified, the other should be updated accordingly. The main difference is that null
          * values are replaced by the default value instead than being a conformance error.
          */
         final Class<T> type = descriptor.getValueClass();
         if (!type.isInstance(value)) {
             error = Errors.format(Errors.Keys.IllegalOperationForValueClass_1, value.getClass());
         } else {
             final T typedValue = type.cast(value);
             final Comparable<T> minimum = descriptor.getMinimumValue();
             final Comparable<T> maximum = descriptor.getMaximumValue();
             if ((minimum != null && minimum.compareTo(typedValue) > 0) ||
                 (maximum != null && maximum.compareTo(typedValue) < 0))
             {
                 error = Errors.format(Errors.Keys.ValueOutOfBounds_3, value, minimum, maximum);
             } else {
                 final Set<T> validValues = descriptor.getValidValues();
                 if (validValues!=null && !validValues.contains(value)) {
                     error = Errors.format(Errors.Keys.IllegalArgument_2, getName(descriptor), value);
                 } else {
                     /*
                      * Passed every tests - the value is valid.
                      */
                     return typedValue;
                 }
             }
         }
         throw new InvalidParameterValueException(error, getName(descriptor), value);
     }
equals()
boolean equals (final Object object)
Compares the specified object with this parameter for equality.
Parameters
object The object to compare to
this
.
Returns
true
if both objects are equal.
References Parameter< T >.equals(), Parameter< T >.unit, and Parameter< T >.value.
Referenced by Parameter< T >.equals().
{
         if (object == this) {
             // Slight optimization
             return true;
         }
         if (super.equals(object)) {
             final Parameter<?> that = (Parameter<?>) object;
             return Objects.equals(this.value, that.value) &&
                    Objects.equals(this.unit,  that.unit);
         }
         return false;
     }
fireValueChanged()
final void fireValueChanged () protected inherited
Informs every listeners that the value changed.
Referenced by Parameter< T >.setSafeValue().
{
         Listeners.fireChanged(this, listeners);
     }
formatTo()
String formatTo (final Formatter formatter) inherited
Formats the inner part of this parameter as Well Known Text (WKT).
References AbstractParameter.Bridge< T >.formatTo().
{
         if (this instanceof ParameterValue<?>) {
             return new Bridge((ParameterValue<?>) this).formatTo(formatter);
         }
         return "PARAMETER";
     }
getClassTypeError()
String getClassTypeError () private
Formats an error message for illegal method call for the current value type.
References AbstractParameter.descriptor, Errors.format(), and Errors.Keys.IllegalOperationForValueClass_1.
Referenced by Parameter< T >.booleanValue(), Parameter< T >.doubleValue(), Parameter< T >.doubleValueList(), Parameter< T >.intValue(), Parameter< T >.intValueList(), Parameter< T >.stringValue(), and Parameter< T >.valueFile().
{
         return Errors.format(Errors.Keys.IllegalOperationForValueClass_1,
                ((ParameterDescriptor<?>) descriptor).getValueClass());
     }
getDescriptor()
ParameterDescriptor<T> getDescriptor () inherited
Returns the abstract definition of this parameter.
{
         return (ParameterDescriptor<T>) super.getDescriptor();
     }
getName()
static String getName (final GeneralParameterDescriptor descriptor) static protected inherited
Convenience method returning the name of the specified descriptor.
This method is used mostly for output to be read by human, not for processing. Consequently, we may consider to returns a localized name in a future version.
Referenced by Parameter< T >.booleanValue(), Parameter< T >.doubleValue(), Parameter< T >.doubleValueList(), ParameterGroup.ensureValidOccurs(), AbstractParameter.ensureValidValue(), Parameter< T >.intValue(), Parameter< T >.intValueList(), Parameters.isValidValue(), Parameter< T >.stringValue(), AbstractParameter.unitlessParameter(), and Parameter< T >.valueFile().
{
         return descriptor.getName().getCode();
     }
getUnit()
Unit<?> getUnit ()
Returns the unit of measure of the doubleValue() parameter value}.
If the parameter value has no unit (for example because it is a String type), then this method returns
null
. Note that "no unit" doesn't means "dimensionless".
{
note for subclasses}
All getter methods which need unit information will invoke this
getUnit()
method. Subclasses can override this method if they need to compute the unit dynamically.
Returns
The unit of measure, or
null
if none.
See also
doubleValue()
doubleValueList()
getValue()
References Parameter< T >.unit.
Referenced by Parameter< T >.doubleValue(), and Parameter< T >.doubleValueList().
{
         return unit;
     }
getUnitMessageID()
static short getUnitMessageID (final Unit<?> unit) static package inherited
Returns the unit type as one of error message code.
Used for checking unit with a better error message formatting if needed.
References Errors.Keys.IncompatibleUnit_1, Errors.Keys.NonAngularUnit_1, Errors.Keys.NonLinearUnit_1, Errors.Keys.NonScaleUnit_1, and Errors.Keys.NonTemporalUnit_1.
Referenced by Parameter< T >.doubleValue(), Parameter< T >.doubleValueList(), and Parameter< T >.setValue().
{
         if (Units.isLinear  (unit)) return Errors.Keys.NonLinearUnit_1;
         if (Units.isAngular (unit)) return Errors.Keys.NonAngularUnit_1;
         if (Units.isTemporal(unit)) return Errors.Keys.NonTemporalUnit_1;
         if (Units.isScale   (unit)) return Errors.Keys.NonScaleUnit_1;
         return Errors.Keys.IncompatibleUnit_1;
     }
getValue()
T getValue ()
Returns the parameter value as an object.
The object type is typically a Double, Integer, Boolean, String, URI,
double[]
or
int[]
. If no value has been set, then this method returns the ParameterDescriptor::getDefaultValue() default value} (which may be null).
{
note for subclasses}
All getter methods will invoke this
getValue()
method. Subclasses can override this method if they need to compute the value dynamically.
Returns
The parameter value as an object, or
null
if no value has been set and there is no default value.
See also
setValue(Object)
References Parameter< T >.value.
Referenced by Parameter< T >.booleanValue(), Parameter< T >.doubleValue(), Parameter< T >.doubleValueList(), Parameter< T >.intValue(), Parameter< T >.intValueList(), Parameter< T >.stringValue(), and Parameter< T >.valueFile().
{
         return value;
     }
hashCode()
int hashCode ()
Returns a hash value for this parameter.
Returns
The hash code value. This value doesn't need to be the same in past or future versions of this class.
References Parameter< T >.serialVersionUID, Parameter< T >.unit, and Parameter< T >.value.
{
         int code = 31 * super.hashCode();
         if (value != null) code +=   value.hashCode();
         if (unit  != null) code += 31*unit.hashCode();
         return code ^ (int)serialVersionUID;
     }
intValue()
int intValue () throws IllegalStateException
Returns the positive integer value of an operation parameter, usually used for a count.
An integer value does not have an associated unit of measure.
Returns
The numeric value represented by this parameter after conversion to type
int
.
Exceptions
InvalidParameterTypeException if the value is not an integer type.
IllegalStateException if the value is not defined and there is no default value.
See also
setValue(int)
intValueList()
References AbstractParameter.descriptor, Parameter< T >.doubleValue(), Errors.format(), Parameter< T >.getClassTypeError(), AbstractParameter.getName(), Parameter< T >.getValue(), and Errors.Keys.NoParameter_1.
{
         final T value = getValue();
         if (value instanceof Number) {
             final int integer = ((Number) value).intValue();
             if (integer == ((Number) value).doubleValue()) {
                 return integer;
             }
         }
         final String name = getName(descriptor);
         if (value == null) {
             throw new IllegalStateException(Errors.format(Errors.Keys.NoParameter_1, name));
         }
         throw new InvalidParameterTypeException(getClassTypeError(), name);
     }
intValueList()
int [] intValueList () throws IllegalStateException
Returns an ordered sequence of two or more integer values of an operation parameter list, usually used for counts.
These integer values do not have an associated unit of measure.
Returns
The sequence of values represented by this parameter.
Exceptions
InvalidParameterTypeException if the value is not an array of
int
s.
IllegalStateException if the value is not defined and there is no default value.
See also
setValue(Object)
intValue()
References AbstractParameter.descriptor, Errors.format(), Parameter< T >.getClassTypeError(), AbstractParameter.getName(), Parameter< T >.getValue(), Errors.Keys.NoParameter_1, and Parameter< T >.value.
{
         final T value = getValue();
         if (value instanceof int[]) {
             return (int[]) value;
         }
         final String name = getName(descriptor);
         if (value == null) {
             throw new IllegalStateException(Errors.format(Errors.Keys.NoParameter_1, name));
         }
         throw new InvalidParameterTypeException(getClassTypeError(), name);
     }
removeChangeListener()
void removeChangeListener (final ChangeListener listener) inherited
Removes the specified listener from the list of objects to inform when the value changed.
Parameters
listener The listener to remove.
{
         listeners = Listeners.removeListener(listener, listeners);
     }
setSafeValue()
void setSafeValue (final T value, final Unit<?> unit) protected
Invoked by all.
setXXX()
methods after the argument has been verified to be safe. Subclasses can override this method if they want to perform more processing on the value before its storage, or to be notified about value changes.
Parameters
value The new parameter value, or
null
for removing the value currently set.
unit The unit associated to the new parameter value, or
null
.
Since
3.20
References AbstractParameterValue< T >.fireValueChanged(), Parameter< T >.unit, and Parameter< T >.value.
Referenced by Parameter< T >.setValue().
{
         this.value = value;
         this.unit  = unit;
         fireValueChanged();
     }
setValue() [1/6]
void setValue (final double value, final Unit<?> unit) throws InvalidParameterValueException
Sets the parameter value as a floating point and its associated unit.
The default implementation verifies the argument validity, then invokes setSafeValue(Object, Unit).
Parameters
value The parameter value.
unit The unit for the specified value.
Exceptions
InvalidParameterValueException if the floating point type is inappropriate for this parameter, or if the value is illegal for some other reason (for example a value out of range).
See also
setValue(double)
#doubleValue(Unit)
References AbstractParameter.descriptor, AbstractParameter.ensureValidValue(), Errors.format(), AbstractParameter.getUnitMessageID(), Errors.Keys.IncompatibleUnit_1, Parameter< T >.setSafeValue(), Parameter< T >.unit, AbstractParameter.unitlessParameter(), and Parameter< T >.value.
Referenced by Parameter< T >.Parameter(), and Parameter< T >.setValue().
{
         ensureNonNull("unit", unit);
         @SuppressWarnings("unchecked") // Checked by constructor.
         final ParameterDescriptor<T> descriptor = (ParameterDescriptor<T>) this.descriptor;
         final Unit<?> targetUnit = descriptor.getUnit();
         if (targetUnit == null) {
             throw unitlessParameter(descriptor);
         }
         final short expectedID = getUnitMessageID(targetUnit);
         if (getUnitMessageID(unit) != expectedID) {
             throw new InvalidParameterValueException(Errors.format(expectedID, unit),
                       descriptor.getName().getCode(), value);
         }
         final Double converted;
         try {
             converted = unit.getConverterToAny(targetUnit).convert(value);
         } catch (IncommensurableException e) {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.IncompatibleUnit_1, unit), e);
         }
         ensureValidValue(descriptor, converted);
         /*
          * Really store the original value, not the converted one, because we store the given
          * unit as well. Conversions will be applied on the fly by the getter method if needed.
          */
         setSafeValue(descriptor.getValueClass().cast(value), unit);
     }
setValue() [2/6]
void setValue (final double value) throws InvalidParameterValueException
Sets the parameter value as a floating point.
The unit, if any, stay unchanged. The default implementation verifies the argument validity, then invokes setSafeValue(Object, Unit).
Parameters
value The parameter value.
Exceptions
InvalidParameterValueException if the floating point type is inappropriate for this parameter, or if the value is illegal for some other reason (for example a value out of range).
See also
#setValue(double,Unit)
doubleValue()
References AbstractParameter.descriptor, AbstractParameter.ensureValidValue(), and Parameter< T >.setSafeValue().
{
         setSafeValue(ensureValidValue((ParameterDescriptor<T>) descriptor, Double.valueOf(value)), unit);
         // Really 'unit', not 'getUnit()' since units are not expected to be involved in this method.
         // We just want the current unit setting to be unchanged.
     }
setValue() [3/6]
void setValue (final int value) throws InvalidParameterValueException
Sets the parameter value as an integer.
The default implementation performs a choice based on the ParameterDescriptor::getValueClass() value class}:
If the value type is
Float.class
or
Double.class
, then this method delegates to setValue(double).
Otherwise this method verifies the argument validity, then invokes setSafeValue(Object, Unit).
Parameters
value The parameter value.
Exceptions
InvalidParameterValueException if the integer type is inappropriate for this parameter, or if the value is illegal for some other reason (for example a value out of range).
See also
intValue()
References AbstractParameter.descriptor, AbstractParameter.ensureValidValue(), Parameter< T >.setSafeValue(), Parameter< T >.setValue(), Parameter< T >.unit, and Parameter< T >.value.
{
         @SuppressWarnings("unchecked") // Checked by constructor.
         final ParameterDescriptor<T> descriptor = (ParameterDescriptor<T>) this.descriptor;
         final Class<T> type = descriptor.getValueClass();
         if (type == Double.class || type == Float.class) {
             setValue((double) value);
         } else {
             setSafeValue(ensureValidValue(descriptor, Integer.valueOf(value)), unit);
             // Really 'unit', not 'getUnit()' since we don't expect units in this context.
             // We just want the current unit setting to be unchanged as a paranoiac safety.
         }
     }
setValue() [4/6]
void setValue (final boolean value) throws InvalidParameterValueException
Sets the parameter value as a boolean.
The default implementation verifies the argument validity, then invokes setSafeValue(Object, Unit).
Parameters
value The parameter value.
Exceptions
InvalidParameterValueException if the boolean type is inappropriate for this parameter.
See also
booleanValue()
References AbstractParameter.descriptor, AbstractParameter.ensureValidValue(), Parameter< T >.setSafeValue(), Parameter< T >.unit, and Parameter< T >.value.
{
         setSafeValue(ensureValidValue(((ParameterDescriptor<T>) descriptor), Boolean.valueOf(value)), unit);
         // Really 'unit', not 'getUnit()' since we don't expect units in this context.
         // We just want the current unit setting to be unchanged as a paranoiac safety.
     }
setValue() [5/6]
void setValue (final Object value) throws InvalidParameterValueException
Sets the parameter value as an object.
The object type is typically a Double, Integer, Boolean, String, URI,
double[]
or
int[]
.
The default implementation verifies the argument validity, then invokes setSafeValue(Object, Unit).
Parameters
value The parameter value, or
null
to restore the default value.
Exceptions
InvalidParameterValueException if the type of
value
is inappropriate for this parameter, or if the value is illegal for some other reason (for example the value is numeric and out of range).
See also
getValue()
References AbstractParameter.descriptor, AbstractParameter.ensureValidValue(), Parameter< T >.setSafeValue(), Parameter< T >.unit, and Parameter< T >.value.
{
         setSafeValue(ensureValidValue((ParameterDescriptor<T>) descriptor, value), unit);
         // Really 'unit', not 'getUnit()' since we don't expect units in this context.
         // We just want the current unit setting to be unchanged as a paranoiac safety.
     }
setValue() [6/6]
void setValue (double [] values, final Unit<?> unit) throws InvalidParameterValueException
Sets the parameter value as an array of floating point and their associated unit.
The default implementation verifies the argument validity, then invokes setSafeValue(Object, Unit).
Parameters
values The parameter values.
unit The unit for the specified value.
Exceptions
InvalidParameterValueException if the floating point type is inappropriate for this parameter, or if the value is illegal for some other reason (for example a value out of range).
References AbstractParameter.descriptor, AbstractParameter.ensureValidValue(), Errors.format(), AbstractParameter.getUnitMessageID(), Errors.Keys.IncompatibleUnit_1, Parameter< T >.setSafeValue(), Parameter< T >.unit, and AbstractParameter.unitlessParameter().
{
         ensureNonNull("unit", unit);
         @SuppressWarnings("unchecked") // Checked by constructor.
         final ParameterDescriptor<T> descriptor = (ParameterDescriptor<T>) this.descriptor;
         final Unit<?> targetUnit = descriptor.getUnit();
         if (targetUnit == null) {
             throw unitlessParameter(descriptor);
         }
         final short expectedID = getUnitMessageID(targetUnit);
         if (getUnitMessageID(unit) != expectedID) {
             throw new IllegalArgumentException(Errors.format(expectedID, unit));
         }
         final double[] converted = values.clone();
         final UnitConverter converter;
         try {
             converter = unit.getConverterToAny(targetUnit);
         } catch (IncommensurableException e) {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.IncompatibleUnit_1, unit), e);
         }
         for (int i=0; i<converted.length; i++) {
             converted[i] = converter.convert(converted[i]);
         }
         setSafeValue(ensureValidValue(descriptor, converted), unit);
     }
stringValue()
String stringValue () throws IllegalStateException
Returns the string value of an operation parameter.
A string value does not have an associated unit of measure.
Returns
The string value represented by this parameter.
Exceptions
InvalidParameterTypeException if the value is not a string.
IllegalStateException if the value is not defined and there is no default value.
See also
getValue()
setValue(Object)
References AbstractParameter.descriptor, Errors.format(), Parameter< T >.getClassTypeError(), AbstractParameter.getName(), Parameter< T >.getValue(), and Errors.Keys.NoParameter_1.
{
         final T value = getValue();
         if (value instanceof CharSequence) {
             return value.toString();
         }
         final String name = getName(descriptor);
         if (value == null) {
             throw new IllegalStateException(Errors.format(Errors.Keys.NoParameter_1, name));
         }
         throw new InvalidParameterTypeException(getClassTypeError(), name);
     }
unitlessParameter()
static IllegalStateException unitlessParameter (final GeneralParameterDescriptor descriptor) static protected inherited
Returns an exception initialized with a "Unitless parameter" error message for the specified descriptor.
References Errors.format(), AbstractParameter.getName(), and Errors.Keys.UnitlessParameter_1.
Referenced by Parameter< T >.doubleValue(), Parameter< T >.doubleValueList(), and Parameter< T >.setValue().
{
         return new IllegalStateException(Errors.format(
                 Errors.Keys.UnitlessParameter_1, getName(descriptor)));
     }
valueFile()
URI valueFile () throws IllegalStateException
Returns a reference to a file or a part of a file containing one or more parameter values.
When referencing a part of a file, that file must contain multiple identified parts, such as an XML encoded document. Furthermore, the referenced file or part of a file can reference another part of the same or different files, as allowed in XML documents.
Returns
The reference to a file containing parameter values.
Exceptions
InvalidParameterTypeException if the value is not a reference to a file or an URI.
IllegalStateException if the value is not defined and there is no default value.
See also
getValue()
setValue(Object)
References AbstractParameter.descriptor, Errors.format(), Parameter< T >.getClassTypeError(), AbstractParameter.getName(), Parameter< T >.getValue(), Errors.Keys.NoParameter_1, and Parameter< T >.value.
{
         final T value = getValue();
         if (value instanceof URI) {
             return (URI) value;
         }
         if (value instanceof File) {
             return ((File) value).toURI();
         }
         Exception cause = null;
         try {
             if (value instanceof URL) {
                 return ((URL) value).toURI();
             }
             if (value instanceof String) {
                 return new URI(IOUtilities.encodeURI((String) value));
             }
         } catch (URISyntaxException exception) {
             cause = exception;
         }
         /*
          * Value can't be converted.
          */
         final String name = getName(descriptor);
         if (value == null) {
             throw new IllegalStateException(Errors.format(Errors.Keys.NoParameter_1, name));
         }
         throw new InvalidParameterTypeException(getClassTypeError(), cause, name);
     }
Member Data Documentation
descriptor
final GeneralParameterDescriptor descriptor protected inherited
The abstract definition of this parameter or group of parameters.
Referenced by AbstractParameter.AbstractParameter(), ParameterGroup.addGroup(), Parameter< T >.booleanValue(), Parameter< T >.doubleValue(), Parameter< T >.doubleValueList(), ParameterGroup.ensureValidOccurs(), AbstractParameter.equals(), Parameter< T >.getClassTypeError(), AbstractParameter.getDescriptor(), ParameterGroup.groups(), Parameter< T >.intValue(), Parameter< T >.intValueList(), Parameter< T >.Parameter(), ParameterGroup.parameter(), Parameter< T >.setValue(), Parameter< T >.stringValue(), Parameter< T >.valueFile(), and ParameterGroup.values().
serialVersionUID
final long serialVersionUID = -5837826787089486776L static private
Serial number for inter-operability with different versions.
Referenced by Parameter< T >.hashCode().
unit
Unit<?> unit private
The unit of measure for the value, or.
null
if it doesn't apply. Except for the constructors, the equals(Object) and the hashCode() methods, this field is read only by getUnit() and written by setSafeValue(Object, Unit).
Referenced by Parameter< T >.equals(), Parameter< T >.getUnit(), Parameter< T >.hashCode(), Parameter< T >.setSafeValue(), and Parameter< T >.setValue().
value
T value private
The value, or.
null
if undefined. Except for the constructors, the equals(Object) and the hashCode() methods, this field is read only by getValue() and written by setSafeValue(Object, Unit).
Referenced by Parameter< T >.doubleValueList(), Parameter< T >.equals(), Parameter< T >.getValue(), Parameter< T >.hashCode(), Parameter< T >.intValueList(), Parameter< T >.setSafeValue(), Parameter< T >.setValue(), and Parameter< T >.valueFile().