jena-geo: WKTParsingAuthorityFactory.Parser Class Reference
WKTParsingAuthorityFactory.Parser Class Reference
The WKT parser for this authority factory.
Public Member Functions
Parser ()
Creates the parser.
Protected Member Functions
Map< String,?> complete (Map< String,?> properties)
Adds the authority code to the specified properties, if not already present.
Package Attributes
String code
The authority code for the WKT to be parsed.
Comparable<?> primaryKey
The primary key corresponding to the code.
Detailed Description
The WKT parser for this authority factory.
This parser add automatically the authority code if it was not explicitly specified in the WKT.
Constructor & Destructor Documentation
Parser()
Parser ()
Creates the parser.
{
         }
Member Function Documentation
complete()
Map<String,?> complete (Map< String,?> properties) protected
Adds the authority code to the specified properties, if not already present.
In addition, if a primary key was used for fetching the CRS, adds also that primary key to the list of identifiers.
References WKTParsingAuthorityFactory.authorities, WKTParsingAuthorityFactory.getAuthorities(), WKTParsingAuthorityFactory.getPrimaryKeyAuthority(), and WKTParsingAuthorityFactory.trimAuthority().
{
             final Citation pkAuthority = getPrimaryKeyAuthority();
             final Citation[] authorities;
             final Identifier[] identifiers;
             final Identifier declaredIdentifier =
                     (Identifier) properties.get(IdentifiedObject.IDENTIFIERS_KEY);
             /*
              * If the WKT does not declare explicitly an authority code, we will adds an
              * identifier for all authorities given at construction time. Otherwise we
              * will add an identifier only for the primary key (if there is one).
              */
             if (declaredIdentifier == null) {
                 authorities = getAuthorities();
                 identifiers = new NamedIdentifier[authorities.length];
             } else if (pkAuthority != null) {
                 authorities = new Citation[] {pkAuthority};
                 identifiers = new Identifier[2];
                 identifiers[0] = declaredIdentifier;
             } else {
                 authorities = null;
                 identifiers = null;
             }
             /*
              * Now create an identifier for each authority in the 'authorities' array.
              * Note that the 'identifiers' array may be longer, in which case the first
              * elements are assumed already initialized.
              */
             if (authorities != null) {
                 String trimmedCode = null, pkCode = null;
                 final int offset = identifiers.length - authorities.length;
                 for (int i=0; i<authorities.length; i++) {
                     final String ci;
                     final Citation authority = authorities[i];
                     if (pkAuthority == null || pkAuthority.equals(authority)) {
                         if (pkCode == null) {
                             pkCode = primaryKey.toString();
                         }
                         ci = pkCode;
                     } else {
                         if (trimmedCode == null) {
                             trimmedCode = trimAuthority(code);
                         }
                         ci = trimmedCode;
                     }
                     identifiers[i + offset] = new NamedIdentifier(authority, ci);
                 }
                 final Map<String,Object> modified = new HashMap<>(properties);
                 modified.put(IdentifiedObject.IDENTIFIERS_KEY, identifiers);
                 properties = modified;
             }
             return super.complete(properties);
         }
Member Data Documentation
code
String code package
The authority code for the WKT to be parsed.
This is the code provided by the user to the WKTParsingAuthorityFactory#createCoordinateReferenceSystem(String) method.
Referenced by WKTParsingAuthorityFactory.getWKT().
primaryKey
Comparable<?> primaryKey package
The primary key corresponding to the code.
For PropertyAuthorityFactory, this is equals to code. For DirectPostgisFactory, this is an Integer obtained from the
srid
column.
Referenced by WKTParsingAuthorityFactory.getWKT().