jena-geo: Search1D Class Reference
Search1D Class Reference
Table sans interpolation.
Public Member Functions
void clear ()
Oublie toutes références vers les données.
final double interpolate (final double xi) throws ExtrapolationException
Renvoie la valeur de y interpolée au x spécifié.
final double interpolateAt (final int index) throws ExtrapolationException
Renvoie la valeur de y interpolée au x qui se trouve à l'index spécifié.
final double [] interpolateNaN (final double dxStart, final double dxStop, double yi[])
Interpole les NaN trouvés dans le vecteur des y.
double [] interpolateNaN (final double dxStart, final double dxStop)
Interpole les NaN trouvés dans le vecteur des y, en les remplaçant directement dans le vecteur des y si possible.
final double [] interpolateInPlaceNaN (final double dxStart, final double dxStop)
Interpole les NaN trouvés dans le vecteur des y, en les remplaçant directement dans le vecteur des y sans créer de vecteur temporaire.
final boolean locate (final double xi, final int index[])
Trouve l'index de la valeur xi dans le vecteur des x et renvoie dans le tableu index les index qui y correspondent.
void setData (final double[] x, final double[] y) throws MismatchedSizeException
Définies les vecteurs x et y de cette table.
void recompute ()
Signale à la table que des données du vecteurs des x ou du vecteur des y ont été changées.
boolean ignoreNaN (final boolean ignore)
Indique si les interpolations devront ignorer les NaN dans le vecteur des y.
Protected Member Functions
double interpolate (final double xi, final boolean reuseIndex) throws ExtrapolationException
Interpole y en utilisant les données qui apparaissent aux index klo et khi.
final void copyIndexInto (final int index[])
Copie dans le tableau spécifié en argument la valeur des champs klo et khi.
final boolean validateIndex (final int index[], final double y[])
Ajuste les index spécifiés de façon à ce qu'ils ne pointent vers aucune donnée NaN.
final boolean validateIndex (final double y[]) throws ExtrapolationException
Ajuste les index klo et khi de façon à ce qu'ils pointent vers des données valides.
Protected Attributes
int klo
Position de la dernière donnée trouvée, de sorte que xi est entre x[klo] et x[khi].
boolean ignoreYNaN
Indique aux méthodes interpole qu'elles devront ignorer les NaN dans le vecteur des y.
double [] x
Vecteurs des x de cette table.
double y []
Vecteurs des y de cette table.
Package Functions
final void throwArrayIndexOutOfBoundsException (final int n) throws ArrayIndexOutOfBoundsException
Lance une exception indiquant qu'on a pas trouvé suffisament de données valides dans le vecteur des x ou des y.
Package Attributes
int khi
Private Member Functions
final boolean locate (final double xi)
Trouve les index des valeurs du vecteur des x qui englobent la valeur spécifiée.
final void locateAt (final int index) throws ExtrapolationException
Positionne les index klo et khi autour de l'index spécifié.
double getInterval (final int lower, final int upper)
Renvoie la plage dx que couvrent les données entre les deux index spécifiés.
Detailed Description
Table sans interpolation.
L'appel de la méthode interpolate de cette classe se contente de retourner la valeur y correspondant au x le plus proche de celui qui a été demandé (xi). Cette classe offre des outils de recherche qui seront utilisées par les classes dérivées pour implémenter des interpolations.
Version
1.0
Author
Martin Desruisseaux
Member Function Documentation
clear()
void clear ()
Oublie toutes références vers les données.
Vous pouvez appeller cette méthode lorsque vous en avez terminé avec les interpolations et que vous voulez laisser le nettoyeur faire son travail.
Implements Extrapolation.
{
         super.clear();
         klo = 0;
         khi = 0;
     }
copyIndexInto()
final void copyIndexInto (final int index[]) protected
Copie dans le tableau spécifié en argument la valeur des champs klo et khi.
Ce tableau peut avoir diverses longueurs. Un cas typique est lorsque qu'il a une longueur de 2. Alors le champs klo sera simplement copié dans index[0] et khi dans index[1]. Si le tableau à une longueur de 1, alors seul klo sera copié dans index[0]. Si le tableau à une longueur de 0, rien ne sera fait.
Les cas le plus intéressants se produisent lorsque le tableau index à une longueur de 3 et plus. Cette méthode écrira klo et khi au milieu de ce tableau, puis complètera les autres cellules avec la suite des index qui pointent vers des valeurs autres que NaN. Par exemple si le vecteur des x contient:
[5 8 NaN 12 NaN 19 21 34]
Alors l'appel de la méthode locate(15) donnera aux champs klo et khi les valeurs 3 et 5 respectivement, de sorte que x[3] < 15 < x[5]. Si vous souhaitez effectuer une interpolation polynomiale d'ordre 4 autour de ces données, vous pouvez ensuite écrire:
int index[]=new int[4];
copyIndexInto(index);
Le tableau index contiendra alors [1 3 5 6].
Cette méthode fonctionne correctement même si les index klo et khi pointait vers le début au à la fin du vecteur des x. Notez toutefois qu'après l'appel de cette méthode, les index klo et khi auront une valeur indéterminée.
Parameters
index tableau dans lequel copier les champs klo et khi.
Exceptions
ArrayIndexOutOfBoundsException s'il n'y a pas suffisament de données valides.
See also
locate(double)
validateIndex(int[], double[])
References Search1D.khi, Search1D.klo, Table1D.throwArrayIndexOutOfBoundsException(), and Table1D.x.
Referenced by Polynomial1D.interpolate(), and Search1D.locate().
{
         final int xlength = x.length;
         int center = index.length;
         if (center >= 2) {
             center >>= 1;
             int i = center;
             /*
              *  Si khi et klo sont identiques, on n'écrira pas klo afin de ne
              *  pas répéter deux fois le même index. On écrira seulement khi.
              *  La boucle 'loop' copie au début du tableau 'index' les index
              *  qui précèdent klo.
              */
             if (khi != klo) {
                 index[--i] = klo;
             }
             loop:
             while (i > 0) {
                 do {
                     if (--klo < 0) {
                         center -= i;
                         System.arraycopy(index, i, index, 0, center);
                         break loop;
                     }
                 } while (Double.isNaN(x[klo]));
                 index[--i] = klo;
             }
             /*
              *  La boucle suivante copie khi et les index qui le suivent dans
              *  le tableau 'index'. Si on a atteint la fin des données sans
              *  avoir réussi à copier tous les index, on décalera vers la droite
              *  les index qui ont été copié et on tentera de combler le trou créé
              *  à gauche en copiant d'autres index qui précédaient klo.
              */
             i = center;
             index[i++] = khi;
             loop:
             while (i < index.length) {
                 do {
                     if (++khi >= xlength) {
                         int remainder = index.length - i;
                         // center += remainder; // (not needed)
                         System.arraycopy(index, 0, index, remainder, i);
                         i = remainder;
                         do {
                             do {
                                 if (--klo < 0) {
                                     throwArrayIndexOutOfBoundsException(index.length);
                                 }
                             } while (Double.isNaN(x[klo]));
                             index[--i] = klo;
                         } while (i > 0);
                         break loop;
                     }
                 } while (Double.isNaN(x[khi]));
                 index[i++] = khi;
             }
         } else if (center > 0) {
             index[0] = klo;
         }
     }
getInterval()
double getInterval (final int lower, final int upper) private
Renvoie la plage dx que couvrent les données entre les deux index spécifiés.
Cette plage est mesurée à partir de l'espace qui se trouve entre deux données, comme dans le dessin ci-dessous.
            lower       upper
             |           |
146   148   150   152   154   156   158
          |                 |
          ^------plage------^
Les exemples suivants supposent que vos données sont échantillonées aux heures:
getInterval(20,20) retournerait 1 heure.
getInterval(17,18) retournerait 2 heures.
getInterval(30,34) retournerait 5 heures.
Il n'est pas obligatoire que l'intervalle d'échantillonnage soit constant. Cette méthode utilisera une interpolation linéaire lorsqu'il y a des NaN.
Parameters
lower index de la première donnée de la plage.
upper index de la dernière donnée de la plage.
Returns
intervalle dx entre ces deux index.
References Table1D.x.
Referenced by Search1D.interpolateNaN().
{
         int k0, k1;
         /*
          *  Repère les index pointant vers les données à utiliser pour le calcul
          *  de l'intervalle. En l'absence de NaN on obtient:
          *
          *      klo0 = lower            khi0 = upper
          *      klo1 = klo0-1           khi1 = upper+1
          *
          *  Le schema ci-dessous donne un exemple de la façon dont se comporte
          *  le code en la présence de NaN pour des "lower" et "upper" donnés.
          *
          *                         lower          upper
          *                           |              |
          *      140  145  150  NaN  160  165  170  NaN  180  185  190
          *                 ^         ^         ^         ^
          *                k1        k0         k0        k1
          */
         k0 = k1 = lower;
         final int xlength = x.length;
         while (Double.isNaN(x[k0])) {
             if (++k0 >= xlength) {
                 return Double.NaN;
             }
         }
         do {
             if (--k1 < 0) {
                 k1 = k0;
                 do {
                     if (++k0 >= xlength) {
                         return Double.NaN;
                     }
                 } while (Double.isNaN(x[k0]));
                 break;
             }
         } while (Double.isNaN(x[k1]));
         double x0 = x[k0];
         double xlo = (x[k1] - x0) / (k1 - k0) * (lower - k0 - 0.5) + x0;
         k0 = k1 = upper;
         while (Double.isNaN(x[k0])) {
             if (--k0 < 0) {
                 return Double.NaN;
             }
         }
         do {
             if (++k1 >= xlength) {
                 k1 = k0;
                 do {
                     if (--k0 < 0) {
                         return Double.NaN;
                     }
                 } while (Double.isNaN(x[k0]));
                 break;
             }
         } while (Double.isNaN(x[k1]));
         x0 = x[k0];
         return (x[k1] - x0) / (k1 - k0) * (upper - k0 + 0.5) + x0 - xlo;
     }
ignoreNaN()
boolean ignoreNaN (final boolean ignore) inherited
Indique si les interpolations devront ignorer les NaN dans le vecteur des y.
Par défaut, les NaN ne seront pas ignorés de sorte qu'ils pourront être retournés par la méthode interpolate(double) s'ils apparaissent dans le vecteur des y. Si vous demandez à ignorer les NaN, alors la méthode interpole tentera de toujours utiliser des données valides pour ses calculs. Cette méthode n'a aucun effet sur les vecteur des x. Pour ce dernier, les NaN seront toujours ignorés.
Parameters
ignore true si la méthode interpolate(double) doit agir comme si elle utilisait des copies des données dans lesquelles on avait retiré tout les NaN.
Returns
l'ancien état.
Implements Extrapolation.
References Table1D.ignoreYNaN, Table1D.interpolate(), and Table1D.interpolateAt().
{
         boolean old = ignoreYNaN;
         ignoreYNaN = ignore;
         return old;
     }
interpolate() [1/2]
final double interpolate (final double xi) throws ExtrapolationException
Renvoie la valeur de y interpolée au x spécifié.
Les NaN apparaissant dans le vecteur des x seront ignorés. Ceux qui apparaissent dans le vecteur des y seront aussi ignorés si Table1D#ignoreNaN a été appellée avec l'argument true.
Parameters
xi valeur de x pour laquelle on désire une valeur y.
Returns
valeur interpolée.
Exceptions
ExtrapolationException si une extrapolation non-permise a eu lieu.
Implements Extrapolation.
References Search1D.locate().
Referenced by Search1D.interpolateAt(), and Search1D.interpolateNaN().
{
         if (locate(xi)) {
             return interpolate(xi, false);
         } else {
             throw new ExtrapolationException(xi);
         }
     }
interpolate() [2/2]
double interpolate (final double xi, final boolean reuseIndex) throws ExtrapolationException protected
Interpole y en utilisant les données qui apparaissent aux index klo et khi.
Cette méthode ne doit pas appeller locate car c'est déjà fait. Elle n'est pas non-plus synchronisée pour des raisons de performances.
L'implémentation par défaut de cette méthode retourne simplement la valeur y qui correspond au x le plus proche de celui qui est spécifié. Cette méthode doit être redéfinie par les classes dérivées qui implémenteront des interpolations plus évoluées.
Au moment de l'appel de cette méthode, les NaN ont déjà été pris en compte dans le vecteur des x. Cette méthode doit décider ce qu'elle fait des NaN dans le vecteur des y en consultant le champs Table1D#ignoreYNaN.
Si l'argument reUseIndex est true, alors cette méthode doit réutiliser exactement les mêmes index klo et khi que lors de la dernière interpolation sans chercher à vérifier s'il y a des données manquantes. Cela suppose donc qu'aucune implémentation de cette méthode ne modifie les index dont elle a besoin. Cette aptitude est nécessaire pour éviter qu'une interpolation ne se base sur des données interpolées lorsque l'on interpole plusieurs données consécutives.
Parameters
xi valeur de x pour laquelle on désire une valeur y interpolée.
reuseIndex true s'il faut réutiliser les même index que ceux de la dernière interpolation.
Returns
Valeur y interpolée.
References Table1D.ignoreYNaN, ExtrapolationException.index, Search1D.validateIndex(), Table1D.x, ExtrapolationException.xi, and Table1D.y.
{
         if (ignoreYNaN && !reuseIndex) {
             try {
                 validateIndex(y);
             } catch (ExtrapolationException extrapole) {
                 if (extrapole.index >= 0) {
                     return y[extrapole.index];
                 }
                 extrapole.xi = xi;
                 throw extrapole;
             }
         }
         return y[(Math.abs(x[klo] - xi) <= Math.abs(x[khi] - xi)) ? klo : khi];
     }
interpolateAt()
final double interpolateAt (final int index) throws ExtrapolationException
Renvoie la valeur de y interpolée au x qui se trouve à l'index spécifié.
L'interpolation fera intervenir les valeurs autour de y[index] sans utiliser y[index] lui-même. Les NaN apparaissant dans le vecteur des x seront ignorés. Ceux qui apparaissent dans le vecteur des y seront aussi ignorés si Table1D#ignoreNaN a été appellée avec l'argument true.
Parameters
index de la donnée x pour laquelle on veut interpoller y.
Returns
valeur interpolée.
Exceptions
ExtrapolationException si une extrapolation non-permise a eu lieu.
Implements Extrapolation.
References Search1D.interpolate(), Search1D.locateAt(), and Table1D.x.
{
         locateAt(index);
         return interpolate(x[index], false);
     }
interpolateInPlaceNaN()
final double [] interpolateInPlaceNaN (final double dxStart, final double dxStop)
Interpole les NaN trouvés dans le vecteur des y, en les remplaçant directement dans le vecteur des y sans créer de vecteur temporaire.
Cette méthode peut être plus rapide et plus économe en mémoire que l'autre méthode interpolateNaN(double,double). Elle peut toutefois donner des résultats légèrement différents. Supposons que vous vouliez interpoler les NaN du vecteur suivant en utilisant une interpolation polynomiale d'ordre 4.
8.524 8.473 8.322 NaN NaN NaN 8.163 NaN 8.019 NaN 7.983 7.864 7.931 8.004
Cette méthode interpole toujours les "grappes" de NaN en une étape. Dans cet exemple, les trois premiers NaN seront correctement interpolés en utilisant les valeurs 8.473, 8.322, 8.163 et 8.019. Le quatrième NaN forme une "grappe" à lui tout seul, parce qu'il est entouré de deux données valides. Il sera donc interpolé en une seconde étape. Mais comme la première "grappe" de trois NaN a été interpolée avant lui, l'interpolation du quatrième NaN se fera intervenir le résultat de la dernière interpolation (au lieu de 8.322), 8.163, 8.019 et 7.983.
Des exemples d'interpolations qui sont affectés par cet effet sont Polynomial1D (avec un ordre supérieur à 2) et Hermite1D. Des exemples d'interpolations qui ne sont pas affectés (et n'ont donc pas besoin d'utiliser un vecteur temporaire) sont Search1D, {link Linear1D} et {link Spline1D}. Si la quantité de mémoire disponible n'est pas trop critique, il vaut mieux utiliser la méthode interpolateNaN(double,double), qui décidera elle-même s'il vaux mieux créer un vecteur temporaire ou non.
Parameters
dxStart Plage minimal des x qu'il doit y avoir de chaque côté d'un NaN pour l'interpoler.
dxStop Plage maximal des x couvert par les données manquantes pour qu'elles puissent être interpolées.
Returns
Le tableau des y.
References Search1D.interpolateNaN(), and Table1D.y.
{
         return interpolateNaN(dxStart, dxStop, y);
     }
interpolateNaN() [1/2]
final double [] interpolateNaN (final double dxStart, final double dxStop, double yi[])
Interpole les NaN trouvés dans le vecteur des y.
Les arguments de cette méthode contrôle la façon de décider si des NaN doivent être interpolés ou non. Trois conditions s'appliquent pour qu'une interpolations puissent se faire:
La donnée x correspondant au y à interpoler ne doit pas être NaN.
S'il y a des NaN qui se suivent, ils ne doivent pas former un trou plus grand que dxStop. Par exemple si le vecteur des x représente le temps exprimé en heure et que le vecteur des y représente la température, alors la valeur 4.5 pour l'argument dxStop indiquera à cette méthode qu'elle ne doit pas interpoler les températures à l'intérieur des trous de plus de 4œ heures. Dans le cas de données échantillonées aux demi-heures, cela signifie que s'il y a plus de 9 NaN consécutifs, ceux-ci ne seront pas interpolés.
De chaque côté des NaN, il doit y avoir des données valides représentant une plage d'au moins dxStart. Par exemple si le vecteur des x représente le temps exprimé en heure et que le vecteur des y représente la salinité, alors la valeur 3 pour l'argument dxStart indiquera à cette méthode qu'elle ne peut interpoler la salinité qu'à la condition qu'il y aie au moins 3 heures de données valides de part et d'autres de la donnée manquante (NaN).
Parameters
dxStart Plage minimal des x qu'il doit y avoir de chaque côté d'un NaN pour l'interpoler. Spécifiez 0 si vous ne voulez pas imposer de minimum.
dxStop Plage maximal des x couvert par les données manquantes pour qu'elles puissent être interpolées. Spécifiez Float.POSITIVE_INFINITY pour ne pas imposer de taille maximale (déconseillé!).
yi Tableau dans lequel copier tout les y en remplaçant les NaN par les valeurs interpolés. Ce tableau ne doit pas être plus long que les tableaux x et y spécifiés lors de la construction de la table. Il peut toutefois être plus court. Dans ce cas les interpolations ne se feront que sur les yi.length premières données. Si vous spécifiez null, un tableau sera créé automatiquement avec la longueur nécessaire pour contenir toutes les données.
Returns
Le tableau yi. Si yi était nul, alors le résultat sera soit un tableau nouvellement construit si des données ont été interpolées, ou soit le vecteur des y original si aucune interpolation n'a été faite.
See also
interpolateNaN(double,double)
References Search1D.getInterval(), ExtrapolationException.getMessage(), Table1D.ignoreYNaN, Search1D.interpolate(), Search1D.locateAt(), Table1D.x, and Table1D.y.
Referenced by Search1D.interpolateInPlaceNaN(), and Search1D.interpolateNaN().
{
         boolean toCreate;
         if (yi == null) {
             toCreate = true;
             yi = y;
         } else {
             toCreate = false;
             if (y != yi) {
                 System.arraycopy(y, 0, yi, 0, yi.length);
             }
         }
         boolean oldStatus = ignoreYNaN;
         ignoreYNaN = true;
         try {
             loop:
             for (int index = 0; index < yi.length; index++) {
                 if (!Double.isNaN(y[index]) && !Double.isNaN(x[index])) {
                     while (true) {
                         /*
                          *  Si on entre dans ce bloc, c'est qu'on a ignoré tous les NaN qui se trouvaient
                          *  au début du vecteur (ou d'un segment) et qu'on vient de trouver une donnée
                          *  valide. Il faut maintenant vérifier s'il y a suffisament de données valides
                          *  consécutives pour accepter de reprendre les interpolations.
                          */
                         int begin = index;
                         do {
                             if (++index >= yi.length) {
                                 return yi;
                             }
                         } while (!Double.isNaN(y[index]) && !Double.isNaN(x[index]));
                         if (Math.abs(getInterval(begin, index - 1)) < dxStart) {
                             continue loop;
                         }
                         /*
                          *  Un nombre suffisant de données valides ayant été trouvées, on
                          *  comptera maintenant le nombre de NaN consécutifs qui apparaissent.
                          *  S'il n'y en a trop, l'instruction "break" fera recommencer les 4
                          *  lignes précédentes.
                          */
                         while (true) {
                             int beginNaN = index;
                             do {
                                 if (++index >= yi.length) {
                                     return yi;
                                 }
                             } while (Double.isNaN(y[index]) || Double.isNaN(x[index]));
                             if (Math.abs(getInterval(beginNaN, index - 1)) > dxStop) {
                                 break;
                             }
                             int endNaN = index;
                             /*
                              *  Sachant qu'il n'y a pas trop de données manquantes, on vérifie
                              *  maintenant s'il y a suffisament de données après le trou.
                              */
                             begin = index;
                             while (++index < yi.length && !Double.isNaN(y[index]) && !Double.isNaN(x[index]));
                             if (Math.abs(getInterval(begin, index - 1)) < dxStart) {
                                 continue loop;
                             }
                             /*
                              *  Maintenant que l'on est tout-à-fait rassuré quant au nombre de
                              *  données disponibles, on peut enfin procéder aux interpolations.
                              */
                             locateAt((beginNaN + endNaN) >> 1);
                             boolean reUseIndex = false;
                             while (beginNaN < endNaN) {
                                 if (Double.isNaN(y[beginNaN])) {
                                     double xi = x[beginNaN];
                                     if (!Double.isNaN(xi)) {
                                         if (toCreate) {
                                             toCreate = false;
                                             yi = new double[y.length];
                                             System.arraycopy(y, 0, yi, 0, yi.length);
                                         }
                                         yi[beginNaN] = interpolate(xi, reUseIndex);
                                         reUseIndex = true;
                                     }
                                 }
                                 beginNaN++;
                             }
                         }
                     }
                 }
             }
         } catch (ExtrapolationException exception) {
             throw new IllegalStateException("Unexpected extrapolation: " + exception.getMessage());
         } finally {
             ignoreYNaN = oldStatus;
         }
         return yi;
     }
interpolateNaN() [2/2]
double [] interpolateNaN (final double dxStart, final double dxStop)
Interpole les NaN trouvés dans le vecteur des y, en les remplaçant directement dans le vecteur des y si possible.
Le fait de ne pas avoir à créer de vecteur temporaire peut rendre cette méthode plus rapide et plus économe en mémoire que l'autre méthode interpolateNaN(double,double,double[]).
Si votre vecteur de données est si gros que vous ne pouvez vous permettre de créer de vecteur temporaire, vous pouvez envisager d'utiliser la méthode interpolateInPlaceNaN(double,double).
Note pour les développeurs de classes dérivées:</strong
Les classes dérivées devrait redéfinir cette méthode avec l'une des deux lignes suivantes: return interpolateNaN(dxStart, dxStop, null) s'il est nécessaire d'utiliser un vecteur temporaire (c'est l'implémentation par défaut), ou return interpolateNaN(dxStart, dxStop, y) si ce n'est pas nécessaire.
Parameters
dxStart Plage minimal des x qu'il doit y avoir de chaque côté d'un NaN pour l'interpoler.
dxStop Plage maximal des x couvert par les données manquantes pour qu'elles puissent être interpolées.
Returns
Le tableau des y.
See also
interpolateNaN(double, double, double[])
interpolateInPlaceNaN(double, double)
References Search1D.interpolateNaN().
{
         return interpolateNaN(dxStart, dxStop, null);
     }
locate() [1/2]
final boolean locate (final double xi, final int index[])
Trouve l'index de la valeur xi dans le vecteur des x et renvoie dans le tableu index les index qui y correspondent.
Ce tableau peut avoir une longueur quelconque. Cette méthode tentera de créer une suite d'index, mais en sautant les NaN qui apparaissent dans le vecteur des x ou le vecteur des y. Par exemple supposons que cet objet représente la table suivante:
 index: 0 1 2 3 4  5   6  7
                    X = [2 4 5 7 8 NaN 12 14];
                    Y = [4 7 2 1 6  1  NaN 5];
Alors, si index est un tableau de 4 éléments, locate(10, index) écrira dans ce tableau [2 3 4 7]. Les valeurs 5 et 6 ont été sautées parce que X[5]==NaN et Y[6]==NaN.
Parameters
xi valeur x dont on désire les index.
index tableau dans lequel écrire les index.
Returns
true si l'opération à réussie, false si elle a échouée parce qu'il n'y a pas suffisament de données valides dans les vecteurs X et Y.
References Search1D.copyIndexInto(), Table1D.ignoreYNaN, Search1D.validateIndex(), and Table1D.y.
Referenced by Search1D.interpolate().
{
         if (locate(xi)) {
             copyIndexInto(index);
             if (ignoreYNaN) {
                 validateIndex(index, y);
             }
             return true;
         } else {
             return false;
         }
     }
locate() [2/2]
final boolean locate (final double xi) private
Trouve les index des valeurs du vecteur des x qui englobent la valeur spécifiée.
Cette méthode ajuste la valeurs des champs klo et khi de façon à respecter l'une des conditions suivantes:
x[klo]  < xi <  x[khi]
si les données du vecteur des x sont en ordre croissant.
x[klo]  > xi >  x[khi]
si les données du vecteur des x sont en ordre décroissant.
x[klo] == xi == x[khi]
si une correspondance exacte fut trouvée.
Notez que le dernier cas implique que klo==khi. Si non (c'est-à-dire si le vecteur des x ne contient pas une valeur identique à xi), alors klo sera toujours inférieure à khi.
Mis à part les correspondances exactes, cette méthode produira dans la plupart des cas un résultat tel que khi==klo+1. Si toutefois le vecteur des x contient des NaN, alors l'écart entre klo et khi peut être plus grand. En effet, cette méthode s'efforce de faire pointer les index klo et khi vers des données valides.
Exemples: Supposons que le vecteur des x contient les données suivantes:
[4 9 12 NaN NaN 34 56 76 89]
Alors,
locate(9)
donnera klo=1 et khi=1.
locate(60)
donnera klo=6 et khi=7.
locate(20)
donnera klo=2 et khi=5.
Si les données du vecteur des x ne sont pas en ordre croissant ou décroissant, alors cette méthode produira un résultat indéterminé. En particulier, elle peut tomber dans une boucle infinie.
Parameters
xi valeur à rechercher dans le vecteur des x.
Returns
true si la valeur spécifiée est comprise dans la plage du vecteur des x. false si elle se trouve en dehors ou si le vecteur n'a pas suffisamment de données autres que NaN.
See also
klo
khi
copyIndexInto(int[]);
References Search1D.khi, Search1D.klo, and Table1D.x.
{
         klo = 0;
         khi = x.length - 1;
         while (klo <= khi) {
             double x_klo = x[klo];
             double x_khi = x[khi];
             if (x_klo < xi && xi < x_khi) {
                 /*
                  * Recherche l'index de la donnée xi dans
                  * un vecteur des x en ordre croissant.
                  */
                 loop:
                 while (khi - klo > 1) {
                     int k = (khi + klo) >> 1;
                     double xk = x[k];
                     if (xi < xk) {
                         khi = k;
                         continue loop;
                     }
                     if (xi > xk) {
                         klo = k;
                         continue loop;
                     }
                     if (xi == xk) {
                         klo = khi = k;
                         break loop;
                     }
                     /*
                      *  Le code suivant ne sera exécuté que si l'on vient de tomber sur un NaN.
                      *  Le "+1" de la ligne suivante n'existe que pour forcer un arrondissement
                      *  vers le haut dans la division par 2. Exemple: avec klo=1 et khi=5, on a
                      *  k=3 et kmax=2. Le code précédent avait examiné x[3], et le code suivant
                      *  examinera x[2] et x[4].
                      */
                     int kmax = (khi - klo + 1) >> 1;
                     for (int i = 1; i < kmax; i++) {
                         int ki = k + i;
                         xk = x[ki];
                         if (xi < xk && ki < khi) {
                             khi = ki;
                             continue loop;
                         }
                         if (xi > xk && ki > klo) {
                             klo = ki;
                             continue loop;
                         }
                         if (xi == xk) {
                             klo = khi = ki;
                             break loop;
                         }
                         ki = k - i;
                         xk = x[ki];
                         if (xi < xk && ki < khi) {
                             khi = ki;
                             continue loop;
                         }
                         if (xi > xk && ki > klo) {
                             klo = ki;
                             continue loop;
                         }
                         if (xi == xk) {
                             klo = khi = ki;
                             break loop;
                         }
                     }
                     break loop;
                 }
                 return true;
             }
             if (x_klo > xi && xi > x_khi) {
                 /*
                  * Recherche l'index de la donnée xi dans
                  * un vecteur des x en ordre décroissant.
                  */
                 loop:
                 while (khi - klo > 1) {
                     int k = (khi + klo) >> 1;
                     double xk = x[k];
                     if (xi > xk) {
                         khi = k;
                         continue loop;
                     }
                     if (xi < xk) {
                         klo = k;
                         continue loop;
                     }
                     if (xi == xk) {
                         klo = khi = k;
                         break loop;
                     }
                     /*
                      *  Le code suivant ne sera exécuté que si l'on vient de tomber sur un NaN.
                      *  Le "+1" de la ligne suivante n'existe que pour forcer un arrondissement
                      *  vers le haut dans la division par 2. Exemple: avec klo=0 et khi=5, on a
                      *  k=2 et kmax=3. Le code précédent avait examiné x[2], et le code suivant
                      *  examinera x[0],x[1] ainsi que x[3],x[4].
                      */
                     int kmax = (khi - klo + 1) >> 1;
                     for (int i = 1; i < kmax; i++) {
                         int ki = k + i;
                         xk = x[ki];
                         if (xi > xk && ki < khi) {
                             khi = ki;
                             continue loop;
                         }
                         if (xi < xk && ki > klo) {
                             klo = ki;
                             continue loop;
                         }
                         if (xi == xk) {
                             klo = khi = ki;
                             break loop;
                         }
                         ki = k - i;
                         xk = x[ki];
                         if (xi > xk && ki < khi) {
                             khi = ki;
                             continue loop;
                         }
                         if (xi < xk && ki > klo) {
                             klo = ki;
                             continue loop;
                         }
                         if (xi == xk) {
                             klo = khi = ki;
                             break loop;
                         }
                     }
                     break loop;
                 }
                 return true;
             }
             /*
              * Cas où xi se trouve à la limite ou en dehors
              * du vecteur des x, ou que l'on a des NaN.
              */
             if (x_klo == xi) {
                 khi = klo;
                 return true;
             }
             if (x_khi == xi) {
                 klo = khi;
                 return true;
             }
             if (Double.isNaN(xi)) {
                 break;
             }
             if (!Double.isNaN(x_klo) && !Double.isNaN(x_khi)) {
                 break;
             }
             while (klo <= khi && Double.isNaN(x[klo])) {
                 klo++;
             }
             while (khi >= klo && Double.isNaN(x[khi])) {
                 khi--;
             }
         }
         return false;
     }
locateAt()
final void locateAt (final int index) throws ExtrapolationException private
Positionne les index klo et khi autour de l'index spécifié.
Si le vecteur des x ne contient pas de NaN, alors klo sera égal à index-1 et khi sera égal à index+1. Si le vecteur des x contient des NaN, alors klo sera un peu plus bas et/ou khi un peu plus haut.
Parameters
index index autour duquel on veut se positionner.
Exceptions
ExtrapolationException si les index tombent en dehors des limites du vecteur des x.
See also
#validateIndex(float[])
References Table1D.x.
Referenced by Search1D.interpolateAt(), and Search1D.interpolateNaN().
{
         klo = khi = index;
         final int length = x.length;
         do {
             if (++khi >= length) {
                 do {
                     if (--klo < 0) {
                         throw new ExtrapolationException();
                     }
                 } while (Double.isNaN(x[klo]));
                 throw new ExtrapolationException(+1, klo);
             }
         } while (Double.isNaN(x[khi]));
         do {
             if (--klo < 0) {
                 throw new ExtrapolationException(-1, khi);
             }
         } while (Double.isNaN(x[klo]));
     }
recompute()
void recompute () inherited
Signale à la table que des données du vecteurs des x ou du vecteur des y ont été changées.
Certains types d'interpolations telle que l'interpolation cubique B-Spline ont besoin de savoir s'ils doivent recalculer leurs champs internes. L'implémentation par défaut ne fait rien.
Implements Extrapolation.
Referenced by Table1D.setData().
{
     }
setData()
void setData (final double [] x, final double [] y) throws MismatchedSizeException inherited
Définies les vecteurs x et y de cette table.
Exceptions
MismatchedSizeException si les deux vecteurs n'ont pas la même longueur.
Implements Extrapolation.
References Table1D.recompute(), Table1D.x, and Table1D.y.
{
         this.x = x;
         this.y = y;
         if (x.length != y.length) {
             throw new MismatchedSizeException(); // TODO: Localize
         }
         this.x = x;
         recompute();
     }
throwArrayIndexOutOfBoundsException()
final void throwArrayIndexOutOfBoundsException (final int n) throws ArrayIndexOutOfBoundsException package inherited
Lance une exception indiquant qu'on a pas trouvé suffisament de données valides dans le vecteur des x ou des y.
Cette méthode est appellée entre autre par la méthode copyIndexInto en cas d'erreur.
Cette méthode appelle toujours clearData afin de libérer la mémoire occupée par certains tableaux temporaires, comme le vecteur de dérivés secondes dans Spline.
Parameters
n nombre minimal de données valides qui étaient nécessaires.
Exceptions
ArrayIndexOutOfBoundsException toujours lancée avec un message appropriée.
Referenced by Spline1D.constructY2(), Search1D.copyIndexInto(), and Search1D.validateIndex().
{
         // TODO: Localize
         throw new ArrayIndexOutOfBoundsException("Il fallait " + n + " données valides, ce qui n'a pas été trouvé.");
     }
validateIndex() [1/2]
final boolean validateIndex (final int index[], final double y[]) protected
Ajuste les index spécifiés de façon à ce qu'ils ne pointent vers aucune donnée NaN.
Ces index sont habituellement obtenus par la méthode copyIndexInto.
Supposons que vous vous apprêtez à faire une interpolation polynomiale d'ordre 4 autour de la donnée x=84. Supposons qu'avec les méthodes locate et copyIndexInto, vous ayiez obtenu les index [4 5 6 7]. La valeur 84 se trouverait typiquement entre x[5] et x[6]. Maintenant supposons que votre vecteur des y contienne les données suivantes:
y=[5 3 1 2 7 NaN 12 6 4 ...etc...]
Vous voulez vous assurez que les index obtenus par copyIndexInto pointent tous vers une donnée y valide. Après avoir appellé la méthode
validateIndex(index, y)
vos index [4 5 6 7] deviendront [3 4 6 7], car y[5] avait pour valeur NaN. Notez que vous n'avez pas à vous préocupper de savoir si les index pointent vers des x valides. Ça avait déjà été assuré par copyIndexInto et continuera à être assuré par validateIndex.
Voici un exemple d'utilisation. Supposons que trois vecteurs de données (Y1, Y2 et Y3) se partagent le même vecteur des x (X). Supposons que vous souhaitez obtenir 4 index valides simultanément pour tous les vecteurs autour de x=1045. Vous pourriez écrire:
 locate(1045);
 int index[]=new int[4];
 copyIndexIntoArray(index);
 boolean hasChanged=false;
 do
 {
     hasChanged |= validateIndex(index, Y1);
     hasChanged |= validateIndex(index, Y2);
     hasChanged |= validateIndex(index, Y3);
 }
 while (hasChanged);
S'il n'est pas nécessaire que les index soient valides pour tous les vecteurs simultanément, vous pourriez copier les éléments de index dans un tableau temporaire après l'appel de copyIndexInto. Il vous suffira alors de restituer cette copie avant chaque appel de validateIndex pour chacun des vecteurs Y. En réutilisant cette copie, vous évitez d'appeller trois fois locate et y gagnez ainsi un peu en vitesse d'éxecution.
Parameters
index A l'entrée, tableau d'index à vérifier. A la sortie, tableau d'index modifiés. Cette méthode s'efforce autant que possible de ne pas modifier les index se trouvant au centre de ce tableau.
y Vecteur des données y servant à la vérification.
Returns
true si des changements ont été fait, false sinon.
Exceptions
ArrayIndexOutOfBoundsException s'il n'y a pas suffisament de données valides.
See also
locate(double)
copyIndexInto(int[])
References Search1D.khi, Search1D.klo, Table1D.throwArrayIndexOutOfBoundsException(), and Table1D.x.
Referenced by Linear1D.interpolate(), Polynomial1D.interpolate(), Spline1D.interpolate(), Hermite1D.interpolate(), Search1D.interpolate(), and Search1D.locate().
{
         boolean hasChanged = false;
         final int xlength = x.length;
         int center = index.length >> 1;
         loop:
         for (int i = center; --i >= 0;) {
             if (Double.isNaN(y[index[i]])) {
                 /*
                  *  Ce bloc ne sera exécuté que si un NaN a été trouvé (sinon cette méthode sera
                  *  exécutée rapidement car elle n'aurait pratiquement rien à faire). La prochaine
                  *  boucle décale les index qui avaient déjà été trouvés (par 'copyIndexInto') de
                  *  façon à exclure les NaN. L'autre boucle va chercher d'autre index, de la même
                  *  façon que 'copyIndexInto' s'y prenait.
                  */
                 hasChanged = true;
                 for (int j = i; --j >= 0;) {
                     if (!Double.isNaN(y[index[j]])) {
                         index[i--] = index[j];
                     }
                 }
                 int klo = index[0];
                 do {
                     do {
                         if (--klo < 0) {
                             center -= ++i;
                             System.arraycopy(index, i, index, 0, index.length - i);
                             break loop;
                         }
                     } while (Double.isNaN(x[klo]) || Double.isNaN(y[klo]));
                     index[i--] = klo;
                 } while (i >= 0);
                 break loop;
             }
         }
         /*
          *  Le code suivant fait la même opération que le code précédent,
          *  mais pour la deuxième moitié des index.
          */
         loop:
         for (int i = center; i < index.length; i++) {
             if (Double.isNaN(y[index[i]])) {
                 hasChanged = true;
                 for (int j = i; ++j < index.length;) {
                     if (!Double.isNaN(y[index[j]])) {
                         index[i++] = index[j];
                     }
                 }
                 int khi = index[index.length - 1];
                 do {
                     do {
                         if (++khi >= xlength || khi >= y.length) {
                             int remainder = index.length - i;
                             // center += remainder; // (not needed)
                             System.arraycopy(index, 0, index, remainder, i);
                             i = remainder;
                             int klo = index[0];
                             do {
                                 do {
                                     if (--klo < 0) {
                                         throwArrayIndexOutOfBoundsException(index.length);
                                     }
                                 } while (Double.isNaN(x[klo]) || Double.isNaN(y[klo]));
                                 index[--i] = klo;
                             } while (i > 0);
                             break loop;
                         }
                     } while (Double.isNaN(x[khi]) || Double.isNaN(y[khi]));
                     index[i++] = khi;
                 } while (i < index.length);
                 break loop;
             }
         }
         return hasChanged;
     }
validateIndex() [2/2]
final boolean validateIndex (final double y[]) throws ExtrapolationException protected
Ajuste les index klo et khi de façon à ce qu'ils pointent vers des données valides.
Cette méthode est très similaire à l'autre méthode validateIndex(int[], double[]), excepté qu'elle agit directement sur klo et khi plutôt que sur un tableau passé en argument. On y gagne ainsi en rapidité d'exécution (on évite de faire un appel à copyIndexInto(int[]), mais ça ne gère toujours que ces deux index.
Tout ce qui était entre klo et khi avant l'appel de cette méthode le resteront après. Cette méthode ne fait que diminuer klo et augmenter khi, si nécessaire. Si ce n'était pas possible, une exception ExtrapolationException sera lancée.
Parameters
y Vecteur des données y servant à la vérification.
Returns
true si des changements ont été fait, false sinon.
Exceptions
ExtrapolationException s'il n'y a pas suffisament de données valides.
See also
validateIndex(int[], double[])
locateAt(int)
locate(double)
References Table1D.x, and Table1D.y.
{
         boolean hasChanged = false;
         if (Double.isNaN(y[khi])) {
             hasChanged = true;
             do {
                 if (++khi >= y.length) {
                     while (Double.isNaN(x[klo]) || Double.isNaN(y[klo])) {
                         if (--klo < 0) {
                             throw new ExtrapolationException();
                         }
                     }
                     throw new ExtrapolationException(+1, klo);
                 }
             } while (Double.isNaN(x[khi]) || Double.isNaN(y[khi]));
         }
         if (Double.isNaN(y[klo])) {
             hasChanged = true;
             do {
                 if (--klo < 0) {
                     throw new ExtrapolationException(-1, khi);
                 }
             } while (Double.isNaN(x[klo]) || Double.isNaN(y[klo]));
         }
         return hasChanged;
     }
Member Data Documentation
ignoreYNaN
boolean ignoreYNaN protected inherited
Indique aux méthodes interpole qu'elles devront ignorer les NaN dans le vecteur des y.
Ce champs n'affecte pas le comportement des méthodes vis-à-vis le vecteur des x. En effet, les NaN dans ce dernier sont toujours ignorés.
Referenced by Table1D.ignoreNaN(), Linear1D.interpolate(), Polynomial1D.interpolate(), Spline1D.interpolate(), Hermite1D.interpolate(), Search1D.interpolate(), Search1D.interpolateNaN(), Hermite1D.isNaN(), and Search1D.locate().
khi
int khi package
Referenced by Search1D.copyIndexInto(), Linear1D.interpolate(), Spline1D.interpolate(), Hermite1D.interpolate(), Search1D.locate(), and Search1D.validateIndex().
klo
int klo protected
Position de la dernière donnée trouvée, de sorte que xi est entre x[klo] et x[khi].
Referenced by Search1D.copyIndexInto(), Linear1D.interpolate(), Spline1D.interpolate(), Hermite1D.interpolate(), Search1D.locate(), and Search1D.validateIndex().
x
double [] x protected inherited
Vecteurs des x de cette table.
Referenced by Spline1D.constructY2(), Search1D.copyIndexInto(), Search1D.getInterval(), Linear1D.interpolate(), Polynomial1D.interpolate(), Spline1D.interpolate(), Hermite1D.interpolate(), Search1D.interpolate(), Search1D.interpolateAt(), Search1D.interpolateNaN(), Hermite1D.isNaN(), Search1D.locate(), Search1D.locateAt(), Table1D.setData(), and Search1D.validateIndex().
y
double y[] protected inherited
Vecteurs des y de cette table.
Referenced by Spline1D.clear(), Spline1D.constructY2(), Linear1D.interpolate(), Polynomial1D.interpolate(), Spline1D.interpolate(), Hermite1D.interpolate(), Search1D.interpolate(), Search1D.interpolateInPlaceNaN(), Linear1D.interpolateNaN(), Search1D.interpolateNaN(), Polynomial1D.interpolateNaN(), Spline1D.interpolateNaN(), Hermite1D.isNaN(), Search1D.locate(), Spline1D.recompute(), Table1D.setData(), and Search1D.validateIndex().