jena-geo: IOUtilities Class Reference
IOUtilities Class Reference
Utility methods related to I/O operations.
Static Public Member Functions
static void deleteOnExit (Path path)
Register Path for a delete on JM shutdown event.
static synchronized Writer standardWriter ()
Returns a writer to the standard output stream.
static synchronized PrintWriter standardPrintWriter ()
Returns a printer to the standard output stream.
static Path commonParent (Path root, final Path file)
If the two given Path are equals, return that Path.
static Object tryToFile (Object path) throws IOException
Tries to convert the given path to a File object if possible, or returns the path unchanged otherwise.
static Object tryToPath (Object path)
Tries to convert the given object to a Path object if possible, or returns the path unchanged otherwise.
static Path toPath (Object candidate) throws IOException, IllegalArgumentException
Tries to convert the given candidate into a Path object if possible, or throw IllegalArgumentException if candidate can't be converted.
static boolean canProcessAsPath (final Object path)
Returns.
static boolean isFileSystemSupported (final Object path)
Test if an object can be process as Path (see canProcessAsPath(Object)) and if input object target a known FileSystem using his scheme and FileSystemProvider#installedProviders().
static String filename (Object input)
Wrap of org.apache.sis.internal.storage.io.IOUtilities#filename(Object) (Object)} to avoid double import.
static String extension (Object input)
Wrap of org.apache.sis.internal.storage.io.IOUtilities#extension(Object) (Object)} to avoid double import.
static String filenameWithoutExtension (Object path)
Extract file name without extension from path object (Usually instance of String, File, URL, URI or Path).
static String filenameWithoutExtension (Path path)
Extract file name without extension from a Path.
static Object changeExtension (final Object path, final String extension) throws MalformedURLException, IOException
Changes the extension of the given String, File, URL, URI Path argument.
static Path changeExtension (final Path path, final String extension)
Changes the extension of the given Path argument.
static InputStream open (Object resource) throws IOException
Opens an input stream from the given String, File, URL, URI, Path or InputStream.
static InputStream open (Object resource, OpenOption... options) throws IOException
Opens an input stream from the given String, File, URL, URI, Path or InputStream.
static LineNumberReader openLatin (final Object path) throws IOException
Opens a reader from the given String, File, URL, URI , Path or InputStream.
static OutputStream openWrite (Object resource) throws IOException
Opens an output stream from the given String, File, URL, URI, Path or OutputStream.
static OutputStream openWrite (Object resource, OpenOption... options) throws IOException
Opens an output stream from the given String, File, URL, URI, Path or OutputStream.
static void close (final Object stream) throws IOException
Closes the given stream if it is closeable, or do nothing otherwise.
static void readMatrixRow (final BufferedReader in, final double[] grid, final int offset, final int numCol) throws IOException
Reads a row of a matrix and stores the values in the given buffer.
static void readMatrixRow (final BufferedReader in, final float[] grid, final int offset, final int numCol) throws IOException
Reads a row of a matrix and stores the values in the given buffer.
static void copy (final InputStream input, final OutputStream output) throws IOException
Copies the content from the given input stream to the given output stream.
static void copy (Path sourcePath, Path targetPath, CopyOption... copyOption) throws IOException
Copy content behind source Path into target Path.
static void deleteRecursively (final Path root) throws IOException
This method delete recursively a file or a folder.
static boolean deleteSilently (Path path)
This method delete recursively a file or directory behind a Path without raising an exception if delete failed.
static void appendToFile (final String text, final Path filePath) throws IOException
Append the specified text at the end of the File.
static void emptyFile (final Path filePath) throws IOException
Empty a file.
static List< Path > listChildren (Path directory) throws IllegalArgumentException, IOException
Traverse a directory an return children files with depth 0.
static List< Path > listChildren (Path directory, String glob) throws IllegalArgumentException, IOException
Traverse a directory an return children files with depth 0.
static String toString (final Path filePath) throws IOException
Read the contents of a file into String using UTF-8 encoding.
static String toString (final Path filePath, final Charset encoding) throws IOException
Read the contents of a file into String using specified encoding.
static String toString (final InputStream stream) throws IOException
Read the contents of a stream into String using UTF-8 encoding and close the Stream.
static String toString (final InputStream stream, final Charset encoding) throws IOException
Read the contents of a stream into String with specified encoding and close the Stream.
static void writeString (final String content, final Path outputPath) throws IOException
Write the contents of a string into path using UTF-8 encoding.
static void writeString (final String content, final Path outputPath, final Charset encoding) throws IOException
Write the contents of a string into path.
static void writeStream (final InputStream stream, final Path outputPath) throws IOException
Write the content of an InputStream into a Path
static Properties getPropertiesFromFile (final Path path) throws IOException
Load the properties from a properties file.
static void storeProperties (final Properties prop, final Path path, String comment) throws IOException
Store an Properties object "prop" into the specified File.
static Path getResourceAsPath (String resource) throws URISyntaxException, IOException
Searches in the Context ClassLoader for the named file and returns it.
static Path getResourceAsPath (String resource, ClassLoader classLoader) throws URISyntaxException, IOException
Searches in the Context ClassLoader for the named file and returns it.
static Path copyResource (String resource, ClassLoader classLoader, Path output, boolean createResourceHierarchy) throws IOException, URISyntaxException, IllegalArgumentException
Find and copy resource into a target directory.
Static Public Attributes
static final Charset UTF8_CHARSET = Charset.forName("UTF-8")
Default charset with UTF-8.
Static Package Functions
[static initializer]
Private Member Functions
IOUtilities ()
Do not allow instantiation of this class.
Static Private Member Functions
static String toSafeURI (String candidate)
Encode a String into a safe URI format.
static boolean isUnsafe (char ch)
Check if a char need to be encoded into URI format.
static String concatenate (String message, final Exception exception)
Concatenates the given message with the message of the given exception, if any.
Static Private Attributes
static final Logger LOGGER = Logging.getLogger("org.geotoolkit.io")
Logger.
static final int BUFFER_SIZE = 8192
The default buffer size for copy operations.
static Writer stdout
The writer to the console (if possible) or standard output stream otherwise.
static PrintWriter printer
A printer wrapping stdout, created when first needed.
static final Set< Path > DELETE_ON_EXIT_PATHS = Collections.newSetFromMap(new ConcurrentHashMap<Path, Boolean>())
Keep all Path to delete on JVM shutdown event on a concurrent Set.
Detailed Description
Utility methods related to I/O operations.
Author
Martin Desruisseaux (Geomatys)
Johann Sorel (Geomatys)
Quentin Boileau (Geomatys)
Version
4.1
Since
3.00
Constructor & Destructor Documentation
IOUtilities()
IOUtilities () private
Do not allow instantiation of this class.
{
     }
Member Function Documentation
[static initializer]()
[static initializer] () static package
appendToFile()
static void appendToFile (final String text, final Path filePath) throws IOException static
Append the specified text at the end of the File.
Parameters
text The text to append to the file.
filePath The url file.
Exceptions
IOException if the file does not exist or cannot be read.
{
         try (BufferedWriter output = Files.newBufferedWriter(filePath, UTF8_CHARSET, APPEND)) {
             output.newLine();
             output.write(text);
             output.flush();
         }
     }
canProcessAsPath()
static boolean canProcessAsPath (final Object path) static
Returns.
true
if the method in this class can process the given object as a path. Note: String input is not considered compatible as Path.
Parameters
path The object to test, or
null
.
Returns
true
If the given object is non-null and can be processed like a path.
Since
3.08
Referenced by IOUtilities.changeExtension(), IOUtilities.filenameWithoutExtension(), IOUtilities.isFileSystemSupported(), IOUtilities.open(), and IOUtilities.openWrite().
{
         return (
                 //(path instanceof CharSequence) ||
                 (path instanceof File) ||
                 (path instanceof URL) ||
                 (path instanceof URI) ||
                 (path instanceof Path));
     }
changeExtension() [1/2]
static Object changeExtension (final Object path, final String extension) throws MalformedURLException, IOException static
Changes the extension of the given String, File, URL, URI Path argument.
If the argument is not recognized, returns
null
. If the result of this method is an object equals to
path
, then the
path
instance is returned.
Note that this method converts URI objects to URL.
Parameters
path The path as a String, File, URL, URI or Path.
extension The new extension, without leading dot.
Returns
The path with the new extension, or
null
if the given object has not been recognized (including
null
path).
Exceptions
MalformedURLException If the given object is an URI or URL, and changing the extension does not result in a valid URL.
Since
3.07
References IOUtilities.canProcessAsPath(), IOUtilities.extension(), and IOUtilities.toPath().
{
         final boolean isPath = canProcessAsPath(path);
         if (!isPath) {
             //special case of CharSequence and String
             if (path instanceof CharSequence) {
                 String pathStr = (String) path;
                 int dotIdx = pathStr.lastIndexOf('.');
                 if (dotIdx > 0) {
                     pathStr = pathStr.substring(0, dotIdx);
                 }
                 return pathStr + "." + extension;
             }
             return null;
         }
         Path realPath = toPath(path);
         final Path outPath = changeExtension(realPath, extension);
         if (path instanceof Path) {
             return outPath;
         } else if (path instanceof String) {
             return outPath.toString();
         } else if (path instanceof File) {
             return outPath.toFile();
         } else if (path instanceof URL || path instanceof URI) {
             return outPath.toUri().toURL();
         }
         return null;
     }
changeExtension() [2/2]
static Path changeExtension (final Path path, final String extension) static
Changes the extension of the given Path argument.
Parameters
path The path as Path.
extension The new extension, without leading dot.
Returns
The path with the new extension.
References IOUtilities.extension(), and IOUtilities.filenameWithoutExtension().
{
         final String previousExt = org.apache.sis.internal.storage.io.IOUtilities.extension(path);
         if ((previousExt == null && extension == null) || (previousExt != null && previousExt.equals(extension))) {
             return path;
         }
         final String siblingName = filenameWithoutExtension(path) +'.'+ extension;
         return path.resolveSibling(siblingName);
     }
close()
static void close (final Object stream) throws IOException static
Closes the given stream if it is closeable, or do nothing otherwise.
Closeable objects are any instance of Closeable.
Parameters
stream The object to close if it is closeable.
Exceptions
IOException If an error occurred while closing the stream.
Since
3.07
{
         if (stream instanceof Closeable) {
             ((Closeable) stream).close();
         }
         // On JDK6, we needed an explicit check for ImageInputStream.
         // Since JDK7, this is not needed anymore.
     }
commonParent()
static Path commonParent (Path root, final Path file) static
If the two given Path are equals, return that Path.
Otherwise returns the first common parent found.
Parameters
root The Path which is the most likely to be the root.
file The other Path, which is more likely to be in a sub-directory of the root.
Returns
The root or a common parent, or
null
if no common parent has been found.
{
         while (root != null) {
             root = root.normalize();
             if (file != null) {
                 final Path nfile = file.normalize();
                 for (Path candidate = nfile; candidate != null; candidate = candidate.getParent()) {
                     if (root.equals(candidate)) {
                         return root;
                     }
                 }
                 root = root.getParent();
             }
         }
         return null;
     }
concatenate()
static String concatenate (String message, final Exception exception) static private
Concatenates the given message with the message of the given exception, if any.
This is used when an exception is catch and rethrow, in order to provide more useful message.
Referenced by IOUtilities.readMatrixRow(), and IOUtilities.tryToFile().
{
         final String cause = exception.getLocalizedMessage();
         if (cause != null) {
             message = message + ' ' + cause;
         }
         return message;
     }
copy() [1/2]
static void copy (final InputStream input, final OutputStream output) throws IOException static
Copies the content from the given input stream to the given output stream.
This method does not close the given streams.
Parameters
input The source of bytes to copy.
output The destination where to copy.
Exceptions
IOException If an error occurred while performing the copy operation.
Since
3.20
References IOUtilities.BUFFER_SIZE.
Referenced by ZipUtilities.unzipCore(), IOUtilities.writeStream(), and ZipUtilities.zipCore().
{
         final byte[] buffer = new byte[BUFFER_SIZE];
         int bytesRead;
         while ((bytesRead = input.read(buffer)) >= 0) {
             output.write(buffer, 0, bytesRead);
         }
     }
copy() [2/2]
static void copy (Path sourcePath, Path targetPath, CopyOption... copyOption) throws IOException static
Copy content behind source Path into target Path.
If source Path is a directory, all his content will be copied recursively.
Parameters
sourcePath source to copy, can be a file or a folder
targetPath target where source will be copied
copyOption optional copy option
Exceptions
IOException
{
         ArgumentChecks.ensureNonNull("sourcePath", sourcePath);
         ArgumentChecks.ensureNonNull("targetPath", targetPath);
         if (isDirectory(sourcePath)) {
             Files.walkFileTree(sourcePath, new CopyFileVisitor(targetPath, copyOption));
         } else {
             Files.copy(sourcePath, targetPath, copyOption);
         }
     }
copyResource()
static Path copyResource (String resource, ClassLoader classLoader, Path output, boolean createResourceHierarchy) throws IOException, URISyntaxException, IllegalArgumentException static
Find and copy resource into a target directory.
Parameters
resource resource path relative to resource directory like "org/geotoolkit/myresource". Can target a file or a directory
classLoader ClassLoader used for resource search. (Use current thread ClassLoader if
null
).
output Output directory where resource will be copied.
createResourceHierarchy flag to enable/disable creation of resource parent directory in output directory e.g.:
   IOUtilities.copyResource("org/geotoolkit/myresource", null, Paths.get("directory"), true);
   // will create directory/org/geotoolkit/myresource
   IOUtilities.copyResource("org/geotoolkit/myresource", null, Paths.get("directory"), false);
   // will create directory/myresource
Returns
Path to extracted resource. If resource is a directory, returned Path will target root directory where resource content is copied.
Exceptions
IOException if copy or file access went wrong
URISyntaxException an error occurs during resource URI conversion
IllegalArgumentException if output Path is not a directory
FileNotFoundException if resource is not found on classloader
{
         ArgumentChecks.ensureNonNull("resource", resource);
         ArgumentChecks.ensureNonNull("output", output);
         output = output.toAbsolutePath();
         if (!Files.exists(output)) {
             Files.createDirectories(output);
         }
         if (!Files.isDirectory(output)) {
             throw new IllegalArgumentException("Output is not a directory");
         }
         if (classLoader == null) {
             classLoader = Thread.currentThread().getContextClassLoader();
         }
         URL resURL = classLoader.getResource(resource);
         if (resURL != null) {
             URI resURI = resURL.toURI();
             //handle JAR resources
             Path resPath;
             if (resURI.getScheme().startsWith("jar")) {
                 FileSystem fileSystem;
                 try {
                     fileSystem = FileSystems.getFileSystem(resURI);
                 } catch (FileSystemNotFoundException ex) {
                     fileSystem = FileSystems.newFileSystem(resURI, new HashMap<String, Object>());
                 }
                 resPath = fileSystem.getPath(resource);
                 //hack add start / for CopyFileVisitor relativize
                 if (!resPath.toString().startsWith("/")) {
                     resPath = resPath.getFileSystem().getPath("/", resPath.toString());
                 }
             } else {
                 resPath = Paths.get(resURI);
             }
             String resourceName = resPath.getFileName().toString();
             //prepare workspace directory
             Path copyDir = output;
             if (Files.isDirectory(resPath)) {
                 copyDir = output.resolve(resourceName);
             }
             if (createResourceHierarchy) {
                 if (Files.isDirectory(resPath)) {
                     copyDir = output.resolve(resource);
                 } else {
                     String lastDirectory = resource.substring(0, resource.lastIndexOf('/'));
                     copyDir = output.resolve(lastDirectory);
                 }
             }
             Files.createDirectories(copyDir);
             Path outputPath = copyDir;
             if (Files.isRegularFile(resPath)) {
                 outputPath = outputPath.resolve(resourceName);
             }
             //copy files
             Files.walkFileTree(resPath, new CopyFileVisitor(copyDir, StandardCopyOption.REPLACE_EXISTING));
             return outputPath;
         }
         throw new FileNotFoundException("Unable to find resource "+resource+ " into ClassLoader "+classLoader);
     }
deleteOnExit()
static void deleteOnExit (Path path) static
Register Path for a delete on JM shutdown event.
Under the hood, this method register path to be delete using Runtime#addShutdownHook(Thread).
Parameters
path path to delete
Referenced by QuadTreeDirectory.createDirectory(), and ImageTilesCache.remove().
{
         DELETE_ON_EXIT_PATHS.add(path);
     }
deleteRecursively()
static void deleteRecursively (final Path root) throws IOException static
This method delete recursively a file or a folder.
Parameters
root The File or directory to delete.
Referenced by QuadTreeDirectory.cleanDirectory(), and IOUtilities.deleteSilently().
{
         ArgumentChecks.ensureNonNull("root", root);
         if (Files.exists(root)) {
             if (Files.isRegularFile(root)) {
                 Files.deleteIfExists(root);
             } else {
                 Files.walkFileTree(root, new SimpleFileVisitor<Path>() {
                     @Override
                     public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
                         Files.deleteIfExists(file);
                         return FileVisitResult.CONTINUE;
                     }
                     @Override
                     public FileVisitResult postVisitDirectory(Path dir, IOException exc) throws IOException {
                         Files.deleteIfExists(dir);
                         return FileVisitResult.CONTINUE;
                     }
                 });
             }
         }
     }
deleteSilently()
static boolean deleteSilently (Path path) static
This method delete recursively a file or directory behind a Path without raising an exception if delete failed.
If an exception occurs, message will be logged as debug.
TODO create asyncDeleteSilently to delete recursively a file/folder in a separate thread
Parameters
path file or folder to delete
Returns
delete status.
true
if delete succeed,
false
otherwise
References IOUtilities.deleteRecursively().
Referenced by TemporaryFile.delete(), and TemporaryFile.deleteAll().
{
         try {
             deleteRecursively(path);
             return true;
         } catch (IOException e) {
             LOGGER.log(Level.FINER, e.getLocalizedMessage(), e);
             return false;
         }
     }
emptyFile()
static void emptyFile (final Path filePath) throws IOException static
Empty a file.
Parameters
filePath The url file.
Exceptions
IOException if the file does not exist or cannot be read.
{
         if (Files.exists(filePath)) {
             Files.delete(filePath);
         }
         Files.createFile(filePath);
     }
extension()
static String extension (Object input) static
Wrap of org.apache.sis.internal.storage.io.IOUtilities#extension(Object) (Object)} to avoid double import.
Returns the filename extension from a Path, File, URL, URI or CharSequence instance. If no extension is found, returns an empty string. If the given object is of unknown type, return
null
.
Parameters
input An instance of one of the above-cited types, or
null
.
Returns
The extension in the given path, or an empty string if none, or
null
if the given object is null or of unknown type.
Referenced by IOUtilities.changeExtension(), and IOUtilities.getResourceAsPath().
{
         return org.apache.sis.internal.storage.io.IOUtilities.extension(input);
     }
filename()
static String filename (Object input) static
Wrap of org.apache.sis.internal.storage.io.IOUtilities#filename(Object) (Object)} to avoid double import.
Returns the filename from a Path, File, URL, URI or CharSequence instance. If the given argument is specialized type like
Path
or
File
, then this method uses dedicated API like Path#getFileName(). Otherwise this method gets a string representation of the path and returns the part after the last
'/'
or platform-dependent name separator character, if any.
Parameters
input An instance of one of the above-cited types, or
null
.
Returns
The filename in the given input, or
null
if the given object is null or of unknown type.
{
         return org.apache.sis.internal.storage.io.IOUtilities.filename(input);
     }
filenameWithoutExtension() [1/2]
static String filenameWithoutExtension (Object path) static
Extract file name without extension from path object (Usually instance of String, File, URL, URI or Path).
Parameters
path candidate path object
Returns
path file name without extension or
null
if input object can't be processed as Path.
References IOUtilities.canProcessAsPath(), and IOUtilities.toPath().
Referenced by IOUtilities.changeExtension(), and ZipUtilities.unzipNIO().
{
         final boolean isPath = canProcessAsPath(path);
         if (!isPath) {
             return null;
         }
         try {
             return filenameWithoutExtension(toPath(path));
         } catch (IOException e) {
             //silent exception
             return null;
         }
     }
filenameWithoutExtension() [2/2]
static String filenameWithoutExtension (Path path) static
Extract file name without extension from a Path.
If path file name doesn't have an extension, full file name String will be returned.
Parameters
path path to process
Returns
file name without extension.
Exceptions
NullPointerException if input path is
null
.
{
         ArgumentChecks.ensureNonNull("path", path);
         final String fileName = path.getFileName().toString();
         final int dot = fileName.lastIndexOf('.');
         if (dot > 0) {
             return fileName.substring(0, dot);
         }
         return fileName;
     }
getPropertiesFromFile()
static Properties getPropertiesFromFile (final Path path) throws IOException static
Load the properties from a properties file.
If the file does not exist it will be created and an empty Properties object will be return.
Parameters
path to a properties file.
Returns
a Properties Object.
{
         ArgumentChecks.ensureNonNull("path", path);
         final Properties prop = new Properties();
         try (InputStream in = Files.newInputStream(path)) {
             prop.load(in);
         }
         return prop;
     }
getResourceAsPath() [1/2]
static Path getResourceAsPath (String resource) throws URISyntaxException, IOException static
Searches in the Context ClassLoader for the named file and returns it.
Parameters
resource resource path. As package or path format (with '.' or '/' separators)
Returns
A file path if it exist or null otherwise.
{
         return getResourceAsPath(resource, null);
     }
getResourceAsPath() [2/2]
static Path getResourceAsPath (String resource, ClassLoader classLoader) throws URISyntaxException, IOException static
Searches in the Context ClassLoader for the named file and returns it.
Parameters
resource resource path. As package or path format (with '.' or '/' separators)
classLoader classloader, can be null
Returns
A file path if it exist or null otherwise.
References IOUtilities.extension().
{
         //change package based location to path based
         final String extension = org.apache.sis.internal.storage.io.IOUtilities.extension(resource);
         int lastDotIdx = resource.lastIndexOf('.');
         if (lastDotIdx > 0) {
             resource = resource.substring(0, lastDotIdx);
         }
         resource = resource.replace('.', '/') ;
         if (!extension.isEmpty()) {
             resource +="." + extension;
         }
         if (classLoader == null) {
             classLoader = Thread.currentThread().getContextClassLoader();
         }
         final URL systemResource = classLoader.getResource(resource);
         if (systemResource != null) {
             URI resourceURI = systemResource.toURI();
             if (resourceURI.getScheme().startsWith("jar")) {
                 //get or create FileSystem if needed (if resource is in another JAR)
                 FileSystem fileSystem;
                 try {
                     fileSystem = FileSystems.getFileSystem(resourceURI);
                 } catch (FileSystemNotFoundException ex) {
                     fileSystem = FileSystems.newFileSystem(resourceURI, new HashMap<String, Object>());
                 }
                 return fileSystem.getPath(resource);
             } else {
                 return Paths.get(resourceURI);
             }
         }
         return null;
     }
isFileSystemSupported()
static boolean isFileSystemSupported (final Object path) static
Test if an object can be process as Path (see canProcessAsPath(Object)) and if input object target a known FileSystem using his scheme and FileSystemProvider#installedProviders().
Parameters
path candidate object
Returns
true
if input object is compatible with Path API AND if FileSystem is known.
false
otherwise.
References IOUtilities.canProcessAsPath().
{
         if (!canProcessAsPath(path)) {
             return false;
         }
         URI uri = null;
         if (path instanceof URL) {
             try {
                 uri = org.apache.sis.internal.storage.io.IOUtilities.toURI((URL) path, "UTF-8");
             } catch (IOException e) {
                 //unable to create URI from URL
                 return false;
             }
         } else if (path instanceof URI) {
             uri = (URI) path;
         } else {
             return true;
         }
         String scheme = uri.getScheme();
         if (scheme == null) {
             //scheme null, consider as Path on default FileSystem
            return true;
         } else {
             // loop over FS providers and test path creation
             for (FileSystemProvider provider: FileSystemProvider.installedProviders()) {
                 if (provider.getScheme().equalsIgnoreCase(scheme)) {
                     try {
                         provider.getPath(uri);
                         return true;
                     } catch (IllegalArgumentException fse) {
                         // path construction failed
                     }
                 }
             }
             //no matching FS provider
             return false;
         }
     }
isUnsafe()
static boolean isUnsafe (char ch) static private
Check if a char need to be encoded into URI format.
Ignore reserved characters see URI RFC/a> ch
Referenced by IOUtilities.toSafeURI().
{
         return ch > 128 || " <>".indexOf(ch) >= 0;
     }
listChildren() [1/2]
static List<Path> listChildren (Path directory) throws IllegalArgumentException, IOException static
Traverse a directory an return children files with depth 0.
Result of this method can result of an OutOfMemory if scanned folder contains very large number of files.
Parameters
directory input Path, should be a directory
Returns
children Path
Exceptions
IllegalArgumentException if input Path is not a directory
IOException if an error occurs during directory scanning
{
         return listChildren(directory, "*");
     }
listChildren() [2/2]
static List<Path> listChildren (Path directory, String glob) throws IllegalArgumentException, IOException static
Traverse a directory an return children files with depth 0.
Result of this method can result of an OutOfMemory if scanned folder contains very large number of files.
Parameters
directory input Path, should be a directory
glob glob filter
Returns
children Path
Exceptions
IllegalArgumentException if input Path is not a directory
IOException if an error occurs during directory scanning
{
         if (!Files.isDirectory(directory)) {
             throw new IllegalArgumentException("Input Path is not a directory or doesn't exist");
         }
         if (glob == null || glob.isEmpty()) {
             glob = "*";
         }
         final List<Path> children = new LinkedList<>();
         try (DirectoryStream<Path> stream = Files.newDirectoryStream(directory, glob)) {
             for (Path child : stream) {
                 children.add(child);
             }
         }
         //asc sort
         Collections.sort(children);
         return children;
     }
open() [1/2]
static InputStream open (Object resource) throws IOException static
Opens an input stream from the given String, File, URL, URI, Path or InputStream.
The stream will not be buffered, and is not required to support the mark or reset methods.
It is the caller responsibility to close the given stream. This method does not accept pre-existing streams because they would usually require a different handling by the caller (e.g. in many case, the caller will not want to close such pre-existing streams).
Parameters
resource The file to open,
Returns
The input stream for the given resource.
Exceptions
IOException If an error occurred while opening the given file or input resource is not supported.
Referenced by IOUtilities.openLatin(), WKBRasterImageReader.read(), and DomUtilities.toInputStream().
{
         return open(resource, READ);
     }
open() [2/2]
static InputStream open (Object resource, OpenOption... options) throws IOException static
Opens an input stream from the given String, File, URL, URI, Path or InputStream.
The stream will not be buffered, and is not required to support the mark or reset methods.
It is the caller responsibility to close the given stream. This method does not accept pre-existing streams because they would usually require a different handling by the caller (e.g. in many case, the caller will not want to close such pre-existing streams).
Parameters
resource The file to open,
options open options
Returns
The input stream for the given resource.
Exceptions
IOException If an error occurred while opening the given file or input resource is not supported.
References IOUtilities.canProcessAsPath(), and IOUtilities.toPath().
{
         ArgumentChecks.ensureNonNull("resource", resource);
         if (resource instanceof InputStream) {
             return (InputStream) resource;
         }
         if (!canProcessAsPath(resource)) {
             throw new IOException("Can not handle input type : " + resource.getClass());
         }
         try {
             Path realPath = toPath(resource);
             return newInputStream(realPath, options);
         } catch (IOException e) {
              /*
                 An IOException is also thrown if toPath catch a FileSystemNotFoundException (http case)
                 Try with URL.
                 Typical case when resource input is an URL not supported as FileSystem
                 Path conversion will fail
              */
             URL url = null;
             if (resource instanceof URL) {
                 url = (URL) resource;
             }
             if (resource instanceof URI) {
                 URI uri = (URI) resource;
                 try {
                     url = uri.toURL();
                 } catch (MalformedURLException e2) {
                     e.addSuppressed(e2);
                 }
             }
             if (url != null) {
                 final URLConnection cnx = url.openConnection();
                 if (cnx instanceof HttpURLConnection) {
                     cnx.setRequestProperty("Accept-Encoding", "gzip");
                     if ("gzip".equals(cnx.getContentEncoding())) {
                         return new GZIPInputStream(cnx.getInputStream());
                      } else {
                         return cnx.getInputStream();
                      }
                 } else {
                     return cnx.getInputStream();
                 }
             }
             throw e;
         }
     }
openLatin()
static LineNumberReader openLatin (final Object path) throws IOException static
Opens a reader from the given String, File, URL, URI , Path or InputStream.
The character encoding is assumed ISO-LATIN-1.
Parameters
path The file to open, as a String, File, URL or URI.
Returns
The buffered reader for the given file.
Exceptions
IOException If an error occurred while opening the given file.
ClassCastException If the given object is not a known type.
References IOUtilities.open().
{
         return new LineNumberReader(new InputStreamReader(open(path), "ISO-8859-1"));
     }
openWrite() [1/2]
static OutputStream openWrite (Object resource) throws IOException static
Opens an output stream from the given String, File, URL, URI, Path or OutputStream.
Parameters
resource The resource to open,
Returns
The output stream for the given file.
Exceptions
IOException If an error occurred while opening the given file or input resource is not supported.
Since
3.07
Referenced by DomUtilities.toOutputStream(), and WKBRasterImageWriter.write().
{
         return openWrite(resource, CREATE, WRITE);
     }
openWrite() [2/2]
static OutputStream openWrite (Object resource, OpenOption... options) throws IOException static
Opens an output stream from the given String, File, URL, URI, Path or OutputStream.
Parameters
resource The resource to open,
options open options
Returns
The output stream for the given file.
Exceptions
IOException If an error occurred while opening the given file or input resource is not supported.
References IOUtilities.canProcessAsPath(), and IOUtilities.toPath().
{
         ArgumentChecks.ensureNonNull("resource", resource);
         if (resource instanceof OutputStream) {
             return (OutputStream) resource;
         }
         if (!canProcessAsPath(resource)) {
             throw new IOException("Can not handle input type : " + resource.getClass());
         }
         try {
             Path realPath = toPath(resource);
             return newOutputStream(realPath, options);
         } catch (IOException e) {
             /*
                 Try with URL.
                 Typical case when resource input is an URL not supported as FileSystem
                 Path conversion will fail
              */
             URL url = null;
             if (resource instanceof URL) {
                 url = (URL) resource;
             }
             if (resource instanceof URI) {
                 URI uri = (URI) resource;
                 try {
                     url = uri.toURL();
                 } catch (MalformedURLException e2) {
                     e.addSuppressed(e2);
                 }
             }
             if (url != null) {
                 URLConnection connection = url.openConnection();
                 connection.setDoOutput(true);
                 return connection.getOutputStream();
             }
             throw e;
         }
     }
readMatrixRow() [1/2]
static void readMatrixRow (final BufferedReader in, final double [] grid, final int offset, final int numCol) throws IOException static
Reads a row of a matrix and stores the values in the given buffer.
Parameters
in The input stream.
grid Where to store the values.
offset Index of the first value to write in
grid
.
numCol Expected number of columns.
Exceptions
IOException if an error occurred while reading the row.
References IOUtilities.concatenate(), Errors.Keys.EndOfDataFile, Errors.format(), Errors.Keys.LineTooLong_3, Errors.Keys.LineTooShort_2, and Errors.Keys.UnparsableNumber_1.
     {
         final String line = in.readLine();
         if (line == null) {
             throw new EOFException(Errors.format(Errors.Keys.EndOfDataFile));
         }
         final StringTokenizer tokens = new StringTokenizer(line);
         for (int i=0; i<numCol; i++) {
             if (!tokens.hasMoreTokens()) {
                 throw new ContentFormatException(Errors.format(
                         Errors.Keys.LineTooShort_2, i, numCol));
             }
             final String token = tokens.nextToken();
             final double value;
             try {
                 value = Double.parseDouble(token);
             } catch (NumberFormatException e) {
                 throw new ContentFormatException(concatenate(
                         Errors.format(Errors.Keys.UnparsableNumber_1, token), e), e);
             }
             grid[offset + i] = value;
         }
         if (tokens.hasMoreElements()) {
             throw new ContentFormatException(Errors.format(Errors.Keys.LineTooLong_3,
                     numCol+tokens.countTokens(), numCol, tokens.nextToken()));
         }
     }
readMatrixRow() [2/2]
static void readMatrixRow (final BufferedReader in, final float [] grid, final int offset, final int numCol) throws IOException static
Reads a row of a matrix and stores the values in the given buffer.
Parameters
in The input stream.
grid Where to store the values.
offset Index of the first value to write in
grid
.
numCol Expected number of columns.
Exceptions
IOException if an error occurred while reading the row.
References IOUtilities.concatenate(), Errors.Keys.EndOfDataFile, Errors.format(), Errors.Keys.LineTooLong_3, Errors.Keys.LineTooShort_2, and Errors.Keys.UnparsableNumber_1.
     {
         final String line = in.readLine();
         if (line == null) {
             throw new EOFException(Errors.format(Errors.Keys.EndOfDataFile));
         }
         final StringTokenizer tokens = new StringTokenizer(line);
         for (int i=0; i<numCol; i++) {
             if (!tokens.hasMoreTokens()) {
                 throw new ContentFormatException(Errors.format(
                         Errors.Keys.LineTooShort_2, i, numCol));
             }
             final String token = tokens.nextToken();
             final float value;
             try {
                 value = Float.parseFloat(token);
             } catch (NumberFormatException e) {
                 throw new ContentFormatException(concatenate(
                         Errors.format(Errors.Keys.UnparsableNumber_1, token), e), e);
             }
             grid[offset + i] = value;
         }
         if (tokens.hasMoreElements()) {
             throw new ContentFormatException(Errors.format(Errors.Keys.LineTooLong_3,
                     numCol+tokens.countTokens(), numCol, tokens.nextToken()));
         }
     }
standardPrintWriter()
static synchronized PrintWriter standardPrintWriter () static
Returns a printer to the standard output stream.
This method returns the Console::writer() console printer} if available, because that printer uses a more appropriate encoding on some platform. In no console printer is available, then a printer wrapping the System::out standard output stream} is returned.
Returns
A printer to the standard output stream.
See also
org.geotoolkit.io.NumberedLineWriter::getStandardOutput()
Since
3.17
References IOUtilities.printer, and IOUtilities.standardWriter().
{
         if (printer == null) {
             final Writer writer = standardWriter();
             if (printer == null) {
                 printer = new PrintWriter(writer, true);
             }
         }
         return printer;
     }
standardWriter()
static synchronized Writer standardWriter () static
Returns a writer to the standard output stream.
This method returns the Console::writer() console writer} if available, because that writer uses a more appropriate encoding on some platform. In no console writer is available, then a writer wrapping the System::out standard output stream} is returned.
Returns
A writer to the standard output stream.
Since
3.17
References IOUtilities.stdout.
Referenced by IOUtilities.standardPrintWriter(), and Synchronizer.Synchronizer().
{
         if (stdout == null) {
             final Console console = System.console();
             if (console != null) {
                 stdout = printer = console.writer();
             } else {
                 stdout = new OutputStreamWriter(System.out);
             }
         }
         return stdout;
     }
storeProperties()
static void storeProperties (final Properties prop, final Path path, String comment) throws IOException static
Store an Properties object "prop" into the specified File.
If file behind input path already exist, content will be truncated first.
Parameters
prop A properties Object.
path A file.
comment Comment in output property file. Can be
null
.
Exceptions
IOException
{
         ArgumentChecks.ensureNonNull("prop", prop);
         ArgumentChecks.ensureNonNull("path", path);
         //replace content
         try (OutputStream out = Files.newOutputStream(path, CREATE, WRITE, TRUNCATE_EXISTING)) {
             prop.store(out, (comment != null ? comment : ""));
         }
     }
toPath()
static Path toPath (Object candidate) throws IOException, IllegalArgumentException static
Tries to convert the given candidate into a Path object if possible, or throw IllegalArgumentException if candidate can't be converted.
Conversion attempts are performed for paths of class CharSequence, URL, URI or File.
If a conversion from a URL object was necessary, then the URL is assumed to not be encoded.
Parameters
candidate The candidate to convert to a Path if possible. Can return
null
if input candidate was
null
Returns
The candidate as a Path if this conversion was possible.
Exceptions
IOException If an error occurred while converting the candidate to a Path. For example a not supported FileSystem
IllegalArgumentException input object can't be converted into Path
References IOUtilities.toSafeURI().
Referenced by IOUtilities.changeExtension(), IOUtilities.filenameWithoutExtension(), IOUtilities.open(), IOUtilities.openWrite(), and IOUtilities.tryToPath().
{
         if (candidate == null) {
             return null;
         }
         if (candidate instanceof Path) {
             return (Path) candidate;
         }
         if (candidate instanceof CharSequence) {
             URI uri = URI.create(toSafeURI(String.valueOf(candidate)));
             if (uri.getScheme() != null) {
                 //let java check matching FileSystem
                 return Paths.get(uri);
             } else {
                 //assume on local filesystem
                 return Paths.get(candidate.toString());
             }
         } else if (candidate instanceof URL) {
             final URL url = (URL) candidate;
             return org.apache.sis.internal.storage.io.IOUtilities.toPath(url, null);
         } else if (candidate instanceof File) {
             return ((File) candidate).toPath();
         } else if (candidate instanceof URI) {
             final URI uri = (URI) candidate;
             try {
                 if (uri.getScheme() == null) {
                     //scheme null, consider as Path on default FileSystem
                     return Paths.get(uri.toString());
                 }
                 return Paths.get(uri);
             } catch (IllegalArgumentException | FileSystemNotFoundException cause) {
                 final String message = Exceptions.formatChainedMessages(null,
                         org.apache.sis.util.resources.Errors.format(org.apache.sis.util.resources.Errors.Keys.IllegalArgumentValue_2, "URI", uri), cause);
                 /*
                  * If the exception is IllegalArgumentException, then the URI scheme has been recognized
                  * but the URI syntax is illegal for that file system. So we can consider that the URL is
                  * malformed in regard to the rules of that particular file system.
                  */
                 final IOException e;
                 if (cause instanceof IllegalArgumentException) {
                     e = new MalformedURLException(message);
                     e.initCause(cause);
                 } else {
                     e = new IOException(message, cause);
                 }
                 throw e;
             }
         }
         throw new IllegalArgumentException("Can't convert "+candidate.getClass()+" into a Path."+
         "Supported candidate type are CharSequence, URL, URI, File and Path");
     }
toSafeURI()
static String toSafeURI (String candidate) static private
Encode a String into a safe URI format.
For example space characters will be replaced with %20
Parameters
candidate String
Returns
encoded candidate String
References IOUtilities.isUnsafe().
Referenced by IOUtilities.toPath().
{
         StringBuilder sb = new StringBuilder();
         for (char ch : candidate.toCharArray()) {
             if (isUnsafe(ch)) {
                 sb.append('%');
                 sb.append(Integer.toHexString(ch));
             } else {
                 sb.append(ch);
             }
         }
         return sb.toString();
     }
toString() [1/4]
static String toString (final Path filePath) throws IOException static
Read the contents of a file into String using UTF-8 encoding.
Parameters
filePath the file path
Returns
The file contents as string
Exceptions
IOException if the file does not exist or cannot be read.
Referenced by ReferencingUtilities.readTransform(), and IOUtilities.toString().
{
         return toString(filePath, UTF8_CHARSET);
     }
toString() [2/4]
static String toString (final Path filePath, final Charset encoding) throws IOException static
Read the contents of a file into String using specified encoding.
Parameters
filePath the file path
encoding encoding of file
Returns
The file contents as string
Exceptions
IOException if the file does not exist or cannot be read.
{
         final List<String> lines = Files.readAllLines(filePath, encoding);
         final StringBuilder sb = new StringBuilder();
         for (String line : lines) {
             sb.append(line).append('\n');
         }
         return sb.toString();
     }
toString() [3/4]
static String toString (final InputStream stream) throws IOException static
Read the contents of a stream into String using UTF-8 encoding and close the Stream.
Parameters
stream input steam
Returns
The file contents as string
Exceptions
IOException if the file does not exist or cannot be read.
References IOUtilities.toString().
{
         return toString(stream, UTF8_CHARSET);
     }
toString() [4/4]
static String toString (final InputStream stream, final Charset encoding) throws IOException static
Read the contents of a stream into String with specified encoding and close the Stream.
Parameters
stream input steam
Returns
The file contents as string
Exceptions
IOException if the file does not exist or cannot be read.
{
         final StringBuilder sb  = new StringBuilder();
         try (BufferedReader br = new BufferedReader(new InputStreamReader(stream, encoding))) {
             String line;
             while ((line = br.readLine()) != null) {
                 sb.append(line).append('\n');
             }
         } finally {
             stream.close();
         }
         return sb.toString();
     }
tryToFile()
static Object tryToFile (Object path) throws IOException static
Tries to convert the given path to a File object if possible, or returns the path unchanged otherwise.
Conversion attempts are performed for paths of class CharSequence, URL, URI or Path.
If a conversion from a URL object was necessary, then the URL is assumed to not be encoded.
Parameters
path The path to convert to a File if possible.
Returns
The path as a File if this conversion was possible.
Exceptions
IOException If an error occurred while converting the path to a file.
Since
3.07
Deprecated:
prefer using tryToPath(Object) method to deal with Path instead of File
References IOUtilities.concatenate(), Errors.format(), and Errors.Keys.IllegalArgument_2.
{
         if (path == null) {
             return null;
         }
         if (path instanceof File) {
             return (File) path;
         } else if (path instanceof CharSequence) {
             return org.apache.sis.internal.storage.io.IOUtilities.toFileOrURL(path.toString(), null);
         } else if (path instanceof URL) {
             final URL url = (URL) path;
             if (url.getProtocol().equalsIgnoreCase("file")) {
                 return org.apache.sis.internal.storage.io.IOUtilities.toFile(url, null);
             }
         } else if (path instanceof URI) {
             final URI uri = (URI) path;
             final String scheme = uri.getScheme();
             if (scheme != null && scheme.equalsIgnoreCase("file")) try {
                 return new File(uri);
             } catch (IllegalArgumentException cause) {
                 /*
                  * Typically because the URI contains a fragment (for example a query part)
                  * that can not be represented as a File. We consider that as an error
                  * because the scheme pretended that we had a file URI.
                  */
                 final IOException e = new MalformedURLException(concatenate(
                         Errors.format(Errors.Keys.IllegalArgument_2, "URI", path), cause));
                 e.initCause(cause);
                 throw e;
             }
         } else if (path instanceof Path) {
             return ((Path) path).toFile();
         }
         return path;
     }
tryToPath()
static Object tryToPath (Object path) static
Tries to convert the given object to a Path object if possible, or returns the path unchanged otherwise.
Conversion attempts are performed for objects of class CharSequence, URL, URI or File.
If a conversion from a URL object was necessary, then the URL is assumed to not be encoded.
Parameters
path The path to convert to a Path if possible.
Returns
The path as a Path if this conversion was possible. A Conversion to Path can fail if input Object is not supported or converted Path use a FileSystem not supported by default.
Since
3.20 (derived from 3.07)
References IOUtilities.toPath().
{
         try {
             return toPath(path);
         } catch (IllegalArgumentException | IOException ex) {
             // input candidate can't be converted into Path
             return path;
         }
     }
writeStream()
static void writeStream (final InputStream stream, final Path outputPath) throws IOException static
Write the content of an InputStream into a Path
Parameters
stream InputStream to write
outputPath the Path to write into.
Exceptions
IOException
References IOUtilities.copy().
{
         ArgumentChecks.ensureNonNull("stream", stream);
         ArgumentChecks.ensureNonNull("outputPath", outputPath);
         try (OutputStream outputStream = Files.newOutputStream(outputPath, CREATE, WRITE, TRUNCATE_EXISTING)) {
             copy(stream, outputStream);
         }
     }
writeString() [1/2]
static void writeString (final String content, final Path outputPath) throws IOException static
Write the contents of a string into path using UTF-8 encoding.
Parameters
content string to write
outputPath the Path to write into.
Exceptions
IOException if the file does not exist or cannot be read.
{
        writeString(content, outputPath, UTF8_CHARSET);
     }
writeString() [2/2]
static void writeString (final String content, final Path outputPath, final Charset encoding) throws IOException static
Write the contents of a string into path.
Parameters
content string to write
outputPath the Path to write into.
encoding encoding of output file.
Exceptions
IOException if the file does not exist or cannot be read.
{
         ArgumentChecks.ensureNonNull("content", content);
         ArgumentChecks.ensureNonNull("outputPath", outputPath);
         try (BufferedWriter bw = Files.newBufferedWriter(outputPath, encoding, CREATE, WRITE, TRUNCATE_EXISTING)) {
             bw.write(content);
         }
     }
Member Data Documentation
BUFFER_SIZE
final int BUFFER_SIZE = 8192 static private
The default buffer size for copy operations.
Referenced by IOUtilities.copy().
DELETE_ON_EXIT_PATHS
final Set<Path> DELETE_ON_EXIT_PATHS = Collections.newSetFromMap(new ConcurrentHashMap<Path, Boolean>()) static private
Keep all Path to delete on JVM shutdown event on a concurrent Set.
LOGGER
final Logger LOGGER = Logging.getLogger("org.geotoolkit.io") static private
Logger.
printer
PrintWriter printer static private
A printer wrapping stdout, created when first needed.
Referenced by IOUtilities.standardPrintWriter().
stdout
Writer stdout static private
The writer to the console (if possible) or standard output stream otherwise.
This is created when first needed.
Referenced by IOUtilities.standardWriter().
UTF8_CHARSET
final Charset UTF8_CHARSET = Charset.forName("UTF-8") static
Default charset with UTF-8.