jena-geo: VectorPair Class Reference
VectorPair Class Reference
Utility methods related to a pair of Vector objects.
Public Member Functions
VectorPair (final Vector X, final Vector Y)
Creates a new pair of vector.
Vector getX ()
Returns the vector of x values.
Vector getY ()
Returns the vector of y values.
int length () throws MismatchedSizeException
Returns the length of the two vectors, or thrown an exception if they don't have the same length.
void omitColinearPoints (final double xTolerance, double yTolerance) throws MismatchedSizeException
Merges consecutive colinear segments, if any.
void makeStepwise (int direction) throws MismatchedSizeException
Computes views of (X,Y) vectors where every diagonal line is replaced by a horizontal line followed by a vertical line.
Protected Attributes
Vector X
The vectors specified to the.
Package Attributes
Vector Y
Static Private Attributes
static final long serialVersionUID = 8330893190189236019L
For cross-version compatibility.
Detailed Description
Utility methods related to a pair of Vector objects.
The
VectorPair
constructor expects two vectors in argument, namely X and Y. Every operations defined in this class create <cite>views</cite> of the given vectors; they never copy or calculate data values. Because they are views, callers should not change the values of the original vectors, unless propagation to the views is really wanted.
Author
Martin Desruisseaux (Geomatys)
Version
3.00
Since
3.00
Constructor & Destructor Documentation
VectorPair()
VectorPair (final Vector X, final Vector Y)
Creates a new pair of vector.
Whatever the two given vectors need to have the same length or not depends on the operation to be applied on this pair of vectors.
Parameters
X The first vector of the pair.
Y The second vector of the pair.
{
         ensureNonNull("X", this.X = X);
         ensureNonNull("Y", this.Y = Y);
     }
Member Function Documentation
getX()
Vector getX ()
Returns the vector of x values.
Returns
The vector of x values.
References VectorPair.X.
{
         return X;
     }
getY()
Vector getY ()
Returns the vector of y values.
Returns
The vector of y values.
References VectorPair.Y.
{
         return Y;
     }
length()
int length () throws MismatchedSizeException
Returns the length of the two vectors, or thrown an exception if they don't have the same length.
Returns
The vector length, which is the same for the two vectors.
Exceptions
MismatchedSizeException if the two vectors don't have the same length.
References Errors.format(), and Errors.Keys.MismatchedArrayLength.
Referenced by VectorPair.makeStepwise(), and VectorPair.omitColinearPoints().
{
         final int length = Y.size();
         if (length != X.size()) {
             throw new MismatchedSizeException(Errors.format(Errors.Keys.MismatchedArrayLength));
         }
         return length;
     }
makeStepwise()
void makeStepwise (int direction) throws MismatchedSizeException
Computes views of (X,Y) vectors where every diagonal line is replaced by a horizontal line followed by a vertical line.
For this purpose, every x and y values are repeated once. A graph of the resulting vectors would have the visual appareance of a stair, or the outer limit of a histogram.
When invoked with
direction=0
, This method can be used before to plot (X,Y) data where X can takes only some fixed values, in order to visualy emphase its discontinuous nature. When invoked with positive or negative
direction
argument, this method can be used for plotting upper or lower limit respectively (for example computed from a standard deviation) of the above data.
{
input}
Starting with Xi and Yi as the input vectors before this method is invoked, take s to be the length of the Yi vector, then the length of the Xi vector must be s+1.
{
input}
Let define Xo and Yo the output vectors after this method has been invoked. The length of those two vectors will be at most 2s (they will be exactly of that length if
abs(direction) <= 1
). The first point and the last point in the output vectors will be the same than the first point and the last point in the input vectors. More specifically, assuming that the output vectors have the maximal length:
(Xo[0], Yo[0]) = (Xi[0], Yi[0])
(Xo[2s-1], Yo[2s-1]) = (Xi[s], Yi[s-1])
It is often a good idea to invoke omitColinearPoints after this method.
Parameters
direction Controls the order of horizontal and vertical lines.
If zero (neutral), then the order of line segments will always be <cite>horizontal line followed by vertical line</cite>, which produce the appearance of a histogram outer limit.
If +1 or -1, then some vertical lines may appear before their horizontal counterpart, when it makes the value of y higher (if
direction
is +1) or lower (if
direction
is -1) than they would otherwise be. So
direction
can be interpreted as the sign of the allowed change of y values.
If +2 or -2, then the same reordering than +1 or -1 is executed, followed by:
If
direction
is +2, the removal of lower point when the y values are going down and up again at the same x value.
If
direction
is -2, the removal of higher point when the y values are going up and down again at the same x value.
So +2 and -2 argument can be interpreted as shifting the main y value toward positive or negative infinity slightly more than what +1 or -1 does.
Exceptions
MismatchedSizeException If the length of the X vector is not equal to the length of the Y vector + 1.
References VectorPair.length(), VectorPair.X, and VectorPair.Y.
{
         final Vector X = this.X;
         final Vector Y = this.Y;
         final int length = Y.size();
         if (length+1 != X.size()) {
             throw new MismatchedSizeException();
         }
         int[] Xi = new int[length*2];
         int[] Yi = new int[length*2];
         if (length != 0) {
             boolean swap = false;
             double x0 = X.doubleValue(0);
             double y0 = Y.doubleValue(0);
             for (int i=0,j=0; i<length; i++) {
                 if (direction != 0) {
                     if (i+1 == length) {
                         // We have reached the end of the vector. Never swap the last
                         // index, otherwise we get an IndexOutOfBoundsException.
                         swap = false;
                     } else {
                         final double xi = X.doubleValue(i+1);
                         final double yi = Y.doubleValue(i+1);
                         int xs = (xi > x0) ? +1 : (xi < x0) ? -1 : 0; // We want 0 for NaN.
                         if (xs != 0) {
                             boolean up = (direction >= 0) ^ (xs < 0) ^ swap;
                             if (up ? (yi > y0) : (yi < y0)) {
                                 swap = !swap;
                             }
                         }
                         x0 = xi;
                         y0 = yi;
                     }
                 }
                 Xi[j]   = i;
                 Yi[j++] = i;
                 Xi[j]   = swap ? i : i+1;
                 Yi[j++] = swap ? i+1 : i;
             }
             assert ArraysExt.isSorted(Xi, false);
             assert ArraysExt.isSorted(Yi, false);
             /*
              * At this point we are done. However if 'direction' is different than 0, then the
              * index swapping may have caused situations where a Y value goes down, then up at
              * the same X value.  The code below will erase the down point (or the opposite if
              * 'direction' is negative instead than positive).
              */
             if (Math.abs(direction) >= 2) {
                 direction = Integer.signum(direction);
                 int size = Xi.length;
                 for (int i=size; --i>=2;) {
                     if (Xi[i] == Xi[i-2]) {
                         final double y1, y2;
                         y0 = Y.doubleValue(Yi[i-2]) * direction;
                         y1 = Y.doubleValue(Yi[i-1]) * direction;
                         y2 = Y.doubleValue(Yi[i  ]) * direction;
                         if (y1 < Math.min(y0, y2)) {
                             System.arraycopy(Xi, i, Xi, i-1, size-i);
                             System.arraycopy(Yi, i, Yi, i-1, size-i);
                             size--;
                         }
                     }
                 }
                 Xi = ArraysExt.resize(Xi, size);
                 Yi = ArraysExt.resize(Yi, size);
             }
         }
         this.X = X.pick(Xi);
         this.Y = Y.pick(Yi);
     }
omitColinearPoints()
void omitColinearPoints (final double xTolerance, double yTolerance) throws MismatchedSizeException
Merges consecutive colinear segments, if any.
More specifically for any index i, if the point having the coordinate
(x[i], y[i])
lies on the line segment defined by the two end points
(x[i-1], y[i-1])
and
(x[i+1], y[i+1])
, then the point at index i will be dropped.
If the (X,Y) vectors are data to be plotted, then this method can be used for simplifying the data without visual impact.
Parameters
xTolerance The maximal distance measured along the x axis to consider that a point lies on a line segment.
yTolerance The maximal distance measured along the y axis to consider that a point lies on a line segment.
Exceptions
MismatchedSizeException If the X and Y vectors don't have the same length.
References VectorPair.length(), VectorPair.X, and VectorPair.Y.
{
         final int length = length(); // Invoked first for forcing an inconditional check of vectors length.
         final double ratio = yTolerance / xTolerance;
         if (!Double.isNaN(ratio)) {
             final Vector X = this.X;
             final Vector Y = this.Y;
             int[] indices  = null;
             int count = 0;
             if (length >= 3) {
                 yTolerance *= yTolerance;
                 double x1 = X.doubleValue(0) * ratio;
                 double y1 = Y.doubleValue(0);
                 double x2 = X.doubleValue(1) * ratio;
                 double y2 = Y.doubleValue(1);
                 for (int i=2; i<length; i++) {
                     double x3 = X.doubleValue(i) * ratio;
                     double y3 = Y.doubleValue(i);
                     final double dsq = Line2D.ptSegDistSq(x1, y1, x3, y3, x2, y2);
                     if (dsq <= yTolerance) {
                         // Found a colinear point: (x2,y2) is on the line segment (x1,y1)-(x3,y3)
                         if (indices == null) {
                             indices = new int[length - 1];
                             while (count < i) {
                                 indices[count] = count++;
                             }
                         }
                         // Overwrite the point in the middle (x2,y2) with the last one (x3,y3).
                         indices[count-1] = i;
                     } else {
                         // The point is not colinear, so remember that we must keep it.
                         if (indices != null) {
                             indices[count++] = i;
                         }
                         x1 = x2;
                         y1 = y2;
                     }
                     x2 = x3;
                     y2 = y3;
                 }
             }
             if (indices != null) {
                 indices = ArraysExt.resize(indices, count);
                 this.X = X.pick(indices);
                 this.Y = Y.pick(indices);
             }
         }
     }
Member Data Documentation
serialVersionUID
final long serialVersionUID = 8330893190189236019L static private
For cross-version compatibility.
X
Vector X protected
The vectors specified to the.
VectorPair
constructor, or the result of the last operation performed on this object.
Referenced by VectorPair.getX(), VectorPair.makeStepwise(), and VectorPair.omitColinearPoints().
Y
Vector Y package
Referenced by VectorPair.getY(), VectorPair.makeStepwise(), and VectorPair.omitColinearPoints().