jena-geo: ParameterGroup Class Reference
ParameterGroup Class Reference
A group of related parameter values.
Public Member Functions
ParameterGroup (final ParameterDescriptorGroup descriptor)
Constructs a parameter group from the specified descriptor.
ParameterGroup (final ParameterDescriptorGroup descriptor, final GeneralParameterValue... values)
Constructs a parameter group from the specified descriptor and list of parameters.
ParameterGroup (final Map< String,?> properties, final GeneralParameterValue... values)
Constructs a parameter group from the specified list of parameters.
ParameterDescriptorGroup getDescriptor ()
Returns the abstract definition of this group of parameters.
List< GeneralParameterValue > values ()
Returns the values in this group.
ParameterValue<?> parameter (String name) throws ParameterNotFoundException
Returns the value in this group for the specified Identifier::getCode identifier code}.
List< ParameterValueGroup > groups (String name) throws ParameterNotFoundException
Returns all subgroups with the specified name.
ParameterValueGroup addGroup (String name) throws ParameterNotFoundException, InvalidParameterCardinalityException
Creates a new group of the specified name.
boolean equals (final Object object)
Compares the specified object with this parameter for equality.
int hashCode ()
Returns a hash value for this parameter.
ParameterGroup clone ()
Returns a deep copy of this group of parameter values.
String formatTo (final Formatter formatter)
Formats the inner part of this parameter as Well Known Text (WKT).
Static Public Attributes
static final ParameterValueGroup EMPTY
An empty parameter value group.
Static Protected Member Functions
static IllegalStateException unitlessParameter (final GeneralParameterDescriptor descriptor)
Returns an exception initialized with a "Unitless parameter" error message for the specified descriptor.
static String getName (final GeneralParameterDescriptor descriptor)
Convenience method returning the name of the specified descriptor.
Protected Attributes
final GeneralParameterDescriptor descriptor
The abstract definition of this parameter or group of parameters.
Package Functions
final GeneralParameterValue parameter (final int index) throws IndexOutOfBoundsException
Returns the parameter value at the specified index.
static< T > T ensureValidValue (final ParameterDescriptor< T > descriptor, final Object value) throws InvalidParameterValueException
Ensures that the given value is valid according the specified parameter descriptor.
Static Package Functions
static short getUnitMessageID (final Unit<?> unit)
Returns the unit type as one of error message code.
Static Private Member Functions
static ParameterDescriptorGroup createDescriptor (final Map< String,?> properties, final GeneralParameterValue[] values)
Work around for RFE #4093999 in Sun's bug database ("Relax constraint on placement of this()/super() call in constructors").
static void ensureValidOccurs (final GeneralParameterValue[] values, final Map< GeneralParameterDescriptor, Integer > occurrences)
Makes sure that the number of occurrences of each values is inside the expected range.
Private Attributes
final ArrayList< GeneralParameterValue > values
The values() parameter values} for this group.
transient List< GeneralParameterValue > asList
A view of values as an checked list.
Static Private Attributes
static final long serialVersionUID = -1985309386356545126L
Serial number for inter-operability with different versions.
Detailed Description
A group of related parameter values.
The same group can be repeated more than once in an org.opengis.referencing.operation.Operation operation} or higher level ParameterValueGroup, if those instances contain different values of one or more ParameterValues which suitably distinguish among those groups.
Author
Martin Desruisseaux (IRD, Geomatys)
Jody Garnett (Refractions)
Version
3.17
See also
DefaultParameterDescriptorGroup
Parameter
Since
2.0
Deprecated:
Moved to Apache SIS org.apache.sis.parameter.DefaultParameterValueGroup.
Constructor & Destructor Documentation
ParameterGroup() [1/3]
ParameterGroup (final ParameterDescriptorGroup descriptor)
Constructs a parameter group from the specified descriptor.
All values parameter values} will be initialized to their default value.
Parameters
descriptor The descriptor for this group.
Referenced by ParameterGroup.clone(), and ParameterGroup.equals().
{
         super(descriptor);
         final List<GeneralParameterDescriptor> parameters = descriptor.descriptors();
         values = new ArrayList<>(parameters.size());
         for (final GeneralParameterDescriptor element : parameters) {
             for (int count=element.getMinimumOccurs(); --count>=0;) {
                 final GeneralParameterValue value = element.createValue();
                 ensureNonNull("createValue", value);
                 values.add(value);
             }
         }
     }
ParameterGroup() [2/3]
ParameterGroup (final ParameterDescriptorGroup descriptor, final GeneralParameterValue... values)
Constructs a parameter group from the specified descriptor and list of parameters.
Parameters
descriptor The descriptor for this group.
values The list of parameter values.
Exceptions
IllegalStateException If the number of parameter values is not in the range of minimum and maximum occurrences declared in the descriptor.
References ParameterGroup.ensureValidOccurs().
     {
         super(descriptor);
         ensureNonNull("values", values);
         this.values = new ArrayList<>(Arrays.asList(values));
         final List<GeneralParameterDescriptor> parameters = descriptor.descriptors();
         final Map<GeneralParameterDescriptor,Integer> occurrences =
                 new LinkedHashMap<>(hashMapCapacity(parameters.size()));
         for (final GeneralParameterDescriptor param : parameters) {
             ensureNonNull("parameters", param);
             occurrences.put(param, 0);
         }
         ensureValidOccurs(values, occurrences);
     }
ParameterGroup() [3/3]
ParameterGroup (final Map< String,?> properties, final GeneralParameterValue... values)
Constructs a parameter group from the specified list of parameters.
Parameters
properties The properties for the DefaultParameterDescriptorGroup operation parameter group} to construct from the list of parameters.
values The list of parameter values.
Exceptions
IllegalStateException If the number of parameter values is not in the range of minimum and maximum occurrences declared in the descriptor.
References ParameterGroup.createDescriptor().
{
         super(createDescriptor(properties, values));
         this.values = new ArrayList<>(Arrays.asList(values));
     }
Member Function Documentation
addGroup()
ParameterValueGroup addGroup (String name) throws ParameterNotFoundException, InvalidParameterCardinalityException
Creates a new group of the specified name.
The specified name must be the Identifier::getCode identifier code} of a ParameterDescriptorGroup descriptor group}.
Parameters
name The case insensitive Identifier::getCode identifier code} of the parameter group to create.
Returns
A newly created parameter group for the given identifier code.
Exceptions
ParameterNotFoundException If no ParameterDescriptorGroup descriptor} was found for the given name.
InvalidParameterCardinalityException If this parameter group already contains the ParameterDescriptorGroup::getMaximumOccurs maximum number of occurrences} of subgroups of the given name.
References AbstractParameter.descriptor, Errors.format(), Errors.Keys.TooManyOccurrences_2, and Errors.Keys.UnknownParameterName_1.
     {
         final GeneralParameterDescriptor check =
                 ((ParameterDescriptorGroup) descriptor).descriptor(name);
         if (!(check instanceof ParameterDescriptorGroup)) {
             throw new ParameterNotFoundException(Errors.format(
                     Errors.Keys.UnknownParameterName_1, name), name);
         }
         int count = 0;
         for (final GeneralParameterValue value : values) {
             if (IdentifiedObjects.isHeuristicMatchForName(value.getDescriptor(), name)) {
                 count++;
             }
         }
         if (count >= check.getMaximumOccurs()) {
             throw new InvalidParameterCardinalityException(Errors.format(
                     Errors.Keys.TooManyOccurrences_2, name, count), name);
         }
         final ParameterValueGroup value = ((ParameterDescriptorGroup) check).createValue();
         values.add(value);
         return value;
     }
clone()
ParameterGroup clone ()
Returns a deep copy of this group of parameter values.
Included parameter values and subgroups are cloned recursively.
Returns
A copy of this group of parameter values.
Implements Cloneable.
References ParameterGroup.asList, ParameterGroup.clone(), ParameterGroup.ParameterGroup(), and ParameterGroup.values.
Referenced by ParameterGroup.clone().
{
         final ParameterGroup copy = (ParameterGroup) super.clone();
         try {
             // Set the 'provider' field using reflection, because this field is final. This is
             // a legal usage for cloning according Field.set(...) documentation in J2SE 1.5.
             final Field field = ParameterGroup.class.getDeclaredField("values");
             field.setAccessible(true);
             field.set(copy, values.clone());
         } catch (ReflectiveOperationException cause) {
             throw new AssertionError(cause);
         }
         for (int i=copy.values.size(); --i>=0;) {
             copy.values.set(i, copy.values.get(i).clone());
         }
         copy.asList = null;
         return copy;
     }
createDescriptor()
static ParameterDescriptorGroup createDescriptor (final Map< String,?> properties, final GeneralParameterValue [] values) static private
Work around for RFE #4093999 in Sun's bug database ("Relax constraint on placement of this()/super() call in constructors").
Exceptions
IllegalStateException If the number of parameter values is not in the range of minimum and maximum occurrences declared in the descriptor.
References ParameterGroup.ensureValidOccurs(), and ParameterGroup.getDescriptor().
Referenced by ParameterGroup.ParameterGroup().
     {
         ensureNonNull("values", values);
         final Map<GeneralParameterDescriptor,Integer> occurrences =
                 new LinkedHashMap<>(hashMapCapacity(values.length));
         for (int i=0; i<values.length; i++) {
             ensureNonNullElement("values", i, values);
             occurrences.put(values[i].getDescriptor(), 0);
         }
         ensureValidOccurs(values, occurrences);
         final Set<GeneralParameterDescriptor> descriptors = occurrences.keySet();
         return new DefaultParameterDescriptorGroup(properties, 1, 1,
                 descriptors.toArray(new GeneralParameterDescriptor[descriptors.size()]));
     }
ensureValidOccurs()
static void ensureValidOccurs (final GeneralParameterValue [] values, final Map< GeneralParameterDescriptor, Integer > occurrences) static private
Makes sure that the number of occurrences of each values is inside the expected range.
Parameters
values The list of parameter values.
occurrences A map of the number of occurrences of a value for each descriptor. The key must be GeneralParameterDescriptor instances and the values must be Integer initialized with the 0 value.
Exceptions
IllegalStateException If the number of parameter values is not in the range of minimum and maximum occurrences declared in the descriptor.
References AbstractParameter.descriptor, Errors.format(), AbstractParameter.getName(), Errors.Keys.IllegalDescriptorForParameter_1, and Errors.Keys.IllegalOccursForParameter_4.
Referenced by ParameterGroup.createDescriptor(), and ParameterGroup.ParameterGroup().
     {
         /*
          * Count the parameters occurrences.
          */
         for (int i=0; i<values.length; i++) {
             ensureNonNullElement("values", i, values);
             final GeneralParameterDescriptor descriptor = values[i].getDescriptor();
             final Integer count = occurrences.put(descriptor, 1);
             if (count == null) {
                 final String name = getName(descriptor);
                 throw new InvalidParameterTypeException(Errors.format(
                         Errors.Keys.IllegalDescriptorForParameter_1, name), name);
             }
             if (count != 0) {
                 // Rarely enter in this block because there is usually at most 1 occurrence.
                 occurrences.put(descriptor, count + 1);
             }
         }
         /*
          * Now check if the occurrences are in the expected ranges.
          */
         for (final Map.Entry<GeneralParameterDescriptor,Integer> entry : occurrences.entrySet()) {
             final GeneralParameterDescriptor descriptor = entry.getKey();
             final int count = entry.getValue();
             final int min   = descriptor.getMinimumOccurs();
             final int max   = descriptor.getMaximumOccurs();
             if (!(count>=min && count<=max)) {
                 final String name = getName(descriptor);
                 throw new InvalidParameterCardinalityException(Errors.format(
                         Errors.Keys.IllegalOccursForParameter_4, name, count, min, max), name);
             }
         }
     }
ensureValidValue()
static<T> T ensureValidValue (final ParameterDescriptor< T > descriptor, final Object value) throws InvalidParameterValueException package inherited
Ensures that the given value is valid according the specified parameter descriptor.
This convenience method ensures that
value
is assignable to the ParameterDescriptor::getValueClass() expected class}, is between the ParameterDescriptor::getMinimumValue() minimum} and ParameterDescriptor::getMaximumValue() maximum} values and is one of the ParameterDescriptor::getValidValues() set of valid values}. If the value fails any of those tests, then an exception is thrown.
This method is similar to Parameters#isValid(ParameterValue) except that the exception contains an error message formatted with a description of the failure raison.
Parameters
<T> The type of parameter value. The given
value
should typically be an instance of this class. This is not required by this method signature but is checked by this method implementation.
descriptor The parameter descriptor to check against.
value The value to check, or
null
.
Returns
The value casted to the descriptor parameterized type, or the ParameterDescriptor::getDefaultValue() default value} if the given value was null while the parameter is mandatory.
Exceptions
InvalidParameterValueException if the parameter value is invalid.
References Errors.format(), AbstractParameter.getName(), Errors.Keys.IllegalArgument_2, Errors.Keys.IllegalOperationForValueClass_1, and Errors.Keys.ValueOutOfBounds_3.
Referenced by Parameter< T >.setValue().
     {
         if (value == null) {
             if (descriptor.getMinimumOccurs() != 0) {
                 return descriptor.getDefaultValue();
             }
             return null;
         }
         final String error;
         /*
          * Note: the implementation below is similar (except for different error message) to the
          * one in Parameters.isValidValue(ParameterDescriptor, Object). If one implementation is
          * modified, the other should be updated accordingly. The main difference is that null
          * values are replaced by the default value instead than being a conformance error.
          */
         final Class<T> type = descriptor.getValueClass();
         if (!type.isInstance(value)) {
             error = Errors.format(Errors.Keys.IllegalOperationForValueClass_1, value.getClass());
         } else {
             final T typedValue = type.cast(value);
             final Comparable<T> minimum = descriptor.getMinimumValue();
             final Comparable<T> maximum = descriptor.getMaximumValue();
             if ((minimum != null && minimum.compareTo(typedValue) > 0) ||
                 (maximum != null && maximum.compareTo(typedValue) < 0))
             {
                 error = Errors.format(Errors.Keys.ValueOutOfBounds_3, value, minimum, maximum);
             } else {
                 final Set<T> validValues = descriptor.getValidValues();
                 if (validValues!=null && !validValues.contains(value)) {
                     error = Errors.format(Errors.Keys.IllegalArgument_2, getName(descriptor), value);
                 } else {
                     /*
                      * Passed every tests - the value is valid.
                      */
                     return typedValue;
                 }
             }
         }
         throw new InvalidParameterValueException(error, getName(descriptor), value);
     }
equals()
boolean equals (final Object object)
Compares the specified object with this parameter for equality.
Parameters
object The object to compare to
this
.
Returns
true
if both objects are equal.
References ParameterGroup.equals(), ParameterGroup.ParameterGroup(), and ParameterGroup.values.
Referenced by ParameterGroup.equals().
{
         if (object == this) {
             return true;
         }
         if (super.equals(object)) {
             final ParameterGroup that = (ParameterGroup) object;
             return Objects.equals(this.values, that.values);
         }
         return false;
     }
formatTo()
String formatTo (final Formatter formatter) inherited
Formats the inner part of this parameter as Well Known Text (WKT).
References AbstractParameter.Bridge< T >.formatTo().
{
         if (this instanceof ParameterValue<?>) {
             return new Bridge((ParameterValue<?>) this).formatTo(formatter);
         }
         return "PARAMETER";
     }
getDescriptor()
ParameterDescriptorGroup getDescriptor ()
Returns the abstract definition of this group of parameters.
Referenced by ParameterGroup.createDescriptor(), and ParameterGroup.parameter().
{
         return (ParameterDescriptorGroup) super.getDescriptor();
     }
getName()
static String getName (final GeneralParameterDescriptor descriptor) static protected inherited
Convenience method returning the name of the specified descriptor.
This method is used mostly for output to be read by human, not for processing. Consequently, we may consider to returns a localized name in a future version.
Referenced by Parameter< T >.booleanValue(), Parameter< T >.doubleValue(), Parameter< T >.doubleValueList(), ParameterGroup.ensureValidOccurs(), AbstractParameter.ensureValidValue(), Parameter< T >.intValue(), Parameter< T >.intValueList(), Parameters.isValidValue(), Parameter< T >.stringValue(), AbstractParameter.unitlessParameter(), and Parameter< T >.valueFile().
{
         return descriptor.getName().getCode();
     }
getUnitMessageID()
static short getUnitMessageID (final Unit<?> unit) static package inherited
Returns the unit type as one of error message code.
Used for checking unit with a better error message formatting if needed.
References Errors.Keys.IncompatibleUnit_1, Errors.Keys.NonAngularUnit_1, Errors.Keys.NonLinearUnit_1, Errors.Keys.NonScaleUnit_1, and Errors.Keys.NonTemporalUnit_1.
Referenced by Parameter< T >.doubleValue(), Parameter< T >.doubleValueList(), and Parameter< T >.setValue().
{
         if (Units.isLinear  (unit)) return Errors.Keys.NonLinearUnit_1;
         if (Units.isAngular (unit)) return Errors.Keys.NonAngularUnit_1;
         if (Units.isTemporal(unit)) return Errors.Keys.NonTemporalUnit_1;
         if (Units.isScale   (unit)) return Errors.Keys.NonScaleUnit_1;
         return Errors.Keys.IncompatibleUnit_1;
     }
groups()
List<ParameterValueGroup> groups (String name) throws ParameterNotFoundException
Returns all subgroups with the specified name.
This method do not create new groups. If the requested group is optional (i.e. ParameterDescriptor::getMinimumOccurs minimumOccurs} == 0) and no value were set, then this method returns an empty set.
Parameters
name The case insensitive Identifier::getCode identifier code} of the parameter group to search for.
Returns
The set of all parameter group for the given identifier code.
Exceptions
ParameterNotFoundException If no ParameterDescriptorGroup descriptor} was found for the given name.
References AbstractParameter.descriptor, Errors.format(), and Errors.Keys.UnknownParameterName_1.
{
         ensureNonNull("name", name);
         name = name.trim();
         final List<ParameterValueGroup> groups = new ArrayList<>(Math.min(values.size(), 10));
         for (final GeneralParameterValue value : values) {
             if (value instanceof ParameterValueGroup) {
                 if (IdentifiedObjects.isHeuristicMatchForName(value.getDescriptor(), name)) {
                     groups.add((ParameterValueGroup) value);
                 }
             }
         }
         /*
          * No groups were found. Check if the group actually exists (i.e. is declared in the
          * descriptor). If it doesn't exists, then an exception is thrown. If it exists (i.e.
          * it is simply an optional group not yet defined), then returns an empty list.
          */
         if (groups.isEmpty()) {
             final GeneralParameterDescriptor check =
                     ((ParameterDescriptorGroup) descriptor).descriptor(name);
             if (!(check instanceof ParameterDescriptorGroup)) {
                 throw new ParameterNotFoundException(Errors.format(
                         Errors.Keys.UnknownParameterName_1, name), name);
             }
         }
         return groups;
     }
hashCode()
int hashCode ()
Returns a hash value for this parameter.
Returns
The hash code value. This value doesn't need to be the same in past or future versions of this class.
{
         return super.hashCode() ^ values.hashCode();
     }
parameter() [1/2]
final GeneralParameterValue parameter (final int index) throws IndexOutOfBoundsException package
Returns the parameter value at the specified index.
Parameters
index The zero-based index.
Returns
The parameter value at the specified index.
Exceptions
IndexOutOfBoundsException if the specified index is out of bounds.
{
         return values.get(index);
     }
parameter() [2/2]
ParameterValue<?> parameter (String name) throws ParameterNotFoundException
Returns the value in this group for the specified Identifier::getCode identifier code}.
If no ParameterValue parameter value} is found but a ParameterDescriptor parameter descriptor} is found (which may occurs if the parameter is optional, i.e. ParameterDescriptor::getMinimumOccurs minimumOccurs} == 0), then a ParameterValue parameter value} is automatically created and initialized to its ParameterDescriptor::getDefaultValue default value} (if any).
This convenience method provides a way to get and set parameter values by name. For example the following idiom fetches a floating point value for the
"false_easting"
parameter:
{ java double value = parameter("false_easting").doubleValue(); }
This method does not search recursively in subgroups. This is because more than one subgroup may exist for the same ParameterDescriptorGroup descriptor}. The user must groups query all subgroups} and select explicitly the appropriate one to use.
Parameters
name The case insensitive Identifier::getCode identifier code} of the parameter to search for.
Returns
The parameter value for the given identifier code.
Exceptions
ParameterNotFoundException if there is no parameter value for the given identifier code.
See also
Parameters::getOrCreate(ParameterDescriptor, ParameterValueGroup)
References AbstractParameter.descriptor, Errors.format(), ParameterGroup.getDescriptor(), and Errors.Keys.UnknownParameterName_1.
{
         ensureNonNull("name", name);
         name = name.trim();
         for (final GeneralParameterValue value : values) {
             if (value instanceof ParameterValue<?>) {
                 if (IdentifiedObjects.isHeuristicMatchForName(value.getDescriptor(), name)) {
                     return (ParameterValue<?>) value;
                 }
             }
         }
         /*
          * No existing parameter found. Check if an optional parameter exists.
          * If such a descriptor is found, create it, add it to the list of values
          * and returns it.
          */
         for (final GeneralParameterDescriptor descriptor : getDescriptor().descriptors()) {
             if (descriptor instanceof ParameterDescriptor<?>) {
                 if (IdentifiedObjects.isHeuristicMatchForName(descriptor, name)) {
                     final ParameterValue<?> value = ((ParameterDescriptor<?>) descriptor).createValue();
                     values.add(value);
                     return value;
                 }
             }
         }
         throw new ParameterNotFoundException(Errors.format(Errors.Keys.UnknownParameterName_1, name), name);
     }
unitlessParameter()
static IllegalStateException unitlessParameter (final GeneralParameterDescriptor descriptor) static protected inherited
Returns an exception initialized with a "Unitless parameter" error message for the specified descriptor.
References Errors.format(), AbstractParameter.getName(), and Errors.Keys.UnitlessParameter_1.
Referenced by Parameter< T >.doubleValue(), Parameter< T >.doubleValueList(), and Parameter< T >.setValue().
{
         return new IllegalStateException(Errors.format(
                 Errors.Keys.UnitlessParameter_1, getName(descriptor)));
     }
values()
List<GeneralParameterValue> values ()
Returns the values in this group.
Changes in this list are reflected on this
ParameterValueGroup
. The returned list supports the add operation.
References ParameterGroup.asList, and AbstractParameter.descriptor.
{
         if (asList == null) {
             asList = new ParameterValueList((ParameterDescriptorGroup) descriptor, values);
         }
         return asList;
     }
Member Data Documentation
asList
transient List<GeneralParameterValue> asList private
A view of values as an checked list.
Will be constructed only when first needed. Note that elements can be added in this list and modified. Example:
{ java values().get(i).setValue(myValue); }
Referenced by ParameterGroup.clone(), and ParameterGroup.values().
descriptor
final GeneralParameterDescriptor descriptor protected inherited
The abstract definition of this parameter or group of parameters.
Referenced by AbstractParameter.AbstractParameter(), ParameterGroup.addGroup(), Parameter< T >.booleanValue(), Parameter< T >.doubleValue(), Parameter< T >.doubleValueList(), ParameterGroup.ensureValidOccurs(), AbstractParameter.equals(), Parameter< T >.getClassTypeError(), AbstractParameter.getDescriptor(), ParameterGroup.groups(), Parameter< T >.intValue(), Parameter< T >.intValueList(), Parameter< T >.Parameter(), ParameterGroup.parameter(), Parameter< T >.setValue(), Parameter< T >.stringValue(), Parameter< T >.valueFile(), and ParameterGroup.values().
EMPTY
final ParameterValueGroup EMPTY static
Initial value:
= new ParameterGroup(
            Collections.singletonMap(ParameterDescriptorGroup.NAME_KEY, "Void"))
An empty parameter value group.
This group contains no parameter value.
serialVersionUID
final long serialVersionUID = -1985309386356545126L static private
Serial number for inter-operability with different versions.
values
final ArrayList<GeneralParameterValue> values private
The values() parameter values} for this group.
Referenced by ParameterGroup.clone(), and ParameterGroup.equals().