jena-geo: LinearInterpolator1D Class Reference
LinearInterpolator1D Class Reference
MathTransform1D with linear interpolation between values.
Public Member Functions
double transform (double d) throws TransformException
.
double derivative (double d) throws TransformException
.
MathTransform1D inverse () throws NoninvertibleTransformException
boolean isIdentity ()
Static Public Member Functions
static LinearInterpolator1D create (double[] values)
static LinearInterpolator1D create (double[] antecedents, double[] values)
Private Member Functions
LinearInterpolator1D (double[] values)
LinearInterpolator1D (double[] antecedents, double[] values)
Two tables such as : f(antecedents) = values.
Private Attributes
final double [] antecedent
final double [] values
boolean isIncreaseOrder = true
final int l
Detailed Description
MathTransform1D with linear interpolation between values.
Author
Johann Sorel (Geomatys)
Remi Marechal (Geomatys).
Deprecated:
Moved to org.apache.sis.referencing.operation.transform.MathTransforms#interpolate
Constructor & Destructor Documentation
LinearInterpolator1D() [1/2]
LinearInterpolator1D (double [] values) private
In this case an antecedents default table is construct such as :
[0, 1, ... , N] with N is length of image table values.
Parameters
values image from antecedents table values.
References LinearInterpolator1D.l, and LinearInterpolator1D.values.
Referenced by LinearInterpolator1D.create(), and LinearInterpolator1D.inverse().
{
         ArgumentChecks.ensureNonNull("values", values);
         this.l          = values.length;
         if (l < 2)
             throw new IllegalArgumentException("table must have more than only two values");
         this.values     = values;
         this.antecedent = new double[l];
         for (int v = 0;v<l;v++) this.antecedent[v] = v;
     }
LinearInterpolator1D() [2/2]
LinearInterpolator1D (double [] antecedents, double [] values) private
Two tables such as : f(antecedents) = values.
Parameters
antecedents "abscissa" table values.
values image from antecedents table values.
References LinearInterpolator1D.l, and LinearInterpolator1D.values.
{
         ArgumentChecks.ensureNonNull("values", values);
         ArgumentChecks.ensureNonNull("antecedents", antecedents);
         this.l = antecedents.length;
         if (l<2)
             throw new IllegalArgumentException("table must have more than only two values");
         if (l != values.length)
             throw new IllegalArgumentException("antecedents and values table must have same length");
         if (!ArraysExt.isSorted(antecedents, true)) {
             final double[] antecedent2 = new double[l];
             int id = l;
             for (int i = 0; i < l; i++) antecedent2[i] = antecedents[--id];
             if (!ArraysExt.isSorted(antecedent2, true))
                 throw new IllegalArgumentException("antecedents table must be strictly increasing or decreasing");
             isIncreaseOrder = false;
         }
         this.antecedent = antecedents;
         this.values     = values;
     }
Member Function Documentation
create() [1/2]
static LinearInterpolator1D create (double [] values) static
References LinearInterpolator1D.LinearInterpolator1D().
Referenced by ReferencingUtilities.toTransform().
{
         return new LinearInterpolator1D(values);
     }
create() [2/2]
static LinearInterpolator1D create (double [] antecedents, double [] values) static
References LinearInterpolator1D.LinearInterpolator1D().
{
         return new LinearInterpolator1D(antecedents, values);
     }
derivative()
double derivative (double d) throws TransformException
.
Note : for each segment lower sequence point derivative is inclusive whereas upper sequence point is exclusive.
References LinearInterpolator1D.l.
{
         int idn, idn1;
         if (isIncreaseOrder) {
             idn  = 0; idn1 = 1;
             if (d < antecedent[0] || d >= antecedent[l-1]) return 0;
         } else {
             idn  = 1; idn1 = 0;
             if (d <= antecedent[l-1] || d > antecedent[0]) return 0;
         }
         for (int id = 0; id < l; id++) {
             if ((d > antecedent[idn]  && d < antecedent[idn1]) || d == antecedent[id])
                 return (values[idn1]-values[idn]) / (antecedent[idn1]-antecedent[idn]);
             idn++;idn1++;
         }
         return 0;//impossible
     }
inverse()
MathTransform1D inverse () throws NoninvertibleTransformException
References LinearInterpolator1D.l, and LinearInterpolator1D.LinearInterpolator1D().
{
         if (!ArraysExt.isSorted(values, true)) {
             final double[] values2 = new double[l];
             int id = l;
             for (int i = 0; i < l; i++) values2[i] = values[--id];
             if (!ArraysExt.isSorted(values2, true))
                 throw new NoninvertibleTransformException("non inversible");
         }
         return new LinearInterpolator1D(values, antecedent);
     }
isIdentity()
boolean isIdentity ()
{
         return Arrays.equals(antecedent, values);
     }
transform()
double transform (double d) throws TransformException
.
{
         int ida, idb, idn, idn1;
         if (isIncreaseOrder) {
             ida = 0; idb  = l-1;
             idn = 0; idn1 = 1;
         } else {
             ida = l-1; idb  = 0;
             idn = 1;   idn1 = 0;
         }
         if (d <= antecedent[ida]) return values[ida];
         if (d >= antecedent[idb]) return values[idb];
         double x0, x1;
         for (int id = 0; id < l-1; id++) {
             x0 = antecedent[idn];
             x1 = antecedent[idn1];
             if      (d == x0) return values[idn];
             else if (d == x1) return values[idn1];
             else if (d > antecedent[idn] && d < antecedent[idn1])
                 return values[idn] + (values[idn1] - values[idn]) * ((d-x0) / (x1-x0));
             idn++;idn1++;
         }
         return 0;//impossible
     }
Member Data Documentation
antecedent
final double [] antecedent private
isIncreaseOrder
boolean isIncreaseOrder = true private
l
final int l private
Referenced by LinearInterpolator1D.derivative(), LinearInterpolator1D.inverse(), and LinearInterpolator1D.LinearInterpolator1D().
values
final double [] values private
Referenced by LinearInterpolator1D.LinearInterpolator1D().