jena-geo: PredefinedCS Class Reference
PredefinedCS Class Reference
Predefined coordinate systems.
Static Public Member Functions
static Quantity<?> distance (final CoordinateSystem cs, final double[] coord1, final double[] coord2) throws UnsupportedOperationException, MismatchedDimensionException
Computes the distance between two points.
static CartesianCS usingUnit (final CartesianCS cs, final Unit<?> unit) throws IllegalArgumentException
Returns a coordinate system with the same properties than the given one except for axis units.
static EllipsoidalCS usingUnit (final EllipsoidalCS cs, final Unit<?> unit) throws IllegalArgumentException
Returns a coordinate system with the same properties than the current one except for axis units.
Static Public Attributes
static final DefaultCartesianCS PROJECTED
A two-dimensional Cartesian CS with Axes::EASTING Easting}, Axes::NORTHING Northing} axis in metres.
static final DefaultCartesianCS CARTESIAN_2D
A two-dimensional Cartesian CS with Axes::X x}, Axes::Y y} axis in metres.
static final DefaultCartesianCS CARTESIAN_3D
A three-dimensional Cartesian CS with Axes::X x}, Axes::Y y}, Axes::Z z} axis in metres.
static final DefaultCartesianCS GRID
A two-dimensional Cartesian CS with Axes::COLUMN column}, Axes::ROW row} axis.
Static Package Functions
static Map< String, Object > getProperties (final IdentifiedObject info, final Citation authority)
Returns the properties to be given to an identified object derived from the specified one.
Private Member Functions
PredefinedCS ()
Creates a comparator.
Static Private Member Functions
static Map< String, Object > name (final int key)
Creates a name for the predefined constants in subclasses.
static void ensureDimensionMatch (final CoordinateSystem cs, final String name, final double[] coordinates) throws MismatchedDimensionException
Convenience method for checking object dimension validity.
static DefaultCartesianCS createCartesian (final Map< String,?> properties, final CoordinateSystemAxis[] axis)
static DefaultEllipsoidalCS createEllipsoidal (final Map< String,?> properties, final CoordinateSystemAxis[] axis)
static Quantity<?> distance (final CartesianCS cs, final double[] coord1, final double[] coord2) throws UnsupportedOperationException, MismatchedDimensionException
Computes the distance between two points.
static Unit<?> getDistanceUnit (final CoordinateSystem cs)
Suggests an unit for measuring distances in this coordinate system.
static CoordinateSystemAxis [] axisUsingUnit (final CoordinateSystem cs, final Unit<?> unit, final Unit<?> ignore) throws IncommensurableException
Returns all axis in the specified unit.
Detailed Description
Predefined coordinate systems.
Warning: this is a temporary class which may disappear in future Geotk version, after we migrated functionality to Apache SIS.
Author
Martin Desruisseaux (IRD)
Constructor & Destructor Documentation
PredefinedCS()
PredefinedCS () private
Creates a comparator.
{
     }
Member Function Documentation
axisUsingUnit()
static CoordinateSystemAxis [] axisUsingUnit (final CoordinateSystem cs, final Unit<?> unit, final Unit<?> ignore) throws IncommensurableException static private
Returns all axis in the specified unit.
This method was used for implementation of
usingUnit
methods in CS subclasses.
Parameters
unit The unit for the new axes.
ignore Units#METRE for ignoring linear units, Units#RADIAN for ignoring angular units, or
null
for none.
Returns
New axes using the specified unit, or
null
if no change is needed.
Exceptions
IncommensurableException If the specified unit is incompatible with the expected one.
See also
DefaultCartesianCS::usingUnit(Unit)
DefaultEllipsoidalCS::usingUnit(Unit)
References Axes.usingUnit().
Referenced by PredefinedCS.usingUnit().
{
         final int dimension = cs.getDimension();
         CoordinateSystemAxis[] newAxis = null;
         for (int i=0; i<dimension; i++) {
             final CoordinateSystemAxis a = cs.getAxis(i);
             final Unit<?> current = a.getUnit();
             if (!unit.equals(current) && (ignore == null || !ignore.equals(unit.getSystemUnit()))) {
                 final CoordinateSystemAxis converted = Axes.usingUnit(a, unit);
                 if (converted != a) {
                     if (newAxis == null) {
                         newAxis = new CoordinateSystemAxis[dimension];
                         for (int j=0; j<i; j++) {
                             newAxis[j] = cs.getAxis(j);
                         }
                     }
                     newAxis[i] = converted;
                 }
             }
         }
         return newAxis;
     }
createCartesian()
static DefaultCartesianCS createCartesian (final Map< String,?> properties, final CoordinateSystemAxis [] axis) static private
Referenced by PredefinedCS.usingUnit().
{
         switch (axis.length) {
             case 2: return new DefaultCartesianCS(properties, axis[0], axis[1]);
             case 3: return new DefaultCartesianCS(properties, axis[0], axis[1], axis[2]);
             default: throw new IllegalArgumentException();
         }
     }
createEllipsoidal()
static DefaultEllipsoidalCS createEllipsoidal (final Map< String,?> properties, final CoordinateSystemAxis [] axis) static private
Referenced by PredefinedCS.usingUnit().
{
         switch (axis.length) {
             case 2: return new DefaultEllipsoidalCS(properties, axis[0], axis[1]);
             case 3: return new DefaultEllipsoidalCS(properties, axis[0], axis[1], axis[2]);
             default: throw new IllegalArgumentException();
         }
     }
distance() [1/2]
static Quantity<?> distance (final CoordinateSystem cs, final double [] coord1, final double [] coord2) throws UnsupportedOperationException, MismatchedDimensionException static
Computes the distance between two points.
This method is not available for all coordinate systems. For example, the DefaultEllipsoidalCS ellipsoidal CS} doesn't have sufficient information.
In the default Geotk implementation, this method is supported by the following class:
All one-dimensional coordinate systems (DefaultLinearCS, DefaultVerticalCS, DefaultTimeCS), in which case this method returns the absolute difference between the given ordinate values.
DefaultCartesianCS#distance(double[], double[]).
Parameters
coord1 Coordinates of the first point.
coord2 Coordinates of the second point.
Returns
The distance between
coord1
and
coord2
.
Exceptions
UnsupportedOperationException if this coordinate system can't compute distances.
MismatchedDimensionException if a coordinate doesn't have the expected dimension.
References PredefinedCS.ensureDimensionMatch(), Errors.format(), and Errors.Keys.UnsupportedCoordinateSystem_1.
     {
         if (cs instanceof CartesianCS) {
             // Temporary patch replacing method overriding until we completed the migration to Apache SIS.
             return distance((CartesianCS) cs, coord1, coord2);
         }
         ensureDimensionMatch(cs, "coord1", coord1);
         ensureDimensionMatch(cs, "coord2", coord2);
         if (cs.getDimension() == 1) {
             return Quantities.create(Math.abs(coord1[0] - coord2[0]), cs.getAxis(0).getUnit());
         }
         throw new UnsupportedOperationException(Errors.format(Errors.Keys.UnsupportedCoordinateSystem_1, cs.getClass()));
     }
distance() [2/2]
static Quantity<?> distance (final CartesianCS cs, final double [] coord1, final double [] coord2) throws UnsupportedOperationException, MismatchedDimensionException static private
Computes the distance between two points.
Parameters
coord1 Coordinates of the first point.
coord2 Coordinates of the second point.
Returns
The distance between
coord1
and
coord2
.
Exceptions
UnsupportedOperationException if this coordinate system can't compute distances.
MismatchedDimensionException if a coordinate doesn't have the expected dimension.
References PredefinedCS.ensureDimensionMatch(), Errors.format(), PredefinedCS.getDistanceUnit(), and Errors.Keys.IncompatibleUnit_1.
     {
         ensureDimensionMatch(cs, "coord1", coord1);
         ensureDimensionMatch(cs, "coord2", coord2);
         final Unit<?> unit = getDistanceUnit(cs);
         final UnitConverter[] converters = new UnitConverter[cs.getDimension()];
         for (int i=0; i<converters.length; i++) {
             final Unit<?> axisUnit = cs.getAxis(i).getUnit();
             try {
                 converters[i] = axisUnit.getConverterToAny(unit);
             } catch (IncommensurableException e) {
                 throw new UnsupportedOperationException(Errors.format(
                         Errors.Keys.IncompatibleUnit_1, axisUnit), e);
             }
         }
         final double[] delta = new double[converters.length];
         for (int i=0; i<converters.length; i++) {
             final UnitConverter  c = converters[i];
             delta[i] = c.convert(coord1[i]) - c.convert(coord2[i]);
         }
         return Quantities.create(MathFunctions.magnitude(delta), unit);
     }
ensureDimensionMatch()
static void ensureDimensionMatch (final CoordinateSystem cs, final String name, final double [] coordinates) throws MismatchedDimensionException static private
Convenience method for checking object dimension validity.
Parameters
name The name of the argument to check.
coordinates The coordinate array to check.
Exceptions
MismatchedDimensionException if the coordinate doesn't have the expected dimension.
References Errors.format(), Errors.Keys.MismatchedDimension_3, and PredefinedCS.name().
Referenced by PredefinedCS.distance().
     {
         final int dimension = cs.getDimension();
         if (coordinates.length != dimension) {
             throw new MismatchedDimensionException(Errors.format(
                     Errors.Keys.MismatchedDimension_3,
                     name, coordinates.length, dimension));
         }
     }
getDistanceUnit()
static Unit<?> getDistanceUnit (final CoordinateSystem cs) static private
Suggests an unit for measuring distances in this coordinate system.
The default implementation scans all CoordinateSystemAxis::getUnit() axis units}, then returns the "largest" one (e.g. kilometre instead of metre).
Returns
Suggested distance unit.
Referenced by PredefinedCS.distance().
{
         Unit<?> unit = null;
         double maxScale = 0;
         for (int i=cs.getDimension(); --i>=0;) {
             final Unit<?> candidate = cs.getAxis(i).getUnit();
             if (candidate != null) {
                 final double scale = Math.abs(Units.toStandardUnit(candidate));
                 if (scale > maxScale) {
                     unit = candidate;
                     maxScale = scale;
                 }
             }
         }
         return unit;
     }
getProperties()
static Map<String,Object> getProperties (final IdentifiedObject info, final Citation authority) static package
Returns the properties to be given to an identified object derived from the specified one.
This method returns the same properties than the supplied argument (as of #getProperties(IdentifiedObject) getProperties}(info)), except for the following:
The IdentifiedObject::getName() name}'s authority is replaced by the specified one.
All IdentifiedObject::getIdentifiers identifiers} are removed, because the new object to be created is probably not endorsed by the original authority.
This method returns a mutable map. Consequently, callers can add their own identifiers directly to this map if they wish.
Parameters
info The identified object to view as a properties map.
authority The new authority for the object to be created, or
null
if it is not going to have any declared authority.
Returns
The identified object properties in a mutable map.
Deprecated:
Will be removed.
Referenced by Axes.usingUnit(), and PredefinedCS.usingUnit().
{
         final Map<String,Object> properties = new HashMap<>(org.apache.sis.referencing.IdentifiedObjects.getProperties(info));
         properties.put(NAME_KEY, new NamedIdentifier(authority, info.getName().getCode()));
         properties.remove(IDENTIFIERS_KEY);
         return properties;
     }
name()
static Map<String,Object> name (final int key) static private
Creates a name for the predefined constants in subclasses.
The name is an unlocalized String object. However, since this method is used for creation of convenience objects only (not for objects created from an "official" database), the "unlocalized" name is actually chosen according the user's locale at class initialization time. The same name is also added in a localizable form as an alias. Since the nameMatches convenience method checks the alias, it still possible to consider two objects are equivalent even if their names were formatted in different locales.
References Vocabulary.formatInternational().
Referenced by PredefinedCS.ensureDimensionMatch().
{
         final Map<String,Object> properties = new HashMap<>(4);
         final InternationalString name = Vocabulary.formatInternational(key);
         properties.put(NAME_KEY,  name.toString());
         properties.put(ALIAS_KEY, name);
         return properties;
     }
usingUnit() [1/2]
static CartesianCS usingUnit (final CartesianCS cs, final Unit<?> unit) throws IllegalArgumentException static
Returns a coordinate system with the same properties than the given one except for axis units.
Parameters
unit The unit for the new axis.
Returns
A coordinate system with axis using the specified units.
Exceptions
IllegalArgumentException If the specified unit is incompatible with the expected one.
References PredefinedCS.axisUsingUnit(), PredefinedCS.createCartesian(), Errors.format(), PredefinedCS.getProperties(), and Errors.Keys.IncompatibleUnit_1.
{
         final CoordinateSystemAxis[] axes;
         try {
             axes = axisUsingUnit(cs, unit, null);
         } catch (IncommensurableException e) {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.IncompatibleUnit_1, unit), e);
         }
         if (axes == null) {
             return cs;
         }
         return createCartesian(getProperties(cs, null), axes);
     }
usingUnit() [2/2]
static EllipsoidalCS usingUnit (final EllipsoidalCS cs, final Unit<?> unit) throws IllegalArgumentException static
Returns a coordinate system with the same properties than the current one except for axis units.
If this coordinate system already uses the given unit, then this method returns
this
.
Parameters
unit The unit for the new axis.
Returns
A coordinate system with axis using the specified units, or
this
.
Exceptions
IllegalArgumentException If the specified unit is incompatible with the expected one.
References PredefinedCS.axisUsingUnit(), PredefinedCS.createEllipsoidal(), Errors.format(), PredefinedCS.getProperties(), and Errors.Keys.IncompatibleUnit_1.
{
         final CoordinateSystemAxis[] axes;
         try {
             axes = PredefinedCS.axisUsingUnit(cs, unit, Units.isLinear(unit) ? Units.RADIAN : Units.METRE);
         } catch (IncommensurableException e) {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.IncompatibleUnit_1, unit), e);
         }
         if (axes == null) {
             return cs;
         }
         return createEllipsoidal(getProperties(cs, null), axes);
     }
Member Data Documentation
CARTESIAN_2D
final DefaultCartesianCS CARTESIAN_2D static
Initial value:
= new DefaultCartesianCS(
                    name(Vocabulary.Keys.Cartesian2d),
                    Axes.X,
                    Axes.Y)
A two-dimensional Cartesian CS with Axes::X x}, Axes::Y y} axis in metres.
CARTESIAN_3D
final DefaultCartesianCS CARTESIAN_3D static
Initial value:
= new DefaultCartesianCS(
                    name(Vocabulary.Keys.Cartesian3d),
                    Axes.X,
                    Axes.Y,
                    Axes.Z)
A three-dimensional Cartesian CS with Axes::X x}, Axes::Y y}, Axes::Z z} axis in metres.
GRID
final DefaultCartesianCS GRID static
Initial value:
= new DefaultCartesianCS(
                    name(Vocabulary.Keys.Grid),
                    Axes.COLUMN,
                    Axes.ROW)
A two-dimensional Cartesian CS with Axes::COLUMN column}, Axes::ROW row} axis.
PROJECTED
final DefaultCartesianCS PROJECTED static
Initial value:
= new DefaultCartesianCS(
                    name(Vocabulary.Keys.Projected),
                    Axes.EASTING,
                    Axes.NORTHING)
A two-dimensional Cartesian CS with Axes::EASTING Easting}, Axes::NORTHING Northing} axis in metres.
Referenced by IGNF.createCoordinateReferenceSystem().