jena-geo: GridTransform2D Class Reference
GridTransform2D Class Reference
A specialization of GridTransform in the two-dimensional case.
Classes
class Inverse
Transforms target coordinates to source coordinates.
Public Member Functions
synchronized MathTransform2D inverse () throws NoninvertibleTransformException
Returns the inverse of this transform.
final int getSourceDimensions ()
Returns the dimension of input points, which is 2.
final int getTargetDimensions ()
Returns the dimension of output points.
boolean isIdentity ()
Returns.
Matrix transform (final double[] srcPts, final int srcOff, final double[] dstPts, int dstOff, final boolean derivate)
Transforms a source coordinate into target coordinate.
void transform (final double[] srcPts, int srcOff, final double[] dstPts, int dstOff, int numPts)
Transforms a source coordinate into target coordinate.
void transform (final float[] srcPts, int srcOff, final float[] dstPts, int dstOff, int numPts)
Transforms a source coordinate into target coordinate.
void transform (final double[] srcPts, int srcOff, final float [] dstPts, int dstOff, int numPts)
Transforms a source coordinate into target coordinate.
void transform (final float [] srcPts, int srcOff, final double[] dstPts, int dstOff, int numPts)
Transforms a source coordinate into target coordinate.
Point2D transform (final Point2D ptSrc, final Point2D ptDst) throws TransformException
Transforms the specified.
boolean equals (final Object object, final ComparisonMode mode)
Compares this transform with the specified object for equality.
String getName ()
Returns a name for this math transform (never.
Shape createTransformedShape (final Shape shape) throws TransformException
Transform the specified shape.
Matrix derivative (final Point2D point) throws TransformException
Gets the derivative of this transform at a point.
String formatTo (Formatter formatter)
Static Public Member Functions
static GridTransform create (final int width, final int height, final float[]... data)
Constructs a GridType::LOCALIZATION localization} grid using the specified data.
static GridTransform create (final int width, final int height, final double[]... data)
Constructs a GridType::LOCALIZATION localization} grid using the specified data.
static GridTransform create (final GridType type, final DataBuffer grid, final Dimension size, final Rectangle2D area)
Constructs a grid using the specified data.
Protected Member Functions
GridTransform2D (final GridType type, final DataBuffer grid, final Dimension size, final Rectangle2D area)
Constructs a grid using the specified data.
int computeHashCode ()
Static Protected Member Functions
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException
Makes sure that an argument is non-null.
Protected Attributes
final int width
Number of columns in the grid.
final int height
Number of rows in the grid.
final transient DataBuffer grid
The grid of values.
Static Package Functions
static String mismatchedDimension (final String argument, final int dimension, final int expected)
Constructs an error message for the MismatchedDimensionException.
Package Attributes
final double yOrigin
final double scaleY
final GridType type
Whatever the grid values are directly the target coordinates or offsets to apply on source coordinates.
Private Attributes
transient MathTransform2D inverse
The inverse of this math transform.
Static Private Attributes
static final long serialVersionUID = -5797129125459758798L
Serial number for inter-operability with different versions.
Detailed Description
A specialization of GridTransform in the two-dimensional case.
The default implementation is invertible for the OFFSET, NADCON and NTv2 grid types (assuming that the offsets are small), but not for the GridType::LOCALIZATION LOCALIZATION} type. For an invertible localization grid, see the org.geotoolkit.referencing.operation.builder.LocalizationGrid builder.
Author
Rueben Schulz (UBC)
Martin Desruisseaux (IRD, Geomatys)
Version
3.20
Since
3.00
Deprecated:
Replaced by org.apache.sis.referencing.operation.transform.InterpolatedTransform
Constructor & Destructor Documentation
GridTransform2D()
GridTransform2D (final GridType type, final DataBuffer grid, final Dimension size, final Rectangle2D area) protected
Constructs a grid using the specified data.
Parameters
type Whatever the grid values are directly the target coordinates or offsets to apply on source coordinates.
grid The grid of values. It must complies with the conditions documented in the grid field.
size Number of columns (Dimension::width width}) and rows (Dimension::height height}) in the grid.
area Grid envelope in "real world" coordinates, or
null
if none. The minimal (x,y) coordinate will maps the (0,0) grid coordinate, and the maximal (x,y) coordinate will maps the (width width}, height height}) grid coordinate.
References Errors.format(), and Errors.Keys.MismatchedDimension_3.
     {
         super(type, grid, size, area);
         final int n = grid.getNumBanks();
         if (n != 2) {
             throw new MismatchedDimensionException(Errors.format(
                     Errors.Keys.MismatchedDimension_3, "grid", n, 2));
         }
     }
Member Function Documentation
computeHashCode()
int computeHashCode () protected inherited
{
         return hash(xOrigin, hash(yOrigin, hash(scaleX, hash(scaleY, hash(width, hash(height,
                hash(grid.getNumBanks(), super.computeHashCode())))))));
     }
create() [1/3]
static GridTransform create (final int width, final int height, final float... [] data) static inherited
Constructs a GridType::LOCALIZATION localization} grid using the specified data.
This convenience method creates the intermediate DataBufferFloat object from the supplied data assuming that the first valid values is located at index 0. If this is not the case, user can create a
DataBufferFloat
object directly in order to gain more control.
Parameters
width Number of columns in the grid.
height Number of rows in the grid.
data Data stored in row-major order, one array for each target dimension.
Returns
The math transform backed by the given grid.
References GridType.LOCALIZATION.
Referenced by GridTransform.create().
{
         return create(GridType.LOCALIZATION, new DataBufferFloat(data, width*height),
                       new Dimension(width, height), null);
     }
create() [2/3]
static GridTransform create (final int width, final int height, final double... [] data) static inherited
Constructs a GridType::LOCALIZATION localization} grid using the specified data.
This convenience method creates the intermediate DataBufferDouble object from the supplied data assuming that the first valid values is located at index 0. If this is not the case, user can create a
DataBufferDouble
object directly in order to gain more control.
Parameters
width Number of columns in the grid.
height Number of rows in the grid.
data Data stored in row-major order, one array for each target dimension.
Returns
The math transform backed by the given grid.
References GridTransform.create(), and GridType.LOCALIZATION.
{
         return create(GridType.LOCALIZATION, new DataBufferDouble(data, width*height),
                       new Dimension(width, height), null);
     }
create() [3/3]
static GridTransform create (final GridType type, final DataBuffer grid, final Dimension size, final Rectangle2D area) static inherited
Constructs a grid using the specified data.
Parameters
type Whatever the grid values are directly the target coordinates or offsets to apply on source coordinates.
grid The grid of values. It must complies with the conditions documented in the grid field.
size Number of columns (Dimension::width width}) and rows (Dimension::height height}) in the grid.
area Grid envelope in "real world" coordinates, or
null
if none. The minimal (x,y) coordinate will maps the (0,0) grid coordinate, and the maximal (x,y) coordinate will maps the (
size.width
,
size.height
) grid coordinate.
Returns
The math transform backed by the given grid.
References GridTransform.GridTransform().
     {
         if (grid.getNumBanks() == 2) {
             return new GridTransform2D(type, grid, size, area);
         }
         return new GridTransform(type, grid, size, area);
     }
createTransformedShape()
Shape createTransformedShape (final Shape shape) throws TransformException inherited
Transform the specified shape.
The default implementation computes quadratic curves using three points for each line segment in the shape. The returned object is often a Path2D, but may also be a Line2D or a QuadCurve2D if such simplification is possible.
Parameters
shape Shape to transform.
Returns
Transformed shape, or
shape
if this transform is the identity transform.
Exceptions
IllegalStateException if this transform doesn't map 2D coordinate systems.
TransformException if a transform failed.
See also
MathTransform2D::createTransformedShape(Shape)
References AbstractMathTransform.mismatchedDimension().
{
         int dim;
         if ((dim = getSourceDimensions()) != 2 || (dim = getTargetDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("shape", 2, dim));
         }
         if (isIdentity()) return shape;
         try {
             final Method method = org.apache.sis.referencing.operation.transform.AbstractMathTransform2D.class.getMethod(
                     "createTransformedShape", MathTransform2D.class, Shape.class, AffineTransform.class, AffineTransform.class, Boolean.TYPE);
             method.setAccessible(true);
             return (Shape) method.invoke(null, (MathTransform2D) this, shape, null, null, false);
         } catch (ReflectiveOperationException e) {
             throw new TransformException(e);
         }
     }
derivative()
Matrix derivative (final Point2D point) throws TransformException inherited
Gets the derivative of this transform at a point.
The default implementation performs the following steps:
Ensure that this math transform getSourceDimensions() source dimensions} is equals to 2. Note that the getTargetDimensions() target dimensions} can be anything, not necessarily 2 (so this transform doesn't need to implement the MathTransform2D interface).
Copy the coordinate in a temporary array and pass that array to the transform(double[], int, double[], int, boolean) method, with the
derivate
boolean argument set to
true
.
If the later method returned a non-null matrix, returns that matrix. Otherwise throws TransformException.
Parameters
point The coordinate point where to evaluate the derivative.
Returns
The derivative at the specified point as a 2×2 matrix.
Exceptions
MismatchedDimensionException if the input dimension is not 2.
TransformException if the derivative can't be evaluated at the specified point.
See also
MathTransform2D::derivative(Point2D)
References Errors.Keys.CantComputeDerivative, Errors.format(), AbstractMathTransform.mismatchedDimension(), and AbstractMathTransform.transform().
Referenced by AbstractMathTransform.Inverse.derivative(), and GridTransform.transform().
{
         final int dimSource = getSourceDimensions();
         if (dimSource != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("point", 2, dimSource));
         }
         final double[] coordinate = new double[] {point.getX(), point.getY()};
         final Matrix derivative = transform(coordinate, 0, null, 0, true);
         if (derivative == null) {
             throw new TransformException(Errors.format(Errors.Keys.CantComputeDerivative));
         }
         return derivative;
     }
ensureNonNull()
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException static protected inherited
Makes sure that an argument is non-null.
This is a convenience method for subclass constructors.
Parameters
name Argument name.
object User argument.
Exceptions
InvalidParameterValueException if
object
is null.
References Errors.format(), and Errors.Keys.NullArgument_1.
Referenced by EarthGravitationalModel.EarthGravitationalModel().
     {
         if (object == null) {
             throw new InvalidParameterValueException(Errors.format(
                         Errors.Keys.NullArgument_1, name), name, object);
         }
     }
equals()
boolean equals (final Object object, final ComparisonMode mode) inherited
Compares this transform with the specified object for equality.
This method returns
true
if the two objects are of the same class and have the same width}, height}, getTargetDimensions target dimension} and the same values in all valid grid cells. Note that the grids are not required to be of the same type (TYPE_FLOAT, TYPE_DOUBLE, etc.) if the values casted to the
double
type are equal.
References Utilities.equals(), GridTransform.grid, GridTransform.GridTransform(), GridTransform.height, GridTransform.scaleX, GridTransform.scaleY, GridTransform.width, GridTransform.xOrigin, and GridTransform.yOrigin.
{
         if (object == this) {
             return true;
         }
         if (super.equals(object, mode)) {
             final GridTransform that = (GridTransform) object;
             if (width == that.width && height == that.height &&
                 Utilities.equals(xOrigin, that.xOrigin) &&
                 Utilities.equals(yOrigin, that.yOrigin) &&
                 Utilities.equals(scaleX,  that.scaleX)  &&
                 Utilities.equals(scaleY,  that.scaleY))
             {
                 final int dstDim = grid.getNumBanks();
                 if (dstDim == that.grid.getNumBanks()) {
                     final int size = width * height;
                     for (int b=0; b<dstDim; b++) {
                         for (int i=0; i<size; i++) {
                             final double va = this.grid.getElemDouble(b,i);
                             final double vb = that.grid.getElemDouble(b,i);
                             if (!Utilities.equals(va, vb)) {
                                 return false;
                             }
                         }
                     }
                     return true;
                 }
             }
         }
         return false;
     }
formatTo()
String formatTo (Formatter formatter) inherited
{
         return super.formatTo(formatter);
     }
getName()
String getName () inherited
Returns a name for this math transform (never.
null
). This convenience methods returns the name of the #getParameterDescriptors parameter descriptors} if any, or the short class name otherwise.
Returns
A name for this math transform (never
null
).
Since
2.5
Referenced by AbstractMathTransform.Inverse.getName().
{
         final ParameterDescriptorGroup descriptor = getParameterDescriptors();
         if (descriptor != null) {
             final Identifier identifier = descriptor.getName();
             if (identifier != null) {
                 final String code = identifier.getCode();
                 if (code != null) {
                     return code;
                 }
             }
         }
         return Classes.getShortClassName(this);
     }
getSourceDimensions()
final int getSourceDimensions () inherited
Returns the dimension of input points, which is 2.
References GridTransform.srcDim.
{
         return srcDim;
     }
getTargetDimensions()
final int getTargetDimensions () inherited
Returns the dimension of output points.
This is the number of banks in the underlying grid}.
{
         return grid.getNumBanks();
     }
inverse()
synchronized MathTransform2D inverse () throws NoninvertibleTransformException
Returns the inverse of this transform.
Exceptions
NoninvertibleTransformException If this transform is not invertible.
References GridTransform.type.
{
         if (inverse == null) {
             switch (type) {
                 case LOCALIZATION: {
                     // Actually throws an exception since this transform is not invertible.
                     inverse = (MathTransform2D) super.inverse();
                     break;
                 }
                 default: {
                     inverse = new Inverse();
                     break;
                 }
             }
         }
         return inverse;
     }
isIdentity()
boolean isIdentity () inherited
Returns.
false
since this transform is not the identity one.
{
         return false;
     }
mismatchedDimension()
static String mismatchedDimension (final String argument, final int dimension, final int expected) static package inherited
Constructs an error message for the MismatchedDimensionException.
CAUTION: Argument order is different than in Apache SIS.
Parameters
argument The argument name with the wrong number of dimensions.
dimension The wrong dimension.
expected The expected dimension.
References Errors.format(), and Errors.Keys.MismatchedDimension_3.
Referenced by AbstractMathTransform.createTransformedShape(), AbstractMathTransform.derivative(), and AbstractMathTransform.transform().
{
         return Errors.format(Errors.Keys.MismatchedDimension_3, argument, dimension, expected);
     }
transform() [1/6]
Point2D transform (final Point2D ptSrc, final Point2D ptDst) throws TransformException inherited
Transforms the specified.
ptSrc
and stores the result in
ptDst
. The default implementation performs the following steps:
Ensures that the getSourceDimensions() source} and getTargetDimensions() target dimensions} of this math transform are equal to 2.
Delegates to the transform(double[],int,double[],int,boolean) method using a temporary array of doubles.
Parameters
ptSrc The coordinate point to be transformed.
ptDst The coordinate point that stores the result of transforming
ptSrc
, or
null
if a new point should be created.
Returns
The coordinate point after transforming
ptSrc
and storing the result in
ptDst
, or in a new point if
ptDst
was null.
Exceptions
MismatchedDimensionException If this transform doesn't map two-dimensional coordinate systems.
TransformException If the point can't be transformed.
See also
MathTransform2D::transform(Point2D,Point2D)
References AbstractMathTransform.mismatchedDimension().
Referenced by AbstractMathTransform.derivative().
{
         int dim;
         if ((dim = getSourceDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("ptSrc", 2, dim));
         }
         if ((dim = getTargetDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("ptDst", 2, dim));
         }
         final double[] ord = new double[] {ptSrc.getX(), ptSrc.getY()};
         transform(ord, 0, ord, 0, false);
         if (ptDst != null) {
             ptDst.setLocation(ord[0], ord[1]);
             return ptDst;
         } else {
             return new Point2D.Double(ord[0], ord[1]);
         }
     }
transform() [2/6]
Matrix transform (final double [] srcPts, final int srcOff, final double [] dstPts, int dstOff, final boolean derivate) inherited
Transforms a source coordinate into target coordinate.
The transformation will involve bilinear interpolations if the source coordinates are not integer values. This method can also estimate the derivative at the location of the transformed points.
Parameters
srcPts The source coordinate.
srcOff Index of the first valid ordinate in the
srcPts
array.
dstPts Where to store the target coordinate, or
null
.
dstOff Index where to store the first ordinate.
derivate
References AbstractMathTransform.derivative(), GridTransform.width, GridTransform.xOrigin, and GridTransform.yOrigin.
Referenced by GridTransform2D.Inverse.transform(), and GridTransform.transform().
     {
         /*
          * Following code is a copy-and-paste of:
          *
          *    transform(null, srcPts, srcOff, null, dstPts, dstOff, 1);
          *
          * with the loop over many points and the management of overlapping array removeds,
          * since they are managed by the caller. This code is copied because this method is
          * invoked often during inverse transformations.
          *
          * In addition, derivative calculation has been in-lined.
          */
         final double x = srcPts[srcOff  ];
         final double y = srcPts[srcOff+1];
         final double xi = (x - xOrigin) * scaleX;
         final double yi = (y - yOrigin) * scaleY;
         final int col = Math.max(Math.min((int) xi, width  - 2), 0);
         final int row = Math.max(Math.min((int) yi, height - 2), 0);
         final int offset00 = col + row*width;
         final int offset01 = offset00 + width;
         final int offset10 = offset00 + 1;
         final int offset11 = offset01 + 1;
         final double dx = xi - col;
         final double dy = yi - row;
         final int dstDim = grid.getNumBanks();
         final Matrix derivative = derivate ? Matrices.createDiagonal(dstDim, srcDim) : null;
         for (int j=0; j<dstDim; j++) {
             final double v00 = (grid.getElemDouble(j, offset00));
             final double v01 = (grid.getElemDouble(j, offset01));
             final double v10 = (grid.getElemDouble(j, offset10));
             final double v11 = (grid.getElemDouble(j, offset11));
             if (derivative != null) {
                 double dxj = (v10 - v00); dxj += ((v11 - v01) - dxj) * dy;
                 double dyj = (v01 - v00); dyj += ((v11 - v10) - dyj) * dx;
                 switch (type) {
                     case NTv2:
                     case NADCON: {
                         dxj /= -3600;
                         dyj /= +3600;
                         break;
                     }
                 }
                 derivative.setElement(j, 0, dxj);
                 derivative.setElement(j, 1, dyj);
             }
             if (dstPts != null) {
                 final double v0  = (v10 - v00) * dx + v00;
                 final double v1  = (v11 - v01) * dx + v01;
                 double value = v0 + (v1-v0) * dy;
                 switch (type) {
                     case OFFSET: {
                         switch (j) {
                             case 0: value += x; break;
                             case 1: value += y; break;
                         }
                         break;
                     }
                     case NTv2:
                     case NADCON: {
                         switch (j) {
                             case 0: value = x - value/3600; break;
                             case 1: value = y + value/3600; break;
                         }
                         break;
                     }
                 }
                 dstPts[dstOff++] = value;
             }
         }
         return derivative;
     }
transform() [3/6]
void transform (final double [] srcPts, int srcOff, final double [] dstPts, int dstOff, int numPts) inherited
Transforms a source coordinate into target coordinate.
The transformation will involve bilinear interpolations if the source coordinates are not integer values.
Parameters
srcPts The source coordinates.
srcOff Index of the first valid ordinate in the
srcPts
array.
dstPts Where to store the target coordinates.
dstOff Index where to store the first ordinate.
References GridTransform.transform().
     {
         transform(null, srcPts, srcOff, null, dstPts, dstOff, numPts);
     }
transform() [4/6]
void transform (final float [] srcPts, int srcOff, final float [] dstPts, int dstOff, int numPts) inherited
Transforms a source coordinate into target coordinate.
The transformation will involve bilinear interpolations if the source coordinates are not integer values.
Parameters
srcPts The source coordinates.
srcOff Index of the first valid ordinate in the
srcPts
array.
dstPts Where to store the target coordinates.
dstOff Index where to store the first ordinate.
References GridTransform.transform().
     {
         transform(srcPts, null, srcOff, dstPts, null, dstOff, numPts);
     }
transform() [5/6]
void transform (final double [] srcPts, int srcOff, final float [] dstPts, int dstOff, int numPts) inherited
Transforms a source coordinate into target coordinate.
The transformation will involve bilinear interpolations if the source coordinates are not integer values.
Parameters
srcPts The source coordinates.
srcOff Index of the first valid ordinate in the
srcPts
array.
dstPts Where to store the target coordinates.
dstOff Index where to store the first ordinate.
References GridTransform.transform().
     {
         transform(null, srcPts, srcOff, dstPts, null, dstOff, numPts);
     }
transform() [6/6]
void transform (final float [] srcPts, int srcOff, final double [] dstPts, int dstOff, int numPts) inherited
Transforms a source coordinate into target coordinate.
The transformation will involve bilinear interpolations if the source coordinates are not integer values.
Parameters
srcPts The source coordinates.
srcOff Index of the first valid ordinate in the
srcPts
array.
dstPts Where to store the target coordinates.
dstOff Index where to store the first ordinate.
References GridTransform.transform().
     {
         transform(srcPts, null, srcOff, null, dstPts, dstOff, numPts);
     }
Member Data Documentation
grid
final transient DataBuffer grid protected inherited
The grid of values.
The DataBuffer::getSize size} is equal to the product of the width} and height}. The number of banks determines the getTargetDimensions target dimension}, which is typically 2. The buffer type is typically DataBufferFloat or DataBufferDouble, but is not restricted to.
When a
transform
method is invoked, a target value is interpolated for every banks in the data buffer. Values in each data buffer bank are stored in row-major order.
Referenced by GridTransform.equals(), and GridTransform.GridTransform().
height
final int height protected inherited
Number of rows in the grid.
Referenced by GridTransform.equals(), GridTransform.GridTransform(), and GridTransform.readObject().
inverse
transient MathTransform2D inverse private
The inverse of this math transform.
Will be created only when first needed.
Referenced by GridTransform2D.Inverse.readObject().
scaleY
final double scaleY package inherited
Referenced by GridTransform.equals().
serialVersionUID
final long serialVersionUID = -5797129125459758798L static private
Serial number for inter-operability with different versions.
type
final GridType type package inherited
Whatever the grid values are directly the target coordinates or offsets to apply on source coordinates.
Referenced by GridTransform.GridTransform(), and GridTransform2D.inverse().
width
final int width protected inherited
Number of columns in the grid.
Referenced by GridTransform.equals(), and GridTransform.transform().
yOrigin
final double yOrigin package inherited
Referenced by GridTransform.equals(), and GridTransform.transform().