jena-geo: WKTParsingAuthorityFactory Class Reference
WKTParsingAuthorityFactory Class Reference
A CRS Authority Factory that manages object creation by parsing <cite>Well Known Text</cite> (WKT) strings.
Classes
class Codes
The set of codes for a specific type of CRS.
class Parser
The WKT parser for this authority factory.
Public Member Functions
WKTParsingAuthorityFactory (final Map< String, String > definitions, Citation... authorities)
Creates a factory for the specified authorities using the definitions in the given map.
synchronized Citation getAuthority ()
Returns the authority.
synchronized Set< String > getAuthorityCodes (final Class<? extends IdentifiedObject > type) throws FactoryException
Returns the set of authority codes of the given type.
InternationalString getDescriptionText (final String code) throws NoSuchAuthorityCodeException, FactoryException
Gets a description of the object corresponding to a code.
synchronized IdentifiedObject createObject (final String code) throws NoSuchAuthorityCodeException, FactoryException
Returns an arbitrary object from a code.
synchronized CoordinateReferenceSystem createCoordinateReferenceSystem (final String code) throws NoSuchAuthorityCodeException, FactoryException
Returns a coordinate reference system from a code.
Citation getVendor ()
Returns the vendor responsible for creating this factory implementation.
String getBackingStoreDescription () throws FactoryException
Returns a description of the underlying backing store, or.
Static Public Attributes
static final Logger LOGGER = Logging.getLogger("org.geotoolkit.referencing.factory")
The logger for event related to Geotk factories.
Protected Member Functions
String trimAuthority (String code)
Trims the authority scope, if presents.
synchronized void dispose (final boolean shutdown)
Releases resources immediately instead of waiting for the garbage collector.
final NoSuchAuthorityCodeException noSuchAuthorityCode (final Class<?> type, final String code)
Creates an exception for an unknown authority code.
Static Protected Member Functions
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException
Makes sure that an argument is non-null.
Protected Attributes
final NameFactory nameFactory
The name factory to use for creating GenericName.
final ReferencingFactoryContainer factories
The underlying factories used for objects creation.
Package Functions
WKTParsingAuthorityFactory (final Map< String, String > definitions)
Creates a factory without authorities.
Citation [] getAuthorities ()
Returns all authority names.
Citation getPrimaryKeyAuthority ()
Returns the authority which is responsible for the maintenance of the primary keys, or.
Comparable<?> getPrimaryKey (Class<? extends IdentifiedObject > type, String code) throws FactoryException
Returns the primary key for the specified authority code.
Static Package Functions
[static initializer]
static FactoryException databaseFailure (final Class<?> type, final String code, final Throwable exception)
Wraps an Exception into a FactoryException.
static Class<?> getWKTClassOf (String element)
Returns the class of the specified WKT element.
static String getWKTNameOf (final Class<?> type)
Returns the WKT name of the specified object type.
Package Attributes
Citation authority
The authority for this factory.
Citation [] authorities
The authorities for this factory, usually as an array of length 1.
final Map< String, String > definitions
The properties object for our properties file.
Private Member Functions
String getWKT (final Class<? extends IdentifiedObject > type, final String code, final Parser parser) throws FactoryException
Returns the Well Know Text from a code.
Parser getParser ()
Returns the parser.
Private Attributes
transient Set< String > codes
An unmodifiable view of the authority keys.
transient Map< Class<? extends IdentifiedObject >, Set< String > > filteredCodes
Views of codes for different types.
transient Parser parser
A WKT parser.
Static Private Attributes
static final Map< String, Class<?> > TYPES
The mapping between WKT element name and the object class to be created.
Detailed Description
A CRS Authority Factory that manages object creation by parsing <cite>Well Known Text</cite> (WKT) strings.
The strings may be loaded from property files or be queried in a database (for example the
"spatial_ref_sys"
table in a PostGIS database).
This base implementation expects a map of (code, WKT) entries, where the authority codes are the keys and WKT strings are the values. If the map is backed by a store which may throw checked exceptions (for example a connection to a PostGIS database), then it shall wrap the checked exceptions in BackingStoreExceptions.
{
more than one authority}
There is usually only one authority for a given instance of
WKTParsingAuthorityFactory
, but more authorities can be given to the constructor if the CRS objects to create should have more than one CoordinateReferenceSystem::getIdentifiers identifier}, each with the same code but different namespace. For example a org.geotoolkit.referencing.factory.epsg.EsriExtension factory for CRS defined by ESRI} uses the
"ESRI"
namespace, but also the
"EPSG"
namespace because those CRS are used as extension of the EPSG database. Consequently the same CRS can be identified as both
"ESRI:53001"
and
"EPSG:53001"
, where
"53001"
is a unused code in the official EPSG database.
{
of CRS objects}
This factory doesn't cache any result. Any call to a
createFoo
method will trig a new WKT parsing. For adding caching service, this factory should be wrapped in org.geotoolkit.referencing.factory.CachingAuthorityFactory.
Author
Jody Garnett (Refractions)
Rueben Schulz (UBC)
Martin Desruisseaux (IRD, Geomatys)
Version
3.14
Since
3.10 (derived from 3.00)
Constructor & Destructor Documentation
WKTParsingAuthorityFactory() [1/2]
WKTParsingAuthorityFactory (final Map< String, String > definitions, Citation... authorities)
Creates a factory for the specified authorities using the definitions in the given map.
There is usually only one authority, but more can be given when the objects to create should have more than one CoordinateReferenceSystem::getIdentifiers identifier}, each with the same code but different namespace. See the class javadoc for more details.
Parameters
definitions The object definitions as a map with authority codes as keys and WKT strings as values.
authorities The organizations or parties responsible for definition and maintenance of the database.
References WKTParsingAuthorityFactory.definitions, Errors.Keys.EmptyArray, DirectAuthorityFactory.ensureNonNull(), and Errors.format().
{
         this(definitions);
         ensureNonNull("authorities", authorities);
         if (authorities.length == 0) {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.EmptyArray));
         }
         this.authorities = authorities = authorities.clone();
         for (final Citation authority : authorities) {
             ensureNonNull("authority", authority);
         }
     }
WKTParsingAuthorityFactory() [2/2]
WKTParsingAuthorityFactory (final Map< String, String > definitions) package
Creates a factory without authorities.
This is subclass responsibility to initialize the authorities field when first needed.
References WKTParsingAuthorityFactory.definitions, and DirectAuthorityFactory.ensureNonNull().
{
         ensureNonNull("definitions", definitions);
         this.definitions = definitions;
     }
Member Function Documentation
[static initializer]()
[static initializer] () static package
createCoordinateReferenceSystem()
synchronized CoordinateReferenceSystem createCoordinateReferenceSystem (final String code) throws NoSuchAuthorityCodeException, FactoryException
Returns a coordinate reference system from a code.
If the object type is know at compile time, it is recommended to invoke the most precise method instead of this one.
Parameters
code Value allocated by authority.
Exceptions
NoSuchAuthorityCodeException if the specified
code
was not found.
FactoryException if the object creation failed for some other reason.
References WKTParsingAuthorityFactory.getParser(), and WKTParsingAuthorityFactory.getWKT().
Referenced by WKTParsingAuthorityFactory.createObject(), and PropertyEpsgFactory.reportInstantiationFailures().
     {
         final Parser parser = getParser();
         final String wkt = getWKT(CoordinateReferenceSystem.class, code, parser);
         return parser.createFromWKT(wkt);
     }
createObject()
synchronized IdentifiedObject createObject (final String code) throws NoSuchAuthorityCodeException, FactoryException
Returns an arbitrary object from a code.
If the object type is know at compile time, it is recommended to invoke the most precise method instead of this one.
Parameters
code Value allocated by authority.
Exceptions
NoSuchAuthorityCodeException if the specified
code
was not found.
FactoryException if the object creation failed for some other reason.
References WKTParsingAuthorityFactory.createCoordinateReferenceSystem().
     {
         return createCoordinateReferenceSystem(code);
     }
databaseFailure()
static FactoryException databaseFailure (final Class<?> type, final String code, final Throwable exception) static package
Wraps an Exception into a FactoryException.
The given exception is typically a java.sql.SQLException.
Parameters
type The type of the object being created, or
null
if unknown.
code The code of the object being created, or
null
if unknown.
exception The exception that occurred while querying the backing store.
Returns
A factory exception wrapping the given exception.
References Errors.Keys.DatabaseFailure_2, Errors.format(), Vocabulary.format(), and Vocabulary.Keys.Unknown.
Referenced by DirectPostgisFactory.getAuthorityCodes(), DirectPostgisFactory.getAuthorityNames(), DirectPostgisFactory.getBackingStoreDescription(), DirectPostgisFactory.getPrimaryKey(), and WKTParsingAuthorityFactory.getWKT().
{
         String message = exception.getLocalizedMessage();
         if (code != null) {
             String typeName;
             if (type != null) {
                 typeName = type.getSimpleName();
             } else {
                 typeName = Vocabulary.format(Vocabulary.Keys.Unknown);
             }
             message = Errors.format(Errors.Keys.DatabaseFailure_2, typeName, code) + ": " + message;
         }
         return new FactoryException(message, exception);
     }
dispose()
synchronized void dispose (final boolean shutdown) protected
Releases resources immediately instead of waiting for the garbage collector.
{
         authority     = null;
         authorities   = null;
         codes         = null;
         filteredCodes = null;
         parser        = null;
         super.dispose(shutdown);
     }
ensureNonNull()
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException static protected inherited
Makes sure that an argument is non-null.
This is a convenience method for subclass methods.
Parameters
name Argument name.
object User argument.
Exceptions
InvalidParameterValueException if
object
is null.
References Errors.format(), and Errors.Keys.NullArgument_1.
Referenced by DirectAuthorityFactory.DirectAuthorityFactory(), DirectPostgisFactory.getPrimaryKey(), WKTParsingAuthorityFactory.getWKT(), PropertyAuthorityFactory.load(), and WKTParsingAuthorityFactory.WKTParsingAuthorityFactory().
     {
         if (object == null) {
             throw new InvalidParameterValueException(Errors.format(
                     Errors.Keys.NullArgument_1, name), name, object);
         }
     }
getAuthorities()
Citation [] getAuthorities () package
Returns all authority names.
The default implementation returns the authority given to the constructor. This method must be overridden if the subclass used the constructor without authority list. This method is not allowed to return
null
.
The returned array shall contain the value returned by getPrimaryKeyAuthority()}, if non-null.
Returns
All authorities known to this factory. Do not modify, since this method returns a direct reference to the internal array.
References WKTParsingAuthorityFactory.authorities, Errors.Keys.DisposedFactory, and Errors.format().
Referenced by WKTParsingAuthorityFactory.Parser.complete(), WKTParsingAuthorityFactory.getAuthority(), and WKTParsingAuthorityFactory.trimAuthority().
{
         if (authorities == null) {
             throw new IllegalStateException(Errors.format(Errors.Keys.DisposedFactory));
         }
         return authorities;
     }
getAuthority()
synchronized Citation getAuthority ()
Returns the authority.
The default implementation returns the first citation given to the constructor, or a modified version of that citation if many of them were given to the constructor. In the later case, the returned citation will have a set of Citation::getIdentifiers() identifiers} which is the union of identifiers of all citations given to the constructor.
References WKTParsingAuthorityFactory.authority, WKTParsingAuthorityFactory.getAuthorities(), and WKTParsingAuthorityFactory.getPrimaryKeyAuthority().
Referenced by DirectPostgisFactory.getBackingStoreDescription().
{
         if (authority == null) {
             Citation[] authorities = getAuthorities();
             final Citation pkAuthority = getPrimaryKeyAuthority();
             if (pkAuthority != null) {
                 for (int i=0; i<authorities.length; i++) {
                     if (pkAuthority.equals(authorities[i])) {
                         authorities = ArraysExt.remove(authorities, i, 1);
                         break;
                     }
                 }
             }
             switch (authorities.length) {
                 case 0: authority = new SimpleCitation("Unknown"); break;
                 case 1: authority = authorities[0]; break;
                 default: {
                     final DefaultCitation c = new DefaultCitation(authorities[0]);
                     final Collection<Identifier> identifiers = c.getIdentifiers();
                     for (int i=1; i<authorities.length; i++) {
                         identifiers.addAll(authorities[i].getIdentifiers());
                     }
                     c.transitionTo(DefaultCitation.State.FINAL);
                     authority = c;
                     break;
                 }
             }
         }
         return authority;
     }
getAuthorityCodes()
synchronized Set<String> getAuthorityCodes (final Class<? extends IdentifiedObject > type) throws FactoryException
Returns the set of authority codes of the given type.
The
type
argument specifies the base class. For example if this factory is an instance of CRSAuthorityFactory, then:
CoordinateReferenceSystem.class
asks for all authority codes accepted by createGeographicCRS, createProjectedCRS, createVerticalCRS, createTemporalCRS and any other method returning a sub-type of
CoordinateReferenceSystem
.
ProjectedCRS.class
asks only for authority codes accepted by createProjectedCRS.
The default implementation filters the set of codes based on the
"PROJCS"
and
"GEOGCS"
at the start of the WKT strings.
Parameters
type The spatial reference objects type (can be
IdentifiedObject.class
).
Returns
The set of authority codes for spatial reference objects of the given type. If this factory doesn't contains any object of the given type, then this method returns an empty set.
Exceptions
FactoryException if access to the underlying database failed.
References WKTParsingAuthorityFactory.codes.
Referenced by PropertyEpsgFactory.reportDuplicates(), and PropertyEpsgFactory.reportInstantiationFailures().
     {
         if (codes == null) {
             codes = Collections.unmodifiableSet(definitions.keySet());
         }
         if (type == null || type.isAssignableFrom(IdentifiedObject.class)) {
             return codes;
         }
         if (filteredCodes == null) {
             filteredCodes = new HashMap<>();
         }
         Set<String> filtered = filteredCodes.get(type);
         if (filtered == null) {
             filtered = new Codes(type);
             filteredCodes.put(type, filtered);
         }
         return filtered;
     }
getBackingStoreDescription()
String getBackingStoreDescription () throws FactoryException inherited
Returns a description of the underlying backing store, or.
null
if unknown. This is for example the database software used for storing the data. The default implementation returns always
null
.
Returns
The description of the underlying backing store, or
null
.
Exceptions
FactoryException if a failure occurs while fetching the engine description.
{
         return null;
     }
getDescriptionText()
InternationalString getDescriptionText (final String code) throws NoSuchAuthorityCodeException, FactoryException
Gets a description of the object corresponding to a code.
Parameters
code Value allocated by authority.
Returns
A description of the object, or
null
if the object corresponding to the specified
code
has no description.
Exceptions
NoSuchAuthorityCodeException if the specified
code
was not found.
FactoryException if the query failed for some other reason.
References WKTParsingAuthorityFactory.getWKT().
     {
         final String wkt;
         synchronized (this) {
             wkt = getWKT(IdentifiedObject.class, code, null);
         }
         int start = wkt.indexOf('"');
         if (start >= 0) {
             final int end = wkt.indexOf('"', ++start);
             if (end >= 0) {
                 return new SimpleInternationalString(wkt.substring(start, end).trim());
             }
         }
         return null;
     }
getParser()
Parser getParser () private
Returns the parser.
References WKTParsingAuthorityFactory.parser.
Referenced by WKTParsingAuthorityFactory.createCoordinateReferenceSystem().
{
         if (parser == null) {
             parser = new Parser();
         }
         return parser;
     }
getPrimaryKey()
Comparable<?> getPrimaryKey (Class<? extends IdentifiedObject > type, String code) throws FactoryException package
Returns the primary key for the specified authority code.
The default implementation returns the given code with the "authority" part trimmed. This method is overridden by DirectPostgisFactory. Note that
DirectPostgisFactory
will trim the authority itself, because it needs the authority part of the code.
Parameters
type The type of the object being created.
code The authority code to convert to primary key value.
Returns
The primary key for the supplied code.
Exceptions
FactoryException if an error occurred while querying the database.
See also
getPrimaryKeyAuthority()
References WKTParsingAuthorityFactory.trimAuthority().
Referenced by WKTParsingAuthorityFactory.Codes.baseToDerived(), and WKTParsingAuthorityFactory.getWKT().
{
         return trimAuthority(code);
     }
getPrimaryKeyAuthority()
Citation getPrimaryKeyAuthority () package
Returns the authority which is responsible for the maintenance of the primary keys, or.
null
if none. The returned value (if non-null) shall also be one of the elements returned by getAuthorities().
The default implementation returns
null
in all cases. This method is overridden and made public by implementations that are backed by a SQL database. For example the DirectPostgisFactory overrides this method in order to return Citations#POSTGIS.
Returns
The authority which is reponsible for the maintenance of primary keys, or
null
if none.
See also
#getPrimaryKey(Class, String)
Referenced by WKTParsingAuthorityFactory.Parser.complete(), and WKTParsingAuthorityFactory.getAuthority().
{
         return null;
     }
getVendor()
Citation getVendor () inherited
Returns the vendor responsible for creating this factory implementation.
Many implementations from different vendors may be available for the same factory interface.
The default for Geotk implementations is to return Citations::GEOTOOLKIT Geotoolkit.org}.
Returns
The vendor for this factory implementation.
See also
Citations::GEOTOOLKIT
References DirectAuthorityFactory.getAuthority().
{
         return new SimpleCitation(getClass().getName().startsWith("org.geotoolkit.") ? "Geotk" : "Unknown");
     }
getWKT()
String getWKT (final Class<? extends IdentifiedObject > type, final String code, final Parser parser) throws FactoryException private
Returns the Well Know Text from a code.
Parameters
type The type of the object to be created.
code Value allocated by authority.
parser If non-null, code and primary key will be stored in this parser.
Returns
The Well Know Text (WKT) for the specified code.
Exceptions
NoSuchAuthorityCodeException if the specified
code
was not found.
References WKTParsingAuthorityFactory.Parser.code, WKTParsingAuthorityFactory.databaseFailure(), DirectAuthorityFactory.ensureNonNull(), WKTParsingAuthorityFactory.getPrimaryKey(), DirectAuthorityFactory.noSuchAuthorityCode(), WKTParsingAuthorityFactory.Parser.primaryKey, and WKTParsingAuthorityFactory.Codes.type.
Referenced by WKTParsingAuthorityFactory.createCoordinateReferenceSystem(), and WKTParsingAuthorityFactory.getDescriptionText().
     {
         assert Thread.holdsLock(this);
         ensureNonNull("code", code);
         final Comparable<?> pk;
         final String wkt;
         try {
             pk = getPrimaryKey(type, code);
             wkt = definitions.get(pk);
         } catch (BackingStoreException e) {
             final Throwable cause = e.getCause();
             if (cause instanceof FactoryException) {
                 throw (FactoryException) cause;
             }
             throw databaseFailure(type, code, cause);
         }
         if (wkt == null) {
             throw noSuchAuthorityCode(type, code);
         }
         if (parser != null) {
             parser.code = code;
             parser.primaryKey = pk;
         }
         return wkt.trim();
     }
getWKTClassOf()
static Class<?> getWKTClassOf (String element) static package
Returns the class of the specified WKT element.
For example this method returns ProjectedCRS}.class for element "@code PROJCS @endcode ".
This method is the converse of getNameOf.
Parameters
element The WKT element name.
Returns
The GeoAPI class of the specified element, or
null
if unknown.
References WKTParsingAuthorityFactory.getWKTNameOf(), and WKTParsingAuthorityFactory.Codes.type.
Referenced by WKTParsingAuthorityFactory.Codes.baseToDerived().
{
         if (element == null) {
             return null;
         }
         element = element.trim().toUpperCase(Locale.US);
         final Class<?> type = TYPES.get(element);
         assert type == null || type.equals(MathTransform.class) || element.equals(getWKTNameOf(type)) : type;
         return type;
     }
getWKTNameOf()
static String getWKTNameOf (final Class<?> type) static package
Returns the WKT name of the specified object type.
For example this method returns "@code PROJCS @endcode " for type ProjectedCRS}.class.
This method is the converse of getClassOf.
Parameters
type The GeoAPI class of the specified element.
Returns
The WKT element name, or
null
if unknown.
Referenced by SpatialRefSysMap.getAuthorityCodes(), and WKTParsingAuthorityFactory.getWKTClassOf().
{
         if (type != null) {
             for (final Map.Entry<String,Class<?>> entry : TYPES.entrySet()) {
                 final Class<?> candidate = entry.getValue();
                 if (candidate.isAssignableFrom(type)) {
                     return entry.getKey();
                 }
             }
         }
         return null;
     }
noSuchAuthorityCode()
final NoSuchAuthorityCodeException noSuchAuthorityCode (final Class<?> type, final String code) protected inherited
Creates an exception for an unknown authority code.
This convenience method is provided for implementation of
createXXX
methods.
Parameters
type The GeoAPI interface that was to be created (e.g.
CoordinateReferenceSystem.class
).
code The unknown authority code.
Returns
An exception initialized with an error message built from the specified informations.
References Errors.format(), DirectAuthorityFactory.getAuthority(), Errors.Keys.NoSuchAuthorityCode_3, and DirectAuthorityFactory.trimAuthority().
Referenced by IGNF.createCoordinateReferenceSystem(), DirectPostgisFactory.getPrimaryKey(), and WKTParsingAuthorityFactory.getWKT().
{
         final InternationalString authority = getAuthority().getTitle();
         return new NoSuchAuthorityCodeException(Errors.format(Errors.Keys.NoSuchAuthorityCode_3,
                    code, authority, type), authority.toString(), trimAuthority(code), code);
     }
trimAuthority()
String trimAuthority (String code) protected
Trims the authority scope, if presents.
If more than one authority were given at WKTParsingAuthorityFactory construction time}, then any of them may appears as the scope in the supplied code.
Parameters
code The code to trim.
Returns
The code without the authority scope.
References WKTParsingAuthorityFactory.getAuthorities(), and DirectAuthorityFactory.nameFactory.
Referenced by WKTParsingAuthorityFactory.Parser.complete(), and WKTParsingAuthorityFactory.getPrimaryKey().
{
         code = code.trim();
         final GenericName name  = nameFactory.parseGenericName(null, code);
         if (name instanceof ScopedName) {
             final GenericName scope = ((ScopedName) name).path();
             final String candidate = scope.toString();
             final Citation[] authorities = getAuthorities();
             for (int i=0; i<authorities.length; i++) {
                 if (Citations.identifierMatches(authorities[i], candidate)) {
                     return name.tip().toString().trim();
                 }
             }
         }
         return code;
     }
Member Data Documentation
authorities
Citation [] authorities package
The authorities for this factory, usually as an array of length 1.
Referenced by WKTParsingAuthorityFactory.Parser.complete(), DirectPostgisFactory.dispose(), DirectPostgisFactory.getAuthorities(), WKTParsingAuthorityFactory.getAuthorities(), PropertyAuthorityFactory.load(), PropertyAuthorityFactory.PropertyAuthorityFactory(), and PropertyEpsgFactory.PropertyEpsgFactory().
authority
Citation authority package
The authority for this factory.
Will be computed by getAuthority() when first needed.
Referenced by DirectPostgisFactory.dispose(), DirectPostgisFactory.getAuthorities(), WKTParsingAuthorityFactory.getAuthority(), DirectPostgisFactory.getBackingStoreDescription(), DirectPostgisFactory.getPrimaryKey(), and PropertyAuthorityFactory.load().
codes
transient Set<String> codes private
An unmodifiable view of the authority keys.
Will be created when first needed.
Referenced by WKTParsingAuthorityFactory.getAuthorityCodes(), and PropertyEpsgFactory.reportInstantiationFailures().
definitions
final Map<String,String> definitions package
The properties object for our properties file.
Keys are the authority code for a coordinate reference system and the associated value is a WKT string for the CRS.
Referenced by DirectPostgisFactory.dispose(), PropertyAuthorityFactory.dispose(), DirectPostgisFactory.getAuthorityCodes(), DirectPostgisFactory.getAuthorityNames(), DirectPostgisFactory.getBackingStoreDescription(), DirectPostgisFactory.getPrimaryKey(), PropertyAuthorityFactory.load(), and WKTParsingAuthorityFactory.WKTParsingAuthorityFactory().
factories
final ReferencingFactoryContainer factories protected inherited
The underlying factories used for objects creation.
Referenced by IGNF.createCoordinateReferenceSystem(), and DirectAuthorityFactory.DirectAuthorityFactory().
filteredCodes
transient Map<Class<? extends IdentifiedObject>, Set<String> > filteredCodes private
Views of codes for different types.
Views will be constructed only when first needed. View are always up to date even if entries are added or removed in the definitions} map.
LOGGER
final Logger LOGGER = Logging.getLogger("org.geotoolkit.referencing.factory") static inherited
The logger for event related to Geotk factories.
Referenced by DirectPostgisFactory.getAuthorities(), PropertyAuthorityFactory.log(), and PropertyAuthorityFactory.PropertyAuthorityFactory().
nameFactory
final NameFactory nameFactory protected inherited
The name factory to use for creating GenericName.
Since
3.00
Referenced by WKTParsingAuthorityFactory.trimAuthority().
parser
transient Parser parser private
A WKT parser.
Will be created when first needed.
Referenced by WKTParsingAuthorityFactory.getParser().
TYPES
final Map<String,Class<?> > TYPES static private
The mapping between WKT element name and the object class to be created.
Keys must be upper case.