jena-geo: VerticalTransform Class Reference
VerticalTransform Class Reference abstract
Base class for transformations from a <cite>height above the ellipsoid</cite> to a <cite>height above the geoid</cite>.
Public Member Functions
final int getSourceDimensions ()
Gets the dimension of input points, which is 3.
final int getTargetDimensions ()
Gets the dimension of output points, which is 3.
Matrix transform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff, final boolean derivate) throws TransformException
Transforms a single coordinate point in a list of ordinal values, and optionally computes the derivative at that location.
void transform (double[] srcPts, int srcOff, double[] dstPts, int dstOff, int numPts) throws TransformException
Transforms a list of coordinate point ordinal values.
void transform (float[] srcPts, int srcOff, float[] dstPts, int dstOff, int numPts) throws TransformException
Transforms a list of coordinate point ordinal values.
void transform (float [] srcPts, int srcOff, double[] dstPts, int dstOff, int numPts) throws TransformException
Transforms a list of coordinate point ordinal values.
void transform (double[] srcPts, int srcOff, float [] dstPts, int dstOff, int numPts) throws TransformException
Transforms a list of coordinate point ordinal values.
String getName ()
Returns a name for this math transform (never.
Point2D transform (final Point2D ptSrc, final Point2D ptDst) throws TransformException
Transforms the specified.
Shape createTransformedShape (final Shape shape) throws TransformException
Transform the specified shape.
Matrix derivative (final Point2D point) throws TransformException
Gets the derivative of this transform at a point.
String formatTo (Formatter formatter)
Protected Member Functions
VerticalTransform ()
Creates a new instance of.
abstract double heightOffset (double longitude, double latitude, double height) throws TransformException
Returns the value to add to a <cite>height above the ellipsoid</cite> in order to get a <cite>height above the geoid</cite> for the specified geographic coordinate.
Static Protected Member Functions
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException
Makes sure that an argument is non-null.
Static Package Functions
static String mismatchedDimension (final String argument, final int dimension, final int expected)
Constructs an error message for the MismatchedDimensionException.
Static Private Attributes
static final int DIMENSION = 3
The input and output dimension.
Detailed Description
Base class for transformations from a <cite>height above the ellipsoid</cite> to a <cite>height above the geoid</cite>.
This transform expects three-dimensional geographic coordinates in (longitude, latitude, height) order. The transformations are usually backed by some ellipsoid-dependent database.
Author
Martin Desruisseaux (IRD, Geomatys)
Version
3.20
Since
2.3
Constructor & Destructor Documentation
VerticalTransform()
VerticalTransform () protected
Creates a new instance of.
VerticalTransform
.
{
     }
Member Function Documentation
createTransformedShape()
Shape createTransformedShape (final Shape shape) throws TransformException inherited
Transform the specified shape.
The default implementation computes quadratic curves using three points for each line segment in the shape. The returned object is often a Path2D, but may also be a Line2D or a QuadCurve2D if such simplification is possible.
Parameters
shape Shape to transform.
Returns
Transformed shape, or
shape
if this transform is the identity transform.
Exceptions
IllegalStateException if this transform doesn't map 2D coordinate systems.
TransformException if a transform failed.
See also
MathTransform2D::createTransformedShape(Shape)
References AbstractMathTransform.mismatchedDimension().
{
         int dim;
         if ((dim = getSourceDimensions()) != 2 || (dim = getTargetDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("shape", 2, dim));
         }
         if (isIdentity()) return shape;
         try {
             final Method method = org.apache.sis.referencing.operation.transform.AbstractMathTransform2D.class.getMethod(
                     "createTransformedShape", MathTransform2D.class, Shape.class, AffineTransform.class, AffineTransform.class, Boolean.TYPE);
             method.setAccessible(true);
             return (Shape) method.invoke(null, (MathTransform2D) this, shape, null, null, false);
         } catch (ReflectiveOperationException e) {
             throw new TransformException(e);
         }
     }
derivative()
Matrix derivative (final Point2D point) throws TransformException inherited
Gets the derivative of this transform at a point.
The default implementation performs the following steps:
Ensure that this math transform getSourceDimensions() source dimensions} is equals to 2. Note that the getTargetDimensions() target dimensions} can be anything, not necessarily 2 (so this transform doesn't need to implement the MathTransform2D interface).
Copy the coordinate in a temporary array and pass that array to the transform(double[], int, double[], int, boolean) method, with the
derivate
boolean argument set to
true
.
If the later method returned a non-null matrix, returns that matrix. Otherwise throws TransformException.
Parameters
point The coordinate point where to evaluate the derivative.
Returns
The derivative at the specified point as a 2×2 matrix.
Exceptions
MismatchedDimensionException if the input dimension is not 2.
TransformException if the derivative can't be evaluated at the specified point.
See also
MathTransform2D::derivative(Point2D)
References Errors.Keys.CantComputeDerivative, Errors.format(), AbstractMathTransform.mismatchedDimension(), and AbstractMathTransform.transform().
Referenced by AbstractMathTransform.Inverse.derivative(), and GridTransform.transform().
{
         final int dimSource = getSourceDimensions();
         if (dimSource != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("point", 2, dimSource));
         }
         final double[] coordinate = new double[] {point.getX(), point.getY()};
         final Matrix derivative = transform(coordinate, 0, null, 0, true);
         if (derivative == null) {
             throw new TransformException(Errors.format(Errors.Keys.CantComputeDerivative));
         }
         return derivative;
     }
ensureNonNull()
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException static protected inherited
Makes sure that an argument is non-null.
This is a convenience method for subclass constructors.
Parameters
name Argument name.
object User argument.
Exceptions
InvalidParameterValueException if
object
is null.
References Errors.format(), and Errors.Keys.NullArgument_1.
Referenced by EarthGravitationalModel.EarthGravitationalModel().
     {
         if (object == null) {
             throw new InvalidParameterValueException(Errors.format(
                         Errors.Keys.NullArgument_1, name), name, object);
         }
     }
formatTo()
String formatTo (Formatter formatter) inherited
{
         return super.formatTo(formatter);
     }
getName()
String getName () inherited
Returns a name for this math transform (never.
null
). This convenience methods returns the name of the #getParameterDescriptors parameter descriptors} if any, or the short class name otherwise.
Returns
A name for this math transform (never
null
).
Since
2.5
Referenced by AbstractMathTransform.Inverse.getName().
{
         final ParameterDescriptorGroup descriptor = getParameterDescriptors();
         if (descriptor != null) {
             final Identifier identifier = descriptor.getName();
             if (identifier != null) {
                 final String code = identifier.getCode();
                 if (code != null) {
                     return code;
                 }
             }
         }
         return Classes.getShortClassName(this);
     }
getSourceDimensions()
final int getSourceDimensions ()
Gets the dimension of input points, which is 3.
References VerticalTransform.DIMENSION.
Referenced by VerticalTransform.transform().
{
         return DIMENSION;
     }
getTargetDimensions()
final int getTargetDimensions ()
Gets the dimension of output points, which is 3.
References VerticalTransform.DIMENSION, and VerticalTransform.heightOffset().
Referenced by VerticalTransform.transform().
{
         return DIMENSION;
     }
heightOffset()
abstract double heightOffset (double longitude, double latitude, double height) throws TransformException abstract protected
Returns the value to add to a <cite>height above the ellipsoid</cite> in order to get a <cite>height above the geoid</cite> for the specified geographic coordinate.
Parameters
longitude The geodetic longitude, in decimal degrees.
latitude The geodetic latitude, in decimal degrees.
height The height above the ellipsoid in metres.
Returns
The value to add in order to get the height above the geoid (in metres).
Exceptions
TransformException if the offset can't be computed for the specified coordinates.
Referenced by VerticalTransform.getTargetDimensions(), and VerticalTransform.transform().
mismatchedDimension()
static String mismatchedDimension (final String argument, final int dimension, final int expected) static package inherited
Constructs an error message for the MismatchedDimensionException.
CAUTION: Argument order is different than in Apache SIS.
Parameters
argument The argument name with the wrong number of dimensions.
dimension The wrong dimension.
expected The expected dimension.
References Errors.format(), and Errors.Keys.MismatchedDimension_3.
Referenced by AbstractMathTransform.createTransformedShape(), AbstractMathTransform.derivative(), and AbstractMathTransform.transform().
{
         return Errors.format(Errors.Keys.MismatchedDimension_3, argument, dimension, expected);
     }
transform() [1/6]
Matrix transform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff, final boolean derivate) throws TransformException
Transforms a single coordinate point in a list of ordinal values, and optionally computes the derivative at that location.
Exceptions
TransformException If the point can't be transformed.
Since
3.20 (derived from 3.00)
References VerticalTransform.getSourceDimensions(), VerticalTransform.getTargetDimensions(), and VerticalTransform.heightOffset().
     {
         if (dstPts != null) {
             final double x = srcPts[srcOff  ];
             final double y = srcPts[srcOff+1];
             final double z = srcPts[srcOff+2];
             dstPts[dstOff  ] = x;
             dstPts[dstOff+1] = y;
             dstPts[dstOff+2] = z + heightOffset(x,y,z);
         }
         return derivate ? Matrices.createDiagonal(getTargetDimensions(), getSourceDimensions()) : null;
     }
transform() [2/6]
void transform (double [] srcPts, int srcOff, double [] dstPts, int dstOff, int numPts) throws TransformException
Transforms a list of coordinate point ordinal values.
References VerticalTransform.DIMENSION, and VerticalTransform.heightOffset().
     {
         boolean reverse = false;
         if (srcPts == dstPts) {
             switch (IterationStrategy.suggest(srcOff, DIMENSION, dstOff, DIMENSION, numPts)) {
                 case ASCENDING: {
                     break;
                 }
                 case DESCENDING: {
                     final int offset = (numPts-1) * DIMENSION;
                     srcOff += offset;
                     dstOff += offset;
                     reverse = true;
                     break;
                 }
                 default: {
                     srcPts = Arrays.copyOfRange(srcPts, srcOff, srcOff + numPts*DIMENSION);
                     srcOff = 0;
                     break;
                 }
             }
         }
         while (--numPts >= 0) {
             final double x = srcPts[srcOff++];
             final double y = srcPts[srcOff++];
             final double z = srcPts[srcOff++];
             dstPts[dstOff++] = x;
             dstPts[dstOff++] = y;
             dstPts[dstOff++] = z + heightOffset(x,y,z);
             if (reverse) {
                 srcOff -= 2*DIMENSION;
                 dstOff -= 2*DIMENSION;
             }
         }
     }
transform() [3/6]
Point2D transform (final Point2D ptSrc, final Point2D ptDst) throws TransformException inherited
Transforms the specified.
ptSrc
and stores the result in
ptDst
. The default implementation performs the following steps:
Ensures that the getSourceDimensions() source} and getTargetDimensions() target dimensions} of this math transform are equal to 2.
Delegates to the transform(double[],int,double[],int,boolean) method using a temporary array of doubles.
Parameters
ptSrc The coordinate point to be transformed.
ptDst The coordinate point that stores the result of transforming
ptSrc
, or
null
if a new point should be created.
Returns
The coordinate point after transforming
ptSrc
and storing the result in
ptDst
, or in a new point if
ptDst
was null.
Exceptions
MismatchedDimensionException If this transform doesn't map two-dimensional coordinate systems.
TransformException If the point can't be transformed.
See also
MathTransform2D::transform(Point2D,Point2D)
References AbstractMathTransform.mismatchedDimension().
Referenced by AbstractMathTransform.derivative().
{
         int dim;
         if ((dim = getSourceDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("ptSrc", 2, dim));
         }
         if ((dim = getTargetDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("ptDst", 2, dim));
         }
         final double[] ord = new double[] {ptSrc.getX(), ptSrc.getY()};
         transform(ord, 0, ord, 0, false);
         if (ptDst != null) {
             ptDst.setLocation(ord[0], ord[1]);
             return ptDst;
         } else {
             return new Point2D.Double(ord[0], ord[1]);
         }
     }
transform() [4/6]
void transform (float [] srcPts, int srcOff, float [] dstPts, int dstOff, int numPts) throws TransformException
Transforms a list of coordinate point ordinal values.
References VerticalTransform.DIMENSION, and VerticalTransform.heightOffset().
     {
         boolean reverse = false;
         if (srcPts == dstPts) {
             switch (IterationStrategy.suggest(srcOff, DIMENSION, dstOff, DIMENSION, numPts)) {
                 case ASCENDING: {
                     break;
                 }
                 case DESCENDING: {
                     final int offset = (numPts-1) * DIMENSION;
                     srcOff += offset;
                     dstOff += offset;
                     reverse = true;
                     break;
                 }
                 default: {
                     srcPts = Arrays.copyOfRange(srcPts, srcOff, srcOff + numPts*DIMENSION);
                     srcOff = 0;
                     break;
                 }
             }
         }
         while (--numPts >= 0) {
             final float  x = srcPts[srcOff++];
             final float  y = srcPts[srcOff++];
             final double z = srcPts[srcOff++];
             dstPts[dstOff++] = x;
             dstPts[dstOff++] = y;
             dstPts[dstOff++] = (float) (z + heightOffset(x,y,z));
             if (reverse) {
                 srcOff -= 2*DIMENSION;
                 dstOff -= 2*DIMENSION;
             }
         }
     }
transform() [5/6]
void transform (float [] srcPts, int srcOff, double [] dstPts, int dstOff, int numPts) throws TransformException
Transforms a list of coordinate point ordinal values.
References VerticalTransform.heightOffset().
     {
         while (--numPts >= 0) {
             final double x,y,z;
             dstPts[dstOff++] =  (x = srcPts[srcOff++]);
             dstPts[dstOff++] =  (y = srcPts[srcOff++]);
             dstPts[dstOff++] = ((z = srcPts[srcOff++]) + heightOffset(x,y,z));
         }
     }
transform() [6/6]
void transform (double [] srcPts, int srcOff, float [] dstPts, int dstOff, int numPts) throws TransformException
Transforms a list of coordinate point ordinal values.
References VerticalTransform.heightOffset().
     {
         while (--numPts >= 0) {
             final double x,y,z;
             dstPts[dstOff++] = (float)  (x = srcPts[srcOff++]);
             dstPts[dstOff++] = (float)  (y = srcPts[srcOff++]);
             dstPts[dstOff++] = (float) ((z = srcPts[srcOff++]) + heightOffset(x,y,z));
         }
     }
Member Data Documentation
DIMENSION
final int DIMENSION = 3 static private
The input and output dimension.
Referenced by VerticalTransform.getSourceDimensions(), VerticalTransform.getTargetDimensions(), and VerticalTransform.transform().