jena-geo: UnitaryProjection Class Reference
UnitaryProjection Class Reference abstract
Protected Member Functions
UnitaryProjection (final OperationMethod method, final org.apache.sis.parameter.Parameters parameters, Map< ParameterRole, ParameterDescriptor< Double >> roles)
Constructs a new map projection from the supplied parameters.
abstract void inverseTransform (double[] srcPts, int srcOff, double[] dstPts, int dstOff) throws ProjectionException
Package Functions
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor)
final double msfn (final double sinφ, final double cosφ)
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
final double ssfn (double φ, double sinφ)
Computes part of function (3-1) from Snyder.
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ)
Computes the derivative of the ssfn(double, double) method divided by.
final double qsfn (final double sinφ)
Calculates q, Snyder equation (3-12).
final double dqsfn_dφ (final double sinφ, final double cosφ)
Gets the derivative of the qsfn(double) method.
Static Package Functions
static boolean isSpherical (final Parameters parameters)
Static Package Attributes
static final double ANGLE_TOLERANCE = 1E-6
Maximum difference allowed when comparing longitudes or latitudes in radians.
static final double ITERATION_TOLERANCE = 1E-10
Difference allowed in iterative computations.
static final int MAXIMUM_ITERATIONS = 15
Maximum number of iterations for iterative computations.
static final double EPSILON = 1E-7
Maximum difference allowed when comparing real numbers (other cases).
Static Private Member Functions
static Map< ParameterRole, ParameterDescriptor< Double > > defaultMap (final OperationMethod projection) throws ParameterNotFoundException, ClassCastException
Provides default (role → parameter) associations for the given map projection.
Static Private Attributes
static final double ARGUMENT_TOLERANCE = 1E-15
Tolerance in the correctness of argument values provided to the mathematical functions defined in this class.
Constructor & Destructor Documentation
UnitaryProjection()
UnitaryProjection (final OperationMethod method, final org.apache.sis.parameter.Parameters parameters, Map< ParameterRole, ParameterDescriptor< Double >> roles) protected
Constructs a new map projection from the supplied parameters.
Parameters
parameters The parameters of the projection to be created.
References UnitaryProjection.defaultMap().
     {
         super(method, parameters, (roles != null) ? roles : defaultMap(method));
     }
Member Function Documentation
defaultMap()
static Map<ParameterRole, ParameterDescriptor<Double> > defaultMap (final OperationMethod projection) throws ParameterNotFoundException, ClassCastException static private
Provides default (role → parameter) associations for the given map projection.
This is a convenience method for a typical set of parameters found in map projections. This method expects a
projection
argument containing descriptors for the given parameters (using OGC names):
"semi_major"
"semi_minor"
"central_meridian"
"scale_factor"
"false_easting"
"false_northing"
Note: Apache SIS uses EPSG names as much as possible, but this method is an exception to this rule. In this particular case we use OGC names because they are identical for a wide range of projections. For example there is at least #SCALE_FACTOR three different EPSG names} for the <cite>"scale factor"</cite> parameter, which OGC defines only
"scale_factor"
for all of them.
Parameters
projection The map projection method for which to infer (role → parameter) associations.
Returns
The parameters associated to most role in this enumeration.
Exceptions
ParameterNotFoundException if one of the above-cited parameters is not found in the given projection method.
ClassCastException if a parameter has been found but is not an instance of
ParameterDescriptor<Double>
.
Referenced by UnitaryProjection.UnitaryProjection().
     {
         final ParameterDescriptorGroup parameters = projection.getParameters();
         final EnumMap<ParameterRole, ParameterDescriptor<Double>> roles = new EnumMap<>(ParameterRole.class);
         for (final ParameterRole role : ParameterRole.values()) {
             if (role != ParameterRole.LATITUDE_OF_CONFORMAL_SPHERE_RADIUS &&
                 role != ParameterRole.FALSE_WESTING && role != ParameterRole.FALSE_SOUTHING)
             {
                 final String name = role.name().toLowerCase();
                 final GeneralParameterDescriptor p = parameters.descriptor(name);
                 roles.put(role, Parameters.cast((ParameterDescriptor<?>) p, Double.class));
             }
         }
         return roles;
     }
dqsfn_dφ()
final double dqsfn_dφ (final double sinφ, final double cosφ) package
Gets the derivative of the qsfn(double) method.
Parameters
sinφ The sine of latitude.
cosφ The cosines of latitude.
Returns
The
qsfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by LambertAzimuthalEqualArea.transform().
{
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         double esinφ2 = eccentricity * sinφ;
         esinφ2 *= esinφ2;
         return (1 - eccentricitySquared) * (cosφ / (1 - esinφ2)) * (1 + ((1 + esinφ2) / (1 - esinφ2)));
     }
dssfn_dφ()
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ) package
Computes the derivative of the ssfn(double, double) method divided by.
ssfn
. Callers must multiply the return value by
ssfn
in order to get the actual value.
Parameters
φ The latitude.
sinφ the sine of latitude.
cosφ The cosine of latitude.
Returns
The
dssfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         assert !(abs(cosφ - cos(φ)) > ARGUMENT_TOLERANCE) : φ;
         return (1/cosφ) - (eccentricitySquared*cosφ)/(1-eccentricitySquared*sinφ*sinφ);
         /*
          * NOTE: 0.5*(t + 1/t)   =   1/cosφ
          */
     }
getAndStore()
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor) package
Referenced by CassiniOrMercator.CassiniOrMercator(), Krovak.Krovak(), LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), NewZealandMapGrid.NewZealandMapGrid(), Orthographic.Orthographic(), and Stereographic.Stereographic().
{
         final double value = parameters.doubleValue(descriptor);    // Apply a unit conversion if needed.
         final Double defaultValue = descriptor.getDefaultValue();
         if (defaultValue == null || !defaultValue.equals(value)) {
             org.apache.sis.internal.referencing.provider.MapProjection.validate(descriptor, value);
             String name = IdentifiedObjects.getName(descriptor, parameters.getDescriptor().getName().getAuthority());
             if (name == null) {
                 name = descriptor.getName().getCode();
             }
             getContextualParameters().parameter(name).setValue(value);
         }
         return value;
     }
inverseTransform()
abstract void inverseTransform (double [] srcPts, int srcOff, double [] dstPts, int dstOff) throws ProjectionException abstract protected
Referenced by UnitaryProjection.isSpherical().
isSpherical()
static boolean isSpherical (final Parameters parameters) static package
References UnitaryProjection.inverseTransform().
Referenced by CassiniSoldner.create(), Stereographic.create(), LambertAzimuthalEqualArea.create(), and LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
{
         return parameters.parameter("semi_major").doubleValue() == parameters.parameter("semi_minor").doubleValue();
     }
msfn()
final double msfn (final double sinφ, final double cosφ) package
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
Special cases:
If φ is 0°, then this method returns 1.
If φ is ±90°, then this method returns 0 provided that we are not in the spherical case (otherwise we get Double#NaN).
Parameters
sinφ The sine of the φ latitude in radians.
cosφ The cosine of the φ latitude in radians.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic().
                                                               {               // == cosφ / rν(sinφ)
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         return cosφ / sqrt(1.0 - (sinφ*sinφ) * eccentricitySquared);
     }
qsfn()
final double qsfn (final double sinφ) package
Calculates q, Snyder equation (3-12).
This equation has the following properties:
Input in the [-1 ... +1] range.
Output in the [-2 ... +2] range.
Output is 0 when input is 0.
Output of the same sign than input.
qsfn(-sinφ) == -qsfn(sinφ)
.
Parameters
sinφ Sine of the latitude q is calculated for.
Returns
q from Snyder equation (3-12).
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.transform().
{
         if (eccentricity < EPSILON) {
             return 2 * sinφ;
         }
         /*
          * Above check was required because the expression below would simplify to
          * sinφ - 0.5/0*log(1) where the right terms are infinity multiplied by
          * zero, thus producing NaN.
          */
         final double esinφ = eccentricity * sinφ;
         return (1 - eccentricitySquared) * (sinφ / (1 - esinφ*esinφ) + atanh(esinφ)/eccentricity);
     }
ssfn()
final double ssfn (double φ, double sinφ) package
Computes part of function (3-1) from Snyder.
This is numerically equivalent to #tsfn tsfn}(-φ, sinφ), but is defined as a separated function for clarity and because the function properties are not the same.
Parameters
φ The latitude in radians.
sinφ The sine of the φ argument. This is provided explicitly because in many cases, the caller has already computed this value.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic(), EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         sinφ *= eccentricity;
         return tan(PI/4 + 0.5*φ) * pow((1-sinφ) / (1+sinφ), 0.5*eccentricity);
     }
Member Data Documentation
ANGLE_TOLERANCE
final double ANGLE_TOLERANCE = 1E-6 static package
Maximum difference allowed when comparing longitudes or latitudes in radians.
A tolerance of 1E-6 is about 0.2 second of arcs, which is about 6 kilometers (computed from the standard length of nautical mile).
Some formulas use this tolerance value for testing sinus or cosinus of an angle. In the sinus case, this is justified because sin(θ) ≅ θ when θ is small. Similar reasoning applies to cosinus with cos(θ) ≅ θ + π/2 when θ is small.
Referenced by Stereographic.create(), Orthographic.inverseTransform(), LambertAzimuthalEqualArea.inverseTransform(), Orthographic.Orthographic(), and Stereographic.Stereographic().
ARGUMENT_TOLERANCE
final double ARGUMENT_TOLERANCE = 1E-15 static private
Tolerance in the correctness of argument values provided to the mathematical functions defined in this class.
Since
3.18
Referenced by UnitaryProjection.dqsfn_dφ(), UnitaryProjection.dssfn_dφ(), UnitaryProjection.msfn(), and UnitaryProjection.ssfn().
EPSILON
final double EPSILON = 1E-7 static package
Maximum difference allowed when comparing real numbers (other cases).
The value defined here is consistent with the one that was used in LambertAzimuthalEqualArea for the same purpose (not to be confused with the current
EPSILON
constant defined in the above-mentioned class, which has been renamed), and the modified value used in AlbersEqualArea.
ITERATION_TOLERANCE
final double ITERATION_TOLERANCE = 1E-10 static package
Difference allowed in iterative computations.
A value of 1E-10 causes the cphi2 function to compute the latitude at a precision of 1E-10 radians, which is slightly smaller than one millimetre.
Referenced by CassiniOrMercator.inv_mlfn(), and Stereographic.inverseTransform().
MAXIMUM_ITERATIONS
final int MAXIMUM_ITERATIONS = 15 static package
Maximum number of iterations for iterative computations.
Referenced by CassiniOrMercator.inv_mlfn(), Stereographic.inverseTransform(), and Krovak.inverseTransform().