jena-geo: ProcessFinder Class Reference
ProcessFinder Class Reference
Utility class to find Process factories and descriptors.
Static Public Member Functions
static synchronized Iterator< ProcessingRegistry > getProcessFactories ()
static synchronized ProcessingRegistry getProcessFactory (final String authorityCode)
Return the factory for the given authority code.
static synchronized ProcessDescriptor getProcessDescriptor (String authority, final String processName) throws NoSuchIdentifierException
Search for a Process descriptor in the given authority and the given name.
static void scanForPlugins ()
Research all ProcessingRegistries at next ProcessFinder call.
static ProcessingRegistry getProcessFactory (final Iterator<? extends ProcessingRegistry > factories, final String authorityCode)
Return the factory for the given authority code.
static ProcessDescriptor getProcessDescriptor (final Iterator<? extends ProcessingRegistry > factories, String authority, final String processName) throws NoSuchIdentifierException
Search for a Process descriptor in the given authority and the given name.
Private Member Functions
ProcessFinder ()
Static Private Attributes
static List< ProcessingRegistry > REGISTRIES = null
Detailed Description
Utility class to find Process factories and descriptors.
At he fist ProcessFinder method call, he finder will use ServiceRegistry to lookup all ProcessingRegistry in jar files and he cache this list of ProcessingRegistry.
To update the list, call scanForPlugins() method.
Usage : //get all factories Iterator<ProcessingRegistry> registries = ProcessFinder.getProcessFactories();
//get a factory from her name ProcessingRegistry registry = ProcessFinder.getProcessFactory("myFactoryName");
//get a ProcessDescriptor from specific factory ProcessingRegistry registry = ProcessFinder.getProcessDescriptor("myFactoryName", "processDescriptorName");
//search a ProcessDescriptor without knowing registry name. ProcessingRegistry registry = ProcessFinder.getProcessDescriptor(null, "processDescriptorName");
//Rescan jars with ServiceRegistry to get the last ProcessRegistries ProcessFinder.scanForPlugins();
Author
Johann Sorel (Geomatys)
Quentin Boileau (Geomatys) pending
Constructor & Destructor Documentation
ProcessFinder()
ProcessFinder () private
{
     }
Member Function Documentation
getProcessDescriptor() [1/2]
static synchronized ProcessDescriptor getProcessDescriptor (String authority, final String processName) throws NoSuchIdentifierException static
Search for a Process descriptor in the given authority and the given name.
Parameters
authority registry name
processName process descriptor name
Returns
ProcessDescriptor
Exceptions
IllegalArgumentException if description could not be found
References ProcessingRegistry.getDescriptor(), ProcessFinder.getProcessFactories(), and ProcessFinder.getProcessFactory().
{
         if (authority != null && authority.trim().isEmpty()) {
             authority = null;
         }
         if (authority != null) {
             final ProcessingRegistry factory = getProcessFactory(authority);
             if (factory != null) {
                 return factory.getDescriptor(processName);
             } else {
                 throw new NoSuchIdentifierException("No processing registry for given code.", authority);
             }
         }
         //try all factories
         final Iterator<ProcessingRegistry> ite = getProcessFactories();
         while (ite.hasNext()) {
             final ProcessingRegistry factory = ite.next();
             try {
                 return factory.getDescriptor(processName);
             } catch (NoSuchIdentifierException ex) {
             }
         }
         throw new NoSuchIdentifierException("No process for given code.", processName);
     }
getProcessDescriptor() [2/2]
static ProcessDescriptor getProcessDescriptor (final Iterator<? extends ProcessingRegistry > factories, String authority, final String processName) throws NoSuchIdentifierException static
Search for a Process descriptor in the given authority and the given name.
Parameters
authority registry name
processName process descriptor name
Returns
ProcessDescriptor
Exceptions
IllegalArgumentException if description could not be found
References ProcessingRegistry.getDescriptor(), and ProcessFinder.getProcessFactory().
{
         if (authority != null && authority.trim().isEmpty()) {
             authority = null;
         }
         if (authority != null) {
             final ProcessingRegistry factory = getProcessFactory(factories, authority);
             if (factory != null) {
                 return factory.getDescriptor(processName);
             } else {
                 throw new NoSuchIdentifierException("No processing registry for given code.", authority);
             }
         }
         //try all factories
         while (factories.hasNext()) {
             final ProcessingRegistry factory = factories.next();
             try {
                 return factory.getDescriptor(processName);
             } catch (NoSuchIdentifierException ex) {
             }
         }
         throw new NoSuchIdentifierException("No process for given code.", processName);
     }
getProcessFactories()
static synchronized Iterator<ProcessingRegistry> getProcessFactories () static
Returns
Iterator of all available ProcessFactory.
Referenced by ProcessFinder.getProcessDescriptor(), and ProcessFinder.getProcessFactory().
{
         if (REGISTRIES == null) {
             final Iterator<ProcessingRegistry> ite = ServiceLoader.load(ProcessingRegistry.class).iterator();
             REGISTRIES = new ArrayList<ProcessingRegistry>();
             while (ite.hasNext()) {
                 REGISTRIES.add(ite.next());
             }
         }
         return REGISTRIES.iterator();
     }
getProcessFactory() [1/2]
static synchronized ProcessingRegistry getProcessFactory (final String authorityCode) static
Return the factory for the given authority code.
Parameters
authorityCode registry name
Returns
ProcessingRegistry or null if not found
References ProcessingRegistry.getIdentification(), and ProcessFinder.getProcessFactories().
Referenced by ProcessFinder.getProcessDescriptor().
{
         final Iterator<ProcessingRegistry> ite = getProcessFactories();
         while (ite.hasNext()) {
             final ProcessingRegistry candidate = ite.next();
             for (final Identifier id : candidate.getIdentification().getCitation().getIdentifiers()) {
                 if (id.getCode().equalsIgnoreCase(authorityCode)) {
                     return candidate;
                 }
             }
         }
         return null;
     }
getProcessFactory() [2/2]
static ProcessingRegistry getProcessFactory (final Iterator<? extends ProcessingRegistry > factories, final String authorityCode) static
Return the factory for the given authority code.
Parameters
authorityCode registry name
Returns
ProcessingRegistry or null if not found
References ProcessingRegistry.getIdentification().
{
         while (factories.hasNext()) {
             final ProcessingRegistry candidate = factories.next();
             for (final Identifier id : candidate.getIdentification().getCitation().getIdentifiers()) {
                 if (id.getCode().equalsIgnoreCase(authorityCode)) {
                     return candidate;
                 }
             }
         }
         return null;
     }
scanForPlugins()
static void scanForPlugins () static
Research all ProcessingRegistries at next ProcessFinder call.
{
         REGISTRIES = null;
     }
Member Data Documentation
REGISTRIES
List<ProcessingRegistry> REGISTRIES = null static private