jena-geo: ReferencingFactoryContainer Class Reference
ReferencingFactoryContainer Class Reference
A container of factories frequently used together, with utility methods.
Public Member Functions
ReferencingFactoryContainer (Hints userHints)
Creates an instance from the specified hints.
Citation getVendor ()
Returns the vendor responsible for creating this factory implementation.
synchronized Map< RenderingHints.Key, ?> getImplementationHints ()
Returns all factories in this group.
synchronized DatumFactory getDatumFactory ()
Returns the Datum datum} factory.
synchronized CSFactory getCSFactory ()
Returns the CoordinateSystem coordinate system} factory.
synchronized CRSFactory getCRSFactory ()
Returns the CoordinateReferenceSystem coordinate reference system} factory.
synchronized MathTransformFactory getMathTransformFactory ()
Returns the MathTransform math transform} factory.
SingleCRS toGeodetic3D (SingleCRS crs) throws FactoryException
Adds an ellipsoidal height to the given CRS, if not already presents.
CoordinateReferenceSystem toGeodetic3D (final CompoundCRS crs) throws FactoryException
Returns a CRS equivalents to the given one, with some components replaced by their 3D counterpart when possible.
CoordinateReferenceSystem separate (final CoordinateReferenceSystem crs, final int... dimensions) throws FactoryException
Returns a new coordinate reference system with only the specified dimension.
Static Public Member Functions
static synchronized ReferencingFactoryContainer instance ()
Protected Attributes
final Map< RenderingHints.Key, Object > hints = new LinkedHashMap<>()
The getImplementationHints implementation hints}.
Private Member Functions
void fetchAllFactories ()
Forces the initialization of all factories.
void declaredFactoryHints (final Map<? super RenderingHints.Key, Object > hints)
Puts all available factories into the specified map of hints.
Hints getCurrentHints ()
Returns the hints to be used for lazy creation of default factories in various.
SingleCRS toGeodetic3D (final CompoundCRS crs, final SingleCRS horizontal, final CoordinateSystemAxis vertical, final boolean xyFirst) throws FactoryException
Implementation of toGeodetic3D(CompoundCRS) invoked after the horizontal and vertical parts have been identified.
Static Private Member Functions
static Factory getFactory (final Map<?,?> hints, final Hints.Key key)
Returns the factory for the specified hint, or.
static Matrix toStandard (final CoordinateReferenceSystem crs, final boolean inverse) throws FactoryException
Delegates to AbstractCS#standard(CoordinateSystem).
static Map< String,?> getTemporaryName (final IdentifiedObject source, final String suffix)
Returns a temporary name for object derived from the specified one.
Private Attributes
final Map< RenderingHints.Key, Object > unmodifiableHints = Collections.unmodifiableMap(hints)
An unmodifiable view of hints.
DatumFactory datumFactory
The Datum datum} factory.
CSFactory csFactory
The CoordinateSystem coordinate system} factory.
CRSFactory crsFactory
The CoordinateReferenceSystem coordinate reference system} factory.
MathTransformFactory mtFactory
The MathTransform math transform} factory.
Static Private Attributes
static ReferencingFactoryContainer cache
Detailed Description
A container of factories frequently used together, with utility methods.
This class serves two purpose:
A container for the following factories:
DatumFactory
CSFactory
CRSFactory
MathTransformFactory
Utilities methods for creating new CRS derived from an existing one.
{
Note
The CoordinateOperationFactory factory is intentionally excluded from this container, because CoordinateOperationFactory is more a processing class than a factory creating directly objects from the parameters.}
Author
Martin Desruisseaux (IRD, Geomatys)
Version
3.16
Since
2.1 advanced
Deprecated:
Replaced by org.apache.sis.internal.referencing.ReferencingFactoryContainer.
Constructor & Destructor Documentation
ReferencingFactoryContainer()
ReferencingFactoryContainer (Hints userHints)
Creates an instance from the specified hints.
This constructor recognizes the CRS, CS, DATUM and MATH_TRANSFORM
FACTORY
hints.
This constructor is public mainly for org.geotoolkit.factory.DynamicFactoryRegistry usage. Consider invoking instance instance}(userHints) instead.
Parameters
userHints The hints, or
null
if none (not the system-wide default; factory constructors consume the hints verbatism).
References Hints.clone(), Hints.CRS_FACTORY, Hints.CS_FACTORY, Hints.DATUM_FACTORY, ReferencingFactoryContainer.declaredFactoryHints(), ReferencingFactoryContainer.fetchAllFactories(), ReferencingFactoryContainer.getFactory(), and Hints.MATH_TRANSFORM_FACTORY.
Referenced by ReferencingFactoryContainer.instance().
{
         if (userHints != null) {
             userHints = userHints.clone();
             /*
              * If some factories were explicitly specified, fetch them immediately (no lazy
              * instantiation for them). Any factory not explicitly specified will be left to
              * null for now.
              */
             datumFactory =         (DatumFactory) getFactory(userHints, Hints.DATUM_FACTORY);
             csFactory    =            (CSFactory) getFactory(userHints, Hints.CS_FACTORY);
             crsFactory   =           (CRSFactory) getFactory(userHints, Hints.CRS_FACTORY);
             mtFactory    = (MathTransformFactory) getFactory(userHints, Hints.MATH_TRANSFORM_FACTORY);
             /*
              * Remove the entries consumed in the search for factories. We can do that only after
              * the search is done for all factories. If there is no remaining hints, then it doesn't
              * matter if some fields are still null. If there is some remaining hints, then we need
              * to fetch all factories that were not fetched by the above code because we can't guess
              * which hints are relevant and which ones are not.
              */
             if (datumFactory != null) userHints.remove(Hints.DATUM_FACTORY);
             if (csFactory    != null) userHints.remove(Hints.CS_FACTORY);
             if (crsFactory   != null) userHints.remove(Hints.CRS_FACTORY);
             if (mtFactory    != null) userHints.remove(Hints.MATH_TRANSFORM_FACTORY);
             if (!userHints.isEmpty()) {
                 declaredFactoryHints(userHints);          // Adds the hints for the factories we fetched above.
                 addImplementationHints(userHints, hints); // Copies temporarily the result in super.hints map.
                 fetchAllFactories();                      // Forces fetching of remaining factories.
                 hints.clear();                            // Cancel addImplementationHints(userHints).
             }
         }
     }
Member Function Documentation
declaredFactoryHints()
void declaredFactoryHints (final Map<? super RenderingHints.Key, Object > hints) private
Puts all available factories into the specified map of hints.
This method is invoked before or after fetchAllFactories, depending on whatever we are consuming or resolving hints.
References Hints.MATH_TRANSFORM_FACTORY.
Referenced by ReferencingFactoryContainer.getCurrentHints(), ReferencingFactoryContainer.getImplementationHints(), and ReferencingFactoryContainer.ReferencingFactoryContainer().
{
         if (  crsFactory != null) hints.put(Hints.           CRS_FACTORY,   crsFactory);
         if (   csFactory != null) hints.put(Hints.            CS_FACTORY,    csFactory);
         if (datumFactory != null) hints.put(Hints.         DATUM_FACTORY, datumFactory);
         if (   mtFactory != null) hints.put(Hints.MATH_TRANSFORM_FACTORY,    mtFactory);
     }
fetchAllFactories()
void fetchAllFactories () private
Forces the initialization of all factories.
This method is invoked in one of the following situations:
When we need to consume all hints specified at construction time.
When we need to resolve all hints used by the factories.
{
Note
We try to create the factories in typical dependency order, with the CRS factory last because it has the greatest chances to depends on other factories.}
References ReferencingFactoryContainer.getCRSFactory(), ReferencingFactoryContainer.getCSFactory(), ReferencingFactoryContainer.getDatumFactory(), and ReferencingFactoryContainer.getMathTransformFactory().
Referenced by ReferencingFactoryContainer.getImplementationHints(), and ReferencingFactoryContainer.ReferencingFactoryContainer().
{
         mtFactory    = getMathTransformFactory();
         datumFactory = getDatumFactory();
         csFactory    = getCSFactory();
         crsFactory   = getCRSFactory();
     }
getCRSFactory()
synchronized CRSFactory getCRSFactory ()
Returns the CoordinateReferenceSystem coordinate reference system} factory.
Returns
The Coordinate Reference System factory.
References ReferencingFactoryContainer.crsFactory.
Referenced by IGNF.createCoordinateReferenceSystem(), ReferencingFactoryContainer.fetchAllFactories(), ReferencingFactoryContainer.separate(), and ReferencingFactoryContainer.toGeodetic3D().
{
         if (crsFactory == null) {
             crsFactory = DefaultFactories.forBuildin(CRSFactory.class);
         }
         return crsFactory;
     }
getCSFactory()
synchronized CSFactory getCSFactory ()
Returns the CoordinateSystem coordinate system} factory.
Returns
The Coordinate System factory.
References ReferencingFactoryContainer.csFactory.
Referenced by ReferencingFactoryContainer.fetchAllFactories(), ReferencingFactoryContainer.separate(), and ReferencingFactoryContainer.toGeodetic3D().
{
         if (csFactory == null) {
             csFactory = DefaultFactories.forBuildin(CSFactory.class);
         }
         return csFactory;
     }
getCurrentHints()
Hints getCurrentHints () private
Returns the hints to be used for lazy creation of default factories in various.
getFoo
methods. At the difference of getImplementationHints, this method do not force fetching of factories that were not already obtained.
References Hints.clone(), ReferencingFactoryContainer.declaredFactoryHints(), and EmptyHints.INSTANCE.
{
         final Hints completed = EmptyHints.INSTANCE.clone();
         assert Thread.holdsLock(this);
         completed.putAll(hints);
         declaredFactoryHints(completed);
         return completed;
     }
getDatumFactory()
synchronized DatumFactory getDatumFactory ()
Returns the Datum datum} factory.
Returns
The Datum factory.
References ReferencingFactoryContainer.datumFactory.
Referenced by ReferencingFactoryContainer.fetchAllFactories().
{
         if (datumFactory == null) {
             datumFactory = DefaultFactories.forBuildin(DatumFactory.class);
         }
         return datumFactory;
     }
getFactory()
static Factory getFactory (final Map<?,?> hints, final Hints.Key key) static private
Returns the factory for the specified hint, or.
null
if the hint is not a factory instance (it could be for example a Class). The given hints are left untouched.
Referenced by ReferencingFactoryContainer.ReferencingFactoryContainer().
{
         final Object candidate = hints.get(key);
         return (candidate instanceof Factory) ? (Factory) candidate : null;
     }
getImplementationHints()
synchronized Map<RenderingHints.Key, ?> getImplementationHints ()
Returns all factories in this group.
The returned map contains values for the CRS, CS, DATUM and MATH_TRANSFORM
FACTORY
hints.
References ReferencingFactoryContainer.declaredFactoryHints(), ReferencingFactoryContainer.fetchAllFactories(), and ReferencingFactoryContainer.unmodifiableHints.
{
         if (hints.isEmpty()) {
             fetchAllFactories();
             declaredFactoryHints(hints);
         }
         return unmodifiableHints;
     }
getMathTransformFactory()
synchronized MathTransformFactory getMathTransformFactory ()
Returns the MathTransform math transform} factory.
Returns
The Math Transform factory.
References ReferencingFactoryContainer.mtFactory.
Referenced by IGNF.createCoordinateReferenceSystem(), ReferencingFactoryContainer.fetchAllFactories(), and ReferencingFactoryContainer.toGeodetic3D().
{
         if (mtFactory == null) {
             mtFactory = DefaultFactories.forBuildin(MathTransformFactory.class);
         }
         return mtFactory;
     }
getTemporaryName()
static Map<String,?> getTemporaryName (final IdentifiedObject source, final String suffix) static private
Returns a temporary name for object derived from the specified one.
Referenced by ReferencingFactoryContainer.separate(), and ReferencingFactoryContainer.toGeodetic3D().
{
         final Identifier id = source.getName();
         return Collections.singletonMap(IdentifiedObject.NAME_KEY,
                 new ImmutableIdentifier(null, // Null because we are inventing a code.
                     id.getCodeSpace(), id.getCode() + suffix));
     }
getVendor()
Citation getVendor ()
Returns the vendor responsible for creating this factory implementation.
Many implementations from different vendors may be available for the same factory interface.
The default for Geotk implementations is to return Citations::GEOTOOLKIT Geotoolkit.org}.
Returns
The vendor for this factory implementation.
See also
Citations::GEOTOOLKIT
{
         return new SimpleCitation(getClass().getName().startsWith("org.geotoolkit.") ? "Geotk" : "Unknown");
     }
instance()
static synchronized ReferencingFactoryContainer instance () static
References ReferencingFactoryContainer.cache, and ReferencingFactoryContainer.ReferencingFactoryContainer().
{
         if (cache == null) {
             cache = new ReferencingFactoryContainer(null);
         }
         return cache;
     }
separate()
CoordinateReferenceSystem separate (final CoordinateReferenceSystem crs, final int... dimensions) throws FactoryException
Returns a new coordinate reference system with only the specified dimension.
This method can be used for example in order to get a component of a CompoundCRS compound CRS}.
Todo:
The current implementation has incomplete support of 3D Geographic CRS. See GEOTK-129.
Parameters
crs The original (usually compound) CRS.
dimensions The dimensions to keep.
Returns
The CRS with only the specified dimensions.
Exceptions
FactoryException if the given dimensions can not be isolated in the given CRS.
See also
org.apache.sis.referencing.CRS::getComponentAt(CoordinateReferenceSystem, int, int)
References Errors.Keys.CantSeparateCrs_1, Errors.format(), ReferencingFactoryContainer.getCRSFactory(), ReferencingFactoryContainer.getCSFactory(), ReferencingFactoryContainer.getTemporaryName(), and Errors.Keys.IllegalArgument_1.
     {
         final int length = dimensions.length;
         final CoordinateSystem cs = crs.getCoordinateSystem();
         final int crsDimension = cs.getDimension();
         if (length == 0 || dimensions[0] < 0 || dimensions[length-1] >= crsDimension ||
             !ArraysExt.isSorted(dimensions, true))
         {
             throw new IllegalArgumentException(Errors.format(
                     Errors.Keys.IllegalArgument_1, "dimension"));
         }
         if (length == crsDimension) {
             return crs;
         }
         /*
          * If the CRS is a compound one, separate each components independently.
          * For each component, we search the sub-array of 'dimensions' that apply
          * to this component and invoke 'separate' recursively.
          */
         if (crs instanceof CompoundCRS) {
             int count=0, lowerDimension=0, lowerIndex=0;
             final List<CoordinateReferenceSystem> sources = ((CompoundCRS) crs).getComponents();
             final CoordinateReferenceSystem[] targets = new CoordinateReferenceSystem[sources.size()];
 search:     for (final CoordinateReferenceSystem source : sources) {
                 final int upperDimension = lowerDimension + source.getCoordinateSystem().getDimension();
                 /*
                  * 'source' CRS applies to dimension 'lowerDimension' inclusive to 'upperDimension'
                  * exclusive. Now search the smallest range in the user-specified 'dimensions' that
                  * cover the [lowerDimension .. upperDimension] range.
                  */
                 if (lowerIndex == dimensions.length) {
                     break search;
                 }
                 while (dimensions[lowerIndex] < lowerDimension) {
                     if (++lowerIndex == dimensions.length) {
                         break search;
                     }
                 }
                 int upperIndex = lowerIndex;
                 while (dimensions[upperIndex] < upperDimension) {
                     if (++upperIndex == dimensions.length) {
                         break;
                     }
                 }
                 if (lowerIndex != upperIndex) {
                     final int[] sub = new int[upperIndex - lowerIndex];
                     for (int j=0; j<sub.length; j++) {
                         sub[j] = dimensions[j+lowerIndex] - lowerDimension;
                     }
                     targets[count++] = separate(source, sub);
                 }
                 lowerDimension = upperDimension;
                 lowerIndex     = upperIndex;
             }
             if (count == 1) {
                 return targets[0];
             }
             return getCRSFactory().createCompoundCRS(getTemporaryName(crs, " (subset)"), ArraysExt.resize(targets, count));
         }
         /*
          * Three-dimensional geographic CRS.
          *
          * TODO: needs a better inspection of axis order.
          */
         if (crsDimension == 3 && (cs instanceof EllipsoidalCS) && (crs instanceof GeodeticCRS)) {
             switch (dimensions.length) {
                 case 1: {
                     if (dimensions[0] == 2) {
                         return CommonCRS.Vertical.ELLIPSOIDAL.crs();
                     }
                     break;
                 }
                 case 2: {
                     if (dimensions[0] == 0 && dimensions[1] == 1) {
                         if (Utilities.equalsIgnoreMetadata(crs, AbstractCRS.castOrCopy(CommonCRS.WGS84.geographic3D()).forConvention(AxesConvention.RIGHT_HANDED))) {    // Common case.
                             return CommonCRS.WGS84.normalizedGeographic();
                         }
                         return getCRSFactory().createGeographicCRS(getTemporaryName(crs, " (subset)"), ((GeodeticCRS) crs).getDatum(),
                                 getCSFactory().createEllipsoidalCS(getTemporaryName(cs, " (subset)"), cs.getAxis(0), cs.getAxis(1)));
                     }
                     break;
                 }
             }
         }
         /*
          * TODO: Implement other cases here (3D-GeographicCRS, etc.).
          *       It may requires the creation of new CoordinateSystem objects,
          *       which is why this method live in ReferencingFactoryContainer.
          */
         throw new FactoryException(Errors.format(
                 Errors.Keys.CantSeparateCrs_1, crs.getName().getCode()));
     }
toGeodetic3D() [1/3]
SingleCRS toGeodetic3D (SingleCRS crs) throws FactoryException
Adds an ellipsoidal height to the given CRS, if not already presents.
This method accepts only GeographicCRS geographic} or ProjectedCRS projected} CRS. If the given CRS is already three-dimensional, then it is returned unchanged. Otherwise an ellipsoidal height in the same units than the Ellipsoid::getAxisUnit() ellipsoid axis units} (typically metres) is appended as the third dimension of the given CRS, and the resulting three-dimensional CRS is returned.
Parameters
crs The geographic or projected CRS to make three-dimensional.
Returns
The given CRS with an ellipsoidal height.
Exceptions
FactoryException If an ellipsoidal height can not be added to the given CRS.
Since
3.16
References Axes.ELLIPSOIDAL_HEIGHT, Errors.format(), ReferencingFactoryContainer.getCSFactory(), and Errors.Keys.UnsupportedCrs_1.
Referenced by ReferencingFactoryContainer.toGeodetic3D().
{
         if (crs instanceof GeographicCRS || crs instanceof ProjectedCRS) {
             switch (crs.getCoordinateSystem().getDimension()) {
                 case 2: {
                     CoordinateSystemAxis vertical = Axes.ELLIPSOIDAL_HEIGHT;
                     final Unit<Length> units = ((GeodeticDatum) crs.getDatum()).getEllipsoid().getAxisUnit();
                     if (!Units.METRE.equals(units)) {
                         vertical = getCSFactory().createCoordinateSystemAxis(
                                 IdentifiedObjects.getProperties(vertical),
                                 vertical.getAbbreviation(), vertical.getDirection(), units);
                     }
                     crs = toGeodetic3D(null, crs, vertical, true);
                     // Fall through
                 }
                 case 3: {
                     return crs;
                 }
             }
         }
         throw new FactoryException(Errors.format(Errors.Keys.UnsupportedCrs_1, crs.getName()));
     }
toGeodetic3D() [2/3]
CoordinateReferenceSystem toGeodetic3D (final CompoundCRS crs) throws FactoryException
Returns a CRS equivalents to the given one, with some components replaced by their 3D counterpart when possible.
More specifically, if the given compound CRS contains two consecutive CompoundCRS::getComponents() components CRS} where:
One component is a two-dimensional GeographicCRS geographic} or ProjectedCRS projected} CRS;
The other component is a one-dimensional VerticalCRS vertical} CRS and its datum type is
ELLIPSOIDAL
(height above the ellipsoid)
Then this method replaces those two components by a single three-dimensional component. The other components (for example TemporalCRS temporal} CRS) are included unchanged in the returned CRS.
If there is no (2D + 1D) components that this method could replace by a 3D component, then this method returns the
crs
argument unchanged. In any case, the transform from the given CRS to the returned CRS shall be an identity transform.
Parameters
crs The CRS in which to replace (2D + 1D) components by 3D components.
Returns
A CRS equivalents to the given one with the replacements performed, if any.
Exceptions
FactoryException If a new CRS needs to be created and the call to its factory method failed.
References CRS.getCompoundCRS(), ReferencingFactoryContainer.getCRSFactory(), and ReferencingFactoryContainer.toGeodetic3D().
{
         SingleCRS   horizontal = null;
         VerticalCRS vertical   = null;
         int hi = -2, vi = -2; // Initial condition: Math.abs(vi-hi)!=1 even when hi==0 or vi==0.
         /*
          * Get a copy of the components list and iterate in reverse order,
          * because we may remove elements from that list while iterating.
          */
         final List<SingleCRS> components = new ArrayList<>(org.apache.sis.referencing.CRS.getSingleComponents(crs));
         final int count = components.size();
         for (int i=count; --i>=0;) {
             final SingleCRS component = components.get(i);
             if (component instanceof GeographicCRS || component instanceof ProjectedCRS) {
                 if (component.getCoordinateSystem().getDimension() == 2) {
                     horizontal = component;
                     hi = i;
                 }
             } else if (component instanceof VerticalCRS) {
                 final VerticalCRS candidate = (VerticalCRS) component;
                 if (VerticalDatumTypes.ELLIPSOIDAL.equals(candidate.getDatum().getVerticalDatumType())) {
                     vertical = candidate;
                     vi = i;
                 }
             }
             if (Math.abs(vi - hi) == 1) {
                 /*
                  * Found a horizontal and a vertical CRS, and those two CRS are consecutive. Replace
                  * them by a new 3D CRS, and continue the search in case new (2D, 1D) pairs are found.
                  */
                 final boolean xyFirst = (hi < vi);
                 final int iMin = xyFirst ? hi : vi;
                 components.remove(iMin);
                 components.set(iMin, toGeodetic3D(CRS.getCompoundCRS(crs, horizontal, vertical),
                         horizontal, vertical.getCoordinateSystem().getAxis(0), xyFirst));
             }
         }
         /*
          * At this point, all replacements (if any) have been performed. If the length of the
          * component array didn't changed, then no replacement were performed and the original
          * CRS can be returned unchanged.
          */
         final int r = components.size();
         if (r == 1) {
             return components.get(0);
         } else if (r == count) {
             return crs;
         } else {
             return getCRSFactory().createCompoundCRS(IdentifiedObjects.getProperties(crs),
                     components.toArray(new SingleCRS[components.size()]));
         }
     }
toGeodetic3D() [3/3]
SingleCRS toGeodetic3D (final CompoundCRS crs, final SingleCRS horizontal, final CoordinateSystemAxis vertical, final boolean xyFirst) throws FactoryException private
Implementation of toGeodetic3D(CompoundCRS) invoked after the horizontal and vertical parts have been identified.
This method may invoke itself recursively if the horizontal CRS is a derived one.
Parameters
crs The compound CRS to convert to a 3D geographic CRS, or
null
. Used only in order to infer the name properties of objects to create.
horizontal The horizontal component of
crs
.
vertical The vertical axis of
crs
.
xyFirst
References Identifier3D.addHorizontalCRS(), ReferencingFactoryContainer.crsFactory, ReferencingFactoryContainer.csFactory, ReferencingFactoryContainer.getCRSFactory(), ReferencingFactoryContainer.getCSFactory(), ReferencingFactoryContainer.getMathTransformFactory(), ReferencingFactoryContainer.getTemporaryName(), ReferencingFactoryContainer.mtFactory, ReferencingFactoryContainer.toGeodetic3D(), and ReferencingFactoryContainer.toStandard().
     {
         /*
          * Creates the set of axes in an order which depends of the xyFirst argument.
          * Then creates the property maps to be given to the object to be created.
          * They are common to whatever CRS type this method will create.
          */
         final CoordinateSystemAxis[] axis = new CoordinateSystemAxis[3];
         final CoordinateSystem cs = horizontal.getCoordinateSystem();
         axis[xyFirst ? 0 : 1] = cs.getAxis(0);
         axis[xyFirst ? 1 : 2] = cs.getAxis(1);
         axis[xyFirst ? 2 : 0] = vertical;
         Map<String,?> csName, crsName;
         if (crs != null) {
             csName  = IdentifiedObjects.getProperties(crs.getCoordinateSystem());
             crsName = IdentifiedObjects.getProperties(crs);
         } else {
             csName  = getTemporaryName(cs, " (3D)");
             crsName = getTemporaryName(horizontal, " (3D)");
         }
         crsName = Identifier3D.addHorizontalCRS(crsName, horizontal);
         final  CSFactory  csFactory = getCSFactory();
         final CRSFactory crsFactory = getCRSFactory();
         if (horizontal instanceof GeographicCRS) {
             /*
              * Merges a 2D geographic CRS with the vertical CRS. This is the easiest
              * part - we just give the 3 axis all together to a new GeographicCRS.
              */
             final GeographicCRS sourceCRS = (GeographicCRS) horizontal;
             final EllipsoidalCS targetCS  = csFactory.createEllipsoidalCS(csName, axis[0], axis[1], axis[2]);
             return crsFactory.createGeographicCRS(crsName, sourceCRS.getDatum(), targetCS);
         }
         if (horizontal instanceof ProjectedCRS) {
             /*
              * Merges a 2D projected CRS with the vertical CRS. This part is more tricky,
              * since we need a defining conversion which does not include axis swapping or
              * unit conversions. We revert them with concatenation of "CS to standardCS"
              * transform. The axis swapping will be added back by createProjectedCRS(...)
              * but not in the same place (they will be performed sooner than they would be
              * otherwise).
              */
             final ProjectedCRS  sourceCRS = (ProjectedCRS) horizontal;
             final CartesianCS   targetCS  = csFactory.createCartesianCS(csName, axis[0], axis[1], axis[2]);
             final GeographicCRS base2D    = sourceCRS.getBaseCRS();
             final GeographicCRS base3D    = (GeographicCRS) toGeodetic3D(null, base2D, vertical, xyFirst);
             final Matrix        prepend   = toStandard(base2D, true);
             final Matrix        append    = toStandard(sourceCRS, false);
             final MathTransformFactory mtFactory = getMathTransformFactory();
             Conversion projection = sourceCRS.getConversionFromBase();
             MathTransform mt = projection.getMathTransform();
             mt = mtFactory.createConcatenatedTransform(
                  mtFactory.createConcatenatedTransform(
                  mtFactory.createAffineTransform(prepend), mt),
                  mtFactory.createAffineTransform(append));
             mt = mtFactory.createPassThroughTransform(0, mt, 1);
             projection = new DefaultConversion(IdentifiedObjects.getProperties(projection),
                                                 projection.getMethod(), mt, null);
             return crsFactory.createProjectedCRS(crsName, base3D, projection, targetCS);
         }
         // Should never happen.
         throw new AssertionError(horizontal.getClass());
     }
toStandard()
static Matrix toStandard (final CoordinateReferenceSystem crs, final boolean inverse) throws FactoryException static private
Delegates to AbstractCS#standard(CoordinateSystem).
Parameters
crs The CRS from which to extract the CS to standardize.
inverse
References Errors.format(), and Errors.Keys.UnsupportedCrs_1.
Referenced by ReferencingFactoryContainer.toGeodetic3D().
     {
         Exception failure;
         try {
             final CoordinateSystem sourceCS = crs.getCoordinateSystem();
             final CoordinateSystem targetCS = CoordinateSystems.replaceAxes(sourceCS, AxesConvention.NORMALIZED);
             if (inverse) {
                 return CoordinateSystems.swapAndScaleAxes(targetCS, sourceCS);
             } else {
                 return CoordinateSystems.swapAndScaleAxes(sourceCS, targetCS);
             }
         } catch (IllegalArgumentException | IncommensurableException e) {
             failure = e;
         }
         throw new FactoryException(Errors.format(Errors.Keys.UnsupportedCrs_1, crs.getName()), failure);
     }
Member Data Documentation
cache
ReferencingFactoryContainer cache static private
Referenced by ReferencingFactoryContainer.instance().
crsFactory
CRSFactory crsFactory private
The CoordinateReferenceSystem coordinate reference system} factory.
If null, then a default factory will be created only when first needed.
Referenced by ReferencingFactoryContainer.getCRSFactory(), and ReferencingFactoryContainer.toGeodetic3D().
csFactory
CSFactory csFactory private
The CoordinateSystem coordinate system} factory.
If null, then a default factory will be created only when first needed.
Referenced by ReferencingFactoryContainer.getCSFactory(), and ReferencingFactoryContainer.toGeodetic3D().
datumFactory
DatumFactory datumFactory private
The Datum datum} factory.
If null, then a default factory will be created only when first needed.
Referenced by ReferencingFactoryContainer.getDatumFactory().
hints
final Map<RenderingHints.Key, Object> hints = new LinkedHashMap<>() protected
The getImplementationHints implementation hints}.
This map should be filled by subclasses at construction time. If possible, constructors should not copy blindly all user-provided hints. They should select only the relevant hints and resolve them as of getImplementationHints implementation hints} contract. For example if a org.opengis.referencing.datum.DatumAuthorityFactory datum authority factory} uses an ordinary org.opengis.referencing.datum.DatumFactory datum factory}, its method could be implemented as below (note that we should not check if the datum factory is null, since key with null value is the expected behavior in this case).
{ java hints.put(Hints.DATUM_FACTORY, datumFactory); }
This field is not an instance of
Hints
because:
The primary use of this map is to check if this factory can be reused. It is not for creating new factories.
This map needs to allow
null
values, as of getImplementationHints contract.
mtFactory
MathTransformFactory mtFactory private
The MathTransform math transform} factory.
If null, then a default factory will be created only when first needed.
Referenced by ReferencingFactoryContainer.getMathTransformFactory(), and ReferencingFactoryContainer.toGeodetic3D().
unmodifiableHints
final Map<RenderingHints.Key, Object> unmodifiableHints = Collections.unmodifiableMap(hints) private
An unmodifiable view of hints.
This is the actual map to be returned by getImplementationHints. Its content reflects the hints map even if the later is modified.
Referenced by ReferencingFactoryContainer.getImplementationHints().