jena-geo: ReferencingUtilities Class Reference
ReferencingUtilities Class Reference
Complementary utility methods for CRS manipulation.
Static Public Member Functions
static DirectPosition [] findWrapAround (CoordinateReferenceSystem crs) throws TransformException
Test if the Coordinate Reference System has a wrap around axis.
static double [] convertResolution (final Envelope srcEnvelope, final double[] oldResolution, final CoordinateReferenceSystem targetCrs, double... newResolution) throws TransformException
Convert resolution from old resolution and Envelope::getCoordinateReferenceSystem() source CRS} within srcEnvelope, and store result into destination array newResolution.
static Envelope wrapNormalize (Envelope env, DirectPosition[] warp)
static Envelope transform (Envelope env, CoordinateReferenceSystem targetCRS) throws TransformException
Transform the given envelope to the given crs.
static GeneralEnvelope combine (final Envelope bounds, final Date[] temporal, final Double[] elevation) throws TransformException
Make a new envelope with vertical and temporal dimensions.
static GeneralEnvelope combine (CoordinateReferenceSystem crs, final Rectangle2D bounds, final Date[] temporal, final Double[] elevation) throws TransformException
Make a new envelope with vertical and temporal dimensions.
static CoordinateReferenceSystem change2DComponent (final CoordinateReferenceSystem originalCRS, final CoordinateReferenceSystem crs2D) throws TransformException
Change the 2D CRS part of the CRS.
static Envelope transform2DCRS (final Envelope env, final CoordinateReferenceSystem crs2D) throws TransformException
Transform the CRS 2D component of this envelope.
static Envelope setLongitudeFirst (final Envelope env) throws TransformException, FactoryException
Try to change a coordinate reference system axis order to place the east axis first.
static CoordinateReferenceSystem setLongitudeFirst (final CoordinateReferenceSystem crs) throws FactoryException
Try to change a coordinate reference system axis order to place the east axis first.
static AffineTransform toAffine (final Dimension rect, final Envelope env)
Create an affine transform object where (0,0) in the dimension match the top left corner of the envelope.
static MathTransform toTransform (final MathTransform base, double[] ... values)
static MathTransform toTransform (final int firstBaseOrdinate, final MathTransform subTransform, final Map< Integer, double[]> axisValues, final int expectedTargetDimension)
Returns a PassThroughTransform with expectedTargetDimension number, from subtransform at dimension index firstBaseOrdinate and with axisValues infomation on each other dimensions.
static Map< Integer, CoordinateReferenceSystem > indexedDecompose (CoordinateReferenceSystem crs)
Decompose CRS and return each sub-crs along with their dimension index.
static GeneralEnvelope transposeEnvelope (final GeneralEnvelope source, GeneralEnvelope destination)
For each axis value of the source envelope, we'll set corresponding one in destination envelope, if we find a valid transform.
static GeneralEnvelope intersectEnvelopes (final Envelope layerEnvelope, final Envelope filterEnvelope) throws TransformException
Build an envelope which is the intersection between both of the parameters.
static AffineTransform readTransform (Path f) throws IOException, NumberFormatException
Read TFW file and return the content affine transform.
static String lookupIdentifier (final IdentifiedObject object, final boolean fullScan) throws FactoryException
Looks up an Identifier identifier}, such as.
static boolean intersects (Envelope env1, Envelope env2)
Test if two envelopes intersects.
static Optional<? extends GeographicBoundingBox > findGeographicBBox (final Resource r) throws DataStoreException
Try to extract a geographic bounding box from given resource.
static double orthodromicDistance (final double radius, double λ1, double φ1, double λ2, double φ2)
Returns the orthodromic distance between two geographic coordinates.
Static Public Attributes
static final double EARTH_RADIUS = 6371007
Authalic sphere radius in metres.
Private Member Functions
ReferencingUtilities ()
Static Private Member Functions
static boolean isWrapAroundCompatible (MathTransform trs)
static int [] findDimensionIndexes (CoordinateReferenceSystem crs)
Return array of dimensions indexes with [0, 1] : geographic [2] : elevation [3] : temporal.
static void checkMTToTransform (final int firstBaseOrdinate, final MathTransform subTransform, final Map< Integer, double[]> axisValues, final int expectedTargetDimension)
Check than all needed parameters to build appropriate PassThroughTransform are conform.
static Map< String, String > name (final String name)
Detailed Description
Complementary utility methods for CRS manipulation.
Author
Johann Sorel (Geomatys)
Constructor & Destructor Documentation
ReferencingUtilities()
ReferencingUtilities () private
 {}
Member Function Documentation
change2DComponent()
static CoordinateReferenceSystem change2DComponent (final CoordinateReferenceSystem originalCRS, final CoordinateReferenceSystem crs2D) throws TransformException static
Change the 2D CRS part of the CRS.
Parameters
originalCRS base CRS, possible multi-dimension
crs2D replacement 2D crs
Referenced by ReferencingUtilities.transform2DCRS().
{
         if (crs2D.getCoordinateSystem().getDimension() != 2) {
             throw new IllegalArgumentException("Expected a 2D CRS");
         }
         final CoordinateReferenceSystem targetCRS;
         if (originalCRS instanceof CompoundCRS) {
             final CompoundCRS ccrs = (CompoundCRS) originalCRS;
             final CoordinateReferenceSystem part2D = CRS.getHorizontalComponent(originalCRS);
             final List<CoordinateReferenceSystem> lst = new ArrayList<>();
             for (CoordinateReferenceSystem c : ccrs.getComponents()) {
                 if (c.equals(part2D)) {
                     //replace the 2D part
                     lst.add(crs2D);
                 } else {
                     //preserve other axis
                     lst.add(c);
                 }
             }
             try {
                 targetCRS = CRS.compound(lst.toArray(new CoordinateReferenceSystem[lst.size()]));
             } catch (FactoryException ex) {
                 throw new TransformException(ex.getMessage(), ex);      // TODO: not appropriate.
             }
         } else if (originalCRS.getCoordinateSystem().getDimension() == 2) {
             //no other axis, just reproject normally
             targetCRS = crs2D;
         } else {
             throw new UnsupportedOperationException("How do we change the 2D component of a CRS if it's not a CompoundCRS ?");
         }
         return targetCRS;
     }
checkMTToTransform()
static void checkMTToTransform (final int firstBaseOrdinate, final MathTransform subTransform, final Map< Integer, double[]> axisValues, final int expectedTargetDimension) static private
Check than all needed parameters to build appropriate PassThroughTransform are conform.
Parameters
firstBaseOrdinate the first minimum ordinate of subtransform into the expected target dimension.
subTransform the sub transformation which will be wrapped by other mathematical functions.
axisValues the list of mathmatical function for each other dimensions than already present subtransform dimensions.
expectedTargetDimension the expected target PassThroughTransform dimension.
Returns
true
if all needed dimension are informed else
false
.
Exceptions
NullArgumentException if subtransform or axisValues are
null
.
MismatchedDimensionException if expected targetDimension is lesser than subtransform dimension.
IllegalArgumentException if firstBaseOrdinate is out of target dimension boundary [0 —> targetDim - subtransform target dim]
Referenced by ReferencingUtilities.toTransform().
{
         ArgumentChecks.ensureNonNull("subTransform", subTransform);
         ArgumentChecks.ensureNonNull("axisValues", axisValues);
         final int subTransformDimensionNumber = subTransform.getTargetDimensions();
         if (expectedTargetDimension < subTransformDimensionNumber)
             throw new MismatchedDimensionException("expectedTargetDimension should be "
                     + "upper than subtransform target dimension. Expected upper than : "
                     +subTransformDimensionNumber+" found : "+expectedTargetDimension);
         ArgumentChecks.ensureBetween("firstBaseOrdinate", 0, expectedTargetDimension - subTransformDimensionNumber, firstBaseOrdinate);
         if (expectedTargetDimension > 64)
             throw new IllegalArgumentException("targetDimension > 64 not supported");
         //-- create a long where the bits ordinate are at 1 in relation with subtransform ordinate.
         long isOrdinateChecked = ((1 << (subTransformDimensionNumber)) -1) << (expectedTargetDimension - firstBaseOrdinate - subTransformDimensionNumber);
         for (final Integer dim : axisValues.keySet()) {
             isOrdinateChecked = isOrdinateChecked | (1 << (expectedTargetDimension - dim - 1));
         }
         if (isOrdinateChecked != ((1 << expectedTargetDimension) - 1)) {
             final StringBuilder strB = new StringBuilder("The following dimension must be informed : ");
             for (int d = 0; d < expectedTargetDimension; d++) {
                 long currentDim = 1 << d;
                 if ((isOrdinateChecked & currentDim) != currentDim){
                     strB.append(d);
                     if (d != (expectedTargetDimension - 1)) strB.append(",");
                 }
             }
             throw new IllegalArgumentException(strB.toString());
         }
     }
combine() [1/2]
static GeneralEnvelope combine (final Envelope bounds, final Date [] temporal, final Double [] elevation) throws TransformException static
Make a new envelope with vertical and temporal dimensions.
{
         CoordinateReferenceSystem crs = bounds.getCoordinateReferenceSystem();
         Rectangle2D rect = new Rectangle2D.Double(
                 bounds.getMinimum(0),
                 bounds.getMinimum(1),
                 bounds.getSpan(0),
                 bounds.getSpan(1));
         return combine(crs, rect, temporal, elevation);
     }
combine() [2/2]
static GeneralEnvelope combine (CoordinateReferenceSystem crs, final Rectangle2D bounds, final Date [] temporal, final Double [] elevation) throws TransformException static
Make a new envelope with vertical and temporal dimensions.
References ReferencingUtilities.findDimensionIndexes(), and CRSUtilities.getCRS2D().
{
         final CoordinateReferenceSystem crs2D = CRSUtilities.getCRS2D(crs);
         TemporalCRS temporalDim = null;
         VerticalCRS verticalDim = null;
         if(temporal != null && (temporal[0] != null || temporal[1] != null)){
             temporalDim = getTemporalComponent(crs);
             if(temporalDim == null){
                 temporalDim = CommonCRS.Temporal.JAVA.crs();
             }
         }
         if(elevation != null && (elevation[0] != null || elevation[1] != null)){
             verticalDim = getVerticalComponent(crs, true);
             if(verticalDim == null){
                 verticalDim = CommonCRS.Vertical.ELLIPSOIDAL.crs();
             }
         }
         final GeneralEnvelope env;
         if (temporalDim != null && verticalDim != null) {
             try {
                 crs = CRS.compound(crs2D, verticalDim, temporalDim);
             } catch (FactoryException ex) {
                 throw new TransformException(ex.getMessage(), ex);      // TODO: not appropriate.
             }
             env = new GeneralEnvelope(crs);
             int[] indexes = findDimensionIndexes(crs);
             env.setRange(indexes[0], bounds.getMinX(), bounds.getMaxX());
             env.setRange(indexes[1], bounds.getMinY(), bounds.getMaxY());
             try {
                 final CoordinateReferenceSystem realTemporal = CommonCRS.Temporal.JAVA.crs();
                 final MathTransform trs = CRS.findOperation(realTemporal, temporalDim, null).getMathTransform();
                 final double[] coords = new double[2];
                 coords[0] = (temporal[0] != null) ? temporal[0].getTime() : Double.NEGATIVE_INFINITY;
                 coords[1] = (temporal[1] != null) ? temporal[1].getTime() : Double.POSITIVE_INFINITY;
                 trs.transform(coords, 0, coords, 0, 2);
                 env.setRange(indexes[3],coords[0],coords[1]);
             } catch (FactoryException ex) {
                 throw new TransformException(ex.getMessage(),ex);
             }
             try {
                 final CoordinateReferenceSystem realElevation = CommonCRS.Vertical.ELLIPSOIDAL.crs();
                 final MathTransform trs = CRS.findOperation(realElevation, verticalDim, null).getMathTransform();
                 final double[] coords = new double[2];
                 coords[0] = (elevation[0] != null) ? elevation[0] : Double.NEGATIVE_INFINITY;
                 coords[1] = (elevation[1] != null) ? elevation[1] : Double.POSITIVE_INFINITY;
                 trs.transform(coords, 0, coords, 0, 2);
                 env.setRange(indexes[2],coords[0],coords[1]);
             } catch (FactoryException ex) {
                 throw new TransformException(ex.getMessage(),ex);
             }
         } else if (temporalDim != null) {
             try {
                 crs = CRS.compound(crs2D,  temporalDim);
             } catch (FactoryException ex) {
                 throw new TransformException(ex.getMessage(), ex);      // TODO: not appropriate.
             }
             env = new GeneralEnvelope(crs);
             int[] indexes = findDimensionIndexes(crs);
             env.setRange(indexes[0], bounds.getMinX(), bounds.getMaxX());
             env.setRange(indexes[1], bounds.getMinY(), bounds.getMaxY());
             try {
                 final CoordinateReferenceSystem realTemporal = CommonCRS.Temporal.JAVA.crs();
                 final MathTransform trs = CRS.findOperation(realTemporal, temporalDim, null).getMathTransform();
                 final double[] coords = new double[2];
                 coords[0] = (temporal[0] != null) ? temporal[0].getTime() : Double.NEGATIVE_INFINITY;
                 coords[1] = (temporal[1] != null) ? temporal[1].getTime() : Double.POSITIVE_INFINITY;
                 trs.transform(coords, 0, coords, 0, 2);
                 env.setRange(indexes[3],coords[0],coords[1]);
             } catch (FactoryException ex) {
                 throw new TransformException(ex.getMessage(),ex);
             }
         } else if (verticalDim != null) {
             try {
                 crs = CRS.compound(crs2D, verticalDim);
             } catch (FactoryException ex) {
                 throw new TransformException(ex.getMessage(), ex);      // TODO: not appropriate.
             }
             env = new GeneralEnvelope(crs);
             int[] indexes = findDimensionIndexes(crs);
             env.setRange(indexes[0], bounds.getMinX(), bounds.getMaxX());
             env.setRange(indexes[1], bounds.getMinY(), bounds.getMaxY());
             try {
                 final CoordinateReferenceSystem realElevation = CommonCRS.Vertical.ELLIPSOIDAL.crs();
                 final MathTransform trs = CRS.findOperation(realElevation, verticalDim, null).getMathTransform();
                 final double[] coords = new double[2];
                 coords[0] = (elevation[0] != null) ? elevation[0] : Double.NEGATIVE_INFINITY;
                 coords[1] = (elevation[1] != null) ? elevation[1] : Double.POSITIVE_INFINITY;
                 trs.transform(coords, 0, coords, 0, 2);
                 env.setRange(indexes[2],coords[0],coords[1]);
             } catch (FactoryException ex) {
                 throw new TransformException(ex.getMessage(),ex);
             }
         }else{
             crs = crs2D;
             env = new GeneralEnvelope(crs);
             env.setRange(0, bounds.getMinX(), bounds.getMaxX());
             env.setRange(1, bounds.getMinY(), bounds.getMaxY());
         }
         return env;
     }
convertResolution()
static double [] convertResolution (final Envelope srcEnvelope, final double [] oldResolution, final CoordinateReferenceSystem targetCrs, double... newResolution) throws TransformException static
Convert resolution from old resolution and Envelope::getCoordinateReferenceSystem() source CRS} within srcEnvelope, and store result into destination array newResolution.
Note 1 : newResolution array may be
null
, in this case a new array result will be created, where its length will be equals to targetCRS dimensions number.
Note 2 : the resolution convertion will be compute from CRSUtilities::getCRS2D(org.opengis.referencing.crs.CoordinateReferenceSystem) 2D CRS horizontal part} of source CRS from Envelope and 2D targetCRS horizontal part.
Note 3 : if destination resolution array is not
null
the resolution values about other dimensions than 2D horizontal targetCRS part are unchanged, else (if new resolution array is
null
) the resolution values on other dimensions are setted to
1
.
Note 4 : oldResolution array length may not be mandatory equal to Envelope::getDimension() source Envelope dimension number}. The resolution convertion will be computed on horizontal CRS 2D part.
Parameters
srcEnvelope source envelope in relation with the source resolution.
oldResolution the old resolution which will be convert.
targetCrs destination CoordinateReferenceSystem where the new resolution will be exprimate.
newResolution the result array of the transformed resolution. You may pass the same array than oldResolution if you want to store result in the same array.
Returns
a new resolution array compute from oldResolution exprimate into targetCRS.
Exceptions
TransformException if problem during Envelope transformation into targetCrs.
NullArgumentException if one of these parameter is
null
: srcEnvelope, oldResolution or targetCRS.
MismatchedDimensionException if oldResolution array have length different than 2.
MismatchedDimensionException if newResolution array length and target CRS dimension are differents.
References CRSUtilities.firstHorizontalAxis(), and CRSUtilities.getCRS2D().
{
         ArgumentChecks.ensureNonNull("srcEnvelope",   srcEnvelope);
         ArgumentChecks.ensureNonNull("oldResolution", oldResolution);
         ArgumentChecks.ensureNonNull("targetCRS",     targetCrs);
         //-- initialize destination array if it is null.
         if (newResolution == null || newResolution.length == 0) {
             newResolution = new double[targetCrs.getCoordinateSystem().getDimension()];
             Arrays.fill(newResolution, 1);
         } else {
             if (targetCrs.getCoordinateSystem().getDimension() != newResolution.length)
             throw new MismatchedDimensionException("Destination resolution array length should be equals than target CRS dimension number."
                     + "Destination resolution array length = "+newResolution.length+", CRS dimension number = "+targetCrs.getCoordinateSystem().getDimension());
         }
         final CoordinateReferenceSystem srcCRS = srcEnvelope.getCoordinateReferenceSystem();
         if (oldResolution.length != 2)
             throw new IllegalArgumentException("Resolution array length should be equals to 2. Founded array length : " + oldResolution.length);
         final int targetMinOrdi = CRSUtilities.firstHorizontalAxis(targetCrs);
         if (Utilities.equalsIgnoreMetadata(srcCRS, targetCrs)) {
             assert targetMinOrdi + oldResolution.length <= newResolution.length : "First horizontal index from target CRS + old resolution array length " +
                     "should be lesser than new resolution array length.";
             System.arraycopy(oldResolution, 0, newResolution, targetMinOrdi, oldResolution.length);
         } else {
             final int srcMinOrdi = CRSUtilities.firstHorizontalAxis(srcCRS);
             final CoordinateReferenceSystem srcCRS2D    = CRSUtilities.getCRS2D(srcCRS);
             final CoordinateReferenceSystem targetCRS2D = CRSUtilities.getCRS2D(targetCrs);
             final DirectPosition center = new GeneralDirectPosition(srcCRS2D);
             center.setOrdinate(0, srcEnvelope.getMedian(srcMinOrdi));
             center.setOrdinate(1, srcEnvelope.getMedian(srcMinOrdi+1));
             try {
                 final MathTransform trs = CRS.findOperation(srcCRS2D, targetCRS2D, null).getMathTransform();
                 final Matrix derivative = trs.derivative(center);
                 double[] res2d = MatrixSIS.castOrCopy(derivative).multiply(oldResolution);
                 //array sizes may differ, copy only the 2D resolution.
                 newResolution[0] = res2d[0];
                 newResolution[1] = res2d[1];
             } catch (FactoryException | ProjectionException ex) {
                 //uncorrect fallback solution, better then nothing
                 //-- grid envelope
                 final int displayWidth  = (int) StrictMath.ceil(srcEnvelope.getSpan(srcMinOrdi)     / oldResolution[0]);
                 final int displayHeight = (int) StrictMath.ceil(srcEnvelope.getSpan(srcMinOrdi + 1) / oldResolution[1]);
                 final GeneralEnvelope srcEnvelope2D = new GeneralEnvelope(srcCRS2D);
                 srcEnvelope2D.setRange(0, srcEnvelope.getMinimum(srcMinOrdi),     srcEnvelope.getMaximum(srcMinOrdi));
                 srcEnvelope2D.setRange(1, srcEnvelope.getMinimum(srcMinOrdi + 1), srcEnvelope.getMaximum(srcMinOrdi + 1));
                 //-- target image into target CRS 2D
                 final Envelope targetEnvelope2D = Envelopes.transform(srcEnvelope2D, targetCRS2D);
                 newResolution[targetMinOrdi]     = targetEnvelope2D.getSpan(0) / displayWidth;
                 newResolution[targetMinOrdi + 1] = targetEnvelope2D.getSpan(1) / displayHeight;
             }
         }
         //at current step, resolution may have negative values du to derivate.
         for(int i=0; i<newResolution.length; i++) {
             newResolution[i] = abs(newResolution[i]);
             if (Double.isNaN(newResolution[i]) && (i == targetMinOrdi || i == targetMinOrdi+1)) {
                 //if a value is NaN, peek resolution of the other horizontal axis
                 newResolution[i] = newResolution[i == targetMinOrdi ? i+1 : i-1];
             }
             if (Double.isNaN(newResolution[i])) {
                 //if a value is still NaN, use original resolution
                 newResolution[i] = oldResolution[i];
             }
         }
         return newResolution;
     }
findDimensionIndexes()
static int [] findDimensionIndexes (CoordinateReferenceSystem crs) static private
Return array of dimensions indexes with [0, 1] : geographic [2] : elevation [3] : temporal.
Deprecated:
dimension not found have their index left to 0, which is probably not appropriate (they will be taken as longitude or easting).
Referenced by ReferencingUtilities.combine().
{
         final CoordinateSystem cs = crs.getCoordinateSystem();
         assert (cs.getDimension() <= 4);
         int[] indexes = new int[4];
         int d = 0;
         for (SingleCRS crs2 : getSingleComponents(crs)) {
             final int dim = crs2.getCoordinateSystem().getDimension();
             if (crs2 instanceof GeographicCRS || crs2 instanceof ProjectedCRS) {
                 for (int i=0; i<dim; i++) {      // May be 2 or 3 dimensional.
                     indexes[i] = d++;
                 }
             } else if (crs2 instanceof VerticalCRS) {
                 assert dim == 1;
                 indexes[2] = d++;
             } else if (crs2 instanceof TemporalCRS) {
                 assert dim == 1;
                 indexes[3] = d++;
             } else {
                 throw new IllegalArgumentException("Unsupported CRS: " + crs2);
             }
         }
         return indexes;
     }
findGeographicBBox()
static Optional<? extends GeographicBoundingBox> findGeographicBBox (final Resource r) throws DataStoreException static
Try to extract a geographic bounding box from given resource.
: We'll try to acquire metadata from the resource, and making an union of all available geographic boxes found in it.
Parameters
r The resource to analyze.
Returns
A geographic envelope if we've found any in the resource metadata. Nothing otherwise.
Exceptions
DataStoreException If accessing the resource metadata failed.
{
         return r.getMetadata().getIdentificationInfo().stream()
                 .flatMap(i -> i.getExtents().stream())
                 .map(Extents::getGeographicBoundingBox)
                 .map(DefaultGeographicBoundingBox::new )
                 .reduce((b1, b2) -> {b1.add(b2); return b1;});
     }
findWrapAround()
static DirectPosition [] findWrapAround (CoordinateReferenceSystem crs) throws TransformException static
Test if the Coordinate Reference System has a wrap around axis.
This method checks if the CRS is geographic or projected with a compatible transformation (only linear or Mercator).
Example, for EPSG:4326 the result is : [0] = Position(0,-180) [1] = Position(0,+180)
Example, for EPSG:3395 (mercator) the result is : [0] = Position(-2M,0) [1] = Position(+2M,0)
Example, for EPSG:27582 (conic) the result is : null since there is no possible wrap around.
Parameters
crs to test
Returns
DirectPosition[] size 2 : [0] : start wrap around position in given CRS. [1] : end wrap around position in given CRS. null if crs does not have a wrap around axis
References ReferencingUtilities.isWrapAroundCompatible().
{
         if(crs instanceof GeographicCRS){
             final EllipsoidalCS cs = ((GeographicCRS)crs).getCoordinateSystem();
             for(int i=0,n=cs.getDimension();i<n;i++){
                 final CoordinateSystemAxis axis = cs.getAxis(i);
                 if(RangeMeaning.WRAPAROUND.equals(axis.getRangeMeaning())){
                     final DirectPosition start = new GeneralDirectPosition(crs);
                     start.setOrdinate(i, axis.getMinimumValue());
                     final DirectPosition end = new DirectPosition2D(crs);
                     end.setOrdinate(i, axis.getMaximumValue());
                     return new DirectPosition[]{start,end};
                 }
             }
         }else if(crs instanceof ProjectedCRS){
             final ProjectedCRS projectedCRS = (ProjectedCRS) crs;
             final MathTransform trs = projectedCRS.getConversionFromBase().getMathTransform();
             //test if the transform can contain a wrap axis
             if(isWrapAroundCompatible(trs)){
                 final CoordinateReferenceSystem baseCrs = projectedCRS.getBaseCRS();
                 final DirectPosition[] info = findWrapAround(baseCrs);
                 info[0] = trs.transform(info[0], null);
                 info[1] = trs.transform(info[1], null);
                 return info;
             }
         }
         return null;
     }
indexedDecompose()
static Map<Integer, CoordinateReferenceSystem> indexedDecompose (CoordinateReferenceSystem crs) static
Decompose CRS and return each sub-crs along with their dimension index.
Returns
Map of index and sub-crs
{
         final TreeMap<Integer, CoordinateReferenceSystem> result = new TreeMap<>();
         int index = 0;
         CoordinateReferenceSystem crsPart;
         CoordinateSystem csPart;
         final List<SingleCRS> crsParts = getSingleComponents(crs);
         for (int j = 0; j < crsParts.size(); j++) {
             crsPart = crsParts.get(j);
             csPart = crsPart.getCoordinateSystem();
             result.put(index, crsPart);
             index += csPart.getDimension();
         }
         return result;
     }
intersectEnvelopes()
static GeneralEnvelope intersectEnvelopes (final Envelope layerEnvelope, final Envelope filterEnvelope) throws TransformException static
Build an envelope which is the intersection between both of the parameters.
The CRS of the two input envelopes can be different, with different number of dimension.
Parameters
layerEnvelope The envelope of the source layer. Result envelope will keep this object CRS.
filterEnvelope the envelope used as filter.
Returns
An envelope which is the found intersection between the two inputs. The CRS of the result will be the same as the first input.
Exceptions
TransformException if an incompatibility between CRSs is found.
References CRS.getCompoundCRS().
{
         ArgumentChecks.ensureNonNull("source envelope", layerEnvelope);
         GeneralEnvelope resultEnvelope = new GeneralEnvelope(layerEnvelope);
         if (filterEnvelope == null) {
             return resultEnvelope;
         }
         final CoordinateReferenceSystem inputCRS = layerEnvelope.getCoordinateReferenceSystem();
         final CoordinateReferenceSystem filterCRS = filterEnvelope.getCoordinateReferenceSystem();
         if (resultEnvelope.getDimension() <= filterEnvelope.getDimension()) {
             resultEnvelope.intersect(Envelopes.transform(filterEnvelope, inputCRS));
         } else {
             /* If source CRS got more dimensions than the one given as filter,
              * we need to isolate each component of the filter to insert them
              * into an envelope of the source CRS.
              */
             if (inputCRS instanceof CompoundCRS) {
                 final ArrayList<SingleCRS> toFind = new ArrayList<>(3);
                 final TemporalCRS inputTemporal = getTemporalComponent(inputCRS);
                 final TemporalCRS filterTemporal = getTemporalComponent(filterCRS);
                 final SingleCRS inputHorizontal = getHorizontalComponent(inputCRS);
                 final SingleCRS filterHorizontal = getHorizontalComponent(filterCRS);
                 final VerticalCRS inputVertical = getVerticalComponent(inputCRS, true);
                 final VerticalCRS filterVertical = getVerticalComponent(filterCRS, true);
                 if (inputHorizontal != null && filterHorizontal != null) {
                     toFind.add(inputHorizontal);
                 }
                 if (inputTemporal != null && filterTemporal != null) {
                     toFind.add(inputTemporal);
                 }
                 if (inputVertical != null && filterVertical != null) {
                     toFind.add(inputVertical);
                 }
                 /* build a sub-CRS, containing all the input components which can
                  * be compared with current filter.
                  */
                 final CoordinateReferenceSystem tmpCRS;
                 if (toFind.size() <= 0) {
                     throw new TransformException("An error occured while applying filter : input layer CRS and filter CRS aren't compatible.");
                 } else if (toFind.size() == 1) {
                     tmpCRS = toFind.get(0);
                 } else {
                     tmpCRS = org.geotoolkit.referencing.CRS.getCompoundCRS((CompoundCRS) inputCRS, toFind.toArray(new SingleCRS[toFind.size()]));
                 }
                 final GeneralEnvelope tmpFilter = new GeneralEnvelope(Envelopes.transform(filterEnvelope, tmpCRS));
                 final GeneralEnvelope tmpResult = new GeneralEnvelope(Envelopes.transform(resultEnvelope, tmpCRS));
                 tmpResult.intersect(tmpFilter);
                 /* Re-injection pass. For each component crs of the above computed
                  * intersection, we try to find the same in input envelope, to
                  * replace its values.
                  */
                 int tmpOffset = 0;
                 for (CoordinateReferenceSystem tmpSubCRS : toFind) {
                     final int srcOffset = org.apache.sis.internal.referencing.AxisDirections.indexOfColinear(
                             inputCRS.getCoordinateSystem(), tmpSubCRS.getCoordinateSystem());
                     if(srcOffset>=0){
                         int tmpDimNumber = tmpSubCRS.getCoordinateSystem().getDimension();
                         final GeneralEnvelope subTmp = tmpResult.subEnvelope(tmpOffset, tmpOffset + tmpDimNumber);
                         resultEnvelope.subEnvelope(srcOffset, srcOffset+tmpResult.getDimension()).setEnvelope(subTmp);
                         break;
                     }
                 }
             } else {
                 throw new TransformException("An error occured while applying filter : input layer CRS and filter CRS aren't compatible.");
             }
         }
         return resultEnvelope;
     }
intersects()
static boolean intersects (Envelope env1, Envelope env2) static
Test if two envelopes intersects.
This method will transform envelopes if needed.
Returns
true if envelopes intersect
{
         final CoordinateReferenceSystem crs1 = env1.getCoordinateReferenceSystem();
         final CoordinateReferenceSystem crs2 = env2.getCoordinateReferenceSystem();
         //try to find a compatible crs
         final CoordinateReferenceSystem crs = CRS.suggestCommonTarget(null, crs1,crs2);
         if (crs!=null) {
             try {
                 final Envelope penv1 = Envelopes.transform(env1, crs);
                 final Envelope penv2 = Envelopes.transform(env2, crs);
                 return GeneralEnvelope.castOrCopy(penv1).intersects(penv2);
             } catch(Exception ex) {/*do nothing*/}
         }
         //try both way intersection
         cas1:
         try {
             final Envelope penv2 = Envelopes.transform(env2, crs1);
             if (GeneralEnvelope.castOrCopy(penv2).isEmpty()) break cas1;
             return GeneralEnvelope.castOrCopy(env1).intersects(penv2);
         } catch(Exception ex) {/*do nothing*/}
         cas2:
         try {
             final Envelope penv1 = Envelopes.transform(env1, crs2);
             if (GeneralEnvelope.castOrCopy(penv1).isEmpty()) break cas2;
             return GeneralEnvelope.castOrCopy(penv1).intersects(env2);
         } catch(Exception ex) {/*do nothing*/}
         /*
          * TODO: an exception means that a value exist, but can not be computed because the calculation
          *       do not converge. The value that we have not been able to calculate could be inside the
          *       other envelope. Concequently returning 'false' is not okay - we should propagate the
          *       exception instead.
          */
         return false;
     }
isWrapAroundCompatible()
static boolean isWrapAroundCompatible (MathTransform trs) static private
Referenced by ReferencingUtilities.findWrapAround().
{
         for (final MathTransform step : MathTransforms.getSteps(trs)) {
             if (!(step instanceof LinearTransform || step instanceof Mercator)) {
                 return false;
             }
         }
         return true;
     }
lookupIdentifier()
static String lookupIdentifier (final IdentifiedObject object, final boolean fullScan) throws FactoryException static
Looks up an Identifier identifier}, such as.
"EPSG:4326"
, of the specified object. This method searches in registered factories for an object ComparisonMode::APPROXIMATE approximately equals} to the specified object. If such an object is found, then its first identifier is returned. Otherwise this method returns
null
.
Note that this method checks the identifier validity. If the given object declares explicitly an identifier, then this method will instantiate an object from the authority factory using that identifier and compare it with the given object. If the comparison fails, then this method returns
null
. Consequently this method may returns
null
even if the given object declares explicitly its identifier. If the declared identifier is wanted unconditionally, use getIdentifier(IdentifiedObject) instead.
Parameters
object The object (usually a CoordinateReferenceSystem coordinate reference system}) whose identifier is to be found, or
null
.
fullScan If
true
, an exhaustive full scan against all registered objects should be performed (may be slow). Otherwise only a fast lookup based on embedded identifiers and names will be performed.
Returns
The identifier, or
null
if none was found or if the given object was null.
Exceptions
FactoryException If an unexpected failure occurred during the search.
See also
AbstractAuthorityFactory::getIdentifiedObjectFinder(Class)
IdentifiedObjectFinder::findIdentifier(IdentifiedObject)
Referenced by ReferencingUtilities.setLongitudeFirst().
{
         if (object == null) {
             return null;
         }
         final IdentifiedObjectFinder f = org.apache.sis.referencing.IdentifiedObjects.newFinder(null);
         f.setSearchDomain(fullScan ? IdentifiedObjectFinder.Domain.ALL_DATASET : IdentifiedObjectFinder.Domain.DECLARATION);
         for (final IdentifiedObject o : f.find(object)) {
             final String i = org.apache.sis.referencing.IdentifiedObjects.toString(
                     org.apache.sis.referencing.IdentifiedObjects.getIdentifier(o, null));
             if (i != null) return i;
         }
         return null;
     }
name()
static Map<String,String> name (final String name) static private
{
         return Collections.singletonMap(IdentifiedObject.NAME_KEY, name);
     }
orthodromicDistance()
static double orthodromicDistance (final double radius, double λ1, double φ1, double λ2, double φ2) static
Returns the orthodromic distance between two geographic coordinates.
The orthodromic distance is the shortest distance between two points on a sphere's surface. The orthodromic path is always on a great circle.
Parameters
λ1 longitude of first point (in decimal degrees).
φ1 latitude of first point (in decimal degrees).
λ2 longitude of second point (in decimal degrees).
φ2 latitude of second point (in decimal degrees).
Returns
the orthodromic distance (in the units of this ellipsoid's axis).
{
         φ1 = toRadians(φ1);
         φ2 = toRadians(φ2);
         final double dx = toRadians(abs(λ2-λ1) % 360);
         double rho = sin(φ1)*sin(φ2) + cos(φ1)*cos(φ2)*cos(dx);
         assert abs(rho) < 1.0000001 : rho;
         if (rho > +1) rho = +1;                         // Catch rounding error.
         if (rho < -1) rho = -1;                         // Catch rounding error.
         return acos(rho) * radius;
     }
readTransform()
static AffineTransform readTransform (Path f) throws IOException, NumberFormatException static
Read TFW file and return the content affine transform.
References IOUtilities.toString().
{
         final String str = IOUtilities.toString(f);
         final String[] parts = str.split("\n");
         final double[] vals = new double[6];
         int idx=0;
         for(String line : parts){
             line = line.trim();
             if(line.isEmpty() || line.startsWith("#") || line.startsWith("//")) continue;
             vals[idx] = Double.parseDouble(line);
             idx++;
         }
         return new AffineTransform(vals);
     }
setLongitudeFirst() [1/2]
static Envelope setLongitudeFirst (final Envelope env) throws TransformException, FactoryException static
Try to change a coordinate reference system axis order to place the east axis first.
Reproject the envelope.
Referenced by ReferencingUtilities.setLongitudeFirst().
{
         if(env == null) return env;
         final CoordinateReferenceSystem crs = env.getCoordinateReferenceSystem();
         final CoordinateReferenceSystem flipped = setLongitudeFirst(crs);
         return Envelopes.transform(env, flipped);
     }
setLongitudeFirst() [2/2]
static CoordinateReferenceSystem setLongitudeFirst (final CoordinateReferenceSystem crs) throws FactoryException static
Try to change a coordinate reference system axis order to place the east axis first.
Deprecated:
Use org.apache.sis.referencing.crs.AbstractCRS#forConvention instead.
References ReferencingUtilities.lookupIdentifier(), and ReferencingUtilities.setLongitudeFirst().
{
         if (crs instanceof SingleCRS) {
             final SingleCRS singlecrs = (SingleCRS) crs;
             final CoordinateSystem cs = singlecrs.getCoordinateSystem();
             final int dimension = cs.getDimension();
             if (dimension <= 1) {
                 //can't change anything if it's only one axis
                 return crs;
             }
             //find the east axis
             int eastAxis = -1;
             for (int i=0; i<dimension; i++) {
                 final AxisDirection firstAxis = cs.getAxis(i).getDirection();
                 if (firstAxis == AxisDirection.EAST || firstAxis == AxisDirection.WEST) {
                     eastAxis = i;
                     break;
                 }
             }
             if (eastAxis == 0) {
                 //the crs is already in the correct order or does not have any east axis
                 return singlecrs;
             }
             //try to change the crs axis
             final String id = lookupIdentifier(singlecrs, true);
             if (id != null) {
                 return AbstractCRS.castOrCopy(CRS.forCode(id)).forConvention(AxesConvention.RIGHT_HANDED);
             } else {
                 //TODO how to manage custom crs ? might be a derivedCRS.
                 throw new FactoryException("Failed to create flipped axis for crs : " + singlecrs);
             }
         } else if (crs instanceof CompoundCRS) {
             final CompoundCRS compoundcrs = (CompoundCRS) crs;
             final List<CoordinateReferenceSystem> components = compoundcrs.getComponents();
             final int size = components.size();
             final CoordinateReferenceSystem[] parts = new CoordinateReferenceSystem[size];
             //only recreate the crs if one element changed.
             boolean changed = false;
             for (int i=0; i<size; i++) {
                 final CoordinateReferenceSystem orig = components.get(i);
                 parts[i] = setLongitudeFirst(orig);
                 if (!parts[i].equals(orig)) changed = true;
             }
             if (changed) {
                 return CRS.compound(parts);
             } else {
                 return crs;
             }
         }
         return crs;
     }
toAffine()
static AffineTransform toAffine (final Dimension rect, final Envelope env) static
Create an affine transform object where (0,0) in the dimension match the top left corner of the envelope.
This method assumes that the Y axis of the rectangle is going down. This returns the display to objective transform (rect to env).
{
         final double minx = env.getMinimum(0);
         final double maxy = env.getMaximum(1);
         final double scaleX = env.getSpan(0)/rect.width;
         final double scaleY = - env.getSpan(1)/rect.height;
         return new AffineTransform(scaleX, 0, 0, scaleY, minx, maxy);
     }
toTransform() [1/2]
static MathTransform toTransform (final MathTransform base, double ... [] values) static
Deprecated:
replaced by toTransform(int, org.opengis.referencing.operation.MathTransform, java.util.Map, int)
References LinearInterpolator1D.create().
{
         MathTransform result = MathTransforms.passThrough(0, base, values.length);
         final int baseDim = base.getSourceDimensions();
         for(int i=0; i<values.length; i++){
             final double[] array = values[i];
             final MathTransform1D axistrs;
             if(array.length == 0){
                 axistrs = (MathTransform1D) MathTransforms.linear(1, 0);
             }else if(array.length == 1){
                 axistrs = (MathTransform1D) MathTransforms.linear(1, array[0]);
             }else{
                 axistrs = LinearInterpolator1D.create(array);
             }
             final MathTransform mask = MathTransforms.passThrough(baseDim+i, axistrs, values.length-i-1);
             result = MathTransforms.concatenate(result, mask);
         }
         return result;
     }
toTransform() [2/2]
static MathTransform toTransform (final int firstBaseOrdinate, final MathTransform subTransform, final Map< Integer, double[]> axisValues, final int expectedTargetDimension) static
Returns a PassThroughTransform with expectedTargetDimension number, from subtransform at dimension index firstBaseOrdinate and with axisValues infomation on each other dimensions.
Parameters
firstBaseOrdinate the first minimum ordinate of subtransform into the expected target dimension.
subTransform the sub transformation which will be wrapped by other mathematical functions.
axisValues the list of mathmatical function for each other dimensions than already present subtransform dimensions.
expectedTargetDimension the expected target PassThroughTransform dimension.
Returns
expected PassThroughTransform, created from given parameters.
See also
checkMTToTransform(int, org.opengis.referencing.operation.MathTransform, java.util.Map, int)
References ReferencingUtilities.checkMTToTransform(), and LinearInterpolator1D.create().
{
         checkMTToTransform(firstBaseOrdinate, subTransform, axisValues, expectedTargetDimension);
         MathTransform result = MathTransforms.passThrough(firstBaseOrdinate, subTransform, expectedTargetDimension - subTransform.getTargetDimensions() - firstBaseOrdinate);
         for (Integer dim : axisValues.keySet()) {
             final double[] currentAxisValues = axisValues.get(dim);
             final MathTransform1D axistrs;
             if(currentAxisValues.length <= 1) {
                 axistrs = (MathTransform1D) MathTransforms.linear(1, (currentAxisValues.length == 0)
                                                                      ? 0 : currentAxisValues[0]);
             } else {
                 axistrs = LinearInterpolator1D.create(currentAxisValues);
             }
             final MathTransform mask = MathTransforms.passThrough(dim, axistrs, expectedTargetDimension - dim - 1);
             result                   = MathTransforms.concatenate(result, mask);
         }
         return result;
     }
transform()
static Envelope transform (Envelope env, CoordinateReferenceSystem targetCRS) throws TransformException static
Transform the given envelope to the given crs.
Unlike Envelopes.transform this method handle growing number of dimensions by filling other axes with default values.
Parameters
env source Envelope
targetCRS target CoordinateReferenceSystem
Returns
transformed envelope
{
         try {
             return Envelopes.transform(env, targetCRS);
         } catch (TransformException ex) {
             //we tried...
         }
         //lazy transform
         final CoordinateReferenceSystem sourceCRS = env.getCoordinateReferenceSystem();
         final GeneralEnvelope result = new GeneralEnvelope(targetCRS);
         //decompose crs
         final List<SingleCRS> sourceParts = getSingleComponents(sourceCRS);
         final List<SingleCRS> targetParts = getSingleComponents(targetCRS);
         int sourceAxeIndex=0;
         sourceLoop:
         for(CoordinateReferenceSystem sourcePart : sourceParts){
             final int sourcePartDimension = sourcePart.getCoordinateSystem().getDimension();
             int targetAxeIndex=0;
             targetLoop:
             for(CoordinateReferenceSystem targetPart : targetParts){
                 final int targetPartDimension = targetPart.getCoordinateSystem().getDimension();
                 //try conversion
                 try {
                     final MathTransform trs = CRS.findOperation(sourcePart, targetPart, null).getMathTransform();
                     //we could transform by using two coordinate, but envelope conversion allows to handle
                     //crs singularities more efficiently
                     final GeneralEnvelope partSource = new GeneralEnvelope(sourcePart);
                     for(int i=0;i<sourcePartDimension;i++){
                         partSource.setRange(i, env.getMinimum(sourceAxeIndex+i), env.getMaximum(sourceAxeIndex+i));
                     }
                     final Envelope partResult = Envelopes.transform(trs, partSource);
                     for(int i=0;i<targetPartDimension;i++){
                         result.setRange(targetAxeIndex+i, partResult.getMinimum(i), partResult.getMaximum(i));
                     }
                     break targetLoop;
                 } catch (FactoryException ex) {
                     //we tried...
                 }
                 targetAxeIndex += targetPartDimension;
             }
             sourceAxeIndex += sourcePartDimension;
         }
         return result;
     }
transform2DCRS()
static Envelope transform2DCRS (final Envelope env, final CoordinateReferenceSystem crs2D) throws TransformException static
Transform the CRS 2D component of this envelope.
This preserve temporal/elevation or other axis.
References ReferencingUtilities.change2DComponent().
{
         final CoordinateReferenceSystem originalCRS = env.getCoordinateReferenceSystem();
         final CoordinateReferenceSystem targetCRS = change2DComponent(originalCRS, crs2D);
         return Envelopes.transform(env, targetCRS);
     }
transposeEnvelope()
static GeneralEnvelope transposeEnvelope (final GeneralEnvelope source, GeneralEnvelope destination) static
For each axis value of the source envelope, we'll set corresponding one in destination envelope, if we find a valid transform.
For all the components of the destination that can't be filled, they're left as is.
Parameters
source The envelope to take values from.
destination The envelope to set values into. Will be modified.
Returns
The destination envelope that have been modified.
{
         ArgumentChecks.ensureNonNull("source envelope", source);
         ArgumentChecks.ensureNonNull("destination envelope", destination);
         final CoordinateReferenceSystem sourceCRS = source.getCoordinateReferenceSystem();
         final CoordinateReferenceSystem destCRS = destination.getCoordinateReferenceSystem();
         // If they're the same, we can return the source envelope.
         if (Utilities.equalsApproximately(sourceCRS, destCRS)) {
             destination = new GeneralEnvelope(source);
         }
         // Decompose source and destination CRSs
         final List<SingleCRS> sourceComponents = getSingleComponents(sourceCRS);
         final List<SingleCRS> destComponents = getSingleComponents(destCRS);
         // Store sub-CRSs of destination which have already been used for range transfer.
         final List<CoordinateReferenceSystem> usedCRS = new ArrayList<>(destComponents.size());
         boolean searchHorizontal;
         boolean searchTemporal;
         boolean searchVertical;
         boolean compatible;
         int srcLowerAxis = 0;
         int srcAxisCount = 0;
         int destLowerAxis;
         int destAxisCount;
         browseSource:
         for (int srcCptCounter = 0; srcCptCounter < sourceComponents.size(); srcCptCounter++) {
             // Prepare iteration.
             searchHorizontal = false;
             searchVertical = false;
             searchTemporal = false;
             srcLowerAxis += srcAxisCount;
             destLowerAxis = 0;
             destAxisCount = 0;
             final CoordinateReferenceSystem srcCurrent = sourceComponents.get(srcCptCounter);
             srcAxisCount = srcCurrent.getCoordinateSystem().getDimension();
              // First, we must browse destination to check if we can find an equal CRS.
             for (int destCptCounter = 0; destCptCounter < destComponents.size(); destCptCounter++) {
                 destLowerAxis += destAxisCount;
                 final CoordinateReferenceSystem destCurrent = destComponents.get(destCptCounter);
                 destAxisCount = destCurrent.getCoordinateSystem().getDimension();
                 // We already bind a dimension of the source envelope for this CRS, just keep going.
                 if (usedCRS.contains(destCurrent)) {
                     continue;
                 }
                 if (Utilities.equalsApproximately(srcCurrent, destCurrent)) {
                     final GeneralEnvelope srcSubEnvelope = source.subEnvelope(srcLowerAxis, srcLowerAxis + srcAxisCount);
                     destination.subEnvelope(destLowerAxis, destLowerAxis+ srcSubEnvelope.getDimension()).setEnvelope(srcSubEnvelope);
                     usedCRS.add(destCurrent);
                     continue browseSource;
                 }
             }
             destLowerAxis = 0;
             destAxisCount = 0;
             /*
              * If equality failed, we'll try to get CRS whose meaning is
              * compatible. To do so, we try to identify the CRS type (horizontal,
              * vertical or temporal). If it's a fail, our last chance is to
              * compare both CRS axis.
              */
             if (getHorizontalComponent(srcCurrent) != null) {
                 searchHorizontal = true;
             } else if (getVerticalComponent(srcCurrent, true) != null) {
                 searchVertical = true;
             } else if (getTemporalComponent(srcCurrent) != null) {
                 searchTemporal = true;
             }
             for (int destCptCounter = 0; destCptCounter < destComponents.size(); destCptCounter++) {
                 compatible = false;
                 destLowerAxis += destAxisCount;
                 final CoordinateReferenceSystem destCurrent = destComponents.get(destCptCounter);
                 destAxisCount = destCurrent.getCoordinateSystem().getDimension();
                 // We already bind a dimension of the source envelope for this CRS, just keep going.
                 if (usedCRS.contains(destCurrent)) {
                     continue;
                 }
                 if (searchHorizontal) {
                     if (getHorizontalComponent(destCurrent) != null) {
                         compatible = true;
                     }
                 } else if (searchVertical) {
                     if (getVerticalComponent(destCurrent, true) != null) {
                         compatible = true;
                     }
                 } else if (searchTemporal) {
                     if (getTemporalComponent(destCurrent) != null) {
                         compatible = true;
                     }
                 } else {
                     // Check both CRS axis.
                     final CoordinateSystem sourceCS = srcCurrent.getCoordinateSystem();
                     final CoordinateSystem destCS = destCurrent.getCoordinateSystem();
                     if (sourceCS.getDimension() == destCS.getDimension()) {
                         boolean sameAxis = true;
                         for (int axisCount = 0; axisCount < sourceCS.getDimension(); axisCount++) {
                             if (AxisDirections.indexOfColinear(destCS, sourceCS.getAxis(axisCount).getDirection()) < 0) {
                                 sameAxis = false;
                                 break;
                             }
                         }
                         compatible = sameAxis;
                     }
                 }
                 // We found matching CRS, Now we can transfer coordinates.
                 if (compatible) {
                     final GeneralEnvelope srcSubEnvelope = source.subEnvelope(srcLowerAxis, srcLowerAxis + srcAxisCount);
                     srcSubEnvelope.setCoordinateReferenceSystem(srcCurrent);
                     try {
                         final Envelope tmp = Envelopes.transform(srcSubEnvelope, destCurrent);
                         destination.subEnvelope(destLowerAxis, destLowerAxis + tmp.getDimension()).setEnvelope(tmp);
                     } catch (TransformException e) {
                         // If we can't transform it, we just have to go to the next iteration.
                         continue;
                     }
                     usedCRS.add(destCurrent);
                     break;
                 }
             }
         }
         return destination;
     }
wrapNormalize()
static Envelope wrapNormalize (Envelope env, DirectPosition [] warp) static
{
         if (warp == null) return env;
         //TODO we assume the warp is on a along an axis of the coordinate system.
         final DirectPosition p0 = warp[0];
         final DirectPosition p1 = warp[1];
         for (int i = 0, n = p0.getDimension(); i < n; i++) {
             final double minimum = p0.getOrdinate(i);
             final double maximum = p1.getOrdinate(i);
             if(minimum == maximum){
                 //not the wrap axis
                 continue;
             }
             final double csSpan = maximum-minimum;
             double o1 = env.getMinimum(i);
             double o2 = env.getMaximum(i);
             final GeneralEnvelope res = new GeneralEnvelope(env);
             if (abs(o2-o1) >= csSpan) {
                 /*
                  * If the range exceed the CS span, then we have to replace it by the
                  * full span, otherwise the range computed by the "else" block is too
                  * small. The full range will typically be [-180 … 180]°.  However we
                  * make a special case if the two bounds are multiple of the CS span,
                  * typically [0 … 360]°. In this case the [0 … -0]° range matches the
                  * original values and is understood by GeneralEnvelope as a range
                  * spanning all the world.
                  */
                 if (o1 != minimum || o2 != maximum) {
                     if ((o1 % csSpan) == 0 && (o2 % csSpan) == 0) {
                         res.setRange(i, +0.0, -0.0);
                     } else {
                         res.setRange(i, minimum, maximum);
                     }
                 }
             } else {
                 if(o1<minimum || o2>maximum){
                     //envelope cross the anti-méridian
                     res.setRange(i, minimum, maximum);
                 }
 //                o1 = floor((o1 - minimum) / csSpan) * csSpan;
 //                o2 = floor((o2 - minimum) / csSpan) * csSpan;
 //                if (o1 != 0){
 //                    res.setRange(i, res.getMinimum(i)-o1, res.getMaximum(i));
 //                }
 //                if (o2 != 0){
 //                    res.setRange(i, res.getMinimum(i), res.getMaximum(i)-o2);
 //                }
             }
             return res;
         }
         return env;
     }
Member Data Documentation
EARTH_RADIUS
final double EARTH_RADIUS = 6371007 static
Authalic sphere radius in metres.