jena-geo: PropertyEpsgFactory Class Reference
PropertyEpsgFactory Class Reference
Authority factory for CoordinateReferenceSystem Coordinate Reference Systems} beyong the one defined in the EPSG database.
Public Member Functions
PropertyEpsgFactory () throws IOException
Constructs a default authority factory.
PropertyEpsgFactory (final Hints userHints) throws IOException
Constructs an authority factory from the given hints.
PropertyEpsgFactory (final Hints userHints, final String filename, final Citation... authorities) throws IOException
Constructs an authority factory for the given authorities.
Set< String > reportDuplicates (final PrintWriter out) throws FactoryException
Prints a list of codes that duplicate the ones provided by ThreadedEpsgFactory.
Set< String > reportInstantiationFailures (final PrintWriter out) throws FactoryException
Prints a list of CRS that can't be instantiated.
synchronized Citation getAuthority ()
Returns the authority.
synchronized Set< String > getAuthorityCodes (final Class<? extends IdentifiedObject > type) throws FactoryException
Returns the set of authority codes of the given type.
InternationalString getDescriptionText (final String code) throws NoSuchAuthorityCodeException, FactoryException
Gets a description of the object corresponding to a code.
synchronized IdentifiedObject createObject (final String code) throws NoSuchAuthorityCodeException, FactoryException
Returns an arbitrary object from a code.
synchronized CoordinateReferenceSystem createCoordinateReferenceSystem (final String code) throws NoSuchAuthorityCodeException, FactoryException
Returns a coordinate reference system from a code.
Citation getVendor ()
Returns the vendor responsible for creating this factory implementation.
String getBackingStoreDescription () throws FactoryException
Returns a description of the underlying backing store, or.
Static Public Attributes
static final String FILENAME = "epsg.properties"
The default filename to read, which is {}.
static final Logger LOGGER = Logging.getLogger("org.geotoolkit.referencing.factory")
The logger for event related to Geotk factories.
Protected Member Functions
synchronized void load (final Collection< URL > definitionFiles) throws IOException
Loads the WKT strings from the given property files.
synchronized void dispose (final boolean shutdown)
Disposes the resources used by this factory.
String trimAuthority (String code)
Trims the authority scope, if presents.
final NoSuchAuthorityCodeException noSuchAuthorityCode (final Class<?> type, final String code)
Creates an exception for an unknown authority code.
Static Protected Member Functions
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException
Makes sure that an argument is non-null.
Protected Attributes
final NameFactory nameFactory
The name factory to use for creating GenericName.
final ReferencingFactoryContainer factories
The underlying factories used for objects creation.
Package Functions
Citation [] getAuthorities ()
Returns all authority names.
Citation getPrimaryKeyAuthority ()
Returns the authority which is responsible for the maintenance of the primary keys, or.
Comparable<?> getPrimaryKey (Class<? extends IdentifiedObject > type, String code) throws FactoryException
Returns the primary key for the specified authority code.
Static Package Functions
[static initializer]
static FactoryException databaseFailure (final Class<?> type, final String code, final Throwable exception)
Wraps an Exception into a FactoryException.
static Class<?> getWKTClassOf (String element)
Returns the class of the specified WKT element.
static String getWKTNameOf (final Class<?> type)
Returns the WKT name of the specified object type.
Package Attributes
Citation authority
The authority for this factory.
Citation [] authorities
The authorities for this factory, usually as an array of length 1.
final Map< String, String > definitions
The properties object for our properties file.
Detailed Description
Authority factory for CoordinateReferenceSystem Coordinate Reference Systems} beyong the one defined in the EPSG database.
This factory is used as a fallback when a requested code is not found in the EPSG database, or when there is no connection at all to the EPSG database. The CRS are defined as <cite>Well Known Text</cite> in a property file named { FILENAME}. The search path is as below, in that order:
If a value for Hints#CRS_AUTHORITY_EXTRA_DIRECTORY exists in the hints map given at construction time, then that value will be used as the directory where to search for the { FILENAME} file. Reminder: such hint can be Hints::putSystemDefault defined system-wide} for convenience.
The { FILENAME} files found in all
org/geotoolkit/referencing/factory/epsg
directories on the classpath are merged with the values found in previous step, if any. If the same value is defined twice, the value of previous step have precedence.
This factory can also be used to provide custom extensions or overrides to a main EPSG factory:
In order to provide a custom extension, you can create a subclass that invoke the PropertyEpsgFactory(Hints, String, Citation[]) constructor with different constants. You can also subclass PropertyAuthorityFactory directly for getting more control.
In order to make the factory be an override, override the setOrdering(...) method as below:
{ java protected void setOrdering(Organizer organizer) { organizer.before(ThreadedEpsgFactory.class); } }
{
of CRS objects}
This factory doesn't cache any result. Any call to a
createFoo
method will trig a new WKT parsing. For adding caching service, this factory should be wrapped in org.geotoolkit.referencing.factory.CachingAuthorityFactory. Note that this is done automatically when this factory is used through the org.geotoolkit.referencing.CRS static methods.
{
}
If the { FILENAME} file is on the classpath but seems to be ignored, the following actions may provide some useful informations:
Print the list of every registered factories using the code snippet documented in the org.geotoolkit.referencing.factory.FactoryDependencies class and verify that
PropertyEpsgFactory
is presents.
Set the logging level for the
org.geotoolkit
loggers to
CONFIG
. See Java Logging Overview for the standard way, or use the following Geotk convenience method:
{ java Logging.GEOTOOLKIT.forceMonolineConsoleOutput(Level.CONFIG); }
Force the system to ignore any factory other than
PropertyEpsgFactory
:
{ java Hints.putSystemDefault(Hints.CRS_AUTHORITY_FACTORY, PropertyEpsgFactory.class); }
Author
Martin Desruisseaux (IRD)
Jody Garnett (Refractions)
Rueben Schulz (UBC)
Andrea Aime (TOPP)
Version
3.00
Since
2.1
Constructor & Destructor Documentation
PropertyEpsgFactory() [1/3]
PropertyEpsgFactory () throws IOException
Constructs a default authority factory.
Exceptions
IOException If an error occurred while reading the definition files. Note that do exception is thrown if there is no file - in this case the factory is only considered not #availability available}.
{
         this(null);
     }
PropertyEpsgFactory() [2/3]
PropertyEpsgFactory (final Hints userHints) throws IOException
Constructs an authority factory from the given hints.
Hints of special interest are:
Hints#CRS_AUTHORITY_EXTRA_DIRECTORY
Hints#FORCE_LONGITUDE_FIRST_AXIS_ORDER
This constructor recognizes also CRS, CS, DATUM and MATH_TRANSFORM
FACTORY
hints.
Parameters
userHints An optional set of hints, or
null
if none.
Exceptions
IOException If an error occurred while reading the definition files. Note that do exception is thrown if there is no file - in this case the factory is only considered not #availability available}.
References PropertyEpsgFactory.FILENAME.
{
         this(userHints, FILENAME, Citations.EPSG);
     }
PropertyEpsgFactory() [3/3]
PropertyEpsgFactory (final Hints userHints, final String filename, final Citation... authorities) throws IOException
Constructs an authority factory for the given authorities.
This constructor recognizes the same hints than PropertyEpsgFactory(Hints). The
authorities
argument should enumerate all relevant authorities, with Citations::EPSG EPSG} in last position. For example EsriExtension returns { Citations::ESRI ESRI}, Citations::EPSG EPSG}}.
Parameters
userHints An optional set of hints, or
null
if none.
filename The name of the file to look in the Hints#CRS_AUTHORITY_EXTRA_DIRECTORY directory and in every
org/geotoolkit/referencing/factory/espg
directories found on the classpath.
authorities The organizations or parties responsible for definition and maintenance of the database. Should contains at least Citations#EPSG.
Exceptions
IOException If an error occurred while reading the definition files. Note that do exception is thrown if there is no file - in this case the factory is only considered not #availability available}.
Since
3.00
References WKTParsingAuthorityFactory.authorities, and Hints.CRS_AUTHORITY_EXTRA_DIRECTORY.
     {
         super(userHints, Hints.CRS_AUTHORITY_EXTRA_DIRECTORY, PropertyEpsgFactory.class, filename, authorities);
     }
Member Function Documentation
[static initializer]()
[static initializer] () static package inherited
createCoordinateReferenceSystem()
synchronized CoordinateReferenceSystem createCoordinateReferenceSystem (final String code) throws NoSuchAuthorityCodeException, FactoryException inherited
Returns a coordinate reference system from a code.
If the object type is know at compile time, it is recommended to invoke the most precise method instead of this one.
Parameters
code Value allocated by authority.
Exceptions
NoSuchAuthorityCodeException if the specified
code
was not found.
FactoryException if the object creation failed for some other reason.
References WKTParsingAuthorityFactory.getParser(), and WKTParsingAuthorityFactory.getWKT().
Referenced by WKTParsingAuthorityFactory.createObject(), and PropertyEpsgFactory.reportInstantiationFailures().
     {
         final Parser parser = getParser();
         final String wkt = getWKT(CoordinateReferenceSystem.class, code, parser);
         return parser.createFromWKT(wkt);
     }
createObject()
synchronized IdentifiedObject createObject (final String code) throws NoSuchAuthorityCodeException, FactoryException inherited
Returns an arbitrary object from a code.
If the object type is know at compile time, it is recommended to invoke the most precise method instead of this one.
Parameters
code Value allocated by authority.
Exceptions
NoSuchAuthorityCodeException if the specified
code
was not found.
FactoryException if the object creation failed for some other reason.
References WKTParsingAuthorityFactory.createCoordinateReferenceSystem().
     {
         return createCoordinateReferenceSystem(code);
     }
databaseFailure()
static FactoryException databaseFailure (final Class<?> type, final String code, final Throwable exception) static package inherited
Wraps an Exception into a FactoryException.
The given exception is typically a java.sql.SQLException.
Parameters
type The type of the object being created, or
null
if unknown.
code The code of the object being created, or
null
if unknown.
exception The exception that occurred while querying the backing store.
Returns
A factory exception wrapping the given exception.
References Errors.Keys.DatabaseFailure_2, Errors.format(), Vocabulary.format(), and Vocabulary.Keys.Unknown.
Referenced by DirectPostgisFactory.getAuthorityCodes(), DirectPostgisFactory.getAuthorityNames(), DirectPostgisFactory.getBackingStoreDescription(), DirectPostgisFactory.getPrimaryKey(), and WKTParsingAuthorityFactory.getWKT().
{
         String message = exception.getLocalizedMessage();
         if (code != null) {
             String typeName;
             if (type != null) {
                 typeName = type.getSimpleName();
             } else {
                 typeName = Vocabulary.format(Vocabulary.Keys.Unknown);
             }
             message = Errors.format(Errors.Keys.DatabaseFailure_2, typeName, code) + ": " + message;
         }
         return new FactoryException(message, exception);
     }
dispose()
synchronized void dispose (final boolean shutdown) protected inherited
Disposes the resources used by this factory.
Parameters
shutdown
References WKTParsingAuthorityFactory.definitions.
{
         // The call to definitions.clear() is not performed in the super-class because we
         // don't want to touch user-supplied collection. It could be backed by a database.
         definitions.clear();
         super.dispose(shutdown);
     }
ensureNonNull()
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException static protected inherited
Makes sure that an argument is non-null.
This is a convenience method for subclass methods.
Parameters
name Argument name.
object User argument.
Exceptions
InvalidParameterValueException if
object
is null.
References Errors.format(), and Errors.Keys.NullArgument_1.
Referenced by DirectAuthorityFactory.DirectAuthorityFactory(), DirectPostgisFactory.getPrimaryKey(), WKTParsingAuthorityFactory.getWKT(), PropertyAuthorityFactory.load(), and WKTParsingAuthorityFactory.WKTParsingAuthorityFactory().
     {
         if (object == null) {
             throw new InvalidParameterValueException(Errors.format(
                     Errors.Keys.NullArgument_1, name), name, object);
         }
     }
getAuthorities()
Citation [] getAuthorities () package inherited
Returns all authority names.
The default implementation returns the authority given to the constructor. This method must be overridden if the subclass used the constructor without authority list. This method is not allowed to return
null
.
The returned array shall contain the value returned by getPrimaryKeyAuthority()}, if non-null.
Returns
All authorities known to this factory. Do not modify, since this method returns a direct reference to the internal array.
References WKTParsingAuthorityFactory.authorities, Errors.Keys.DisposedFactory, and Errors.format().
Referenced by WKTParsingAuthorityFactory.Parser.complete(), WKTParsingAuthorityFactory.getAuthority(), and WKTParsingAuthorityFactory.trimAuthority().
{
         if (authorities == null) {
             throw new IllegalStateException(Errors.format(Errors.Keys.DisposedFactory));
         }
         return authorities;
     }
getAuthority()
synchronized Citation getAuthority () inherited
Returns the authority.
The default implementation returns the first citation given to the constructor, or a modified version of that citation if many of them were given to the constructor. In the later case, the returned citation will have a set of Citation::getIdentifiers() identifiers} which is the union of identifiers of all citations given to the constructor.
References WKTParsingAuthorityFactory.authority, WKTParsingAuthorityFactory.getAuthorities(), and WKTParsingAuthorityFactory.getPrimaryKeyAuthority().
Referenced by DirectPostgisFactory.getBackingStoreDescription().
{
         if (authority == null) {
             Citation[] authorities = getAuthorities();
             final Citation pkAuthority = getPrimaryKeyAuthority();
             if (pkAuthority != null) {
                 for (int i=0; i<authorities.length; i++) {
                     if (pkAuthority.equals(authorities[i])) {
                         authorities = ArraysExt.remove(authorities, i, 1);
                         break;
                     }
                 }
             }
             switch (authorities.length) {
                 case 0: authority = new SimpleCitation("Unknown"); break;
                 case 1: authority = authorities[0]; break;
                 default: {
                     final DefaultCitation c = new DefaultCitation(authorities[0]);
                     final Collection<Identifier> identifiers = c.getIdentifiers();
                     for (int i=1; i<authorities.length; i++) {
                         identifiers.addAll(authorities[i].getIdentifiers());
                     }
                     c.transitionTo(DefaultCitation.State.FINAL);
                     authority = c;
                     break;
                 }
             }
         }
         return authority;
     }
getAuthorityCodes()
synchronized Set<String> getAuthorityCodes (final Class<? extends IdentifiedObject > type) throws FactoryException inherited
Returns the set of authority codes of the given type.
The
type
argument specifies the base class. For example if this factory is an instance of CRSAuthorityFactory, then:
CoordinateReferenceSystem.class
asks for all authority codes accepted by createGeographicCRS, createProjectedCRS, createVerticalCRS, createTemporalCRS and any other method returning a sub-type of
CoordinateReferenceSystem
.
ProjectedCRS.class
asks only for authority codes accepted by createProjectedCRS.
The default implementation filters the set of codes based on the
"PROJCS"
and
"GEOGCS"
at the start of the WKT strings.
Parameters
type The spatial reference objects type (can be
IdentifiedObject.class
).
Returns
The set of authority codes for spatial reference objects of the given type. If this factory doesn't contains any object of the given type, then this method returns an empty set.
Exceptions
FactoryException if access to the underlying database failed.
References WKTParsingAuthorityFactory.codes.
Referenced by PropertyEpsgFactory.reportDuplicates(), and PropertyEpsgFactory.reportInstantiationFailures().
     {
         if (codes == null) {
             codes = Collections.unmodifiableSet(definitions.keySet());
         }
         if (type == null || type.isAssignableFrom(IdentifiedObject.class)) {
             return codes;
         }
         if (filteredCodes == null) {
             filteredCodes = new HashMap<>();
         }
         Set<String> filtered = filteredCodes.get(type);
         if (filtered == null) {
             filtered = new Codes(type);
             filteredCodes.put(type, filtered);
         }
         return filtered;
     }
getBackingStoreDescription()
String getBackingStoreDescription () throws FactoryException inherited
Returns a description of the underlying backing store, or.
null
if unknown. This is for example the database software used for storing the data. The default implementation returns always
null
.
Returns
The description of the underlying backing store, or
null
.
Exceptions
FactoryException if a failure occurs while fetching the engine description.
{
         return null;
     }
getDescriptionText()
InternationalString getDescriptionText (final String code) throws NoSuchAuthorityCodeException, FactoryException inherited
Gets a description of the object corresponding to a code.
Parameters
code Value allocated by authority.
Returns
A description of the object, or
null
if the object corresponding to the specified
code
has no description.
Exceptions
NoSuchAuthorityCodeException if the specified
code
was not found.
FactoryException if the query failed for some other reason.
References WKTParsingAuthorityFactory.getWKT().
     {
         final String wkt;
         synchronized (this) {
             wkt = getWKT(IdentifiedObject.class, code, null);
         }
         int start = wkt.indexOf('"');
         if (start >= 0) {
             final int end = wkt.indexOf('"', ++start);
             if (end >= 0) {
                 return new SimpleInternationalString(wkt.substring(start, end).trim());
             }
         }
         return null;
     }
getPrimaryKey()
Comparable<?> getPrimaryKey (Class<? extends IdentifiedObject > type, String code) throws FactoryException package inherited
Returns the primary key for the specified authority code.
The default implementation returns the given code with the "authority" part trimmed. This method is overridden by DirectPostgisFactory. Note that
DirectPostgisFactory
will trim the authority itself, because it needs the authority part of the code.
Parameters
type The type of the object being created.
code The authority code to convert to primary key value.
Returns
The primary key for the supplied code.
Exceptions
FactoryException if an error occurred while querying the database.
See also
getPrimaryKeyAuthority()
References WKTParsingAuthorityFactory.trimAuthority().
Referenced by WKTParsingAuthorityFactory.Codes.baseToDerived(), and WKTParsingAuthorityFactory.getWKT().
{
         return trimAuthority(code);
     }
getPrimaryKeyAuthority()
Citation getPrimaryKeyAuthority () package inherited
Returns the authority which is responsible for the maintenance of the primary keys, or.
null
if none. The returned value (if non-null) shall also be one of the elements returned by getAuthorities().
The default implementation returns
null
in all cases. This method is overridden and made public by implementations that are backed by a SQL database. For example the DirectPostgisFactory overrides this method in order to return Citations#POSTGIS.
Returns
The authority which is reponsible for the maintenance of primary keys, or
null
if none.
See also
#getPrimaryKey(Class, String)
Referenced by WKTParsingAuthorityFactory.Parser.complete(), and WKTParsingAuthorityFactory.getAuthority().
{
         return null;
     }
getVendor()
Citation getVendor () inherited
Returns the vendor responsible for creating this factory implementation.
Many implementations from different vendors may be available for the same factory interface.
The default for Geotk implementations is to return Citations::GEOTOOLKIT Geotoolkit.org}.
Returns
The vendor for this factory implementation.
See also
Citations::GEOTOOLKIT
References DirectAuthorityFactory.getAuthority().
{
         return new SimpleCitation(getClass().getName().startsWith("org.geotoolkit.") ? "Geotk" : "Unknown");
     }
getWKTClassOf()
static Class<?> getWKTClassOf (String element) static package inherited
Returns the class of the specified WKT element.
For example this method returns ProjectedCRS}.class for element "@code PROJCS @endcode ".
This method is the converse of getNameOf.
Parameters
element The WKT element name.
Returns
The GeoAPI class of the specified element, or
null
if unknown.
References WKTParsingAuthorityFactory.getWKTNameOf(), and WKTParsingAuthorityFactory.Codes.type.
Referenced by WKTParsingAuthorityFactory.Codes.baseToDerived().
{
         if (element == null) {
             return null;
         }
         element = element.trim().toUpperCase(Locale.US);
         final Class<?> type = TYPES.get(element);
         assert type == null || type.equals(MathTransform.class) || element.equals(getWKTNameOf(type)) : type;
         return type;
     }
getWKTNameOf()
static String getWKTNameOf (final Class<?> type) static package inherited
Returns the WKT name of the specified object type.
For example this method returns "@code PROJCS @endcode " for type ProjectedCRS}.class.
This method is the converse of getClassOf.
Parameters
type The GeoAPI class of the specified element.
Returns
The WKT element name, or
null
if unknown.
Referenced by SpatialRefSysMap.getAuthorityCodes(), and WKTParsingAuthorityFactory.getWKTClassOf().
{
         if (type != null) {
             for (final Map.Entry<String,Class<?>> entry : TYPES.entrySet()) {
                 final Class<?> candidate = entry.getValue();
                 if (candidate.isAssignableFrom(type)) {
                     return entry.getKey();
                 }
             }
         }
         return null;
     }
load()
synchronized void load (final Collection< URL > definitionFiles) throws IOException protected inherited
Loads the WKT strings from the given property files.
This method should be invoked from constructors only. Changes after construction are not allowed.
Parameters
definitionFiles URL to the definition file(s). This is typically built from the values returned by ClassLoader#getResources(String).
Exceptions
IOException If the definition files can't be read.
Since
3.00
References WKTParsingAuthorityFactory.authorities, WKTParsingAuthorityFactory.authority, WKTParsingAuthorityFactory.definitions, Loggings.Keys.DuplicatedContentInFile_1, DirectAuthorityFactory.ensureNonNull(), PropertyAuthorityFactory.log(), and Loggings.Keys.UsingFileAsFactory_2.
Referenced by PropertyAuthorityFactory.PropertyAuthorityFactory().
{
         ensureNonNull("definitionFiles", definitionFiles);
         @SuppressWarnings("unchecked")
         final Properties definitions = (Properties) (Map<?,?>) this.definitions;
         Properties currentFile = definitions;
         boolean containsAxis = false;
         for (final URL url : definitionFiles) {
             /*
              * If we have read other files before this one, use a temporary object.
              * It allows us to remove duplicated keys before they are merged.
              */
             if (!currentFile.isEmpty()) {
                 if (currentFile == definitions) {
                     currentFile = new Properties();
                 } else {
                     currentFile.clear();
                 }
             }
             try (InputStream in = url.openStream()) {
                 currentFile.load(in);
             }
             if (!currentFile.isEmpty()) {
                 // Note: the 'authorities' array length is never 0 (checked by the constructor).
                 final String authority = String.valueOf(Citations.getIdentifier(authorities[0]));
                 log(false, Loggings.Keys.UsingFileAsFactory_2, url, authority);
             }
             if (currentFile != definitions) {
                 if (currentFile.keySet().removeAll(definitions.keySet())) {
                     log(true, Loggings.Keys.DuplicatedContentInFile_1, url, null);
                 }
                 definitions.putAll(currentFile);
             }
             /*
              * Checks if the map we just loaded contains axis. We don't do that in the constructor
              * expecting a Map argument because we don't know if iteration over that map is costly,
              * neither if the user intend to modify it after construction.
              */
             if (!containsAxis) {
                 final Symbols s = Symbols.getDefault();
                 for (final Object wkt : definitions.values()) {
                     if (s.containsAxis((String) wkt)) {
                         containsAxis = true;
                         break;
                     }
                 }
             }
         }
     }
noSuchAuthorityCode()
final NoSuchAuthorityCodeException noSuchAuthorityCode (final Class<?> type, final String code) protected inherited
Creates an exception for an unknown authority code.
This convenience method is provided for implementation of
createXXX
methods.
Parameters
type The GeoAPI interface that was to be created (e.g.
CoordinateReferenceSystem.class
).
code The unknown authority code.
Returns
An exception initialized with an error message built from the specified informations.
References Errors.format(), DirectAuthorityFactory.getAuthority(), Errors.Keys.NoSuchAuthorityCode_3, and DirectAuthorityFactory.trimAuthority().
Referenced by IGNF.createCoordinateReferenceSystem(), DirectPostgisFactory.getPrimaryKey(), and WKTParsingAuthorityFactory.getWKT().
{
         final InternationalString authority = getAuthority().getTitle();
         return new NoSuchAuthorityCodeException(Errors.format(Errors.Keys.NoSuchAuthorityCode_3,
                    code, authority, type), authority.toString(), trimAuthority(code), code);
     }
reportDuplicates()
Set<String> reportDuplicates (final PrintWriter out) throws FactoryException
Prints a list of codes that duplicate the ones provided by ThreadedEpsgFactory.
This is used in order to check the content of the { FILENAME} file (or whatever property file used as backing store for this factory) from the command line.
{ text java -jar geotk-referencing.jar test duplicates }
Parameters
out The writer where to print the report.
Returns
The set of duplicated codes.
Exceptions
FactoryException if an error occurred.
Since
2.4
References Vocabulary.Keys.CompareWith, Vocabulary.Keys.DuplicatedValue, WKTParsingAuthorityFactory.getAuthorityCodes(), Vocabulary.getLabel(), Vocabulary.getResources(), Vocabulary.Keys.NoDuplicationFound, and IndentedLineWriter.setIndentation().
{
         final GeodeticAuthorityFactory sqlFactory = (GeodeticAuthorityFactory) org.apache.sis.referencing.CRS.getAuthorityFactory("EPSG");
         final Vocabulary resources = Vocabulary.getResources(null);
         out.println(resources.getLabel(Vocabulary.Keys.CompareWith));
         try {
             final IndentedLineWriter w = new IndentedLineWriter(out);
             w.setIndentation(4);
             w.write(sqlFactory.getAuthority().getTitle().toString());
             w.flush();
         } catch (IOException e) {
             // Should never happen, since we are writing to a PrintWriter.
             throw new AssertionError(e);
         }
         out.println();
         final Set<String> wktCodes   = this.      getAuthorityCodes(IdentifiedObject.class);
         final Set<String> sqlCodes   = sqlFactory.getAuthorityCodes(IdentifiedObject.class);
         final Set<String> duplicated = new TreeSet<>();
         for (String code : wktCodes) {
             code = code.trim();
             if (sqlCodes.contains(code)) {
                 duplicated.add(code);
                 /*
                  * Note: we don't use wktCodes.retainsAll(sqlCode) because the Set implementations
                  *       are usually not the standard ones, but rather some implementations backed
                  *       by a connection to the resources of the underlying factory. We also close
                  *       the connection after this loop for the same reason.  In addition, we take
                  *       this opportunity for sorting the codes.
                  */
             }
         }
         if (duplicated.isEmpty()) {
             out.println(resources.getString(Vocabulary.Keys.NoDuplicationFound));
         } else {
             for (final String code : duplicated) {
                 out.print(resources.getLabel(Vocabulary.Keys.DuplicatedValue));
                 out.print(' ');
                 out.println(code);
             }
         }
         return duplicated;
     }
reportInstantiationFailures()
Set<String> reportInstantiationFailures (final PrintWriter out) throws FactoryException
Prints a list of CRS that can't be instantiated.
This is used in order to check the content of the { FILENAME} file (or whatever property file used as backing store for this factory) from the command line. To lauch from the command line, use the following:
{ text java -jar geotk-referencing.jar test creates }
Parameters
out The writer where to print the report.
Returns
The set of codes that can't be instantiated.
Exceptions
FactoryException if an error occurred while getAuthorityCodes fetching authority codes}.
Since
2.4
References WKTParsingAuthorityFactory.codes, WKTParsingAuthorityFactory.createCoordinateReferenceSystem(), and WKTParsingAuthorityFactory.getAuthorityCodes().
{
         final Set<String> codes = getAuthorityCodes(CoordinateReferenceSystem.class);
         final Map<String,String> failures = new TreeMap<>();
         for (final String code : codes) {
             try {
                 createCoordinateReferenceSystem(code);
             } catch (FactoryException exception) {
                 failures.put(code, exception.getLocalizedMessage());
             }
         }
         if (!failures.isEmpty()) {
             final TableAppender writer = new TableAppender(out, " ");
             for (final Map.Entry<String,String> entry : failures.entrySet()) {
                 writer.append(entry.getKey());
                 writer.append(':');
                 writer.nextColumn();
                 writer.append(entry.getValue());
                 writer.nextLine();
             }
             try {
                 writer.flush();
             } catch (IOException e) {
                 // Should not happen, since we are writing to a PrintWriter
                 throw new AssertionError(e);
             }
         }
         return failures.keySet();
     }
trimAuthority()
String trimAuthority (String code) protected inherited
Trims the authority scope, if presents.
If more than one authority were given at WKTParsingAuthorityFactory construction time}, then any of them may appears as the scope in the supplied code.
Parameters
code The code to trim.
Returns
The code without the authority scope.
References WKTParsingAuthorityFactory.getAuthorities(), and DirectAuthorityFactory.nameFactory.
Referenced by WKTParsingAuthorityFactory.Parser.complete(), and WKTParsingAuthorityFactory.getPrimaryKey().
{
         code = code.trim();
         final GenericName name  = nameFactory.parseGenericName(null, code);
         if (name instanceof ScopedName) {
             final GenericName scope = ((ScopedName) name).path();
             final String candidate = scope.toString();
             final Citation[] authorities = getAuthorities();
             for (int i=0; i<authorities.length; i++) {
                 if (Citations.identifierMatches(authorities[i], candidate)) {
                     return name.tip().toString().trim();
                 }
             }
         }
         return code;
     }
Member Data Documentation
authorities
Citation [] authorities package inherited
The authorities for this factory, usually as an array of length 1.
Referenced by WKTParsingAuthorityFactory.Parser.complete(), DirectPostgisFactory.dispose(), DirectPostgisFactory.getAuthorities(), WKTParsingAuthorityFactory.getAuthorities(), PropertyAuthorityFactory.load(), PropertyAuthorityFactory.PropertyAuthorityFactory(), and PropertyEpsgFactory.PropertyEpsgFactory().
authority
Citation authority package inherited
The authority for this factory.
Will be computed by getAuthority() when first needed.
Referenced by DirectPostgisFactory.dispose(), DirectPostgisFactory.getAuthorities(), WKTParsingAuthorityFactory.getAuthority(), DirectPostgisFactory.getBackingStoreDescription(), DirectPostgisFactory.getPrimaryKey(), and PropertyAuthorityFactory.load().
definitions
final Map<String,String> definitions package inherited
The properties object for our properties file.
Keys are the authority code for a coordinate reference system and the associated value is a WKT string for the CRS.
Referenced by DirectPostgisFactory.dispose(), PropertyAuthorityFactory.dispose(), DirectPostgisFactory.getAuthorityCodes(), DirectPostgisFactory.getAuthorityNames(), DirectPostgisFactory.getBackingStoreDescription(), DirectPostgisFactory.getPrimaryKey(), PropertyAuthorityFactory.load(), and WKTParsingAuthorityFactory.WKTParsingAuthorityFactory().
factories
final ReferencingFactoryContainer factories protected inherited
The underlying factories used for objects creation.
Referenced by IGNF.createCoordinateReferenceSystem(), and DirectAuthorityFactory.DirectAuthorityFactory().
FILENAME
final String FILENAME = "epsg.properties" static
The default filename to read, which is {}.
The default
PropertyEpsgFactory
implementation will search for every occurrences of
org/geotoolkit/referencing/factory/espg/epsg.properties
on the classpath. However a different directory for this filename can be specified using Hints#CRS_AUTHORITY_EXTRA_DIRECTORY.
Referenced by PropertyEpsgFactory.PropertyEpsgFactory().
LOGGER
final Logger LOGGER = Logging.getLogger("org.geotoolkit.referencing.factory") static inherited
The logger for event related to Geotk factories.
Referenced by DirectPostgisFactory.getAuthorities(), PropertyAuthorityFactory.log(), and PropertyAuthorityFactory.PropertyAuthorityFactory().
nameFactory
final NameFactory nameFactory protected inherited
The name factory to use for creating GenericName.
Since
3.00
Referenced by WKTParsingAuthorityFactory.trimAuthority().