jena-geo: DataStores Class Reference
DataStores Class Reference
Creates DataStore instances from a set of parameters.
Static Public Member Functions
static Collection<? extends Resource > flatten (Resource root, boolean includeRoot) throws DataStoreException
List all resources in given resource.
static< T extends Resource > Collection< T > flatten (Resource root, boolean includeRoot, Class< T > resourceClass) throws DataStoreException
List all resources in given resource.
static final< T extends Resource > Set< GenericName > getNames (Resource root, boolean includeRoot, Class< T > resourceClass) throws DataStoreException
Get a collection of all available names of a specific resource type.
static ResourceType [] getResourceTypes (DataStoreProvider provider)
Extract the ResourceType supported by the DataStoreProvider.
static< T > Set< T > getProviders (final Class< T > clazz, ResourceType ... types)
Returns the set of all providers, optionally filtered by class and resource types.
static synchronized DataStoreFactory getFactoryById (final String identifier)
Returns a factory having an DataStoreFactory::getIdentification() identification} equals (ignoring case) to the given string.
static synchronized DataStoreProvider getProviderById (final String identifier)
Returns a provider having an DataStoreProvider::getOpenParameters() identification} equals (ignoring case) to the given string.
static org.apache.sis.storage.DataStore open (final Map< String, Serializable > parameters) throws DataStoreException
Creates a DataStore instance for the given map of parameter values.
static org.apache.sis.storage.DataStore open (final ParameterValueGroup parameters) throws DataStoreException
Creates a DataStore instance for the given parameters group.
static org.apache.sis.storage.DataStore open (DataStoreProvider factory, Map< String, ? extends Serializable > params) throws DataStoreException
static org.apache.sis.storage.DataStore create (DataStoreProvider factory, Map< String, ? extends Serializable > params) throws DataStoreException
Static Package Functions
static final Map< String, Serializable > forceIdentifier (DataStoreProvider factory, Map params)
Set the identifier parameter in the map if not present.
Private Member Functions
DataStores ()
Do not allow instantiation of this class.
Static Private Member Functions
static< T extends Resource > void list (Resource resource, Collection< T > list, Class< T > resourceClass) throws DataStoreException
static synchronized org.apache.sis.storage.DataStore open (final ParameterValueGroup parameters, final Map< String, Serializable > asMap) throws DataStoreException
Implementation of the public.
static boolean canProcess (DataStoreFactory factory, Map< String, ? extends Serializable > params)
Test to see if this factory is suitable for processing the data pointed to by the params map.
Detailed Description
Creates DataStore instances from a set of parameters.
{
}
DataStore factories must implement the DataStoreFactory interface and declare their fully qualified class name in a
META-INF/services/org.geotoolkit.storage.DataStoreFactory
file. See the ServiceLoader javadoc for more information.
Author
Martin Desruisseaux (Geomatys)
Johann Sorel (Geomatys)
Constructor & Destructor Documentation
DataStores()
DataStores () private
Do not allow instantiation of this class.
{
     }
Member Function Documentation
canProcess()
static boolean canProcess (DataStoreFactory factory, Map< String, ? extends Serializable > params) static private
Test to see if this factory is suitable for processing the data pointed to by the params map.
If this data source requires a number of parameters then this method should check that they are all present and that they are all valid. If the data source is a file reading data source then the extensions or mime types of any files specified should be checked. For example, a Shapefile data source should check that the url param ends with shp, such tests should be case insensitive.
Parameters
params The full set of information needed to construct a live data source.
Returns
boolean true if and only if this factory can process the resource indicated by the param set and all the required params are present.
References DataStoreFactory.canProcess(), DataStores.forceIdentifier(), DataStoreFactory.IDENTIFIER, and Parameters.toParameter().
Referenced by DataStores.open().
{
         params = forceIdentifier(factory, params);
         //ensure it's the valid identifier
         final Object id = params.get(DataStoreFactory.IDENTIFIER.getName().getCode());
         try{
             final String expectedId = ((ParameterDescriptor<String>)factory.getOpenParameters()
                 .descriptor(DataStoreFactory.IDENTIFIER.getName().getCode())).getDefaultValue();
             if (!expectedId.equals(id)) {
                 return false;
             }
         } catch(ParameterNotFoundException ex) {
             //this feature store factory does not declare a identifier id
         }
         final ParameterValueGroup prm = Parameters.toParameter(params, factory.getOpenParameters());
         if (prm == null) {
             return false;
         }
         try {
             return factory.canProcess(prm);
         } catch (InvalidParameterValueException ex) {
             return false;
         }
     }
create()
static org.apache.sis.storage.DataStore create (DataStoreProvider factory, Map< String, ? extends Serializable > params) throws DataStoreException static
See also
DataStoreFactory::create(org.opengis.parameter.ParameterValueGroup)
References DataStores.forceIdentifier(), and Parameters.toParameter().
{
         final ParameterValueGroup prm;
         try {
             prm = Parameters.toParameter(DataStores.forceIdentifier(factory, params), factory.getOpenParameters());
         } catch(IllegalArgumentException ex) {
             throw new DataStoreException(ex);
         }
         if (factory instanceof DataStoreFactory) {
             return ((DataStoreFactory) factory).create(prm);
         } else {
             return factory.open(prm);
         }
     }
flatten() [1/2]
static Collection<? extends Resource> flatten (Resource root, boolean includeRoot) throws DataStoreException static
List all resources in given resource.
Parameters
root Root resource to explore
includeRoot include the root in the stream
Returns
Collection of all resources
Referenced by DataStores.getNames().
{
         return flatten(root, includeRoot, Resource.class);
     }
flatten() [2/2]
static <T extends Resource> Collection<T> flatten (Resource root, boolean includeRoot, Class< T > resourceClass) throws DataStoreException static
List all resources in given resource.
Parameters
root Root resource to explore
includeRoot include the root in the stream
resourceClass class of searched resources
Returns
Collection of all resources
References DataStores.list().
{
         ArgumentChecks.ensureNonNull("resourceClass", resourceClass);   // null not allowed because unsafe.
         if (root instanceof Aggregate) {
             final List<T> list = new ArrayList<>();
             if (includeRoot && resourceClass.isInstance(root)) list.add((T) root);
             list(root, list, resourceClass);
             return list;
         } else if (includeRoot && resourceClass.isInstance(root)) {
             return Collections.singleton((T) root);
         } else {
             return Collections.emptyList();
         }
     }
forceIdentifier()
static final Map<String,Serializable> forceIdentifier (DataStoreProvider factory, Map params) static package
Set the identifier parameter in the map if not present.
References DataStoreFactory.IDENTIFIER.
Referenced by DataStores.canProcess(), DataStores.create(), and DataStores.open().
{
         if (!params.containsKey(DataStoreFactory.IDENTIFIER.getName().getCode())) {
             //identifier is not specified, force it
             final ParameterDescriptorGroup desc = factory.getOpenParameters();
             params = new HashMap<String, Serializable>(params);
             final Object value = ((ParameterDescriptor)desc.descriptor(DataStoreFactory.IDENTIFIER.getName().getCode())).getDefaultValue();
             params.put(DataStoreFactory.IDENTIFIER.getName().getCode(), (Serializable)value);
         }
         return params;
     }
getFactoryById()
static synchronized DataStoreFactory getFactoryById (final String identifier) static
Returns a factory having an DataStoreFactory::getIdentification() identification} equals (ignoring case) to the given string.
If more than one factory is found, then this method selects an arbitrary one. If no factory is found, then this method returns
null
.
Parameters
identifier The identifier of the factory to find.
Returns
A factory for the given identifier, or
null
if none.
References DataStores.getProviders().
{
         for (final DataStoreFactory factory : getProviders(DataStoreFactory.class)) {
             for (String name : IdentifiedObjects.getNames(factory.getOpenParameters(),null)) {
                 if (name.equals(identifier)) {
                     return factory;
                 }
             }
         }
         return null;
     }
getNames()
static final<T extends Resource> Set<GenericName> getNames (Resource root, boolean includeRoot, Class< T > resourceClass) throws DataStoreException static
Get a collection of all available names of a specific resource type.
Returns
Set<GenericName> , never null, but can be empty.
Exceptions
DataStoreException
References DataStores.flatten().
{
         final Set<GenericName> names = new HashSet<>();
         for (T t : flatten(root, includeRoot, resourceClass)) {
             t.getIdentifier().ifPresent((name) -> names.add(name));
         }
         return names;
     }
getProviderById()
static synchronized DataStoreProvider getProviderById (final String identifier) static
Returns a provider having an DataStoreProvider::getOpenParameters() identification} equals (ignoring case) to the given string.
If more than one provider is found, then this method selects an arbitrary one. If no factory is found, then this method returns
null
.
Parameters
identifier The identifier of the factory to find.
Returns
A factory for the given identifier, or
null
if none.
{
         for (final DataStoreProvider factory : org.apache.sis.storage.DataStores.providers()) {
             for (String name : IdentifiedObjects.getNames(factory.getOpenParameters(),null)) {
                 if (name.equals(identifier)) {
                     return factory;
                 }
             }
         }
         return null;
     }
getProviders()
static <T> Set<T> getProviders (final Class< T > clazz, ResourceType ... types) static
Returns the set of all providers, optionally filtered by class and resource types.
Parameters
<T> The type of provider to be returned.
clazz The type of factories to be returned, or
null
for all kind of factories.
types types of resources that must be supported by the provider, none for all
Returns
The set of factories for the given conditions.
Deprecated:
the implementation of this method is unsafe.
References DataStores.getResourceTypes().
Referenced by DataStores.getFactoryById(), and DataStores.open().
{
         final Set<T> results = new HashSet<>();
         loop:
         for (DataStoreProvider p : org.apache.sis.storage.DataStores.providers()) {
             if (clazz != null && !clazz.isInstance(p)) continue;
             if (types != null && types.length > 0) {
                 final ResourceType[] supportedTypes = getResourceTypes(p);
                 for (ResourceType type : types) {
                     if (ArraysExt.contains(supportedTypes, type)) {
                         results.add((T) p);
                         continue loop;
                     }
                 }
             } else {
                 results.add((T) p);
             }
         }
         return results;
     }
getResourceTypes()
static ResourceType [] getResourceTypes (DataStoreProvider provider) static
Extract the ResourceType supported by the DataStoreProvider.
Returns
supported resource types, never null, can be empty
References StoreMetadataExt.resourceTypes().
Referenced by DataStores.getProviders().
{
         final StoreMetadataExt meta = provider.getClass().getAnnotation(StoreMetadataExt.class);
         if (meta == null) return new ResourceType[0];
         return meta.resourceTypes();
     }
list()
static <T extends Resource> void list (Resource resource, Collection< T > list, Class< T > resourceClass) throws DataStoreException static private
Referenced by DataStores.flatten().
{
         if (resource instanceof Aggregate) {
             final Aggregate ds = (Aggregate) resource;
             for (Resource rs : ds.components()) {
                 if (resourceClass.isInstance(rs)) list.add((T) rs);
                 list(rs, list, resourceClass);
             }
         }
     }
open() [1/4]
static org.apache.sis.storage.DataStore open (final Map< String, Serializable > parameters) throws DataStoreException static
Creates a DataStore instance for the given map of parameter values.
This method iterates over all #getAvailableFactories(Class) available factories} until a factory claiming to DataStoreFactory::canProcess(Map) be able to process} the given parameters is found. This factory then DataStoreFactory::open(Map) open} the data store.
Parameters
parameters The configuration of the desired data store.
Returns
A data store created from the given parameters, or
null
if none.
Exceptions
DataStoreException If a factory is found but can't open the data store.
Referenced by DataStores.open().
{
         ArgumentChecks.ensureNonNull("parameters", parameters);
         return open((ParameterValueGroup)null, parameters);
     }
open() [2/4]
static org.apache.sis.storage.DataStore open (final ParameterValueGroup parameters) throws DataStoreException static
Creates a DataStore instance for the given parameters group.
This method iterates over all #getAvailableFactories(Class) available factories} until a factory claiming to DataStoreFactory::canProcess(ParameterValueGroup) be able to process} the given parameters is found. This factory then DataStoreFactory::open(ParameterValueGroup) open} the data store.
Parameters
parameters The configuration of the desired data store.
Returns
A data store created from the given parameters, or
null
if none.
Exceptions
DataStoreException If a factory is found but can't open the data store.
References DataStores.open().
{
         ArgumentChecks.ensureNonNull("parameters", parameters);
         return open(parameters, null);
     }
open() [3/4]
static synchronized org.apache.sis.storage.DataStore open (final ParameterValueGroup parameters, final Map< String, Serializable > asMap) throws DataStoreException static private
Implementation of the public.
open
method. Exactly one of the
parameters
and
asMap
arguments shall be non-null.
References DataStores.canProcess(), DataStores.getProviders(), and DataStores.open().
     {
         CharSequence unavailable = null;
         Exception error = null;
         for (final DataStoreFactory factory : getProviders(DataStoreFactory.class)) {
             try {
                 if ((parameters != null) ? factory.canProcess(parameters) : canProcess(factory,asMap)) {
                     return ((parameters != null) ? factory.open(parameters) : open(factory,asMap));
                 }
             } catch (Exception e) {
                 // If an error occurs with a factory, we skip it and try another factory.
                 if (error != null) {
                     error.addSuppressed(e);
                 } else {
                     error = e;
                 }
             }
         }
         if (unavailable != null) {
             throw new DataStoreException("The " + unavailable + " data store is not available. "
                     + "Are every required JAR files accessible on the classpath?");
         } else if (error instanceof DataStoreException) {
             throw (DataStoreException) error;
         } else if (error != null) {
             throw new DataStoreException("An error occurred while searching for a datastore", error);
         }
         return null;
     }
open() [4/4]
static org.apache.sis.storage.DataStore open (DataStoreProvider factory, Map< String, ? extends Serializable > params) throws DataStoreException static
References DataStores.forceIdentifier(), DataStores.open(), and Parameters.toParameter().
{
         final ParameterValueGroup prm;
         try {
             prm = Parameters.toParameter(
                     forceIdentifier(factory, params),
                     factory.getOpenParameters());
         } catch (IllegalArgumentException ex) {
             throw new DataStoreException(ex);
         }
         return open(prm);
     }