jena-geo: Assertions Class Reference
Assertions Class Reference
Static methods for assertions.
Static Package Functions
static boolean checkTransform (final double[] expected, final int offset, final double x, final double y, final double tolerance) throws ProjectionException
Checks if transform using spherical formulas produces the same result than ellipsoidal formulas.
static boolean checkTransform (final double[] expected, final int offset, final double x, final double y) throws ProjectionException
Default version of checkTransform(double,double,double[],int).
static boolean checkInverseTransform (final double[] expected, final int offset, final double λ, final double φ, final double tolerance) throws ProjectionException
Checks if inverse transform using spherical formulas produces the same result than ellipsoidal formulas.
static boolean checkInverseTransform (final double[] expected, final int offset, final double λ, final double φ) throws ProjectionException
Default version of checkInverseTransform(double,double,double[],int,double).
static boolean checkDerivative (final Matrix spherical, final Matrix ellipsoidal) throws ProjectionException
Checks if derivatives using spherical formulas produces the same result than ellipsoidal formulas.
Private Member Functions
Assertions ()
Do not allows instantiation of this class.
Static Private Member Functions
static void compare (final String variable, double expected, double actual, final double tolerance) throws ProjectionException
Compares two value for equality up to some tolerance threshold.
Static Private Attributes
static final double INVERSE_TOLERANCE = 1E-7
Maximum difference allowed when comparing the result of an inverse projections, in radians.
static final double FORWARD_TOLERANCE = 1E-7
Maximum difference allowed when comparing the result of forward projections, in distance on the unit ellipse.
static final double DERIVATIVE_TOLERANCE = 1E-1
Maximum difference allowed between spherical and ellipsoidal formulas when comparing derivatives.
Detailed Description
Static methods for assertions.
This is used only when Java 1.4 assertions are enabled. When a point has been projected using spherical formulas, compare with the same point transformed using spherical formulas and throw an exception if the result differ.
Author
Martin Desruisseaux (Geomatys)
Rémi Maréchal (Geomatys)
Since
2.0
Constructor & Destructor Documentation
Assertions()
Assertions () private
Do not allows instantiation of this class.
{
     }
Member Function Documentation
checkDerivative()
static boolean checkDerivative (final Matrix spherical, final Matrix ellipsoidal) throws ProjectionException static package
Checks if derivatives using spherical formulas produces the same result than ellipsoidal formulas.
This method is invoked during assertions only. The spherical formulas are used for the "expected" results since they are simpler than the ellipsoidal formulas.
Since
3.18
References Assertions.compare(), and Assertions.DERIVATIVE_TOLERANCE.
Referenced by EquatorialStereographic.Spherical.transform(), CassiniSoldner.Spherical.transform(), Stereographic.Spherical.transform(), and LambertAzimuthalEqualArea.Spherical.transform().
     {
         if (spherical != null || ellipsoidal != null) { // NullPointerException is ok if only one is null.
             compare("m00", spherical.getElement(0,0), ellipsoidal.getElement(0,0), DERIVATIVE_TOLERANCE);
             compare("m01", spherical.getElement(0,1), ellipsoidal.getElement(0,1), DERIVATIVE_TOLERANCE);
             compare("m10", spherical.getElement(1,0), ellipsoidal.getElement(1,0), DERIVATIVE_TOLERANCE);
             compare("m11", spherical.getElement(1,1), ellipsoidal.getElement(1,1), DERIVATIVE_TOLERANCE);
         }
         return true;
     }
checkInverseTransform() [1/2]
static boolean checkInverseTransform (final double [] expected, final int offset, final double λ, final double φ, final double tolerance) throws ProjectionException static package
Checks if inverse transform using spherical formulas produces the same result than ellipsoidal formulas.
This method is invoked during assertions only.
{
Note
This method ignores the longitude if the latitude is at a pole, because in such case the longitude is meanless.}
Parameters
expected The (longitude,latitude) computed by ellipsoidal formulas.
offset Index of the coordinate in the
expected
array.
λ The longitude computed by spherical formulas, in radians.
φ The latitude computed by spherical formulas, in radians.
tolerance The tolerance (optional).
Returns
Always
true
if the
tolerance
value is valid.
Exceptions
ProjectionException if the comparison failed.
References Assertions.compare().
Referenced by Assertions.checkInverseTransform(), EquatorialStereographic.Spherical.checkInverseTransform(), CassiniSoldner.Spherical.checkInverseTransform(), Stereographic.Spherical.checkInverseTransform(), and LambertAzimuthalEqualArea.Spherical.checkInverseTransform().
     {
         compare("latitude", expected[offset+1], φ, tolerance);
         if (abs(PI/2 - abs(φ)) > ANGLE_TOLERANCE) {
             compare("longitude", expected[offset], λ, tolerance);
         }
         return tolerance < POSITIVE_INFINITY;
     }
checkInverseTransform() [2/2]
static boolean checkInverseTransform (final double [] expected, final int offset, final double λ, final double φ) throws ProjectionException static package
Default version of checkInverseTransform(double,double,double[],int,double).
References Assertions.checkInverseTransform().
     {
         return checkInverseTransform(expected, offset, λ, φ, INVERSE_TOLERANCE);
     }
checkTransform() [1/2]
static boolean checkTransform (final double [] expected, final int offset, final double x, final double y, final double tolerance) throws ProjectionException static package
Checks if transform using spherical formulas produces the same result than ellipsoidal formulas.
This method is invoked during assertions only.
Parameters
expected The (easting,northing) computed by ellipsoidal formulas.
offset Index of the coordinate in the
expected
array.
x The easting computed by spherical formulas on the unit sphere.
y The northing computed by spherical formulas on the unit sphere.
tolerance The tolerance (optional).
Returns
Always
true
if the
tolerance
value is valid.
Exceptions
ProjectionException if the comparison failed.
References Assertions.compare().
Referenced by Assertions.checkTransform(), EquatorialStereographic.transform(), EquatorialStereographic.Spherical.transform(), CassiniSoldner.Spherical.transform(), Stereographic.Spherical.transform(), and LambertAzimuthalEqualArea.Spherical.transform().
     {
         if (expected != null) {
             compare("x", expected[offset  ], x, tolerance);
             compare("y", expected[offset+1], y, tolerance);
         }
         return tolerance < POSITIVE_INFINITY;
     }
checkTransform() [2/2]
static boolean checkTransform (final double [] expected, final int offset, final double x, final double y) throws ProjectionException static package
Default version of checkTransform(double,double,double[],int).
References Assertions.checkTransform().
     {
         return checkTransform(expected, offset, x, y, FORWARD_TOLERANCE);
     }
compare()
static void compare (final String variable, double expected, double actual, final double tolerance) throws ProjectionException static private
Compares two value for equality up to some tolerance threshold.
This is used during assertions only. The comparison does not fail if at least one value to compare is Double#NaN or infinity.
Hack: if the
variable
name starts by lower-case
L
(as in "longitude" and "latitude"), then the value is assumed to be an angle in radians. This is used for formatting an error message, if needed.
Exceptions
ProjectionException if the comparison failed.
References Errors.format(), and Errors.Keys.TestFailure_3.
Referenced by Assertions.checkDerivative(), Assertions.checkInverseTransform(), and Assertions.checkTransform().
     {
         final double delta = abs(expected - actual);
         if (delta > tolerance) {
             if (variable.charAt(0) == 'l') {
                 actual   = toDegrees(actual);
                 expected = toDegrees(expected);
             } else if (abs(actual) > 30 && abs(expected) > 30) {
                 /*
                  * If the projected point tend toward infinity, treats the value as if is was
                  * really infinity. Note that 30 is considered as "close to infinity" because
                  * of the result we get when projecting 90°N using Mercator spherical formula:
                  *
                  *     y = log(tan(π/4 + φ/2))
                  *
                  * Because there is no exact representation of π/2 in base 2, the tangent
                  * function gives 1.6E+16 instead of infinity, which leads the logarithmic
                  * function to give us 37.3.
                  *
                  * This behavior is tested in MercatorTest.testSphericalFormulas().
                  */
                 if (signum(actual) == signum(expected)) {
                     return;
                 }
             }
             throw new ProjectionException(Errors.format(Errors.Keys.TestFailure_3, variable,
                     String.valueOf(expected), String.valueOf(actual)) + // Force full precision.
                     "(Δ" + variable + '=' + delta + " ε=" + tolerance + ')');
         }
     }
Member Data Documentation
DERIVATIVE_TOLERANCE
final double DERIVATIVE_TOLERANCE = 1E-1 static private
Maximum difference allowed between spherical and ellipsoidal formulas when comparing derivatives.
Units are metres.
Referenced by Assertions.checkDerivative().
FORWARD_TOLERANCE
final double FORWARD_TOLERANCE = 1E-7 static private
Maximum difference allowed when comparing the result of forward projections, in distance on the unit ellipse.
A value of 1E-7 is approximatively 0.1 metres.
INVERSE_TOLERANCE
final double INVERSE_TOLERANCE = 1E-7 static private
Maximum difference allowed when comparing the result of an inverse projections, in radians.
A value of 1E-7 radians is approximatively 0.5 kilometres. Note that inverse projections are typically less accurate than forward projections. This tolerance is set to such high value for avoiding too intrusive assertion errors. This is okay only for catching gross programming errors.