jena-geo: ProgressController Class Reference
ProgressController Class Reference abstract
Monitors the progress of some lengthly operation, and allows cancellation.
Public Member Functions
Locale getLocale ()
Returns the locale used for formatting messages.
InternationalString getTask ()
Returns the description of the current task being performed, or.
void setTask (CharSequence task)
Sets the description of the current task being performed.
abstract void started ()
Notifies this controller that the operation begins.
void started (final ProcessEvent event)
Notifies this controller that the operation begins and sets the states of this controller according the given event.
abstract void paused ()
Notifies this controller that the operation is suspended.
void paused (final ProcessEvent event)
Notifies this controller that the operation is suspended and sets the states of this controller according the given event.
abstract void resumed ()
Notifies this controller that the operation is resumed.
void resumed (final ProcessEvent event)
Notifies this controller that the operation is resumed and sets the states of this controller according the given event.
float getProgress ()
Returns the current progress as a percent completed.
void setProgress (float percent)
Notifies this controller of progress in the lengthly operation.
void progressing (final ProcessEvent event)
Updates the setTask(CharSequence) task} and setProgress(float) progress} state, and exceptionOccurred(Throwable) reports the exception} if any.
abstract void completed ()
Notifies this controller that the operation has finished.
void completed (final ProcessEvent event)
Notifies this controller that the operation has finished and sets the states of this controller according the given event.
void failed (final ProcessEvent event)
Notifies this controller that the operation has failed and sets the states of this controller according the given event.
void dismissed (final ProcessEvent event)
Reports that a process has been dismissed.
void cancel ()
Indicates that this job should be canceled.
boolean isCanceled ()
Returns.
abstract void warningOccurred (String source, String location, String warning)
Reports a warning.
abstract void exceptionOccurred (Throwable exception)
Reports an exception.
Protected Member Functions
ProgressController ()
Constructs a progress controller which will format messages in the Locale::getDefault() system default locale}.
Private Attributes
final Locale locale
The language to use for formatting messages.
volatile InternationalString task
Name of the lengthly operation.
volatile float progress
The current progress percentage, as a value between 0 and 100.
volatile boolean canceled
Detailed Description
Monitors the progress of some lengthly operation, and allows cancellation.
This abstract class makes no assumption about the output device. Additionally, this class provides support for non-fatal warning and exception reports.
All implementations should be multi-thread safe, even the ones that provide feedback to a user interface thread.
Usage example:
{ java float scale = 100f / maximumCount; controller.started(); for (int counter=0; counter<maximumCount; counter++) { if (controller.isCanceled()) { break; } controller.progress(scale * counter); try { // Do some work... } catch (NonFatalException e) { controller.exceptionOccurred(e); } } controller.complete(); }
Author
Martin Desruisseaux (IRD, Geomatys)
Jody Garnet (Refractions Research)
Guilhem Legal (Geomatys)
Version
3.20
Since
3.19 (derived from 2.0)
Constructor & Destructor Documentation
ProgressController()
ProgressController () protected
Constructs a progress controller which will format messages in the Locale::getDefault() system default locale}.
{
         locale = Locale.getDefault();
     }
Member Function Documentation
cancel()
void cancel ()
Indicates that this job should be canceled.
{
         canceled = true;
     }
completed() [1/2]
abstract void completed () abstract
Notifies this controller that the operation has finished.
The progress indicator will shows 100% or disappears, at implementor choice. If warning messages were pending, they will be displayed now.
Referenced by ProgressController.completed(), and ProgressController.progressing().
completed() [2/2]
void completed (final ProcessEvent event)
Notifies this controller that the operation has finished and sets the states of this controller according the given event.
The default implementation first invokes progressing(ProcessEvent) progressing}(event), then invokes completed().
Parameters
event The progress event, or
null
if none.
Since
3.19
Implements ProcessListener.
References ProgressController.completed(), and ProgressController.progressing().
{
         progressing(event);
         completed();
     }
dismissed()
void dismissed (final ProcessEvent event)
Reports that a process has been dismissed.
Parameters
event The progress event.
Implements ProcessListener.
References ProgressController.failed().
{
         canceled = true;
         failed(event);
     }
exceptionOccurred()
abstract void exceptionOccurred (Throwable exception) abstract
Reports an exception.
This method may prints the stack trace to the System::err standard error stream} or display it in a dialog box, at implementor choice.
Parameters
exception The exception to report.
Referenced by ProgressController.isCanceled(), and ProgressController.progressing().
failed()
void failed (final ProcessEvent event)
Notifies this controller that the operation has failed and sets the states of this controller according the given event.
The default implementation just delegates to progressing(ProcessEvent) progressing}(event). Note that the above
progressing
method pass the ProcessEvent::getException() exception declared by the event} (if any) to the exceptionOccurred(Throwable) method.
Parameters
event The progress event, or
null
if none.
Since
3.19
Implements ProcessListener.
References ProgressController.progressing().
Referenced by ProgressController.dismissed().
{
         progressing(event);
     }
getLocale()
Locale getLocale ()
Returns the locale used for formatting messages.
The default value is the Locale::getDefault() system default} locale.
Returns
The locale.
References ProgressController.locale.
{
         return locale;
     }
getProgress()
float getProgress ()
Returns the current progress as a percent completed.
Returns
Percent completed between 0 and 100 inclusive.
References ProgressController.progress.
{
         return progress;
     }
getTask()
InternationalString getTask ()
Returns the description of the current task being performed, or.
null
if none. It is assumed that if the task is
null
applications may simply report that the process is "<cite>in progress</cite>" or "<cite>working</cite>" as represented in the getLocale() current locale}.
Returns
Description of the task being performed, or
null
if none.
References ProgressController.task.
{
         return task;
     }
isCanceled()
boolean isCanceled ()
Returns.
true
if this job is canceled.
Returns
true
if this job is canceled.
References ProgressController.canceled, ProgressController.exceptionOccurred(), and ProgressController.warningOccurred().
{
         return canceled;
     }
paused() [1/2]
abstract void paused () abstract
Notifies this controller that the operation is suspended.
Since
3.20
Referenced by ProgressController.paused(), and ProgressController.started().
paused() [2/2]
void paused (final ProcessEvent event)
Notifies this controller that the operation is suspended and sets the states of this controller according the given event.
The default implementation first invokes progressing(ProcessEvent) progressing}(event), then invokes paused().
Parameters
event The progress event, or
null
if none.
Since
3.20
Implements ProcessListener.
References ProgressController.paused(), ProgressController.progressing(), and ProgressController.resumed().
{
         progressing(event);
         paused();
     }
progressing()
void progressing (final ProcessEvent event)
Updates the setTask(CharSequence) task} and setProgress(float) progress} state, and exceptionOccurred(Throwable) reports the exception} if any.
More specifically:
The new task is set to the ProcessEvent#getTask() value unless the later method returned
null
, in which case this
ProgressController
task is left unchanged.
The new progress is set to the ProcessEvent#getProgress() value unless the later method returned Float#NaN, in which case this
ProgressController
progress state is left unchanged.
If ProcessEvent#getException() returns a non-null value, then that value is given to exceptionOccurred(Throwable).
Parameters
event The progress event, or
null
if none.
Since
3.19
Implements ProcessListener.
References ProgressController.completed(), ProgressController.exceptionOccurred(), ProgressController.setProgress(), and ProgressController.setTask().
Referenced by ProgressController.completed(), ProgressController.failed(), ProgressController.paused(), ProgressController.resumed(), and ProgressController.started().
{
         if (event != null) {
             final InternationalString task = event.getTask();
             if (task != null) {
                 setTask(task);
             }
             final float progress = event.getProgress();
             if (!Float.isNaN(progress)) {
                 setProgress(progress);
             }
             final Exception ex = event.getException();
             if (ex != null) {
                 exceptionOccurred(ex);
             }
         }
     }
resumed() [1/2]
abstract void resumed () abstract
Notifies this controller that the operation is resumed.
Since
3.20
Referenced by ProgressController.paused(), and ProgressController.resumed().
resumed() [2/2]
void resumed (final ProcessEvent event)
Notifies this controller that the operation is resumed and sets the states of this controller according the given event.
The default implementation first invokes resumed(), then invokes progressing(ProcessEvent) progressing}(event).
Parameters
event The progress event, or
null
if none.
Since
3.20
Implements ProcessListener.
References ProgressController.progressing(), and ProgressController.resumed().
{
         resumed();
         progressing(event);
     }
setProgress()
void setProgress (float percent)
Notifies this controller of progress in the lengthly operation.
Progresses are reported as a value between 0 and 100 inclusive. Values out of bounds will be clamped.
Parameters
percent The progress as a value between 0 and 100 inclusive.
Referenced by ProgressController.progressing().
{
         if (percent < 0  ) percent = 0;
         if (percent > 100) percent = 100;
         progress = percent;
     }
setTask()
void setTask (CharSequence task)
Sets the description of the current task being performed.
This method is usually invoked before any progress begins. However, it is legal to invoke this method at any time during the operation, in which case the task label is updated without any change to the percentage accomplished.
Parameters
task Description of the task being performed as a String or InternationalString, or
null
if none.
References ProgressController.started().
Referenced by ProgressController.progressing().
{
         if (task != null && !(task instanceof InternationalString)) {
             task = new SimpleInternationalString(task.toString());
         }
         this.task = (InternationalString) task;
     }
started() [1/2]
abstract void started () abstract
Notifies this controller that the operation begins.
Referenced by ProgressController.setTask(), and ProgressController.started().
started() [2/2]
void started (final ProcessEvent event)
Notifies this controller that the operation begins and sets the states of this controller according the given event.
The default implementation first invokes started(), then invokes progressing(ProcessEvent) progressing}(event).
Parameters
event The progress event, or
null
if none.
Since
3.19
Implements ProcessListener.
References ProgressController.paused(), ProgressController.progressing(), and ProgressController.started().
{
         started();
         progressing(event);
     }
warningOccurred()
abstract void warningOccurred (String source, String location, String warning) abstract
Reports a warning.
This warning may be java.util.logger.Logger logged}, printed to the System::err standard error stream}, appears in a windows or be ignored, at implementor choice.
Parameters
source Name of the warning source, or
null
if none. This is typically the name of the file being parsed, or the URL of the data being processed.
location Text to write on the left side of the warning message, or
null
if none. This is typically the line number where the error occurred in the
source
file or the feature ID of the feature that produced the message.
warning The warning message.
Referenced by ProgressController.isCanceled().
Member Data Documentation
canceled
volatile boolean canceled private
true
if the action has been canceled.
Referenced by ProgressController.isCanceled().
locale
final Locale locale private
The language to use for formatting messages.
Referenced by ProgressController.getLocale().
progress
volatile float progress private
The current progress percentage, as a value between 0 and 100.
Referenced by ProgressController.getProgress().
task
volatile InternationalString task private
Name of the lengthly operation.
Referenced by ProgressController.getTask().