jena-geo: DirectAuthorityFactory Class Reference
DirectAuthorityFactory Class Reference abstract
The base class for authority factories that create referencing object directly.
Public Member Functions
Citation getVendor ()
Returns the vendor responsible for creating this factory implementation.
abstract Citation getAuthority ()
Returns the organization or party responsible for definition and maintenance of the database.
String getBackingStoreDescription () throws FactoryException
Returns a description of the underlying backing store, or.
Static Public Attributes
static final Logger LOGGER = Logging.getLogger("org.geotoolkit.referencing.factory")
The logger for event related to Geotk factories.
Protected Member Functions
DirectAuthorityFactory ()
DirectAuthorityFactory (final ReferencingFactoryContainer factories)
Constructs an instance using the specified set of factories.
void dispose (final boolean shutdown)
Releases resources immediately instead of waiting for the garbage collector.
String trimAuthority (String code)
Trims the authority scope, if presents.
final NoSuchAuthorityCodeException noSuchAuthorityCode (final Class<?> type, final String code)
Creates an exception for an unknown authority code.
Static Protected Member Functions
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException
Makes sure that an argument is non-null.
Protected Attributes
final NameFactory nameFactory
The name factory to use for creating GenericName.
final ReferencingFactoryContainer factories
The underlying factories used for objects creation.
Detailed Description
The base class for authority factories that create referencing object directly.
This is in contrast with other factories like the AuthorityFactoryAdapter adapter} or CachingAuthorityFactory caching} ones, which delegates their work to an other factory.
Author
Martin Desruisseaux (IRD)
Deprecated:
Moved to org.apache.sis.referencing.factory.GeodeticAuthorityFactory in Apache SIS.
Constructor & Destructor Documentation
DirectAuthorityFactory() [1/2]
DirectAuthorityFactory () protected
{
         this(new ReferencingFactoryContainer());
     }
DirectAuthorityFactory() [2/2]
DirectAuthorityFactory (final ReferencingFactoryContainer factories) protected
Constructs an instance using the specified set of factories.
Parameters
factories The low-level factories to use.
References DirectAuthorityFactory.ensureNonNull(), and DirectAuthorityFactory.factories.
{
         ensureNonNull("factories", factories);
         this.factories = factories;
         nameFactory = DefaultFactories.forBuildin(NameFactory.class);
     }
Member Function Documentation
dispose()
void dispose (final boolean shutdown) protected
Releases resources immediately instead of waiting for the garbage collector.
Once a factory has been disposed, further
create(...)
invocations may throw a FactoryException. Disposing a previously-disposed factory, however, has no effect.
{
         // To be overridden by subclasses.
     }
ensureNonNull()
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException static protected
Makes sure that an argument is non-null.
This is a convenience method for subclass methods.
Parameters
name Argument name.
object User argument.
Exceptions
InvalidParameterValueException if
object
is null.
References Errors.format(), and Errors.Keys.NullArgument_1.
Referenced by DirectAuthorityFactory.DirectAuthorityFactory(), DirectPostgisFactory.getPrimaryKey(), WKTParsingAuthorityFactory.getWKT(), PropertyAuthorityFactory.load(), and WKTParsingAuthorityFactory.WKTParsingAuthorityFactory().
     {
         if (object == null) {
             throw new InvalidParameterValueException(Errors.format(
                     Errors.Keys.NullArgument_1, name), name, object);
         }
     }
getAuthority()
abstract Citation getAuthority () abstract
Returns the organization or party responsible for definition and maintenance of the database.
Referenced by DirectAuthorityFactory.getVendor(), and DirectAuthorityFactory.noSuchAuthorityCode().
getBackingStoreDescription()
String getBackingStoreDescription () throws FactoryException
Returns a description of the underlying backing store, or.
null
if unknown. This is for example the database software used for storing the data. The default implementation returns always
null
.
Returns
The description of the underlying backing store, or
null
.
Exceptions
FactoryException if a failure occurs while fetching the engine description.
{
         return null;
     }
getVendor()
Citation getVendor ()
Returns the vendor responsible for creating this factory implementation.
Many implementations from different vendors may be available for the same factory interface.
The default for Geotk implementations is to return Citations::GEOTOOLKIT Geotoolkit.org}.
Returns
The vendor for this factory implementation.
See also
Citations::GEOTOOLKIT
References DirectAuthorityFactory.getAuthority().
{
         return new SimpleCitation(getClass().getName().startsWith("org.geotoolkit.") ? "Geotk" : "Unknown");
     }
noSuchAuthorityCode()
final NoSuchAuthorityCodeException noSuchAuthorityCode (final Class<?> type, final String code) protected
Creates an exception for an unknown authority code.
This convenience method is provided for implementation of
createXXX
methods.
Parameters
type The GeoAPI interface that was to be created (e.g.
CoordinateReferenceSystem.class
).
code The unknown authority code.
Returns
An exception initialized with an error message built from the specified informations.
References Errors.format(), DirectAuthorityFactory.getAuthority(), Errors.Keys.NoSuchAuthorityCode_3, and DirectAuthorityFactory.trimAuthority().
Referenced by IGNF.createCoordinateReferenceSystem(), DirectPostgisFactory.getPrimaryKey(), and WKTParsingAuthorityFactory.getWKT().
{
         final InternationalString authority = getAuthority().getTitle();
         return new NoSuchAuthorityCodeException(Errors.format(Errors.Keys.NoSuchAuthorityCode_3,
                    code, authority, type), authority.toString(), trimAuthority(code), code);
     }
trimAuthority()
String trimAuthority (String code) protected
Trims the authority scope, if presents.
For example if this factory is an EPSG authority factory and the specified code start with the
"EPSG:"
prefix, then the prefix is removed. Otherwise, the string is returned unchanged (except for leading and trailing spaces).
Parameters
code The code to trim.
Returns
The code without the authority scope.
Referenced by IGNF.createCoordinateReferenceSystem(), and DirectAuthorityFactory.noSuchAuthorityCode().
{
         /*
          * IMPLEMENTATION NOTE: This method is overridden in PropertyAuthorityFactory. If
          * implementation below is modified, it is probably worth to revisit the overridden
          * method as well.
          */
         code = code.trim();
         final GenericName name  = nameFactory.parseGenericName(null, code);
         if (name instanceof ScopedName) {
             final GenericName scope = ((ScopedName) name).path();
             if (Citations.identifierMatches(getAuthority(), scope.toString())) {
                 return name.tip().toString().trim();
             }
         }
         return code;
     }
Member Data Documentation
factories
final ReferencingFactoryContainer factories protected
The underlying factories used for objects creation.
Referenced by IGNF.createCoordinateReferenceSystem(), and DirectAuthorityFactory.DirectAuthorityFactory().
LOGGER
final Logger LOGGER = Logging.getLogger("org.geotoolkit.referencing.factory") static
The logger for event related to Geotk factories.
Referenced by DirectPostgisFactory.getAuthorities(), PropertyAuthorityFactory.log(), and PropertyAuthorityFactory.PropertyAuthorityFactory().
nameFactory
final NameFactory nameFactory protected
The name factory to use for creating GenericName.
Since
3.00
Referenced by WKTParsingAuthorityFactory.trimAuthority().