jena-geo: SpatialRefSysMap Class Reference
SpatialRefSysMap Class Reference
A java.util.Map view over a.
Public Member Functions
SpatialRefSysMap (final Connection connection) throws SQLException
Creates a map.
String get (final Object key) throws BackingStoreException
Returns the WKT for the given code.
boolean containsKey (final Object key) throws BackingStoreException
Returns.
boolean isEmpty ()
Returns.
Set< Entry< String, String > > entrySet ()
Returns a view over the (key, wkt) pair in the database.
Package Functions
Map< String, Boolean > getAuthorityNames () throws SQLException
Returns the authority names found in the database.
Set< String > getAuthorityCodes (final Class<? extends IdentifiedObject > category) throws SQLException
Returns the authority codes defined in the database for the given type.
Integer getPrimaryKey (final String code, final String authority, final int srid) throws SQLException
Returns the primary key for the specified authority code.
void dispose () throws SQLException
Releases resources immediately instead of waiting for the garbage collector.
Package Attributes
final Connection connection
Connection to the database, or.
Private Member Functions
StringBuilder appendFrom (final StringBuilder sql)
Appends the.
Static Private Member Functions
static< T > T singleton (final PreparedStatement statement, final Class< T > type, final String code) throws SQLException
Returns the value in the specified statement.
Private Attributes
final String schema
The schema of the CRS table, or.
transient PreparedStatement selectPK
The prepared statement for fetching the primary key, or.
transient PreparedStatement select
The prepared statement for selecting an object, or.
Detailed Description
A java.util.Map view over a.
"spatial_ref_sys"
table in a PostGIS database. If a SQLException is thrown, then it is wrapped in a BackingStoreException.
Author
Martin Desruisseaux (Geomatys)
Version
3.10
Since
3.10 (derived from 2.5)
Constructor & Destructor Documentation
SpatialRefSysMap()
SpatialRefSysMap (final Connection connection) throws SQLException
Creates a map.
This constructor auto-detects the schema where the
"spatial_ref_sys"
table is declared.
Parameters
connection The connection to the database.
Exceptions
SQLException If an error occurred while fetching metadata from the database.
References SpatialRefSysMap.connection, and SpatialRefSysMap.schema.
{
         this.connection = connection;
         String schema;
         try (ResultSet result = connection.getMetaData().getTables(null, null, TABLE, new String[] {"TABLE"})) {
             schema = null;
             if (result.next()) {
                 schema = result.getString("TABLE_SCHEM");
             }
         }
         this.schema = schema;
     }
Member Function Documentation
appendFrom()
StringBuilder appendFrom (final StringBuilder sql) private
Appends the.
"FROM"
clause to the specified SQL statement.
Referenced by SpatialRefSysMap.get(), SpatialRefSysMap.getAuthorityCodes(), SpatialRefSysMap.getAuthorityNames(), and SpatialRefSysMap.getPrimaryKey().
{
         sql.append(" FROM ");
         if (schema != null) {
             sql.append(schema).append('.');
         }
         return sql.append(TABLE);
     }
containsKey()
boolean containsKey (final Object key) throws BackingStoreException
Returns.
true
if the database contains the given code.
Parameters
code The code of the CRS object to query, as an Integer.
Exceptions
BackingStoreException if an error occurred while querying the database.
{
         return get(key) != null;
     }
dispose()
void dispose () throws SQLException package
Releases resources immediately instead of waiting for the garbage collector.
{
         if (select != null) {
             select.close();
             select = null;
         }
         if (selectPK != null) {
             selectPK.close();
             selectPK = null;
         }
         connection.close();
     }
entrySet()
Set<Entry<String, String> > entrySet ()
Returns a view over the (key, wkt) pair in the database.
We do not support this operation at this stage (it is not needed by WKTParsingAuthorityFactory).
{
         throw new UnsupportedOperationException();
     }
get()
String get (final Object key) throws BackingStoreException
Returns the WKT for the given code.
Parameters
code The code of the CRS object to query, as an Integer.
Returns
The Well Known Text (WKT) for the given code, or
null
if none.
Exceptions
BackingStoreException if an error occurred while querying the database.
References SpatialRefSysMap.appendFrom(), and SpatialRefSysMap.singleton().
{
         final int srid = (Integer) key;
         try {
             if (select == null) {
                 final StringBuilder sql = new StringBuilder("SELECT ").append(WKT_COLUMN);
                 appendFrom(sql).append(" WHERE ").append(PRIMARY_KEY).append("=?");
                 select = connection.prepareStatement(sql.toString());
             }
             select.setInt(1, srid);
             return singleton(select, String.class, key.toString());
         } catch (SQLException exception) {
             throw new BackingStoreException(exception);
         }
     }
getAuthorityCodes()
Set<String> getAuthorityCodes (final Class<? extends IdentifiedObject > category) throws SQLException package
Returns the authority codes defined in the database for the given type.
Parameters
category The type of objects to search for (typically org.opengis.referencing.crs.CoordinateReferenceSystem}.class).
Returns
The set of available codes.
Exceptions
SQLException if an error occurred while querying the database.
References SpatialRefSysMap.appendFrom(), and WKTParsingAuthorityFactory.getWKTNameOf().
{
         final StringBuilder sql = new StringBuilder("SELECT CASE WHEN ")
                 .append(CODE_COLUMN).append('=').append(PRIMARY_KEY).append(" THEN ")
                 .append(PRIMARY_KEY).append("::text ELSE ").append(AUTHORITY_COLUMN)
                 .append(" || '").append(DefaultNameSpace.DEFAULT_SEPARATOR).append("' || ")
                 .append(CODE_COLUMN).append(" END AS code");
         appendFrom(sql);
         final String type = WKTParsingAuthorityFactory.getWKTNameOf(category);
         if (type != null) {
             sql.append(" WHERE srtext ILIKE '").append(type).append("%'");
         }
         sql.append(" ORDER BY ").append(PRIMARY_KEY);
         final Set<String> codes = new LinkedHashSet<>();
         try (Statement stmt = connection.createStatement();
              ResultSet results = stmt.executeQuery(sql.toString()))
         {
             while (results.next()) {
                 codes.add(results.getString(1));
             }
         }
         return codes;
     }
getAuthorityNames()
Map<String,Boolean> getAuthorityNames () throws SQLException package
Returns the authority names found in the database.
Keys are authority names, and values are whatever the authority codes match primary keys or not.
Returns
All authority names found in the database.
Exceptions
SQLException if an access to the database failed.
References SpatialRefSysMap.appendFrom().
{
         final StringBuilder sql = new StringBuilder("SELECT ").append(AUTHORITY_COLUMN)
                 .append(", SUM(CASE WHEN ").append(CODE_COLUMN).append('=').append(PRIMARY_KEY)
                 .append(" THEN 1 ELSE 0 END) AS np, COUNT(").append(AUTHORITY_COLUMN).append(") AS n");
         appendFrom(sql)
                 .append(" GROUP BY ").append(AUTHORITY_COLUMN)
                 .append(" ORDER BY np DESC, n DESC");
         final Map<String,Boolean> authorities = new LinkedHashMap<>();
         try (Statement stmt = connection.createStatement();
              ResultSet results = stmt.executeQuery(sql.toString()))
         {
             while (results.next()) {
                 final String name = results.getString(1); // May be null.
                 final int    np   = results.getInt   (2);
                 final int    n    = results.getInt   (3);
                 authorities.put(name, np == n);
             }
         }
         return authorities;
     }
getPrimaryKey()
Integer getPrimaryKey (final String code, final String authority, final int srid) throws SQLException package
Returns the primary key for the specified authority code.
This method searches for a row with the given authority in the <cite>authority name</cite> column and the given integer code in the <cite>authority SRID</cite> column. If such row is found, the value of its <cite>SRID</cite> column is returned. Otherwise this method returns
null
.
Parameters
code The authority code, for formatting an error message if needed.
authority The authority part of the above code.
srid The integer code part of the above code.
Returns
The primary key for the supplied code, or
null
if it has not been found.
Exceptions
SQLException if an error occurred while querying the database.
References SpatialRefSysMap.appendFrom(), and SpatialRefSysMap.singleton().
{
         if (selectPK == null) {
             final StringBuilder sql = new StringBuilder("SELECT ").append(PRIMARY_KEY);
             appendFrom(sql).append(" WHERE ").append(AUTHORITY_COLUMN).append("=?")
                     .append(" AND ").append(CODE_COLUMN).append("=?");
             selectPK = connection.prepareStatement(sql.toString());
         }
         selectPK.setString(1, authority);
         selectPK.setInt   (2, srid);
         return singleton(selectPK, Integer.class, code);
     }
isEmpty()
boolean isEmpty ()
Returns.
false
in all cases. This is a violation of the Map contract, but we do that because this method is invoked by WKTParsingAuthorityFactory#availability() and we want to avoid querying the database at this stage.
{
         return false;
     }
singleton()
static <T> T singleton (final PreparedStatement statement, final Class< T > type, final String code) throws SQLException static private
Returns the value in the specified statement.
This method ensures that the result set contains only one value.
Parameters
statement The statement to execute.
type The type of the value to fetch.
code The authority code, for formatting an error message if needed.
Returns
The singleton value found, or
null
if none.
Exceptions
SQLException if an error occurred while querying the database.
References Errors.Keys.DuplicatedValuesForKey_1, and Errors.format().
Referenced by SpatialRefSysMap.get(), and SpatialRefSysMap.getPrimaryKey().
     {
         T value = null;
         try (ResultSet results = statement.executeQuery()) {
             while (results.next()) {
                 final Object candidate;
                 if (Integer.class.isAssignableFrom(type)) {
                     candidate = results.getInt(1);
                 } else {
                     candidate = results.getString(1);
                 }
                 if (!results.wasNull()) {
                     if (value != null && !candidate.equals(value)) {
                         throw new SQLIntegrityConstraintViolationException(
                                 Errors.format(Errors.Keys.DuplicatedValuesForKey_1, code));
                     }
                     value = type.cast(candidate);
                 }
             }
         }
         return value;
     }
Member Data Documentation
connection
final Connection connection package
Connection to the database, or.
null
if none.
Referenced by SpatialRefSysMap.SpatialRefSysMap().
schema
final String schema private
The schema of the CRS table, or.
null
if none.
Referenced by SpatialRefSysMap.SpatialRefSysMap().
select
transient PreparedStatement select private
The prepared statement for selecting an object, or.
null
if not yet created.
selectPK
transient PreparedStatement selectPK private
The prepared statement for fetching the primary key, or.
null
if not yet created.