jena-geo: LambertAzimuthalEqualArea.Spherical Class Reference
LambertAzimuthalEqualArea.Spherical Class Reference
Provides the transform equations for the spherical case.
Public Member Functions
Matrix transform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
ParameterDescriptorGroup getParameterDescriptors ()
Returns the parameter descriptors for this unitary projection.
boolean equals (final Object object, final ComparisonMode mode)
Compares the given object with this transform for equivalence.
Static Public Member Functions
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values)
Creates an Albers Equal Area projection from the given parameters.
Protected Member Functions
Spherical (final OperationMethod method, final Parameters parameters)
Constructs a new map projection from the supplied parameters.
void inverseTransform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff) throws ProjectionException
Package Functions
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor)
final double msfn (final double sinφ, final double cosφ)
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
final double ssfn (double φ, double sinφ)
Computes part of function (3-1) from Snyder.
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ)
Computes the derivative of the ssfn(double, double) method divided by.
final double qsfn (final double sinφ)
Calculates q, Snyder equation (3-12).
final double dqsfn_dφ (final double sinφ, final double cosφ)
Gets the derivative of the qsfn(double) method.
Static Package Functions
static boolean isSpherical (final Parameters parameters)
Package Attributes
final boolean pole
final boolean north
If.
final boolean oblique
If.
final double latitudeOfOrigin
Latitude of origin, in radians.
final double sinb1
Parameters derived from the latitude of origin and the eccentricity.
final double cosb1
final double qp
Constant parameters.
final double rq
final double APA1
final double APA2
Static Package Attributes
static final double P01 = 0.17222222222222222222
static final double P02 = 0.10257936507936507936
static final double P10 = 0.06388888888888888888
static final double P11 = 0.06640211640211640211
static final double P20 = 0.01641501294219154443
static final double ANGLE_TOLERANCE = 1E-6
Maximum difference allowed when comparing longitudes or latitudes in radians.
static final double ITERATION_TOLERANCE = 1E-10
Difference allowed in iterative computations.
static final int MAXIMUM_ITERATIONS = 15
Maximum number of iterations for iterative computations.
Private Member Functions
boolean checkInverseTransform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff, final double λ, final double φ) throws ProjectionException
Computes using ellipsoidal formulas and compare with the result from spherical formulas.
Static Private Attributes
static final long serialVersionUID = 2091431369806844342L
For cross-version compatibility.
Detailed Description
Provides the transform equations for the spherical case.
Author
Gerald Evenden (USGS)
Beate Stollberg
Martin Desruisseaux (IRD, Geomatys)
Version
3.00
Since
2.4
Constructor & Destructor Documentation
Spherical()
Spherical (final OperationMethod method, final Parameters parameters) protected
Constructs a new map projection from the supplied parameters.
Parameters
parameters The parameters of the projection to be created.
{
             super(method, parameters);
         }
Member Function Documentation
checkInverseTransform()
boolean checkInverseTransform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff, final double λ, final double φ) throws ProjectionException private
Computes using ellipsoidal formulas and compare with the result from spherical formulas.
Used in assertions only.
References Assertions.checkInverseTransform().
Referenced by LambertAzimuthalEqualArea.Spherical.inverseTransform().
         {
             super.inverseTransform(srcPts, srcOff, dstPts, dstOff);
             return Assertions.checkInverseTransform(dstPts, dstOff, λ, φ);
         }
create()
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values) static inherited
Creates an Albers Equal Area projection from the given parameters.
The descriptor argument is usually org.geotoolkit.referencing.operation.provider.LambertAzimuthalEqualArea#PARAMETERS, but is not restricted to. If a different descriptor is supplied, it is user's responsibility to ensure that it is suitable to a Lambert Azimuthal Equal Area projection.
Parameters
descriptor Typically
LambertAzimuthalEqualArea.PARAMETERS
.
values The parameter values of the projection to create.
Returns
The map projection.
Since
3.00
References UnitaryProjection.isSpherical(), and LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
Referenced by LambertAzimuthalEqualArea.createMathTransform().
     {
         final Parameters parameters = Parameters.castOrWrap(values);
         final LambertAzimuthalEqualArea projection;
         if (isSpherical(parameters)) {
             projection = new Spherical(descriptor, parameters);
         } else {
             projection = new LambertAzimuthalEqualArea(descriptor, parameters);
         }
         try {
             return (MathTransform2D) projection.createMapProjection(
                     org.apache.sis.internal.system.DefaultFactories.forBuildin(
                             org.opengis.referencing.operation.MathTransformFactory.class));
         } catch (org.opengis.util.FactoryException e) {
             throw new IllegalArgumentException(e); // TODO
         }
     }
dqsfn_dφ()
final double dqsfn_dφ (final double sinφ, final double cosφ) package inherited
Gets the derivative of the qsfn(double) method.
Parameters
sinφ The sine of latitude.
cosφ The cosines of latitude.
Returns
The
qsfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by LambertAzimuthalEqualArea.transform().
{
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         double esinφ2 = eccentricity * sinφ;
         esinφ2 *= esinφ2;
         return (1 - eccentricitySquared) * (cosφ / (1 - esinφ2)) * (1 + ((1 + esinφ2) / (1 - esinφ2)));
     }
dssfn_dφ()
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ) package inherited
Computes the derivative of the ssfn(double, double) method divided by.
ssfn
. Callers must multiply the return value by
ssfn
in order to get the actual value.
Parameters
φ The latitude.
sinφ the sine of latitude.
cosφ The cosine of latitude.
Returns
The
dssfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         assert !(abs(cosφ - cos(φ)) > ARGUMENT_TOLERANCE) : φ;
         return (1/cosφ) - (eccentricitySquared*cosφ)/(1-eccentricitySquared*sinφ*sinφ);
         /*
          * NOTE: 0.5*(t + 1/t)   =   1/cosφ
          */
     }
equals()
boolean equals (final Object object, final ComparisonMode mode) inherited
Compares the given object with this transform for equivalence.
References LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.latitudeOfOrigin.
{
         if (super.equals(object, mode)) {
             final LambertAzimuthalEqualArea that = (LambertAzimuthalEqualArea) object;
             return epsilonEqual(this.latitudeOfOrigin, that.latitudeOfOrigin, mode);
             // All other coefficients are derived from the latitude of origin and eccentricity.
         }
         return false;
     }
getAndStore()
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor) package inherited
Referenced by CassiniOrMercator.CassiniOrMercator(), Krovak.Krovak(), LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), NewZealandMapGrid.NewZealandMapGrid(), Orthographic.Orthographic(), and Stereographic.Stereographic().
{
         final double value = parameters.doubleValue(descriptor);    // Apply a unit conversion if needed.
         final Double defaultValue = descriptor.getDefaultValue();
         if (defaultValue == null || !defaultValue.equals(value)) {
             org.apache.sis.internal.referencing.provider.MapProjection.validate(descriptor, value);
             String name = IdentifiedObjects.getName(descriptor, parameters.getDescriptor().getName().getAuthority());
             if (name == null) {
                 name = descriptor.getName().getCode();
             }
             getContextualParameters().parameter(name).setValue(value);
         }
         return value;
     }
getParameterDescriptors()
ParameterDescriptorGroup getParameterDescriptors () inherited
Returns the parameter descriptors for this unitary projection.
Note that the returned descriptor is about the unitary projection, not the full one.
References LambertAzimuthalEqualArea.PARAMETERS.
{
         return org.geotoolkit.referencing.operation.provider.LambertAzimuthalEqualArea.PARAMETERS;
     }
inverseTransform()
void inverseTransform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff) throws ProjectionException protected
References LambertAzimuthalEqualArea.Spherical.checkInverseTransform(), LambertAzimuthalEqualArea.latitudeOfOrigin, and LambertAzimuthalEqualArea.sinb1.
         {
             double x = srcPts[srcOff  ];
             double y = srcPts[srcOff+1];
             double λ, φ;
             final double ρ = hypot(x, y);
             φ = 2.0 * asin(0.5 * ρ);
             if (pole) {
                 /*
                  * Reminder in the North case:
                  *   - Before this block, sign of y has been reverted by the affine transform.
                  *   - After this block, sign of φ will be reverted by the affine transform.
                  */
                 φ -= (PI / 2);
                 λ = atan2(x, y);
             } else {
                 final double sinz = sin(φ);
                 final double cosz = cos(φ);
                 if (!oblique) {
                     φ = abs(ρ) <= EPSILON ? 0 : asin(y * sinz / ρ);
                     y = ρ * cosz;
                 } else {
                     y *= sinz;
                     φ = abs(ρ) <= EPSILON ? latitudeOfOrigin : asin(cosz*sinb1 + y*cosb1/ρ);
                     y = ρ*cosz*cosb1 - y*sinb1;
                 }
                 x *= sinz;
                 λ = atan2(x, y);
             }
             assert checkInverseTransform(srcPts, srcOff, dstPts, dstOff, λ, φ);
             dstPts[dstOff  ] = λ;
             dstPts[dstOff+1] = φ;
         }
isSpherical()
static boolean isSpherical (final Parameters parameters) static package inherited
References UnitaryProjection.inverseTransform().
Referenced by CassiniSoldner.create(), Stereographic.create(), LambertAzimuthalEqualArea.create(), and LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
{
         return parameters.parameter("semi_major").doubleValue() == parameters.parameter("semi_minor").doubleValue();
     }
msfn()
final double msfn (final double sinφ, final double cosφ) package inherited
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
Special cases:
If φ is 0°, then this method returns 1.
If φ is ±90°, then this method returns 0 provided that we are not in the spherical case (otherwise we get Double#NaN).
Parameters
sinφ The sine of the φ latitude in radians.
cosφ The cosine of the φ latitude in radians.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic().
                                                               {               // == cosφ / rν(sinφ)
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         return cosφ / sqrt(1.0 - (sinφ*sinφ) * eccentricitySquared);
     }
qsfn()
final double qsfn (final double sinφ) package inherited
Calculates q, Snyder equation (3-12).
This equation has the following properties:
Input in the [-1 ... +1] range.
Output in the [-2 ... +2] range.
Output is 0 when input is 0.
Output of the same sign than input.
qsfn(-sinφ) == -qsfn(sinφ)
.
Parameters
sinφ Sine of the latitude q is calculated for.
Returns
q from Snyder equation (3-12).
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.transform().
{
         if (eccentricity < EPSILON) {
             return 2 * sinφ;
         }
         /*
          * Above check was required because the expression below would simplify to
          * sinφ - 0.5/0*log(1) where the right terms are infinity multiplied by
          * zero, thus producing NaN.
          */
         final double esinφ = eccentricity * sinφ;
         return (1 - eccentricitySquared) * (sinφ / (1 - esinφ*esinφ) + atanh(esinφ)/eccentricity);
     }
ssfn()
final double ssfn (double φ, double sinφ) package inherited
Computes part of function (3-1) from Snyder.
This is numerically equivalent to #tsfn tsfn}(-φ, sinφ), but is defined as a separated function for clarity and because the function properties are not the same.
Parameters
φ The latitude in radians.
sinφ The sine of the φ argument. This is provided explicitly because in many cases, the caller has already computed this value.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic(), EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         sinφ *= eccentricity;
         return tan(PI/4 + 0.5*φ) * pow((1-sinφ) / (1+sinφ), 0.5*eccentricity);
     }
transform()
Matrix transform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
References Assertions.checkDerivative(), Assertions.checkTransform(), and LambertAzimuthalEqualArea.EPSILON.
         {
             final double λ    = srcPts[srcOff];
             final double φ    = srcPts[srcOff + 1];
             final double sinλ = sin(λ);
             final double cosλ = cos(λ);
             double x,y;
             if (!pole) {
                 final double sinφ = sin(φ);
                 final double cosφ = cos(φ);
                 /*
                  * 'x' (actually not really x before the end of this block,  but rather an
                  * intermediate scale coefficient elsewhere called 'k') is checked against
                  * zero as a safety and because Proj4 does that way.  The formulas already
                  * leads naturally to NaN in Java because division by 0 produces infinity,
                  * and the following multiplication by zero (x == 0 implies sinφ == 0 at
                  * least in the equatorial case) would produce NaN. But the explicit check
                  * makes sure that we set both coordinates to NaN.
                  */
                 if (!oblique) {
                     x = 1.0 + cosφ * cosλ;
                     if (x >= EPSILON) {
                         x = sqrt(2.0 / x);
                         y = x * sinφ;
                     } else {
                         x = y = NaN;
                     }
                 } else {
                     y = cosφ * cosλ;
                     x = 1.0 + sinb1 * sinφ + cosb1 * y;
                     if (x >= EPSILON) {
                         x = sqrt(2.0 / x);
                         y = x * (cosb1 * sinφ - sinb1 * y);
                     } else {
                         x = y = NaN;
                     }
                 }
                 x *= cosφ * sinλ;
             } else if (abs(φ - PI/2) >= EPSILON) {
                 /*
                  * Polar projection (North and South cases).
                  * Reminder: in the North case, the sign of φ is reversed before this block
                  * and the sign of y will be reversed after this block by the affine transforms.
                  */
                 y = 2 * cos(PI/4 - 0.5*φ);
                 x = y * sinλ;
                 y *= cosλ;
             } else {
                 /*
                  * Attempt to project the opposite pole. Actually the above formula would works
                  * and returns an acceptable answer, but every points on a circle of radius 2
                  * would fit. Proj4 was returning an error code; in Geotk we said that no
                  * single point is the answer.
                  */
                 x = y = NaN;
             }
             Matrix derivative = null;
             if (derivate) {
                 final double m00, m01, m10, m11;
                 if (pole) {
                     final double U = 2 * cos(PI/4 - 0.5*φ);
                     final double dU_dφ = sin(PI/4 - 0.5*φ);
                     m00 =  cosλ * U;
                     m10 = -sinλ * U;
                     m01 =  sinλ * dU_dφ;
                     m11 =  cosλ * dU_dφ;
                 } else {
                     final double sinφ = sin(φ);
                     final double cosφ = cos(φ);
                     final double cosφcosλ = cosφ * cosλ;
                     final double cosφsinλ = cosφ * sinλ;
                     final double sinφcosλ = sinφ * cosλ;
                     double b = 1 + sinb1*sinφ + cosb1*cosφcosλ;
                     final double S = sqrt(2 / b);
                     b *= b*S;
                     final double dS_dλ = (cosb1*cosφsinλ) / b;
                     final double dS_dφ = (cosb1*sinφcosλ - sinb1*cosφ) / b;
                     m00 = dS_dλ * cosφsinλ + cosφcosλ*S;
                     m01 = dS_dφ * cosφsinλ - sinφ*sinλ*S;
                     m10 = cosb1 *  dS_dλ*sinφ           - sinb1*(dS_dλ*cosφcosλ - cosφsinλ*S);
                     m11 = cosb1 * (dS_dφ*sinφ + cosφ*S) - sinb1*(dS_dφ*cosφcosλ - sinφcosλ*S);
                 }
                 derivative = new Matrix2(m00, m01, m10, m11);
             }
             // Following part is common to all spherical projections: verify, store and return.
             assert Assertions.checkDerivative(derivative, super.transform(srcPts, srcOff, dstPts, dstOff, derivate))
                 && Assertions.checkTransform(dstPts, dstOff, x, y); // dstPts = result from ellipsoidal formulas.
             if (dstPts != null) {
                 dstPts[dstOff  ] = x;
                 dstPts[dstOff+1] = y;
             }
             return derivative;
         }
Member Data Documentation
ANGLE_TOLERANCE
final double ANGLE_TOLERANCE = 1E-6 static package inherited
Maximum difference allowed when comparing longitudes or latitudes in radians.
A tolerance of 1E-6 is about 0.2 second of arcs, which is about 6 kilometers (computed from the standard length of nautical mile).
Some formulas use this tolerance value for testing sinus or cosinus of an angle. In the sinus case, this is justified because sin(θ) ≅ θ when θ is small. Similar reasoning applies to cosinus with cos(θ) ≅ θ + π/2 when θ is small.
Referenced by Stereographic.create(), Orthographic.inverseTransform(), LambertAzimuthalEqualArea.inverseTransform(), Orthographic.Orthographic(), and Stereographic.Stereographic().
APA1
final double APA1 package inherited
APA2
final double APA2 package inherited
cosb1
final double cosb1 package inherited
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.transform().
ITERATION_TOLERANCE
final double ITERATION_TOLERANCE = 1E-10 static package inherited
Difference allowed in iterative computations.
A value of 1E-10 causes the cphi2 function to compute the latitude at a precision of 1E-10 radians, which is slightly smaller than one millimetre.
Referenced by CassiniOrMercator.inv_mlfn(), and Stereographic.inverseTransform().
latitudeOfOrigin
final double latitudeOfOrigin package inherited
Latitude of origin, in radians.
Referenced by LambertAzimuthalEqualArea.equals(), LambertAzimuthalEqualArea.inverseTransform(), and LambertAzimuthalEqualArea.Spherical.inverseTransform().
MAXIMUM_ITERATIONS
final int MAXIMUM_ITERATIONS = 15 static package inherited
Maximum number of iterations for iterative computations.
Referenced by CassiniOrMercator.inv_mlfn(), Stereographic.inverseTransform(), and Krovak.inverseTransform().
north
final boolean north package inherited
If.
pole
is
true
, then this field
true
is true for the North pole and
false
for the South pole.
oblique
final boolean oblique package inherited
If.
pole
is
false
, then this field
true
is true for the oblique case and
false
for the equatorial case.
P01
final double P01 = 0.17222222222222222222 static package inherited
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
P02
final double P02 = 0.10257936507936507936 static package inherited
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
P10
final double P10 = 0.06388888888888888888 static package inherited
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
P11
final double P11 = 0.06640211640211640211 static package inherited
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
P20
final double P20 = 0.01641501294219154443 static package inherited
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
pole
final boolean pole package inherited
true
if the projection is at a pole.
qp
final double qp package inherited
Constant parameters.
They depend only on the eccentricity, not on the latitude of origin. Consequently they are not used in the spherical case.
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.transform().
rq
final double rq package inherited
Referenced by LambertAzimuthalEqualArea.inverseTransform().
serialVersionUID
final long serialVersionUID = 2091431369806844342L static private
For cross-version compatibility.
sinb1
final double sinb1 package inherited
Parameters derived from the latitude of origin and the eccentricity.
In the spherical case, they are straight sinus and cosinus of the latitude of origin.
Referenced by LambertAzimuthalEqualArea.Spherical.inverseTransform(), and LambertAzimuthalEqualArea.transform().