jena-geo: CassiniOrMercator Class Reference
CassiniOrMercator Class Reference abstract
The base class for Cassini-Solder and Transverse Mercator projections.
Protected Member Functions
abstract void inverseTransform (double[] srcPts, int srcOff, double[] dstPts, int dstOff) throws ProjectionException
Package Functions
CassiniOrMercator (final OperationMethod method, final Parameters parameters)
Constructs a new map projection from the supplied parameters.
final double mlfn (final double φ, double sinφ, double cosφ)
Calculates the meridian distance.
final double dmlfn_dφ (final double sinφ2, final double cosφ2)
Gets the derivative of this mlfn(double, double, double) method.
final double inv_mlfn (final double delta) throws ProjectionException
Calculates the latitude (.
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor)
final double msfn (final double sinφ, final double cosφ)
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
final double ssfn (double φ, double sinφ)
Computes part of function (3-1) from Snyder.
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ)
Computes the derivative of the ssfn(double, double) method divided by.
final double qsfn (final double sinφ)
Calculates q, Snyder equation (3-12).
final double dqsfn_dφ (final double sinφ, final double cosφ)
Gets the derivative of the qsfn(double) method.
Static Package Functions
static boolean isSpherical (final Parameters parameters)
Package Attributes
final double en1
final double en2
final double en3
final double en4
Static Package Attributes
static final double ASSERTION_DOMAIN = 5 * (PI/180)
Maximal difference (in radians) from central meridian for enabling assertions.
static final double C02 = 0.25
static final double C04 = 0.046875
static final double C06 = 0.01953125
static final double C08 = 0.01068115234375
static final double C22 = 0.75
static final double C44 = 0.46875
static final double C46 = 0.01302083333333333333
static final double C48 = 0.00712076822916666666
static final double C66 = 0.36458333333333333333
static final double C68 = 0.00569661458333333333
static final double C88 = 0.3076171875
static final double ANGLE_TOLERANCE = 1E-6
Maximum difference allowed when comparing longitudes or latitudes in radians.
static final double ITERATION_TOLERANCE = 1E-10
Difference allowed in iterative computations.
static final int MAXIMUM_ITERATIONS = 15
Maximum number of iterations for iterative computations.
static final double EPSILON = 1E-7
Maximum difference allowed when comparing real numbers (other cases).
Private Attributes
final double en0
Constant needed for the mlfn method.
Static Private Attributes
static final long serialVersionUID = -8816056150503228733L
For cross-version compatibility.
static final double C00 = 1.0
Constants used to calculate en0, en1, en2, en3, en4.
Detailed Description
The base class for Cassini-Solder and Transverse Mercator projections.
Author
Gerald Evenden (USGS)
André Gosselin (MPO)
Martin Desruisseaux (MPO, IRD, Geomatys)
Rueben Schulz (UBC)
Rémi Maréchal (Geomatys)
Since
3.00
Deprecated:
Replaced by org.apache.sis.referencing.operation.projection.MeridionalDistanceBased.
Constructor & Destructor Documentation
CassiniOrMercator()
CassiniOrMercator (final OperationMethod method, final Parameters parameters) package
Constructs a new map projection from the supplied parameters.
Parameters
parameters The parameters of the projection to be created.
References CassiniOrMercator.C00, CassiniOrMercator.C02, CassiniOrMercator.C04, CassiniOrMercator.C06, CassiniOrMercator.C08, CassiniOrMercator.C22, CassiniOrMercator.C44, CassiniOrMercator.C46, CassiniOrMercator.C48, CassiniOrMercator.C66, CassiniOrMercator.C68, CassiniOrMercator.C88, UnitaryProjection.getAndStore(), and CassiniOrMercator.mlfn().
{
         super(method, parameters, null);
         final double eccentricitySquared = this.eccentricitySquared;
         double t;
         en0 = C00 - eccentricitySquared  * (C02 + eccentricitySquared  *
              (C04 + eccentricitySquared  * (C06 + eccentricitySquared  * C08)));
         en1 =       eccentricitySquared  * (C22 - eccentricitySquared  *
              (C04 + eccentricitySquared  * (C06 + eccentricitySquared  * C08)));
         en2 =  (t = eccentricitySquared  *        eccentricitySquared) *
              (C44 - eccentricitySquared  * (C46 + eccentricitySquared  * C48));
         en3 = (t *= eccentricitySquared) * (C66 - eccentricitySquared  * C68);
         en4 =  t *  eccentricitySquared  *  C88;
         final double latitudeOfOrigin = toRadians(getAndStore(parameters, org.apache.sis.internal.referencing.provider.TransverseMercator.LATITUDE_OF_ORIGIN));
         final double ml0;
         if (eccentricitySquared != 0) {
             ml0 = mlfn(latitudeOfOrigin, sin(latitudeOfOrigin), cos(latitudeOfOrigin));
         } else {
             // Above equation simplifies to the latitude of origin in the spherical case.
             ml0 = latitudeOfOrigin;
         }
         /*
          * At this point, all parameters have been processed. Now process to their
          * validation and the initialization of (de)normalize affine transforms.
          *
          * Note that in the South Orientated case, the meaning of False Easting (FE) and
          * False Northing (FN) are reversed: they are effectively False Westing and False
          * Southing. This is the opposite of what we would expect from the parameter names,
          * but is documented that way in the EPSG database. In other words while the usual
          * Transverse Mercator formulas are:
          *
          *     easting   =  FE + px
          *     northing  =  FN + py
          *
          * the Transverse Mercator South Orientated Projection formulas are:
          *
          *     westing   =  (pseudo FE) - px  =  -FE - px  =  -easting
          *     southing  =  (pseudo FN) - py  =  -FN - py  =  -northing
          *
          * Where the px and py terms are the same in both cases. Because of the sign reversal
          * of FE and FN (despite their names) there is actually nothing special to do in this
          * method for the South Orientated case.
          */
         final MatrixSIS denormalize = getContextualParameters().getMatrix(MatrixRole.DENORMALIZATION);
         denormalize.convertBefore(1, null, -ml0);
     }
Member Function Documentation
dmlfn_dφ()
final double dmlfn_dφ (final double sinφ2, final double cosφ2) package
Gets the derivative of this mlfn(double, double, double) method.
Returns
The derivative at the specified latitude.
Referenced by CassiniSoldner.transform().
{
         return en0 +
                en1 * (sinφ2 -   cosφ2) + sinφ2*(
                en2 * (sinφ2 - 3*cosφ2) + sinφ2*(
                en3 * (sinφ2 - 5*cosφ2) + sinφ2*
                en4 * (    1 - 7*cosφ2)));
     }
dqsfn_dφ()
final double dqsfn_dφ (final double sinφ, final double cosφ) package inherited
Gets the derivative of the qsfn(double) method.
Parameters
sinφ The sine of latitude.
cosφ The cosines of latitude.
Returns
The
qsfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by LambertAzimuthalEqualArea.transform().
{
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         double esinφ2 = eccentricity * sinφ;
         esinφ2 *= esinφ2;
         return (1 - eccentricitySquared) * (cosφ / (1 - esinφ2)) * (1 + ((1 + esinφ2) / (1 - esinφ2)));
     }
dssfn_dφ()
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ) package inherited
Computes the derivative of the ssfn(double, double) method divided by.
ssfn
. Callers must multiply the return value by
ssfn
in order to get the actual value.
Parameters
φ The latitude.
sinφ the sine of latitude.
cosφ The cosine of latitude.
Returns
The
dssfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         assert !(abs(cosφ - cos(φ)) > ARGUMENT_TOLERANCE) : φ;
         return (1/cosφ) - (eccentricitySquared*cosφ)/(1-eccentricitySquared*sinφ*sinφ);
         /*
          * NOTE: 0.5*(t + 1/t)   =   1/cosφ
          */
     }
getAndStore()
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor) package inherited
Referenced by CassiniOrMercator.CassiniOrMercator(), Krovak.Krovak(), LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), NewZealandMapGrid.NewZealandMapGrid(), Orthographic.Orthographic(), and Stereographic.Stereographic().
{
         final double value = parameters.doubleValue(descriptor);    // Apply a unit conversion if needed.
         final Double defaultValue = descriptor.getDefaultValue();
         if (defaultValue == null || !defaultValue.equals(value)) {
             org.apache.sis.internal.referencing.provider.MapProjection.validate(descriptor, value);
             String name = IdentifiedObjects.getName(descriptor, parameters.getDescriptor().getName().getAuthority());
             if (name == null) {
                 name = descriptor.getName().getCode();
             }
             getContextualParameters().parameter(name).setValue(value);
         }
         return value;
     }
inv_mlfn()
final double inv_mlfn (final double delta) throws ProjectionException package
Calculates the latitude (.
φ
) from a meridian distance. Determines φ to a tenth of { ITERATION_TOLERANCE} radians.
Parameters
delta meridian distance to calculate latitude for.
Returns
The latitude of the meridian distance.
Exceptions
ProjectionException if the iteration does not converge.
References Errors.format(), UnitaryProjection.ITERATION_TOLERANCE, UnitaryProjection.MAXIMUM_ITERATIONS, CassiniOrMercator.mlfn(), and Errors.Keys.NoConvergence.
Referenced by CassiniSoldner.inverseTransform().
{
         final double k = 1/(1 - eccentricitySquared);
         double φ = delta;
         int i=MAXIMUM_ITERATIONS;
         do { // rarely goes over 5 iterations
             final double s = sin(φ);
             double t = 1 - eccentricitySquared * (s*s);
             t = (mlfn(φ, s, cos(φ)) - delta) * (t * sqrt(t)) * k;
             φ -= t;
             if (abs(t) < ITERATION_TOLERANCE/10) {
                 return φ;
             }
         } while (--i >= 0);
         throw new ProjectionException(Errors.format(Errors.Keys.NoConvergence));
     }
inverseTransform()
abstract void inverseTransform (double [] srcPts, int srcOff, double [] dstPts, int dstOff) throws ProjectionException abstract protected inherited
Referenced by UnitaryProjection.isSpherical().
isSpherical()
static boolean isSpherical (final Parameters parameters) static package inherited
References UnitaryProjection.inverseTransform().
Referenced by CassiniSoldner.create(), Stereographic.create(), LambertAzimuthalEqualArea.create(), and LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
{
         return parameters.parameter("semi_major").doubleValue() == parameters.parameter("semi_minor").doubleValue();
     }
mlfn()
final double mlfn (final double φ, double sinφ, double cosφ) package
Calculates the meridian distance.
This is the distance along the central meridian from the equator to
φ
. Accurate to < 1E-5 metres when used in conjuction with typical major axis values.
Special cases:
If φ is 0°, then this method returns 0.
Parameters
φ latitude to calculate meridian distance for.
sinφ sin(φ).
cosφ cos(φ).
Returns
Meridian distance for the given latitude.
References CassiniOrMercator.en4.
Referenced by CassiniOrMercator.CassiniOrMercator(), CassiniOrMercator.inv_mlfn(), and CassiniSoldner.transform().
{
         cosφ *= sinφ;
         sinφ *= sinφ;
         return en0*φ - cosφ*(en1 + sinφ*(en2 + sinφ*(en3 + sinφ*en4)));
     }
msfn()
final double msfn (final double sinφ, final double cosφ) package inherited
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
Special cases:
If φ is 0°, then this method returns 1.
If φ is ±90°, then this method returns 0 provided that we are not in the spherical case (otherwise we get Double#NaN).
Parameters
sinφ The sine of the φ latitude in radians.
cosφ The cosine of the φ latitude in radians.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic().
                                                               {               // == cosφ / rν(sinφ)
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         return cosφ / sqrt(1.0 - (sinφ*sinφ) * eccentricitySquared);
     }
qsfn()
final double qsfn (final double sinφ) package inherited
Calculates q, Snyder equation (3-12).
This equation has the following properties:
Input in the [-1 ... +1] range.
Output in the [-2 ... +2] range.
Output is 0 when input is 0.
Output of the same sign than input.
qsfn(-sinφ) == -qsfn(sinφ)
.
Parameters
sinφ Sine of the latitude q is calculated for.
Returns
q from Snyder equation (3-12).
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.transform().
{
         if (eccentricity < EPSILON) {
             return 2 * sinφ;
         }
         /*
          * Above check was required because the expression below would simplify to
          * sinφ - 0.5/0*log(1) where the right terms are infinity multiplied by
          * zero, thus producing NaN.
          */
         final double esinφ = eccentricity * sinφ;
         return (1 - eccentricitySquared) * (sinφ / (1 - esinφ*esinφ) + atanh(esinφ)/eccentricity);
     }
ssfn()
final double ssfn (double φ, double sinφ) package inherited
Computes part of function (3-1) from Snyder.
This is numerically equivalent to #tsfn tsfn}(-φ, sinφ), but is defined as a separated function for clarity and because the function properties are not the same.
Parameters
φ The latitude in radians.
sinφ The sine of the φ argument. This is provided explicitly because in many cases, the caller has already computed this value.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic(), EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         sinφ *= eccentricity;
         return tan(PI/4 + 0.5*φ) * pow((1-sinφ) / (1+sinφ), 0.5*eccentricity);
     }
Member Data Documentation
ANGLE_TOLERANCE
final double ANGLE_TOLERANCE = 1E-6 static package inherited
Maximum difference allowed when comparing longitudes or latitudes in radians.
A tolerance of 1E-6 is about 0.2 second of arcs, which is about 6 kilometers (computed from the standard length of nautical mile).
Some formulas use this tolerance value for testing sinus or cosinus of an angle. In the sinus case, this is justified because sin(θ) ≅ θ when θ is small. Similar reasoning applies to cosinus with cos(θ) ≅ θ + π/2 when θ is small.
Referenced by Stereographic.create(), Orthographic.inverseTransform(), LambertAzimuthalEqualArea.inverseTransform(), Orthographic.Orthographic(), and Stereographic.Stereographic().
ASSERTION_DOMAIN
final double ASSERTION_DOMAIN = 5 * (PI/180) static package
Maximal difference (in radians) from central meridian for enabling assertions.
When assertions are enabled, projections using spherical formulas are followed by projections using the ellipsoidal formulas, and the results are compared. If a distance greater than the tolerance level is found, then an AssertionError will be thrown.
Referenced by CassiniSoldner.Spherical.checkInverseTransform().
C00
final double C00 = 1.0 static private
Constants used to calculate en0, en1, en2, en3, en4.
Referenced by CassiniOrMercator.CassiniOrMercator().
C02
final double C02 = 0.25 static package
Referenced by CassiniOrMercator.CassiniOrMercator().
C04
final double C04 = 0.046875 static package
Referenced by CassiniOrMercator.CassiniOrMercator().
C06
final double C06 = 0.01953125 static package
Referenced by CassiniOrMercator.CassiniOrMercator().
C08
final double C08 = 0.01068115234375 static package
Referenced by CassiniOrMercator.CassiniOrMercator().
C22
final double C22 = 0.75 static package
Referenced by CassiniOrMercator.CassiniOrMercator().
C44
final double C44 = 0.46875 static package
Referenced by CassiniOrMercator.CassiniOrMercator().
C46
final double C46 = 0.01302083333333333333 static package
Referenced by CassiniOrMercator.CassiniOrMercator().
C48
final double C48 = 0.00712076822916666666 static package
Referenced by CassiniOrMercator.CassiniOrMercator().
C66
final double C66 = 0.36458333333333333333 static package
Referenced by CassiniOrMercator.CassiniOrMercator().
C68
final double C68 = 0.00569661458333333333 static package
Referenced by CassiniOrMercator.CassiniOrMercator().
C88
final double C88 = 0.3076171875 static package
Referenced by CassiniOrMercator.CassiniOrMercator().
en0
final double en0 private
Constant needed for the mlfn method.
Setup at construction time.
en1
final double en1 package
en2
final double en2 package
Referenced by CassiniSoldner.transform().
en3
final double en3 package
en4
final double en4 package
Referenced by CassiniOrMercator.mlfn().
EPSILON
final double EPSILON = 1E-7 static package inherited
Maximum difference allowed when comparing real numbers (other cases).
The value defined here is consistent with the one that was used in LambertAzimuthalEqualArea for the same purpose (not to be confused with the current
EPSILON
constant defined in the above-mentioned class, which has been renamed), and the modified value used in AlbersEqualArea.
ITERATION_TOLERANCE
final double ITERATION_TOLERANCE = 1E-10 static package inherited
Difference allowed in iterative computations.
A value of 1E-10 causes the cphi2 function to compute the latitude at a precision of 1E-10 radians, which is slightly smaller than one millimetre.
Referenced by CassiniOrMercator.inv_mlfn(), and Stereographic.inverseTransform().
MAXIMUM_ITERATIONS
final int MAXIMUM_ITERATIONS = 15 static package inherited
Maximum number of iterations for iterative computations.
Referenced by CassiniOrMercator.inv_mlfn(), Stereographic.inverseTransform(), and Krovak.inverseTransform().
serialVersionUID
final long serialVersionUID = -8816056150503228733L static private
For cross-version compatibility.