jena-geo: Vocabulary Class Reference
Vocabulary Class Reference
Locale-dependent resources for words or simple sentences.
Classes
class International
The international string to be returned by formatInternational.
class Keys
Resource keys.
Public Member Functions
Vocabulary (final java.net.URL filename)
Constructs a new resource bundle loading data from the given UTF file.
final String getLabel (final short key) throws MissingResourceException
Gets a string for the given key and appends ":" to it.
Static Public Member Functions
static Vocabulary getResources (Locale locale) throws MissingResourceException
Returns resources in the given locale.
static InternationalString formatInternational (final int key)
Gets an international string for the given key.
static InternationalString formatInternational (final short key, final Object arg)
Gets an international string for the given key.
static InternationalString formatInternational (final short key, final Object... args)
Gets an international string for the given key.
static String format (final short key) throws MissingResourceException
Gets a string for the given key from this resource bundle or one of its parents.
static String format (final short key, final Object arg0) throws MissingResourceException
Gets a string for the given key are replace all occurrence of "{0}" with values of.
static String format (final short key, final Object arg0, final Object arg1) throws MissingResourceException
Gets a string for the given key are replace all occurrence of "{0}", "{1}", with values of.
static String format (final short key, final Object arg0, final Object arg1, final Object arg2) throws MissingResourceException
Gets a string for the given key are replace all occurrence of "{0}", "{1}", with values of.
Detailed Description
Locale-dependent resources for words or simple sentences.
Author
Martin Desruisseaux (IRD)
Version
3.00
Since
2.2
Constructor & Destructor Documentation
Vocabulary()
Vocabulary (final java.net.URL filename)
Constructs a new resource bundle loading data from the given UTF file.
Parameters
filename The file or the JAR entry containing resources.
{
         super(filename);
     }
Member Function Documentation
format() [1/4]
static String format (final short key) throws MissingResourceException static
Gets a string for the given key from this resource bundle or one of its parents.
Parameters
key The key for the desired string.
Returns
The string for the given key.
Exceptions
MissingResourceException If no object for the given key can be found.
References Vocabulary.getResources().
Referenced by WKTParsingAuthorityFactory.databaseFailure(), Vocabulary.formatInternational(), ScriptRunner.getCurrentPosition(), and AbstractMathTransform.Inverse.getName().
{
         return getResources(null).getString(key);
     }
format() [2/4]
static String format (final short key, final Object arg0) throws MissingResourceException static
Gets a string for the given key are replace all occurrence of "{0}" with values of.
arg0
.
Parameters
key The key for the desired string.
arg0 Value to substitute to "{0}".
Returns
The formatted string for the given key.
Exceptions
MissingResourceException If no object for the given key can be found.
References Vocabulary.getResources().
     {
         return getResources(null).getString(key, arg0);
     }
format() [3/4]
static String format (final short key, final Object arg0, final Object arg1) throws MissingResourceException static
Gets a string for the given key are replace all occurrence of "{0}", "{1}", with values of.
arg0
,
arg1
.
Parameters
key The key for the desired string.
arg0 Value to substitute to "{0}".
arg1 Value to substitute to "{1}".
Returns
The formatted string for the given key.
Exceptions
MissingResourceException If no object for the given key can be found.
References Vocabulary.getResources().
     {
         return getResources(null).getString(key, arg0, arg1);
     }
format() [4/4]
static String format (final short key, final Object arg0, final Object arg1, final Object arg2) throws MissingResourceException static
Gets a string for the given key are replace all occurrence of "{0}", "{1}", with values of.
arg0
,
arg1
, etc.
Parameters
key The key for the desired string.
arg0 Value to substitute to "{0}".
arg1 Value to substitute to "{1}".
arg2 Value to substitute to "{2}".
Returns
The formatted string for the given key.
Exceptions
MissingResourceException If no object for the given key can be found.
References Vocabulary.getResources().
     {
         return getResources(null).getString(key, arg0, arg1, arg2);
     }
formatInternational() [1/3]
static InternationalString formatInternational (final int key) static
Gets an international string for the given key.
This method does not check for the key validity. If the key is invalid, then a MissingResourceException may be thrown when a InternationalString#toString method is invoked.
Parameters
key The key for the desired string.
Returns
An international string for the given key.
Referenced by Axes.create(), PredefinedCRS.name(), PredefinedCS.name(), and IdentifierCode.remarks().
{
         return new International(key);
     }
formatInternational() [2/3]
static InternationalString formatInternational (final short key, final Object arg) static
Gets an international string for the given key.
This method does not check for the key validity. If the key is invalid, then a MissingResourceException may be thrown when a InternationalString#toString method is invoked.
{
Note
This method is redundant with the one expecting Object..., but is provided for binary compatibility with previous Geotk versions. It also avoid the creation of a temporary array. There is no risk of confusion since the two methods delegate their work to the same format method anyway.}
Parameters
key The key for the desired string.
arg Values to substitute to "{0}".
Returns
An international string for the given key.
Todo:
Current implementation just invokes format. Need to format only when
toString(Locale)
is invoked.
References Vocabulary.format().
{
         return new org.apache.sis.util.iso.SimpleInternationalString(format(key, arg));
     }
formatInternational() [3/3]
static InternationalString formatInternational (final short key, final Object... args) static
Gets an international string for the given key.
This method does not check for the key validity. If the key is invalid, then a MissingResourceException may be thrown when a InternationalString#toString method is invoked.
Parameters
key The key for the desired string.
args Values to substitute to "{0}", "{1}", etc.
Returns
An international string for the given key.
Todo:
Current implementation just invokes format. Need to format only when
toString(Locale)
is invoked.
References Vocabulary.format().
{
         return new org.apache.sis.util.iso.SimpleInternationalString(format(key, args));
     }
getLabel()
final String getLabel (final short key) throws MissingResourceException
Gets a string for the given key and appends ":" to it.
A space may or may not be added before ":", depending on the locale. No space is added after the string; it is up to the caller to add such space if needed.
Parameters
key the key for the desired string.
Returns
the string for the given key.
Exceptions
MissingResourceException if no object for the given key can be found.
Referenced by DirectPostgisFactory.getBackingStoreDescription(), and PropertyEpsgFactory.reportDuplicates().
{
         String label = getString(key);
         if (Locale.FRENCH.getLanguage().equals(getLocale().getLanguage())) {
             label += "\u00A0:";
         } else {
             label += ':';
         }
         return label;
     }
getResources()
static Vocabulary getResources (Locale locale) throws MissingResourceException static
Returns resources in the given locale.
Parameters
locale The locale, or
null
for the default locale.
Returns
Resources in the given locale.
Exceptions
MissingResourceException if resources can't be found.
Referenced by Vocabulary.format(), DirectPostgisFactory.getBackingStoreDescription(), Vocabulary.International.getBundle(), and PropertyEpsgFactory.reportDuplicates().
{
         return getBundle(Vocabulary.class, locale);
     }