jena-geo: EarthGravitationalModel Class Reference
EarthGravitationalModel Class Reference
Transforms vertical coordinates using coefficients from the Earth Gravitational Model.
Public Member Functions
double heightOffset (final double longitude, final double latitude, final double height)
ParameterDescriptorGroup getParameterDescriptors ()
Returns the parameter descriptors for this math transform.
ParameterValueGroup getParameterValues ()
Returns the parameters for this math transform.
boolean equals (final Object object, final ComparisonMode mode)
Compares this transform with the given object for equality.
final int getSourceDimensions ()
Gets the dimension of input points, which is 3.
final int getTargetDimensions ()
Gets the dimension of output points, which is 3.
Matrix transform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff, final boolean derivate) throws TransformException
Transforms a single coordinate point in a list of ordinal values, and optionally computes the derivative at that location.
void transform (double[] srcPts, int srcOff, double[] dstPts, int dstOff, int numPts) throws TransformException
Transforms a list of coordinate point ordinal values.
void transform (float[] srcPts, int srcOff, float[] dstPts, int dstOff, int numPts) throws TransformException
Transforms a list of coordinate point ordinal values.
void transform (float [] srcPts, int srcOff, double[] dstPts, int dstOff, int numPts) throws TransformException
Transforms a list of coordinate point ordinal values.
void transform (double[] srcPts, int srcOff, float [] dstPts, int dstOff, int numPts) throws TransformException
Transforms a list of coordinate point ordinal values.
Point2D transform (final Point2D ptSrc, final Point2D ptDst) throws TransformException
Transforms the specified.
String getName ()
Returns a name for this math transform (never.
Shape createTransformedShape (final Shape shape) throws TransformException
Transform the specified shape.
Matrix derivative (final Point2D point) throws TransformException
Gets the derivative of this transform at a point.
String formatTo (Formatter formatter)
Static Public Member Functions
static EarthGravitationalModel create (final GeodeticDatum datum, final int nmax) throws IllegalArgumentException, FactoryException
Creates a model for the specified datum and maximum degree and order.
Static Public Attributes
static final int DEFAULT_ORDER = 180
The default maximum degree and order, which is {}.
Protected Member Functions
EarthGravitationalModel () throws FactoryException
Creates a model for the WGS84 datum with the default maximum degree and order.
EarthGravitationalModel (final GeodeticDatum datum, final int nmax) throws IllegalArgumentException, FactoryException
Creates a model for the specified datum and maximum degree and order.
int computeHashCode ()
Static Protected Member Functions
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException
Makes sure that an argument is non-null.
Package Functions
EarthGravitationalModel (final GeodeticDatum datum, final int nmax, final boolean dummy) throws IllegalArgumentException
Creates a model without loading the data.
final void load (final String filename) throws IOException
Loads the coefficients from the specified binary file.
Static Package Functions
static int locatingArray (final int n)
Computes the index as it would be returned by the locating array.
static String mismatchedDimension (final String argument, final int dimension, final int expected)
Constructs an error message for the MismatchedDimensionException.
Package Attributes
final double [] cnmGeopCoef
The geopotential coefficients read from the ASCII file.
final double [] snmGeopCoef
final double [] bClenshaw
final double [] as
Static Package Attributes
static final double SQRT_05 = 2.2360679774997896964091736687313
static final double SQRT_13 = 3.6055512754639892931192212674705
static final double SQRT_17 = 4.1231056256176605498214098559741
static final double SQRT_21 = 4.5825756949558400065880471937280
Private Member Functions
void initialize ()
Computes the <cite>clenshaw arrays</cite> after all coefficients have been read.
Static Private Member Functions
static int hashCode (final boolean isWGS84, int nmax)
Returns a hash code for the given fields value.
Private Attributes
final boolean isWGS84
final int nmax
Maximum degree and order attained.
final double semiMajor
WGS 84 semi-major axis.
final double esq
The first Eccentricity Squared (e²) for WGS 84 ellipsoid.
final double c2
Even zonal coefficient.
final double rkm
WGS 84 Earth's Gravitational Constant w/ atmosphere.
final double grava
Theoretical (Normal) Gravity at the Equator (on the Ellipsoid).
final double star
Theoretical (Normal) Gravity Formula Constant.
final double [] aClenshaw
Cleanshaw coefficients needed for the selected gravimetric quantities that are computed.
Static Private Attributes
static final double SQRT_03 = 1.7320508075688772935274463415059
Pre-computed values of some square roots.
static final WeakValueHashMap< Integer, EarthGravitationalModel > POOL = new WeakValueHashMap<>(Integer.class)
The pool of models created up to date.
Detailed Description
Transforms vertical coordinates using coefficients from the Earth Gravitational Model.
See any of the following providers for a list of programmatic parameters:
org.geotoolkit.referencing.operation.provider.EllipsoidToGeoid
{
Note
This class is an adaption of Fortran code clenqt.for from the <cite>National Geospatial-Intelligence Agency</cite> and available in public domain. The <cite>normalized geopotential coefficients</cite> file bundled in this module is an adaptation of egm180.nor file, with some spaces trimmed.}
Author
Pierre Cardinal
Martin Desruisseaux (IRD, Geomatys)
Version
3.18
Since
2.3
Constructor & Destructor Documentation
EarthGravitationalModel() [1/3]
EarthGravitationalModel () throws FactoryException protected
Creates a model for the WGS84 datum with the default maximum degree and order.
Exceptions
FactoryException If an error occurred while loading the data.
References EarthGravitationalModel.DEFAULT_ORDER.
Referenced by EarthGravitationalModel.create(), and EarthGravitationalModel.equals().
{
         this(CommonCRS.WGS84.datum(), DEFAULT_ORDER);
     }
EarthGravitationalModel() [2/3]
EarthGravitationalModel (final GeodeticDatum datum, final int nmax) throws IllegalArgumentException, FactoryException protected
Creates a model for the specified datum and maximum degree and order.
In current version, only DefaultGeodeticDatum::WGS84 WGS84} and DefaultGeodeticDatum::WGS72 WGS72} datum are supported.
Parameters
datum The datum for which to create the model.
nmax The maximum degree and order.
Exceptions
IllegalArgumentException If
nmax
is not greater than zero, or if the given datum is not a supported one.
FactoryException If an error occurred while loading the data.
References Errors.Keys.CantReadFile_1, Errors.format(), EarthGravitationalModel.initialize(), EarthGravitationalModel.load(), and EarthGravitationalModel.nmax.
     {
         this(datum, nmax, true);
         /*
          * Loads the data. The filename is hardcoded for now. But in a future version, we
          * may load different data for different datum if we have more example of data files.
          */
         final String filename = "EGM180.bnor";
         try {
             load(filename);
         } catch (IOException e) {
             throw new FactoryException(Errors.format(Errors.Keys.CantReadFile_1, filename), e);
         }
         initialize();
     }
EarthGravitationalModel() [3/3]
EarthGravitationalModel (final GeodeticDatum datum, final int nmax, final boolean dummy) throws IllegalArgumentException package
Creates a model without loading the data.
This constructor is for the test suite only.
References AbstractMathTransform.ensureNonNull(), Errors.format(), EarthGravitationalModel.locatingArray(), EarthGravitationalModel.nmax, and Errors.Keys.UnsupportedDatum_1.
     {
         ensureNonNull("datum", datum);
         ensureBetween("nmax", 2, 9999, nmax); // Arbitrary upper limit.
         this.nmax = nmax;
         isWGS84 = Utilities.equalsApproximately(CommonCRS.WGS84.datum(), datum);
         if (isWGS84) {
             /*
              * WGS84 model values.
              * NOTE: The Fortran program gives 3.9860015e+14 for 'rkm' constant. This value has been
              * modified in later programs. From http://cddis.gsfc.nasa.gov/926/egm96/doc/S11.HTML :
              *
              *     "We next need to consider the determination of GM, GM0, W0, U0. The value of GM0
              *      will be that adopted for the updated GM of the WGS84 ellipsoid. This value is
              *      3.986004418e+14 m³/s², which is identical to that given in the IERS Numerical
              *      Standards [McCarthy, 1996, Table 4.1]. The best estimate of GM can be taken as
              *      the same value based on the recommendations of the IAG Special Commission SC3,
              *      Fundamental Constants [Bursa, 1995b, p. 381]."
              */
             semiMajor = 6378137.0;
             esq       = 0.00669437999013;
             c2        = 108262.9989050e-8;
             rkm       = 3.986004418e+14;
             grava     = 9.7803267714;
             star      = 0.001931851386;
         } else if (Utilities.equalsIgnoreMetadata(CommonCRS.WGS72.datum(), datum)) {
             /*
              * WGS72 model values.
              */
             semiMajor = 6378135.0;
             esq       = 0.006694317778;
             c2        = 108263.0e-8;
             rkm       = 3.986005e+14;
             grava     = 9.7803327;
             star      = 0.005278994;
         } else {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.UnsupportedDatum_1,
                     datum.getName().getCode()));
         }
         final int cleanshawLength = locatingArray(nmax + 3);
         final int  geopCoefLength = locatingArray(nmax + 1);
         aClenshaw   = new double[cleanshawLength];
         bClenshaw   = new double[cleanshawLength];
         cnmGeopCoef = new double[geopCoefLength];
         snmGeopCoef = new double[geopCoefLength];
         as          = new double[nmax + 1];
     }
Member Function Documentation
computeHashCode()
int computeHashCode () protected
References EarthGravitationalModel.hashCode().
{
         return hash(hashCode(isWGS84, nmax), super.computeHashCode());
     }
create()
static EarthGravitationalModel create (final GeodeticDatum datum, final int nmax) throws IllegalArgumentException, FactoryException static
Creates a model for the specified datum and maximum degree and order.
In current version, only DefaultGeodeticDatum::WGS84 WGS84} and DefaultGeodeticDatum::WGS72 WGS72} datum are supported.
Parameters
datum The datum for which to create the model.
nmax The maximum degree and order.
Returns
The model.
Exceptions
IllegalArgumentException If
nmax
is not greater than zero, or if the given datum is not a supported one.
FactoryException If an error occurred while loading the data.
References EarthGravitationalModel.EarthGravitationalModel(), EarthGravitationalModel.hashCode(), and EarthGravitationalModel.POOL.
     {
         EarthGravitationalModel model;
         final Integer key = hashCode(Utilities.equalsApproximately(CommonCRS.WGS84.datum(), datum), nmax);
         synchronized (POOL) {
             model = POOL.get(key);
             if (model == null) {
                 model = new EarthGravitationalModel(datum, nmax);
                 POOL.put(key, model);
             }
         }
         return model;
     }
createTransformedShape()
Shape createTransformedShape (final Shape shape) throws TransformException inherited
Transform the specified shape.
The default implementation computes quadratic curves using three points for each line segment in the shape. The returned object is often a Path2D, but may also be a Line2D or a QuadCurve2D if such simplification is possible.
Parameters
shape Shape to transform.
Returns
Transformed shape, or
shape
if this transform is the identity transform.
Exceptions
IllegalStateException if this transform doesn't map 2D coordinate systems.
TransformException if a transform failed.
See also
MathTransform2D::createTransformedShape(Shape)
References AbstractMathTransform.mismatchedDimension().
{
         int dim;
         if ((dim = getSourceDimensions()) != 2 || (dim = getTargetDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("shape", 2, dim));
         }
         if (isIdentity()) return shape;
         try {
             final Method method = org.apache.sis.referencing.operation.transform.AbstractMathTransform2D.class.getMethod(
                     "createTransformedShape", MathTransform2D.class, Shape.class, AffineTransform.class, AffineTransform.class, Boolean.TYPE);
             method.setAccessible(true);
             return (Shape) method.invoke(null, (MathTransform2D) this, shape, null, null, false);
         } catch (ReflectiveOperationException e) {
             throw new TransformException(e);
         }
     }
derivative()
Matrix derivative (final Point2D point) throws TransformException inherited
Gets the derivative of this transform at a point.
The default implementation performs the following steps:
Ensure that this math transform getSourceDimensions() source dimensions} is equals to 2. Note that the getTargetDimensions() target dimensions} can be anything, not necessarily 2 (so this transform doesn't need to implement the MathTransform2D interface).
Copy the coordinate in a temporary array and pass that array to the transform(double[], int, double[], int, boolean) method, with the
derivate
boolean argument set to
true
.
If the later method returned a non-null matrix, returns that matrix. Otherwise throws TransformException.
Parameters
point The coordinate point where to evaluate the derivative.
Returns
The derivative at the specified point as a 2×2 matrix.
Exceptions
MismatchedDimensionException if the input dimension is not 2.
TransformException if the derivative can't be evaluated at the specified point.
See also
MathTransform2D::derivative(Point2D)
References Errors.Keys.CantComputeDerivative, Errors.format(), AbstractMathTransform.mismatchedDimension(), and AbstractMathTransform.transform().
Referenced by AbstractMathTransform.Inverse.derivative(), and GridTransform.transform().
{
         final int dimSource = getSourceDimensions();
         if (dimSource != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("point", 2, dimSource));
         }
         final double[] coordinate = new double[] {point.getX(), point.getY()};
         final Matrix derivative = transform(coordinate, 0, null, 0, true);
         if (derivative == null) {
             throw new TransformException(Errors.format(Errors.Keys.CantComputeDerivative));
         }
         return derivative;
     }
ensureNonNull()
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException static protected inherited
Makes sure that an argument is non-null.
This is a convenience method for subclass constructors.
Parameters
name Argument name.
object User argument.
Exceptions
InvalidParameterValueException if
object
is null.
References Errors.format(), and Errors.Keys.NullArgument_1.
Referenced by EarthGravitationalModel.EarthGravitationalModel().
     {
         if (object == null) {
             throw new InvalidParameterValueException(Errors.format(
                         Errors.Keys.NullArgument_1, name), name, object);
         }
     }
equals()
boolean equals (final Object object, final ComparisonMode mode)
Compares this transform with the given object for equality.
References EarthGravitationalModel.EarthGravitationalModel(), EarthGravitationalModel.isWGS84, and EarthGravitationalModel.nmax.
{
         if (object == this) {
             // Slight optimization
             return true;
         }
         if (super.equals(object, mode)) {
             final EarthGravitationalModel that = (EarthGravitationalModel) object;
             return isWGS84 == that.isWGS84 && nmax == that.nmax;
         }
         return false;
     }
formatTo()
String formatTo (Formatter formatter) inherited
{
         return super.formatTo(formatter);
     }
getName()
String getName () inherited
Returns a name for this math transform (never.
null
). This convenience methods returns the name of the getParameterDescriptors parameter descriptors} if any, or the short class name otherwise.
Returns
A name for this math transform (never
null
).
Since
2.5
Referenced by AbstractMathTransform.Inverse.getName().
{
         final ParameterDescriptorGroup descriptor = getParameterDescriptors();
         if (descriptor != null) {
             final Identifier identifier = descriptor.getName();
             if (identifier != null) {
                 final String code = identifier.getCode();
                 if (code != null) {
                     return code;
                 }
             }
         }
         return Classes.getShortClassName(this);
     }
getParameterDescriptors()
ParameterDescriptorGroup getParameterDescriptors ()
Returns the parameter descriptors for this math transform.
Referenced by EarthGravitationalModel.getParameterValues().
{
         return PARAMETERS;
     }
getParameterValues()
ParameterValueGroup getParameterValues ()
Returns the parameters for this math transform.
References EarthGravitationalModel.getParameterDescriptors().
{
         return new ParameterGroup(getParameterDescriptors(),
                 new Parameter<>(DATUM, isWGS84 ? "WGS84" : "WGS72"),
                 new Parameter<>(ORDER, nmax));
     }
getSourceDimensions()
final int getSourceDimensions () inherited
Gets the dimension of input points, which is 3.
References VerticalTransform.DIMENSION.
Referenced by VerticalTransform.transform().
{
         return DIMENSION;
     }
getTargetDimensions()
final int getTargetDimensions () inherited
Gets the dimension of output points, which is 3.
References VerticalTransform.DIMENSION, and VerticalTransform.heightOffset().
Referenced by VerticalTransform.transform().
{
         return DIMENSION;
     }
hashCode()
static int hashCode (final boolean isWGS84, int nmax) static private
Returns a hash code for the given fields value.
This value must be different for every legal combination of the arguments. This is required for proper working of the pool.
Parameters
References EarthGravitationalModel.nmax.
Referenced by EarthGravitationalModel.computeHashCode(), and EarthGravitationalModel.create().
{
         if (!isWGS84) {
             nmax = ~nmax;
         }
         return nmax;
     }
heightOffset()
double heightOffset (final double longitude, final double latitude, final double height)
References EarthGravitationalModel.esq, EarthGravitationalModel.locatingArray(), and EarthGravitationalModel.nmax.
{
         /*
          * Note: no need to ensure that longitude is in [-180..+180°] range, because its value
          * is used only in trigonometric functions (sin / cos), which roll it as we would expect.
          * Latitude is used only in trigonometric functions as well.
          */
         final double φ     = toRadians(latitude);
         final double sinφ  = sin(φ);
         final double sin2φ = sinφ * sinφ;
         final double rni   = sqrt(1.0 - esq*sin2φ);
         final double rn    = semiMajor / rni;
         final double t22   = (rn + height) * cos(φ);
         final double z1    = ((rn * (1 - esq)) + height) * sinφ;
         final double th    = (PI/2) - atan(z1 / t22);
         final double y     = sin(th);
         final double t     = cos(th);
         final double f1    = semiMajor / hypot(t22, z1);
         final double f2    = f1*f1;
         final double λ     = toRadians(longitude);
         final double gravn;
         if (isWGS84) {
             gravn = grava * (1.0 + star * sin2φ) / rni;
         } else {
             gravn = grava * (1.0 + star * sin2φ) + 0.000023461 * (sin2φ * sin2φ);
         }
         final double[] cr  = new double[nmax + 1];
         final double[] sr  = new double[nmax + 1];
         final double[] s11 = new double[nmax + 3];
         final double[] s12 = new double[nmax + 3];
         sr[0]=0; sr[1]=sin(λ);
         cr[0]=1; cr[1]=cos(λ);
         for (int j=2; j<=nmax; j++) {
             sr[j] = (2.0 * cr[1] * sr[j-1]) - sr[j-2];
             cr[j] = (2.0 * cr[1] * cr[j-1]) - cr[j-2];
         }
         double sht=0, previousSht=0;
         for (int i=nmax; i>=0; i--) {
             for (int j=nmax; j>=i; j--) {
                 final int    ll  = locatingArray(j) + i;
                 final int    ll2 = ll  + j + 1;
                 final int    ll3 = ll2 + j + 2;
                 final double ta  = aClenshaw[ll2] * f1 * t;
                 final double tb  = bClenshaw[ll3] * f2;
                 s11[j] = (ta * s11[j + 1]) - (tb * s11[j + 2]) + cnmGeopCoef[ll];
                 s12[j] = (ta * s12[j + 1]) - (tb * s12[j + 2]) + snmGeopCoef[ll];
             }
             previousSht = sht;
             sht = (-as[i] * y * f1 * sht) + (s11[i] * cr[i]) + (s12[i] * sr[i]);
         }
         return ((s11[0] + s12[0]) * f1 + (previousSht * SQRT_03 * y * f2)) * rkm /
                (semiMajor * (gravn - (height * 0.3086e-5)));
     }
initialize()
void initialize () private
Computes the <cite>clenshaw arrays</cite> after all coefficients have been read.
We performs this step in a separated method than from in case we wish to read the coefficient from an other source than an ASCII file in some future version.
References EarthGravitationalModel.c2, EarthGravitationalModel.esq, EarthGravitationalModel.locatingArray(), EarthGravitationalModel.nmax, EarthGravitationalModel.SQRT_05, EarthGravitationalModel.SQRT_13, EarthGravitationalModel.SQRT_17, and EarthGravitationalModel.SQRT_21.
Referenced by EarthGravitationalModel.EarthGravitationalModel().
{
         /*
          * MODIFY CNM EVEN ZONAL COEFFICIENTS.
          */
         if (isWGS84) {
             final double[] c2n = new double[6];
             c2n[1] = c2;
             int sign = 1;
             double esqi = esq;
             for (int i=2; i<c2n.length; i++) {
                 sign *= -1;
                 esqi *= esq;
                 c2n[i] = sign * (3*esqi) / ((2*i + 1) * (2*i + 3)) * (1-i + (5*i*c2 / esq));
             }
             /* all nmax */ cnmGeopCoef[ 3] += c2n[1] / SQRT_05;
             /* all nmax */ cnmGeopCoef[10] += c2n[2] / 3;
             /* all nmax */ cnmGeopCoef[21] += c2n[3] / SQRT_13;
             if (nmax > 6)  cnmGeopCoef[36] += c2n[4] / SQRT_17;
             if (nmax > 9)  cnmGeopCoef[55] += c2n[5] / SQRT_21;
         } else {
             /* all nmax */ cnmGeopCoef[ 3] += 4.841732e-04;
             /* all nmax */ cnmGeopCoef[10] += -7.8305e-07;
         }
         /*
          * BUILD ALL CLENSHAW COEFFICIENT ARRAYS.
          */
         for (int i=0; i<=nmax; i++) {
             as[i] = -sqrt(1.0 + 1.0/(2*(i+1)));
         }
         for (int i=0; i<=nmax; i++) {
             for (int j=i+1; j<=nmax; j++) {
                 final int ll = locatingArray(j) + i;
                 final int n  = 2*j + 1;
                 final int ji = (j-i) * (j+i);
                 aClenshaw[ll] = sqrt(n*(2*j - 1)           / (double) (ji));
                 bClenshaw[ll] = sqrt(n*(j+i - 1)*(j-i - 1) / (double) (ji*(2*j - 3)));
             }
         }
     }
load()
final void load (final String filename) throws IOException package
Loads the coefficients from the specified binary file.
Callers must invoke initialize() after this method in order to initialize the internal <cite>clenshaw arrays</cite>.
Parameters
filename The filename (e.g.
"EGM180.nor"
, relative to this class directory.
Exceptions
IOException if the file can't be read or has an invalid content.
Referenced by EarthGravitationalModel.EarthGravitationalModel().
{
         final InputStream stream = EarthGravitationalModel.class.getResourceAsStream(filename);
         if (stream == null) {
             throw new FileNotFoundException(filename);
         }
         try (DataInputStream in = new DataInputStream(new BufferedInputStream(stream))) {
             for (int i=0; i<cnmGeopCoef.length; i++) {
                 cnmGeopCoef[i] = in.readDouble();
                 snmGeopCoef[i] = in.readDouble();
             }
         }
     }
locatingArray()
static int locatingArray (final int n) static package
Computes the index as it would be returned by the locating array.
iv
(from the Fortran code).
Tip (used in some place in this class):
locatingArray(n+1)
==
locatingArray(n) + n + 1
.
Referenced by EarthGravitationalModel.EarthGravitationalModel(), EarthGravitationalModel.heightOffset(), and EarthGravitationalModel.initialize().
{
         return ((n+1) * n) >> 1;
     }
mismatchedDimension()
static String mismatchedDimension (final String argument, final int dimension, final int expected) static package inherited
Constructs an error message for the MismatchedDimensionException.
CAUTION: Argument order is different than in Apache SIS.
Parameters
argument The argument name with the wrong number of dimensions.
dimension The wrong dimension.
expected The expected dimension.
References Errors.format(), and Errors.Keys.MismatchedDimension_3.
Referenced by AbstractMathTransform.createTransformedShape(), AbstractMathTransform.derivative(), and AbstractMathTransform.transform().
{
         return Errors.format(Errors.Keys.MismatchedDimension_3, argument, dimension, expected);
     }
transform() [1/6]
Matrix transform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff, final boolean derivate) throws TransformException inherited
Transforms a single coordinate point in a list of ordinal values, and optionally computes the derivative at that location.
Exceptions
TransformException If the point can't be transformed.
Since
3.20 (derived from 3.00)
References VerticalTransform.getSourceDimensions(), VerticalTransform.getTargetDimensions(), and VerticalTransform.heightOffset().
     {
         if (dstPts != null) {
             final double x = srcPts[srcOff  ];
             final double y = srcPts[srcOff+1];
             final double z = srcPts[srcOff+2];
             dstPts[dstOff  ] = x;
             dstPts[dstOff+1] = y;
             dstPts[dstOff+2] = z + heightOffset(x,y,z);
         }
         return derivate ? Matrices.createDiagonal(getTargetDimensions(), getSourceDimensions()) : null;
     }
transform() [2/6]
void transform (double [] srcPts, int srcOff, double [] dstPts, int dstOff, int numPts) throws TransformException inherited
Transforms a list of coordinate point ordinal values.
References VerticalTransform.DIMENSION, and VerticalTransform.heightOffset().
     {
         boolean reverse = false;
         if (srcPts == dstPts) {
             switch (IterationStrategy.suggest(srcOff, DIMENSION, dstOff, DIMENSION, numPts)) {
                 case ASCENDING: {
                     break;
                 }
                 case DESCENDING: {
                     final int offset = (numPts-1) * DIMENSION;
                     srcOff += offset;
                     dstOff += offset;
                     reverse = true;
                     break;
                 }
                 default: {
                     srcPts = Arrays.copyOfRange(srcPts, srcOff, srcOff + numPts*DIMENSION);
                     srcOff = 0;
                     break;
                 }
             }
         }
         while (--numPts >= 0) {
             final double x = srcPts[srcOff++];
             final double y = srcPts[srcOff++];
             final double z = srcPts[srcOff++];
             dstPts[dstOff++] = x;
             dstPts[dstOff++] = y;
             dstPts[dstOff++] = z + heightOffset(x,y,z);
             if (reverse) {
                 srcOff -= 2*DIMENSION;
                 dstOff -= 2*DIMENSION;
             }
         }
     }
transform() [3/6]
Point2D transform (final Point2D ptSrc, final Point2D ptDst) throws TransformException inherited
Transforms the specified.
ptSrc
and stores the result in
ptDst
. The default implementation performs the following steps:
Ensures that the getSourceDimensions() source} and getTargetDimensions() target dimensions} of this math transform are equal to 2.
Delegates to the transform(double[],int,double[],int,boolean) method using a temporary array of doubles.
Parameters
ptSrc The coordinate point to be transformed.
ptDst The coordinate point that stores the result of transforming
ptSrc
, or
null
if a new point should be created.
Returns
The coordinate point after transforming
ptSrc
and storing the result in
ptDst
, or in a new point if
ptDst
was null.
Exceptions
MismatchedDimensionException If this transform doesn't map two-dimensional coordinate systems.
TransformException If the point can't be transformed.
See also
MathTransform2D::transform(Point2D,Point2D)
References AbstractMathTransform.mismatchedDimension().
Referenced by AbstractMathTransform.derivative().
{
         int dim;
         if ((dim = getSourceDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("ptSrc", 2, dim));
         }
         if ((dim = getTargetDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("ptDst", 2, dim));
         }
         final double[] ord = new double[] {ptSrc.getX(), ptSrc.getY()};
         transform(ord, 0, ord, 0, false);
         if (ptDst != null) {
             ptDst.setLocation(ord[0], ord[1]);
             return ptDst;
         } else {
             return new Point2D.Double(ord[0], ord[1]);
         }
     }
transform() [4/6]
void transform (float [] srcPts, int srcOff, float [] dstPts, int dstOff, int numPts) throws TransformException inherited
Transforms a list of coordinate point ordinal values.
References VerticalTransform.DIMENSION, and VerticalTransform.heightOffset().
     {
         boolean reverse = false;
         if (srcPts == dstPts) {
             switch (IterationStrategy.suggest(srcOff, DIMENSION, dstOff, DIMENSION, numPts)) {
                 case ASCENDING: {
                     break;
                 }
                 case DESCENDING: {
                     final int offset = (numPts-1) * DIMENSION;
                     srcOff += offset;
                     dstOff += offset;
                     reverse = true;
                     break;
                 }
                 default: {
                     srcPts = Arrays.copyOfRange(srcPts, srcOff, srcOff + numPts*DIMENSION);
                     srcOff = 0;
                     break;
                 }
             }
         }
         while (--numPts >= 0) {
             final float  x = srcPts[srcOff++];
             final float  y = srcPts[srcOff++];
             final double z = srcPts[srcOff++];
             dstPts[dstOff++] = x;
             dstPts[dstOff++] = y;
             dstPts[dstOff++] = (float) (z + heightOffset(x,y,z));
             if (reverse) {
                 srcOff -= 2*DIMENSION;
                 dstOff -= 2*DIMENSION;
             }
         }
     }
transform() [5/6]
void transform (float [] srcPts, int srcOff, double [] dstPts, int dstOff, int numPts) throws TransformException inherited
Transforms a list of coordinate point ordinal values.
References VerticalTransform.heightOffset().
     {
         while (--numPts >= 0) {
             final double x,y,z;
             dstPts[dstOff++] =  (x = srcPts[srcOff++]);
             dstPts[dstOff++] =  (y = srcPts[srcOff++]);
             dstPts[dstOff++] = ((z = srcPts[srcOff++]) + heightOffset(x,y,z));
         }
     }
transform() [6/6]
void transform (double [] srcPts, int srcOff, float [] dstPts, int dstOff, int numPts) throws TransformException inherited
Transforms a list of coordinate point ordinal values.
References VerticalTransform.heightOffset().
     {
         while (--numPts >= 0) {
             final double x,y,z;
             dstPts[dstOff++] = (float)  (x = srcPts[srcOff++]);
             dstPts[dstOff++] = (float)  (y = srcPts[srcOff++]);
             dstPts[dstOff++] = (float) ((z = srcPts[srcOff++]) + heightOffset(x,y,z));
         }
     }
Member Data Documentation
aClenshaw
final double [] aClenshaw private
Cleanshaw coefficients needed for the selected gravimetric quantities that are computed.
Those arrays are computed by the initialize method.
as
final double [] as package
bClenshaw
final double [] bClenshaw package
c2
final double c2 private
Even zonal coefficient.
Referenced by EarthGravitationalModel.initialize().
cnmGeopCoef
final double [] cnmGeopCoef package
The geopotential coefficients read from the ASCII file.
Those arrays are filled by the load method.
DEFAULT_ORDER
final int DEFAULT_ORDER = 180 static
The default maximum degree and order, which is {}.
Referenced by EarthGravitationalModel.EarthGravitationalModel().
esq
final double esq private
The first Eccentricity Squared (e²) for WGS 84 ellipsoid.
Referenced by EarthGravitationalModel.heightOffset(), and EarthGravitationalModel.initialize().
grava
final double grava private
Theoretical (Normal) Gravity at the Equator (on the Ellipsoid).
isWGS84
final boolean isWGS84 private
true
for WGS84 model, or
false
for WGS72 model.
Referenced by EarthGravitationalModel.equals().
nmax
final int nmax private
Maximum degree and order attained.
Referenced by EarthGravitationalModel.EarthGravitationalModel(), EarthGravitationalModel.equals(), EarthGravitationalModel.hashCode(), EarthGravitationalModel.heightOffset(), and EarthGravitationalModel.initialize().
POOL
final WeakValueHashMap<Integer,EarthGravitationalModel> POOL = new WeakValueHashMap<>(Integer.class) static private
The pool of models created up to date.
We recycle existing instance in order to reduce memory usage (avoid duplicating arrays), not for saving the CPU time associated to the creation of the model. So we really want weak references, not soft references.
Referenced by EarthGravitationalModel.create().
rkm
final double rkm private
WGS 84 Earth's Gravitational Constant w/ atmosphere.
semiMajor
final double semiMajor private
WGS 84 semi-major axis.
snmGeopCoef
final double [] snmGeopCoef package
SQRT_03
final double SQRT_03 = 1.7320508075688772935274463415059 static private
Pre-computed values of some square roots.
SQRT_05
final double SQRT_05 = 2.2360679774997896964091736687313 static package
Referenced by EarthGravitationalModel.initialize().
SQRT_13
final double SQRT_13 = 3.6055512754639892931192212674705 static package
Referenced by EarthGravitationalModel.initialize().
SQRT_17
final double SQRT_17 = 4.1231056256176605498214098559741 static package
Referenced by EarthGravitationalModel.initialize().
SQRT_21
final double SQRT_21 = 4.5825756949558400065880471937280 static package
Referenced by EarthGravitationalModel.initialize().
star
final double star private
Theoretical (Normal) Gravity Formula Constant.