jena-geo: GridTransform Class Reference
GridTransform Class Reference
Transforms a set of coordinate points using bilinear interpolation in a grid.
Public Member Functions
final int getSourceDimensions ()
Returns the dimension of input points, which is 2.
final int getTargetDimensions ()
Returns the dimension of output points.
boolean isIdentity ()
Returns.
Matrix transform (final double[] srcPts, final int srcOff, final double[] dstPts, int dstOff, final boolean derivate)
Transforms a source coordinate into target coordinate.
void transform (final double[] srcPts, int srcOff, final double[] dstPts, int dstOff, int numPts)
Transforms a source coordinate into target coordinate.
void transform (final float[] srcPts, int srcOff, final float[] dstPts, int dstOff, int numPts)
Transforms a source coordinate into target coordinate.
void transform (final double[] srcPts, int srcOff, final float [] dstPts, int dstOff, int numPts)
Transforms a source coordinate into target coordinate.
void transform (final float [] srcPts, int srcOff, final double[] dstPts, int dstOff, int numPts)
Transforms a source coordinate into target coordinate.
boolean equals (final Object object, final ComparisonMode mode)
Compares this transform with the specified object for equality.
String getName ()
Returns a name for this math transform (never.
Point2D transform (final Point2D ptSrc, final Point2D ptDst) throws TransformException
Transforms the specified.
Shape createTransformedShape (final Shape shape) throws TransformException
Transform the specified shape.
Matrix derivative (final Point2D point) throws TransformException
Gets the derivative of this transform at a point.
String formatTo (Formatter formatter)
Static Public Member Functions
static GridTransform create (final int width, final int height, final float[]... data)
Constructs a GridType::LOCALIZATION localization} grid using the specified data.
static GridTransform create (final int width, final int height, final double[]... data)
Constructs a GridType::LOCALIZATION localization} grid using the specified data.
static GridTransform create (final GridType type, final DataBuffer grid, final Dimension size, final Rectangle2D area)
Constructs a grid using the specified data.
Protected Member Functions
GridTransform (final GridType type, final DataBuffer grid, final Dimension size, final Rectangle2D area)
Constructs a grid using the specified data.
int computeHashCode ()
Static Protected Member Functions
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException
Makes sure that an argument is non-null.
Protected Attributes
final int width
Number of columns in the grid.
final int height
Number of rows in the grid.
final transient DataBuffer grid
The grid of values.
Static Package Functions
static String mismatchedDimension (final String argument, final int dimension, final int expected)
Constructs an error message for the MismatchedDimensionException.
Package Attributes
final double yOrigin
final double scaleY
final GridType type
Whatever the grid values are directly the target coordinates or offsets to apply on source coordinates.
Private Member Functions
void transform (float[] srcPts1, double[] srcPts2, int srcOff, float[] dstPts1, double[] dstPts2, int dstOff, int numPts)
Implementation of direct transformation.
void writeObject (final ObjectOutputStream out) throws IOException
Serializes this grid.
void readObject (final ObjectInputStream in) throws IOException, ClassNotFoundException
Deserializes this grid.
Private Attributes
final double xOrigin
The "real world" coordinate which correspond to the (0,0) grid coordinate.
final double scaleX
The scale factor by which to multiply the "real world" coordinate in order to get the grid coordinate.
Static Private Attributes
static final long serialVersionUID = -7973466015425546562L
Serial number for inter-operability with different versions.
static final int srcDim = 2
Number of source dimensions.
Detailed Description
Transforms a set of coordinate points using bilinear interpolation in a grid.
{
and output coordinates}
First, "<cite>real world</cite>" input coordinates (x, y) are optionally converted to <cite>grid</cite> coordinates (xi, yi), which are zero-based index in the two-dimensional grid. This conversion is applied only if a "real world" envelope was given to the constructor, otherwise the input coordinates are assumed to be directly grid coordinates.
{
Note
This <cite>real world</cite> to <cite>grid</cite> transform is affine, but is still performed internally by this class in a simplified form (no rotation or axis swapping) rather than delegated to an AffineTransform instance because this class needs the original coordinates if the grid values are offset to be added, as in NADCON grids.}
Output coordinates are the values stored in the grid at the specified grid coordinate. If the grid coordinates are non-integer values, then output coordinates are interpolated using a bilinear interpolation. If the grid coordinates are outside the grid domain ([0 … width-2] × [0 … height-2] where width} and height} are the number of columns and rows in the grid), then output coordinates are extrapolated.
In the case of a LOCALIZATION grid, we are done. But in the case of OFFSET, NADCON or NTv2 grids, the above coordinates are added to the input coordinates in order to get the final output coordinates.
{
}
By default
GridTransform
s are not invertible. However some subclasses like GridTransform2D and the one created by org.geotoolkit.referencing.operation.builder.LocalizationGrid provide conditional support for inverse transforms.
Author
Rémi Eve (IRD)
Martin Desruisseaux (IRD, Geomatys)
Simon Reynard (Geomatys)
Version
3.20
Since
3.00
Deprecated:
Replaced by org.apache.sis.referencing.operation.transform.InterpolatedTransform
Constructor & Destructor Documentation
GridTransform()
GridTransform (final GridType type, final DataBuffer grid, final Dimension size, final Rectangle2D area) protected
Constructs a grid using the specified data.
Parameters
type Whatever the grid values are directly the target coordinates or offsets to apply on source coordinates.
grid The grid of values. It must complies with the conditions documented in the grid field.
size Number of columns (Dimension::width width}) and rows (Dimension::height height}) in the grid.
area Grid envelope in "real world" coordinates, or
null
if none. The minimal (x,y) coordinate will maps the (0,0) grid coordinate, and the maximal (x,y) coordinate will maps the (width}, height}) grid coordinate.
References Errors.format(), GridTransform.grid, GridTransform.height, Errors.Keys.MismatchedArrayLength, GridType.NTv2, and GridTransform.type.
Referenced by GridTransform.create(), and GridTransform.equals().
     {
         this.grid   = grid;
         this.type   = type;
         this.width  = size.width;
         this.height = size.height;
         ensureStrictlyPositive("width",  width);
         ensureStrictlyPositive("height", height);
         if (grid.getSize() != width*height) {
             throw new IllegalArgumentException(Errors.format(Errors.Keys.MismatchedArrayLength));
         }
         if (area != null) {
             final double longitudeSign = (type == GridType.NTv2) ? -1 : +1;
             xOrigin = area.getMinX() * longitudeSign;
             yOrigin = area.getMinY();
             scaleX  = width  / area.getWidth() * longitudeSign;
             scaleY  = height / area.getHeight();
         } else {
             xOrigin = 0;
             yOrigin = 0;
             scaleX  = 1;
             scaleY  = 1;
         }
     }
Member Function Documentation
computeHashCode()
int computeHashCode () protected
{
         return hash(xOrigin, hash(yOrigin, hash(scaleX, hash(scaleY, hash(width, hash(height,
                hash(grid.getNumBanks(), super.computeHashCode())))))));
     }
create() [1/3]
static GridTransform create (final int width, final int height, final float... [] data) static
Constructs a GridType::LOCALIZATION localization} grid using the specified data.
This convenience method creates the intermediate DataBufferFloat object from the supplied data assuming that the first valid values is located at index 0. If this is not the case, user can create a
DataBufferFloat
object directly in order to gain more control.
Parameters
width Number of columns in the grid.
height Number of rows in the grid.
data Data stored in row-major order, one array for each target dimension.
Returns
The math transform backed by the given grid.
References GridType.LOCALIZATION.
Referenced by GridTransform.create().
{
         return create(GridType.LOCALIZATION, new DataBufferFloat(data, width*height),
                       new Dimension(width, height), null);
     }
create() [2/3]
static GridTransform create (final int width, final int height, final double... [] data) static
Constructs a GridType::LOCALIZATION localization} grid using the specified data.
This convenience method creates the intermediate DataBufferDouble object from the supplied data assuming that the first valid values is located at index 0. If this is not the case, user can create a
DataBufferDouble
object directly in order to gain more control.
Parameters
width Number of columns in the grid.
height Number of rows in the grid.
data Data stored in row-major order, one array for each target dimension.
Returns
The math transform backed by the given grid.
References GridTransform.create(), and GridType.LOCALIZATION.
{
         return create(GridType.LOCALIZATION, new DataBufferDouble(data, width*height),
                       new Dimension(width, height), null);
     }
create() [3/3]
static GridTransform create (final GridType type, final DataBuffer grid, final Dimension size, final Rectangle2D area) static
Constructs a grid using the specified data.
Parameters
type Whatever the grid values are directly the target coordinates or offsets to apply on source coordinates.
grid The grid of values. It must complies with the conditions documented in the grid field.
size Number of columns (Dimension::width width}) and rows (Dimension::height height}) in the grid.
area Grid envelope in "real world" coordinates, or
null
if none. The minimal (x,y) coordinate will maps the (0,0) grid coordinate, and the maximal (x,y) coordinate will maps the (
size.width
,
size.height
) grid coordinate.
Returns
The math transform backed by the given grid.
References GridTransform.GridTransform().
     {
         if (grid.getNumBanks() == 2) {
             return new GridTransform2D(type, grid, size, area);
         }
         return new GridTransform(type, grid, size, area);
     }
createTransformedShape()
Shape createTransformedShape (final Shape shape) throws TransformException inherited
Transform the specified shape.
The default implementation computes quadratic curves using three points for each line segment in the shape. The returned object is often a Path2D, but may also be a Line2D or a QuadCurve2D if such simplification is possible.
Parameters
shape Shape to transform.
Returns
Transformed shape, or
shape
if this transform is the identity transform.
Exceptions
IllegalStateException if this transform doesn't map 2D coordinate systems.
TransformException if a transform failed.
See also
MathTransform2D::createTransformedShape(Shape)
References AbstractMathTransform.mismatchedDimension().
{
         int dim;
         if ((dim = getSourceDimensions()) != 2 || (dim = getTargetDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("shape", 2, dim));
         }
         if (isIdentity()) return shape;
         try {
             final Method method = org.apache.sis.referencing.operation.transform.AbstractMathTransform2D.class.getMethod(
                     "createTransformedShape", MathTransform2D.class, Shape.class, AffineTransform.class, AffineTransform.class, Boolean.TYPE);
             method.setAccessible(true);
             return (Shape) method.invoke(null, (MathTransform2D) this, shape, null, null, false);
         } catch (ReflectiveOperationException e) {
             throw new TransformException(e);
         }
     }
derivative()
Matrix derivative (final Point2D point) throws TransformException inherited
Gets the derivative of this transform at a point.
The default implementation performs the following steps:
Ensure that this math transform getSourceDimensions() source dimensions} is equals to 2. Note that the getTargetDimensions() target dimensions} can be anything, not necessarily 2 (so this transform doesn't need to implement the MathTransform2D interface).
Copy the coordinate in a temporary array and pass that array to the transform(double[], int, double[], int, boolean) method, with the
derivate
boolean argument set to
true
.
If the later method returned a non-null matrix, returns that matrix. Otherwise throws TransformException.
Parameters
point The coordinate point where to evaluate the derivative.
Returns
The derivative at the specified point as a 2×2 matrix.
Exceptions
MismatchedDimensionException if the input dimension is not 2.
TransformException if the derivative can't be evaluated at the specified point.
See also
MathTransform2D::derivative(Point2D)
References Errors.Keys.CantComputeDerivative, Errors.format(), AbstractMathTransform.mismatchedDimension(), and AbstractMathTransform.transform().
Referenced by AbstractMathTransform.Inverse.derivative(), and GridTransform.transform().
{
         final int dimSource = getSourceDimensions();
         if (dimSource != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("point", 2, dimSource));
         }
         final double[] coordinate = new double[] {point.getX(), point.getY()};
         final Matrix derivative = transform(coordinate, 0, null, 0, true);
         if (derivative == null) {
             throw new TransformException(Errors.format(Errors.Keys.CantComputeDerivative));
         }
         return derivative;
     }
ensureNonNull()
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException static protected inherited
Makes sure that an argument is non-null.
This is a convenience method for subclass constructors.
Parameters
name Argument name.
object User argument.
Exceptions
InvalidParameterValueException if
object
is null.
References Errors.format(), and Errors.Keys.NullArgument_1.
Referenced by EarthGravitationalModel.EarthGravitationalModel().
     {
         if (object == null) {
             throw new InvalidParameterValueException(Errors.format(
                         Errors.Keys.NullArgument_1, name), name, object);
         }
     }
equals()
boolean equals (final Object object, final ComparisonMode mode)
Compares this transform with the specified object for equality.
This method returns
true
if the two objects are of the same class and have the same width}, height}, getTargetDimensions target dimension} and the same values in all valid grid cells. Note that the grids are not required to be of the same type (TYPE_FLOAT, TYPE_DOUBLE, etc.) if the values casted to the
double
type are equal.
References Utilities.equals(), GridTransform.grid, GridTransform.GridTransform(), GridTransform.height, GridTransform.scaleX, GridTransform.scaleY, GridTransform.width, GridTransform.xOrigin, and GridTransform.yOrigin.
{
         if (object == this) {
             return true;
         }
         if (super.equals(object, mode)) {
             final GridTransform that = (GridTransform) object;
             if (width == that.width && height == that.height &&
                 Utilities.equals(xOrigin, that.xOrigin) &&
                 Utilities.equals(yOrigin, that.yOrigin) &&
                 Utilities.equals(scaleX,  that.scaleX)  &&
                 Utilities.equals(scaleY,  that.scaleY))
             {
                 final int dstDim = grid.getNumBanks();
                 if (dstDim == that.grid.getNumBanks()) {
                     final int size = width * height;
                     for (int b=0; b<dstDim; b++) {
                         for (int i=0; i<size; i++) {
                             final double va = this.grid.getElemDouble(b,i);
                             final double vb = that.grid.getElemDouble(b,i);
                             if (!Utilities.equals(va, vb)) {
                                 return false;
                             }
                         }
                     }
                     return true;
                 }
             }
         }
         return false;
     }
formatTo()
String formatTo (Formatter formatter) inherited
{
         return super.formatTo(formatter);
     }
getName()
String getName () inherited
Returns a name for this math transform (never.
null
). This convenience methods returns the name of the #getParameterDescriptors parameter descriptors} if any, or the short class name otherwise.
Returns
A name for this math transform (never
null
).
Since
2.5
Referenced by AbstractMathTransform.Inverse.getName().
{
         final ParameterDescriptorGroup descriptor = getParameterDescriptors();
         if (descriptor != null) {
             final Identifier identifier = descriptor.getName();
             if (identifier != null) {
                 final String code = identifier.getCode();
                 if (code != null) {
                     return code;
                 }
             }
         }
         return Classes.getShortClassName(this);
     }
getSourceDimensions()
final int getSourceDimensions ()
Returns the dimension of input points, which is 2.
References GridTransform.srcDim.
{
         return srcDim;
     }
getTargetDimensions()
final int getTargetDimensions ()
Returns the dimension of output points.
This is the number of banks in the underlying grid}.
{
         return grid.getNumBanks();
     }
isIdentity()
boolean isIdentity ()
Returns.
false
since this transform is not the identity one.
{
         return false;
     }
mismatchedDimension()
static String mismatchedDimension (final String argument, final int dimension, final int expected) static package inherited
Constructs an error message for the MismatchedDimensionException.
CAUTION: Argument order is different than in Apache SIS.
Parameters
argument The argument name with the wrong number of dimensions.
dimension The wrong dimension.
expected The expected dimension.
References Errors.format(), and Errors.Keys.MismatchedDimension_3.
Referenced by AbstractMathTransform.createTransformedShape(), AbstractMathTransform.derivative(), and AbstractMathTransform.transform().
{
         return Errors.format(Errors.Keys.MismatchedDimension_3, argument, dimension, expected);
     }
readObject()
void readObject (final ObjectInputStream in) throws IOException, ClassNotFoundException private
Deserializes this grid.
This method processes grid in a special way because the default JDK implementations are not serializable.
References Errors.format(), GridTransform.height, and Errors.Keys.UnsupportedDataType.
{
         in.defaultReadObject();
         final int    size = width * height;
         final Object type = in.readObject();
         final Object data = in.readObject();
         try {
             final Class<? extends DataBuffer> classe = ((Class<?>) type).asSubclass(DataBuffer.class);
             final DataBuffer buffer = classe.getConstructor(data.getClass(), Integer.TYPE).newInstance(data, size);
             final Field field = GridTransform.class.getDeclaredField("grid");
             field.setAccessible(true);
             field.set(this, buffer);
         } catch (ReflectiveOperationException e) {
             InvalidObjectException exception = new InvalidObjectException(
                     Errors.format(Errors.Keys.UnsupportedDataType));
             exception.initCause(e);
             throw exception;
         }
     }
transform() [1/7]
Point2D transform (final Point2D ptSrc, final Point2D ptDst) throws TransformException inherited
Transforms the specified.
ptSrc
and stores the result in
ptDst
. The default implementation performs the following steps:
Ensures that the getSourceDimensions() source} and getTargetDimensions() target dimensions} of this math transform are equal to 2.
Delegates to the transform(double[],int,double[],int,boolean) method using a temporary array of doubles.
Parameters
ptSrc The coordinate point to be transformed.
ptDst The coordinate point that stores the result of transforming
ptSrc
, or
null
if a new point should be created.
Returns
The coordinate point after transforming
ptSrc
and storing the result in
ptDst
, or in a new point if
ptDst
was null.
Exceptions
MismatchedDimensionException If this transform doesn't map two-dimensional coordinate systems.
TransformException If the point can't be transformed.
See also
MathTransform2D::transform(Point2D,Point2D)
References AbstractMathTransform.mismatchedDimension().
Referenced by AbstractMathTransform.derivative().
{
         int dim;
         if ((dim = getSourceDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("ptSrc", 2, dim));
         }
         if ((dim = getTargetDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("ptDst", 2, dim));
         }
         final double[] ord = new double[] {ptSrc.getX(), ptSrc.getY()};
         transform(ord, 0, ord, 0, false);
         if (ptDst != null) {
             ptDst.setLocation(ord[0], ord[1]);
             return ptDst;
         } else {
             return new Point2D.Double(ord[0], ord[1]);
         }
     }
transform() [2/7]
Matrix transform (final double [] srcPts, final int srcOff, final double [] dstPts, int dstOff, final boolean derivate)
Transforms a source coordinate into target coordinate.
The transformation will involve bilinear interpolations if the source coordinates are not integer values. This method can also estimate the derivative at the location of the transformed points.
Parameters
srcPts The source coordinate.
srcOff Index of the first valid ordinate in the
srcPts
array.
dstPts Where to store the target coordinate, or
null
.
dstOff Index where to store the first ordinate.
derivate
References AbstractMathTransform.derivative(), GridTransform.width, GridTransform.xOrigin, and GridTransform.yOrigin.
Referenced by GridTransform2D.Inverse.transform(), and GridTransform.transform().
     {
         /*
          * Following code is a copy-and-paste of:
          *
          *    transform(null, srcPts, srcOff, null, dstPts, dstOff, 1);
          *
          * with the loop over many points and the management of overlapping array removeds,
          * since they are managed by the caller. This code is copied because this method is
          * invoked often during inverse transformations.
          *
          * In addition, derivative calculation has been in-lined.
          */
         final double x = srcPts[srcOff  ];
         final double y = srcPts[srcOff+1];
         final double xi = (x - xOrigin) * scaleX;
         final double yi = (y - yOrigin) * scaleY;
         final int col = Math.max(Math.min((int) xi, width  - 2), 0);
         final int row = Math.max(Math.min((int) yi, height - 2), 0);
         final int offset00 = col + row*width;
         final int offset01 = offset00 + width;
         final int offset10 = offset00 + 1;
         final int offset11 = offset01 + 1;
         final double dx = xi - col;
         final double dy = yi - row;
         final int dstDim = grid.getNumBanks();
         final Matrix derivative = derivate ? Matrices.createDiagonal(dstDim, srcDim) : null;
         for (int j=0; j<dstDim; j++) {
             final double v00 = (grid.getElemDouble(j, offset00));
             final double v01 = (grid.getElemDouble(j, offset01));
             final double v10 = (grid.getElemDouble(j, offset10));
             final double v11 = (grid.getElemDouble(j, offset11));
             if (derivative != null) {
                 double dxj = (v10 - v00); dxj += ((v11 - v01) - dxj) * dy;
                 double dyj = (v01 - v00); dyj += ((v11 - v10) - dyj) * dx;
                 switch (type) {
                     case NTv2:
                     case NADCON: {
                         dxj /= -3600;
                         dyj /= +3600;
                         break;
                     }
                 }
                 derivative.setElement(j, 0, dxj);
                 derivative.setElement(j, 1, dyj);
             }
             if (dstPts != null) {
                 final double v0  = (v10 - v00) * dx + v00;
                 final double v1  = (v11 - v01) * dx + v01;
                 double value = v0 + (v1-v0) * dy;
                 switch (type) {
                     case OFFSET: {
                         switch (j) {
                             case 0: value += x; break;
                             case 1: value += y; break;
                         }
                         break;
                     }
                     case NTv2:
                     case NADCON: {
                         switch (j) {
                             case 0: value = x - value/3600; break;
                             case 1: value = y + value/3600; break;
                         }
                         break;
                     }
                 }
                 dstPts[dstOff++] = value;
             }
         }
         return derivative;
     }
transform() [3/7]
void transform (final double [] srcPts, int srcOff, final double [] dstPts, int dstOff, int numPts)
Transforms a source coordinate into target coordinate.
The transformation will involve bilinear interpolations if the source coordinates are not integer values.
Parameters
srcPts The source coordinates.
srcOff Index of the first valid ordinate in the
srcPts
array.
dstPts Where to store the target coordinates.
dstOff Index where to store the first ordinate.
References GridTransform.transform().
     {
         transform(null, srcPts, srcOff, null, dstPts, dstOff, numPts);
     }
transform() [4/7]
void transform (final float [] srcPts, int srcOff, final float [] dstPts, int dstOff, int numPts)
Transforms a source coordinate into target coordinate.
The transformation will involve bilinear interpolations if the source coordinates are not integer values.
Parameters
srcPts The source coordinates.
srcOff Index of the first valid ordinate in the
srcPts
array.
dstPts Where to store the target coordinates.
dstOff Index where to store the first ordinate.
References GridTransform.transform().
     {
         transform(srcPts, null, srcOff, dstPts, null, dstOff, numPts);
     }
transform() [5/7]
void transform (final double [] srcPts, int srcOff, final float [] dstPts, int dstOff, int numPts)
Transforms a source coordinate into target coordinate.
The transformation will involve bilinear interpolations if the source coordinates are not integer values.
Parameters
srcPts The source coordinates.
srcOff Index of the first valid ordinate in the
srcPts
array.
dstPts Where to store the target coordinates.
dstOff Index where to store the first ordinate.
References GridTransform.transform().
     {
         transform(null, srcPts, srcOff, dstPts, null, dstOff, numPts);
     }
transform() [6/7]
void transform (final float [] srcPts, int srcOff, final double [] dstPts, int dstOff, int numPts)
Transforms a source coordinate into target coordinate.
The transformation will involve bilinear interpolations if the source coordinates are not integer values.
Parameters
srcPts The source coordinates.
srcOff Index of the first valid ordinate in the
srcPts
array.
dstPts Where to store the target coordinates.
dstOff Index where to store the first ordinate.
References GridTransform.transform().
     {
         transform(srcPts, null, srcOff, null, dstPts, dstOff, numPts);
     }
transform() [7/7]
void transform (float [] srcPts1, double [] srcPts2, int srcOff, float [] dstPts1, double [] dstPts2, int dstOff, int numPts) private
Implementation of direct transformation.
References GridTransform.srcDim, GridTransform.width, GridTransform.xOrigin, and GridTransform.yOrigin.
     {
         final int maxCol = width  - 2;
         final int maxRow = height - 2;
         final int dstDim = grid.getNumBanks();
         /*
          * Determine how to iterate over the coordinates in the special case where some values
          * overlap. For example we may iterate in reverse order (from higher index to lower index),
          * or we may compute the target coordinates in a temporary buffer to be copied later.
          */
         int offFinal = 0;
         Object dstFinal = null;
         boolean descending = false;
         if ((srcPts2 != null) ? srcPts2 == dstPts2 : srcPts1 == dstPts1) {
             switch (IterationStrategy.suggest(srcOff, srcDim, dstOff, dstDim, numPts)) {
                 case ASCENDING: {
                     break;
                 }
                 case DESCENDING: {
                     srcOff += (numPts-1)*srcDim;
                     dstOff += (numPts-1)*dstDim;
                     descending = true;
                     break;
                 }
                 default: // Following is a reasonable default for any unknown cases.
                 case BUFFER_SOURCE: {
                     final int upper = srcOff + numPts*srcDim;
                     if (srcPts1 != null) {
                         srcPts1 = Arrays.copyOfRange(srcPts1, srcOff, upper);
                     } else {
                         srcPts2 = Arrays.copyOfRange(srcPts2, srcOff, upper);
                     }
                     srcOff = 0;
                     break;
                 }
                 case BUFFER_TARGET: {
                     final int length = numPts * dstDim;
                     if (dstPts1 != null) {
                         dstFinal = dstPts1;
                         dstPts1 = new float[length];
                     } else {
                         dstFinal = dstPts2;
                         dstPts2 = new double[length];
                     }
                     offFinal = dstOff;
                     dstOff = 0;
                     break;
                 }
             }
         }
         /*
          * Now process to the interpolations. Note that this code has similarities with the
          * implementation of derivative(DirectPosition) method. Same variable names are used
          * on purpose, for making comparisons easier.
          */
         while (--numPts >= 0) {
             final double x, y;
             if (srcPts2 != null) {
                 x = srcPts2[srcOff++];
                 y = srcPts2[srcOff++];
             } else {
                 x = srcPts1[srcOff++];
                 y = srcPts1[srcOff++];
             }
             final double xi = (x - xOrigin) * scaleX;
             final double yi = (y - yOrigin) * scaleY;
             final int col = Math.max(Math.min((int) xi, maxCol), 0);
             final int row = Math.max(Math.min((int) yi, maxRow), 0);
             final int offset00 = col + row*width;
             final int offset01 = offset00 + width; // Une ligne plus bas
             final int offset10 = offset00 + 1;     // Une colonne à droite
             final int offset11 = offset01 + 1;     // Une colonne à droite, une ligne plus bas
             final double dx = xi - col;
             final double dy = yi - row;
             for (int j=0; j<dstDim; j++) {
                 final double v00 = (grid.getElemDouble(j, offset00));
                 final double v01 = (grid.getElemDouble(j, offset01));
                 final double v0  = (grid.getElemDouble(j, offset10) - v00) * dx + v00;
                 final double v1  = (grid.getElemDouble(j, offset11) - v01) * dx + v01;
                 double value = v0 + (v1-v0) * dy;
                 switch (type) {
                     case OFFSET: {
                         switch (j) {
                             case 0: value += x; break;
                             case 1: value += y; break;
                         }
                         break;
                     }
                     case NTv2:
                     case NADCON: {
                         switch (j) {
                             case 0: value = x - value/3600; break;
                             case 1: value = y + value/3600; break;
                         }
                         break;
                     }
                 }
                 if (dstPts2 != null) {
                     dstPts2[dstOff++] = value;
                 } else {
                     dstPts1[dstOff++] = (float) value;
                 }
             }
             if (descending) {
                 srcOff -= 2*srcDim;
                 dstOff -= 2*dstDim;
             }
         }
         /*
          * At this point the interpolations are completed. However if we stored the values
          * in a temporary array, then we need to copy them to their final location now.
          */
         if (dstFinal != null) {
             final int length;
             final Object dstPts;
             if (dstPts1 != null) {
                 dstPts = dstPts1;
                 length = dstPts1.length;
             } else {
                 dstPts = dstPts2;
                 length = dstPts2.length;
             }
             System.arraycopy(dstPts, 0, dstFinal, offFinal, length);
         }
     }
writeObject()
void writeObject (final ObjectOutputStream out) throws IOException private
Serializes this grid.
This method processes grid in a special way because the default JDK implementations are not serializable.
{
         out.defaultWriteObject();
         final int size = grid.getSize();
         final int[] offsets = grid.getOffsets();
         final Class<? extends DataBuffer> type = grid.getClass();
         final Object data; // Assigned to DataBuffer.getBankData(), which returns a clone.
         try {
             data = type.getMethod("getBankData", (Class<?>[]) null).invoke(grid, (Object[]) null);
             for (int i=Array.getLength(data); --i>=0;) {
                 Object bank = Array.get(data, i);
                 final int offset = offsets[i];
                 if (offset != 0 || Array.getLength(bank) != size) {
                     final Object original = bank;
                     bank = Array.newInstance(original.getClass().getComponentType(), size);
                     System.arraycopy(original, offset, bank, 0, size);
                     Array.set(data, i, bank);
                 }
             }
         } catch (ReflectiveOperationException e) {
             NotSerializableException exception = new NotSerializableException(type.getCanonicalName());
             exception.initCause(e);
             throw exception;
         }
         out.writeObject(type);
         out.writeObject(data);
     }
Member Data Documentation
grid
final transient DataBuffer grid protected
The grid of values.
The DataBuffer::getSize size} is equal to the product of the width} and height}. The number of banks determines the getTargetDimensions target dimension}, which is typically 2. The buffer type is typically DataBufferFloat or DataBufferDouble, but is not restricted to.
When a
transform
method is invoked, a target value is interpolated for every banks in the data buffer. Values in each data buffer bank are stored in row-major order.
Referenced by GridTransform.equals(), and GridTransform.GridTransform().
height
final int height protected
Number of rows in the grid.
Referenced by GridTransform.equals(), GridTransform.GridTransform(), and GridTransform.readObject().
scaleX
final double scaleX private
The scale factor by which to multiply the "real world" coordinate in order to get the grid coordinate.
Referenced by GridTransform.equals().
scaleY
final double scaleY package
Referenced by GridTransform.equals().
serialVersionUID
final long serialVersionUID = -7973466015425546562L static private
Serial number for inter-operability with different versions.
srcDim
final int srcDim = 2 static private
Number of source dimensions.
Referenced by GridTransform.getSourceDimensions(), and GridTransform.transform().
type
final GridType type package
Whatever the grid values are directly the target coordinates or offsets to apply on source coordinates.
Referenced by GridTransform.GridTransform(), and GridTransform2D.inverse().
width
final int width protected
Number of columns in the grid.
Referenced by GridTransform.equals(), and GridTransform.transform().
xOrigin
final double xOrigin private
The "real world" coordinate which correspond to the (0,0) grid coordinate.
Referenced by GridTransform.equals(), and GridTransform.transform().
yOrigin
final double yOrigin package
Referenced by GridTransform.equals(), and GridTransform.transform().