jena-geo: AbstractMathTransform Class Reference
AbstractMathTransform Class Reference abstract
Classes
class Inverse
Default implementation for inverse math transform.
Public Member Functions
String getName ()
Returns a name for this math transform (never.
Point2D transform (final Point2D ptSrc, final Point2D ptDst) throws TransformException
Transforms the specified.
Shape createTransformedShape (final Shape shape) throws TransformException
Transform the specified shape.
Matrix derivative (final Point2D point) throws TransformException
Gets the derivative of this transform at a point.
String formatTo (Formatter formatter)
Protected Member Functions
AbstractMathTransform ()
Constructs a math transform.
Static Protected Member Functions
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException
Makes sure that an argument is non-null.
Static Package Functions
static String mismatchedDimension (final String argument, final int dimension, final int expected)
Constructs an error message for the MismatchedDimensionException.
Detailed Description
Deprecated:
Moved to Apache SIS as org.apache.sis.referencing.operation.transform.AbstractMathTransform.
{
transforms}
AbstractMathTransform
implements also the methods required by the MathTransform2D interface, but does not implements that interface directly. Subclasses must add the "@code implements MathTransform2D @endcode " clause themselves, or extend the AbstractMathTransform2D base class, if they know to map two-dimensional coordinate systems.
Constructor & Destructor Documentation
AbstractMathTransform()
AbstractMathTransform () protected
Constructs a math transform.
{
     }
Member Function Documentation
createTransformedShape()
Shape createTransformedShape (final Shape shape) throws TransformException
Transform the specified shape.
The default implementation computes quadratic curves using three points for each line segment in the shape. The returned object is often a Path2D, but may also be a Line2D or a QuadCurve2D if such simplification is possible.
Parameters
shape Shape to transform.
Returns
Transformed shape, or
shape
if this transform is the identity transform.
Exceptions
IllegalStateException if this transform doesn't map 2D coordinate systems.
TransformException if a transform failed.
See also
MathTransform2D::createTransformedShape(Shape)
References AbstractMathTransform.mismatchedDimension().
{
         int dim;
         if ((dim = getSourceDimensions()) != 2 || (dim = getTargetDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("shape", 2, dim));
         }
         if (isIdentity()) return shape;
         try {
             final Method method = org.apache.sis.referencing.operation.transform.AbstractMathTransform2D.class.getMethod(
                     "createTransformedShape", MathTransform2D.class, Shape.class, AffineTransform.class, AffineTransform.class, Boolean.TYPE);
             method.setAccessible(true);
             return (Shape) method.invoke(null, (MathTransform2D) this, shape, null, null, false);
         } catch (ReflectiveOperationException e) {
             throw new TransformException(e);
         }
     }
derivative()
Matrix derivative (final Point2D point) throws TransformException
Gets the derivative of this transform at a point.
The default implementation performs the following steps:
Ensure that this math transform #getSourceDimensions() source dimensions} is equals to 2. Note that the #getTargetDimensions() target dimensions} can be anything, not necessarily 2 (so this transform doesn't need to implement the MathTransform2D interface).
Copy the coordinate in a temporary array and pass that array to the transform(double[], int, double[], int, boolean) method, with the
derivate
boolean argument set to
true
.
If the later method returned a non-null matrix, returns that matrix. Otherwise throws TransformException.
Parameters
point The coordinate point where to evaluate the derivative.
Returns
The derivative at the specified point as a 2×2 matrix.
Exceptions
MismatchedDimensionException if the input dimension is not 2.
TransformException if the derivative can't be evaluated at the specified point.
See also
MathTransform2D::derivative(Point2D)
References Errors.Keys.CantComputeDerivative, Errors.format(), AbstractMathTransform.mismatchedDimension(), and AbstractMathTransform.transform().
Referenced by AbstractMathTransform.Inverse.derivative(), and GridTransform.transform().
{
         final int dimSource = getSourceDimensions();
         if (dimSource != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("point", 2, dimSource));
         }
         final double[] coordinate = new double[] {point.getX(), point.getY()};
         final Matrix derivative = transform(coordinate, 0, null, 0, true);
         if (derivative == null) {
             throw new TransformException(Errors.format(Errors.Keys.CantComputeDerivative));
         }
         return derivative;
     }
ensureNonNull()
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException static protected
Makes sure that an argument is non-null.
This is a convenience method for subclass constructors.
Parameters
name Argument name.
object User argument.
Exceptions
InvalidParameterValueException if
object
is null.
References Errors.format(), and Errors.Keys.NullArgument_1.
Referenced by EarthGravitationalModel.EarthGravitationalModel().
     {
         if (object == null) {
             throw new InvalidParameterValueException(Errors.format(
                         Errors.Keys.NullArgument_1, name), name, object);
         }
     }
formatTo()
String formatTo (Formatter formatter)
{
         return super.formatTo(formatter);
     }
getName()
String getName ()
Returns a name for this math transform (never.
null
). This convenience methods returns the name of the #getParameterDescriptors parameter descriptors} if any, or the short class name otherwise.
Returns
A name for this math transform (never
null
).
Since
2.5
Referenced by AbstractMathTransform.Inverse.getName().
{
         final ParameterDescriptorGroup descriptor = getParameterDescriptors();
         if (descriptor != null) {
             final Identifier identifier = descriptor.getName();
             if (identifier != null) {
                 final String code = identifier.getCode();
                 if (code != null) {
                     return code;
                 }
             }
         }
         return Classes.getShortClassName(this);
     }
mismatchedDimension()
static String mismatchedDimension (final String argument, final int dimension, final int expected) static package
Constructs an error message for the MismatchedDimensionException.
CAUTION: Argument order is different than in Apache SIS.
Parameters
argument The argument name with the wrong number of dimensions.
dimension The wrong dimension.
expected The expected dimension.
References Errors.format(), and Errors.Keys.MismatchedDimension_3.
Referenced by AbstractMathTransform.createTransformedShape(), AbstractMathTransform.derivative(), and AbstractMathTransform.transform().
{
         return Errors.format(Errors.Keys.MismatchedDimension_3, argument, dimension, expected);
     }
transform()
Point2D transform (final Point2D ptSrc, final Point2D ptDst) throws TransformException
Transforms the specified.
ptSrc
and stores the result in
ptDst
. The default implementation performs the following steps:
Ensures that the #getSourceDimensions() source} and #getTargetDimensions() target dimensions} of this math transform are equal to 2.
Delegates to the transform(double[],int,double[],int,boolean) method using a temporary array of doubles.
Parameters
ptSrc The coordinate point to be transformed.
ptDst The coordinate point that stores the result of transforming
ptSrc
, or
null
if a new point should be created.
Returns
The coordinate point after transforming
ptSrc
and storing the result in
ptDst
, or in a new point if
ptDst
was null.
Exceptions
MismatchedDimensionException If this transform doesn't map two-dimensional coordinate systems.
TransformException If the point can't be transformed.
See also
MathTransform2D::transform(Point2D,Point2D)
References AbstractMathTransform.mismatchedDimension().
Referenced by AbstractMathTransform.derivative().
{
         int dim;
         if ((dim = getSourceDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("ptSrc", 2, dim));
         }
         if ((dim = getTargetDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("ptDst", 2, dim));
         }
         final double[] ord = new double[] {ptSrc.getX(), ptSrc.getY()};
         transform(ord, 0, ord, 0, false);
         if (ptDst != null) {
             ptDst.setLocation(ord[0], ord[1]);
             return ptDst;
         } else {
             return new Point2D.Double(ord[0], ord[1]);
         }
     }