jena-geo: LambertAzimuthalEqualArea Class Reference
LambertAzimuthalEqualArea Class Reference
<cite>Lambert Azimuthal Equal Area</cite> projection (EPSG codes 9820, 1027, <del>9821</del>).
Classes
class Spherical
Provides the transform equations for the spherical case.
Public Member Functions
ParameterDescriptorGroup getParameterDescriptors ()
Returns the parameter descriptors for this unitary projection.
Matrix transform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
Converts the specified (λ,φ) coordinate (units in radians) and stores the result in.
boolean equals (final Object object, final ComparisonMode mode)
Compares the given object with this transform for equivalence.
Static Public Member Functions
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values)
Creates an Albers Equal Area projection from the given parameters.
Protected Member Functions
LambertAzimuthalEqualArea (final OperationMethod method, final Parameters parameters)
Constructs a new map projection from the supplied parameters.
void inverseTransform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff) throws ProjectionException
Transforms the specified (x,y) coordinates and stores the result in.
Package Functions
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor)
final double msfn (final double sinφ, final double cosφ)
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
final double ssfn (double φ, double sinφ)
Computes part of function (3-1) from Snyder.
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ)
Computes the derivative of the ssfn(double, double) method divided by.
final double qsfn (final double sinφ)
Calculates q, Snyder equation (3-12).
final double dqsfn_dφ (final double sinφ, final double cosφ)
Gets the derivative of the qsfn(double) method.
Static Package Functions
static boolean isSpherical (final Parameters parameters)
Package Attributes
final boolean pole
final boolean north
If.
final boolean oblique
If.
final double latitudeOfOrigin
Latitude of origin, in radians.
final double sinb1
Parameters derived from the latitude of origin and the eccentricity.
final double cosb1
final double qp
Constant parameters.
final double rq
final double APA1
final double APA2
Static Package Attributes
static final double P01 = 0.17222222222222222222
static final double P02 = 0.10257936507936507936
static final double P10 = 0.06388888888888888888
static final double P11 = 0.06640211640211640211
static final double P20 = 0.01641501294219154443
static final double ANGLE_TOLERANCE = 1E-6
Maximum difference allowed when comparing longitudes or latitudes in radians.
static final double ITERATION_TOLERANCE = 1E-10
Difference allowed in iterative computations.
static final int MAXIMUM_ITERATIONS = 15
Maximum number of iterations for iterative computations.
Private Attributes
final double APA0
Coefficients for authalic latitude.
Static Private Attributes
static final long serialVersionUID = 1639914708790574760L
For cross-version compatibility.
static final double EPSILON = 1E-10
Epsilon for the comparison of small quantities.
static final double P00 = 0.33333333333333333333
Constants for authalic latitude.
Detailed Description
<cite>Lambert Azimuthal Equal Area</cite> projection (EPSG codes 9820, 1027, <del>9821</del>).
See the Lambert Azimuthal Equal-Area projection on MathWorld for an overview. See any of the following providers for a list of programmatic parameters:
org.geotoolkit.referencing.operation.provider.LambertAzimuthalEqualArea
{
}
A. Annoni, C. Luzet, E.Gubler and J. Ihde - Map Projections for Europe
John P. Snyder (Map Projections - A Working Manual,
U.S. Geological Survey Professional Paper 1395)
Author
Gerald Evenden (USGS)
Beate Stollberg
Martin Desruisseaux (IRD, Geomatys)
Rémi Maréchal (Geomatys)
Since
2.4
Constructor & Destructor Documentation
LambertAzimuthalEqualArea()
LambertAzimuthalEqualArea (final OperationMethod method, final Parameters parameters) protected
Constructs a new map projection from the supplied parameters.
Parameters
parameters The parameters of the projection to be created.
References LambertAzimuthalEqualArea.cosb1, LambertAzimuthalEqualArea.EPSILON, UnitaryProjection.getAndStore(), UnitaryProjection.isSpherical(), LambertAzimuthalEqualArea.LATITUDE_OF_CENTRE, LambertAzimuthalEqualArea.P01, LambertAzimuthalEqualArea.P02, LambertAzimuthalEqualArea.P10, LambertAzimuthalEqualArea.P11, LambertAzimuthalEqualArea.P20, LambertAzimuthalEqualArea.qp, and UnitaryProjection.qsfn().
Referenced by LambertAzimuthalEqualArea.create(), and LambertAzimuthalEqualArea.equals().
{
         super(method, parameters, null);
         /*
          * Detects the mode (oblique, etc.).
          */
         latitudeOfOrigin = toRadians(getAndStore(parameters, org.geotoolkit.referencing.operation.provider.LambertAzimuthalEqualArea.LATITUDE_OF_CENTRE));
         final double t = abs(latitudeOfOrigin);
         if (abs(t - PI/2) < EPSILON) {
             pole    = true;
             north   = (latitudeOfOrigin >= 0.0);
             oblique = false;
         } else {
             pole    = false;
             north   = false;
             oblique = (abs(t) >= EPSILON);
         }
         /*
          * Computes the constants for authalic latitude. Those constants depend
          * only on the eccentricity. Note that in the spherical cases:
          *
          *   - All APA coefficients simplifies to zero.
          *   - qp = 2  (result of qsfn(1) when e² = 0).
          *   - rq = 1  (concequence of the above).
          */
         final double es2 = eccentricitySquared * eccentricitySquared;
         final double es3 = eccentricitySquared * es2;
         APA0 = P02 * es3 + P01 * es2 + P00 * eccentricitySquared;
         APA1 = P11 * es3 + P10 * es2;
         APA2 = P20 * es3;
         qp   = qsfn(1);
         rq   = sqrt(0.5 * qp);
         /*
          * Now computes the coefficients that depend on the latitude of origin.
          * Note that in the equatorial case:
          *
          *     - sinb1 = 0
          *     - cosb1 = 1
          *
          * The polar case is sinb1 = 2/qp for North, -2/qp for South.
          */
         final double sinφ = sin(latitudeOfOrigin);
         final boolean isSpherical = (this instanceof Spherical);
         if (isSpherical) {
             sinb1 = sinφ;
             cosb1 = cos(latitudeOfOrigin);
         } else {
             sinb1 = qsfn(sinφ) / qp;
             cosb1 = sqrt(1.0 - sinb1 * sinb1);
         }
         /*
          * At this point, all parameters have been processed. Now process to their
          * validation and the initialization of (de)normalize affine transforms.
          */
         final MatrixSIS   normalize = getContextualParameters().getMatrix(MatrixRole.NORMALIZATION);
         final MatrixSIS denormalize = getContextualParameters().getMatrix(MatrixRole.DENORMALIZATION);
         if (north) {
             normalize  .convertBefore(1, -1, null);
             denormalize.convertBefore(1, -1, null);
         } else if (!isSpherical) {
             if (oblique) {
                 /*
                  * Conceptually we can consider that this block is executed for all oblique cases,
                  * including spherical. However in the spherical case, the equation simplifies to
                  * dd = 1/rq. With rq = 1 (see above), we get dd = 1.
                  */
                 final double dd = cos(latitudeOfOrigin) / (sqrt(1 - eccentricitySquared*(sinφ*sinφ))*rq*cosb1);
                 denormalize.convertBefore(0,   dd, null);
                 denormalize.convertBefore(1, 1/dd, null);
             } else {
                 /*
                  * In the equatorial case the above equation simplify to dd = 1/rq. However the
                  * equatorial case is treated differently, so we do not put those coefficients
                  * in the affine transform.
                  */
             }
         }
     }
Member Function Documentation
create()
static MathTransform2D create (final OperationMethod descriptor, final ParameterValueGroup values) static
Creates an Albers Equal Area projection from the given parameters.
The descriptor argument is usually org.geotoolkit.referencing.operation.provider.LambertAzimuthalEqualArea#PARAMETERS, but is not restricted to. If a different descriptor is supplied, it is user's responsibility to ensure that it is suitable to a Lambert Azimuthal Equal Area projection.
Parameters
descriptor Typically
LambertAzimuthalEqualArea.PARAMETERS
.
values The parameter values of the projection to create.
Returns
The map projection.
Since
3.00
References UnitaryProjection.isSpherical(), and LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
Referenced by LambertAzimuthalEqualArea.createMathTransform().
     {
         final Parameters parameters = Parameters.castOrWrap(values);
         final LambertAzimuthalEqualArea projection;
         if (isSpherical(parameters)) {
             projection = new Spherical(descriptor, parameters);
         } else {
             projection = new LambertAzimuthalEqualArea(descriptor, parameters);
         }
         try {
             return (MathTransform2D) projection.createMapProjection(
                     org.apache.sis.internal.system.DefaultFactories.forBuildin(
                             org.opengis.referencing.operation.MathTransformFactory.class));
         } catch (org.opengis.util.FactoryException e) {
             throw new IllegalArgumentException(e); // TODO
         }
     }
dqsfn_dφ()
final double dqsfn_dφ (final double sinφ, final double cosφ) package inherited
Gets the derivative of the qsfn(double) method.
Parameters
sinφ The sine of latitude.
cosφ The cosines of latitude.
Returns
The
qsfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by LambertAzimuthalEqualArea.transform().
{
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         double esinφ2 = eccentricity * sinφ;
         esinφ2 *= esinφ2;
         return (1 - eccentricitySquared) * (cosφ / (1 - esinφ2)) * (1 + ((1 + esinφ2) / (1 - esinφ2)));
     }
dssfn_dφ()
final double dssfn_dφ (final double φ, final double sinφ, final double cosφ) package inherited
Computes the derivative of the ssfn(double, double) method divided by.
ssfn
. Callers must multiply the return value by
ssfn
in order to get the actual value.
Parameters
φ The latitude.
sinφ the sine of latitude.
cosφ The cosine of latitude.
Returns
The
dssfn
derivative at the specified latitude.
Since
3.18
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         assert !(abs(cosφ - cos(φ)) > ARGUMENT_TOLERANCE) : φ;
         return (1/cosφ) - (eccentricitySquared*cosφ)/(1-eccentricitySquared*sinφ*sinφ);
         /*
          * NOTE: 0.5*(t + 1/t)   =   1/cosφ
          */
     }
equals()
boolean equals (final Object object, final ComparisonMode mode)
Compares the given object with this transform for equivalence.
References LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.latitudeOfOrigin.
{
         if (super.equals(object, mode)) {
             final LambertAzimuthalEqualArea that = (LambertAzimuthalEqualArea) object;
             return epsilonEqual(this.latitudeOfOrigin, that.latitudeOfOrigin, mode);
             // All other coefficients are derived from the latitude of origin and eccentricity.
         }
         return false;
     }
getAndStore()
final double getAndStore (final Parameters parameters, final ParameterDescriptor< Double > descriptor) package inherited
Referenced by CassiniOrMercator.CassiniOrMercator(), Krovak.Krovak(), LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), NewZealandMapGrid.NewZealandMapGrid(), Orthographic.Orthographic(), and Stereographic.Stereographic().
{
         final double value = parameters.doubleValue(descriptor);    // Apply a unit conversion if needed.
         final Double defaultValue = descriptor.getDefaultValue();
         if (defaultValue == null || !defaultValue.equals(value)) {
             org.apache.sis.internal.referencing.provider.MapProjection.validate(descriptor, value);
             String name = IdentifiedObjects.getName(descriptor, parameters.getDescriptor().getName().getAuthority());
             if (name == null) {
                 name = descriptor.getName().getCode();
             }
             getContextualParameters().parameter(name).setValue(value);
         }
         return value;
     }
getParameterDescriptors()
ParameterDescriptorGroup getParameterDescriptors ()
Returns the parameter descriptors for this unitary projection.
Note that the returned descriptor is about the unitary projection, not the full one.
References LambertAzimuthalEqualArea.PARAMETERS.
{
         return org.geotoolkit.referencing.operation.provider.LambertAzimuthalEqualArea.PARAMETERS;
     }
inverseTransform()
void inverseTransform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff) throws ProjectionException protected
Transforms the specified (x,y) coordinates and stores the result in.
dstPts
(angles in radians).
References UnitaryProjection.ANGLE_TOLERANCE, LambertAzimuthalEqualArea.latitudeOfOrigin, and LambertAzimuthalEqualArea.rq.
     {
         double x = srcPts[srcOff  ];
         double y = srcPts[srcOff+1];
         final double ab;
         if (pole) {
             // See comments in the transform(...) method for an explanation about why we
             // don't need a special case for the North pole. Similar rational applies here.
             ab = (x*x + y*y)/qp - 1;
         } else {
             /*
              * (x /= dd) and (y *= dd) have been performed by the affine transform, but only in
              * the oblique case. For the equatorial case we need to apply it ourself.  Reminder
              * from the constructor: dd = 1/rd in the equatorial case.
              */
             if (!oblique) {
                 x *= rq;
                 y /= rq;
             }
             final double ρ = hypot(x, y);
             if (ρ < EPSILON) {
                 // This check is required because otherwise, the equations
                 // in the "else" block would contains 0/0 expressions.
                 dstPts[dstOff] = 0.0;
                 dstPts[dstOff + 1] = latitudeOfOrigin;
                 return;
             }
             double sCe, cCe;
             sCe = 2.0 * asin(0.5 * ρ / rq);
             cCe = cos(sCe);
             sCe = sin(sCe);
             x *= sCe;
             if (oblique) {
                 ab = cCe * sinb1 + y * sCe * cosb1 / ρ;
                 y  = ρ * cosb1 * cCe - y * sinb1 * sCe;
             } else {
                 ab = y * sCe / ρ;
                 y  = ρ * cCe;
             }
         }
         double t = abs(ab);
         if (t > 1 && t <= (1 + ANGLE_TOLERANCE)) {
             t = copySign(PI/2, ab);
         } else {
             t = asin(ab);
         }
         dstPts[dstOff+1] = t + APA0 * sin(t += t) + APA1 * sin(t += t) + APA2 * sin(t + t);
         dstPts[dstOff  ] = atan2(x, y);
     }
isSpherical()
static boolean isSpherical (final Parameters parameters) static package inherited
References UnitaryProjection.inverseTransform().
Referenced by CassiniSoldner.create(), Stereographic.create(), LambertAzimuthalEqualArea.create(), and LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
{
         return parameters.parameter("semi_major").doubleValue() == parameters.parameter("semi_minor").doubleValue();
     }
msfn()
final double msfn (final double sinφ, final double cosφ) package inherited
Computes function f(s,c,e²) = c/sqrt(1 - s²×e²) needed for the true scale latitude (Snyder 14-15), where s and c are the sine and cosine of the true scale latitude, and e² is the #eccentricitySquared eccentricity squared}.
Special cases:
If φ is 0°, then this method returns 1.
If φ is ±90°, then this method returns 0 provided that we are not in the spherical case (otherwise we get Double#NaN).
Parameters
sinφ The sine of the φ latitude in radians.
cosφ The cosine of the φ latitude in radians.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic().
                                                               {               // == cosφ / rν(sinφ)
         assert !(abs(sinφ*sinφ + cosφ*cosφ - 1) > ARGUMENT_TOLERANCE);
         return cosφ / sqrt(1.0 - (sinφ*sinφ) * eccentricitySquared);
     }
qsfn()
final double qsfn (final double sinφ) package inherited
Calculates q, Snyder equation (3-12).
This equation has the following properties:
Input in the [-1 ... +1] range.
Output in the [-2 ... +2] range.
Output is 0 when input is 0.
Output of the same sign than input.
qsfn(-sinφ) == -qsfn(sinφ)
.
Parameters
sinφ Sine of the latitude q is calculated for.
Returns
q from Snyder equation (3-12).
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.transform().
{
         if (eccentricity < EPSILON) {
             return 2 * sinφ;
         }
         /*
          * Above check was required because the expression below would simplify to
          * sinφ - 0.5/0*log(1) where the right terms are infinity multiplied by
          * zero, thus producing NaN.
          */
         final double esinφ = eccentricity * sinφ;
         return (1 - eccentricitySquared) * (sinφ / (1 - esinφ*esinφ) + atanh(esinφ)/eccentricity);
     }
ssfn()
final double ssfn (double φ, double sinφ) package inherited
Computes part of function (3-1) from Snyder.
This is numerically equivalent to #tsfn tsfn}(-φ, sinφ), but is defined as a separated function for clarity and because the function properties are not the same.
Parameters
φ The latitude in radians.
sinφ The sine of the φ argument. This is provided explicitly because in many cases, the caller has already computed this value.
References UnitaryProjection.ARGUMENT_TOLERANCE.
Referenced by Stereographic.Stereographic(), EquatorialStereographic.transform(), and Stereographic.transform().
{
         assert !(abs(sinφ - sin(φ)) > ARGUMENT_TOLERANCE) : φ;
         sinφ *= eccentricity;
         return tan(PI/4 + 0.5*φ) * pow((1-sinφ) / (1+sinφ), 0.5*eccentricity);
     }
transform()
Matrix transform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff, final boolean derivate) throws ProjectionException
Converts the specified (λ,φ) coordinate (units in radians) and stores the result in.
dstPts
(linear distance on a unit sphere). In addition, opportunistically computes the projection derivative if
derivate
is
true
.
Since
3.20 (derived from 3.00)
References LambertAzimuthalEqualArea.cosb1, UnitaryProjection.dqsfn_dφ(), LambertAzimuthalEqualArea.qp, UnitaryProjection.qsfn(), and LambertAzimuthalEqualArea.sinb1.
     {
         final double λ = srcPts[srcOff];
         final double φ = srcPts[srcOff + 1];
         final double cosλ = cos(λ);
         final double sinλ = sin(λ);
         final double sinφ = sin(φ);
         final double q = qsfn(sinφ);
         final double b,c;
         double x, y;
         if (!pole) {
             final double sinb = q / qp;
             final double cosb = sqrt(1 - sinb*sinb);
             if (oblique) {
                 c = 1.0 + sinb * sinb1 + cosb * cosλ * cosb1;
                 y = rq * (sinb * cosb1 - cosb * cosλ * sinb1);
                 x = rq * cosb * sinλ;
                 // xmf was (rq * dd) and ymf was (rq / dd), but the
                 // dd part is now handled by the affine transform.
             } else {
                 c = 1.0 + cosb * cosλ;
                 y = sinb * (0.5*qp);
                 x = cosb * sinλ;
                 // Proj4 had (xmf, ymf) terms here, but xmf simplifies to (rq * 1/rq) == 1
                 // (see the comments in the constructor) and ymf simplify to rq² = 0.5*qp.
             }
             b = sqrt(2/c);
             x *= b;
             y *= b;
         } else {
             /*
              * Polar case. If this is the North case, then:
              *
              *  - Before this block, sign of φ has been reversed by the normalize affine
              *    transform. Concequence of the above, sign of q is also reversed.
              *
              *  - After this block, sign of y will be reversed by the denormalize affine
              *    transform, so it should not be reversed here.
              *
              * A little bit of algebra shows that the formulas become identical to the South case
              * exept for the sign of c (which doesn't matter), so only South case needs to be here.
              */
             c = φ - PI/2;
             b = sqrt(qp + q);
             /*
              * Proj4 tested for (qp + q) > 0, but this can be negative only if the given
              * latitude is greater (in absolute value) than 90°. By removing this check,
              * we let Java produces NaN in such cases, which is probably a right thing.
              */
             x = b * sinλ;
             y = b * cosλ;
         }
         if (abs(c) < EPSILON) {
             /*
              * Projecting the antipode of origin. For example if the origin is the North pole,
              * then projection of South pole would be all the points on the circle of radius 2.
              * We can not return a single point for that (or actually we could if we took the
              * longitude value in account despite the fact that all longitudes still at the same
              * point when the latitude is at a pole).
              */
             x = y = NaN;
         }
         if (dstPts != null) {
             dstPts[dstOff]   = x;
             dstPts[dstOff+1] = y;
         }
         if (!derivate) {
             return null;
         }
         //
         // End of map projection. Now compute the derivative.
         //
         final double cosφ  = cos(φ);
         final double dq_dφ = dqsfn_dφ(sinφ, cosφ);
         if (pole) {
             final double db_dφ = 0.5 * dq_dφ / b;
             return new Matrix2(y, db_dφ*sinλ,
                               -x, db_dφ*cosλ);
         }
         final double sinb      = q / qp;
         final double dsinb_dφ  = dq_dφ / qp;
         final double cosb      = sqrt(1.0 - sinb*sinb);
         final double dcosb_dφ  = -dsinb_dφ * (sinb/cosb);
         final double sinλcosb  = sinλ *  cosb;
         final double cosλcosb  = cosλ *  cosb;
         final double cosλdcosb = cosλ * dcosb_dφ;
         /*
          * In equatorial case, sinb1=0 and cosb1=1. We could do a special case
          * with the simplification, but the result is not that much simpler.
          */
         final double T     =    cosb1*sinb - sinb1*cosλcosb;
         final double dT_dλ =    sinb1*sinλcosb;
         final double db_dλ =    cosb1*sinλcosb / (2*c);
         final double dT_dφ =   (cosb1*dsinb_dφ - sinb1*cosλdcosb);
         final double db_dφ =  -(sinb1*dsinb_dφ + cosb1*cosλdcosb) / (2*c);
         final double f     =    2*rq / sqrt(2*c);
         return new Matrix2(
                 f * (cosλ     + db_dλ*sinλ)*cosb,
                 f * (dcosb_dφ + db_dφ*cosb)*sinλ,
                 f * (dT_dλ    + db_dλ*T),
                 f * (dT_dφ    + db_dφ*T));
     }
Member Data Documentation
ANGLE_TOLERANCE
final double ANGLE_TOLERANCE = 1E-6 static package inherited
Maximum difference allowed when comparing longitudes or latitudes in radians.
A tolerance of 1E-6 is about 0.2 second of arcs, which is about 6 kilometers (computed from the standard length of nautical mile).
Some formulas use this tolerance value for testing sinus or cosinus of an angle. In the sinus case, this is justified because sin(θ) ≅ θ when θ is small. Similar reasoning applies to cosinus with cos(θ) ≅ θ + π/2 when θ is small.
Referenced by Stereographic.create(), Orthographic.inverseTransform(), LambertAzimuthalEqualArea.inverseTransform(), Orthographic.Orthographic(), and Stereographic.Stereographic().
APA0
final double APA0 private
Coefficients for authalic latitude.
They depend only on the eccentricity, not on the latitude of origin. They are all zero in the spherical case.
APA1
final double APA1 package
APA2
final double APA2 package
cosb1
final double cosb1 package
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.transform().
EPSILON
final double EPSILON = 1E-10 static private
Epsilon for the comparison of small quantities.
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.Spherical.transform().
ITERATION_TOLERANCE
final double ITERATION_TOLERANCE = 1E-10 static package inherited
Difference allowed in iterative computations.
A value of 1E-10 causes the cphi2 function to compute the latitude at a precision of 1E-10 radians, which is slightly smaller than one millimetre.
Referenced by CassiniOrMercator.inv_mlfn(), and Stereographic.inverseTransform().
latitudeOfOrigin
final double latitudeOfOrigin package
Latitude of origin, in radians.
Referenced by LambertAzimuthalEqualArea.equals(), LambertAzimuthalEqualArea.inverseTransform(), and LambertAzimuthalEqualArea.Spherical.inverseTransform().
MAXIMUM_ITERATIONS
final int MAXIMUM_ITERATIONS = 15 static package inherited
Maximum number of iterations for iterative computations.
Referenced by CassiniOrMercator.inv_mlfn(), Stereographic.inverseTransform(), and Krovak.inverseTransform().
north
final boolean north package
If.
pole
is
true
, then this field
true
is true for the North pole and
false
for the South pole.
oblique
final boolean oblique package
If.
pole
is
false
, then this field
true
is true for the oblique case and
false
for the equatorial case.
P00
final double P00 = 0.33333333333333333333 static private
Constants for authalic latitude.
P01
final double P01 = 0.17222222222222222222 static package
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
P02
final double P02 = 0.10257936507936507936 static package
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
P10
final double P10 = 0.06388888888888888888 static package
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
P11
final double P11 = 0.06640211640211640211 static package
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
P20
final double P20 = 0.01641501294219154443 static package
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea().
pole
final boolean pole package
true
if the projection is at a pole.
qp
final double qp package
Constant parameters.
They depend only on the eccentricity, not on the latitude of origin. Consequently they are not used in the spherical case.
Referenced by LambertAzimuthalEqualArea.LambertAzimuthalEqualArea(), and LambertAzimuthalEqualArea.transform().
rq
final double rq package
Referenced by LambertAzimuthalEqualArea.inverseTransform().
serialVersionUID
final long serialVersionUID = 1639914708790574760L static private
For cross-version compatibility.
sinb1
final double sinb1 package
Parameters derived from the latitude of origin and the eccentricity.
In the spherical case, they are straight sinus and cosinus of the latitude of origin.
Referenced by LambertAzimuthalEqualArea.Spherical.inverseTransform(), and LambertAzimuthalEqualArea.transform().