jena-geo: StorageEvent Class Reference
StorageEvent Class Reference abstract
Storage event.
Public Member Functions
StorageEvent (final Resource source)
abstract StorageEvent copy (Resource source)
Copy this event changing it's source.
Detailed Description
Storage event.
Author
Johann Sorel (Geomatys)
Constructor & Destructor Documentation
StorageEvent()
StorageEvent (final Resource source)
References StorageEvent.copy().
{
         super(source);
     }
Member Function Documentation
copy()
abstract StorageEvent copy (Resource source) abstract
Copy this event changing it's source.
Parameters
source new source
Returns
StorageEvent
Referenced by AbstractResource.forwardEvent(), and StorageEvent.StorageEvent().