jena-geo: IdentifierCode Class Reference
IdentifierCode Class Reference
A reference identifier for EPSG or GeoTiff codes.
Public Member Functions
boolean isDeprecated ()
Returns.
InternationalString getRemarks ()
Package Functions
IdentifierCode (final Citation authority, final int code)
Creates a new identifier for the given authority.
IdentifierCode (final Citation authority, final int code, final int supersededBy)
Creates a deprecated identifier for the given authority.
Package Attributes
final int supersededBy
If this identifier is deprecated, the identifier that supersede this one.
Static Private Member Functions
static String codespace (final Citation authority)
Returns the code space for the given authority.
static InternationalString remarks (final int supersededBy)
formats a "Superseded by" international string.
Static Private Attributes
static final long serialVersionUID = 357222258307746767L
For cross-version compatibility.
Detailed Description
A reference identifier for EPSG or GeoTiff codes.
Author
Martin Desruisseaux (Geomatys)
Version
3.03
Since
3.03
Constructor & Destructor Documentation
IdentifierCode() [1/2]
IdentifierCode (final Citation authority, final int code) package
Creates a new identifier for the given authority.
Parameters
authority Organization for definition and maintenance of the code space or code.
code Identifier code from the authority.
{
         this(authority, code, 0);
     }
IdentifierCode() [2/2]
IdentifierCode (final Citation authority, final int code, final int supersededBy) package
Creates a deprecated identifier for the given authority.
Parameters
authority Organization for definition and maintenance of the code space or code.
code Identifier code from the authority.
supersededBy The code that replace this one.
References IdentifierCode.codespace(), IdentifierCode.remarks(), and IdentifierCode.supersededBy.
{
         super(authority, codespace(authority), Integer.toString(code), null, remarks(supersededBy));
         this.supersededBy = supersededBy;
     }
Member Function Documentation
codespace()
static String codespace (final Citation authority) static private
Returns the code space for the given authority.
Referenced by IdentifierCode.IdentifierCode().
{
         if (authority != null) {
             String t = Citations.toCodeSpace(authority);
             if (t != null) {
                 return t.substring(t.lastIndexOf(':') + 1).trim();
             }
         }
         return null;
     }
getRemarks()
InternationalString getRemarks ()
{
         return super.getDescription();
     }
isDeprecated()
boolean isDeprecated ()
Returns.
true
if this code is deprecated.
{
         return supersededBy != 0;
     }
remarks()
static InternationalString remarks (final int supersededBy) static private
formats a "Superseded by" international string.
References Vocabulary.formatInternational(), and Vocabulary.Keys.SupersededBy_1.
Referenced by IdentifierCode.IdentifierCode().
{
         if (supersededBy == 0) {
             return null;
         }
         return Vocabulary.formatInternational(Vocabulary.Keys.SupersededBy_1, supersededBy);
     }
Member Data Documentation
serialVersionUID
final long serialVersionUID = 357222258307746767L static private
For cross-version compatibility.
supersededBy
final int supersededBy package
If this identifier is deprecated, the identifier that supersede this one.
Otherwise
0
.
Referenced by IdentifierCode.IdentifierCode().