jena-geo: GridTransform2D.Inverse Class Reference
GridTransform2D.Inverse Class Reference
Transforms target coordinates to source coordinates.
Public Member Functions
Matrix transform (final double[] srcPts, final int srcOff, final double[] dstPts, final int dstOff, final boolean derivate) throws TransformException
Transforms a single coordinate in a list of ordinal values, and optionally returns the derivative at that location.
MathTransform2D inverse ()
Returns the inverse of this transform.
String getName ()
Returns a name for this math transform (never.
int getSourceDimensions ()
Gets the dimension of input points.
int getTargetDimensions ()
Gets the dimension of output points.
Matrix derivative (final Point2D point) throws TransformException
Gets the derivative of this transform at a point.
Matrix derivative (final DirectPosition point) throws TransformException
Gets the derivative of this transform at a point.
boolean isIdentity ()
Tests whether this transform does not move any points.
boolean equals (final Object object, final ComparisonMode mode)
Compares the specified object with this inverse math transform for equality.
String formatTo (final Formatter formatter)
Formats the inner part of a Well Known Text (WKT) element.
Point2D transform (final Point2D ptSrc, final Point2D ptDst) throws TransformException
Transforms the specified.
Shape createTransformedShape (final Shape shape) throws TransformException
Transform the specified shape.
Protected Member Functions
int computeHashCode ()
Static Protected Member Functions
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException
Makes sure that an argument is non-null.
Package Functions
Inverse ()
Creates an inverse transform.
Static Package Functions
static String mismatchedDimension (final String argument, final int dimension, final int expected)
Constructs an error message for the MismatchedDimensionException.
Private Member Functions
void readObject (ObjectInputStream in) throws IOException, ClassNotFoundException
Restores reference to this object after deserialization.
Static Private Attributes
static final long serialVersionUID = -6779719408779847014L
Serial number for inter-operability with different versions.
static final double ITERATION_TOLERANCE = 5E-10
Difference allowed in iterative computations.
static final int MAXIMUM_ITERATIONS = 10
Maximum number of iterations for iterative computations.
Detailed Description
Transforms target coordinates to source coordinates.
This is done by iteratively finding a target coordinate that shifts to the input coordinate. The input coordinate is used as the first approximation.
This method is not applicable in the GridType#LOCALIZATION case.
Author
Rueben Schulz (UBC)
Martin Desruisseaux (IRD, Geomatys)
Version
3.00
Since
3.00
Constructor & Destructor Documentation
Inverse()
Inverse () package
Creates an inverse transform.
                   {
             GridTransform2D.this.super();
         }
Member Function Documentation
computeHashCode()
int computeHashCode () protected inherited
{
             return hash(AbstractMathTransform.this.hashCode(), super.computeHashCode());
         }
createTransformedShape()
Shape createTransformedShape (final Shape shape) throws TransformException inherited
Transform the specified shape.
The default implementation computes quadratic curves using three points for each line segment in the shape. The returned object is often a Path2D, but may also be a Line2D or a QuadCurve2D if such simplification is possible.
Parameters
shape Shape to transform.
Returns
Transformed shape, or
shape
if this transform is the identity transform.
Exceptions
IllegalStateException if this transform doesn't map 2D coordinate systems.
TransformException if a transform failed.
See also
MathTransform2D::createTransformedShape(Shape)
References AbstractMathTransform.mismatchedDimension().
{
         int dim;
         if ((dim = getSourceDimensions()) != 2 || (dim = getTargetDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("shape", 2, dim));
         }
         if (isIdentity()) return shape;
         try {
             final Method method = org.apache.sis.referencing.operation.transform.AbstractMathTransform2D.class.getMethod(
                     "createTransformedShape", MathTransform2D.class, Shape.class, AffineTransform.class, AffineTransform.class, Boolean.TYPE);
             method.setAccessible(true);
             return (Shape) method.invoke(null, (MathTransform2D) this, shape, null, null, false);
         } catch (ReflectiveOperationException e) {
             throw new TransformException(e);
         }
     }
derivative() [1/2]
Matrix derivative (final Point2D point) throws TransformException inherited
Gets the derivative of this transform at a point.
The default implementation computes the inverse of the matrix returned by the enclosing math transform.
References AbstractMathTransform.derivative().
Referenced by GridTransform2D.Inverse.transform().
{
             return MatrixSIS.castOrCopy(AbstractMathTransform.this.derivative(this.transform(point, null))).inverse();
         }
derivative() [2/2]
Matrix derivative (final DirectPosition point) throws TransformException inherited
Gets the derivative of this transform at a point.
The default implementation computes the inverse of the matrix returned by the enclosing math transform.
References AbstractMathTransform.derivative().
{
             return MatrixSIS.castOrCopy(AbstractMathTransform.this.derivative(this.transform(point, null))).inverse();
         }
ensureNonNull()
static void ensureNonNull (final String name, final Object object) throws InvalidParameterValueException static protected inherited
Makes sure that an argument is non-null.
This is a convenience method for subclass constructors.
Parameters
name Argument name.
object User argument.
Exceptions
InvalidParameterValueException if
object
is null.
References Errors.format(), and Errors.Keys.NullArgument_1.
Referenced by EarthGravitationalModel.EarthGravitationalModel().
     {
         if (object == null) {
             throw new InvalidParameterValueException(Errors.format(
                         Errors.Keys.NullArgument_1, name), name, object);
         }
     }
equals()
boolean equals (final Object object, final ComparisonMode mode) inherited
Compares the specified object with this inverse math transform for equality.
The default implementation tests if
object
in an instance of the same class than
this
, and if so compares their enclosing
AbstractMathTransform
.
References AbstractMathTransform.Inverse.enclosing(), and AbstractMathTransform.Inverse.Inverse().
{
             if (object == this) {
                 // Slight optimization
                 return true;
             }
             if (object != null && object.getClass() == getClass()) {
                 final Inverse that = (Inverse) object;
                 return AbstractMathTransform.this.equals(that.enclosing(), mode);
             } else {
                 return false;
             }
         }
formatTo()
String formatTo (final Formatter formatter) inherited
Formats the inner part of a Well Known Text (WKT) element.
If this inverse math transform has any parameter values, then this method format the WKT as in the AbstractMathTransform::formatWKT super-class method}. Otherwise this method format the math transform as an "INVERSE_MT" entity.
Parameters
formatter The formatter to use.
Returns
The WKT element name, which is
"PARAM_MT"
or
"INVERSE_MT"
in the default implementation.
{
             final ParameterValueGroup parameters = getParameterValues();
             if (parameters != null) {
                 WKTUtilities.appendParamMT(parameters, formatter);
                 return "PARAM_MT";
             } else {
                 formatter.append((FormattableObject) AbstractMathTransform.this);
                 return "INVERSE_MT";
             }
         }
getName()
String getName () inherited
Returns a name for this math transform (never.
null
). The default implementation returns the direct transform name concatenated with localized flavor (when available) of "(Inverse transform)".
Returns
A name for this math transform (never
null
).
Since
2.5
References Vocabulary.format(), AbstractMathTransform.getName(), and Vocabulary.Keys.InverseTransform.
{
             return AbstractMathTransform.this.getName() +
                     " (" + Vocabulary.format(Vocabulary.Keys.InverseTransform) + ')';
         }
getSourceDimensions()
int getSourceDimensions () inherited
Gets the dimension of input points.
The default implementation returns the dimension of output points of the enclosing math transform.
Referenced by GridTransform2D.Inverse.transform().
{
             return AbstractMathTransform.this.getTargetDimensions();
         }
getTargetDimensions()
int getTargetDimensions () inherited
Gets the dimension of output points.
The default implementation returns the dimension of input points of the enclosing math transform.
{
             return AbstractMathTransform.this.getSourceDimensions();
         }
inverse()
MathTransform2D inverse ()
Returns the inverse of this transform.
{
             return GridTransform2D.this;
         }
isIdentity()
boolean isIdentity () inherited
Tests whether this transform does not move any points.
The default implementation delegates this tests to the enclosing math transform.
{
             return AbstractMathTransform.this.isIdentity();
         }
mismatchedDimension()
static String mismatchedDimension (final String argument, final int dimension, final int expected) static package inherited
Constructs an error message for the MismatchedDimensionException.
CAUTION: Argument order is different than in Apache SIS.
Parameters
argument The argument name with the wrong number of dimensions.
dimension The wrong dimension.
expected The expected dimension.
References Errors.format(), and Errors.Keys.MismatchedDimension_3.
Referenced by AbstractMathTransform.createTransformedShape(), AbstractMathTransform.derivative(), and AbstractMathTransform.transform().
{
         return Errors.format(Errors.Keys.MismatchedDimension_3, argument, dimension, expected);
     }
readObject()
void readObject (ObjectInputStream in) throws IOException, ClassNotFoundException private
Restores reference to this object after deserialization.
References GridTransform2D.inverse.
{
             in.defaultReadObject();
             GridTransform2D.this.inverse = this;
         }
transform() [1/2]
Point2D transform (final Point2D ptSrc, final Point2D ptDst) throws TransformException inherited
Transforms the specified.
ptSrc
and stores the result in
ptDst
. The default implementation performs the following steps:
Ensures that the getSourceDimensions() source} and getTargetDimensions() target dimensions} of this math transform are equal to 2.
Delegates to the transform(double[],int,double[],int,boolean) method using a temporary array of doubles.
Parameters
ptSrc The coordinate point to be transformed.
ptDst The coordinate point that stores the result of transforming
ptSrc
, or
null
if a new point should be created.
Returns
The coordinate point after transforming
ptSrc
and storing the result in
ptDst
, or in a new point if
ptDst
was null.
Exceptions
MismatchedDimensionException If this transform doesn't map two-dimensional coordinate systems.
TransformException If the point can't be transformed.
See also
MathTransform2D::transform(Point2D,Point2D)
References AbstractMathTransform.mismatchedDimension().
Referenced by AbstractMathTransform.derivative().
{
         int dim;
         if ((dim = getSourceDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("ptSrc", 2, dim));
         }
         if ((dim = getTargetDimensions()) != 2) {
             throw new MismatchedDimensionException(mismatchedDimension("ptDst", 2, dim));
         }
         final double[] ord = new double[] {ptSrc.getX(), ptSrc.getY()};
         transform(ord, 0, ord, 0, false);
         if (ptDst != null) {
             ptDst.setLocation(ord[0], ord[1]);
             return ptDst;
         } else {
             return new Point2D.Double(ord[0], ord[1]);
         }
     }
transform() [2/2]
Matrix transform (final double [] srcPts, final int srcOff, final double [] dstPts, final int dstOff, final boolean derivate) throws TransformException
Transforms a single coordinate in a list of ordinal values, and optionally returns the derivative at that location.
Exceptions
TransformException If there is no convergence.
Since
3.20 (derived from 3.00)
References AbstractMathTransform.Inverse.derivative(), Errors.format(), AbstractMathTransform.Inverse.getSourceDimensions(), GridTransform2D.Inverse.ITERATION_TOLERANCE, GridTransform2D.Inverse.MAXIMUM_ITERATIONS, Errors.Keys.NoConvergence, and GridTransform.transform().
         {
             Matrix derivative = null;
             if (derivate) {
                 derivative = derivative(new DirectPositionView.Double(srcPts, srcOff, getSourceDimensions()));
             }
             if (dstPts == null) {
                 return derivative;
             }
             double xi, yi;
             final double x, y;
             dstPts[dstOff  ] = xi = x = srcPts[srcOff  ];
             dstPts[dstOff+1] = yi = y = srcPts[srcOff+1];
             int i = MAXIMUM_ITERATIONS;
             do {
                 GridTransform2D.this.transform(dstPts, dstOff, dstPts, dstOff, false);
                 final double dx = dstPts[dstOff  ] - x;
                 final double dy = dstPts[dstOff+1] - y;
                 dstPts[dstOff  ] = (xi -= dx);
                 dstPts[dstOff+1] = (yi -= dy);
                 if (Math.abs(dx) <= ITERATION_TOLERANCE && Math.abs(dy) <= ITERATION_TOLERANCE) {
                     return derivative;
                 }
             } while (--i >= 0);
             throw new TransformException(Errors.format(Errors.Keys.NoConvergence));
         }
Member Data Documentation
ITERATION_TOLERANCE
final double ITERATION_TOLERANCE = 5E-10 static private
Difference allowed in iterative computations.
This is half the value used in the NGS Fortran code (so all tests pass).
Referenced by GridTransform2D.Inverse.transform().
MAXIMUM_ITERATIONS
final int MAXIMUM_ITERATIONS = 10 static private
Maximum number of iterations for iterative computations.
Referenced by GridTransform2D.Inverse.transform().
serialVersionUID
final long serialVersionUID = -6779719408779847014L static private
Serial number for inter-operability with different versions.