jena-geo: GridTraversal.PointList Interface Reference
GridTraversal.PointList Interface Reference
A simple abstraction allowing to access input polyline points, whatever structure it is in.
Public Member Functions
int size ()
boolean isEmpty ()
double [] getPoint (int index)
int getDimension ()
Detailed Description
A simple abstraction allowing to access input polyline points, whatever structure it is in.
For now, we only manage 1D array of value, but in the future, we could simply add a new PointList using a JTS polyline as input, or any other structure.
TODO : replace with true List interface.
Member Function Documentation
getDimension()
int getDimension ()
Returns
Number of coordinates in a single point (length of a point vector).
Implemented in GridTraversal.Point2DList, and GridTraversal.ContiguousArrayPoint.
getPoint()
double [] getPoint (int index)
Implemented in GridTraversal.Point2DList, and GridTraversal.ContiguousArrayPoint.
Referenced by GridTraversal.prepareSegment(), and GridTraversal.Builder.stream().
isEmpty()
boolean isEmpty ()
Implemented in GridTraversal.Point2DList, and GridTraversal.ContiguousArrayPoint.
Referenced by GridTraversal.Builder.stream().
size()
int size ()
Implemented in GridTraversal.Point2DList, and GridTraversal.ContiguousArrayPoint.
Referenced by GridTraversal.GridTraversal(), GridTraversal.ContiguousArrayPoint.size(), and GridTraversal.Builder.stream().