jena-geo: Loggings Class Reference
Loggings Class Reference
Locale-dependent resources for logging messages.
Classes
class Keys
Resource keys.
Public Member Functions
Loggings (final java.net.URL filename)
Constructs a new resource bundle loading data from the given UTF file.
Static Public Member Functions
static Loggings getResources (Locale locale) throws MissingResourceException
Returns resources in the given locale.
static LogRecord format (final Level level, final short key) throws MissingResourceException
Gets a log record for the given key from this resource bundle or one of its parents.
static LogRecord format (final Level level, final short key, final Object arg0) throws MissingResourceException
Gets a log record for the given key.
static LogRecord format (final Level level, final short key, final Object arg0, final Object arg1) throws MissingResourceException
Gets a log record for the given key.
static LogRecord format (final Level level, final short key, final Object arg0, final Object arg1, final Object arg2) throws MissingResourceException
Gets a log record for the given key.
static LogRecord format (final Level level, final short key, final Object arg0, final Object arg1, final Object arg2, final Object arg3) throws MissingResourceException
Gets a log record for the given key.
static String format (final LogRecord record)
Localizes and formats the message string from a log record.
Static Private Member Functions
static void unexpectedException (final RuntimeException exception)
Invoked when an unexpected exception occurred in the format method.
Detailed Description
Locale-dependent resources for logging messages.
Author
Martin Desruisseaux (IRD)
Version
3.00
Since
2.2
Constructor & Destructor Documentation
Loggings()
Loggings (final java.net.URL filename)
Constructs a new resource bundle loading data from the given UTF file.
Parameters
filename The file or the JAR entry containing resources.
{
         super(filename);
     }
Member Function Documentation
format() [1/6]
static LogRecord format (final Level level, final short key) throws MissingResourceException static
Gets a log record for the given key from this resource bundle or one of its parents.
Parameters
level The log record level.
key The key for the desired string.
Returns
The string for the given key.
Exceptions
MissingResourceException If no object for the given key can be found.
References Loggings.getResources().
Referenced by TemporaryFile.dispose(), DeferredPlanarImage.getTile(), DefaultDataSource.log(), PropertyAuthorityFactory.log(), Registry.registerGeotoolkitServices(), Registry.setNativeAccelerationAllowed(), and Registry.setNativeCodecAllowed().
     {
         return getResources(null).getLogRecord(level, key);
     }
format() [2/6]
static LogRecord format (final Level level, final short key, final Object arg0) throws MissingResourceException static
Gets a log record for the given key.
Replaces all occurrence of "{0}" with values of
arg0
.
Parameters
level The log record level.
key The key for the desired string.
arg0 Value to substitute to "{0}".
Returns
The formatted string for the given key.
Exceptions
MissingResourceException If no object for the given key can be found.
References Loggings.getResources().
     {
         return getResources(null).getLogRecord(level, key, arg0);
     }
format() [3/6]
static LogRecord format (final Level level, final short key, final Object arg0, final Object arg1) throws MissingResourceException static
Gets a log record for the given key.
Replaces all occurrence of "{0}", "{1}", with values of
arg0
,
arg1
.
Parameters
level The log record level.
key The key for the desired string.
arg0 Value to substitute to "{0}".
arg1 Value to substitute to "{1}".
Returns
The formatted string for the given key.
Exceptions
MissingResourceException If no object for the given key can be found.
References Loggings.getResources().
     {
         return getResources(null).getLogRecord(level, key, arg0, arg1);
     }
format() [4/6]
static LogRecord format (final Level level, final short key, final Object arg0, final Object arg1, final Object arg2) throws MissingResourceException static
Gets a log record for the given key.
Replaces all occurrence of "{0}", "{1}", with values of
arg0
,
arg1
, etc.
Parameters
level The log record level.
key The key for the desired string.
arg0 Value to substitute to "{0}".
arg1 Value to substitute to "{1}".
arg2 Value to substitute to "{2}".
Returns
The formatted string for the given key.
Exceptions
MissingResourceException If no object for the given key can be found.
References Loggings.getResources().
     {
         return getResources(null).getLogRecord(level, key, arg0, arg1, arg2);
     }
format() [5/6]
static LogRecord format (final Level level, final short key, final Object arg0, final Object arg1, final Object arg2, final Object arg3) throws MissingResourceException static
Gets a log record for the given key.
Replaces all occurrence of "{0}", "{1}", with values of
arg0
,
arg1
, etc.
Parameters
level The log record level.
key The key for the desired string.
arg0 Value to substitute to "{0}".
arg1 Value to substitute to "{1}".
arg2 Value to substitute to "{2}".
arg3 Value to substitute to "{3}".
Returns
The formatted string for the given key.
Exceptions
MissingResourceException If no object for the given key can be found.
References Loggings.getResources().
     {
         return getResources(null).getLogRecord(level, key, arg0, arg1, arg2, arg3);
     }
format() [6/6]
static String format (final LogRecord record) static
Localizes and formats the message string from a log record.
This method performs a work similar to java.util.logging.Formatter#formatMessage, except that the work will be delegated to getString(int, Object) if the LogRecord::getResourceBundle record resource bundle} is an instance of
IndexedResourceBundle
.
Parameters
record The log record to format.
Returns
The formatted message.
References Loggings.unexpectedException().
{
         String message = record.getMessage();
         final ResourceBundle resources = record.getResourceBundle();
         if (resources instanceof IndexedResourceBundle) {
             int key = -1;
             try {
                 key = Integer.parseInt(message);
             } catch (NumberFormatException e) {
                  unexpectedException(e);
             }
             if (key >= 0) {
                 final Object[] parameters = record.getParameters();
                 return ((IndexedResourceBundle) resources).getString((short) key, parameters);
             }
         }
         if (resources != null) {
             try {
                 message = resources.getString(message);
             } catch (MissingResourceException e) {
                 unexpectedException(e);
             }
             final Object[] parameters = record.getParameters();
             if (parameters != null && parameters.length != 0) {
                 final int offset = message.indexOf('{');
                 if (offset >= 0 && offset < message.length()-1) {
                     // Uses a more restrictive check than Character.isDigit(char)
                     final char c = message.charAt(offset);
                     if (c>='0' && c<='9') try {
                         return MessageFormat.format(message, parameters);
                     } catch (IllegalArgumentException e) {
                         unexpectedException(e);
                     }
                 }
             }
         }
         return message;
     }
getResources()
static Loggings getResources (Locale locale) throws MissingResourceException static
Returns resources in the given locale.
Parameters
locale The locale, or
null
for the default locale.
Returns
Resources in the given locale.
Exceptions
MissingResourceException if resources can't be found.
Referenced by Loggings.format(), and Registry.registerGeotoolkitServices().
{
         return getBundle(Loggings.class, locale);
     }
unexpectedException()
static void unexpectedException (final RuntimeException exception) static private
Invoked when an unexpected exception occurred in the format method.
Referenced by Loggings.format().
{
         Logging.unexpectedException(null, IndexedResourceBundle.class, "format", exception);
     }