jena-geo: CheckedHashSet< E > Class Template Reference
CheckedHashSet< E > Class Template Reference
A Collections::checkedSet(Set, Class) checked} and Collections::synchronizedSet(Set) synchronized} LinkedHashSet.
Classes
class Iter
A synchronized iterator with a check for write permission prior element removal.
Public Member Functions
CheckedHashSet (final Class< E > type)
Constructs a set of the specified type.
CheckedHashSet (final Class< E > type, final int capacity)
Constructs a set of the specified type and initial capacity.
Class< E > getElementType ()
Returns the element type given at construction time.
Iterator< E > iterator ()
Returns an iterator over the elements in this set.
int size ()
Returns the number of elements in this set.
boolean isEmpty ()
Returns.
boolean contains (final Object o)
Returns.
boolean add (final E element) throws IllegalArgumentException, UnsupportedOperationException
Adds the specified element to this set if it is not already present.
boolean addAll (final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
Appends all of the elements in the specified collection to this set.
boolean remove (Object o) throws UnsupportedOperationException
Removes the specified element from this set.
boolean removeAll (Collection<?> c) throws UnsupportedOperationException
Removes all of this set's elements that are also contained in the specified collection.
boolean retainAll (Collection<?> c) throws UnsupportedOperationException
Retains only the elements in this set that are contained in the specified collection.
void clear () throws UnsupportedOperationException
Removes all of the elements from this set.
Object [] toArray ()
Returns an array containing all of the elements in this set.
String toString ()
Returns a string representation of this set.
boolean equals (Object o)
Compares the specified object with this set for equality.
int hashCode ()
Returns the hash code value for this set.
CheckedHashSet< E > clone ()
Returns a shallow copy of this set.
Protected Member Functions
void ensureValid (final E element) throws IllegalArgumentException
Ensures that the given element can be added to this set.
void checkWritePermission () throws UnsupportedOperationException
Checks if changes in this set are allowed.
Object getLock ()
Returns the synchronization lock.
Package Functions
public< T > T [] toArray (T[] a)
Returns an array containing all of the elements in this set.
Private Member Functions
void ensureValidCollection (final Collection<? extends E > collection) throws IllegalArgumentException
Ensures that all elements of the given collection can be added to this set.
Private Attributes
final Class< E > type
The element type.
Static Private Attributes
static final long serialVersionUID = 1999408533884863599L
Serial version UID for compatibility with different versions.
Detailed Description
A Collections::checkedSet(Set, Class) checked} and Collections::synchronizedSet(Set) synchronized} LinkedHashSet.
The type checks are performed at run-time in addition to the compile-time checks.
Using this class is similar to wrapping a LinkedHashSet using the methods provided in the standard Collections class, except for the following advantages:
Avoid the two levels of indirection (for type check and synchronization).
Checks for write permission.
Overrideable methods for controlling the synchronization lock, type checks and write permission checks.
The synchronization is provided mostly in order to prevent damages to the set in case of concurrent access. It does not prevent java.util.ConcurrentModificationException to be thrown during iterations, unless the whole iteration is synchronized on this set getLock() lock}. For real concurrency, see the java.util.concurrent package instead.
{
Note
The above is the reason why the name of this class emphases the <cite>checked</cite> aspect rather than the <cite>synchronized</cite> aspect of the set.}
Parameters
<E> The type of elements in the set.
Author
Martin Desruisseaux (Geomatys)
Since
2.1
Version
3.22
See also
Collections::checkedSet(Set, Class)
Collections::synchronizedSet(Set)
Constructor & Destructor Documentation
CheckedHashSet() [1/2]
CheckedHashSet (final Class< E > type)
Constructs a set of the specified type.
Parameters
type The element type (can not be null).
References CheckedHashSet< E >.type.
{
         super();
         this.type = type;
         ensureNonNull("type", type);
     }
CheckedHashSet() [2/2]
CheckedHashSet (final Class< E > type, final int capacity)
Constructs a set of the specified type and initial capacity.
Parameters
type The element type (should not be null).
capacity The initial capacity.
References CheckedHashSet< E >.type.
{
         super(capacity);
         this.type = type;
         ensureNonNull("type", type);
     }
Member Function Documentation
add()
boolean add (final E element) throws IllegalArgumentException, UnsupportedOperationException
Adds the specified element to this set if it is not already present.
Parameters
element element to be added to this set.
Returns
true
if the set did not already contain the specified element.
Exceptions
IllegalArgumentException if the specified element is not of the expected type.
UnsupportedOperationException if this collection is unmodifiable.
References CheckedHashSet< E >.checkWritePermission(), CheckedHashSet< E >.ensureValid(), and CheckedHashSet< E >.getLock().
     {
         ensureValid(element);
         synchronized (getLock()) {
             checkWritePermission();
             return super.add(element);
         }
     }
addAll()
boolean addAll (final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
Appends all of the elements in the specified collection to this set.
Parameters
collection the elements to be inserted into this set.
Returns
true
if this set changed as a result of the call.
Exceptions
IllegalArgumentException if at least one element is not of the expected type.
UnsupportedOperationException if this collection is unmodifiable.
References CheckedHashSet< E >.checkWritePermission(), CheckedHashSet< E >.ensureValidCollection(), and CheckedHashSet< E >.getLock().
     {
         ensureValidCollection(collection);
         synchronized (getLock()) {
             checkWritePermission();
             return super.addAll(collection);
         }
     }
checkWritePermission()
void checkWritePermission () throws UnsupportedOperationException protected
Checks if changes in this set are allowed.
This method is automatically invoked after this set got the getLock() lock} and before any operation that may change the content. If the write operation is allowed, then this method shall returns normally. Otherwise an UnsupportedOperationException is thrown.
The default implementation does nothing significant (see below), thus allowing this set to be modified. Subclasses can override this method if they want to control write permissions.
{
Note
Actually the current implementation contains an assert statement ensuring that the thread holds the lock. This is an implementation details that may change in any future version of the SIS library. Nevertheless methods that override this one are encouraged to invoke super.checkWritePermission().}
Exceptions
UnsupportedOperationException if this set is unmodifiable.
References CheckedHashSet< E >.getLock().
Referenced by CheckedHashSet< E >.add(), CheckedHashSet< E >.addAll(), CheckedHashSet< E >.clear(), CheckedHashSet< E >.Iter.remove(), CheckedHashSet< E >.remove(), CheckedHashSet< E >.removeAll(), and CheckedHashSet< E >.retainAll().
{
         assert Thread.holdsLock(getLock());
     }
clear()
void clear () throws UnsupportedOperationException
Removes all of the elements from this set.
Exceptions
UnsupportedOperationException if this collection is unmodifiable.
References CheckedHashSet< E >.checkWritePermission(), and CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             checkWritePermission();
             super.clear();
         }
     }
clone()
CheckedHashSet<E> clone ()
Returns a shallow copy of this set.
Returns
A shallow copy of this set.
Implements Cloneable.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return (CheckedHashSet<E>) super.clone();
         }
     }
contains()
boolean contains (final Object o)
Returns.
true
if this set contains the specified element.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return super.contains(o);
         }
     }
ensureValid()
void ensureValid (final E element) throws IllegalArgumentException protected
Ensures that the given element can be added to this set.
The default implementation ensures that the object is
null
or assignable to the type specified at construction time. Subclasses can override this method if they need to perform additional checks.
{
}
This method is invoked before to get the synchronization getLock() lock}. This is different than the checkWritePermission() method, which is invoked inside the synchronized block.
Parameters
element the object to check, or
null
.
Exceptions
IllegalArgumentException if the specified element can not be added to this set.
References Errors.format(), and Errors.Keys.IllegalArgumentClass_3.
Referenced by CheckedHashSet< E >.add(), and CheckedHashSet< E >.ensureValidCollection().
{
         if (element != null && !type.isInstance(element)) {
             throw new IllegalArgumentException(Errors.format(
                     Errors.Keys.IllegalArgumentClass_3, "element", type, element.getClass()));
         }
     }
ensureValidCollection()
void ensureValidCollection (final Collection<? extends E > collection) throws IllegalArgumentException private
Ensures that all elements of the given collection can be added to this set.
Parameters
collection the collection to check, or
null
.
Exceptions
IllegalArgumentException if at least one element can not be added to this set.
References CheckedHashSet< E >.ensureValid().
Referenced by CheckedHashSet< E >.addAll().
{
         for (final E element : collection) {
             ensureValid(element);
         }
     }
equals()
boolean equals (Object o)
Compares the specified object with this set for equality.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return super.equals(o);
         }
     }
getElementType()
Class<E> getElementType ()
Returns the element type given at construction time.
References CheckedHashSet< E >.type.
{
         return type;
     }
getLock()
Object getLock () protected
Returns the synchronization lock.
The default implementation returns
this
.
{
on floating point types}
Subclasses that override this method must be careful to update the lock reference (if needed) when this set is clone() cloned}.
Returns
The synchronization lock.
Referenced by CheckedHashSet< E >.add(), CheckedHashSet< E >.addAll(), CheckedHashSet< E >.checkWritePermission(), CheckedHashSet< E >.clear(), CheckedHashSet< E >.clone(), CheckedHashSet< E >.contains(), CheckedHashSet< E >.equals(), CheckedHashSet< E >.hashCode(), CheckedHashSet< E >.Iter.hasNext(), CheckedHashSet< E >.isEmpty(), CheckedHashSet< E >.iterator(), CheckedHashSet< E >.Iter.next(), CheckedHashSet< E >.Iter.remove(), CheckedHashSet< E >.remove(), CheckedHashSet< E >.removeAll(), CheckedHashSet< E >.retainAll(), CheckedHashSet< E >.size(), CheckedHashSet< E >.toArray(), and CheckedHashSet< E >.toString().
{
         return this;
     }
hashCode()
int hashCode ()
Returns the hash code value for this set.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return super.hashCode();
         }
     }
isEmpty()
boolean isEmpty ()
Returns.
true
if this set contains no elements.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return super.isEmpty();
         }
     }
iterator()
Iterator<E> iterator ()
Returns an iterator over the elements in this set.
The returned iterator will support Iterator::remove() element removal} only if the checkWritePermission() method does not throw exception.
References CheckedHashSet< E >.getLock(), and CheckedHashSet< E >.Iter.Iter().
{
         synchronized (getLock()) {
             return new Iter(super.iterator());
         }
     }
remove()
boolean remove (Object o) throws UnsupportedOperationException
Removes the specified element from this set.
Exceptions
UnsupportedOperationException if this collection is unmodifiable.
References CheckedHashSet< E >.checkWritePermission(), and CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             checkWritePermission();
             return super.remove(o);
         }
     }
removeAll()
boolean removeAll (Collection<?> c) throws UnsupportedOperationException
Removes all of this set's elements that are also contained in the specified collection.
Exceptions
UnsupportedOperationException if this collection is unmodifiable.
References CheckedHashSet< E >.checkWritePermission(), and CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             checkWritePermission();
             return super.removeAll(c);
         }
     }
retainAll()
boolean retainAll (Collection<?> c) throws UnsupportedOperationException
Retains only the elements in this set that are contained in the specified collection.
Exceptions
UnsupportedOperationException if this collection is unmodifiable.
References CheckedHashSet< E >.checkWritePermission(), and CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             checkWritePermission();
             return super.retainAll(c);
         }
     }
size()
int size ()
Returns the number of elements in this set.
References CheckedHashSet< E >.getLock().
                       {
         synchronized (getLock()) {
             return super.size();
         }
     }
toArray() [1/2]
Object [] toArray ()
Returns an array containing all of the elements in this set.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return super.toArray();
         }
     }
toArray() [2/2]
public<T> T [] toArray (T [] a) package
Returns an array containing all of the elements in this set.
Parameters
<T> The type of array elements.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return super.toArray(a);
         }
     }
toString()
String toString ()
Returns a string representation of this set.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return super.toString();
         }
     }
Member Data Documentation
serialVersionUID
final long serialVersionUID = 1999408533884863599L static private
Serial version UID for compatibility with different versions.
type
final Class<E> type private
The element type.
Referenced by CheckedHashSet< E >.CheckedHashSet(), and CheckedHashSet< E >.getElementType().