jena-geo: CheckedHashSet< E >.Iter Class Reference
CheckedHashSet< E >.Iter Class Reference
A synchronized iterator with a check for write permission prior element removal.
Public Member Functions
boolean hasNext ()
Returns.
E next () throws NoSuchElementException
Returns the next element in the iteration.
void remove () throws UnsupportedOperationException
Removes the previous element if the enclosing CheckedHashSet allows write operations.
Package Functions
Iter (final Iterator< E > iterator)
Creates a new wrapper for the given LinkedHashSet iterator.
Private Attributes
final Iterator< E > iterator
The LinkedHashSet iterator.
Detailed Description
A synchronized iterator with a check for write permission prior element removal.
This class wraps the iterator provided by LinkedHashSet#iterator().
See also
CheckedHashSet::iterator()
Constructor & Destructor Documentation
Iter()
Iter (final Iterator< E > iterator) package
Creates a new wrapper for the given LinkedHashSet iterator.
References CheckedHashSet< E >.Iter.iterator.
Referenced by CheckedHashSet< E >.iterator().
{
             this.iterator = iterator;
         }
Member Function Documentation
hasNext()
boolean hasNext ()
Returns.
true
if there is more elements in the iteration.
References CheckedHashSet< E >.getLock().
{
             synchronized (getLock()) {
                 return iterator.hasNext();
             }
         }
next()
E next () throws NoSuchElementException
Returns the next element in the iteration.
References CheckedHashSet< E >.getLock().
{
             synchronized (getLock()) {
                 return iterator.next();
             }
         }
remove()
void remove () throws UnsupportedOperationException
Removes the previous element if the enclosing CheckedHashSet allows write operations.
References CheckedHashSet< E >.checkWritePermission(), and CheckedHashSet< E >.getLock().
{
             synchronized (getLock()) {
                 checkWritePermission();
                 iterator.remove();
             }
         }
Member Data Documentation
iterator
final Iterator<E> iterator private
The LinkedHashSet iterator.
Referenced by CheckedHashSet< E >.Iter.Iter().