jena-geo: NotifiedCheckedSet< E > Class Template Reference
NotifiedCheckedSet< E > Class Template Reference abstract
Abstract synchronized set that define notify methods called when objects are added or removed.
Public Member Functions
NotifiedCheckedSet (final Class< E > type)
NotifiedCheckedSet (final Class< E > type, final int capacity)
boolean add (final E element) throws IllegalArgumentException, UnsupportedOperationException
boolean addAll (final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
boolean remove (final Object o) throws UnsupportedOperationException
boolean removeAll (final Collection<?> c) throws UnsupportedOperationException
Class< E > getElementType ()
Returns the element type given at construction time.
Iterator< E > iterator ()
Returns an iterator over the elements in this set.
int size ()
Returns the number of elements in this set.
boolean isEmpty ()
Returns.
boolean contains (final Object o)
Returns.
boolean retainAll (Collection<?> c) throws UnsupportedOperationException
Retains only the elements in this set that are contained in the specified collection.
void clear () throws UnsupportedOperationException
Removes all of the elements from this set.
Object [] toArray ()
Returns an array containing all of the elements in this set.
String toString ()
Returns a string representation of this set.
boolean equals (Object o)
Compares the specified object with this set for equality.
int hashCode ()
Returns the hash code value for this set.
CheckedHashSet< E > clone ()
Returns a shallow copy of this set.
Protected Member Functions
abstract void notifyAdd (final E item, NumberRange< Integer > range)
abstract void notifyAdd (final Collection<? extends E > item, NumberRange< Integer > range)
abstract void notifyRemove (final E item, NumberRange< Integer > range)
void ensureValid (final E element) throws IllegalArgumentException
Ensures that the given element can be added to this set.
void checkWritePermission () throws UnsupportedOperationException
Checks if changes in this set are allowed.
Object getLock ()
Returns the synchronization lock.
Package Functions
public< T > T [] toArray (T[] a)
Returns an array containing all of the elements in this set.
Detailed Description
Abstract synchronized set that define notify methods called when objects are added or removed.
Author
Johann Sorel (Geomatys)
Constructor & Destructor Documentation
NotifiedCheckedSet() [1/2]
NotifiedCheckedSet (final Class< E > type)
{
         super(type);
     }
NotifiedCheckedSet() [2/2]
NotifiedCheckedSet (final Class< E > type, final int capacity)
References NotifiedCheckedSet< E >.notifyAdd(), and NotifiedCheckedSet< E >.notifyRemove().
{
         super(type,capacity);
     }
Member Function Documentation
add()
boolean add (final E element) throws IllegalArgumentException, UnsupportedOperationException
References NotifiedCheckedSet< E >.notifyAdd().
{
         if(element == null) return false;
         final boolean added = super.add(element);
         if (added) {
             notifyAdd(element, null);
         }
         return added;
     }
addAll()
boolean addAll (final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
References NotifiedCheckedSet< E >.notifyAdd().
{
         final boolean added = super.addAll(collection);
         if (added) {
             notifyAdd(collection, null );
         }
         return added;
     }
checkWritePermission()
void checkWritePermission () throws UnsupportedOperationException protected inherited
Checks if changes in this set are allowed.
This method is automatically invoked after this set got the getLock() lock} and before any operation that may change the content. If the write operation is allowed, then this method shall returns normally. Otherwise an UnsupportedOperationException is thrown.
The default implementation does nothing significant (see below), thus allowing this set to be modified. Subclasses can override this method if they want to control write permissions.
{
Note
Actually the current implementation contains an assert statement ensuring that the thread holds the lock. This is an implementation details that may change in any future version of the SIS library. Nevertheless methods that override this one are encouraged to invoke super.checkWritePermission().}
Exceptions
UnsupportedOperationException if this set is unmodifiable.
References CheckedHashSet< E >.getLock().
Referenced by CheckedHashSet< E >.add(), CheckedHashSet< E >.addAll(), CheckedHashSet< E >.clear(), CheckedHashSet< E >.Iter.remove(), CheckedHashSet< E >.remove(), CheckedHashSet< E >.removeAll(), and CheckedHashSet< E >.retainAll().
{
         assert Thread.holdsLock(getLock());
     }
clear()
void clear () throws UnsupportedOperationException inherited
Removes all of the elements from this set.
Exceptions
UnsupportedOperationException if this collection is unmodifiable.
References CheckedHashSet< E >.checkWritePermission(), and CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             checkWritePermission();
             super.clear();
         }
     }
clone()
CheckedHashSet<E> clone () inherited
Returns a shallow copy of this set.
Returns
A shallow copy of this set.
Implements Cloneable.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return (CheckedHashSet<E>) super.clone();
         }
     }
contains()
boolean contains (final Object o) inherited
Returns.
true
if this set contains the specified element.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return super.contains(o);
         }
     }
ensureValid()
void ensureValid (final E element) throws IllegalArgumentException protected inherited
Ensures that the given element can be added to this set.
The default implementation ensures that the object is
null
or assignable to the type specified at construction time. Subclasses can override this method if they need to perform additional checks.
{
}
This method is invoked before to get the synchronization getLock() lock}. This is different than the checkWritePermission() method, which is invoked inside the synchronized block.
Parameters
element the object to check, or
null
.
Exceptions
IllegalArgumentException if the specified element can not be added to this set.
References Errors.format(), and Errors.Keys.IllegalArgumentClass_3.
Referenced by CheckedHashSet< E >.add(), and CheckedHashSet< E >.ensureValidCollection().
{
         if (element != null && !type.isInstance(element)) {
             throw new IllegalArgumentException(Errors.format(
                     Errors.Keys.IllegalArgumentClass_3, "element", type, element.getClass()));
         }
     }
equals()
boolean equals (Object o) inherited
Compares the specified object with this set for equality.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return super.equals(o);
         }
     }
getElementType()
Class<E> getElementType () inherited
Returns the element type given at construction time.
References CheckedHashSet< E >.type.
{
         return type;
     }
getLock()
Object getLock () protected inherited
Returns the synchronization lock.
The default implementation returns
this
.
{
on floating point types}
Subclasses that override this method must be careful to update the lock reference (if needed) when this set is clone() cloned}.
Returns
The synchronization lock.
Referenced by CheckedHashSet< E >.add(), CheckedHashSet< E >.addAll(), CheckedHashSet< E >.checkWritePermission(), CheckedHashSet< E >.clear(), CheckedHashSet< E >.clone(), CheckedHashSet< E >.contains(), CheckedHashSet< E >.equals(), CheckedHashSet< E >.hashCode(), CheckedHashSet< E >.Iter.hasNext(), CheckedHashSet< E >.isEmpty(), CheckedHashSet< E >.iterator(), CheckedHashSet< E >.Iter.next(), CheckedHashSet< E >.Iter.remove(), CheckedHashSet< E >.remove(), CheckedHashSet< E >.removeAll(), CheckedHashSet< E >.retainAll(), CheckedHashSet< E >.size(), CheckedHashSet< E >.toArray(), and CheckedHashSet< E >.toString().
{
         return this;
     }
hashCode()
int hashCode () inherited
Returns the hash code value for this set.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return super.hashCode();
         }
     }
isEmpty()
boolean isEmpty () inherited
Returns.
true
if this set contains no elements.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return super.isEmpty();
         }
     }
iterator()
Iterator<E> iterator () inherited
Returns an iterator over the elements in this set.
The returned iterator will support Iterator::remove() element removal} only if the checkWritePermission() method does not throw exception.
References CheckedHashSet< E >.getLock(), and CheckedHashSet< E >.Iter.Iter().
{
         synchronized (getLock()) {
             return new Iter(super.iterator());
         }
     }
notifyAdd() [1/2]
abstract void notifyAdd (final E item, NumberRange< Integer > range) abstract protected
Referenced by NotifiedCheckedSet< E >.add(), NotifiedCheckedSet< E >.addAll(), and NotifiedCheckedSet< E >.NotifiedCheckedSet().
notifyAdd() [2/2]
abstract void notifyAdd (final Collection<? extends E > item, NumberRange< Integer > range) abstract protected
notifyRemove()
abstract void notifyRemove (final E item, NumberRange< Integer > range) abstract protected
Referenced by NotifiedCheckedSet< E >.NotifiedCheckedSet(), and NotifiedCheckedSet< E >.remove().
remove()
boolean remove (final Object o) throws UnsupportedOperationException
References NotifiedCheckedSet< E >.notifyRemove().
{
         final boolean removed = super.remove(o);
         if (removed) {
             notifyRemove(super.getElementType().cast(o), null );
         }
         return removed;
     }
removeAll()
boolean removeAll (final Collection<?> c) throws UnsupportedOperationException
{
         //TODO handle remove by collection events if possible
         // to avoid several calls to remove
         boolean valid = false;
         for(Object i : c){
             final boolean val = remove(i);
             if(val) valid = val;
         }
         return valid;
     }
retainAll()
boolean retainAll (Collection<?> c) throws UnsupportedOperationException inherited
Retains only the elements in this set that are contained in the specified collection.
Exceptions
UnsupportedOperationException if this collection is unmodifiable.
References CheckedHashSet< E >.checkWritePermission(), and CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             checkWritePermission();
             return super.retainAll(c);
         }
     }
size()
int size () inherited
Returns the number of elements in this set.
References CheckedHashSet< E >.getLock().
                       {
         synchronized (getLock()) {
             return super.size();
         }
     }
toArray() [1/2]
Object [] toArray () inherited
Returns an array containing all of the elements in this set.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return super.toArray();
         }
     }
toArray() [2/2]
public<T> T [] toArray (T [] a) package inherited
Returns an array containing all of the elements in this set.
Parameters
<T> The type of array elements.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return super.toArray(a);
         }
     }
toString()
String toString () inherited
Returns a string representation of this set.
References CheckedHashSet< E >.getLock().
{
         synchronized (getLock()) {
             return super.toString();
         }
     }