jena-geo: CheckedHashMap< K, V > Class Template Reference
CheckedHashMap< K, V > Class Template Reference
A Collections::checkedMap(Map, Class, Class) checked} and Collections::synchronizedMap(Map) synchronized} LinkedHashMap.
Classes
class Iter
A synchronized iterator with a check for write permission prior element removal.
class Sync
A collection or a set synchronized on the enclosing map getLock() lock}.
class SyncSet
A set synchronized on the enclosing map getLock() lock}.
Public Member Functions
CheckedHashMap (final Class< K > keyType, final Class< V > valueType)
Constructs a map of the specified key and value types.
int size ()
Returns the number of elements in this map.
boolean isEmpty ()
Returns.
boolean containsKey (final Object key)
Returns.
boolean containsValue (final Object value)
Returns.
V get (Object key)
Returns the value to which the specified key is mapped, or.
V put (final K key, final V value) throws IllegalArgumentException, UnsupportedOperationException
Associates the specified value with the specified key in this map.
void putAll (Map<? extends K, ? extends V > m) throws UnsupportedOperationException
Copies all of the mappings from the specified map to this map.
V remove (Object key) throws UnsupportedOperationException
Removes the mapping for the specified key from this map if present.
void clear () throws UnsupportedOperationException
Removes all of the elements from this map.
Set< K > keySet ()
Returns a view of the keys in the map.
Collection< V > values ()
Returns a view of the values in the map.
Set< Map.Entry< K, V > > entrySet ()
Returns a view of the entries in the map.
String toString ()
Returns a string representation of this map.
boolean equals (Object o)
Compares the specified object with this map for equality.
int hashCode ()
Returns the hash code value for this map.
CheckedHashMap< K, V > clone ()
Returns a shallow copy of this map.
Protected Member Functions
void checkWritePermission () throws UnsupportedOperationException
Checks if changes in this map are allowed.
Object getLock ()
Returns the synchronization lock.
Static Private Member Functions
static< E > void ensureValidType (final E element, final Class< E > type) throws IllegalArgumentException
Checks the type of the specified object.
Private Attributes
final Class< K > keyType
The class type for keys.
final Class< V > valueType
The class type for values.
Static Private Attributes
static final long serialVersionUID = -5983828895888575736L
Serial version UID for compatibility with different versions.
Detailed Description
A Collections::checkedMap(Map, Class, Class) checked} and Collections::synchronizedMap(Map) synchronized} LinkedHashMap.
The type checks are performed at run-time in addition to the compile-time checks.
Using this class is similar to wrapping a LinkedHashMap using the methods provided in the standard Collections class, except for the following advantages:
Avoid the two levels of indirection (for type check and synchronization).
Checks for write permission.
Overrideable methods for controlling the synchronization lock and write permission checks.
The synchronization is provided mostly in order to prevent damages to the map in case of concurrent access. It does not prevent java.util.ConcurrentModificationException to be thrown during iterations, unless the whole iteration is synchronized on this map getLock() lock}. For real concurrency, see the java.util.concurrent package instead.
{
Note
The above is the reason why the name of this class emphases the <cite>checked</cite> aspect rather than the <cite>synchronized</cite> aspect of the map.}
Parameters
<K> The type of keys in the map.
<V> The type of values in the map.
Author
Martin Desruisseaux (Geomatys)
Since
2.1
Version
3.22
See also
Collections::checkedMap(Map, Class, Class)
Collections::synchronizedMap(Map)
Constructor & Destructor Documentation
CheckedHashMap()
CheckedHashMap (final Class< K > keyType, final Class< V > valueType)
Constructs a map of the specified key and value types.
Parameters
keyType The key type (can not be null).
valueType The value type (can not be null).
References CheckedHashMap< K, V >.keyType, and CheckedHashMap< K, V >.valueType.
{
         this.keyType   = keyType;
         this.valueType = valueType;
         ensureNonNull("keyType",   keyType);
         ensureNonNull("valueType", valueType);
     }
Member Function Documentation
checkWritePermission()
void checkWritePermission () throws UnsupportedOperationException protected
Checks if changes in this map are allowed.
This method is automatically invoked after this map got the getLock() lock} and before any operation that may change the content. If the write operation is allowed, then this method shall returns normally. Otherwise an UnsupportedOperationException is thrown.
The default implementation does nothing significant (see below), thus allowing this map to be modified. Subclasses can override this method if they want to control write permissions.
{
Note
Actually the current implementation contains an assert statement ensuring that the thread holds the lock. This is an implementation details that may change in any future version of the SIS library. Nevertheless methods that override this one are encouraged to invoke super.checkWritePermission().}
Exceptions
UnsupportedOperationException if this map is unmodifiable.
References CheckedHashMap< K, V >.getLock().
Referenced by CheckedHashMap< K, V >.clear(), CheckedHashMap< K, V >.Sync< E >.clear(), CheckedHashMap< K, V >.put(), CheckedHashMap< K, V >.putAll(), CheckedHashMap< K, V >.remove(), CheckedHashMap< K, V >.Iter< E >.remove(), CheckedHashMap< K, V >.Sync< E >.remove(), CheckedHashMap< K, V >.Sync< E >.removeAll(), and CheckedHashMap< K, V >.Sync< E >.retainAll().
{
         assert Thread.holdsLock(getLock());
     }
clear()
void clear () throws UnsupportedOperationException
Removes all of the elements from this map.
Exceptions
UnsupportedOperationException if this collection is unmodifiable.
References CheckedHashMap< K, V >.checkWritePermission(), and CheckedHashMap< K, V >.getLock().
{
         synchronized (getLock()) {
             checkWritePermission();
             super.clear();
         }
     }
clone()
CheckedHashMap<K,V> clone ()
Returns a shallow copy of this map.
Returns
A shallow copy of this map.
Implements Cloneable.
References CheckedHashMap< K, V >.getLock().
{
         synchronized (getLock()) {
             return (CheckedHashMap<K,V>) super.clone();
         }
     }
containsKey()
boolean containsKey (final Object key)
Returns.
true
if this map contains the specified key.
References CheckedHashMap< K, V >.getLock().
{
         synchronized (getLock()) {
             return super.containsKey(key);
         }
     }
containsValue()
boolean containsValue (final Object value)
Returns.
true
if this map contains the specified value.
References CheckedHashMap< K, V >.getLock().
{
         synchronized (getLock()) {
             return super.containsValue(value);
         }
     }
ensureValidType()
static <E> void ensureValidType (final E element, final Class< E > type) throws IllegalArgumentException static private
Checks the type of the specified object.
Parameters
element the object to check, or
null
.
Exceptions
IllegalArgumentException if the specified element is not of the expected type.
References Errors.format(), and Errors.Keys.IllegalArgumentClass_3.
Referenced by CheckedHashMap< K, V >.put(), and CheckedHashMap< K, V >.putAll().
     {
         if (element!=null && !type.isInstance(element)) {
             throw new IllegalArgumentException(Errors.format(
                     Errors.Keys.IllegalArgumentClass_3, "element", type, element.getClass()));
         }
     }
entrySet()
Set<Map.Entry<K,V> > entrySet ()
Returns a view of the entries in the map.
The returned set will support Set::remove(Object) element removal} only if the checkWritePermission() method does not throw exception.
Returns
A synchronized view of the keys in the map.
References CheckedHashMap< K, V >.getLock().
{
         synchronized (getLock()) {
             return new SyncSet<>(super.entrySet());
         }
     }
equals()
boolean equals (Object o)
Compares the specified object with this map for equality.
References CheckedHashMap< K, V >.getLock().
{
         synchronized (getLock()) {
             return super.equals(o);
         }
     }
get()
V get (Object key)
Returns the value to which the specified key is mapped, or.
null
if none.
References CheckedHashMap< K, V >.getLock().
{
         synchronized (getLock()) {
             return super.get(key);
         }
     }
getLock()
Object getLock () protected
Returns the synchronization lock.
The default implementation returns
this
.
{
on floating point types}
Subclasses that override this method must be careful to update the lock reference (if needed) when this map is clone() cloned}.
Returns
The synchronization lock.
Referenced by CheckedHashMap< K, V >.checkWritePermission(), CheckedHashMap< K, V >.clear(), CheckedHashMap< K, V >.Sync< E >.clear(), CheckedHashMap< K, V >.clone(), CheckedHashMap< K, V >.Sync< E >.contains(), CheckedHashMap< K, V >.Sync< E >.containsAll(), CheckedHashMap< K, V >.containsKey(), CheckedHashMap< K, V >.containsValue(), CheckedHashMap< K, V >.entrySet(), CheckedHashMap< K, V >.equals(), CheckedHashMap< K, V >.Sync< E >.equals(), CheckedHashMap< K, V >.get(), CheckedHashMap< K, V >.hashCode(), CheckedHashMap< K, V >.Sync< E >.hashCode(), CheckedHashMap< K, V >.Iter< E >.hasNext(), CheckedHashMap< K, V >.isEmpty(), CheckedHashMap< K, V >.Sync< E >.isEmpty(), CheckedHashMap< K, V >.Sync< E >.iterator(), CheckedHashMap< K, V >.keySet(), CheckedHashMap< K, V >.Iter< E >.next(), CheckedHashMap< K, V >.put(), CheckedHashMap< K, V >.putAll(), CheckedHashMap< K, V >.remove(), CheckedHashMap< K, V >.Iter< E >.remove(), CheckedHashMap< K, V >.Sync< E >.remove(), CheckedHashMap< K, V >.Sync< E >.removeAll(), CheckedHashMap< K, V >.Sync< E >.retainAll(), CheckedHashMap< K, V >.size(), CheckedHashMap< K, V >.Sync< E >.size(), CheckedHashMap< K, V >.Sync< E >.toArray(), CheckedHashMap< K, V >.toString(), CheckedHashMap< K, V >.Sync< E >.toString(), and CheckedHashMap< K, V >.values().
{
         return this;
     }
hashCode()
int hashCode ()
Returns the hash code value for this map.
References CheckedHashMap< K, V >.getLock().
{
         synchronized (getLock()) {
             return super.hashCode();
         }
     }
isEmpty()
boolean isEmpty ()
Returns.
true
if this map contains no elements.
References CheckedHashMap< K, V >.getLock().
{
         synchronized (getLock()) {
             return super.isEmpty();
         }
     }
keySet()
Set<K> keySet ()
Returns a view of the keys in the map.
The returned set will support Set::remove(Object) element removal} only if the checkWritePermission() method does not throw exception.
Returns
A synchronized view of the keys in the map.
References CheckedHashMap< K, V >.getLock().
{
         synchronized (getLock()) {
             return new SyncSet<>(super.keySet());
         }
     }
put()
V put (final K key, final V value) throws IllegalArgumentException, UnsupportedOperationException
Associates the specified value with the specified key in this map.
If the map previously contained a mapping for this key, the old value is replaced.
Parameters
key key with which the specified value is to be associated.
value value to be associated with the specified key.
Returns
previous value associated with specified key, or
null
.
Exceptions
IllegalArgumentException if the key or the value is not of the expected type.
UnsupportedOperationException if this collection is unmodifiable.
References CheckedHashMap< K, V >.checkWritePermission(), CheckedHashMap< K, V >.ensureValidType(), and CheckedHashMap< K, V >.getLock().
     {
         ensureValidType(key,     keyType);
         ensureValidType(value, valueType);
         synchronized (getLock()) {
             checkWritePermission();
             return super.put(key, value);
         }
     }
putAll()
void putAll (Map<? extends K, ? extends V > m) throws UnsupportedOperationException
Copies all of the mappings from the specified map to this map.
Exceptions
UnsupportedOperationException if this collection is unmodifiable.
References CheckedHashMap< K, V >.checkWritePermission(), CheckedHashMap< K, V >.ensureValidType(), CheckedHashMap< K, V >.getLock(), CheckedHashMap< K, V >.keyType, and CheckedHashMap< K, V >.valueType.
{
         for (final Map.Entry<? extends K, ? extends V> entry : m.entrySet()) {
             ensureValidType(entry.getKey(),     keyType);
             ensureValidType(entry.getValue(), valueType);
         }
         synchronized (getLock()) {
             checkWritePermission();
             super.putAll(m);
         }
     }
remove()
V remove (Object key) throws UnsupportedOperationException
Removes the mapping for the specified key from this map if present.
Exceptions
UnsupportedOperationException if this collection is unmodifiable.
References CheckedHashMap< K, V >.checkWritePermission(), and CheckedHashMap< K, V >.getLock().
{
         synchronized (getLock()) {
             checkWritePermission();
             return super.remove(key);
         }
     }
size()
int size ()
Returns the number of elements in this map.
References CheckedHashMap< K, V >.getLock().
                       {
         synchronized (getLock()) {
             return super.size();
         }
     }
toString()
String toString ()
Returns a string representation of this map.
References CheckedHashMap< K, V >.getLock().
{
         synchronized (getLock()) {
             return super.toString();
         }
     }
values()
Collection<V> values ()
Returns a view of the values in the map.
The returned collection will support Collection::remove(Object) element removal} only if the checkWritePermission() method does not throw exception.
Returns
A synchronized view of the values in the map.
References CheckedHashMap< K, V >.getLock().
{
         synchronized (getLock()) {
             return new Sync<>(super.values());
         }
     }
Member Data Documentation
keyType
final Class<K> keyType private
The class type for keys.
Referenced by CheckedHashMap< K, V >.CheckedHashMap(), and CheckedHashMap< K, V >.putAll().
serialVersionUID
final long serialVersionUID = -5983828895888575736L static private
Serial version UID for compatibility with different versions.
valueType
final Class<V> valueType private
The class type for values.
Referenced by CheckedHashMap< K, V >.CheckedHashMap(), and CheckedHashMap< K, V >.putAll().