jena-geo: Ranks Class Reference
Ranks Class Reference
Sorts elements in an array while remembering their ranks.
Classes
class Any
A rank element for the Comparable type.
class Byte
A rank element for the.
class Double
A rank element for the.
class Float
A rank element for the.
class Integer
A rank element for the.
class Long
A rank element for the.
class Short
A rank element for the.
Static Public Member Functions
static< T extends Comparable< T > int [] ranks (final T[] source, final T[] target)
Sorts the elements in the given array and return their ranks.
static int [] ranks (final double[] source, final double[] target)
Sorts the elements in the given array and return their ranks.
static int [] ranks (final float[] source, final float[] target)
Sorts the elements in the given array and return their ranks.
static int [] ranks (final long[] source, final long[] target)
Sorts the elements in the given array and return their ranks.
static int [] ranks (final int[] source, final int[] target)
Sorts the elements in the given array and return their ranks.
static int [] ranks (final short[] source, final short[] target)
Sorts the elements in the given array and return their ranks.
static int [] ranks (final byte[] source, final byte[] target)
Sorts the elements in the given array and return their ranks.
Private Member Functions
Ranks (final int index)
For inner class constructors only.
Static Private Member Functions
static int [] ranks (final Ranks[] entries)
Extracts the ranks from the specified entries.
Private Attributes
final int index
The index in the array before it has been sorted.
Detailed Description
Sorts elements in an array while remembering their ranks.
Each method in this class sort the given array in the same way than Arrays#sort(Object[]) does, and in addition return the index that each element had in the original array prior the sorting.
Every methods are used in the same way:
{ java int[] index = ranks(source, target); }
where
source
and
target
are arrays of Comparable elements or of a primitive type. The
source
argument is the array to sort and is left untouched (unless
target
is a reference to the same array). The
target
argument, if non-null, is the array where to store the sorted values.
The returned
index
array will have the same length than the
source
array. Each element in the returned array is an index ranging from 0 inclusive to
source.length
exclusive, such that
target[i]
=
source[index[i]]
for all i.
Invoking #ranks(double[],double[]) ranks}(source, source) is equivalent to invoking Arrays::sort(double[]) Arrays.sort}(source) in a less efficient way. The later should always be used (cloning the source array if needed) if the returned ranks are not used.
Author
Martin Desruisseaux (Geomatys)
Version
3.00
Since
2.5
Constructor & Destructor Documentation
Ranks()
Ranks (final int index) private
For inner class constructors only.
References Ranks.index.
{
         this.index = index;
     }
Member Function Documentation
ranks() [1/8]
static <T extends Comparable<T> int [] ranks (final T [] source, final T [] target) static
Sorts the elements in the given array and return their ranks.
See class description for details.
Parameters
<T> The type of elements in the array to be sorted.
source The array of values to sort, or
null
.
target The array where to store sorted values, or
null
if none. May be the same array than
source
, in which case the sorting will be performed in place.
Returns
The value ranks, or
null
if
source
was null.
See also
Arrays::sort(Object[])
Referenced by Ranks.ranks().
{
         if (source == null) {
             return null;
         }
         @SuppressWarnings({"unchecked","rawtypes"}) // Generic array creation.
         final Any<T>[] entries = new Any[source.length];
         for (int i=0; i<entries.length; i++) {
             entries[i] = new Any<>(i, source[i]);
         }
         final int[] ranks = ranks(entries);
         if (target != null) {
             for (int i=Math.min(entries.length, target.length); --i>=0;) {
                 target[i] = entries[i].value;
             }
         }
         return ranks;
     }
ranks() [2/8]
static int [] ranks (final double [] source, final double [] target) static
Sorts the elements in the given array and return their ranks.
See class description for details.
Parameters
source The array of values to sort, or
null
.
target The array where to store sorted values, or
null
if none. May be the same array than
source
, in which case the sorting will be performed in place.
Returns
The value ranks, or
null
if
source
was null.
See also
Arrays::sort(double[])
References Ranks.ranks(), and Ranks.Double.value.
{
         if (source == null) {
             return null;
         }
         final Double[] entries = new Double[source.length];
         for (int i=0; i<entries.length; i++) {
             entries[i] = new Double(i, source[i]); // NOSONAR: This is not java.lang.Double
         }
         final int[] ranks = ranks(entries);
         if (target != null) {
             for (int i=Math.min(entries.length, target.length); --i>=0;) {
                 target[i] = entries[i].value;
             }
         }
         return ranks;
     }
ranks() [3/8]
static int [] ranks (final float [] source, final float [] target) static
Sorts the elements in the given array and return their ranks.
See class description for details.
Parameters
source The array of values to sort, or
null
.
target The array where to store sorted values, or
null
if none. May be the same array than
source
, in which case the sorting will be performed in place.
Returns
The value ranks, or
null
if
source
was null.
See also
Arrays::sort(float[])
References Ranks.ranks(), and Ranks.Float.value.
{
         if (source == null) {
             return null;
         }
         final Float[] entries = new Float[source.length];
         for (int i=0; i<entries.length; i++) {
             entries[i] = new Float(i, source[i]); // NOSONAR: This is not java.lang.Float
         }
         final int[] ranks = ranks(entries);
         if (target != null) {
             for (int i=Math.min(entries.length, target.length); --i>=0;) {
                 target[i] = entries[i].value;
             }
         }
         return ranks;
     }
ranks() [4/8]
static int [] ranks (final long [] source, final long [] target) static
Sorts the elements in the given array and return their ranks.
See class description for details.
Parameters
source The array of values to sort, or
null
.
target The array where to store sorted values, or
null
if none. May be the same array than
source
, in which case the sorting will be performed in place.
Returns
The value ranks, or
null
if
source
was null.
See also
Arrays::sort(long[])
References Ranks.ranks(), and Ranks.Long.value.
{
         if (source == null) {
             return null;
         }
         final Long[] entries = new Long[source.length];
         for (int i=0; i<entries.length; i++) {
             entries[i] = new Long(i, source[i]); // NOSONAR: This is not java.lang.Long
         }
         final int[] ranks = ranks(entries);
         if (target != null) {
             for (int i=Math.min(entries.length, target.length); --i>=0;) {
                 target[i] = entries[i].value;
             }
         }
         return ranks;
     }
ranks() [5/8]
static int [] ranks (final int [] source, final int [] target) static
Sorts the elements in the given array and return their ranks.
See class description for details.
Parameters
source The array of values to sort, or
null
.
target The array where to store sorted values, or
null
if none. May be the same array than
source
, in which case the sorting will be performed in place.
Returns
The value ranks, or
null
if
source
was null.
See also
Arrays::sort(int[])
References Ranks.ranks(), and Ranks.Integer.value.
{
         if (source == null) {
             return null;
         }
         final Integer[] entries = new Integer[source.length];
         for (int i=0; i<entries.length; i++) {
             entries[i] = new Integer(i, source[i]); // NOSONAR: This is not java.lang.Integer
         }
         final int[] ranks = ranks(entries);
         if (target != null) {
             for (int i=Math.min(entries.length, target.length); --i>=0;) {
                 target[i] = entries[i].value;
             }
         }
         return ranks;
     }
ranks() [6/8]
static int [] ranks (final short [] source, final short [] target) static
Sorts the elements in the given array and return their ranks.
See class description for details.
Parameters
source The array of values to sort, or
null
.
target The array where to store sorted values, or
null
if none. May be the same array than
source
, in which case the sorting will be performed in place.
Returns
The value ranks, or
null
if
source
was null.
See also
Arrays::sort(short[])
References Ranks.ranks(), and Ranks.Short.value.
{
         if (source == null) {
             return null;
         }
         final Short[] entries = new Short[source.length];
         for (int i=0; i<entries.length; i++) {
             entries[i] = new Short(i, source[i]); // NOSONAR: This is not java.lang.Short
         }
         final int[] ranks = ranks(entries);
         if (target != null) {
             for (int i=Math.min(entries.length, target.length); --i>=0;) {
                 target[i] = entries[i].value;
             }
         }
         return ranks;
     }
ranks() [7/8]
static int [] ranks (final byte [] source, final byte [] target) static
Sorts the elements in the given array and return their ranks.
See class description for details.
Parameters
source The array of values to sort, or
null
.
target The array where to store sorted values, or
null
if none. May be the same array than
source
, in which case the sorting will be performed in place.
Returns
The value ranks, or
null
if
source
was null.
See also
Arrays::sort(byte[])
References Ranks.ranks(), and Ranks.Byte.value.
{
         if (source == null) {
             return null;
         }
         final Byte[] entries = new Byte[source.length];
         for (int i=0; i<entries.length; i++) {
             entries[i] = new Byte(i, source[i]); // NOSONAR: This is not java.lang.Byte
         }
         final int[] ranks = ranks(entries);
         if (target != null) {
             for (int i=Math.min(entries.length, target.length); --i>=0;) {
                 target[i] = entries[i].value;
             }
         }
         return ranks;
     }
ranks() [8/8]
static int [] ranks (final Ranks [] entries) static private
Extracts the ranks from the specified entries.
References Ranks.index, and Ranks.ranks().
{
         Arrays.sort(entries);
         final int[] ranks = new int[entries.length];
         for (int i=0; i<ranks.length; i++) {
             ranks[i] = entries[i].index;
         }
         return ranks;
     }
Member Data Documentation
index
final int index private
The index in the array before it has been sorted.
Referenced by Ranks.Ranks(), and Ranks.ranks().