jena-geo: CheckedArrayList< E > Class Template Reference
CheckedArrayList< E > Class Template Reference
A Collections::checkedList(List, Class) checked} and Collections::synchronizedList(List) synchronized} ArrayList.
Classes
class Iter
A synchronized iterator with a check for write permission prior element removal.
class ListIter
A synchronized list iterator with a check for write permission prior element removal.
Public Member Functions
CheckedArrayList (final Class< E > type)
Constructs a list of the specified type.
CheckedArrayList (final Class< E > type, final int capacity)
Constructs a list of the specified type and initial capacity.
Class< E > getElementType ()
Returns the element type given at construction time.
Iterator< E > iterator ()
Returns an iterator over the elements in this list.
ListIterator< E > listIterator ()
Returns an iterator over the elements in this list.
ListIterator< E > listIterator (final int index)
Returns an iterator over the elements in this list, starting at the given index.
int size ()
Returns the number of elements in this list.
boolean isEmpty ()
Returns.
boolean contains (final Object o)
Returns.
int indexOf (Object o)
Returns the index of the first occurrence of the specified element in this list, or -1 if none.
int lastIndexOf (Object o)
Returns the index of the last occurrence of the specified element in this list, or -1 if none.
E get (int index)
Returns the element at the specified position in this list.
E set (final int index, final E element) throws IllegalArgumentException, UnsupportedOperationException
Replaces the element at the specified position in this list with the specified element.
boolean add (final E element) throws IllegalArgumentException, UnsupportedOperationException
Appends the specified element to the end of this list.
void add (final int index, final E element) throws IllegalArgumentException, UnsupportedOperationException
Inserts the specified element at the specified position in this list.
boolean addAll (final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
Appends all of the elements in the specified collection to the end of this list, in the order that they are returned by the specified Collection's Iterator.
boolean addAll (final int index, final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
Inserts all of the elements in the specified collection into this list, starting at the specified position.
E remove (int index) throws UnsupportedOperationException
Removes the element at the specified position in this list.
boolean remove (Object o) throws UnsupportedOperationException
Removes the first occurrence of the specified element from this list.
boolean removeAll (Collection<?> c) throws UnsupportedOperationException
Removes all of this list's elements that are also contained in the specified collection.
boolean retainAll (Collection<?> c) throws UnsupportedOperationException
Retains only the elements in this list that are contained in the specified collection.
void trimToSize ()
Trims the capacity to the list's current size.
void ensureCapacity (final int minCapacity)
Increases the capacity, if necessary, to ensure that it can hold the given number of elements.
void clear () throws UnsupportedOperationException
Removes all of the elements from this list.
Object [] toArray ()
Returns an array containing all of the elements in this list.
String toString ()
Returns a string representation of this list.
boolean equals (Object o)
Compares the specified object with this list for equality.
int hashCode ()
Returns the hash code value for this list.
CheckedArrayList< E > clone ()
Returns a shallow copy of this list.
Protected Member Functions
void ensureValid (final E element) throws IllegalArgumentException
Ensures that the given element can be added to this list.
void checkWritePermission () throws UnsupportedOperationException
Checks if changes in this list are allowed.
Object getLock ()
Returns the synchronization lock.
Package Functions
public< T > T [] toArray (T[] a)
Returns an array containing all of the elements in this list in proper sequence.
Private Member Functions
void ensureValidCollection (final Collection<? extends E > collection) throws IllegalArgumentException
Ensures that all elements of the given collection can be added to this list.
Private Attributes
final Class< E > type
The element type.
Static Private Attributes
static final long serialVersionUID = -8265578982723471814L
Serial version UID for compatibility with different versions.
Detailed Description
A Collections::checkedList(List, Class) checked} and Collections::synchronizedList(List) synchronized} ArrayList.
The type checks are performed at run-time in addition to the compile-time checks.
Using this class is similar to wrapping an ArrayList using the methods provided in the standard Collections class, except for the following advantages:
Avoid the two levels of indirection (for type check and synchronization).
Checks for write permission.
Overrideable methods for controlling the synchronization lock, type checks and write permission checks.
The synchronization is provided mostly in order to prevent damages to the list in case of concurrent access. It does not prevent java.util.ConcurrentModificationException to be thrown during iterations, unless the whole iteration is synchronized on this list getLock() lock}. For real concurrency, see the java.util.concurrent package instead.
{
Note
The above is the reason why the name of this class emphases the <cite>checked</cite> aspect rather than the <cite>synchronized</cite> aspect of the list.}
Parameters
<E> The type of elements in the list.
Author
Martin Desruisseaux (Geomatys)
Since
2.1
Version
3.22
See also
Collections::checkedList(List, Class)
Collections::synchronizedList(List)
Constructor & Destructor Documentation
CheckedArrayList() [1/2]
CheckedArrayList (final Class< E > type)
Constructs a list of the specified type.
Parameters
type The element type (can not be null).
References CheckedArrayList< E >.type.
{
         super();
         this.type = type;
         ensureNonNull("type", type);
     }
CheckedArrayList() [2/2]
CheckedArrayList (final Class< E > type, final int capacity)
Constructs a list of the specified type and initial capacity.
Parameters
type The element type (should not be null).
capacity The initial capacity.
References CheckedArrayList< E >.type.
{
         super(capacity);
         this.type = type;
         ensureNonNull("type", type);
     }
Member Function Documentation
add() [1/2]
boolean add (final E element) throws IllegalArgumentException, UnsupportedOperationException
Appends the specified element to the end of this list.
Parameters
element element to be appended to this list.
Returns
always
true
.
Exceptions
IllegalArgumentException if the specified element is not of the expected type.
UnsupportedOperationException if this collection is unmodifiable.
References CheckedArrayList< E >.checkWritePermission(), CheckedArrayList< E >.ensureValid(), and CheckedArrayList< E >.getLock().
     {
         ensureValid(element);
         synchronized (getLock()) {
             checkWritePermission();
             return super.add(element);
         }
     }
add() [2/2]
void add (final int index, final E element) throws IllegalArgumentException, UnsupportedOperationException
Inserts the specified element at the specified position in this list.
Parameters
index index at which the specified element is to be inserted.
element element to be inserted.
Exceptions
IndexOutOfBoundsException if index out of range.
IllegalArgumentException if the specified element is not of the expected type.
UnsupportedOperationException if this collection is unmodifiable.
References CheckedArrayList< E >.checkWritePermission(), CheckedArrayList< E >.ensureValid(), and CheckedArrayList< E >.getLock().
     {
         ensureValid(element);
         synchronized (getLock()) {
             checkWritePermission();
             super.add(index, element);
         }
     }
addAll() [1/2]
boolean addAll (final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
Appends all of the elements in the specified collection to the end of this list, in the order that they are returned by the specified Collection's Iterator.
Parameters
collection the elements to be inserted into this list.
Returns
true
if this list changed as a result of the call.
Exceptions
IllegalArgumentException if at least one element is not of the expected type.
UnsupportedOperationException if this collection is unmodifiable.
References CheckedArrayList< E >.checkWritePermission(), CheckedArrayList< E >.ensureValidCollection(), and CheckedArrayList< E >.getLock().
     {
         ensureValidCollection(collection);
         synchronized (getLock()) {
             checkWritePermission();
             return super.addAll(collection);
         }
     }
addAll() [2/2]
boolean addAll (final int index, final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
Inserts all of the elements in the specified collection into this list, starting at the specified position.
Parameters
index index at which to insert first element fromm the specified collection.
collection elements to be inserted into this list.
Returns
true
if this list changed as a result of the call.
Exceptions
IllegalArgumentException if at least one element is not of the expected type.
UnsupportedOperationException if this collection is unmodifiable.
References CheckedArrayList< E >.checkWritePermission(), CheckedArrayList< E >.ensureValidCollection(), and CheckedArrayList< E >.getLock().
     {
         ensureValidCollection(collection);
         synchronized (getLock()) {
             checkWritePermission();
             return super.addAll(index, collection);
         }
     }
checkWritePermission()
void checkWritePermission () throws UnsupportedOperationException protected
Checks if changes in this list are allowed.
This method is automatically invoked after this list got the getLock() lock} and before any operation that may change the content. If the write operation is allowed, then this method shall returns normally. Otherwise an UnsupportedOperationException is thrown.
The default implementation does nothing significant (see below), thus allowing this list to be modified. Subclasses can override this method if they want to control write permissions.
{
Note
Actually the current implementation contains an assert statement ensuring that the thread holds the lock. This is an implementation details that may change in any future version of the SIS library. Nevertheless methods that override this one are encouraged to invoke super.checkWritePermission().}
Exceptions
UnsupportedOperationException if this list is unmodifiable.
References CheckedArrayList< E >.getLock().
Referenced by CheckedArrayList< E >.ListIter.add(), CheckedArrayList< E >.add(), CheckedArrayList< E >.addAll(), CheckedArrayList< E >.clear(), CheckedArrayList< E >.Iter< ListIterator< E > >.remove(), CheckedArrayList< E >.remove(), CheckedArrayList< E >.removeAll(), CheckedArrayList< E >.retainAll(), CheckedArrayList< E >.ListIter.set(), and CheckedArrayList< E >.set().
{
         assert Thread.holdsLock(getLock());
     }
clear()
void clear () throws UnsupportedOperationException
Removes all of the elements from this list.
Exceptions
UnsupportedOperationException if this collection is unmodifiable.
References CheckedArrayList< E >.checkWritePermission(), and CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             checkWritePermission();
             super.clear();
         }
     }
clone()
CheckedArrayList<E> clone ()
Returns a shallow copy of this list.
Returns
A shallow copy of this list.
Implements Cloneable.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return (CheckedArrayList<E>) super.clone();
         }
     }
contains()
boolean contains (final Object o)
Returns.
true
if this list contains the specified element.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.contains(o);
         }
     }
ensureCapacity()
void ensureCapacity (final int minCapacity)
Increases the capacity, if necessary, to ensure that it can hold the given number of elements.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             super.ensureCapacity(minCapacity);
         }
     }
ensureValid()
void ensureValid (final E element) throws IllegalArgumentException protected
Ensures that the given element can be added to this list.
The default implementation ensures that the object is
null
or assignable to the type specified at construction time. Subclasses can override this method if they need to perform additional checks.
{
}
This method is invoked before to get the synchronization getLock() lock}. This is different than the checkWritePermission() method, which is invoked inside the synchronized block.
Parameters
element the object to check, or
null
.
Exceptions
IllegalArgumentException if the specified element can not be added to this list.
References Errors.format(), and Errors.Keys.IllegalArgumentClass_3.
Referenced by CheckedArrayList< E >.ListIter.add(), CheckedArrayList< E >.add(), CheckedArrayList< E >.ensureValidCollection(), CheckedArrayList< E >.ListIter.set(), and CheckedArrayList< E >.set().
{
         if (element != null && !type.isInstance(element)) {
             throw new IllegalArgumentException(Errors.format(
                     Errors.Keys.IllegalArgumentClass_3, "element", type, element.getClass()));
         }
     }
ensureValidCollection()
void ensureValidCollection (final Collection<? extends E > collection) throws IllegalArgumentException private
Ensures that all elements of the given collection can be added to this list.
Parameters
collection the collection to check, or
null
.
Exceptions
IllegalArgumentException if at least one element can not be added to this list.
References CheckedArrayList< E >.ensureValid().
Referenced by CheckedArrayList< E >.addAll().
{
         for (final E element : collection) {
             ensureValid(element);
         }
     }
equals()
boolean equals (Object o)
Compares the specified object with this list for equality.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.equals(o);
         }
     }
get()
E get (int index)
Returns the element at the specified position in this list.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.get(index);
         }
     }
getElementType()
Class<E> getElementType ()
Returns the element type given at construction time.
References CheckedArrayList< E >.type.
{
         return type;
     }
getLock()
Object getLock () protected
Returns the synchronization lock.
The default implementation returns
this
.
{
on floating point types}
Subclasses that override this method must be careful to update the lock reference (if needed) when this list is clone() cloned}.
Returns
The synchronization lock.
Referenced by CheckedArrayList< E >.ListIter.add(), CheckedArrayList< E >.add(), CheckedArrayList< E >.addAll(), CheckedArrayList< E >.checkWritePermission(), CheckedArrayList< E >.clear(), CheckedArrayList< E >.clone(), CheckedArrayList< E >.contains(), CheckedArrayList< E >.ensureCapacity(), CheckedArrayList< E >.equals(), CheckedArrayList< E >.get(), CheckedArrayList< E >.hashCode(), CheckedArrayList< E >.Iter< ListIterator< E > >.hasNext(), CheckedArrayList< E >.ListIter.hasPrevious(), CheckedArrayList< E >.indexOf(), CheckedArrayList< E >.isEmpty(), CheckedArrayList< E >.iterator(), CheckedArrayList< E >.lastIndexOf(), CheckedArrayList< E >.listIterator(), CheckedArrayList< E >.Iter< ListIterator< E > >.next(), CheckedArrayList< E >.ListIter.nextIndex(), CheckedArrayList< E >.ListIter.previous(), CheckedArrayList< E >.ListIter.previousIndex(), CheckedArrayList< E >.Iter< ListIterator< E > >.remove(), CheckedArrayList< E >.remove(), CheckedArrayList< E >.removeAll(), CheckedArrayList< E >.retainAll(), CheckedArrayList< E >.ListIter.set(), CheckedArrayList< E >.set(), CheckedArrayList< E >.size(), CheckedArrayList< E >.toArray(), CheckedArrayList< E >.toString(), and CheckedArrayList< E >.trimToSize().
{
         return this;
     }
hashCode()
int hashCode ()
Returns the hash code value for this list.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.hashCode();
         }
     }
indexOf()
int indexOf (Object o)
Returns the index of the first occurrence of the specified element in this list, or -1 if none.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.indexOf(o);
         }
     }
isEmpty()
boolean isEmpty ()
Returns.
true
if this list contains no elements.
References CheckedArrayList< E >.getLock().
Referenced by NotifiedCheckedList< E >.clear().
{
         synchronized (getLock()) {
             return super.isEmpty();
         }
     }
iterator()
Iterator<E> iterator ()
Returns an iterator over the elements in this list.
The returned iterator will support Iterator::remove() element removal} only if the checkWritePermission() method does not throw exception.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return new Iter<>(super.iterator());
         }
     }
lastIndexOf()
int lastIndexOf (Object o)
Returns the index of the last occurrence of the specified element in this list, or -1 if none.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.lastIndexOf(o);
         }
     }
listIterator() [1/2]
ListIterator<E> listIterator ()
Returns an iterator over the elements in this list.
The returned iterator will support ListIterator::remove() element removal}, ListIterator::add(Object) addition} or ListIterator::set(Object) modification} only if the checkWritePermission() method does not throw exception.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return new ListIter(super.listIterator());
         }
     }
listIterator() [2/2]
ListIterator<E> listIterator (final int index)
Returns an iterator over the elements in this list, starting at the given index.
The returned iterator will support ListIterator::remove() element removal}, ListIterator::add(Object) addition} or ListIterator::set(Object) modification} only if the checkWritePermission() method does not throw exception.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return new ListIter(super.listIterator(index));
         }
     }
remove() [1/2]
E remove (int index) throws UnsupportedOperationException
Removes the element at the specified position in this list.
Exceptions
UnsupportedOperationException if this collection is unmodifiable.
References CheckedArrayList< E >.checkWritePermission(), and CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             checkWritePermission();
             return super.remove(index);
         }
     }
remove() [2/2]
boolean remove (Object o) throws UnsupportedOperationException
Removes the first occurrence of the specified element from this list.
Exceptions
UnsupportedOperationException if this collection is unmodifiable.
References CheckedArrayList< E >.checkWritePermission(), and CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             checkWritePermission();
             return super.remove(o);
         }
     }
removeAll()
boolean removeAll (Collection<?> c) throws UnsupportedOperationException
Removes all of this list's elements that are also contained in the specified collection.
Exceptions
UnsupportedOperationException if this collection is unmodifiable.
References CheckedArrayList< E >.checkWritePermission(), and CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             checkWritePermission();
             return super.removeAll(c);
         }
     }
retainAll()
boolean retainAll (Collection<?> c) throws UnsupportedOperationException
Retains only the elements in this list that are contained in the specified collection.
Exceptions
UnsupportedOperationException if this collection is unmodifiable.
References CheckedArrayList< E >.checkWritePermission(), and CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             checkWritePermission();
             return super.retainAll(c);
         }
     }
set()
E set (final int index, final E element) throws IllegalArgumentException, UnsupportedOperationException
Replaces the element at the specified position in this list with the specified element.
Parameters
index index of element to replace.
element element to be stored at the specified position.
Returns
the element previously at the specified position.
Exceptions
IndexOutOfBoundsException if index out of range.
IllegalArgumentException if the specified element is not of the expected type.
UnsupportedOperationException if this collection is unmodifiable.
References CheckedArrayList< E >.checkWritePermission(), CheckedArrayList< E >.ensureValid(), and CheckedArrayList< E >.getLock().
     {
         ensureValid(element);
         synchronized (getLock()) {
             checkWritePermission();
             return super.set(index, element);
         }
     }
size()
int size ()
Returns the number of elements in this list.
References CheckedArrayList< E >.getLock().
                       {
         synchronized (getLock()) {
             return super.size();
         }
     }
toArray() [1/2]
Object [] toArray ()
Returns an array containing all of the elements in this list.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.toArray();
         }
     }
toArray() [2/2]
public<T> T [] toArray (T [] a) package
Returns an array containing all of the elements in this list in proper sequence.
Parameters
<T> The type of array elements.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.toArray(a);
         }
     }
toString()
String toString ()
Returns a string representation of this list.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.toString();
         }
     }
trimToSize()
void trimToSize ()
Trims the capacity to the list's current size.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             super.trimToSize();
         }
     }
Member Data Documentation
serialVersionUID
final long serialVersionUID = -8265578982723471814L static private
Serial version UID for compatibility with different versions.
type
final Class<E> type private
The element type.
Referenced by CheckedArrayList< E >.CheckedArrayList(), and CheckedArrayList< E >.getElementType().