jena-geo: CheckedHashMap< K, V >.Iter< E > Class Template Reference
CheckedHashMap< K, V >.Iter< E > Class Template Reference
A synchronized iterator with a check for write permission prior element removal.
Public Member Functions
boolean hasNext ()
Returns.
E next () throws NoSuchElementException
Returns the next element in the iteration.
void remove () throws UnsupportedOperationException
Removes the previous element if the enclosing CheckedHashMap allows write operations.
Package Functions
Iter (final Iterator< E > iterator)
Creates a new wrapper for the given LinkedHashMap iterator.
Private Attributes
final Iterator< E > iterator
The LinkedHashMap iterator.
Detailed Description
A synchronized iterator with a check for write permission prior element removal.
This class wraps the iterator provided by the LinkedHashMap views.
Constructor & Destructor Documentation
Iter()
Iter (final Iterator< E > iterator) package
Creates a new wrapper for the given LinkedHashMap iterator.
References CheckedHashMap< K, V >.Iter< E >.iterator.
{
             this.iterator = iterator;
         }
Member Function Documentation
hasNext()
boolean hasNext ()
Returns.
true
if there is more elements in the iteration.
References CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 return iterator.hasNext();
             }
         }
next()
E next () throws NoSuchElementException
Returns the next element in the iteration.
References CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 return iterator.next();
             }
         }
remove()
void remove () throws UnsupportedOperationException
Removes the previous element if the enclosing CheckedHashMap allows write operations.
References CheckedHashMap< K, V >.checkWritePermission(), and CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 checkWritePermission();
                 iterator.remove();
             }
         }
Member Data Documentation
iterator
final Iterator<E> iterator private
The LinkedHashMap iterator.
Referenced by CheckedHashMap< K, V >.Iter< E >.Iter().