jena-geo: LazyLoadElement Class Reference
LazyLoadElement Class Reference
Implementation of org.w3c.dom.Element to lazy load XML file on element access.
Public Member Functions
LazyLoadElement (Path xmlFile)
String getTagName ()
String getAttribute (String name)
void setAttribute (String name, String value) throws DOMException
void removeAttribute (String name) throws DOMException
Attr getAttributeNode (String name)
Attr setAttributeNode (Attr newAttr) throws DOMException
Attr removeAttributeNode (Attr oldAttr) throws DOMException
NodeList getElementsByTagName (String name)
String getAttributeNS (String namespaceURI, String localName) throws DOMException
void setAttributeNS (String namespaceURI, String qualifiedName, String value) throws DOMException
void removeAttributeNS (String namespaceURI, String localName) throws DOMException
Attr getAttributeNodeNS (String namespaceURI, String localName) throws DOMException
Attr setAttributeNodeNS (Attr newAttr) throws DOMException
NodeList getElementsByTagNameNS (String namespaceURI, String localName) throws DOMException
boolean hasAttribute (String name)
boolean hasAttributeNS (String namespaceURI, String localName) throws DOMException
TypeInfo getSchemaTypeInfo ()
void setIdAttribute (String name, boolean isId) throws DOMException
void setIdAttributeNS (String namespaceURI, String localName, boolean isId) throws DOMException
void setIdAttributeNode (Attr idAttr, boolean isId) throws DOMException
String getNodeName ()
String getNodeValue () throws DOMException
void setNodeValue (String nodeValue) throws DOMException
short getNodeType ()
Node getParentNode ()
NodeList getChildNodes ()
Node getFirstChild ()
Node getLastChild ()
Node getPreviousSibling ()
Node getNextSibling ()
NamedNodeMap getAttributes ()
Document getOwnerDocument ()
Node insertBefore (Node newChild, Node refChild) throws DOMException
Node replaceChild (Node newChild, Node oldChild) throws DOMException
Node removeChild (Node oldChild) throws DOMException
Node appendChild (Node newChild) throws DOMException
boolean hasChildNodes ()
Node cloneNode (boolean deep)
void normalize ()
boolean isSupported (String feature, String version)
String getNamespaceURI ()
String getPrefix ()
void setPrefix (String prefix) throws DOMException
String getLocalName ()
boolean hasAttributes ()
String getBaseURI ()
short compareDocumentPosition (Node other) throws DOMException
String getTextContent () throws DOMException
void setTextContent (String textContent) throws DOMException
boolean isSameNode (Node other)
String lookupPrefix (String namespaceURI)
boolean isDefaultNamespace (String namespaceURI)
String lookupNamespaceURI (String prefix)
boolean isEqualNode (Node arg)
Object getFeature (String feature, String version)
Object setUserData (String key, Object data, UserDataHandler handler)
Object getUserData (String key)
Private Member Functions
Element getElement ()
Use double check synchronization to ensure Element is loaded once by the first thread using it.
Private Attributes
final Path xmlFile
volatile Element element
volatile boolean loaded = false
Static Private Attributes
static final Logger LOGGER = Logging.getLogger("org.geotoolkit.util.dom")
Detailed Description
Implementation of org.w3c.dom.Element to lazy load XML file on element access.
This may be used to reduce memory footprint of javax.imageio.metadata.IIOMetadata when metadata tree is merged with an external metadata xml file.
Author
Quentin Boileau (Geomatys)
Constructor & Destructor Documentation
LazyLoadElement()
LazyLoadElement (Path xmlFile)
References LazyLoadElement.xmlFile.
{
         this.xmlFile = xmlFile;
     }
Member Function Documentation
appendChild()
Node appendChild (Node newChild) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.appendChild(newChild) : null;
     }
cloneNode()
Node cloneNode (boolean deep)
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.cloneNode(deep) : null;
     }
compareDocumentPosition()
short compareDocumentPosition (Node other) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.compareDocumentPosition(other) : 0;
     }
getAttribute()
String getAttribute (String name)
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getAttribute(name) : null;
     }
getAttributeNode()
Attr getAttributeNode (String name)
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getAttributeNode(name) : null;
     }
getAttributeNodeNS()
Attr getAttributeNodeNS (String namespaceURI, String localName) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getAttributeNodeNS(namespaceURI, localName) : null;
     }
getAttributeNS()
String getAttributeNS (String namespaceURI, String localName) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getAttributeNS(namespaceURI, localName) : null;
     }
getAttributes()
NamedNodeMap getAttributes ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getAttributes() : null;
     }
getBaseURI()
String getBaseURI ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getBaseURI() : null;
     }
getChildNodes()
NodeList getChildNodes ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getChildNodes() : null;
     }
getElement()
Element getElement () private
Use double check synchronization to ensure Element is loaded once by the first thread using it.
Returns
org.w3c.dom.Element or null if file can't be read or invalid.
References LazyLoadElement.element, and DomUtilities.read().
Referenced by LazyLoadElement.appendChild(), LazyLoadElement.cloneNode(), LazyLoadElement.compareDocumentPosition(), LazyLoadElement.getAttribute(), LazyLoadElement.getAttributeNode(), LazyLoadElement.getAttributeNodeNS(), LazyLoadElement.getAttributeNS(), LazyLoadElement.getAttributes(), LazyLoadElement.getBaseURI(), LazyLoadElement.getChildNodes(), LazyLoadElement.getElementsByTagName(), LazyLoadElement.getElementsByTagNameNS(), LazyLoadElement.getFeature(), LazyLoadElement.getFirstChild(), LazyLoadElement.getLastChild(), LazyLoadElement.getLocalName(), LazyLoadElement.getNamespaceURI(), LazyLoadElement.getNextSibling(), LazyLoadElement.getNodeName(), LazyLoadElement.getNodeType(), LazyLoadElement.getNodeValue(), LazyLoadElement.getOwnerDocument(), LazyLoadElement.getParentNode(), LazyLoadElement.getPrefix(), LazyLoadElement.getPreviousSibling(), LazyLoadElement.getSchemaTypeInfo(), LazyLoadElement.getTagName(), LazyLoadElement.getTextContent(), LazyLoadElement.getUserData(), LazyLoadElement.hasAttribute(), LazyLoadElement.hasAttributeNS(), LazyLoadElement.hasAttributes(), LazyLoadElement.hasChildNodes(), LazyLoadElement.insertBefore(), LazyLoadElement.isDefaultNamespace(), LazyLoadElement.isEqualNode(), LazyLoadElement.isSameNode(), LazyLoadElement.isSupported(), LazyLoadElement.lookupNamespaceURI(), LazyLoadElement.lookupPrefix(), LazyLoadElement.normalize(), LazyLoadElement.removeAttribute(), LazyLoadElement.removeAttributeNode(), LazyLoadElement.removeAttributeNS(), LazyLoadElement.removeChild(), LazyLoadElement.replaceChild(), LazyLoadElement.setAttribute(), LazyLoadElement.setAttributeNode(), LazyLoadElement.setAttributeNodeNS(), LazyLoadElement.setAttributeNS(), LazyLoadElement.setIdAttribute(), LazyLoadElement.setIdAttributeNode(), LazyLoadElement.setIdAttributeNS(), LazyLoadElement.setNodeValue(), LazyLoadElement.setPrefix(), LazyLoadElement.setTextContent(), and LazyLoadElement.setUserData().
{
         if (!loaded) {
             synchronized (this) {
                 if (!loaded) {
                     try {
                         Document doc = DomUtilities.read(xmlFile);
                         element = doc.getDocumentElement();
                     } catch (IOException | ParserConfigurationException | SAXException ex) {
                         LOGGER.log(Level.WARNING, "Unable to load file : "+xmlFile, ex);
                     }
                     loaded = true;
                 }
             }
         }
         return element;
     }
getElementsByTagName()
NodeList getElementsByTagName (String name)
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getElementsByTagName(name) : null;
     }
getElementsByTagNameNS()
NodeList getElementsByTagNameNS (String namespaceURI, String localName) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getElementsByTagNameNS(namespaceURI, localName) : null;
     }
getFeature()
Object getFeature (String feature, String version)
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getFeature(feature, version) : null;
     }
getFirstChild()
Node getFirstChild ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getFirstChild() : null;
     }
getLastChild()
Node getLastChild ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getLastChild() : null;
     }
getLocalName()
String getLocalName ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getLocalName() : null;
     }
getNamespaceURI()
String getNamespaceURI ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getNamespaceURI() : null;
     }
getNextSibling()
Node getNextSibling ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getNextSibling() : null;
     }
getNodeName()
String getNodeName ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getNodeName() : null;
     }
getNodeType()
short getNodeType ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getNodeType() : Node.ELEMENT_NODE;
     }
getNodeValue()
String getNodeValue () throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getNodeValue() : null;
     }
getOwnerDocument()
Document getOwnerDocument ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getOwnerDocument() : null;
     }
getParentNode()
Node getParentNode ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getParentNode() : null;
     }
getPrefix()
String getPrefix ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getPrefix() : null;
     }
getPreviousSibling()
Node getPreviousSibling ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getPreviousSibling() : null;
     }
getSchemaTypeInfo()
TypeInfo getSchemaTypeInfo ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getSchemaTypeInfo() : null;
     }
getTagName()
String getTagName ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getTagName() : null;
     }
getTextContent()
String getTextContent () throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getTextContent() : null;
     }
getUserData()
Object getUserData (String key)
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.getUserData(key) : null;
     }
hasAttribute()
boolean hasAttribute (String name)
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.hasAttribute(name) : Boolean.FALSE;
     }
hasAttributeNS()
boolean hasAttributeNS (String namespaceURI, String localName) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.hasAttributeNS(namespaceURI, localName) : Boolean.FALSE;
     }
hasAttributes()
boolean hasAttributes ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.hasAttributes() : Boolean.FALSE;
     }
hasChildNodes()
boolean hasChildNodes ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.hasChildNodes() : Boolean.FALSE;
     }
insertBefore()
Node insertBefore (Node newChild, Node refChild) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.insertBefore(newChild, refChild) : null;
     }
isDefaultNamespace()
boolean isDefaultNamespace (String namespaceURI)
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.isDefaultNamespace(namespaceURI) : Boolean.FALSE;
     }
isEqualNode()
boolean isEqualNode (Node arg)
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.isEqualNode(arg) : Boolean.FALSE;
     }
isSameNode()
boolean isSameNode (Node other)
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.isSameNode(other) : Boolean.FALSE;
     }
isSupported()
boolean isSupported (String feature, String version)
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.isSupported(feature, version) : Boolean.FALSE;
     }
lookupNamespaceURI()
String lookupNamespaceURI (String prefix)
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.lookupNamespaceURI(prefix) : null;
     }
lookupPrefix()
String lookupPrefix (String namespaceURI)
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.lookupPrefix(namespaceURI) : null;
     }
normalize()
void normalize ()
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         if (elem != null) elem.normalize();
     }
removeAttribute()
void removeAttribute (String name) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         if (elem != null) elem.removeAttribute(name);
     }
removeAttributeNode()
Attr removeAttributeNode (Attr oldAttr) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.removeAttributeNode(oldAttr) : null;
     }
removeAttributeNS()
void removeAttributeNS (String namespaceURI, String localName) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         if (elem != null) elem.removeAttributeNS(namespaceURI, localName);
     }
removeChild()
Node removeChild (Node oldChild) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.removeChild(oldChild) : null;
     }
replaceChild()
Node replaceChild (Node newChild, Node oldChild) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.replaceChild(newChild, oldChild) : null;
     }
setAttribute()
void setAttribute (String name, String value) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         if (elem != null) elem.setAttribute(name, value);
     }
setAttributeNode()
Attr setAttributeNode (Attr newAttr) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.setAttributeNode(newAttr) : null;
     }
setAttributeNodeNS()
Attr setAttributeNodeNS (Attr newAttr) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.setAttributeNodeNS(newAttr) : null;
     }
setAttributeNS()
void setAttributeNS (String namespaceURI, String qualifiedName, String value) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         if (elem != null) elem.setAttributeNS(namespaceURI, qualifiedName, value);
     }
setIdAttribute()
void setIdAttribute (String name, boolean isId) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         if (elem != null) elem.setIdAttribute(name, isId);
     }
setIdAttributeNode()
void setIdAttributeNode (Attr idAttr, boolean isId) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         if (elem != null) elem.setIdAttributeNode(idAttr, isId);
     }
setIdAttributeNS()
void setIdAttributeNS (String namespaceURI, String localName, boolean isId) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         if (elem != null) elem.setIdAttributeNS(namespaceURI, localName, isId);
     }
setNodeValue()
void setNodeValue (String nodeValue) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         if (elem != null) elem.setNodeValue(nodeValue);
     }
setPrefix()
void setPrefix (String prefix) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         if (elem != null) elem.setPrefix(prefix);
     }
setTextContent()
void setTextContent (String textContent) throws DOMException
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         if (elem != null) elem.setTextContent(textContent);
     }
setUserData()
Object setUserData (String key, Object data, UserDataHandler handler)
References LazyLoadElement.getElement().
{
         final Element elem = getElement();
         return elem != null ? elem.setUserData(key, data, handler) : null;
     }
Member Data Documentation
element
volatile Element element private
Referenced by LazyLoadElement.getElement().
loaded
volatile boolean loaded = false private
LOGGER
final Logger LOGGER = Logging.getLogger("org.geotoolkit.util.dom") static private
xmlFile
final Path xmlFile private
Referenced by LazyLoadElement.LazyLoadElement().