jena-geo: MonoDimensionMove Class Reference
MonoDimensionMove Class Reference
Public Member Functions
MonoDimensionMove (int dimension, double[] startPoint, final double distanceLeft)
boolean tryAdvance (final Consumer<? super double[]> consumer)
Spliterator< double[]> trySplit ()
long estimateSize ()
int characteristics ()
Package Attributes
boolean hasNext = true
Private Attributes
final int dimension
double [] startPoint
Point to consider as origin for the next move.
final DoubleUnaryOperator moveDir
double distanceLeft
Detailed Description
Author
Alexis Manin (Geomatys)
Constructor & Destructor Documentation
MonoDimensionMove()
MonoDimensionMove (int dimension, double [] startPoint, final double distanceLeft)
References GridTraversal.ceilOrIncrement(), MonoDimensionMove.dimension, MonoDimensionMove.distanceLeft, and GridTraversal.floorOrDecrement().
Referenced by MonoDimensionMove.trySplit().
{
             this.dimension = dimension;
             this.startPoint = Arrays.copyOf(startPoint, startPoint.length);
             this.distanceLeft = distanceLeft;
             moveDir = (distanceLeft < 0)? GridTraversal::floorOrDecrement : GridTraversal::ceilOrIncrement;
         }
Member Function Documentation
characteristics()
int characteristics ()
{
             return ORDERED | DISTINCT | NONNULL;
         }
estimateSize()
long estimateSize ()
{
             /* TODO : Not exact: we could have one more element left initially.
              * Example : if distanceleft=2.3, and our current position is 1.9, we must browse values 2.0, 3.0, 4.0 and
              * 4.2. But, with below computation, we will return 3 moves left instead of 4.
              */
             return (long) Math.ceil(Math.abs(distanceLeft));
         }
tryAdvance()
boolean tryAdvance (final Consumer<? super double[]> consumer)
References MonoDimensionMove.dimension, MonoDimensionMove.distanceLeft, and GridTraversal.isNearZero().
{
             if (!hasNext || GridTraversal.isNearZero(distanceLeft)) return false;
             final double start = startPoint[dimension];
             double nextPos = moveDir.applyAsDouble(start);
             final double dist = nextPos - start;
             if (Math.abs(dist) > Math.abs(distanceLeft)) {
                 nextPos = start + distanceLeft;
                 hasNext = false;
             }
             distanceLeft -= dist;
             final double[] nextPoint = new double[startPoint.length];
             System.arraycopy(startPoint, 0, nextPoint, 0, startPoint.length);
             nextPoint[dimension] = nextPos;
             consumer.accept(nextPoint);
             startPoint = nextPoint;
             return true;
         }
trySplit()
Spliterator<double[]> trySplit ()
References MonoDimensionMove.dimension, and MonoDimensionMove.MonoDimensionMove().
{
             if (distanceLeft < 3.0) {
                 return null;
             } else {
                 // For consistency, we must cut on an integer value. Otherwise, we would introduce a point in an
                 // arbitrary position in the grid.
                 double cutDistance = distanceLeft/2.0;
                 double cutNearestInt = Math.floor(startPoint[dimension] + cutDistance);
                 cutDistance = distanceLeft - (cutNearestInt - startPoint[dimension]);
                 distanceLeft -= cutDistance;
                 final double[] splitStart = Arrays.copyOf(startPoint, startPoint.length);
                 splitStart[dimension] = cutNearestInt;
                 final MonoDimensionMove prefix = new MonoDimensionMove(dimension, startPoint, distanceLeft);
                 startPoint = splitStart;
                 distanceLeft = cutDistance;
                 return prefix;
             }
         }
Member Data Documentation
dimension
final int dimension private
Referenced by MonoDimensionMove.MonoDimensionMove(), MonoDimensionMove.tryAdvance(), and MonoDimensionMove.trySplit().
distanceLeft
double distanceLeft private
Referenced by MonoDimensionMove.MonoDimensionMove(), and MonoDimensionMove.tryAdvance().
hasNext
boolean hasNext = true package
moveDir
final DoubleUnaryOperator moveDir private
startPoint
double [] startPoint private
Point to consider as origin for the next move.