jena-geo: CheckedArrayList< E >.ListIter Class Reference
CheckedArrayList< E >.ListIter Class Reference
A synchronized list iterator with a check for write permission prior element removal.
Public Member Functions
int nextIndex ()
Returns the index of the element to be returned by next().
int previousIndex ()
Returns the index of the element to be returned by previous().
boolean hasPrevious ()
Returns.
E previous () throws NoSuchElementException
Returns the previous element in the iteration.
void set (final E element) throws IllegalArgumentException, UnsupportedOperationException
See the CheckedArrayList#set(int, Object) method contract.
void add (final E element) throws IllegalArgumentException, UnsupportedOperationException
See the CheckedArrayList#add(Object) method contract.
final boolean hasNext ()
Returns.
final E next () throws NoSuchElementException
Returns the next element in the iteration.
final void remove () throws UnsupportedOperationException
Removes the previous element if the enclosing CheckedArrayList allows write operations.
Protected Attributes
final I iterator
The ArrayList iterator.
Package Functions
ListIter (final ListIterator< E > iterator)
Creates a new wrapper for the given ArrayList list iterator.
Detailed Description
A synchronized list iterator with a check for write permission prior element removal.
This class wraps the iterator provided by ArrayList#listIterator().
See also
CheckedArrayList::listIterator()
CheckedArrayList::listIterator(int)
Constructor & Destructor Documentation
ListIter()
ListIter (final ListIterator< E > iterator) package
Creates a new wrapper for the given ArrayList list iterator.
{
             super(iterator);
         }
Member Function Documentation
add()
void add (final E element) throws IllegalArgumentException, UnsupportedOperationException
See the CheckedArrayList#add(Object) method contract.
References CheckedArrayList< E >.checkWritePermission(), CheckedArrayList< E >.ensureValid(), CheckedArrayList< E >.getLock(), and CheckedArrayList< E >.Iter< I extends Iterator< E >.iterator.
{
             ensureValid(element);
             synchronized (getLock()) {
                 checkWritePermission();
                 iterator.add(element);
             }
         }
hasNext()
final boolean hasNext () inherited
Returns.
true
if there is more elements in the iteration.
References CheckedArrayList< E >::getLock().
{
             synchronized (getLock()) {
                 return iterator.hasNext();
             }
         }
hasPrevious()
boolean hasPrevious ()
Returns.
true
if there is elements before current position.
References CheckedArrayList< E >.getLock(), and CheckedArrayList< E >.Iter< I extends Iterator< E >.iterator.
{
             synchronized (getLock()) {
                 return iterator.hasPrevious();
             }
         }
next()
final E next () throws NoSuchElementException inherited
Returns the next element in the iteration.
References CheckedArrayList< E >::getLock().
{
             synchronized (getLock()) {
                 return iterator.next();
             }
         }
nextIndex()
int nextIndex ()
Returns the index of the element to be returned by next().
References CheckedArrayList< E >.getLock(), and CheckedArrayList< E >.Iter< I extends Iterator< E >.iterator.
{
             synchronized (getLock()) {
                 return iterator.nextIndex();
             }
         }
previous()
E previous () throws NoSuchElementException
Returns the previous element in the iteration.
References CheckedArrayList< E >.getLock(), and CheckedArrayList< E >.Iter< I extends Iterator< E >.iterator.
{
             synchronized (getLock()) {
                 return iterator.previous();
             }
         }
previousIndex()
int previousIndex ()
Returns the index of the element to be returned by previous().
References CheckedArrayList< E >.getLock(), and CheckedArrayList< E >.Iter< I extends Iterator< E >.iterator.
{
             synchronized (getLock()) {
                 return iterator.previousIndex();
             }
         }
remove()
final void remove () throws UnsupportedOperationException inherited
Removes the previous element if the enclosing CheckedArrayList allows write operations.
References CheckedArrayList< E >::checkWritePermission(), and CheckedArrayList< E >::getLock().
{
             synchronized (getLock()) {
                 checkWritePermission();
                 iterator.remove();
             }
         }
set()
void set (final E element) throws IllegalArgumentException, UnsupportedOperationException
See the CheckedArrayList#set(int, Object) method contract.
References CheckedArrayList< E >.checkWritePermission(), CheckedArrayList< E >.ensureValid(), CheckedArrayList< E >.getLock(), and CheckedArrayList< E >.Iter< I extends Iterator< E >.iterator.
{
             ensureValid(element);
             synchronized (getLock()) {
                 checkWritePermission();
                 iterator.set(element);
             }
         }
Member Data Documentation
iterator
final I iterator protected inherited
The ArrayList iterator.