jena-geo: DisjointSet< E >.Iter Class Reference
DisjointSet< E >.Iter Class Reference
The iterator for DisjointSet.
Public Member Functions
boolean hasNext ()
Returns.
E next ()
Returns the next element in the iteration.
void remove ()
Removes from the underlying set the last element returned by the iterator.
Private Member Functions
Iter ()
Construct a new iterator.
Map.Entry< E, DisjointSet< E > > prefetch ()
Returns the prefetch entry.
Private Attributes
final Iterator< Map.Entry< E, DisjointSet< E > > > iterator
The iterator over the entries of the underlying Map object.
Map.Entry< E, DisjointSet< E > > prefetch
Entry for the next element to return, or.
Map.Entry< E, DisjointSet< E > > toRemove
Entry to remove if the remove operation is invoked, or.
Detailed Description
The iterator for DisjointSet.
Author
Martin Desruisseaux (IRD)
Version
3.00
Since
2.0
Constructor & Destructor Documentation
Iter()
Iter () private
Construct a new iterator.
{
             iterator = map.entrySet().iterator();
         }
Member Function Documentation
hasNext()
boolean hasNext ()
Returns.
true
if the iteration has more elements.
References DisjointSet< E >.Iter.prefetch().
{
             return prefetch() != null;
         }
next()
E next ()
Returns the next element in the iteration.
References DisjointSet< E >.Iter.prefetch().
Referenced by DisjointSet< E >.Iter.prefetch().
{
             toRemove = prefetch();
             prefetch = null;
             if (toRemove != null) {
                 return toRemove.getKey();
             } else {
                 throw new NoSuchElementException();
             }
         }
prefetch()
Map.Entry<E, DisjointSet<E> > prefetch () private
Returns the prefetch entry.
If this entry was
null
, fetch the next entry. If there is no more entries, returns
null
.
References DisjointSet< E >.Iter.next().
Referenced by DisjointSet< E >.Iter.hasNext(), and DisjointSet< E >.Iter.next().
{
             toRemove = null;
             if (prefetch == null) {
                 while (iterator.hasNext()) {
                     final Map.Entry<E, DisjointSet<E>> next = iterator.next();
                     if (next.getValue() == DisjointSet.this) {
                         prefetch = next;
                         break;
                     }
                 }
             }
             return prefetch;
         }
remove()
void remove ()
Removes from the underlying set the last element returned by the iterator.
{
             if (toRemove != null) {
                 if (trash != null) {
                     // Move to the trash set.
                     toRemove.setValue(trash);
                 } else {
                     iterator.remove();
                 }
                 toRemove = null;
             } else {
                 throw new IllegalStateException();
             }
         }
Member Data Documentation
iterator
final Iterator<Map.Entry<E, DisjointSet<E> > > iterator private
The iterator over the entries of the underlying Map object.
prefetch
Map.Entry<E, DisjointSet<E> > prefetch private
Entry for the next element to return, or.
null
if there is no more element.
toRemove
Map.Entry<E, DisjointSet<E> > toRemove private
Entry to remove if the remove operation is invoked, or.
null
if this iterator is not in a legal state for element removing. An element can be removed only after a next call and only if this call still synchronized with the Iterator#next call on the underlying map's iterator.