jena-geo: AbstractVersionControl Class Reference
AbstractVersionControl Class Reference abstract
Abstract Version control, override methods to support edition.
Public Member Functions
boolean isEditable ()
Overwrite to enable versioning edition.
boolean isAutomatic ()
Overwrite to enable automatic edition.
Version createVersion (Date date) throws VersioningException
Overwrite to enable manual edition.
void dropVersion (Version version) throws VersioningException
Overwrite to enable manual edition.
void trim (Version version) throws VersioningException
Overwrite to enable versioning edition.
void trim (Date date) throws VersioningException
Overwrite to enable versioning edition.
void revert (Version version) throws VersioningException
Overwrite to enable versioning edition.
void revert (Date date) throws VersioningException
Overwrite to enable versioning edition.
void startVersioning () throws VersioningException
Overwrite to enable versioning edition.
void dropVersioning () throws VersioningException
Overwrite to enable versioning edition.
Version getVersion (String label) throws VersioningException
Find version for given label.
Version getVersion (Date date) throws VersioningException
Returns the version for for given date.
List< Version > list () throws VersioningException
Unmodifiable list of versions available.
boolean isVersioned () throws VersioningException
Test if the object versioning mechanic is present.
Detailed Description
Abstract Version control, override methods to support edition.
Author
Johann Sorel (Geomatys)
Member Function Documentation
createVersion()
Version createVersion (Date date) throws VersioningException
Overwrite to enable manual edition.
Returns
false
Exceptions
VersioningException
Implements VersionControl.
{
         throw new VersioningException("Versioning edition not supported.");
     }
dropVersion()
void dropVersion (Version version) throws VersioningException
Overwrite to enable manual edition.
Returns
false
Exceptions
VersioningException
Implements VersionControl.
{
         throw new VersioningException("Versioning edition not supported.");
     }
dropVersioning()
void dropVersioning () throws VersioningException
Overwrite to enable versioning edition.
Exceptions
VersioningException
Implements VersionControl.
{
         throw new VersioningException("Versioning edition not supported.");
     }
getVersion() [1/2]
Version getVersion (String label) throws VersioningException inherited
Find version for given label.
Parameters
label
Returns
Version or null
Implements VersionHistory.
References VersionHistory.list().
{
         for(Version v : list()){
             if(v.getLabel().equals(label)){
                 return v;
             }
         }
         throw new VersioningException("No version with given label.");
     }
getVersion() [2/2]
Version getVersion (Date date) throws VersioningException inherited
Returns the version for for given date.
In case the date do not overlaps the closest version will be returned.
Parameters
date : date in GMT+0
Returns
Version
Implements VersionHistory.
References VersionHistory.list().
{
         final List<Version> lst = list();
         Collections.sort(lst, new VersionComparator());
         //ensure date in GMT0
         final Calendar vCal = new GregorianCalendar(GMT0);
         final Calendar rCal = new GregorianCalendar(GMT0);
         rCal.setTime(date);
         for(Version v : lst){
             vCal.setTime(v.getDate());
             //if requested date is after version date
             if(rCal.getTimeInMillis() >= vCal.getTimeInMillis()) {
                 return v;
             }
         }
         //date is before. return first version
         //this is not exact, yet versioning might have started a very long time afeter initial data creation.
         return lst.isEmpty() ? null : lst.get(0);
     }
isAutomatic()
boolean isAutomatic ()
Overwrite to enable automatic edition.
Returns
false
Exceptions
VersioningException
Implements VersionControl.
{
         return false;
     }
isEditable()
boolean isEditable ()
Overwrite to enable versioning edition.
Returns
false
Exceptions
VersioningException
Implements VersionControl.
{
         return false;
     }
isVersioned()
boolean isVersioned () throws VersioningException inherited
Test if the object versioning mechanic is present.
If false modifications of the object won't be historized. Use methods install and uninstall to respectivly start versioning and drop the all history.
Returns
true if the versioning is enable.
list()
List<Version> list () throws VersioningException inherited
Unmodifiable list of versions available.
List is ordered by date ascending
Returns
List<Version>
Referenced by AbstractVersionHistory.getVersion().
revert() [1/2]
void revert (Version version) throws VersioningException
Overwrite to enable versioning edition.
Parameters
version
Exceptions
VersioningException
Implements VersionControl.
{
         revert(version.getDate());
     }
revert() [2/2]
void revert (Date date) throws VersioningException
Overwrite to enable versioning edition.
Parameters
version
Exceptions
VersioningException
Implements VersionControl.
{
         throw new VersioningException("Versioning edition not supported.");
     }
startVersioning()
void startVersioning () throws VersioningException
Overwrite to enable versioning edition.
Exceptions
VersioningException
Implements VersionControl.
{
         throw new VersioningException("Versioning edition not supported.");
     }
trim() [1/2]
void trim (Version version) throws VersioningException
Overwrite to enable versioning edition.
Parameters
version
Exceptions
VersioningException
Implements VersionControl.
{
         trim(version.getDate());
     }
trim() [2/2]
void trim (Date date) throws VersioningException
Overwrite to enable versioning edition.
Parameters
version
Exceptions
VersioningException
Implements VersionControl.
{
         throw new VersioningException("Versioning edition not supported.");
     }