jena-geo: CheckedHashMap< K, V >.SyncSet< E > Class Template Reference
CheckedHashMap< K, V >.SyncSet< E > Class Template Reference
A set synchronized on the enclosing map getLock() lock}.
Public Member Functions
final Iterator< E > iterator ()
Returns a synchronized and checked iterator over the elements in this collection.
final int size ()
Returns the number of elements in the collection.
final boolean isEmpty ()
Returns.
final boolean contains (final Object element)
Returns.
final boolean containsAll (final Collection<?> collection)
Returns.
final boolean add (final E element) throws UnsupportedOperationException
Always unsupported operation in hash map views.
final boolean addAll (final Collection<? extends E > collection) throws UnsupportedOperationException
Always unsupported operation in hash map views.
final boolean remove (final Object element) throws UnsupportedOperationException
Remove the given element if the enclosing CheckedHashMap supports write operations.
final boolean removeAll (final Collection<?> collection) throws UnsupportedOperationException
Remove the given elements if the enclosing CheckedHashMap supports write operations.
final boolean retainAll (final Collection<?> collection) throws UnsupportedOperationException
Retains only the given elements if the enclosing CheckedHashMap supports write operations.
final void clear () throws UnsupportedOperationException
Removes all elements from the collection.
final Object [] toArray ()
Returns the elements in an array.
final< T > T [] toArray (final T[] array)
Returns the elements in an array.
final String toString ()
Returns a string representation of the elements.
final boolean equals (final Object other)
Compare this collection with the given object for equality.
final int hashCode ()
Returns a hash code value for this collection.
Package Functions
SyncSet (final Set< E > set)
Create a new synchronized wrapper for the given view.
Detailed Description
A set synchronized on the enclosing map getLock() lock}.
This is used for wrapping Map#keySet() or Map#entrySet() views.
Constructor & Destructor Documentation
SyncSet()
SyncSet (final Set< E > set) package
Create a new synchronized wrapper for the given view.
{
             super(set);
         }
Member Function Documentation
add()
final boolean add (final E element) throws UnsupportedOperationException inherited
Always unsupported operation in hash map views.
References Errors.format(), and Errors.Keys.UnsupportedOperation_1.
{
             throw new UnsupportedOperationException(Errors.format(Errors.Keys.UnsupportedOperation_1, "add"));
         }
addAll()
final boolean addAll (final Collection<? extends E > collection) throws UnsupportedOperationException inherited
Always unsupported operation in hash map views.
References Errors.format(), and Errors.Keys.UnsupportedOperation_1.
{
             throw new UnsupportedOperationException(Errors.format(Errors.Keys.UnsupportedOperation_1, "addAll"));
         }
clear()
final void clear () throws UnsupportedOperationException inherited
Removes all elements from the collection.
References CheckedHashMap< K, V >.checkWritePermission(), and CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 checkWritePermission();
                 view.clear();
             }
         }
contains()
final boolean contains (final Object element) inherited
Returns.
true
if the collection contains the given element.
References CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 return view.contains(element);
             }
         }
containsAll()
final boolean containsAll (final Collection<?> collection) inherited
Returns.
true
if the collection contains all elements of the given collection.
References CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 return view.containsAll(collection);
             }
         }
equals()
final boolean equals (final Object other) inherited
Compare this collection with the given object for equality.
References CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 return view.equals(other);
             }
         }
hashCode()
final int hashCode () inherited
Returns a hash code value for this collection.
References CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 return view.hashCode();
             }
         }
isEmpty()
final boolean isEmpty () inherited
Returns.
true
if the collection is empty.
References CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 return view.isEmpty();
             }
         }
iterator()
final Iterator<E> iterator () inherited
Returns a synchronized and checked iterator over the elements in this collection.
References CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 return new Iter<>(view.iterator());
             }
         }
remove()
final boolean remove (final Object element) throws UnsupportedOperationException inherited
Remove the given element if the enclosing CheckedHashMap supports write operations.
References CheckedHashMap< K, V >.checkWritePermission(), and CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 checkWritePermission();
                 return view.remove(element);
             }
         }
removeAll()
final boolean removeAll (final Collection<?> collection) throws UnsupportedOperationException inherited
Remove the given elements if the enclosing CheckedHashMap supports write operations.
References CheckedHashMap< K, V >.checkWritePermission(), and CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 checkWritePermission();
                 return view.removeAll(collection);
             }
         }
retainAll()
final boolean retainAll (final Collection<?> collection) throws UnsupportedOperationException inherited
Retains only the given elements if the enclosing CheckedHashMap supports write operations.
References CheckedHashMap< K, V >.checkWritePermission(), and CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 checkWritePermission();
                 return view.retainAll(collection);
             }
         }
size()
final int size () inherited
Returns the number of elements in the collection.
References CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 return view.size();
             }
         }
toArray() [1/2]
final Object [] toArray () inherited
Returns the elements in an array.
References CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 return view.toArray();
             }
         }
toArray() [2/2]
final<T> T [] toArray (final T [] array) inherited
Returns the elements in an array.
References CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 return view.toArray(array);
             }
         }
toString()
final String toString () inherited
Returns a string representation of the elements.
References CheckedHashMap< K, V >.getLock().
{
             synchronized (getLock()) {
                 return view.toString();
             }
         }