jena-geo: LazyList< E > Class Template Reference
LazyList< E > Class Template Reference
An immutable list filled when needed from the values returned by an iterator.
Classes
class Iter
The iterator implementation for the LazySet lazy set}.
Public Member Functions
LazyList (final Iterator<? extends E > iterator)
Constructs a list to be filled using the specified iterator.
final boolean isEmpty ()
Returns.
final int size ()
Returns the number of elements in this list.
final E get (final int index) throws IndexOutOfBoundsException
Returns the element at the specified position in this list.
ListIterator< E > listIterator (final int index) throws IndexOutOfBoundsException
Returns an iterator over the elements in this list.
Package Functions
final boolean exists (final int index)
Returns.
Private Member Functions
void addNext ()
Adds the next element from the iterator to this list.
void trimToSize ()
Invoked when we have reached the end of iteration.
Private Attributes
Iterator<? extends E > iterator
The iterator to use for filling this set.
E [] elements
The elements in this set.
int next
Index past the last valid element.
Detailed Description
An immutable list filled when needed from the values returned by an iterator.
Parameters
<E> The type of elements in the list.
Author
Martin Desruisseaux (IRD)
Version
3.00
Since
2.0
Constructor & Destructor Documentation
LazyList()
LazyList (final Iterator<? extends E > iterator)
Constructs a list to be filled using the specified iterator.
Iteration will occurs only when needed.
Parameters
iterator The iterator to use for filling this list.
References LazyList< E >.iterator.
{
         this.iterator = iterator;
         elements = (E[]) new Object[4];
     }
Member Function Documentation
addNext()
void addNext () private
Adds the next element from the iterator to this list.
This method doesn't check if more elements are available; the check must have been done before to invoke this method.
Referenced by LazyList< E >.get(), LazyList< E >.listIterator(), and LazyList< E >.size().
{
         if (next >= elements.length) {
             elements = Arrays.copyOf(elements, next*2);
         }
         elements[next++] = iterator.next();
     }
exists()
final boolean exists (final int index) package
Returns.
true
if an element exists at the given index. The element is not loaded immediately.
NOTE: This method is for use by iterators only. It is not suited for more general usage since it doesn't check for negative index and for skipped elements.
Referenced by LazyList< E >.Iter.hasNext(), and LazyList< E >.Iter.next().
{
         return index < next || (iterator != null && iterator.hasNext());
     }
get()
final E get (final int index) throws IndexOutOfBoundsException
Returns the element at the specified position in this list.
Parameters
index The index at which to obtain an element.
Returns
The element at the given index.
Exceptions
IndexOutOfBoundsException If the given index is out of bounds.
References LazyList< E >.addNext(), Errors.format(), Errors.Keys.IndexOutOfBounds_1, and LazyList< E >.trimToSize().
{
         if (index >= 0) {
             if (index < next) {
                 return elements[index];
             }
             if (iterator != null) {
                 while (iterator.hasNext()) {
                     addNext();
                     if (index < next) {
                         return elements[index];
                     }
                 }
                 trimToSize();
             }
         }
         throw new IndexOutOfBoundsException(Errors.format(Errors.Keys.IndexOutOfBounds_1, index));
     }
isEmpty()
final boolean isEmpty ()
Returns.
true
if this list has no elements.
References LazyList< E >.trimToSize().
{
         if (next != 0) {
             return false;
         }
         if (iterator != null) {
             if (iterator.hasNext()) {
                 return false;
             }
             trimToSize();
         }
         return true;
     }
listIterator()
ListIterator<E> listIterator (final int index) throws IndexOutOfBoundsException
Returns an iterator over the elements in this list.
Parameters
index Index of first element to be returned from the iterator.
Returns
An iterator over the elements in this list.
Exceptions
IndexOutOfBoundsException If the given index is out of bounds.
References LazyList< E >.addNext(), Errors.format(), Errors.Keys.IndexOutOfBounds_1, and LazyList< E >.trimToSize().
{
         if (index >= 0) {
             if (index < next) {
                 return new Iter(index);
             }
             if (iterator != null) {
                 while (iterator.hasNext()) {
                     if (index == next) {
                         return new Iter(index);
                     }
                     addNext();
                 }
                 trimToSize();
             }
         }
         throw new IndexOutOfBoundsException(Errors.format(Errors.Keys.IndexOutOfBounds_1, index));
     }
size()
final int size ()
Returns the number of elements in this list.
Invoking this method force the set to immediately iterates through all remaining elements.
References LazyList< E >.addNext(), LazyList< E >.next, and LazyList< E >.trimToSize().
{
         if (iterator != null) {
             while (iterator.hasNext()) {
                 addNext();
             }
             trimToSize();
         }
         return next;
     }
trimToSize()
void trimToSize () private
Invoked when we have reached the end of iteration.
Referenced by LazyList< E >.get(), LazyList< E >.isEmpty(), LazyList< E >.listIterator(), and LazyList< E >.size().
{
         iterator = null; // Lets GC do its work.
         elements = ArraysExt.resize(elements, next);
     }
Member Data Documentation
elements
E [] elements private
The elements in this set.
This array will grown as needed.
iterator
Iterator<? extends E> iterator private
The iterator to use for filling this set.
Will be set to
null
when the iteration is over.
Referenced by LazyList< E >.LazyList().
next
int next private
Index past the last valid element.
This value will increases as long as there is some elements remaining in the iterator.
Referenced by LazyList< E >.size().