jena-geo: GridTraversal Class Reference
GridTraversal Class Reference
Find all intersections between a regular grid (whose cells are aligned with 0 origin, and size is 1 on each of their axes) and a polyline.
Classes
class Builder
Prepare a grid traversal tool.
class ContiguousArrayPoint
class Point2DList
interface PointList
A simple abstraction allowing to access input polyline points, whatever structure it is in.
Public Member Functions
boolean tryAdvance (Consumer<? super double[]> action)
Spliterator< double[]> trySplit ()
long estimateSize ()
int characteristics ()
Static Public Member Functions
static Stream< double[]> stream (final double[] trajectory, final int dimension, final boolean includeStart, final boolean parallel)
Return a new polyline, populated with points intersecting a grid of reference - origin on (0, 0) and cell size is 1.
Static Package Functions
static double ceilOrIncrement (final double source)
static double floorOrDecrement (final double source)
static boolean isNearZero (double ordinate)
static double [] toVector (double[] start, double[] end)
Static Package Attributes
static final double EPSILON = 1e-7
Private Member Functions
GridTraversal (PointList trajectory)
Create a new traversal analyzer for given polyline.
GridTraversal (final PointList trajectory, final int startPoint, final int endPoint)
void prepareSegment ()
Prepare analysis for the polyline segment denoted by currently configured start and end point.
Private Attributes
final PointList trajectory
int startPoint
final int endPoint
Spliterator< double[]> intersectionEvaluator
Detailed Description
Find all intersections between a regular grid (whose cells are aligned with 0 origin, and size is 1 on each of their axes) and a polyline.
It returns all points of the polyline, adding intersection points on the fly.
To acquire a stream of all points in the populated line string, use stream(double[], int, boolean) or the Builder class.
This algorithm complexity is roughly O(d*n), with d the number of dimensions of the polyline, and n is the total number of intersection point found.
It is partially splittable : each segment of input polyline will be treated in a separate thread if using a parallel stream. Also, if one of the polyline segment is aligned on an reference axis (meaning only one of the dimension is changing along the segment), it can be splitted too.
TODO : make compliant with future ISO-19107 API.
Author
Alexis Manin (Geomatys)
Constructor & Destructor Documentation
GridTraversal() [1/2]
GridTraversal (PointList trajectory) private
Create a new traversal analyzer for given polyline.
Parameters
trajectory The polyline coordinates. We expect coordinates of each points are given in order. Example: for a 3 dimension polyline composed of points a and b, we expect the array to be: [a0, a1, a2, b0, b1, b2].
dimension Number of dimension of the polyline.
References GridTraversal.prepareSegment(), GridTraversal.PointList.size(), and GridTraversal.trajectory.
Referenced by GridTraversal.Builder.stream(), and GridTraversal.trySplit().
{
         this.trajectory = trajectory;
         startPoint = 0;
         endPoint = this.trajectory.size() - 1;
         prepareSegment();
     }
GridTraversal() [2/2]
GridTraversal (final PointList trajectory, final int startPoint, final int endPoint) private
References GridTraversal.endPoint, GridTraversal.prepareSegment(), GridTraversal.startPoint, and GridTraversal.trajectory.
{
         this.trajectory = trajectory;
         this.startPoint = startPoint;
         this.endPoint = endPoint;
         prepareSegment();
     }
Member Function Documentation
ceilOrIncrement()
static double ceilOrIncrement (final double source) static package
Referenced by MonoDimensionMove.MonoDimensionMove(), and MultiDimensionMove.MultiDimensionMove().
{
         double upper = Math.ceil(source);
         if (source - EPSILON < upper && upper < source + EPSILON) {
             upper += 1;
         }
         return upper;
     }
characteristics()
int characteristics ()
{
         // We cannot mark it immutable, because input trajectory is a double array which could be modified externally.
         return ORDERED | NONNULL | DISTINCT;
     }
estimateSize()
long estimateSize ()
{
         return Long.MAX_VALUE;
     }
floorOrDecrement()
static double floorOrDecrement (final double source) static package
Referenced by MonoDimensionMove.MonoDimensionMove(), and MultiDimensionMove.MultiDimensionMove().
{
         double lower = Math.floor(source);
         if (source - EPSILON < lower && lower < source + EPSILON) {
             lower -= 1;
         }
         return lower;
     }
isNearZero()
static boolean isNearZero (double ordinate) static package
References GridTraversal.EPSILON.
Referenced by GridTraversal.prepareSegment(), and MonoDimensionMove.tryAdvance().
{
         return -EPSILON < ordinate && ordinate < EPSILON;
     }
prepareSegment()
void prepareSegment () private
Prepare analysis for the polyline segment denoted by currently configured start and end point.
References GridTraversal.PointList.getPoint(), GridTraversal.isNearZero(), and GridTraversal.toVector().
Referenced by GridTraversal.GridTraversal(), GridTraversal.tryAdvance(), and GridTraversal.trySplit().
{
         if (startPoint >= endPoint)
             return;
         final double[] start = trajectory.getPoint(startPoint);
         final double[] end = trajectory.getPoint(startPoint+1);
         double[] vec = toVector(start, end);
         int nonZeroCount = 0; int lastNonZero = 0;
         for (int i = 0 ; i < vec.length ; i++) {
             if (!isNearZero(vec[i])) {
                 nonZeroCount++;
                 lastNonZero = i;
             }
         }
         switch (nonZeroCount) {
             case 0:
                 startPoint++;
                 prepareSegment();
                 break;
             case 1:
                 intersectionEvaluator = new MonoDimensionMove(lastNonZero, start, vec[lastNonZero]);
                 break;
             default:
                 intersectionEvaluator = new MultiDimensionMove(start, end);
                 break;
         }
     }
stream()
static Stream<double[]> stream (final double [] trajectory, final int dimension, final boolean includeStart, final boolean parallel) static
Return a new polyline, populated with points intersecting a grid of reference - origin on (0, 0) and cell size is 1.
Parameters
trajectory The polyline coordinates. We expect coordinates of each points are given in order. Example: for a 3 dimension polyline composed of points a and b, we expect the array to be: [a0, a1, a2, b0, b1, b2].
dimension Number of dimension of the polyline.
includeStart True if we want result stream to give back start point of given trajectory on first move. False if we want it to omit the first point of input polyline.
parallel True if we want returned stream to use multi-threading, false otherwise.
Returns
A stream giving back in order points composing given polyline, adding points intersecting virual grid in the same time.
References GridTraversal.Builder.setIncludeStart(), GridTraversal.Builder.setParallel(), GridTraversal.Builder.setPolyline(), and GridTraversal.Builder.stream().
{
         return new GridTraversal.Builder()
                 .setPolyline(trajectory, dimension)
                 .setIncludeStart(includeStart)
                 .setParallel(parallel)
                 .stream();
     }
toVector()
static double [] toVector (double [] start, double [] end) static package
Referenced by GridTraversal.prepareSegment().
{
         double[] vec = new double[start.length];
         for (int i = 0; i < vec.length; i++) {
             vec[i] = end[i] - start[i];
         }
         return vec;
     }
tryAdvance()
boolean tryAdvance (Consumer<? super double[]> action)
References GridTraversal.prepareSegment().
{
         while (intersectionEvaluator != null) {
             boolean pushedForward = intersectionEvaluator.tryAdvance(action);
             if (pushedForward) {
                 return true;
             }
             intersectionEvaluator = null;
             startPoint++;
             prepareSegment();
         }
         return false;
     }
trySplit()
Spliterator<double[]> trySplit ()
References GridTraversal.GridTraversal(), GridTraversal.prepareSegment(), and GridTraversal.startPoint.
{
         final int span = endPoint - startPoint;
         if (span > 1) {
             final int splitPoint = startPoint + span / 2;
             // At least two segments remain
             final Spliterator<double[]> prefix = new GridTraversal(trajectory, startPoint, splitPoint);
             this.startPoint = splitPoint;
             prepareSegment();
             return prefix;
         }
         // Last hope : maybe our inner spliterator is splittable
         if (intersectionEvaluator == null) {
             prepareSegment();
         }
         if (intersectionEvaluator != null) {
             return intersectionEvaluator.trySplit();
         }
         return null;
     }
Member Data Documentation
endPoint
final int endPoint private
Referenced by GridTraversal.GridTraversal().
EPSILON
final double EPSILON = 1e-7 static package
Referenced by GridTraversal.isNearZero().
intersectionEvaluator
Spliterator<double[]> intersectionEvaluator private
startPoint
int startPoint private
Referenced by GridTraversal.GridTraversal(), and GridTraversal.trySplit().
trajectory
final PointList trajectory private
Referenced by GridTraversal.GridTraversal().