jena-geo: DomUtilities Class Reference
DomUtilities Class Reference
Utils method for dom parsing.
Static Public Member Functions
static Document read (final Object input) throws ParserConfigurationException, SAXException, IOException
Convinient method to aquiere a DOM document from an input.
static void write (final Document doc, final Object output) throws TransformerException, FileNotFoundException, IOException
Convinient method to write a dom.
static Element firstElement (final Element parent, final String tagName)
Search and return the first node with a given tag name.
static Element firstElement (final Element parent, final String tagName, final boolean recursive)
Search and return the first node with a given tag name.
static List< Element > getListElements (final Element parent, final String tagName)
Search and return the list node with a given tag name.
static List< Element > getListElementsNonRecusive (final Element parent, final String tagName)
Search and return the list node with a given tag name.
static Node getNodeByLocalName (final Node parent, final String name)
Return the first node in the given node children which localName matchs the given name.
static< T > T textValue (final Element parent, final String tagName, final Class< T > clazz) throws UnconvertibleObjectException
Search a child node with the given tag name and return it's text value converted to the given clazz.
static< T > T textValue (final Element parent, final String tagName, final Class< T > clazz, final boolean recursive) throws UnconvertibleObjectException
Search a child node with the given tag name and return it's text value converted to the given clazz.
static< T > T textAttributeValue (final Element parent, final String tagName, final String attributeName, final Class< T > clazz) throws UnconvertibleObjectException
Search a child node with the given tag name and return it's text attribute converted to the given clazz.
static< T > T textAttributeValue (final Element parent, final String tagName, final String attributeName, final Class< T > clazz, boolean recursive) throws UnconvertibleObjectException
Search a child node with the given tag name and return it's text attribute converted to the given clazz.
static< T > T textValueSafe (final Element parent, final String tagName, final Class< T > clazz)
Same as DomUtilities#textValue(org.w3c.dom.Element, java.lang.String, java.lang.Class) but dont throw any exception.
static< T > T textValueSafe (final Element parent, final String tagName, final Class< T > clazz, final boolean recusive)
Same as DomUtilities#textValue(org.w3c.dom.Element, java.lang.String, java.lang.Class) but dont throw any exception.
static< T > T textAttributeValueSafe (final Element parent, final String tagName, final String attributeName, final Class< T > clazz)
Same as DomUtilities#textAttributeValue(org.w3c.dom.Element, java.lang.String, java.lang.String, java.lang.Class) but dont throw any exception.
static< T > T textAttributeValueSafe (final Element parent, final String tagName, final String attributeName, final Class< T > clazz, final boolean recursive)
Same as DomUtilities#textAttributeValue(org.w3c.dom.Element, java.lang.String, java.lang.String, java.lang.Class, java.lang.boolean) but dont throw any exception.
static void prettyPrint (Path input, Path output) throws TransformerConfigurationException, ParserConfigurationException, SAXException, IOException, TransformerException
Reformat and indent an xml file.
Private Member Functions
DomUtilities ()
Static Private Member Functions
static OutputStream toOutputStream (final Object input) throws FileNotFoundException, IOException
Convert an object source to a stream.
static InputStream toInputStream (final Object input) throws FileNotFoundException, IOException
Convert an object source to a stream.
Detailed Description
Utils method for dom parsing.
Author
Johann Sorel (Geomatys)
Constructor & Destructor Documentation
DomUtilities()
DomUtilities () private
 {}
Member Function Documentation
firstElement() [1/2]
static Element firstElement (final Element parent, final String tagName) static
Search and return the first node with a given tag name.
This will search recursivly in the node
Parameters
parent : node to explore
tagName : child node name
Returns
first element with tagName in parent node or null
Referenced by DomUtilities.textAttributeValue(), and DomUtilities.textValue().
{
         return firstElement(parent, tagName, true);
     }
firstElement() [2/2]
static Element firstElement (final Element parent, final String tagName, final boolean recursive) static
Search and return the first node with a given tag name.
Parameters
parent : node to explore
tagName : child node name
recursive : search in sub nodes or not
Returns
first element with tagName in parent node or null
{
         if(recursive){
             final NodeList lst = parent.getElementsByTagName(tagName);
             if(lst.getLength() > 0){
                 return (Element) lst.item(0);
             }
         }else{
             //search only in this node
             final NodeList lst = parent.getChildNodes();
             for(int i=0,n=lst.getLength();i<n;i++){
                 final Node child = lst.item(i);
                 if(child instanceof Element && tagName.equalsIgnoreCase(child.getLocalName())){
                     return (Element) child;
                 }
             }
         }
         return null;
     }
getListElements()
static List<Element> getListElements (final Element parent, final String tagName) static
Search and return the list node with a given tag name.
Parameters
parent : node to explore
tagName : child node name
recursive : search in sub nodes or not
Returns
first element with tagName in parent node or null
{
         final NodeList lst = parent.getElementsByTagName(tagName);
         List<Element> result = new ArrayList<>();
         for(int i=0,n=lst.getLength();i<n;i++){
             final Node child = lst.item(i);
             if(child instanceof Element && tagName.equalsIgnoreCase(child.getNodeName())){
                 result.add((Element) child);
             }
         }
         return result;
     }
getListElementsNonRecusive()
static List<Element> getListElementsNonRecusive (final Element parent, final String tagName) static
Search and return the list node with a given tag name.
Parameters
parent : node to explore
tagName : child node name
recursive : search in sub nodes or not
Returns
first element with tagName in parent node or null
{
         final NodeList lst = parent.getChildNodes();
         List<Element> result = new ArrayList<>();
         for(int i=0,n=lst.getLength();i<n;i++){
             final Node child = lst.item(i);
             if(child instanceof Element && tagName.equalsIgnoreCase(child.getLocalName())){
                 result.add((Element) child);
             }
         }
         return result;
     }
getNodeByLocalName()
static Node getNodeByLocalName (final Node parent, final String name) static
Return the first node in the given node children which localName matchs the given name.
Or null if there are no such node.
{
         if (name.equalsIgnoreCase(parent.getLocalName())) return parent;
         final NodeList lst = parent.getChildNodes();
         for(int i=0,n=lst.getLength();i<n;i++){
             final Node child = lst.item(i);
             if(name.equalsIgnoreCase(child.getLocalName())){
                 return child;
             }
         }
         return null;
     }
prettyPrint()
static void prettyPrint (Path input, Path output) throws TransformerConfigurationException, ParserConfigurationException, SAXException, IOException, TransformerException static
Reformat and indent an xml file.
References DomUtilities.read().
{
         Transformer transformer = TransformerFactory.newInstance().newTransformer();
         transformer.setOutputProperty(OutputKeys.INDENT, "yes");
         transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "2");
         StreamResult result = new StreamResult(output.toFile());
         DOMSource source = new DOMSource(read(input));
         transformer.transform(source, result);
     }
read()
static Document read (final Object input) throws ParserConfigurationException, SAXException, IOException static
Convinient method to aquiere a DOM document from an input.
This is provided as a convinient method, use the default JRE classes so it may not be the faster parsing method.
References DomUtilities.toInputStream().
Referenced by LazyLoadElement.getElement(), and DomUtilities.prettyPrint().
{
         final InputStream stream = toInputStream(input);
         final DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
         final DocumentBuilder constructeur = factory.newDocumentBuilder();
         final Document document = constructeur.parse(stream);
         stream.close();
         return document;
     }
textAttributeValue() [1/2]
static <T> T textAttributeValue (final Element parent, final String tagName, final String attributeName, final Class< T > clazz) throws UnconvertibleObjectException static
Search a child node with the given tag name and return it's text attribute converted to the given clazz.
The convertion in made using the geotoolkit Converters.
Parameters
<T> : wished value class
parent : node to explore
tagName : child node name
attributeName : child node attibute name
clazz : wished value class
Returns
T or null if no node with tagname was found or convertion to given class failed.
References DomUtilities.firstElement().
Referenced by DomUtilities.textAttributeValueSafe().
{
         final Element ele = firstElement(parent, tagName, true);
         if(ele == null) return null;
         final String text = ele.getAttribute(attributeName);
         if(text == null) return null;
         return ObjectConverters.convert(text, clazz);
     }
textAttributeValue() [2/2]
static <T> T textAttributeValue (final Element parent, final String tagName, final String attributeName, final Class< T > clazz, boolean recursive) throws UnconvertibleObjectException static
Search a child node with the given tag name and return it's text attribute converted to the given clazz.
The convertion in made using the geotoolkit Converters.
Parameters
<T> : wished value class
parent : node to explore
tagName : child node name
attributeName : child node attibute name
clazz : wished value class
Returns
T or null if no node with tagname was found or convertion to given class failed.
References DomUtilities.firstElement().
{
         final Element ele = firstElement(parent, tagName, recursive);
         if(ele == null) return null;
         final String text = ele.getAttribute(attributeName);
         if(text == null) return null;
         return ObjectConverters.convert(text, clazz);
     }
textAttributeValueSafe() [1/2]
static <T> T textAttributeValueSafe (final Element parent, final String tagName, final String attributeName, final Class< T > clazz) static
Same as DomUtilities#textAttributeValue(org.w3c.dom.Element, java.lang.String, java.lang.String, java.lang.Class) but dont throw any exception.
References DomUtilities.textAttributeValue().
{
         try {
             return textAttributeValue(parent, tagName,attributeName,  clazz);
         } catch (UnconvertibleObjectException ex) {
             Logging.getLogger("org.geotoolkit.util").log(Level.WARNING, null, ex);
             return null;
         }
     }
textAttributeValueSafe() [2/2]
static <T> T textAttributeValueSafe (final Element parent, final String tagName, final String attributeName, final Class< T > clazz, final boolean recursive) static
Same as DomUtilities#textAttributeValue(org.w3c.dom.Element, java.lang.String, java.lang.String, java.lang.Class, java.lang.boolean) but dont throw any exception.
References DomUtilities.textAttributeValue().
{
         try {
             return textAttributeValue(parent, tagName,attributeName,  clazz, recursive);
         } catch (UnconvertibleObjectException ex) {
             Logging.getLogger("org.geotoolkit.util").log(Level.WARNING, null, ex);
             return null;
         }
     }
textValue() [1/2]
static <T> T textValue (final Element parent, final String tagName, final Class< T > clazz) throws UnconvertibleObjectException static
Search a child node with the given tag name and return it's text value converted to the given clazz.
The convertion in made using the geotoolkit Converters.
Parameters
<T> : wished value class
parent : node to explore
tagName : child node name
clazz : wished value class
Returns
T or null if no node with tagname was found or convertion to given class failed.
References DomUtilities.firstElement().
Referenced by DomUtilities.textValueSafe().
{
         final Element ele = firstElement(parent, tagName, true);
         if(ele == null) return null;
         final String text = ele.getTextContent();
         if(text == null) return null;
         return ObjectConverters.convert(text, clazz);
     }
textValue() [2/2]
static <T> T textValue (final Element parent, final String tagName, final Class< T > clazz, final boolean recursive) throws UnconvertibleObjectException static
Search a child node with the given tag name and return it's text value converted to the given clazz.
The convertion in made using the geotoolkit Converters.
Parameters
<T> : wished value class
parent : node to explore
tagName : child node name
clazz : wished value class
Returns
T or null if no node with tagname was found or convertion to given class failed.
References DomUtilities.firstElement().
{
         final Element ele = firstElement(parent, tagName, recursive);
         if(ele == null) return null;
         final String text = ele.getTextContent();
         if(text == null) return null;
         return ObjectConverters.convert(text, clazz);
     }
textValueSafe() [1/2]
static <T> T textValueSafe (final Element parent, final String tagName, final Class< T > clazz) static
Same as DomUtilities#textValue(org.w3c.dom.Element, java.lang.String, java.lang.Class) but dont throw any exception.
References DomUtilities.textValue().
{
         try {
             return textValue(parent, tagName, clazz);
         } catch (UnconvertibleObjectException ex) {
             Logging.getLogger("org.geotoolkit.util").log(Level.WARNING, null, ex);
             return null;
         }
     }
textValueSafe() [2/2]
static <T> T textValueSafe (final Element parent, final String tagName, final Class< T > clazz, final boolean recusive) static
Same as DomUtilities#textValue(org.w3c.dom.Element, java.lang.String, java.lang.Class) but dont throw any exception.
References DomUtilities.textValue().
{
         try {
             return textValue(parent, tagName, clazz, recusive);
         } catch (UnconvertibleObjectException ex) {
             Logging.getLogger("org.geotoolkit.util").log(Level.WARNING, null, ex);
             return null;
         }
     }
toInputStream()
static InputStream toInputStream (final Object input) throws FileNotFoundException, IOException static private
Convert an object source to a stream.
References IOUtilities.open().
Referenced by DomUtilities.read().
{
         //special case when input object is document itelf
         if (input instanceof String) {
             try {
                 //try to open it as a path
                 final URL url = new URL((String) input);
             } catch (MalformedURLException ex) {
                 //consider it's the document itself
                 return new ByteArrayInputStream(input.toString().getBytes());
             }
         }
         return IOUtilities.open(input);
     }
toOutputStream()
static OutputStream toOutputStream (final Object input) throws FileNotFoundException, IOException static private
Convert an object source to a stream.
References IOUtilities.openWrite().
Referenced by DomUtilities.write().
{
         return IOUtilities.openWrite(input);
     }
write()
static void write (final Document doc, final Object output) throws TransformerException, FileNotFoundException, IOException static
Convinient method to write a dom.
Parameters
doc : DOM document to write
output : output file, url, uri, outputstream
References DomUtilities.toOutputStream().
{
         final Source source = new DOMSource(doc);
         final Result result;
         if(output instanceof File){
             result = new StreamResult((File)output);
         }else if(output instanceof Writer){
             result = new StreamResult((Writer)output);
         }else{
             final OutputStream stream = toOutputStream(output);
             result = new StreamResult(stream);
         }
         final TransformerFactory factory = TransformerFactory.newInstance();
         final Transformer trs = factory.newTransformer();
         trs.setOutputProperty(OutputKeys.INDENT, "yes");
         trs.setOutputProperty(OutputKeys.ENCODING, "ISO-8859-1");
         trs.transform(source, result);
     }