jena-geo: Exceptions Class Reference
Exceptions Class Reference
Utilities methods for dealing with exceptions.
Static Public Member Functions
static boolean isValidMessage (String message)
Returns.
static String formatStackTrace (final Throwable exception)
Returns the exception trace as a string.
static void paintStackTrace (final Graphics2D graphics, final Rectangle widgetBounds, final Throwable exception)
Writes the specified exception trace in the specified graphics context.
static void show (final Component owner, final Throwable exception) throws UnsupportedOperationException
Displays an error message for the specified exception.
static void show (final Component owner, final Throwable exception, final String message) throws UnsupportedOperationException
Displays an error message for the specified exception.
Private Member Functions
Exceptions ()
Do not allow instantiation of this class.
Static Private Member Functions
static void show (final Object[] arguments) throws UnsupportedOperationException
Delegates to the.
Static Private Attributes
static final int TAB_WIDTH = 4
Number of spaces to leave between each tab.
Detailed Description
Utilities methods for dealing with exceptions.
Those methods can reformat the stack trace for console output, paint the stack trace in a Graphics2D handler, or show the stack trace in a <cite>Swing</cite> component.
The <cite>Swing</cite> component is available only if the
geotk-widgets-swing
module is available in the classpath. It looks like the following picture:
Author
Martin Desruisseaux (IRD, Geomatys)
Johann Sorel (Geomatys)
Version
3.21
See also
org.apache.sis.util.Exceptions
Since
2.0
Constructor & Destructor Documentation
Exceptions()
Exceptions () private
Do not allow instantiation of this class.
{
     }
Member Function Documentation
formatStackTrace()
static String formatStackTrace (final Throwable exception) static
Returns the exception trace as a string.
This method get the stack trace using the Throwable#printStackTrace(PrintWriter) method, then replaces the tabulation characters by 4 white spaces.
Parameters
exception The exception to format.
Returns
A string representation of the given exception.
Referenced by Exceptions.paintStackTrace().
{
         final StringWriter writer = new StringWriter();
         exception.printStackTrace(new PrintWriter(writer));
         final StringBuilder buffer = new StringBuilder();
         final LineAppender formatter = new LineAppender(buffer);
         formatter.setTabulationWidth(TAB_WIDTH);
         try {
             formatter.append(writer.toString());
         } catch (IOException e) {
             throw new AssertionError(e);
         }
         return buffer.toString();
     }
isValidMessage()
static boolean isValidMessage (String message) static
Returns.
true
if the given message is non-null and holds a reliable information. The message shall not be null, empty (ignoring white spaces) or equals to the string
"null"
(ignoring case).
This method is intended for use in assertions like below:
{ java assert Exceptions.isValidMessage(message); throw new SomeException(message); }
Parameters
message The message argument to check.
Returns
true
if the message is informative, or
false
otherwise.
Since
3.21
{
         if (message == null) {
             return false;
         }
         message = message.trim();
         return !message.isEmpty() && !message.equalsIgnoreCase("null");
     }
paintStackTrace()
static void paintStackTrace (final Graphics2D graphics, final Rectangle widgetBounds, final Throwable exception) static
Writes the specified exception trace in the specified graphics context.
This method is useful when an exception has occurred inside a java.awt.Component#paint method and we want to write it rather than leaving an empty window.
Parameters
graphics Graphics context in which to write exception. The graphics context shall be in its initial state (default affine transform, default color, etc.)
widgetBounds Size of the trace which was being drawn.
exception Exception whose trace we want to write.
References Exceptions.formatStackTrace().
     {
         /*
          * Obtains the exception trace in the form of a character chain.
          * The carriage returns in this chain can be "\r", "\n" or "r\n".
          */
         final String message = formatStackTrace(exception);
         /*
          * Examines the character chain line by line.
          * "Glyphs" will be created as we go along and we will take advantage
          * of this to calculate the necessary space.
          */
         double width = 0, height = 0;
         final List<GlyphVector> glyphs = new ArrayList<>();
         final List<Rectangle2D> bounds = new ArrayList<>();
         final int length = message.length();
         final Font font = graphics.getFont();
         final FontRenderContext context = graphics.getFontRenderContext();
         for (int i = 0; i < length;) {
             int ir = message.indexOf('\r', i);
             int in = message.indexOf('\n', i);
             if (ir < 0) ir = length;
             if (in < 0) in = length;
             final int irn = Math.min(ir, in);
             final GlyphVector line = font.createGlyphVector(context, message.substring(i, irn));
             final Rectangle2D rect = line.getVisualBounds();
             final double w = rect.getWidth();
             if (w > width) width = w;
             height += rect.getHeight();
             glyphs.add(line);
             bounds.add(rect);
             i = (Math.abs(ir - in) <= 1 ? Math.max(ir, in) : irn) + 1;
         }
         /*
          * Proceeds to draw all the previously calculated glyphs.
          */
         float xpos = widgetBounds.x + (float) (0.5 * Math.max(0, widgetBounds.width  - width));
         float ypos = widgetBounds.y + (float) (0.5 * Math.max(0, widgetBounds.height - height));
         final int size = glyphs.size();
         for (int i = 0; i < size; i++) {
             final GlyphVector line = glyphs.get(i);
             final Rectangle2D rect = bounds.get(i);
             ypos += rect.getHeight();
             graphics.drawGlyphVector(line, xpos, ypos);
         }
     }
show() [1/3]
static void show (final Component owner, final Throwable exception) throws UnsupportedOperationException static
Displays an error message for the specified exception.
Note that this method can be called from any thread (not necessarily the <cite>Swing</cite> thread).
Parameters
owner Component in which the exception is produced, or
null
if unknown.
exception Exception which has been thrown and is to be reported to the user.
Exceptions
UnsupportedOperationException If the
geotk-widgets-swing
module is not found on the classpath.
See also
org.jdesktop.swingx.JXErrorPane
Since
3.18 (derived from 1.0)
Referenced by Exceptions.show().
{
         show(new Object[] {owner, exception});
     }
show() [2/3]
static void show (final Component owner, final Throwable exception, final String message) throws UnsupportedOperationException static
Displays an error message for the specified exception.
Note that this method can be called from any thread (not necessarily the <cite>Swing</cite> thread).
Parameters
owner Component in which the exception is produced, or
null
if unknown.
exception Exception which has been thrown and is to be reported to the user.
message Message to display. If this parameter is
null
, then Exception#getLocalizedMessage will be called to obtain the message.
Exceptions
UnsupportedOperationException If the
geotk-widgets-swing
module is not found on the classpath.
See also
org.jdesktop.swingx.JXErrorPane
Since
3.18 (derived from 1.0)
References Exceptions.show().
     {
         show(new Object[] {owner, exception, message});
     }
show() [3/3]
static void show (final Object [] arguments) throws UnsupportedOperationException static private
Delegates to the.
show
method in the
geotk-widgets-swing
module, if present.
References Errors.format(), and Errors.Keys.MissingModule_1.
{
         final Class<?>[] types = new Class<?>[arguments.length];
         switch (types.length) {
             default: types[2] = String.class;
             case 2:  types[1] = Throwable.class;
             case 1:  types[0] = Component.class;
             case 0:  break;
         }
         try {
             Class.forName("org.geotoolkit.internal.swing.ExceptionMonitor").getMethod("show", types).invoke(null, arguments);
         } catch (ClassNotFoundException e) {
             // This is the expected exception if the widget module is not available.
             throw new UnsupportedOperationException(Errors.format(
                     Errors.Keys.MissingModule_1, "geotk-widgets-swing"), e);
         } catch (NoSuchMethodException | IllegalAccessException e) {
             // Should never happen, since have control on our implementation.
             throw new AssertionError(e);
         } catch (InvocationTargetException e) {
             final Throwable cause = e.getCause();
             if (cause instanceof RuntimeException) {
                 throw (RuntimeException) cause;
             }
             if (cause instanceof Error) {
                 throw (Error) cause;
             }
             // The invoked method does not declare any checked exception,
             // so if we reach this point we have an unexpected exception.
             throw new UndeclaredThrowableException(cause);
         }
     }
Member Data Documentation
TAB_WIDTH
final int TAB_WIDTH = 4 static private
Number of spaces to leave between each tab.