jena-geo: GridTraversal.Builder Class Reference
GridTraversal.Builder Class Reference
Prepare a grid traversal tool.
Public Member Functions
Builder setPolyline (Point2D... coordinates)
Builder setPolyline (final List< Point2D > coordinates)
Builder setPolyline (final double[] coordinates, final int dimension)
Builder setIncludeStart (boolean includeStart)
Builder setParallel (boolean parallel)
Stream< double[]> stream ()
Package Attributes
PointList polyline
boolean includeStart = true
boolean parallel = false
Detailed Description
Prepare a grid traversal tool.
You have to specify at least the polyline to study using one of the setPolyline methods (see setPolyline(double[], int), setPolyline(java.awt.geom.Point2D...) or setPolyline(java.util.List).
You can optionally specify if you want returned point stream to be evaluated with multi-threading using setParallel(boolean) method.
IMPORTANT: There's a method allowwing to configure resulting point stream to omit the polyline first point. That can be useful for ray analysis. By default, result stream return the given polyline start point as first element. Configure this behavior with setIncludeStart(boolean).
Member Function Documentation
setIncludeStart()
Builder setIncludeStart (boolean includeStart)
Parameters
includeStart True if you want the first point of result stream to be input polyline start point. False to omit it.
Returns
this builder for further configuration.
Referenced by GridTraversal.stream().
{
             this.includeStart = includeStart;
             return this;
         }
setParallel()
Builder setParallel (boolean parallel)
Referenced by GridTraversal.stream().
{
             this.parallel = parallel;
             return this;
         }
setPolyline() [1/3]
Builder setPolyline (Point2D... coordinates)
Referenced by GridTraversal.stream().
{
             if (coordinates == null || coordinates.length == 0) {
                 polyline = null;
             }
             return setPolyline(Arrays.asList(coordinates));
         }
setPolyline() [2/3]
Builder setPolyline (final List< Point2D > coordinates)
{
             polyline = coordinates == null? null : new Point2DList(coordinates);
             return this;
         }
setPolyline() [3/3]
Builder setPolyline (final double [] coordinates, final int dimension)
{
             polyline = coordinates == null? null : new ContiguousArrayPoint(coordinates, dimension);
             return this;
         }
stream()
Stream<double[]> stream ()
References GridTraversal.PointList.getPoint(), GridTraversal.GridTraversal(), GridTraversal.PointList.isEmpty(), and GridTraversal.PointList.size().
Referenced by GridTraversal.stream().
{
             ArgumentChecks.ensureNonNull("Polyline", polyline);
             if (polyline.isEmpty()) {
                 return Stream.empty();
             } else if (polyline.size() == 1) {
                 return includeStart ? Stream.of(polyline.getPoint(0)) : Stream.empty();
             } else {
                 Stream<double[]> pointStream = StreamSupport.stream(new GridTraversal(polyline), parallel);
                 if (includeStart) {
                     // Spliterator omit the very first point, so we must add it manually.
                     double[] firstPoint = polyline.getPoint(0);
                     final Stream<double[]> startPoint = Stream.of(firstPoint);
                     return Stream.concat(startPoint, pointStream);
                 } else {
                     return pointStream;
                 }
             }
         }
Member Data Documentation
includeStart
boolean includeStart = true package
parallel
boolean parallel = false package
polyline
PointList polyline package