jena-geo: NotifiedCheckedList< E > Class Template Reference
NotifiedCheckedList< E > Class Template Reference abstract
Abstract synchronized list that define notify methods called when objects are added or removed.
Public Member Functions
NotifiedCheckedList (final Class< E > type)
NotifiedCheckedList (final Class< E > type, final int capacity)
boolean add (final E element) throws IllegalArgumentException, UnsupportedOperationException
void add (final int index, final E element) throws IllegalArgumentException, UnsupportedOperationException
E set (int index, E element) throws IllegalArgumentException, UnsupportedOperationException
boolean addAll (final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
boolean addAll (final int index, final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
boolean remove (final Object o) throws UnsupportedOperationException
E remove (final int index) throws UnsupportedOperationException
boolean removeAll (final Collection<?> c) throws UnsupportedOperationException
void clear () throws UnsupportedOperationException
Class< E > getElementType ()
Returns the element type given at construction time.
Iterator< E > iterator ()
Returns an iterator over the elements in this list.
ListIterator< E > listIterator ()
Returns an iterator over the elements in this list.
ListIterator< E > listIterator (final int index)
Returns an iterator over the elements in this list, starting at the given index.
int size ()
Returns the number of elements in this list.
boolean isEmpty ()
Returns.
boolean contains (final Object o)
Returns.
int indexOf (Object o)
Returns the index of the first occurrence of the specified element in this list, or -1 if none.
int lastIndexOf (Object o)
Returns the index of the last occurrence of the specified element in this list, or -1 if none.
E get (int index)
Returns the element at the specified position in this list.
boolean retainAll (Collection<?> c) throws UnsupportedOperationException
Retains only the elements in this list that are contained in the specified collection.
void trimToSize ()
Trims the capacity to the list's current size.
void ensureCapacity (final int minCapacity)
Increases the capacity, if necessary, to ensure that it can hold the given number of elements.
Object [] toArray ()
Returns an array containing all of the elements in this list.
String toString ()
Returns a string representation of this list.
boolean equals (Object o)
Compares the specified object with this list for equality.
int hashCode ()
Returns the hash code value for this list.
CheckedArrayList< E > clone ()
Returns a shallow copy of this list.
Protected Member Functions
abstract void notifyAdd (final E item, int index)
abstract void notifyAdd (final Collection<? extends E > items, NumberRange< Integer > range)
abstract void notifyChange (final E oldItem, E newItem, int index)
abstract void notifyRemove (final E item, int index)
abstract void notifyRemove (final Collection<? extends E > items, NumberRange< Integer > range)
void ensureValid (final E element) throws IllegalArgumentException
Ensures that the given element can be added to this list.
void checkWritePermission () throws UnsupportedOperationException
Checks if changes in this list are allowed.
Object getLock ()
Returns the synchronization lock.
Package Functions
public< T > T [] toArray (T[] a)
Returns an array containing all of the elements in this list in proper sequence.
Detailed Description
Abstract synchronized list that define notify methods called when objects are added or removed.
Author
Johann Sorel (Geomatys)
Constructor & Destructor Documentation
NotifiedCheckedList() [1/2]
NotifiedCheckedList (final Class< E > type)
{
         super(type);
     }
NotifiedCheckedList() [2/2]
NotifiedCheckedList (final Class< E > type, final int capacity)
References NotifiedCheckedList< E >.notifyAdd(), NotifiedCheckedList< E >.notifyChange(), and NotifiedCheckedList< E >.notifyRemove().
{
         super(type,capacity);
     }
Member Function Documentation
add() [1/2]
boolean add (final E element) throws IllegalArgumentException, UnsupportedOperationException
References NotifiedCheckedList< E >.notifyAdd().
{
         if(element == null) return false;
         final boolean added = super.add(element);
         if (added) {
             final int index = super.size() - 1;
             notifyAdd(element, index);
         }
         return added;
     }
add() [2/2]
void add (final int index, final E element) throws IllegalArgumentException, UnsupportedOperationException
References NotifiedCheckedList< E >.notifyAdd().
{
         super.add(index, element);
         notifyAdd(element, index);
     }
addAll() [1/2]
boolean addAll (final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
References NotifiedCheckedList< E >.notifyAdd().
{
         final int startIndex = super.size();
         final boolean added = super.addAll(collection);
         if (added) {
             notifyAdd(collection, NumberRange.create(startIndex, true, super.size()-1, true) );
         }
         return added;
     }
addAll() [2/2]
boolean addAll (final int index, final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
References NotifiedCheckedList< E >.notifyAdd().
{
         final boolean added = super.addAll(index, collection);
         if (added) {
             notifyAdd(collection, NumberRange.create(index, true, index + collection.size(), true) );
         }
         return added;
     }
checkWritePermission()
void checkWritePermission () throws UnsupportedOperationException protected inherited
Checks if changes in this list are allowed.
This method is automatically invoked after this list got the getLock() lock} and before any operation that may change the content. If the write operation is allowed, then this method shall returns normally. Otherwise an UnsupportedOperationException is thrown.
The default implementation does nothing significant (see below), thus allowing this list to be modified. Subclasses can override this method if they want to control write permissions.
{
Note
Actually the current implementation contains an assert statement ensuring that the thread holds the lock. This is an implementation details that may change in any future version of the SIS library. Nevertheless methods that override this one are encouraged to invoke super.checkWritePermission().}
Exceptions
UnsupportedOperationException if this list is unmodifiable.
References CheckedArrayList< E >.getLock().
Referenced by CheckedArrayList< E >.ListIter.add(), CheckedArrayList< E >.add(), CheckedArrayList< E >.addAll(), CheckedArrayList< E >.clear(), CheckedArrayList< E >.Iter< ListIterator< E > >.remove(), CheckedArrayList< E >.remove(), CheckedArrayList< E >.removeAll(), CheckedArrayList< E >.retainAll(), CheckedArrayList< E >.ListIter.set(), and CheckedArrayList< E >.set().
{
         assert Thread.holdsLock(getLock());
     }
clear()
void clear () throws UnsupportedOperationException
References CheckedArrayList< E >.isEmpty(), and NotifiedCheckedList< E >.notifyRemove().
{
         if(!isEmpty()){
             final Collection<E> copy = new ArrayList<E>(this);
             final NumberRange<Integer> range = NumberRange.create(0, true, copy.size()-1, true);
             super.clear();
             notifyRemove(copy, range);
         }
     }
clone()
CheckedArrayList<E> clone () inherited
Returns a shallow copy of this list.
Returns
A shallow copy of this list.
Implements Cloneable.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return (CheckedArrayList<E>) super.clone();
         }
     }
contains()
boolean contains (final Object o) inherited
Returns.
true
if this list contains the specified element.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.contains(o);
         }
     }
ensureCapacity()
void ensureCapacity (final int minCapacity) inherited
Increases the capacity, if necessary, to ensure that it can hold the given number of elements.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             super.ensureCapacity(minCapacity);
         }
     }
ensureValid()
void ensureValid (final E element) throws IllegalArgumentException protected inherited
Ensures that the given element can be added to this list.
The default implementation ensures that the object is
null
or assignable to the type specified at construction time. Subclasses can override this method if they need to perform additional checks.
{
}
This method is invoked before to get the synchronization getLock() lock}. This is different than the checkWritePermission() method, which is invoked inside the synchronized block.
Parameters
element the object to check, or
null
.
Exceptions
IllegalArgumentException if the specified element can not be added to this list.
References Errors.format(), and Errors.Keys.IllegalArgumentClass_3.
Referenced by CheckedArrayList< E >.ListIter.add(), CheckedArrayList< E >.add(), CheckedArrayList< E >.ensureValidCollection(), CheckedArrayList< E >.ListIter.set(), and CheckedArrayList< E >.set().
{
         if (element != null && !type.isInstance(element)) {
             throw new IllegalArgumentException(Errors.format(
                     Errors.Keys.IllegalArgumentClass_3, "element", type, element.getClass()));
         }
     }
equals()
boolean equals (Object o) inherited
Compares the specified object with this list for equality.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.equals(o);
         }
     }
get()
E get (int index) inherited
Returns the element at the specified position in this list.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.get(index);
         }
     }
getElementType()
Class<E> getElementType () inherited
Returns the element type given at construction time.
References CheckedArrayList< E >.type.
{
         return type;
     }
getLock()
Object getLock () protected inherited
Returns the synchronization lock.
The default implementation returns
this
.
{
on floating point types}
Subclasses that override this method must be careful to update the lock reference (if needed) when this list is clone() cloned}.
Returns
The synchronization lock.
Referenced by CheckedArrayList< E >.ListIter.add(), CheckedArrayList< E >.add(), CheckedArrayList< E >.addAll(), CheckedArrayList< E >.checkWritePermission(), CheckedArrayList< E >.clear(), CheckedArrayList< E >.clone(), CheckedArrayList< E >.contains(), CheckedArrayList< E >.ensureCapacity(), CheckedArrayList< E >.equals(), CheckedArrayList< E >.get(), CheckedArrayList< E >.hashCode(), CheckedArrayList< E >.Iter< ListIterator< E > >.hasNext(), CheckedArrayList< E >.ListIter.hasPrevious(), CheckedArrayList< E >.indexOf(), CheckedArrayList< E >.isEmpty(), CheckedArrayList< E >.iterator(), CheckedArrayList< E >.lastIndexOf(), CheckedArrayList< E >.listIterator(), CheckedArrayList< E >.Iter< ListIterator< E > >.next(), CheckedArrayList< E >.ListIter.nextIndex(), CheckedArrayList< E >.ListIter.previous(), CheckedArrayList< E >.ListIter.previousIndex(), CheckedArrayList< E >.Iter< ListIterator< E > >.remove(), CheckedArrayList< E >.remove(), CheckedArrayList< E >.removeAll(), CheckedArrayList< E >.retainAll(), CheckedArrayList< E >.ListIter.set(), CheckedArrayList< E >.set(), CheckedArrayList< E >.size(), CheckedArrayList< E >.toArray(), CheckedArrayList< E >.toString(), and CheckedArrayList< E >.trimToSize().
{
         return this;
     }
hashCode()
int hashCode () inherited
Returns the hash code value for this list.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.hashCode();
         }
     }
indexOf()
int indexOf (Object o) inherited
Returns the index of the first occurrence of the specified element in this list, or -1 if none.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.indexOf(o);
         }
     }
isEmpty()
boolean isEmpty () inherited
Returns.
true
if this list contains no elements.
References CheckedArrayList< E >.getLock().
Referenced by NotifiedCheckedList< E >.clear().
{
         synchronized (getLock()) {
             return super.isEmpty();
         }
     }
iterator()
Iterator<E> iterator () inherited
Returns an iterator over the elements in this list.
The returned iterator will support Iterator::remove() element removal} only if the checkWritePermission() method does not throw exception.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return new Iter<>(super.iterator());
         }
     }
lastIndexOf()
int lastIndexOf (Object o) inherited
Returns the index of the last occurrence of the specified element in this list, or -1 if none.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.lastIndexOf(o);
         }
     }
listIterator() [1/2]
ListIterator<E> listIterator () inherited
Returns an iterator over the elements in this list.
The returned iterator will support ListIterator::remove() element removal}, ListIterator::add(Object) addition} or ListIterator::set(Object) modification} only if the checkWritePermission() method does not throw exception.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return new ListIter(super.listIterator());
         }
     }
listIterator() [2/2]
ListIterator<E> listIterator (final int index) inherited
Returns an iterator over the elements in this list, starting at the given index.
The returned iterator will support ListIterator::remove() element removal}, ListIterator::add(Object) addition} or ListIterator::set(Object) modification} only if the checkWritePermission() method does not throw exception.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return new ListIter(super.listIterator(index));
         }
     }
notifyAdd() [1/2]
abstract void notifyAdd (final E item, int index) abstract protected
Referenced by NotifiedCheckedList< E >.add(), NotifiedCheckedList< E >.addAll(), and NotifiedCheckedList< E >.NotifiedCheckedList().
notifyAdd() [2/2]
abstract void notifyAdd (final Collection<? extends E > items, NumberRange< Integer > range) abstract protected
notifyChange()
abstract void notifyChange (final E oldItem, E newItem, int index) abstract protected
Referenced by NotifiedCheckedList< E >.NotifiedCheckedList(), and NotifiedCheckedList< E >.set().
notifyRemove() [1/2]
abstract void notifyRemove (final E item, int index) abstract protected
Referenced by NotifiedCheckedList< E >.clear(), NotifiedCheckedList< E >.NotifiedCheckedList(), and NotifiedCheckedList< E >.remove().
notifyRemove() [2/2]
abstract void notifyRemove (final Collection<? extends E > items, NumberRange< Integer > range) abstract protected
remove() [1/2]
boolean remove (final Object o) throws UnsupportedOperationException
References NotifiedCheckedList< E >.notifyRemove().
{
         final int index = super.indexOf(o);
         if (index >= 0) {
             super.remove(index);
             notifyRemove(super.getElementType().cast(o), index );
             return true;
         }
         return false;
     }
remove() [2/2]
E remove (final int index) throws UnsupportedOperationException
References NotifiedCheckedList< E >.notifyRemove().
{
         final E removed = super.remove(index);
         notifyRemove(removed, index );
         return removed;
     }
removeAll()
boolean removeAll (final Collection<?> c) throws UnsupportedOperationException
{
         //TODO handle remove by collection events if possible
         // to avoid several calls to remove
         boolean valid = false;
         for(final Object i : c){
             final boolean val = remove(i);
             if(val) valid = val;
         }
         return valid;
     }
retainAll()
boolean retainAll (Collection<?> c) throws UnsupportedOperationException inherited
Retains only the elements in this list that are contained in the specified collection.
Exceptions
UnsupportedOperationException if this collection is unmodifiable.
References CheckedArrayList< E >.checkWritePermission(), and CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             checkWritePermission();
             return super.retainAll(c);
         }
     }
set()
E set (int index, E element) throws IllegalArgumentException, UnsupportedOperationException
References NotifiedCheckedList< E >.notifyChange().
{
         final E old = super.set(index, element);
         notifyChange(old, element, index);
         return old;
     }
size()
int size () inherited
Returns the number of elements in this list.
References CheckedArrayList< E >.getLock().
                       {
         synchronized (getLock()) {
             return super.size();
         }
     }
toArray() [1/2]
Object [] toArray () inherited
Returns an array containing all of the elements in this list.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.toArray();
         }
     }
toArray() [2/2]
public<T> T [] toArray (T [] a) package inherited
Returns an array containing all of the elements in this list in proper sequence.
Parameters
<T> The type of array elements.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.toArray(a);
         }
     }
toString()
String toString () inherited
Returns a string representation of this list.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             return super.toString();
         }
     }
trimToSize()
void trimToSize () inherited
Trims the capacity to the list's current size.
References CheckedArrayList< E >.getLock().
{
         synchronized (getLock()) {
             super.trimToSize();
         }
     }