jena-geo: NotifiedCopyOnWriteArrayList< E > Class Template Reference
NotifiedCopyOnWriteArrayList< E > Class Template Reference abstract
Extends CopyOnWriteArrayList and define notify methods called when objects are added or removed.
Public Member Functions
NotifiedCopyOnWriteArrayList ()
boolean add (final E element) throws IllegalArgumentException, UnsupportedOperationException
void add (final int index, final E element) throws IllegalArgumentException, UnsupportedOperationException
boolean addAll (final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
boolean addAll (final int index, final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
boolean remove (final Object o) throws UnsupportedOperationException
E remove (final int index) throws UnsupportedOperationException
boolean removeAll (final Collection<?> c) throws UnsupportedOperationException
void clear () throws UnsupportedOperationException
Protected Member Functions
abstract void notifyAdd (final E item, int index)
abstract void notifyAdd (final Collection<? extends E > items, NumberRange< Integer > range)
abstract void notifyRemove (final E item, int index)
abstract void notifyRemove (final Collection<? extends E > items, NumberRange< Integer > range)
Detailed Description
Extends CopyOnWriteArrayList and define notify methods called when objects are added or removed.
Author
Johann Sorel (Geomatys)
Constructor & Destructor Documentation
NotifiedCopyOnWriteArrayList()
NotifiedCopyOnWriteArrayList ()
References NotifiedCopyOnWriteArrayList< E >.notifyAdd(), and NotifiedCopyOnWriteArrayList< E >.notifyRemove().
{
         super();
     }
Member Function Documentation
add() [1/2]
boolean add (final E element) throws IllegalArgumentException, UnsupportedOperationException
References NotifiedCopyOnWriteArrayList< E >.notifyAdd().
{
         if(element == null) return false;
         final boolean added = super.add(element);
         if (added) {
             final int index = super.size() - 1;
             notifyAdd(element, index);
         }
         return added;
     }
add() [2/2]
void add (final int index, final E element) throws IllegalArgumentException, UnsupportedOperationException
References NotifiedCopyOnWriteArrayList< E >.notifyAdd().
{
         super.add(index, element);
         notifyAdd(element, index);
     }
addAll() [1/2]
boolean addAll (final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
References NotifiedCopyOnWriteArrayList< E >.notifyAdd().
{
         final int startIndex = super.size();
         final boolean added = super.addAll(collection);
         if (added) {
             notifyAdd(collection, NumberRange.create(startIndex, true, super.size()-1, true) );
         }
         return added;
     }
addAll() [2/2]
boolean addAll (final int index, final Collection<? extends E > collection) throws IllegalArgumentException, UnsupportedOperationException
References NotifiedCopyOnWriteArrayList< E >.notifyAdd().
{
         final boolean added = super.addAll(index, collection);
         if (added) {
             notifyAdd(collection, NumberRange.create(index, true, index + collection.size(), true) );
         }
         return added;
     }
clear()
void clear () throws UnsupportedOperationException
References NotifiedCopyOnWriteArrayList< E >.notifyRemove().
{
         if(!isEmpty()){
             final Collection<E> copy = new ArrayList<E>(this);
             final NumberRange<Integer> range = NumberRange.create(0, true, copy.size()-1, true);
             super.clear();
             notifyRemove(copy, range);
         }
     }
notifyAdd() [1/2]
abstract void notifyAdd (final E item, int index) abstract protected
Referenced by NotifiedCopyOnWriteArrayList< E >.add(), NotifiedCopyOnWriteArrayList< E >.addAll(), and NotifiedCopyOnWriteArrayList< E >.NotifiedCopyOnWriteArrayList().
notifyAdd() [2/2]
abstract void notifyAdd (final Collection<? extends E > items, NumberRange< Integer > range) abstract protected
notifyRemove() [1/2]
abstract void notifyRemove (final E item, int index) abstract protected
Referenced by NotifiedCopyOnWriteArrayList< E >.clear(), NotifiedCopyOnWriteArrayList< E >.NotifiedCopyOnWriteArrayList(), and NotifiedCopyOnWriteArrayList< E >.remove().
notifyRemove() [2/2]
abstract void notifyRemove (final Collection<? extends E > items, NumberRange< Integer > range) abstract protected
remove() [1/2]
boolean remove (final Object o) throws UnsupportedOperationException
References NotifiedCopyOnWriteArrayList< E >.notifyRemove().
{
         final int index = super.indexOf(o);
         if (index >= 0) {
             super.remove(index);
             notifyRemove((E) o,index);
             return true;
         }
         return false;
     }
remove() [2/2]
E remove (final int index) throws UnsupportedOperationException
References NotifiedCopyOnWriteArrayList< E >.notifyRemove().
{
         final E removed = super.remove(index);
         notifyRemove(removed, index );
         return removed;
     }
removeAll()
boolean removeAll (final Collection<?> c) throws UnsupportedOperationException
{
         //TODO handle remove by collection events if possible
         // to avoid several calls to remove
         boolean valid = false;
         for(final Object i : c){
             final boolean val = remove(i);
             if(val) valid = val;
         }
         return valid;
     }