jena-geo: ExtendedParameterDescriptor< T > Class Template Reference
ExtendedParameterDescriptor< T > Class Template Reference
ExtendedParameterDescriptor extent the org.apache.sis.parameter.DefaultParameterDescriptor class to add a.
Public Member Functions
ExtendedParameterDescriptor (final ExtendedParameterDescriptor< T > descriptor)
ExtendedParameterDescriptor (final String name, final Class< T > valueClass, final T[] validValues, final T defaultValue, final Map< String, Object > userObject)
ExtendedParameterDescriptor (final String name, final CharSequence remarks, final Class< T > valueClass, final T defaultValue, final boolean required, final Map< String, Object > userObject)
ExtendedParameterDescriptor (final String name, final CharSequence remarks, final int minOccurs, final int maxOccurs, final Class< T > valueClass, final T defaultValue, final T[] validValues, final Map< String, Object > userObject)
ExtendedParameterDescriptor (final String name, final String alias, final CharSequence remarks, final int minOccurs, final int maxOccurs, final Class< T > valueClass, final T defaultValue, final T[] validValues, final Map< String, Object > userObject)
ExtendedParameterDescriptor (final Map< String, ?> properties, final Class< T > valueClass, final T[] validValues, final T defaultValue, final Comparable< T > minimum, final Comparable< T > maximum, final Unit<?> unit, final boolean required, final Map< String, Object > userObject)
ExtendedParameterDescriptor (final String name, final CharSequence remarks, final Class< T > valueClass, final T[] validValues, final T defaultValue, final Comparable< T > minimum, final Comparable< T > maximum, final Unit<?> unit, final boolean required, final Map< String, Object > userObject)
ExtendedParameterDescriptor (final Citation authority, final String name, final Class< T > valueClass, final T[] validValues, final T defaultValue, final Comparable< T > minimum, final Comparable< T > maximum, final Unit<?> unit, final boolean required, final Map< String, Object > userObject)
Map< String, Object > getUserObject ()
Returns the user object map.
Static Private Member Functions
static Map< String, CharSequence > properties (final String name, final CharSequence remarks)
Work around for RFE #4093999 in Sun's bug database ("Relax constraint on placement of this()/super() call in constructors").
static Map< String, CharSequence > properties (final String name, final String alias, final CharSequence remarks)
static< T > Range<?> toRange (Class< T > valueClass, Comparable< T > minimum, Comparable< T > maximum, Unit<?> unit)
Create a range from min/max values.
Private Attributes
Map< String, Object > userObject
Detailed Description
ExtendedParameterDescriptor extent the org.apache.sis.parameter.DefaultParameterDescriptor class to add a.
userObject
Map that will contain others additional parameters. Add also a new constructor that take parameter name and remarks and others parameters like validValues, minimum, maximum and units.
Author
Quentin Boileau (Geomatys).
See also
org.apache.sis.parameter.DefaultParameterDescriptor
Constructor & Destructor Documentation
ExtendedParameterDescriptor() [1/8]
ExtendedParameterDescriptor (final ExtendedParameterDescriptor< T > descriptor)
References ExtendedParameterDescriptor< T >.getUserObject().
{
         super(descriptor);
         this.userObject = descriptor.getUserObject();
     }
ExtendedParameterDescriptor() [2/8]
ExtendedParameterDescriptor (final String name, final Class< T > valueClass, final T [] validValues, final T defaultValue, final Map< String, Object > userObject)
Parameters
userObject map that contain additional value for the parameter.
References ExtendedParameterDescriptor< T >.properties(), and ExtendedParameterDescriptor< T >.userObject.
{
         super(properties(name, null), 1, 1, valueClass, null, validValues, defaultValue);
         this.userObject = userObject;
     }
ExtendedParameterDescriptor() [3/8]
ExtendedParameterDescriptor (final String name, final CharSequence remarks, final Class< T > valueClass, final T defaultValue, final boolean required, final Map< String, Object > userObject)
Parameters
userObject map that contain additional value for the parameter.
References ExtendedParameterDescriptor< T >.properties(), and ExtendedParameterDescriptor< T >.userObject.
{
         super(properties(name, remarks), (required ? 1 : 0), 1, valueClass, null, null, defaultValue);
         this.userObject = userObject;
     }
ExtendedParameterDescriptor() [4/8]
ExtendedParameterDescriptor (final String name, final CharSequence remarks, final int minOccurs, final int maxOccurs, final Class< T > valueClass, final T defaultValue, final T [] validValues, final Map< String, Object > userObject)
Parameters
name
remarks
minOccurs
maxOccurs
valueClass
defaultValue
userObject
References ExtendedParameterDescriptor< T >.properties(), and ExtendedParameterDescriptor< T >.userObject.
{
         super(properties(name, remarks),minOccurs, maxOccurs, valueClass, null, validValues, defaultValue);
         this.userObject = userObject;
     }
ExtendedParameterDescriptor() [5/8]
ExtendedParameterDescriptor (final String name, final String alias, final CharSequence remarks, final int minOccurs, final int maxOccurs, final Class< T > valueClass, final T defaultValue, final T [] validValues, final Map< String, Object > userObject)
References ExtendedParameterDescriptor< T >.properties(), and ExtendedParameterDescriptor< T >.userObject.
{
         super(properties(name, alias, remarks),minOccurs, maxOccurs, valueClass, null, validValues, defaultValue);
         this.userObject = userObject;
     }
ExtendedParameterDescriptor() [6/8]
ExtendedParameterDescriptor (final Map< String, ?> properties, final Class< T > valueClass, final T [] validValues, final T defaultValue, final Comparable< T > minimum, final Comparable< T > maximum, final Unit<?> unit, final boolean required, final Map< String, Object > userObject)
Parameters
unit not used since ExtendedParameter extend SIS DefaultParameterDescriptor.
userObject map that contain additional value for the parameter.
References ExtendedParameterDescriptor< T >.toRange(), and ExtendedParameterDescriptor< T >.userObject.
{
         super(properties, (required ? 1 : 0), 1, valueClass, toRange(valueClass, minimum, maximum, unit), validValues, defaultValue);
         this.userObject = userObject;
     }
ExtendedParameterDescriptor() [7/8]
ExtendedParameterDescriptor (final String name, final CharSequence remarks, final Class< T > valueClass, final T [] validValues, final T defaultValue, final Comparable< T > minimum, final Comparable< T > maximum, final Unit<?> unit, final boolean required, final Map< String, Object > userObject)
Parameters
unit not used since ExtendedParameter extend SIS DefaultParameterDescriptor.
userObject map that contain additional value for the parameter.
References ExtendedParameterDescriptor< T >.properties(), ExtendedParameterDescriptor< T >.toRange(), and ExtendedParameterDescriptor< T >.userObject.
{
         super(properties(name, remarks), (required ? 1 : 0), 1, valueClass, toRange(valueClass, minimum, maximum, unit), validValues, defaultValue);
         this.userObject = userObject;
     }
ExtendedParameterDescriptor() [8/8]
ExtendedParameterDescriptor (final Citation authority, final String name, final Class< T > valueClass, final T [] validValues, final T defaultValue, final Comparable< T > minimum, final Comparable< T > maximum, final Unit<?> unit, final boolean required, final Map< String, Object > userObject)
Parameters
authority not used since ExtendedParameter extend SIS DefaultParameterDescriptor.
userObject map that contain additional value for the parameter.
References ExtendedParameterDescriptor< T >.properties(), ExtendedParameterDescriptor< T >.toRange(), and ExtendedParameterDescriptor< T >.userObject.
{
         super(properties(name, null), (required ? 1 : 0), 1, valueClass, toRange(valueClass, minimum, maximum, unit), validValues, defaultValue);
         this.userObject = userObject;
     }
Member Function Documentation
getUserObject()
Map<String, Object> getUserObject ()
Returns the user object map.
Returns
The user object map.
References ExtendedParameterDescriptor< T >.userObject.
Referenced by ExtendedParameterDescriptor< T >.ExtendedParameterDescriptor().
{
         return userObject;
     }
properties() [1/2]
static Map<String,CharSequence> properties (final String name, final CharSequence remarks) static private
Work around for RFE #4093999 in Sun's bug database ("Relax constraint on placement of this()/super() call in constructors").
Referenced by ExtendedParameterDescriptor< T >.ExtendedParameterDescriptor(), and ExtendedParameterDescriptor< T >.properties().
{
         return properties(name, null, remarks);
     }
properties() [2/2]
static Map<String,CharSequence> properties (final String name, final String alias, final CharSequence remarks) static private
References ExtendedParameterDescriptor< T >.properties().
{
         ArgumentChecks.ensureNonNull("Name", name);
         final Map<String,CharSequence> properties = new HashMap<>(4);
         properties.put(NAME_KEY, name);
         if (alias != null) {
             properties.put(ALIAS_KEY, alias);
         }
         if (remarks != null) {
             properties.put(REMARKS_KEY, remarks);
         }
         return properties;
     }
toRange()
static <T> Range<?> toRange (Class< T > valueClass, Comparable< T > minimum, Comparable< T > maximum, Unit<?> unit) static private
Create a range from min/max values.
Parameters
valueClass
minimum value inclusive
maximum value inclusive
unit
Returns
a Range
Referenced by ExtendedParameterDescriptor< T >.ExtendedParameterDescriptor().
{
         if (unit != null && Number.class.isAssignableFrom(valueClass)) {
             return new MeasurementRange(valueClass, (Number)minimum, true, (Number)maximum, true, unit);
         } else if(Comparable.class.isAssignableFrom(valueClass) && (minimum!=null || maximum!=null) )  {
             return new Range(valueClass, minimum, true, maximum, true);
         } else {
             return null;
         }
     }
Member Data Documentation
userObject
Map<String, Object> userObject private
Referenced by ExtendedParameterDescriptor< T >.ExtendedParameterDescriptor(), and ExtendedParameterDescriptor< T >.getUserObject().