jena-geo: DateRange Class Reference
DateRange Class Reference
A range of dates.
Public Member Functions
DateRange (final Date startTime, final Date endTime)
Creates a new date range for the given dates.
DateRange (final Date startTime, boolean isMinIncluded, final Date endTime, boolean isMaxIncluded)
Creates a new date range for the given dates.
DateRange (final MeasurementRange<?> range, final Date origin) throws IncommensurableException
Creates a date range from the specified measurement range.
Date getMinValue ()
Returns the start time.
Date getMaxValue ()
Returns the end time.
DateRange union (final Range< Date > range) throws IllegalArgumentException
DateRange intersect (final Range< Date > range) throws IllegalArgumentException
DateRange [] subtract (final Range< Date > range) throws IllegalArgumentException
Private Member Functions
DateRange (final MeasurementRange<?> range, final UnitConverter converter, final long origin) throws IncommensurableException
Workaround for RFE #4093999 ("Relax constraint on placement of this()/super() call in constructors").
Static Private Member Functions
static DateRange cast (final Range<?> range)
Casts the given.
static Date clone (final Date date)
Returns a clone of the specified date.
static UnitConverter getConverter (final Unit<?> source) throws IncommensurableException
Workaround for RFE #4093999 ("Relax constraint on placement of this()/super() call in constructors").
Static Private Attributes
static final long serialVersionUID = -6400011350250757942L
For cross-version compatibility.
Detailed Description
A range of dates.
The elements in this range are Date objects. Consequently the precision of
DateRange
objects is milliseconds.
Author
Martin Desruisseaux (Geomatys)
Version
3.20
See also
org.geotoolkit.measure.RangeFormat
Since
2.5
Constructor & Destructor Documentation
DateRange() [1/4]
DateRange (final Date startTime, final Date endTime)
Creates a new date range for the given dates.
Start time and end time are inclusive.
Parameters
startTime The start time (inclusive), or
null
if none.
endTime The end time (inclusive), or
null
if none.
References DateRange.clone().
Referenced by DateRange.cast().
{
         super(Date.class, clone(startTime), true, clone(endTime), true);
     }
DateRange() [2/4]
DateRange (final Date startTime, boolean isMinIncluded, final Date endTime, boolean isMaxIncluded)
Creates a new date range for the given dates.
Parameters
startTime The start time, or
null
if none.
isMinIncluded
References DateRange.clone().
     {
         super(Date.class, clone(startTime), isMinIncluded,
                           clone(  endTime), isMaxIncluded);
     }
DateRange() [3/4]
DateRange (final MeasurementRange<?> range, final Date origin) throws IncommensurableException
Creates a date range from the specified measurement range.
Units are converted as needed.
Parameters
range The range to convert.
origin The date to use as the origin.
Exceptions
IncommensurableException if the given range doesn't have a MeasurementRange::getUnits unit} compatible with milliseconds.
References DateRange.getConverter().
{
         this(range, getConverter(range.unit()), origin.getTime());
     }
DateRange() [4/4]
DateRange (final MeasurementRange<?> range, final UnitConverter converter, final long origin) throws IncommensurableException private
Workaround for RFE #4093999 ("Relax constraint on placement of this()/super() call in constructors").
     {
         super(Date.class,
               new Date(origin + Math.round(converter.convert(range.getMinDouble()))), range.isMinIncluded(),
               new Date(origin + Math.round(converter.convert(range.getMaxDouble()))), range.isMaxIncluded());
     }
Member Function Documentation
cast()
static DateRange cast (final Range<?> range) static private
Casts the given.
Range
object to a
DateRange
. This method shall be invoked only in context where we have verified that the range element class is compatible. This verification is performed by Range#ensureCompatible(Range) method.
References DateRange.DateRange().
Referenced by DateRange.intersect(), DateRange.subtract(), and DateRange.union().
{
         if (range == null || range instanceof DateRange) {
             return (DateRange) range;
         }
         return new DateRange((Date) range.getMinValue(), range.isMinIncluded(),
                              (Date) range.getMaxValue(), range.isMaxIncluded());
     }
clone()
static Date clone (final Date date) static private
Returns a clone of the specified date.
Referenced by DateRange.DateRange(), DateRange.getMaxValue(), and DateRange.getMinValue().
{
         return (date != null) ? (Date) date.clone() : null;
     }
getConverter()
static UnitConverter getConverter (final Unit<?> source) throws IncommensurableException static private
Workaround for RFE #4093999 ("Relax constraint on placement of this()/super() call in constructors").
References Errors.format(), and Errors.Keys.NoUnit.
Referenced by DateRange.DateRange().
{
         if (source == null) {
             throw new IncommensurableException(Errors.format(Errors.Keys.NoUnit));
         }
         return source.getConverterToAny(Units.MILLISECOND);
     }
getMaxValue()
Date getMaxValue ()
Returns the end time.
References DateRange.clone().
{
         return clone(super.getMaxValue());
     }
getMinValue()
Date getMinValue ()
Returns the start time.
References DateRange.clone().
{
         return clone(super.getMinValue());
     }
intersect()
DateRange intersect (final Range< Date > range) throws IllegalArgumentException
Since
3.20
References DateRange.cast().
{
         return cast(super.intersect(range));
     }
subtract()
DateRange [] subtract (final Range< Date > range) throws IllegalArgumentException
Since
3.20
References DateRange.cast().
{
         final Range<Date>[] ranges = super.subtract(range);
         final DateRange[] result = new DateRange[ranges.length];
         for (int i=0; i<result.length; i++) {
             result[i] = cast(ranges[i]);
         }
         return result;
     }
union()
DateRange union (final Range< Date > range) throws IllegalArgumentException
Since
3.20
References DateRange.cast().
{
         return cast(super.union(range));
     }
Member Data Documentation
serialVersionUID
final long serialVersionUID = -6400011350250757942L static private
For cross-version compatibility.