jena-geo: Utilities Class Reference
Utilities Class Reference
Miscellaneous methods.
Static Public Member Functions
static boolean equals (final float o1, final float o2)
Returns.
static boolean equals (final double o1, final double o2)
Returns.
static int hash (final boolean value, final int seed)
Alters the given seed with the hash code value computed from the given value.
static int hash (final char value, final int seed)
Alters the given seed with the hash code value computed from the given value.
static int hash (final int value, final int seed)
Alters the given seed with the hash code value computed from the given value.
static int hash (final long value, final int seed)
Alters the given seed with the hash code value computed from the given value.
static int hash (final float value, final int seed)
Alters the given seed with the hash code value computed from the given value.
static int hash (final double value, final int seed)
Alters the given seed with the hash code value computed from the given value.
static int hash (final Object value, int seed) throws AssertionError
Alters the given seed with the hash code value computed from the given value.
static boolean listNullEquals (List<?> l1, List<?> l2)
Utility method to avoid to fill an empty list during equals.
Static Public Attributes
static final Version VERSION = new Version("4.00-SNAPSHOT")
The version of this Geotoolkit.org distribution.
Private Member Functions
Utilities ()
Forbid object creation.
Static Private Member Functions
static String name (final Object object)
Returns the class name of the given object.
Static Private Attributes
static final int PRIME_NUMBER = 31
A prime number used for hash code computation.
Detailed Description
Miscellaneous methods.
This class also provides convenience methods for computing Object::hashCode hash code} values. All those methods expect a
seed
argument, which is the hash code value computed for previous fields in a class. For the initial seed (the one for the field for which to compute an hash code), an arbitrary value must be provided. We suggest a different number for different class in order to reduce the risk of collision between "empty" instances of different classes. java.io.Serializable} classes can use
(int) serialVersionUID
for example.
Constructor & Destructor Documentation
Utilities()
Utilities () private
Forbid object creation.
{
     }
Member Function Documentation
equals() [1/2]
static boolean equals (final float o1, final float o2) static
Returns.
true
if the given floats are equals. Positive and negative zero are considered different, while a NaN value is considered equal to all other NaN values.
Parameters
o1 The first value to compare.
o2 The second value to compare.
Returns
true
if both values are equal.
See also
Float::equals(Object)
Referenced by InternalUtilities.epsilonEqual(), ContinuousPalette.equals(), and GridTransform.equals().
{
         return Float.floatToIntBits(o1) == Float.floatToIntBits(o2);
     }
equals() [2/2]
static boolean equals (final double o1, final double o2) static
Returns.
true
if the given doubles are equals. Positive and negative zero are considered different, while a NaN value is considered equal to all other NaN values.
Parameters
o1 The first value to compare.
o2 The second value to compare.
Returns
true
if both values are equal.
See also
Double::equals(Object)
{
         return Double.doubleToLongBits(o1) == Double.doubleToLongBits(o2);
     }
hash() [1/7]
static int hash (final boolean value, final int seed) static
Alters the given seed with the hash code value computed from the given value.
Parameters
value The value whose hash code to compute.
seed The hash code value computed so far. If this method is invoked for the first field, then any arbitrary value (preferably different for each class) is okay.
Returns
An updated hash code value.
Referenced by Utilities.hash(), and FloatParameter.hashCode().
{
         // Use the same values than Boolean.hashCode()
         return seed * PRIME_NUMBER + (value ? 1231 : 1237);
     }
hash() [2/7]
static int hash (final char value, final int seed) static
Alters the given seed with the hash code value computed from the given value.
Parameters
value The value whose hash code to compute.
seed The hash code value computed so far. If this method is invoked for the first field, then any arbitrary value (preferably different for each class) is okay.
Returns
An updated hash code value.
{
         return seed * PRIME_NUMBER + (int) value;
     }
hash() [3/7]
static int hash (final int value, final int seed) static
Alters the given seed with the hash code value computed from the given value.
byte
and
short
primitive types are handled by this method as well through implicit widening conversion.
Parameters
value The value whose hash code to compute.
seed The hash code value computed so far. If this method is invoked for the first field, then any arbitrary value (preferably different for each class) is okay.
Returns
An updated hash code value.
{
         return seed * PRIME_NUMBER + value;
     }
hash() [4/7]
static int hash (final long value, final int seed) static
Alters the given seed with the hash code value computed from the given value.
byte
and
short
primitive types are handled by this method as well through implicit widening conversion.
Parameters
value The value whose hash code to compute.
seed The hash code value computed so far. If this method is invoked for the first field, then any arbitrary value (preferably different for each class) is okay.
Returns
An updated hash code value.
{
         return seed * PRIME_NUMBER + (((int) value) ^ ((int) (value >>> 32)));
     }
hash() [5/7]
static int hash (final float value, final int seed) static
Alters the given seed with the hash code value computed from the given value.
Parameters
value The value whose hash code to compute.
seed The hash code value computed so far. If this method is invoked for the first field, then any arbitrary value (preferably different for each class) is okay.
Returns
An updated hash code value.
{
         return seed * PRIME_NUMBER + Float.floatToIntBits(value);
     }
hash() [6/7]
static int hash (final double value, final int seed) static
Alters the given seed with the hash code value computed from the given value.
Parameters
value The value whose hash code to compute.
seed The hash code value computed so far. If this method is invoked for the first field, then any arbitrary value (preferably different for each class) is okay.
Returns
An updated hash code value.
References Utilities.hash().
{
         return hash(Double.doubleToLongBits(value), seed);
     }
hash() [7/7]
static int hash (final Object value, int seed) throws AssertionError static
Alters the given seed with the hash code value computed from the given value.
The given object may be null. This method do not iterates recursively in array elements. If array needs to be hashed, use one of Arrays method or deepHashCode instead.
Note on assertions: There is no way to ensure at compile time that this method is not invoked with an array argument, while doing so would usually be a program error. Performing a systematic argument check would impose a useless overhead for correctly implemented Object#hashCode methods. As a compromise we perform this check at runtime only if assertions are enabled. Using assertions for argument check in a public API is usually a deprecated practice, but we make an exception for this particular method.
Parameters
value The value whose hash code to compute, or
null
.
seed The hash code value computed so far. If this method is invoked for the first field, then any arbitrary value (preferably different for each class) is okay.
Returns
An updated hash code value.
Exceptions
AssertionError If assertions are enabled and the given value is an array.
References Utilities.name(), and Utilities.PRIME_NUMBER.
{
         seed *= PRIME_NUMBER;
         if (value != null) {
             assert !value.getClass().isArray() : name(value);
             seed += value.hashCode();
         }
         return seed;
     }
listNullEquals()
static boolean listNullEquals (List<?> l1, List<?> l2) static
Utility method to avoid to fill an empty list during equals.
But we want to consider equals a null list and an empty one, for JAXB purpose.
Parameters
l1 first list to compare
l2 second list to compare
Returns
True if the two list are equals, or if one is null and the other empty
{
         if (l1 == null && l2 != null && l2.isEmpty()) {
             return true;
         } else if (l2 == null && l1 != null && l1.isEmpty()) {
             return true;
         } else {
             return Objects.equals(l1, l2);
         }
     }
name()
static String name (final Object object) static private
Returns the class name of the given object.
Used in assertions only.
Referenced by Utilities.hash().
{
         return object.getClass().getSimpleName();
     }
Member Data Documentation
PRIME_NUMBER
final int PRIME_NUMBER = 31 static private
A prime number used for hash code computation.
Value 31 is often used because some modern compilers can optimize
x*31
as
(x << 5) - x
(Josh Bloch, <cite>Effective Java</cite>).
Referenced by Utilities.hash().
VERSION
final Version VERSION = new Version("4.00-SNAPSHOT") static
The version of this Geotoolkit.org distribution.
Referenced by WKBRasterImageReader.Spi.Spi(), and WKBRasterImageWriter.Spi.Spi().