jena-geo: Ranks.Float Class Reference
Ranks.Float Class Reference
A rank element for the.
Public Member Functions
int compareTo (final Float other)
Compares this element with the specified one for order.
Static Public Member Functions
static< T extends Comparable< T > int [] ranks (final T[] source, final T[] target)
Sorts the elements in the given array and return their ranks.
static int [] ranks (final double[] source, final double[] target)
Sorts the elements in the given array and return their ranks.
static int [] ranks (final float[] source, final float[] target)
Sorts the elements in the given array and return their ranks.
static int [] ranks (final long[] source, final long[] target)
Sorts the elements in the given array and return their ranks.
static int [] ranks (final int[] source, final int[] target)
Sorts the elements in the given array and return their ranks.
static int [] ranks (final short[] source, final short[] target)
Sorts the elements in the given array and return their ranks.
static int [] ranks (final byte[] source, final byte[] target)
Sorts the elements in the given array and return their ranks.
Package Functions
Float (final int index, final float value)
Creates an element for the specified value.
Private Attributes
final float value
The value to sort.
Detailed Description
A rank element for the.
float
type.
Constructor & Destructor Documentation
Float()
Float (final int index, final float value) package
Creates an element for the specified value.
References Ranks.Double.value.
{
             super(index);
             this.value = value;
         }
Member Function Documentation
compareTo()
int compareTo (final Float other)
Compares this element with the specified one for order.
References Ranks.Float.value.
{
             return java.lang.Float.compare(value, other.value);
         }
ranks() [1/7]
static <T extends Comparable<T> int [] ranks (final T [] source, final T [] target) static inherited
Sorts the elements in the given array and return their ranks.
See class description for details.
Parameters
<T> The type of elements in the array to be sorted.
source The array of values to sort, or
null
.
target The array where to store sorted values, or
null
if none. May be the same array than
source
, in which case the sorting will be performed in place.
Returns
The value ranks, or
null
if
source
was null.
See also
Arrays::sort(Object[])
Referenced by Ranks.ranks().
{
         if (source == null) {
             return null;
         }
         @SuppressWarnings({"unchecked","rawtypes"}) // Generic array creation.
         final Any<T>[] entries = new Any[source.length];
         for (int i=0; i<entries.length; i++) {
             entries[i] = new Any<>(i, source[i]);
         }
         final int[] ranks = ranks(entries);
         if (target != null) {
             for (int i=Math.min(entries.length, target.length); --i>=0;) {
                 target[i] = entries[i].value;
             }
         }
         return ranks;
     }
ranks() [2/7]
static int [] ranks (final double [] source, final double [] target) static inherited
Sorts the elements in the given array and return their ranks.
See class description for details.
Parameters
source The array of values to sort, or
null
.
target The array where to store sorted values, or
null
if none. May be the same array than
source
, in which case the sorting will be performed in place.
Returns
The value ranks, or
null
if
source
was null.
See also
Arrays::sort(double[])
References Ranks.ranks(), and Ranks.Double.value.
{
         if (source == null) {
             return null;
         }
         final Double[] entries = new Double[source.length];
         for (int i=0; i<entries.length; i++) {
             entries[i] = new Double(i, source[i]); // NOSONAR: This is not java.lang.Double
         }
         final int[] ranks = ranks(entries);
         if (target != null) {
             for (int i=Math.min(entries.length, target.length); --i>=0;) {
                 target[i] = entries[i].value;
             }
         }
         return ranks;
     }
ranks() [3/7]
static int [] ranks (final float [] source, final float [] target) static inherited
Sorts the elements in the given array and return their ranks.
See class description for details.
Parameters
source The array of values to sort, or
null
.
target The array where to store sorted values, or
null
if none. May be the same array than
source
, in which case the sorting will be performed in place.
Returns
The value ranks, or
null
if
source
was null.
See also
Arrays::sort(float[])
References Ranks.ranks(), and Ranks.Float.value.
{
         if (source == null) {
             return null;
         }
         final Float[] entries = new Float[source.length];
         for (int i=0; i<entries.length; i++) {
             entries[i] = new Float(i, source[i]); // NOSONAR: This is not java.lang.Float
         }
         final int[] ranks = ranks(entries);
         if (target != null) {
             for (int i=Math.min(entries.length, target.length); --i>=0;) {
                 target[i] = entries[i].value;
             }
         }
         return ranks;
     }
ranks() [4/7]
static int [] ranks (final long [] source, final long [] target) static inherited
Sorts the elements in the given array and return their ranks.
See class description for details.
Parameters
source The array of values to sort, or
null
.
target The array where to store sorted values, or
null
if none. May be the same array than
source
, in which case the sorting will be performed in place.
Returns
The value ranks, or
null
if
source
was null.
See also
Arrays::sort(long[])
References Ranks.ranks(), and Ranks.Long.value.
{
         if (source == null) {
             return null;
         }
         final Long[] entries = new Long[source.length];
         for (int i=0; i<entries.length; i++) {
             entries[i] = new Long(i, source[i]); // NOSONAR: This is not java.lang.Long
         }
         final int[] ranks = ranks(entries);
         if (target != null) {
             for (int i=Math.min(entries.length, target.length); --i>=0;) {
                 target[i] = entries[i].value;
             }
         }
         return ranks;
     }
ranks() [5/7]
static int [] ranks (final int [] source, final int [] target) static inherited
Sorts the elements in the given array and return their ranks.
See class description for details.
Parameters
source The array of values to sort, or
null
.
target The array where to store sorted values, or
null
if none. May be the same array than
source
, in which case the sorting will be performed in place.
Returns
The value ranks, or
null
if
source
was null.
See also
Arrays::sort(int[])
References Ranks.ranks(), and Ranks.Integer.value.
{
         if (source == null) {
             return null;
         }
         final Integer[] entries = new Integer[source.length];
         for (int i=0; i<entries.length; i++) {
             entries[i] = new Integer(i, source[i]); // NOSONAR: This is not java.lang.Integer
         }
         final int[] ranks = ranks(entries);
         if (target != null) {
             for (int i=Math.min(entries.length, target.length); --i>=0;) {
                 target[i] = entries[i].value;
             }
         }
         return ranks;
     }
ranks() [6/7]
static int [] ranks (final short [] source, final short [] target) static inherited
Sorts the elements in the given array and return their ranks.
See class description for details.
Parameters
source The array of values to sort, or
null
.
target The array where to store sorted values, or
null
if none. May be the same array than
source
, in which case the sorting will be performed in place.
Returns
The value ranks, or
null
if
source
was null.
See also
Arrays::sort(short[])
References Ranks.ranks(), and Ranks.Short.value.
{
         if (source == null) {
             return null;
         }
         final Short[] entries = new Short[source.length];
         for (int i=0; i<entries.length; i++) {
             entries[i] = new Short(i, source[i]); // NOSONAR: This is not java.lang.Short
         }
         final int[] ranks = ranks(entries);
         if (target != null) {
             for (int i=Math.min(entries.length, target.length); --i>=0;) {
                 target[i] = entries[i].value;
             }
         }
         return ranks;
     }
ranks() [7/7]
static int [] ranks (final byte [] source, final byte [] target) static inherited
Sorts the elements in the given array and return their ranks.
See class description for details.
Parameters
source The array of values to sort, or
null
.
target The array where to store sorted values, or
null
if none. May be the same array than
source
, in which case the sorting will be performed in place.
Returns
The value ranks, or
null
if
source
was null.
See also
Arrays::sort(byte[])
References Ranks.ranks(), and Ranks.Byte.value.
{
         if (source == null) {
             return null;
         }
         final Byte[] entries = new Byte[source.length];
         for (int i=0; i<entries.length; i++) {
             entries[i] = new Byte(i, source[i]); // NOSONAR: This is not java.lang.Byte
         }
         final int[] ranks = ranks(entries);
         if (target != null) {
             for (int i=Math.min(entries.length, target.length); --i>=0;) {
                 target[i] = entries[i].value;
             }
         }
         return ranks;
     }
Member Data Documentation
value
final float value private
The value to sort.
Referenced by Ranks.Float.compareTo(), and Ranks.ranks().