jena-geo: NullProgressListener Class Reference
NullProgressListener Class Reference
A default progress listener implementation suitable for subclassing.
Public Member Functions
NullProgressListener ()
Creates a null progress listener with no description.
void started ()
void warningOccurred (final String source, final String location, final String warning)
void exceptionOccurred (final Throwable exception)
void completed ()
void paused ()
void resumed ()
Locale getLocale ()
Returns the locale used for formatting messages.
InternationalString getTask ()
Returns the description of the current task being performed, or.
void setTask (CharSequence task)
Sets the description of the current task being performed.
void started (final ProcessEvent event)
Notifies this controller that the operation begins and sets the states of this controller according the given event.
void paused (final ProcessEvent event)
Notifies this controller that the operation is suspended and sets the states of this controller according the given event.
void resumed (final ProcessEvent event)
Notifies this controller that the operation is resumed and sets the states of this controller according the given event.
float getProgress ()
Returns the current progress as a percent completed.
void setProgress (float percent)
Notifies this controller of progress in the lengthly operation.
void progressing (final ProcessEvent event)
Updates the setTask(CharSequence) task} and setProgress(float) progress} state, and exceptionOccurred(Throwable) reports the exception} if any.
void completed (final ProcessEvent event)
Notifies this controller that the operation has finished and sets the states of this controller according the given event.
void failed (final ProcessEvent event)
Notifies this controller that the operation has failed and sets the states of this controller according the given event.
void dismissed (final ProcessEvent event)
Reports that a process has been dismissed.
void cancel ()
Indicates that this job should be canceled.
boolean isCanceled ()
Returns.
Detailed Description
A default progress listener implementation suitable for subclassing.
This implementation supports cancelation and getting/setting the description. The default implementations of the other methods do nothing.
Since
2.2
Version
$Id$
Constructor & Destructor Documentation
NullProgressListener()
NullProgressListener ()
Creates a null progress listener with no description.
{
     }
Member Function Documentation
cancel()
void cancel () inherited
Indicates that this job should be canceled.
{
         canceled = true;
     }
completed() [1/2]
void completed ()
{
         //do nothing
     }
completed() [2/2]
void completed (final ProcessEvent event) inherited
Notifies this controller that the operation has finished and sets the states of this controller according the given event.
The default implementation first invokes #progressing(ProcessEvent) progressing}(event), then invokes completed().
Parameters
event The progress event, or
null
if none.
Since
3.19
Implements ProcessListener.
References ProgressController.completed(), and ProgressController.progressing().
{
         progressing(event);
         completed();
     }
dismissed()
void dismissed (final ProcessEvent event) inherited
Reports that a process has been dismissed.
Parameters
event The progress event.
Implements ProcessListener.
References ProgressController.failed().
{
         canceled = true;
         failed(event);
     }
exceptionOccurred()
void exceptionOccurred (final Throwable exception)
{
         //do nothing
     }
failed()
void failed (final ProcessEvent event) inherited
Notifies this controller that the operation has failed and sets the states of this controller according the given event.
The default implementation just delegates to #progressing(ProcessEvent) progressing}(event). Note that the above
progressing
method pass the ProcessEvent::getException() exception declared by the event} (if any) to the exceptionOccurred(Throwable) method.
Parameters
event The progress event, or
null
if none.
Since
3.19
Implements ProcessListener.
References ProgressController.progressing().
Referenced by ProgressController.dismissed().
{
         progressing(event);
     }
getLocale()
Locale getLocale () inherited
Returns the locale used for formatting messages.
The default value is the Locale::getDefault() system default} locale.
Returns
The locale.
References ProgressController.locale.
{
         return locale;
     }
getProgress()
float getProgress () inherited
Returns the current progress as a percent completed.
Returns
Percent completed between 0 and 100 inclusive.
References ProgressController.progress.
{
         return progress;
     }
getTask()
InternationalString getTask () inherited
Returns the description of the current task being performed, or.
null
if none. It is assumed that if the task is
null
applications may simply report that the process is "<cite>in progress</cite>" or "<cite>working</cite>" as represented in the getLocale() current locale}.
Returns
Description of the task being performed, or
null
if none.
References ProgressController.task.
{
         return task;
     }
isCanceled()
boolean isCanceled () inherited
Returns.
true
if this job is canceled.
Returns
true
if this job is canceled.
References ProgressController.canceled, ProgressController.exceptionOccurred(), and ProgressController.warningOccurred().
{
         return canceled;
     }
paused() [1/2]
void paused ()
{
         //do nothing
     }
paused() [2/2]
void paused (final ProcessEvent event) inherited
Notifies this controller that the operation is suspended and sets the states of this controller according the given event.
The default implementation first invokes #progressing(ProcessEvent) progressing}(event), then invokes paused().
Parameters
event The progress event, or
null
if none.
Since
3.20
Implements ProcessListener.
References ProgressController.paused(), ProgressController.progressing(), and ProgressController.resumed().
{
         progressing(event);
         paused();
     }
progressing()
void progressing (final ProcessEvent event) inherited
Updates the setTask(CharSequence) task} and setProgress(float) progress} state, and exceptionOccurred(Throwable) reports the exception} if any.
More specifically:
The new task is set to the ProcessEvent#getTask() value unless the later method returned
null
, in which case this
ProgressController
task is left unchanged.
The new progress is set to the ProcessEvent#getProgress() value unless the later method returned Float#NaN, in which case this
ProgressController
progress state is left unchanged.
If ProcessEvent#getException() returns a non-null value, then that value is given to exceptionOccurred(Throwable).
Parameters
event The progress event, or
null
if none.
Since
3.19
Implements ProcessListener.
References ProgressController.completed(), ProgressController.exceptionOccurred(), ProgressController.setProgress(), and ProgressController.setTask().
Referenced by ProgressController.completed(), ProgressController.failed(), ProgressController.paused(), ProgressController.resumed(), and ProgressController.started().
{
         if (event != null) {
             final InternationalString task = event.getTask();
             if (task != null) {
                 setTask(task);
             }
             final float progress = event.getProgress();
             if (!Float.isNaN(progress)) {
                 setProgress(progress);
             }
             final Exception ex = event.getException();
             if (ex != null) {
                 exceptionOccurred(ex);
             }
         }
     }
resumed() [1/2]
void resumed ()
{
         //do nothing
     }
resumed() [2/2]
void resumed (final ProcessEvent event) inherited
Notifies this controller that the operation is resumed and sets the states of this controller according the given event.
The default implementation first invokes resumed(), then invokes #progressing(ProcessEvent) progressing}(event).
Parameters
event The progress event, or
null
if none.
Since
3.20
Implements ProcessListener.
References ProgressController.progressing(), and ProgressController.resumed().
{
         resumed();
         progressing(event);
     }
setProgress()
void setProgress (float percent) inherited
Notifies this controller of progress in the lengthly operation.
Progresses are reported as a value between 0 and 100 inclusive. Values out of bounds will be clamped.
Parameters
percent The progress as a value between 0 and 100 inclusive.
Referenced by ProgressController.progressing().
{
         if (percent < 0  ) percent = 0;
         if (percent > 100) percent = 100;
         progress = percent;
     }
setTask()
void setTask (CharSequence task) inherited
Sets the description of the current task being performed.
This method is usually invoked before any progress begins. However, it is legal to invoke this method at any time during the operation, in which case the task label is updated without any change to the percentage accomplished.
Parameters
task Description of the task being performed as a String or InternationalString, or
null
if none.
References ProgressController.started().
Referenced by ProgressController.progressing().
{
         if (task != null && !(task instanceof InternationalString)) {
             task = new SimpleInternationalString(task.toString());
         }
         this.task = (InternationalString) task;
     }
started() [1/2]
void started ()
{
         //do nothing
     }
started() [2/2]
void started (final ProcessEvent event) inherited
Notifies this controller that the operation begins and sets the states of this controller according the given event.
The default implementation first invokes started(), then invokes #progressing(ProcessEvent) progressing}(event).
Parameters
event The progress event, or
null
if none.
Since
3.19
Implements ProcessListener.
References ProgressController.paused(), ProgressController.progressing(), and ProgressController.started().
{
         started();
         progressing(event);
     }
warningOccurred()
void warningOccurred (final String source, final String location, final String warning)
{
         //do nothing
     }