jena-geo: NamesExt Class Reference
NamesExt Class Reference
GenericName utilities.
Static Public Member Functions
static GenericName create (final QName qname)
static GenericName create (final String local)
static GenericName create (final String namespace, final String local)
static GenericName valueOf (final String candidate)
Parse a string value that can be expressed in 2 different forms : JSR-283 extended form : {uri}localpart Separator form : uri:localpart.
static String toExtendedForm (final GenericName name)
static String toExpandedString (final GenericName name)
static boolean match (final GenericName name, final String candidate)
Tests that the given string representation matches the given name.
static boolean match (final GenericName name, final GenericName candidate)
static String getNamespace (GenericName name)
Static Private Member Functions
static GenericName toSessionNamespaceFromExtended (final String candidate)
Detailed Description
GenericName utilities.
Author
Johann Sorel (Geomatys)
Member Function Documentation
create() [1/3]
static GenericName create (final QName qname) static
Referenced by NamesExt.create(), NamesExt.toSessionNamespaceFromExtended(), and NamesExt.valueOf().
{
         return create(qname.getNamespaceURI(), qname.getLocalPart());
     }
create() [2/3]
static GenericName create (final String local) static
References NamesExt.create().
{
         return create(null,local);
     }
create() [3/3]
static GenericName create (final String namespace, final String local) static
Parameters
namespace if null or empty will not be used for the name
local mandatory
{
         // WARNING: DefaultFactories.NAMES is not a public API and may change in any future SIS version.
         if(namespace==null || namespace.isEmpty()){
             return DefaultFactories.forBuildin(NameFactory.class).createGenericName(null, local);
         }else{
             return DefaultFactories.forBuildin(NameFactory.class).createGenericName(null, namespace, local);
         }
     }
getNamespace()
static String getNamespace (GenericName name) static
Referenced by NamesExt.match(), NamesExt.toExpandedString(), and NamesExt.toExtendedForm().
{
         if (name instanceof ScopedName) {
             return ((ScopedName) name).path().toString();
         } else if (name instanceof Identifier) {
             return ((Identifier) name).getCodeSpace();
         }
         return null;
     }
match() [1/2]
static boolean match (final GenericName name, final String candidate) static
Tests that the given string representation matches the given name.
String can be written with only the local part or in extendedform or JCR extended form.
Returns
true if the string match the name
References NamesExt.getNamespace(), and NamesExt.toExpandedString().
{
         if(candidate.startsWith("{")){
             //candidate is in extended form
             return candidate.equals(toExpandedString(name));
         }
         final int index = candidate.lastIndexOf(':');
         if(index <= 0){
             return candidate.equals(name.tip().toString());
         }else{
             final String uri = candidate.substring(0,index);
             final String local = candidate.substring(index+1,candidate.length());
             return uri.equals(getNamespace(name)) && local.equals(name.tip().toString());
         }
     }
match() [2/2]
static boolean match (final GenericName name, final GenericName candidate) static
References NamesExt.getNamespace().
{
         final String ns1 = getNamespace(name);
         final String ns2 = getNamespace(candidate);
         if(ns1==null || ns2==null){
             //compare only localpart
             return name.tip().toString().equals(candidate.tip().toString());
         }else{
             return name.toString().equals(candidate.toString());
         }
     }
toExpandedString()
static String toExpandedString (final GenericName name) static
References NamesExt.getNamespace().
Referenced by NamesExt.match().
{
         String ns = getNamespace(name);
         if(ns==null){
             return name.tip().toString();
         }else{
             return new StringBuilder("{").append(ns).append('}').append(name.tip()).toString();
         }
     }
toExtendedForm()
static String toExtendedForm (final GenericName name) static
References NamesExt.getNamespace().
{
         final String ns = NamesExt.getNamespace(name);
         if(ns==null || ns.isEmpty()){
             return name.toString();
         }else{
             return new StringBuilder(ns).append(':').append(name.tip()).toString();
         }
     }
toSessionNamespaceFromExtended()
static GenericName toSessionNamespaceFromExtended (final String candidate) static private
References NamesExt.create().
Referenced by NamesExt.valueOf().
{
         final int index = candidate.indexOf('}');
         if(index == -1) throw new IllegalArgumentException("Invalide extended form : "+ candidate);
         final String uri = candidate.substring(1, index);
         final String name = candidate.substring(index+1, candidate.length());
         return NamesExt.create(uri, name);
     }
valueOf()
static GenericName valueOf (final String candidate) static
Parse a string value that can be expressed in 2 different forms : JSR-283 extended form : {uri}localpart Separator form : uri:localpart.
if the given string do not match any, then a Name with no namespace will be created and the localpart will be the given string.
References NamesExt.create(), and NamesExt.toSessionNamespaceFromExtended().
{
         if(candidate.startsWith("{")){
             //name is in extended form
             return toSessionNamespaceFromExtended(candidate);
         }
         int index = candidate.lastIndexOf(':');
         if(index <= 0){
             return NamesExt.create(null, candidate);
         }else{
             final String uri = candidate.substring(0,index);
             final String name = candidate.substring(index+1,candidate.length());
             return NamesExt.create(uri, name);
         }
     }