jena-geo: LoggedFormat< T > Class Template Reference
LoggedFormat< T > Class Template Reference
Wraps a Format object in order to either parse fully a string, or log a warning.
Public Member Functions
void setLogger (final String logger)
Sets the logger where to send the warnings eventually emitted by the parse method.
void setLevel (final Level level)
Sets the logger level for the warnings eventually emitted by the parse method.
void setCaller (final Class<?> caller, final String method)
Sets the LogRecord::setSourceClassName source class name} and LogRecord::setSourceMethodName source method name} for the warnings eventually emitted by the parse method.
T parse (String text)
Parses the specified string.
Object parseObject (final String text) throws ParseException
Parses text from a string to produce an object.
Object parseObject (final String text, final ParsePosition position)
Parses text from a string to produce an object.
StringBuffer format (final Object value, final StringBuffer toAppendTo, final FieldPosition position)
Formats the specified object.
AttributedCharacterIterator formatToCharacterIterator (final Object value)
Formats the specified object.
String toString ()
Returns a string representation for debugging purpose.
Static Public Member Functions
static< T > LoggedFormat< T > getInstance (final Format format, final Class< T > type)
Creates a new format wrapping the specified one.
static String formatUnparsable (final String text, final int index, final int errorIndex, final Locale locale)
Formats an error message for an unparsable string.
static LogRecord formatUnparsable (final String text, final int index, final int errorIndex, final Locale locale, Level level)
Formats a log record for an unparsable string.
Protected Member Functions
LoggedFormat (final Format format, final Class< T > type)
Creates a new format wrapping the specified one.
void logWarning (final LogRecord warning)
Logs a warning.
Locale getWarningLocale ()
Returns the locale to use for formatting warnings.
Private Member Functions
void doLogWarning (final LogRecord warning)
Logs a warning.
Static Private Member Functions
static Object doFormatUnparsable (String text, final int index, int errorIndex, final Locale locale, final Level level)
Implementation of.
Private Attributes
final Format format
The wrapped format.
final Class< T > type
The expected type for the parsed values.
Level level
The level to use for the messages to be logged.
String logger
The logger where to log warnings, or.
String className
The class to declare in as the warning emitter, or.
String methodName
The method to declare in as the warning emitter, or.
Static Private Attributes
static final long serialVersionUID = 4578880360344271325L
For cross-version compatibility.
Detailed Description
Wraps a Format object in order to either parse fully a string, or log a warning.
This class provides a parse(String) method which performs the following tasks:
Checks if the string was fully parsed and log a warning if it was not. This is different than the default parseObject(String) behavior which check only if the beginning of the string was parsed and ignore any remaining characters.
Ensures that the parsed object is of some specific class specified at construction time.
If the string can't be fully parsed or is not of the expected class, logs a warning.
Parameters
<T> The expected type of values to be parsed.
Author
Martin Desruisseaux (IRD)
Since
2.4
Constructor & Destructor Documentation
LoggedFormat()
LoggedFormat (final Format format, final Class< T > type) protected
Creates a new format wrapping the specified one.
Parameters
format The format to use for parsing and formatting.
type The expected type of parsed values.
References LoggedFormat< T >.format, and LoggedFormat< T >.type.
{
         this.format = format;
         this.type   = type;
         this.level  = Level.WARNING;
     }
Member Function Documentation
doFormatUnparsable()
static Object doFormatUnparsable (String text, final int index, int errorIndex, final Locale locale, final Level level) static private
Implementation of.
formatUnparsable
methods. Returns a LogRecord if
level
is non-null, or a String otherwise.
References Errors.getResources(), Errors.Keys.UnexpectedEndOfString, and Errors.Keys.UnparsableString_2.
Referenced by LoggedFormat< T >.formatUnparsable().
     {
         final Errors resources = Errors.getResources(locale);
         final int length = text.length();
         if (errorIndex < index) {
             errorIndex = index;
         }
         if (errorIndex == length) {
             if (level != null) {
                 return resources.getLogRecord(level, Errors.Keys.UnexpectedEndOfString);
             }
             return resources.getString(Errors.Keys.UnexpectedEndOfString);
         }
         final String error = CharSequences.token(text, errorIndex).toString();
         text = text.substring(index);
         if (level != null) {
             return resources.getLogRecord(level, Errors.Keys.UnparsableString_2, text, error);
         }
         return resources.getString(Errors.Keys.UnparsableString_2, text, error);
     }
doLogWarning()
void doLogWarning (final LogRecord warning) private
Logs a warning.
The caller is set before to invoke the user-overridable method.
References LoggedFormat< T >.logWarning().
Referenced by LoggedFormat< T >.parse().
{
         if (className != null) {
             warning.setSourceClassName(className);
         }
         if (methodName != null) {
             warning.setSourceMethodName(methodName);
         }
         logWarning(warning);
     }
format()
StringBuffer format (final Object value, final StringBuffer toAppendTo, final FieldPosition position)
Formats the specified object.
This method delegates the work to the Format format} specified at construction time.
Parameters
value The object to format.
toAppendTo The buffer where the text is to be appended.
position Identifies a field in the formatted text.
Returns
The string buffer passed in with formatted text appended.
     {
         return format.format(value, toAppendTo, position);
     }
formatToCharacterIterator()
AttributedCharacterIterator formatToCharacterIterator (final Object value)
Formats the specified object.
This method delegates the work to the Format format} specified at construction time.
Parameters
value The object to format.
Returns
The character iterator describing the formatted value.
{
         return format.formatToCharacterIterator(value);
     }
formatUnparsable() [1/2]
static String formatUnparsable (final String text, final int index, final int errorIndex, final Locale locale) static
Formats an error message for an unparsable string.
This method performs the same work that formatUnparsable(..., Level), except that the result is returned as a String rather than a LogRecord. This is provided as a convenience method for creating the message to give to an Exception::Exception(String) exception constructor}.
Parameters
text The unparsable string.
index The parse position. This is usually ParsePosition#getIndex.
errorIndex The index where the error occurred. This is usually ParsePosition#getErrorIndex.
locale The locale for the message, or
null
for the default one.
Returns
A formatted error message.
Since
2.5
References LoggedFormat< T >.doFormatUnparsable().
Referenced by LoggedFormat< T >.parse().
     {
         return (String) doFormatUnparsable(text, index, errorIndex, locale, null);
     }
formatUnparsable() [2/2]
static LogRecord formatUnparsable (final String text, final int index, final int errorIndex, final Locale locale, Level level) static
Formats a log record for an unparsable string.
This method is invoked by the parse method for formatting the log record to be given to the logWarning method. It is made public as a convenience for implementors who wish to manage loggings outside this
LoggedFormat
class.
Parameters
text The unparsable string.
index The parse position. This is usually ParsePosition#getIndex.
errorIndex The index where the error occurred. This is usually ParsePosition#getErrorIndex.
locale The locale for the log message, or
null
for the default one.
level The log record level.
Returns
A formatted log record.
Since
2.5
References LoggedFormat< T >.doFormatUnparsable().
     {
         if (level == null) {
             // It is necessary to ensure that the level argument is non-null,
             // otherwise we would get a ClassCastException in the code below.
             level = Level.WARNING;
         }
         return (LogRecord) doFormatUnparsable(text, index, errorIndex, locale, level);
     }
getInstance()
static <T> LoggedFormat<T> getInstance (final Format format, final Class< T > type) static
Creates a new format wrapping the specified one.
Parameters
<T> The expected type of parsed values.
format The format to use for parsing and formatting.
type The expected type of parsed values.
Returns
A new format which will delegate parsing to the given format and log failures.
References LoggedFormat< T >.format, and LoggedFormat< T >.type.
{
         return new LoggedFormat<>(format, type);
     }
getWarningLocale()
Locale getWarningLocale () protected
Returns the locale to use for formatting warnings.
The default implementation returns the Locale::getDefault() default locale}.
Returns
The locale to use for formatting warnings.
Referenced by LoggedFormat< T >.parse().
{
         return Locale.getDefault(Locale.Category.DISPLAY);
     }
logWarning()
void logWarning (final LogRecord warning) protected
Logs a warning.
This method is invoked automatically by the parse method when a text can't be fully parsed. The default implementation logs the warning to the logger specified by the last call to the setLogger method. Subclasses may override this method if they want to change the log record before the logging.
Parameters
warning The warning to log.
Referenced by LoggedFormat< T >.doLogWarning().
{
         if (logger != null) {
             final Logger logger = Logging.getLogger(this.logger);
             if (warning.getLoggerName() == null) {
                 warning.setLoggerName(logger.getName());
             }
             logger.log(warning);
         }
     }
parse()
T parse (String text)
Parses the specified string.
If the string can't be parsed, then this method returns
null
. If it can be parsed at least partially and is of the kind specified at construction time, then it is returned. If the string has not been fully parsed, then a LogRecord log record} is prepared and logged.
Parameters
text The text to parse, or
null
.
Returns
The parsed object, or
null
if
text
was null or can't be parsed.
References LoggedFormat< T >.doLogWarning(), LoggedFormat< T >.formatUnparsable(), Errors.getResources(), LoggedFormat< T >.getWarningLocale(), Errors.Keys.IllegalClass_2, LoggedFormat< T >.parseObject(), and LoggedFormat< T >.type.
{
         if (text == null || (text=text.trim()).isEmpty()) {
             return null;
         }
         final ParsePosition position = new ParsePosition(0);
         final Object value = parseObject(text, position);
         int index = position.getIndex();
         final int error = position.getErrorIndex();
         if (error >= 0 && error < index) {
             index = error;
         }
         if (index < text.length()) {
             doLogWarning(formatUnparsable(text, 0, index, getWarningLocale(), level));
         } else if (value!=null && !type.isInstance(value)) {
             doLogWarning(Errors.getResources(getWarningLocale()).getLogRecord(level,
                     Errors.Keys.IllegalClass_2, value.getClass(), type));
             return null;
         }
         return type.cast(value);
     }
parseObject() [1/2]
Object parseObject (final String text) throws ParseException
Parses text from a string to produce an object.
This method delegates the work to the Format format} specified at construction time. This method to not perform any logging.
Parameters
text The text to parse.
Returns
An object parsed from the string.
Exceptions
ParseException if parsing failed.
Referenced by LoggedFormat< T >.parse().
{
         return format.parseObject(text);
     }
parseObject() [2/2]
Object parseObject (final String text, final ParsePosition position)
Parses text from a string to produce an object.
This method delegates the work to the Format format} specified at construction time. This method to not perform any logging.
Parameters
text The text to parse.
position Index and error index information.
Returns
An object parsed from the string, or
null
in case of error.
{
         return format.parseObject(text, position);
     }
setCaller()
void setCaller (final Class<?> caller, final String method)
Sets the LogRecord::setSourceClassName source class name} and LogRecord::setSourceMethodName source method name} for the warnings eventually emitted by the parse method.
Parameters
caller The class to declare as the warning emitter, or
null
if none.
method The method to declare as the warning emitter, or
null
if none.
{
         this.className  = (caller != null) ? caller.getCanonicalName() : null;
         this.methodName = method;
     }
setLevel()
void setLevel (final Level level)
Sets the logger level for the warnings eventually emitted by the parse method.
The default value is Level#WARNING.
Parameters
level The new logging level.
Since
2.5
References LoggedFormat< T >.level.
{
         if (level != null) {
             this.level = level;
         }
     }
setLogger()
void setLogger (final String logger)
Sets the logger where to send the warnings eventually emitted by the parse method.
Parameters
logger The logger where to log warnings, or
null
if none.
References LoggedFormat< T >.logger.
{
         this.logger = logger;
     }
toString()
String toString ()
Returns a string representation for debugging purpose.
{
         final StringBuilder buffer = new StringBuilder(Classes.getShortClassName(this))
                 .append('[').append(Classes.getShortClassName(format));
         if (logger != null) {
             buffer.append(", logger=").append(logger);
         }
         return buffer.append(']').toString();
     }
Member Data Documentation
className
String className private
The class to declare in as the warning emitter, or.
null
if none.
See also
setCaller
format
final Format format private
The wrapped format.
Referenced by LoggedFormat< T >.getInstance(), and LoggedFormat< T >.LoggedFormat().
level
Level level private
The level to use for the messages to be logged.
Referenced by LoggedFormat< T >.setLevel().
logger
String logger private
The logger where to log warnings, or.
null
if none.
See also
setLogger
Referenced by LoggedFormat< T >.setLogger().
methodName
String methodName private
The method to declare in as the warning emitter, or.
null
if none.
See also
setCaller
serialVersionUID
final long serialVersionUID = 4578880360344271325L static private
For cross-version compatibility.
type
final Class<T> type private
The expected type for the parsed values.
Referenced by LoggedFormat< T >.getInstance(), LoggedFormat< T >.LoggedFormat(), and LoggedFormat< T >.parse().