jena-geo: AbstractVersionHistory Class Reference
AbstractVersionHistory Class Reference abstract
Abstract version history,.
Classes
class VersionComparator
Comparator to sort Version list in reverted chronological order.
Public Member Functions
Version getVersion (String label) throws VersioningException
Find version for given label.
Version getVersion (Date date) throws VersioningException
Returns the version for for given date.
List< Version > list () throws VersioningException
Unmodifiable list of versions available.
Static Private Attributes
static final TimeZone GMT0 = TimeZone.getTimeZone("GMT+0")
Detailed Description
Abstract version history,.
Author
Johann Sorel (Geomatys)
Member Function Documentation
getVersion() [1/2]
Version getVersion (String label) throws VersioningException
Find version for given label.
Parameters
label
Returns
Version or null
Implements VersionHistory.
References VersionHistory.list().
{
         for(Version v : list()){
             if(v.getLabel().equals(label)){
                 return v;
             }
         }
         throw new VersioningException("No version with given label.");
     }
getVersion() [2/2]
Version getVersion (Date date) throws VersioningException
Returns the version for for given date.
In case the date do not overlaps the closest version will be returned.
Parameters
date : date in GMT+0
Returns
Version
Implements VersionHistory.
References VersionHistory.list().
{
         final List<Version> lst = list();
         Collections.sort(lst, new VersionComparator());
         //ensure date in GMT0
         final Calendar vCal = new GregorianCalendar(GMT0);
         final Calendar rCal = new GregorianCalendar(GMT0);
         rCal.setTime(date);
         for(Version v : lst){
             vCal.setTime(v.getDate());
             //if requested date is after version date
             if(rCal.getTimeInMillis() >= vCal.getTimeInMillis()) {
                 return v;
             }
         }
         //date is before. return first version
         //this is not exact, yet versioning might have started a very long time afeter initial data creation.
         return lst.isEmpty() ? null : lst.get(0);
     }
list()
List<Version> list () throws VersioningException inherited
Unmodifiable list of versions available.
List is ordered by date ascending
Returns
List<Version>
Referenced by AbstractVersionHistory.getVersion().
Member Data Documentation
GMT0
final TimeZone GMT0 = TimeZone.getTimeZone("GMT+0") static private