jena-geo: AnchoredMarshallerPool Class Reference
AnchoredMarshallerPool Class Reference
Public Member Functions
AnchoredMarshallerPool () throws JAXBException
AnchoredMarshallerPool (final JAXBContext context) throws JAXBException
Creates a new factory for the given JAXB context, with a default empty namespace.
AnchoredMarshallerPool (final JAXBContext context, final Map< String, Object > properties) throws JAXBException
AnchoredMarshallerPool (final Class<?>... classesToBeBound) throws JAXBException
Creates a new factory for the given class to be bound, with a default empty namespace.
AnchoredMarshallerPool (final String schemaLocation, final Class<?>... classesToBeBound) throws JAXBException
Creates a new factory for the given class to be bound.
AnchoredMarshallerPool (final String packages) throws JAXBException
Creates a new factory for the given packages, with a default empty namespace.
AnchoredMarshallerPool (final String packages, final String schemaLocation) throws JAXBException
Creates a new factory for the given packages.
void addAnchor (final String label, final URI linkage) throws IllegalStateException
Adds a label associated to an URN.
Protected Member Functions
Marshaller createMarshaller () throws JAXBException
Private Member Functions
AnchoredMarshallerPool (final JAXBContext context, final String schemaLocation, final Map< String, URI > anchors, final Map< String, Object > properties) throws JAXBException
Static Private Member Functions
static Map< String, Object > getProperties (final Map< String, URI > anchors, final Map< String, Object > previousProperties)
Return a Map of Marshaller properties.
Private Attributes
final String schemaLocation
final Map< String, URI > anchors
Binds string labels with URNs or anchors.
Detailed Description
Author
Guilhem Legal (Geomatys)
Constructor & Destructor Documentation
AnchoredMarshallerPool() [1/8]
AnchoredMarshallerPool () throws JAXBException
{
         this(TypeRegistration.getSharedContext());
     }
AnchoredMarshallerPool() [2/8]
AnchoredMarshallerPool (final JAXBContext context) throws JAXBException
Creates a new factory for the given JAXB context, with a default empty namespace.
Parameters
context The JAXB context.
Exceptions
JAXBException If the JAXB context can not be created.
{
         this(context, null, new HashMap<String,URI>(), null);
     }
AnchoredMarshallerPool() [3/8]
AnchoredMarshallerPool (final JAXBContext context, final Map< String, Object > properties) throws JAXBException
{
         this(context, null, new HashMap<String,URI>(), properties);
     }
AnchoredMarshallerPool() [4/8]
AnchoredMarshallerPool (final Class<?>... classesToBeBound) throws JAXBException
Creates a new factory for the given class to be bound, with a default empty namespace.
Parameters
classesToBeBound The classes to be bound, for example
DefaultMetadata.class
.
Exceptions
JAXBException If the JAXB context can not be created.
{
         this(null, classesToBeBound);
     }
AnchoredMarshallerPool() [5/8]
AnchoredMarshallerPool (final String schemaLocation, final Class<?>... classesToBeBound) throws JAXBException
Creates a new factory for the given class to be bound.
Parameters
classesToBeBound The classes to be bound, for example
DefaultMetadata.class
.
Exceptions
JAXBException If the JAXB context can not be created.
References AnchoredMarshallerPool.schemaLocation.
{
         this(JAXBContext.newInstance(classesToBeBound), schemaLocation, new HashMap<String,URI>(), null);
     }
AnchoredMarshallerPool() [6/8]
AnchoredMarshallerPool (final String packages) throws JAXBException
Creates a new factory for the given packages, with a default empty namespace.
The separator character for the packages is the colon.
Parameters
packages The packages in which JAXB will search for annotated classes to be bound, for example
"org.apache.sis.metadata.iso:org.apache.sis.metadata.iso.citation"
.
Exceptions
JAXBException If the JAXB context can not be created.
{
         this(packages, (String) null);
     }
AnchoredMarshallerPool() [7/8]
AnchoredMarshallerPool (final String packages, final String schemaLocation) throws JAXBException
Creates a new factory for the given packages.
The separator character for the packages is the colon.
Parameters
packages The packages in which JAXB will search for annotated classes to be bound, for example
"org.apache.sis.metadata.iso:org.apache.sis.metadata.iso.citation"
.
schemaLocation The main xsd schema location for all the returned xml.
Exceptions
JAXBException If the JAXB context can not be created.
References AnchoredMarshallerPool.schemaLocation.
{
         this(JAXBContext.newInstance(packages), schemaLocation, new HashMap<String,URI>(), null);
     }
AnchoredMarshallerPool() [8/8]
AnchoredMarshallerPool (final JAXBContext context, final String schemaLocation, final Map< String, URI > anchors, final Map< String, Object > properties) throws JAXBException private
References AnchoredMarshallerPool.anchors, AnchoredMarshallerPool.getProperties(), and AnchoredMarshallerPool.schemaLocation.
     {
         super(context, getProperties(anchors, properties));
         this.schemaLocation = schemaLocation;
         this.anchors = anchors;
     }
Member Function Documentation
addAnchor()
void addAnchor (final String label, final URI linkage) throws IllegalStateException
Adds a label associated to an URN.
For some methods expected to return a code as a String object, the code will be completed by the given URN in an
AnchorType
element.
This method should be invoked from subclasses constructor only. Anchors can be added but can not be removed or modified.
Parameters
label The label associated to the URN.
linkage The URN.
Exceptions
IllegalStateException If a URN is already associated to the given linkage.
References AnchoredMarshallerPool.anchors, Errors.format(), and Errors.Keys.ValueAlreadyDefined_1.
{
         synchronized (anchors) {
             final URI old = anchors.put(label, linkage);
             if (old != null) {
                 anchors.put(label, old);
                 throw new IllegalStateException(Errors.format(Errors.Keys.ValueAlreadyDefined_1, label));
             }
         }
     }
createMarshaller()
Marshaller createMarshaller () throws JAXBException protected
{
         final Marshaller marshaller = super.createMarshaller();
         if (schemaLocation != null) {
             marshaller.setProperty(Marshaller.JAXB_SCHEMA_LOCATION, schemaLocation);
         }
         return marshaller;
     }
getProperties()
static Map<String, Object> getProperties (final Map< String, URI > anchors, final Map< String, Object > previousProperties) static private
Return a Map of Marshaller properties.
Parameters
anchors Map of anchors to be stored as the anchors field.
References AnchoredMarshallerPool.anchors.
Referenced by AnchoredMarshallerPool.AnchoredMarshallerPool().
{
         final Map<String, Object> properties;
         if (previousProperties != null) {
             properties = previousProperties;
         } else {
             properties = new HashMap<>();
         }
         properties.put(XML.RESOLVER, new ReferenceResolver() {
             @Override
             public XLink anchor(final MarshalContext context, final Object value, final CharSequence text) {
                 final URI linkage;
                 synchronized (anchors) {
                     linkage = anchors.get(value);
                 }
                 if (linkage != null) {
                     final XLink xlink = new XLink();
                     xlink.setHRef(linkage);
                     return xlink;
                 }
                 return super.anchor(context, value, text);
             }
         });
         return properties;
     }
Member Data Documentation
anchors
final Map<String,URI> anchors private
Binds string labels with URNs or anchors.
See also
addAnchor(String, URI)
Referenced by AnchoredMarshallerPool.addAnchor(), AnchoredMarshallerPool.AnchoredMarshallerPool(), and AnchoredMarshallerPool.getProperties().
schemaLocation
final String schemaLocation private
Referenced by AnchoredMarshallerPool.AnchoredMarshallerPool().