jena-geo: IsCollectionTest Class Reference
IsCollectionTest Class Reference
Public Member Functions
void testMultiPointIsCollection ()
void testMultiPolygonIsCollection ()
void testMultiLineStringIsCollection ()
void testGeometryCollectionIsCollection ()
void testPointIsCollection ()
void testLineStringIsCollection ()
void testPolygonIsCollection ()
Member Function Documentation
testGeometryCollectionIsCollection()
void testGeometryCollectionIsCollection ()
References IsCollection.exec().
{
                 System.out.println("exec_false");
         NodeValue geometryLiteral = NodeValue.makeNode("<http://www.opengis.net/def/crs/EPSG/0/27700> GEOMETRYCOLLECTION(POINT(4 6),LINESTRING(4 6,7 10))", WKTDatatype.INSTANCE);
         IsCollection instance=new IsCollection();
         NodeValue expResult = NodeValue.makeNodeBoolean(true);
         NodeValue result = instance.exec(geometryLiteral);
         assertEquals(expResult, result);
         }
testLineStringIsCollection()
void testLineStringIsCollection ()
References IsCollection.exec().
{
         NodeValue geometryLiteral = NodeValue.makeNode("<http://www.opengis.net/def/crs/EPSG/0/27700> LINESTRING (30 10, 10 30, 40 40)", WKTDatatype.INSTANCE);
         IsCollection instance=new IsCollection();
         NodeValue expResult = NodeValue.makeNodeBoolean(false);
         NodeValue result = instance.exec(geometryLiteral);
         assertEquals(expResult, result);
         }
testMultiLineStringIsCollection()
void testMultiLineStringIsCollection ()
References IsCollection.exec().
{
                 System.out.println("exec_false");
         NodeValue geometryLiteral = NodeValue.makeNode("<http://www.opengis.net/def/crs/EPSG/0/27700> MULTILINESTRING ((10 10, 20 20, 10 40),(40 40, 30 30, 40 20, 30 10))", WKTDatatype.INSTANCE);
         IsCollection instance=new IsCollection();
         NodeValue expResult = NodeValue.makeNodeBoolean(true);
         NodeValue result = instance.exec(geometryLiteral);
         assertEquals(expResult, result);
         }
testMultiPointIsCollection()
void testMultiPointIsCollection ()
References IsCollection.exec().
{
         NodeValue geometryLiteral = NodeValue.makeNode("<http://www.opengis.net/def/crs/EPSG/0/27700> MULTIPOINT (10 40, 40 30, 20 20, 30 10)", WKTDatatype.INSTANCE);
         IsCollection instance=new IsCollection();
         NodeValue expResult = NodeValue.makeNodeBoolean(true);
         NodeValue result = instance.exec(geometryLiteral);
         assertEquals(expResult, result);
         }
testMultiPolygonIsCollection()
void testMultiPolygonIsCollection ()
References IsCollection.exec().
{
         NodeValue geometryLiteral = NodeValue.makeNode("<http://www.opengis.net/def/crs/EPSG/0/27700> MULTIPOLYGON (((40 40, 20 45, 45 30, 40 40)),((20 35, 10 30, 10 10, 30 5, 45 20, 20 35),(30 20, 20 15, 20 25, 30 20)))", WKTDatatype.INSTANCE);
         IsCollection instance=new IsCollection();
         NodeValue expResult = NodeValue.makeNodeBoolean(true);
         NodeValue result = instance.exec(geometryLiteral);
         assertEquals(expResult, result);
         }
testPointIsCollection()
void testPointIsCollection ()
References IsCollection.exec().
{
         NodeValue geometryLiteral = NodeValue.makeNode("<http://www.opengis.net/def/crs/EPSG/0/27700> POINT (30 10)", WKTDatatype.INSTANCE);
         IsCollection instance=new IsCollection();
         NodeValue expResult = NodeValue.makeNodeBoolean(false);
         NodeValue result = instance.exec(geometryLiteral);
         assertEquals(expResult, result);
         }
testPolygonIsCollection()
void testPolygonIsCollection ()
References IsCollection.exec().
{
         NodeValue geometryLiteral = NodeValue.makeNode("<http://www.opengis.net/def/crs/EPSG/0/27700> POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))", WKTDatatype.INSTANCE);
         IsCollection instance=new IsCollection();
         NodeValue expResult = NodeValue.makeNodeBoolean(false);
         NodeValue result = instance.exec(geometryLiteral);
         assertEquals(expResult, result);
         }