jena-geo: NDimsTest Class Reference
NDimsTest Class Reference
Public Member Functions
void test2DGeom ()
void test3DGeom ()
void testMGeom ()
Static Public Attributes
static final String geom2D ="POINT(1 1)"
static final String geom3D ="POINT Z(1 1 2)"
static final String geomM ="POINT M(1 1 0.5)"
Member Function Documentation
test2DGeom()
void test2DGeom ()
References NDims.exec().
{
         NodeValue geometryLiteral = NodeValue.makeNode(geom2D, WKTDatatype.INSTANCE);
         NDims instance=new NDims();
         NodeValue expResult = NodeValue.makeInteger(2);
         NodeValue result = instance.exec(geometryLiteral);
         assertEquals(expResult, result);
         }
test3DGeom()
void test3DGeom ()
References NDims.exec().
{
         NodeValue geometryLiteral = NodeValue.makeNode(geom3D, WKTDatatype.INSTANCE);
         NDims instance=new NDims();
         NodeValue expResult = NodeValue.makeInteger(3);
         NodeValue result = instance.exec(geometryLiteral);
         assertEquals(expResult, result);
         }
testMGeom()
void testMGeom ()
References NDims.exec().
{
         NodeValue geometryLiteral = NodeValue.makeNode(geomM, WKTDatatype.INSTANCE);
         NDims instance=new NDims();
         NodeValue expResult = NodeValue.makeInteger(2);
         NodeValue result = instance.exec(geometryLiteral);
         assertEquals(expResult, result);
         }
Member Data Documentation
geom2D
final String geom2D ="POINT(1 1)" static
geom3D
final String geom3D ="POINT Z(1 1 2)" static
geomM
final String geomM ="POINT M(1 1 0.5)" static