package de.hsmainz.cs.semgis.arqextension.geometry;

import java.math.BigInteger;

import org.apache.jena.datatypes.DatatypeFormatException;
import org.apache.jena.sparql.expr.ExprEvalException;
import org.apache.jena.sparql.expr.NodeValue;
import org.apache.jena.sparql.function.FunctionBase3;
import org.opengis.geometry.MismatchedDimensionException;

import io.github.galbiston.geosparql_jena.implementation.GeometryWrapper; import io.github.galbiston.geosparql_jena.implementation.GeometryWrapperFactory;

/**
 * 	Sets the effective area for each vertex, storing the value in the M ordinate. A simplified geometry can then be generated by filtering on the M ordinate. 
 *
 */
public class SetEffectiveArea extends FunctionBase3 {

	@Override
	public NodeValue exec(NodeValue v1, NodeValue v2, NodeValue v3) {
        try {
            GeometryWrapper geom1 = GeometryWrapper.extract(v1);
            Double threshold=v2.getDouble();
            BigInteger set_area=v3.getInteger();
        	throw new UnsupportedOperationException("Not supported yet.");
        } catch (DatatypeFormatException | MismatchedDimensionException  ex) {
            throw new ExprEvalException(ex.getMessage(), ex);
        }
	}

}
